### ISSUE TITLE
Allow user to navigate + log in to their home page via cut and paste or type entering URL

### ISSUE THREAD

**Issue by Mgranfie** [openshiftio/openshift.io#1]
@pmuir
As a user of OpenShift.io I want to be able to paste or type my URL "openshift.io/" into the browser and if I am not yet logged in, I am directly navigated to the RHD login, so that I don't have to click the "Log in" option/button on the OS.io beta page every time I want to log in to OS.io.

**Comment by RanjithRV** [comment]
@sbose78 @alexeykazakov can you please take a look at this very old issue. I am guessing we are way past it but can you please confirm so that we can close it

**Comment by alexeykazakov** [comment]
Won't fix. Closing.
