### ISSUE TITLE
Task: Generate component-categories mapping for Spring Boot

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#1009]
**Description:**

1. Generate component-categories mapping for springboot components from [start.spring.io](http://start.spring.io/).

**Comment by abs51295** [comment]
The following [JSON file](https://drive.google.com/file/d/0B9-xNPFDl6o3NGFJNVFzd19WSlU/view?ts=59c8e7cb) is generated as a result of the curation of data.

**Comment by sunilk747** [comment]
This is the final [JSON](https://privatebin-it-iso.int.open.paas.redhat.com/?760e23ed18aa0784#RBPN6RG4rLZNU7B/5qaZm7ItvTl/rTmEWjLK2QyT42s=) file that maps the packages with the categories for springbot.
