### ISSUE TITLE
Task: Generate component-categories mapping for Vertx.io

### ISSUE THREAD

**Issue by abs51295** [openshiftio/openshift.io#1010]
**Description:**

1. Generate component-categories mapping for springboot components from [vertx.io](http://vertx.io/).

**Comment by sunilk747** [comment]
This is the final [JSON](https://privatebin-it-iso.int.open.paas.redhat.com/?33c2bf8c29cf075e#XRXd7dkQN3Dx69yL8NHDknuZRbXGzMcRAhy59BrDHMc=) file that maps the packages with the categories for vertx.
