### ISSUE TITLE
Task: Generate a list of common categories

### ISSUE THREAD

**Issue by abs51295** [openshiftio/openshift.io#1011]
**Description:**
 
1. As the categories generated for Spring Boot and Vert.x ecosystem are different, a list of common categories is required to aggregate packages from both the ecosystems.

**Comment by joshuawilson** [comment]
Common categories of what and for what? I get it from the labels that it should be for analytics, but it is better to be clear then to rely on labels to imply knowledge.

**Comment by abs51295** [comment]
@joshuawilson I have edited the description. Please review.

**Comment by joshuawilson** [comment]
nice, thanks

**Comment by abs51295** [comment]
This the final [JSON](https://privatebin-it-iso.int.open.paas.redhat.com/?959850b418baeae1#WvwafmEEHVNexLTsTqQoqnndiHgAK/cIqSOTJKK3u5U=) file that maps the packages with the categories.
