### ISSUE TITLE
[8] Figure out a way how to configure SQS queues automatically

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1014]
# Description

Queues in SQS are created automatically when they are needed. However, we use non-default values for some of the configuration options:
- Default Visibility Timeout (maybe not? check)
- Message Retention Period (we want 14 days)

These were set manually in staging/prod.

We need to find a way how to configure the queues automatically, ideally at creation time.

# Acceptance criteria
- [x] queues in staging and production are configured automatically

**Comment by fridex** [comment]
> - Message Retention Period (we want 14 days)

Implementation is in https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/409.

> - Default Visibility Timeout (maybe not? check)

This is configurable directly by Celery and we already configure it - see [f8a_worker/celery_settings.py](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/celery_settings.py#L56).
