### ISSUE TITLE
Optimize tagger run

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#1015]
# Description

The current speed of tagging can be optimized. The main bottleneck in the tagging task is the fact that configuration files are parsed and post-processed multiple times during a task run. These config files capture tags present in the analysed ecosystem, stopwords etc. It would be nice to introduce "context" that would carry these config entries and devel would handle this context on his own. This should reduce task run time considerably.

# Acceptance criteria

- [ ] tagger implementation is adjusted so a user keeps context that is passed along with free text to library API calls
- [ ] context captures all the configuration files and can be reused multiple times when automated tagging is done
- [ ] changes and code are tested
- [ ] modified tagger runs in production

**Comment by miteshvp** [comment]
Not relevant.
