### ISSUE TITLE
Microservices Proposal: Edit multiple projects in CHE

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#1016]
We would need to find a way for a team/developer to work in a microservices environment. Initially I would think about importing more than one project at time with a single "Create workspace" button and multiple checkbox to select the desired microservices just like the picture bellow.

![microservices proposal](https://user-images.githubusercontent.com/30131/30818884-d856829c-a1ea-11e7-9d6d-60846a82a5d9.png)

That doesn't solve the problem completely because the microservices can be developed by different teams in a different space.

**Comment by l0rd** [comment]
@rafabene that's the current proposal to change the codebase UI: https://github.com/openshiftio/openshift.io/issues/388#issuecomment-329260367

**Comment by ibuziuk** [comment]
Closing as won't fix
