### ISSUE TITLE
Investigate ~1 hour time period on September 25 where Che failed to import quickstart code

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1019]
This issue is being logged to track an issue where, from about 11AM to noon (Boston time) on September 25, attempting to create a new Che workspace failed - as Che was not able to import quickstarts' code.

![screenshot 65](https://user-images.githubusercontent.com/642621/30824265-fde53d16-a1fc-11e7-8f0d-11af5108e7e6.png)

I do not have any OSO logs from this time period, but for that hour, the error was consistently seen. The problem seemed to have been resolved at about noon.

**Comment by joshuawilson** [comment]
@kbsingh @jfchevrette I think the change made to authentication is the cause of this error.

**Comment by kbsingh** [comment]
@joshuawilson agreed.

**Comment by jfchevrette** [comment]
@joshuawilson +1 That does fit the time window while auth was broken.

**Comment by ldimaggi** [comment]
Can you provide any details on the failure?

**Comment by ldimaggi** [comment]
Also - I have this test running every 2 hours - it failed while the auth issue happened. Can we talk about running a test like this on a more frequent basis to serve as a "heart monitor" for the system?  ;-)

**Comment by jfchevrette** [comment]
@ldimaggi an authentication secret was rotated earlier and then got reverted by an automated system which caused the authentication issues.

My understanding is that this e2e test runs multiple times per hour as often as it can at the moment. Is that correct? We should monitor the test result and trigger alerts if it fails.

**Comment by kbsingh** [comment]
@jfchevrette the e2e tests are meant to be in the zabbix dashboard, and we should alert on that

**Comment by ldimaggi** [comment]
Are the EE tests in zabbix? URL? Thx!
