### ISSUE TITLE
Intermittent error opening Che workspace - 403 - User "system:serviceaccount:[user]-che:che" cannot watch events in project "[user]-che

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1022]
Started seeing this error today - see attached log file - when creating a new workspace - not reproducible at will. Was there a KC outage today?
[che_log.txt](https://github.com/openshiftio/openshift.io/files/1330664/che_log.txt)

```
2017-09-25 18:46:43,077[default.svc/...]  [WARN ] [k.c.d.i.WatchConnectionManager 175]  - Exec Failure: HTTP 403, Status: 403 - User "system:serviceaccount:ldimaggi-osiotest1-che:che" cannot watch events in project "ldimaggi-osiotest1-che"
--
  | java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
  | at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:216)
  | at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:183)
  | at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
  | at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
```

**Comment by l0rd** [comment]
@jfchevrette sent an email about the auth problem. Che side there is nothing we can do to fix that.

**Comment by jfchevrette** [comment]
The auth problem was resolved yesterday. I have a feeling this is something else. Is this still occurring?

**Comment by ldimaggi** [comment]
The problem was only seen intermittently - and this was after the September 25 auth issue was resolved. Leave it open for now and assigning to me to try to recreate. Thx!

**Comment by slemeur** [comment]
@ldimaggi : Have you been able to reproduce this problem ? If not, can we close it for now and reopen if we encounter it again?

**Comment by ldimaggi** [comment]
I think that we can close this issue - I have not seen it for a while. Thx for the followup!
