### ISSUE TITLE
When unapproved users are logging in then redirect to a page with proper explanation what to do

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#1023]
Currently if unapproved user is trying to log into OSIO we show a simple JSON error with a message "User is not approved". We should create a page with proper explanation instead of showing a JSON.

Related to https://github.com/fabric8-services/fabric8-auth/issues/53

**Comment by joshuawilson** [comment]
cc @catrobson

**Comment by austincunningham** [comment]
Behaviour different in Mozilla Firefox 

![image](https://user-images.githubusercontent.com/16667688/31019269-0879abea-a527-11e7-965e-47b0af4bca57.png)

**Comment by austincunningham** [comment]
Looks to be resolved :)

**Comment by joshuawilson** [comment]
@alexeykazakov @catrobson can we close this?

**Comment by alexeykazakov** [comment]
No, we still redirect to OSO account management page which may be confusing.

**Comment by catrobson** [comment]
We have a page design for implementation: https://redhat.invisionapp.com/share/BGEPRG73N#/screens.  @mindreeper2420 would you be able to do the HTML/CSS for this page?  Would that be enough for you to take and implement into the workflow @alexeykazakov?

**Comment by mindreeper2420** [comment]
I can create the page for this, if Alexey and team can implement into the workflow. Will this reside inside of the app, or outside (like the marketing page)?

**Comment by alexeykazakov** [comment]
I was thinking about the outside app. @joshuawilson wdyt?

**Comment by joshuawilson** [comment]
I think we keep the work on the platform team since there are not UI devs on the Auth team. With oversight/review by the Auth team.
This should live with the marketing pages on this repo: https://github.com/openshiftio/openshift.io

**Comment by qodfathr** [comment]
@alexeykazakov @catrobson @joshuawilson is this done?

**Comment by alexeykazakov** [comment]
@qodfathr almost! :) I have been chasing this issue for quite long time and we are almost there. Hope to close it tomorrow.

**Comment by alexeykazakov** [comment]
Done.
