### ISSUE TITLE
Free unused entries in RDS

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#1024]
# Description

As we often cleaned queues in the past due to issues and fixes in the cluster, it resolved in unusable entries in RDS. These entries consist of JSONB data that would be subsequently synced onto S3, but as a flow was interrupted by cleaning queues, this was not done.

Our jobs service is really good candidate to introduce such capability as it already has authentication and there is already present `clean-postgres` endpoint which served very similar purposes in the past. The aim of this task is to refresh this endpoint, make sure it is fully functional and can be used to clean our RDS from data that won't be used.

# Acceptance criteria

- [x] refresh `clean-postgres` endpoint - do code changes as needed
- [x] code runs in production
- [ ] old entries in RDS are removed

**Comment by kbsingh** [comment]
Before rolling this out,  if you need any backups run for the prod db, please sync with @pbergene for the state and backup

**Comment by msrb** [comment]
Our RDS instance is slowly filling up, there in only 6 GB left out of 30. Hence raising priority.

Note another option could be to stop using RDS as a temporary result storage and store results on S3 right away. Partial results would be available sooner and there would be no need for "result collector" task and subsequent RDS cleanup.

**Comment by pbergene** [comment]
I have increased the size available to the DB, which should give you a little headroom.  Also took a snapshot immediately before.

**Comment by msrb** [comment]
Thanks @pbergene :)

**Comment by fridex** [comment]
Implementation (WIP) in https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/204.

**Comment by msrb** [comment]
Implementation ready, we need to test this, move it prod and run the job there.

**Comment by msrb** [comment]
The code is in prod, I will flip the switch later this week (but in staging first:)).

**Comment by pkajaba** [comment]
@msrb what is current status of this? Do we have to just promote to prod?

**Comment by msrb** [comment]
Low priority, moving to backlog.
