### ISSUE TITLE
Analytic report "In Progress" displays a meaningless (to the user) ID number

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1027]
The "in progress" message for an analytic report refers to an ID field that is meaningless to the user:

![screen shot 2017-09-26 at 3 49 51 pm](https://user-images.githubusercontent.com/642621/30881153-c8104ce0-a2d2-11e7-928f-84454694087c.png)

_____________________________________

In contrast, the titles and text displayed when the report is completed are more informative

![screen shot 2017-09-26 at 3 52 29 pm](https://user-images.githubusercontent.com/642621/30881151-c80e2406-a2d2-11e7-92c8-b5c5138b2ff4.png)
![screen shot 2017-09-26 at 3 52 16 pm](https://user-images.githubusercontent.com/642621/30881152-c80f3800-a2d2-11e7-9323-4d0c4841054c.png)
![screen shot 2017-09-26 at 3 48 24 pm](https://user-images.githubusercontent.com/642621/30881150-c80b2a30-a2d2-11e7-9b8f-af59b7905ab6.png)

**Comment by ldimaggi** [comment]
The easiest solution is just to remove the ID numeric value from the display. Thx!

**Comment by invincibleJai** [comment]
@ldimaggi this has been fixed and changes are in prod.

**Comment by ldimaggi** [comment]
Verified - closing.
