### ISSUE TITLE
When starting workspace the eclipse editor popup gets blocked by chrome

### ISSUE THREAD

**Issue by gnufied** [openshiftio/openshift.io#1032]
I tried opening the eclipse workspace in browser but Google Chrome kept blocking the popup. I did not notice for awhile that popup was being blocked and I was very confused.

**Comment by joshuawilson** [comment]
This is explained in the getting started workshop guide. Have you read through that? 
https://docs.google.com/document/d/1KsV8oHRe7DYCVCMfVrB2yd3hU4iBi11YI5MyuXoozQw/edit#heading=h.ozijuvnl8msv

**Comment by gnufied** [comment]
No, I did not read that.  I did not even realize that there is a workshop guide that exists. 

I think we should fix this nonetheless. We can't expect people to read workshop guide (IMHO).

**Comment by joshuawilson** [comment]
Submit a PR, we'll get it merged.

**Comment by joshuawilson** [comment]
@gnufied if you think this is important, please file an issue as an enhancement. I'm closing this since your question was answered.
