### ISSUE TITLE
Intermittent issue - Resetting a user's environment fails to restart Che and Jenkins pods, or requires up to 10 min to start

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1034]
This problem is being encountered intermittently by automated tests and is not reproducible at will. 

![screenshot from 2017-09-28 06-38-22](https://user-images.githubusercontent.com/642621/30968652-05054798-a42e-11e7-958b-da949fca3684.png)

**Comment by ldimaggi** [comment]
Logs are not written. A fragment of the events listing for Jenkins is attached.
![screenshot from 2017-09-28 06-43-52](https://user-images.githubusercontent.com/642621/30968688-1ce24ed8-a42e-11e7-90df-7c89579a2bca.png)

**Comment by ldimaggi** [comment]
It looks like the pods get into a state where repeated attempts to reset the user account environment fail.

**Comment by ldimaggi** [comment]
Assigning to me to attempt to recreate and obtain more details.

**Comment by joshuawilson** [comment]
@aslakknutsen @kbsingh I don't know who else should look at this.

**Comment by ldimaggi** [comment]
Event log - required ~9 min to successfuly start Jenkins after an env. reset

[jenkins_pod_9_min.pdf](https://github.com/openshiftio/openshift.io/files/1383136/jenkins_pod_9_min.pdf)

**Comment by joshuawilson** [comment]
@aslakknutsen do think this is an issue for Platform, SD, or build?

**Comment by joshuawilson** [comment]
Is this still an issue?

**Comment by ldimaggi** [comment]
Yes - I am still seeing instances where the pods do not start - maybe 10% of the time recently.

**Comment by kbsingh** [comment]
original issue was resolved, please open a new issue if you continue to see the problem
