### ISSUE TITLE
Add logout button to the _gettingstarted page

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#1035]
For some reason there is no logout button on the _gettingstarted page. So, users are stuck if they don't have OSO/GH account linked and want to re-login using another account.
We should add at least the "Logout" button to that page. But maybe just adding the regular toolbar as we have in other pages will be even better.

**Comment by alexeykazakov** [comment]
cc: @joshuawilson

**Comment by alexeykazakov** [comment]
Workaround: Use https://openshift.io/_home and logout from there.

**Comment by joshuawilson** [comment]
@dlabrecq can you please add this.

**Comment by sbose78** [comment]
I took a shot at this : https://github.com/fabric8-ui/fabric8-ui/pull/2045

**Comment by joshuawilson** [comment]
Thanks @sbose78
