### ISSUE TITLE
After resetting a user's environment, Che and Jenkins are not deployed

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1036]
Just started seeing this!

![screenshot from 2017-09-28 18-42-20](https://user-images.githubusercontent.com/642621/30993652-ed248ee0-a47d-11e7-80be-30a96b400c62.png)

**Comment by aslakknutsen** [comment]
Related to https://github.com/fabric8-services/fabric8-wit/commit/a2ebc85befa8944749fe54049525009c395f9c88 and tenant client not copying Auth headers on redirect request to different domain.

**Comment by alexeykazakov** [comment]
https://github.com/fabric8-services/fabric8-wit/pull/1670 should fix the issue

**Comment by ldimaggi** [comment]
Perfect - many thanks!
