### ISSUE TITLE
API logic to handle generation of manifest file

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#1037]
## Description

Following this user story - https://github.com/openshiftio/openshift.io/issues/1005, the user can have the ability to generate downloadable manifest files.

Tasks:

- [x] Setting up of API environment (Python, Flask)
- [x] Handling logic for receiving and sending the response in a specified format
- [x] Hosting it in a dev cluster, for now.

**Comment by arunkumars08** [comment]
Closing as the tasks are complete.

**Comment by arunkumars08** [comment]
This is the PR for moving changes into fabric8-analytics-server, https://github.com/fabric8-analytics/fabric8-analytics-server/pull/175

**Comment by fridex** [comment]
> This is the PR for moving changes into fabric8-analytics-server, fabric8-analytics/fabric8-analytics-server#175

@arunkumars08 AFAIK the PR was not merged, so this shouldn't be closed and considered as done. Or did I miss something?

**Comment by arunkumars08** [comment]
@fridex Yes Fridolin, that's my mistake.

**Comment by samuzzal-choudhury** [comment]
`/api/v1/generate-file` is available on prod. Closing this. Reopen with the proper sprint milestone if someone thinks otherwise.
