### ISSUE TITLE
Setting up of UI infrastructure for machine generated stacks

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#1039]
## Description
Following the user story - https://github.com/openshiftio/openshift.io/issues/1005, the user needs to have an interface where he/she has the ability to generate stacks required to him/her.

Tasks

- [x] Bringing in the basic Angular2 code structure so the framework is ready and usable
- [ ] Setting up unit tests
- [x] Creation of UI as per design mock.
    - [x] Bringing in the ability to select ecosystems, frameworks, versions
    - [x] Bringing in the ability to get the user's input for project names, description and the rest.
    - [x] Handling logic for generating matching suggestions for the keywords user types (Search API)
    - [x] Handling multi select option for the suggestions shown and display them.
    - [x] Handle the pop over mechanism to show more information about the component he has picked and wishes to see.
- [x] Hosting in the dev cluster, for now

**Comment by samuzzal-choudhury** [comment]
The iteration 1 can be considered complete with a completed demo. We can create another user story going forward
