### ISSUE TITLE
Intermittent/recurring error - OSIO fails to create Che workspace - timeout when starting a process

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1041]
This is being seen - intermittently - with Che 2.0.31

Steps to recreate:
* Create a new space
* Create a new quickstart project - Vert.x basic
* The error occurs intermittently - no pattern seen yet

![screenshot from 2017-09-29 07-27-33](https://user-images.githubusercontent.com/642621/31023803-04b77da0-a50b-11e7-81e8-92d68cf92b01.png)

**Comment by ldimaggi** [comment]
See attached Che pod log
[che1log.txt](https://github.com/openshiftio/openshift.io/files/1344923/che1log.txt)

**Comment by ldimaggi** [comment]
[che1log.txt](https://github.com/openshiftio/openshift.io/files/1345084/che1log.txt)

**Comment by l0rd** [comment]
It looks like the exec agent hasn't been downloaded. Agents are usually downloaded from the che pod to the workspace pod via http. Can you rsh into the che pod and look for any evidence of that in the logs:

```bash
oc rsh <pod-id>
grep -C 3 /agent-binaries/linux_amd64/exec/exec-agent-linux_amd64.tar.gz /data/logs/logs/localhost-access.log
```

**Comment by ibuziuk** [comment]
@ldimaggi is it still reproducible with the lastest version of che?

**Comment by ldimaggi** [comment]
Not seeing this issue - closing - thx!
