### ISSUE TITLE
Angular version consistency broken between patternfly-ng, platform, and ngx-widgets

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#1044]
Currently, we have a mixup of Angular versions between those three components (and Planner, for that matter). Some of them are using 4.0.3, some 4.4.3. This causes the Planner build to break with newer features, especially some that we need for stories in the current sprint. This is currently blocking the Planner team.

All components should use 4.4.3 as per suggestion from the Patternfly team.

**Comment by joshuawilson** [comment]
I've been working on this, I think I have a resolution worked out. If it works it will be rolled out this week.

**Comment by joshuawilson** [comment]
The versions have been aligned and the code updated to use the latest version of Angular (4.4.4).

**Comment by joshuawilson** [comment]
To be clear, PF does not drive what version of Angular someone should use. They can tell you what they support.
