### ISSUE TITLE
Deleting a space is a bit unintuitive

### ISSUE THREAD

**Issue by containscafeine** [openshiftio/openshift.io#1045]
I created a space from my openshift.io homepage, and after a few clicks it gets created and reflects at the homepage.
Now, to delete the space I just created,
- I start looking for a _bin_ or a _trash_ icon after hovering over the space name under recent spaces, but there is nothing there.
- Then I assume that the delete option will be there after going into the space after clicking on the space name under _Recent Spaces_, but I don't see anything there either.
- But, I see a _settings_ icon at the top near _Analyze_, but there is nothing to delete there either.

Where I end up finding the delete space option is -
- click on my username at the top right
- click on Profile
- go to the Spaces tab
- delete the space
Or,
- under my email at top left
- under _View all spaces_
- I see the _bin_ icon next to my namespace

I found this deletion process a tiny bit unintuitive, but YMMV :)
Just wanted to share the feedback.

**Comment by joshuawilson** [comment]
We have a user story to track this issue. We are are aware of how difficult it currently is to maintain spaces. 
Thank you for your feedback, please track the issue at https://github.com/openshiftio/openshift.io/issues/478. I'm going to close this one.
