### ISSUE TITLE
Not able to proceed after create pipeline step

### ISSUE THREAD

**Issue by hrishin** [openshiftio/openshift.io#1046]
Not able to proceed after create pipeline stage while creating the application.

Steps to reproduce:
1) Reset the environment from update profile
2) Create space
3) Create QuickStart project
4) Choose Vertx booster application, click next
5) Enter group id, artifact id, project name, click next
6) Choose any pipeline option, click next, it shows validating message but nothing happens

Screenshot OpenShift Online:

![screenshot from 2017-10-05 17-55-20](https://user-images.githubusercontent.com/28615674/31227153-69a8a618-a9f6-11e7-84c5-dc05fa079b21.png)

**Comment by aslakknutsen** [comment]
Logout and login again (or hard refresh OSIO).. That should reprovision you in a useful state

**Comment by joshuawilson** [comment]
It appears this was an issue with your environment and is fixed now. If it is still an issue please reopen and comment.
