### ISSUE TITLE
On prod-preview - Jenkins pod fails to start after environment reset

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1047]
This problem is reproducible 100% of the time. After an environment reset, Jenkins fails to start. No log file is written. This event is reported:

Error creating: No API token found for service account "jenkins", retry after the token is automatically created and added to the service account
18 times in the last 9 minutes
38 times in the last 20 minuites

**Comment by joshuawilson** [comment]
@ldimaggi Is this still an issue?
@rawlingsj were you aware of this?

**Comment by ldimaggi** [comment]
Closing - there is a newer new issue- https://github.com/openshiftio/openshift.io/issues/1111
