### ISSUE TITLE
Users with "@" char in their OSIO usernames experience 404 errors on recent active pipelines

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1048]
If a user with a '@' char in his/her OSIO username clicks on a 'recent active pipeline' - this error is raised:
![screenshot from 2017-10-03 09-44-52](https://user-images.githubusercontent.com/642621/31128861-f895970a-a820-11e7-94ad-4a4b8d1a0c2d.png)

The problem is that the pipelines URL is:
https://openshift.io/ldimaggi/Oct3/create/pipelines

When it should be:
https://openshift.io/ldimaggi%40redhat.com/Oct3/create/pipelines

**Comment by joshuawilson** [comment]
I'm not sure if this needs to be fixed in the UI auth component or on the pipelines page. We need to investigate to see where to fix it.
@dgutride @jstrachan do you have any ideas?

**Comment by jstrachan** [comment]
probably its a bug in the pipelines dashboard page; using the user email rather than entity name or something?

**Comment by joshuawilson** [comment]
Is this still an issue?

**Comment by andrewazores** [comment]
This looks to be effectively a dupe of #575 . Both links are implemented the same way and exhibit the same incorrect behaviour.
