### ISSUE TITLE
add red hat repos to maven settings.xml secret so pipelines can run FIS quickstarts

### ISSUE THREAD

**Issue by rawlingsj** [openshiftio/openshift.io#1050]
Reported on IRC we cant build this project https://github.com/rawlingsj/mlo-fis2-karaf-demo in a pipeline because we're missing artifacts in https://maven.repository.redhat.com/earlyaccess/all and https://maven.repository.redhat.com/ga.

**Comment by rawlingsj** [comment]
Adding these repos to the build settings xml makes sense, hopefully we can build the example project after.  Will take a look...

**Comment by rawlingsj** [comment]
Rather than adding the repos I just removed the mirror that preventing folks from using `<repository>` in their poms.  I just merged this https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/26 but it will take a little while to trickle up the pipelines and be available in OSIO.

**Comment by joshuawilson** [comment]
Based on your last comment, is this fixed?

**Comment by qodfathr** [comment]
It sounds like we have a reasonable work-around now, and if we run into further needs adding the Red Hat repos we can either reopen this or create a new issue as part of a larger Scenario.
