### ISSUE TITLE
Creating pipelines (while adding a new quickstart project to a space) is failing: rg.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1051]
See attached Jenkins pod log.

Started seeing this on Oct 3 - steps to recreate:
* Create a new quickstart/project
* Observe the project's build pipeline fail to run
[jenkins_pod_log.txt](https://github.com/openshiftio/openshift.io/files/1353462/jenkins_pod_log.txt)

**Comment by ldimaggi** [comment]
Looks like this may not be reproducible.

**Comment by ldimaggi** [comment]
Multiple (>160) instances of references to projects' build configs already existing. 

WARNING: Caught: java.lang.IllegalArgumentException: testoct31507056344110 already exists
java.lang.IllegalArgumentException: testoct31507056344110 already exists
2:54 PM

**Comment by joshuawilson** [comment]
@ldimaggi is this still an issue? Can you reproduce it?
cc @rawlingsj @jstrachan

**Comment by ldimaggi** [comment]
This one turned out to not be reproducible - closing - thx!
