### ISSUE TITLE
User cannot see Content Repo status in Current OSIO Status Display

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1055]
The current status display looks like this:
![screenshot from 2017-10-04 09-55-39](https://user-images.githubusercontent.com/642621/31179616-6a09a998-a8ea-11e7-9a2c-a5168ae2c56c.png)

If the Content Repo deployment has failed, the user will not know until a quickstart deployment fails with this error: 
```
Oct 04, 2017 1:42:34 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://content-repository:80: No route to host (Host unreachable)
```

**Comment by joshuawilson** [comment]
@jstrachan @kbsingh any idea how we can get notified if the Content repo fails?

**Comment by jstrachan** [comment]
zabbix should be able to alert on a tenants content repo; its a canonical URL for each user.

Its such a trivial microservice; it should never really fail; it uses minimal memory and some PV. However if users need to know if its up or not we could always add a status icon to the fabric8-ui status UI; we can just do a HTTP GET on the content repo to see if its up

**Comment by joshuawilson** [comment]
@ldimaggi is this something you happening often or just this once? Can you reproduce it?

**Comment by ldimaggi** [comment]
Yes - this is reproducible - if the Jenkins pod is up, but the Content Repo pod is down - the "Jenkins" status icon in the status display is still green.

**Comment by joshuawilson** [comment]
What is the Content Repo?

**Comment by jstrachan** [comment]
A small nexus like thing to store releases Pom / jars

**Comment by joshuawilson** [comment]
@jstrachan is this something you can fix?

**Comment by jstrachan** [comment]
not sure which part of this you want me to fix. 

* there's something going wrong if the Content Repo can't run - I've no clue why thats happening or what the fix to stop it is. Someone who reproduces this issue needs to use `oc` to describe the `DeploymentConfig` / `Pod` and maybe look at the pods log to find out why its not running - is it quota related? PVs full maybe?
* someone on the monitoring team can add Zabbix monitoring of the Content Repository to check if its up or down for each tenant (you should be able to get a 200 from its public Route)
* someone who works on fabric8-ui should be able to add a Content Repository status icon to the status widget UI - its a simple REST endpoint that can have a GET operation on it

I could help on the latter but my TODO list is kinda huge right now - could someone else try have a go?

**Comment by ldimaggi** [comment]
Sorry for any confusion - the issue here is that the content repo status is not shown in the OSIO status icon pulldown list. So - the user will not know if it is down. It's a different issue if it crashes or fails to start. Thx!

**Comment by joshuawilson** [comment]
@jstrachan thanks, that lists helps enough for others to pick up the bits.
