### ISSUE TITLE
Stack analysis on the production server does not finish, even after 1 hour

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1056]
How to reproduce:

1. call the API to start new stack analysis on the recommender.api.openshift.io address
2. try to wait for the analysis to finish

Actual behaviour:
1. only HTTP 202 Accepted code is returned (almost) endlessly

Expected behaviour:
1. after some time (let's say under 5 minutes) the HTTP 200 OK + stack analysis should be returned

Possible causes:
1. Performance tests were run ~6 hours ago

**Comment by tisnik** [comment]
@samuzzal-choudhury @msrb @fridex [FYI ^]

**Comment by ldimaggi** [comment]
Automated test to trap this bug:
https://ci.centos.org/view/Devtools/job/devtools-test-end-to-end-openshift.io-runTest/

**Comment by samuzzal-choudhury** [comment]
@tisnik this should be fixed now by the PR https://github.com/fabric8-analytics/fabric8-analytics-server/pull/172

**Comment by joshuawilson** [comment]
Is this fixed? Can we close it?

**Comment by joshuawilson** [comment]
Closing as this is fixed.
