### ISSUE TITLE
Restrict pushes to master and force review process

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#1057]
# Description

We would like to restrict pushes to master and let all contributors submit PRs that would go through review process. With this restriction we are sure that all PRs are reviewed and CI passes.

https://help.github.com/articles/enabling-branch-restrictions/

# Acceptance criteria

 - [ ] All repositories in fabric8-analytics organization have "master" branch protected
-  [ ] All repositories in fabric8-analytics organization have "Require pull request reviews before merging" set
- [ ]  All repositories in fabric8-analytics organization have "Require status checks to pass before merging" so no PRs are merged without CI/linter success

**Comment by joshuawilson** [comment]
@fridex  this is something we try to have on all our repos. Has this been done yet. To be honest, it should be done, I don't know why it is an issue.
cc @krishnapaparaju

**Comment by fridex** [comment]
> @fridex this is something we try to have on all our repos. Has this been done yet. To be honest, it should just be done, I don't know why it is an issue as it is not a change to the code.

We don't do that currently in fabric8-analytics repos. This issue was created so this workflow is approved - it's a manner of few mins to turn this on, but still it's good to know about it and notify devs about this change.

**Comment by joshuawilson** [comment]
good point

**Comment by krishnapaparaju** [comment]
@fridex precursor to enable these checks is team start using Dev. cluster. Will enable these checks once team is on board with starting development work from the dev. cluster.

**Comment by miteshvp** [comment]
Already done. Closing.
