### ISSUE TITLE
Run As -> JUnit test works only if the project was built beforehand

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1060]
**Blocked by JDT LS switch** eclipse/che#6157

Steps to recreate:
* Create new quicksart - for example Vert.x Basic
* Create Che workspace
* In the Che workspace, attempt to run the test programs as JUnit tests;
![screenshot from 2017-10-05 11-52-50](https://user-images.githubusercontent.com/642621/31237695-ad047c06-a9c5-11e7-8390-b0f9916bf16f.png)

**Comment by ibuziuk** [comment]
@ldimaggi one needs to build project first before running the tests.
related rh-che issue - https://github.com/redhat-developer/rh-che/issues/365
upstream che issue - eclipse/che#6549

**Comment by joshuawilson** [comment]
Is this a valid issue? Is it a duplicate? Can we close it?

**Comment by slemeur** [comment]
The issue is still valid and the end-user experience is really not straight forward this way. We might find workarounds for that.

**Comment by ibuziuk** [comment]
The issue will be resolved once che will switch to jdt.ls in upstream
@slemeur in the mean time, could we change severity to SEV3 ?

**Comment by qodfathr** [comment]
@ibuziuk this is an important and prominent feature which is not working out-of-the-box, so IMHO `SEV2` is appropriate.

**Comment by ibuziuk** [comment]
The issue is going to be fixed after swithing to JDT LS.
demo link https://youtu.be/zE9Cvu_u9-c

**Comment by miteshvp** [comment]
@slemeur @ibuziuk - any updates here? Is this moved to prod? If not any ETA?

**Comment by ibuziuk** [comment]
@miteshvp this is going to be fixed upstream [1] as part of the switch to JDT LS. In terms of ETA  @tsmaeder is the right person to ask 

[1] https://github.com/eclipse/che/issues/6157

**Comment by slemeur** [comment]
This is going to be fixed in Eclipse Che during the next release train. While the experience is not optimal, there is still a way to run the tests: user needs to build the project before starting to run the tests, or in the terminal run the command `mvn install`. 

@miteshvp : This should not block your acceptance criterias as we have a workaround for that and an upcoming solution as well.

**Comment by miteshvp** [comment]
@slemeur ack

**Comment by ibuziuk** [comment]
@rhopp @ScrewTSW @Katka92 Che has been switched to jdt.ls [1] so it would be great to see if this problem is still reproducible

[1] https://github.com/eclipse/che/issues/6157

**Comment by ldimaggi** [comment]
Closing - this problem is not being seen now:

![screenshot from 2018-12-02 16-18-23](https://user-images.githubusercontent.com/642621/49345088-f77ed800-f64d-11e8-9919-0f2e1fb758c8.png)
