### ISSUE TITLE
Epic: Enable support for generating effective POM in IDE plugins

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#1063]
##### Definition:
As part of [an on-hold change](https://github.com/openshiftio/openshift.io/issues/705), mercator-go will stop generating effective POM for user uploaded pom.xml files while calling /stack-analyses. A client, on the other hand, is the best place to resolve all dependencies used in a developer environment and hence, to generate the effective POM.

This requirement triggers changes in all IDE plugins for fabric8-analytics that we deliver. So, all plugins should provide the mechanism to generate effective POM for maven projects and upload those with the /stack-analyses calls in order to get proper stack analytics reports.

**Comment by miteshvp** [comment]
Done.
