### ISSUE TITLE
[prod-preview] Incognito mode / cleaning cache is required for login to prod-preview 

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#1066]
Related openshift.io issue for prod-cluster - https://github.com/openshiftio/openshift.io/issues/955

**Comment by alexeykazakov** [comment]
Is there any reason to keep two separate issues open for prod and preview? :)
Looks like just a duplicate of https://github.com/openshiftio/openshift.io/issues/955

**Comment by ibuziuk** [comment]
everything works fine for me on prod, but not on prod-preview, so I have created a separate one.
Anyway, feel free to close this issue if tracking it in one place is more handy

**Comment by alexeykazakov** [comment]
Yeah.. It's browser state dependent. For some it works fine in prod but not in preview. For some it's fine in preview but not in prod. Something wrong in browser cache/local storage. I'm closing it as duplicate.
