### ISSUE TITLE
[prod-preview] Can not create a space - error occurs with Forge backend

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#1068]
Can not create a space on prod-preview - error occurs with Forge backend
![image](https://user-images.githubusercontent.com/1461122/31277859-34ebd046-aaa3-11e7-9216-54d330bba22b.png)

**Comment by joshuawilson** [comment]
I don't think we have ever had prod-preview working with Forge. 
@jstrachan @kbsingh @corinnekrych is this something we are going to fix or should we close it as "not fixing"?

**Comment by jstrachan** [comment]
I've never really been able to use prod preview; we can test local UI / forge against prod on our tenants so I don't really see the point of prod preview for UI / forge really. We can already test PRs of UI against prod too; would be more interested in testing PRs against forge on prod as well

**Comment by corinnekrych** [comment]
@joshuawilson @jstrachan @kbsingh As log as we keep "localhost" in the list of valid (it was once removed and then added back by @alexeykazakov https://github.com/fabric8-services/fabric8-auth/pull/122) we indeed have an env variable to work locally (ui and forge) targeting remote WIT. I guess where it becomes mor ecomplex is if you need all servers running locally (ie WIT too).

@ibuziuk here is the doc on how to run local ui with local forge: https://github.com/fabric8-ui/fabric8-ui/wiki/How-to...#how-to-run-local-ui-with-local-forge 
is your use-case different?

**Comment by ibuziuk** [comment]
@corinnekrych my use-case is different - I can not create a quickstart on staging environment ;) 

> I've never really been able to use prod preview; we can test local UI / forge against prod on our tenants so I don't really see the point of prod preview for UI / forge really - its more a place to test auth/wit/f8tenant.

@jstrachan how could we test openshift upgrades without staging environment? Migration from 3.5 to 3.6 was literally a nightmare for Che and I believe it was agreed that before cluster update everything must be tested on staging environment first (free-int is 3.7 / prod is 3.6 currently)

**Comment by jstrachan** [comment]
I'm not saying we shouldn't use testing or other clusters - am just saying I've never found the staging cluster to be useful for anything I've work on in OSIO. 

We can boot up the entire OSIO platform on any openshift/kubernetes cluster via the [fabric8 installer](https://github.com/fabric8io/fabric8-platform/blob/master/INSTALL.md) and then test that - stuff typically then works too. Whereas outside of the fabric8 installer its very easy to get a cluster that doesn't work if its all wired together by hand - there are so many things that can go wrong trying to configure a staging environment by hand.

**Comment by kbsingh** [comment]
at the moment the errors look specific, eg :
```
WARNING: Failed to load /var/lib/jenkins/hudson.tasks.Maven.xmljava.io.IOException: Unable to read /var/lib/jenkins/hudson.tasks.Maven.xml
```

it would be good if we can investigate what the problem is - its possible this is symptoms of something that is going to blow up in prod next.

**Comment by kbsingh** [comment]
that specific error might not be interesting, Jenkins seems to be running ok. I think someone on the Forge team is going to need to look at this.

**Comment by jfchevrette** [comment]
![jenkins](https://user-images.githubusercontent.com/3001/31451480-370996bc-ae7a-11e7-9ef4-6bb448ded748.png)

```
Caused by: com.thoughtworks.xstream.converters.ConversionException:  : no more data available - expected end tag </hudson.tasks.Maven_-DescriptorImpl> to close start tag <hudson.tasks.Maven_-DescriptorImpl> from line 2, parser stopped on TEXT seen ...</installations>\n</hudson.tasks.Maven_-DescriptorImpl... @17:37 :  : no more data available - expected end tag </hudson.tasks.Maven_-DescriptorImpl> to close start tag <hudson.tasks.Maven_-DescriptorImpl> from line 2, parser stopped on TEXT seen ...</installations>\n</hudson.tasks.Maven_-DescriptorImpl... @17:37
---- Debugging information ----
message             :  : no more data available - expected end tag </hudson.tasks.Maven_-DescriptorImpl> to close start tag <hudson.tasks.Maven_-DescriptorImpl> from line 2, parser stopped on TEXT seen ...</installations>\n</hudson.tasks.Maven_-DescriptorImpl... @17:37
cause-exception     : com.thoughtworks.xstream.io.StreamException
cause-message       :  : no more data available - expected end tag </hudson.tasks.Maven_-DescriptorImpl> to close start tag <hudson.tasks.Maven_-DescriptorImpl> from line 2, parser stopped on TEXT seen ...</installations>\n</hudson.tasks.Maven_-DescriptorImpl... @17:37
class               : hudson.tasks.Maven$DescriptorImpl
required-type       : hudson.tasks.Maven$DescriptorImpl
converter-type      : hudson.util.RobustReflectionConverter
path                : /hudson.tasks.Maven$DescriptorImpl
line number         : 17
version             : not available
-------------------------------
```

**Comment by vpavlin** [comment]
@ibuziuk I think the issue you saw should be gone on prod-preview now with change in https://github.com/fabric8io/generator-backend/pull/63/files

There is another bug though - according to @jstrachan and @rawlingsj probably related to 3.7

```
017-10-13 10:57:50,877 SEVERE [org.obsidiantoaster.generator.rest.ObsidianResource] (default task-49) Failed to create BuildConfig from from project vasek-blahblah. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.free-int.openshift.com/apis/build.openshift.io/v1/namespaces/vpavlin/buildconfigs. Message: BuildConfig in version "v1" cannot be handled as a BuildConfig: no kind "BuildConfig" is registered for version "build/v1". Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=BuildConfig in version "v1" cannot be handled as a BuildConfig: no kind "BuildConfig" is registered for version "build/v1", metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).: java.lang.RuntimeException: Failed to create BuildConfig from from project vasek-blahblah. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.free-int.openshift.com/apis/build.openshift.io/v1/namespaces/vpavlin/buildconfigs. Message: BuildConfig in version "v1" cannot be handled as a BuildConfig: no kind "BuildConfig" is registered for version "build/v1". Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=BuildConfig in version "v1" cannot be handled as a BuildConfig: no kind "BuildConfig" is registered for version "build/v1", metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
```

Generally it seems Forge (?) cannot upload build configs to OSO 3.7

**Comment by jstrachan** [comment]
that error should have gone away now with the revert of the new kubernetes client in forge https://github.com/fabric8io/fabric8-generator/commit/e80e93ccb205e8a8aca876875ba36be687e8a895

**Comment by ibuziuk** [comment]
@vpavlin @jstrachan having another problem right now
![image](https://user-images.githubusercontent.com/1461122/31602871-94a5862c-b25e-11e7-98ba-1f23673cfd42.png)

**Comment by vpavlin** [comment]
@ibuziuk Assuming you get this at the end of the Forge workflow, it's cause by the error I pasted above (error is from container logs)

**Comment by rawlingsj** [comment]
Looks like there's an issue with openshift because the version that has the fix for https://github.com/openshiftio/openshift.io/issues/1068#issuecomment-336818638 is in fabric8-forge https://github.com/fabric8io/generator-backend/tree/v1.0.81, the DC in prod preview is  1.0.81 but the pods are still at 1.0.80.

Also checking the DC it shows it has 2 desired but 0 current:
```
NAME                REVISION   DESIRED   CURRENT   TRIGGERED BY
generator-backend   52         2         0         config
```

**Comment by ibuziuk** [comment]
@vpavlin yeah, it was at the very end

**Comment by vpavlin** [comment]
@rawlingsj I kick off another deployment and it succeeded - could that the image was unavailable or something? There were some readiness probe fails toos, but probably not enough to kill the deployment, though we could give it more head room for readiness probe..

Anyway, I was able to get through the quickstart generation and pipeline kicked off

**Comment by rawlingsj** [comment]
So this issue can be closed?

**Comment by rawlingsj** [comment]
As a side point it would be good to get some monitoring / alerting to notify if a DC deployment fails or pods are at the wrong version.

**Comment by vpavlin** [comment]
If @ibuziuk confirms it works for him, then yes

**Comment by vpavlin** [comment]
@jfchevrette I am sure it's somewhere in Zabbix, do we send failed prod-preview DCs notification somewhere?

**Comment by corinnekrych** [comment]
@ibuziuk @vpavlin I was able to import a repo using wizard on prod-preview;
https://www.dropbox.com/s/4dr40tdl6txfh2q/Screenshot%202017-10-16%2011.15.41.png?dl=0 
🎉 
It looks good to me.

**Comment by ibuziuk** [comment]
Still not able to create space based on vertx quickstart, but with a different error now:

![image](https://user-images.githubusercontent.com/1461122/31610470-793644ca-b278-11e7-981a-bd76aa5685f3.png)

> forge.api.prod-preview.openshift.io//forge/commands/fabric8-new-project Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by vpavlin** [comment]
Something had to change again:) I see it too, but I also see a change in Forge UI (but generator backend did not update, so I blame the UI this time:) ). @joshuawilson What do you think?

**Comment by rawlingsj** [comment]
I suspect it's related to this endpoint having an extra`/` at the end? https://github.com/fabric8io/generator-backend/blob/master/Jenkinsfile#L78

**Comment by vpavlin** [comment]
I don't think so..I've specifically put it there to follow the default value here https://github.com/fabric8io/fabric8-generator/blob/master/src/main/java/io/fabric8/forge/generator/EnvironmentVariables.java#L35

**Comment by rawlingsj** [comment]
OK so in that case yeah sounds like this commit might be related @corinnekrych https://github.com/fabric8-ui/fabric8-ui/commit/07b035dab43a4d415321e3c9207991dd59d7764b

**Comment by corinnekrych** [comment]
@rawlingsj @vpavlin I confirmed we just pushed a big UI PR.
Checking https://github.com/fabric8-ui/fabric8-ui/blob/master/environments/openshift-prod-cluster.sh#L49 it seems the forge one is without `/` so we add it here https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/forge-wizard/forge.service.ts#L16 but i guess we should wether or not it's here already. let me fix that.

**Comment by vpavlin** [comment]
I consider this one fixed

@ibuziuk What about you?

**Comment by ibuziuk** [comment]
@vpavlin yeah, let's close it
