### ISSUE TITLE
Using proxy user instead of requiring OpenShift token

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#1069]
In a discussion with Jake, @alexeykazakov, and @aslakknutsen we determined that we could improve the user flows (remove the first time user experience need of asking for connection to OpenShift) and make the system more scalable through the use of a proxy user for requesting information and actions on OpenShift over using a token for those actions.  This issue to a place to start to gather the tasks required to shift to this model.

Acceptance criteria/Tasks:
_unknown, need to be identified_

**Comment by alexeykazakov** [comment]
This issue is covered by https://github.com/openshiftio/openshift.io/issues/948 and https://github.com/openshiftio/openshift.io/issues/1747
I'm closing this issue as a dupe.
