### ISSUE TITLE
[8] Sync nuget and npm data to graph

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1072]
# Description

Not all Nuget and NPM data made it all the way to graph. We need to sync them.

# Acceptance criteria

- [x] all Nuget data from from production S3 buckets are available in graph
- [ ] all NPM data from from production S3 buckets are available in graph

**Comment by fridex** [comment]
I've just scheduled syncs of nuget packages to graph on priority workers. Once finished, we can move on to nuget ecosystem.

**Comment by miteshvp** [comment]
- Once finished, we can move on to nuget ecosystem.

@fridex - I guess you meant node ecosystem here. Any updates whether we already started node syncs?

**Comment by fridex** [comment]
> - Once finished, we can move on to nuget ecosystem.
>
> @fridex - I guess you meant node ecosystem here. Any updates whether we already finished nuget and started node syncs? Can you please check mark corresponding items.

Nope, nuget is in progress. Will wait for nuget to finish first, we can start with npm afterwards.

**Comment by miteshvp** [comment]
- I've just scheduled syncs of nuget packages to graph on priority workers. Once finished, we can move on to nuget ecosystem.

@fridex - you mentioned nuget in both the places which got me confused. But my understanding is correct. Thanks. Given the priority, we would like to sync npm first rather than nuget. Can it be done?

**Comment by fridex** [comment]
? @fridex - you mentioned nuget in both the places which got me confused. But my understanding is correct. Thanks. Given the priority, we would like to sync npm first rather than nuget. Can it be done?

Ah, sorry - corrected. Sure, I will do it today.

**Comment by fridex** [comment]
> Ah, sorry - corrected. Sure, I will do it today.

Scheduled NPM sync on priority workers.

@miteshvp could you please check the current status of nuget in the graph? The sync should be over.

**Comment by miteshvp** [comment]
@fridex - I don't see nuget syncs increments anymore. Maybe they have finished. Have provided the numbers in MM

**Comment by msrb** [comment]
@miteshvp can you please confirm that this is running as expected? I can see activity on priority workers, but I don't see anything in graph-importer logs.

Thanks.

**Comment by miteshvp** [comment]
@msrb - I see activity in graph-importer logs. Maybe workers were busy processing something else. Currently there are 65086 EPVs for node.

**Comment by fridex** [comment]
I guess this sync was done for both npm and nuget ecosystem. @miteshvp, could you please verify it?

**Comment by miteshvp** [comment]
@fridex - this is still ongoing as I can see increments in graph for npm nodes. Currently I see `113886` EPVs in Graph

**Comment by miteshvp** [comment]
I see `122529` EPVs for node ecosystem in graph

**Comment by msrb** [comment]
@miteshvp with the libio integration via firehose-fetcher, we are analyzing/syncing newly released NPM packages every day. So the number should/will grow every day :)

**Comment by miteshvp** [comment]
@msrb - I see a total of `241537` npm EPVs in S3. We are nowhere close there yet.

**Comment by msrb** [comment]
Marking as blocked. We need to implement https://github.com/openshiftio/openshift.io/issues/1085, otherwise this task is almost impossible to finish. This graph ingestion piece of pipeline is still incredible fragile. We can schedule the sync, it will run for 2 weeks, but since the whole sync can take longer than 14 days, some messages on SQS can timeout. And currently there is no way of telling which data are already in graph and which are not.

**Comment by msrb** [comment]
Replaced by https://github.com/openshiftio/openshift.io/issues/2047
