### ISSUE TITLE
Please add 'schema' attribute into the JSON file for the keywords taggings in component core data

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1074]
Please add 'schema' attribute into the JSON file for the keywords taggings in component core data. This attribute should contains nodes 'name' and 'version'.

Please note: it is not urgent, but other metadata already have this attribute, so we would need to be consistent a bit ;)

**Comment by fridex** [comment]
Done in https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/392 (still WIP).
