### ISSUE TITLE
Intermittent failure in pipeline build

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1075]
Started seeing this on Oct 9 - when a new project/quickstart is created and its build pipeline runs - the build fails intermittently with this error:
```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.28:build (fmp) on project testoct91507577130712: Failed to execute the build: Unable to build the image using the OpenShift build service: OpenShift Build testoct91507577130712-s2i-1: Failed: PullBuilderImageFailed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.28:build (fmp) on project testoct91507577130712: Failed to execute the build
```

See atta
[build_log_1.txt](https://github.com/openshiftio/openshift.io/files/1370349/build_log_1.txt)
[build_log_2.txt](https://github.com/openshiftio/openshift.io/files/1370350/build_log_2.txt)

ched build logs.

**Comment by joshuawilson** [comment]
@ldimaggi did you see this question?

**Comment by ldimaggi** [comment]
Closing as non-reproducible - I think that this was caused by resource contention when multiple tests ran (inadvertently) at the same time - and collided.
