### ISSUE TITLE
Task : Update Ops Portal UI to accommodate the new license data

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#1078]
- Update the recommender portal in the OSIO with the new license data.

Below is the new json structure for license data :-
{
  "license_analysis": {
    "f8a_stack_licenses": [],
    "status": "Unknown",
    "conflict_packages": [{
        "package1": "",
        "license1": "",
        "package2": "",
        "license2": ""
      },
      {
        "package1": "",
        "license1": "",
        "package2": "",
        "license2": ""
      }
    ],
    "unknown_licenses": {
      "really_unknown": [{
        "package": "vert.x-5",
        "license": "lgplv3+"
      }],
      "component_conflict": [{
        "package": "vert.x-5",
        "conflict_licenses": [{
          "license1": "l1",
          "license2": "l2"
        }, {
          "license1": "l3",
          "license2": "l4"
        }]
      }]
    },
    "outlier_packages": [{
        "package": "vert.x-5",
        "license": "lgplv3+"
      },
      {
        "package": "vert.x-5",
        "license": "lgplv3+"
      }
    ]
  }
}

**Comment by samuzzal-choudhury** [comment]
This is already available on prod. Hence, closing.
