### ISSUE TITLE
Clear up / Back up messages at SQS Queues

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1079]
Both to serve user facing traffic (async) and ingestion of data, Analytics platform heavily uses SQS queues. From the operational side, there been couple of instances where messages at these queues pileup (during some failure scenario) and require cleaning / backing up of messages at these SQS queues to resume user facing traffic / data ingestion.

A script to clear up messages at these SQS queues (TODO: need to document the queue names) would be useful to avoid manual clearing up of these messages thru AWS console.

**Comment by fridex** [comment]
Is there some specific case for doing this? Queues are currently configured to drop messages after 14 days (that is maximum that AWS SQS offers) - messages will be automatically removed from queues.

Also clearing messages is not that straightforward as if cleaned in a wrong way, it can result in infinite task flows (workers would get stuck). Cleaning queues should occur in really necessary situations (ideally never).

**Comment by krishnapaparaju** [comment]
With readonly access at console, would need to script all the delete of AWS resources if required for operational needs

**Comment by fridex** [comment]
> With readonly access at console, would need to script all the delete of AWS resources if required for operational needs

Already done. We can also get queue attributes (for now age of messages).

See https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/196 https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/183 https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/206

**Comment by msrb** [comment]
Our jobs service now has `api/v1/jobs/queue-purge` endpoint which can be used to purge all or explicitly listed queues. This functionality is available in production.

**Comment by jpopelka** [comment]
Has been completed since Nov 2017, closing.
