### ISSUE TITLE
Track API calls across multiple services of Analytics platform

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1080]
Currently manual verification / pattern of log files at multiple services is required to trace current state of incoming API call: its either waiting at SQS queue, pending with Service A / B etc. Unique ID would need to be prefixed to every log message being printed to track current state of incoming API call.

**Comment by joshuawilson** [comment]
This type of thing might be good for the whole project. You should discuss it with @kbsingh @aslakknutsen  @jstrachan

**Comment by ncoghlan** [comment]
Given http://www.hawkular.org/blog/2017/04/19/hawkular-apm-jaeger.html, perhaps it would make sense to explore the use of https://github.com/jaegertracing/jaeger-client-python?

**Comment by miteshvp** [comment]
Not relevant any longer. Moved to backbone service.
