### ISSUE TITLE
[5] Mapping of AWS resources to Dev,Stage and production environments

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1081]
AWS resources being used currently from various analytics platform developer environments (Dev, stage and production) would require (a) List all the AWS resources being used (b) tag AWS resources to associate with Dev,Stage, production / individual developers. 

Tagging cloud resources is the most common way to handle this: either thru AWS console, APIs

**Comment by joshuawilson** [comment]
Does @kbsingh know about this?

**Comment by krishnapaparaju** [comment]
Yes, discussed the need to get handle on resources being used.

**Comment by msrb** [comment]
@jpopelka @pkajaba @tuxdna @humaton

Team, this is another task which requires some attention. We want to automatically tag AWS resources that we allocate so we can later identify and delete resources that are no longer needed (like for example resources allocated by developers, not associated with prod/staging envs.)

Take a look what we already do for S3 buckets: https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/storages/s3.py#L98-L109

We want to do the same for SQS, RDS and DynamoDB.

Note not all AWS resources support tagging. If that's the case for any of the resources mentioned above, then we just want to document that we allocate them and what conventions we use (e.g. `prod-` prefix vs. `msrb-` prefix, etc.)

**Comment by msrb** [comment]
Note this is only about tagging the resources, then there is a separate task for deleting unnecessary resources: https://github.com/openshiftio/openshift.io/issues/1330.

**Comment by jpopelka** [comment]
- [Worker PR #470 for SQS](https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/470)
- [Common PR #400 for RDS](https://github.com/fabric8-analytics/fabric8-analytics-common/pull/400)

**Comment by msrb** [comment]
Everything should be merged and I just pushed the new worker to production. Thanks @jpopelka 😉
