### ISSUE TITLE
Checks of system liveness and readiness

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1082]
It would be nice to implement a system, that will periodically check system liveness and readiness by:

- [ ] accessing server API (stage, prod)
- [ ] accessing jobs API (stage, prod)
- [ ] accessing AWS S3 and all relevant buckets
- [ ] performing stack analysis (with less frequency)

**Comment by joshuawilson** [comment]
I think we already have some of this, please check with @kbsingh

**Comment by tisnik** [comment]
It's part of #1099
