### ISSUE TITLE
Resilient infra for services of Analytics platform

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1084]
When one of our services unexpectedly fail (fail=gets restarted by OpenShift) during stack analysis, data ingestion, etc. the system should be able to recover and analysis shouldn't stay "in progress" indefinitely. We'd like to add/modify our E2E tests so we can easily test such scenarios and discover bugs early.

It's not necessary to run these types of tests in CI for every merge to master branch. But the way how to run them on-demand against existing deployments should be documented.

**Comment by krishnapaparaju** [comment]
Please check this Choas Monkey for OpenShift 3X: https://github.com/Produban/monkey-ops

**Comment by krishnapaparaju** [comment]
@msrb any thing we waiting / blocked for this task ?

**Comment by msrb** [comment]
@krishnapaparaju no blockers other than manpower. We will start working on this this week. As we discussed on cabal, we will rescope this a bit - we will trust OpenShift to automatically restart services that failed from some reason, but we will review/improve Zabbix monitoring that should give us an early warning that something is not stable enough, or not working properly.

**Comment by krishnapaparaju** [comment]
thanks @msrb . we can start with scope of network / API connectivity with AWS hosted resources as one of the initial tests for failures...

**Comment by msrb** [comment]
Thinking about this more: we can actually identify good candidates for this type of testing by just looking at the current architecture. The services that rely on SQS are in advantage here as, as long as tasks on queues are idempotent, they will continue where they left before crash (we trust OpenShift to handle this). Interrupted tasks will be transparently re-tried again, thanks to [visibility timeouts](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html). We could try to simulate a situation when network is temporarily unavailable. I think workers are currently configured to intentionally crash to force container restart.

data-importer being unavailable means that data won't reach graph, but then Saleem recently implemented "sync-missing" functionality that we can help us in such scenarios.

I will need to take a look into server's backbone implementation, but I suspect that if one of the replicas crashes, then new requests will be transparently routed to the replicas that are still running, but all the state that the crashed replica was holding is permanently lost and thus stack analyses that were handled by the replica will forever stay in "in-progress" state. I am not 100% sure about this though, it needs some investigation.

**Comment by msrb** [comment]
We discussed this with @tisnik and we agreed that we will start with a test when we will focus on resiliency of the user-facing part of the pipeline.

**Comment by miteshvp** [comment]
@msrb - you are right about backbone implementation. Its more a stateless service. Hence, as part of the workflow, if we have book-keeping record with a stack-id created, but still does not have any recommendation or aggregator result in RDS, we should invoke them again.

**Comment by tisnik** [comment]
@miteshvp how do you check when to invoke new stack analysis? IIRC we don't track the progress and don't have any threshold for (possible) timeout.

**Comment by miteshvp** [comment]
@tisnik - you are right and true for any stateless service to not maintain the status/progress. But with this [PR](https://github.com/fabric8-analytics/f8a-server-backbone/pull/14) we can trigger one more stack-analyses call ir-respective of whether the original call is actually in progress or not. To further this, we can utilize started_at timestamp from original book-keeping record and initiate a new stack-analyses or wait for some more time. Hope it helps.

**Comment by tisnik** [comment]
@miteshvp ah I see. Interesting implementation. Thank you for clarification.

**Comment by msrb** [comment]
@miteshvp yeah, stack analyses should be idempotent, so we should be able to run them more than once without any consequences. One thing that we still need to figure out is who/when will retry.

In the mean time, I've opened PR for @tisnik test suite that will help us test these types of scenarios.

**Comment by msrb** [comment]
Another good candidate for this type of testing is pgbouncer. We had problems with it before - services were not able reconnect after pgbouncer restart.

**Comment by msrb** [comment]
@tisnik any update here?

**Comment by tisnik** [comment]
@msrb I did some research on the easy-to-test side: network failures between OS services, shutting down pods etc. ATM it is not automatic, ie there's no test script to do it and check the behaviour.

**Comment by msrb** [comment]
This is something we need to finish in 147.

**Comment by sivaavkd** [comment]
@msrb please update story points

**Comment by sivaavkd** [comment]
@msrb Where are we with this ?  Is this spilling over to 148 ?  Please update accordingly.

**Comment by msrb** [comment]
PR: https://github.com/fabric8-analytics/fabric8-analytics-common/pull/524
