### ISSUE TITLE
RFE planner: Ability to update card (task item) type

### ISSUE THREAD

**Issue by navidshaikh** [openshiftio/openshift.io#1088]
This RFE is regarding planner for OSIO. 

```OSIO -> Space -> Plan -> Board```

While creating cards (task items) during planning, the task item could be created with wrong type [Feature/Task/Bug/etc]. While reviewing / updating the card, user might want to update the type of task item.

[We](https://github.com/CentOS/container-pipeline-service) are using planner for our sprints.

**Comment by joshuawilson** [comment]
cc @michaelkleinhenz @nimishamukherjee

**Comment by nimishamukherjee** [comment]
@navidshaikh this request has a larger implication. We will revisit this post Freesia.

**Comment by nimishamukherjee** [comment]
We now allow changing of work item type.
