### ISSUE TITLE
[3] Configure Pydocstyle in all relevant fabric8-analytics repositories

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1089]
This issue belongs to the #829 epic.

# Description

In order to improve code quality, we would like to run Pydocstyle on every PR.

# Acceptance criteria

- [x] PRs are checked in CI

All pull requests in the following repo listing are checked against the output of Pydocstyle:

- [x] fabric8-analytics-server
- [x] fabric8-analytics-worker
- [x] fabric8-analytics-common
- [x] fabric8-analytics-stack-analysis
- [x] fabric8-analytics-license-analysis
- [x] fabric8-analytics-jobs
- [x] fabric8-analytics-tagger
- [x] fabric8-analytics-data-model
- [x] fabric8-analytics-recommender
- [x] fabric8-gemini-server

# Individual steps

## Put the script to run Pydocstyle into all repositories

- [x] fabric8-analytics-server
- [x] fabric8-analytics-worker
- [x] fabric8-analytics-common
- [x] fabric8-analytics-stack-analysis
- [x] fabric8-analytics-license-analysis
- [x] fabric8-analytics-jobs
- [x] fabric8-analytics-tagger
- [x] fabric8-analytics-data-model
- [x] fabric8-analytics-recommender
- [x] fabric8-gemini-server

## Put the CI configuration script into all repositories

- [x] fabric8-analytics-server
- [x] fabric8-analytics-worker
- [x] fabric8-analytics-common
- [x] fabric8-analytics-stack-analysis
- [x] fabric8-analytics-license-analysis
- [x] fabric8-analytics-jobs
- [x] fabric8-analytics-tagger
- [x] fabric8-analytics-data-model
- [x] fabric8-analytics-recommender
- [x] fabric8-gemini-server

## Configure CI to run Pydocstyle

- [x] fabric8-analytics-server
- [x] fabric8-analytics-worker
- [x] fabric8-analytics-common
- [x] fabric8-analytics-stack-analysis
- [x] fabric8-analytics-license-analysis
- [x] fabric8-analytics-jobs
- [x] fabric8-analytics-tagger
- [x] fabric8-analytics-data-model
- [x] fabric8-analytics-recommender
- [x] fabric8-gemini-server

**Comment by sivaavkd** [comment]
@tisnik - The epic this issue belongs to (#829), is already closed.  Are we targeting this for the current sprint ?

**Comment by tisnik** [comment]
@sivaavkd yes, this is a long term goal and we are going to finish it soon
