### ISSUE TITLE
Better failed /stack-analyses error report

### ISSUE THREAD

**Issue by jpopelka** [openshiftio/openshift.io#1093]
Follow-up of #850 

When `/stack-analyses` fails because of some problem in manifest file the subsequent `/stack-analyses/<external_request_id>` call returns just `{ "error": "Invalid manifest file(s) received. Please submit valid manifest files for stack analysis" }`
I think we should give more details about why it was not possible to process the manifest file, for example: `Dependencies could not be resolved: [foopackagebar==1.2.3]`

Question for @fridex: If a task raises `FatalTaskError("Failed due to xyz")` is this "Failed due to xyz" stored somewhere or it's just logged ? If it's stored then the change should be easy, otherwise we'd need to figure out how to store it so that we could later retrieve it in [StackAnalysesGET](https://github.com/fabric8-analytics/fabric8-analytics-server/blob/master/bayesian/api_v1.py#L312)

**Comment by fridex** [comment]
> Question for @fridex: If a task raises FatalTaskError("Failed due to xyz") is this "Failed due to xyz" stored somewhere or it's just logged ? If it's stored then the change should be easy, otherwise we'd need to figure out how to store it so that we could later retrieve it in StackAnalysesGET

[FatalTaskError](http://selinon.readthedocs.io/en/latest/tasks.html#task-failures) causes that a task will not be retried (overriding retry stated in `nodes.yaml`). If a task raises some error, it can be transparently stored in the storage adapter that is assigned to that particular task - selinon will call `store_error` that [can store information](http://selinon.readthedocs.io/en/latest/storage.html#using-a-custom-storage-adapter) about task failures/error reports.

**Comment by msrb** [comment]
@tuxdna any ETA on this issue? If this is going to take more than 1 day, then please pick different issue from the current sprint. We have SEV-2 issues that we need to close. Thanks :wink:

**Comment by tuxdna** [comment]
@msrb Yes, this one will take more than 1 day for sure. Which SEV2 issue do you mean ?

**Comment by miteshvp** [comment]
Improved. Closing.
