### ISSUE TITLE
UX refinement for the page loader spinner

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#1097]
https://docs.google.com/document/d/1NvbCbiHDKTkLHwALDXf91szke4miVuny4K_l_n5eXCg/edit#heading=h.jgwvnrr16u46

**Comment by michaelkleinhenz** [comment]
See https://redhat.invisionapp.com/share/UGDX1WHZ5

**Comment by mindreeper2420** [comment]
@nimishamukherjee @michaelkleinhenz is this only for Planner, or for all of OpenShift.io?

**Comment by joshuawilson** [comment]
Yes, It makes sense to me to have this be consistent.

**Comment by sunilmalagi** [comment]
Please create the issue on PF repository, here is the link:
https://github.com/patternfly/patternfly-design/issues

Removing the area/UX label since PF team is responsible for spinner component.

**Comment by christianvogt** [comment]
Closing as we have empty / loading states. There are many consistency issues that are going to be addressed by common components using pf4.
