### ISSUE TITLE
[5] RFE: a simple QA dashboard

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1099]
# Description

Provide a simple dashboard that displays all QA-relevant data:

## Services liveness and readiness
- [x] Actual status of stage server (OK, N/A)
- [x] Actual status of production server (OK, N/A)

## SLA
- [x] Basic perf.tests results (component and stack analysis duration)
- [x] Integration tests results for Stage env. (note it is different from testing on CI)
- [x] Integration tests results for Prod env. (note it is different from testing on CI)

## Code style
- [x] linter results for all repositories
- [x] Pydocstyle results for all repositories

For the 1st iteration, the dashboard might be generated daily and it might be static (generated) HTML page (+graphs etc.)

**Comment by tisnik** [comment]
The 1st version of the dashboard can be seen here:
https://fabric8-analytics.github.io/dashboard/dashboard.html

**Comment by samuzzal-choudhury** [comment]
Closing this as the task has been completed. @tisnik @msrb @miteshvp  reopen if required.
