### ISSUE TITLE
Spike: lower memory requirements of license worker

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1101]
Worker containers often get killed by OOM when running license analysis. We want to do a quick spike and see if we could lower memory requirements.

**Comment by krishnapaparaju** [comment]
@miteshvp this I guess need to be picked analytics stream to fix any memory related enhancements.

cc @msrb

**Comment by jpopelka** [comment]
@krishnapaparaju Michal is probably talking about the [scancode toolkit](https://github.com/nexB/scancode-toolkit) which we (core stream) use during component license scan.

I already increased the memory limit of the worker twice (https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/127 and https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/326).
Michal, if you spot it again, please add the EPV here, thanks.

**Comment by krishnapaparaju** [comment]
@jpopelka  thanks for the clarification...
