### ISSUE TITLE
Setup Wizard - Next Button goes nowehre after specifying github repo

### ISSUE THREAD

**Issue by harrymower** [openshiftio/openshift.io#111]
![image](https://cloud.githubusercontent.com/assets/1022371/25556892/b5b9f25a-2cd3-11e7-99b7-a18b31710997.png)

**Comment by joshuawilson** [comment]
@mitchharpur please look at this.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1360
