### ISSUE TITLE
Cannot create new quickstart project on prod-preview

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1111]
Steps to recreate:
* On prod-preview, create a new space
* Attempt to create a new quickstart project - observe this Forge error:
![screenshot from 2017-10-11 09-16-48](https://user-images.githubusercontent.com/642621/31443435-72e1622c-ae67-11e7-80d0-445f5dcb87fe.png)

This error is seen when the Jenkins log when the pod starts up:

```
WARNING: Failed to load /var/lib/jenkins/hudson.tasks.Maven.xml
java.io.IOException: Unable to read /var/lib/jenkins/hudson.tasks.Maven.xml
```

[jenkins.log](https://github.com/openshiftio/openshift.io/files/1375741/jenkins.log)

**Comment by ibuziuk** [comment]
Look like a duplicate of https://github.com/openshiftio/openshift.io/issues/1068

**Comment by ldimaggi** [comment]
![screenshot from 2017-10-11 11-40-20](https://user-images.githubusercontent.com/642621/31451030-fdbe53f8-ae78-11e7-91f4-78565e4c02fe.png)

**Comment by ldimaggi** [comment]
Closing as no longer reproducible.
