### ISSUE TITLE
Update e2e test to run with new application design

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#1114]
# Description
To follow up on https://github.com/openshiftio/openshift.io/issues/966 we need to revisit e2e test and Forge API test to run with the new wizard.

# Acceptance Criteria
- [ ] update fabric8-test e2e space creation test
- [ ] update fabric8-test e2e quickstart test
- [ ] update fabric8-test e2e import wizard test
- [ ] update API test quickstart test
- [ ] update API test import wizard test

cc @ldimaggi @rgarg1 I'll need you as reviewer.

**Comment by qodfathr** [comment]
This was targeted for Sprint 140. Status?

**Comment by corinnekrych** [comment]
let me close this one. @ldimaggi did update the test long ago (using another issue I think)
