### ISSUE TITLE
Cannot open a space when username is an email address

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#1116]
working locally with my username being my email address, I can create a space but cannot open it: `/xcoulon%40redhat.com/test` not found. Also, once created, it does not appear in the `recent spaces` card of my home page. For that latter case, the request is sent to `http://localhost:8080/api/namedspaces/xcoulon@redhat.com?page[limit]=5` which returns a `404 Not Found` response.

Also, the server's log contain the following line:

`level=error msg="Fail to locate Keycloak identity for user" file=".../fabric8-services/fabric8-wit/controller/namedspaces.go" func="github.com/fabric8-services/fabric8-wit/controller.loadKeyCloakIdentityByUserName" identity_id=e242c28e-d764-491d-a797-0a92a5210e54 line=105 pid=52418 pkg=controller req_headers=map[Referer:[http://localhost:3000/_home] Accept-Encoding:[gzip, deflate, br] Connection:[keep-alive] Origin:[http://localhost:3000] Accept:[application/json, text/plain, */*] Authorization:***** Dnt:[1] User-Agent:[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36] Content-Type:[application/json] Accept-Language:[en-US,en;q=0.8,fr;q=0.6]] req_id=0ITg0a9olt-19 req_params=map[page[limit]:[10] userName:[xcoulon@redhat.com]] username="xcoulon@redhat.com"`

**Comment by xcoulon** [comment]
Also opened here: https://github.com/fabric8-services/fabric8-wit/issues/1707

**Comment by joshuawilson** [comment]
@xcoulon I can see how this could be fixed in just the UI, but you posted it in -wit too. Do you plan on fixing this or see where it can be fixed in the backend?

**Comment by joshuawilson** [comment]
@xcoulon what is your intent with this issue?

**Comment by joshuawilson** [comment]
@alexeykazakov I thought was had a solution in place for this, do you remember this issue?

**Comment by alexeykazakov** [comment]
Username has nothing to do with this issue. It was a problem of local dev enthronement configuration in WIT on Mac. See details here - https://github.com/fabric8-services/fabric8-wit/issues/1707
I believe we can close this issue.
