### ISSUE TITLE
After completing the wizard, the wizard get started menu should close and go back to the dashboard (or somewhere)

### ISSUE THREAD

**Issue by harrymower** [openshiftio/openshift.io#112]
![image](https://cloud.githubusercontent.com/assets/1022371/25556912/3409c888-2cd4-11e7-8cf7-80309bd1089b.png)

**Comment by joshuawilson** [comment]
@catrobson Can you look at updating the flow for this?

**Comment by catrobson** [comment]
Yes, it is supposed to bring you to the space dashboard after completing the QuickStart so you can see your project building.  It is also supposed to do some other things that are currently not implemented, like add your new codebase automatically.  I'll capture a workflow with all of the expected interactions when I get in front of a laptop tonight so we have that documented.  The screen flow landing on space dashboard can already be seen in the designs - https://redhat.invisionapp.com/m/share/Z9B9OWP5S#/228462993

**Comment by joshuawilson** [comment]
@mitchharpur can you take this on when @catrobson completes the designs and flow.

**Comment by catrobson** [comment]
Flow:
![gettingstarted](https://cloud.githubusercontent.com/assets/3739227/25561212/9c71a138-2d34-11e7-9e7f-73deca98cf10.png)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1361
