### ISSUE TITLE
Notification email threading 'broken' in Gmail

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1121]
The current email layout combined with gmails 'remove things we've seen before' is causing some odd looking results..

![screenshot from 2017-10-12 12-45-19](https://user-images.githubusercontent.com/132158/31492466-756bfcf2-af4b-11e7-9d58-211d6511d189.png)

@mindreeper2420 Something you can look at?

**Comment by mindreeper2420** [comment]
@aslakknutsen would it be possible to have an option in all of the emails to view them as a web page? That might help with this issue. I'm not sure how much time it will take (as I need to research Gmail threading) to lock this down for all email clients.

**Comment by aslakknutsen** [comment]
@mindreeper2420 You can just as well 'un thread/un hide' them in the client.

**Comment by qodfathr** [comment]
Status on this? Some threads look fine in Gmail, but some make it look like the entire body of the message is the old, quoted portion. See the ... in the image below? That's the most recent email in the thread, and it should be showing the body of the message.

![image](https://user-images.githubusercontent.com/16322190/35242419-834fe298-ff87-11e7-923f-7d76d658beff.png)

**Comment by mindreeper2420** [comment]
From what I've seen, Google tends to do this for a lot of emails in my account - whether from OpenShift.io or just replies within Gmail. I'm not sure, at this point, if this is a Gmail application issue, or something from our service.

**Comment by joshuawilson** [comment]
@aslakknutsen is this something you can fix or should we close his?

**Comment by muruGanesan** [comment]
@aslakknutsen, 
Could please let us know the status of this issue? i.e. is it still appears as you mentioned?

**Comment by joshuawilson** [comment]
I think we should involve @alexeykazakov in this.

**Comment by alexeykazakov** [comment]
We need some help from UX/UI experts here to fix the email templates - https://github.com/fabric8-services/fabric8-notification/tree/master/template

**Comment by joshuawilson** [comment]
ok, we can work together on it

**Comment by alexeykazakov** [comment]
Duplicates https://github.com/openshiftio/openshift.io/issues/3385

**Comment by alexeykazakov** [comment]
@joshuawilson instead of replicating multiple issues with broken html template rendering in notification service we can just ask the UI team to fix it once and in one place?

**Comment by joshuawilson** [comment]
Each bug points to a different issue in the template. If you want to close them all then they should all be listed in a story to fix them.

**Comment by stevengutz** [comment]
@Veethika this is assigned to you and is very old.  Are we going to fix this so we can get it off our plate?

**Comment by Veethika** [comment]
@stevengutz I think we should close this. There's no clarity yet if this there's a problem with Gmail or in our layout. Unassigning myself.
