### ISSUE TITLE
Logged in user is able to view in another user's space - attempts to create projects in another users space hang - should raise an error

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1122]
While debugging a failed test - I was able to access a different user's space:

![screenshot from 2017-10-12 15-56-19](https://user-images.githubusercontent.com/642621/31516536-e719d2d2-af66-11e7-8c32-0e2a10c40578.png)

Impacts #2133

**Comment by joshuawilson** [comment]
Accessing another space is not really a bug. There doesn't appear to be a security risk, it is just some bad UI that needs cleaning up.

**Comment by ldimaggi** [comment]
I will need the other space's owner (James) to do this - but if he sets a project's associated github repo to private - should I be able to see it through OSIO?

**Comment by joshuawilson** [comment]
I don't think we support private repos yet, so it shouldn't work at all.

**Comment by joshuawilson** [comment]
@ldimaggi can you confirm that you can or can NOT actually create projects in another users space?

**Comment by ldimaggi** [comment]
What I am seeing is that if user #1 attempts to create a project in user #2's space, the 'add to space' dialog hangs. It would better if we could return an error to the user:

![screenshot from 2017-10-25 11-14-51](https://user-images.githubusercontent.com/642621/32006900-fb0b2ffc-b975-11e7-97cb-383884b603a2.png)

**Comment by joshuawilson** [comment]
So the UI looks like you are allowed until you actually try it and then it fails?

**Comment by ldimaggi** [comment]
The wizard stops at the loading screen shown in the screenshot^.  No error is raised to the user - but - the user can press cancel. It really should put up an error message.

**Comment by qodfathr** [comment]
When I go to someone else's Space and Add to Space, I can walk through the wizard and it actually creates a new repo in *my* GitHub account. "Finishing" the wizard seems to try and run it again, during which it hangs.

The "Add to Space" buttons either need to be disabled or removed when I'm in another space for which I am not a collaborator. (And given that the collaboration model is pretty light right now and we are in need of the Permissions model, I'd argue in favor of not even letting Collaborators to Add to Spaces they do not own.) Furthermore, the APIs behind the Add to Space button should immediately return an error if this situation is attempted programmatically.

**Comment by qodfathr** [comment]
Okay, let's just remove the 'Add to Space' button if you are not the Space owner, and we'll better address what should and what should not be possible in a future train (it's going to require #2068 anyway).

**Comment by jiekang** [comment]
@andrewazores Maybe you can assist Chris with pushing through this.

**Comment by andrewazores** [comment]
@jiekang yup, I'm already reviewing his PR on this issue
