### ISSUE TITLE
On a single screen, showing up duplicate panels for Pipeline, Codebase views

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1124]
Few clicks on 'Codebases' , 'Pipelines' (repeatedly) would add (repeatedly) UI panels for 'Codebases and 'Pipelines' resulting in duplicate content / panels on a single UI screen.

**Comment by joshuawilson** [comment]
Is this a duplicate of https://github.com/openshiftio/openshift.io/issues/1128 or something different. I don't know how to reproduce created duplicated tabs under `Create`.

**Comment by krishnapaparaju** [comment]
duplicate panels of Pipelines and CodeBase getting added vertically to the current screen with each click on either 'pipelines' / 'Codebases' links

**Comment by joshuawilson** [comment]
Is this a duplicate of #1128 or something different.

**Comment by krishnapaparaju** [comment]
Its different from #1128.  I am not able to reproduce this problem anymore..
