### ISSUE TITLE
Che: Clicking on preview link in run tab does not reflect the latest change

### ISSUE THREAD

**Issue by sthaha** [openshiftio/openshift.io#1125]
Che version
----------------
```
Version :
Revision :fac865a74eebefc0
Build Time :2017-09-29 08:54:44
```

### Setup ###
1. Create a Vert.x Helloworld project 
1. Open the project in `che`
1. Make changes to the `index.html` under `src/main/resources/webroot/`
1. Run 
1. Click on the preview link (opens a new tab)

### Test ###
1. Modify the `index.html` file (save)
1. Wait for the `run` to finish
1. Click on preview link which opens a new tab but ...

Actual output
-----------------
The preview shows the a version older than the current
Refresh the page manually and you would see the current version

Expected Output:
----------------------
The preview should reflect the changes made to the html file

**Comment by l0rd** [comment]
@sthaha it looks like a problem of cache that doesn't get invalidated. It's not related to Che. You can verify that you get the same result even without Che. For example you get the same result running the vertx booster from a shell:

```bash
# In a first shell
git clone git@github.com:openshiftio-vertx-boosters/vertx-http-booster.git
cd vertx-http-booster/
mvn vertx:run

# In a second shell
open http://localhost:8080 
cd vertx-http-booster/
echo "THIS IS A TEST" >> src/main/resources/webroot/index.html
open http://localhost:8080 # <==== Changes won't show up if you don't refresh your browser
```

@cescoffier it may be a problem of the vert.x booster?

**Comment by sthaha** [comment]
@l0rd thanks for digging deeper. http-cache didn't cross my mind. 

I agree that setting cache-control for index.html could be confusing to the user.

**Comment by sthaha** [comment]
@l0rd Please feel free to close the bug since this isn't a che issue per se.
