### ISSUE TITLE
pipeline: clicking stage preview link opens an older version

### ISSUE THREAD

**Issue by sthaha** [openshiftio/openshift.io#1126]
Openshift.io version
--------------------------
```
Build #703
Time stamp 2017-10-13T17:45:47+00:00
```

### Setup ###
1. Create a Vert.x Helloworld project, choose `build -> roll to stage -> approve -> run` pipeline
1. Wait for the pipeline (build-1) to finish (waiting approval)
1. Click on the `Stage - Preview link`
1. Abort pushing to `Run`

1. Open the project in `che`

### Test ###
1. Make some changes say: to the `index.html` under `src/main/resources/webroot/`
1. git commit and push

1. In the pipelines tab - wait for Build-2 to trigger and waiting for approval
1. Click on the preview link (opens a new tab)

Actual output
-----------------
The preview shows the a version older than the current
Refresh the page manually and you would see the current version

Expected Output:
----------------------
The preview should reflect the changes made in the commit

**Comment by alexeykazakov** [comment]
Pipeline actually shows builds. So, when you the staging step gets green it means it has been built but it still takes some time to deploy it to stage. The same for "Run"/prod.
@jstrachan please correct me if it has changed.

@sthaha, so, if you wait for successful deployment then it should work.

@jstrachan @rawlingsj, It's actually confusing. It would be useful if we have something in pipelines on OSIO to reflect the status of deployments. Not sure if it has been fixed or if we already have an issue opened for that.

**Comment by sthaha** [comment]
@alexeykazakov thanks, your explanation matches my observation and I agree that the UI seems counter intuitive. It says "Rollout to stage" and has a ✔ which IMHO indicates the rollout to stage is successful and at this point I would expect to see the new version deployed to stage.

**Comment by rafabene** [comment]
This issue is annoying. Is there a way to just complete the stage if the deployment completes?

**Comment by chmouel** [comment]
should it just go to the fabric8-ui backlog instead of build backlog?

**Comment by alexeykazakov** [comment]
There is no fabric8-ui backlog. Who is responsible for pipeline front end? Build-cd team, right? If it should be fixed in fabric8-ui component then the build-cd team is responsible for fixing it in fabric8-ui.

**Comment by qodfathr** [comment]
Although related to #508, I actual think, based upon my experience, that this is a separate issue. I believe that I have often observed that, after having deployed an update to Stage, when I view the application (even after the rolling update is complete) I see the old version of the application.

A refresh fixes the problem, so this feels like a caching issue.

I do not know if it's a problem with the Quickstart itself (maybe it has some odd caching directives) or OSO. But I don't think this is an OSIO issue.

Thoughts?

**Comment by piyush1594** [comment]
@sthaha I tried to reproduce it. Setup phase goes perfectly. In the test phase when I commit and push to origin/master from che. There is no second pipeline that comes up for me.

**Comment by sthaha** [comment]
@piyush1594 
> In the test phase when I commit and push to origin/master from che. 

that seems like another unrelated bug if this is the case. Changes to the project should result in a build. 

Could you please confirm that you did abort the first build?

**Comment by piyush1594** [comment]
Yes, I abort the first build. @sthaha

**Comment by piyush1594** [comment]
@sthaha I tried it again. Its not triggering PR on commit and push

**Comment by piyush1594** [comment]
@sthaha I tried to reproduce this and it is working fine. Not able to reproduce this.

**Comment by sthaha** [comment]
Closing the issue based on https://github.com/openshiftio/openshift.io/issues/1126#issuecomment-408790258
