### ISSUE TITLE
Clicking on "Plan" tab followed by "Create"  and then back to "Plan" creates duplicate tabs

### ISSUE THREAD

**Issue by sthaha** [openshiftio/openshift.io#1128]
Version Info
----------------
```
Build #703
Time stamp 2017-10-13T17:45:47+00:00
```

![osio-multiple-tabs-bug](https://user-images.githubusercontent.com/3005132/31600057-5dfa2012-b298-11e7-9491-f23e1aa85a58.gif)

**Comment by joshuawilson** [comment]
It works for me. Can you try in incognito mode.

**Comment by joshuawilson** [comment]
OK, I can reproduce it now. 
Go to a space, go to settings, go to any other tab.
@dlabrecq can you please take a look.

**Comment by dlabrecq** [comment]
It was difficult to reproduce at first, but now I cannot stop it. Just clicking on the settings tab is enough.

**Comment by dlabrecq** [comment]
Fixed by https://github.com/fabric8-ui/fabric8-ui/pull/2116

**Comment by sthaha** [comment]
Can't reproduce this in  `Build #709 Time stamp 2017-10-16T20:25:22+00:00` so marking it as fixed.
