### ISSUE TITLE
Gather some data points for the Freesia Release Retrospective

### ISSUE THREAD

**Issue by RanjithRV** [openshiftio/openshift.io#1130]
Request for data related to number of commits to pre-prod and prod along with any other data that   might us to have a very focused and objective retrospective. 

List of failures that slowed us down such as pipelines failing or some commit breaking the production etc. We know that we are not there yet from a CI/CD point of view and hoping this will help us to realise the length of the journey to have an well optimised CI/CD working model & supporting tech.

**Comment by joshuawilson** [comment]
@RanjithRV you can also see that we closed 149 issues at https://github.com/openshiftio/openshift.io/milestone/14 
I'm not sure how to count how many issues were logged during the sprint without counting them.

**Comment by RanjithRV** [comment]
Closing this ticket as this information is no longer needed due to active triaging of issues and active monitoring via Zabbix, Kibana and PCP.
