### ISSUE TITLE
Improve summary screen

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#1136]
The last screen of the wizard is not very intuitive.

There''s no label that indicates what the following information means and how it's useful to the users.

![screenshot 2017-10-16 23 05 12](https://user-images.githubusercontent.com/30131/31641904-9fe6d24e-b2c6-11e7-9fb4-730f72905e33.png)

**Comment by joshuawilson** [comment]
@catrobson can you please have someone look into this

**Comment by catrobson** [comment]
https://github.com/fabric8-ui/fabric8-ux/issues/696 . We'll be looking at this information as part of this story.

**Comment by arunkumars08** [comment]
@catrobson Regarding summary screen ux for the wizard, I see this story (https://github.com/fabric8-ui/fabric8-ux/issues/696) has been closed already. Just to be on the same page, we are going with this design https://redhat.invisionapp.com/share/UME00N9CD , right?

**Comment by catrobson** [comment]
Correct.  My apologies, I had shared that with Corinne in Mattermost.  I'll keep you informed on any changes in the future.  Thanks!

**Comment by arunkumars08** [comment]
Sure no problem. @catrobson Thanks!

**Comment by joshuawilson** [comment]
This is being redesigned. The new design will cover this.
