### ISSUE TITLE
WORKSHOP CRITICAL: CHE doesn't create Run and Debug commands for Vert.x and SpringBoot projects

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#1137]
CHE doesn't have the "run" and "debug" commands.

It only allows the user to add a new one.

![screenshot 2017-10-17 00 13 45](https://user-images.githubusercontent.com/30131/31643567-1018ddb0-b2d0-11e7-93dc-6ca07079820a.png)

**Comment by ibuziuk** [comment]
@joshuawilson it looks like with the latest UI changes the UI is not passing correct stack id to wit: all workspaces are created against `java-centos` stack

**Comment by ibuziuk** [comment]
According to the che-starter logs all the workspaces are created against `java-centos` stack 

> {"time":"2017-10-17T16:08:02.823+00:00","msg":"Stack: java-centos","logger":"io.fabric8.che.starter.client.WorkspaceClient","thread":"qtp1738236591-78","level":"INFO","HOSTNAME":"che-starter-32-4ml30","req_id":"56ee7d2d-4951-43d2-a03f-44fd2fd01c8a","identity_id":"9956255a-776f-4c8a-950e-878dc54f871a"}

**Comment by corinnekrych** [comment]
@ibuziuk I confirm we don't pass stackId for quickstart. Let me fix it on f8-ui
