### ISSUE TITLE
Workshop critical: SpringBoot quickstart doesn't show correctly

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#1138]
If I don't use filters in the wizard, I can't scroll down the options and I barely can see the SpringBoot option.

![screenshot 2017-10-17 00 25 20](https://user-images.githubusercontent.com/30131/31643851-ad69729a-b2d1-11e7-9206-c4e5f98d50f0.png)

**Comment by joshuawilson** [comment]
@corinnekrych please take a look

**Comment by corinnekrych** [comment]
@dlabrecq I had `overflow: auto` to `.pfng-wizard-position-override` it sorts out the display. is it something to fix on patternfly-ng? or it possible to override it in f8-ui?
![screenshot 2017-10-17 09 15 34_preview](https://user-images.githubusercontent.com/1395710/31651482-1faff3fc-b31c-11e7-9784-1fb40a33b430.png)

cc @edewit

**Comment by dlabrecq** [comment]
The space wizard seems to be overriding a lot of CSS, but you really don't need to. Please have a look at the wizard example for patternfly-ng. We're defining selectors to set the height and overflow like so:

    this.wizardConfig = {
      title: 'Wizard Title',
      sidebarStyleClass: 'example-wizard-sidebar',
      stepStyleClass: 'example-wizard-step'
    } as WizardConfig;

This outputs selectors on these tags:

<div class="wizard-pf-sidebar example-wizard-sidebar" >
and
<div class="wizard-pf-main example-wizard-step">

The CSS used in this particular example is as follows.

.example-wizard-sidebar {
    height: 500px;
    max-height: 500px;
    overflow-y: auto;
}
.example-wizard-step {
    height: 500px;
    max-height: 500px;
    overflow-y: auto;
}

**Comment by corinnekrych** [comment]
`Encapsulation.None` at component level was the missing instruction to make it work.
