### ISSUE TITLE
Adding collaborators does not find any users

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#1140]
I'm testing adding and editing Collaborators to a space for an article but am unable to add any Collaborators at all. The search field seems unresponsive and displays nobody. I tried this with my team mates (searched for "Preeti" and "Robert" and even "Burr" for the name search, then tried username "rkratky" as an alternative). The result remains as displayed in the screenshot no matter what I search for.

![collab_error](https://user-images.githubusercontent.com/926572/31649189-f1fbaf08-b354-11e7-9bb9-367959080c97.png)

**Comment by alexeykazakov** [comment]
This issue was reported in https://github.com/openshiftio/openshift.io/issues/1134 (see the comments)

**Comment by joshuawilson** [comment]
@dlabrecq are you ok, to take this on this week?

**Comment by dlabrecq** [comment]
Sure. I'll start digging...

**Comment by dlabrecq** [comment]
FYI, it appears that the searchFilterText property of angular-2-dropdown-multiselect was removed at some point. It's not available for v1.6.0; however, it works if I revert back to v1.1.0.

**Comment by dlabrecq** [comment]
Fixed by: https://github.com/fabric8-ui/fabric8-ui/pull/2150
