### ISSUE TITLE
Incorrect and odd Space creation error when logging out

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#1141]
I tried this twice and both times I get an incorrect and unnecessary error about my space not being created.

**How to reproduce error:**
1. Create a new space
2. In the new space, try to add a collaborator (doesn't work)
3. Click your name at top right corner of screen and then Log out
4. Logs out but displays weird message about recently created space not being created, but this is not correct because the space was created and I'm using it and can see it when I log in again.

![failed](https://user-images.githubusercontent.com/926572/31649510-9586c594-b356-11e7-9b57-15766ff58da8.png)

**Comment by qodfathr** [comment]
Step # 2 worked for me, but I still got the error all the same.

**Comment by jiekang** [comment]
This should be resolved. Feel free to re-open if the issue persists

https://github.com/openshiftio/openshift.io/issues/2206
https://github.com/fabric8-ui/fabric8-ui/pull/2581
