### ISSUE TITLE
Figure out the delta for incremental ingest of packages into OSIO platform

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1142]
OSIO analytics platform relies on providing accurate information to OSIO users and able to incrementally ingest the changes to package attributes and newer packages. Need a dashboard to display the newer packages, package attributes YET / required to be ingested. This would require background jobs to be run (maybe once in a week) to display information about incremental data refresh.

@msrb

**Comment by miteshvp** [comment]
We inrementally update graph.
