### ISSUE TITLE
Bug - Stack report Independent Portal doesn't load properly in Edge Browser

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#1143]
This happens when the stack report that is generated via Dev Studio IDE and viewed via IDE Browser (When Edge browser appears as the default browser).

**Comment by samuzzal-choudhury** [comment]
The merged PR https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/21 fixes this. Closing this bug. Please reopen if you think otherwise.
