### ISSUE TITLE
Bug: Show the unknown license count for unique unknown licenses in the stack report UI

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#1147]
Currently, we display just the count of total unknown licenses ignoring the fact that a license can be unknown for two components, but at stack level this has to be taken only once to show the count.

- [ ] Fix in recommender UI
- [ ] Fix in stack report UI portal

**Comment by miteshvp** [comment]
@invincibleJai @jyasveer - Is anything happening on this one? I am assuming we fixed it when Jai was handling UI part for licensing. If that is the case, can you please update this issue accordingly?

**Comment by invincibleJai** [comment]
count thing i fixed as in https://github.com/openshiftio/openshift.io/issues/1449 @jyasveer @miteshvp

**Comment by jyasveer** [comment]
@invincibleJai @miteshvp this issue talks about the license count for each component but not the analyzed component count. I guess i have to fix it.

**Comment by invincibleJai** [comment]
@jyasveer am not sure what this issue targets , let's connect once. Coz even in licence card i did some work, not sure if this exists now

**Comment by krishnapaparaju** [comment]
@jyasveer would the new UX (for the stack report)   take care of this issue ?

**Comment by krishnapaparaju** [comment]
@jyasveer please take care of this issue as part of UX revamp , due by end of the current sprint # 143.

**Comment by sunilk747** [comment]
Closing this as it is handled as part of new UI.
