### ISSUE TITLE
Task: Update the existing user-intent end point in server to serve manual tagging requests

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#1148]
### List of Tasks:-
- [x] Add a get logic to get the user data
- [x] Update the post logic to serve manual tagging and also adding intent from the recommender UI
- [x] Add a new storage adapter in the worker for manual tagging
- [x] Update the latest commit hash of worker in the server docker file
- [x] Fix review comments if any and see that the PR is merged.
- [x] Update the saas-git repo with the latest commits from server and worker

### List of PRs for this task:-
- https://github.com/fabric8-analytics/fabric8-analytics-server/pull/167
- https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/402

### Will update the structure of the get and post request here shortly.

**Comment by samuzzal-choudhury** [comment]
All tasks have been completed for this. Hence, closing
