### ISSUE TITLE
Deploy Che 6 on OSIO

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#1150]
## Description
A lot of work has been done around the SPI in the new version of Che, usually called Che 6. 
This version will have impacts how Che is running on OSIO. 

The goal of this epic is to have multi-tenant Che on OSIO running the new version with the SPI coming with Che 6.

### Linked issues
https://github.com/eclipse/che/issues/5098

**Comment by l0rd** [comment]
rh-che issue with more details about the single tasks needed to achieve this epic https://github.com/redhat-developer/rh-che/issues/448.

**Comment by riuvshin** [comment]
AFAIK CHE6 is deployed to OSIO more info: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1351

**Comment by l0rd** [comment]
@riuvshin that's technically right. But Che 5 is still running and serving most of osio users. We have currently activated Che 6 for osio-che team engineers only.

**Comment by riuvshin** [comment]
@l0rd yeah, thanks that was just an update. not all users are migrated to che6 
but it is deployed.

**Comment by slemeur** [comment]
Closing as it has been done.
