### ISSUE TITLE
UX Enhancement: Back from new WI page should be Planner view

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#1152]
1. Click **Plan** tab for Planner view
2. Click the **+ Create** button on the right side of the page to create a new WI
3. Work Item type page displays. If you changed your mind here and just want to go back to seeing the Work Items list, no cancel button available so instead, I press the back button for my browser.
4. Unexpectedly, I'm back at the Space Dashboard view (same result as clicking **Analyze*).

This seems like non-intuitive UX so I would propose the back button should take us back to the Planner view instead of changing your mind and returning to a completely separate part of OSIO.

**Comment by qodfathr** [comment]
A cancel button is now available, but back shouldn't behave the way it does. (For me, Back just leaves me on the same Work Item Type screen.)

FWIW, I believe this button is going away. Is that correct, @michaelkleinhenz ?

**Comment by michaelkleinhenz** [comment]
@qodfathr yes, this will go away when the "Create and Open" button is working.

**Comment by qodfathr** [comment]
Closed due to removal.
