### ISSUE TITLE
[Enhancement]Provide validation for project name when typing

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1156]
When creating a new application, we cna provide an OpenShift Project name which is "invalid", there is an error message only after clicking next (which is not even emphasizing which field exactly)

no error:
![image](https://user-images.githubusercontent.com/1105127/31772497-2e40d33a-b4e0-11e7-8143-23df24a55a2f.png)

error after clicking on next
![image](https://user-images.githubusercontent.com/1105127/31772489-27515c3e-b4e0-11e7-805e-99900602d474.png)

**Comment by apupier** [comment]
it would be nice to provide the exact regexp used for valid name seems that it doesn't like capital letters:
![image](https://user-images.githubusercontent.com/1105127/31772544-5a0f5d74-b4e0-11e7-8c33-dd8cdb9ab7bd.png)

Considering "capital letters" as "special characters" is not very user friendly. Maybe improving the error message in a first time will help.

**Comment by joshuawilson** [comment]
@corinnekrych when you get a chance can you please take a look.
