### ISSUE TITLE
generated OpenShift project name when "Space" contains spaces is invalid

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1157]
create a Space named with some spaces like "second space of my life"
try to create a new Application based on template, it will generate an OpenShift project name with underscores instead of space:
![image](https://user-images.githubusercontent.com/1105127/31773003-ab09443c-b4e1-11e7-95b7-5fc93f385651.png)

after clicking next it is reported as invalid:
![image](https://user-images.githubusercontent.com/1105127/31773019-b61a4fba-b4e1-11e7-81ce-baf0fd6fd398.png)

**Comment by joshuawilson** [comment]
@corinnekrych is this fixed?

**Comment by corinnekrych** [comment]
yes `_` are removed as they are not authorized for k8s namespace.

**Comment by apupier** [comment]
> yes _ are removed as they are not authorized for k8s namespace.

they are now replaced by what?

**Comment by corinnekrych** [comment]
Default name for space "My own space with spaces" => `myownspacewithspaces`
