### ISSUE TITLE
[enhancement] provide by default a "light" theme for OpenShift Eclipse Che

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1161]
it would be best to use the same theme than the other part of of openshift.io but at least avoid to have switching between a dark and light theme will be far more user-friendly

**Comment by ibuziuk** [comment]
this is smth. that should be discussed with PMs before prioritization @slemeur @bmicklea

**Comment by bmicklea** [comment]
I generally agree, but the light theme used to be a little rough around the edges. @slemeur - thoughts?

**Comment by ibuziuk** [comment]
Closing as outdated. Black theme is supposed to be a default for Che 6 / Che 7 on che.openshift.io
