### ISSUE TITLE
[enhancement][che]Provide more space for commiter fields in Preferences dialog

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1162]
![image](https://user-images.githubusercontent.com/1105127/31774271-8ebbf280-b4e5-11e7-9c64-9b8ec28103f9.png)
there is quite a lot of space available and it will avoid to have cropped email or names

**Comment by ibuziuk** [comment]
@apupier could you please create an upstream issue for this, since it is pure IDE improvement - https://github.com/eclipse/che ?

**Comment by apupier** [comment]
> @apupier could you please create an upstream issue for this, since it is pure IDE improvement - https://github.com/eclipse/che ?

done https://github.com/eclipse/che/issues/6923

**Comment by qodfathr** [comment]
Closing, as this is now being tracked in upstream.
