### ISSUE TITLE
English text across 'stack report' needs to be revamped

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1167]
UX of stack report needs to be revamped, get reviewed.  eg: words like 'conflict with in a component' does not make sense.

**Comment by jyasveer** [comment]
@krishnapaparaju 
This are changes in the UI for the license module. Below is the deck showing the screenshots of all license analysis scenarios. Please suggest some changes if you find any
https://docs.google.com/presentation/d/1DiMQsXQxPze9Pl8-341r5VhP8k2_HK4LMyPi6JOmKXk/edit#slide=id.g28cfca7043_0_17

**Comment by samuzzal-choudhury** [comment]
@krishnapaparaju The UX revamp is in-progress which should address this issue. We already have a work item for this purpose https://github.com/openshiftio/openshift.io/issues/1277. Closing this to track the UX revamp progress in the [sprint 140 work item](https://github.com/openshiftio/openshift.io/issues/1277).
