### ISSUE TITLE
Stack report does not load completely

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1168]
Stack report does not load completely, hour glass does not go away.

**Comment by invincibleJai** [comment]
fix are in place 
- https://github.com/fabric8-ui/fabric8-recommender/pull/365
- https://github.com/fabric8-ui/fabric8-ui/pull/2158

@jyasveer thanks for help

**Comment by krishnapaparaju** [comment]
Stack report now shows up as expected. Closing this...
