### ISSUE TITLE
Footer text getting appended every time stack report opens up

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1169]
The footer text 'Report title on Application - *' at the bottom of the stack report screen is getting appended after every time stack report  is opened. Opening stack report 4 times, 4 times the footer text is getting appended.

**Comment by invincibleJai** [comment]
fix are in place 
- https://github.com/fabric8-ui/fabric8-recommender/pull/365
- https://github.com/fabric8-ui/fabric8-ui/pull/2158

@jyasveer thanks for help

**Comment by samuzzal-choudhury** [comment]
@krishnapaparaju this fixes for this has been on prod. Closing this issue. Please reopen if you think otherwise.
