### ISSUE TITLE
[Che]Only "null" written in Download outputs log file

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1173]
when creating a workspace, there is alittle notification window at the top saying "starting workspace", there is a "Download outputs" links, 
![image](https://user-images.githubusercontent.com/1105127/31810417-04dacb1c-b57c-11e7-9a54-8e2d25d678ba.png)

When downloaded I got only "null" written in the log file.

**Comment by ibuziuk** [comment]
Duplicate - https://github.com/openshiftio/openshift.io/issues/513
