### ISSUE TITLE
Overlapping of text in "Summary" when importing existing projects

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1175]
![image](https://user-images.githubusercontent.com/1105127/31811070-78d65926-b57e-11e7-9050-5b632289ea34.png)

**Comment by joshuawilson** [comment]
@mindreeper2420 this looks like another styles issue, you can work with @edewit for implementation details.

**Comment by mindreeper2420** [comment]
@joshuawilson @edewit it looks to be a truncation/constraint issue. All of this was done while I was on leave, so it will take time to sort through it all.

**Comment by edewit** [comment]
@mindreeper2420 html for this screen is here: https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/forge-wizard/import-pages/step5/review-step.component.html guess quick fix would be to put the github url above the other information.

**Comment by mindreeper2420** [comment]
@edewit Why the use of a list view there? It seems that a table would be more suitable for this instance?

**Comment by edewit** [comment]
@mindreeper2420 don't know you'll have to ask @corinnekrych she made it like this

**Comment by corinnekrych** [comment]
@edewit @mindreeper2420 for this screen we have a UX ticket to revisit it: https://github.com/openshiftio/openshift.io/issues/1136

**Comment by qodfathr** [comment]
Fixed.
