### ISSUE TITLE
"Unable to load preferences after creating a workspace

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1176]
![image](https://user-images.githubusercontent.com/1105127/31811144-b6d9ea94-b57e-11e7-94ce-02b16cb7eed9.png)

I already created for another codebase.
Fo rthis one, I imported the code from https://github.com/apupier/quickstarts and then click on "create workspace in the "Codebases" window

**Comment by apupier** [comment]
doing F5 is providign the same error

doing Ctrl+F5 is opening the workspace correctly

**Comment by joshuawilson** [comment]
can you please try this again and verify

**Comment by ibuziuk** [comment]
version of che ?

**Comment by apupier** [comment]
> version of che ?

I think it is still the same that I have currently as I think that i didn't reset the environment since I reported it so Che 2.0.37

**Comment by joshuawilson** [comment]
@ibuziuk does the import wizard add the needed che file? I haven't looked in a while.

**Comment by apupier** [comment]
> can you please try this again and verify

I don't reproduce anymore
