### ISSUE TITLE
[Codebases]Worskpaces cells vanishes when changing the sort

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1177]
create several codecases
then in Codebases page, try to change the sort order from Name to last commit for instance, if one line is moving, we don't have anymore the Workspaces information:
![image](https://user-images.githubusercontent.com/1105127/31815769-081e3298-b58e-11e7-9f9e-96ae2107548f.png)
![image](https://user-images.githubusercontent.com/1105127/31815776-0e2d4638-b58e-11e7-8bcd-fd3a81d40667.png)
![image](https://user-images.githubusercontent.com/1105127/31815788-165ae1a8-b58e-11e7-91c8-20d9581ad64c.png)

**Comment by joshuawilson** [comment]
related to https://github.com/openshiftio/openshift.io/issues/198

**Comment by qodfathr** [comment]
Fixed
