### ISSUE TITLE
[codebases]the popup dialog to add a codebase from codebases is a little dialog at the top-right

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1180]
![image](https://user-images.githubusercontent.com/1105127/31815996-dbf4b6be-b58e-11e7-921b-2cf0ffb9af92.png)

it would be better to have a centered dialog like all others on the UI that i noticed so far.
Also if GitHub Repository can be wirtten on a single line it would be better

**Comment by joshuawilson** [comment]
cc @mindreeper2420

**Comment by mindreeper2420** [comment]
@joshuawilson I'll be submitting a PR the ngx-widgets for this.

@apupier as the design called for the use of the [Modaless Overlay](http://www.patternfly.org/pattern-library/forms-and-controls/modeless-overlay/), this is something that can be revisited as part of a separate issue. I will just be fixing the placement of it at the bottom of the page.
