### ISSUE TITLE
[codebases]First click on + is always a miss

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1181]
The first time I try to click the + button, a scrollbar appears and then the click finally is not triggered as the cursor is moved outside of the +

see video: https://drive.google.com/open?id=0B-rING_ZzzceT0R2Ml9jd05ueUk

**Comment by joshuawilson** [comment]
@mindreeper2420 can you take a look and see if this is a styles thing. 
@apupier that video made me LOL, thanks for pointing that out.

**Comment by mindreeper2420** [comment]
@joshuawilson it looks like something happened with this PR: https://github.com/fabric8-ui/fabric8-ui/pull/2077. The Add Codebases panel tries to slide out, but does not (causing the scrollbar), and then actually works on the second click.

@dlabrecq any thoughts? I can't fully tell what is happening (the commit is massive), but I do not believe this to be a CSS issue.

**Comment by dlabrecq** [comment]
I don't see the scroll-bar. The slide-out appears at the bottom of the page for me. It's also broken for the ngx-widgets demo. It appears a few .detail-pane styles may be overridden (e.g., top: em(34) is no longer applied).

![screen shot 2017-10-20 at 10 27 31 am](https://user-images.githubusercontent.com/17481322/31825825-694c4544-b581-11e7-867d-45f134991f4d.png)

**Comment by dlabrecq** [comment]
@mindreeper2420 I hard reset my ngx-widgets branch to commit 0669dc5, from Aug 18. The slide-out panel works fine for the ngx-widgets demo. However, when I hard reset to commit 97dc40d, from Sep 8, the slide-out panel is broken. I've confirmed by resetting the commits multiple times, clearing my cache, etc.

The broken commit appears to be related to the LESS conversion? The ngx-widgets version was only recently updated from 1.1.2 to 2.2.3 on 10/13, so it appears to have been broken for a while.

**Comment by joshuawilson** [comment]
@mindreeper2420 were you able to figure this out?

**Comment by mindreeper2420** [comment]
@joshuawilson I'm still catching up from leave, so I'll take a look at ngx-widgets today. A few things changed in there while I was away, so I'll go through the various PRs as well.

**Comment by mindreeper2420** [comment]
@joshuawilson @dlabrecq I've created a PR that addresses this issue. The tooltip was set render off-screen, which caused the misfires, click errors and scrollbars.
