### ISSUE TITLE
Analytic reports not created on prod-preview

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1182]
After the successful completion of a build pipeline on prod-preview - the analytics report is never generated:

![screenshot from 2017-10-20 09-56-57](https://user-images.githubusercontent.com/642621/31825058-f8317160-b57e-11e7-883a-6fca97ec6ebc.png)

**Comment by joshuawilson** [comment]
@ldimaggi can you please verify. Fixes were applied, should have fixed it.

**Comment by ldimaggi** [comment]
Verified - closing - thx!
