### ISSUE TITLE
Can't Create a Space using the max number of characters

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#1183]
When creating a Space through the wizard, the first screen states that Spaces cannot have names longer than 63 characters.
![screen shot 2017-10-20 at 10 51 41 am](https://user-images.githubusercontent.com/4032718/31827331-70d5a7a2-b585-11e7-8617-9e77430d9c8b.png)

When meeting that requirement, the Space fails to create (with no error), but still allows me to select either Quickstart or Import and continue the process (which will result in nothing, as no Space was created).
![screen shot 2017-10-20 at 10 52 26 am](https://user-images.githubusercontent.com/4032718/31827347-7bfbfbf4-b585-11e7-99e4-5a90392b3498.png)

In order to create a Space, I capped the name at 38 characters. Upon doing so, I was met with another error that OpenShift cannot have names over 24 characters.
![screen shot 2017-10-20 at 10 48 59 am](https://user-images.githubusercontent.com/4032718/31827363-8c152592-b585-11e7-8d86-2120be8ce2cc.png)

As the Space name can be up to 63 characters, but the Space cannot be created with that many characters, and OpenShift does not accept more than 24, this is an issue. The first input's maximum characters should be set at a number that allows the entire process to work and complete.

**Comment by joshuawilson** [comment]
cc @corinnekrych @edewit

**Comment by edewit** [comment]
@joshuawilson 63 characters should be the max for "Openshift project name" and this validation is done in the Forge addon.

**Comment by edewit** [comment]
was fixed in this commit: https://github.com/fabric8-launch/launchpad-addon/commit/db71e10b3a15f05078ef0f262afce1053b7ec722

**Comment by joshuawilson** [comment]
So how do we get this fix to production?

**Comment by edewit** [comment]
update this to version 17 https://github.com/fabric8io/fabric8-generator/blob/f3c23c794fc9cf387603e5ea60e46ac51a31755b/pom.xml#L25

**Comment by qodfathr** [comment]
Still not fixed in prod.

**Comment by qodfathr** [comment]
I am going to close this as fixed and I've opened a new issue #1970.
