### ISSUE TITLE
Cannot access Che on prod-preview (403 error)

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1184]
See attached log.

```

2017-10-20 16:49:58,065[nio-8080-exec-7]  [ERROR] [.k.t.p.u.KeycloakUserValidator 227]  - Exception while getting OpenShift token. keycloakToken: Bearer, Exception: {}
--
  | java.io.IOException: Failed access: https://sso.openshift.io/auth/realms/fabric8/broker/openshift-v3/token?token, method: GET, response code: 500, message: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">;
  | <html xmlns="http://www.w3.org/1999/xhtml" class="login-pf">
```

![screenshot from 2017-10-20 13-36-49](https://user-images.githubusercontent.com/642621/31834662-c2fa5b56-b59c-11e7-9c92-b7c8877ed473.png)

[che_log.txt](https://github.com/openshiftio/openshift.io/files/1402827/che_log.txt)

**Comment by joshuawilson** [comment]
This looks like it might be an issue for the SD team. cc @kbsingh @vpavlin

**Comment by alexeykazakov** [comment]
It tries to get an OSO token from sso prod. Not prod-preview. Look at the log: https://sso.openshift.io/auth/realms
Seems to be an issue with che configuration in preview. It should call sso.prod-preview.openshift.io

**Comment by ibuziuk** [comment]
Duplicate - https://github.com/openshiftio/openshift.io/issues/1067
