### ISSUE TITLE
Add Button to Quickly Access Chat on OpenShift.io homepage

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#1185]
Add a 'Chat with us on MatterMost' button to the OpenShift.io homepage that will bring people to chat.openshift.io. There, they can either sign in or sign up to speak with the OpenShift.io team on the #openshiftio channel.

Requirements:
- [ ] UX Design w/flow
- [ ] Code Updates with proper linkage

**Comment by mindreeper2420** [comment]
![osio_chat](https://user-images.githubusercontent.com/4032718/31846293-739d993e-b5d7-11e7-94ca-fcf936437ef6.png)

**Comment by joshuawilson** [comment]
@mindreeper2420 have you discussed adding this feature you really should discuss this with PM ( @qodfathr ) during this sprint. 
And I think that @kbsingh has been planning something around adding chat so you should talk to him too.

**Comment by mindreeper2420** [comment]
@joshuawilson yes, this came from PM. The button, placement, text and flow have already been given the okay. I added this story for tracking against a soon-to-be-filed PR. :-)

**Comment by mindreeper2420** [comment]
**Flow:**
OSIO Homepage chat button--> MatterMost Login w/ registration link
