### ISSUE TITLE
Add component to ngx-forge

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#1186]
# Description
As a developer, I want to have all forge components in ngx-forge.
this is a follow-up of https://github.com/openshiftio/openshift.io/issues/1112 

# Acceptance Criteria
- [ ] move [forge error component](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/forge-wizard/components/forge-errors/forge-errors.component.ts) to ngx-forge
- [ ] move [forge-exception](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/forge-wizard/components/forge-exception/forge-exception.component.ts)
- [ ] move [multiple-selection-list](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/forge-wizard/components/multiple-selection-list/multiple-selection-list.component.ts)
- [ ] move [pipeline-view.component)](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/forge-wizard/components/pipeline-view/pipeline-view.component.ts)
- [ ] move [single-selection-dropdown](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/forge-wizard/components/single-selection-dropdown/single-selection-dropdown.component.ts)
- [ ] reuse la-input in f8-ui
- [ ] move spinner
cc @edewit

**Comment by joshuawilson** [comment]
in master, closing
