### ISSUE TITLE
ngx-forge should have CI?CD integration for fabric8-ui

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#1187]
# Description
As a developer, I want to do PR on ngx-forge and have fabric8-cd run CI. Once merged fabrci8-ui should be updated,

# Acceptance Criteria
- [ ] CI runs unit test on PR
- [ ] CD integration with fabric8-ui

cc @edewit

**Comment by joshuawilson** [comment]
@corinnekrych we are in sprint 139, did you intend to put this in 140? If so, I think it should just go to the backlog.

**Comment by corinnekrych** [comment]
@joshuawilson should we transfer that task to analytics team as they're now working on this lib?

**Comment by joshuawilson** [comment]
@corinnekrych that makes sense. 
@krishnapaparaju moving this to your team.

**Comment by invincibleJai** [comment]
@GeorgeActon yes we have it in our task list https://github.com/openshiftio/openshift.io/issues/2178

**Comment by animuk** [comment]
it's being tracked here https://github.com/openshiftio/openshift.io/issues/2945
