### ISSUE TITLE
It is possible to create a space without selecting a template

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#119]
When a user creates a space, the _Template_ drop-down is empty by default. It should not be possible to create a space without a template.

The field should be marked mandatory to make sure the user selects one. We can also select a template by default.

![create-space-empty-template](https://cloud.githubusercontent.com/assets/3001/25580792/ac93a5fc-2e51-11e7-8e46-fc076868adaf.png)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1363

**Comment by joshuawilson** [comment]
This has been fixed for a while.
