### ISSUE TITLE
Component analysis is slow on the production server, probably because of memory allocation issue

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1191]
We have found that the component analysis is slow on the production server. The SLA threshold is one second, now we got average time just below two seconds for known component and over three seconds for the unknown component! Additionally it seems that the Pod is using all its 512 MiB of memory, but we are unable to figure out what's the original cause of this memory consumption.

Please note that the new version of the server images has been installed today by @msrb, so it might be a consequence of calling a new version.

![component_analysis_sequenced_calls_known_component](https://user-images.githubusercontent.com/4579967/31891512-ee17ac5a-b806-11e7-9e67-c9e837fa6ce7.png)
![component_analysis_sequenced_calls_known_component_min_max_avg_times](https://user-images.githubusercontent.com/4579967/31891513-ee33e8b6-b806-11e7-92e1-7cfd2d8e881e.png)
![component_analysis_sequenced_calls_unknown_component](https://user-images.githubusercontent.com/4579967/31891514-ee4ea48a-b806-11e7-8754-d8b3bda16df7.png)
![component_analysis_sequenced_calls_unknown_component_min_max_avg_times](https://user-images.githubusercontent.com/4579967/31891515-ee6da128-b806-11e7-8807-56ccd102d494.png)

**Comment by tisnik** [comment]
@msrb @fridex @samuzzal-choudhury FYI ^^^

**Comment by fridex** [comment]
As discussed in the office, we could expose a debug endpoint and try to track memory usage (e.g. https://pythonhosted.org/Pympler).

Compared to our jobs service the memory consumption is really high (jobs service takes ~190MiB compared to API which takes 440MiB on fresh start).

We could also try to switch the underlying http server (jobs uses gunicorn, api server uses apache httpd).

**Comment by msrb** [comment]
The API pod consumes 550 MiB of RAM right after start.

**Comment by samuzzal-choudhury** [comment]
@tisnik are we still observing this issue on prod? How critical it is to get fixed?

**Comment by GeorgeActon** [comment]
@samuzzal-choudhury we do not apply severity to a feature, it only applies to defects. If this is a performance issue then it is a defect.

Severity not = equal priority.

**Comment by krishnapaparaju** [comment]
@tisnik can you please check out if you are able to reproduce this issue..

**Comment by sivaavkd** [comment]
@tisnik - Can you please verify if this is resolved with the performance work that we did in sprint 142 ?

**Comment by tisnik** [comment]
I've run the benchmarks on prod today and the results are much better:

https://fabric8-analytics.github.io/perf-tests/core_api/component_analysis/2018-01-31/component_analysis_sequenced_calls_known_component.png

https://fabric8-analytics.github.io/perf-tests/core_api/component_analysis/2018-01-31/component_analysis_sequenced_calls_known_component_min_max_avg_times.png

https://fabric8-analytics.github.io/perf-tests/core_api/component_analysis/2018-01-31/component_analysis_sequenced_calls_unknown_component.png

https://fabric8-analytics.github.io/perf-tests/core_api/component_analysis/2018-01-31/component_analysis_sequenced_calls_unknown_component_min_max_avg_times.png

**Comment by tisnik** [comment]
Also the output data seems to be correct -> ok to move this issue to current sprint and close it.
