### ISSUE TITLE
On prod-preview, unable to access pipeline build logs

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1195]
The login to Jenkins through OSIO are failing with a 403 error.

To recreate:
* Create new project
* Attempt to view the pipeline build log - the login to Jenkins will fail
* The chrome browser log shows a 403 error

**Comment by jfchevrette** [comment]
This is caused by OpenShift not allowing jenkins to unidle because of the new hibernation/force-sleep features in OSO 3.7

I will bring this up with the OSO/CD team and will loop back here once I have a solution

**Comment by jfchevrette** [comment]
After verification, this is NOT caused by 'force-sleep'.

@ldimaggi can you give more details on how the jenkins login fails? Do you get sent to OpenShift for auth? Are you given the opportunity to link jenkins authentication to openshift's?

Can you take a screenshot or copy/paste the chrome browser 403 error (along with request details)

**Comment by ldimaggi** [comment]
The problem is no longer visible - I was just able to access a build log:


[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Vert.x - HTTP 1.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- stackinfo-maven-plugin:0.2:prepare (default-cli) @ testoct26 ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.026 s
[INFO] Finished at: 2017-10-26T16:40:47+00:00
[INFO] Final Memory: 9M/89M
[INFO] ------------------------------------------------------------------------

Many thanks!

**Comment by ldimaggi** [comment]
The fix to this bug has opened a path to this new bug - analytic report generation failing: https://github.com/openshiftio/openshift.io/issues/1234
