### ISSUE TITLE
Tests for fabric8-analytics Jenkins plugin

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1198]
Planner ID: 2286

# Description

We don't have any tests for our Jenkins plugin, which is bad. We want to add some.

# Acceptance criteria
- [ ] there are tests for [fabric8-analytics-jenkins-plugin](https://github.com/fabric8-analytics/fabric8-analytics-jenkins-plugin) and they run in CI

**Comment by GeorgeActon** [comment]
@msrb Sevrity applies to bugs only.

Severity not= priority

**Comment by msrb** [comment]
We not have first tests for the jenkins plugin.
