### ISSUE TITLE
Notifications are sometimes hidden behind other overlays.

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#120]
Should we make the notifications appear on top of everything else?

![error-overlay](https://cloud.githubusercontent.com/assets/3001/25580893/3a8ed994-2e52-11e7-9899-ef82e55b31d7.png)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1364

**Comment by jfchevrette** [comment]
Closing in favor of https://github.com/fabric8-ui/fabric8-ui/issues/1364
