### ISSUE TITLE
Decouple API server and worker

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1200]
# Description

API server and worker used to reside in the same repository. We later split them into separate repositories, but the codebases are still quite tightly coupled. For example, many functions that are only needed by the API server reside in `f8a_worker.utils`. Server also directly talks to worker tables in RDS, but worker is responsible for database migrations.

Ideally, API server shouldn't depend on full worker library.

# Acceptance criteria
- [ ] if possible, API server doesn't directly talk to RDS tables maintained by workers
- [ ] all functions that are only needed by API are moved from worker to server

**Comment by miteshvp** [comment]
Done.

**Comment by miteshvp** [comment]
Done.
