### ISSUE TITLE
[5] spike: exclude result collector from the main flow

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1201]
# Description

The way how flows are designed right now is that results are first stored in RDS and they are moved to S3 only at the end of the flow. This means that one needs to wait till the flow is almost finished in order to see any results. It also means that if flow is interrupted before result collector is called, we don't get any results.

Storing results in S3 directly could give us at least partial results much sooner.

In this spike we want to identify pros/cons of this approach.

# Acceptance criteria
- [ ] pros and cons of the flows without result collector are documented

**Comment by fridex** [comment]
Done in https://docs.google.com/a/redhat.com/document/d/1azMHHv6Sj_aokNWAbGOBQUhdJUM1ikgkf35esjaOdB4/edit?usp=sharing

**Comment by msrb** [comment]
Thanks, we are done here 😉

**Comment by msrb** [comment]
Follow up task: https://github.com/openshiftio/openshift.io/issues/1440
