### ISSUE TITLE
CI/CD for mercator-go

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1202]
# Description

Our mercator-go project doesn't have CI job defined in https://ci.centos.org/ yet.

# Acceptance criteria

- [ ] job for mercator-go exists in https://ci.centos.org/, both PRs and master branch are tested there

**Comment by pkajaba** [comment]
@msrb I guess this one is done 

https://ci.centos.org/job/devtools-mercator-go-copr-mercator-build-master/
https://ci.centos.org/job/devtools-mercator-go-fabric8-analytics-copr-mercator/

**Comment by aditya-konarde** [comment]
@msrb @pkajaba I think we're good to close this ticket now?

**Comment by msrb** [comment]
Yup, thanks 👍
