### ISSUE TITLE
On prod-preview, rollout to 'run' fails with exceeded quota error

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1204]
To recreate on prod-preview:
* Reset user account
* Create new space
* Create new project - accept all defaults - select Vert.x Basic
* Observe that the project is rolled out to stage, but not run
* Observe the following error in the Jenkins pod log:

```
Oct 24, 2017 1:31:00 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
--
  | WARNING: Error in provisioning; slave=KubernetesSlave name: jenkins-slave-q344w-cdbgl, template=org.csanchez.jenkins.plugins.kubernetes.PodTemplate@6378bc
  | io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/api/v1/namespaces/ldimaggi-osiotest1-jenkins/pods . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "jenkins-slave-q344w-cdbgl" is forbidden: exceeded quota: compute-resources-timebound, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=3,limits.memory=1536Mi, limited: limits.cpu=4,limits.memory=2Gi.
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:407)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:769)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
  | at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:133)
  | at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:262)
  | at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)


```

**Comment by joshuawilson** [comment]
cc @kbsingh @vpavlin

**Comment by jfchevrette** [comment]
I cannot find anything specific to free-int or OCP 3.7 that can explain this. As the error state at the time jenkins could not launch a slave to execute the deploy job.

If you can re-produce let me know and I can live-debug to see what's going on

**Comment by jfchevrette** [comment]
From my investigation it appears that after the build is completed the jenkins-slave pod takes from 5-10 minutes to terminate completely and as such for 5-10 minutes after a build it is not possible to promote to prod as there are not enough quota to spawn a new slave for that task.

We need to investigate why the jenkins slave is stuck in Terminating state for 5-10 minutes after a termination request.

**Comment by jfchevrette** [comment]
- Initial state, no build, jenkins master is running

```
Thu Nov  2 11:32:17 EDT 2017

Name:		compute-resources
limits.cpu	2	4
limits.memory	1Gi	2Gi
Name:		compute-resources-timebound
limits.cpu	0	4
limits.memory	0	2Gi

content-repository-1-c7xsf   1/1       Running   0         20h
jenkins-2-z9p1w              1/1       Running   0         20h
```

- Push change to github repo, webhook pings jenkins
- Jenkins start slave jenkins-slave-1br17-4qld8

```
Thu Nov  2 11:33:30 EDT 2017

Name:		compute-resources
limits.cpu	2	4
limits.memory	1Gi	2Gi
Name:		compute-resources-timebound
limits.cpu	3	4
limits.memory	1536Mi	2Gi

content-repository-1-c7xsf   1/1       Running             0         20h
jenkins-2-z9p1w              1/1       Running             0         20h
jenkins-slave-1br17-4qld8    0/2       ContainerCreating   0         1s
```

- Actual jenkins build starts once the slave pod is ready
- A few minutes later s2i build pod starts

```
Thu Nov  2 11:34:47 EDT 2017

Name:		compute-resources
limits.cpu	2	4
limits.memory	1Gi	2Gi
Name:		compute-resources-timebound
limits.cpu	4	4
limits.memory	2Gi	2Gi

content-repository-1-c7xsf   1/1       Running    0         20h
jenkins-2-z9p1w              1/1       Running    0         20h
jenkins-slave-1br17-4qld8    2/2       Running    0         1m
testapp3-s2i-5-build         0/1       Init:0/2   0         2s
```

- s2i build finished, s2i pod is in completed state

```
Thu Nov  2 11:35:35 EDT 2017

Name:		compute-resources
limits.cpu	2	4
limits.memory	1Gi	2Gi
Name:		compute-resources-timebound
limits.cpu	3	4
limits.memory	1536Mi	2Gi

content-repository-1-c7xsf   1/1       Running     0         20h
jenkins-2-z9p1w              1/1       Running     0         20h
jenkins-slave-1br17-4qld8    2/2       Running     0         2m
testapp3-s2i-5-build         0/1       Completed   0         50s
```

- jenkins build finishes, slave pod is in terminating state

```
Thu Nov  2 11:35:56 EDT 2017

Name:		compute-resources
limits.cpu	2	4
limits.memory	1Gi	2Gi
Name:		compute-resources-timebound
limits.cpu	3	4
limits.memory	1536Mi	2Gi

content-repository-1-c7xsf   1/1       Running       0         20h
jenkins-2-z9p1w              1/1       Running       0         20h
jenkins-slave-1br17-4qld8    2/2       Terminating   0         2m
testapp3-s2i-5-build         0/1       Completed     0         1m
```

- slave in terminating state for a long time, killing containers (maven, jnlp)
  - grace period 30 sec is not honored?
  - 2 containers reported as being 'Terminated' & ready:false  however pod is still in 'Terminating state'
  - during this the pods quota is not released

- at this stage, if i promote to run I will get an error because it can't launch a new slave

- slave in terminating state for 5 minutes

```
Thu Nov  2 11:40:05 EDT 2017

Name:		compute-resources
limits.cpu	2	4
limits.memory	1Gi	2Gi
Name:		compute-resources-timebound
limits.cpu	0	4
limits.memory	0	2Gi

content-repository-1-c7xsf   1/1       Running     0         20h
jenkins-2-z9p1w              1/1       Running     0         20h
testapp3-s2i-5-build         0/1       Completed   0         5m
```

**Comment by jfchevrette** [comment]
Quickfix idea: can we make the jenkins build wait for the slave pod to be gone/deleted before the build is marked as finished?

Better fix: understand why it takes 5-10 minutes for the slave pod to terminate and optimize. I've seen this happen when processes inside containers don't respond to to SIGTERM and so OpenShift has to wait longer and eventually sends a SIGKILL

**Comment by jfchevrette** [comment]
In production the jenkins slave takes about 30 seconds to terminate and get deleted

**Comment by ldimaggi** [comment]
More slow results.

On production - 5 min:
![screenshot from 2017-11-02 13-52-09](https://user-images.githubusercontent.com/642621/32341889-28f0cffc-bfd5-11e7-8468-aa0b06fd2c94.png)


On prod-preview - 11 min:
![screenshot from 2017-11-02 13-08-54](https://user-images.githubusercontent.com/642621/32341919-46571cae-bfd5-11e7-9951-64ea84ab35ef.png)

**Comment by ldimaggi** [comment]
Closing as this issue seems to be closed - the speed on production and prod-preview looks similar today and rollout to run is successful.
