### ISSUE TITLE
[Backlog] contextual menu for the "more" 3 vertical points is expanding inside the frame of the task (and so almost hidden)

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1206]
![image](https://user-images.githubusercontent.com/1105127/31957583-8b5d963a-b8ef-11e7-9da9-1fa2cf81d45b.png)

try to click on the 3 vertical dots:
![image](https://user-images.githubusercontent.com/1105127/31957592-90938e3e-b8ef-11e7-899a-371d299f4aac.png)

a long scroll is available

![image](https://user-images.githubusercontent.com/1105127/31957597-9510709e-b8ef-11e7-994b-8bf80b7281d3.png)

**Comment by qodfathr** [comment]
Closing, as this part of the UI has been completely rewritten
