### ISSUE TITLE
[Planner]Unassigned filter is not working

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1207]
I have a task Unassigned
![image](https://user-images.githubusercontent.com/1105127/31957862-50d40d86-b8f0-11e7-9066-b9712923a00f.png)

if I choose unassigned filter, nothing is displayed 
![image](https://user-images.githubusercontent.com/1105127/31957879-6107eb6e-b8f0-11e7-865b-73369b2934ca.png)

**Comment by apupier** [comment]
please note that it is working to filter Assigned tasks

**Comment by nimishamukherjee** [comment]
@apupier following up on this issue. We have fixed it. Please verify.

**Comment by debloper** [comment]
Verified: fixed.
