### ISSUE TITLE
Create new space - UI limits user to <64 characters - but, the real limit is <63

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1209]
Steps to recreate:
* Create a new space
* Attempt to use a 63 character string as the space name
* Observe that the UI accepts the string, but the space is not created

In order for the space to be created, the upper-limit on the number of characters is 62.

**Comment by alexeykazakov** [comment]
Duplicates https://github.com/openshiftio/openshift.io/issues/1183
