### ISSUE TITLE
Review and Confirm can't 'Confirm Subsciption'

### ISSUE THREAD

**Issue by austincunningham** [openshiftio/openshift.io#1211]
Clicking on 'Confirm Subscription' renders the same page again

![image](https://user-images.githubusercontent.com/16667688/31971814-70c69940-b915-11e7-9db1-527f2a0b485a.png)

**Comment by alexeykazakov** [comment]
It looks like your subscription has been confirmed successfully. What browser are you using? Does it help if you refresh the page?

**Comment by austincunningham** [comment]
tried chrome and firefox

**Comment by austincunningham** [comment]
The Early Access Program, may not be provisioned yet :)

**Comment by alexeykazakov** [comment]
Your account has not been provisioned yet. You are in the waiting list. But you should see the following screen instead:
![oso](https://user-images.githubusercontent.com/620087/31972988-592f8234-b8d8-11e7-8fc9-1b588211f413.png)

Try open https://manage.openshift.com/account/index it should work.

**Comment by alexeykazakov** [comment]
I can reproduce:
1. Sing up
2. Confirm subscription
3. Try to sign up again
4. The registration app redirects to the confirm subscription page instead of https://manage.openshift.com/account/index

**Comment by austincunningham** [comment]
https://manage.openshift.com/account/index renders correctly

**Comment by pbergene** [comment]
I got the welcome email myself for an account I signed up on my private email during summit.  Tried it and got the same result. Screen capture [here](https://sometimes.works/osio/new-user.ogv).  It's not the best user experience or first impression. The first instinct I would have after getting the welcome email from Todd would be to log in :)

**Comment by alexeykazakov** [comment]
Fixed. Closing.

**Comment by alexeykazakov** [comment]
@austincunningham btw thank you for reporting this issue! :)

**Comment by joshuawilson** [comment]
@alexeykazakov is this done?

**Comment by alexeykazakov** [comment]
yes.
