### ISSUE TITLE
Crowd Sourcing - Generation from IDE end. (UI Portal)

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#1212]
### Description

There is already a user story that targets the crowd sourcing functionality featuring in the Stack Reports (OSIO)

In continuation to the same thought, this user story targets the same functionality featuring from direct IDEs.

In this case, we tentatively assume to generate a captcha at specified intervals in order to make sure the user is utilising the feature in a positive way.

##### Sub Tasks

- [ ] Bring in a user interface in the portal to cater the need for generating and rendering captcha feature.
- [ ] Make it accessible from IDEs

Service

- [ ] Hit necessary service to get the desired captcha information and send the response back accordingly.

**Comment by arunkumars08** [comment]
@samuzzal-choudhury This is added almost at the end of the sprint, hence I ain't measuring the points for this user story.

**Comment by samuzzal-choudhury** [comment]
`/api/v1/generate-file` is available on prod currently. Hence, closing this issue. Please feel free to reopen with the valid sprint milestone.
