### ISSUE TITLE
Cannot open work item immediately after creating on a board

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#1218]
1. Switch to board view
2. Create a work item
3. Try to open it

It should open, but it never does for me.

If I refresh the page, then I can open it.

**Comment by qodfathr** [comment]
Also, when I create the new work item, another empty work item appears. If I refresh, that new one goes away. Not sure if this is by design or not.

**Comment by nimishamukherjee** [comment]
Created issue on OSIO [1669](https://openshift.io/openshiftio/openshiftio/plan/detail/1669)

**Comment by sudsen** [comment]
PR - https://github.com/fabric8-ui/fabric8-planner/pull/2324

**Comment by michaelkleinhenz** [comment]
Fixed, but we have a different issue with the board currently. Will create a new bug.
