### ISSUE TITLE
Cannot scroll to 'Closed' column on planner board

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#1220]
1. Set screen resolution to 1920x1080
2. Go to board
3. Leave sidebar expanded
4. Bottom scroll bar is visible; Closed column is not
5. Move scroll bar

Closed column should become visible, but it does not.
If you collapse side bar, you can see the closed column.

**Comment by nimishamukherjee** [comment]
Create issue on OSIO [1668](https://openshift.io/openshiftio/openshiftio/plan/detail/1668)

**Comment by michaelkleinhenz** [comment]
@nimishamukherjee I think we fixed that. I can't reproduce it with current master. Can you check and close the OSIO issue?

**Comment by qodfathr** [comment]
Fixed.
