### ISSUE TITLE
Labels for everything in WI creation is "label"

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#1221]
I was trying to create a new work item from the Planner Backlog view (non Quick Add way) and all the labels for fields appear to be "label". I couldn't find a label specific issue in the issues. so @alexeykazakov  please feel free to close this if it's already reported somewhere.

![label](https://user-images.githubusercontent.com/926572/32036282-2fb993f0-ba62-11e7-9861-daa07b804e9e.png)

**Comment by qodfathr** [comment]
Fixed
