### ISSUE TITLE
[3] RFE: Improve code quality for all projects in fabric8-analytics-common repository

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1224]
Acceptance criteria:
- [x] all source files are checked by Pylinter
- [x] script to run Pydocstyle is in the repository
- [x] all source files are checked by Pydocstyle
- [x] CI is setup to run Pydocstyle
- [x] results (all green) are available on QA dashboard: https://fabric8-analytics.github.io/dashboard/dashboard.html

Blocker for #1089

**Comment by samuzzal-choudhury** [comment]
@tisnik I think this is a core stream goal. Hence, removed the stream/integration tag.

**Comment by tisnik** [comment]
Docstrings have been added into all source files, Pydocstyle script has been created, and CI configured. DB is green (for this repo).
