### ISSUE TITLE
User Story: Revamp the Analytics stack report UI

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#1235]
#### Description:
Improve the current design of the stack report UI based on the UX wireframe in this [link](http://to-be-done-by-muru).

#### Acceptance Criteria:
The new UI is developed based on the above wireframe and is deployed on the production cluster for OSIO users.

**Comment by arunkumars08** [comment]
@samuzzal-choudhury I think you can close this issue as another revamp has happened and that is tracked here - https://github.com/openshiftio/openshift.io/issues/1773

**Comment by miteshvp** [comment]
Done.
