### ISSUE TITLE
Handling unknown scenarios: OSIO user enquiring for a Component

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1236]
OSIO user while editing at Che editor would be flagged for a component if a component got a CVE associated. This flow is triggered thru LSP (Language server protocol) server initiating REST API onto OSIO platform.

In case this specific component is unknown to OSIO platform (has not ingested the data for this component), trace message at log file need to be printed. This would help to gather the list of missing components at OSIO and ingest the same into the platform at the earliest date.

**Comment by miteshvp** [comment]
Implemented.
