### ISSUE TITLE
UX/UI: Label menu needs an OK or check mark button

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#1239]
When adding a label to my new Work Item, I select one or more labels and expect to have an OK or &#10003; button to confirm that I would like to add the selected labels. Instead, I have to press X (common associated with cancel and/or close) to save my changes.

![label](https://user-images.githubusercontent.com/926572/32155768-24b6a260-bd85-11e7-9e8a-83445ef2c759.png)

Furthermore, the newly selected labels do not appear in the original field (See screenshot) so there is no way of telling that they are already added if I just click X. I would recommend adding an OK or &#10003; button to this menu for a better UX.

**Comment by nimishamukherjee** [comment]
Created feature on OSIO [1671](https://openshift.io/openshiftio/openshiftio/plan/detail/1671)

**Comment by qodfathr** [comment]
Done.

**Comment by qodfathr** [comment]
This is regarding the application of existing labels; reopening as I misunderstood.

**Comment by mishaone** [comment]
Adding details for clarity:
* X is usually a negative closing option, translating to "Cancel/stop this and don't save the changes I made".
* OK/Check is usually a positive closing option, translating to "Yes, I'm done with my changes, save and close this now."

In this case, we probably need a positive closing icon to confirm that your changes are saved and you want to exit the options menu.

**Comment by qodfathr** [comment]
@mishaone I agree with you, but not 100%. For example, look how labels are applied in GitHub to an issue (like this one). If the actions taken within the 'dialog' occur immediately, then `X` is just close, not cancel. I think for things like labels, the immediate application is the correct behavior.

That being said, I personally think that the whole work item detail form itself should behave a you describe. Extending that example, if I were to

1. Open a work item
2. Apply a label with the widget of interest in this issue -- this happens immediately to the work item **in memory** but is not actually persisted back. The work item is now dirty.
3. Click a cancel operation of some sort (a `Cancel` button or an `X` button or press `ESC`), the work item changes are not saved and, therefore, the applied label is not applied in the backend repository

@sdash-redhat can UXD make a determination on all of this? Thx.

**Comment by sdash-redhat** [comment]
@qodfathr  Sure.  Sunil is looking into it.

**Comment by sunilmalagi** [comment]
@qodfathr @mishaone Its designed based on the requirement / user story provided, I will discuss with Dev team and decide based on the updated user story or the requirement I will provide the design.

**Comment by nimishamukherjee** [comment]
Decided to continue with the current label mechanism. Label list closes when we click outside it.
