### ISSUE TITLE
[3] Ignore description inherited from parent POM

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1244]
Bug discovered by @rootAvish, thanks :wink:

# Description

We first build effective pom before we try to extract information from pom.xml files. This means, among other things, that if given pom.xml doesn't have `<description>` on its own, the description is inherited from parent pom. This can lead to a situation when dozens of packages share the same description inherited from common parent pom, e.g. [org.sonatype.oss:oss-parent](https://github.com/sonatype/oss-parents/blob/master/oss-parent/pom.xml#L24).

We should ignore inherited descriptions.

# Acceptance criteria
- [x] mercator ignores descriptions inherited from parent POMs
- [x] Build RPM
- [x] code runs in production

**Comment by pkajaba** [comment]
Hello @rootAvish,

Can you elaborate how did you get this result?


I am trying to run mercator in base folder of freshly cloned git repo:
a) `MERCATOR_JAVA_RESOLVE_POMS=true mercator  .`
b) `mercator  .` 
c) `mercator oss-parent/pom.xml` 
d) `MERCATOR_JAVA_RESOLVE_POMS=true mercator oss-parent/pom.xml`

all of commands returns correct description.

Thanks!

**Comment by rootAvish** [comment]
@pkajaba I needed the descriptions to run evaluations on the tagging work, for that I collected the descriptions that are present in the `metadata.json` file in the "prod-bayesian-core-data" bucket under the latest version folder of these packages. I'm sorry I can't help you with how they got there 🙁 , I've shared the file that I have containing the package names and the aggregated data with you on MM. Maybe you can try running Mercator for those packages.

**Comment by pkajaba** [comment]
@rootAvish Thanks for providing examples. It seems to be a bug or "normal behavior" in generating effecting POMs. Let's see how we can fix it.

**Comment by msrb** [comment]
@pkajaba I think you need to run mercator on a pom.xml which doesn't have `<description>` on its own, but has `<parent>` section and therefore inherits the description from parent.

**Comment by pkajaba** [comment]
https://github.com/fabric8-analytics/mercator-go/pull/21 PR submitted here. @msrb or @tuxdna PTAL, thanks!

**Comment by msrb** [comment]
@pkajaba I think we will need to bump spec file before we build an RPM.

**Comment by pkajaba** [comment]
@msrb https://github.com/fabric8-analytics/mercator-go/pull/22 Done. I asked to build RPM too.

**Comment by msrb** [comment]
Done, thanks @pkajaba 😉
