### ISSUE TITLE
Implement idling of tenant Jenkins instance

### ISSUE THREAD

**Issue by vpavlin** [openshiftio/openshift.io#1245]
* Jenkins is taking 1GB of RAM even if there are no builds running
* Idle Jenkins if not used (based on builds status)
* Add cache/proxy for webhooks coming to Jenkins
* Investigate if we can proxy all Jenkins traffic to get better UX when unidling

Implementation in the services [fabric8-jenkins-proxy](https://github.com/fabric8-services/fabric8-jenkins-proxy) and  [fabric8-jenkins-idler](https://github.com/fabric8-services/fabric8-jenkins-idler)

The progress of the rollout of Proxy and Idler can be tracked in the [Proxy rollout](https://github.com/fabric8-services/fabric8-jenkins-proxy/projects/1) resp [Idler rollout](https://github.com/fabric8-services/fabric8-jenkins-idler/projects/1) GitHub projects.

**Comment by xcoulon** [comment]
(checked the mark for the `Reverse lookup tenant by cluster/namespace` task in the description as it was resolved last week)

**Comment by vpavlin** [comment]
I've deployed new version of Idler and Proxy yesterday - Idler now uses new permissions added to our token for OSO, so it does not do polling anymore. Also Proxy now gives you a loading page while Jenkins is unidling.

JF had an issue that Jenkins was killed immediately after update or reset tenant event - this is now solved too and Jenkins will stay up after such event for some time.

I am working with Hardy on making the repos more manageable - adding comments, Makefiles, packaging etc

Things missing before we can deploy to production:
- [ ] Integration with toggle service
- [ ] Auto-update of github webhook in generated repos (from OSO jenkins route url, to https://jenkins.(prod-preview.)openshift.io)
- [ ] Change URLs for Jenkins in OSIO UI
- [ ] It would be probably good if someone from UX looked at the loading page (the content is far from good)

**Comment by mmclanerh** [comment]
@vpavlin can you give this issue an update with where we're at / what's outstanding?  thanks!

**Comment by maxandersen** [comment]
want to assign @hferentschik but he needs to accept invite ;)

**Comment by qodfathr** [comment]
Is this done?

**Comment by maxandersen** [comment]
jenkins idler is in production for subset of users now. still work to be done to enable for users by default.

**Comment by maxandersen** [comment]
@hferentschik on the performance test - this was more a stresttest you were setting up, right ? to verify the idler and proxy actually behaved correctly ?

**Comment by hferentschik** [comment]
The rollout of Idler/Proxy will occur in two steps. First, we enable the Jenkins Proxy for everyone and then we deploy the Jenkins Idler and enable the idling feature.

The Proxy itself is ready to go, but there are two migration tasks which need to occur in parallel with the rollout:

* https://github.com/fabric8-services/fabric8-jenkins-proxy/issues/114 - Updating the links in the pipeline view 
* https://github.com/fabric8-services/fabric8-jenkins-proxy/issues/94 - Updating existing GitHub webhook URLs

Work for these tasks is in progress. 

Regarding the Idler, there is some re-work in progress which needs to be completed and tests - https://github.com/fabric8-services/fabric8-jenkins-idler/pull/101

**Comment by kbsingh** [comment]
@hferentschik it might be good to ensure the launcher team have delivered their new code, so new users are not going to need migrations etc, before we do the cluster wide rollout for idler/proxy.  cc @gastaldi - as he's doing that work in launcher

**Comment by hferentschik** [comment]
> it might be good to ensure the launcher team have delivered their new code, so new users are not going to need migrations etc, before we do the cluster wide rollout for idler/proxy. cc

Right, this is a requirement. As I keep saying there are several pieces which need to fall in place when enabling the Jenkins Proxy for everyone.

**Comment by hferentschik** [comment]
> on the performance test - this was more a stresttest you were setting up, right ? to verify the idler and proxy actually behaved correctly ?

This was an integration test really. It was not about determining any baseline of similar. It was about verifying that things work and that there are no obvious leaks. So far the test just covers the pure proxying part. To also test the actual idle/unidle functionality some more changes on the Idler side are needed (https://github.com/fabric8-services/fabric8-jenkins-idler/pull/101).

**Comment by hferentschik** [comment]
Another thing which I think needs to be discussed more is the combination of Idler and multi-cluster. @vpavlin had the idea of running one Idler per cluster, but I am wondering whether this would even be possible.

**Comment by maxandersen** [comment]
for multicluster I would assume its about running one idler instance per cluster on OSD, right ?  and each of those idlers will have a cluster name to talk to and monitor ? I guess that would work...why wouldn't it ?

**Comment by vpavlin** [comment]
Correct, N clusters would result in N idler deployments on OSD, each consuming events from a different cluster.

On the other hand, I think with current refactoring @hferentschik is doing, it might be also possible to use a single Idler per multiple clusters (as long it it handles the load), but that would require code changes in Idler and a bit more thought.

Proxy is ok from the point of getting information about users, but as it communicates with Idler to figure out state of Jenkins, we might get into issue of not knowing which Idler to ask (in case of Idler per cluster)..

I can come up with couple solutions right away:
* We give Proxy a view access for namespace and allow it to query list of idler services and then ask idlers about which OSO clusters they take care of
* We build the above into OSO proxy, Jenkins proxy then simply goes to OSO proxy (saying this only with very shallow understanding of OSO proxy)
* We strictly configure mapping between Idler deployment name and cluster in some common config map used by both proxy and idler

I'd probably prefer anything where some level of auto-discovery is used, so let's say #1:
* we create multiple deployments for idler (one per cluster)
* idler exposes API call which returns cluster URL it handles
* Proxy has simple OpenShift client which lists DCs with `label: jenkins-idler` and from the list it builds a map of cluster -> idler service name
* Based on user info, it looks up idler service in the map and uses that to get info about Jenkins

**Comment by aslakknutsen** [comment]
@vpavlin Jenkins proxy does proxying both with and without access to the users token, correct?

**Comment by vpavlin** [comment]
Not sure if I understand the question, but I'll try to answer:)

There are 2 paths of proxying

1. Github webhook - does not require auth/token, user is recognized based on codebase URL
2. Authenticated user - based on token acquired through redirect to auth service - then cookies are used to verify auth against Jenkins so that we don't need to redirect to auth everytime

Not sure if it helps:)

**Comment by joshuawilson** [comment]
This appears to be done. While there are other bugs and features around this, it does work. Closing.
