### ISSUE TITLE
Backlog view: Work Items are within a panel which limits menu options display

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#1247]
In the Planner's Backlog view, I clicked on the three dots icon for additional options for my Work Item. The options display, but is cut off, as seen in the screenshot:

![1](https://user-images.githubusercontent.com/926572/32208147-57f65efa-be4c-11e7-9213-fbf5eef70e9f.png)

This makes it really obvious that there is a restricted panel displaying the list of Work Items. I try to view the rest of the menu options listed, but this removes the Work Items from view and looks very strange:

![2](https://user-images.githubusercontent.com/926572/32208161-7943d4ac-be4c-11e7-8924-f876929b7dfa.png)

This makes for a troublesome UX when trying to view options for one of a list of Work Items.

**Comment by qodfathr** [comment]
Closing as the kebab menu no longer exists.
