### ISSUE TITLE
spike: explore download statistics in JBoss Nexus

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1249]
# Description

We had a meeting with David Hladky from JBoss and he could give us access to some Maven Central download statistics that they have in their Nexus repository. We want to explore the data.

David needs our JBoss username in order to give us access to the data. 

# Acceptance criteria
- [ ] document describing what data we could get from JBoss Nexus exists

**Comment by miteshvp** [comment]
Not relevant. Can re-visit and re-open and needed.
