### ISSUE TITLE
Identification of Anchor Packages for Node Ecosystem

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#1251]
### Description

Currently, PGM doesn't have the notion of anchor packages. Need to determine the anchor packages for Node Ecosystem to generate better PGM recommendation's for outliers.

#### Acceptance Criteria
- A list of anchor packages should be generated for Node ecosystem.

**Comment by miteshvp** [comment]
@sunilk747 - you can close this issue now. Incrementally we need to find top 100 anchor package for entire node ecosystem we have and not just for 3k packages. Please open one backlog issue for the same.

**Comment by sunilk747** [comment]
refer #1293
