### ISSUE TITLE
After quickstart project creation new codebase is not visible in the dashboard

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#1252]
After quickstart project creation new codebase is not visible in the dashboard:
See https://youtu.be/h7OhxG6je84?t=1m55s

**Comment by bartoszmajsak** [comment]
I was about to open the same issue - if you refresh it shows up though.

**Comment by joshuawilson** [comment]
@aslakknutsen @dgutride this is one of those things we need to figure out how to refresh/update so the user knows the system is live.

**Comment by aditya-konarde** [comment]
+1

**Comment by qodfathr** [comment]
Bumping to SEV2 as this is becoming a larger point of confusion for new users.
