### ISSUE TITLE
areas don't scroll/handle well when more areas than can fit on a page

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#1256]
I just created a new area called "testinfra" under https://openshift.io/openshiftio/openshiftio/settings and it won't show it how much I try to scroll or refresh.

Only if a use Ctlr+F to search for it the area shows up - using normal scroll does not work.

**Comment by qodfathr** [comment]
@maxandersen I think this is fixed. Can you verify, please, and close if it is? Thanks.

**Comment by maxandersen** [comment]
verified it works. closing.
