### ISSUE TITLE
[3] Push images built from PRs to a registry

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1257]
# Description

We want to allow developers to easily test their changes on the dev cluster, but they need images with the changes to be available in a registry somewhere (devshift?).

Currently we build images in https://ci.centos.org/  when someone opens a PR in https://github.com/fabric8-analytics/. We test them, but we don't push them.

We could modify our CI jobs and start pushing PR images.

Note it should be easy to map images back to corresponding PRs (via tag for example).

# Acceptance criteria
- [x] PR images are available in a registry and developers are able to deploy such images on the dev cluster

**Comment by pkajaba** [comment]
Hello @kbsingh, would it be OK, if we pushed images from PR as it is described in this issue into the devshift?

**Comment by krishnapaparaju** [comment]
With integration tests be done at two clusters (Dev, Stage) and three instances (1. developer's branch  content at Dev cluster , 2. after rebasing at Dev cluster, 3. After merge to master at Staging cluster). Which of these three instances do we wanna push images to Registry ? 2,3 ?

**Comment by pkajaba** [comment]
At this point, we are doing the third option. This task suggests pushing images when there is PR open for a repository.

**Comment by pkajaba** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/120
https://github.com/fabric8-analytics/gremlin-docker/pull/21
https://github.com/fabric8-analytics/fabric8-analytics-server/pull/200
https://github.com/fabric8-analytics/fabric8-analytics-stack-report-ui/pull/45
https://github.com/fabric8-analytics/fabric8-analytics-data-model/pull/60

**Comment by msrb** [comment]
I guess that's it. Thanks @jpopelka and @pkajaba, great work 😉
