### ISSUE TITLE
[5] Make it possible to easily run E2E tests against f8a deployments on the dev cluster

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1258]
# User story

As a fabric8-analytics developer, I want to be able to test my fabric8-analytics deployment running on the dev cluster so I can verify that my changes did not break anything.

# Description

Devs testing their changes on the dev cluster may want to run E2E tests from time to time. It should be easy enough to do so. See https://github.com/fabric8-analytics/fabric8-analytics-common for information about our E2E tests. The goal is to make running the tests against custom dev cluster deployment as easy as possible.

Note this is only about running the tests, we assume that the deployment already exists.

# Acceptance criteria
- the way how to run E2E tests against custom dev cluster deployment is straightforward and documented

# Tasks
_TBA_

**Comment by joshuawilson** [comment]
cc @ldimaggi

**Comment by msrb** [comment]
Moving to sprint 141.

**Comment by humaton** [comment]
This should be possible [now](https://github.com/fabric8-analytics/fabric8-analytics-common/tree/master/openshift#e2e-test)
