### ISSUE TITLE
[3] Collect license information from GitHub

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1261]
# Description

Our GitHub worker doesn't collect license information from repositories.

# Acceptance criteria
- [x] existing GitHub worker collects also repository level license information

**Comment by pkajaba** [comment]
PR created: https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/424

**Comment by msrb** [comment]
Done. Thanks @pkajaba  😉 Good job 👍
