### ISSUE TITLE
Add new Auth API URL env var to fabric8-ui

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#1265]
There should be a new FABRIC8_AUTH_API_URL env var available in all relevant deployments in prod, preview and badger. We expect this env var set to access Auth service from our UI,

We need this to unblock https://github.com/fabric8-ui/fabric8-ui/pull/2011
Part of https://github.com/fabric8-services/fabric8-auth/issues/149

**Comment by alexeykazakov** [comment]
cc: @jstrachan @rawlingsj @sbose78 

Could someone from the SD team to help with this while James x2 are not available? @kbsingh

**Comment by sbose78** [comment]
This is done, and is in Prod.
