### ISSUE TITLE
Profile page is an hard coded mockup

### ISSUE THREAD

**Issue by fbricon** [openshiftio/openshift.io#127]
Opening https://openshift.io/fbricon%40redhat.com shows a mockup profile page

<img width="878" alt="screen shot 2017-05-02 at 10 42 46 am" src="https://cloud.githubusercontent.com/assets/148698/25623072/4e3c2686-2f24-11e7-93eb-e8ba54e38dbf.png">

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1366

**Comment by qodfathr** [comment]
@joshuawilson this looks like a dup of closed #1366. Can we close? (I vote to close.)
