### ISSUE TITLE
[8] Crowd Sourcing: Offline pipeline for PGM training

### ISSUE THREAD

**Issue by SaketJNU** [openshiftio/openshift.io#1270]
## Description:
As the tagger could not automatically generate accurate tags for a huge percentage of packages, so here the idea is to **crowd-source** the tagging work of those unknown packages. The end-users(developer) of **osio** may assign the tags to packages suggested to them, which will further be used for PGM training after post data-cleansing. 

### Acceptance Criteria:
Able to read end-user's tags assigned to packages, perform data-cleansing followed by tags verification. Finally provide the package_topic list to PGM for next level of training. 

### User Stories

- [x] Create a job to read tags from graph. (https://github.com/openshiftio/openshift.io/issues/1283) 
- [x] Crowd Sourcing: Implement verification logic (https://github.com/openshiftio/openshift.io/issues/1311)

**Comment by sivaavkd** [comment]
This is completed and hence closing this.
