### ISSUE TITLE
Deploy 3scale user registration portal on production

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#1278]
### Description:
As a fabric8-analytics developer I would like to deploy 3scale user registration portal on the production so that the IDE extensions can consume its services during the IDE user authentication via OSIO.

### Acceptance criteria:
The 3scale user registration portal is to be deployed on production with a route exposed for consuming its services

PR- https://github.com/openshiftio/saas-analytics/pull/179

**Comment by samuzzal-choudhury** [comment]
@GeetikaBatra are you working on this? If yes, is the portal deployed on staging already?

**Comment by GeetikaBatra** [comment]
@samuzzal-choudhury, currently, I am working on making the api cast available on staging. I remember that this was not supposed to be deployed on production.
Please make a note, this is about making api cast available on deployment and not the self hosted 3scale gateway.

**Comment by GeetikaBatra** [comment]
This should be closed with the merge of following PR.
https://github.com/openshiftio/saas-analytics/pull/179

**Comment by GeetikaBatra** [comment]
3scale connect api is available in production, we can close this one.

**Comment by sunilk747** [comment]
@GeetikaBatra If this user story is completed please close it.
