### ISSUE TITLE
Workshop issue: Che is not starting

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#1279]
CHE 2.0.45 tab opens with a message/dialog "Workspace is not running".

In the CHE pod log I see the following message: 

"org.eclipse.che.api.core.ServerException: Multiple ImageStreamTags found for name che-ws-nlzkmmtkz8n42aqvpzhwfs4h1f3rl2xb"

**Comment by ibuziuk** [comment]
@rafabene is it for vert.x stack ? also would be great to get some some steps to repro

**Comment by joshuawilson** [comment]
This was an AWS limit issue and has been fixed.
