### ISSUE TITLE
Opening a new bug shows overlaying bug status menu

### ISSUE THREAD

**Issue by fbricon** [openshiftio/openshift.io#128]
Opening a new bug shows overlaying bug status menu, hiding the OK/Validation button.

<img width="723" alt="screen shot 2017-05-02 at 10 46 34 am" src="https://cloud.githubusercontent.com/assets/148698/25623327/cb11d624-2f24-11e7-82ec-494aa333722d.png">

Tested on Chrome 57.0.2987.133 (64-bit)

**Comment by mindreeper2420** [comment]
this is remedied in an upcoming release

**Comment by mindreeper2420** [comment]
@joshuawilson this has been fixed, but I do not have a PR to link it to. I believe it was done as part of other work on the Detail Panel.
