### ISSUE TITLE
Show a relevant message to the user if we do not have any usage data in the fabric8 analytics stack report(dashboard & modal screen)

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#1288]
In the below screenshot, we get a message in the usage section saying "Components that aren't common", but we don't see a usage count below. This has to be handled on the UI side showing a valid message to the user like "No usage data available"

![screenshot from 2017-11-03 12-43-13](https://user-images.githubusercontent.com/5430080/32369277-a0871970-c0ae-11e7-9724-0def28693c9f.png)

**Comment by GeorgeActon** [comment]
The component total line also does not seem to make sense. 
Should it be

Components Total:  4 | Known 3 | Unknown 1

**Comment by samuzzal-choudhury** [comment]
@GeorgeActon thanks for the comment. We will be fixing that in https://github.com/openshiftio/openshift.io/issues/1449.

**Comment by jyasveer** [comment]
@Preeticp Can you please suggest a appropriate message to display for this issue ?

**Comment by Preeticp** [comment]
@jyasveer, quite a few stack-level label and layout changes went through as part of this PR: https://github.com/fabric8-ui/fabric8-recommender/pull/373
Can you please validate and confirm if any further changes are required.

**Comment by jyasveer** [comment]
@Preeticp i dont think for now we have anything more to do on this.

**Comment by jyasveer** [comment]
@Preeticp yes we require a proper message to display for this scenario

**Comment by invincibleJai** [comment]
@jyasveer `Components that aren't commonly used in your stack` was replaced with `Components not used together`. So is the question here is in case of 0, can we show 0 under `Components not used together` or do we need to show some different message? CC @Preeticp

**Comment by jyasveer** [comment]
yes @invincibleJai this is my question to @Preeticp

**Comment by Preeticp** [comment]
@jyasveer, @samuzzal-choudhury , @invincibleJai  in case of  `Components not used together` > `0` can we give a more positive message to the user like: `No usage outliers in your stack.
All the components in your stack work well with each other.`

**Comment by jyasveer** [comment]
For me this will be a apt message

**Comment by samuzzal-choudhury** [comment]
@jyasveer @Preeticp @invincibleJai  The card header is now "Usage Outliers" and this is how we display '0' usage outlier info:

![image](https://user-images.githubusercontent.com/17740190/33420830-13233022-d5d6-11e7-814c-2b576b45c0d3.png)

I think this is good enough. But, if we choose to be verbose, IMO, we can put `All the components in your stack work well with each other` .

CC: @krishnapaparaju

**Comment by jyasveer** [comment]
So what is the final decision here ?

**Comment by jyasveer** [comment]
Okay I am changing the code to show the message `All the components in your stack work well with each other.`

**Comment by jyasveer** [comment]
closing this as it is in prod now.
