### ISSUE TITLE
[Spike] evaluate websocket vs REST

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#1289]
Currently we have a lot of REST calls. There are a few websockets set up. There are some concerns regarding websockets on network traffic especially on a multi-cluster set up.

Please list findings and concerns here.

**Comment by jiekang** [comment]
The Openshift Container platform documentation for REST API [1] has "The API is designed to work via the websocket protocol. API requests may take the form of "one-shot" calls to list resources or by passing in query parameter watch=true. When watching an endpoint, changes to the system may be observed through an open endpoint. Using callbacks, dynamic systems may be developed that integrate with the API."

This suggests their endpoints support standard REST requests like GET for one shot requests, as well as upgrading to a websocket for 'watching' via a query parameter. Maybe we can adopt a similar system for endpoints that require this capability?

We need data on the network traffic, especially on a multi-cluster set-up, to have a more informed decision.


[1] https://docs.openshift.com/container-platform/3.6/rest_api/index.html

**Comment by joshuawilson** [comment]
Met with Clayton and we all agreed to use websocket for now.
