### ISSUE TITLE
Can't import repository to the new space

### ISSUE THREAD

**Issue by kadel** [openshiftio/openshift.io#1300]
I've created new space and imported codebase from GitHub repository.
Then I have deleted the whole space and created the new one with different name.

If I try to import the same repository to the new space I get the following error:

```
The repository golang-example has already a build config, please select another repo. 
```

**Comment by corinnekrych** [comment]
@joshuawilson this is not a bug, more an enhancement on fabric8-generator addon to add ability to override of buildconfig.
@kadel have you use the `Reset environment` in the profile page to clean?

**Comment by kadel** [comment]
> @kadel have you use the Reset environment in the profile page to clean?

Yes, I did that. That is the only way to around that issue that I know.

**Comment by joshuawilson** [comment]
this was fixed with a reset, closing

**Comment by kadel** [comment]
Resetting environment no longer works as a workaround for this.
I'm unable to import repository that I've imported and deleted before :-(
