### ISSUE TITLE
Link to pipelines is invalid

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#1301]
The pipeline link is invalid. It appear to be missing '@gmail.com' of my username.

Steps to reproduce
1) Reset environment
2) Create a new space and Vertx codebase from wizard
3) Observe that I am redirected to that new workspace at URL https://prod-preview.openshift.io/jfchevrette@gmail.com/testapp4
3) Observe that Build #1 starts immediately
4) Click on 'testapp4' in the pipelines section(screenshot below)

![pipeline](https://user-images.githubusercontent.com/3001/32499393-74bd0c2e-c3a0-11e7-9dba-67012b346e5e.png)

5) Link goes to https://prod-preview.openshift.io/jfchevrette/testapp4/create/pipelines which loads the 404 page and shows an error notice "/jfchevrette/testapp4/create/pipelines not found"
6) If I manually navigate to https://prod-preview.openshift.io/jfchevrette@gmail.com/testapp4/create/pipelines (adding @gmail.com myself) it works.

## Impacts
- [ ] #2138 Platform Navigation Issues for Heather

**Comment by qodfathr** [comment]
Is this still an open issue? I don't have an `@` account to verify.

**Comment by jfchevrette** [comment]
Yes I am still having this issue in production.

Attached screenshot should be clear. Let me know if I can provide more info. 

![pipeline-bad-link](https://user-images.githubusercontent.com/3001/35348864-5edf3f7c-0107-11e8-9a6c-f317db778c68.png)

**Comment by andrewazores** [comment]
This looks like a dupe of https://github.com/openshiftio/openshift.io/issues/2334

**Comment by ldimaggi** [comment]
This looks like it is working now - JF - can you retry and close?

**Comment by jfchevrette** [comment]
This is not fixed.

- My space URL is: https://openshift.io/jfchevrette@gmail.com/demovertx5
- From the space page (above URL), the pipeline URL is: https://openshift.io/jfchevrette/demovertx5/create/pipelines

**Comment by andrewazores** [comment]
@jfchevrette would you be able to test on prod-preview? I don't think the change has bubbled to prod yet (@joshuawilson ?)

**Comment by joshuawilson** [comment]
I have not pushed it to prod yet.

**Comment by piyush1594** [comment]
@jfchevrette Can you please check once more. Can you please confirm if this is still there?

**Comment by jfchevrette** [comment]
I can confirm this is fixed now. Thanks!
