### ISSUE TITLE
UX: Hovering mouse over icons with tooltip make them jump around

### ISSUE THREAD

**Issue by sthaha** [openshiftio/openshift.io#1305]
![osio-icon-jumps-around](https://user-images.githubusercontent.com/3005132/32530054-96efc6aa-c487-11e7-882e-5953a42c7b06.gif)

I have seen the behaviour happen in icons used in planner as well

**Comment by joshuawilson** [comment]
What page is this on?

**Comment by sthaha** [comment]
@joshuawilson I saw this behaviour on `Create/Codebases` - https://openshift.io/sunil.thaha/foobar/create

**Comment by sthaha** [comment]
I see this happen only when the workspaces are empty

**Comment by sthaha** [comment]
@joshuawilson I think the reason this happens is when the tooltip doesn't have enough space to the right to be displayed. Adding `padding-right` to make enough space for the tooltip seems to resolve this. See: 

![padding](https://user-images.githubusercontent.com/3005132/32532711-e485a0a0-c497-11e7-8286-0bcadd7b1390.gif)

**Comment by mindreeper2420** [comment]
@joshuawilson I'll take this. It was fixed before, so there is something larger going on. Last time, it was code in the `.ts` file that was positioning against the wishes of the CSS.

**Comment by joshuawilson** [comment]
thanks @mindreeper2420

**Comment by mindreeper2420** [comment]
related to https://github.com/openshiftio/openshift.io/issues/1179
