### ISSUE TITLE
"Update Profile" presents the user with a blank screen

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1309]
See attached screenshots:

![screenshot from 2017-11-08 16-25-36](https://user-images.githubusercontent.com/642621/32575333-b1d56b18-c4a1-11e7-89e2-ce1f87ac291b.png)

![screenshot from 2017-11-08 16-26-08](https://user-images.githubusercontent.com/642621/32575339-b71531da-c4a1-11e7-8ecb-2495ea460aed.png)

**Comment by joshuawilson** [comment]
@mindreeper2420 Please take a look.

**Comment by joshuawilson** [comment]
fixed in #2218
