### ISSUE TITLE
Creating a new space doesn't filter Github repos properly

### ISSUE THREAD

**Issue by fbricon** [openshiftio/openshift.io#131]
I can't type my repository name in the filter field, it's readonly apparently. Which forces me to scroll through my hundreds of repo.
<img width="572" alt="screen shot 2017-05-02 at 11 13 06 am" src="https://cloud.githubusercontent.com/assets/148698/25624880/ce75c240-2f28-11e7-9ab1-c77d98549774.png">

Moreover, all repositories display the same hard-coded description (`The regexp pattern to match the repository name`)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1367

**Comment by fbricon** [comment]
Upstream issue was closed
