### ISSUE TITLE
Pipelines are not shown when importing repo without overriding Jenkinsfile

### ISSUE THREAD

**Issue by kadel** [openshiftio/openshift.io#1315]
When I import a repository with unchecked  "Override Jenkins and POM files."  pipeline page is empty. 

The repository that I'm importing has its own custom Jenkinsfile.

I've checked OpenShift console and I can see that pipeline was created and I is running, but openshift.io Pipelines page is empty.

**Comment by joshuawilson** [comment]
@kadel the import in OSIO adds a jenkinsfile. If you have one then it does not overwrite it. And yours probably won't work. You could try to save a copy of your jenkinsfile and then remove it so that the import can install the one that is needed. Once you confirm it works you can try to modify the new one based on your old one. However, there is no promise it will work after you change it.
@jstrachan please confirm I got this right.

**Comment by kadel** [comment]
Jenkinsfile is fine, as I can see it running in Jenkins and in OpenShift console, only OpenShift.io is not showing it.
If I import repository with my own Jenkinsfile and let OSIO overwrite it and then put my Jenkinsfile back, then pipelines are shown correctly.

I've also tried to import repository that was created by OSIO quickstart (with default Jenkinsfile) and OSIO pipelines page was empty even than (import was with "Override Jenkins and POM files." unchecked)

The issues seems to be only when "Override Jenkins and POM files." is not checked.

**Comment by joshuawilson** [comment]
@corinnekrych are you aware of this?

**Comment by corinnekrych** [comment]
@joshuawilson nope i wasn't aware of this issue. maye the existing jenkins/pom is causing issue. @kadel would you mind linking your test repo?
@jstrachan is the bet to comment about it.

**Comment by kadel** [comment]
@corinnekrych

You can try to reproduce it by importing  https://github.com/kadel/test and unchecking  "Overriding Jenkins and POM files".

That repo is Verte.x quickstart created by OSIO with default valid Jenkinsfile without any modification.

**Comment by joshuawilson** [comment]
If you uncheck "override", they are saying don't override my jenkinsfile just use mine. If you use your own then there is a very good chance it is not set up correctly. All of this is pre-beta, so i expect things to break. We just need to produce it so we can fix it. :)

**Comment by kadel** [comment]
> If you use your own then there is a very good chance it is not set up correctly.

That is not the case as the Jenkinsfile is exactly the as same the one generated by OSIO quickstart and works there.
The issue is not Jenkinsfile.

You can reproduce this with Jekinsfile that you can be sure is 100% working using following steps:
 - create a new space
 - create new quickstart project
 - choose one of the stacks - for example "Verte.x HTTP Booster"
 - next, next, ... finish
 - check that Pipeline is running and finishes correctly
 - now reset environment to start from a clean state (deleting space is not enough because of #1300)
  - create new space
  - choose Import existing code
  - choose the same repository that was created using quickstart  (before we did reset environment)
  - uncheck "Overriding Jenkins and POM files"
  - next, ..., finish

Now you have exactly the same code with the same Jenkinsfile as generated by quickstart, the only difference is that it is not created but imported. And you won't see any Pipelines running in OSIO console. If you check OpenShift or Jenkins console you will see that is running fine.

**Comment by joshuawilson** [comment]
I know there is an issue with deleting pipelines after resetting your environement, that may be the cause.

We can test this if you reset and then try to import one that I made, that way you aren't importing the same one that may not have been fully deleted. https://github.com/joshuawilson/hawk

**Comment by joshuawilson** [comment]
ok, thanks @kadel we'll take a look

**Comment by qodfathr** [comment]
Is this still an issue? Perhaps the problem is/was something along the lines of a missing Space label in OSO?

**Comment by joshuawilson** [comment]
@chmouel @rupalibehera can you verify this?

**Comment by bartoszmajsak** [comment]
There is no option of overwritting `Jenkinsfile` anymore in the import flow. That functionality existed in the old Launcher wizard. We will work on refining this experience - #4155
