### ISSUE TITLE
Deleting a space doesn't delete associated pipelines

### ISSUE THREAD

**Issue by fbricon** [openshiftio/openshift.io#132]
After deleting a space, I still have a zombie pipeline still trying to build. It's possible the pipeline state is in a borked state that prevents it from being deleted, I have no idea, but in that case the deletion process should be more robust.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1344

**Comment by RanjithRV** [comment]
@chmouel @pradeepto made this issue Sev3 as it has been hanging around since May 2017. Please update if needed.

**Comment by qodfathr** [comment]
@catrobson Is this something for which UXD has a plan? Or is this one of the open issues around Space deletion?

**Comment by catrobson** [comment]
Yes, this is one of the open issues around space deletion.

**Comment by piyush1594** [comment]
Duplicate of #3802 Can we close this.
