### ISSUE TITLE
Make the Integration Cookbook publicly available

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1324]
Because the fabric8 API can be consumed by virtually anyone, it would be nice to:

1) finish the Integration Cookbook
2) perform proofreading
3) update it according to latest changes in the stack-analysis response
4) make it available

We can either make it part of OSIO documentation or build the book on CI.

Acceptance criteria:

1) person outside the fabric8 team will be able to read the book and make API call to perform stack analysis and component analysis, get the results, and gather required data

**Comment by samuzzal-choudhury** [comment]
@tisnik these are the updates on the Integration cookbook -

1. It was Finished.
2. It was proof-read by Preeti from the documentation team.
3. It was updated with the latest stack analysis response.
4. It was already made available to the devtools team on Aug 9.

Here is the link - https://docs.google.com/document/d/1k5hbknuebBZVVMkWpKZKAP6LoHWXD2bbvrn-4P4wmjg/edit

We can discuss about how to distribute that for public viewing.

**Comment by tisnik** [comment]
@samuzzal-choudhury nice! TYVM. I'm going to talk about the public viewing with people from the CCS team.

**Comment by rkratky** [comment]
@tisnik, what is the intended audience for this doc? End users or Analytics devs?

**Comment by tisnik** [comment]
@rkratky Hi Robert, ATM this API is consumed by OSIO and by the Eclipse plugin only (AFAIK), but it might be consumed by our customers and external users in the future.

**Comment by rkratky** [comment]
@tisnik, if it's only for 'internal' (developer) purposes, I'd suggest using GitHub pages (gh.io) to host it. But if it should be exposed (even if only in the future) to customers/users, then I expect it should live on docs.openshift.io (I can help with that).

**Comment by tisnik** [comment]
Cool, TYVM @rkratky. I'll need to talk about it with @samuzzal-choudhury 

PS: our gh.io pages are a bit ...minimalistic ATM: https://fabric8-analytics.github.io/

**Comment by qodfathr** [comment]
This seems to be done? Can we close?

**Comment by rkratky** [comment]
@qodfathr We prepped the cookbook, but were asked to hold on with publishing because of some part that wasn't supposed to be seen publicly. So we're holding on to it for now. Tracking in https://github.com/fabric8io/fabric8-online-docs/issues/116

@Preeticp, could you provide details, please?

**Comment by Preeticp** [comment]
@rkratky apologies for the late response, this is now good to be published.

**Comment by rkratky** [comment]
Publication has now been greenlighted by the Analytics team.

@qodfathr A question has been raised whether docs.openshift.io is the right place to publish this cookbook. I suggest modifying the page to make a clear distinction between docs for end users and docs for devs who want to contribute to the project.

Please, have a look on prod-preview (https://docs.prod-preview.openshift.io/) and let me know if an arrangement like that is OK from your perspective.

**Comment by qodfathr** [comment]
@rkratky that works for me. I trust your judgement.

**Comment by rkratky** [comment]
Cookbook published on https://docs.openshift.io/
