### ISSUE TITLE
After successfully creating a new quickstart project, the UI implies that the user can cancel the project

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1325]
Steps to recreate:
* Create a new quickstart project
* At the completion of the 'add to space' wizard, observe the dislog:

![screenshot from 2017-11-08 21-24-58](https://user-images.githubusercontent.com/642621/32666569-d45fbbc4-c605-11e7-9561-0238bb5392d1.png)

The user has 3 options:
* Select 'OK' - the project has been created and the dialog is closed
* Select 'Cancel' - the project has been created and the dialog is closed
* Select the 'x' icon - the project has been created and the dialog is closed

I think that we should remove/disable the Cancel key as the project has been created and cannot be cancelled.

**Comment by joshuawilson** [comment]
@ldimaggi you are using a word we don't have in the application, "project". Do mean the Space is created or the application is created. Those Cancels should cancel the application. The Space gets created in the first step. We do have it on the UX redesign to create more separation there.

**Comment by ldimaggi** [comment]
Sorry - this is in regard to the app that is created. (But - it does refer to "project.  ;-)

![screenshot from 2017-11-10 12-00-22](https://user-images.githubusercontent.com/642621/32669565-f9e4f504-c60e-11e7-8ac5-e4dc4062d3ed.png)

**Comment by joshuawilson** [comment]
So how do know that it created it, the app is in the apps page and github link was created/added? Because I don't see those. I have the newly created Space.

**Comment by ldimaggi** [comment]
After pressing the Cancel button - the app's pipeline is created:

![screenshot from 2017-11-10 18-37-56](https://user-images.githubusercontent.com/642621/32683056-5c39cbbc-c646-11e7-932b-6fb2f1dad6a0.png)
![screenshot from 2017-11-10 18-37-29](https://user-images.githubusercontent.com/642621/32683057-5c4320e0-c646-11e7-90a1-518052ef80e9.png)

**Comment by joshuawilson** [comment]
@corinnekrych @edewit are you aware of this?

**Comment by corinnekrych** [comment]
@joshuawilson yes it's per design. the summary is an extra step to add codebase to wit backend. the previsous screen has a `finish` button this si where the pipeline is created on the forge backend.

**Comment by joshuawilson** [comment]
Why is there a `Cancel` button on the page if there is nothing to cancel?

@corinnekrych can you confirm it does nothing? If so then this is a UX question.

**Comment by ldimaggi** [comment]
Ah - ok - when the user selects "Finish" - it completes the creation of the new app/project/quickstart.

The confusion is that the screen/window displayed after Finish implies that the user has options when in reality that final screen is only displaying post-creation information for the user. 

I think all we have to do is to remove the Cancel button on that final screen. Thx!

**Comment by corinnekrych** [comment]
@ldimaggi @joshuawilson you can cancel the create of the codebase.
This was discussed in our UX review, we renamed "review" to summary. cc @catrobson do you think we should remove the cancel button to make it clearer?

**Comment by catrobson** [comment]
@corinnekrych yes we can remove the cancel button.  I actually think our team is just about ready to send an updated design for the summary page, so you might want to make that change along with any layout changes proposed by the team in general.

**Comment by qodfathr** [comment]
Fixed
