### ISSUE TITLE
On prod-preview, resetting the user environment is failing ~90% of the time

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1326]
Seeing this on prod-preview;
* Reset the user environment
* About ~90 of the time - the reset fails - the error displayed to the user is:

![screenshot from 2017-11-10 10-32-55](https://user-images.githubusercontent.com/642621/32666808-b51bdc38-c606-11e7-820f-5d576f434627.png)

![screenshot from 2017-11-10 10-33-25](https://user-images.githubusercontent.com/642621/32666822-be10f512-c606-11e7-84e9-4b2ade6d67a0.png)
![screenshot from 2017-11-10 10-33-11](https://user-images.githubusercontent.com/642621/32666823-be1d5258-c606-11e7-9f23-2976372fe862.png)

**Comment by joshuawilson** [comment]
@ldimaggi have you tried this on prod.

@aslakknutsen @kbsingh are you aware of this?

**Comment by ldimaggi** [comment]
Seeing this on production:  https://github.com/openshiftio/openshift.io/issues/1328

**Comment by aslakknutsen** [comment]
There is a bug in tenant service when 'waiting for the clean jobs to finish' so the UI times out on a Gateway erroor, but the root cause of the hang is due to the openshift client timing out waiting for, in my case, the Che namespace to clean out.

```
imagestream "registry.devshift.net_che_vertx" deleted
deploymentconfig "che" deleted
route "che" deleted
service "che-host" deleted
replicaset "che-ws-gqlbfnlk6xyy2fhu-1512972599" deleted
replicaset "che-ws-q3vs3dj0vgj7t9vl-1084878659" deleted
persistentvolumeclaim "che-data-volume" deleted
persistentvolumeclaim "claim-che-workspace" deleted
configmap "che" deleted
configmap "fabric8-online-che" deleted
timed out waiting for the condition
timed out waiting for the condition
```

It left behind a few Workspaces.. Cleaning a second time passes.

**Comment by ldimaggi** [comment]
What I am seeing on prod-preview is that a 2nd attempt at a cleaning also fails (as does a 3rd, etc.)

**Comment by l0rd** [comment]
@aslakknutsen I don't know if that is related but the 9th Nov. the fabric8 maven plugin has been upgraded in `fabric8-tenant-che`. As a consequence I have seen some weird differences in the yaml file that has been generated like:

```diff
- - apiVersion: v1
+ - apiVersion: apps.openshift.io/v1
```

**Comment by aslakknutsen** [comment]
@ldimaggi As oppose to my account, you seem to be getting timeouts on the second attempt as well:

```
timed out waiting for the condition
timed out waiting for the condition
timed out waiting for the condition
timed out waiting for the condition
timed out waiting for the condition
timed out waiting for the condition
timed out waiting for the condition
timed out waiting for the condition
timed out waiting for the condition
timed out waiting for the condition
timed out waiting for the condition
```

Not sure what's going on here. Can't reproduce atm. I'll keep trying and see if Openshift is reporting anything.

**Comment by joshuawilson** [comment]
This appears related to https://github.com/openshiftio/openshift.io/issues/1328

**Comment by ldimaggi** [comment]
Closing - this problem seems to be fixed.
