### ISSUE TITLE
On https://openshift.io, resetting a user's environment is not restarting the Jenkins pod

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1328]
Steps to recreate:
* On https://openshift.io, reset a user's environment
* Observe the Che pod restart, and the Jenkins pod not restart:

![screenshot from 2017-11-10 12-14-15](https://user-images.githubusercontent.com/642621/32670336-7207b7fe-c611-11e7-8b8c-c4a5af609f0f.png)
![screenshot from 2017-11-10 12-13-58](https://user-images.githubusercontent.com/642621/32670337-7216fc00-c611-11e7-9a14-571d60fee03f.png)
![screenshot from 2017-11-10 12-13-42](https://user-images.githubusercontent.com/642621/32670338-722276ca-c611-11e7-9244-9cf6fa8a5baa.png)

**Comment by ldimaggi** [comment]
This seems to be reproducible - just saw it 4 out of 4 tries.

**Comment by joshuawilson** [comment]
@aslakknutsen is this related to the issue you are seeing?
cc @kbsingh @jstrachan

**Comment by aslakknutsen** [comment]
Tenant Service is failing to update the namespaces. Something wrong with the templates.

```
rolebindingrestriction "dsaas-user-access" configured
limitrange "resource-limits" configured
resourcequota "compute-resources" configured
resourcequota "object-counts" configured
resourcequota "compute-resources-timebound" configured
secret "che-recommender-api-token" configured
serviceaccount "che" configured
service "che-host" created
rolebinding "user-edit" configured
rolebinding "che" configured
persistentvolumeclaim "che-data-volume" created
persistentvolumeclaim "claim-che-workspace" created
configmap "che" created
configmap "fabric8-online-che" created
deploymentconfig "che" created
route "che" created
Error from server (Forbidden): rolebinding.authorization.openshift.io "user-view" is forbidden: user "devtools-sre" cannot grant extra privileges:
{Verbs:["get" "list" "watch"], APIGroups:["batch"], Resources:["cronjobs"]}
{Verbs:["get" "list" "watch"], APIGroups:["batch"], Resources:["scheduledjobs"]}
```

**Comment by aslakknutsen** [comment]
@ibuziuk Never mind. This seems to have been around since at least Nov 3. Effects all namespaces.

**Comment by aslakknutsen** [comment]
@ldimaggi Raised to @jfchevrette

**Comment by ldimaggi** [comment]
On November 11 - I started seeing also this problem with the Che pod on https://openshift.io

**Comment by joshuawilson** [comment]
This appears to be effecting all new users too.

**Comment by joshuawilson** [comment]
@ldimaggi can you confirm this was fixed?

**Comment by joshuawilson** [comment]
I think this was fixed. Please reopen if you are still seeing it.

**Comment by pbergene** [comment]
I suspect this was due to the hibernation/ force-sleep quotas which affected creation of all new pods. These applied to 331 jenkins and 2 che namespaces (with @ldimaggi / e2e as one of the latter). The rolebinding error was a red herring.
