### ISSUE TITLE
Invalid link to Home from the pipeline history page

### ISSUE THREAD

**Issue by fbricon** [openshiftio/openshift.io#133]
Clicking on the `Home` link from the Pipeline history (`https://openshift.io/<user>/<space>/create/pipelines/<repo>/history`) page fails:

<img width="946" alt="screen shot 2017-05-02 at 11 25 33 am" src="https://cloud.githubusercontent.com/assets/148698/25625313/2fdc9a12-2f2a-11e7-9a08-2820d0c7e90c.png">

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1345

**Comment by jstrachan** [comment]
fixed by https://github.com/fabric8-ui/fabric8-runtime-console/pull/
