### ISSUE TITLE
Delete unnecessary AWS resources if required for operational needs

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1330]
Many a times , AWS resources get created for pure experimental needs and these resources would not be required after some time (weeks from creation) and they become stale, never get deleted.

Need to script to delete unnecessary DynamoDB tables and S3 buckets.

**Comment by msrb** [comment]
I believe this depends on https://github.com/openshiftio/openshift.io/issues/1081.

**Comment by krishnapaparaju** [comment]
Yes

**Comment by jpopelka** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-common/pull/446

**Comment by krishnapaparaju** [comment]
@jpopelka what is the criteria being followed to term a resoruce as 'stale / unnecessary' resource ?

**Comment by jpopelka** [comment]
@krishnapaparaju So far, the script for deleting the AWS resources doesn't operate with 'stale/unnecessary' term as that would probably be too risky.
One needs to explicitly specify a tag (see #1081) and the script will delete all resources tagged with this tag.
