### ISSUE TITLE
"Learn more" on front page brings you back to the first page again

### ISSUE THREAD

**Issue by Rydekull** [openshiftio/openshift.io#1333]
When you go to: https://openshift.io/_home

And click "Learn more"
OpenShift.io information
Learn more about what OpenShift.io can do for you

It links to: https://openshift.io/
Which loads https://openshift.io/_gettingstarted

Which brings you back to: https://openshift.io/_home

**Comment by joshuawilson** [comment]
@mindreeper2420 can you update this user flow loop to point to the docs?

**Comment by mindreeper2420** [comment]
Currently, the site is not configured to allow visitors back to OpenShift.io and stay there. It will always redirect users back to _home or _gettingstarted. Not a bug, but by request.

**Comment by joshuawilson** [comment]
`Learn more` should not take you back to the landing page but to a doc.

**Comment by joshuawilson** [comment]
If the `learn more` is on the landing page then the button needs to tell the user what is happening and where to go once there.

**Comment by mindreeper2420** [comment]
The “Learn More” isn’t actually called that anymore, as it was reworded to “Features”. As this lives on the marketing page, the redirect logic will need to be rewritten to account for this. I’ll be taking care of that as part of a separate story that was already in the queue. I’ll use this issue for renaming and relinking the Dashboard URL to use “Features”.
