### ISSUE TITLE
OpenShift.io Frontpage - Recent spaces widget

### ISSUE THREAD

**Issue by Rydekull** [openshiftio/openshift.io#1335]
Some feedback about the widget(with lack of a better term):
 - it is called recent spaces, and it holds a "+" button where you can create a new space (in recent spaces?)
   Perhaps just a rename of Recent Spaces to something else?

 - Seems like it tracks spaces I've visited, regardless if they are mine or someone else, but it does not show who the owner of each space is unless I hover above it and inspect the URL

**Comment by joshuawilson** [comment]
@mindreeper2420 when you get a chance, please take a look at this one.

**Comment by mindreeper2420** [comment]
@joshuawilson I'll create a story in fabric8-ux for this, as the Dashboards are currently being reviewed.

**Comment by jiekang** [comment]
The story in fabric8-ux was closed as the dashboard is being redesigned. I think this can be closed as well; feel free to reopen otherwise.
