### ISSUE TITLE
Logging into OpenShift.io yields a 500 in developer console

### ISSUE THREAD

**Issue by Rydekull** [openshiftio/openshift.io#1336]
Looking at the details

**Request:**
GET /api/user/services HTTP/1.1
Host: api.openshift.io
Connection: keep-alive
Origin: https://openshift.io
Authorization: Bearer 
xyz
Content-Type: application/json
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
X-Request-Id: 92d43fa2-ed4d-4860-8601-45e8c9c6ae25
Referer: https://openshift.io/_home
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,fr;q=0.8

**Response:**
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://openshift.io
Access-Control-Max-Age: 600
Content-Encoding: gzip
Content-Type: application/vnd.api+json
Vary: Origin
Date: Mon, 13 Nov 2017 20:14:41 GMT
Content-Length: 112
Set-Cookie: b2c7c4d8013d0faf3d6bc4a99018e01f=a86ccc3c582398664b7f98e398802c78; path=/; HttpOnly; Secure
{"errors":[{"code":"internal_error","detail":"record not found","status":"500","title":"Internal error"}]}

**Comment by joshuawilson** [comment]
Did you do anything besides or after logging in?

**Comment by Rydekull** [comment]
Well, i did things after. but that was the loading of the first dashboard you get when you login. From the page that you get sent to after finishing your username/password input.

**Comment by joshuawilson** [comment]
@Rydekull are you still seeing this?

**Comment by joshuawilson** [comment]
This should be fixed, please reopen if it is still an issue.

**Comment by sbose78** [comment]
This was the fix I assume: https://github.com/fabric8-services/fabric8-auth/commit/aa6c3f6f2a6d74e88b2d549708df61135035064f
