### ISSUE TITLE
Searching for spaces gives no feedback

### ISSUE THREAD

**Issue by Rydekull** [openshiftio/openshift.io#1337]
Going to: https://openshift.io/arydekul@redhat.com/_spaces

And using the search for spaces, returns no feedback if its successful, failure, or syntax error.

Also, there is no "search" button, but confusingly a "New" button at the end of the form. So I am searching by hitting enter.

**Comment by joshuawilson** [comment]
Currently it searches as you type. This page is not ideal and is under a redesign at https://github.com/openshiftio/openshift.io/issues/477.

**Comment by qodfathr** [comment]
Closing because (1) it's currently working as designed and (2) a new design is on the way.
