### ISSUE TITLE
Jenkins and che services does not load properly when logging in

### ISSUE THREAD

**Issue by Rydekull** [openshiftio/openshift.io#1338]
In the top right corner when looking at status of service, the services does not load properly.

![image](https://user-images.githubusercontent.com/1591438/32747269-88bbc554-c8b8-11e7-9776-9ee38bb5e0ee.png)

**Comment by Rydekull** [comment]
Its worth noting. I found my way into OpenShift Online. And in there I could see the following

All pods in username-jenkins project was in Error state.

No pods exists in username-che project.

So there seems to have been something going wrong with the initial setup of my user

**Comment by Rydekull** [comment]
Oh, and after manually starting the pods in username-jenkins, The status icon within OpenShift.io is still in the same state.

**Comment by joshuawilson** [comment]
@kbsingh here is the issue from earlier today.

**Comment by ldimaggi** [comment]
Related to:  https://github.com/openshiftio/openshift.io/issues/1328

**Comment by joshuawilson** [comment]
@Rydekull is this still an issue?

**Comment by joshuawilson** [comment]
If it is still an issue you should log into https://console.starter-us-east-2.openshift.com/console/ and confirm that you did not add any projects manually. They need to be deleted and then you should relogin to OSIO and go to `profile` and `reset env`.

**Comment by joshuawilson** [comment]
being worked at #1031

**Comment by joshuawilson** [comment]
@xcoulon @pbergene can you work with @Rydekull to get his account clean to

**Comment by pbergene** [comment]
All 5 projects are in place and look correctly set up.  @Rydekull did you set up the 'arydekul' namespace on openshift yourself (so the tenant db doesn't know about it) or was that provisioned by OSIO? I'm not sure this is a https://github.com/openshiftio/openshift.io/issues/1031 thing. 

Reset environment and reset tenant would be the place to start.

**Comment by kbsingh** [comment]
agree with @pbergene this isnt #1031 but more likely to be #1448

**Comment by pbergene** [comment]
Issues with a specific user, account cleaned on Monday 27.11.17. Closing, ping on here if you are still experiencing this @Rydekull
