### ISSUE TITLE
Documentation links point to different places

### ISSUE THREAD

**Issue by Rydekull** [openshiftio/openshift.io#1339]
In the top right, there is a link to documentation at docs.openshift.io

When you for example have no space ćreated and you look at your profile page, the "My Spaces" widget tells you:
Create a Space
Learn how to get started in the documentation

That link points to access.redhat.com-documentation.

Should be pointing to the same

**Comment by joshuawilson** [comment]
@mindreeper2420 was this fixed or only partially?

**Comment by mindreeper2420** [comment]
@joshuawilson the original issue was to just add/update the link in the user drop down. There was no mention of it being updated or added elsewhere. Easy fix though.

**Comment by joshuawilson** [comment]
thanks
