### ISSUE TITLE
Existing OpenShift account holders not able to access

### ISSUE THREAD

**Issue by baijum** [openshiftio/openshift.io#134]
From the issue reported at HN:
https://news.ycombinator.com/reply?id=14246981
```
I have an OpenShift account and now I'm shown an
 "additional action needed" page on login. When i complete it
 and hit submit, it tells me that email already exists
```

**Comment by baijum** [comment]
One more report : https://news.ycombinator.com/item?id=14247163

**Comment by alexeykazakov** [comment]
https://issues.jboss.org/browse/RHDENG-1320

**Comment by alexeykazakov** [comment]
Fixed upstream - https://issues.jboss.org/browse/RHDENG-1320

**Comment by joshuawilson** [comment]
@baijum can you please verify if this is still an issue?

**Comment by baijum** [comment]
@joshuawilson I don't have an account which I can use to verify this particular issue. It was reported by someone in hacker news.

**Comment by joshuawilson** [comment]
@baijum you can create a new account with a new email.

**Comment by baijum** [comment]
@joshuawilson I used another account and it's working now. This issue can be closed.
