### ISSUE TITLE
Deleting a space still leaves it in "recent spaces" as an active link

### ISSUE THREAD

**Issue by Rydekull** [openshiftio/openshift.io#1342]
When I go to : https://openshift.io/username/_spaces

And delete a space in the list, it disappears from that page, and from the menu in the top-left.

However, if I then go to https://openshift.io/_home

My deleted space will still appear in the list of recent spaces. And its a clickable link. 
If I try to click it, it will give me an error in the top right saying its not found.

**Comment by joshuawilson** [comment]
This is a refresh issue. It is being tracked at #879, please add any other comments there.

Closing as a duplicate.
