### ISSUE TITLE
Unessecary link in notification when creating a new space

### ISSUE THREAD

**Issue by Rydekull** [openshiftio/openshift.io#1343]
If I create a new space, it'll transport me to my new space. 

At the same time, in the top right corner, there is a notification saying I can visit my new space and gives me a link to visit the same page which I am already on.

**Comment by joshuawilson** [comment]
Originally the notification was the way to move to the new Space and then we found it easier to redirect you .

@catrobson can you add this to your backlog to have someone work out the UX please.

**Comment by catrobson** [comment]
Added a story about removing the pop-up notification when space is created.  https://github.com/fabric8-ui/fabric8-ux/issues/746

**Comment by joshuawilson** [comment]
thanks

**Comment by qodfathr** [comment]
Fixed.
