### ISSUE TITLE
Codebase creation page has a UI-bug in top right

### ISSUE THREAD

**Issue by Rydekull** [openshiftio/openshift.io#1345]
If I navigate to:
https://openshift.io/user/myspace/create

And then in the codebase-part of the page try to hover at the + in the upper right of that page. The browser will start having a seizure.

Also, I have noticed that at some circumstances (still not able to replicate) it fails to load my workspaces and gives me a red error popout next to the workspaces column.

**Comment by joshuawilson** [comment]
@mindreeper2420 I thought you had fixed this, is it just not in prod or not done yet?

@Rydekull can you please make a new issue for the second comment about workspaces loading.

**Comment by mindreeper2420** [comment]
@joshuawilson this has been fixed and verified at least once. Not sure what the issue is now. How do you tell if something is in prod? The releases don’t seem to be up to date.

**Comment by mindreeper2420** [comment]
@joshuawilson at this point, the tooltip problem might be the module that we use. It is not something made by us, but an external piece.

**Comment by mindreeper2420** [comment]
This has been fixed. The tooltip now appears above the text, similar to the other pieces in the toolbar. This eliminates any rendering issues and page jumps.

<img width="214" alt="screen shot 2017-12-01 at 1 40 56 pm" src="https://user-images.githubusercontent.com/4032718/33497858-55d42d82-d69d-11e7-9b42-ae9b88ea0730.png">
