### ISSUE TITLE
Sometimes the settings button for a space, does not bring the settings but replicates the top menu

### ISSUE THREAD

**Issue by Rydekull** [openshiftio/openshift.io#1347]
When navigating around in the UI, sometimes when you go to a space settings
https://openshift.io/user/myspace/settings

By clicking in the top menu UI next to the drop down, it does not bring you to the settings, rather it replicates the menu once more. For each time you click the icon "Analyze Plan Create" replicates to the right

**Comment by qodfathr** [comment]
I cannot reproduce this. @Rydekull can you verify that it is fixed?

**Comment by joshuawilson** [comment]
This had been an issue, but we think we fixed it. If you see it again and can document how to reproduce it, please reopen this.
