### ISSUE TITLE
Importing a project from github produces two pipeline builds immediately.

### ISSUE THREAD

**Issue by jerboaa** [openshiftio/openshift.io#1355]
Steps to reproduce:

1. Create new space, give it any name, import basic Vert.X booster via the quickstart wizard. Do not import existing code.
2. Wait for builds to finish.
2. Reset env.
3. Create a new space, give it any name not equal to the one in step 1. Import the git repo as created by step 1 above.
4. Observe two jenkins pipeline builds being scheduled. One is likely triggered by the git push OSIO itself is doing so as to update the space name.

Expected: Only one build gets scheduled.

Other: I've used the pipeline setup with approval in the wizards.

**Comment by jerboaa** [comment]
![screenshot from 2017-11-14 13-18-38](https://user-images.githubusercontent.com/357222/32779532-6929a176-c93e-11e7-811e-339f822a26c0.png)

Example schedule. What's weird is that the second build runs first.

**Comment by joshuawilson** [comment]
I thought this was closed in #915.

I think this is less an issue with importing and more with the deletion of pipelines not happening. What do you think @jstrachan @aslakknutsen ?

**Comment by jerboaa** [comment]
I should note that if I deselect "Trigger build" in the wizard, only one build gets scheduled (the "Provide CI integration hook" checkbox is still marked). So I suppose in order to reproduce this one needs to have both of them selected (default). The expectation would be to: If both are checked (default), only create one build on initial import.

**Comment by joshuawilson** [comment]
@jerboaa you can verify by importing one I made via the quickstart. That way there is no name conflict.
https://github.com/joshuawilson/hawk

**Comment by jerboaa** [comment]
@joshuawilson I'm trying, but joshuawilson is not possible via the "Application Wizard". I'm using the "Import existing code" widget within the wizard, not the button in "Codebases". So I've forked the repo to my space, now this new repo in my namespace isn't showing in the UI (yet?).

**Comment by jerboaa** [comment]
Ok seems to have worked now. And for that, `hawk`, it only schedules one job. This one gave me two:
https://github.com/jerboaa/vertx-http-booster

**Comment by jerboaa** [comment]
![screenshot from 2017-11-14 17-04-14](https://user-images.githubusercontent.com/357222/32790146-ed10aa42-c95d-11e7-9a63-f631087e74a8.png)

**Comment by jerboaa** [comment]
I was too fast. After an env reset this does happen. 
![screenshot from 2017-11-14 18-05-57](https://user-images.githubusercontent.com/357222/32793630-c57dff30-c966-11e7-8cd1-3a2a6551a16a.png)

**Comment by bartoszmajsak** [comment]
Mother of all issues: https://github.com/openshiftio/openshift.io/issues/592

**Comment by jerboaa** [comment]
Alright. No point with keeping multiple duplicates around. I'm closing this one in favour of #592
