### ISSUE TITLE
Include list of available features in the `show user` response

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#1357]
As part of https://github.com/openshiftio/openshift.io/issues/1356, the goal is to enrich the `GET /api/user` response by including the list of available "toggled" features given the current level of features that the user wants to use (`no pre-production`, `beta-only` or `experimental`). 
The user needs to be flagged as a member of one of the `internal`, `beta` or `experimental` groups to be able to get the actual list of toggled features

**Comment by corinnekrych** [comment]
let's close it for now as per the spike we might not need it anymore. we can always reopen if needed
