### ISSUE TITLE
Codebases is not populates after the new quickstart wizard.

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#1358]
**Codebases** is not populates after the new quickstart wizard. **Pipelines** are shown.

Should **applications** show something?

![screenshot 2017-11-14 12 18 56](https://user-images.githubusercontent.com/30131/32784452-08ee9fa8-c936-11e7-86ef-de60da929e05.png)

**Comment by joshuawilson** [comment]
duplicates #1252
