### ISSUE TITLE
Enhancement request - Enable users to refresh set of repos than can be imported 

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1360]
If a user forks a repo, it can take OSIO up to 5 min for OSIO to recognize that newly forked repo. This seems to be on a 5 minute timer.

Can we enhance this by adding a feature/button to enable users to force an immediate refresh? I think that users will want to see this feature. Thx!

**Comment by joshuawilson** [comment]
What are steps to reproduce this? What needs to be set up first in OSIO?

**Comment by ldimaggi** [comment]
Steps to recreate:
* Log into OSIO
* In a diff browser window - log into github and fork a repo
* In OSIO observe a ~5 min delay before the forked repo can be accessed in the Import option of 'add to space'

**Comment by qodfathr** [comment]
@ldimaggi any update on this? I think I've seen something similar recently. Not sure if this is an OSIO issue or a behavior of GitHub. Regardless, this is a bug until determined to be otherwise.

**Comment by ldimaggi** [comment]
It's still there - is there something that runs every 5 min to update OSIO?

**Comment by qodfathr** [comment]
That last question was to you, @joshuawilson , I think.

FWIW, I do not want to see us add a refresh button. I just want it to work transparently (if possible).

**Comment by joshuawilson** [comment]
I'll have to check if there is an update running. 
I agree, it should "feel" live even if it isn't.

**Comment by ldimaggi** [comment]
This is still an issue as of June 7, 2018.

**Comment by invincibleJai** [comment]
I tried now, it works fine for me 

Steps : 
1. Open openshift.io in a tab 
2. Open gitHub in another tab
3. Forked a repo under one of my organisations in gitHub
4. Opened new launcher in openshift.io selected import flow 
5. Selected gitHub flow and Org in dropdown I was able to see the forked repo in the dropdown.

Note: if Organisation is already selected in launcher gitHub step and then user forked a repo in that particular Org. User needs to reselect that particular org in launcher gitHub step.

CC @animuk can you pls give a try.

**Comment by animuk** [comment]
Closing this as the issue does not seem to be there
