### ISSUE TITLE
Reset Environment on prod-preview - Che pod fails to restart

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1364]
This problem started showing up on November 15 - it appears to be reproducible.

Steps to recreate:
* Reset user environment.

For Che pod, observe that the pod does not restart, observe errors in the events log:
```
Stop retrying: couldn't create deployer pod for "ldimaggi-osiotest1-che/che-1": 
pods "che-1-deploy" is forbidden: exceeded quota: force-sleep, requested: 
pods=1, used: pods=0, limited: pods=0

Error creating deployer pod: pods "che-1-deploy" is forbidden: 
exceeded quota: force-sleep, requested: pods=1, used: pods=0, limited: pods=0
16 times in the last 3 minutes
```
![screenshot from 2017-11-15 08-28-55](https://user-images.githubusercontent.com/642621/32838933-a3d341ae-c9e0-11e7-96f0-ea429f9619e3.png)
![screenshot from 2017-11-15 08-28-25](https://user-images.githubusercontent.com/642621/32838934-a3e84266-c9e0-11e7-9e36-33a53550c161.png)

**Comment by ldimaggi** [comment]
Note - I was not seeing this issue yesterday/last night - seems to be new.

**Comment by l0rd** [comment]
@ldimaggi It looks like for some reason you have a misconfigured namespace (with bad quotas). I have tried on prod and cannot reproduce it (the yaml files are the same). Will try to reproduce it on prod-preview as soon a I get access to it.

**Comment by l0rd** [comment]
@ldimaggi are you able to provide the `fabric8-tenant-che` version of you deployment config (you should see it amongst the dc labels).

**Comment by ldimaggi** [comment]
labels:
      app: che
      group: io.fabric8.tenant.apps
      provider: fabric8
      version: 2.0.55

**Comment by ldimaggi** [comment]
Yes - the quotes look wrong - what would have misconfigured the namespace? Thx!

**Comment by l0rd** [comment]
@aslakknutsen do you have any clue?

**Comment by l0rd** [comment]
I have tried on prod-preview too and I am not able to reproduce. Quotas looks fine:

![image](https://user-images.githubusercontent.com/606959/32843040-0326ffb8-ca1f-11e7-9252-bbbbf1ce5e05.png)

**Comment by ldimaggi** [comment]
So - this is limited to *some* namespaces?

**Comment by ldimaggi** [comment]
After 3 hours this problem became non-reproducible - closing now - will re-open is needed.

**Comment by ldimaggi** [comment]
Re-opening - seeing this again - after a reset - on prod-preview:

```
Error creating deployer pod: pods "che-2-deploy" is forbidden: exceeded quota: force-sleep,
requested: pods=1, used: pods=0, limited: pods=0 
9 times in the last minute
```

But - no quota issues are seen:

![screenshot from 2017-11-16 08-19-26](https://user-images.githubusercontent.com/642621/32893361-275d8676-caa7-11e7-9a5c-741b4bbd529e.png)
![screenshot from 2017-11-16 08-19-09](https://user-images.githubusercontent.com/642621/32893362-2768a11e-caa7-11e7-84a7-e30d1ba87674.png)
![screenshot from 2017-11-16 08-18-50](https://user-images.githubusercontent.com/642621/32893363-2772bda2-caa7-11e7-9fc5-be604111439f.png)
![screenshot from 2017-11-16 08-18-31](https://user-images.githubusercontent.com/642621/32893364-277d3dcc-caa7-11e7-9d78-7544da4a92ff.png)

**Comment by ldimaggi** [comment]
```
Error creating deployer pod: pods "che-1-deploy" is forbidden: exceeded quota: force-sleep,
requested: pods=1, used: pods=0, limited: pods=0
14 times in the last 
```

**Comment by ldimaggi** [comment]
Closing - not seeing this issue on prod-preview today.
