### ISSUE TITLE
Collaborators page has wrong email css when hovering over user

### ISSUE THREAD

**Issue by fbricon** [openshiftio/openshift.io#137]
Minor issue when hovering over a user in the collaborators page
![may-02-2017 12-29-46](https://cloud.githubusercontent.com/assets/148698/25628205/6155f29c-2f33-11e7-9efa-4fc7267093d6.gif)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1346

**Comment by fbricon** [comment]
Upstream issue was closed
