### ISSUE TITLE
Use f8-wit endpoints instead of mock self-generated data

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1370]
The deployments page services should make HTTP requests against the f8-wit API instead of generating mock data.

**Comment by jiekang** [comment]
A WIT repository with the latest prototype API can be found at:
https://github.com/jiekang/fabric8-wit/tree/deployments-api

**Comment by jiekang** [comment]
I think this issue can be closed now. There's still a few pieces of API that are awaiting changes in the backend but they can be tracked in their own issues if needed. @andrewazores thoughts?

**Comment by andrewazores** [comment]
How about I modify the commit message for https://github.com/fabric8-ui/fabric8-ui/pull/2416 so that it closes this issue when merged, and we can create a new tracking issue for the stuff in the card dropdown menu?

**Comment by jiekang** [comment]
That sounds good to me. Thanks!

**Comment by andrewazores** [comment]
Dropdown menu issue here: https://github.com/openshiftio/openshift.io/issues/1969
