### ISSUE TITLE
Split elements into separate directives/components

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1372]
The elements in the deployments page should be split into separate, smaller components that handle their specific task.

**Comment by joshuawilson** [comment]
Are there specific elements this needs to be done to?

**Comment by jiekang** [comment]
Hmm, right. I think this can be split into a separate issue for each element.

At the time this is already done for:

* deployment cards

It should be done for:

* resource usage panel

This can also be done for:

* Elements within the resource panel
E.g. the utilization bars are duplicate content with different data, these could be the same component with constructor setup pointing at the write data provider. The resource panel uses multiple instances of the 1 content so there's less duplication

* Elements within the deployment cards
Same reasoning as above for the repeated charts to be added to the detailed information for each deployment card

**Comment by andrewazores** [comment]
@jiekang yes, that sounds about right to me.

I've created the first sub-task for that here: https://github.com/openshiftio/openshift.io/issues/1385

**Comment by andrewazores** [comment]
IMO, breaking the Resource Usage panel out into a component makes sense, and the cards within that would also be their own component. Call this deployments-resource-usage and deployments-resource-usage-card.

The top half of the view (Applications x Environments grid) can also be a component, again with the cards within also a component. deployments-appenvs and deployments-appenvs-card ? I hope somebody else has a better idea for the name.

Then the top-level component just has a deployments-appenvs and a deployments-resource-usage below (within?) it, and those children are just containers with dynamic card contents and some decoration around them.

Does this sound about right @joshuawilson ?

Once we have the components' layout figured out we can make sure we have the right ideas on how the parents communicate to their children, and then we can see quite easily where and how services/models live or are shared.

**Comment by joshuawilson** [comment]
@andrewazores that sounds like a good plan.

**Comment by jiekang** [comment]
Under: #287
