### ISSUE TITLE
Internal server error when trying to reset my account on PROD Preview - user is blocked on prod-preview

### ISSUE THREAD

**Issue by l0rd** [openshiftio/openshift.io#1377]
This happened the first time I've tried to reset my account on prod preview

![image](https://user-images.githubusercontent.com/606959/32894436-1a320dc4-cadd-11e7-8a48-4f2c23fe2af7.png)

![image](https://user-images.githubusercontent.com/606959/32894516-517f54da-cadd-11e7-923b-73fd4d16abc0.png)

**Comment by aslakknutsen** [comment]
The cause of the 500 "Get http://f8tenant:80/api/tenant: dial tcp 172.30.248.54:80: getsockopt: no route to host"

e.g. req_id: "331bb83d-179b-4654-823f-554671a5551a"

There seems to be a ~10min gap between when a tenant pod was stopped, before the next pod was started.

Coming from a Node eviction

2:37:03 PM "Node controller eviction  Marking for deletion Pod f8tenant-360-1t5x8 from Node ip-172-31-56-253.ec2.internal"

Then it failed for some time to get healthy for unknown reason, was attempted started a few times, then came up.

@jfchevrette

**Comment by joshuawilson** [comment]
@l0rd can you try again? Looks like the Node was down and is back now.

**Comment by l0rd** [comment]
@joshuawilson it works now. Thanks @joshuawilson
