### ISSUE TITLE
Randomly occurring issue - Invalid minute counter shows up in build pipeline

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1378]
This problem is not reproducible at will.

Steps to recreate:
* Create a new app/quickstart
* Observe the build pipeline:

![screenshot from 2017-11-16 09-50-06](https://user-images.githubusercontent.com/642621/32897758-6b5ab418-cab4-11e7-97f1-8f83637e63b8.png)

**Comment by joshuawilson** [comment]
Have you ever seen this on Prod?

**Comment by ldimaggi** [comment]
Only on prod-preview - started seeing it today.

**Comment by ldimaggi** [comment]
Saw this on production on November 28:

![screenshot from 2017-11-28 11-49-10](https://user-images.githubusercontent.com/642621/33379780-ff6ec798-d4e6-11e7-8e5c-5380982ab93f.png)

**Comment by ldimaggi** [comment]
And - just saw it on prod-preview:

![screenshot from 2017-11-29 09-27-58](https://user-images.githubusercontent.com/642621/33379997-ade3fd8e-d4e7-11e7-8ea9-d7414694bdb5.png)

**Comment by qodfathr** [comment]
I have not seen this in a long time. Anyone else?

**Comment by ldimaggi** [comment]
I saw this last week. Let's keep it open for a bit. I will keep an eye open for this and catch a new screenshot.

**Comment by ldimaggi** [comment]
Just saw it again

![screenshot from 2018-01-26 12-31-31](https://user-images.githubusercontent.com/642621/35452577-004185da-0295-11e8-84cd-7bb9bfe121f2.png)

**Comment by ldimaggi** [comment]
![screenshot from 2018-01-26 12-38-05](https://user-images.githubusercontent.com/642621/35452892-2dddf90a-0296-11e8-8cf0-62215e3ccc90.png)

**Comment by joshuawilson** [comment]
48 yrs is a long time to wait for a build

**Comment by joshuawilson** [comment]
@chmouel @pradeepto @rupalibehera any ideas?

**Comment by qodfathr** [comment]
Sure does feel like a sign bug. Any chance that, due to a difference in clocks on two of the systems (e.g. the user's browser and the Jenkins pod), that the elapsed time is being calculated as something like -1 secs? And, if yes, can we either just correctly use unsigned or maybe even just Math.Min() to floor at zero?

**Comment by miteshvp** [comment]
One more
<img width="504" alt="image" src="https://user-images.githubusercontent.com/17736013/36896232-dab74728-1e37-11e8-8299-78cdcdde7075.png">

**Comment by ldimaggi** [comment]
Still seeing this issue:

![screenshot from 2018-04-27 11-29-15](https://user-images.githubusercontent.com/642621/39371017-718ef36a-4a0e-11e8-8b63-efa27b4dd750.png)

Recommending a P0 designation for this issue due to potential user confusion.

**Comment by piyush1594** [comment]
This is a rare intermittent issue. Never happened to me. Not sure where to fix this @sthaha

**Comment by joshuawilson** [comment]
No one can reproduce this and it is rare. I'm going to close it. If someone can reproduce it, please reopen this.
