### ISSUE TITLE
[prod-preview] space creation via wizard is failing

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#1379]
This is quite critical for testing workshop scenario on prod-preview against multi-tenant che-server
![image](https://user-images.githubusercontent.com/1461122/32898839-982ceda0-cae9-11e7-9087-3fc691083f43.png)

**Comment by ibuziuk** [comment]
hmmm... can not repro any more :/

**Comment by alexeykazakov** [comment]
I see 4(!!!) requests for a GH token for this user within one second in Auth backend around the time when the issue was reported. All of them were successful. @joshuawilson can we ask someone to take a look at the wizard? Why we are sending so many requests?

**Comment by alexeykazakov** [comment]
OK. I found a 500 error from Keycloak in the logs a bit earlier that the successful requests above ^^^
Keycloak is not very stable in that endpoint for some reason.. but we can workaround it in Auth service.

**Comment by alexeykazakov** [comment]
I will take care of this error, so it will work even if Keycloak is down. But @joshuawilson it's still worth looking at the wizard to see why we are calling Auth so many times.

**Comment by joshuawilson** [comment]
@alexeykazakov can you please post the question in a new issue.

**Comment by alexeykazakov** [comment]
https://github.com/openshiftio/openshift.io/issues/1386
