### ISSUE TITLE
Landing page link to user doc 404s

### ISSUE THREAD

**Issue by fbricon** [openshiftio/openshift.io#138]
`Learn more using our documentation.` on the [home page](https://openshift.io/_home) opens https://access.redhat.com/documentation/en-us/red_hat_openshift.io/1/html-single/user_guide which is not reachable

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1347

**Comment by RanjithRV** [comment]
@rkratky Looks like this issue should be closed as its linked to https://github.com/openshiftio/openshift.io/issues/912 which is closed as the navigation has been updated is the new page https://docs.openshift.io/ is working fine and does not give a 404 error. Can you please confirm.

**Comment by joshuawilson** [comment]
appears fixed, closing

**Comment by rkratky** [comment]
That's right @RanjithRV. Thanks for taking care of it @joshuawilson.
