### ISSUE TITLE
Intermittent issue - seeing on prod-preview only - in build pipeline, run link is not displayed

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1380]
Started seeing this problem - intermittently - on prod-preview (and not on production) on November 16.

Steps to recreate:
* Create a new app/quickstart, observe the build pipeline, promote to stage/run

![screenshot from 2017-11-16 10-45-10](https://user-images.githubusercontent.com/642621/32901737-8c0c72a0-cabe-11e7-8c22-c63ea1336a5e.png)

**Comment by qodfathr** [comment]
@ldimaggi can we consider this to be a dupe of #508?

**Comment by ldimaggi** [comment]
Closing as a dupe of #508
