### ISSUE TITLE
Intermittent, but recurring build failures being seen on prod-preview

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1381]
To recreate the issue:
* Create a new app/quickstart - observe the Jenkins build log

The failures are happening about 35-50% of the time - the failures are consistently happening here:

```
[INFO] F8: [testnov161510848166384:1.0.1] "vertx": Created docker source tar /home/jenkins/workspace/stnov161510848166384_master-TKIRHIGIKVPAG6EUQ6WM5MJQEUPTJLV6TPBLEYAOO33JTSLM7MBA/target/docker/testnov161510848166384/1.0.1/tmp/docker-build.tar
[INFO] F8: Creating BuildServiceConfig testnov161510848166384-s2i for Source build
[INFO] F8: Creating ImageStream testnov161510848166384
[INFO] F8: Starting Build testnov161510848166384-s2i
[ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:42 min
[INFO] Finished at: 2017-11-16T16:13:04+00:00
[INFO] Final Memory: 29M/46M
[INFO] ------------------------------------------------------------------------
```

See attached production (success) and prod-preview (failure) build logs:

[prod-preview-build.txt](https://github.com/openshiftio/openshift.io/files/1479299/prod-preview-build.txt)
[prod_build.txt](https://github.com/openshiftio/openshift.io/files/1479300/prod_build.txt)

**Comment by ldimaggi** [comment]
This issue is not being seen on production.

**Comment by ldimaggi** [comment]
Issue is being seen by manual and automated EE tests.

**Comment by rajdavies** [comment]
from the logs - looks like the build service is unavailable or timesout

**Comment by rawlingsj** [comment]
Yeah - there may be logs from an s2i build in the Jenkins namespace that gives more info but as @rajdavies said the error is saying it’s the openshift build that fails.

**Comment by kbsingh** [comment]
not really a service delivery thing, the cicd team will need to investigate

**Comment by rajdavies** [comment]
Its not a build problem - removed CD from this issue

**Comment by joshuawilson** [comment]
@ldimaggi are you still seeing this? has it been reported in one of the other issues?

**Comment by ldimaggi** [comment]
Closing - problem is no longer seen. Thx!
