### ISSUE TITLE
Rename Applications page to Deployments

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1382]
The Applications page is being updated with new content and should be titled 'Deployments', at the least in the tab under 'Create', if not throughout the code itself (file names and contents).

**Comment by joshuawilson** [comment]
@catrobson did we finalize on changing the name from `applications` to `deployments`?

**Comment by catrobson** [comment]
Yes, we have.

**Comment by andrewazores** [comment]
See https://github.com/openshiftio/openshift.io/issues/1397

**Comment by andrewazores** [comment]
@joshuawilson what do you want to do with this issue now that the old Applications and the new Deployments are living side-by-side while under development? Would the acceptance criteria be "when Deployments is complete and Applications is removed" now?

**Comment by jiekang** [comment]
@andrewazores I think this issue can be considered 'done' now. Deployments being completed and Applications removed is really the whole task at hand, and I don't think this issue is right for it.

**Comment by andrewazores** [comment]
@jiekang yes, true. @joshuawilson ping, thoughts? Can we close this?

**Comment by joshuawilson** [comment]
I think you covered it with the new name. Closing.
