### ISSUE TITLE
Move fabric8-analytics deployment scripts and documentation to a separate repository

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1383]
# Description

Currently all f8a deployment scripts and documentation resides in https://github.com/fabric8-analytics/fabric8-analytics-common, together with E2E tests and other things (don't ask why:)). I think it would be better to move it to a separate repository so it is easier to find.

# Acceptance criteria
- [x] f8a deployment scripts and documentation has been moved to a separate repository

**Comment by msrb** [comment]
@tisnik @humaton what do you guys think?

**Comment by tisnik** [comment]
@msrb I'm ok with it.
