### ISSUE TITLE
Split  "Resource Usage" panel into component

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#1385]

**Comment by c-koehler** [comment]
@andrewazores Would you say this issue is fixed by this: https://github.com/fabric8-ui/fabric8-ui/commit/ae6c38279f297e124a8b43a2c2271ba426b981f6

**Comment by andrewazores** [comment]
No, not quite. Splitting out the resource cards is the majority of it 
though, but I think moving the collapsible div out of the main component 
HTML makes some sense too. It's a pretty small task now that you've done 
the resource card so please feel free to knock this one out too :)

**Comment by c-koehler** [comment]
@andrewazores @jiekang Following up: I will do the final part from the comments today on the extraction of the collapsible piece to complete this now that the main one was merged in.
