### ISSUE TITLE
Changing logins

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#1387]
From a new user:
"If I want to keep my openshift.io account but have changed companies with a new redhat login how do I do that? "

**Comment by alexeykazakov** [comment]
You can change your email in developers.redhat.com - https://developers.redhat.com/auth/realms/rhd/account/ so you will be able to login using the new email.
But OSIO do not support changing emails in OSIO user profile atm - https://github.com/fabric8-services/fabric8-auth/issues/62. And it means that the OSIO notifications will go to the old email. The rest should work.

**Comment by joshuawilson** [comment]
What about changing RHD accounts?

**Comment by alexeykazakov** [comment]
New RHD account == new OSIO account. I don't think we will ever support changing RHD accounts for OSIO accounts. We should rather move to even closer relation between these two accounts.
It's like "hey, I created a new Google account. Can I use tight it to my old gmail account?"

**Comment by alexeykazakov** [comment]
What's this issue about actually? Is it about updating email? Then it's not SEV2 (Important and should be done before any work on features).
If it's about changing RHD accounts then I don't think we will support it.

**Comment by joshuawilson** [comment]
I shouldn't have put the SEV on it to begin with. That is why I removed it.

**Comment by joshuawilson** [comment]
I also think you answered the question. Let's close it and reopen if needed.
