### ISSUE TITLE
Developer poll seems hard coded

### ISSUE THREAD

**Issue by fbricon** [openshiftio/openshift.io#139]
Developer poll on https://openshift.io/_home seems hard coded. It resets after the page is reloaded. Seems like a left over mockup piece. Either make it functional or remove it, since the website is now live.

**Comment by joshuawilson** [comment]
It was a space filler and there are UX plans to replace it.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1348

**Comment by joshuawilson** [comment]
This was removed a while ago.
