### ISSUE TITLE
On https://openshift.io, "Log out" menu item is seen after a user logs out

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1390]
Started seeing this late on November 17 - steps to recreate:
* Log out of https://openshift.io
* Observe the "LOG OUT" item in the top level menu bar:

![screenshot from 2017-11-17 09-12-59](https://user-images.githubusercontent.com/642621/32951846-640159f4-cb79-11e7-98af-7ad1cde76f13.png)

**Comment by joshuawilson** [comment]
@mindreeper2420 this looks like a result of the latest changes that you made. Can you please take a look.

**Comment by mindreeper2420** [comment]
@joshuawilson - there is some brutal caching or logging issue going on. This works without issue using incognito or private mode (depending on browser). This didn’t occur running locally outside of incognito.

A similar issue happened when the design refresh was done. It took hours/days for the site to load properly.

**Comment by joshuawilson** [comment]
@ldimaggi can you please do a hard refresh and try again.

**Comment by ldimaggi** [comment]
OK - it's gone now - thx!
