### ISSUE TITLE
Add onboarding doc

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#1392]
We need to get the onboarding PDF file available via an openshift.io URL. Anticipate the need to replace the PDF with newer versions in the future. 

This will be a temporary solution, even if something as simple as "openshift.io/gettingstarted.pdf" can serve up a static file. 

This file must NOT be blocked by login; it needs to be accessible to all

**Comment by joshuawilson** [comment]
@mindreeper2420 do you think this is something you can do? You can get the doc from @qodfathr.

**Comment by mindreeper2420** [comment]
@joshuawilson sure - is there a thought as to where this link would exist, or would it jsut be shared in a doc/email of some kind?

**Comment by joshuawilson** [comment]
@qodfathr do you have an opinion?
@catrobson any thoughts?

**Comment by catrobson** [comment]
@rkratky - do you have any HTML based open source tools that you use for docs like this that we might look at for the openshift.io webpage?  Would need to be a quick, lightweight, option so we could get the doc into it and stand it up quickly.

@qodfathr is there a requirement to need to be able to make edits to this as things change in the service as well?  If so we probably either need to point to a doc, or have a markdown based situation where Todd or others could easily make edits and get those onto the site without going through UXD every time.

**Comment by mindreeper2420** [comment]
@catrobson The thought after talking with @qodfathr is to have a PDF hosted on the landing page, with a simple URL. Updates to that file would only take a PR of a new PDF. The URL wouldn't be shared anywhere on the landing page or inside the product.

I'm open to other ideas, just wouldn't want it to be so complicated that it requires a chunk of changes to the overall config of the landing page.

**Comment by catrobson** [comment]
@mindreeper2420 thanks - that sounds good to me.

**Comment by qodfathr** [comment]
This is essentially a temporary solution to meet an **immediate** need. We absolutely need to move to a more flexible, "HTML-based" solution longer term.

**Comment by qodfathr** [comment]
@mindreeper2420 is /osiogettingstarted.pdf an acceptable filename / URL? I have a revised document (slightly different than the one I shared with you earlier) if you want to tell me into which directory in the repo to place it. I'll fork and generate a PR based upon your instructions.

**Comment by mindreeper2420** [comment]
@qodfathr the PR is in place (#1396) for this addition. I've added it to the route of the directory, so that it is a lot easier to access. Once that PR is merged, you can create a PR for that file, and it will update accordingly.

**Comment by rkratky** [comment]
@catrobson, @joshuawilson, we already have our docs (including an onboarding doc) built as both HTML and PDF. You can see that at https://docs.prod-preview.openshift.io/ -- these get automatically rebuilt with every update.

This is ready to be deployoed on doc.openshift.io whenever we get the go-ahead from Todd.

**Comment by qodfathr** [comment]
@rkratky the user guide and on boarding documentation you reference were based, in part, upon other non-canonical (e.g. the first several revisions of the workshop document) or outdated sources (e.g. the glossary) and, as such, has issues related to the naming of things, the messaging behind certain capabilities, etc. Not a fault of the documentation team, but it will take some degree of effort to correct it. I'd ask that my revised getting started guide be used to help fix some of these issues (if only to fix naming issues). (e. g. OSIO has neither Projects nor Collaboration Spaces, both of which are older, deprecated terms.) 

Furthermore, I feel we need more documentation which explains the "why's" of OSIO; today there is a lot of "how's", but I feel that important, high level messages are being lost. Something like a "day in the life" story could possibly help.

**Comment by rkratky** [comment]
> but it will take some degree of effort to correct it. I'd ask that my revised getting started guide be used to help fix some of these issues

@qodfathr, we're working on that right now. That said, it would be of great help if people could start filing issues in https://github.com/fabric8io/fabric8-online-docs/issues

> Furthermore, I feel we need more documentation which explains the "why's" of OSIO; today there is a lot of "how's", but I feel that important, high level messages are being lost. Something like a "day in the life" story could possibly help.

I filed https://github.com/fabric8io/fabric8-online-docs/issues/70 -- more input/details would be appreciated.

**Comment by qodfathr** [comment]
Verified in prod.
