### ISSUE TITLE
Openshift.io landing page asks logged-in users to sign up

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#1393]
1. Open your browser in incognito mode to make sure there is no any cache issues involved
2. Login to OSIO
3. go to openshift.io

- I'm still logged-in but the first thing I see is a big red button: "Sign up for preview".
- It's quite hard to figure out what you have to do to get back to the home page (you have to click on your name).

![newflow](https://user-images.githubusercontent.com/620087/32957839-a2900628-cb71-11e7-9be6-af4498e2f064.png)

**Comment by joshuawilson** [comment]
@catrobson @mindreeper2420 can we get someone to look at this new UX flow, please? It is very awkward.

**Comment by mindreeper2420** [comment]
@catrobson do we want to return this to what it was a while back, with a "HOME" link added to the navbar, and the "Sign Up for the Preview" button hidden when logged in?

**Comment by mindreeper2420** [comment]
A fix will be coming that will update the handling of redirects. Should be in by the beginning of next week.

**Comment by joshuawilson** [comment]
great, thanks

**Comment by mindreeper2420** [comment]
@joshuawilson was this solved by @dgutride's PR?

**Comment by alexeykazakov** [comment]
I see it now redirects to _home after hard refresh .The fact that hard refresh is still required after UI updates is another issue. Closing.
