### ISSUE TITLE
[2] Configure SQS queues only once per deployment

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1398]
# Description

Currently we configure SQS every time when worker container starts. We can have dozens of worker containers and thus we'd be configuring SQS from all of them, at the same time. And we do it once again when containers get restarted. This was implemented recently and I noticed a lot of "Request is throttled" error messages in logs.

I think we should configure queues only once per deployment, for example in a [pre-hook](https://docs.openshift.com/container-platform/3.6/dev_guide/deployments/deployment_strategies.html#pod-based-lifecycle-hook).

# Acceptance criteria
- [x] queues are configured only once per deployment
- [x] these changes are running in production

**Comment by msrb** [comment]
@jpopelka @pkajaba @tuxdna @humaton 

Team, if you're done with your current tasks, please take a look here. We still have couple more days in this sprint.

I _think_ this should be fairly trivial to implement. We basically want to take [this](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/hack/workers.sh#L55) and run it [here](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/openshift/template.yaml#L26). :)

**Comment by jpopelka** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/468

**Comment by msrb** [comment]
This is done, thanks @jpopelka 😉
