### ISSUE TITLE
Open source Spaces on OpenShift.io may be browsed anonymously

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#1399]
When the user is not logged in or viewing someone else's account there are certain fields and elements that they can NOT access. These elements need restricting.

@catrobson has a list that we can start with at: https://docs.google.com/a/redhat.com/spreadsheets/d/1cNSDuek0v1EBPpdPlFwG_Y_yOlux86m9MYf9UrF82l4/edit?usp=drive_web

## Parent Scenario
#2159 A world of open source Scenario placeholder

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2064
