### ISSUE TITLE
No way to open the OpenShift console or Jenkins?

### ISSUE THREAD

**Issue by fbricon** [openshiftio/openshift.io#140]
There's no link to the openshift console that I could find, or to Jenkins.

I'm trying to figure out how to fix my zombie pipelines from #130

**Comment by fbricon** [comment]
I finally found a link to the OpenShift Console from the Pipelines page. Dunno how I missed it. Maybe it could be made more prominent?

**Comment by joshuawilson** [comment]
The UI has changed even further and now each pipeline has a link to the OpenShift console.
