### ISSUE TITLE
Stack-report shows blank if result comes as empty list in response of stack-analysis call

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#1407]
Stack-report shows blank if result comes as empty list in response of stack-analysis call as in 

![image](https://user-images.githubusercontent.com/5129024/33012696-b28b6520-ce07-11e7-9c4d-04f75d77b2fe.png)

To reproduce need to make STACK-ANALYSIS POST call and make a call to stack-analysis GET call this can be seen as intermediate response.

**Comment by jyasveer** [comment]
@invincibleJai what do we mean here by 'Stack report shows blank' ?

**Comment by invincibleJai** [comment]
@jyasveer sorry this has been taken care of , closing it.
