### ISSUE TITLE
Can't delete *-jenkins project in OpenShift

### ISSUE THREAD

**Issue by fbricon** [openshiftio/openshift.io#141]
All projects can be deleted in OpenShift, except for `Project 'fbricon-jenkins'' could not be deleted.User "fbricon@redhat.com" cannot delete projects in project "fbricon-jenkins"`

Behaviour should be consistent for all OpenShift projects

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1350

**Comment by jstrachan** [comment]
the `-jenkins` + `-che` namespaces are owned by openshift.io; am not sure we should let users be able to delete them.

**Comment by aslakknutsen** [comment]
All namespaces are now locked down. Closing.
