### ISSUE TITLE
Status did not go green, can't use the system

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#1414]
A new user logged in and their status had the grey half circle. It did not update after a `tenant update`or `reset env`.

**Comment by ldimaggi** [comment]
They probably do not have pod logs for Che/Jenkins - are any events visible in OSO?

**Comment by joshuawilson** [comment]
User was able to create a custom project, making an account that had to be removed to use OSIO.

**Comment by joshuawilson** [comment]
Closing as the user account was fixed. Needed to remove manually created project in OSO.

being worked at #1031

**Comment by joshuawilson** [comment]
The account was not fully fixed.

**Comment by joshuawilson** [comment]
Closing as this is now being tracked by #1415
