### ISSUE TITLE
User blocked has tenant service still has entries for him

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#1415]
user `mmclane` is blocked because the tenant service has entries for Che and Jenkins for his previous project. The `env reset` procedure did not reset all the data, and manually removing the projects was not enough.

**Comment by xcoulon** [comment]
Status for his account: 
![image pasted at 2017-11-20 14-58](https://user-images.githubusercontent.com/178502/33043843-0ea94b6c-ce47-11e7-8a82-7ff5c26b4235.png)

**Comment by mmclanerh** [comment]
Created an empty project in OSO before initiating OSIO.    Removed that project (learned that is a known issue: https://github.com/openshiftio/openshift.io/issues/1031).   The OSIO projects are still active in OSO:

![image](https://user-images.githubusercontent.com/33727536/33043954-54236e36-ce04-11e7-99a8-47bad613f113.png)

**Comment by pbergene** [comment]
Synced with @xcoulon - waiting for @mmclanerh to come on today and we'll walk through the steps required to clean out the tenant DB.

**Comment by xcoulon** [comment]
The awesome @pbergene cleaned the `tenant` database with the remaining entries for @mmclanerh entries (1 entry in the `tenants` table and 4 entries in the `namespaces` table, for the `-che`, `-jenkins`, `-stage` and `-run` projects on OSO), then he deleted the corresponding projects on OSO using the `devtools-sre-tools` account, since those 4 remaining projects did belong to this SA user and not to @mmclanerh himself.
