### ISSUE TITLE
On prod-preview, cannot log into OSO (e.g., to view build logs)

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1416]
Steps to recreate:
* On prod-preview, create new app/quickstart
* Attempt to view build log - observe this menu:

![screenshot from 2017-11-20 22-18-06](https://user-images.githubusercontent.com/642621/33053279-b662c4ca-ce40-11e7-9087-18859911291c.png)

Attempting to login fails:

![screenshot from 2017-11-20 22-18-49](https://user-images.githubusercontent.com/642621/33053301-cf0f4e30-ce40-11e7-9d50-e1507cb67b43.png)

**Comment by alexeykazakov** [comment]
What button did you click? I clicked on the top one and it worked.

**Comment by alexeykazakov** [comment]
@kbsingh is this something the SD team can look at? Something is wrong with free-int cluster.

**Comment by alexeykazakov** [comment]
free-int (OSO) is experiencing issues

**Comment by ldimaggi** [comment]
The top button is not working for me - it just loops back to the same login page.

**Comment by kbsingh** [comment]
this looks to have been a transient issue with free-int, should have cleared.

**Comment by ldimaggi** [comment]
Closing - I was just able to login.

**Comment by alexeykazakov** [comment]
It seems that issue is back

**Comment by c-koehler** [comment]
I was getting this last Friday, now when I go to prod-preview and try to link my OSO account, it won't redirect to the keycloak auth page.

I have the same issue that shows up on the first image at the top of this issue.

**Comment by ldimaggi** [comment]
This problem had been resolved - but - as of this morning I am seeing it again. After selecting "View Log," the user is directed to this sequence of screens:

![screenshot from 2017-12-11 10-06-42](https://user-images.githubusercontent.com/642621/33837731-5115df82-de5b-11e7-8215-45c2c8d96f3d.png)

![screenshot from 2017-12-11 10-07-12](https://user-images.githubusercontent.com/642621/33837730-5106849c-de5b-11e7-82b0-b6cb45555da8.png)

![screenshot from 2017-12-11 10-07-56](https://user-images.githubusercontent.com/642621/33837729-50dcfadc-de5b-11e7-959c-601df7a28e5a.png)

**Comment by ldimaggi** [comment]
Closing - not seeing this issue on prod-preview today.
