### ISSUE TITLE
README doesn't say what this repository contains

### ISSUE THREAD

**Issue by jaseemabid** [openshiftio/openshift.io#1417]
Can we add a top level heading? Is this marketing pages? What else do we have here?

**Comment by joshuawilson** [comment]
The code for this repo is just the marketing page. However, since the repo has the same name as the application it started to be a place where people posted issues. Out of that the dev team decided to openly track all work items/issues/bugs in this repo.

**Comment by jaseemabid** [comment]
@joshuawilson Sent a PR https://github.com/openshiftio/openshift.io/pull/1418

**Comment by joshuawilson** [comment]
Thanks for the PR, merged. Closing this issue.
