### ISSUE TITLE
Creating/Deleting spaces doesn't update the top left menu

### ISSUE THREAD

**Issue by fbricon** [openshiftio/openshift.io#142]
Creating/Deleting spaces doesn't update the top left menu, which can lead to situations like this, where the menu is missing spaces :
<img width="544" alt="screen shot 2017-05-02 at 2 52 05 pm" src="https://cloud.githubusercontent.com/assets/148698/25634021/24711e1a-2f47-11e7-97f1-cf4df5f3b500.png">

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1351

**Comment by mvulavak** [comment]
Closing this issue as the associated Issue #1351 was closed.
