### ISSUE TITLE
Text element to select a github repo is confusing

### ISSUE THREAD

**Issue by jaseemabid** [openshiftio/openshift.io#1421]
Please see the attached screenshots. The white block area to the left of the filter icon looks like a text area but its not. Clicking on the filter opens up a real text area underneath which looks ugly. 

Suggestions: 

   1. Make the white block actually a text area and avoid the extra space that pops below. 
   2. Make sure user can type there without actually clicking the tiny icon.

![screenshot from 2017-11-21 14-41-59](https://user-images.githubusercontent.com/601714/33064106-a0164ec8-ceca-11e7-80a5-16494c190cd5.png)
![screenshot from 2017-11-21 14-42-12](https://user-images.githubusercontent.com/601714/33064107-a04a88dc-ceca-11e7-9266-132999dd3269.png)

**Comment by joshuawilson** [comment]
@slemeur can you please take a look at this? Who is doing UX on this?

**Comment by jaseemabid** [comment]
Update. Suggestion 3.  

It might be a good idea to just remove the tiny icon and have a filter that is always active.

**Comment by qodfathr** [comment]
Closing as dupe #543. This particular issue isn't fixed per-se, but a whole new design is coming (see 543 for details).
