### ISSUE TITLE
[multi-tenant] Che status should be obtained not from user namespace, but from dsaas / rh-idev

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#1423]
Currently, for multi-tenant che users, status is still obtained from *-che namespace and not from dsaas / rh-idev wheremulti-tenant che is deployed:

![image](https://user-images.githubusercontent.com/1461122/33079890-0694f936-ced7-11e7-93a4-6c29548f63e8.png) 

We could possibly treat this as a known issue since the whole migration is going to happen in the next few weeks and there is no API for obtaining the user status (multi-tenant / single-tenant) from wit. However, before the multi-tenant migration is finished che status should be obtained not from user namespace, but from dsaas / rh-idev, so that multi-tenant che-sever status would be reflected correctly

Also, Multi-tenant che status should be taken into account as a part of fabric8 UX status page user story 
[1] https://github.com/fabric8-ui/fabric8-ux/issues/729

**Comment by ibuziuk** [comment]
@slemeur @qodfathr do you agree that we could treat status icon as a know issue for multi-tenant users and switch to using multi-tenant status before the major migration ?

**Comment by qodfathr** [comment]
We either need to get the status indicating working properly against the multi-tenant server, or we need to remove this status icon temporarily until we've got it working against the mutli-tenant server. It will cause a lot of support problems if users do not see a green checkmark when everything is operating nominally.

My preference is that we get the status checkmark to report correctly for the multi-tenant server.

**Comment by qodfathr** [comment]
Setting to SEV-3 for now, but will become SEV-2 or SEV-1 if we do not have this addressed when the mass migration begins.

**Comment by ibuziuk** [comment]
@joshuawilson @xcoulon could you please point to the place in the code where che status is currently obtained ?

**Comment by joshuawilson** [comment]
@ibuziuk here is a starting point for you https://github.com/fabric8-ui/fabric8-ui/blob/master/src/a-runtime-console/kubernetes/ui/status/status-list.component.ts#L98

**Comment by ibuziuk** [comment]
@joshuawilson it was decided to hide [1] che status icon temporary for now as a first step. Could you point to the place where we could use `hidden` attribute for che status info ?


[1] https://github.com/redhat-developer/rh-che/issues/449

**Comment by ibuziuk** [comment]
PR is sent - https://github.com/fabric8-ui/fabric8-ui/pull/2268

**Comment by qodfathr** [comment]
Can this be closed? Also, is the intent to bring the Che version number back to the status widget? If yes, is there an issue filed for this yet? (I searched but did not find anything, but it's easy to not find things in GitHub.)

**Comment by ibuziuk** [comment]
@qodfathr yeah, I think we can close it - version of the service (not only che) should be obtained as part of  https://github.com/openshiftio/openshift.io/issues/1870
