### ISSUE TITLE
Scrollbar appears when context menu of an issue is opened in planner backlog

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#1424]
Sorry if this issue is a duplicate, couldn't find anything when searching with "scroll". I have only two issues in the backlog, but when I open the context menu for one of them the menu is not visible fully, instead a scrollbar appears in the view that contains just the two issues.

I don't think this behavior is desired, is it?

<img width="1680" alt="screen shot 2017-11-21 at 11 48 44 pm" src="https://user-images.githubusercontent.com/5445560/33089615-2ff84176-cf17-11e7-926a-2fdf0c963ae9.png">

**Comment by qodfathr** [comment]
Closing as this menu no longer exists.
