### ISSUE TITLE
On prod-preview, env reset failing - Che and Jenkins pod not starting after an environment reset - reproducible

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1426]
Seeing errors similar to this in the event log:
```
Error creating deployer pod: pods "che-3-deploy" is forbidden: exceeded quota: 
force-sleep, requested: pods=1, used: pods=0, limited: pods=0
10 times in the last 
```

**Comment by ldimaggi** [comment]
Steps to reproduce:
* Reset the user environment

**Comment by ldimaggi** [comment]
![screenshot from 2017-11-21 19-37-55](https://user-images.githubusercontent.com/642621/33103962-80acec76-cef3-11e7-9a26-967100d35d4b.png)

**Comment by ldimaggi** [comment]
Updated on November 22 - Now, the env reset is failing - and neither the Che nor Jenkins pods are restarting on prod-preview. This error is not being seen on production.

**Comment by alexeykazakov** [comment]
free-int is down

**Comment by ldimaggi** [comment]
Closing as this problem was resolved. Question - do we have any active monitoring of free-int? Thanks!
