### ISSUE TITLE
Not able to calculate license for quickstarter application stack

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1427]
Pleas see the screenshot : 

<img width="1345" alt="screen shot 2017-11-22 at 10 03 27 am" src="https://user-images.githubusercontent.com/15967765/33110243-9424421c-cf6c-11e7-98cd-77b6b5c78523.png">

**Comment by sunilk747** [comment]
refer #1472

**Comment by sunilk747** [comment]
https://github.com/openshiftio/saas-analytics/pull/182 fixes this issue.

**Comment by miteshvp** [comment]
@krishnapaparaju - closing this issue as we have added the support to cover licenses for all OSIO quick starts. Feel free to reopen if you see any issues.
