### ISSUE TITLE
Stack report: Label texts need to be revamped for better understanding (UX)

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1428]
<img width="1330" alt="screen shot 2017-11-22 at 10 06 29 am" src="https://user-images.githubusercontent.com/15967765/33110336-34dbdd3c-cf6d-11e7-8a57-5634226f3aec.png">

There are couple of labels which do not make sense, eg: 'Conflict with in a component'

**Comment by invincibleJai** [comment]
@krishnapaparaju Changes are in Prod now.

**Comment by krishnapaparaju** [comment]
Looks good. thanks @invincibleJai .. closing this issue...
