### ISSUE TITLE
Incorrect usage outliers show up at stack report

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1429]
Take any quick start application, run the stack report two times : (a) with no changes at current pom.xml (b) remove some packages at pom.xml. New usage outliers show up in (b) that do not show up at (a).

**Comment by rootAvish** [comment]
@sivaavkd Spills to 142, related to #1471, need to have a clear acceptance criteria around the same.

**Comment by rootAvish** [comment]
@abs51295 Since you're coding the outlier logic you might want to assign yourself here.

**Comment by abs51295** [comment]
The following PR solves this issue: https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/168.

**Comment by abs51295** [comment]
PR has been merged and the new logic works fine on staging. Sent a PR to saas-analytics in order to push it to production: https://github.com/openshiftio/saas-analytics/pull/193

**Comment by abs51295** [comment]
Pushed to Prod. Thanks.
