### ISSUE TITLE
No way to recover from  *cough* accidental *cough* OpenShift project deletion

### ISSUE THREAD

**Issue by fbricon** [openshiftio/openshift.io#143]
Because this user doesn't know what he's doing, (following #130 and #141), some critical, missing OpenShift projects prevent new spaces from being operational, even though a git project was successfully created

<img width="469" alt="screen shot 2017-05-02 at 2 56 27 pm" src="https://cloud.githubusercontent.com/assets/148698/25634320/23fb470c-2f48-11e7-9803-f3e5b47e0839.png">

Either openshift.io should be able to recover from that state (recreate the missing openshift projects) or prevent these projects from being "accidentally" deleted.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1352

**Comment by fbricon** [comment]
Upstream issue was closed
