### ISSUE TITLE
No Categories shown for basic vertx packages

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1430]
Please check this screenshot:

<img width="1351" alt="screen shot 2017-11-22 at 10 40 47 am" src="https://user-images.githubusercontent.com/15967765/33111020-b43b6d50-cf71-11e7-8ff0-c3ca2e0e10fc.png">

**Comment by samuzzal-choudhury** [comment]
The PR https://github.com/fabric8-analytics/fabric8-analytics-server/pull/216 has been merged for this.

**Comment by samuzzal-choudhury** [comment]
@krishnapaparaju  The fix is on the prod cluster ATM. Closing this bug. Please feel free to reopen if you think otherwise.

![image](https://user-images.githubusercontent.com/17740190/33175276-387409d2-d081-11e7-8c24-8d917917db30.png)
