### ISSUE TITLE
Quick-add Work Item behavior is unexpected

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#1431]
I used the quick add fields to create a new Work Item (bottom of the Planner view, see screenshot) and it worked as expected. After creating the WI, I changed the Work Item type to Bug to create a new WI. Unexpectedly, the WI name and description fields retained the values I added for the previous (already created) Work Item. Moreover, the text for the name field is greyed out but still displays the old information, and when I mouse over it, the mouse icon becomes a Not Available icon (also in screenshot).

![work_item_odd_behavior](https://user-images.githubusercontent.com/926572/33112276-21c4045a-cf9e-11e7-9e07-21f544e39c96.png)

Expected behavior is that the fields should be cleared (reset) after the first WI was created and I should be able to edit them to add the details for my second Work Item.

**Comment by rgarg1** [comment]
Fixed!
