### ISSUE TITLE
"Error syncing pod" for workers in staging

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1433]
# Description

E2E tests have [started failing](https://ci.centos.org/job/devtools-f8a-master-deploy-e2e-test/387/console) for workers recently. The root cause seems to be that the pods can spend 10+ minutes in "Container creating" state. We need to investigate and fix this problem.

**Comment by msrb** [comment]
@vpavlin just told me that rh-idev lacks resources. That could explain the problem...

**Comment by samuzzal-choudhury** [comment]
@msrb can this be closed as it is not related to the analytics application?
