### ISSUE TITLE
User blocked with an existing OSO project

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#1436]
User @abs51295 is blocked with an existing OSO project that he created during a workshop before starting on OSIO:

![openshift-web](https://user-images.githubusercontent.com/178502/33120867-98e93080-cf73-11e7-99a0-bf77795d8524.png)

Project has since been deleted, but the setup remains incomplete.

**Comment by joshuawilson** [comment]
is this fixed?

**Comment by pbergene** [comment]
This is not yet fixed, we will be doing these cleanups manually in weekly batches starting Monday.  For it to be successful @abs51295 needs to delete their 'Capstone Project' and we will clear the tenant database, remove all other projects and the account will be re-initialized on next login.  The work in https://github.com/openshiftio/openshift.io/issues/1031 should remove the need for this manual job.

**Comment by pbergene** [comment]
This account should now cleanly re-initialize on next relogin if there are no projects in openshift.com. cc @abs51295 @joshuawilson @xcoulon

**Comment by joshuawilson** [comment]
Closing for now. Thanks for the clean up.
