### ISSUE TITLE
Blocked with an existing OSO project: @ssamal

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#1437]
similar to #1436

**Comment by sunilk747** [comment]
@sbose78 @xcoulon

**Comment by joshuawilson** [comment]
@pbergene

**Comment by joshuawilson** [comment]
@sunilk747 please post back when this is cleared.

**Comment by pbergene** [comment]
I could not find any projects on openshift, assuming these have been deleted.  Entries removed in tenant service. This account should now cleanly re-initialize on next relogin if there are no projects in openshift.com. cc @sunilk747  @joshuawilson @xcoulon

**Comment by sunilk747** [comment]
@pbergene @joshuawilson  Yeah. I am unblocked now. Should I close this issue?

**Comment by pbergene** [comment]
Great! Closing - ping me if it turns out it didn't create the projects correctly. Keep in mind that you currently need a 'reset tenant' after init to get che up and running.
