### ISSUE TITLE
Extend API for interaction with Che workspaces

### ISSUE THREAD

**Issue by ashumilova** [openshiftio/openshift.io#1439]
There is need to expose Che workspace API (https://github.com/fabric8-services/fabric8-wit/blob/master/codebase/che/client.go) with the following items:
- [ ] ability to stop workspace
- [ ] ability to create workspace pointing the repository branch ? (maybe here changes for codebases are needed as well to be identified by source location + branch)
- [ ] ability to delete workspace 
- [ ] ability to handle workspace statuses
- [ ] add project info (branch / repo) while getting the list of workspaces

**Comment by joshuawilson** [comment]
@xcoulon Can you work with @ashumilova to get these API's added?

**Comment by ashumilova** [comment]
Adding some additional information:
1. Workspace creation in che-starter already has ability to handle the branch https://github.com/redhat-developer/che-starter/blob/master/src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java#L150,
and the WIT API too - https://github.com/fabric8-services/fabric8-wit/blob/master/codebase/che/client.go#L396, so here will need to provide branch information from  https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/create/codebases/services/workspaces.service.ts#L34
2. Workspace stop - should be added both to Che starter and WIT API - same as for https://github.com/fabric8-services/fabric8-wit/blob/master/codebase/che/client.go#L237
3. Workspace start - should be added to WIT API
4. Workspace statuses - could be provided by posting more Che workspace information to client.

**Comment by joshuawilson** [comment]
@ashumilova is there anyone on your team that can do this work?

**Comment by gorkem** [comment]
@l0rd @ibuziuk Do we still need to use WIT API or che-starter for workspace operations? Wouldn't it be OK for these UIs to deal with Che server nowadays?

**Comment by joshuawilson** [comment]
What is the status of this? It is blocking #2291

**Comment by ibuziuk** [comment]
@ashumilova am I correct that after merging PR to wit [1] which would add "self" / "ide" links and status info it would be enough for UI to handle the following operations directly without calling wit:

- status
- stop
- delete

[1] https://github.com/fabric8-services/fabric8-wit/pull/1893

**Comment by ashumilova** [comment]
@ibuziuk hi, yes - will try, thank you

**Comment by joshuawilson** [comment]
@ibuziuk have you done everything needed here? What is left?

**Comment by ibuziuk** [comment]
PR for listing project info - https://github.com/fabric8-services/fabric8-wit/pull/1914
PR for possibility of specifying branch during workspace creation https://github.com/fabric8-services/fabric8-wit/pull/1915

**Comment by ibuziuk** [comment]
> Do we still need to use WIT API or che-starter for workspace operations? Wouldn't it be OK for these UIs to deal with Che server nowadays?

During PR [1] discussion with @aslakknutsen this was considered as fundamentally wrong approach. The right one would be using the following arch:

> UI -> wit -> che-starter / che-adapter -> che-host 

Pros of the approach:
- the reason why Che has been stable from an OSiO perspective is because of the role CheStarter has been playing. 
- the Che upstream team could completely change their deployment structure with no impact on anyone else becasue of CheStarter. Good example is switch osio on che6 [2] / CheStrarter provides stable API & CheServer does not
- Future integation with codebases (CodeHost|CodeEdit|CodeHostEditIntegration) provide the stable OSiO API for internal and external usage

@ashumilova self / ide links already available and UI can call che-server directly, but it looks like it is the approach we should avoid. WDYT ?

[1]  https://github.com/fabric8-services/fabric8-wit/pull/1893
[2]  https://github.com/redhat-developer/che-starter/issues/257

**Comment by ibuziuk** [comment]
Current status of this issue:

The following PRs were merged:
- https://github.com/fabric8-services/fabric8-wit/pull/1893
- https://github.com/fabric8-services/fabric8-wit/pull/1914
- https://github.com/fabric8-services/fabric8-wit/pull/1915

payload provided by GET `codebaseID/workspaces` endpoint:

```
"attributes":{  
   "description":"",
   "id":"workspacev4dva7dj2twny0nt",
   "name":"zicoa",
   "status":"STOPPED"
},
"links":{  
   "ide":"https://che.prod-preview.openshift.io/ibuziuk@redhat.com/zicoa",
   "open":"http://localhost:8080/api/codebases/a8b0da3f-8309-409e-9ed2-db3172f92c41/open/zicoa",
   "self":"https://che.prod-preview.openshift.io/wsmaster/api/workspace/workspacev4dva7dj2twny0nt"
},
"relationships":{  
   "codebase":{  
      "links":{  
         "related":"http://localhost:8080/api/codebases/a8b0da3f-8309-409e-9ed2-db3172f92c41"
      },
      "meta":{  
         "branch":"test"
      }
   }
},
"type":"workspaces"```
Optional payload for POST `/:codebaseID/create` endpoint:

```
{
    "data": {
        "attributes": {
           "branch": "master"
        }
    }
}
```

- [ ] ability to stop workspace 
currently should be done via self / ide workspace links (direct manipulations with che server). Should be reworked as part of https://github.com/openshiftio/openshift.io/issues/2745
- [ ] ability to delete workspace 
currently should be done via self / ide workspace links (direct manipulations with che server). Should be reworked as part of https://github.com/openshiftio/openshift.io/issues/2745
- [ ] ability to create workspace pointing the repository branch ? (maybe here changes for codebases are needed as well to be identified by source location + branch)
Optional payload for POST `/:codebaseID/create` endpoint
- [ ] ability to handle workspace statuses
Status is provided in wokspace attribute of GET `codebaseID/workspaces`
- [ ] add project info (branch / repo) while getting the list of workspaces
branch is provided in `relationships.codebase.meta` GET `codebaseID/workspaces` / repository is codebase URL / could be obtained from GET request to relationships.codebases.links.related

NOTE: auxiliary projects that were imported manually to che workspace will not be displayed in codebases UI currently.

**Comment by ibuziuk** [comment]
@ashumilova IMO we could close this issue since all functional requirements seems to be met. Even though that temporary UI would call che server directly for stopping / deleting workspaces it would be trivial to change it to wit endpoint once it would be in place https://github.com/openshiftio/openshift.io/issues/2745

**Comment by ashumilova** [comment]
@ibuziuk thank you for the update

**Comment by joshuawilson** [comment]
nice work @ibuziuk

**Comment by l0rd** [comment]
@ashumilova can we close this issue?

**Comment by ibuziuk** [comment]
yes we can close, I have checked today with Ann
