### ISSUE TITLE
Planner: Integrate issues with github issues

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#1447]
All OSIO issues should be integrated with Github. So github issues would appear in OSIO and all OSIO created issues should be published on Github

**Comment by qodfathr** [comment]
This is a pretty broad request / epic. We've got the first elements of GitHub issue integration on the OSIO side of things (you can link GitHub issues into an OSIO work item and see their status within the WI).

As deeper integration is certainly part of the long-term plan and will likely span a Scenario or two, @rafabene are you okay with this being closed in favor of new epics yet-to-be-written? I promise they are coming. :)

**Comment by nimishamukherjee** [comment]
Closing this as we have revived remote work items - https://openshift.io/openshiftio/Openshift_io/plan/detail/958
