### ISSUE TITLE
Che is not deployed to the namespace of new users

### ISSUE THREAD

**Issue by ibuziuk-test** [openshiftio/openshift.io#1448]
For some reason che template is applied partially and che deployment never starts:

Reproduced against new test account
Workaround: Profile -> Update Profile -> Update tenant

Events:

![image](https://user-images.githubusercontent.com/33908548/33143590-a2e8e9b2-cfba-11e7-885c-12d68e336b1c.png)

The following resources are applied correctly:

Cms:

![image](https://user-images.githubusercontent.com/33908548/33143650-d6499efa-cfba-11e7-98f4-732ad040f9c1.png)

PVC:

![image](https://user-images.githubusercontent.com/33908548/33143686-efa2e82a-cfba-11e7-958e-4cab60fc857e.png)

Quotas are also applied correctly

![image](https://user-images.githubusercontent.com/33908548/33143830-660691ba-cfbb-11e7-8948-bb21ea89d59c.png)

**Comment by ibuziuk** [comment]
@xcoulon could we have someone from the platform team to help us with this problem ?

**Comment by ibuziuk** [comment]
Logs for my test `identity_id` : `8923a6a3-aa10-4980-96bb-82b9a1e8e52c`

https://logs.dsaas.openshift.com/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-1w,mode:relative,to:now))&_a=(columns:!(identity_id),filters:!(),index:'project.dsaas-production.129c1244-1b37-11e7-8db9-124160897002.*',interval:M,query:(query_string:(analyze_wildcard:!t,query:'kubernetes.pod_name:%22f8tenant-317-bzrq6%22%20AND%20kubernetes.namespace_name:%22dsaas-production%22%20AND%20identity_id%20:%228923a6a3-aa10-4980-96bb-82b9a1e8e52c%22')),sort:!('@timestamp',desc),vis:(aggs:!((params:(field:identity_id,orderBy:'2',size:20),schema:segment,type:terms),(id:'2',schema:metric,type:count)),type:histogram))&indexPattern=project.dsaas-production.129c1244-1b37-11e7-8db9-124160897002.*&type=histogram

**Comment by ibuziuk** [comment]
@xcoulon in the logs I see 409 status:

`{"action":"setup","bytes":0,"ctrl":"TenantController","duration":2.280348,"duration_unit":"ms","identity_id":"8923a6a3-aa10-4980-96bb-82b9a1e8e52c","level":"info","msg":"completed","pkg":"github.com/fabric8-services/fabric8-tenant/vendor/log.LogRequest.func1","req_id":"NrLLP9JPLv-31536","status":409,"time":"2017-11-23 10:15:11"}`

Any ideas what does it mean ?

**Comment by ibuziuk** [comment]
{"action":"setup","bytes":0,"ctrl":"TenantController","duration":1.834306,"duration_unit":"ms","identity_id":"8923a6a3-aa10-4980-96bb-82b9a1e8e52c","level":"info","msg":"completed","pkg":"github.com/fabric8-services/fabric8-tenant/vendor/log.LogRequest.func1","req_id":"NrLLP9JPLv-31536","status":409,"time":"2017-11-23 10:15:11"}

**Comment by ibuziuk** [comment]
Logs from another f8tenant pod:

https://logs.dsaas.openshift.com/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-1w,mode:relative,to:now))&_a=(columns:!(kubernetes.container_name,message,identity_id),index:'project.dsaas-production.129c1244-1b37-11e7-8db9-124160897002.*',interval:w,query:(query_string:(analyze_wildcard:!t,query:'kubernetes.pod_name:%22f8tenant-317-nj34z%22%20AND%20kubernetes.namespace_name:%22dsaas-production%22%20%20AND%20identity_id%20:%228923a6a3-aa10-4980-96bb-82b9a1e8e52c%22')),sort:!('@timestamp',desc))

**Comment by l0rd** [comment]
Looking at the init tenant logs when initializing a che namespace there was a `POST` request which got a response with status `400`:

```json
{
"identity_id":"aadd0586-2e84-477c-80a0-8eb90fc84819",
"kind":"DeploymentConfig",
"level":"info",
"method":"POST",
"msg":"resource requested",
"name":"che",
"namespace":"mloriedo-che",
"pkg":"github.com/fabric8-services/fabric8-tenant/controller.InitTenant",
"req_id":"8decfd73-fd5a-4db9-855a-e7651ca76da6",
"status":400,
"time":"2017-11-29 09:46:09"
}
``` 

Looking deeper that was related to an update of the `fabric8-maven-plugin` that uses Kubernetes 3.x model in Che and Jenkins templates (while `init-tenant` continued to use the old model):

```yaml
apiVersion: v1
code: 400
kind: Status
message: the API version in the data (apps.openshift.io/v1) does not match the expected API version
  (v1)
metadata: {}
reason: BadRequest
status: Failure
```

This PR should fix the problem: https://github.com/fabric8-services/fabric8-tenant/pull/487

**Comment by l0rd** [comment]
The PR of the previous comment had [some side effects on Jenkins](https://github.com/fabric8-services/fabric8-tenant/pull/487#issuecomment-349259646) and we have not merged it.

As an alternative we have created https://github.com/fabric8-services/fabric8-tenant-che/pull/88 that should fix the problem as well.

**Comment by l0rd** [comment]
https://github.com/fabric8-services/fabric8-tenant-che/pull/88 has been merged and deployed to prod and I have been able to test it: Che deploymentconfig is now successfully created for new users. I am closing this issue.
