### ISSUE TITLE
Stack report: Count mismatch for packages been analyzed

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1449]
Please check out numbers shown at the top right corner of the screen:

Total, Analyzed, Unknown: Total number is shown as greater than Analyzed. 

When 'Unknown' count is shown (packages that OSIO analytics can not understand), would need to display the unknown package names as well...
<img width="1368" alt="screen shot 2017-11-23 at 9 10 13 am" src="https://user-images.githubusercontent.com/15967765/33158279-98f181ca-d02e-11e7-9507-539d6d619095.png">

**Comment by invincibleJai** [comment]
@krishnapaparaju changes are in Prod now.

**Comment by GeorgeActon** [comment]
@invincibleJai If it is in prod please mark as closed.

**Comment by invincibleJai** [comment]
Closing it as changes are in prod. Please feel free to reopen if feel otherwise.
