### ISSUE TITLE
Launching Che section, the "Your Workspaces are loading" Stuck

### ISSUE THREAD

**Issue by Swannie007** [openshiftio/openshift.io#1453]
Hi

I am attempting to go through the osiogettingstarted.pdf and is stuck on the.

Launching Che section, the Your Workspaces are loading spinning wheel has been going for about 20-30 minutes.

Regards

**Comment by kbsingh** [comment]
maybe dupe for #1448

**Comment by joshuawilson** [comment]
@Swannie007 can you please `update tenant` or `reset env` to get the latest update and try again.

**Comment by Swannie007** [comment]
That works thank you.
