### ISSUE TITLE
Missing Applications on the Space page

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#1456]
After importing the `Vert.X` quickstart and deploying the application on the environments using the pre-configured pipeline, the space page still shows no content in the `Application` card:

<img width="1237" alt="screenshot 2017-11-24 09 05 29" src="https://user-images.githubusercontent.com/178502/33200924-da3afe7c-d0f6-11e7-821e-357919853d8a.png">
<img width="1197" alt="screenshot 2017-11-24 09 05 17" src="https://user-images.githubusercontent.com/178502/33200927-dbefebf6-d0f6-11e7-9e42-ec3da714dc79.png">

## Impacts
#2133 Dashboard Rendering Issues

**Comment by qodfathr** [comment]
@xcoulon looks fixed to me. Can you please confirm?

**Comment by jiekang** [comment]
This is a known intermittent issue. The Applications widget is renamed to the Deployments widget and being fixed [1]

[1]
Issue: https://github.com/openshiftio/openshift.io/issues/2301
PR: https://github.com/fabric8-ui/fabric8-ui/pull/2574

**Comment by jiekang** [comment]
This is tracked in issue above and the related PR has been merged. Closing this issue. If the issue persists feel free to re-open.
