### ISSUE TITLE
Avoid using a browser popup to open a Che workspace ?

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#1457]
If the browser blocks the popup (could be turned on by default), then trying to open the Che workspace from the `Codebases` page will result in ... nothing happened and if the user did not notice the popup blocker message in the navigation bar of the browser, he/she may think that an error occurred... This is at least my own experience :/
Could we try to find a workaround to avoid this situation, or at least provide an explicit feedback to the user if the popup (actually, another tab) could not be opened ?

**Comment by ashumilova** [comment]
+1 had same experience - first thought that Open button is not working.

**Comment by xcoulon** [comment]
yes, that's exactly what I was meaning, and I suspect a few (lot ?) of users will have the same reaction...

**Comment by slemeur** [comment]
Could we do with the same mechanism than the one used to display the openshift console. Like here:
![screen_shot_2017-11-28_at_17_22_19](https://user-images.githubusercontent.com/1636769/33331031-c8707d6c-d460-11e7-9c84-ddfe1b4eed2d.png)

**Comment by slemeur** [comment]
@joshuawilson + @ashumilova : I added the label, team/platform but that might be something team/che/plugins could handle too.

**Comment by joshuawilson** [comment]
I think it is for `team/che/plugins` but if they need help we can assist.
