### ISSUE TITLE
Make 3scale intermediate API repository fool proof

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#1459]
Currently it hits almost 7 to 8 REST API calls to fully register an application inside 3 scale with mappings, metrics, proxies, end points and everything that is needed for a full fledged application to seamlessly work.

While making REST calls, currently it doesn't rollback or handle gracefully the failures in API calls if any.

This will create some faulty registrations and it might be prone to some problems.

This tech debt is to find a way to handle that in a better way.

**Comment by GeorgeActon** [comment]
@arunkumars08 we do not have a type "Technical Debt". If this is creating incorrect registrations then it is a bug and should be labelled as a bug.

**Comment by arunkumars08** [comment]
@GeorgeActon 3 scale feature isn't in production yet. Currently it is in the dev phase. 
To make it clear, currently the developed intermediate API can handle registrations just fine. It is just to make sure we handle all the probable failure scenarios before pushing it to production.

**Comment by krishnapaparaju** [comment]
Not relevant at this time as analytics platform does not make use of dynamic routes at 3Scale..
