### ISSUE TITLE
[3] Run E2E tests against fabric8-analytics prod deployment

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1460]
# Description

We run E2E tests against staging every time changes are merged to master branch and automatically deployed there. Other teams run their E2E tests also against prod deployment, every hour or so. We'd like to follow their example and start doing the same for fabric8-analytics.

**Comment by msrb** [comment]
@tisnik FYI

**Comment by msrb** [comment]
Note we don't need to run all E2E tests that we have against prod. Because we know that some of them will not work (e.g. gremlin - it doesn't have public route).

**Comment by tisnik** [comment]
The plan is to run only tests that are explicitly tagged by a tag @production. Some other tests change the state of the tested system and we probably don't want to break everything (right now :)

**Comment by tisnik** [comment]
Job for prod testing (fail ATM): https://ci.centos.org/job/devtools-test-end-to-end-prod-fabric8-analytics/

**Comment by tisnik** [comment]
Tests that should run on prod are now marked accordingly: https://github.com/fabric8-analytics/fabric8-analytics-common/pull/423

**Comment by tisnik** [comment]
The test jobs has been created and now the CI run it periodically:
https://ci.centos.org/job/devtools-test-end-to-end-prod-fabric8-analytics/

Please note that six scenarios fail ATM: https://ci.centos.org/job/devtools-test-end-to-end-prod-fabric8-analytics/448/console

I'm looking at those failures.

**Comment by tisnik** [comment]
FYI: pull requests to almighty jobs that are related to this task:

https://github.com/almighty/almighty-jobs/pull/444/
https://github.com/almighty/almighty-jobs/pull/438

**Comment by tisnik** [comment]
FYI: yet another PR, now with updated token:
https://github.com/almighty/almighty-jobs/pull/460

**Comment by tisnik** [comment]
another small fix:
https://github.com/almighty/almighty-jobs/pull/466

**Comment by tisnik** [comment]
e2e test has been setup and now is green (finally!) https://ci.centos.org/job/devtools-test-end-to-end-prod-fabric8-analytics/
