### ISSUE TITLE
Stack report includes multiple replicas of the same repository with varying number of stars in Github Dependants column

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#1464]
<img width="1680" alt="screen shot 2017-11-27 at 3 50 57 pm" src="https://user-images.githubusercontent.com/5445560/33267415-67609b54-d39f-11e7-9458-84cbc8ff3e56.png">

**Observed behaviour**: The same repository is shown multiple times.

**Expected behaviour**: One repository should be included only once.

**Steps to reproduce**:
- Create a new spring boot http booster app on OSIO
- Wait for stack report to show up

**Environment**: Production

/cc @miteshvp

**Comment by miteshvp** [comment]
Fixes are in prod. Please re-open if you see this issue again.
