### ISSUE TITLE
[3] Perform and publish load test results for stack analysis

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1467]
# Perform the following performance tests on production:

1. Start 100 stack analysis requests
1. Check that SLA requirements are met (2 minutes to finish)
1. Start 500 component analysis requests for known components
1. Check that SLA requirements are met (1 second to finish)
1. Start 500 component analysis requests for unknown components
1. Check that SLA requirements are met (1 second to finish)

# Acceptance criteria:

## Stack analysis
- [x] all stack analysis return expected data (200 OK + the JSON with known format)
- [ ] all stack analysis finish in 2 minutes

## Component analysis for known components
- [ ] all component analysis return expected data (200 OK + the JSON)
- [ ] all component analysis finish in 1 second

## Component analysis for unknown components
- [ ] all component analysis return expected data (200 OK + the JSON)
- [ ] all component analysis finish in 1 second

**Comment by tisnik** [comment]
Stack analysis results for current production setup:

https://raw.githubusercontent.com/fabric8-analytics/fabric8-analytics.github.io/master/perf-tests/core_api/stack_analysis/production_100_calls/stack_analysis_parallel_calls_100_threads_concurrent_100_threads_min_max_avg_times.png

https://raw.githubusercontent.com/fabric8-analytics/fabric8-analytics.github.io/master/perf-tests/core_api/stack_analysis/production_100_calls/stack_analysis_parallel_calls_100_threads.png

**Comment by msrb** [comment]
@tisnik thanks!

These results were achieved with following resources:
- 4 API workers
- 1 kronos for PyPI
- 1 kronos for Maven

Pavel, were these Maven or Python stacks?

**Comment by msrb** [comment]
This doesn't look that bad, could you please perform the same test (Maven) at least one more time please?

**Comment by tisnik** [comment]
@msrb that tests were run for Python stacks. I'm going to run tests for Maven stack at today night. Will let you know when results will be available.

**Comment by tisnik** [comment]
@msrb so the results for Maven stack (the classic vert.x) show that there's still room for improvements ;)

https://fabric8-analytics.github.io/perf-tests/core_api/stack_analysis/production_100_calls_vertx/stack_analysis_parallel_calls_100_threads_concurrent_100_threads_min_max_avg_times.png

https://fabric8-analytics.github.io/perf-tests/core_api/stack_analysis/production_100_calls_vertx/stack_analysis_parallel_calls_100_threads.png

**Comment by tisnik** [comment]
The next step would be to increase # of PODs assigned to workers and/or kronos, right?

**Comment by msrb** [comment]
Thanks  @tisnik, this is exactly what we needed to know.

I'd first try to increase number of worker replicas. That should help a lot here. We can later try to scale up kronos as well.

**Comment by GeorgeActon** [comment]
@tisnik Are you able to do anything more on this while you are waiting for https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/870 to be acted on?

**Comment by tisnik** [comment]
@GeorgeActon this issue is blocked ATM, because if I run the tests again prod with the same number of resources, the durations will remain the same

**Comment by krishnapaparaju** [comment]
performance work is being tracked at #1144

**Comment by samuzzal-choudhury** [comment]
@msrb @tisnik the objective of this issuee has already been achieved through this issue and https://github.com/openshiftio/openshift.io/issues/1763. I only performance related activity left to do is the one mentioned in the Sprint 144 goals as "Scale the platform to support 1000 concurrent users". Can one of you please close this? CC: @sivaavkd
