### ISSUE TITLE
On prod-preview, users cannot access build logs

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1470]
This problem has been seen in the past and is back again.

Steps to recreate:
* Start a build pipeline
* Attempt to view the build log - this window is opened:
![screenshot from 2017-11-28 14-42-44](https://user-images.githubusercontent.com/642621/33340712-e3d36850-d44a-11e7-8ba8-fbc18f61dfeb.png)

* Selecting the first menu choice - brings the user to this screen:
![screenshot from 2017-11-28 14-43-02](https://user-images.githubusercontent.com/642621/33340748-f69f4f26-d44a-11e7-9f1f-6dabe5ca538d.png)

* Attempting to login there brings the user back to this window:
![screenshot from 2017-11-28 14-42-44](https://user-images.githubusercontent.com/642621/33340776-09b2d8bc-d44b-11e7-9624-844d1b9f8514.png)

**Comment by ldimaggi** [comment]
This situation makes it impossible to debug problems such as this:

![screenshot from 2017-11-28 15-06-39](https://user-images.githubusercontent.com/642621/33341735-de5cc77e-d44d-11e7-8890-7c00f50e9232.png)

**Comment by jfchevrette** [comment]
This is a known issue with the prod-preview environment. In the meantime, clicking the first button labeled 'Login with Keycloak' should get you past the login page and allow you to access the build logs.

**Comment by ldimaggi** [comment]
That's just the problem - clocking on the first button locks the user into the loop described in this issue.

**Comment by jfchevrette** [comment]
I'm sorry, there are no mentions of a loop in your original issue description.

I hate to say this but clicking on 'Login with Keycloak' worked for me (tm)

**Comment by ldimaggi** [comment]
Closing - this is now working - thx!
