### ISSUE TITLE
Improve licence recommendation for quickstarter application stack

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#1472]
#### User Story
As an OSIO developer, I will be able to get better license recommendation for my selected stack.

#### Description
Currently the licence analysis not showing the correct license for quickstarter application. This user story aims to improve on that.
#### Acceptance Criteria

- The application should be able to give correct license recommendation for quickstarter application.

#### Task list

- [x] Check compatibility of unknown licence with the existing licenses. 
- [x] Add unknown licenses to existing license tree.

**Comment by sunilk747** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/pull/34 fixes this issue.

**Comment by sara-02** [comment]
@miteshvp I think we close this issue now.
