### ISSUE TITLE
On prod-preview, rollout to stage failing

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1479]
Steps to recreate:
* Create new app/quickstart
* Observe build pipeline runs to completion
* Verify that app is deployed to run environment
* Verify that app is not deployed to stage environment

Attached build log does not indicate an error related to rollout to stage.

[build_log.txt](https://github.com/openshiftio/openshift.io/files/1514281/build_log.txt)

**Comment by ldimaggi** [comment]
[jenkins_log.txt](https://github.com/openshiftio/openshift.io/files/1514305/jenkins_log.txt)

**Comment by ldimaggi** [comment]
This problem seems to be reproducible. Seeing it 5 out of 5 tries today.

**Comment by joshuawilson** [comment]
Is this still an issue? Is it specific to OSO 3.7? If not then it would be a CD team issue.

**Comment by ldimaggi** [comment]
Not seeing this problem today - closing.
