### ISSUE TITLE
On prod-preview, Jenkins pod idling fails to transition to a running state

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1481]
Started seeing this today - November 29 - steps to recreate:

* Reset user environment in OSIO
* In OSO console, observe content-repo pod start
* In OSO console, wait ~10 min, observe jenkins transition to an idle state

* Attempting to force activity by creating a build pipeline does not cause the jenkins pod to start - it remains in the idle state

**Comment by ldimaggi** [comment]
After a few hours - this problem is not being seen - closing.

**Comment by kbsingh** [comment]
@ldimaggi can you elaborate a bit on exaclty how you are creating the pipeline ?

**Comment by ldimaggi** [comment]
To create a pipeline - add a new app/quickstart ('add to space') in OSIO - and then observe the pipeline created.

**Comment by ldimaggi** [comment]
Closing - no longer an issue.
