### ISSUE TITLE
Overflow of spaces list outside of Space card in profile

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#1482]
Issue: Under user profile if user has more number of spaces , it flows out of "my space" card
Browser : chrome (OSX)
Screenshot : 

<img width="1639" alt="screen shot 2017-11-30 at 9 05 48 am" src="https://user-images.githubusercontent.com/5129024/33411948-97a262f0-d5ae-11e7-8ae1-d9438685d09c.png">

Steps : 
- login to OSIO
- Click on Profile from right top
- Should have more number of spaces 
- View "my spaces" card

**Comment by mindreeper2420** [comment]
I believe this was fixed less than a day ago - I just checked your profile and the list is scrolling in the card (not overflowing). Can you verify in your environment? Thanks!

**Comment by joshuawilson** [comment]
closing as this was fixed, please reopen if it is still an issue
