### ISSUE TITLE
CVEs do not show up at stack summary section of stack report

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1483]
If a package of stack report has a CVE associated, CVE would show up at 'detailed analysis section' of stack report. This CVE is not showing up at 'Stack summary' section of the stack report.

Please see the screenshot...
<img width="1370" alt="screen shot 2017-11-30 at 9 29 37 am" src="https://user-images.githubusercontent.com/15967765/33412479-93cb21e6-d5b1-11e7-84a5-4ddddce3ee55.png">

**Comment by miteshvp** [comment]
@krishnapaparaju - would it be possible to share the stack id? You need to get it more developer tools

**Comment by invincibleJai** [comment]
@miteshvp i guess Krishna tried on https://github.com/krishnapaparaju/some-one/blob/master/pom.xml

**Comment by krishnapaparaju** [comment]
@miteshvp am not seeing stack id at the stack report..

**Comment by samuzzal-choudhury** [comment]
@krishnapaparaju the stack id should be available in the network console's xhr tab in the browser.

**Comment by krishnapaparaju** [comment]
@samuzzal-choudhury @miteshvp here is the stack id: 48d602148d154afcb77e0f42a1b9b235

**Comment by invincibleJai** [comment]
@samuzzal-choudhury @miteshvp here is response json for ID which Krishna have shared https://gist.github.com/invincibleJai/04f693ff52fdb70d02a40958c7a01126

**Comment by jyasveer** [comment]
this issue is fixed in this PR https://github.com/fabric8-ui/fabric8-recommender/pull/377

**Comment by jyasveer** [comment]
closing this as it is in prod now
