### ISSUE TITLE
With default resolution on Mac, not to able to see Additional components at Stack report

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1485]
With default resolution on Mac, not to able to see Additional components. Clickin on 'additional components often used by similar stacks' will not show these additional components (keyboard scroll down would not scroll the screen).

Please see attached 
<img width="1357" alt="screen shot 2017-11-30 at 10 45 12 am" src="https://user-images.githubusercontent.com/15967765/33415304-9daf1712-d5bb-11e7-97f0-7f6cf280f5c9.png">
screenshot...

**Comment by krishnapaparaju** [comment]
Is some cases (where the number of packages are around6  in a stack), there is no way to see 'additional components' / nor scroll down with keyboard.. Please check attaches screenshot.. 

Bumping up the severity...
<img width="1359" alt="screen shot 2017-11-30 at 12 23 23 pm" src="https://user-images.githubusercontent.com/15967765/33417938-8cd5ce82-d5c9-11e7-9f8c-bf81c9be7c46.png">

**Comment by jyasveer** [comment]
@krishnapaparaju we have to revert this change https://github.com/fabric8-ui/fabric8-recommender/pull/375 to get the key binding back on the modal.
By default key binding will act on the browser page.
However we can write some javascript logic and make the modal scroll down in its fixed height window, but this will be very hacky and not a good practice of doing things.

IMO, we should change back the height of the modal to `auto`

**Comment by krishnapaparaju** [comment]
no using  hacks, would suggest discuss at tomorrow's standup if needs more discussion.

**Comment by jyasveer** [comment]
fix for this is here https://github.com/fabric8-ui/fabric8-recommender/pull/381
