### ISSUE TITLE
Filter dropdown is getting truncated at stack report

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1486]
Select 'License outliers' from the stack report, if there are no 'License outliers to display', this drop down would not show any other options below 'License outliers'.. 

Please check the screenshot ..

<img width="205" alt="screen shot 2017-11-30 at 1 28 41 pm" src="https://user-images.githubusercontent.com/15967765/33419875-67f0967a-d5d2-11e7-95f3-a8c79e67a69c.png">

**Comment by invincibleJai** [comment]
@krishnapaparaju this is happening as we have scroll in modal rather than using browser's window scroll, other options can be seen if we scroll manually , as keyboard binding has issued with modal scroll https://github.com/openshiftio/openshift.io/issues/1485

CC @jyasveer

**Comment by jyasveer** [comment]
this issue is fixed here https://github.com/fabric8-ui/fabric8-recommender/pull/381
