### ISSUE TITLE
Column width would need to be adjustable at stack report

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1488]
Currently the most important attributes to look at stack report: package name and categories are not visible (full text) as the column width is not adjustable.

Please see the attached screenshot

<img width="1337" alt="screen shot 2017-11-30 at 1 44 22 pm" src="https://user-images.githubusercontent.com/15967765/33420564-13052fc4-d5d5-11e7-994e-e33137d99eb2.png">

**Comment by arunkumars08** [comment]
Closing this as design has been changed for the new-revamp which will be in prod.
