### ISSUE TITLE
Usage Outliers card's content message should be centre aligned like other cards in summary

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#1489]
In Stack summary (dashboard) Usage Outliers card's content message should be centre aligned like other cards in summary.
<img width="1047" alt="screen shot 2017-12-01 at 9 25 18 am" src="https://user-images.githubusercontent.com/5129024/33467308-9a3fdf12-d679-11e7-933e-fad9c44b5024.png">

**Comment by jyasveer** [comment]
this is fixed here https://github.com/fabric8-ui/fabric8-recommender/pull/380
