### ISSUE TITLE
Usage Outliers card just have heading without any content.

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#1491]
Issue : Usage Outliers card just have heading without any content.
Steps : 
- Create a space with any starter Project (i tried spring-boot-crud)
- let build go through
- open stack report immediately , can see usage outliers card with just heading (later it works)

<img width="1560" alt="screen shot 2017-12-01 at 9 48 13 am" src="https://user-images.githubusercontent.com/5129024/33467821-5a39291a-d67d-11e7-82be-ceb2967098ac.png">

**Comment by GeorgeActon** [comment]
@jyasveer I do not see any related work but you have majked this as complete?
If you submitted a PR then go to it and reference this bug so we see it and the status of it here.

**Comment by jyasveer** [comment]
this is fixed here https://github.com/fabric8-ui/fabric8-recommender/pull/380
