### ISSUE TITLE
Che workspace not loading for the first time at OSIO

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1492]
<img width="505" alt="screen shot 2017-12-01 at 3 47 18 pm" src="https://user-images.githubusercontent.com/15967765/33478491-7684aee6-d6af-11e7-8e49-44ee5b6aa1f1.png">
Have created two times: creating space, choose a quickstart application (SpringBoot CRUD) , create Che workspace. First time while Che workspace is launched, its failing with either of two errors (Please see the attached screenshots).
 Closing this workspace and opening the same workspace again is doing the trick,... workspace is ready to use..
<img width="924" alt="screen shot 2017-12-01 at 3 36 47 pm" src="https://user-images.githubusercontent.com/15967765/33478482-6fe33148-d6af-11e7-8853-365fd79f2669.png">

**Comment by ibuziuk** [comment]
@krishnapaparaju looks like a duplicate https://github.com/openshiftio/openshift.io/issues/1304
Refresh should probably help
