### ISSUE TITLE
[prod-preview] After resetting environment che pod fails to start - "Failed create pod sandbox" 

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#1493]
Che 2.0.67 on https://console.free-int.openshift.com

Steps to reprodue: **Profile -> Update Profile -> Reset Environment**

![image](https://user-images.githubusercontent.com/1461122/33483814-d7ed0562-d69f-11e7-91ac-b14953e7b4c1.png)

Events:

![image](https://user-images.githubusercontent.com/1461122/33483829-e9d14b58-d69f-11e7-8071-8aaccc579dd1.png)

**Comment by vpavlin** [comment]
I've seen this with Jenkins yesterday whole day. It came up after some time. I found this https://github.com/openshift/origin/issues/17047

**Comment by ibuziuk** [comment]
Currently this issue is a blocker for testing che on prod-preview

**Comment by kbsingh** [comment]
@vpavlin can we get a seperate issue filed for jenkins

**Comment by ibuziuk** [comment]
Still can reproduce on prod:

![image](https://user-images.githubusercontent.com/1461122/33728124-b7345490-db79-11e7-98b5-508a5cfcee45.png)

**Comment by ibuziuk** [comment]
@kbsingh After a few attempts I was able to deploy Che on console.free-int.openshift.com, so probably we should change the severity to SEV2-high

**Comment by vpavlin** [comment]
Yeah, same for Jenkins - this is not 100 % reproducible

**Comment by joshuawilson** [comment]
@kbsingh do you want me to add a label `area/jenkins` that we can filter by? Most of these issues get filed under `area/pipelines`.

**Comment by kbsingh** [comment]
yes please, Also - talk in the SD team, we are ok to drop SEV1 to SEV2 if the owning dev is happy with that.

@joshuawilson @ibuziuk

**Comment by mmclanerh** [comment]
Likely related:  https://github.com/openshiftio/openshift.io/issues/1550

**Comment by mmclanerh** [comment]
https://github.com/openshiftio/openshift.io/issues/1550#issuecomment-350254802 is now resolved.   can we get this re-tested and if it's all great, let's close this out.

**Comment by mmclanerh** [comment]
correction, the pod sandbox issue may be related to aws limits here:  https://github.com/openshiftio/openshift.io/issues/1538  -- asking for some validation around this.

**Comment by ibuziuk** [comment]
@mmclanerh can not reproduce anymore but for some reason there are only 3 projects on free-int for my account: 

![image](https://user-images.githubusercontent.com/1461122/33804270-aa56d2a0-dda1-11e7-887d-8ef626caa35a.png)

**Comment by kbsingh** [comment]
@mmclanerh i dont think the sandbox issues are related to aws limits; note that the clustwr with the limit problem does not have sandbox issues.

**Comment by kbsingh** [comment]
@ibuziuk i would suggest  chasing the projects issue on a seperate issue. Closing sandbox problem for now.

**Comment by ibuziuk** [comment]
@kbsingh separate issue for missing namespaces - https://github.com/openshiftio/openshift.io/issues/1612
