### ISSUE TITLE
Che missing from Status widget and not starting reliably

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#1495]
![image](https://user-images.githubusercontent.com/16322190/33491081-294b81f4-d687-11e7-8c93-a5b1d17cd261.png)

Note that Che is not showing yup in the status widget. When navigating to Codebases, it is taking an exceptionally long time for existing workspaces to appear in the drop-down. (3 minutes). Trying to open a workspace launched the Che IDE, but was unable to successfully start the workspace.

Navigating to the Che Dashboard, I was able to start the workspace. However, existing Che IDE browser tab never seemed to be 100% correct. For example, it did not show my project in the Projects Explorer.

Returning back to the Codebases screen, if I attempt to open the workspace again, it appears that the Che IDE is now functioning properly.

Labeling SEV-1 as this is a significant mismatch to the first steps of the Getting Started guide, and new users are on boardining.

**Comment by qodfathr** [comment]
Reducing to SEV2 because #1496 has updating the Getting Started guide. Che starting issue is still a concern.

**Comment by ibuziuk** [comment]
Related to https://github.com/redhat-developer/rh-che/issues/450 
Need to provide multi-tenant che-server status icon & update Getting Started guide

**Comment by ibuziuk** [comment]
Closing - new success Che icon placeholder is now available on prod
