### ISSUE TITLE
Stack Report not updating when viewed from the popup box

### ISSUE THREAD

**Issue by c-koehler** [openshiftio/openshift.io#1497]
After making a pipeline run to completion, opening up the Stack Recommendation popup box before it's done leaves you with the window on the image provided below (on the right half). When refreshing the dashboard to see if it has completed (on the left half of the image below), it shows it as completed.

The popup window (right side of the image below) has the word "Updating..." at the top, along with the loading bar at the middle that never goes past 50%, which leads me to believe it'll automatically refresh when everything finishes... but never does. Is this supposed to be the case? Or is the user expected to know to refresh the page for the results?

![update-sync](https://user-images.githubusercontent.com/33262856/33499173-e7b4f098-d6a1-11e7-83ca-eddeaf0e21c5.png)

**Comment by samuzzal-choudhury** [comment]
@jyasveer can you please look into this scenario? For your ready reference, I see that the stack analysis is complete for ID '1c096084c85e46dab58d628bdef91865'.

**Comment by miteshvp** [comment]
@samuzzal-choudhury @jyasveer - I guess it is more of when the stack report dashboard says it is completed, but the modal on the right still says 50%. I guess it is never the case that modal refreshes. Please correct me if I am wrong.

**Comment by jyasveer** [comment]
As per this use case IMO, lets not show the user the progress bar and show just a message showing like 'report is not ready'. And we can also provide a button which says 'Refresh' and this button does the modal refresh. I have to work with the UX team and decide on what is the best way to show this to the user.

**Comment by samuzzal-choudhury** [comment]
@jyasveer let's plan this in the upcoming sprint.

**Comment by krishnapaparaju** [comment]
@arunkumars08 @jyasveer please test this out as part of UX revamp work , due by end of sprint # 143.

**Comment by sunilk747** [comment]
Closing this as it is handled as part of new UI. Please feel free to reopen if you feel otherwise.
