### ISSUE TITLE
On prod-preview, cannot access OSO console

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1498]
Attempts to access https://console.free-int.openshift.com/console - are failing with 429 (too many requests) errors:

![screenshot from 2017-12-01 22-13-23](https://user-images.githubusercontent.com/642621/33511247-0b48da4a-d6e5-11e7-9ed1-c42ce1230901.png)

**Comment by aditya-konarde** [comment]
@ldimaggi free-int was down for a while and is back now. Could you try accessing the console again?

**Comment by joshuawilson** [comment]
Closing, please reopen if it is still an issue.
