### ISSUE TITLE
Stack report recommendations show up only for one quick start application

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1500]
Currently stack report recommendations show up / validated only for one quick start application (SpringBoot CRUD). 
Stack report recommendations would need to show up for other 5 quick start apps. at OSIO.

**Comment by krishnapaparaju** [comment]
@GeorgeActon This issue talks about the analytics platform is available (recommendations) for only quick start application. For other quick start applications, analytics platform is not generating any recommendations / nor exists (for users who choose any other stack than SpringBoot-CRUD. Its SEV-1 in my opinion as analytics service is breaking the OSIO user experience for majority (5 out of 6) of quick start apps..

**Comment by rootAvish** [comment]
@sivaavkd Spills to 142.

**Comment by rootAvish** [comment]
This is solved in https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/163.
