### ISSUE TITLE
In Che - unclear clear icon to delete a command from the command explorers 

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#1502]
Reported by *deven.phillips* on #openshift.io mattermost channel.

Unclear icon to delete command from the command explorer
![screen shot 2017-12-04 at 17 33 21](https://user-images.githubusercontent.com/1636769/33564007-bdf0d310-d919-11e7-9c17-99daff8344c9.png)

**Comment by InfoSec812** [comment]
The icon appears to indicate a "collapse" operation instead of a "delete" operation... Perhaps a "trash" icon instead?

It would also be beneficial to allow highlighting the item and pressing the "delete" key on the keyboard to accomplish this task as well.

**Comment by vzhukovskii** [comment]
@slemeur can you provide an icon for this operation?

**Comment by ibuziuk** [comment]
Should be closed after switching to che6

**Comment by slemeur** [comment]
The icon has been changed but the interaction are going to be improved as part of the current sprint: Upstream issue https://github.com/eclipse/che/issues/7715

**Comment by joshuawilson** [comment]
Was this done?

**Comment by benoitf** [comment]
@joshuawilson it requires the update to che 6 on OSIO

**Comment by joshuawilson** [comment]
I'm moving it to your backlog to close the sprint.

**Comment by ibuziuk** [comment]
fixed in che 6 and new icon is available on prod. Closing
![image](https://user-images.githubusercontent.com/1461122/39751504-b0e7e8ca-52b8-11e8-96f6-8933de1820bd.png)
