### ISSUE TITLE
Unable to init tenant following changes on _tenant

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1508]
I am unable to see any projects on my OSO console, looks like init tenant does not work.

In the status dropdown, Jenkins shows up with a loading icon. 

Relevant snippet from logs:
```
{"err":"Failed to GET template from https://nexus.cd.test.fabric8.io/content/repositories/staging/io/fabric8/tenant/packages/fabric8-tenant-jenkins/asdasd/fabric8-tenant-jenkins-asdasd-openshift.yml got status code to: 404","file":"/tmp/go/src/github.com/fabric8-services/fabric8-tenant/controller/tenant.go","func":"github.com/fabric8-services/fabric8-tenant/controller.(*TenantController).Update.func1","identity_id":"masked","level":"error","line":170,"msg":"unable initialize tenant","os_user":"akonarde","pid":1,"pkg":"github.com/fabric8-services/fabric8-tenant/controller.(*TenantController).Update","req_headers":{"Accept-Encoding":["gzip"],"Authorization":"*****","User-Agent":["Go-http-client/1.1"],"X-Request-Id":["masked"]},"req_id":"masked","time":"2017-12-04 14:00:15"}
```

Context: I had put some test values ('asdasd') on the custom tenant page, but have tried clicking `clear all values`, save, and then reset environment again. Also tried a manual hard-reset with the help of @pbergene and @jfchevrette 

This situation is blocking me from doing anything on OpenShift.io

**Comment by pbergene** [comment]
We should try dropping from the tenant db now that you have cleared the values in _tenant.

**Comment by aditya-konarde** [comment]
@pbergene  Sure, we can try that and check.

**Comment by joshuawilson** [comment]
Was this fixed?

**Comment by aditya-konarde** [comment]
@joshuawilson Not yet, need a full account nuke it seems. I was able to change the invalid string by going to _tenant, but nothing shows up on my OpenShift console yet. Needs further investigation.

**Comment by aditya-konarde** [comment]
With help from @pbergene and @xcoulon , got the account unborked. Not yet sure what was causing the init failure.

**Comment by pbergene** [comment]
@maxandersen pointed out that these are kept in the users profile which are not wiped on reset/re-init. Good to know cc @kbsingh

**Comment by rawlingsj** [comment]
Can the reset feature be extended to clear these too?

**Comment by pbergene** [comment]
sbose: contextInformation is arbitrary data that is saved along with the user info

**Comment by xcoulon** [comment]
yes, @rawlingsj, I think it makes sense to also get rid of the `tenantConfig` section of the `contextInformation` data in the user's profile during the reset. I'll add this task to the relevant issue

**Comment by sbose78** [comment]
Sure, but we managed to fix it without clearing the user profile's `contextInformation` - makes me wonder if that's the right direction :)

**Comment by rupalibehera** [comment]
I am facing this issue too, I am blocked on doing anything on OSIO. I want to test this issue on it but I cannot for now

**Comment by sbose78** [comment]
To cleanup : 
```
curl -X PATCH \
  https://auth.openshift.io/api/users \
  -H 'authorization: Bearer $token' \
  -H 'content-type: application/json' \
  -d '{"data":{"attributes":{"contextInformation":{"boosterCatalog":null,"tenantConfig":null}},"type":"identities"}}'
```

**Comment by pbergene** [comment]
Will drop tenant db - to re-trigger tenant init.

**Comment by rupalibehera** [comment]
@pbergene let me know when you are done I will re-login and check

**Comment by pbergene** [comment]
I see no entries in tenant namespaces schema for username rupa*, tenants schema for email matching rupa* nor namespaces on starter-us-east-2.  Should the user match this pattern?

This means the tenant should attempt re-init.  Note that no openshift namespaces must exist for that user.

**Comment by kbsingh** [comment]
i am guessing we are also deleting all the OSO side assets before the tenant-db is cleared for a specific user ?

**Comment by pbergene** [comment]
Yeah, oso account empty

**Comment by jfchevrette** [comment]
I have done a full reset of the tenant database which has links to namespaces in the backing Openshift cluster. I have also done a full reset of the namespaces in the backing openshift cluster.

I believe this may have resolve this specific issue but we should wait to hear back from the people who had the issue in the first place.

**Comment by mmclanerh** [comment]
@rupalibehera  please verify you are no longer having this issue in prod-preview.  it is suspected that https://github.com/openshiftio/openshift.io/issues/1569 resolved most tenant state issues.  thanks!

**Comment by mmclanerh** [comment]
with fix action from https://github.com/openshiftio/openshift.io/issues/1569 applied, @rupalibehera was able to confirm a now working state in https://github.com/openshiftio/openshift.io/issues/1525.  closing this issue, please lmk and will re-open otherwise.
