### ISSUE TITLE
Intermittent issue on https://openshift.io - Che fails to start workspace - unable to load preferences

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1510]
Saw this once on December 5 while attempting to create a new workspace.

Steps to reproduce:
*  Create new space
* Create new quickstart/app
* Attempt to create new workspace

![screenshot from 2017-12-05 10-47-35](https://user-images.githubusercontent.com/642621/33617242-4259a896-d9ad-11e7-866c-229c401215a6.png)

Seen this once so far - nothing in the Jenkins pod log.

**Comment by ibuziuk** [comment]
@ldimaggi I believe this one is related to various wsagent / route flapping issue. Could you please verify ?

**Comment by ldimaggi** [comment]
Closing as this has not been seen recently.
