### ISSUE TITLE
Stack Report Recommendations not updating when build status is complete

### ISSUE THREAD

**Issue by sanketpathak** [openshiftio/openshift.io#1511]
In Openshift.IO window when a build is complete, the Stack Report Recommendations section shows the window as shown in the image below which leads user to believe it'll automatically refresh when everything finishes but never does. As I tried this I had to refresh my window to see the stack summary section and 'show complete stack report' button(as in the ideal case)
![s01](https://user-images.githubusercontent.com/10252230/33657016-fcee902c-da9d-11e7-8b6f-03fcb50c407b.png)

**Comment by krishnapaparaju** [comment]
@sanketpathak Are you able reproduce this problem, I could not reproduce this issue..

**Comment by arunkumars08** [comment]
@sanketpathak Currently, the progress bar doesn't appear. Please close it if you think it works fine.

**Comment by sanketpathak** [comment]
As this case is handled in UI. closing it
