### ISSUE TITLE
On prod-preview, reset env results in a 500 server error

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1514]
Just started seeing this:

![screenshot from 2017-12-06 10-52-42](https://user-images.githubusercontent.com/642621/33670756-cbba5c36-da73-11e7-8bf4-e1533b400f34.png)

**Comment by pbergene** [comment]
@ldimaggi Just to make sure, did you re-link on https://sso.prod-preview.openshift.io/auth/realms/fabric8/account/identity ?

**Comment by ldimaggi** [comment]
Closing - not seeing this issue on prod-preview today.
