### ISSUE TITLE
Jenkins & content-repository not provisioned into the jenkins namespace for new users

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#1519]
When a new user is logging in for the first time to OSIO, no jenkins or content-repository deployments are created on the jenkins namespace.

If the user does a 'reset tenant', the deployments are created properly.

This was observed on prod-preview.

This appear to be very similar to #1448 (and hopefully the fix is similar too)

**Comment by joshuawilson** [comment]
Are you saying the fix is to `reset env` for the tenant? OR do you have fix since you just did it for something else?

**Comment by jfchevrette** [comment]
@joshuawilson i meant that `reset tenant` is a workaround that _must_ be executed after a new user sign up. Otherwise builds will not work as jenkins is missing completely.

**Comment by joshuawilson** [comment]
So this is a likely an OSO 3.7 thing and we need a solution or we have to use this workaround?
Any ideas on a fix?

**Comment by l0rd** [comment]
That's because there has been a change in the `apiVersion` used for `DeploymentConfig` in Jenkins and Che yml templates:
```diff
- - apiVersion: v1
+ - apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
```
And init-tenant need to be updated too. These PRs https://github.com/fabric8-services/fabric8-tenant/pull/487 https://github.com/fabric8-services/fabric8-tenant-che/pull/89 should fix this issue.

**Comment by l0rd** [comment]
@jfchevrette should be solved now. Can you confirm?

**Comment by jfchevrette** [comment]
@l0rd that fixed it. thanks!

**Comment by jfchevrette** [comment]
The jenkins deployments are created but the jenkins-recommender-api-token secret is missing.

I have created #1529 to track this
