### ISSUE TITLE
Run E2E tests against f8a deployments at OSIO

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1522]
**# User story**

 For all F8 Analytics deployments, ensure the new changes are tested E2E and regression performed at OSIO (production cluster)

**# Description**

These E2E tests would need to touch/cover all the OSIO user facing components. 

**# Acceptance criteria**

These tests can be run at each production promotion / every 30 mins. Tests run with frequency need to be co-ordinated with @ldimaggi 's work on E2E tests at production.

**Comment by krishnapaparaju** [comment]
Has dependency on creation / availability of UI integration test cases

**Comment by tisnik** [comment]
The CI job to run EE tests has been setup:
https://ci.centos.org/job/devtools-test-end-to-end-prod-fabric8-analytics/

Now we are about to figure what caused the failures.

**Comment by pkajaba** [comment]
@tisnik @krishnapaparaju the problem is an invalid token for API. I sent a request to insert valid one into centos CI. I thought that we could reuse existing ones at first, but it somehow did not work.

**Comment by GeorgeActon** [comment]
Closing, no longer relevant. All this work is in planner
