### ISSUE TITLE
UI integration tests for F8A platform

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1523]
**# User story**

 For all F8 Analytics deployments, UI integration tests are run at Dev., Stage and Production clusters

**# Description**

These UI integration tests would need to touch/cover all the OSIO user facing components. 

**# Acceptance criteria**

These UI integration tests would need to be integrated into E2E tests currently being done at respective environments..

**Comment by tisnik** [comment]
cc @ldimaggi FYI

**Comment by jyasveer** [comment]
Please refer this User Story for this task
https://github.com/openshiftio/openshift.io/issues/1693
