### ISSUE TITLE
Fix bottlenecks in stack analysis

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1527]
We need to identify and fix the bottlenecks in the stack analysis. Possible areas:

- graph DB access times
- kronos efficiency and scalability
- workers efficiency and scalability
- accessing S3 queue

Measured data so far:
https://fabric8-analytics.github.io/perf-tests/core_api/stack_analysis/production_100_calls_vertx/stack_analysis_parallel_calls_100_threads_concurrent_100_threads_min_max_avg_times.png

https://fabric8-analytics.github.io/perf-tests/core_api/stack_analysis/production_100_calls_vertx/stack_analysis_parallel_calls_100_threads.png

**Comment by krishnapaparaju** [comment]
performance work is being tracked #1144

**Comment by samuzzal-choudhury** [comment]
@tisnik this has already been addressed in the sprint 143 through https://github.com/openshiftio/openshift.io/issues/1763. Can you please close this issue?

**Comment by sivaavkd** [comment]
@tisnik - closing this since this is taken care of in 143 as per @samuzzal-choudhury .  Please reopen if you think otherwise.
