### ISSUE TITLE
Error: secrets "jenkins-recommender-api-token" not found

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#1529]
When a new tenant is initialized, the jenkins-recommender-api-token secret is missing / not deployed.

This is probably related to the changes made in fabric8-services/fabric8-tenant#487

A similar issue was fixed in #1519

**Comment by jfchevrette** [comment]
`{"identity_id":"016033e6-c9a7-4190-bcee-1307d04a135e","kind":"Secret","level":"info","method":"POST","msg":"resource requested","name":"jenkins-recommender-api-token","namespace":"jchevret-osiotest1-jenkins","pkg":"github.com/fabric8-services/fabric8-tenant/controller.InitTenant","req_id":"jgIuthfaTI-3271","status":403,"time":"2017-12-07 14:37:21"}`

**Comment by jfchevrette** [comment]
init tenant fails to create the secret but running 'update tenant' can

**Comment by rawlingsj** [comment]
are there different roles required for create and update?

wonder if you can get the roles for the service account in prod and compare with prod preview?

**Comment by jfchevrette** [comment]
This issue appear to have been caused by me deleting the denant and trying to have it re-initialized to fast resulting in f8tenant trying to create resources (secret in this case) which were not completely removed in the backend yet.
