### ISSUE TITLE
Mitigate all the UI changes done in fabric8-recommender to fabric8-analytics-stack-report-ui

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#1530]
- [ ] License card changes.
- [ ] Usage card changes
- [ ] All label changes
- [ ] Misc changes

**Comment by sunilk747** [comment]
@jyasveer What's the status for this user story. Can we close it?

**Comment by jyasveer** [comment]
this can be closed now. as it is handled in the revamp of UI work.
