### ISSUE TITLE
Spinner from analyze page on 'Stack Report Recommendations' bleeds through add-work-item window

### ISSUE THREAD

**Issue by c-koehler** [openshiftio/openshift.io#1531]
If you have a report that is loading when you visit your space homepage (or the analyze button), if you have a stack report that is taking a while to load and has a spinner that won't go away for a while, it will leak through if you click the **(+)** button next to 'My Work Items', causing the following:

![leaking-through](https://user-images.githubusercontent.com/33262856/33720072-d3a0d30e-db30-11e7-8462-9d9eba8a7b92.png)

**Comment by nimishamukherjee** [comment]
Closing this as we have removed this screen from planner.

**Comment by debloper** [comment]
Closing as per Nimisha's comment.
