### ISSUE TITLE
Jenkins idler is idling my jenkins continuously

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#1533]
How to reproduce

- Created a new tenant
- Ran through getting/started, Init Tenant
- Tried to launch a build, build was pending
- Found that jenkins was not running
- Jenkins was scaled to 0/idled
- Scaled jenkins to 1
- Jenkins was immediately scaled back to 0

What I was expecting

- As a new tenant I expect my jenkins to start and run for ~1 hour and not get idled immediately.
- As an existing tenant, when I push a commit to github I expect my jenkins to be unidled

Observations

- My github repo was created with the following webhook URL: https://jenkins-jchevret-osiotest1-jenkins.d800.free-int.openshiftapps.com/github-webhook/ which is not the idler endpoint

**Comment by vpavlin** [comment]
It should be fixed now, let me know if you are able to verify or reproduce still

**Comment by kbsingh** [comment]
@vpavlin @jfchevrette can we get confirmation and close this issue ?

**Comment by jfchevrette** [comment]
Not able to reproduce anymore. Closing.
