### ISSUE TITLE
space count is wrong

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#154]
I have played around with openshift.io and creating/deleting around spaces (on openshift.online  or openshift.io).

It seems that the number of spaces available on the tab as seen in the screenshot as I have no spaces but it still list it as 2 : 

![image](https://cloud.githubusercontent.com/assets/98980/25736997/a249a0e8-3175-11e7-87e9-60259a7fb133.png)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1353

**Comment by RanjithRV** [comment]
Closing this issue as the associated issue was closed 
#https://github.com/fabric8-ui/fabric8-ui/issues/1353

Final comment on 1353 by Joshua 
"The number has been removed. Closing."
