### ISSUE TITLE
'Create' button on create space page gets disabled for no reason

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#1540]
1. Go to the create new space window
2. Enter a few characters in the space name field. Observe that on entering a new character, the Create button at the bottom of the window briefly turns disabled.

https://drive.google.com/open?id=1W2h3hzv1t1LtEaf9o25yjgCFM0mxI5kH

**Comment by joshuawilson** [comment]
This is working as designed. The Space name must be unique, this is the system performing a uniqueness test as you type. 
Do you have a suggestion on a different way?

**Comment by joshuawilson** [comment]
related to #1542

**Comment by rgarg1** [comment]
Performing a name check is good, disabling the button every time is not. Gray the button out only if a matching space name is found.

**Comment by qodfathr** [comment]
Closing as working as designed; however, as @joshuawilson points out, #1542 may result in a design change.
