### ISSUE TITLE
Space Creation - Minimum character notification creates a jumping effect

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#1542]
![jumpingerror](https://user-images.githubusercontent.com/1892722/33758842-f0710036-dbf7-11e7-833d-486e9d289df2.gif)

Validation happens every time a character is entered. This creates a jumping effect.

**Comment by joshuawilson** [comment]
We are running validation on each keystroke. We could allow for multiple keystrokes if done in a certain time and then check.
@catrobson do you have any insight into this. Should we change the location of the notification? How long is a enough of a delay before validation?

**Comment by catrobson** [comment]
@corinnekrych I thought we had discussed this on another thread and talked about doing validation after focus is lost on the field.  Am I not remembering that correctly?

**Comment by corinnekrych** [comment]
@joshuawilson @catrobson, this is plain modal, not done in app wizard flow, 2 options:
- as suggested by josh group the input collection and do validation
- or do validation on lots focus
Note that each validation goes server side to validate the name does not already exist.
![screenshot 2017-12-11 09 30 59_preview](https://user-images.githubusercontent.com/1395710/33822011-4bbd333c-de56-11e7-92f0-6b200b426905.png)
Therefore option 2 (which limits the number of validation) seem a good approach to me.

**Comment by joshuawilson** [comment]
@catrobson do you have an opinion? 
I would agree with you @corinnekrych to perform less server side checks. Is it possible to get list of spaces first and then check locally? It should only be the spaces the user has not all spaces. Then you can validate against the service at the end just to confirm that something wasn't added while filling in the form.

**Comment by catrobson** [comment]
Agreed we should do less server side checks, so if we can't grab the spaces first and check locally I'm fine with doing grouped input collection and then a check so we don't do 2 server side checks.

**Comment by qodfathr** [comment]
As a stop-gap measure, would it help if we just moved the validation DIV to below the Create button? That would seemingly stop the distracting jumping and let us close this issue. Any redesign should be tracked separately.

**Comment by jiekang** [comment]
This space creation dialog no longer exists. Closing this issue.
