### ISSUE TITLE
The URL to view workitem created from stack report is incorrect and lands user on a 404 page

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#1544]
1) Create a workitem from the stack report page. A pop-up appears asking user to view the workitem
2) Click on the pop-up and observe that user lands on the 404 page

Wrong URL: https://openshift.io/rgarg-osiotest1/Exploratory%20Dec8/plan/detail/2
Expected URL: https://openshift.io/rgarg-osiotest1/Exploratory_Dec8/plan/detail/2

Reason: The underscore in the spacename is encoded, breaking the URL to the Workitem

**Comment by krishnapaparaju** [comment]
@arunkumars08 @jyasveer please test this out as part of UX revamp work , due by end of sprint # 143.

**Comment by arunkumars08** [comment]
@krishnapaparaju Will be addressed as a part of the UI revamp.

**Comment by qodfathr** [comment]
Fixed.
