### ISSUE TITLE
Che workspace failed to start

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#1545]
First attempt to launch Che gave 403
![403](https://user-images.githubusercontent.com/1892722/33759649-02e08d06-dbfb-11e7-85ce-6cb6c2ee2349.png)

Second time, "Could not start" error message is shown.
![chedoesnotstart](https://user-images.githubusercontent.com/1892722/33759685-24797158-dbfb-11e7-9581-4966049a1bca.png)

**Comment by kbsingh** [comment]
@nimishamukherjee just to confirm, you have been through the update-tenant flow and are running the latest builds ?

**Comment by nimishamukherjee** [comment]
@kbsingh I did not do that as it would delete my existing spaces.

**Comment by ibuziuk** [comment]
@nimishamukherjee `update_tenant` does not remove existing workspaces

**Comment by nimishamukherjee** [comment]
@ibuziuk I'm following https://openshift.io/osiogettingstarted.pdf (Page 69)
Also, I get this screen
![eraseall](https://user-images.githubusercontent.com/1892722/33763610-16f81bc0-dc09-11e7-8bf6-5b9f565276ef.png)
It does look like it will delete all.

Can you confirm that I can follow these steps?

**Comment by sbose78** [comment]
@nimishamukherjee do not 'reset environment' . you will find another option to `update tenant`

**Comment by nimishamukherjee** [comment]
@sbose78 found the button. It is next to Reset Environment.
The instructions under https://openshift.io/osiogettingstarted.pdf page 69 are confusing as the header states Update Tenant Services and lists the steps for resetting the environment.

**Comment by ibuziuk** [comment]
@nimishamukherjee so, do you have the same problem after env reset ?

**Comment by sbose78** [comment]
> The instructions under https://openshift.io/osiogettingstarted.pdf page 69 are confusing as the header states Update Tenant Services and lists the steps for resetting the environment.

:( log an issue please?

**Comment by nimishamukherjee** [comment]
@ibuziuk @sbose78 after Update Tenant the Che workspace comes up properly.

**Comment by ibuziuk** [comment]
@nimishamukherjee thanks for the update. Are you ok if I close ?

**Comment by nimishamukherjee** [comment]
@ibuziuk please close this issue
@sbose78 raised #1563 for the Update Tenant instruction in the guide.
