### ISSUE TITLE
Stack Report - we can click and create multiple work items for the same recommendation

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#1546]
![multiplewis](https://user-images.githubusercontent.com/1892722/33760557-f46c363c-dbfd-11e7-8aaf-f9263fae95c1.png)
The "Create Work Item" link could be disabled after a work item has been clicked on.

**Comment by krishnapaparaju** [comment]
@arunkumars08 please take care of this issue as part of the new UX implementation ..

**Comment by arunkumars08** [comment]
@krishnapaparaju This will be addressed as a part of the revamp.

**Comment by arunkumars08** [comment]
@nimishamukherjee The ui has been revamped and this issue has been taken care. Please try once and close this issue if this is no longer reproducible.

**Comment by sivaavkd** [comment]
@nimishamukherjee - I just tried this and we cannot create multiple work items anymore.  can you try once and see if it is reproducible ?

**Comment by arunkumars08** [comment]
@nimishamukherjee Closing this issue as this is not reproducible. Please reopen it if you find it otherwise.
