### ISSUE TITLE
Stack Report - Table columns resize on hover causing the table to "jump"

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#1547]
![jumpingstack](https://user-images.githubusercontent.com/1892722/33760725-8e3fd958-dbfe-11e7-98ed-3304bf313341.gif)

Stack components analysis table and recommendations table exhibit this behaviour.

**Comment by miteshvp** [comment]
@arunkumars08 - can you please point to the issue where new UX is been implemented. Maybe this might be a stale issue now and can be closed.

**Comment by krishnapaparaju** [comment]
@arunkumars08 @jyasveer please test this out as part of UX revamp work , due by end of sprint # 143.

**Comment by arunkumars08** [comment]
This will be handled as a part of the new revamp.

**Comment by sunilk747** [comment]
Closing this issue as it is handled as part of new UI.
