### ISSUE TITLE
Unable to delete codebases

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#1549]
Originally I tried to rename an underlying GitHub repository. I ended up with the original codebase which I cannot delete (even though the underlying GitHub repository does not exist anymore). And for resaons I cannot explain, I got the codebase for the new repository created twice. Again, without a way to delete them.

IMO, if there is an add functionality, there needs to be a remove as well.

**Comment by hferentschik** [comment]
![codebases](https://user-images.githubusercontent.com/296354/33766182-aec79fd0-dc1c-11e7-8257-a25aaf405225.png)

Note, I am really only interested in the first codebase. The second is a duplicate created by openshift.io and the third is the original codebase which does not refer to a valid repo anymore.

**Comment by sbose78** [comment]
Thanks.
We have an API on the backend at the moment though - need to find the story for the UI feature and link here.

**Comment by joshuawilson** [comment]
Duplicates #388
