### ISSUE TITLE
OpenShift project is not accecible

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#155]
Maybe I am missing some things but when creating a new space I am getting this error : 

![image](https://cloud.githubusercontent.com/assets/98980/25737056/f85357ae-3175-11e7-88fa-c2a7da49d10b.png)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1354

**Comment by RanjithRV** [comment]
Closing this issue as the associated Issue #1354 was closed. 

Comment by Chmouel on issue #1354 confirms that the issue no longer exists. For more info refer to #https://github.com/fabric8-ui/fabric8-ui/issues/1354
