### ISSUE TITLE
On prod-preview, creating a new app/quickstart - the app wizard hangs

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1550]
This problem is being seen on prod-preview and not on https://openshift.io

Steps to recreate:
* Reset user env
* Verify that che and jenkins pods are up after the reset
* Create a new space
* Create a new app/quickstart
* Observe the new app wizard hang:

![screenshot from 2017-12-08 07-23-58](https://user-images.githubusercontent.com/642621/33766168-4d4f5c70-dbea-11e7-89f7-583be3f96257.png)

**Comment by pbergene** [comment]
Quick rundown on what I think we might be facing: when we ran move to free-stg we wiped the tenant db, which would have worked fine for a re-init on free-stg.  However when we moved back to free-int and wiped the db, the namespaces already exist, so we can't do a clean re-init on free-int.  This results in lack of namespaces entries in the tenant DB.   This is consistent with not seeing entries in the namespaces table for the affected users - however new users and users who have had their namespaces deleted will still succeed. 

To clean up we need to get hold of a service token for free-int is needed to delete 4 of the namespaces and the user token is required to delete the last before a successful re-init.

Another option is restoring an older snapshot, but we would still have some sync issues with users who had their namespaces deleted and newly created users. I want to run this over with @jfchevrette to make sure I have all the pieces right with regards to the history.

**Comment by vpavlin** [comment]
Interestingly, the reset tenant still works (cleans OSIO spaces and OSO services)

**Comment by pbergene** [comment]
yes, that has me confused, but apparently doesn't rely on namespaces entries..

**Comment by jfchevrette** [comment]
I have done a full reset of the tenant database which has links to namespaces in the backing Openshift cluster. I have also done a full reset of the namespaces in the backing openshift cluster.

I believe this has resolved the quickstart issues as I have been unable to reproduce.

Lets wait for a few +1s before we mark this as resolved

**Comment by mmclanerh** [comment]
@ldimaggi if you could ack good / not good here, that would be fantastic. thanks!

**Comment by vpavlin** [comment]
If it helps.. I can confirm that tests are able to create space, create project and run a build which successfully finished (although something failed after that https://ci.centos.org/view/Devtools/job/devtools-test-end-to-end-idling-prod-preview.openshift.io-quickstartTest/4/console)

**Comment by ldimaggi** [comment]
It's working now - thanks!
