### ISSUE TITLE
UI duplicates whole components/pages

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#1555]
When navigating through the various pages and tabs, you can get into situations where the UI is repeating certain UI components over and over again. For example here is the environment pane after some navigating:

![random-ui-twitches](https://user-images.githubusercontent.com/296354/33767930-5040cb8c-dc24-11e7-97cd-8ca4bc992ba1.png)

note also the spinners which never disappears. No idea what it actually tries to load. It never seems to arrive.

**Comment by joshuawilson** [comment]
This page is being completely redone with a new design. Closing.
