### ISSUE TITLE
Broken navigation from Create|Environments to View All Spaces

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#1556]
Navigating from "Create|Environments" to "View all spaces", let's the menu disappear and nothing happens:

Before:

![env](https://user-images.githubusercontent.com/296354/33768078-e445daa2-dc24-11e7-83d6-7467bfb4e4d9.png)

After: 

![disappeared](https://user-images.githubusercontent.com/296354/33768080-e7e9fe86-dc24-11e7-9e3d-cc3a60c9471c.png)

**Comment by joshuawilson** [comment]
Confirmed this is still an issue.
@dgutride or @dlabrecq do you have time to look at this?

**Comment by dlabrecq** [comment]
Are there any errors in the browser console?

**Comment by qodfathr** [comment]
Closing as the Environments page is now deprecated in favor of #287
