### ISSUE TITLE
Make choice about experimental features persistent

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#1557]
Each time I access an experimental area of the site I get the "This feature is experimental. You can manage experimental features on your profile page.". 

I am not sure how often I have to say "got it" before the site actually gets that I got it ;-) Do we really have to display this on each refresh of the site? IMO this is a once off choice which should be persisted.

**Comment by joshuawilson** [comment]
@catrobson can you please confirm the correct UX for this.

**Comment by catrobson** [comment]
@hferentschik just want to confirm you're talking about the green bar across the top of the section that you're clicking "got it" on.  If so, I agree we should persist this decision.

**Comment by hferentschik** [comment]
>  just want to confirm you're talking about the green bar across the top of the section that you're clicking "got it" on. If so, I agree we should persist this decision.

Right.

**Comment by catrobson** [comment]
Added UX/UI issue into fabric8-ux backlog for this:  https://github.com/fabric8-ui/fabric8-ux/issues/782

**Comment by dlabrecq** [comment]
PR has been merged: https://github.com/fabric8-ui/fabric8-ui/pull/2410

**Comment by joshuawilson** [comment]
I merged it early and reverted it. So this is still open.

**Comment by corinnekrych** [comment]
@dgutride @catrobson do we want to save the feature-banner got it per feature? ie: for planner in experimental level, got-it was acknowledge dso if i go back don't display full size got-it banner. But if i got to another experimental feature like Applications I still got the full size got-it banner. Do we need this granularity?
why not just say this user has acknowledge the beta/exp state for all features. go-it being similar for all. I'm not sure the granularity is necessary here.

**Comment by dlabrecq** [comment]
Yes, I believe showing the banner for each feature is necessary, but will defer to @catrobson. The profile page doesn't necessarily make it clear which features you opt-in to. For example, is Applications an internal feature, experimental, etc.?

**Comment by joshuawilson** [comment]
until we can provide a list of what is in each level, the banner is the only way to know what you are opting in for
