### ISSUE TITLE
Displayed information on Environments unclear

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#1560]
On the Environments page we are displaying some status about the available applications. This information is without context. 

![env](https://user-images.githubusercontent.com/296354/33769138-45a0bf3e-dc29-11e7-9b16-8ef57c6a5f61.png)

snafu com.example fabric8 snafu 1.0.2 I can understand, but what does 0/1/1 9 days ago mean?
The last one seems to be the number of pods running for the application. At least I think tough. Initially there was nothing and when I started the application, it was displayed as 1. 

Note, that the 'Scale' option in the menu did not work. I tried to start the pod/app via the scale option and nothing happened. I then selected "OpenShift console" and started the pod directly. Then 1 is displayed. However, the underlying pod is not starting up properly and eventually gets into a non running state. The Environments UI still displayes the last '1' though.

**Comment by joshuawilson** [comment]
This page is being removed and the information will be made available in the new Deployments page. The current Env page was never designed. 
Closing.

**Comment by hferentschik** [comment]
What is the issue to track that? Can one provide input to that? Where or what is the "Deployment" page?

**Comment by joshuawilson** [comment]
Sure it is being tracked with the Epic https://github.com/openshiftio/openshift.io/issues/287 and there are there are tasks that fall under it for specific work.

The new Deployments page is a replacement for the Apps and Env pages.
