### ISSUE TITLE
OpenShift Console hard to access

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#1561]
The OpenShift console is an important part of the solution. A lot of things only become clear once one sees the underlying OpenShift namespaces and what they entail. Also, for most problem, the OpenShift Console is the place to get more information (reaching resource limits, failing pod deployments, etc). 

The only point I find a link to the Console is on the "Envionments" tab and there it is even hidden behind a menu I need to expand. 

IMO the Console needs much more visibility. I would put it on the top menu. 

Why is the Console so hidden?

**Comment by joshuawilson** [comment]
you should take a look at https://github.com/openshiftio/openshift.io/issues/287 and the work the team is doing around it. Please provide feedback on the new designs.

cc @catrobson

**Comment by qodfathr** [comment]
@hferentschik based upon new designs in #287, may we close?

**Comment by joshuawilson** [comment]
The new design can be seen at https://openshift.io/josh-6/flew/create/deployments
There is a menu option on the card that links to OSO. 
Closing as it is has been redesigned. Please comment on #287 if disagree or want something different.
