### ISSUE TITLE
Instructions for Update Tenant point to Reset Environment instructions

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#1563]
The instructions under https://openshift.io/osiogettingstarted.pdf page 69 are confusing as the header states Update Tenant Services and lists the steps for resetting the environment.

Also there are texts Asdsadasd and Sdasdasd

**Comment by joshuawilson** [comment]
cc @qodfathr

**Comment by qodfathr** [comment]
Making a SEV4 because this doc will soon be obsolete.

**Comment by Preeticp** [comment]
@stevengutz, this issue can be closed. This was with reference to the earlier PDF doc which was later deprecated. 
The current [Getting Started guide](https://docs.openshift.io/getting-started-guide.html) does not have any of these issues.

**Comment by stevengutz** [comment]
Closing based on @Preeticp comment above
