### ISSUE TITLE
Login - question - how long does the user remain logged in ?

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#1565]
I was logged out after two hours - is this expected?
I opened Che editor made a commit and then when I viewed the pipeline it showed me as logged out.

**Comment by alexeykazakov** [comment]
It’s not expected. If you don’t close your browser you should stay logged in forever. If you close it then you will need to re login in 30 days.

**Comment by alexeykazakov** [comment]
If UI gets 401 response for some requests to backend then UI forces logout. We should improve this approach because not all 401 should be followed by logout.

**Comment by joshuawilson** [comment]
@nimishamukherjee is this reproducible?

**Comment by alexeykazakov** [comment]
The question is answered. @nimishamukherjee if we see any problems with login please give some details and open an issue. Closing this one.
