### ISSUE TITLE
Unclear display of route and docker image

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#1567]
On the environment pane, I see the following: 

![route](https://user-images.githubusercontent.com/296354/33770465-f3630a7e-dc2d-11e7-8d80-e7a6807e81d8.png)

It took me some time to understand what it means and given that the link was so close to the text, I was thinking these two things belong together. However, the icon is the external route for the app and the second the docker image of the current app/pod.

IMO, the route needs to be displayed as an actual link as well. This is an essential piece of information. 

As mentioned in another issue, I am missing in general information what the various columns mean. Even with knowing OpenShift a fair bit, I am not quite able to make sense of everything displayed.

Also, using ellipses for the docker image is unfortunate. As it stands now, no valuable information is displayed. The visible content will basically be identical for whatever app I am running. The interesting part of is the second half which is no visible. I also can neither scroll nor cut&paste the image name. 

I would like to be able to cut&paste the whole string (not just see it in the hover over text). For example I might want to copy the sha to then do a diff against 'git log' to verify that the right version of the app/image is deployed.  I cannot do this.

It seems this shortening approach is taken at several other places as well without an easy way to  cut&paste. URLs, image names, shas are important pieces of information which become essential when tracking problems. Wherever they are displayed they should be cut&past-able either via selecting the whole test and manually copying it or by explicit buttons which copy the values into the text buffer (a la GitHub and clone url).

**Comment by joshuawilson** [comment]
This page is being replaced by the Deployments page but we should keep this in mind.

@andrewazores @jiekang please take a look at this and make sure you take this into consideration.

**Comment by joshuawilson** [comment]
This was from the Env page, that page has been removed. If you see anything related in the Deployments page please reopen and comment.
