### ISSUE TITLE
[prod-preview] tenant db and free-int out of sync

### ISSUE THREAD

**Issue by pbergene** [openshiftio/openshift.io#1569]
Ref: https://github.com/openshiftio/openshift.io/issues/1550#issuecomment-350254802

Quick rundown on what I think we might be facing: when we ran move to free-stg we wiped the tenant db, which would have worked fine for a re-init on free-stg. However when we moved back to free-int and wiped the db, the namespaces already exist, so we can't do a clean re-init on free-int. This results in lack of namespaces entries in the tenant DB. This is consistent with not seeing entries in the namespaces table for the affected users - however new users and users who have had their namespaces deleted will still succeed.

To clean up we need to get hold of an appropriate token for free-int that is needed to delete 4 of the namespaces and the user token is required to delete the last before a successful re-init.

Another option is restoring an older tenant db snapshot, but we would still have some sync issues with users who had their namespaces deleted and newly created users. I want to run this over with @jfchevrette to make sure I have all the pieces right with regards to the history.

After this is cleared we need to see if we are still experiencing some of the issues from prod-preview which I suspect some of which are symptoms.

**Comment by jfchevrette** [comment]
We can clear all 5 of the old namespaces on a case-by-case basis with the token we have.

Do we have a list of tenants which need a reset?

**Comment by mmclanerh** [comment]
possibly to auto-derive a comprehensive list?

**Comment by kbsingh** [comment]
@alexeykazakov @sbose78 @aslakknutsen @xcoulon : can we rest to zero and just start this again ? 

if that is an option, @jfchevrette @pbergene can we can work with the infra service ops team to do the clearout in the cluster space for tenant artifacts ?

**Comment by alexeykazakov** [comment]
There is no any issues with the Auth side of things if we nuke user's namespaces and tenant DB in free-int.

**Comment by jfchevrette** [comment]
I have done a full reset of the tenant database as well as the namespaces on the backing openshift cluster. 

Will add a comment in #1550 as well.

I believe we can close this.

**Comment by mmclanerh** [comment]
this work was completed.. and thus far, everything seems to be fine.  closing this issue.
