### ISSUE TITLE
Planner causes navigation problems

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#1571]
In going through the scenario outlined in the OSIO 'Getting Started Guide' [1], Planner suffered navigation issues.

When viewing Planner/'All', navigation to other areas (my profile, 'View all spaces') was broken.  (The user remained in the same place, the view did not change.)  

Viewing Planner/'Portfolio' allowed navigation to other places (the view then changed).

[1] https://openshift.io/osiogettingstarted.pdf

**Comment by joshuawilson** [comment]
I've been looking into this with @mindreeper2420. We think we know what it is.
cc @michaelkleinhenz @nimishamukherjee

**Comment by joshuawilson** [comment]
It is possible that the styles are overriding the ones from patternfly or from the main UI.

**Comment by mindreeper2420** [comment]
@joshuawilson yes, there are forced overrides in Planner that are affecting Platform. They will need to be fixed for issues such as this to be resolved.

**Comment by qodfathr** [comment]
Closing as this part of the Planner UI no longer exists. Please feel free to open new issues against the navigation.
