### ISSUE TITLE
Inconsistent terminology when importing a codebase

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#1576]
I cleared my environment and started with a clean workspace. I select "Import Codebase" and get asked to specify a GitHub repository. The action on this screen is "Sync". Should it not be "Import". That's the term used to open this dialog. I am a bit confused to see this displayed as "Sync" now. 

![sync](https://user-images.githubusercontent.com/296354/33776566-19134e32-dc42-11e7-89e3-397cf97886f4.png)

It even gets better. So after pressing sync. I get presented completely irrelevant information about the repository (created, last updated, last commit date) and then an "associate repository to space". So we go from importing to sync to associate. What is the terminology we want to use?

Also, what's the point of the dates being displayed? I could imagine several pieces of information which could provide some sort of help to determine whether I specified the right repository, but these dates are not amongst them. The repository description might help? A list of files in the git root. Anything which would help me to identiy I selected the right repo. Unfortunately, I am not keeping track of these dates when I think about my repositories.

![save](https://user-images.githubusercontent.com/296354/33776826-ec0c4032-dc42-11e7-8ada-927e541dd089.png)

**Comment by joshuawilson** [comment]
@ashumilova you may want to talk to @dlabrecq. I think he worked on this. 
We may need some UX help on this from @catrobson and team.

**Comment by dlabrecq** [comment]
The “sync” is more of a validation to ensure a code base can be created from the information provided — an invalid entry will demonstrate this. The “completely irrelevant” information obtained from GitHub simply confirms that. At this point, “it gets better” because now we’re able to proceed by “associating” the repo.

I have defer to @mindreeper2420 regarding the terminology...

**Comment by hferentschik** [comment]
> The “sync” is more of a validation to ensure a code base can be created from the information provided

Sure, I get that. However, even apart from the inconsistency "syncing" != "validation". From http://www.yourdictionary.com/syncing - " Transferring data between two or more devices so they will have the same files". That's what most people understand under "syncing". What happens here is "get repository info", a step which is imo unnecessary, especially if the best we can come up with is to present three irrelevant dates.

**Comment by qodfathr** [comment]
I feel that the Import Codebase dialog does have some pretty inconsistent wording -- to the point that it actually confuses me when I use it. I'm increasing to SEV2 and would like to see UXD get involved in helping to establish consistent terminology.

cc: @catrobson

**Comment by catrobson** [comment]
Agree we have several problems with this dialog and flow.  Captured story for UXD to determine improvements and then create implementation stories.

**Comment by hferentschik** [comment]
I'd argue there is no reason to have it at all. It could be safely removed.

**Comment by aptmac** [comment]
The old import codebases actions have been replaced with the new launcher in https://github.com/fabric8-ui/fabric8-ui/pull/2839
