### ISSUE TITLE
+ icon for space creation doesn't exit

### ISSUE THREAD

**Issue by kwk** [openshiftio/openshift.io#1579]
The getting started document on page 14 shows an image and a text that says one should click on a blue + 
sign. That image doesn't exist. See the following screenshot:

![bildschirmfoto von 2017-12-08 19-31-02](https://user-images.githubusercontent.com/193408/33780044-916da9a6-dc4f-11e7-9283-bfcdd8ef4968.png)

**Comment by mindreeper2420** [comment]
@kwk from your screenshot, it appears that the directions are inline with your image. The '+' appears when you have Spaces in the list. Your screenshot does not have any Spaces in your card.

**Comment by kwk** [comment]
@mindreeper2420 okay, sounds reasonable. But then the guide should not contain any space.

**Comment by joshuawilson** [comment]
@qodfathr can you please update the guide in this regard.

**Comment by qodfathr** [comment]
This has been an on-going concern of mine, and is making any kind of future documentation very difficult. It's also just odd behavior (IMHO) that "add something" acts so differently when the list is empty vs. not empty. I like the fact that the empty list has a big, bold "add something" gadget where the list would be displayed, but I disagree that this should also make invisible the normal "add something" button. So my proposal is to not fix the dox, but to always have the regular "add something" button visible, regardless of the whether or not the list contains any items.

**Comment by joshuawilson** [comment]
@catrobson do we need an updated design or just make the change?

**Comment by catrobson** [comment]
@mindreeper2420, @joshuawilson, @dlabrecq  I'm fine with this change from a Design/UX point of view.  I know we have this as a ng pattern, can you speak towards any concerns in implementing the change to make sure we get this consistently changed?

**Comment by dlabrecq** [comment]
The recent spaces widget isn't from patternfly-ng, but some patternfly-ng components show an empty state. For example, when a list , tree list, and table have no data to display. Changing the recent spaces widget is doable, but inconsistent.

**Comment by mindreeper2420** [comment]
That card is built directly into the home dashboard and the icon is controlled by an `*ngIf` statement. If the desire is to always have the "+" icon in the title bar, that is just an adjustment to the statement.

**Comment by catrobson** [comment]
Created a UXD issue to fix this here:  https://github.com/fabric8-ui/fabric8-ux/issues/809

**Comment by mindreeper2420** [comment]
@qodfathr @catrobson I've updated the code (PR filed https://github.com/fabric8-ui/fabric8-ui/pull/2386) to include the "+" icon at all times in the Card Header.
<img width="464" alt="screen shot 2018-01-12 at 10 26 26 am" src="https://user-images.githubusercontent.com/4032718/34882156-a2d73b04-f783-11e7-855f-0144bee6cc61.png">
<img width="464" alt="screen shot 2018-01-12 at 10 28 07 am" src="https://user-images.githubusercontent.com/4032718/34882157-a2e9b0b8-f783-11e7-8447-2832862bb0ca.png">

**Comment by joshuawilson** [comment]
Do we want to do this consistently?

**Comment by mindreeper2420** [comment]
@joshuawilson I'm going through the other cards with the "+" options and making sure that they are always present, no matter the state. That will keep it consistent across all cards/dashboards and documentation.

**Comment by joshuawilson** [comment]
ok, thanks

**Comment by mindreeper2420** [comment]
@joshuawilson this can be closed, as the PR to fix has been merged.
