### ISSUE TITLE
appwizard shows broken rows of stacks

### ISSUE THREAD

**Issue by kwk** [openshiftio/openshift.io#1580]
I'm going through the quickstart side by side with a browser to the right side and it seems like we try to fit to many of the stacks in one row (3 in this case). Maybe just one per row is better for this screen size.

![bildschirmfoto von 2017-12-08 19-47-41](https://user-images.githubusercontent.com/193408/33780371-c995ea68-dc50-11e7-85f0-a46e0ddf9fc2.png)

**Comment by joshuawilson** [comment]
Closing as this page is going through a complete redesign.
