### ISSUE TITLE
app wizard summary screen not utilizing space to display repo

### ISSUE THREAD

**Issue by kwk** [openshiftio/openshift.io#1582]
The summary screen in the app wizard (3A) doesn't show the full path to the repository created.

![bildschirmfoto von 2017-12-08 19-56-16](https://user-images.githubusercontent.com/193408/33780698-f79e5278-dc51-11e7-9746-7eee77b87baa.png)

**Comment by sbose78** [comment]
@corinnekrych is there something we could do about this? :)

**Comment by corinnekrych** [comment]
@sbose78 @kwk I think Arun is going to work on the redesign of this summary screen:
https://github.com/openshiftio/openshift.io/issues/1365

**Comment by joshuawilson** [comment]
This is getting completely redesigned. Closing.
