### ISSUE TITLE
app wizard final screen shows both "Ok" and "Cancel"

### ISSUE THREAD

**Issue by kwk** [openshiftio/openshift.io#1583]
The app wizard final screen shows both "ok" and "cancel". The effect of clicking both is the same I guess, because "Cancel" also brings me back to my newly created space. Maybe only Ok should remain because at this point there's not much to cancel.

![bildschirmfoto von 2017-12-08 20-05-32](https://user-images.githubusercontent.com/193408/33781355-96988ee6-dc54-11e7-8cd5-458689095c4e.png)

**Comment by ldimaggi** [comment]
See: https://github.com/openshiftio/openshift.io/issues/1325

**Comment by kwk** [comment]
Closing in favor of #1325. Thanks @ldimaggi for pointing that out.
