### ISSUE TITLE
Signup page and login page footer do not match footer on other pages

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1584]
OpenShift.io has inconsistency in the footers. 

For the Signup page and the Login page, the footer is: 
![previewsignup-footer](https://user-images.githubusercontent.com/6318164/33781312-195d9a86-dc7a-11e7-80f7-e747b5470ba8.png)

While on the Homepage, along with other pages, the footer is:
![homepage-footer](https://user-images.githubusercontent.com/6318164/33781330-2b771530-dc7a-11e7-8c55-31bed219c8fa.png)

This leads to an inconsistent experience, and the number of linked pages in footer also being different across these.

> Meta:
> Area: UI/UX 
> Type: Bug
> Priority: Minor

**Comment by mindreeper2420** [comment]
@aditya-konarde Can you provide URLs for these pages? All of the marketing pages (openshift.io, openshift.io/get-involved.html, and openshift.io/features.html) have the same footer, so I'm unsure what the signup/login page is. The marketing page is also where you signup/login to the application.

**Comment by aditya-konarde** [comment]
@mindreeper2420 

Homepage: https://openshift.io/ (When you're logged out)
Signup page: Click 'Sign up for preview' on the home page
Log in: Click 'Log in' on the home page.

From what I can see, The sign up/login pages are actually hosted on developers.redhat.com, and has an  OpenShift.io header. So the footer might not be something specific to OpenShift.io, and is just the original footer from developer.redhat. 

What we can do is - just like we added the OpenShift.io branding to the header, carry over the footer from OpenShift.io to the login page.

What do you think?

**Comment by mindreeper2420** [comment]
I understand what you are saying now. As it stands, we have no control over what the developers.redhat.com site does with their content. The header only says 'OpenShift.io', as that login is specific to the authentication services of OpenShift.io. Everything else (colors, fonts, buttons, alignments, etc.) are controlled purely by developers.redhat.com. The footer falls under that criteria.
Ideally, every brand page would have the same footer, but that is outside of the purview of OpenShift.io.

**Comment by joshuawilson** [comment]
@catrobson is this something that can be changed or influenced? Or should we close this as "can't fix"?

**Comment by catrobson** [comment]
Let's close this as "can't fix".
