### ISSUE TITLE
Intermittent failures opening Che workspace on https://openshift.io - "Unable to initialize IDE"

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1585]
Seeing this problem about 10% of the time on https://openshift.io on December 8

Steps to recreate:
* Create a new space
* Create a new app/quickstart
* Attempt to create new Che workspace

Che pod log is attached - no errors are logged - where else can we debug this?

[che_log.txt](https://github.com/openshiftio/openshift.io/files/1543619/che_log.txt)

**Comment by l0rd** [comment]
The root cause (and solution) for this issue is the same of #1599

**Comment by ldimaggi** [comment]
Have not seen this bug all day today - closing until/unless we see it again.
