### ISSUE TITLE
UI: Login and Logout buttons both displayed at same time

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1586]
While loading the Homepage, Logout and Login buttons are both displayed at the same time for a brief period. 

![logout-login](https://user-images.githubusercontent.com/6318164/33781604-46f6e05a-dc7b-11e7-91aa-731fe6bac583.png)

> Meta:
> Area: UI 
> Type: Bug
> Priority: Minor

**Comment by alexeykazakov** [comment]
Hard refresh usually helps with this issue. Refresh should not be required of course.

**Comment by joshuawilson** [comment]
This is just a refresh issue, closing.

**Comment by alexeykazakov** [comment]
Yeah sure. But the fact that OSIO still requires hard refresh is a bug itself.

**Comment by joshuawilson** [comment]
very true

**Comment by aditya-konarde** [comment]
@joshuawilson I think this issue should stay open, and that needs to be fixed. Doesn't look good to me from a UX perspective.

**Comment by joshuawilson** [comment]
Are you saying it should stay open because it looks bad in the image you posted or because we have caching issues?
