### ISSUE TITLE
pipelines access to logs times out

### ISSUE THREAD

**Issue by kwk** [openshiftio/openshift.io#1587]
As you can see from the screenshot accessing the Jenkins log doesn't work:

https://jenkins-kkleine-jenkins.8a09.starter-us-east-2.openshiftapps.com/job/kwk/job/myvertexhello/job/master/1/console

I followed the steps described on page 21 of the getting started guide, clicked on "Pipelines" in my space and then clicked on "View log". After clicking on "Log In" the page timed out.

The error occurred between 20:15 - 20:25 UTC+1.

![bildschirmfoto von 2017-12-08 20-20-28](https://user-images.githubusercontent.com/193408/33781578-7590e1de-dc55-11e7-819a-f9293633d070.png)

**Comment by kwk** [comment]
I tried to go to the logs again and after clicking "Log In" to jenkins I can see the logs now.

**Comment by alexeykazakov** [comment]
might be related to https://github.com/openshiftio/openshift.io/issues/1525

**Comment by mmclanerh** [comment]
it's possible this was related to #1525 which seems to be resolved as of fix action: https://github.com/openshiftio/openshift.io/issues/1569#issuecomment-350361961

unless there are further issues, i believe this can be closed. @kwk  if you could verify you're still working, we can close this up.

**Comment by kwk** [comment]
Sorry @mmclanerh I cannot reproduce it, so I guess it is fixed. Feel free to close.
