### ISSUE TITLE
URL to view Create Space docs in Profile page leads to 404

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1588]
In the 'Profile' page, the link for 'learn how to get started in the documentation' leads to [this page](https://access.redhat.com/documentation/en-us/red_hat_openshift.io/1/html-single/user_guide) and the user sees a 404 error.

![profilepage-docs-404](https://user-images.githubusercontent.com/6318164/33781778-df26adf6-dc7b-11e7-9e3c-65ccc1832857.png)

Priority: Low

## Impacts
- [ ] #2138 Platform Navigation Issues for Heather

**Comment by liangxia** [comment]
The correct link might be "https://docs.openshift.io"

**Comment by joshuawilson** [comment]
@rkratky if you can provide the correct link, we can get it updated.

**Comment by liangxia** [comment]
On "Account Home" page, in the "Recent Spaces" part, it links to "https://docs.openshift.io" when there are no spaces created.

**Comment by joshuawilson** [comment]
谢谢

**Comment by rkratky** [comment]
@joshuawilson I opened https://github.com/openshiftio/saas-openshiftio/pull/540 to get the docs.openshift.io updated with docs content. As soon as it's merged, the docs.openshift.io address can be used to link to official docs.

**Comment by rkratky** [comment]
@joshuawilson https://docs.openshift.io/ is now live, it can be safely linked to.

**Comment by joshuawilson** [comment]
This is in prod.
