### ISSUE TITLE
no "Rollout to Run" after promoting visible (only after a while)

### ISSUE THREAD

**Issue by kwk** [openshiftio/openshift.io#1589]
As you can see from my screenshot there is no "Rollout to Run"

![bildschirmfoto von 2017-12-08 20-31-29](https://user-images.githubusercontent.com/193408/33781955-e7366088-dc56-11e7-99dc-5ed3651ea4e1.png)

After I waited longer (a minute or so) the "Rollout to Run" stage did finally show up.

![bildschirmfoto von 2017-12-08 20-33-00](https://user-images.githubusercontent.com/193408/33782006-2319df26-dc57-11e7-8a54-f15a6dd8e85a.png)

**Comment by ldimaggi** [comment]
It cannot show the rollout link/icon - until it is rolled out.   ;-)

It would be a nice improvement if there was a "working..." icon to update the user on the progress.

**Comment by qodfathr** [comment]
I believe this is fixed. @kwk @ldimaggi @joshuawilson anyone want to confirm & close?

**Comment by qodfathr** [comment]
Close as dupe #456.
