### ISSUE TITLE
Cannot update space description once set

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1590]
Steps to reproduce:
1. Create a new space
2. Go to the space page
3. Add some description
4. Try to edit the description

![spacedesc-update](https://user-images.githubusercontent.com/6318164/33781891-65fd1284-dc7c-11e7-8a1b-4c987fd022c6.png)

**Comment by qodfathr** [comment]
Fixed, although the edit button is crazy-hard to click.
