### ISSUE TITLE
Planner: New work Item - Created Value shows: Creating now

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1591]
New work item creation in Planner has a confusing way to display Value for `Created` timestamp when a new item is being created. 

![planner-created-creatingnow](https://user-images.githubusercontent.com/6318164/33782094-4b5b618c-dc7d-11e7-8bd6-8b3954d18a42.png)

Area: UX
Type: Enhancement

**Comment by qodfathr** [comment]
Fixed (well, removed).
