### ISSUE TITLE
Broken Jenkins logo in Environment -> Services

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1592]
The logo shown in Environment -> Services for Jenkins results hits a 404 for the source, leading to a broken/image not found placeholder being displayed.

![envservices-brokenjenkinslogo](https://user-images.githubusercontent.com/6318164/33782214-c81ae684-dc7d-11e7-9774-3293421e0bd5.png)

Area: UI
Priority: Low

**Comment by sbose78** [comment]
@joshuawilson a bit unsure who should be looking at this ? Because i remember folks in the platform team are working on similar things?

**Comment by joshuawilson** [comment]
that whole pages is being completely reworked under the epic https://github.com/openshiftio/openshift.io/issues/287

Closing as, won't fix.
