### ISSUE TITLE
Planner: Confirmation dialog is towards the top of page instead of page center

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1594]
Type: Enhancement

The Confirmation dialog (eg. for delete comment) appears towards the top of the page. This can be moved to the marked area for better accessibility.
![planner-confirmationdialog-position](https://user-images.githubusercontent.com/6318164/33782455-d26abc26-dc7e-11e7-9c59-6c002dc87332.png)

Team: Planner, UX

**Comment by sbose78** [comment]
Hi @nimishamukherjee @sanbornsen is this as per design , or should we have a UX review on this ?

**Comment by nimishamukherjee** [comment]
@sbose78 @aditya-konarde we have used Patternfly modal - http://www.patternfly.org/pattern-library/widgets/#modal

This is as per design.

**Comment by qodfathr** [comment]
Closing as By Design
