### ISSUE TITLE
Planner: New work item - Buttons placement

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1597]
[Enhancement] The new work item dialog has buttons either: touching the boundary of the dialog (dropdown button)  or too far away from the dialog border(close).  
![planner-newitem-buttonplacement](https://user-images.githubusercontent.com/6318164/33782633-7948fb7a-dc7f-11e7-98c4-228ace0ef40f.png)

Area: UI
Team: Planner

**Comment by sbose78** [comment]
CC: @nimishamukherjee @sanbornsen @michaelkleinhenz

**Comment by qodfathr** [comment]
Fixed
