### ISSUE TITLE
Planner: Sidebar icons are not vertically center-aligned with text

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1598]
:Sidebar icons should be center aligned with the text (vertically)

![planner-sidebar-icons-align](https://user-images.githubusercontent.com/6318164/33782764-f39d5042-dc7f-11e7-85e2-1f29ecbfc823.png)

Area: UI
Team: Planner

**Comment by aditya-konarde** [comment]
Also, the font sizing looks inconsistent?

**Comment by sbose78** [comment]
CC : @michaelkleinhenz @nimishamukherjee @sanbornsen

**Comment by joshuawilson** [comment]
I added `area/ui` because this issue and fix are in the styles and placement of text and icons on the screen. It does not mean the UI for the planner. It also has `area/planner` since this issue is in the planner app.

@RanjithRV this is a good example of `area/UI`.

**Comment by ppitonak** [comment]
It seems to be outdated.

**Comment by nimishamukherjee** [comment]
@aditya-konarde please check on prod. The side panel design has changed.

**Comment by nimishamukherjee** [comment]
Fix is on prod. Please re-open if you face the issue.
