### ISSUE TITLE
UI: Vertx logo is squashed on most pages

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1600]
Need to maintain brand guidelines for product logos:

![vertx-squashedlogo](https://user-images.githubusercontent.com/6318164/33782874-608f3efe-dc80-11e7-99e1-aeabf60a9c72.png)

Area: UI

**Comment by joshuawilson** [comment]
@catrobson I don't know if we are squishing a good icon or the wrong one was provided.
@gastaldi can you talk to the owners.

**Comment by gastaldi** [comment]
@edewit can you identify if the correct icon image is used in this case?

**Comment by gastaldi** [comment]
This is what we use in the launcher-frontend: https://github.com/fabric8-launcher/launcher-frontend/blob/master/src/assets/img/project-select-icons/vertx.svg

**Comment by catrobson** [comment]
I don't think this was designed to handle the logo in the card.  Our new design shouldn't have the application name in the card at all.  Do we really think showing the technology logo is valuable here?  I'd think that the application name that the user has provided is far more important and shouldn't be distracted from by a runtime logo.

https://redhat.invisionapp.com/share/YSDL0KRKW#/screens

**Comment by joshuawilson** [comment]
I agree I don't see this as providing a lot of value.

**Comment by aditya-konarde** [comment]
@catrobson +1.

**Comment by joshuawilson** [comment]
This page is getting deprecated in favor of the new Deployments page. As @catrobson said, the new design doesn't have this in it. Closing.
