### ISSUE TITLE
Design: Stack report not consistent with the overall product UI 

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1601]
The colors and design make it feel like an external piece plugged into openshift.io.
An enhancement can be having it more consistent with the design language of the product.

![stackreport-colors](https://user-images.githubusercontent.com/6318164/33783023-f914afb0-dc80-11e7-8f1b-ad21b41e32a1.png)

**Comment by sbose78** [comment]
Hi @aditya-konarde , would you want to provide some specifics to @catrobson ( UX ) ? :)

Need to add Sunil / Muru to the org here so that I can mention them. CC @joshuawilson @adisakala

**Comment by catrobson** [comment]
@aditya-konarde Thanks!  Agreed that the visual language is a mismatch thus far.  @bdellascio, can you work with Sunil on this?

**Comment by bdellasc** [comment]
@catrobson Sure, I can work with him on this.

**Comment by aditya-konarde** [comment]
Thanks @catrobson @bdellasc  :)

**Comment by sunilk747** [comment]
Closing it as it is handled as part of new UI. Feel free to reopen if you feel otherwise.
