### ISSUE TITLE
Che uses different favicon compared to rest of openshift.io

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1602]
Favicon for che is the eclipse favicon, whereas everywhere else we're using the OpenShift favicon:
![cheicon](https://user-images.githubusercontent.com/6318164/33783170-9bb2e6a6-dc81-11e7-87c6-899609cd3048.png)

**Comment by gorkem** [comment]
Closing as we want che.openshift.io to retain Che identity.
