### ISSUE TITLE
Pipeline shows up in recent pipelines after deletion, 404 on click

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1604]
Steps to reproduce:
1. Create a space
2. Add a pipeline
3. Delete the space (pipeline will be deleted as a result)
4. Go to user home page
5. See pipeline in recent pipeline
6. Clicking on this will reach a 404 page
![spacedelete-recentpipelines](https://user-images.githubusercontent.com/6318164/33783370-80ec6ca6-dc82-11e7-9e2a-1e21f571f354.png)

**Comment by piyush1594** [comment]
Duplicate of #3802 Can we close this? @aditya-konarde

**Comment by piyush1594** [comment]
Can we close this? @aditya-konarde

**Comment by sthaha** [comment]
Closing this in favour of #3802
