### ISSUE TITLE
No validation for number of characters in 'Name' field

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1605]
Can set an entire paragraph as the user's Name fields. (Note that this is different from the userid)

![namefield-novalidation](https://user-images.githubusercontent.com/6318164/33783473-fac17102-dc82-11e7-81f8-f614a060b683.png)

**Comment by sbose78** [comment]
Has same problems as https://github.com/openshiftio/openshift.io/issues/1595
+ need to set limits based on persist-ability in keycloak user attributes.

**Comment by joshuawilson** [comment]
@dlabrecq @mindreeper2420 can you guys take a look at this.

**Comment by dlabrecq** [comment]
What should the limit be?

**Comment by mindreeper2420** [comment]
The general online consensus is 70-80 characters. The US Web Design Standards don't say anything on limits, just accessibility requirements (https://standards.usa.gov/components/form-controls/#text-input).

PatternFly does not have any suggestions on limits either, only styling for validation conditions.

**Comment by dlabrecq** [comment]
@sbose78 what is the character limit for keycloak?

**Comment by alexeykazakov** [comment]
> what is the character limit for keycloak?

The limit seems to be 255 characters.

**Comment by dlabrecq** [comment]
I'll add an 80 char limit for the user's name and company. The URL, Bio, and email will be 255.
