### ISSUE TITLE
Delete Space confirmation modal is incorrect

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#1606]
The Delete Space confirmation modal does not match PatternFly modal component designs (http://www.patternfly.org/pattern-library/widgets/#modal).

Additional Items:
- Trash can icon is used, signifying delete or ‘trash’, but confirmation action button is ‘remove’ (along with modal title)
- Punctuation is missing from message text

![screen shot 2017-12-08 at 7 35 50 pm](https://user-images.githubusercontent.com/4032718/33790564-2e128d72-dc4f-11e7-8b8e-371d371a7555.png)

**Comment by joshuawilson** [comment]
@mindreeper2420 are you going to fix this? or do you need help? Maybe @dlabrecq could assist you.

**Comment by qodfathr** [comment]
Also, the lack of the name of the Space in the dialog always scares me to death -- I have to close the dialog and make sure I clicked on the right delete link multiple times before I'm semi-confident I'm deleting the correct space.

This dialog should require strong confirmation -- such as typing in the name of the Space -- as it is destructive/irreversible/data-losing.

**Comment by qodfathr** [comment]
Technically, this issue is reported against the Profile page, and you can no longer delete Spaces from the profile page. So closing as fixed by removal.  However, see all #2107
