### ISSUE TITLE
Planner - Grey bars in the UI when there are no work items

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#1608]
![extragreyboxes](https://user-images.githubusercontent.com/1892722/33817663-8a55430a-de38-11e7-84f2-cd54c49cb594.png)

Grey bars in the UI when there are no work items.
One is above the filter
One is below the filter

**Comment by sbose78** [comment]
Hi @nimishamukherjee is this something that planner team would be able to take up - or is there a need for a UX review prior to that ?

**Comment by nimishamukherjee** [comment]
@sbose78 The planner team can take this up. It looks like a CSS issue.
@SMahil can you have a look?

**Comment by SMahil** [comment]
@nimishamukherjee I am unable to reproduce this issue. It looks fine at my newly created space
<img width="1440" alt="screen shot 2017-12-11 at 1 55 27 pm" src="https://user-images.githubusercontent.com/10396359/33821728-f92cb618-de7a-11e7-84c0-de04ee7955b5.png">

**Comment by qodfathr** [comment]
Fixed.
