### ISSUE TITLE
Planner - quick add does not clear after the first work item is added under a space

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#1609]
Quick add does not clear after the first work item is added under a space.

![quickaddnotcleared](https://user-images.githubusercontent.com/1892722/33817816-6ba84fdc-de39-11e7-91f8-448aa7acfd5e.png)

Also, a message is displayed that the newly created work item does not match the applied filter.

**Comment by sbose78** [comment]
Hi @nimishamukherjee  if it helps for tracking and work estimation purposes, would you suggest tracking the 2 bugs in separate github issues ?

**Comment by qodfathr** [comment]
No need for 2 issues -- it appears both are fixed. :)
