### ISSUE TITLE
E2E have hardcoded github username

### ISSUE THREAD

**Issue by vpavlin** [openshiftio/openshift.io#1611]
Filed an issue against fabric8-test: https://github.com/fabric8io/fabric8-test/issues/353

I've setup an E2E test for an account which has idler enabled to verify it works consistently. This account uses my GH account and as GH username is hardcoded in tests, it fails due to check for GH repo url every time even if everything else succeeds.

@ldimaggi 

## Impacts
#2140 OpenShift.io has automated end-to-end (E2E) tests

**Comment by joshuawilson** [comment]
Has this been changed?
@ldimaggi do know if we have a plan to fix this?

**Comment by ldimaggi** [comment]
I think we need to fix this first - https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/846

**Comment by ldimaggi** [comment]
The hardcoded name has been removed - https://github.com/fabric8io/fabric8-test/pull/422

**Comment by ldimaggi** [comment]
The name is set as a default - the CICO job definition over-rides the value.
