### ISSUE TITLE
[prod-preview] Missing a few namespaces on console.free-int.openshift.com

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#1612]
For some reason there are only 3 projects on free-int for my account: 

![image](https://user-images.githubusercontent.com/1461122/33804270-aa56d2a0-dda1-11e7-887d-8ef626caa35a.png)

**Comment by rhopp** [comment]
Our testing account (kkanova-osiotest1) is also missing one project (kkanova-osiotest1-che).
![image](https://user-images.githubusercontent.com/1215011/33827467-c16e4a14-de68-11e7-8eb5-9fd2374f5d18.png)

**Comment by aslakknutsen** [comment]
Tenant service is failing with "Unknown type: Job"

**Comment by aslakknutsen** [comment]
@ibuziuk Both ibuziuk-jenkins and ibuziuk-stage return 500 from Openshift on ProjectRequest for some unknown reason. req_id: "FiEQQqimbc-38516"

**Comment by ibuziuk** [comment]
@aslakknutsen hmmm... what actually triggers project creation ? is it first time login ?

**Comment by aslakknutsen** [comment]
@ibuziuk Any calls to get /api/user if it's not been setup before and the accounts are linked

**Comment by jfchevrette** [comment]
Is that occurring on a reset tenant? If so then I think what is happening is that we're not waiting long enough after the deletion of namespaces and OpenShift is unable to re-create them.

I've observed a situation where the namespaces was gone (missing from oc get projects) but OpenShift would return an error when trying to re-create it shortly after deleting it.

**Comment by aslakknutsen** [comment]
> I've observed a situation where the namespaces was gone (missing from oc get projects) but OpenShift would return an error when trying to re-create it shortly after deleting it.

Observed that as well. It seems to happen primary with Jenkins and Che namespaces. As if the che/jenkins pods are taking their sweet time to shutdown which holds onto a ghost namespace.

I don't think that was the case here tho, nut I might be wrong.

**Comment by jfchevrette** [comment]
> Observed that as well. It seems to happen primary with Jenkins and Che namespaces. As if the che/jenkins pods are taking their sweet time to shutdown which holds onto a ghost namespace.

that is my impression too

**Comment by rhopp** [comment]
@aslakknutsen @jfchevrette Is there anything we can do to unbork our accounts?

**Comment by rhopp** [comment]
I've relinked my prod-preview account to free-stg and I have exactly the same problem there.

**Comment by joshuawilson** [comment]
What is the status of this?

**Comment by ibuziuk** [comment]
free-int is no longer used as prod-preview cluster, so probably we can just close this one as out-of-date

**Comment by ibuziuk** [comment]
@rhopp ah, sorry - looks like you have the very same problem on https://console.free-stg.openshift.com. Reopening, but I can not repro it on new cluster

**Comment by rhopp** [comment]
I had the same problem on free-stg, but it's solved now. @ibuziuk feel free to close this one (I don't have rights to do that)
