### ISSUE TITLE
Intermittent failure seen today - Che reports error starting workspace - "Workspace agent is no longer responding"

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1616]
Steps to recreate:
* Create new space
* Create new project - quickstart
* Create codebase
* Observe this error in the Che IDE:
```
Workspace agent is no longer responding. To fix the problem, verify you have a good network connection and restart the workspace.
```

![screenshot from 2017-12-11 07-53-26](https://user-images.githubusercontent.com/642621/33832110-b32f6700-de48-11e7-939a-ce01ad770e4a.png)

**Comment by ibuziuk** [comment]
@ldimaggi I believe the fix is already in prod, could you please verify ?

**Comment by ibuziuk** [comment]
@ldimaggi @rhopp closing. Feel free to reopen
