### ISSUE TITLE
List of recent spaces overflows when containing 7 items

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#1617]
1. (create and) visit 7 spaces
2. navigate back to home page

result:
* list of recent spaces overflows (in Chrome 63 and Firefox 57)

![osio_recent_spaces_overflow](https://user-images.githubusercontent.com/445100/33832463-90354c0e-de7c-11e7-9299-212b6605f5a1.png)

**Comment by joshuawilson** [comment]
@mindreeper2420 is this fixed?

**Comment by mindreeper2420** [comment]
I’ll need to check against Master, as I don’t think the fix made it to prod before the freeze. I’ll update this story once I know.

**Comment by mindreeper2420** [comment]
@joshuawilson There was an oddity that threw an error when the card's internal structure was not the same (it differs depending on the data inside of it). I filed PR https://github.com/fabric8-ui/fabric8-ui/pull/2349 to remedy this situation.

**Comment by mindreeper2420** [comment]
@joshuawilson I just tested this on production - issue is resolved.
![screen shot 2018-01-23 at 4 04 21 pm](https://user-images.githubusercontent.com/4032718/35300649-1b096be8-0057-11e8-8d9a-953dfd09d650.png)
