### ISSUE TITLE
Gremlin returns a message with exception for selected packages from the NPM ecosystem

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1619]
# Environment
- graph database prepared for the staging environment

# Problem description
It is impossible to get info about some packages from the NPM ecosystem. The following query returns an error message:

```
g.V().has("pecosystem", "npm")
```

Error message:

```
{   'Exception-Class': 'java.lang.IllegalArgumentException',
    'message': 'Encountered missing datatype registration for number: 32'}
```

## Problematic packages
I have detected this issue for the following 7 packages out of 1697 packages for the NPM ecosystem:

```
eslint
uglify-js
crumb
docco
karma-qunit
karma
qunit-cli
```

# Reproducer
(aka howto get list of problematic packages)

```
import requests

URL="http://STAGE_DATABASE"


def gremlin_search_packages_for_the_ecosystem(ecosystem):
    for i in range(0, 1697):
        # get just the name of the package
        query = 'g.V().has("pecosystem", "npm")[{i}].value("pname")'.format(i=i)
        name = post_query(query)["result"]["data"][0]

        # now try to get all attributes
        query = 'g.V().has("pecosystem", "npm")[{i}]'.format(i=i)
        data = post_query(query)
        try:
            # try to access metadata returned when there's no exception
            x = data["result"]["data"][0]
        except Exception as e:
            print(name)

def post_query(query):
    data = {"gremlin": query}
    response = requests.post(URL, json=data)
    return response.json()

gremlin_search_packages_for_the_ecosystem("npm")

```

**Comment by miteshvp** [comment]
@tisnik - thanks for a detailed log. I went through this data on staging graph and S3. On further debugging, figured out that all the said packages has one or more nodes in inconsistent state. So I had to remove some properties, or remove the nodes itself in the graph and then re-sync the packages that are available in staging S3 onto graph. To note, for below packages there was no data in S3 and hence removed them from staging graph.
```
docco
karma-qunit
qunit-cli
```
Can you please try again and see if this is resolved now? 
TYVM

**Comment by tisnik** [comment]
Thanks a lot @miteshvp . I'm on it.

**Comment by GeorgeActon** [comment]
@miteshvp can you add a severity level to this bug.

**Comment by tisnik** [comment]
@miteshvp staging graph DB API seems to be overloaded ATM, but at least one package is still in inconsistent state:

```
eslint
```

**Comment by miteshvp** [comment]
@tisnik - Updated the graph DB again. Please retry and let me know. TYVM.

**Comment by tisnik** [comment]
The check now passes for all NPM packages, so TYVM => I'm closing this issue.
