### ISSUE TITLE
Landing page - abrupt end of paragraph

### ISSUE THREAD

**Issue by adisakala** [openshiftio/openshift.io#162]
On home page, www.openshift.io, The following paragraph is incomplete. It is missing a word at the end.

Allow development teams be more confident in the technology decisions they make.
OpenShift.io helps developers make better decisions. It provides actionable recommendations and insights around the software components developers use. OpenShift.io Analytics applies machine learning algorithms based on their usage pattern of components. The data is gathered from various public data sources such as Github, Maven and NPM along with our own internal OpenShift data. Through this comprehensive dataset, developers get tangible information for credible

Please append "decision-making." to above paragraph

**Comment by mindreeper2420** [comment]
fixed with PR https://github.com/openshiftio/openshift.io/pull/175
