### ISSUE TITLE
Add service for scaling deployment pods up and down

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1622]
There should be a service (mock at least) for scaling a deployment's pods up or down. The buttons and action already exist but currently do nothing. See `deployments-donut-component.ts`

**Comment by stooke** [comment]
There is a mock service available in the sandbox WIT repo.

**Comment by stooke** [comment]
The current implementation has been coded but does not sucessfully store the new pod scale value.

**Comment by jiekang** [comment]
This issue was initially meant to track the front end work as it still needs some work. I guess it can track both frontend and backend.

**Comment by jiekang** [comment]
A PR for this has been merged on the UI side. For the UI, the last step is to swap the service from returning mock data, to making a http request and returning the data in the response.

**Comment by stooke** [comment]
Current status on the API side: code has been written, will be in the coming PR.
As per @xcoulon request, a future PR will change the API for this to become more JSON-API conformant

**Comment by jiekang** [comment]
Closing as a service is available now.
