### ISSUE TITLE
Use Tenant API to get cluster, etc.

### ISSUE THREAD

**Issue by stooke** [openshiftio/openshift.io#1623]
Currently the WIT /apps implementation accesses the Auth and WIT APIs to get some information such as cluster and namespaces, when it proably should used the Tenant API.

Change the code to use the Tenant API - current showstopper - what is the Teant URL?

**Comment by jiekang** [comment]
@stooke is this still a valid issue or can it be closed?

**Comment by stooke** [comment]
Still an issue, will probably change this to also use the Proxy server where possible.

**Comment by stooke** [comment]
Closing, as we'll be using the proxy server for this.
