### ISSUE TITLE
[5] Implement Referential Integrity (RI) tests for the data stored in S3 database

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1635]
We need to implement some sort of RI tests for the data stored in the S3 database.

### Package level metadata

- [x] identify all missing records (like missing JSON metadata etc.)
- [x] identify all leftovers (metadata used before, but not ATM)

### Version level metadata

- [x] identify all missing records (like missing JSON metadata etc.)
- [x] identify all leftovers (metadata used before, but not ATM)

### Note

Such tests are to be run separately from the IT started on each PR.

**Comment by sivaavkd** [comment]
@tisnik - are we targeting this for the current sprint ?

**Comment by tisnik** [comment]
Implemented in several PR:

- https://github.com/fabric8-analytics/fabric8-analytics-common/pull/506
- https://github.com/fabric8-analytics/fabric8-analytics-common/pull/510
- https://github.com/fabric8-analytics/fabric8-analytics-common/pull/511
- https://github.com/fabric8-analytics/fabric8-analytics-common/pull/514
- https://github.com/fabric8-analytics/fabric8-analytics-common/pull/515
- https://github.com/fabric8-analytics/fabric8-analytics-common/pull/516
