### ISSUE TITLE
If a user's attempt to reset his OSIO environment fails, no root cause, or suggested actions are provided

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1637]
Steps to recreate:
* Reset a user's environment

The reset often fails, but a root cause for the failure is not communicated to the user. Generally, it is possible to reset the environment if a 2nd (or 3rd) attempt is made. We should present error information, and a suggestion for the user's next steps.

![screenshot 79](https://user-images.githubusercontent.com/642621/33886993-52a8d94c-df16-11e7-8bb7-520be2130987.png)

**Comment by joshuawilson** [comment]
@ldimaggi do you have a reliable way to reproduce this?

**Comment by ldimaggi** [comment]
No - sadly - the bug is random. It seems better now, since the change to Che - will watch this and hopefully close it if the problem is not seen.

**Comment by ldimaggi** [comment]
Just saw it again....

![screenshot from 2017-12-22 07-46-55](https://user-images.githubusercontent.com/642621/34298914-18de12ec-e6ee-11e7-8122-e8faf7686b83.png)

**Comment by joshuawilson** [comment]
@aslakknutsen @jfchevrette @vpavlin any idea why the reset would not work?

**Comment by jfchevrette** [comment]
What I have seen in the past is that OpenShift API calls return before the actual backing resources are deleted (which can take some time as pods are gracefully terminated, etc..). If we immediately try to re-create namespaces and/or resources before OpenShift has had the time to terminate them, this can result in a tenant that is half reset (or half recreated)

One potential solution would be to check if the resources have been terminated before trying to re-create them.

**Comment by aslakknutsen** [comment]
@jfchevrette That is a known issue, but the effect has been that it can't create the namespace. While you can't see the namespace it's hanging in the backend waiting for the Jenkins/Che to shutdown so the API return a naming conflict when tenant tries to recreate the namespace. Never seen it fail on a single DC.

**Comment by ldimaggi** [comment]
Closing this issue - no updates since January - has not been seen recently.
