### ISSUE TITLE
In Planner, clicking on "My Work Items" also displays workitems assigned to other users

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1638]
Steps to recreate:
* In the 'Account Home' display, select 'My Work Items':
![screenshot 80](https://user-images.githubusercontent.com/642621/33888894-6b32ccce-df1c-11e7-8d1d-25fadf3baf5f.png)

* Observe that the workitems displayed include workitems assigned to other users:
![screenshot 81](https://user-images.githubusercontent.com/642621/33889197-61944b1a-df1d-11e7-8af9-23c3fb8b0e33.png)

* Observe the contrast to viewing your workitems through a filter:
![screenshot 82](https://user-images.githubusercontent.com/642621/33889225-76e16480-df1d-11e7-8bed-57bba35c8e82.png)

**Comment by joshuawilson** [comment]
@catrobson can you confirm that the `my work items` on the dashboard should be those assigned to me vs the ones I've made.

**Comment by catrobson** [comment]
@joshuawilson - Correct, these should be work items assigned to me.

**Comment by qodfathr** [comment]
@ldimaggi is this still happening?

**Comment by ppitonak** [comment]
Seems to be outdated.

**Comment by nimishamukherjee** [comment]
@ldimaggi please check. Now the work item's detail page opens up.

**Comment by ldimaggi** [comment]
This is still a bug:

![screenshot from 2018-02-28 13-40-40](https://user-images.githubusercontent.com/642621/36806194-421b55be-1c8d-11e8-8d49-8bd4db630dd4.png)

**Comment by ldimaggi** [comment]
No longer a bug - closing.
