### ISSUE TITLE
Usability issue with Welcome Emails

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#164]
You first receive a Welcome to OpenShift.com
https://screencast.com/t/Nz3zaEZFWa2
then you receive a Welcome to OpenShift.io
https://screencast.com/t/GWOyz1WVxgoP
which email does the user follow?
where do I go for help?
this is a no-reply email which always sucks

Also, the openshift.com email refers to something that is NOT my username.  It says "rhn-engineering-bsutter" while I used "bsutter@redhat.com" as my login.  Granted, the generated openshift.com project name is
https://console.starter-us-east-2.openshift.com/console/project/rhn-engineering-bsutter/overview
but it is still confusing

**Comment by pmuir** [comment]
Unfortunately rhn-engineering-bsutter is your username, but you logged in using your email 'bsutter@redhat.com'. We have a page at first login which allows you to change your username, but not all the backend systems are using that new username yet - it will be online soon.

@luciddreamz we should rationalize those emails...

**Comment by joshuawilson** [comment]
cc @qodfathr

**Comment by qodfathr** [comment]
This is getting addressed, but I don't think it's technically a bug. Everything is working as specified. It's just what was specified was not good. :) I recommend switching to `kind/enhancement`; thoughts @joshuawilson? Will be addressed during sprint 141.

**Comment by joshuawilson** [comment]
@qodfathr works for me. I updated it.

**Comment by qodfathr** [comment]
New email deployed; only one is sent. Users have successfully completed Hello World.
