### ISSUE TITLE
On prod-preview, rollout to run fails (FailedCreatePodSandBox Failed create pod sandbox) - other previously reported issues seem to have been resolved

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1640]
On prod-preview today - I was able to create a new app/quickstart, run its build pipeline, deploy to stage, create a Che workspace, and run an analytic report.

Deploying to run fails:

![screenshot from 2017-12-12 11-06-54](https://user-images.githubusercontent.com/642621/33895402-6c00face-df2e-11e7-9674-c3cc561eba61.png)

![screenshot from 2017-12-12 11-07-27](https://user-images.githubusercontent.com/642621/33895400-6be8760c-df2e-11e7-8803-95c505a605e3.png)

[jenkins_log.txt](https://github.com/openshiftio/openshift.io/files/1552400/jenkins_log.txt)

**Comment by rawlingsj** [comment]
Any information about why the pod didn't start?  Did the pod fail?  Any events? i.e. `oc describe pod foo -n my-run`

**Comment by ldimaggi** [comment]
Retrying now - question - are you seeing this rollout to run successfully?

**Comment by ldimaggi** [comment]
Is this the root cause?   FailedCreatePodSandBox  Failed create pod sandbox.

```
oc describe pod -n ldimaggi-osiotest1-run
Name:                   dec13-1-deploy
Namespace:              ldimaggi-osiotest1-run
Security Policy:        restricted
Node:                   ip-172-31-59-87.ec2.internal/172.31.59.87
Start Time:             Wed, 13 Dec 2017 09:01:17 -0500
Labels:                 openshift.io/deployer-pod-for.name=dec13-1
Annotations:            kubernetes.io/limit-ranger=LimitRanger plugin set: cpu, memory request for container deployment; cpu, memory limit for container deployment
                        openshift.io/deployment-config.name=dec13
                        openshift.io/deployment.name=dec13-1
                        openshift.io/scc=restricted
Status:                 Pending
IP:
Controllers:            <none>
Containers:
  deployment:
    Container ID:
    Image:              registry.reg-aws.openshift.com:443/openshift3/ose-deployer:v3.8.18
    Image ID:
    Port:
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Limits:
      cpu:      1
      memory:   512Mi
    Requests:
      cpu:      50m
      memory:   256Mi
    Environment:
      KUBERNETES_MASTER:        https://ip-172-31-50-177.ec2.internal
      OPENSHIFT_MASTER:         https://ip-172-31-50-177.ec2.internal
      BEARER_TOKEN_FILE:        /var/run/secrets/kubernetes.io/serviceaccount/token
      OPENSHIFT_CA_DATA:        -----BEGIN CERTIFICATE-----

(removed for this issue report)

-----END CERTIFICATE-----

      OPENSHIFT_DEPLOYMENT_NAME:        dec13-1
      OPENSHIFT_DEPLOYMENT_NAMESPACE:   ldimaggi-osiotest1-run
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from deployer-token-cpp7f (ro)
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  deployer-token-cpp7f:
    Type:       Secret (a volume populated by a Secret)
    SecretName: deployer-token-cpp7f
    Optional:   false
QoS Class:      Burstable
Node-Selectors: type=compute
Tolerations:    <none>
Events:
  FirstSeen     LastSeen        Count   From                                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                                    -------------   --------        ------                  -------
  13m           13m             1       default-scheduler                                       Normal          Scheduled               Successfully assigned dec13-1-deploy to ip-172-31-59-87.ec2.internal
  12m           12m             1       kubelet, ip-172-31-59-87.ec2.internal                   Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "deployer-token-cpp7f"
  12m           5m              12      kubelet, ip-172-31-59-87.ec2.internal                   Normal          SandboxChanged          Pod sandbox changed, it will be killed and re-created.
  12m           1m              17      kubelet, ip-172-31-59-87.ec2.internal                   Warning         FailedCreatePodSandBox  Failed create pod sandbox.
```

**Comment by rawlingsj** [comment]
There you can see the error message `Pod sandbox changed, it will be killed and re-created.`

I've no idea what that's related to I'm afraid but a quick google suggests to check the kublets log.  Maybe SD team can help here?

**Comment by rawlingsj** [comment]
Here's an issue with the same error message, not sure if the same cause as well but worth referencing https://github.com/openshift/openshift-ansible/issues/5235

**Comment by rawlingsj** [comment]
@joshuawilson not sure if you saw my comments above https://github.com/openshiftio/openshift.io/issues/1640#issuecomment-351436644

Not sure why you added the build-cd label perhaps you meant to add SD?  This seems to be an infra related issue and my guess is it requires investigation from someone that has access to the kubelet logs or someone that might know what the error message means.  But that is the reason the pod isn't starting.

**Comment by rawlingsj** [comment]
@kbsingh is there someone you know that can help out here?

**Comment by mmclanerh** [comment]
@rawlingsj   @ldimaggi  Free-int was updated to 3.8, which introduced some instability.  Late yesterday, prod-preview was moved to free-stg.  Please retry (after relinking/relogging in) and see if this is still an issue.

**Comment by ldimaggi** [comment]
Retrying this is blocked by:  https://github.com/openshiftio/openshift.io/issues/1677

**Comment by mmclanerh** [comment]
likely similar root cause for prod-preview as was affecting production https://github.com/openshiftio/openshift.io/issues/1666 
the aos team is collecting data to better understand why this happened, before restarting controller.

**Comment by mmclanerh** [comment]
controllers restarted, pod creation seems fine now -- however, quickstarts in prod-preview are broken likely do to https://github.com/fabric8-ui/fabric8-ui/pull/2309#issuecomment-352011771

**Comment by ldimaggi** [comment]
Closing - problem is no longer seen. Thx!
