### ISSUE TITLE
Can unstable unit tests in fabric8-ui be disabled?

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1641]
There are a few unit tests in `fabric8-ui` that intermittently fail on jenkins.

Notably:

`src/a-runtime-console/kubernetes/ui/app/list/list.app.spec.ts`
`src/a-runtime-console/kubernetes/ui/environment/list/list.environment.spec.ts`

```
FAILED TESTS:

  AppListComponent
    ✖ should create
      PhantomJS 2.1.1 (Linux 0.0.0)
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

  EnvironmentListComponent
    ✖ should create
      PhantomJS 2.1.1 (Linux 0.0.0)
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

These specs each have a single test that only verifies the component is created. As well, these emit warnings:
```
ERROR: 'Error during cleanup of component', EnvironmentListPageComponent
ERROR: 'Error during cleanup of component', AppListPageComponent
```
 I don't think the tests have any value and have a possibility of affecting the stability of the entire unit test run (async and component cleanup issues). The components will eventually be removed in favor of the Deployments page [1]. Can these tests be disabled? 

[1] https://github.com/openshiftio/openshift.io/issues/287

**Comment by jiekang** [comment]
@joshuawilson Thoughts? If acceptable I don't mind submitting a PR for this.

**Comment by joshuawilson** [comment]
@jiekang go ahead and submit the PRs to fix or disable, they are in code that is getting removed.

**Comment by jiekang** [comment]
Closing as a fix was merged.
