### ISSUE TITLE
Pipeline fails a test that passes

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#1642]
There are builds that sometimes pass and sometimes fail. This one is failing on a test that otherwise passes. 

There are 2 errors and then the fail:
```
AppListPage
    ✔ should create
ERROR: 'Error during cleanup of component'
```

```
EnvironmentListPage
    ✔ should create
ERROR: 'Error during cleanup of component'
```
The fail is at 
```
DeploymentsComponent
    ✖ should set service result to environments property
```

This is on PR https://github.com/fabric8-ui/fabric8-ui/pull/2305 for some html/css changes
The log is at https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-ui/view/change-requests/job/PR-2305/4/console

**Comment by rawlingsj** [comment]
These are repo specific tests which are the responsibility of the repo maintainers.  The pipeline team doesn't have the capacity to fix unreliable tests but if there's more context added to the issue perhaps they can provide advice and suggested investigation steps.

**Comment by joshuawilson** [comment]
@rawlingsj This may be tests but they passed 3 times and then something failed them, then they passed. 
It may be that there is something in the test, but it always passes locally. If the pipeline can not consistently and reliably run the same thing every time it is a pipeline issue.

**Comment by joshuawilson** [comment]
The next build failed differently, recorded at #1643.
The one after that passes. 

To be clear, the Platform team is looking at the tests. That is why I listed both teams on the issue, so we could work together on it.

**Comment by joshuawilson** [comment]
The tests were commented out, this is fixed.
