### ISSUE TITLE
Planner: New Task, drop-down list box overlays the text field

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#165]
see screenshot
https://screencast.com/t/nw4hCfKId

Browser scaled to 100% 
MacOS
Chrome
screen resolution: Default for Display (built-in Retina Display)

**Comment by burrsutter** [comment]
scaling to 75% (command -) allows me to hit the blue button
https://screencast.com/t/Znyt0yxkPeG

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#1914

**Comment by bmicklea** [comment]
reopening because the root issue fabric8io/fabric8-planner#1914 is not yet closed.

**Comment by joshuawilson** [comment]
@bmicklea we can close them if they are tracked in another repo OR we can keep this duplicated open. Either is fine, just saying.
