### ISSUE TITLE
In OSIO builds are not going through in my pipeline view.

### ISSUE THREAD

**Issue by sanketpathak** [openshiftio/openshift.io#1650]
I have tried resetting the environment and updating the tenant but the problem exists

![s02](https://user-images.githubusercontent.com/10252230/33938620-2461f06e-e02e-11e7-861c-f6b51eba0521.png)

**Comment by ldimaggi** [comment]
In OSO - can you check and see if the Che and Jenkins pods are up and running?

**Comment by sanketpathak** [comment]
No there status shows 'failed'.

**Comment by joshuawilson** [comment]
Is this still an issue?

**Comment by sanketpathak** [comment]
Build happens successfully but sometimes failure occurs. I think this issue can be closed.
