### ISSUE TITLE
In the OSIO Planner, queries that contain 3 or more filters *sometimes* return incorrect data

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1656]
See the attached screenshot - the query returned workitems for assignees other than the one designated in the query:

![screenshot 85](https://user-images.githubusercontent.com/642621/33959189-aff0aa72-e014-11e7-8e8f-4e0b8f944aae.png)

**Comment by ldimaggi** [comment]
This seems to be a intermittent/random issue.

**Comment by qodfathr** [comment]
@ldimaggi still happening in new Planner? Is there a regression test for this?

Perhaps #1638 is related?

**Comment by ldimaggi** [comment]
Closing - not seeing this now.
