### ISSUE TITLE
UI: Show pod deployment status icon

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1659]
The pod deployment status should be shown via the green checkmark icon in the mock [1].

If a pod deployment fails, the UI should show a warning icon instead of the green checkmark as shown in the mock [2]. The tooltip should state what caused the failure, e.g. 'Would exceed memory quota', or 'Would exceed CPU quota'.

[1] https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/260764292
[2] https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/262786732

**Comment by jiekang** [comment]
Initial work: https://github.com/fabric8-ui/fabric8-ui/pull/2351

**Comment by chrislessard** [comment]
A solution in under review [here](https://github.com/fabric8-ui/fabric8-ui/pull/2373).

**Comment by chrislessard** [comment]
Can we close this ?

**Comment by jiekang** [comment]
After thought, I'm closing this issue as done. I'll open an appropriate issue for the next step.
