### ISSUE TITLE
API: Provide URLs for logs, openshift console and application

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1662]
The deployments page needs to allow users to access certain URLs for each deployment [1].

Per deployment:
- View logs
- View OpenShift console
- Open application (if application has an endpoint)

[1] https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/260764295

**Comment by stooke** [comment]
This will be implemented after the API becomes JSON-API conformant.

**Comment by andrewazores** [comment]
This API is available since: https://github.com/fabric8-services/fabric8-wit/pull/1870.

**Comment by jiekang** [comment]
Closing as completed. Thanks!
