### ISSUE TITLE
On prod-preview - env reset fails - user prevented from OSO login

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1675]
Steps to recreate:
* Login to OSIO
* Perform env reset
* Observe login screen:

![screenshot from 2017-12-14 07-41-40](https://user-images.githubusercontent.com/642621/33992949-8451d11e-e0a2-11e7-9024-ecbf22b34f23.png)

* Attempt login through top button - observe login failure:

![screenshot from 2017-12-14 07-41-57](https://user-images.githubusercontent.com/642621/33992982-a703db08-e0a2-11e7-8a30-f4f4e308e85e.png)

**Comment by jfchevrette** [comment]
You should be able to use the 'Sign Up' link to register an account on the new stage cluster.

**Comment by aditya-konarde** [comment]
There's the workaround, and this is related to Staging, can we remove the SEV1 label?

**Comment by sbose78** [comment]
"Sign Up" and proceed the usual way, you'll be able to get past.

**Comment by ldimaggi** [comment]
Closing - the solution was to re-sign up.
