### ISSUE TITLE
Changes to text at Stack report

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1676]
1) Replace text 'Components with suggested alternatives' with the text 'Alternative Components' and subtitle as 'Components similar to what you are using that you may consider as alternatives'.

2) When using colors ensure that the icons are also different to avoid color blind situations

3) Replace text 'Suggested component details' with the text 'Alternative component details'

4) Present icons with coloring beside the manifest name to indicate critical issues or important issues

5) Recheck the reason being shown for 'Alternative component details'..

**Comment by sunilk747** [comment]
Closing this issue as it is handled as part of new UI.
