### ISSUE TITLE
New project/app fails on prod-preview

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1677]
This error is being seen when attempting to create a new project/app/quickstart on prod-preview:

![screenshot from 2017-12-14 09-16-27](https://user-images.githubusercontent.com/642621/33996600-b2833958-e0af-11e7-8ea2-724da3e6f310.png)

**Comment by alexeykazakov** [comment]
@ldimaggi make sure you re-linked your OSO account in prod-preview (we switched from int to stg cluster yesterday)

**Comment by ldimaggi** [comment]
Yes - this was AFTER I successfully relinked the account - thx!

**Comment by ldimaggi** [comment]
roblem - only once so far - on production:

![screenshot from 2017-12-14 11-47-18](https://user-images.githubusercontent.com/642621/34004289-7aebedc6-e0c5-11e7-974a-873743073adf.png)

**Comment by mmclanerh** [comment]
likely similar root cause for prod-preview as was affecting production https://github.com/openshiftio/openshift.io/issues/1666 
the aos team is collecting data to better understand why this happened, before restarting controller.

**Comment by ldimaggi** [comment]
Errors still being seen:

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
execute:1 POST https://forge.api.prod-preview.openshift.io/forge/commands/fabric8-new-project/execute 412 (Precondition Failed)
execute:1 POST https://forge.api.prod-preview.openshift.io/forge/commands/fabric8-new-project/execute 412 (Precondition Failed)
fabric8-ui-global-overrides.less:2 An error occurred Response {_body: "{"messages":[{"description":"The repository dec142…dy exists!","severity":"ERROR","input":"named"}]}", status: 412, ok: false, statusText: "Precondition Failed", headers: Headers, …}
```

**Comment by mmclanerh** [comment]
prod-preview still in likely broken state. aos team is using it to gather forensics on why restarting controllers fixed similar issue with production.  myself or @jfchevrette will update once prod-preview is fixed.

**Comment by mmclanerh** [comment]
prod-preview is able to spin up pods correctly now.  with that out of the way, this bug looks like its related to https://github.com/fabric8-ui/fabric8-ui/pull/2309#issuecomment-352011771

**Comment by ldimaggi** [comment]
Closing - problem is no longer seen. Thx!
