### ISSUE TITLE
Pipelines Edit takes us to a 404

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#1678]
From https://openshift.io/cboudjna/Space1/create/pipelines, if I click on the button Edit as per the screenshot : 

![image](https://user-images.githubusercontent.com/98980/33998458-d1710d30-e0e7-11e7-8b64-2edb069c6948.png)

This would get me to this URL https://openshift.io/cboudjna/Space1/create/pipelines/space1/edit and then 404 for me : 

![image](https://user-images.githubusercontent.com/98980/33998484-e7f415b6-e0e7-11e7-9f2c-fd981aad1e61.png)

**Comment by catrobson** [comment]
@joshuawilson do you know if there is a way to route directly into the XML editor in OpenShift?  I think the best we could do is have this route to the Pipelines page in OpenShift, which is the same thing as other links on this page do.

**Comment by joshuawilson** [comment]
We might be able to, I haven't looked at the URL. Something to explore.

**Comment by joshuawilson** [comment]
I thought we were removing the `edit` option.

**Comment by catrobson** [comment]
@joshuawilson yes, you’re right :). Let’s remove as agreed!

**Comment by qodfathr** [comment]
Fixed via removal.
