### ISSUE TITLE
User env reset intermittent failure - in at least some cases due to EBS failures

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1680]
Seeing this issue intermittently - on https://openshift.io - after a user resets the user env, one or more pods (Che, Content Repo, Jenkins) fails to start.

It looks like this is caused by intermittent EBS failures - see screenshots below.

The work around for the user is to access the OSO console and manually redeploy the pod(s).

Seeing this problem about 10-20% of the time today.

![screenshot from 2017-12-14 11-10-27](https://user-images.githubusercontent.com/642621/34002494-bb749168-e0c0-11e7-90d1-272cd29dc840.png)
![screenshot from 2017-12-14 11-06-00](https://user-images.githubusercontent.com/642621/34002496-bb8be340-e0c0-11e7-9a4f-3c471e6ce5c3.png)
![screenshot from 2017-12-14 11-05-01](https://user-images.githubusercontent.com/642621/34002497-bb9af2c2-e0c0-11e7-8df3-615a86fb93c4.png)
![screenshot from 2017-12-14 11-04-28](https://user-images.githubusercontent.com/642621/34002498-bbadb754-e0c0-11e7-96c9-a83e1b2229e7.png)

**Comment by joshuawilson** [comment]
are you still seeing this?

**Comment by ldimaggi** [comment]
Haven't seen this since Che switch to multi-tenant - will retry today and hopefully close.
