### ISSUE TITLE
Possibility of cyclic link chains when using tree/dependency topology

### ISSUE THREAD

**Issue by kwk** [openshiftio/openshift.io#1682]
**See https://github.com/fabric8-services/fabric8-wit/issues/1809 for the issue in the correct repository.**

Currently it is possible to create a link cycle like this where the `task` is both: a child and a parent in the same link chain.

```
task
  scenario
    experience
      feature
        task
```

We have checks in place to do avoid this

```
  scenario
    task
      experience
        feature
          task
```

because here the `task` actually appears in two links as the `target_id`.

**!!! THIS NEEDS AN URGENT FIX !!!**

**Comment by joshuawilson** [comment]
@kwk who do you suggest fix this? It has been sitting here 6 days now?

**Comment by kwk** [comment]
> @kwk who do you suggest fix this? It has been sitting here 6 days now?

@joshuawilson it is assigned to me, so I'm supposed to fix this. And there's already a PR open. I tried to be extremely pedantic about changing the `status/XY` label to indicate what's happening. Please have a look at this pending PR https://github.com/fabric8-services/fabric8-wit/pull/1810.

**Comment by joshuawilson** [comment]
sorry, I missed the assignment ;-)
