### ISSUE TITLE
App-wizard/forge multi-cluster support

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#1684]
As part of our multi-cluster support we should start using OSO-Proxy for all communications with OSO instead of calling OSO API directly from Forge/app-wizard.

- [x] Change OSO api URL to OSO-Proxy URL and use OSIO user token instead of OSO token
- [x] Remove OSO token lookup.

Part of #948

**Comment by maxandersen** [comment]
just to be clear I believe this affects the exisiting launcher wizard and possibly in the backend if forge calls directly to the OS api.

**Comment by adisakala** [comment]
@GeorgeActon please triage this issue with @gastaldi and get it assigned to right people both on wizard side and backend side. Since we have stream lined the codebase may be @gastaldi could take care of backend aspects.

**Comment by GeorgeActon** [comment]
@adisakala, Discussion should already be happening ( @krishnapaparaju & @gastaldi discussing this). Understanding the work can happen now, but to deliver it, the launcher-backend has to be deployed in staging first and with vacation that will be in Jan (since it is a large change).

**Comment by joshuawilson** [comment]
What is the status on this?

**Comment by arunkumars08** [comment]
@joshuawilson This activity could be taken as a part of the coming sprint. Also, the proxy is not yet ready I guess.

**Comment by alexeykazakov** [comment]
Proxy is available in preview. Please start working on this ASAP.

**Comment by maxandersen** [comment]
marking as crucial dependency for #948 as without it we can't complete multicluster support.

**Comment by gastaldi** [comment]
I'll do it. What is the proxy URL?

**Comment by alexeykazakov** [comment]
@gastaldi https://github.com/redhat-developer/rh-che/pull/514#issuecomment-360005601

**Comment by gastaldi** [comment]
I created https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1164 asking to update the OSIO OPENSHIFT API URL. Once that is done, we can merge https://github.com/fabric8-launcher/launcher-backend/pull/34

**Comment by gastaldi** [comment]
Proxy URLs for reference: 

Staging:  https://f8osoproxy-test-dsaas-preview.b6ff.rh-idev.openshiftapps.com
Production: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com

**Comment by gastaldi** [comment]
Changed in prod-preview.

**Comment by gastaldi** [comment]
It works in Prod-preview for me. Can someone test that too?

**Comment by gastaldi** [comment]
Updated in production. Closing this issue. Reopen if the problem persists.
