### ISSUE TITLE
OSIO UI multi-cluster support 

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#1685]
As part of our multi-cluster support we should start using OSO-Proxy for all communications with OSO instead of calling OSO API directly from OSIO UI (pipelines/applications).

- [ ] Change OSO api URL to OSO-Proxy URL and use OSIO user token instead of OSO token
- [ ] Remove OSO token from local storage. We don't need OSO token in UI anymore.
- [x] Switch OSO account linking to new Auth API (the same API which is currently used to connect GitHub account) in getting started page + user profile

Part of #948

**Comment by joshuawilson** [comment]
@dlabrecq you think you want to take this on?

**Comment by alexeykazakov** [comment]
Is anyone working on this?

**Comment by joshuawilson** [comment]
I don't think anyone has taken this on yet.
@dgutride do you have time to look at this?

**Comment by dlabrecq** [comment]
@joshuawilson / @dgutride We had spoken about this issue during UXD planning a couple sprints back. It was suggested that another team was working in this same area?

**Comment by maxandersen** [comment]
marking as crucial dependency for #948 as without it we can't complete multicluster support.

**Comment by sthaha** [comment]
@alexeykazakov Pipeline UI kebab shows an option to `Open in Openshift console` what should this link point to? Would replacing this with OSO-Proxy redirect user to the actual OSO cluster?

**Comment by alexeykazakov** [comment]
Proxy won't help here. Proxy is for API calls only. And here is just a link.
I'm not sure if we have anything in our tenant service which can provide a proper URL for the namespace...
@aslakknutsen ?
If not then UI could construct that URL.
For example here is a pipleline URL for my user: https://console.starter-us-east-2.openshift.com/console/project/alkazako/browse/pipelines
You could load the user's OSO cluster API URL from
```
GET https://auth.openshift.io/api/user 
Authorize: Bearer $OSIO_USER_TOKEN
```
the API url is in the payload:
```
{
  "data": {
    "attributes": {
      "cluster": "https://api.starter-us-east-2.openshift.com",
...
}
```
So you should convert "https://api.starter-us-east-2.openshift.com" to "https://console.starter-us-east-2.openshift.com/console/project/$USER_NAME/browse/pipelines"

**Comment by aslakknutsen** [comment]
@alexeykazakov Shouldn't this link to the Jenkins-Idler-Proxy? @vpavlin

**Comment by sbose78** [comment]
When The `getting started` page's loads, it depends on calling `https://sso.prod-preview.openshift.io/auth/realms/fabric8/broker/openshift-v3/token` to determine if the account is linked, this has to be changed to `GET /api/token?for=<user's cluster url`

**Comment by alexeykazakov** [comment]
OSO Proxy URLs:

Preview: https://f8osoproxy-test-dsaas-preview.b6ff.rh-idev.openshiftapps.com
Production: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com

**Comment by joshuawilson** [comment]
@alexeykazakov I'm marking this as done. If we missed something please reopen.

**Comment by qodfathr** [comment]
FWIW, there are 3 items in the list in the description, but only 1 is marked as done. Please mark the others if they are, in fact, done. Otherwise this issue shows up as both "Closed" and "1 of 3 complete."
