### ISSUE TITLE
Jenkins multi-cluster support

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#1686]
As part of our multi-cluster support we should start using OSO-Proxy for all communications with OSO instead of calling OSO API directly from Jenkins.

Jenkins uses service account tokens (generated by forge/app-wizard?) to call OSO API. So, it's a different flow comparing to other OSO clients in OSIO like UI or Che. 

Part of #948

**Comment by adisakala** [comment]
@pradeepto can you please get this item prioritized into build team backlog working with Chmouel?

**Comment by aslakknutsen** [comment]
The purpose of the proxy is to locate the correct OS cluster from OSiO. Jenkins is running in OS and is already where it needs to be, so no need to route the traffic from OS via OSiO back to the same OS. (The Service Accounts are setup by Tenant Service and are normal OS accounts). 

But Forge needs to call the Proxy when it does the 'QuickStart' init parts against OSO.

**Comment by krishnapaparaju** [comment]
@aslakknutsen How does URLs look like for multi cluster proxy ? Can you please point me to these URLs (prod-preview, production) for Forge to call into these new URLs ?

**Comment by aslakknutsen** [comment]
@krishnapaparaju https://openshift.io/_p/oso/ with osio token. The new proxy isn't deployed yet, but the current proxy in place there support the oso token.

**Comment by alexeykazakov** [comment]
We should also make sure there is no any hardcoded URLs/routes specific to east-2 starter cluster. And Jenkins will just work without modification if run on different cluster.

**Comment by maxandersen** [comment]
marking as crucial dependency for #948 as without it we can't complete multicluster support.

**Comment by alexeykazakov** [comment]
Jenkins seems to work in muliti-cluster env. Closing.
