### ISSUE TITLE
Account for missing package-licenses in the license failure.

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#1696]
Current implementation of license failures to return a result if one or more packages have  missing licenses, even if rest of the packages are not in conflict. The system needs to account the possibility of calculating the results and not just throw an failure.
As faced in this https://github.com/openshiftio/openshift.io/issues/1646 issue and rightly pointed out by @msrb 
> we can expect real-world stacks to be full of components with unknown licensing information. And the system should be able to gracefully handle such situations (simply saying "can't determine the stack level license, because " would be enough in my opinion)

**Comment by miteshvp** [comment]
fabric8-analytics/fabric8-analytics-license-analysis#48  fixes this
