### ISSUE TITLE
Cannot create new quickstart/app on prod-preview (JSON error)

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1698]
New issue today - steps to recreate:
* Create new space
* Create new app/quickstart - select "create new" - observe this error is raised:

![screenshot from 2017-12-15 08-10-44](https://user-images.githubusercontent.com/642621/34043637-eff99e06-e16f-11e7-9845-e61634666483.png)

**Comment by ldimaggi** [comment]
Nothing is written to Jenkins pod log.

**Comment by gastaldi** [comment]
@ldimaggi I think this is caused by https://github.com/fabric8-ui/fabric8-ui/pull/2309

**Comment by mmclanerh** [comment]
I'm still reproducing the error myself, in prod-preview. 

Here's all the 404s that happen during the UI error when attempting to create a quickstart:

![image](https://user-images.githubusercontent.com/33727536/34052825-444f0570-e181-11e7-9e9b-35067562f514.png)

**Comment by gastaldi** [comment]
It will continue to be broken until `FABRIC8_FORGE_API_URL` is set to `/forge` in the deployment configuration

**Comment by gastaldi** [comment]
The commit was reverted. Can this issue be closed now?

**Comment by hferentschik** [comment]
The issue is still there, right?

**Comment by hferentschik** [comment]
The error also occurs for "Add Codebase" when it tries to access my GitHub repos.

**Comment by gastaldi** [comment]
Yes, the fix is available in https://github.com/fabric8-ui/fabric8-ui/pull/2338

**Comment by gastaldi** [comment]
Prod-preview is now updated with the fix above. @hferentschik @ldimaggi can you confirm that this issue can be closed?

**Comment by ldimaggi** [comment]
Closing - problem is no longer seen. Thx!
