### ISSUE TITLE
[multi-tenant] Unable to load workspaces when navigating to "Codebases" 

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#1699]
workaround - refresh the page
<img width="936" alt="screen shot 2017-12-15 at 17 27 17" src="https://user-images.githubusercontent.com/1461122/34051956-b320f38e-e1c0-11e7-839f-795bab019741.png">

workaround - refresh the page

1- I cleaned my account, because I was not able to restart any of my previous workspaces, was stuck with https://github.com/openshiftio/openshift.io/issues/1615
2- I created a new space
3- Once created, I opened codebase tab. It was showing this error
4- I wait a little bit and hit refresh
5- I was able to click on the button "create workspace"

**Comment by ibuziuk** [comment]
@slemeur was not able to reproduce so far. Basically, it is quite weird to see this problem for multi-tenant che since it is supposed to be always available. Please, report here if you will be able to repro this again. 
For now I would still keep it open and close & verify after  all toggle / migration code will be removed from che-starter / init tenant https://github.com/redhat-developer/rh-che/issues/497

**Comment by ibuziuk** [comment]
@slemeur PR to che-starter is merged and promoted to prod - Closing

**Comment by slemeur** [comment]
Thanks @ibuziuk
