### ISSUE TITLE
[prod-preview] Sometimes unable to remove spaces 

### ISSUE THREAD

**Issue by mmclanerh** [openshiftio/openshift.io#1700]
On prod-preview had a case where resetting, was unable to remove at least one of my spaces:

![image](https://user-images.githubusercontent.com/33727536/34059114-d423750a-e19a-11e7-9d1c-83e7aacedc7c.png)

A second attempt resulted in the same condition.

I then went back to my main dashboard, then went back into profile->reset, and the space was removed.  

May be some remove/reset operations area slower than the expectation for completion?

**Comment by joshuawilson** [comment]
Can you please confirm this on prod.

**Comment by mmclanerh** [comment]
This has decayed.  I've been able to not experience this issue several times, since experiencing it.  Closing.
