### ISSUE TITLE
Display Insights from Fabric8 analytics at Che UI

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1706]
Currently Insights from Fabric8 Analytics platform are shown as part of the 'stack report' shown next to the build pipelines. 

Would be quite useful to Che user if these insights are shown right inside Che UI as the user adding in new packages at IDE.

These insights can include:

a) License insights into the combination of packages and their licenses being used
b) Insights into additional packages that can be added
c) Insights into replacing any current package(s) being used with an alternative package(s) typically used for the kind of application user is  building.

**Comment by invincibleJai** [comment]
@joshuawilson am not sure if `team/che/IDE` label is needed as mostly analytics team will be working on this item, may need help from CHE team.

**Comment by joshuawilson** [comment]
The `team` label is for any team that may have an interest or be involved with the issue. The milestone `Analytics Backlog` is to say that your team is responsible for it. The label would allow the Che team to search for this issue and know they need to help you or be aware you are working in their space.

**Comment by GeorgeActon** [comment]
Closing this item.

**Comment by rhopp** [comment]
@GeorgeActon Does that mean this issue was moved to planner? It would be nice, if you include link to planner, when closing issues, which were not yet resolved.
