### ISSUE TITLE
Deployments Sparkline charts are fully expanded when card is first expanded

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1709]
![charts-issue](https://user-images.githubusercontent.com/5430520/34113953-5d8f8b58-e3df-11e7-9958-c522143698c5.png)

When the deployments card is first expanded, the sparkline chart takes up the entire width of the card, overlapping the text content. After a moment, it resizes to fit. If at all possible, this should be fixed so this resize doesn't happen and the chart is the correct size from the start.

**Comment by c-koehler** [comment]
@chrislessard There's been work done (will be up for PR) which uses `ngIf` to hide the sparkline charts. This may take away a chunk of the problem, or possibly even do most or all of the work.

I did some research into this over the break, and I think I know a way of refreshing the graph with some modifications to patternfly. I'm going to check later today or tomorrow to see if there's any luck there and provide you with some more info.

**Comment by andrewazores** [comment]
Is this still relevant? As far as I can tell, it has been fixed as a side-effect of https://github.com/fabric8-ui/fabric8-ui/pull/2359 . @chrislessard if you can still reproduce this then keep the issue open, othewise, close it.

**Comment by c-koehler** [comment]
@andrewazores It's a lot nicer with the fix, it would depend on if we care about window resizing. When the window is dragged to be wider or smaller, the chart will overflow (or be too compressed). Are we okay with that?

I think I had a fix for it however, there's a function (that's unfortunately `protected` so we can't access it) which can be called to refresh the chart, and one of the arguments IIRC is a 'refresh' boolean. I believe if we pass in the existing data it will not change or have any performance penalty, but the `reload = true` parameter would allow it to resize as needed. May be completely overkill or very slow, I have no idea. It was just part of an investigation I did and stumbled across that method.

My idea was to edit the .map file and the interface file to expose it on the local machine, then call it and see how it performs. I don't know if this is as easy as I made it sound above however.

**Comment by andrewazores** [comment]
@c-koehler what function is that? I'm sure there's a way we can get around it being protected - that's just a compile-time TypeScript thing.

**Comment by jiekang** [comment]
I feel like the element should resize automatically as other html elements do. If you take a bland c3js chart and resize the window, it seems to work fine (ie. visit any page on c3js.org with a chart and resize). We need to figure out why this isn't working in our use case.

Manually redrawing the chart on a resize is the very very last resort.

**Comment by jiekang** [comment]
This discussion should be on a separate issue that describes the problem clearly though. @c-koehler can you please open a separate issue?

**Comment by c-koehler** [comment]
New issue: https://github.com/openshiftio/openshift.io/issues/1859

**Comment by jiekang** [comment]
Closing this one. Thanks.
