### ISSUE TITLE
usability issue, when logged in and visiting the openshift.io main page, where are my projects?

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#171]
https://screencast.com/t/mNVwutZBk

Under "Account Home", but that is not obvious

**Comment by omajid** [comment]
I had the same reaction. I was logged in, didn't see my projects, so I scrolled down to the bottom of https://openshift.io and clicked "Log in" again, which asked for my credentials *again* and then brought me back to https://openshift.io without showing me my projects. I thought "Account Home" was for managing my account, not to actually work on my projects.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1356

**Comment by bmicklea** [comment]
Adding this as a P1 because it's something every user will be exposed to initially.

**Comment by burrsutter** [comment]
During login, it does redirect you a partial account home page where you can see some of your own content (spaces, pipelines).

https://screencast.com/t/9e4Powsu1ciu

**Comment by joshuawilson** [comment]
@catrobson what can we do to Marketing page so that people can find the "home" easier? Different word then "Account Home"?

**Comment by omajid** [comment]
Speaking as a user, can we do something like what GitHub does? By default you get the marketing page. Once you sign in, instead of the marketing page, https://openshift.io shows you the dashboard (aka account home).

**Comment by bmicklea** [comment]
+1 for the GitHub model.

**Comment by joshuawilson** [comment]
I like that idea. In GitHub the only way to get to the marketing page is to logout.

**Comment by catrobson** [comment]
Thanks for the feedback!  We completely agree, and we're in the midst of making this change.  We're going through a design review and expect to update the marketing page soon with this new user flow of seeing the account home page when logged in, and the marketing page only when logged out.  We'll be moving much of the "what is OpenShift.io" content onto a features page so even logged in users can reference it as needed.

**Comment by joshuawilson** [comment]
Great! Can't wait!

**Comment by joshuawilson** [comment]
new marketing page fixes this
