### ISSUE TITLE
Deployment card graph label upper bounds should be dynamic

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#1712]
The graph label upper bounds (CPU "x of 10" and Memory "x of 500") are currently static values assigned to the label component by the card component. These values should be taken from service data and dynamically set on the label component.

**Comment by jiekang** [comment]
If there is an upper bound, this value should be the same as the resource quota for the environment the application is deployed in. E.g. environment 'run' has cpu quota of 10 cores. This is the upper bound for the CPU data in the per deployment card for environment 'run'.

For data like network usage that has no quota, there should be no upper bound.
