### ISSUE TITLE
Don't show resource usage cards for environments with no applications deployed

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1714]
If an environment 'run', 'stage', etc. does not have any applications deployed, the card should not be shown.

If the environment does have application deployments but there are no resources being used (pods are 0), the cards should show with 0 resources being used.

**Comment by jiekang** [comment]
@catrobson Can you verify if this is the right way to go UX wise? Another option is to show some kind of empty state.

**Comment by catrobson** [comment]
@jiekang Confirmed, this is how I would expect this to behave.

**Comment by jiekang** [comment]
Closing as fix has been merged.
