### ISSUE TITLE
Error on initialization due to lockfileVersion

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#1715]
When running `npm install` for the first time on fabric8-ui, an error is received that "this version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated with lockfileVersion@0. I'll try to do my best with it!". This in turn throws an npm error of "Cannot read property '0' of undefined".

This error currently occurs with npm version 5.5.1 (controlled with nvm), node version 8.3.0.

Switching over to node 6.11.5 and npm 3.10.10 does not have this error.

**Comment by joshuawilson** [comment]
Please set Node to v8.3.0 and npm to v5.3.0
Then run `npm run reinstall` and if that works you can run `npm start`

**Comment by mindreeper2420** [comment]
I was only able to successfully run the build after I downgraded to npm 5.5.1. with node 8.3.0, and deleted the package-lock.json file.

**Comment by joshuawilson** [comment]
Please set Node to v8.3.0 and npm to v5.3.0

**Comment by joshuawilson** [comment]
Since this was a question on configuration that has been answered I'm closing it. Please reopen if you still have an issue.
