### ISSUE TITLE
Manage the feature group a user belongs to

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#1717]
`auth` service needs to manage the feature group to which a user belongs. He/she can enroll in the `experimental`, `beta` or `internal` groups (for the latter, a validation against the verified email address will be necessary). This `feature group` should be exposed in the `/api/user` endpoint so it can be consumed by the `toggle service` (see https://github.com/openshiftio/openshift.io/issues/1716)

**Comment by joshuawilson** [comment]
Is this something we want the user to control? Or is it a privilege that we assign?

**Comment by alexeykazakov** [comment]
>> Is this something we want the user to control? Or is it a privilege that we assign?

Both. Some groups should be available for the user to change (experimental, beta) and some should be limited (internal).
