### ISSUE TITLE
OSIO homepage renders poorly on Mac/Chrome

### ISSUE THREAD

**Issue by MikGue** [openshiftio/openshift.io#172]
While displaying on Mac/Firefox is fine, the OSIS home page does not display properly on Mac/Chrome.  See attached pic.
![screen shot 2017-05-19 at 12 04 30 pm](https://cloud.githubusercontent.com/assets/10928738/26258298/0ab48ebe-3c92-11e7-9f00-556142c4a72c.png)

**Comment by mindreeper2420** [comment]
this should be remedied once PR https://github.com/openshiftio/openshift.io/pull/176 is implemented.

**Comment by joshuawilson** [comment]
merged #176
