### ISSUE TITLE
Getting Started Experience - Select a Project's Environment flow

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#1721]
### Epic:
https://github.com/openshiftio/openshift.io/issues/1689

### User Story: 
As a OSIO user I will be able to select Project environment in the quickstart flow so that I can see specific results.

### Description:
Currently, in OSIO we don't have Project Environment flow. With this addition, it helps us to merge the flow from Launcher (i.e the Project Env flow and others) and have options to select mission, technology.

### Acceptance Criteria:
OSIO user should be able to select Project environment.
Depending on the selection of environment, Next stps should be updated for selection.

### Task List:
- [ ] - UI flow development as per UX.
- [ ] - API development
- [ ] - Integration of API and UI in case of customisation.

**Comment by GeorgeActon** [comment]
@arunkumars08 it looks like this story and 1689 are bothnow covered in the current flow?

**Comment by arunkumars08** [comment]
@GeorgeActon Yes, it is covered in the current flow. Closing it.
