### ISSUE TITLE
On production (https://openshift.io), env reset results in Che pod not shown in overview

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1722]
Just spotted this today - December 19 - after an env reset, Jenkins pods are shown in overview tab, Che pod is not:

![screenshot from 2017-12-19 07-37-47](https://user-images.githubusercontent.com/642621/34157449-87e74e6c-e48f-11e7-8497-37c9f922ee01.png)

**Comment by rhopp** [comment]
Today, multitenant che should be rolled out to all users in production. Thus this is expected.

**Comment by ldimaggi** [comment]
Ah - OK - thanks!
