### ISSUE TITLE
Blank pipeline page if a repository that already exists is chosen in the UI

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/openshift.io#1723]
![screenshot from 2017-12-19 10-57-46](https://user-images.githubusercontent.com/54133/34158204-9da87520-e4ab-11e7-8ba5-d1ddd8771513.png)

This is a frontend issue. The /validate endpoint in the backend is never called after the repository name changes or before proceeding in the `Define Project` screen with the default values.

![screenshot from 2017-12-19 11-01-07](https://user-images.githubusercontent.com/54133/34158301-ef308cc0-e4ab-11e7-801e-13e2db8af2c4.png)

**Comment by gastaldi** [comment]
The backend does not perform validation on `next` because of performance issues

**Comment by edewit** [comment]
The calls to `/validate` where removed from the front-end because the backend was performing them. To have 2 calls instead of one that performs both. That way the validation can be done async in the background while the user is still filling out the form. And moving to the next screen can be as fast as possible.

**Comment by gastaldi** [comment]
This was a scenario that was not tested during the back-end merge. The launcher-team has agreed to not do the validation on `next` and only when the frond-end calls `validate` (because that way going to the next page will take the least amount of time and the validation can be done async when the user is still entering the form for specific fields as explained in the comment above)

**Comment by gastaldi** [comment]
This happens in prod-preview only btw

**Comment by gastaldi** [comment]
![screenshot_20171220-181758](https://user-images.githubusercontent.com/54133/34227038-de4e1f14-e5b2-11e7-9f22-bf6cbaae5880.png)

I can confirm this is fixed. +1 to close this issue
