### ISSUE TITLE
Cannot create a new app/quickstart on https://openshift.io - 412 error code returned

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1729]
Just stated seeing this - when creating a new quickstart - this error is occurring - seems to be reproducible:

![screenshot from 2017-12-21 00-03-05](https://user-images.githubusercontent.com/642621/34241290-7b81ed2c-e5e2-11e7-80c2-8d16a4332fab.png)

**Comment by ldimaggi** [comment]
Nothing is written to the Jenkins pod log when the error occurs.

**Comment by joshuawilson** [comment]
Does the repo `testDec21` already exist, as that is the error listed?

**Comment by ldimaggi** [comment]
Closing - not reproducible. I had seen this multiple times late on December 20 - with repo's that did not previsouly exist. Not sure what happened. Thx!
