### ISSUE TITLE
2 OSIO accounts, reusing github account, stuck

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#173]
The screen at https://openshift.io/_gettingstarted?wait=true will simply get stuck if the github account had previously been used with openshift.io.

You will see the experience about half way through this video
http://www.screencast.com/t/2N83qKcaZnR

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1357

**Comment by joshuawilson** [comment]
This is being worked on at almighty/almighty-core#1291

**Comment by bmicklea** [comment]
Marking as P2 for workshop only because most users won't have a GH account previously associated with IO.

**Comment by burrsutter** [comment]
Once we have the "unbork" command to put a user into a pristine, pre-openshift.io state, then we can test to see if it works on this particular user account :-)

**Comment by joshuawilson** [comment]
This is now being worked on at https://github.com/fabric8-services/fabric8-auth/issues/36

**Comment by alexeykazakov** [comment]
Duplicates https://github.com/openshiftio/openshift.io/issues/371
