### ISSUE TITLE
FABRIC8_REALM value doesn't actually affect realm value in Fabric8-ui 

### ISSUE THREAD

**Issue by jarifibrahim** [openshiftio/openshift.io#1734]
Steps to reproduce
1. Run `docker run -p 8080:8080  -e PROXY_PASS_URL="https://api.free-int.openshift.com" -e FABRIC8_REALM="someRandomText" fabric8/fabric8-ui:v1fa6be7`
2. Login to fabric8-ui
3. Open network tab and check the URL for the `token` request. It should be `https://sso.prod-preview.openshift.io/auth/realms/someRandomText/broker/openshift-v3/token` but instead it is `https://sso.prod-preview.openshift.io/auth/realms/fabric8/broker/openshift-v3/token`

**Comment by jarifibrahim** [comment]
Can someone please assign this issue to me?

**Comment by abs51295** [comment]
Done @jarifibrahim :)

**Comment by jarifibrahim** [comment]
Thanks @abs51295

**Comment by joshuawilson** [comment]
@alexeykazakov @sbose78 @xcoulon do any of you remember where and why we use this?

**Comment by alexeykazakov** [comment]
Keycloak realm is used to construct the URL for OSO token endpoint: https://sso.openshift.io/auth/realms/fabric8/...
We use different realm names in dev env (fabric8-test) and preview/prod (fabirc8). We won't need any realm name in UI as soon as we switch to Auth for OSO account linking.

**Comment by jarifibrahim** [comment]
Closing this one.
Please see https://github.com/fabric8-ui/fabric8-ui/pull/2350#issuecomment-381298831
