### ISSUE TITLE
"Saving Work Item" spinnings forever

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#174]
https://screencast.com/t/oV50taQ9

Though the workitem appears to be created and landed
https://openshift.io/burrsutter/myspace/plan/detail/817

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#1915

**Comment by joshuawilson** [comment]
fixed https://github.com/fabric8io/fabric8-planner/pull/1939
