### ISSUE TITLE
unable to build fabric-ui due to docker access blocked

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#1741]
There are several PRs that can not build on fabric8-ui with the following error.

```
docker push fabric8/fabric8-ui:SNAPSHOT-PR-2350-1
The push refers to a repository [docker.io/fabric8/fabric8-ui]
...
denied: requested access to the resource is denied
```
ex https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-ui/view/change-requests/job/PR-2350/1/console

**Comment by chmouel** [comment]
I had rawlingjs removed from the user rights on docker hub, i have just added back and it should be fixed now. We are going to work to move away from james username, https://github.com/orgs/fabric8io/projects/2#card-6423971

**Comment by chmouel** [comment]
as per https://hub.docker.com/r/fabric8/fabric8-ui/tags/ It has now uploaded properly, closing this

**Comment by joshuawilson** [comment]
thanks
