### ISSUE TITLE
Provide unit tests for the sources from repository fabric8-analytics-recommender

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1745]
There are no unit tests created and CI job configured for the fabric8-analytics-recommender repository:
https://fabric8-analytics.github.io/dashboard/dashboard.html

Acceptance criteria:

- [ ] a few unit tests prepared
- [ ] CI job configured
- [ ] QA dashboard updated

**Comment by miteshvp** [comment]
@tisnik - can you please add corresponding labels of type for this issue.

**Comment by tisnik** [comment]
This repository has been deprecated, so this issue is no longer valid.
