### ISSUE TITLE
API: Need expanded delete space functionality

### ISSUE THREAD

**Issue by dgutride** [openshiftio/openshift.io#1746]
Goal would be to have a DELETE /api/spaces/{id} to support UI in this story: 

https://github.com/fabric8-ui/fabric8-ux/issues/610

Delete should not just delete the space from the platform database, all labeled space entries on openshift should also be removed so we don't orphan entries.

Internally call:

* Deployment API for OSO App Removal
* Che for Workspace Delete

Long term:

* Build confirmation into the API
  * Delete Space
    * Are you sure you want to Delete X, Y, Z child resources 'link'
      * Delete 'link'

**Comment by aslakknutsen** [comment]
Openshift resources are easy enough assuming all the labeling matches(I think the route is missing it atm), but just that would leave GitHub repos with orphan webhooks as well as Che workspaces referring the codebases.

**Comment by jiekang** [comment]
Also, the Deployments API supports deletion. It could be used as a reference, or directly to assist with this.

**Comment by ebaron** [comment]
Following up on the API Jie pointed out, currently this deletes the following for a deployment (an application within one environment):
- Deployment Config
- Replication Controllers
- Pods
- Services
- Routes

We could expand on this to support deleting a whole application across environments, or all applications within a space.

**Comment by joshuawilson** [comment]
Sounds like this might move us along faster, thanks.

**Comment by aslakknutsen** [comment]
From the UI point of view Delete space should be enough. The rest should be orchestrated internally

**Comment by joshuawilson** [comment]
I agree. However, the current design has delete/remove on several components including Deployments. I want to confirm that you are NOT commenting on that functionality.

**Comment by aslakknutsen** [comment]
@joshuawilson Not sure I understand your comment. Multiple objects or not, the UI shouldn't care. The action the UI care about is Delete space.

**Comment by joshuawilson** [comment]
I was referencing "The rest should be orchestrated internally" comment. Just to make sure you didn't want the functionality removed from the UI components that delete parts. I didn't think you did, just confirming.

**Comment by aslakknutsen** [comment]
@joshuawilson 

Should the UI be able to Delete a single Deployment? yes
Should the UI be able to Delete a Single space? yes
Should the UI have to call Delete on every Deployment within a Space before/when calling Delete Space? No!
Should the UI have to find all the related child objects when deleting a parent? No!

**Comment by joshuawilson** [comment]
Agreed. :)
