### ISSUE TITLE
UI: Show deployments tab

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1751]
The Deployments page is an experimental feature and the tab is hidden (though the page is visible). The tab should be shown.

**Comment by jiekang** [comment]
This should wait till the live data work has been merged.

**Comment by joshuawilson** [comment]
As long as the Env and App tabs are kept we can turn this on with mock data.

**Comment by jiekang** [comment]
Okay, I'll look into it then.

**Comment by jiekang** [comment]
Closing as change has been merged.
