### ISSUE TITLE
UI: Remove applications and environments pages

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1752]
The applications and environments pages should be removed once the deployments page is complete.

**Comment by joshuawilson** [comment]
cc @dgutride

**Comment by jiekang** [comment]
Note there are at least two steps:

1. Removing the applications and environment page from being accessible and loadable in the web application.

2. Removing the `a-runtime-console` codebase that contains the code for these pages.

Step 2 is a much larger task and should be it's own issue.

**Comment by jiekang** [comment]
A tracking issue for removing `a-runtime-console` code has been created: https://github.com/openshiftio/openshift.io/issues/2025

That issue will try to organize what needs to be done for the goal to be completed.

**Comment by jiekang** [comment]
https://github.com/fabric8-ui/fabric8-ui/pull/2493

removes the apps and environments pages.

Closing as above has been merged.
