### ISSUE TITLE
Stack Report not depicted as seen in the Getting Started Guide

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#1753]
On a recent walk-through of the Getting Started Guide, Stack Report did not appear as described in the  Guide.  Maybe an update to the depiction is needed?

**Comment by qodfathr** [comment]
Setting to SEV4 because it's probably that the Getting Started guide will be deprecated before we have a chance to fix it.

**Comment by mishaone** [comment]
This should be fixed (See linked fabric8 bug).

**Comment by mishaone** [comment]
Sorry, just noticed it's assigned to Todd. Reopening in case he wants to do anything more with this.
