### ISSUE TITLE
Getting Started Guide doesn't fully describe "Create WorkItem" features.

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#1755]
"Create Workitem" offered more features than the Getting Started Guide described.

**Comment by qodfathr** [comment]
Setting to SEV4 because it's probably that the Getting Started guide will be deprecated before we have a chance to fix it.

**Comment by nimishamukherjee** [comment]
@Preeticp can we close this?

**Comment by joshuawilson** [comment]
We have a new doc at https://openshift.io/documentation.html that is maintained by @rkratky and his team.   
Please work with them to get it updated.

**Comment by rkratky** [comment]
@RickJWagner The 'Getting Started Guide' is intended to describe only specific paths through the product to allow users to start experimenting with it quickly.

We also have a 'User Guide', which aims to describe the product's feature in a more comprehensive manner. Work items are documented at https://docs.openshift.io/user-guide.html#working_with_work_items -- could you please have a look and potentially sugest improvements for that doc?

**Comment by Preeticp** [comment]
@rkratky, @RickJWagner this section in the user guide is currently being reworked as per the latest changes in Planner UX.

**Comment by RickJWagner** [comment]
Hi @rkratky and @Preeticp,
Thanks for having a look at this.  I've taken a look at the User Guide also, I think we have an opportunity to help our users.
The User Guide clearly explains the mechanics of pushing the right button to make a work item, but what is missing is some context around how the user might want to structure their items.  There are many choices:  Scenario, Fundamental, Papercut, Experience, Value Proposition.  Users may want some guidelines about the 'right' way to organize their work issues.  (What makes something a 'Scenario' versus a 'Value Proposition', for example?)  Some explanation of how to use these categorizations would be useful.  Thanks.

**Comment by rkratky** [comment]
Thanks for the input @RickJWagner. @Preeticp has a WIP section on SDD (scenario-driven development) that should provide the context you're looking for.

**Comment by Preeticp** [comment]
@RickJWagner the work items section in the docs has been updated to provide more context on the work flow for both SDD and Scrum methodologies: https://docs.openshift.io/user-guide.html#using_guided_hierarchy_to_create_work_item
Also terms like Scenarios, Value Proposition have been explained both as infotips in the UX as well as in the User guide glossary: https://docs.openshift.io/user-guide.html#glossary
Please take a look and let us know your thoughts.

**Comment by RickJWagner** [comment]
Hi @Preeticp,
Thank you for your efforts.  I find the Glossary especially good, these entries will help the users decide the best way to use Planner.  We can close this issue, my concerns are addressed.
Thank you,
Rick
