### ISSUE TITLE
Getting Started Guide doesn't tell how to open the terminal in Che.

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#1756]
The user may not know how the terminal should be opened, please provide detail at this point in the Getting Started Guide.

**Comment by eivantsov** [comment]
Isnt terminal tab opened by default and active when a ws is up?

**Comment by RickJWagner** [comment]
Additional notes:
The PDF version of the GSG (https://openshift.io/osiogettingstarted.pdf) has this flaw.  Under section "Explore the Terminal" it instructs the user "Open the Terminal...."  without prior explanation of how to do this.

The Prod-Preview version of the GSG has a nice section, "Using the terminal tab"
https://docs.prod-preview.openshift.io/e2e_workshop.html#using_terminal_tab

**Comment by ibuziuk** [comment]
According to @rkratky comment https://github.com/openshiftio/openshift.io/issues/1559#issuecomment-351107476 we are currently in transitional period to Asciidoc-based guides

**Comment by qodfathr** [comment]
Setting to SEV4 because it's probably that the Getting Started guide will be deprecated before we have a chance to fix it.

**Comment by Preeticp** [comment]
This was an issue for the PDF version of docs earlier which was deprecated. 
The current Getting Started guide maintained by the docs team covers this information in the section on using the Che workspace: https://docs.openshift.io/getting-started-guide.html#running_your_project-hello-world.
We can close this issue.

**Comment by Preeticp** [comment]
@RickJWagner I am closing this issue as it affects the deprecated PDF version of getting started doc. The current version:https://docs.openshift.io/getting-started-guide.html has this documented clearly as you mentioned in your earlier comment.
