### ISSUE TITLE
Getting Started Guide has 'Asdasdasd' template text in 'Troubleshooting' section.

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#1758]
Getting Started Guide has 'Asdasdasd' template text in 'Troubleshooting' section.

**Comment by qodfathr** [comment]
Setting to SEV4 because it's probably that the Getting Started guide will be deprecated before we have a chance to fix it.

**Comment by rkratky** [comment]
The old PDF is now deprecated, and the new doc (https://docs.openshift.io/getting-started-guide.html, https://docs.openshift.io/getting-started-guide.pdf) doesn't have this problem. Closing.
