### ISSUE TITLE
Improve license recommendation for end user

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#1766]
## Motivation
The OSIO user should be able to get a conflict free license for it's selected stack or for a github repository.

## Description
As of now while computing final representative license our license analysis platform produce result without considering the effect of transitive dependencies on license compatibility. Which sometimes result in a license which are in conflict with others. So the task here is to improve the license recommendation by considering the transitive dependency while determining representative license. Also this phase includes logic implementation for determining a representative license for a github repository from it's url entered as an input by user.

## User Stories
#1695
#1761 
#1762

**Comment by miteshvp** [comment]
Not relevant. Closing.
