### ISSUE TITLE
"reason" field comes null in stack analysis response

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#1769]
Stack Id: 6422008e69b9474195ef395918a2c892
Response in Gist: https://gist.github.com/invincibleJai/1e01d422a599697ee82979596cf6da12#file-response-json-L101

**Comment by arunkumars08** [comment]
@sara-02 It seems to work fine for this stack id - ba6fc53625fb47c1901e04fce58d0a05. Something could have been the problem with the previous stack

**Comment by krishnapaparaju** [comment]
@sara-02 please give out one more try for reproducing as its currently not able to reproduce..

**Comment by arunkumars08** [comment]
Closing this issue as it is no more reproducible.
