### ISSUE TITLE
Tests java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#177]
Using the Vert.x Basic booster/quickstart, generated by the main wizard (pick your tech stack/pipeline).   The webhook does pick up changes to the repo and kicks off a pipeline.  I have used both the github UI to make a change as well as Che, however, tests always fail with a timeout.

Here is the project:
https://github.com/burrsutter/myvertxbasic10

and the Jenkins logging

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.openshift.booster.HttpApplicationTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
May 21, 2017 5:10:46 PM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 8b:b9:3a:56:6d:3e:54:c5
Server starter on port 8080
Server starter on port 8080
sh-4.2$ exit
exit
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 122.53 sec <<< FAILURE! - in io.openshift.booster.HttpApplicationTest
callGreetingWithParamTest(io.openshift.booster.HttpApplicationTest)  Time elapsed: 120.014 sec  <<< ERROR!
java.util.concurrent.TimeoutException

Results :

Tests in error: 
  HttpApplicationTest.callGreetingWithParamTest ? Timeout

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1358

**Comment by jstrachan** [comment]
is an issue with the underlying quickstart from RHOAR?
https://github.com/openshiftio-vertx-boosters

**Comment by burrsutter** [comment]
https://github.com/openshiftio-vertx-boosters/vertx-http-booster
after a git clone and "mvn test" it fails for me locally

**Comment by burrsutter** [comment]
i believe Clement fixed this already
