### ISSUE TITLE
Promote dialog in UI fails due to CORS error

### ISSUE THREAD

**Issue by vpavlin** [openshiftio/openshift.io#1771]
I get 

`Failed to load https://forge.api.prod-preview.openshift.io/services/jenkins/vpavlin-jenkins/job/vpavlin/job/vpavlin-pp-test/job/master/3/input/Proceed/proceedEmpty: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://prod-preview.openshift.io' is therefore not allowed access.
`

when I try to promote a build from OSIO UI

![screenshot from 2018-01-03 15-00-21](https://user-images.githubusercontent.com/4759808/34523585-6bc62fc2-f098-11e7-8564-6855a2925bda.png)

@gastaldi

**Comment by gastaldi** [comment]
@edewit looks like we slipped that one. The new URL should be `https://forge.api.prod-preview.openshift.io/api/openshift/services/jenkins/...`

**Comment by joshuawilson** [comment]
Since this was only seen in prod-preview and has now been fixed there, I'm closing it. Please reopen if needed.
