### ISSUE TITLE
In OSIO Planner filters, labels are always an AND, not an OR

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1774]
Situation - A user has created a number of workitems, divides the workitems into 2 groups, and designates a label for each group.

A filter that specifies both group labels will return zero workitems as the filter looks for workitems that have BOTH group labels set.

![screenshot from 2018-01-03 17-04-09](https://user-images.githubusercontent.com/642621/34542316-0b039758-f0aa-11e7-8587-800b9432d063.png)

![screenshot from 2018-01-03 17-04-29](https://user-images.githubusercontent.com/642621/34542315-0af32968-f0aa-11e7-9057-acb448743671.png)

![screenshot from 2018-01-03 17-03-45](https://user-images.githubusercontent.com/642621/34542317-0b158166-f0aa-11e7-936d-ff09538b625d.png)

**Comment by joshuawilson** [comment]
Labels in github work the same way.

**Comment by qodfathr** [comment]
Closing as Working as Designed. Once we've got the fully query system & UI in place, you should be able to do more complex Boolean queries.
