### ISSUE TITLE
Ability to select Private or Public for the Email address on user profile page

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#1775]
Auth back-end is now supports public and private emails. It's just a new field in user's profile payload. See https://github.com/fabric8-services/fabric8-auth/pull/237 for details.
Now we need to add this public/private switcher to the user profile page, so, users can make their emails private/public.

Wireframe - https://redhat.invisionapp.com/share/F4F0D8FZA

**Comment by alexeykazakov** [comment]
@joshuawilson @catrobson @dgutride I hope someone from Platform/UX teams can help us with this UI feature :)

**Comment by joshuawilson** [comment]
Is this critical? If not then we can work it into a sprint.

**Comment by alexeykazakov** [comment]
Well, it's critical but not super urgent :) If it can be done in this sprint then great. Especially because I don't think it will take much time to implement. But if it's tricky then it's OK to fix it in the next sprint. Kinda SV2.

**Comment by joshuawilson** [comment]
I'm confused, who needs this feature? What does it do that makes is so important?

**Comment by catrobson** [comment]
@joshuawilson there was a privacy and security concern about going GA with e-mails available publicly to the world without user choice to make their e-mail private.  So this is critical for GA, but I think we can schedule this into a sprint.

**Comment by catrobson** [comment]
UXD issue for the HTML/CSS implementation of this:  https://github.com/fabric8-ui/fabric8-ux/issues/841

**Comment by mindreeper2420** [comment]
PR for HTML/CSS filed: https://github.com/fabric8-ui/fabric8-ui/pull/2461

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2062
