### ISSUE TITLE
Webhooks sending everything vs. sending push only

### ISSUE THREAD

**Issue by vpavlin** [openshiftio/openshift.io#1776]
Currently when a webhook is generated in repository from Forge, it sends all events to the webhook URL

![screenshot from 2018-01-04 15-30-25](https://user-images.githubusercontent.com/4759808/34567868-38ce4f92-f164-11e7-86d6-37e35cdb7c41.png)

This is might be problematic for idler as that means proxy will get hit unnecessarily and  thus Jenkins might not be idled for user as early as it could be (or ever)

![screenshot from 2018-01-04 15-31-36](https://user-images.githubusercontent.com/4759808/34567915-6a0e0cdc-f164-11e7-9dcd-bd2e1274a139.png)

We should consider only sending push.

If there is a reason for sending all, this needs to be considered and taken care of in Jenkins Proxy somehow.

@gastaldi what do you think?

**Comment by gastaldi** [comment]
I'm fine with that. But how about building pull-requests? Is that needed in those repositories too?

**Comment by vpavlin** [comment]
I am not sure.. @maxandersen?

We could probably hand pick some events and specify those - I am mostly concerned about status events and issue events, which are basically useless for Jenkins

**Comment by gastaldi** [comment]
Just changed in prod-preview to use just PUSH event. @vpavlin can you give it a try if there is any collateral effects with this?

**Comment by gastaldi** [comment]
This is the same behavior that we use for apps deployed through developers.redhat.com/launch

**Comment by maxandersen** [comment]
reopen for clarification - doesn't push cover pull-request ? we would want builds on pull-requests for sure.

@gastaldi feel free to close if build on PRs still works.

**Comment by gastaldi** [comment]
@maxandersen PUSH does not cover when pull-requests are opened. I updated the backend to create the webhook for the `PUSH`, `PULL_REQUEST` and `ISSUE_COMMENT` events.
