### ISSUE TITLE
Long term planning for scaling Fabric8 Analytics platform

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1777]
Document the long term scaling plan covering number of concurrent users (coming either from openshift.io / IDE extensions)

**Comment by qodfathr** [comment]
Related: #2028

**Comment by GeorgeActon** [comment]
@krishnapaparaju @miteshvp I think we did this work and this story is just widowed. If so can you close it? If not it needs to be in the backlog in planner

**Comment by miteshvp** [comment]
Marking this item as closed. Relevant numbers are published here - https://docs.google.com/spreadsheets/d/1xfc_gxPdp-sNkw3gNqe4KLC2wN_IQC1B11NFxIiWc2w/edit?usp=sharing
