### ISSUE TITLE
Typos and incomplete content on the landing page for openshift.io

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#178]
_From @Preeticp on May 18, 2017 13:55_

There seem to be a few typos and incomplete sentences in the content on the OSIO landing/login page. I realize this was done in a hurry, here are a few things I noticed and some suggestions:

1. In the "Makes it simple to create containerized dev, test and staging environments." box:
The sentence: "Pipeline definitions are written using a Groovy DSL providing huge flexibility in how you assemble the pieces into of pipelines." either the word 'of' is not required or some content seems to be missing between 'into...of'.

2. In the "Allow development teams be more confident in the technology decisions they make." box:
- Suggest adding 'to' before the words 'be more confident' > Allow development teams to be more confident in the technology decisions they make.

- In the sentence "OpenShift.io Analytics applies machine learning algorithms based on their usage pattern of components." suggest replacing 'their' with 'the'. 

- Missing content at the end of this sentence "Through this comprehensive dataset, developers get tangible information for credible....".  Also, dataset>data set.

3. In the "Minimize the time and effort it takes to build and maintain an end-to-end development tool chain." box:
We need to add a comma after 'coding' in the sentence "It has coding editing and debugging tools built on Eclipse Che that provide developers with a full featured IDE." 

_Copied from original issue: fabric8io/fabric8-ui#1328_

**Comment by mindreeper2420** [comment]
fixed with PR: https://github.com/openshiftio/openshift.io/pull/180
