### ISSUE TITLE
Cannot create new quickstart on prod-preview - "Error calling service"

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1780]
This started happening in the past hour - nothing is written to the Jenkins log:

![screenshot from 2018-01-04 20-53-57](https://user-images.githubusercontent.com/642621/34592393-965735a2-f191-11e7-9c84-9ba236ce236e.png)

This blocks testing on prod-preview.

**Comment by gastaldi** [comment]
There is something wrong in the launcher-backend pod, because it fails the readiness check. I can't see the logs either: https://console.rh-idev.openshift.com/console/project/launchpad-preview/overview

**Comment by gastaldi** [comment]
Nevermind, it is back up, can you try again?

**Comment by ldimaggi** [comment]
Thx! It's working now.

**Comment by ldimaggi** [comment]
It's fixed - thx!

**Comment by ldimaggi** [comment]
Issue found/encountered by EE tests.
