### ISSUE TITLE
New registered users can't login

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#1781]
Currently our registration process is broken. New approved users can't login to OSIO. The issue was introduced today. Existing users are OK.

**Comment by alexeykazakov** [comment]
We fixed the OSIO side of things - https://github.com/fabric8-services/fabric8-auth/pull/243
Now waiting for the OSO reg app team to adopt this fix on the registration app side.

**Comment by sbose78** [comment]
The issue happened because we were passing an incorrect RHD user id to keycloak.

To fix that:
We added support for `rhd_user_id` in the payload of the `Create User API` in Auth.

This is how the new payload looks like : 
```
curl -X POST   https://auth.openshift.io/api/users   -H 'authorization: Bearer $SERVICE_ACCOUNT_TOKEN'   -H 'content-type: application/json'   -d '{
  "data": {
    "attributes": {
      "email": "sev1test2-01234@a.com",
      "rhd_username": "rhdusername",
      "username": "sev1test2-name",
      "cluster": "https://cluster-url.com",
      "rhd_user_id":"0721866f-6804-45e5-97fb-9904a2fee395"
    },
    "type": "identities"
  }
}'
```

https://github.com/openshift/online-registration/issues/762#issuecomment-355485057

**Comment by sbose78** [comment]
Corresponding change in registration app: https://github.com/openshift/online-registration/pull/882

Tim ( OSO team ) and I have tested out by creating a new test user, got myself provisioned and then logged into Openshift.io successfully.

Marking this as resolved.
