### ISSUE TITLE
[3] RFE: tests for the /schemas* REST API endpoints

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1786]
Currently, only a very small subset of /schemas* REST API endpoints is covered by integration tests. It needs to be fixed to test at least following endpoints:

- [x] ```'/schemas'```
- [x] ```'/schemas/<collection>'```
- [x] ```'/schemas/<collection>/<name>'```
- [x] ```'/schemas/<collection>/<name>/<version>'```

**Comment by miteshvp** [comment]
@tisnik - can you please add corresponding labels of `type` for this issue.

**Comment by qodfathr** [comment]
Related: #2082

**Comment by tisnik** [comment]
Implemented in https://github.com/fabric8-analytics/fabric8-analytics-common/pull/478
