### ISSUE TITLE
Show network resource usage in per deployment sparkline charts 

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1787]
The mock [1] has network resource usage sparkline charts (input/output KiB/s, and no. of requests).

As of this issue, the deployment cards only have the CPU and Memory sparkline charts. The network charts should be added.

[1] https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/260764295

**Comment by jiekang** [comment]
The Network usage chart should mimic the one found in the Openshift Web Console.

I am not convinced the Network Requests chart is useful...

**Comment by andrewazores** [comment]
#2402 is not technically feasible at this time and #2388 has been merged. Closing.
