### ISSUE TITLE
Intermittent/recurring issue - Access to Jenkins logs through OpenShift is broken on prod-preview and production

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1790]
Steps to recreate:
* Create a new quickstart - observe its build pipeline starting
* Attempt to access the build's Jenkins log ("View Log")
* Observe logging in to Jenkins thru OpenShift does not occur - user is directed to this screen instead:

![screenshot from 2018-01-05 21-15-56](https://user-images.githubusercontent.com/642621/34635494-67cbc180-f25e-11e7-8385-11d1f2269372.png)

**Comment by ldimaggi** [comment]
When this issue was first logged, it was being seen on prod-preview - and it seemed to be intermittent.

Today, however, I am seeing it constantly.

**Comment by joshuawilson** [comment]
I just tried it and it asked me to login but then took me to the log.
I closed it and tried again. The second time it took me directly to the logs.

**Comment by ldimaggi** [comment]
Seeing this today:

![screenshot from 2018-01-11 13-02-44](https://user-images.githubusercontent.com/642621/34840168-22984b24-f6d2-11e7-864a-b302c810ad10.png)

**Comment by ldimaggi** [comment]
This problem is recurring. I have encountered this problem multiple times this week, but its timing seems to be random.

The problem is probably not a hardship for end-users, but it affects automated testing as it prevents the tests from automatically extracting the build logs. The absence of these logs makes it difficult to debug failed tests.

**Comment by joshuawilson** [comment]
have you been seeing it on the new cluster 2a? or the old one?

**Comment by ldimaggi** [comment]
So far, only on the old cluster. Will look on the new cluster now too.

**Comment by ldimaggi** [comment]
So far - I have only seen this on the old cluster.

**Comment by jfchevrette** [comment]
Does this occur in Incognito mode too? I have a feeling this may be caused by a prior openshift session/cookie/token under a different username which may not match the one that is logged on to OSIO.

**Comment by ldimaggi** [comment]
Raising to SEV2 as this is having an adverse effect on automated tests.

**Comment by aslakknutsen** [comment]
You can normally get to the 'other login' by clicking the top right 'login' button.

**Comment by stevengutz** [comment]
@pradeepto this one has been lingering since Jan 5th.  Not that there isn't already enough on your plate, but after we get some of the immediate SD issues under control can we get a body on this one?

**Comment by ldimaggi** [comment]
It's annoying for a human user to use the 'other login' path to be able to (mostly) login and then find the jenkins build log. It's much more difficult to code this path into an automated test.  Thx!

**Comment by hferentschik** [comment]
This might be a proxy issue. Also, as @jfchevrette is suggesting, are you using the same browser with multiple accounts? Have you tried with a private browser window. 

That said, I'd prefer this issue to be moved here - https://github.com/fabric8-services/fabric8-jenkins-proxy/issues

@ldimaggi, could you create an issue in the Proxy issue tracker. Also, could you add some more context? Where do you start, what do you do, which links are you following, etc
Have you tried with a private windows, etc ...

**Comment by ldimaggi** [comment]
Related to:  #2752

**Comment by rupalibehera** [comment]
@ldimaggi , are you able to reproduce this issue now also, I am not able to reproduce it now.

**Comment by ldimaggi** [comment]
This specific issue is not being seen - #2752 is a current issue. Closing.
