### ISSUE TITLE
Create Iteration with Force Active not saved

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1791]
## Reproduce

* Create new iteration
    * Set 'Force Active' to On in the Create screen
* Save

## Expected

* Newly created iteration with active state ON

## Actual

* Newly created iteration with active state OFF

**Comment by baijum** [comment]
@nimishamukherjee The fix has been merged to master.

**Comment by rgarg1** [comment]
@nimishamukherjee @aslakknutsen Issue cannot be reproduced in Prod-preview.
