### ISSUE TITLE
Notification toast checkmark overflows over text

### ISSUE THREAD

**Issue by c-koehler** [openshiftio/openshift.io#1798]
After updating to master for https://github.com/openshiftio/openshift.io/issues/1566 I found that the following image occurs when emitting a notification (did not happen before rebasing to master):

![profile-updated](https://user-images.githubusercontent.com/33262856/34697120-ad29310c-f49f-11e7-8157-c9c0e86a231f.png)

It should not overflow, maybe look like the following

![should-look-like](https://user-images.githubusercontent.com/33262856/33773497-1075921c-dc06-11e7-86d1-d618e4e82751.png)

**Comment by mishaone** [comment]
This also happens when a new quickstart project is created:

![issue](https://user-images.githubusercontent.com/926572/35028198-7430ea54-fba0-11e7-91e4-8fb017864a9b.png)
