### ISSUE TITLE
Documentation link on profile page show 404

### ISSUE THREAD

**Issue by liangxia** [openshiftio/openshift.io#1801]
Log into OpenShift.io, go to profile page to setup your profile. There is a link "in the documentation" beside button "Create a Space". Click the link, show 404.

**Comment by liangxia** [comment]
![screenshot from 2018-01-10 11-22-48](https://user-images.githubusercontent.com/4716987/34754447-c083fa7a-f5f8-11e7-8f93-987410b5b9eb.png)

**Comment by aditya-konarde** [comment]
@liangxia Thanks for reporting. Looks like this is a duplicate and is already reported at: https://github.com/openshiftio/openshift.io/issues/1588

**Comment by liangxia** [comment]
Closing this one as it is a duplicate of #1588

**Comment by joshuawilson** [comment]
Closing as a duplicate.
