### ISSUE TITLE
URL and bio in profile need a manual refresh after click update button to fresh.

### ISSUE THREAD

**Issue by liangxia** [openshiftio/openshift.io#1804]
Update to URL and bio in profile for the first time succeed. 
Since the second time, it show updated successfully, but actually the content does not change after you click the update button. You need a manual refresh to get it updated.

**Comment by liangxia** [comment]
Update title and comments to reflect the real problem.

**Comment by aptmac** [comment]
Fixed in https://github.com/fabric8-ui/fabric8-ui/pull/2552
