### ISSUE TITLE
Build takes a long time to start  (noticed during 'Test Day', with 20 users)

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#1806]
During 'Test Day', the first effort to make a build resulted in a long wait.  (8 minutes total build time, from start till 'Rollout to run'.)
The initial wait for build to start was long, it seemed like 4 or 5 minutes.

**Comment by ldimaggi** [comment]
Dupicate of:  https://github.com/openshiftio/openshift.io/issues/1731
