### ISSUE TITLE
Application Wizard thinks that "a" is an invalid group id

### ISSUE THREAD

**Issue by Ladicek** [openshiftio/openshift.io#1807]
When creating a new project, I tried to set the group id in the wizard to `a`, and I'm getting "Group Id should not contain uppercase or special characters". I'm pretty sure `a` is a valid Maven groupId.

**Comment by ldimaggi** [comment]
Can you provide additional context on this?
* Did this fail with "a" only? Or, is the issue that single char group id's failed? Thx!

**Comment by Ladicek** [comment]
Yea, it's a single-char group id that causes this issue, `aa` is fine.

**Comment by GeorgeActon** [comment]
@krishnapaparaju as per George G request on MM please review. This is a UI issue on existing OSIO wizard.

**Comment by krishnapaparaju** [comment]
@arunkumars08 please pick this up as part of next sprint.

**Comment by arunkumars08** [comment]
@krishnapaparaju Sure, will take care in the coming sprint.
