### ISSUE TITLE
Profile page shows events from other users

### ISSUE THREAD

**Issue by bit4man** [openshiftio/openshift.io#181]
When going to https://openshift.io/<username> I'm seeing content from other users in the activity window. For instance my username is plarsen@redhat.com and I'm seeing this:

ryhanych's recent activity

    @jryhanych added BalloonPopGame space Just now

    @jryhanych added BalloonPopGame space Just now

    @jryhanych added BalloonPopGame space Just now

**Comment by joshuawilson** [comment]
There is a fix for this in staging and should be in production soon.

**Comment by RanjithRV** [comment]
@joshuawilson Since we are no longer experiencing this issue. Can we go ahead and close it? Should we mention when this code was deployed to prod?

**Comment by joshuawilson** [comment]
Closing as fixed

**Comment by joshuawilson** [comment]
If you have the time to find it then you can link it.
