### ISSUE TITLE
Application Wizard - enhance wizard forward navigation by clicking in left wizard panel, not only Next button

### ISSUE THREAD

**Issue by rsvoboda** [openshiftio/openshift.io#1810]
Application Wizard - enhance wizard forward navigation possibilities with clicking in left wizard panel, not only Next button.

This is also inconsistency comparing to backward scenario, when I'm at "1B. Define Project" I can chose 2 ways to get to "1A Select Stack":
 * Click on Back button
 * Click on "1A Select Stack" in left panel

Screenshot for the wizard context:
![screenshot from 2018-01-10 12-35-41](https://user-images.githubusercontent.com/925259/34770963-2697295e-f603-11e7-8838-ab2f90a69b14.png)

**Comment by qodfathr** [comment]
Thouhts, @catrobson ?

**Comment by catrobson** [comment]
This wizard design does not let you choose future steps as you must complete the step you are on, and selecting next is often a validation point for the wizard.  This is as designed.  This wizard design/behavior is being changed with the latest quick start flow so we shouldn't continue to see this usability issue moving forward.

**Comment by qodfathr** [comment]
Closing as Working as Designed.
