### ISSUE TITLE
Error "An authentication error occurred" is faced when trying to connect the "OpenShift.com account"

### ISSUE THREAD

**Issue by camilamacedo86** [openshiftio/openshift.io#1812]
# Problem Description
**WHAT:** Error "An authentication error occurred" is faced when trying to associated the "OpenShift.com account"
**WHERE:** Into the OpenShift.com connect accounts 
**WHEN:** Has a new user/account and after to do the required connection to the GitHub account 
**BEHAVIOUR CHECKED AT:** 10/jan/2018

# Steps to reproduce:
1. Register to have a new account on the OpenShift.io
2. After the registration be allowed to click on the button “OpenShift console"
3. The get started process will be made 
4. Connect a GITHUB account as is requested
5. Try to connect the "OpenShift.com account" as it is mandatory. 

# Result:
<img width="1204" alt="screen shot 2018-01-10 at 11 17 30 am" src="https://user-images.githubusercontent.com/7708031/34771243-c7d04132-f5fb-11e7-96e0-5b7116fbc65b.png">

# Expected Behaviour:
It is expected that the "OpenShift.com account" connects without any exception

**Comment by ldimaggi** [comment]
This was a result of a test environment that was unstable and is not supported for anything beyond temporary internal testing. Closing.
