### ISSUE TITLE
HTML entities not rendered in Planner Item Title

### ISSUE THREAD

**Issue by shannon** [openshiftio/openshift.io#1814]
If you use a character such as `>` in a planner item title it converts it to `&gt;` which could make sense but it should probably still render it correctly in the UI. The description seems to allow the character without issue.

<img width="1680" alt="capture" src="https://user-images.githubusercontent.com/1154610/34771603-16137ed2-f5d3-11e7-8059-59d264708fd4.PNG">

## Impacts
- [ ] #2162 Planner Backlog Management Experience placeholder

**Comment by rgarg1** [comment]
Same as https://openshift.io/openshiftio/openshiftio/plan/detail/1785

**Comment by michaelkleinhenz** [comment]
Yes, and this is like beating badgers. We repeatedly fixed this and it keeps coming back.

**Comment by rgarg1** [comment]
@michaelkleinhenz Since we are already tracking this issue in Planner, do we need to keep this open?

**Comment by michaelkleinhenz** [comment]
@rgarg1 yes, for the time being. The GH issues are the channel to the reporting user as Planner issues can only be followed by team members.

**Comment by debloper** [comment]
Full context on this issue: fabric8-services/fabric8-wit#1465
PR to resolve this issue: fabric8-services/fabric8-wit#1470

The PR is green from CI as well as review+
Quite unsure what's the blocker here from merging it.

**Comment by nimishamukherjee** [comment]
https://github.com/fabric8-ui/fabric8-planner/pull/2518

**Comment by nimishamukherjee** [comment]
Fix available on prod.
