### ISSUE TITLE
The search filter is not working when the content/text is changed

### ISSUE THREAD

**Issue by camilamacedo86** [openshiftio/openshift.io#1815]
# Problem Description
**WHAT:** The search filter is not working when the content/text is changed 
**WHERE:** Application Wizard/Quick started
**WHEN:** Type the text it
**BEHAVIOUR CHECKED AT:** 10/jan/2018

# Steps to reproduce:
1. Openshift.io home >> click on the dropdown in the left top >> Create space 
2. Add a name to space >> Create Quick started 
3. Try to search due adding text into the filter field

# Result:
<img width="889" alt="screen shot 2018-01-10 at 11 29 54 am" src="https://user-images.githubusercontent.com/7708031/34771934-351a5618-f5fe-11e7-8241-dd9e3de9cf98.png">

# Expected Behaviour:
The method search should be called for each changed into the text(change to call it `onchange` 
 or `onkeydown` HTML event) 

# WORKAROUND:
Use the ENTER button into the keyboard.

**Comment by qodfathr** [comment]
@catrobson is this a bug, or a feature request? Should the filter text box be dynamically adjusting the list on every character typed?

**Comment by bartoszmajsak** [comment]
Closing as that reflects old Launcher and we don't provide search for quickstarts anymore.

**Comment by camilamacedo86** [comment]
@catrobson In the user point of view is a bug since is it did not have the button search and nothing os telling that is required to give the enter. The usability here is not good at all.

**Comment by bartoszmajsak** [comment]
@camilamacedo86  thanks for raising your concerns. Let me try to address them.

> the openhift.io did not have more wizard with the search filed?

We do have other places with search, no doubt about that :) If their functionality is broken though should be logged as another issue I believe (unless this is a general bug in the search component but then it still should be a different issue). If you can find this behaviour in other places I'm happy to help you file new issue and raise awareness in the team.

> Is the Application Wizard/Quick started removed?

The wizard has been redone and the issue you describe relates to the feature which does not exist - we do not have search for quickstarts - you simple select runtime (vertx, springboot etc.) and mission (health-check, rest etc.).

**Comment by camilamacedo86** [comment]
@bartoszmajsak tks for your attention and reply.
