### ISSUE TITLE
The cancel button on Application Wizard summary page cancels nothing.

### ISSUE THREAD

**Issue by liangxia** [openshiftio/openshift.io#1818]
Going through Application Wizard step by step till the last one (summary page), and click cancel, nothing cancelled.

**Comment by liangxia** [comment]
![screenshot from 2018-01-10 20-03-53](https://user-images.githubusercontent.com/4716987/34772580-770333ca-f643-11e7-8a44-3c837f4cd649.png)

**Comment by ldimaggi** [comment]
Duplicate of:  https://github.com/openshiftio/openshift.io/issues/1325
