### ISSUE TITLE
Unable to check all steps into the lateral menu on the Application Wizard

### ISSUE THREAD

**Issue by camilamacedo86** [openshiftio/openshift.io#1819]
# Problem Description
**WHAT:** Unable to check all steps into the lateral menu on the Application Wizard
**WHERE:** Application Wizard/
**WHEN:** the user is into the "Quick started" and Ïmport code base process" 
**BEHAVIOUR CHECKED AT:** 10/jan/2018

# Steps to reproduce:
1. Openshift.io home >> click on the drop-down in the left top >> Create space 
2. Add a name to space >> Create Quick started 
3. Follow the process

# Result:

<img width="860" alt="screen shot 2018-01-10 at 11 33 02 am" src="https://user-images.githubusercontent.com/7708031/34772201-2a33e48e-f5ff-11e7-8218-2f08e901eaf9.png">

# Expected Behaviour:
IHMO the lateral menu should show ALL steps. If it is not showing all next steps, so, what is the functionality of it?

**Comment by joshuawilson** [comment]
The wizard is getting completely redesigned. Closing as won't fix here.
