### ISSUE TITLE
Broken link to documentation at homepage

### ISSUE THREAD

**Issue by danieloh30** [openshiftio/openshift.io#182]
Can't link to documentation[1] at homepage
[1]https://access.redhat.com/documentation/en-us/red_hat_openshift.io/1/html-single/user_guide

**Comment by mishaone** [comment]
The link is correct but the documentation is (intentionally) not yet published.

**Comment by aditya-konarde** [comment]
@mishaone wanted to know what the status on this is. Are we ready to publish the documentation now?

**Comment by joshuawilson** [comment]
cc @rkratky

**Comment by rkratky** [comment]
@aditya-konarde, it was decided that OSIO docs won't be (at least for time being) published on the RH Customer Portal. Instead, they'll be at docs.openshift.io. As I mentioned in #313, this link should be removed until we have acks to publish on docs.osio.

**Comment by rkratky** [comment]
@aditya-konarde https://docs.openshift.io/ is now live and can be linked to.

**Comment by mindreeper2420** [comment]
In the current iteration of the Home Dashboard, there is no link to the documentation. That link is now in the user drop down menu under 'Documentation'.

The links on the Home Dashboard are "Learn More" (brings you to openshift.io/features), "your profile" (brings user to their profile) and "containerized development and deployment" (brings the user to openshift.com/container-platform).

@joshuawilson - do these need to change, or is the link to the documentation in the user drop down sufficient?

**Comment by joshuawilson** [comment]
I think this is fine, closing.

**Comment by pkettman** [comment]
@joshuawilson I think it would be still valuable to link the user docs also from the "Learn More" page if possible, as it's accessible & visible directly from the Account Homepage as an initial page to start & learn, also the "containerized development and deployment" link points to the comprehensive OCP docs.  

I was also looking for a user manual on "Learn more" first, then gave up and afterwards Robert pointed me to the side drop-down Docs item. I believe the sooner users get to the user documentation the less misunderstandings, confusion they can get into.

**Comment by joshuawilson** [comment]
@pkettman can you write up a new issue requesting this. This bug has been fixed. It is better to create a feature request so that UX and PM can review it.

**Comment by pkettman** [comment]
Done, it's https://github.com/openshiftio/openshift.io/issues/2050
