### ISSUE TITLE
First class citizen support for Firefox

### ISSUE THREAD

**Issue by rsvoboda** [openshiftio/openshift.io#1821]
Firefox is included in standard repositories for Fedora and RHEL.
Chrome is not part of standard repositories for Fedora and RHEL.

Firefox should be first class citizen for OpenShift.io usage too.
We are Red Hat, aren't we :).

**Comment by camilamacedo86** [comment]
However, I believe that Google Chrome is the most used navigator by devs. Particularly, I don't like too much use Firefox and the its dev tools.

**Comment by tradej** [comment]
To further @rsvoboda's point, only developing for Chrome basically [makes it the new Internet Explorer 6](https://www.theverge.com/2018/1/4/16805216/google-chrome-only-sites-internet-explorer-6-web-standards).

**Comment by joshuawilson** [comment]
@rsvoboda what makes you think that FF is not a first class citizen? I don't see any issues listed.

For reference see https://github.com/openshiftio/openshift.io/wiki/Supported-Browsers

**Comment by rsvoboda** [comment]
During the OSIO Test session we were told to use Chrome when people asked about FF.

Getting started guide PDF contains this: 
Page 2 => Browser requirements
`we require all participants to use the Google Chrome browser`

**Comment by joshuawilson** [comment]
We have been trying to make sure it works on other browsers. I think the intent of the doc was to ensure things worked since the first place we developed against was Chrome. 

If you have the time to run through the doc against FF, I would love to know if you run into any issues.

**Comment by qodfathr** [comment]
@ldimaggi does QE have a plan to certify FF?

**Comment by qodfathr** [comment]
Closing in favor of #2018
