### ISSUE TITLE
[RFE] [UX] Links to stage/prod applications are displayed as a regular text

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1822]
Links to stage/prod applications are displayed as a regular text, they got the 'link look and feel' only if the mouse cursor is hover above them. IMHO it might be better to inform users that app versions work as links.

**Comment by tradej** [comment]
I suggest the blue "Open in new tab" icon be used here to make this UI more consistent with the Pipelines view.

**Comment by qodfathr** [comment]
I assume this is regarding the Applications screen, which has be deprecated in favor of the #287 Deployments screen.
