### ISSUE TITLE
Log in problems during OSIO Test Day (Jan 10th 2018)

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#1823]
OSIO showed login problems.  

1)  When trying to access Michael's shared project, I could view the project when not logged in.  If I logged in, then I could no longer see the space.  (If I tried to hack the URL to jump straight to the Space, then it would log me out enroute.)
2)  Note the attached Screenshot.  I am logged in, trying to 'view all spaces'.  It knows it's me-- it's got my picture-- but the 'Log in' button is shown (and enabled).
![osio_login](https://user-images.githubusercontent.com/524520/34772667-6c97ddd4-f5ce-11e7-8081-18a0c7593671.png)

**Comment by ldimaggi** [comment]
This was a result of a test environment that was unstable and is not supported for anything beyond temporary internal testing. Closing - thanks!
