### ISSUE TITLE
Work item popop menu overlap

### ISSUE THREAD

**Issue by liangxia** [openshiftio/openshift.io#1824]
Create some work items, and bring out the popup menu.
![screenshot from 2018-01-10 20-20-50](https://user-images.githubusercontent.com/4716987/34772818-5e2e62ec-f644-11e7-934d-330589d2ed4a.png)

**Comment by michaelkleinhenz** [comment]
The kebab menu will be removed in the next version.

**Comment by michaelkleinhenz** [comment]
Also, this is only appearing in the old grid. The new one will be deployed to prod this week.
