### ISSUE TITLE
Getting started guide, Che and Jenkins versions, stress out that it's about tenant versions 

### ISSUE THREAD

**Issue by rsvoboda** [openshiftio/openshift.io#1826]
Getting started guide, page number 12 and 13 / 16th and 17th page in thumbnails.
Stress out that it's about Jenkins and Che tenant versions.

Example: `When visiting these URLs, you will see a screen like this, which indicates that the latest version of Che is 2.0.45:`

Should say `... latest version of Che tenant is ...`
Maybe add extra note that Jenkins and Che versions are not aligned to tenant versions.

**Comment by joshuawilson** [comment]
cc @rkratky @qodfathr

**Comment by qodfathr** [comment]
Probably could use better wording. I'm not sure "tenant version" is the best wording, however. I wound not expect anyone to know what that means, and we do not expose the term "tenant" anywhere else. It's not clear that we even want to draw attention to this implementation detail, as it can change in the future. Indeed, as we've done some multi-tenancy work, it has already changed.

Our goal is to get to a place whereby the tenants update automatically, anyway, at which point we probably will not so directly expose these version numbers in the UI.

My recommendation is to not address this until GA, in the event that things continue to evolve over the next several months.

**Comment by Preeticp** [comment]
@stevengutz, the Che and Jenkins Status indicator is no longer part of OSIO UX, as a result the docs removed this information: https://github.com/fabric8io/fabric8-online-docs/pull/279
@joshuawilson, @sbose78  can you please confirm on this. 
I believe we can close this issue.

**Comment by stevengutz** [comment]
Closed based on @Preeticp comment above
