### ISSUE TITLE
Creating a workitem in selected Iteration does not assign the workitem to the Iteration

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#1827]
![image](https://user-images.githubusercontent.com/3263627/34772902-065c8902-f60a-11e7-9d05-25ebe3e6cbe7.png)

## Impacts
- [ ] #2162 Planner Backlog Management Experience placeholder

**Comment by michaelkleinhenz** [comment]
Let's look at this again when the new iteration panel is in place. Looks like there is something off with the context, but the mechanism behind that will change with the new panel.

**Comment by nimishamukherjee** [comment]
Fix is on prod. Please re-open if you face the issue.
