### ISSUE TITLE
Quick start project widgets are not uniform

### ISSUE THREAD

**Issue by jkandasa** [openshiftio/openshift.io#1828]
Create a new software project via a “Quickstart.” On Select stacks, we can see a list of predefined projects. These projects display widgets are not uniform, hence not aligned properly.

![image](https://user-images.githubusercontent.com/1004403/34772915-caba2e4c-f62f-11e7-96de-faafd646a519.png)

**Comment by ldimaggi** [comment]
Can you confirm that this issue is seen on both production (https://openshift.io) and prod-preview? Thx!

**Comment by jkandasa** [comment]
@ldimaggi I see this issue in both environments.

**Comment by joshuawilson** [comment]
This looks like a styles setting.

**Comment by qodfathr** [comment]
I've never seen this, and certainly not recently. @ldimaggi , still seeing it?

**Comment by ldimaggi** [comment]
I'm missing something here - what is the issue?

https://ci.centos.org/view/Devtools/job/devtools-test-end-to-end-ts-prod-preview.openshift.io-quickstartTest/

![screenshot from 2018-01-29 17-48-09](https://user-images.githubusercontent.com/642621/35538657-b3234970-051c-11e8-9912-a22e90f79340.png)

**Comment by qodfathr** [comment]
well, @ldimaggi , you did agree what it was a problem 20 days ago. :) Sounds like it is now fixed. Closing.
