### ISSUE TITLE
OS project name mapping changed when github profile email address changed

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#183]
I have had an account on OSIO for a couple of weeks. When I logged in to my account for the first time, it created a bunch of projects under my tenant account. Project are called 'jf-cron0' (, -che, -jenkins, -test, -run, -stage). I assume this is because my github email address is 'jf.cron0@gmail.com'. I was able to successfully deploy code and workspaces in the past. (last time ~2 weeks ago)

Today I tried to create a new space and got the following error:
```
Something went wrong configuring your pipelines and environments as the OpenShift Project 'jfchevrette' is not accessible to you or does not exist.
```

I remembered that last week I changed my github email address to jfchevrette@gmail.com. It appears that because of this the mapping between the openshift projects there were originally created is now broken.

As a user I have no way of fixing it other than changing my github profile email back to the previous value and wait for the credentials cache to expire. I assume there is a cache because I tried changing my email and logged off/on in OSIO and it didn't help.

**Comment by joshuawilson** [comment]
You may try updating your tenant.
Select the dropdown at your username
Select Profile
Click on the Update Profile button
Scroll to the bottom and click on the Update Tenent button

**Comment by jfchevrette** [comment]
@joshuawilson I tried that, didn't seem to do anything. There was no feedback when I clicked the button.

**Comment by RanjithRV** [comment]
@jfchevrette @alexeykazakov can you please look into this issue created in May 2017. I am guessing this must be resolved by now. Can you please verify and close?

**Comment by RanjithRV** [comment]
@alexeykazakov @sbose78 since this is been here since May 2017, I have classified it as SEV3. Please update if its misclassified.

**Comment by alexeykazakov** [comment]
This is/was not an auth issue anyway. Moved it to the build-cd team.

**Comment by piyush1594** [comment]
@jfchevrette Is this still a problem and need to be resolved?

**Comment by jfchevrette** [comment]
I'm not seeing this anymore. Closing.
