### ISSUE TITLE
Planner calendar doesn't allow date usage

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#1831]
Making a new Iteration, I was unable to choose arbitrary dates.

1.  Make Iteration 1.  Assign dates from today - 1 week from today.
2.  Make Iteration 2.  Dates are restricted (see screenshot).

This may be user error -- I assigned the project as the Parent Iteration.  (Is that the right thing to do?)

![osio_cant_use_calendar](https://user-images.githubusercontent.com/524520/34773129-30738df6-f5d0-11e7-9751-a9197961ab78.png)

## Impacts
- [ ] #2162 Planner Backlog Management Experience placeholder

**Comment by michaelkleinhenz** [comment]
I can't reproduce this. Can someone else try? @nimishamukherjee

**Comment by Preeticp** [comment]
Related to this issue: https://github.com/fabric8-ui/fabric8-planner/issues/2386

**Comment by debloper** [comment]
Should have been fixed with fabric8-ui/fabric8-planner#2402

**Comment by nimishamukherjee** [comment]
@vikram-raj please check. I face the issue for the end date for the second iteration.

**Comment by rgarg1** [comment]
@pranavgore09 @vikram-raj Fixed with https://github.com/fabric8-ui/fabric8-planner/pull/2500

**Comment by nimishamukherjee** [comment]
Fix is in prod.
