### ISSUE TITLE
Too much space around text under "Detailed analysis of your stack components"

### ISSUE THREAD

**Issue by budhrg** [openshiftio/openshift.io#1833]
Steps to reproduce:
1. Create space
2. Go to stack report
3. Hover over rows under "Detailed analysis of your stack components"

See below:
![1 hover](https://user-images.githubusercontent.com/1132451/34771109-64f65adc-f629-11e7-970d-bc4499e03a3c.png)
![2 hover](https://user-images.githubusercontent.com/1132451/34771110-652e1c06-f629-11e7-8a3f-2e4a749a3a8d.png)

**Comment by krishnapaparaju** [comment]
@arunkumars08 @jyasveer please test this out as part of UX revamp work , due by end of sprint # 143.

**Comment by arunkumars08** [comment]
@krishnapaparaju Yes, this will be handled as a part of new revamp

**Comment by sunilk747** [comment]
Closing this issue as this case is handled as part of new UI.

**Comment by sunilk747** [comment]
Closing this issue as this case is handled as part of new UI.
