### ISSUE TITLE
Work Item Assignees/Labels selector is unintuitive

### ISSUE THREAD

**Issue by shannon** [openshiftio/openshift.io#1834]
When you select a name or names from the assignee selector, it's unclear that you have to hit the `x` to make the change persistent. `x` feels like it should be cancel. There should probably be a check box. The same goes for the label selector.

<img width="336" alt="capture" src="https://user-images.githubusercontent.com/1154610/34773430-aff6aa32-f5d9-11e7-9d6e-0caa6e684364.PNG">

**Comment by michaelkleinhenz** [comment]
Note: UX issue.

**Comment by qodfathr** [comment]
See also #2000

**Comment by Veethika** [comment]
@shannon @michaelkleinhenz this behavior has been defined by Patternfly and we couldn't take a call to get rid of it. The learning curve with this behavior is very short, hence this doesn't affect the experience much.
If needed please raise an issue on the Patternfly team repository on GitHub
https://github.com/patternfly/patternfly-design/issues

**Comment by christianvogt** [comment]
Closing as UX guidance is to continue using the current design.
