### ISSUE TITLE
Planner 'Experience' Title bar is unintuitive

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#1835]
When making a new 'Experience' in Planner, "Enter title" is depicted in grey and is placed apart from other input fields (which are in white).

To me, this makes the "Enter title" area almost invisible, it is not intuitive.

![osio_makeexperience](https://user-images.githubusercontent.com/524520/34773556-be018532-f5d1-11e7-9e96-4853a6793673.png)

**Comment by michaelkleinhenz** [comment]
Note: UX issue.

**Comment by rgarg1** [comment]
Planner removed the functionality to allow work item creation through the detailed view screen. Also added is a border around the title field to improve visibility. However, I'd le UX take the call on what next should be done.

**Comment by joshuawilson** [comment]
cc @openshiftio/uxd-team

**Comment by muruGanesan** [comment]
@sunilmalagi, @Veethika, any thoughts on this point?

**Comment by Veethika** [comment]
@RickJWagner as @rgarg mentioned we do not allow WorkItem creation through detailed view anymore. That said, we have included an outline around the text field for the title (and other text inputs) to improve noticeability.
