### ISSUE TITLE
jenkins-git-ssh key not created automatically

### ISSUE THREAD

**Issue by edseymour** [openshiftio/openshift.io#1838]
Creating a new space and using one of the quickstarts (vertx health check example), the jenkins slave failed to start. The problem was that the jenkins-git-ssh secret was missing. 

I noticed my github account didn't have a public SSH key configured, although the client would need its own private key to work, I presume. 

Creating a dummy source secret `jenkins-git-ssh` resolved the problem.

**Comment by joshuawilson** [comment]
@alexeykazakov is this an Auth issue?

**Comment by alexeykazakov** [comment]
> is this an Auth issue?

No.

**Comment by bartoszmajsak** [comment]
@piyush1594 @rupalibehera is that related anyhow to Launcher or is that purely Build issue?

**Comment by piyush1594** [comment]
Not sure about this @bartoszmajsak

**Comment by chmouel** [comment]
I don't believe this ever has been reported again, so after almost one year we can close this,
