### ISSUE TITLE
Repeatedly logged out from pre-prod

### ISSUE THREAD

**Issue by pkettman** [openshiftio/openshift.io#1839]
During testing on initial Len's test session on https://fabric8-ui-fabric8-ui-pr-2380-fabric8-planner.badger.fabric8.io I got repeatedly logged out, e.g. each 10-15 minutes while testing the new planner features.

**Comment by ldimaggi** [comment]
This was a result of a test environment that was unstable and is not supported for anything beyond temporary internal testing. Closing - thanks!
