### ISSUE TITLE
Creating a new pipeline collaterally re-recreates deleted pipelines

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#184]
Steps to reproduce :

1. Create space.

2. Create 3-4pipelines 

3. I deleted all but 1 from the openshift online webconsole because the the 'delete pipeline' option in openshift.io returned a HTTP 405  
```
Request URL:https://openshift.io/_p/oso/oapi/v1/namespaces/shbose/buildconfigs/sbose12345
Request Method:DELETE
Status Code:405 Not Allowed
```

4.  So I tried deleting them from OpenShiftOnline , which worked.
5. I checked the Pipelines page on OpenShift.io , the deleted ones were gone - all good till now.
6. I add a new pipeline using the quickstart.
7. In the end, the new one gets added, and the all the deleted ones gets recreated. They show up in OpenshiftOnline too ( so basically its not a UI-only thing )

Video:
https://drive.google.com/file/d/0Bz8VjLQTuhwvVHY5RWxPU2F3SGs/view

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1403
