### ISSUE TITLE
Problems with https://openshift.io/osiogettingstarted.pdf (not typos)

### ISSUE THREAD

**Issue by tradej** [openshiftio/openshift.io#1842]
This is a (non-exhaustive) list of problems I found in the Getting Started document:

* P17, “Name” is in the docs, “OpenShift Project Name” is in GUI.
* P26: Instruction to click “Create workspace” actually missing.
* P27: It is not obvious where the command-line screenshot comes from. My Che instance didn’t show any of that.
* P37: Does not say whether the reader should commit the changes.
* P38: Missing information about what to do with Stack report.
* P46, par. 3: It’s not a red X that appears, but a yellow triangle. Also, gutter seems quite a specialised term to me to be used in a Getting Started material.
* P47, par. 1: Tell users it is the Terminal window on the bottom of Che, not just any terminal.
* P49, par. 2: Not obvious how the reader should save (commit? push?) or what hot redeploy is.
* P50, par. 1: It’s not obvious where the stop button is without the screenshot (bad for accessibility).
* P51, par 1: Not obvious which of the plusses to press without the screenshot (bad for accessibility).
* P51: Could provide information that double-clicking the line number creates a bookmark and not a breakpoint.

Outdated screenshots:

* P41, 42, 52 (first scr.), 53 (second scr.)

**Comment by joshuawilson** [comment]
cc @rkratky @qodfathr

**Comment by rkratky** [comment]
@mishaone, @Preeticp, please check and potentially fix these issues if they also occur in the new doc.

**Comment by qodfathr** [comment]
Thanks for the feedback, @tradej. Setting to SEV4 because it's likely that the Getting Started guide will be deprecated before we have a chance to fix it.. @rkratky, there have been a lot of these types of issues reported. I'm confident the docs team is ensuring these will be addressed, as needed, in the new docs. :)

**Comment by mishaone** [comment]
Logged an issue to check these issues in the latest version of the getting started doc once we finish updating it: https://github.com/fabric8io/fabric8-online-docs/issues/174

**Comment by rkratky** [comment]
The old PDF is no longer used, and all remaining issues have been addressed in https://docs.openshift.io/getting-started-guide.html (and https://docs.openshift.io/getting-started-guide.pdf). Closing.
