### ISSUE TITLE
Work item counter in the sidebar always 0

### ISSUE THREAD

**Issue by inoxx03** [openshiftio/openshift.io#1845]
In the production deployment on openshift.io, in the Planner section, the sidebar always lists the number of outstanding issues as 0, despite there being several issues on the backlog.

This happens regardless of the Issue status (new, open, in progress, resolved...)
The counter does not seem to be responding to the actual number of issues in the backlog.

Attaching image of reference:

![osio-item-counter-issue](https://user-images.githubusercontent.com/17914654/34774830-377d56d6-f611-11e7-85ea-e30ce42dd548.png)

**Comment by michaelkleinhenz** [comment]
The counts will be removed entirely in the next version.
