### ISSUE TITLE
WI Type incorrectly set if quick add is committed using Enter key

### ISSUE THREAD

**Issue by pkettman** [openshiftio/openshift.io#1846]
I have create several new Experiences in Planner on https://fabric8-ui-fabric8-ui-pr-2380-fabric8-planner.badger.fabric8.io/pkettman/PKE_Space and some of them turned to Scenarios and are now listed as Scenarios, see below. In addition one created Requirement was changed to Experience.

![experiences](https://user-images.githubusercontent.com/26871874/34774865-5b291d0e-f611-11e7-9dc7-e703e08932c6.png)
![scenarios](https://user-images.githubusercontent.com/26871874/34774866-5b41870e-f611-11e7-88a1-37c5899a5ea7.png)

## Impacts
- [ ] #2162 Planner Backlog Management Experience placeholder

**Comment by ldimaggi** [comment]
This was a result of a test environment that was unstable and is not supported for anything beyond temporary internal testing. Can you recreate this in production?

**Comment by pkettman** [comment]
No, this functionality is not on Production yet.

**Comment by michaelkleinhenz** [comment]
This weird anyway. Even when unstable, this should not happen at all.

**Comment by rgarg1** [comment]
@pkettman Notice the workitem IDs in the __ID__ column? The IDs for scenarios and Experiences displayed are different, which means that they are different workitems. E.g. Expereinces IDs (21, 20, 14, ...., 6), whereas Scenarios IDS (22, 19, 7, ..., 1). Visually, it may appear that workitems changed while switching context from say, **Experiences** to **Scenarios** as only the matching entries are currently displayed.

Kindly validate my findings and let us know if this is the case. Thanks.

**Comment by pkettman** [comment]
I looks like the wrong Type is associated with a workitem if I add it by writing a name and hitting Enter. When I write a name and click 'Add' or 'Add and Open' it keeps the right type. See pictures, titles explains way of creation :-)

![requirement2](https://user-images.githubusercontent.com/26871874/34818058-07a21ac4-f6ba-11e7-9bb6-b78c3746d68d.png)
![experience2](https://user-images.githubusercontent.com/26871874/34818059-07be0f40-f6ba-11e7-8bef-5820b0cda531.png)
![scenario2](https://user-images.githubusercontent.com/26871874/34818061-08e533c6-f6ba-11e7-9214-20b9d7af2605.png)

**Comment by michaelkleinhenz** [comment]
I can now reproduce this. Steps:

1. Go to "Scenarios".
2. Add a new WI using the quick add. **Do not touch the dropdown.** Press Enter for committing (**do not use the button**).
3. The new WI is added to the current view as a Scenario.
4. Switch to "Experiences". The new Scenario is listed there as an Experience(!).
5. Switch back to "Scenarios". The new Scenario is not listed.

I think what happens here is that the type is not correctly set when the user does not touch the toolbar dropdown and/or buttons. Looks like an issue with the default type then.

**Comment by pkettman** [comment]
Yes, good point when I select a WI type via dropdown, the issue is not reproduced. And the issue is valid also for Experiences and Requirements added by Enter without the dropdown selection.

**Comment by jarifibrahim** [comment]
@michaelkleinhenz I cannot reproduce the bug on prod/prod-preview. Can you please confirm?

**Comment by pkettman** [comment]
I just retested it on prod and it seams to work fine now.
