### ISSUE TITLE
Wrong info about licenses are displayed on openshift.io for the "Hello world" vertx project

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1847]
I've realized in on today's test day:

### Current output:

![stack_analysis_current](https://user-images.githubusercontent.com/4579967/34774940-39fa30d0-f609-11e7-8041-fe7dc3a3f446.png)

### Expected output:

![stack_analysis_expected](https://user-images.githubusercontent.com/4579967/34774941-3a18d10c-f609-11e7-8798-3899556d86f5.png)

**Comment by sara-02** [comment]
@tisnik Please try again in some time.
With the latest code in prod, this error should get resolve.
Let us know if it still does not work.

**Comment by sara-02** [comment]
Will close the issue, once @tisnik has verify :)

**Comment by tisnik** [comment]
@sunilk747 do you think we will need to open another issues for the missing graph?

**Comment by sara-02** [comment]
@tisnik that would be better. 
To further verify that the license service is giving the expected output, you can paste the response stack-analysis `get` request.
Then we can close this issue, and create a new one for the integration team to track. :)

**Comment by tisnik** [comment]
ok @sara-02, thanks!

**Comment by sara-02** [comment]
From the license scoring side, we are finally getting the expected output.
![screenshot from 2018-01-10 15-40-56](https://user-images.githubusercontent.com/7047079/34782851-e9206aac-f64f-11e7-8f5a-d29ed240e385.png)

**Comment by tisnik** [comment]
yeah, that's correct as far as I can tell 👍
