### ISSUE TITLE
Not working "Plan out my space" and "Create new code from scratch" in welcome popup

### ISSUE THREAD

**Issue by danieloh30** [openshiftio/openshift.io#185]
During creating new space, we can see the popup window as below screenshot. But when we click icons related to "Plan out my space" and "Create new code from scratch", it's not working but only "Import exist code" and "Select technology stack and pipeline" . 

![screenshot from 2017-05-29 22-33-37](https://cloud.githubusercontent.com/assets/14066977/26551742/e740010e-44be-11e7-985f-d3e6cea09c92.png)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1417

**Comment by RanjithRV** [comment]
Closing this one as the associated ticket 1417 was closed 

Note: The requirements were changed and those links removed from that particular navigation. more info on #https://github.com/fabric8-ui/fabric8-ui/issues/1417
