### ISSUE TITLE
Unable to recognized and create app environments which are not JAVA

### ISSUE THREAD

**Issue by camilamacedo86** [openshiftio/openshift.io#1850]
# Problem Description
**WHAT:** Unable to recognized and create app environments which are not JAVA
**WHERE:** Import code base actions
**WHEN:** Import a project that is not JAVA stack 
**BEHAVIOUR CHECKED AT:** 10/jan/2018

# Steps to reproduce:
1. Openshift.io home >> click on the drop-down in the left top >> Create a space 
2. Click on the  "import codebase" button
3. Select an organization and repo which is not JAVA (E.g NodeJS)  

# Result:
No matter the project added always get the same pipeline. The project adds to the test was a NodeJS and not JAVA. Following the Jenkins build. 

```
[86_blank-cordova-app_master-4CNXUSJXKIWTWDBGVSJWTN4X46D4W2ZTBYP6JXCR2E5LV6A4YBGA] Running shell script
+ mvn org.codehaus.mojo:versions-maven-plugin:2.2:set -U -DnewVersion=1.0.1
Picked up _JAVA_OPTIONS: -Duser.home=/root/ -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.478 s
[INFO] Finished at: 2018-01-10T14:00:30+00:00
[INFO] Final Memory: 3M/9M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.2:set (default-cli): Goal requires a project to execute but there is no POM in this directory (/home/jenkins/workspace/86_blank-cordova-app_master-4CNXUSJXKIWTWDBGVSJWTN4X46D4W2ZTBYP6JXCR2E5LV6A4YBGA). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
EXITCODE   0[Pipeline] }
```

# Expected Behaviour:
Recognize that type of the Repo and create an adequated pipeline.

**Comment by ldimaggi** [comment]
At present - we only support Java apps.

**Comment by qodfathr** [comment]
Thanks, @camilamacedo86, for this feedback. We totally agree with you! Polyglot support is absolutely a part of our roadmap; it's simply not part of the pre-beta service. There are a lot of pieces that need to be made operational to support a language -- support in the QuickStart wizard, support in Che, support in the build pipelines, support in stack analysis, even support in the runtime environment in OpenShift Online. We are actively working on all of these things, for a number of languages, but we currently do not have a reasonable predictor for when they will ship. "In 2018" is about as accurate a statement as I can make at this time. We hope to provide more concrete roadmaps within the next few months.

As this is part of our backlog, I'm going to close this issue, but I do welcome your opinion on which languages and frameworks you'd like us to support. The unofficial plan beyond Java (so don't hold me to this verbatim) is to support the major languages in use today by our customers -- such as TypeScript/JavaScript (especially for NodeJS apps), GO, C/C++, C#, Python. Does that sound like a reasonable list to you? Do you see any glaring omissions? It appears, based upon the output that you shared, that you are attempting to build a Cordova app. We are also investigating working with the Red Hat Mobile Platform team (https://www.redhat.com/en/technologies/mobile) to bring their Cordova-building capabilities into OpenShift.io; much like the other language support, we currently do not have a concrete timeline for this to happen.

**Comment by camilamacedo86** [comment]
@qodfathr :-) Sure
