### ISSUE TITLE
Jenkins not starting (prod-preview)

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#1855]
(This is on prod-preview) Upon finishing the app wizard, a pipeline build is kicked off. When I go to the pipelines screen, I can see my pipeline, but it's not doing anything. Looking at Jenkins status, it appears to be off.
![image](https://user-images.githubusercontent.com/16322190/34779612-bda93572-f5ee-11e7-86c0-458f26f57c9f.png)
That screenshot was taking 7 minutes after the pipeline tried to start; after 9 minutes nothing had changed.

**Comment by ldimaggi** [comment]
After an env reset, the Jenkins pods are not starting for me on prod-preview:
```
10:33:18 AM | jenkins | Deployment Config | Warning | Failed Retry | Stop retrying: couldn't create deployer pod for "ldimaggi-osiotest1-jenkins/jenkins-1": pods "jenkins-1-deploy" is forbidden: exceeded quota: force-sleep, requested: pods=1, used: pods=0, limited: pods=0
10:33:18 AM | jenkins | Deployment Config | Warning | Failed Create | Error creating deployer pod: pods "jenkins-1-deploy" is forbidden: exceeded quota: force-sleep, requested: pods=1, used: pods=0, limited: pods=016 times in the last 5 minutes
10:33:18 AM | content-repository | Deployment Config | Warning | Failed Retry | Stop retrying: couldn't create deployer pod for "ldimaggi-osiotest1-jenkins/content-repository-1": pods "content-repository-1-deploy" is forbidden: exceeded quota: force-sleep, requested: pods=1, used: pods=0, limited: pods=0
10:33:18 AM | content-repository | Deployment Config | Warning | Failed Create | Error creating deployer pod: pods "content-repository-1-deploy" is forbidden: exceeded quota: force-sleep, requested: pods=1, used: pods=0, limited: pods=016 times in the last
```

**Comment by ldimaggi** [comment]
This looks OK today:

![screenshot from 2018-01-11 08-25-51](https://user-images.githubusercontent.com/642621/34827712-15703796-f6a9-11e7-8afe-88c6be0cea81.png)

**Comment by ldimaggi** [comment]
![screenshot from 2018-01-11 08-26-47](https://user-images.githubusercontent.com/642621/34827741-2fb6748a-f6a9-11e7-8e7d-729b787ac11c.png)

**Comment by ldimaggi** [comment]
And - it's back...

![screenshot from 2018-01-11 16-51-33](https://user-images.githubusercontent.com/642621/34849232-b84563a6-f6ef-11e7-8314-f8a28593c99e.png)
![screenshot from 2018-01-11 16-51-12](https://user-images.githubusercontent.com/642621/34849233-b8545c94-f6ef-11e7-8fca-38d119fcab58.png)

**Comment by ldimaggi** [comment]
Seeing events like this:

Error creating deployer pod: pods "content-repository-4-deploy" is forbidden: exceeded quota: force-sleep, requested: pods=1, used: pods=0, limited: pods=0

**Comment by ldimaggi** [comment]
And now - it seems OK again....
