### ISSUE TITLE
https://openshift.io/osiogettingstarted.pdf should follow the IBM Style Guide

### ISSUE THREAD

**Issue by tradej** [openshiftio/openshift.io#1856]
As a part of the OSIO documentation, I believe the Getting Started document should follow the rules prescribed by the IBM Style Guide, most notably (but not limited to):

* No contractions (isn't, doesn't)
* No future tense unless something really happens in the future (e. g. _The number of GitHub permissions required by OSIO will be reduced..._)
* Use of dashes (Is "Foo -- bar", should be "Foo—bar" with an em dash, no spaces.)
* Using "can" or "might" instead of "may"
* Consistent punctuation at the end of list items
* Consistent formatting of elements, e. g. buttons: _'Play'_ vs. _"Next>"_ vs. _MENU_
* Not referencing images using the word "this" in places where are multiple screenshots on a page

This is valid for the entire document.

**Comment by joshuawilson** [comment]
Just asking, but why `IBM`? Do you have a link? 
Is there a Red Hat Style guide we should follow? 
cc @qodfathr

**Comment by qodfathr** [comment]
The Getting Started guide is being revised by the Red Hat documentation team. It will likely adopt many Red Hat documentation conventions, but the spirit of the Getting Started guide is to be more conversational that traditional technical reference documentation.

Stringent style rules will be applied to reference materials.

I recommend closing this issue and evaluating the new Getting Started guide when it is published.
