### ISSUE TITLE
The license pie chart is not shown on openshift.io

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1858]
The license pie chart is not shown on openshift.io:
![screenshot from 2018-01-10 15-40-56](https://user-images.githubusercontent.com/7047079/34782851-e9206aac-f64f-11e7-8f5a-d29ed240e385.png)

I'm not sure whether it is still supported or not, @samuzzal-choudhury WDYT?

FYI:
Previous issue that has been already fixed on OSIO:
https://github.com/openshiftio/openshift.io/issues/1847

**Comment by qodfathr** [comment]
@slemeur @krishnapaparaju is this a bug? Or do the new stack report designs mean this issue may be closed?

**Comment by miteshvp** [comment]
Closing this as this design is no longer valid. New UX is in place.
