### ISSUE TITLE
Link to stack analysis report missing

### ISSUE THREAD

**Issue by luebken** [openshiftio/openshift.io#186]
<img width="1350" alt="screen shot 2017-05-29 at 16 53 00" src="https://cloud.githubusercontent.com/assets/53055/26571368/f062aec4-4515-11e7-9abb-10e23e436aa1.png">

I expected a link / button to stack analysis report under the "Build Release" stage.

**Comment by miteshvp** [comment]
Yes, I have seen CD pipeline works just fine. Its the CI pipeline that does not report the said button.

**Comment by arunkumars08** [comment]
As far as I have checked, the authentication token seems to have expired. Thus resulting in a 401 while hitting Bayesian's endpoint from Jenkins.

**Comment by samuzzal-choudhury** [comment]
@luebken this is in working condition now. To test, go to your OSO profile > Update profile > Update tenant. Related issue https://github.com/fabric8-analytics/fabric8-analytics-jenkins-plugin/issues/2.  CC: @arunkumars08

**Comment by luebken** [comment]
I was able to re-run the pipeline but the link to the build report is still missing.

<img width="1459" alt="screen shot 2017-06-06 at 09 26 29" src="https://cloud.githubusercontent.com/assets/53055/26818315/77bf8c64-4a9a-11e7-8457-b6507f3e4f50.png">

**Comment by samuzzal-choudhury** [comment]
@luebken do clicking on "View Log" for the build and searching for "bayesian" show you a 401 error in the Jenkins console log? If yes, the tenant has not been updated for you. In that case, we can conclude that your tenant did not update.

**Comment by luebken** [comment]
Did another "update tenant" round. Now it works.

@samuzzal-choudhury thanks.
