### ISSUE TITLE
Che is not able to create workspaces on https://openshift.io

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1860]
Seeing this problem repeatedly for the past couple of hours:

Could not start workspace jan10-t6cyz. Reason: Start of environment 'default' failed. Error: Failed to get the ID of the container running in the OpenShift pod

![screenshot from 2018-01-10 20-31-02](https://user-images.githubusercontent.com/642621/34804208-57af8e86-f645-11e7-9250-2912d22ed490.png)

**Comment by rhopp** [comment]
Is this happening every time? Could you provide some logs? 
Isn't this just https://github.com/openshiftio/openshift.io/issues/1666 again?

**Comment by ibuziuk** [comment]
yeah, there was starter-us-east-2 cluster maintenance and looks like we need to restart contollers yet another time https://github.com/openshiftio/openshift.io/issues/1666#issuecomment-356869719

**Comment by ibuziuk** [comment]
@ldimaggi could you please verify that this does not happen any more ?

**Comment by ldimaggi** [comment]
This looks OK now - thx closing.
