### ISSUE TITLE
https://docs.openshift.io/ should mention at least osiogettingstarted.pdf

### ISSUE THREAD

**Issue by rsvoboda** [openshiftio/openshift.io#1862]
https://docs.openshift.io/ says:
```
OpenShift.io Documentation
coming soon
```

https://docs.openshift.io/ should mention at least https://openshift.io/osiogettingstarted.pdf

I got link to osiogettingstarted.pdf when accessing OpenShift.io for the first time, to find it again I had to search my browser history.

**Comment by joshuawilson** [comment]
cc @rkratky

**Comment by rkratky** [comment]
@qodfathr Would you agree to make docs.openshift.io live? Users who have already been onboarded, i.e. went through the currently used PDF, could benefit from having access to the docs we're developing. And they could start filing issues against them etc.

**Comment by qodfathr** [comment]
@rkratky makes sense. +1.

Thanks for the feedback, @rsvoboda. Two things: (1) that PDF is just a temporary, pre-beta stop-gap solution and (2) the link is also in the welcome email you got. (Not that I would expect people to necessarily remember that.)

**Comment by rkratky** [comment]
@rsvoboda https://docs.openshift.io/ has been updated and now hosts OSIO docs.

**Comment by rsvoboda** [comment]
@rkratky :+1:

**Comment by rkratky** [comment]
@rsvoboda Now that docs.openshift.io is live with docs, can this be closed?

**Comment by rsvoboda** [comment]
yes, closing.
