### ISSUE TITLE
Cannot create new quickstart on https://openshift.io

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1863]
This error is seen - is this the CORS issue again?

![screenshot from 2018-01-11 06-44-30](https://user-images.githubusercontent.com/642621/34824083-0a09ca7e-f69b-11e7-9149-c7f408174d66.png)

**Comment by pbergene** [comment]
Generator backend crashing heavily.  @gastaldi

**Comment by gastaldi** [comment]
Having a look

**Comment by gastaldi** [comment]
It works for me. What steps did you follow to reproduce that?

**Comment by sbose78** [comment]
Worked for me.

**Comment by gastaldi** [comment]
Removing the SEV-1 label, as it is working and apparently it doesn't for @ldimaggi's user only

**Comment by gastaldi** [comment]
Closing as it is not reproducible. Reopen if the problem persists

**Comment by ldimaggi** [comment]
Whatever the problem was - it's gone now - was failing repeatedly early this morning. Thx!

**Comment by ldimaggi** [comment]
Issue found/encountered by EE tests.
