### ISSUE TITLE
Incorporate loading indicator on Deployments page

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1865]
It would be nice for there to be a loading indicator of some sort when waiting for data to arrive before UI elements can be displayed.

For example, setting a delay of 10 seconds on the Observable that deals with application deployments, the UI will not display any application cards till 10 seconds pass. In the meantime, the application deployments section is empty and currently, there is no indication of what's happening. In a real-world scenario, this would occur naturally based on the network RTT.

## Parent Feature
#1658 UI: Show deployment details

**Comment by jiekang** [comment]
@catrobson There is no UX design for this at the moment as far as I know. Should we coordinate with you on how this should look?

**Comment by catrobson** [comment]
@jiekang can you reach out to Michael Celedonia on chat about this to get to a finer level of detail, or maybe a quick bluejeans would help.  I'll ping him to look at this issue and be prepared.

It would be helpful to understand from a technical standpoint whether we can start drawing the screen, but just segments of it might need a loading spinner/indicator, or if we need the whole page to have a loading state, or both.

**Comment by jiekang** [comment]
For the record I've talked with Michael about this and we've agreed on a plan moving forward. Hope to see UI mock ups to code against soon; in the mean time I'll be writing some prototype implementations.

**Comment by jiekang** [comment]
Link to mock:

https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/273548936
