### ISSUE TITLE
fix failing UI builds

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#1866]
The UI builds are failing on the fabric8-cd pipeline. We think it might have to do with PhantomJS.

One issue is listed at https://github.com/karma-runner/karma-phantomjs-launcher/issues/126
Might also try using headless Chrome. 

## Impacts
- [ ] #2131 OpenShift.io development uses CI

**Comment by joshuawilson** [comment]
@bartoszmajsak do you have time to look into this?

**Comment by sthaha** [comment]
This issue seems to be not relevant anymore; hence closing it. Please reopen it if that isn't the case.
