### ISSUE TITLE
Tiny off-center Codebase GitHub icon

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1867]
![screenshot from 2018-01-11 20-49-02](https://user-images.githubusercontent.com/132158/34844329-5ab45bda-f711-11e7-838b-455290f8943f.png)

**Comment by bartoszmajsak** [comment]
Did you try to clear your cache?

**Comment by joshuawilson** [comment]
I can confirm it.

**Comment by aslakknutsen** [comment]
@joshuawilson Did you clear your cache?
