### ISSUE TITLE
There is no header in home page if there is some parameter in URL

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#1868]
If I open https://openshift.io/_home then I see the header (with username, drop down menu, etc). But if I open for example https://openshift.io/_home?verified=true (we redirect there after email verification) then the header is missing.

![scr](https://user-images.githubusercontent.com/620087/34851831-a579aa20-f6e0-11e7-9e76-7feb4f363a34.png)

**Comment by joshuawilson** [comment]
@alexeykazakov do you know why we redirect to that URL?
@dgutride or @dlabrecq can you take a look at this?

**Comment by alexeykazakov** [comment]
@joshuawilson we redirect to this URL when user clicks on the link from the verification email. We are going to redirect to a dedicated page later but for now we redirect to _home with a param.

**Comment by dlabrecq** [comment]
This seems to happen with any query param. I see errors in the browser console and suspect this error prevents the header from rendering properly.

"GET https://api.openshift.io/api/spaces/3eeaa158-a68c-4ff3-9b0d-23ee3368d8b3 404 (Not Found)"
"Failed to retrieve list of spaces owned by user"

**Comment by alexeykazakov** [comment]
I see this space ID is hardcoded here https://github.com/fabric8-ui/fabric8-ui/blob/0db1b8c07de4bbc667826f2c6c309e1ca243e0d9/src/app/profile/my-spaces/my-spaces-item-actions/my-spaces-item-actions.component.spec.ts#L108
Not sure why and how it affects this usecase.

**Comment by dgutride** [comment]
@alexeykazakov - that's just a unit test, this is related to the hardcoded _home in several components.  Must be a new use-case to add something to that url as this hasn't changed in a while on the front end.

**Comment by dgutride** [comment]
Fixed by https://github.com/fabric8-ui/fabric8-ui/pull/2389 @alexeykazakov @joshuawilson
