### ISSUE TITLE
Failed to create space with max character length (63 chars)

### ISSUE THREAD

**Issue by liangxia** [openshiftio/openshift.io#1869]
Max character length for space name is 63 chars.

![screenshot from 2018-01-12 11-07-50](https://user-images.githubusercontent.com/4716987/34858118-67476dce-f789-11e7-8fb8-fc7f03773e6c.png)
When you input 63 chars for the name, no error prompt, and create button is clickable,

![screenshot from 2018-01-12 11-08-17](https://user-images.githubusercontent.com/4716987/34858119-677a958c-f789-11e7-8c6c-a1afec48e1c1.png)
But it actually failed to create the space (The welcome dialog is called out, but actually the space is nto created).
![screenshot from 2018-01-12 11-15-46](https://user-images.githubusercontent.com/4716987/34858266-40e5c4ae-f78a-11e7-91e3-54052cdfa7ee.png)

**Comment by nurali-techie** [comment]
**Issue:** creation of space failed when space name has 63 chars.
**Why:** backend API allowed name with max length 62 chars only.  Check - https://github.com/fabric8-services/fabric8-wit/blob/master/design/resources.go, function -> nameValidationFunction()
**Fix:** modify nameValidationFunction() and set MaxLength to 63
**Impact:** this nameValidationFunction() used not only for space name but also for name of areas, iterations, labels, queries, work_item_link_category, work_item_link_type, workitemtype.  So all these entities name max length will change from 62 to 63.
