### ISSUE TITLE
All status icons apart from "Jenkins" are currently just hardcoded "success" placeholders

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#1870]
![image](https://user-images.githubusercontent.com/1461122/34865895-c34774ac-f77a-11e7-8a79-024bdf153d20.png)

Need to obtain the real status & version of the service for:

- [ ] Che
- [ ] Console
- [ ] Analitics
- [ ] GitHub
- [ ] Forge

**Comment by kbsingh** [comment]
dropping service-delivery from this, please ping me if there is anything we can help with here.

**Comment by joshuawilson** [comment]
@kbsingh do you know how to get access to any of these or how to monitor them to make sure they are up and working?

**Comment by ibuziuk** [comment]
in terms of che server, it is quite easy to obtain the status via `api/system/state` endpoint which is not secured by keycloak. However, probably it would be better to use `cheState` [1] endpoint provided by wit (under the hood it calls che-starter which would call `api/system/state` )
 
[1]  https://github.com/fabric8-services/fabric8-wit/blob/master/design/codebases.go#L245

**Comment by joshuawilson** [comment]
@ibuziuk is this something you can do? 
@andrewazores can you help if needed?
cc @catrobson

**Comment by andrewazores** [comment]
@joshuawilson yes, I'll have time for it coming up

**Comment by joshuawilson** [comment]
@catrobson did we agree that we can remove the "status" icon/dropdown completely?

**Comment by catrobson** [comment]
We either need to implement it properly, or remove it.  I'm open to either direction, but we should decide this week!

**Comment by joshuawilson** [comment]
@aslakknutsen @maxandersen @ibuziuk are we using the Jenkins status to know if it is idled? should we keep that?

**Comment by jiekang** [comment]
These status icons have been removed completely. Closing. Feel free to reopen if this issue is still needed!
