### ISSUE TITLE
Intermittent issue - Analytic report is not always generated by a successful pipeline build

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1874]
Seeing this intermittently over the past couple of days. Steps to recreate:
* Create a new quickstart
* After the successful completion of the build pipeline, sometimes, the analytic report is not generated:

![screenshot from 2018-01-12 09-00-20](https://user-images.githubusercontent.com/642621/34879056-fefcbcce-f779-11e7-8264-de30d663bf34.png)
![screenshot from 2018-01-12 09-00-00](https://user-images.githubusercontent.com/642621/34879057-ff400ec0-f779-11e7-8b0c-ea7fce5e841c.png)

**Comment by ldimaggi** [comment]
It should look like this:

![screenshot from 2018-01-12 10-01-03](https://user-images.githubusercontent.com/642621/34880790-8c5ae622-f77f-11e7-8358-3f8cd205fad7.png)

**Comment by GeorgeActon** [comment]
@sivaavkd please assess

**Comment by arunkumars08** [comment]
@ldimaggi Could you still reproduce the issue? Meaning is it still intermittent?

**Comment by ldimaggi** [comment]
Haven't seen this issue recently - closing.
