### ISSUE TITLE
Fundamental: Browsers Supported by OpenShift.io

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#1879]
details coming; this is mainly a placeholder parent for some other issues.

**Comment by joshuawilson** [comment]
@qodfathr we have this https://github.com/openshiftio/openshift.io/wiki/Supported-Browsers

Are you looking for something else?

**Comment by rkratky** [comment]
Based on the outcome of http://post-office.corp.redhat.com/archives/devtools-leads/2017-November/msg00201.html, shouldn't we update the wiki not to mention incognito/guest mode?

**Comment by qodfathr** [comment]
Closing in favor of #2018
