### ISSUE TITLE
Unresponsive script

### ISSUE THREAD

**Issue by luebken** [openshiftio/openshift.io#188]
Trying to open with Firefox on a Mac I got the following error:

```
Warning: Unresponsive script
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: https://openshift.io/_assets/l…f49acb8aeb061f0c40eb.bundle.js:1
```
<img width="1637" alt="screen shot 2017-06-01 at 11 29 40" src="https://cloud.githubusercontent.com/assets/53055/26673645/ee11faf4-46bd-11e7-83a7-1b7b2f20c2e9.png">

**Comment by maxandersen** [comment]
I don't get unresponsive script - I just don't get it loading at all on Firefox. Very weird.

Works for me in Chrome and Safari which would be the workaround.

Can you tell me if that works for you ?

also, I just used openshift.io - did you try another url ?

**Comment by luebken** [comment]
* opend https://openshift.io/

**Comment by luebken** [comment]
I was able to reproduce it: I opened the pipeline history in a new tab.

<img width="1677" alt="screen shot 2017-06-01 at 14 05 04" src="https://cloud.githubusercontent.com/assets/53055/26678986/7f65ccbe-46d3-11e7-9d45-524e27dfd2fa.png">

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1434

**Comment by luebken** [comment]
Ack. I'm subscribed to the other one. So fine with closing this one.
