### ISSUE TITLE
Use API token for fetching lib io data

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1883]
# Description

We want to start using API token for fetching lib io data. @msrb has the token, ping him :)

**Comment by jpopelka** [comment]
Currently we web scrape the following info from https://libraries.io:

- dependent repositories
  - count (of all)
  - list of top dependent repositories
- dependent projects
  - count
- releases
  - latest release
  - recent releases
  - count (of all)

We're able to get the following via API:
- releases
  - latest
    - `# curl -s https://libraries.io/api/npm/serve-static?api_key=$tk | jq '.latest_stable_release'`
  - recent
    - `# curl -s https://libraries.io/api/npm/serve-static?api_key=$tk | jq '.versions'`
  - count
    - `# curl -s https://libraries.io/api/npm/serve-static?api_key=$tk | jq '.versions | length'`

But I haven't found any reasonable way how to use the API to obtain these:
- dependent repositories
  - count of all dependent repositories
    - [dependent_repositories](https://libraries.io/api#project-dependent-repositories) endpoint returns a list of them, but it's paged and there's no `count`, so we'd need to get through all the pages to get the number - and that'd take incredibly long time
  - top dependent repos
    - API has no equivalent of [top_dependent_repos page](https://libraries.io/npm/serve-static/top_dependent_repos) (where we scrape it from), so (as above) we'd need to get through all the [dependent_repositories](https://libraries.io/api#project-dependent-repositories) pages to get them and sort them
- dependent projects
  - count
    - [dependents](https://libraries.io/api#project-dependents) returns a list of them, but it's paged and there's no `count`, so we'd need to get through all the pages to get the number - and that'd take incredibly long time

So the question is whether we want to use the API only for some and keep web scraping the others ?
For me personally, the answer is no, as it'd just bring more complexity to the code with no added benefits.

**Comment by joshuawilson** [comment]
Do we have permission to use their data?

**Comment by jpopelka** [comment]
> Do we have permission to use their data?

@GeorgeActon ^

**Comment by jpopelka** [comment]
https://github.com/librariesio/libraries.io/issues/1935

**Comment by GeorgeActon** [comment]
@joshuawilson We have permission from Libraries.io to use the information. This was agreed in a business to business meeting at the same time that we negotiated a higher API rate.

**Comment by joshuawilson** [comment]
great, thanks for the confirmation

**Comment by jpopelka** [comment]
Deployed to production with https://github.com/openshiftio/saas-analytics/pull/238 and https://github.com/openshiftio/saas-analytics/pull/238

Can be closed.
