### ISSUE TITLE
After clear filters on my spaces page, the spaces no long sort alphanumeritically

### ISSUE THREAD

**Issue by liangxia** [openshiftio/openshift.io#1884]
1. Go to my spaces page, sort spaces.
2. Type something to search spaces.
![screenshot from 2018-01-15 19-47-22](https://user-images.githubusercontent.com/4716987/34941690-c7e76384-fa2f-11e7-895f-839e7724dec8.png)

3. Clear the filter, and check the spaces again.  The spaces no long sort in order.
![screenshot from 2018-01-15 19-47-58](https://user-images.githubusercontent.com/4716987/34941694-cd1597ae-fa2f-11e7-8e59-a0ff80351585.png)

**Comment by chrislessard** [comment]
A fix has been opened here https://github.com/fabric8-ui/fabric8-ui/pull/2392

**Comment by jiekang** [comment]
This issue likely occurs in most of the toolbar-like components that have the ability to filter and sort. The fix proposed should be able to apply to all of them.
