### ISSUE TITLE
Duplicate scroll bars on profile page.

### ISSUE THREAD

**Issue by liangxia** [openshiftio/openshift.io#1885]
Create several spaces, some of them with long names. Check profile page.
![screenshot from 2018-01-15 20-12-07](https://user-images.githubusercontent.com/4716987/34941962-d3c01d1c-fa30-11e7-9376-9686e67822f8.png)

**Comment by chrislessard** [comment]
I dealt with something similar with our infinite scroll module in the "view all spaces" section, so I'll take a look. I suspect it might just be an issue with how divs are being used.

**Comment by chrislessard** [comment]
A PR w/ a fix has just been opened here : https://github.com/fabric8-ui/fabric8-ui/pull/2391
