### ISSUE TITLE
Closing the green experimental bar by selecting 'Got it' results in the display of a weird looking gray colour bar on the right side

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#1887]
Closing the green experimental bar by selecting Got it, results in the display of a weird looking gray colour bar on the right side of the Planner.

![experimental accept issue](https://user-images.githubusercontent.com/28748448/34942289-21f5c914-fa1d-11e7-845c-552bcf7722ff.png)

**Comment by qodfathr** [comment]
The new feature flag capabilities and UI will probably render this issue obsolete because this functionality will be replaced with new functionality.

**Comment by mindreeper2420** [comment]
@SMahil There is a class in `_planner-layout.less`, that I believe is part of the issue. `.f8-wi-container>main` has the property `overflow: hidden`. When this is removed, the Planner UI fills up the full width of the UI. I would start there, and then look at all of the absolute and fixed positioning. Those are also causing issues.

@qodfathr The HTML/CSS for the Feature Flag work uses the same code from the Experimental Features component, so nothing will change on the UI. When you visit either the Applications, Environments or Deployments sections, those pages do not have bars on the left/right of the content when clicking 'Got It'.

**Comment by ppitonak** [comment]
Looks OK for me.

**Comment by rgarg1** [comment]
With the introduction of feature flags, I can't reproduce this issue anymore.

**Comment by rgarg1** [comment]
Closing.
