### ISSUE TITLE
Pipelines view plank

### ISSUE THREAD

**Issue by luebken** [openshiftio/openshift.io#189]
- I've switched to the pipelines tab.
- Started a new pipeline via the kebab menu.
- As nothing happend I refreshed the page. 
- The resulting page was blank.

<img width="1348" alt="screen shot 2017-06-02 at 16 03 28" src="https://cloud.githubusercontent.com/assets/53055/26729419/dc4a9a1a-47ad-11e7-9f31-6e33cdbc2890.png">

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1436
