### ISSUE TITLE
Wrong icon position of popup

### ISSUE THREAD

**Issue by Katka92** [openshiftio/openshift.io#1890]
Speaking about the popups showed in openshift.io in right top corner - the text is covered by icon. This popups are appearing after creating a workspace, copying token, creating space. I've tried it in Chrome Version 63.0.3239.132 (Official Build) (64-bit) and in incognito mode too. 

![screenshot from 2018-01-16 10-37-46_2](https://user-images.githubusercontent.com/29278800/34982315-5d24cad4-faaa-11e7-911f-da07799fc66d.png)
![screenshot from 2018-01-16 10-43-13_2](https://user-images.githubusercontent.com/29278800/34982319-5f79c0b4-faaa-11e7-9db9-837fe04f3ab5.png)

**Comment by joshuawilson** [comment]
duplicates #1854
