### ISSUE TITLE
Tweak chart height of Deployments card charts

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1893]
The chart height of the Deployments card charts should be reduced to more closely follow the UX design [1].

Adding this to make sure the task isn't forgotten.

[1] https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/260764293

**Comment by aptmac** [comment]
Fixed in https://github.com/fabric8-ui/fabric8-ui/pull/2408
