### ISSUE TITLE
[3] Gradle support in f8a-worker

### ISSUE THREAD

**Issue by pkajaba** [openshiftio/openshift.io#1897]
# User story
In this user story https://github.com/openshiftio/openshift.io/issues/689, gradle support was implemented into Mercator-go. It means that Mercator is able to process Gradle manifest files*. f8a-core should take Mercator's output and parse necessary information (dependencies, version, package, etc.).

# Acceptance criteria
- f8a-worker is able to parse Mercator's output for gradle ecosystem
- f8a-worker's code is running in production.

*to some extent. It's just statically parsing gradle.build file, so if there is some logic (parametrizing versions, including other gradle build files) output might be malformed.

**Comment by sivaavkd** [comment]
@pkajaba - are we targeting this for the current sprint ? 
cc @msrb

**Comment by msrb** [comment]
@sivaavkd that is correct, this is for current sprint.

**Comment by msrb** [comment]
@pkajaba could you please provide time estimate on this one?

**Comment by krishnapaparaju** [comment]
@pkajaba any progress on this ?

**Comment by msrb** [comment]
@krishnapaparaju Pavel spent significant portion of his time on SEV-2 issue: https://github.com/openshiftio/openshift.io/issues/2218, which was tougher than anyone expected. This will need to be implemented in 147.

**Comment by sivaavkd** [comment]
@pkajaba - please target this for the current sprint cc @msrb

**Comment by sivaavkd** [comment]
@pkajaba @msrb This is spilling over to 148, moving it again.

**Comment by msrb** [comment]
PR merged, thanks Pavel :wink:
