### ISSUE TITLE
Unable to login into openshift.io (affecting prod AND prod-preview)

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#1898]
After filling credentials at developers.redhat.com, user is redirected to this page:
![image](https://user-images.githubusercontent.com/1215011/35042787-397a06e0-fb8a-11e7-96dd-dd427bbb3e08.png)

**Comment by pbergene** [comment]
Upstream issue with developer.redhat.com -> reaching out.

**Comment by pbergene** [comment]
I can log in now, their status has gone from red -> yellow.

**Comment by pbergene** [comment]
Anyone still having issues? If not I'll close.

**Comment by pbergene** [comment]
Now status is green, closing.
