### ISSUE TITLE
Errors on Centos CI - Blocking Jenkins jobs from running

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1901]
Multiple users are seeing this today:
```
Starting new HTTP connection (1): admin.ci.centos.org
Resetting dropped connection: admin.ci.centos.org
The requested operation failed as no inventory is available.
'cico node get' failed, trying again in 60s (1/5)
Starting new HTTP connection (1): admin.ci.centos.org
```

**Comment by ldimaggi** [comment]
Issue also emailed to:  ci-users@centos.org

**Comment by kbsingh** [comment]
ci centos should be back - can you confirm

**Comment by rhopp** [comment]
It's fine here.

**Comment by pbergene** [comment]
Spoke to people working on cico, they were back to about 80% an hour ago - aware of the problem and addressing it.  Have had reports of succeeding builds.

**Comment by ldimaggi** [comment]
Issue found/encountered by EE tests.
