### ISSUE TITLE
Jenkins moving out from GKE

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#1902]
We are currently running our own build cluster for an internal project on GKE, we would like to move this to the internal infrastructure.

This story would involve these steps : 

* Investigate what do we need to move, what are the namespaces, what are the artifacts and jobs [https://github.com/openshiftio/openshift.io/issues/2246]
* Investigate where we want to move it on which cluster, and what capacity we would need for there to handle our current stream and the growth.
* Document the perimeters of responsibility, what are the part the SD team would take care and which part is taking care for Build team.
* Change the URL from http://jenkins.cd.test.fabric8.io to a better URL (i.e: no test in there). There is implications in there like oauth authorizations that would need to be changed.
* Implement backup, automation (Ansible), and versioning the current templates on a (internal) GIT repo.

**Comment by kbsingh** [comment]
do we have a good plan in place here ?

**Comment by jaseemabid** [comment]
@kbsingh, @chmouel is on PTO this week, so you might have to wait until he is back to get an update on this.

**Comment by ppitonak** [comment]
@chmouel, what do you mean by "internal infrastructure"? Behind the firewall or public but owned by Red Hat?

**Comment by kbsingh** [comment]
all the infra is public, no plan to move any of it

**Comment by jaseemabid** [comment]
@ppitonak jenkins.cd.test.fabric8.io runs on GKE infra and is not managed by the SD team. This is about build team not having to separately manage any infrastructure.

**Comment by chmouel** [comment]
cprrect, I meant managed by SD team instead of GKE when I meant "internal infra"

**Comment by mmclanerh** [comment]
@pbergene did this all get moved..?

**Comment by jaseemabid** [comment]
@mmclanerh Not yet. @rupalibehera is working on it.

**Comment by rupalibehera** [comment]
Duplicate https://github.com/fabric8io/fabric8-build-team/issues/19 and it is moved to planner
