### ISSUE TITLE
Jenkins monitoring

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#1903]
Monitoring the fabric8 Jenkins instance. The Jenkins master gets rebooted often, perhaps under load. Before we make any assumptions, we need to set up some kind of monitoring for this instance so that we can take an educated call on what needs to be done.

This issue is being worked on here https://github.com/fabric8io/fabric8-build-team/issues/4

**Comment by qodfathr** [comment]
See also #2110 Openshift.io DSaaS Monitoring/Metrics
