### ISSUE TITLE
Remove tenant code that is specific to Kubernetes

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#1906]
The tenant service has blocks of code that are only executed if the platform is Kubernetes and not OpenShift, as defined by an environment variable: https://github.com/fabric8-services/fabric8-tenant/blob/master/openshift/init_tenant.go#L616

Unless we want to keep supporting k8s, we could remove these code blocks in order to simplify the maintenance and future work.

**Comment by qodfathr** [comment]
@bmicklea this likely needs guidance as to our overall upstream story. Historically, fabric8 has been tooling for k8s. Are we going to continue with that principle for the DSaaS fabric8 work? Is supporting OpenShift Origin as an alternative a consideration? And how would we go about putting the processes in place to ensure that the upstream on k8s/Origin/whatever works properly?

That's clearly a larger discussion than dictated by this particular issue, but this issue (and others that I assume will be created for similar reasons) will need official guidance. Perhaps a topic for the f2f?

**Comment by bmicklea** [comment]
+1 on dealing with it in the F2F. My preference would be to keep this open to k8s in the upstream but we may need the community to help...

**Comment by qodfathr** [comment]
@RanjithRV can you please ensure that this is specifically called out on the f2f agenda somewhere so we remember to address it? Thanks!

**Comment by aslakknutsen** [comment]
If we want to keep k8 support we need to setup k8 testing as part of the normal flow. Else we're just coding in the dark and hope it works.
