### ISSUE TITLE
Consistently order environments in Deployments page

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1907]
Users currently always have stage, and run environments. The order these appear should probably always be the same.

**Comment by jiekang** [comment]
@catrobson Do you have a suggestion on what the order should be? Or if it should always be ordered the same, even? My guess on an order would be Test, Run and Stage.

This is referring to the order of environments in [1] where it shows Stage and Run from left to right. The mock doesn't include the Test environment.

[1] https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/260764292

**Comment by jiekang** [comment]
Oh, after further research the Test environment

**Comment by jiekang** [comment]
Okay nevermind... some more digging reveals there is a 'test' environment and it's {spaceName} project on OSO.

@catrobson The question is actually valid. Sorry for the confusion and multiple pings;;

**Comment by jiekang** [comment]
E.g:

run 	name: Run
		namespace: jkang-run
		order: 2
stage 	name: Stage
		namespace: jkang-stage
		order: 1
test 	name: Test
		namespace: jkang
		order: 0


This suggests the order: Test -> Stage -> Run

**Comment by jiekang** [comment]
Though the Test project exists, is there any way in the UI to deploy an application to it? I'm not sure what it's used for. The pipelines have rollout to stage and rollout to run...

@joshuawilson Do you know?

**Comment by joshuawilson** [comment]
you need to talk to @ldimaggi

**Comment by qodfathr** [comment]
There used to be a Test environment, but we removed it ~7 months ago.

For now, the ordering should be Stage then Run.

In the future, users will be able to (1) define their own environments and (2) order them however they want.

**Comment by ldimaggi** [comment]
Sorry - I don't have a path to the Test deployment platform either.

**Comment by joshuawilson** [comment]
please ignore my comment, I had misread

**Comment by jiekang** [comment]
Closing as fix has been merged.
