### ISSUE TITLE
Pipeline doesn't start

### ISSUE THREAD

**Issue by stevengutz** [openshiftio/openshift.io#1908]
Following the basic OSIO tutorial, when I create a space the build never starts.  Spins forever but nothing is ever built

![image](https://user-images.githubusercontent.com/35299711/35062388-292771da-fb92-11e7-9d21-f12d59f6aafe.png)

**Comment by joshuawilson** [comment]
This appears to have been an issue with the permissions on OSO being reset when an update occurred. This should be fixed now. Can we close it?

**Comment by stevengutz** [comment]
I don’t think there’s an actual bug.  I still can run my example ConfigMap example due to some other permission issue but it’s probably not a code issue

Steve Gütz
sgutz@redhat.com

**Comment by joshuawilson** [comment]
Can we close this?

**Comment by stevengutz** [comment]
Yes from my perspective

Steve Gütz
sgutz@redhat.com
