### ISSUE TITLE
Smaller screen size disrupts the layout of Environments on Deployments Page

### ISSUE THREAD

**Issue by aptmac** [openshiftio/openshift.io#1909]
When resizing the browser horizontally (this happens to me if I make the window half the width of my monitor, for example) the "Environments" components on the Deployments page re-position themselves in an unintended way.

Examples:

This is what the deployments page looks like at full screen, note that the "vertx-hello" cards are under the Test and Run environments.
![full-size](https://user-images.githubusercontent.com/10425301/35068557-65717506-fba5-11e7-834c-559bf698120b.png)

This is what the page looks like when the screen size is shortened horizontally; the Run environment header gets shifted over and it's card is positioned directly beside the "Test" environment's card.
![small-size](https://user-images.githubusercontent.com/10425301/35068568-69d00720-fba5-11e7-96da-7f5085782098.png)

## Parent
#1658 UI: Show deployment details

**Comment by joshuawilson** [comment]
@aptmac please talk to @mindreeper2420 about responsive design. He has been implementing it through out the UI.

**Comment by aptmac** [comment]
Okay. Just so it's written out somewhere, I did a bit of shallow digging and this behaviour is a result of hitting the "small" screen size. Currently, the components in question are using a 'col-sm-4' and there are four columns on the page which results in a bit of run-off if the screen reaches this size. Using a 'col-sm-3' for the components maintains the layout, but the other components weren't designed with this intended and would need tweaks.

Here's an example with a quick modification of sm-col-3 on the row-cards-pf and deployment cards: 
![sm-col-3](https://user-images.githubusercontent.com/10425301/35107112-1953a72c-fc3e-11e7-901f-66cfc1dbad5e.png)

**Comment by jiekang** [comment]
@aptmac Right, I suppose col-sm-4 came from the assumption there would only be 3 columns. In the current production this actually holds true, the 'Test' environment shouldn't exist, so it should be okay to keep a 3 column design.

However, in the future the number of environments isn't fixed so we will need to consider how to future-proof it against this. Horizontal scrolling could be applied I suppose, but I think this may be something we ask the UX team about.

**Comment by mindreeper2420** [comment]
As it stands today, with it only being a three column layout, I have no problem continuing to use the `col-sm-4` classes. The page was designed with this 'fixed' methodology in mind, so it falls in line with that.

As far as the issues when the small screen is hit, the product is not currently 100% designed to handle all screen sizes. In some instances, it does not make sense to configure screens for what Bootstrap considers 'mobile', and this is most likely one of them. If the desire of PM is to have this work on small screens, then the design would need to be revisited.

Going forward, there should be a story created to address screens such as this on smaller resolutions. There is a story for investigating rendering on smaller screens (https://github.com/openshiftio/openshift.io/issues/1443), so I will add this issue to that list.

**Comment by mindreeper2420** [comment]
@aptmac @jiekang @joshuawilson is this still an issue or has it been resolved through other work on the Deployments page?

**Comment by aptmac** [comment]
IMO it's still an issue, but perhaps not exclusive to the deployments page like the issue was originally written for. There are oddities that occur at various screen sizes, especially when viewing small screens - but this is also website-wide too. Perhaps it'd be better to capture these individual issues in a larger tracker issue.

**Comment by jiekang** [comment]
Yeah to confirm, this is definitely still an issue for the Deployments page. The UX probably needs a separate design for smaller screen sizes. A lot of information could stand to be compacted to fit the same information on a smaller screen size.

**Comment by mindreeper2420** [comment]
After some thought, this is one of the areas of openshift.io that I'd like to see have a minimal view on mobile, with a message displayed that it is best used on a desktop (or tablet) display. We will soon be at the point where using openshift.io will just be a bad idea for a multitude of screens, and this is the start of that.

@joshuawilson @openshiftio/uxd-team what do y'all think of an approach as described above?

**Comment by joshuawilson** [comment]
I'm fine with telling the user that the screen is better on a desktop but I still want to see it the information and have it laid out so that the columns makes sense. Even if that means horizontal scrolling. 

When I'm on a mobile device I almost never have a laptop available to switch to. So switching isn't usually an option.
