### ISSUE TITLE
Pipeline(s) not shown after creation over 'Add to Space'

### ISSUE THREAD

**Issue by pkettman** [openshiftio/openshift.io#191]
Steps:
Created a new project/codebase over 'Add to Space' with a selected pipeline
The pipeline is not available in OSIO Pipelines list

Reason:
The OSIO codebase was not linked to an expected default namespace pkettman, but to namespace pke-test1, which I had created previously while I testing the OSO.

https://gist.github.com/pkettman/b722228ae7bb67f282a7d1cc93d03711

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1445

**Comment by RanjithRV** [comment]
Closing this issue as it is was associated with a closed ticket referenced below #https://github.com/openshiftio/openshift.io/issues/906

Final comment on 906 by Alexey 
"I think we can close this issue. This particular problem with this user was manually fixed. The general solution will be addressed as part of our multi cluster support effort - #948 (comment)"
--
