### ISSUE TITLE
GitHub link displays over quickstart summary info

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#1910]
When creating a quickstart project, the final summary screen of the wizard is supposed to display the link to the codebase in git. This text used to look correct (elipsis for the remainder of the link) as of yesterday:

![vertx_final](https://user-images.githubusercontent.com/926572/35080421-2f9ad940-fc59-11e7-9162-2cf526e06208.png)

Now the text is overlapping the summary information:
![text](https://user-images.githubusercontent.com/926572/35080437-43edbe76-fc59-11e7-92ce-9f7edc52ca5c.png)

**Comment by joshuawilson** [comment]
duplicates #1175
