### ISSUE TITLE
Long space name cross boarder.

### ISSUE THREAD

**Issue by liangxia** [openshiftio/openshift.io#1911]
![screenshot from 2018-01-18 14-58-35](https://user-images.githubusercontent.com/4716987/35084726-550df868-fc60-11e7-878f-c42c6343b3a6.png)

**Comment by joshuawilson** [comment]
@michaelkleinhenz can you add this to list of UI fixes that we need. This might just be taken care of in the redesign of the navigation. It still needs to be handled there.

**Comment by mindreeper2420** [comment]
@joshuawilson I believe this can be closed, unless it has not been pushed to prod yet.
