### ISSUE TITLE
In Codespace page - icon is mis-aligned

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1916]
![screenshot from 2018-01-18 08-24-31](https://user-images.githubusercontent.com/642621/35100293-55cc42c8-fc29-11e7-92e8-86bdb5582f60.png)

![screenshot from 2018-01-18 08-24-46](https://user-images.githubusercontent.com/642621/35100294-55dc84bc-fc29-11e7-9f49-6cd017c35905.png)

**Comment by joshuawilson** [comment]
duplicates #1867
