### ISSUE TITLE
Analyze tab (dashboard) does not display work items created in planner

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#1918]
I created a fresh space, after resetting environment. Added a few work items using the 'Quick Add', I can see them in the Planner Backlog view. However the work items are not seen in the Analyze tab, My Work Items section.
Refreshing the screen has no effect.

**Comment by Preeticp** [comment]
Also #778 needs to be revisited, I faced the same issue today and have added my observations on the same here: https://github.com/openshiftio/openshift.io/issues/778#issuecomment-356608229

**Comment by aslakknutsen** [comment]
@Preeticp Did you assign the WorkItems to your self?

**Comment by Preeticp** [comment]
Ah no @aslakknutsen that explains it. I will close this issue.
