### ISSUE TITLE
Vert-X ConfigMap QuickStart fails with "Unable to read the configuration"

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1919]
* Use wizard to create a new Vert-X ConfigMap QucikStart
* Wait until pipeline is done
* Check app in either Stage or Run
* Input message: Response fails with "Unable to read the configuration"

The App log 
```
Failure executing: GET at: https://xxxxx/api/v1/namespaces/xxx-stage/configmaps/app-config. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked.
```

There are no attempts to deploy a config map of that name at all in the Jenkins log.

The Config Map does not exist.

**Comment by gastaldi** [comment]
Because this deployment is performed separately from the original launcher code, I decided to remove the booster from the list and add it back after we refactor it to use the same code.
