### ISSUE TITLE
Can't remove a codebase

### ISSUE THREAD

**Issue by pkettman** [openshiftio/openshift.io#192]
The codebases can't be removed over the OSIO GUI. When I clean them on OS over its concole, the OSIO GUI looks strange, see the picture.
![obrazek](https://cloud.githubusercontent.com/assets/26871874/26788622/235fabb8-4a0e-11e7-9a1a-9b933852477b.png)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1446
