### ISSUE TITLE
UI Navigation vanishes on certain UI exceptions

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1921]
* Go to https://openshift.io/openshiftio/openshiftio
* Go to Create
* Go to Environments
* Press top right menu link to Profile

WebConsole reports:

```
(url: '/aslak', error: TypeError: Cannot read property 'attributes' of null)
```

![screenshot from 2018-01-18 17-08-54](https://user-images.githubusercontent.com/132158/35107852-4a78927a-fc72-11e7-82ca-c0c408344746.png)

**Comment by joshuawilson** [comment]
This is related to an error in an observable subscribing to the Context and not being handled, breaking everything else.

**Comment by joshuawilson** [comment]
This is related or even possibly caused by #1928

**Comment by corinnekrych** [comment]
Fix with https://github.com/openshiftio/openshift.io/issues/1370
