### ISSUE TITLE
"Opt-in to Experimental Features" button does nothing

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1922]
Pressing the button does seemingly nothing. From the web console one can see the Navigation is started but Canceled for an unknown reason.

"Router Event: NavigationCancel "

![screenshot from 2018-01-18 17-11-21](https://user-images.githubusercontent.com/132158/35107969-9f7497b0-fc72-11e7-852e-47a887ace60d.png)

**Comment by joshuawilson** [comment]
I'm not sure this has anything to do with the Feature Flags. I think it has to do with how an error is not being handled else where in the observable for the Context. It breaks routing. That is just my first thought, could be something else.

**Comment by joshuawilson** [comment]
This is related or even possibly caused by #1928

**Comment by corinnekrych** [comment]
This has been fixed part of https://github.com/openshiftio/openshift.io/issues/1370
