### ISSUE TITLE
Leaking Query Parameters between component/pages

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1923]
* Go to https://openshift.io/openshiftio/openshiftio
* Go to Plan
* See URL change to ../plan?q=(space:020f...
* Go to Create
* See URL change to ./create?q=(space

**Comment by joshuawilson** [comment]
cc @michaelkleinhenz @nimishamukherjee

**Comment by nimishamukherjee** [comment]
@joshuawilson based on the guided work item hierarchy, planner always needs to have a query.
The default will be space: space-id AND $WITGROUP: group type name
We are setting this only within planner. 
Not sure how it gets applied to the other tabs.
Need to look in to this.

**Comment by jiekang** [comment]
Some notes on behavior:

Looking at Console logs, there are two separate Router event chains when visiting the Planner tab. One for the initial route to the Planner tab, and another routing to the Planner tab with the query parameters set.

When navigating away from the Planner tab to Analyze or Create under a Space, this second Routing event chain persists. There is an initial route to the target tab, e.g. Analyze or Create, followed by the second routing chain to the same tab but with the query parameters.

Routing to pages external from a Space (for example Home, Profile, List of Spaces), does not have this second routing chain. The chain also does not persist when routing to sub tabs of Create. The second routing chain does persist when navigating to Analyze or Create of another Space.

**Comment by nimishamukherjee** [comment]
Fixed with ngrx.
@aslakknutsen please verify.

**Comment by ppitonak** [comment]
Verified in prod

**Comment by jiekang** [comment]
Seems to be fixed in prod for me. Are there no PRs that can be added here for tracking purposes? Or sub-issues?

**Comment by aslakknutsen** [comment]
@nimishamukherjee Agree with @jiekang, please link in PR
