### ISSUE TITLE
"My Spaces" add Empty sub navigation in certain routes

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1925]
* Go to https://openshift.io/openshiftio/openshiftio/
* Go to Create
* Go to "My Spaces" in top left menu

![screenshot from 2018-01-18 18-07-28](https://user-images.githubusercontent.com/132158/35110995-7906906c-fc7a-11e7-8b5c-de537b1b9ac1.png)

**Comment by joshuawilson** [comment]
@mindreeper2420 @dgutride any idea if this is styles thing or a routing thing?

**Comment by mindreeper2420** [comment]
My guess is routing. There are routing modules that add in the secondary navigation based on the parent element. The styles are applied after the parent element tells the UI to display the child navigation.

**Comment by andrewazores** [comment]
I tried this just now and didn't appear to be able to reproduce it. Is this still valid?

![screenshot_2018-05-24_10-06-47](https://user-images.githubusercontent.com/3787464/40490678-2f723532-5f3a-11e8-8694-78b91d3fc24b.png)

**Comment by joshuawilson** [comment]
I can not reproduce either, closing.
