### ISSUE TITLE
Service breaking in Planner

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#1928]
a service is breaking in planner:
```
getLabels(): Observable<LabelModel[]> {
  return this.spaces.current.switchMap(
    currentSpace => this.http.get(currentSpace.links.self + '/labels')
    ).map (response => {
      return response.json().data as LabelModel[];
  })
}
```
app/services/label.service.ts - currentSpace.links isn't always present and this shouldn't be listened to if disposing

@michaelkleinhenz this was found by @dgutride he can give you more details if needed.

**Comment by joshuawilson** [comment]
This is a SEV1 because it is breaking the main UI navigation.

**Comment by joshuawilson** [comment]
cc @nimishamukherjee

**Comment by dgutride** [comment]
@michaelkleinhenz - this is easy to repro, just click on plan -> board and then navigate to profile, the current space observable is updated and there is no .links present on that object so any function in this service that uses that needs to check for null first.

**Comment by joshuawilson** [comment]
There is a fix coming in RxJS 6. Until we have that, this code has to be fixed.

**Comment by nimishamukherjee** [comment]
Raised PR https://github.com/fabric8-ui/fabric8-planner/pull/2413 to fix this defect.

**Comment by nimishamukherjee** [comment]
The issue auto closed as I used Fixes in my commit message. Waiting for deployment on prod.

**Comment by pbergene** [comment]
@nimishamukherjee What is the status here?

**Comment by rgarg1** [comment]
@joshuawilson The fix seems to be available and working in production. Could you please once verify and close.
