### ISSUE TITLE
Service "12-vertxbasic" is invalid: metadata.name: Invalid value:

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#193]
Projects that begin with numbers fail in the Integration Test phase of the Jenkins build.

https://gist.github.com/burrsutter/f48fac019c3e3b371d9f51b9b212ee91

Workaround is to put the numbers later in the string like "vertx12basic".  The reason I moved the numbers earlier in the string is because the back end of the string is cut-off in the UI.

https://screencast.com/t/ilxblIBSplA

**Comment by jstrachan** [comment]
yeah - the wizard should disallow project names starting with numbers as they are invalid as kubernetes names for things like services

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1454
