### ISSUE TITLE
On prod-preview, attempting to view a build pipeline log traps user in infinite login loop

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1938]
Steps to recreate:
* On prod-preview, create a new quickstart, observe its build pipeline start
* Attempt to "View Log" (jenkins build log):

![screenshot from 2018-01-19 08-40-21](https://user-images.githubusercontent.com/642621/35153917-501510ee-fcf6-11e7-9ba8-98978fec84f1.png)

Then, attempt to login to OpenShift:
![screenshot from 2018-01-19 08-40-36](https://user-images.githubusercontent.com/642621/35153941-60a35e48-fcf6-11e7-8edc-3484739d68e3.png)

Select the 1st button:
![screenshot from 2018-01-19 08-40-53](https://user-images.githubusercontent.com/642621/35153959-6e852a96-fcf6-11e7-8327-7b1acbbfb506.png)

And - observe that the user is returned to the "Login with OpenShift" screen:
![screenshot from 2018-01-19 08-41-10](https://user-images.githubusercontent.com/642621/35153983-7ed78920-fcf6-11e7-9154-abd4a579f547.png)

**Comment by ldimaggi** [comment]
![screenshot from 2018-01-19 08-48-26](https://user-images.githubusercontent.com/642621/35153995-84bbf60a-fcf6-11e7-9794-8a4c2ee209f9.png)

**Comment by ldimaggi** [comment]
Issue found/encountered by EE tests.

**Comment by pbergene** [comment]
@alexeykazakov is this an auth / oauth thing or should be solved elsewhere?

**Comment by alexeykazakov** [comment]
@pbergene no. Jenkins doesn't use the Auth service for login. This is something the build-cd team should look at.

**Comment by ldimaggi** [comment]
Closing as non-reproducible.
