### ISSUE TITLE
Fix deployments donut chart to properly apply c3js css

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1939]
The deployments donut chart is a copy of the OSO Web Console donut chart. This has custom CSS that applies to c3js html elements for a specific look and feel. In Angular, CSS is encapsulated to the component the style is applied on. This leads to the c3js specific CSS not applying as it is a 'child' of the DeploymentsDonutChart component.

This should be fixed via ng-deep or view encapsulation none.

**Comment by aptmac** [comment]
Fixed in PR: https://github.com/fabric8-ui/fabric8-ui/pull/2442
