### ISSUE TITLE
Unable to visit Profile page from Environments

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1940]
There is a router navigation error when trying to visit the Profile page from the Create -> Environments page.

e.g.
```
patternfly-additions.min.css:1 NavigationError(id: 6, url: '/jkang@redhat.com/_update', error: TypeError: Cannot read property 'attributes' of null)
```

This breaks the entire application

**Comment by jiekang** [comment]
After further investigation the suggested problem isn't correct. The spaces object should be null when visiting the Profile page. I'm updating the issue to define the issue only so as not to lead people astray.

**Comment by jiekang** [comment]
It looks like some component being loaded when visiting the Environments page is not able to handle a null object. It's highly likely it's an attempt to use `space.attributes` when `space` is set to null when routing to the Profile page, with the access attempt occurring after it's set to null.

I suppose the priority of a fix depends on the remaining lifetime of this page. @joshuawilson Thoughts?

**Comment by joshuawilson** [comment]
we are not removing the page in the next few days, so this will need to be fixed

**Comment by jiekang** [comment]
Closing as the proposed fix has been merged. Tested navigation path of Environments -> Profile works on production at time of writing.
