### ISSUE TITLE
Testing on production

### ISSUE THREAD

**Issue by bartoszmajsak** [openshiftio/openshift.io#1943]
As a developer, I want to test my service on production without affecting currently deployed versions and users so I can gain more confidence when shipping new feature.

## Related stories

- [Spikes for testing in production](https://github.com/arquillian/arquillian-organization/issues/16)

## Parent Scenario
#2169 Development teams desire to adopt best practices

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/1983
