### ISSUE TITLE
My Spaces UI is very hard to use on large monitor

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#1944]
![image](https://user-images.githubusercontent.com/16322190/35185282-fb1dbae8-fdcf-11e7-9661-8f5ef062faee.png)
On my 4K monitor, running my browser full-screen, the kabob menu is extremely far away from the Space names. Also, there is no visual feedback of which row I am hovering over. As such, we I open the kabob menu to delete a space, I have to stop myself because I'm no longer sure if I opened the menu for the Space I really want to delete.

**Comment by joshuawilson** [comment]
Looks like we need to be responsive on large and small screens. 
cc @mindreeper2420

**Comment by mindreeper2420** [comment]
At this time, large screens are anything great than or equal to 1200px wide. As such, the standard 1920x1080 screens are about as large as are supported by default on the current frameworks. For resolutions above that (especially 3840x2160 or 7680x4320), we will need a complete custom set of queries and add-ons.

For reference, these are the supported media queries:
```
/* Extra small devices (phones, less than 768px) */
/* No media query since this is the default in Bootstrap */

/* Small devices (tablets, 768px and up) */
@media (min-width: @screen-sm-min) { ... }

/* Medium devices (desktops, 992px and up) */
@media (min-width: @screen-md-min) { ... }

/* Large devices (large desktops, 1200px and up) */
@media (min-width: @screen-lg-min) { ... }
```

**Comment by joshuawilson** [comment]
What will it take to add custom media queries for the large screens?

**Comment by qodfathr** [comment]
What about highlighting the row via some form of `hover`? That would help a lot...

**Comment by christianvogt** [comment]
Closing as hover treatment is present to address this issue.
Responsive behaviour both small and large screens hasn't been designed and is a larger design task.
