### ISSUE TITLE
"View last build" menu option on a pipeline brings user to a generally useless screen

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#1945]
This:
![image](https://user-images.githubusercontent.com/642621/30660599-6da14614-9e0f-11e7-9ce8-63225112189d.png)
brings you to this:
![image](https://user-images.githubusercontent.com/16322190/35185515-d0c2a4da-fdd3-11e7-87cc-75e3aa456d4a.png)
I have no idea what the purpose of this screen is.

I'm tempted to recommend that we remove this menu option altogether, unless someone can argue in favor of this screen.

FWIW, getting rid of this screen means we do not have to fix:
#979
#980

**Comment by qodfathr** [comment]
@catrobson thoughts on this?

**Comment by catrobson** [comment]
This is all information that is available in the OpenShift console, which we link to readily from the pipeline.  Agree we should get rid of this additional page for now.

**Comment by qodfathr** [comment]
Fixed via removal
