### ISSUE TITLE
Experimental Features Bar Incorrectly Styled

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#1955]
The Experimental Features bar is incorrectly styled. There is an awkward shadow/border around the 'profile' link and the 'Got It!' button in the bar.

<img width="339" alt="screen shot 2018-01-21 at 8 44 05 pm" src="https://user-images.githubusercontent.com/4032718/35201750-f0b25cd6-feeb-11e7-99c2-0a41073d54af.png">

**Comment by corinnekrych** [comment]
fix in https://github.com/fabric8-ui/fabric8-ui/pull/2428#pullrequestreview-90758574
