### ISSUE TITLE
Opt-In Button Styled Incorrectly

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#1956]
The Opt-In button that appears on the Blank State Features screen in styled incorrectly. The shadows are not to PatternFly specs, there is no hover affect and the onclick styles are incorrect.

<img width="270" alt="screen shot 2018-01-21 at 8 46 35 pm" src="https://user-images.githubusercontent.com/4032718/35201785-3225854e-feec-11e7-94b7-2758cc2ee227.png">

**Comment by corinnekrych** [comment]
fixed in https://github.com/fabric8-ui/fabric8-ui/pull/2428#pullrequestreview-90758574
