### ISSUE TITLE
Git Commit in workspace does not commit, says it did

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#1957]
I'm trying the standard demo workflow:
1. Created a new space, a new HTTP Booster project. So far so good.
2. Created a workspace, made a minor change to the code, committed to git. Got a terminal message that the commit successfully happened:
![hw_commit_successful](https://user-images.githubusercontent.com/926572/35207290-daa3ac9a-ff8d-11e7-9644-d7290cddb98f.png)
3. Checked out pipelines page and no new pipeline build has started, which is odd. Checked Git to confirm commit happened, which should trigger the build, but:
![no_commit](https://user-images.githubusercontent.com/926572/35207317-fbc729ce-ff8d-11e7-9585-78d4b94cb86a.png)
4. I go back to the workspace and think maybe the commit did not go through. Try to commit again and get this, which suggests the commit happened already:
![commit_done](https://user-images.githubusercontent.com/926572/35207346-21b6f54c-ff8e-11e7-903f-3bff11704b0a.png)

Now I'm not sure what went wrong or how to recover from this. The UI suggests that the commit happened but in GitHub, there is no commit after the initial creation one, plus the pipeline build is not triggered.

Can anyone help identify the issue? Worst case I'll reset the environment and try again but in case this is a bug, I'm reporting it (and adding any workarounds other than reset env to docs).

**Comment by ibuziuk** [comment]
@mishaone have you commit & push to github, or just commit in the local repo ?

**Comment by qodfathr** [comment]
@mishaone please take another look at the QuickStart guide. It looks like you missed the Push, as @ibuziuk has suggested. When you git commit, you are committing to the *clone* of your GitHub repo which has been placed into your Che workspace. You need to git push from the Che workspace back to the "upstream" GitHub repository for the pipeline to kick off.

**Comment by mishaone** [comment]
ACK, was missing the push checkbox. Thanks folks, apologies for the brainfart.
