### ISSUE TITLE
deployments: allow migration to alternate servers

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#1968]
# Description
As a user I want to be able to move my app to a different server or tier.

# Acceptance Criteria

- [ ] Be able to have the app deploy to different servers per stage
- [ ] Be able to migrate the app from one server to another one
- [ ] Be able to migrate the app while it is live/running
- [ ] Be able to migrate from free tier to pro and back

**Comment by qodfathr** [comment]
Why was this give label train/heather? I don't see a commitment to this in the H plan.

**Comment by joshuawilson** [comment]
This is phase 2 for Deployments and falls under "in-progress". I consider this story a stretch goal however.

**Comment by maxandersen** [comment]
I don't see these in H and also management of deployments is done via jenkins builds and templates - I'm struggling to see how this fits into deployment UI ?
