### ISSUE TITLE
Space dashboard (Analyze), width of Codebases too narrow, vertical too short

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#197]
https://screencast.com/t/eLrhN87RCJ

My codebase list is too narrow and too short, it should also be sorted by last accessed date descending (most recent up top).

The current UI widget is essentially useless

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1455

**Comment by qodfathr** [comment]
All of this UI has undergone substantial change since June, and associated fabric8-ui issue has been closed. Closing.
