### ISSUE TITLE
applications: app name should stay in box

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#1972]
In the Applications page, if we resize the browser window, the application name doesn't stay in the box:

![name](https://user-images.githubusercontent.com/926572/35256900-f4921592-0041-11e8-9884-6632c2da13c6.png)

**Comment by joshuawilson** [comment]
This page is deprecated and will be removed soon. We are not updating it.

**Comment by joshuawilson** [comment]
It is being replaced by the Deployments page.
