### ISSUE TITLE
New work item Add and Open button does not open details

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#1977]
Use quick-add to create a new work item and click Add and Open button.

![image](https://user-images.githubusercontent.com/16322190/35277274-31cfbfaa-0014-11e8-9737-0eff00b9f8e1.png)

You remain on backlog view; work item details are not opened. The item is correctly added.

![image](https://user-images.githubusercontent.com/16322190/35277289-456c7be8-0014-11e8-8d25-02d8774770c3.png)

**Comment by michaelkleinhenz** [comment]
Scheduled for Sprint #144.

**Comment by nimishamukherjee** [comment]
PR for fixing this issue - https://github.com/fabric8-ui/fabric8-planner/pull/2404

**Comment by qodfathr** [comment]
Fixed.
