### ISSUE TITLE
Typo in the Features Opt-In UI in the User profile page

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/openshift.io#1978]
The word *recommended* is spelled as *recommenced*

![screenshot from 2018-01-23 11-39-51](https://user-images.githubusercontent.com/54133/35278806-421b430c-0032-11e8-8ac3-3286e2987c1a.png)

**Comment by xcoulon** [comment]
thanks, @gastaldi !

**Comment by jiekang** [comment]
It's in `update.component.html` of `fabric8-ui`, for what it's worth :)
