### ISSUE TITLE
Menu on iteration hides behind the background

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1979]
![screenshot from 2018-01-23 15-00-17](https://user-images.githubusercontent.com/132158/35279738-3c88f7f6-004e-11e8-9e23-5ed37f7f3e28.png)

![screenshot from 2018-01-23 15-02-14](https://user-images.githubusercontent.com/132158/35279794-6b43134c-004e-11e8-92f0-0a21f93c6ac9.png)

**Comment by qodfathr** [comment]
Fixed
