### ISSUE TITLE
Create, codebases UI should be sorted, most recent

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#198]
https://screencast.com/t/lukyPpyId

Unclear what the current sorting criteria are
The drop-down list box and the ascending/descending UI do nothing
https://screencast.com/t/tLNChNkpVmB

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1456

**Comment by qodfathr** [comment]
Associated issue has been closed. Closing.
