### ISSUE TITLE
Creator avatar in Planner is sometimes missing

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1981]
All WorkItems created by the same user.

Unsure why, but the img elements are different:

* wrong avatar
```html
<img onerror="this.src='https://avatars0.githubusercontent.com/u/563119?v=3&amp;s=23'" placement="left" src="https://avatars0.githubusercontent.com/u/563119?v=3&amp;s=23">
```

* correct avatar
```html
<img onerror="this.src='https://avatars0.githubusercontent.com/u/563119?v=3&amp;s=23'" placement="left" src="https://www.gravatar.com/avatar/f51b467f9ab6f18a90790b151fbedf1f.jpg&amp;s=23">
```

![screenshot from 2018-01-23 15-08-32](https://user-images.githubusercontent.com/132158/35280130-87a7781a-004f-11e8-9ea6-b15dba2bfcc6.png)

**Comment by michaelkleinhenz** [comment]
Maybe a caching issue? Will look at that.

**Comment by debloper** [comment]
Can't reproduce this.
Can we verify if this still happens, else we should close it.

**Comment by aslakknutsen** [comment]
Can't reproduce atm
