### ISSUE TITLE
Saved Status changes are not reflected in Table view

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1984]
![screenshot from 2018-01-23 15-33-22](https://user-images.githubusercontent.com/132158/35281299-dd3b76d4-0052-11e8-87c2-b9e61d9a9f1b.png)

**Comment by michaelkleinhenz** [comment]
Works for me, please check again. We had some hiccups on prod in the last minutes.

**Comment by qodfathr** [comment]
Working for me on prod.

**Comment by aslakknutsen** [comment]
Can't reproduce now. Works in both Prod and Preview. Closing.

**Comment by nimishamukherjee** [comment]
@michaelkleinhenz @aslakknutsen I see this issue for child work items. 
The state gets updated for top level work items but not for child work items.

**Comment by rgarg1** [comment]
@nimishamukherjee @michaelkleinhenz @aslakknutsen I could see the issue with statuses of child workitems. This is a refresh issue, and the updated status is displayed on page refresh.

**Comment by michaelkleinhenz** [comment]
@sudsen can you look into this, seems like a grid issue to me.

**Comment by sanbornsen** [comment]
I am on it.

**Comment by nimishamukherjee** [comment]
@aslakknutsen can you check on prod. This has been fixed with ngrx.

**Comment by aslakknutsen** [comment]
Seems to be working. Closing.
