### ISSUE TITLE
WorkItemType filter on Iteration only show Types on direct Iteration, not children

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1985]
* All Tasks are children of Feature
* All Work Items are in the same iteration hierarchy

When filtered on Work Item Type, only Tasks that are directly on the iteration in question are shown.

https://prod-preview.openshift.io/aslak/test669/plan?q=(iteration:a96bcd5d-8e2d-4f39-a285-60322ad1651c%20$AND%20workitemtype:bbf35418-04b6-426c-a60b-7f80beb0b624,26787039-b68f-4e28-8814-c2f93be1ef4e,0a24d3c2-e0a6-4686-8051-ec0ea1915a28)&workitemtype=Task

![screenshot from 2018-01-23 15-49-44](https://user-images.githubusercontent.com/132158/35283086-815f4e30-0057-11e8-8015-36b7249fde35.png)
![screenshot from 2018-01-23 15-53-38](https://user-images.githubusercontent.com/132158/35283080-7d597aa4-0057-11e8-884f-227909c7f111.png)
![screenshot from 2018-01-23 15-50-02](https://user-images.githubusercontent.com/132158/35283081-7d783584-0057-11e8-8ede-73ffcae61427.png)

**Comment by michaelkleinhenz** [comment]
To clarify the problem here: "Task 4" and "Task 5" should be displayed with the parent ("Feature"). @sudsen @kwk can you check whether this is a UI or backend problem?

**Comment by aslakknutsen** [comment]
@michaelkleinhenz I was expecting "Task 1" and "Task 3" to show up as well, but not under the parent since it's of a different type.

**Comment by nimishamukherjee** [comment]
@aslakknutsen the tree behaviour has been updated along with the url query . We now highlight the exact matches.
Task 1 and Task 3 will not show up as they do not match the query which would be an AND of iteration and work item type.
