### ISSUE TITLE
Che: Run Command for Vertx (compile vertx:run)

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#199]
https://screencast.com/t/3xjfAjqZJxR

Che should have an out-of-the-box run command (it has build and test-compile by default).  The run needs to be "compile vertx:run" to properly leverage the vert.x hot redeploy.   I then use Terminal to curl the endpoint
https://screencast.com/t/Ye7PLsZuwbZd

**Comment by joshuawilson** [comment]
@gorkem this one is for you

**Comment by joshuawilson** [comment]
This issue was moved to redhat-developer/rh-che#95

**Comment by l0rd** [comment]
This has been fixed by https://github.com/redhat-developer/rh-che/issues/216. The fix is included in Che version 1.0.234 or above.
