### ISSUE TITLE
Pressing 'Enter' in 'edit title' field creates newline

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1992]
Expected:

* Enter submits the change

![screenshot from 2018-01-24 02-12-28](https://user-images.githubusercontent.com/132158/35309327-2905c11a-00ac-11e8-92a1-938d8c22e4db.png)

**Comment by divyanshiGupta** [comment]
@aslakknutsen the fix corresponding to this bug is now available in prod. Can you please verify?

**Comment by aslakknutsen** [comment]
@divyanshiGupta Please link to the commit with the change

**Comment by divyanshiGupta** [comment]
@aslakknutsen https://github.com/fabric8-ui/fabric8-planner/commit/4c0984e2e4e0f8e9452a815bd424088eb20aceb7

**Comment by aslakknutsen** [comment]
@divyanshiGupta So it... technically works.. but... The event'ing is wrong. In the current impl you get this behavior:

* Type 'text'
* Press enter
* newline is inserted into the text
* newline is removed from the text
* input is submitted

In the process, the input field/text/size flickers needlessly.

The correct behavior is:

* Type 'text'
* Press enter
* input is submitted

There are a few ways to handle that;

* bind on key.down instead of up

This could cause problems if the user holds the Enter button down as multiple events will get triggered so the 'submit' part would need to keep state if it has been submitted or not...

or

* bind to key.down and key.up

In key.down you cancel the event chain to avoid newline being inserted in the first place, then submit in key up. But the canceling of the chain could cause other issues depending on what other listeners might be triggered on the same element.

**Comment by divyanshiGupta** [comment]
sure @aslakknutsen I will figure out something.

**Comment by divyanshiGupta** [comment]
@aslakknutsen can you please review the changes that I have made? 
PR : https://github.com/fabric8-ui/fabric8-planner/pull/2430
Snapshot : https://fabric8-ui-fabric8-ui-pr-2430-fabric8-planner.badger.fabric8.io

**Comment by aslakknutsen** [comment]
@divyanshiGupta The behavior is saner now.

**Comment by divyanshiGupta** [comment]
@aslakknutsen the changes are available in prod now. If it looks good to you then can you close the issue?
