### ISSUE TITLE
Create iteration should set focus on "Name" input field when opened

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1994]

**Comment by qodfathr** [comment]
Changing to type/bug. type/papercuts is used as a top-level parent for a whole set of related, low priority work. This issue could have been a descendent of a papercut, of course. But now that it got moved to SEV2, that's probably not necessary.

**Comment by nimishamukherjee** [comment]
@aslakknutsen fix on prod. Please check.

**Comment by aslakknutsen** [comment]
@nimishamukherjee General keyboard flow compared to normal forms etc is still behaving odd, but I'll open separate issues.

**Comment by aslakknutsen** [comment]
Focus is lost again in prod.

**Comment by SMahil** [comment]
This issue is one of the tasks of issue number 2628. Sudipta can share the status of this issue

**Comment by joshuawilson** [comment]
This is still an issue.

**Comment by ppitonak** [comment]
@christianvogt why did you close this issue?

**Comment by joshuawilson** [comment]
I think he closed it because the bug was fixed, though it hasn't been pushed to prod yet.
