### ISSUE TITLE
Expanding certain Parent WorkItems cause errors in console

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1996]
Expanding  "Scenario 2" cause error in console
https://openshift.io/aslak/Test666/plan?q=(space:f01a9e4c-4bf8-4609-8d7c-a95930fa209f%20$AND%20$WITGROUP:Scenarios)

```javascript
ERROR TypeError: Cannot read property 'findIndex' of undefined
    at 0.c5d616abcbeed23a35f5.chunk.js:1
    at Array.filter (<anonymous>)
    at 0.c5d616abcbeed23a35f5.chunk.js:1
    at Array.forEach (<anonymous>)
    at SafeSubscriber._next (0.c5d616abcbeed23a35f5.chunk.js:1)
    at SafeSubscriber.__tryOrUnsub (patternfly-additions.min.css:1)
    at SafeSubscriber.next (patternfly-additions.min.css:1)
    at Subscriber._next (patternfly-additions.min.css:1)
    at Subscriber.next (patternfly-additions.min.css:1)
    at ForkJoinSubscriber.notifyComplete (patternfly-additions.min.css:1)
```

![screenshot from 2018-01-24 02-28-58](https://user-images.githubusercontent.com/132158/35309791-6aec952a-00ae-11e8-8774-a21147995d97.png)

**Comment by michaelkleinhenz** [comment]
@aslakknutsen is this a newly created Scenario WI or was it created a while ago?

**Comment by aslakknutsen** [comment]
@michaelkleinhenz 2 days ago. Go to the URL provided in the description. It has all the info and is reproducible every time.

**Comment by nimishamukherjee** [comment]
@aslakknutsen are you still facing this issue?

**Comment by aslakknutsen** [comment]
@nimishamukherjee No, not seeing it anymore. Any attempts to fix it, or just a '5 other changes later' *boom* *magic* gone?

**Comment by nimishamukherjee** [comment]
@aslakknutsen it is the case of "5 other changes later"...

**Comment by michaelkleinhenz** [comment]
Looks like this is fixed. **Magic**.
