### ISSUE TITLE
create workspace sometimes never changes its label

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#200]
After a dozen tests today, I found the Create Workspace "button" does not always switch to Open Workspace after the workspace is created.
http://www.screencast.com/t/wUNyuvKlYXBk

my workaround is to find the Che URL and navigate to the workspace via the Che Dashboard
https://screencast.com/t/PhVMVAfr

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1460

**Comment by burrsutter** [comment]
A recent example of the label not changing
https://screencast.com/t/KlIELQ605G

**Comment by burrsutter** [comment]
Related to https://github.com/fabric8-ui/fabric8-ui/issues/1825

**Comment by bmicklea** [comment]
Closing this as I've no longer seen this issue. @burrsutter please reopen if it reappears or is still happening.
