### ISSUE TITLE
Inconsistent 'User select' between Planner:Assignee and Spaces:Collaborators

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#2000]
![screenshot from 2018-01-24 02-48-34](https://user-images.githubusercontent.com/132158/35310328-2fe92c6a-00b1-11e8-9f94-b9c4b64e9614.png)

![screenshot from 2018-01-24 02-50-00](https://user-images.githubusercontent.com/132158/35310360-4b98fac6-00b1-11e8-8180-d9066222bd10.png)

**Comment by aptmac** [comment]
The collaborators dropdown was updated in https://github.com/fabric8-ui/fabric8-ui/commit/8f493457c2c0b9b8cf7c8c0b6283c1d66466b0f1

It now looks like:
![2018-07-10-125445_612x558_scrot](https://user-images.githubusercontent.com/10425301/42525213-9a1b6842-8440-11e8-9d5e-3149057b6cf4.png)

Is this close enough to the planner one to close this issue?

**Comment by joshuawilson** [comment]
I think it is. If we need any update from here it should be on the Planner. 
I'll close this, please reopen if needed.
