### ISSUE TITLE
Collect requirements for collecting manifest files from GitHub

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#2007]
# Description

We need to collect proper requirements for the job that collects manifest files from GitHub.

- what is the input for the job?
- what is the expected output? (`manifest.json`?)
- who/how/when will consume the results of this job?
- where to store the output?
    - if on S3, what's the expected structure of the bucket?
- do we need to refresh the data?
    - if so, how often?
    - if so, do we override previous results or store the new results elsewhere?
- previously we collected/generated quite a lot of data that were later used to produce the final `manifest.json` (dependency snapshots, etc.), do we need to keep such data, or can we discard it?

**Comment by msrb** [comment]
cc @miteshvp

**Comment by msrb** [comment]
We need to do this first, before we start improving/rewriting the job.

**Comment by msrb** [comment]
We can create more tasks once it's clear what is it we are trying to achieve.

**Comment by msrb** [comment]
Moving to backlog, we didn't need to do any changes to existing code for collecting Wildfly data.

**Comment by miteshvp** [comment]
We get manifest using BigQuery.
