### ISSUE TITLE
Decouple deployment scripts from tests in fabric8-analytics-common

### ISSUE THREAD

**Issue by humaton** [openshiftio/openshift.io#2009]
fabric8-analytics-common repository has become a mess.
We currently have tests, openshift and docker-compose deployments scripts and a couple of other things in it.

I suggest creating a new repository for tests. fabric8-analytics-tests
And use common repo for deployment-related scripts.

**Comment by msrb** [comment]
cc @tisnik

**Comment by msrb** [comment]
@humaton dup? https://github.com/openshiftio/openshift.io/issues/1383

**Comment by jpopelka** [comment]
Deployment scripts are now part of https://github.com/fabric8-analytics/fabric8-analytics-deployment
