### ISSUE TITLE
Che: context assist HTTP 401

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#201]
https://screencast.com/t/549bv3F2

Using the Vert.x Basic template and 
router.
looking at the methods of the Vert.x router - they all pop-up HTTP 401

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1461

**Comment by joshuawilson** [comment]
This issue was moved to redhat-developer/rh-che#94
