### ISSUE TITLE
Expose data from monitored_upstreams table via API

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#2010]
# Description

We store project URLs in `monitored_upstreams` table in RDS. The problem is that there is no easy way how to check what data we have there (no `psql` in prod). Therefore we want to expose the data via API. 

Note OSIO users don't need to know what's in there. This is just for us.

**Comment by jpopelka** [comment]
There's a new [/bookkeeping/upstreams](https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/f8a_jobs/swagger.yaml#L574) endpoint in jobs, which does it.
