### ISSUE TITLE
Stack Report Create Work Item notification pop-up has link which opens in new browser tab

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2014]
1. Open a stack report with a Create Work Item on a suggestion
2. Observe the notification pop-up that a work item has been added to the planner.
3. Click link the the notification
4. Work item details is opened in a new browser tab rather than the current tab

This this the intended behavior?

**Comment by qodfathr** [comment]
@catrobson mainly a question to your team for now. Not sure if this is a bug or not.

**Comment by catrobson** [comment]
This is as designed.  As specified by PatternFly for toast notifications:

"Clicking on an action should either help the user achieve the goal automatically, or open up a modal window or a different page. "

In this case, clicking the link can't perform an immediate action (restart server as an example), it is just bringing the user to information, therefore we open it in a different page as to not interrupt any mid-stream activities that the user might be performing on their current page (mid form-fill out for instance).

**Comment by qodfathr** [comment]
Thanks!
