### ISSUE TITLE
Che: Terminal Tab default focus

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#202]
When I click on the Terminal tab header, I also have to click into the window to give it focus and a cursor.  This is particularly annoying when switching command tabs.  How about the Terminal tab gain focus/cursor by default when clicked on and brought to the foreground.

**Comment by joshuawilson** [comment]
@gorkem here is another Che issue.

**Comment by joshuawilson** [comment]
This issue was moved to redhat-developer/rh-che#93

**Comment by ibuziuk** [comment]
Upstream che issue - https://github.com/eclipse/che/issues/5741

**Comment by benoitf** [comment]
upstream issue is now closed so we can close this one
