### ISSUE TITLE
Che "run" command missing for Wildfly Swarm quickstarts 

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2022]
Just spotted this on https://openshift.io

Steps to recreate:
* Create new WildFly Swarm quickstart
* Create new Che workspace for that quickstart

**Comment by ldimaggi** [comment]
![screenshot from 2018-01-24 10-13-18](https://user-images.githubusercontent.com/642621/35340269-a9fe19ea-00f0-11e8-99d5-698f1ee466a1.png)

**Comment by ibuziuk** [comment]
PR is sent https://github.com/redhat-developer/rh-che/pull/527

**Comment by ibuziuk** [comment]
@ldimaggi could you please verify on `prod-preview` ? we are going to promote the fix today on prod

**Comment by ibuziuk** [comment]
@ldimaggi the fix has been promoted to prod. Could you please verify & close ?

**Comment by ldimaggi** [comment]
Closing - verified fixed in production and on prod-preview.
