### ISSUE TITLE
Several property values are stored as strings instead of ints in the Graph DB

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#2023]
Some values taken from the Libraries.io are stored as strings in the graph database:

```
'libio_dependents_projects': [ { 'id': 'ajcjmdt-2tm0h3c-ebyd', 'value': '35'}],
'libio_dependents_repos': [ { 'id': 'ajcjms1-2tm0h3c-ecqt', 'value': '286'}],
'libio_total_releases': [ { 'id': 'ajcjn69-2tm0h3c-edj9','value': '4'}],
```

Is it expected behaviour? And what's the reason for having such 'schema'?

**Comment by tisnik** [comment]
@msrb FYI

**Comment by miteshvp** [comment]
@tisnik - libio data is represented in string format. e.g something like `85k`, `4.1k`, etc. as seen in the image. 
<img width="388" alt="image" src="https://user-images.githubusercontent.com/17736013/35342833-0b92cefe-014f-11e8-9b3c-7cb901680c38.png">
 Hence this notion. Please close this issue if this helps.

**Comment by tisnik** [comment]
@miteshvp thanks for clarification, I thought it is based on input data. Are we planning to use such numbers for (any) computation?

**Comment by miteshvp** [comment]
AFAIK, we do not have any such plans around libio data sets.

**Comment by tisnik** [comment]
Cool, thanks @miteshvp for explanation. let's close this question then :)
