### ISSUE TITLE
Che: Run has Preview 

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#203]
I created a "compile vertx:run" command and it pops up a preview link of 
http://tomcat8-y5z8fqcsn2bgyg80-burrsutter-che.8a09.starter-us-east-2.openshiftapps.com//vertxbasic23/src/main/java/io/openshift/booster/HttpApplication.java
which is not valid, plus it says "tomcat" and my Vert.x app is totally not Tomcat.
https://screencast.com/t/0TcsLmpsx

**Comment by joshuawilson** [comment]
@gorkem - che issue

**Comment by joshuawilson** [comment]
This issue was moved to redhat-developer/rh-che#92

**Comment by burrsutter** [comment]
One reason this is a bigger problem than expected is because Vert.x is definitely NOT Tomcat.  And while Spring Boot is Tomcat, people think of it as Spring Boot, plus at some point in the never future it will be Spring Boot based on Undertow.  So "tomcat" is almost always wrong

**Comment by benoitf** [comment]
Hello,
I've fixed issue in che OpenShift connector and docker images.
It may take some time to be propagated (time of rebuilding/publishing docker images)

But as @burrsutter suggested, I get rid of "tomcat".

For vert.x it is now "vertx" and for Spring Boot, it is "springboot" service name.
It's also now easy to set any value that we want so let re-open issue if service name is not matching your needs.

**Comment by joshuawilson** [comment]
@burrsutter when you verify this, can we close it?

**Comment by burrsutter** [comment]
This is not fixed.  I am running 1.0.269

**Comment by benoitf** [comment]
yes we decided with @ibuziuk to wait that people upgrade their tenant before updating the images
else if we update the images and tenant is not updated it will fail.

**Comment by benoitf** [comment]
Images are being built, will be fixed when https://ci.centos.org/view/Devtools/job/devtools-che-dockerfiles-build-che-credentials-master/12/ job will be finished

**Comment by benoitf** [comment]
@burrsutter could you confirm it's fixed ?

**Comment by l0rd** [comment]
Closing this issue since it has been fixed and available on OSIO
