### ISSUE TITLE
Space Dashboards

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2032]
When a user opens an OpenShift.io Space, they are show the primary Space dashboard. The primary Space dashboard is one of potentially many Space dashboards; these dashboards display information about the Space, its contained artifacts and its associated environments. The information is displayed via a number of widgets.

When a new Space is created, a single, default dashboard is automatically created with a predefined set of widgets. The user can customize the layout of the dashboard, adding, removing and rearranging widgets. The user may also create additional Space dashboards, using each to provide different views across the Spaces.

Furthermore, each Team also has one or more Space dashboards within the Space.

## Impacted by
- [ ] #1551

## Parent Scenario
 #2026 Finding meaningful and actionable information within a large development project

## See also
#2033 Extending the capabilities of OpenShift.io

**Comment by catrobson** [comment]
Space dashboard designs for H Train: https://redhat.invisionapp.com/share/DQFLCG4G9YK
(Focus on bringing in slightly more informational displays and aligning with visual design for other high level pages like account dashboard and user profile)

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/1998
