### ISSUE TITLE
On prod-preview, creating new quickstart fails

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2035]
Creating a new quickstart fails with this error:

![screenshot from 2018-01-24 17-24-06](https://user-images.githubusercontent.com/642621/35360356-78abd2d4-012b-11e8-8ab2-0817f40ada7b.png)

**Comment by joshuawilson** [comment]
This is due to you having your OSO account tied to free-int instead of free-stg.

**Comment by ldimaggi** [comment]
This had been working until late in the day on January 24 - did something change? Also, how do I reconfigure the user account? Thx!

**Comment by ldimaggi** [comment]
Problem was found by regression test:
https://github.com/openshiftio/openshift.io/issues/2035

**Comment by gastaldi** [comment]
Just pushed a fix, mind trying again? Glad that the change that caused is not in production

**Comment by gastaldi** [comment]
When https://ci.centos.org/view/Devtools/job/devtools-launcher-backend-generator-build-master/118/console finishes, of course

**Comment by ldimaggi** [comment]
It's fixed now - closing.

**Comment by sbose78** [comment]
Hi @gastaldi , do you mind referring the PR here please? Helps learn.. :)

**Comment by gastaldi** [comment]
@sbose78 sure, I'll remind this for future fixes. I commited directly in master: https://github.com/fabric8-launcher/launcher-backend/commit/96fab06d04c47110195efab33d164217d1b61527
