### ISSUE TITLE
Deployments should request the last 15 minutes of data, not start with only one data point

### ISSUE THREAD

**Issue by c-koehler** [openshiftio/openshift.io#2038]
Right now at the beginning our sparklines are barren because they only get one data point... and then wait 60 seconds to get the next data point. This causes the graph to be empty with a single dot until another value comes in. 

What should happen is it should grab the last 15 minutes of data (or `15*60 / POLLING_RATE_SECONDS` points of data) and display those at the beginning.

This will also solve the issue of the graphs looking empty at the beginning which will look probably weird to a client trying to view it... plus with the 60 second polling rate, the emptiness of the graphs stays empty for a while.

## Impacts
- [ ] #287

**Comment by jiekang** [comment]
@stooke @ebaron Does the metrics API support requesting the last 15 minutes of data?

**Comment by aptmac** [comment]
@jiekang There's a query that can be added on the the end of the stats and statseries api to get data within a range of time.

**Comment by jiekang** [comment]
Okay nice. Thanks!

**Comment by andrewazores** [comment]
Perhaps this is large enough to fall under a separate issue, but the once-a-minute polled updates should also include all data samples available from the API since the last update, not just the most recent as I believe is received currently.

**Comment by jiekang** [comment]
The OSO requests are for the last X minutes in buckets of Y minutes. With initial request being 15 and 1, and subsequent requests being 1 and 1. Since the API should be making the same kind of request to Openshift or Kubernetes, we should be able to mimic that to get a 15 minute chart with 1 data point per minute.

**Comment by aptmac** [comment]
Sorry about that, I was having trouble with my fork and must have accidentally closed this. :/
