### ISSUE TITLE
Seq_Scan of complete table: wit.iterations

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#2039]
Somewhere in the work item tracker a complete table load is done over and over and over and over and over...

```sql
SELECT * FROM "ITERATIONS"  WHERE "ITERATIONS"."DELETED_AT" IS NULL
```

**Comment by qodfathr** [comment]
@aslakknutsen do you have a recommendation for severity? Are you suggesting that this is constantly consuming CPU resources on the DB?

**Comment by aslakknutsen** [comment]
@qodfathr It seems like with more or less every operation on a work item we're running two complete table dumps of all the iterations and areas. Both tables are relatively small at the moment so not consuming too much CPU/Network, but that will just increase as more users come on. Based on the data extract I have those two queries count for 49% of the DB queries. But we got plenty of DB resources to go on so not critical, just nice to get out of the way.
