### ISSUE TITLE
Seq_Scan of complete table: wit.areas

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#2040]
Somewhere in the work item tracker a complete table load is done over and over and over and over and over...

```sql
SELECT * FROM "AREAS"  WHERE "AREAS"."DELETED_AT" IS NULL
```

Similar: Seq_Scan of complete table: wit.iterations https://github.com/openshiftio/openshift.io/issues/2039

**Comment by aslakknutsen** [comment]
@pranavgore09 Could you take a look at this? Possible this is called with an empty array https://github.com/fabric8-services/fabric8-wit/blob/master/area/area.go#L139

**Comment by pranavgore09** [comment]
sure @aslakknutsen

**Comment by pranavgore09** [comment]
btw, how do I test that it is no more calling `select * from...` after I make changes?

**Comment by aslakknutsen** [comment]
Good question. One would be to verify the expected output where you find the error, e.g. Create an Area, call it with an empty array, and ensure nothing was returned. Alternatively, you could possibly hook into Gorm to verify the SQL itself. Beyond that, I'm sure we'll see the DB CPU drop a few % points and I'll check the DB log after the merge.

**Comment by pranavgore09** [comment]
you are right @aslakknutsen  
it is firing ` SELECT * FROM "areas"  WHERE "areas"."deleted_at" IS NULL` on DB when we pass an empty slice to `LoadMultiple` function
I have verified by adding `.Debug()` in then calling that function with an empty slice in test (I checked by watching the console that query is fired or not) hence  test is not added to the PR.
PR https://github.com/fabric8-services/fabric8-wit/pull/1865 
thanks @aslakknutsen

**Comment by pranavgore09** [comment]
@aslakknutsen is there any way to check DB logs before merging(on that branch?) and can I check it?
