### ISSUE TITLE
target server issue when running pipeline builds

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#2041]
I haven't been able to get a response in the MM chat so far, so creating this issue. I created a new space and a new quickstart project (HTTP Booster) and the first pipeline build starts but never completes successfully. I tried resetting the environment and doing all of this again a few times yesterday but nothing.

Build log: http://pastebin.test.redhat.com/549969

It looks like this sort of fail is happening a lot:

```INFO: I/O exception (org.apache.maven.wagon.providers.http.httpclient.NoHttpResponseException) caught when processing request to {s}->https://maven.repository.redhat.com:443: The target server failed to respond```

Currently blocked at this point (added separate issue of duplicate rendering of pages):
![duplicate_rendering](https://user-images.githubusercontent.com/926572/35363943-67ae0b04-01b8-11e8-817b-2ee5dfef498f.png)

**Comment by mishaone** [comment]
Update: I reset the environment again today and tried anew and it seems to have worked now. If the issue with the target server not responding is just due to network issues, please feel free to close this.

**Comment by piyush1594** [comment]
@mishaone I think this is not an issue right now. @sthaha Can you please take a look. Seems like a network issue only. Closing this.
