### ISSUE TITLE
Inaccurate license information is displayed for packages

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2042]
Showing different licenses  (for the same packages) while triggering stack analysis from workspace and individual manifest file level. This needs to consistent..

**Comment by krishnapaparaju** [comment]
@sunilk747 @miteshvp were these changes promoted to OSIO ?

**Comment by miteshvp** [comment]
This is promoted to prod. Closing this

**Comment by miteshvp** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-data-model/pull/70
