### ISSUE TITLE
Question to PM: Exploration of child workitems under a matching workitem entry

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#2044]
Should we allow free exploration of all child workitems under all workitem (parent) that match the selection criteria? OR should we limit to display only matching children?

For example, consider the following tree structure:
- Feature-1
  - Bug-1
  - Task-1

When  __Requirements__ is selected from the left sidebar, the context is set to display _Features and Bugs_. So, in this case, the structure displayed is something like this:
__Feature-1
    - Bug-1__

Note that _Task-1_ is NOT displayed as per the current implementation. This was decided to avoid cluttering up the page with non-matching child workitems. However, this also gives a sense of missing workitems to the user.

**Suggestion/Question:**
Would it be better to just allow exploration of all child workitems, without filtering out results so that the data displayed is exact representation of the actual data set:
__Feature-1
    - Bug-1__
    - Task-1

## Regarding
#2146 Planning Experience placeholder

**Comment by rgarg1** [comment]
@qodfathr 

Thanks for the clarification. I used that _contrived_ example to demonstrate the case where this specific workitem filtering was noticed in the tree view. So from your response I understand that:

- Workitems display in the tree should not be constrained in any manner
- The above rule does not apply if the workitem type created is not known to Planner 

Cc @michaelkleinhenz @nimishamukherjee

**Comment by kwk** [comment]
@rgarg1 @qodfathr @nimishamukherjee @michaelkleinhenz 

Sorry if my question seems stupid but I have some concerns in a topology where one of the matches is the child of another match. Let's take this contrived topology:

```
A
  \
   B ____
     \    \        
      C    X
        \
         D
          \
           E
```

Let's say we have a search in which the matching items are `B` and `C`. In normal mode we would start by just showing `B` and `C` (maybe nested or not, I don't know now):

```
   B
     \           
      C  
```

If we click on "show-tree" we would include `A` as well:

```
A
  \
   B
     \           
      C   
```

The intend of this issue seems to be to allow exploring of `B` and `C`. I wonder how this will be presented to the user. With `C` technically being it child of `B` means that it **already is indented** to show their relationship.

So how can you expand `B` (for exploration) in order to show `X` when `B` is already expanded?

**Comment by michaelkleinhenz** [comment]
@rgarg1 @qodfathr There is no WIT not known to the Planner as we're always working from the same one template - at least for now. If an external component creates a WI in the core, it has to be part of the template and thus being known by the Planner. If that is a requirement, we need to introduce filters (or reuse the existing filters in a sense of default filters). But that is not defined nor implemented yet.

**Comment by michaelkleinhenz** [comment]
@rgarg1 @qodfathr what we have is a filter on WILTs. Only the parent-child relationships are recognized for the tree display. There are other Link Types that are available but are not appearing in the tree (likely because they use graph instead of tree topology).

**Comment by michaelkleinhenz** [comment]
@kwk in **non-tree**, we show B and C as a list (non-nested), no exploration. In **tree display**, we show:

```
A
  \
   B ____
     \    \        
     +C    X
```
..with C expandable, but collapsed. B and C are bold/highlighted. **X is not** but is displayed.

**Comment by qodfathr** [comment]
@michaelkleinhenz agreed that Planner knows all WITs today. That will not be true in the future, so you guys should start thinking about what that means on your end. :)

@kwk that's a good example, and not too contrived, either. Although guided type navigation basically avoids the creation of your example, here's a real-world case:

Feature `F1` is specified in the backlog.
Dev team says "that feature is too big"
Feature is decomposed into two new features --  `F1.1` and `F1.2` -- and these are created as children of `F1`. This can be done by linking directly in the work item details of `F1`.

So now we have

```
+A
|
+-+F1
  |
  +-+F1.1
  |
  +-+F1.2
```

What we'd want to see (and this will somewhat contradict the rule I stated above) is that only `F1` is displayed initially. If "show parents" is on, the we'd also see `A`. Both `F1.1` and `F1.2` are not initially shown, but are available when `F1`'s children are expanded (and the same goes for any other children of `F1`).

### Initial requirements view
```
+F1
````

### expanded requirements view
```
+F1
|
+-+F1.1
|
+-+F1.2
```

### Initial requirements view with "show parents"
```
+A
|
+-+F1
```

### Expanded requirements view with "show parents"
```
A
|
+-+F1
  |
  +-+F1.1
  |
  +-+F1.2
```

### Expanded requirements view with "show parents" and child Tasks
Just to show an example with some deeper children
```
A
|
+-+F1
   |
   +-+F1.1
   | |
   | +--T1.1.1
   |
   +-+F1.2
   | |
   | +--T1.2.1
   | |
   | +--T1.2.2
   |
   +--T1.1
   |
   +--T1.2
```

And, yes, I know I'm saying "Show parents" when you guys say "Show tree," but, IMHO, these are **all trees**, so "show tree" doesn't make a lot of sense to me. It's really about controlling the display of the parent nodes.

**Comment by kwk** [comment]
I have a PR to address this: https://github.com/fabric8-services/fabric8-wit/pull/1877
