### ISSUE TITLE
How many levels of nested iteration do we support in planner?

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#2046]
@qodfathr - Keeping the side panel real estate in mind, how many levels of nested iteration do we support?

Currently we set indentation up-to four levels:
![nestediterations](https://user-images.githubusercontent.com/1892722/35378416-bb3c7894-01d8-11e8-8b22-d7375bd6835a.png)
Note: One level to Six level are nested iterations (up to a depth of six)
The indentation works for four levels, beyond that there is not much space on so iterations at level 5 (Five Level) and 6 (Six Level) are not indented. 

If we need to allow "n" level of iterations we need to have generic UX rules for their behaviour in the side 
panel.
If we need to restrict nesting up to tow or three level, we need to introduce functionality checks on the UI.

## Regarding
#2157 Planner iterations Feature placeholder

**Comment by qodfathr** [comment]
As long as the back-end can handle `n` levels of depth, I'm fine with the UI only supporting 4 today.
