### ISSUE TITLE
[EPIC] OSIO feature enablement with fine-grained control via admin UI

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#2049]
## Goal
Ability for Product Management to control with fine granularity which features or groups of features in production are visible to groups of users.
## Description
This is the phase two implementation of feature flags for OSIO. This phase builds on top of phase one [EPIC: Feature Flags](https://github.com/openshiftio/openshift.io/issues/1165).
For this Epic, the PM can control feature flags with a more fine-grained granularity, by grouping features into a hierarchy (PM has the responsibility to provide a valid grouping). This hierarchy will be available via an admin UI. 
### Capabilities
- Developers should be able to mark a component as a pre-production release level, not only a page menu (as implemented in phase one).
- Users can opt-in for a state: internal, beta, exp, production-only.
- PM can group features into a hierarchy via an admin UI. 
### Desired types of control
- Enable/Disable a capability on a screen
e.g. if Planner is disabled as an entire screen, disable Planner widget in home screen
- In admin UI, manage groups of feature in a hierarchy
- In admin UI, toggle on and off a feature hierarchy (cascading rule for updating children)
- coherent feature level management in the hierarchy
### For later:
- authorization and roles for admin user
- login via keycloak 
- display metrics of usage of each features (available by default in unleash admin ui)

**Comment by corinnekrych** [comment]
@xcoulon as we agree with @qodfathr to keep alive the initial one. https://github.com/openshiftio/openshift.io/issues/1165
Let me close that one.
