### ISSUE TITLE
Bug: Build report doesn't show the declared licenses 

### ISSUE THREAD

**Issue by luebken** [openshiftio/openshift.io#205]
In the stack report the dependencies should report the licenses declared by the project.

## Associated test-cases:

- Test-1704E469-02

  - io.vertx/vertx-core/3.4.1 should report Apache 2.0, EPL 1.0

- Test-1704E469-03

  - io.vertx/vertx-web/3.4.1 should report Apache 2.0, EPL 1.0

- Test-1704E469-04

  - org.springframework/spring-core/4.3.3.RELEASE should report Apache 2.0

## Associated experience:

- Experience 1704E469 [P0] – License information

**Comment by joshuawilson** [comment]
This issue was moved to fabric8-ui/fabric8-recommender#241

**Comment by joshuawilson** [comment]
This issue was moved to fabric8-analytics/fabric8-analytics-license-check#9

**Comment by samuzzal-choudhury** [comment]
This issue does not apply any more as the license scorer service is in place which can suggest a stack level license and can also provide information license conflicts and license outliers. Hence, closing this. Please reopen if you think otherwise.
