### ISSUE TITLE
[User-Story] Grouping features in the toggle service admin UI

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#2053]
belongs to [Epic: feature flags](https://github.com/openshiftio/openshift.io/issues/1165)
# Description
The feature toggles can be grouped, so that components of a feature can easily be enabled/disabled or promoted to a given level of enablement, in a coherent manner. This means:
- either the UI needs to provide a treeview of all feature toggles, while the backend provides an endpoint to retrieve the hierarchy.
- or find a way with naming convention to group feature in the unleash ui
The admin UI must provide a mean to create/edit/delete child toggles.

# List of tasks:
- [x] spike: unleash admin ui - how to customize it? 
- [ ] spike: how to reuse unleash (server, admin ui) to be able to group feature
- [ ] discuss with Konrad about hierarchy on WIT backend (see if we can reuse pattern of data structures and SQL queries)
- [ ] reuse unleash DB, add a table to express child relationships.
- [ ] validation rule: check the enablement level of children of a given feature. For example, if one parent is `experimental`, all children must `experimental` or `internal`, but they can't be `beta` or `released`

**Comment by corinnekrych** [comment]
`spike: unleash admin ui - how to customize it?` spike is done. tech used is react.js Some PR done
https://github.com/Unleash/unleash-frontend/ have been merged already. Interactive community :)

**Comment by joshuawilson** [comment]
Is this something that we can do in H train?

**Comment by corinnekrych** [comment]
TRDR; it would be good to move it out of H-train
@joshuawilson I think there still discussion needed on this topic in term of use-cases. More concrete use cases would help.
Discussed with @xcoulon @aslakknutsen (pls add more details on our thoughts if you wish) atm the current implementation used with naming convention could be used for grouping. No special support in admin tho.

**Comment by joshuawilson** [comment]
OK, moving to the backlog

**Comment by xcoulon** [comment]
closing this issue in favor of https://github.com/openshiftio/openshift.io/issues/2857 and https://github.com/openshiftio/openshift.io/issues/2627
