### ISSUE TITLE
Jenkins: java.lang.OutOfMemoryError: Metaspace

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#206]
https://gist.github.com/burrsutter/8ec379579b07115df5e017a2a0cd45cf
workaround, restart the Jenkins pod 
oc scale dc/jenkins --replicas=0 -n burrsutter-jenkins
oc scale dc/jenkins --replicas=1 -n burrsutter-jenkins

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1467

**Comment by rawlingsj** [comment]
We were seeings this pre summit after 5 or 6 pipeline runs that included a call out to bayesian.  We tried a few things like groovy and java tuning.  Perhaps we should look to bump up that Metaspace again https://github.com/fabric8io/jenkins-openshift-base/commit/2328e5e01f6d3d45af0b37c24cd97950623df2da

**Comment by rawlingsj** [comment]
> This issue was moved to fabric8io/fabric8-ui#1467

@joshuawilson we probably don't need to move this issue to fabric8-ui, it relates to a possible few components of openshift.io but not the UI.

**Comment by alexeykazakov** [comment]
> workaround, restart the Jenkins pod
> oc scale dc/jenkins --replicas=0 -n burrsutter-jenkins
> oc scale dc/jenkins --replicas=1 -n burrsutter-jenkins

I can confirm that the workaround helps. @sbose78 could you please add it to your FAQ doc if it's not there yet.

**Comment by joshuawilson** [comment]
@rawlingsj you may continue to comment on it here, I only copy it over so that it gets more visibility. It should only be closed when the issue is resolved. Addtionally, I can copy it to any other repo that you think needs visibility into it. :)

**Comment by burrsutter** [comment]
I have now found that oc scale dc/jenkins --replicas=0 -n burrsutter-jenkins 
no longer works, you need to "oc delete pod jenkins-1231 --now -n burrsutter-jenkins" to give it more gas to run with.

**Comment by rawlingsj** [comment]
This has been resolved https://github.com/fabric8-jenkins/jenkins-openshift-base/commit/2328e5e01f6d3d45af0b37c24cd97950623df2da
