### ISSUE TITLE
Space description edit icon is difficult to use

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2066]
The pencil edit icon for editing a Space description is hard to use.

1. It's not always visible, so it's almost undiscoverable.
2. When you make it visible (by hovering over the description), you start to play a game of trying to mouse over to it without causing it to disappear.

It seems it would be more sensible to just make it so that clicking anywhere on the description turns on edit mode (assuming the user has edit rights to the description).

**Comment by jiekang** [comment]
It looks like what you've described as more sensible now occurs. I am able to click anywhere on the description to turn on edit mode. Closing this as resolved. There is a further issue that the edit function doesn't seem to work: https://github.com/openshiftio/openshift.io/issues/2879
