### ISSUE TITLE
Edits to a workitem's labels are not dynamically updated in backlog view

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2067]
Steps to recreate:
* Create a workitem, assign one or more lables to it
* Locate and open the workitem for editing from the backlog view
* Observe that state changes are immediately reflected in the backlog display
* Observe that label changes are not - the view must be manually refreshed to see the label changes

![screenshot 8](https://user-images.githubusercontent.com/642621/35452168-ac0c610c-0293-11e8-9581-072e6b0e1b73.png)

**Comment by qodfathr** [comment]
@michaelkleinhenz possible dupe of #1984? Feel free to close this as a dupe if you feel that it is.

**Comment by nimishamukherjee** [comment]
Fix is on prod. Please re-open if you face the issue.
