### ISSUE TITLE
Broad End-to-End Permissions Experience

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2069]
This end-to-end experience is a non-canonical example of several ways a permission model could be utilized in OSIO -- in other words, this Experience is making a lot of assumptions about future functionality in various parts of OSIO. This Experience need not be implemented precisely as written; rather, this end-to-end story is meant to provide a reasonably clear demonstration of the expectation of how Permissions will operate in OSIO.

In the following experience, a major assumption is that OSIO is primarily comprised of Extensions. In particular, from a logical model standpoint, the Planner functionality of OSIO is not considered to be a ‘built-in’ part of OSIO, but rather is an Extension written for OSIO (and this is slowly becoming true). Moreover, OSIO is assumed to be a deployment of ‘fabric8’. In other words, OSIO is just one of perhaps millions of instances of fabric8 which people have deployed. It just happens to be the Red Hat managed instance, offered as a SaaS.

An OSIO system operator has decided to add the Planner plug-in to OSIO, so that OSIO will provide Planner functionality to the users of OSIO. The operator navigates to the OSIO operator console. The OSIO permission system (PS) verifies that the operator has the rights to see the console. The operator navigates to the operator functionality governing the system-level Extensions. The PS verifies that the operator is permitted to see the current set of Extensions installed, to see the catalog of available Extensions, and also to install or remove system-level Extensions. The console displays to the operator the currently installed Extensions with the option to uninstall any of them, plus UI for installing a new system-level Extensions from the catalog of Extensions.

The operator clicks the “Install System Extension...” button. Again, the PS verifies that the operator has the rights to do so, and the console then displays a list of system-level Extensions. The operator selects the “Red Hat Planner” Extension from the list and clicks the “Install” button. Again, the PS verifies that the operator has the right to perform this operation. The UI informs the operator that this Extension requires several permissions in order to run -- permissions such as the ability to add new Screens and Screen Groups to OSIO as well as the ability to modify work items on behalf of a user. More importantly, the Planner requires the permission to *add new custom permissions* to the PS.

The operator agrees to these conditions. The Extension is installed and performs some initial set-up. The Extension requests to add new permissions to the PS, and the PS permits this operation because the Extension has been granted the permission to add new permissions. The Extension adds several new permissions to the PS, such as “Space/Modify Execution Order” and “Team/Set Iterations.”

Next, the owner of a Space logs into OSIO and navigates to their Space `S1`. In `S1`, they navigate to the Configuration Screen Group and finally to the Permissions screen. Naturally, every step along the way, the PS is ensuring that the user has the necessary permissions to perform these operations. On the Permissions screen is a list Teams and Security Groups. Clicking on any of these reveals 3 sets of information -- Members (i.e. who is a member of the Team or Group), Member of (i.e. to which other Teams or Groups this Team or Group belongs) and Permissions. The Permissions are a list of all assignable permissions given the current context (in this case, within the context of the Space `S1`). Possible values for any permission are Allow, Deny, Not Set, or Inherited. The permissions listed include built-in permissions, such as “Delete Space,” and also custom Space-level permissions added by the Red Hat Planner Extension, such as “Modify Execution Order.”

The Space Owner selects the “Contributors” security group and sets the “Modify Execution Order” permission to Allow. The Space Owner selects the “Readers” security group and sets the “Modify Execution Order” permission to Deny.

User `U1` is a member of the Contributors group in Space `S1`. User `U2` is a member of the Readers group in Space `S1`.
User `U1` logs into OSIO and navigates to the Backlog screen (provided by the newly installed Red Hat Planner Extension), selects a work item in the backlog, and uses drag-and-drop to change the work item's position in the list. The Planner inquires the PS to verify that the `U1` has the “Modify Execution Order” permission in Space `S1`. The PS confirms that `U1` does have this permission, and the work item is moved.

User `U2` logs into OSIO and navigates to the Backlog screen, selects a work item in the backlog, and uses drag-and-drop to change the work item’s position in the list. The Planner inquires the PS to verify that the `U2` has the “Modify Execution Order” permission in Space `S1`. The PS reports that `U2` does **not** have this permission, the work item is not moved, and a warning is displayed to the user indicating that they lack the appropriate permission to modify the ordering of the backlog.

## Parent Scenario
#2068

**Comment by alexeykazakov** [comment]
@godfathr Security groups look like roles to me. And permission == scope.
Resource server == extension.

In first version we are going to implement pre-defined set of security groups/roles with predefined set of permissions/scopes.

For example we have a resource server (extension) - planner (currently planner is a part of work item tracker).
Planer has a set of roles/groups - admin, writer, reader, etc.
Admin has scopes/permissions: manage permissions, write, read. I would avoid using too fine grained scopes/permissions (like modify order, create Work Item, delete comment etc) because of technical difficulties and implementation limitations. The list of user’s scopes will be too big to keep it in a JWT token.

Roles can be assigned to a team or a user for a particular resource. For planner/wit it’s an area/space.

Later we can allow to manage roles/groups. When an admin can create roles and assign scopes/permissions to them.

WDYT Todd? Does it much your idea or I missed some critical difference?

**Comment by qodfathr** [comment]
Although an extension could define a set of groups, this is generally not desirable. The system itself will define some top-level groups (e.g. System Administrators), and all Spaces will get some reasonable Space-level groups such as Contributor, Reader, and Space Administrator. Space Templates are free to define and use additional groups, but this would likely be uncommon.

Planner would then define some permissions (such as `Create new work item`) and make some reasonable default assignments to these permissions across the default set of groups. For example, `Create new work item` would be `Allow` for Contributors and Space Administrators and `Deny` for Readers.

The counter-example to Extension-created groups is if each Extension in the system defines its own groups, things quickly become unmanageable. Most of the time, users will want to think in the context of a very small number of security groups -- e.g. Anonymous Viewers, Authenticated Readers, Contributors, Space Administrators. Life is much easier if every part of the system behaves well with a small set of default groups. A Reader can see things across the Space, but cannot do much. A Contributor can make new work items, can add codebases, can kick off pipeline runs, etc. If, instead, there were Planner Writers and Pipeline Runners groups, we'd almost immediately have a default configuration with literally dozens of security groups -- and no one will be able to understand it.

On the other hand, if a highly motivated and security-focused user wanted to create that many security groups with that level of control, they are free to do so.

Sorry if I'm being pedantic but having a powerful, flexible and ease-to-use permissioning system is critical for OpenShift.io success.

**Comment by qodfathr** [comment]
Didn't mean to close...

**Comment by alexeykazakov** [comment]
@godfathr my proposal is to implement predefined set of groups (roles) and each group (role) has predefined set of permissions (scopes) in the first version.
And also have a predefined set of resource types (system, organization, space/area) where each type has its own set of roles/groups.

We can add flexibility and allow roles/groups  and scopes/permissions be more dynamic later.
I’m talking about MVP.
Implementing everything described in this issue is not feasible in near future. It’s just to much work. Let’s start with something (keeping in mind the bigger picture of course) and see how it goes and where we want to adjust our design and implementation.

WDYT?

**Comment by alexeykazakov** [comment]
cc: @sbryzak

**Comment by qodfathr** [comment]
FYI @alexeykazakov , you keep tagging the wrong GitHub users. My id starts with a `Q`. The pne starting with a `G` is somebody else.

I'm okay with baking in a set of roles at first, provided we are using those in a manner consistent with the capabilities specified. Sounds like a very wise approach for an MVP.

**Comment by alexeykazakov** [comment]
@qodfathr oh, thanks! I didn't realize I was tagging wrong user :)

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2038
