### ISSUE TITLE
Access Control

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2070]
An organization can provide, on a user-by-user or role-by-role basis, access to data in OpenShift.io, so that only authorized users may create certain content, and only authorized users may view certain content.

## Parent Scenario
#2068

**Comment by ldimaggi** [comment]
The higest level object for OSIO is the organization, right? - and users, groups exist with an organization?

**Comment by joshuawilson** [comment]
From way back we had talked about an Entity being the parent / interface concept technically. A User and an Org would be a type of Entity. This may or may not have any bearing on the user experience.

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2036
