### ISSUE TITLE
Entity(Organization)-level permissions

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2074]
It is possible to define permissions which govern usage rights at the *entity* level of OpenShift.io, when the entity is an *organization*. (In this context, entity can be thought of as the same as an *account*. There are two entity types -- User and Organization.)

An example would be the “Create a new Space” permission. A user `U` with this permission in entity `E` has the ability to create a new Space `S` in `E`. e.g., “Tushar has the ‘create a new space’ permission in entity ‘RedHatContainerGroup’ (an organization) and is therefore able to create a new space ‘Container Interlock Investigations’ within ‘RedHatContainerGroup’.

## Parent Scenario
#2068

**Comment by alexeykazakov** [comment]
@sbryzak so, we need to treat Organizations as resources too.

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2041
