### ISSUE TITLE
Space-level permissions

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2075]
It is possible to define permissions which govern usage rights at the *space* level of OpenShift.io.

An example would be the the “Create tag definition in this space” permission. Users with this permission are permitted to create new tags within the Space.

## Parent Scenario
#2068

**Comment by alexeykazakov** [comment]
@qodfathr I don’t see an experience for permissions on area level. Why? In our initial design we set permissions for resources. For planner and wit the resources are Organizations and Areas (root area == space).

**Comment by qodfathr** [comment]
@alexeykazakov mainly because I'm not done writing issues yet. :) But it won't be on Areas, it will be on Teams.

**Comment by qodfathr** [comment]
Actually, upon further consideration, there are no Team or Area specific Permissions. Teams are just a form of Security Group, and, as such, they are **granted** or **denied** Space-level rights, but no specific Permissions are **defined** at these levels. Note that this issue (and others like it) discuss the *definition* of Permissions, not the *assignment*.

Teams can only be assigned Space-level permissions, because the only exist within a Space. Security Groups, on the other hand, may be created either within a Space or within an Entity (User or Organization). Groups defined at the Entity level may be granted or denied Entity-level permissions.

**Comment by alexeykazakov** [comment]
I’m a bit confused...
Let’s take OSIO as an example.
Our thoughts were that we can create a OSIO Space. Then Planner, Auth, Analytics, etc areas within the OSIO Space.
Then we can create Planner, Auth teams, or let’s say Platform teams which we can assign special roles in the area. For example Planner team has “writer” role in Planner area.
Do you have something else in mind?

**Comment by qodfathr** [comment]
Yes, I have something else in mind. Teams do not create their own security groups / roles; they are, in fact, just a version of a security group.

What you are describing looks good on paper, but not in practice. Very few organizations would have a need for that level of control *within a Space*, and if some organization really does want it, the same level of control can be achieved (with some effort) with the model as specified.

**Comment by alexeykazakov** [comment]
Todd, could you describe some example. How we would organize our “openshift.io” space using your permission model. I mean if we use OSIO to develop OSIO.

**Comment by qodfathr** [comment]
That sounds like a good thing to discuss at the f2f. It will take some whiteboards.

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2042
