### ISSUE TITLE
In the Planner, the display of an Iteration description can be difficult to read

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2079]
If a user creates an iteration description that is more than 40-50 characters in length, the description text will be wrapped in the display in the shortcut bar.

For an example, see: 
https://openshift.io/openshiftio/openshiftio/plan?q=(iteration:f76cc930-77cb-429e-8b25-12fb24867402%20$AND%20workitemtype:bbf35418-04b6-426c-a60b-7f80beb0b624,26787039-b68f-4e28-8814-c2f93be1ef4e,0a24d3c2-e0a6-4686-8051-ec0ea1915a28)

It would be better to display the first ~80 characters, and allow the user to optionally view the full description.
![screenshot from 2018-01-26 14-19-27](https://user-images.githubusercontent.com/642621/35456777-a9689022-02a4-11e8-8193-bee585825d9c.png)

**Comment by qodfathr** [comment]
@catrobson thoughts from UXD? Should we even be displaying the description, or is that best left to be a tooltip or something else?

**Comment by nimishamukherjee** [comment]
@ldimaggi can you confirm if you still get the description field. The Planner UI's iteration section has been updated (last week Thursday)?

**Comment by sunilmalagi** [comment]
@qodfathr @catrobson I had confirmed with Dev team, this is an old screenshot and invalid. Prod has been updated over the weekend. Description is no longer shown...

**Comment by catrobson** [comment]
@sunilmalagi thanks for the update!
