### ISSUE TITLE
Stack Report Recommendations never populates

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#208]
https://screencast.com/t/3vK0v13q6p

**Comment by joshuawilson** [comment]
This issue was moved to fabric8-ui/fabric8-recommender#243

**Comment by samuzzal-choudhury** [comment]
@burrsutter @joshuawilson That was a valid scenario where there was no recommendation generated for the user stack as openshift.io analytics found a 100% match with one of its reference stacks.

We have got the following UX to represent that scenario in the stack report but unfortunately not on the dashboard view.
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/17740190/26915615-7559c1b4-4c44-11e7-96e9-63c7625d71d8.png">

We will use [this issue](https://github.com/fabric8-ui/fabric8-recommender/issues/243) to come up with a UX and do the UI implementation.

**Comment by arunkumars08** [comment]
@samuzzal-choudhury @joshuawilson The implementation was already in place and I think it somehow got removed https://github.com/fabric8io/fabric8-ui/commit/d5af7826a2bb0600ec626b1d26776f3fb8928167

I think this can be brought back in

**Comment by burrsutter** [comment]
There is a notification/recommendation in Che, but not one in the stack report
https://screencast.com/t/mWwSoZqC

The stack report seems to think there are on 2 deps when there are 3, perhaps my use of       <scope>import</scope> is throwing things off?

**Comment by samuzzal-choudhury** [comment]
@burrsutter you are right. Dependencies with only default scope are considered currently.

**Comment by samuzzal-choudhury** [comment]
@burrsutter could you please retry without the scope import for logback-core 1.1.10?

My comment on the related issue https://github.com/openshiftio/openshift.io/issues/207 -
https://github.com/openshiftio/openshift.io/issues/207#issuecomment-307062765

**Comment by samuzzal-choudhury** [comment]
@burrsutter can this issue be closed?

**Comment by joshuawilson** [comment]
The dashboard was fixed in https://github.com/fabric8io/fabric8-ui/pull/1513 
Closing this issue. @burrsutter please reopen if needed.
