### ISSUE TITLE
Permission resolution

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2080]
General rule of thumb: `Deny` always takes precedence. If a permission `P` is explicitly set to `Deny` for **any** Team or Security Group to which a user `U` belongs, either belonging to directly or as an ancestor to `U`, the resolution of `P` is `Deny`. If the permission is not set for `U` nor in all ancestors of `U`, the resolution of `P` is `Not Set`, which is handled as `Deny` per #2081. Otherwise, the resolution of `P` is 'Allow`.

**Pseudo-code Permission Resolution Algorithm to resolve if User `U` has Permission `P`**

```
function resolve(Permission P, SecurityEntity S) returns PermissionStatus 
   boolean anyParentAllow := false
   foreach DirectParent DP of S.GetDirectParents()
      PermissionStatus parentResolution := resolve(P, DP)
      if parentResolution = 'Deny' then return resolve := 'Deny (Inherited)'
      if parentResolution = 'Allow' then anyParentAllow := true
   PermissionStatus myResolution := PermissionsForSecurityEntityStore.Get(P,S)
   if myResolution = 'Not Set' AND anyParentAllow then return resolve := 'Allow (Inherited)'
   else return resolve := myResolution
end function 

resolve(P, U)
```
`PermissionsForSecurityEntityStore.Get(P,S)` returns the explicit permission of `P` set for `S` (i.e. `Deny` or `Allow`), or `Not Set` if one is not set.

This recursive search for permission resolution starts in the context of the individual user `U`. A user `U` is a member of one or more `Teams` and `Security Groups`. These `Teams` and `Security Groups`, in turn, may be members of other `Teams` and `Security Groups`. (A `Team` is just a special case of a `Security Groups`, and is treated the same as a `Security Group` when resolving permissions. Both `Teams` and `Security Groups` may be members of other `Teams` and `Security Groups`. Cyclical membership is not permitted. e.g. If `A` is a member of `B`, `B` cannot be a member of `A`. If `A` is a member of `B` and `B` is a member of `C`, `C` cannot be a member of `A`. And so on.)

## Examples

```
Team A
Group B
Team C, member of Team A and Group B
Group D
User E, member of Team C and Group D

A   B
 \ /
  C    D
    \ /
     E
```
The following example table show several examples of where in `{A,B,C,D,E}` Permission `P` is explicitly set, and the resulting resolution of the permission for User `E`. In the table, `A` is `Allow`, `D` is `Deny` and `_` is `Not Set`.

A|B|C|D|E|Resolution of `P` for `E`
-|-|-|-|-|-
_|_|_|_|_|`Not Set` -- when not explicitly set anywhere in the graph; generally handled as `Deny` but displayed as `Not Set`
_|_|_|_|A|`Allow` -- explicitly set to Allow
_|_|_|_|D|`Deny` -- explicitly set to Deny
_|_|_|A|D|`Deny` -- explicitly set to Deny, even though an ancestor set to Allow
_|_|_|D|_|`Deny` -- set to Deny in direct parent
D|_|_|_|_|`Deny` -- set to Deny in **any** ancestor
_|_|D|_|A|`Deny` -- although explicitly set to Allow for the user, set to Deny in parent
_|D|_|_|A|`Deny` -- although explicitly set to Allow for the user, set to Deny in an ancestor
A|D|_|_|_|`Deny` -- set to Deny in an ancestor, even though another ancestor set to Allow
D|_|A|_|_|`Deny` -- set to Deny in an ancestor, even though a closer ancestor set to Allow
D|A|A|A|A|`Deny` -- set to Deny in an ancestor, regardless of the rest and the explicit on `E`
A|_|_|_|_|`Allow` -- set to Allow in an ancestor

## Parent Scenario
#2068

**Comment by alexeykazakov** [comment]
From client (UI) and resource server (Planner backend/WIT) point of view it seems that we can translate these four states of permission to two states (present, not present) simplifying our implementation significantly. A user has a permission to do something with a resource if he/she has a corresponding scope (permission). Scope can be inherited from a parent resource, granted through teams etc. It doesn't matter.
Client and resource server do not care. It's up to AuthZ server to resolve permission.

cc: @sbryzak

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2047
