### ISSUE TITLE
Permission states

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2081]
For a given user and context, permission can be in one of three states:
* `Allow` -- The permission is explicitly granted
* `Deny` -- The permission is explicitly denied
* `Not set` -- The permission is undefined -- **treated as `Deny`**

Furthermore, there is a single state qualifier
* `Inherited` -- generally used for display purposes, indicating that the value of the permission for the user and the context, regardless if explicitly set or not, has been determined to be either `Allow` or `Deny` as a result of Permission resolution (#2080) from an ancestor. For example, `Allow (Inherited)`

## Parent Scenario
#2068

**Comment by alexeykazakov** [comment]
See further related desiccation here - https://github.com/openshiftio/openshift.io/issues/2080#issuecomment-361000682

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2046
