### ISSUE TITLE
Deployments Screen should show all quota metrics which can block successful deployment

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2086]
OSO quota items:
- [x] CPU
- [x] Memory
- [ ] # of Routes
- [ ] # of Services
(need to determine full list)

## See Also
#287 

## Parent Scenario
#2058

**Comment by joshuawilson** [comment]
@qodfathr if this is for H train, please finish it and move it to the train backlog.

**Comment by ebaron** [comment]
On the OpenShift side there is currently support for quotas of the following objects:

Resource Name | Description
-- | --
pods | The total number of pods in a non-terminal state that can exist in the project.
replicationcontrollers | The total number of replication controllers that can exist in the project.
resourcequotas | The total number of resource quotas that can exist in the project.
services | The total number of services that can exist in the project.
secrets | The total number of secrets that can exist in the project.
configmaps | The total number of ConfigMap objects that can exist in the project.
persistentvolumeclaims | The total number of persistent volume claims that can exist in the project.
openshift.io/imagestreams | The total number of image streams that can exist in the project.

(taken from https://docs.openshift.com/online/dev_guide/compute_resources.html)

Not all of these object types will necessarily have quotas set by the cluster admin. For instance, I only have quotas set for Persistent Volume Claims, Replication Controllers, Secrets and Services.

**Comment by joshuawilson** [comment]
@qodfathr this feels more like a `feature` in scope. Can you please update it.

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2005
