### ISSUE TITLE
"Promote" button in OSIO pipeline calls launcher-backend

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/openshift.io#2093]
As part of the merge initiative with the forked generator-backend, we noticed that the legacy code contains some code that [proxies requests to the user Jenkins](https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/web/endpoints/JenkinsProxyEndpoint.java).

IMHO that doesn't make sense that service to exist in launcher-backend, since launcher functionality ends after the booster is deployed. We need to move that code somewhere else. What would be the appropriate project to live on?

**Comment by gastaldi** [comment]
Assigning to the platform team to start discussion about it

**Comment by gastaldi** [comment]
My gut tells me this service should belong to CD, but I need someone to confirm

**Comment by gastaldi** [comment]
Made SEV-2 because we're refactoring the launcher-backend and that will be gone after that

**Comment by joshuawilson** [comment]
So you want it fixed before you refactor it and it is gone?

**Comment by gastaldi** [comment]
Yes, does that make sense?

**Comment by bartoszmajsak** [comment]
Refactoring is by definition changing internal structure and preserving the behaviour - so removing some functionality without introducing new service providing the same is a no-go.

**Comment by joshuawilson** [comment]
and why should someone fix something that is going away?

**Comment by gastaldi** [comment]
It's not going away, the UI still needs it. It needs to be moved to another project. It doesn't make sense to be where it is right now

**Comment by qodfathr** [comment]
I though we were reserving SEVs for bugs. This issue needs a `type`.

**Comment by ldimaggi** [comment]
Isn't this the same issue as bug: #2034  
?

**Comment by gastaldi** [comment]
No, this is a task asking the CD team to move to their domain

**Comment by gastaldi** [comment]
Can the UI call `jenkins.openshift.io` (or the prod-preview counterpart) directly instead?

**Comment by joshuawilson** [comment]
The goal is to get the UI to talk to a backend service that we control so that we are not tied directly to a service like jenkins.

**Comment by gastaldi** [comment]
@joshua I'm not sure you've seen the URL posted. It's sending the full path Jenkins requires, basically doing what jenkins.openshift.io does. I don't think right now it does what you say it does. 😉

**Comment by gastaldi** [comment]
In any case, this service still has to move out of launcher and something that the build team controls

**Comment by joshuawilson** [comment]
agreed
@chmouel @pradeepto @rupalibehera are you aware of this?
cc @aslakknutsen

**Comment by chmouel** [comment]
I don't know any of this and not aware that we have a new responsibility for a new service to be run in the build infra,

**Comment by aslakknutsen** [comment]
@chmouel Not sure what "another service in build infra" means, but this is about 'moving stuff that is build related out of random other services' to clean up. 'build' to this date has kinda worked as some kind of parasite, attaching 'random' behavior to other unrelated services to avoid having a backend of its own.. :)

**Comment by chmouel** [comment]
@aslakknutsen  Ok so you are suggesting we should have a 'build' backend  on top of jenkins (or whatever) to handle the kind of query like for example the kind of query @gastaldi is mentioning ? So yeah but no, I am not aware of any requirements about this and this probably would have to wait build.next (or whatever) but i'll let @krishnapaparaju chip in,  Footnote: Even tho I do enjoy the fact we don't have to take care of another layer of indirection going on top of jenkins, I understand it's not fair for other services, but I am sure the original architecture have its reasons to be like that

**Comment by maxandersen** [comment]
@chmouel there was no good reason for this architecture - why should something that only exists to serve launcher/forge code proxy requests to jenkins  ? its just bad ;)

Anyone know if that code in launcher is actually used ? and if it is - couldn't it just use jenkins.openshift.io ?

**Comment by aslakknutsen** [comment]
@maxandersen The code is used by the "Promote" button in pipeline view in the UI.

**Comment by aslakknutsen** [comment]
@chmouel We're not talking about another layer of indirection. We're talking about you owning your own code. If the current 'build' requires another service then that's an impl detail on your side.

**Comment by chmouel** [comment]
the reason of "this should not be in my codebase this is not my problem" should not be the reason why we we should add a new piece in the infrastructure that makes it harder to debug, there is probably other good reasons for that like for example API abstraction/orchestration/idler tho, but anyway, build.next and all of that...

**Comment by aslakknutsen** [comment]
"this should not be in my codebase this is not my problem" is the first indication of your second part and should spawn a response in-line off either "Ha, I was unaware of the existence of that. Thank you for bringing it to my attention. Let's see how we can resolve that dependency/conflict/pain point' or 'Yes, I'm aware. And here is the good reason for why it is the way it is'.

"I don't know, so I don't care" is not a good starting point.

**Comment by chmouel** [comment]
okay i got your point, anyway this is will be discussed for build.next

**Comment by gastaldi** [comment]
@chmouel @aslakknutsen this is the kind of error that confuses me: https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/1978/

It's definitely not related to launcher, and yet due to some error in the Jenkins

**Comment by gastaldi** [comment]
Accidentally pressed the Close and comment button in the mobile UI :stuck_out_tongue:

**Comment by chmouel** [comment]
Just updating on this, part of the F2F we decided to start to work on this, we are planning to ave a REST server for clients (here is launcher-backend) to call for build related operations. I will update this issue as soon I will  have more documentation to share,

**Comment by gastaldi** [comment]
Given that the Jenkins may be idled, I'd suggest to increase the priority on this issue. 

As of https://github.com/fabric8-launcher/launcher-backend/pull/390 we're removing the launcher-backend code that talks to Jenkins and the UI needs to change to talk to the jenkins-proxy URL directly instead (https://github.com/fabric8-ui/fabric8-ui/blob/master/src/a-runtime-console/kubernetes/ui/pipeline/input-action-dialog/input-action-dialog.component.ts#L72).

**Comment by gastaldi** [comment]
https://github.com/fabric8-launcher/launcher-backend/pull/390 just refactors the functionality to use the updated API in launcher-backend. The functionality must still be moved to the build team domain or replaced when Build.next comes up

**Comment by bartoszmajsak** [comment]
It seems that calls from https://github.com/fabric8-ui/fabric8-ui/blob/master/src/a-runtime-console/kubernetes/ui/pipeline/input-action-dialog/input-action-dialog.component.ts#L61-L77 do not have `X-App: OSIO` in the headers. That results in Launcher Backend assuming it's a call from Standalone are trying to validate that against RHD KeyCloak keys.

@joshuawilson can anyone from the UI team validate that?

**Comment by hrishin** [comment]
@chmouel I think we should consider this API for build service.

**Comment by piyush-garg** [comment]
Removing SEV-2 label as this is task not bug.
