### ISSUE TITLE
Delete batch of spaces from My Spaces interface

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#2097]
If a user wants to delete a batch of spaces (even if it's as small as two or three of them) via the My Spaces UI, they need to individually click each kebab and go through the warning message. Attached is an image of a (rare) pain point where many spaces need to go, but can only be deleted one by one.
 
![many-spaces](https://user-images.githubusercontent.com/17230733/35521553-0cc5e9cc-04e8-11e8-8c30-ed998ee0449d.png)

Can we implement a functionality, similar to the kind you see in web mail clients like Gmail, that allows you to click a button triggering a batch selection mode, select multiple spaces by clicking them, then finally click another button to delete the batch ?

**Comment by chrislessard** [comment]
@catrobson Before I try to implement this, is there anything I should keep in mind from a design standpoint, regarding which icons or buttons to use and where to place them ?

**Comment by joshuawilson** [comment]
@chrislessard `features` need to go through design and PM. You should not work on it till they work it.

**Comment by chrislessard** [comment]
@joshuawilson Gotcha, thanks !
