### ISSUE TITLE
Validate the email field is not empty

### ISSUE THREAD

**Issue by pmuir** [openshiftio/openshift.io#21]

**Comment by pmuir** [comment]
I've pushed a basic html5 validation but could you look at PF styling for it?

**Comment by mindreeper2420** [comment]
I gave it a look, but the default HTML5 required identifiers are drastically different than the PatternFly styles.
The PF styles are here: [PatternFly Form](http://www.patternfly.org/pattern-library/widgets/#forms), and they use Bootstrap's [Validation States](http://getbootstrap.com/css/#forms-help-text) for rendering. I'm not sure how to properly translate the jquery snippets needed for Bootstrap into something this can consume.

**Comment by pmuir** [comment]
We can just use Bootstrap validation & jquery...

**Comment by mindreeper2420** [comment]
Ok, I thought this had to all be in Angular2/Typescript w/no jQuery. I'll go back and see what I can do with the default framework configs.

**Comment by pmuir** [comment]
The landing page is pure jquery & bootstrap. It is in typescript, but you can also just JS obviously.

**Comment by mindreeper2420** [comment]
@pmuir can you take a crack at this? The HTML5 validation does not work in Safari (desktop or mobile), so even with an incorrect email input, it will still submit and show the success message.

**Comment by pmuir** [comment]
Ok, I will probably use some jquery validation framework...

**Comment by RanjithRV** [comment]
@catrobson guessing the landing page is owned by UX team. Can we close this old issue, as we did make over the page quite a bit from those initial days.

**Comment by mindreeper2420** [comment]
Closing, as signups are handled by the Red Hat Developers portal.
