### ISSUE TITLE
Bug: Che doesn't show analytics error when opening it

### ISSUE THREAD

**Issue by luebken** [openshiftio/openshift.io#210]
- If you add a vulnerable dependency an error is shown
- If you close Che and reopen it the error is not shown.

**Comment by joshuawilson** [comment]
This issue was moved to redhat-developer/rh-che#101

**Comment by l0rd** [comment]
We have closed https://github.com/redhat-developer/rh-che/issues/101 since that's not a Che bug but rather the lack of implementation of `onDidOpen` in recommendation language server. The issue is tracked in https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/issues/13

**Comment by invincibleJai** [comment]
related to https://github.com/openshiftio/openshift.io/issues/376. Actual issue is based on certain content of pom.xml above issue appears which is being fixed by Che side else works as expected.

**Comment by invincibleJai** [comment]
@luebken it's working fine now , let me know if it looks good to you
CC @GeorgeActon

**Comment by GeorgeActon** [comment]
tested multiple times so am closing this issue. If you encounter it again, please re-open.
