### ISSUE TITLE
Line wrapping doesn't seem to be supported in profile bio

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#2100]
It would appear as though long words will not always be wrapped to continue on the next line in a user's profile bio. 

![bio-wrapping-1](https://user-images.githubusercontent.com/17230733/35527129-b9cb12c8-04f7-11e8-8c99-d4622301817d.png)
![bio-wrapping-2](https://user-images.githubusercontent.com/17230733/35527130-b9d5f35a-04f7-11e8-9cdb-16ff07f11256.png)

## Impacts
- [ ] #2135 Profile Screen

**Comment by qodfathr** [comment]
@catrobson is this a bug or working as designed?

**Comment by catrobson** [comment]
@qodfathr Yes, this is a bug, we should truncate on characters.

**Comment by chrislessard** [comment]
For what it's worth, wrapping _does_ seem to apply in certain cases when spaces are introduced. It does not seem like the method we've implemented to achieve wrapping knows how to break up long continuous words. This begs the question: should they be broken up via a hyphen, as is usually the case in English texts ?

**Comment by catrobson** [comment]
@chrislessard yes, you're right, the hyphen needs to be introduced.
