### ISSUE TITLE
Che: loading of the pom.xml

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#211]
Two things: 
1) the pom.xml auto-closes in Che, if I leave the browser tab for too long or after having put the laptop to sleep, or perhaps it is my tab suspender, I find the pom.xml has closed
2) opening the pom.xml may say "loading language server protocol" or something like that and essentially stay frozen, the solution is to stop and start the workspace from the Dashboard.

**Comment by joshuawilson** [comment]
This issue was moved to redhat-developer/rh-che#102

**Comment by bmicklea** [comment]
Closing as the root issue is closed.
