### ISSUE TITLE
Openshift.io DSaaS Monitoring/Metrics

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#2110]
All OSIO services expose metrics for central monitoring

# Services

## Container Level: CPU/Network/Memory, etc

- [x] fabric8-wit (go)
- [x] fabric8-auth (go)
- [x] fabric8-tenant (go)
- [x] fabric8-notification (go)
- [x] fabric8-toggles (node)
- [x] fabric8-osoproxy (go)
- [ ] fabric8-toggles-service (go)
- [x] jenkins-idler (go)
- [ ] jenkins-proxy (go)
- [x] che-mt (java)
- [ ] che-starter (java)
- [ ] generator-backend (java)
- [ ] keycloak (java)
- [ ] logindirector (go)
- [ ] osio-front (nginx)
- [ ] fabric8-ui (nginx)
- [ ] OSO content repo (go)
- [ ] OSO jenkins (java)
- [ ] OSO che worksapce (java)
- [x] fabric8-analytics-worker-*

## Runtime Level: Threads / goroutines / aloc, etc

- [x] fabric8-wit
- [x] fabric8-auth
- [x] fabric8-tenant
- [x] fabric8-notification
- [x] fabric8-toggles
- [x] fabric8-osoproxy
- [ ] fabric8-toggles-service
- [x] jenkins-idler 
- [ ] jenkins-proxy
- [ ] che-mt
- [ ] che-starter
- [ ] generator-backend
- [ ] keycloak
- [ ] logindirector
- [ ] osio-front 
- [ ] fabric8-ui 
- [ ] OSO content repo
- [ ] OSO jenkins
- [ ] OSO che worksapce
- [ ] fabric8-analytics-worker-*

## Application Level: REST calls, Errors, Number of X created, etc 

- [x] fabric8-wit
- [ ] fabric8-auth
- [ ] fabric8-tenant
- [ ] fabric8-notification
- [x] fabric8-toggles
- [x] fabric8-osoproxy
- [ ] fabric8-toggles-service
- [ ] jenkins-idler 
- [ ] jenkins-proxy
- [ ] che-mt
- [ ] che-starter
- [ ] generator-backend
- [ ] keycloak
- [ ] logindirector
- [ ] osio-front 
- [ ] fabric8-ui 
- [ ] OSO content repo
- [ ] OSO jenkins
- [ ] OSO che worksapce
- [ ] fabric8-analytics-worker-*

# Datastores

## Infra level

- [x] Tenant DB
- [x] WIT DB
- [x] Auth DB
- [x] Jenkins Proxy DB
- [x] Toggles DB
- [ ] Keycloak DB

## Internal level
- [x] Tenant DB
- [x] WIT DB
- [x] Auth DB
- [x] Jenkins Proxy DB
- [ ] Toggles DB
- [ ] Keycloak DB

## Parent Fundamental
#2082 OpenShift.io has best-of-breed reliability

**Comment by kbsingh** [comment]
@jfchevrette @fche @pbergene

**Comment by fche** [comment]
Would this moot https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/354 ?

**Comment by fche** [comment]
Note that this list includes only the OSD-side metrics, not tenant OSO-side metrics.

**Comment by aslakknutsen** [comment]
@fche Added OSO components, a few more OSD and some DBs. Which level are analytics workers at, container?

**Comment by fche** [comment]
> Which level are analytics workers at, container?

Same as core OSD: per-container.  Because they're in a separate openshift namespace, they have their own copy of osd-monitor running.

**Comment by nurali-techie** [comment]
Four prometheus metrics added:
* requests_total
* request_duration_seconds
* request_size_bytes
* response_size_bytes

**Comment by aslakknutsen** [comment]
Moved to https://openshift.io/openshiftio/openshiftio/plan/detail/2601
