### ISSUE TITLE
OSIO Deployments page should include links to the deployed run/stage apps

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2112]
The current implementation of the Deployments page does not include links to deployed apps on run/stage - these links are provided on the pipeline page.

It would be helpful if we added the links to the Deployment page too. Thx!

**Comment by jiekang** [comment]
Right. This is in the works. As soon as the API is merged into fabric8-wit, fabric8-ui will be updated and the links will be available.

Closing as this is tracked (loosely) under:
https://github.com/openshiftio/openshift.io/issues/1658
https://github.com/openshiftio/openshift.io/issues/1655
