### ISSUE TITLE
Deployments card details (charts) look unrefined for deployments with 0 pods

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#2115]
![screenshot-20180130145054](https://user-images.githubusercontent.com/3787464/35587869-fe91384e-05cc-11e8-8d2f-1bc5864a257a.png)

Deployment cards' expanded details states look unrefined and incomplete when there are 0 pods to a deployment. Need design guidance on this one - @catrobson ? I have a patch prepared that simply hides the CPU/memory/network charts and labels, but I don't know if that's the direction we want to go in.

**Comment by andrewazores** [comment]
![screenshot-20180130145538](https://user-images.githubusercontent.com/3787464/35588109-a69b36fc-05cd-11e8-943f-b2daefa7dfb6.png)

This is what it looks like with the patch applied to simply hide the charts.

**Comment by catrobson** [comment]
+1 to hide the charts when there are no pods and data, looks good @andrewazores
