### ISSUE TITLE
Old workspaces being reused for new project with same name

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#2116]
I'm testing and documenting our getting started doc so we have a lot of resetting the environment and doing the steps with the same names for spaces and projects over and over (and deleting the codebase in GH) so that the screenshots are consistent.

Today, I reset the environment and then created yet another space called myspace and a new project using the Vertx HTTP quickstart names helloworldvertx. After creating the project, I went to the codebases view and found that instead of the "Create a new workspace" option that I'd expect the first time I look at this view, I see the same two workspaces I created before the reset listed as workspaces for this new project.  Perhaps this is a cache issue?

I reset the environment again and created another new space with the same name and a new *SpringBoot* project with the same name as before: helloworldvertx. Success. In the codebases view, once again, instead of "Create a new workspace", it displays the same two workspaces I created for the project named helloworldvertx two environment resets ago. 

![precreated_workspaces](https://user-images.githubusercontent.com/926572/35603291-73c1f2aa-0688-11e8-96c7-5948683cd088.png)

I tried to open the later created one of these two old workspaces and it does not load, thankfully (see screenshot for error) but an environment reset should certainly clear this out and not display old workspaces at all.

![old_ws](https://user-images.githubusercontent.com/926572/35603318-976c4da4-0688-11e8-9d72-cff4bc0a1020.png)

**Comment by aslakknutsen** [comment]
The match between Codebases and Che is based on User+repo-url. And Che is not part of the delete spaces flow, semi related: https://github.com/openshiftio/openshift.io/issues/1746

**Comment by qodfathr** [comment]
See also #915. Revisions to Space deletion is something that PM and UX need to address.

**Comment by mishaone** [comment]
Update: still happens after moving to newer version of Che. Using the same name (which is unavoidable for docs screenshots) means a new project with the same name as an older one will always offer existing workspaces (from before an env reset).

**Comment by rhopp** [comment]
This should be fixed now, because reset environment also deletes all workspaces from codebases (not the ones created directly using che.openshift.io). Closing.
