### ISSUE TITLE
Occasionally, Ok button greyed out when using quickstart wizard

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#2117]
This is a weird minor issue and may be related to me creating spaces and projects with the same names over and over, but periodically my quickstart wizard's summary step has a greyed out OK button. Not sure why, but this tends to happen sometimes with the first new quickstart I create in a new space after an environment reset.

![not_ok](https://user-images.githubusercontent.com/926572/35604936-e87ce19c-0690-11e8-9857-f8120adbf553.png)

Also, you can see in the background of the screenshot that the pipeline build has started so clearly nothing is held up, just a weird spot where you are forced to click cancel to get out of the wizard.

Additionally, when this happens, I often find the Codebases view empty as well, for example:
![codebase](https://user-images.githubusercontent.com/926572/35605495-bfe65afc-0694-11e8-8935-5aca8c58b90d.png)

This is despite the fact that the pipeline build continued as normal and was also promoted (from Jenkins):
![pipelines](https://user-images.githubusercontent.com/926572/35605502-d0fcba2a-0694-11e8-9d61-0ebe0f8e2c77.png)

My usual workaround at this point is to reset the environment. I've also tried a hard refresh but that doesn't help.

## Impacts
#2143 AppWizard Rendering Issues for Heather

**Comment by qodfathr** [comment]
I know that the OK button is disabled while the appwizrd is doing verifications, but I don;t recall seeing this on the very last page of the wizard. @mishaone , what did you do to dismiss the appwizard so you could go on to the next step?

**Comment by joshuawilson** [comment]
The wizard is going through a completely new redesign. This will soon be out of scope.

**Comment by mishaone** [comment]
@qodfathr I clicked Cancel since that's the only button that's active at the moment. You can see in the first screenshot that the build is already starting so the canceling doesn't cancel anything except the wizard.

**Comment by animuk** [comment]
This type of issue we have resolved by reengineering the new Launcher experience Flow. This issue should not be there. Closing this.
