### ISSUE TITLE
Che: Import context-assist offering an invalid import

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#212]
https://screencast.com/t/hUwgyV5SqDM
why is it offering io.vertx.rxjava.* as option?
https://github.com/burrsutter/vertxbasic23/blob/master/pom.xml

**Comment by joshuawilson** [comment]
This issue was moved to redhat-developer/rh-che#103

**Comment by l0rd** [comment]
As [noted](https://github.com/redhat-developer/rh-che/issues/103#issuecomment-318355925) by @benoitf `io.vertx.rxjava` is a transitive dependency (via `vertx-web`) and the suggestion should be expected. I'm closing this issue but feel free to re-open if that doesn't solve the problem.
