### ISSUE TITLE
Che workspaces cannot be started on prod & prod preview.

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#2122]
All info in original issue: https://github.com/redhat-developer/rh-che/issues/530
Creating also here for tracking purposes.

**Comment by ibuziuk** [comment]
@aslakknutsen I guess there is smth. you could help me with to tackle this problem. Looks like `api/user/services` does return blank `cluster*` payload:

```
"cluster-app-domain": "",
"cluster-console-url": "",
"cluster-metrics-url": "",
"cluster-url": "https://api.starter-us-east-2.openshift.com",
"created-at": "2017-04-21T14:14:28.925054Z",
"name": "ibuziuk",
"state": "created",
"type": "user",
"updated-at": "2017-04-21T14:14:28.925054Z",
"version": "1.0.91"
```

**Comment by ibuziuk** [comment]
PR with validation on rh-che side https://github.com/redhat-developer/rh-che/pull/531

**Comment by ibuziuk** [comment]
@rhopp could you please verify on prod-preview ?

**Comment by rhopp** [comment]
@ibuziuk Has something changed? I can see, that your PR is not merged yet, che pod on rh-idev has been running for ~one day (has not bee updated today) and (most importantly) the issue is still present on prod-preview.

**Comment by ibuziuk** [comment]
@rhopp just figured out with Aslak that PR is not actually fixed. PR for rh-che just improves validation, the real fix is on `fabric8-tenant` side

**Comment by aslakknutsen** [comment]
@rhopp @ibuziuk The PR did fix it, but it failed to deploy to preview. Both preview and prod are now updated.

**Comment by ibuziuk** [comment]
@rhopp @ScrewTSW the fix was promoted to prod. Please verify & close

**Comment by rhopp** [comment]
Verified on both prod&prod-preview. Great work, guys!
