### ISSUE TITLE
Unable to enable experimental features

### ISSUE THREAD

**Issue by bartoszmajsak** [openshiftio/openshift.io#2124]
- Go to the space you are not the owner of (i.e. https://openshift.io/openshiftio/openshiftio/plan)
- You will be presented with "opt-in" button to enable experimental features

### Expected behaviour

Opens user profile and let you enable experimental features

### Actual behaviour

Nothing happens

### Additional info

**This works when in your own space**

JS error while calling GET present in the console. Full dump [here](https://gist.github.com/bartoszmajsak/404227991a941acf94f6761441d470ad).

Failed backend calls:
`unsafe:null&s=23:1 GET unsafe:null&s=23 net::ERR_UNKNOWN_URL_SCHEME`

![image](https://user-images.githubusercontent.com/719616/35627809-6706072e-069a-11e8-949f-b3b5bd113523.png)

**Comment by corinnekrych** [comment]
@joshuawilson @bartoszmajsak I've reproduced the problem on fabric8-ui master, then switch to commit https://github.com/fabric8-ui/fabric8-ui/commit/abfa3a336eef8eff27465ae1fd3aa36cd9d1dec9 and the problem is still there.
One thing I've noticed those calls to `api/spacetemplates` get cancelled when accessing other person space. See:
![screenshot 2018-01-31 15 47 44_preview](https://user-images.githubusercontent.com/1395710/35630523-eeb3f2ec-06a1-11e8-9499-7c530d62b8c3.png)
@konrad does it sound familiar? when do we call this `spacetemplates` endpoints, it might help diagnosis the issue?

**Comment by bartoszmajsak** [comment]
>  then switch to commit fabric8-ui/fabric8-ui@abfa3a3 and the problem is still there.

how about git-bisect and some test to "quickly" find the culprit here?

**Comment by corinnekrych** [comment]
@bartoszmajsak you're welcome topaly the git game but you need to know which component/lib is causing issue.
For me it seems located in Planner but I'm not familiar with the code:
![screenshot 2018-01-31 18 02 21_preview](https://user-images.githubusercontent.com/1395710/35636295-029c60be-06b1-11e8-9ae1-3ae07c64dbae.png)
@michaelkleinhenz does it sound familiar to you?

**Comment by corinnekrych** [comment]
Actually it might be link to guard validation here: https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/owner-guard.service.ts#L29 
I'll take the ticket and look closer

**Comment by joshuawilson** [comment]
that was my first thought too, just not sure how it is related

**Comment by aslakknutsen** [comment]
The "unsafe:null" bit has been there for 8months+

**Comment by corinnekrych** [comment]
The "unsafe:null" => pb is link to DataTableRawWrapperComponent (reading the error). 
@aslakknutsen @joshuawilson Agreed nothing to do with this issue. 

indeed, the navigation is cancelled bc of buggy `owner-guard`. Navigating directly from a space (different then `user_space`) to `user_space/_update` was failing the guard validation. The issue has always been there (old bug) even with original exp. feature in place. 
thanks @bartoszmajsak for finding it and giving reproducible path.
