### ISSUE TITLE
Need to add f8a-server-backbone as part of fabric8-analytics dev cluster deployment

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#2125]
Currently dev cluster deployment for fabric8-analytics does not deploy latest [api-backbone](https://github.com/fabric8-analytics/f8a-server-backbone/) service. This deployment replaces worker-api deployments and it should be handled as part of dev-cluster deployment as well.

**Comment by msrb** [comment]
We already have the backbone service in our `deploy.sh` script: https://github.com/fabric8-analytics/fabric8-analytics-deployment/blob/master/openshift/deploy.sh#L78

**Comment by miteshvp** [comment]
Cool. I was unaware. Thanks.
