### ISSUE TITLE
Create Space workflow does not throw you into the new space

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#213]
Video
https://screencast.com/t/1q2lHgdfl

By default, it left me in my old space.  Granted, I canceled out of the Add to Space wizard but that should still have put me into the new added space

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1485

**Comment by burrsutter** [comment]
This UI has been overhauled
