### ISSUE TITLE
Incorrect number of unknown licenses at stack report

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2147]
<img width="1349" alt="screen shot 2018-02-01 at 11 47 15 am" src="https://user-images.githubusercontent.com/15967765/35663927-c7485456-0745-11e8-83c4-77155c70897f.png">

Please see inconsistent numbers at top panel and bottom panel (for unknown license count)

**Comment by sunilk747** [comment]
@krishnapaparaju This PR will fix this bug. 
https://github.com/fabric8-analytics/fabric8-analytics-data-model/pull/70

**Comment by jyasveer** [comment]
fix is here https://github.com/fabric8-ui/fabric8-recommender/pull/435

**Comment by jyasveer** [comment]
@sunilk747 can you please confirm if your changes are in prod ?

**Comment by sunilk747** [comment]
@jyasveer Yes the changes are in production.

**Comment by jyasveer** [comment]
closing it.
