### ISSUE TITLE
Remove dead Black Duck related code

### ISSUE THREAD

**Issue by jpopelka** [openshiftio/openshift.io#2148]
# Description

Long time ago we created a [Black Duck worker/task](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/workers/blackduck.py), but we used it only very shortly and we haven't utilize it for over a year, so I think it's time to remove all the dead code.
It'll stay in history, so it can be reverted, if needed in future.

# Acceptance criteria
[f8a_worker/workers/blackduck.py](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/workers/blackduck.py), [f8a_worker/blackduck_helpers.py](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/blackduck_helpers.py) and [secrets](https://github.com/fabric8-analytics/fabric8-analytics-deployment/blob/master/openshift/secrets-template.yaml#L56) are removed.

**Comment by msrb** [comment]
+1

**Comment by pbergene** [comment]
Removed from worker secrets.

**Comment by msrb** [comment]
Thanks @pbergene 😉
