### ISSUE TITLE
Confusing UI: Create a new Starter project, Create a new Quick start Project

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#215]
https://screencast.com/t/3B8NL94gq

These two buttons appear to lead to the same place, therefore one of them is superfluous.

I believe the rightmost Quick start option is the most important and therefore should be left-most (most of our end-users will read and prioritize left-to-right).

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1487

**Comment by burrsutter** [comment]
This UI has been overhauled as of July 31st
