### ISSUE TITLE
Unify tasks` error handling

### ISSUE THREAD

**Issue by jpopelka** [openshiftio/openshift.io#2150]
Long time ago there was an issue about the $subject, filled by @fridex , but I can't find it now (maybe it even was in some previous repo).
I recently realized how difficult is to debug a failing tests for a task if we catch `TaskError` and turn it into `{'status': 'error'}`. We should let selinon handle those exceptions (i.e. (re-)raise them when caught or not catch them) instead of masking them into `{'status': 'error'}`.
A change similar to [this](https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/504/commits/af64e524002c4e0112e7b7aac7c8d9eede429aaf) should IMHO be done also in [CVEchecker.py](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/workers/CVEchecker.py#L204), [dependency_snapshot.py](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/workers/dependency_snapshot.py#L89), [githuber.py](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/workers/githuber.py#L88), [mercator.py](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/workers/mercator.py#L211) (and maybe others)

**Comment by fridex** [comment]
Cannot find it, but I think it was on one of the internal issue trackers. IMHO it could simplify rescheduling failed tasks and possible task failure tracking/notifications.
