### ISSUE TITLE
Print format for new Analytic reports is not usable

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2153]
See screenshot - if a user attempts to print an Analytic report, the report is not readable:

![screenshot from 2018-01-31 18-07-58](https://user-images.githubusercontent.com/642621/35685507-eb88fe82-0737-11e8-9bb2-26d673741ad4.png)

**Comment by joshuawilson** [comment]
This will need a second set of styles written for printing and then some kind of print icon on the report to activate it. Need to get UX involved.

**Comment by joshuawilson** [comment]
cc @catrobson

**Comment by catrobson** [comment]
@mganesan - do we have a finalized design for web in place at this point, or is that still changing?  If it is final, it would be good to assign this as a HTML/CSS task to @SMahil.

**Comment by muruGanesan** [comment]
@catrobson,  @joshuawilson, please add me to this repository.
Please remove "mganesan" from the list because IT IS GOING TO SOMEONE ELSE.

I will work with Sukhvir/ Arun and close it.

**Comment by GeorgeActon** [comment]
@catrobson @joshuawilson we have sent already Muru an invite in MM @muruganesan

**Comment by muruGanesan** [comment]
I accepted and I am part of this repository... let me go through UX related open issues (if any and fix with help of team)

**Comment by arunkumars08** [comment]
@muruGanesan Please let us know when the design for the same is finalized. 
Also, @catrobson I know we are following patternfly for style guidelines but is there any place where there are a list of general guidelines like print friendliness, ARIA (accessiblity), browser support and things of this order, which we can look into? If yes, could you please point me to that.
@jyasveer

**Comment by catrobson** [comment]
@arunkumars08 HTML/CSS code guidelines: https://fabric8-ui.github.io/fabric8-ux/code-guidelines
Browser support is currently being documented here: https://github.com/openshiftio/openshift.io/issues/2018
Accessibility standards are not documented yet, nor or print standards.

**Comment by arunkumars08** [comment]
@catrobson Thanks Catherine, and the reason I asked for this is when we talk about print, I think we need to decide on what has to be shown to the user for printing. Analytics, for example, being a data intensive application, we can't simply let the user print all that are being shown as it includes 'accordion', 'tabs', 'cards', and a few more components that aren't by default print friendly.

**Comment by joshuawilson** [comment]
Think about it from a managers point of view. They may ask you as the dev to print the report out so they can review it. Personally I would just have them log in and look at it on the system.

**Comment by arunkumars08** [comment]
Agree.

**Comment by sivaavkd** [comment]
@SMahil - this is raised as Sev2.. I am assigning this to current sprint 145.  Let me know if you think otherwise.

**Comment by joshuawilson** [comment]
You should discuss it with PM, you might downgrade it to SEV3. If there is no expectation for anyone to print the report then it wouldn't be a SEV2. But it is a report and manager like to print reports. :)

**Comment by muruGanesan** [comment]
@SMahil, @arunkumars08,  is it possible to fix using HTML/CSS?

**Comment by GeorgeActon** [comment]
As a manager, I would much prefer to look at this online. It is a more focused & interactive view

**Comment by muruGanesan** [comment]
It may not be a use case for Analytics. But I could see the similar issue in planner too. 
 - Is this a problem across the OSIO? 

![printpreview_osio_planner](https://user-images.githubusercontent.com/26006817/36308008-ce27c30a-1344-11e8-9e3c-7f43fb777c82.jpg)

**Comment by joshuawilson** [comment]
Planner is a dynamic table. Analytics is a report. @muruGanesan yes, the way you do this is with CSS.

**Comment by catrobson** [comment]
IMO this was the inherent risk of calling this a "Report" rather than calling it a dashboard and treating it like a dashboard in our UI.  I believe the intent was to move Analytics over to the Analyze tab, and treat it more like a dashboard.  I think that might be more important in the short term than looking across OSIO for print-friendliness.  We can take on a task into UXD to consider print-friendliness at a later time with higher priority items have been addressed.

**Comment by muruGanesan** [comment]
@ldimaggi, @qodfathr, Can we close this issue or treat it as low priority?
 Because we need to take this up as a separate requirement and work on it.

**Comment by catrobson** [comment]
@muruGanesan is there a clear place where we can capture an issue to work on getting the current analytics report over into the Analyze tab as a dashboard experience?

**Comment by muruGanesan** [comment]
@catrobson, since we (UX Bangalore team) doesn't have separate issue tracking,  I may request @GeorgeActon or @sivaavkd to capture this as an OSIO Analytics requirement and UX can work on it. Headsup information: we would like to take this up after summit/GA.

**Comment by muruGanesan** [comment]
Meanwhile, I request @ldimaggi, @qodfathr to reduce the severity or close this issue. Because 'print preview' is generic requirement (irrespective of Analytics/Planner/HDD etc).

**Comment by joshuawilson** [comment]
I'm going to close this and @qodfathr can reopen it if he wants this included.

**Comment by GeorgeActon** [comment]
@sivaavkd @muruGanesan before taking design action here, review with PM. As a manager I do not think a print out of everything would be useful, inspecting online would be more useful. A condensed subset might be useful but that would actually be a new feature depending on what the use case is.

**Comment by muruGanesan** [comment]
@GeorgeActon, We have not taken any design action on this issue. 
We are considering this (print option) issue as a separate requirement in OSIO.io and would discuss with PM after the summit.
