### ISSUE TITLE
Pipelines can bleed across spaces

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#216]
https://www.screencast.com/t/QcrJtvwKrESV

The vertxbasic24myspace2 was created in myspace2
https://screencast.com/t/SMhokI3oy

**Comment by jstrachan** [comment]
since the UI + wizard was updated recently (this week) to do space filtering, newly created projects (BuildConfigs) are created with a label "space: foo"

So I suspect the 'bleeding' is due to old projects created before we had per-space filtering enabled in the UI + wizard

**Comment by burrsutter** [comment]
if you look at the screenshot, my old space "myspace" is the one picking up the newly added pipelines in the newly added space.  The new space "myspace2" is filtering correctly.

**Comment by joshuawilson** [comment]
@jstrachan is there a way to filter old spaces too? We can't just delete old spaces anymore.

**Comment by jstrachan** [comment]
you can easily delete and reimport git repos at any time. Or `oc edit bc foo` and add a `space: cheese` label

**Comment by jstrachan** [comment]
sorry misread - I've no clue if we can delete spaces, thats a WIT thing - I'd love to be able to delete Spaces or Codebases but I've no idea how ;)

**Comment by joshuawilson** [comment]
@jstrachan we can "delete" spaces. But my question is how do we filter old spaces without deleting. We already have spaces we are using. And yet we need a way to filter them. It sounds like the filter only works for new spaces, is that correct? If so, what do we do with existing spaces that we want to keep?

**Comment by jstrachan** [comment]
we don't need to delete spaces; we just need to either 

* delete all the BCs and import them again 
* label the BCs with the space you want to put them in

We've no software yet that can go back in time and guess the space you meant to create a BC inside I'm afraid - so space-less BCs will stay space-less.

We could one day add a 'Move Pipeline to Space ..." UI option to let folks move BCs that were in an old space into a new space.

**Comment by joshuawilson** [comment]
Having a work around is all I really needed. Thanks.

**Comment by jstrachan** [comment]
added the workaround to the FAQ https://github.com/openshiftio/openshift.io/wiki/FAQ#my-pipelines-are-not-being-properly-filtered-by-my-space
