### ISSUE TITLE
Separate end point for ingestion traffic to Graph database

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2161]
We would need separate end point for write side of ingestion traffic to not impact the OISO users.

cc @msrb

**Comment by msrb** [comment]
@krishnapaparaju could you please provide more context for this task? Thanks 😉

**Comment by miteshvp** [comment]
@msrb - Currently we have common gremlin-http serving ingestion (read graph_sync) and online users. We should separate those two.

**Comment by msrb** [comment]
@tuxdna Saleem, could you please take a look into this? Thanks 👍

**Comment by tuxdna** [comment]
- [ ] https://github.com/fabric8-analytics/gremlin-docker/pull/32

- [ ] https://github.com/openshiftio/saas-analytics/pull/255

**Comment by tuxdna** [comment]
All PRs are merged, now waiting for deployment to succeed:

- [ ] https://github.com/openshiftio/saas-analytics/pull/259

**Comment by msrb** [comment]
@tuxdna deployed to prod now :+1:
