### ISSUE TITLE
Incorrect latest version displayed at stack report

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2165]
Please check the screen shot..
<img width="465" alt="screen shot 2018-02-02 at 6 48 39 pm" src="https://user-images.githubusercontent.com/15967765/35735194-d15128e2-0849-11e8-8270-ca97303c089b.png">

**Comment by krishnapaparaju** [comment]
Have created new stack report resulted in 'latest version' not showing up..

<img width="485" alt="screen shot 2018-02-02 at 7 29 33 pm" src="https://user-images.githubusercontent.com/15967765/35736840-7f45f158-084f-11e8-8356-37712be4bb55.png">

cc @miteshvp

**Comment by miteshvp** [comment]
@krishnapaparaju - this is an expected behavior in case user's version is higher than our collected latest version information. Closing this, please re-open if you think otherwise.
