### ISSUE TITLE
Che: Create Workspace, fails to Import

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#217]
After running the Wizard for a new Vert.x basic project, I click Create Workspace and Che launches but often (perhaps always) it fails to load the project by default.

https://screencast.com/t/H3UgZn1qF

workaround is to manually import the project

**Comment by joshuawilson** [comment]
This issue was moved to redhat-developer/rh-che#104

**Comment by benoitf** [comment]
this issue should be closed as downstream issue has been closed : https://github.com/redhat-developer/rh-che/issues/104

**Comment by joshuawilson** [comment]
@burrsutter can you verify?

**Comment by bmicklea** [comment]
Confirmed closed by linked issue.
