### ISSUE TITLE
Drop ngx-modal dependency from project

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#2170]
One of our dependencies, ngx-modal, has been [deprecated](https://www.npmjs.com/package/ngx-modal). It would be a good idea for us to drop the dependency from the project altogether, since it can easily be replaced with another one of our dependencies, [ngx-bootstrap/modal](https://valor-software.com/ngx-bootstrap/#/modals). 

## Parent Experience
#2175 Platform architecture placeholder

**Comment by chrislessard** [comment]
Technically, there are still some mentions of the dependency in the project. Re-opening until these can be dropped.

**Comment by jiekang** [comment]
@chrislessard if you're not working on this anytime soon feel free to unassign yourself
