### ISSUE TITLE
Deployment card details styling does not match designs

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#2176]
Design: https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/260764293

Current styling:

![screenshot-20180202151619](https://user-images.githubusercontent.com/3787464/35753006-0ec85dda-082c-11e8-9f76-4246daa045ee.png)

The "Resource Usage" label is missing, graph label text seems too large, and graph/label column widths should be adjusted so graphs are wider. The deployments donut pods scaling text should also be above the donut rather than inside it.

**Comment by andrewazores** [comment]
Updated styling:

![screenshot-20180202151238](https://user-images.githubusercontent.com/3787464/35865812-870cd4d4-0b23-11e8-87cb-26b5f77ee9c2.png)

The donut scaling label is still inside the donut, whereas the design shows it as above the donut as a label within the card.

**Comment by andrewazores** [comment]
However, this is how the equivalent charts look in the OSO console:

![screenshot-20180206095709](https://user-images.githubusercontent.com/3787464/35866066-2e72ef7e-0b24-11e8-8c3f-097006a87c2d.png)

The pod count/scaling label is within the donut here, so presumably this is the design that @jiekang mirrored when creating the component seen in the Deployments page.

@catrobson should the label be changed to match the Invision design or should it continue to mirror the OSO console?

**Comment by mceledonia** [comment]
@andrewazores Go ahead and keep the styling consistent with the OSO console, label inside the circle. Looking good!
