### ISSUE TITLE
Decomission old Fabric8 Generator repositories

### ISSUE THREAD

**Issue by bartoszmajsak** [openshiftio/openshift.io#2177]
Someone with admin rights should [archive](https://help.github.com/articles/archiving-repositories/) following repositories, as they are not used anymore:

- https://github.com/fabric8io/generator-backend
- https://github.com/fabric8io/fabric8-generator

They have been moved and are maintained in https://github.com/fabric8-launcher/launcher-backend

**Comment by bartoszmajsak** [comment]
@rupalibehera @chmouel  if you give me admin rights I can clean it up myself

**Comment by abs51295** [comment]
@bartoszmajsak @chmouel @rupalibehera if you can do this it would be quite helpful for us for Gemini activities. Thanks :)

**Comment by chmouel** [comment]
Thanks for the reminder, I have archived it! I would not mind giving you rights but I am not sure I am the one who can give them,
