### ISSUE TITLE
Getting Started Integration : ngx-forge/ngx-launcher in Openshift.io

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#2178]
### Description:
Currently, in OSIO we don't have mission flow. With this addition, it helps us to merge the flow from Launcher (i.e the mission, tech stack flow and others).

### Acceptance Criteria:
OSIO user should be able to select mission, technology stacks than can proceed with Dependency Editor or move  with selecting release strategy, Authorize Git Provider, Confirm Application Summary and creating a starter application. Associated Docs need to be there for this flow.

### User Stories

[Sprint 145] - Getting Started - Services and Unit tests (User Story) https://github.com/openshiftio/openshift.io/issues/2274

[Backlog/would be Sprint 146] - Getting Started https://github.com/openshiftio/openshift.io/issues/2320

**Comment by rkratky** [comment]
@invincibleJai, could we please add the existence of respective docs to the acceptance criteria for this story? I filed https://github.com/fabric8io/fabric8-online-docs/issues/192 to track the work on docs.

**Comment by joshuawilson** [comment]
if this is now an `epic`, please update the description to match

**Comment by invincibleJai** [comment]
Thanks @rkratky , have added it. Currently work is in progress , had synced up with @Preeticp as well. Will keep you updated.

**Comment by qodfathr** [comment]
@joshuawilson what's an Epic? Haven't we moved on from those... :)

**Comment by joshuawilson** [comment]
The devs are still using `epic` and `user-story`. As he called it a User-story but labeled it Epic. 
Is it a bad thing to let them use those labels? You could double up the labels so it works for you too.

So this issue could have `type/user-story` and `type/feature`. Just need the parent.

**Comment by qodfathr** [comment]
This feels closer to an Experience (it's basically describing what the user would see/do in the acceptance criteria), but it would need a parent Scenario and child  Features.

**Comment by joshuawilson** [comment]
This is a learning experience for everyone. As you are explaining it here. 

@invincibleJai can you work with @sivaavkd and @krishnapaparaju to update this according to what @qodfathr has said?

**Comment by invincibleJai** [comment]
Sure @joshuawilson will work through it. 

As per my understanding, we wanted it as an epic which will have user-story associated with it.
I was not aware if we are not supposed to use Epic's

**Comment by invincibleJai** [comment]
@GeorgeActon let me if need to close it as we have planning done here https://github.com/openshiftio/openshift.io/issues/2440 and it has the list of user stories associated with it
