### ISSUE TITLE
Something went wrong your environments as the OpenShift Project 'burrsutter' is not accessible to you or does not exist.

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#218]
On Create, Applications 
https://screencast.com/t/GJsj8Pa1Je

This used to work but started failing on June 9th, in the afternoon.

**Comment by joshuawilson** [comment]
@jstrachan do you know anything about this?

**Comment by jstrachan** [comment]
have a fix coming shortly...

**Comment by jstrachan** [comment]
was fixed by the new fabric8-runtime-console version.

Adding in this PR and we've got the real time tenant status widget too: https://github.com/fabric8io/fabric8-ui/pull/1504

**Comment by jstrachan** [comment]
just needs a new production fabric8-ui release
