### ISSUE TITLE
When adding a codebase, user should be able to select by clicking on any part of the row

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#2184]
When adding a codebase to a space, it would be nice if a user could simply click any section of the row containing their selection. 

Here is an example, where I would like to add "terminal-chat" to my space.

![not-clicky](https://user-images.githubusercontent.com/17230733/35827472-191bc6e8-0ab4-11e8-8ca4-f99839f8145a.png)

As it stands, their selection will only be chosen if they click within the highlighted element shown here : 

![label-show](https://user-images.githubusercontent.com/17230733/35827540-4691bace-0ab4-11e8-8254-1974cdc5804d.png)

**Comment by joshuawilson** [comment]
This wizard is being redesigned. Closing as this version will not be updated.
