### ISSUE TITLE
"Opt-in to Experimental Features" button is not working

### ISSUE THREAD

**Issue by vikram-raj** [openshiftio/openshift.io#2185]
Steps to reproduce

- Select production feature in your profile update page.
- Access https://openshift.io/bkundu@redhat.com/CentOS_Container_Pipeline/plan/board
- A prompt for Optin Experimental feature should come up
- After clicking the ``` Opt-in to Experimental Features ```, there is no further progress on page

**Comment by corinnekrych** [comment]
@vikram-raj it should be fixed by https://github.com/fabric8-ui/fabric8-ui/pull/2470 once deployed to PROD
cc @joshuawilson

**Comment by vikram-raj** [comment]
@corinnekrych Thanks for the update.

**Comment by vikram-raj** [comment]
This issue has been fixed and it is in production.
