### ISSUE TITLE
Redundant entries in RDS monitored_upstream table

### ISSUE THREAD

**Issue by jpopelka** [openshiftio/openshift.io#2186]
Testing the new [/bookkeeping/upstreams](https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/f8a_jobs/swagger.yaml#L574) job endpoint (added in #2010) on prod.
I see that:
- some upstream urls are in the table several times
- they are all marked as `active` even when their `deactivated_at` is not null

```json
[
    {
      "active": true,
      "added_at": "2017-11-03T14:11:12.682546",
      "deactivated_at": null,
      "ecosystem_package": "maven/junit:junit",
      "updated_at": "2017-11-26T16:15:40.601508",
      "url": "http://github.com/junit-team/junit/tree/master"
    },
    {
      "active": true,
      "added_at": "2017-11-03T14:07:44.428575",
      "deactivated_at": "2017-11-03T14:11:12.682546",
      "ecosystem_package": "maven/junit:junit",
      "updated_at": "2017-11-03T14:07:44.431521",
      "url": "http://junit.cvs.sourceforge.net/junit/"
    },
    {
      "active": true,
      "added_at": "2017-11-03T13:44:14.277661",
      "deactivated_at": "2017-11-03T14:07:44.428575",
      "ecosystem_package": "maven/junit:junit",
      "updated_at": "2017-11-03T13:44:14.280737",
      "url": "http://github.com/KentBeck/junit/tree/master"
    },
    {
      "active": true,
      "added_at": "2017-10-08T21:20:00.429645",
      "deactivated_at": "2017-11-03T13:44:14.277661",
      "ecosystem_package": "maven/junit:junit",
      "updated_at": "2017-10-08T21:20:00.432577",
      "url": "http://junit.cvs.sourceforge.net/junit/"
    },
    {
      "active": true,
      "added_at": "2017-10-08T20:51:33.537491",
      "deactivated_at": "2017-10-08T21:20:00.429645",
      "ecosystem_package": "maven/junit:junit",
      "updated_at": "2017-10-08T20:51:33.540705",
      "url": "http://github.com/KentBeck/junit/tree/master"
    },
    {
      "active": true,
      "added_at": "2017-10-08T17:23:37.188757",
      "deactivated_at": "2017-10-08T20:51:33.537491",
      "ecosystem_package": "maven/junit:junit",
      "updated_at": "2017-10-08T17:23:37.192355",
      "url": "http://github.com/junit-team/junit/tree/master"
    },
    {
      "active": true,
      "added_at": "2017-09-24T10:17:21.601805",
      "deactivated_at": "2017-10-08T17:23:37.188757",
      "ecosystem_package": "maven/junit:junit",
      "updated_at": "2017-09-24T10:17:21.606184",
      "url": "http://junit.cvs.sourceforge.net/junit/"
    },
    {
      "active": true,
      "added_at": "2017-09-24T10:13:44.580265",
      "deactivated_at": "2017-09-24T10:17:21.601805",
      "ecosystem_package": "maven/junit:junit",
      "updated_at": "2017-09-24T10:13:44.583111",
      "url": "http://github.com/junit-team/junit/tree/master"
    },
    {
      "active": true,
      "added_at": "2017-07-18T07:34:55.885715",
      "deactivated_at": "2017-09-24T10:13:44.580265",
      "ecosystem_package": "maven/junit:junit",
      "updated_at": "2017-09-24T09:47:09.509592",
      "url": "http://github.com/KentBeck/junit/tree/master"
    },
    {
      "active": true,
      "added_at": "2017-06-15T06:25:05.946764",
      "deactivated_at": "2017-07-18T07:34:55.885715",
      "ecosystem_package": "maven/junit:junit",
      "updated_at": "2017-06-15T06:25:05.952227",
      "url": "http://junit.cvs.sourceforge.net/junit/"
    },
    {
      "active": true,
      "added_at": "2017-06-11T05:51:39.368879",
      "deactivated_at": "2017-06-15T06:25:05.946764",
      "ecosystem_package": "maven/junit:junit",
      "updated_at": "2017-06-11T05:51:39.371734",
      "url": "http://github.com/junit-team/junit/tree/master"
    },
    {
      "active": true,
      "added_at": "2017-06-07T10:25:10.243160",
      "deactivated_at": "2017-06-11T05:51:39.368879",
      "ecosystem_package": "maven/junit:junit",
      "updated_at": "2017-06-07T10:25:10.245818",
      "url": "http://github.com/KentBeck/junit/tree/master"
    }
]
```

I guess the `active` field can be completely removed, since we can just compare `deactivated_at` to `null`.
Regarding the duplicates, we should probably rethink [the code for adding the entries](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/workers/init_package_flow.py#L46).

**Comment by msrb** [comment]
This table and the logic around it seems to be completely broken. What's the purpose of blindly replacing one URL for the other? What if we analyze junit:junit/4.12 today (github.com/junit-team/junit.git) and older junit:junit/3.8.2 tomorrow (with URL http://junit.cvs.sourceforge.net/junit/). We end up monitoring old URL which upstream doesn't use any more.

+1 on removing the confusing "active" column. We will also need to fix the GH job: https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/f8a_jobs/default_jobs/githubGatheringJob.yaml#L34.

**Comment by jpopelka** [comment]
> What's the purpose of blindly replacing one URL for the other?

Maybe @fridex can shed some light on this ?

> We will also need to fix the GH job

https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/253

@msrb Since it's end of sprint, I'd suggest merging [my worker PR](https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/514) to remove the `active` flag and stop adding new entries needlessly.
And create a follow-up ticket for your 'logic-being-completely-broken' issue and continue the discussion there.

**Comment by fridex** [comment]
>> What's the purpose of blindly replacing one URL for the other?

> Maybe @fridex can shed some light on this ?

The original design tried to keep the upstream URL based on the record from the last analyzes assuming f8a analyzes packages when they get released so the upstream URL can be updated to reflect changes that were made upstream. There is kept one upstream URL per package (avoiding keeping multiple URLs per project that could be invalid). Without doing some logic on top of release identifiers there is no straightforward way on how to say which URL should be considered as "the latest". Once you store URLs you can do selective flows to do updates without specifying URLs.

The logic behind this is pretty straightforward so if there are any changes to the expected behavior and the source code is not readable to you, feel free to reach out to me (a simple change I can imaging is checking HTTP heads for 200-399 status codes, but that does not always guarantee to be up2date).

**Comment by msrb** [comment]
Is it really that straightforward? The logic which surrounds the table seems to be the root cause of the bug https://github.com/openshiftio/openshift.io/issues/2218 which nobody was able to crack in more than half a year.
