### ISSUE TITLE
Improve empty states of deployments page

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2188]
Parent: #287  

The deployments page has various empty states that are currently, empty, which leads to what I think is an awkward looking page. 

For example: When a user has an application that does not have any applications deployed, the page currently looks like:

![empty-page](https://user-images.githubusercontent.com/5430520/35862597-3b9f0d22-0b1a-11e8-907d-85c0002254b4.png)

I think this can be improved, at least by adding some padding between the deployments table and the resource usage component.

In this situation, I think the resource usage cards should also appear.

**Comment by jiekang** [comment]
@catrobson @mceledonia Can you give some guidance on this? Is it okay, or should things change and if so, how?

**Comment by catrobson** [comment]
@mceledonia can you post the empty state pages you completed for this?

**Comment by joshuawilson** [comment]
hasn't this been completed?

**Comment by catrobson** [comment]
@joshuawilson there wasn't a good empty state in the initial implementation, only a loading state.  We have an updated design already to include two types of empty state:

- There are no applications at all: https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/286564374
- There are applications, but nothing has been deployed for those applications:
https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/286564375

I'm not certain if @jiekang has already implemented.

**Comment by joshuawilson** [comment]
Thanks, I was only thinking of loading not empty.

**Comment by mceledonia** [comment]
@jiekang Checking in here... See the designs posted by @catrobson above for no applications / no deployments, those should cover the bases but I wanted to double check to see if we were missing anything.

**Comment by jiekang** [comment]
@mceledonia Those designs look pretty good to me. One tiny nit: It would be good to specify exactly where the links 'Add an application', 'Pipelines' and 'Resource Usage panel' are meant to go.

**Comment by mceledonia** [comment]
@jiekang Sure thing, I want to double check this with @catrobson @mindreeper2420 but here's what I'm assuming:

**Pipelines** goes to pipelines tab of current space
**Resource Usage Panel** goes to resource usage tab in user settings 
**Add an application** should prompt the application creation wizard flow (?) The other option for this would be to send the user to their space dashboard but I think shortcutting straight to the creation overlay would make the most sense.

**Comment by mceledonia** [comment]
Also here are the image assets
[Deploym_emptystate_assets.zip](https://github.com/openshiftio/openshift.io/files/1961083/Deploym_emptystate_assets.zip)

**Comment by jiekang** [comment]
The developer tasks are tracked at:

https://github.com/openshiftio/openshift.io/issues/3126
https://github.com/openshiftio/openshift.io/issues/3127

with parent user story at:

https://openshift.io/openshiftio/openshiftio/plan/detail/2144
