### ISSUE TITLE
New Stack Report - issue with Insights card

### ISSUE THREAD

**Issue by sivaavkd** [openshiftio/openshift.io#2190]
See the attachment

Insights card says Usage Outliers - 1.  However, details section says that there are no usage outliers.

<img width="1680" alt="screen shot 2018-02-06 at 9 54 55 am" src="https://user-images.githubusercontent.com/32661994/35866175-71e1014c-0b24-11e8-8e7b-8e2481265bbf.png">

**Comment by sivaavkd** [comment]
I just realised that this issue was fixed few months back.  My build pipeline was 4 months old and hence, the issue.  I created a new build and it worked fine for me.  So, closing this issue.

**Comment by joshuawilson** [comment]
what sprint was it fixed it?
