### ISSUE TITLE
Deployments API breaks when codebases conflict between production and prod-preview

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2191]
If I use the application wizard to add the same codebase to a space in production, and a space in prod-preview, I get conflicts like:

```
{"errors":[{"code":"internal_error","detail":"Deployment config osio-prod-preview is part of space abcdefg, expected space myspace","status":"500","title":"Internal error"}]}
```

for the request to `https://api.openshift.io/api/apps/spaces/<spaceId>`

The application `osio-prod-preview` was first added to production space `myspace`, and then added to prod-preview space `abcdefg`. This error prevents the Deployments page from loading on production.

I suspect it's because of the change to the space label in the repository's `pom.xml`. I feel like there should be a separation between production and prod-preview data, but it may be a low priority issue.

**Comment by qodfathr** [comment]
@jiekang can you do a test on just prod -- adding the same codebase to two Spaces on prod? If you get the same error, that's a more serious bug. A user should be able to add a codebase to multiple Spaces.

**Comment by jiekang** [comment]
@qodfathr 
If a codebase has a pipeline in one space, the validation API no longer allows you to add that codebase with a pipeline in another space. I don't think this happened before. However, whatever is being added to the GH repository for a codebase to have a pipeline looks to be in a format that doesn't allow a codebase + pipeline to exist for multiple spaces. Or reworded, it looks like the files in the GH repository for a pipeline are currently in a format that only allows a single pipeline to be targeted.

You can add the codebase without a pipeline to multiple spaces though.

**Comment by qodfathr** [comment]
@jiekang this is a very significant, and breaking, change. Whom needs to be brought into this conversation to discuss and resolve?

**Comment by jiekang** [comment]
@joshuawilson Do you know who owns this piece of the project?

**Comment by joshuawilson** [comment]
This is a mix of the build/CD team and those working on the wizard. 

cc @pradeepto @chmouel @rupalibehera @krishnapaparaju @gastaldi

**Comment by joshuawilson** [comment]
releated to #2391

**Comment by qodfathr** [comment]
May I get an update on this issue?

**Comment by ebaron** [comment]
#2360 is related. The proper fix I'm working on for it will determine the space label from the OpenShift Build resource corresponding to the executing Jenkins pipeline. This will avoid the need to hardcode a space name in the user's pom.xml.

**Comment by piyush1594** [comment]
@sthaha As @ebaron mentioned #2360 is the issue and he is already working on a proper fix. I don't know we should keep this or close as the other one has more visibility.

@ebaron Is there anything that build team need to do for this. In that case, can we drop the build team label?

**Comment by sthaha** [comment]
Closing this issue in favour of #2360. Please reopen if these 2 issues must be tracked separately.
