### ISSUE TITLE
Planner Not Showing Full Information in the List View

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#2192]
When using Planner, the content of the List View is partially hidden by a horizontal scroll. Unfortunately, there is no scrollbar indicating that I should scroll to the right in order to view the additional information, leaving me to believe that it has been cut off. This is occurring at a screen width of 1440px. This issue becomes compounded when I have child elements.

When I expand my screen to the full width of my browser (2560px), the Planner list view expands to meet that width.

__Example at 1440px:__
![screen shot 2018-02-06 at 11 21 19 am](https://user-images.githubusercontent.com/4032718/35870665-39716368-0b30-11e8-8eeb-5d3aa7bcafd7.png)

__Examples at 1440px w/child elements:__
![screen shot 2018-02-06 at 11 26 32 am](https://user-images.githubusercontent.com/4032718/35870831-aadd264a-0b30-11e8-8a27-881d47d63ccd.png)

__Examples at 1440px w/child elements, scrolled to the right:__
![screen shot 2018-02-06 at 11 26 43 am](https://user-images.githubusercontent.com/4032718/35870839-ae5034a2-0b30-11e8-8190-c4ac95ab9b35.png)

__Example at 2560px:__
![screen shot 2018-02-06 at 11 24 33 am](https://user-images.githubusercontent.com/4032718/35870719-580d36d0-0b30-11e8-9a31-2271e142acc3.png)

**Comment by SMahil** [comment]
PR: https://github.com/fabric8-ui/fabric8-planner/pull/2433

**Comment by nimishamukherjee** [comment]
@mindreeper2420 have a look at https://github.com/fabric8-ui/fabric8-planner/pull/2433. This fix is on production.
The fix works for Fedora Chrome and Firefox browsers. For Mac, the scrollbar shows up after the initial scroll.
Any custom scrollbar for Mac would require changes across the UI. 
Any thoughts on this?

**Comment by mindreeper2420** [comment]
@nimishamukherjee the scrollbar always appears for me on my Mac, running Chrome 64. I can confirm that this is fixed. Thanks!
<img width="1506" alt="screen shot 2018-02-12 at 1 03 00 pm" src="https://user-images.githubusercontent.com/4032718/36111779-45623cc8-0ff5-11e8-876c-1724d34ae20f.png">
