### ISSUE TITLE
Creating a new space - the "Create" button, when pressed, does not close the creation dialog - appears to fail

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2195]
Seeing this since late night on February 6, on production and prod-preview.

Steps to recreate:
* Create a new space
* Observe that when the "Create" button is pressed, the space creation dialog is not closed
* No error is logged in the UI or in the browser console
* The space is created, but this is not obvious to the user
* Pressing the "Create" button a second time fails (as expected) as this results in an attempt to create a 2nd space with the same name

Workaround - After pressing "Create," the user can close the space creation dialog.

Marking as SEV2 as there is a workaround - but - we have to fix this asap as it has high user impact.

**Comment by ldimaggi** [comment]
Issue found/encountered by EE tests.

**Comment by ldimaggi** [comment]
![screenshot from 2018-02-07 08-40-49](https://user-images.githubusercontent.com/642621/35919697-e7ab3414-0be3-11e8-9ab8-0cd3e7f59d22.png)


![screenshot from 2018-02-07 08-40-32](https://user-images.githubusercontent.com/642621/35919698-e7c2f432-0be3-11e8-996f-9dc220a13eda.png)

**Comment by joshuawilson** [comment]
how long have you seen this? Can you confirm that it worked yesterday? (when did the tests start to fail?)

**Comment by ldimaggi** [comment]
![screenshot from 2018-02-07 11-50-27](https://user-images.githubusercontent.com/642621/35940155-39a27222-0c1c-11e8-8ac3-d977e29186b8.png)

Started seeing this late on February 6 (Boston time).

**Comment by ldimaggi** [comment]
It's fixed now - thanks!

**Comment by ldimaggi** [comment]
Just verified that this is fixed in production.
