### ISSUE TITLE
space should not appear in the "recent spaces" card after deletion

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#2196]
After deleting a space, it still appears in the "recent spaces" card on the home page, which is wrong. After a hard refresh, the entry does not appear anymore. Looks like a UI caching issue.

**Comment by joshuawilson** [comment]
This fits under the caching issue we have.

**Comment by aptmac** [comment]
I don't believe this is a caching issue; there is no functionality in the SpacesService for handling space deletions, so it currently only handles changing spaces [[0]](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/spaces.service.ts#L36) and updating spaces [[1]](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/spaces.service.ts#L32). This will tentatively be addressed in a PR commit [[2]](https://github.com/fabric8-ui/fabric8-ui/blob/6f7311d902b675d70dddc9226a5e86c2a5ab0284/src/app/shared/spaces.service.ts#L65) that I'm working on.

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/spaces.service.ts#L36
[1] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/spaces.service.ts#L32
[2] https://github.com/fabric8-ui/fabric8-ui/blob/6f7311d902b675d70dddc9226a5e86c2a5ab0284/src/app/shared/spaces.service.ts#L65

**Comment by aptmac** [comment]
Functionality for removing deleted spaces from recent spaces has been added in https://github.com/fabric8-ui/fabric8-ui/pull/3211.
