### ISSUE TITLE
Create Area Dialog breaks f8-ui web application

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2198]
The application breaks after opening and closing the Create Area dialog with, for example:

```
NavigationError(id: 2, url: '/jkang@redhat.com', error: TypeError: Cannot read property 'unsubscribe' of undefined)

TypeError: Cannot read property 'unsubscribe' of undefined at CreateAreaDialogComponent.webpackJsonpac__name_../src/app/space/settings/areas/create-area-dialog/create-area-dialog.component.ts.CreateAreaDialogComponent.ngOnDestroy
```

The code has:

```
  ngOnDestroy() {
    this.openSubscription.unsubscribe();
  }
```

but `openSubscription` is never given a value.

**Comment by jiekang** [comment]
@dgutride Do you know what the intended use of `openSubscription` is in `create-area-dialog.component.ts`?

**Comment by dgutride** [comment]
If it's not used - we can remove it.  It was probably a holdover from trying to capture the open event that didn't work for us.

**Comment by joshuawilson** [comment]
What severity is this?

**Comment by jiekang** [comment]
@joshuawilson

I suggest 2 or 1 as the entire application is unusable after visiting the areas page. You can't even hard refresh since it will visit the areas page and immediately break; you need to hard refresh into a different page by entering a different URL.

I've opened a PR that fixes this. https://github.com/fabric8-ui/fabric8-ui/pull/2509

I'm perplexed why this wasn't seen in the past though.

**Comment by jiekang** [comment]
Closed as fix has been merged.
