### ISSUE TITLE
It does's display any list of workspaces when it hit "workspaces(2) on left menu at Eclipse Che window.

### ISSUE THREAD

**Issue by danieloh30** [openshiftio/openshift.io#220]
There is no changes in right window when I hit workspace menu in Eclipse Che window even though there is 2 workspaces like "workspaces(2)" as below screenshot. Normally it expects the details of workspace list.
![screenshot from 2017-06-12 17-08-51](https://user-images.githubusercontent.com/14066977/27024582-08800958-4f92-11e7-80a4-60d9b7c6d7db.png)

**Comment by joshuawilson** [comment]
This issue was moved to redhat-developer/rh-che#105

**Comment by l0rd** [comment]
This has been fixed by https://github.com/redhat-developer/rh-che/commit/8950bf1f3936fdd17b003fbe11e69f18cdfe227d

![image](https://user-images.githubusercontent.com/606959/28176608-65ce06b8-67f8-11e7-8090-fb1000c50b7c.png)
