### ISSUE TITLE
Intermittent issue - user's OSO account is disconnected

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2201]
Started seeing this problem on February 5 - seeing it intermittently. A user's OSO account is getting disconnected from OSIO:

![screenshot from 2018-02-07 15-23-45](https://user-images.githubusercontent.com/642621/35941505-6f323d9c-0c20-11e8-92af-f1b0b7677b49.png)

No cause or pattern is apparent yet, but it has been see 5+ times in the past 72 hours.

## Impacts
- [ ] #2278 Environments placeholder Experience

**Comment by ldimaggi** [comment]
Issue found/encountered by EE tests.

**Comment by qodfathr** [comment]
How intermittent is this? Perhaps better off as a SEV3?

**Comment by ldimaggi** [comment]
Actually - this was only seen for one day - closing for now, will re-open if it appears again.
