### ISSUE TITLE
Jenkins status in the tenant status indicator is always "in progress"/grey

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#2202]
After resetting the environment and tenant several times, the Jenkins tenant status remains greyed out, i.e. "in progress". I can access Jenkins builds okay, etc. so it looks like it's just the presentation and doesn't reflect the actual status AFAIK.
![jenkins](https://user-images.githubusercontent.com/926572/35949409-06a7c1c8-0cbd-11e8-84aa-9baf51118da9.png)

**Comment by sthaha** [comment]
Closing this we have removed the status entry for Jenkins.
