### ISSUE TITLE
UI does not reflect permissions on viewed space

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#2203]
Per design, spaces are public, which means they can be accessed by anyone provided one has the link. However, one does not have any permissions to modify anything (eg create codebases, pipelines, etc). This is not reflected in the UI. The UI looks and behaves the same no matter whether I view my own space or another user's space.

To reproduce, log into the UI. There will be all the UI elements to add codebases, pipelines, etc. Now access the URL of another user's space. You are able to view this space and the UI does in no way reflect that. In fact, you can go through the steps to create a codebase or pipeline and the workflow will "succeed", except that the created codebase/pipeline is nowhere to be found since you tried to create it as a user in a space you don't have permission to.

**Comment by joshuawilson** [comment]
This is something we are planning to fix. @catrobson do you have designs on this or just notes?

**Comment by jiekang** [comment]
Changes have been made so the actions are no longer accessible when visiting another users space. Closing this issue.
