### ISSUE TITLE
Deployments network chart shows fractional values in tooltip

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#2204]
![screenshot from 2018-02-08 08-51-42](https://user-images.githubusercontent.com/3787464/35976311-b76402a2-0cad-11e8-94e5-f8929cf510d6.png)

I believe the values are fractional because the backend is returning an average sample over a time span, but this may not be clear to users. It seems especially confusing when the traffic is low and the units are Bytes. Should the value be rounded/truncated? Should this only be done when the units are Bytes? For units larger than bytes, how many decimal places should be shown?

**Comment by joshuawilson** [comment]
@catrobson @qodfathr do you have any thoughts on this question?

**Comment by qodfathr** [comment]
While I'm okay with fractions for time-series data, I also feel that more than 1-2 decimal places is hard on the eyes. @catrobson does UXD have guidelines on this?

**Comment by catrobson** [comment]
I agree we should be limiting to 2 decimal places at the very least, but in this case I would round to the whole number for bytes since the fractions are not really going to do much for the user.
