### ISSUE TITLE
Unit tests will not run in Che for Vert.x HTTP Booster -- "No tests found to run. Test suite is empty."

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2205]
Create a new HTTP booster.
Create a workspace for the codebase.
In Che, run the project (so that is compiles)
Navigate to src/test/java/io.openshift.booster
Right-click on that folder and Run JUnit tests:
![image](https://user-images.githubusercontent.com/16322190/35978716-7948f2dc-0cb4-11e8-9c5b-718530429b8e.png)
Notification indicates that tests ran successfully:
![image](https://user-images.githubusercontent.com/16322190/35978759-8ff64b74-0cb4-11e8-88b4-9535201a8504.png)
But output shows that no tests were run:
![image](https://user-images.githubusercontent.com/16322190/35978789-9e23ffac-0cb4-11e8-95be-c575289bb87a.png)

## Impacts
- [ ] #2084 Getting Started Quickly with a Framework - from Wizard, to IDE, to Deployment

**Comment by ibuziuk** [comment]
@qodfathr could we close it as duplicate of https://github.com/openshiftio/openshift.io/issues/1060 ?
Currently JUnit test works via project explorer only if the project was built beforehand

**Comment by qodfathr** [comment]
How do I build it? I did run it before running the unit tests. There is no build option that I can find (other than run).

**Comment by ibuziuk** [comment]
@qodfathr you could build the project by executing the "build" command from Command Explorer

**Comment by qodfathr** [comment]
I'll close as a dupe. Is the lack of a build command in the menus another issue?

**Comment by ibuziuk** [comment]
well, I believe it was not exposed deliberately in order not to overload UI panels. In Che 6 apart from command explorer there is also command palette for command execution:
![image](https://user-images.githubusercontent.com/1461122/35983674-c907488a-0cf2-11e8-9c2b-4d9d7bb0c819.png)
