### ISSUE TITLE
'Failed to create "<SPACE>"' error notification occurs when logging out after completing space-qs-creating wizard

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#2206]
Steps to reproduce:
1. Login to `openshift.io`:
2. Click on `Create a Space` button to start the wizard
3. Follow and finish the wizard to create a new QS project for 'Spring Boot - HTTP Example '.
4. When space and project are created a build appears in Pipelines and OK notification is shown (which indicates that space is indeed created:

![image](https://user-images.githubusercontent.com/3263627/35979643-21ca5124-0ce9-11e8-8acb-e5d96d23af7d.png)

5. As soon as the bubble disappears click to `Log Out` in the user menu and the error notification is shown before the page is redirected away:

![image](https://user-images.githubusercontent.com/3263627/35979749-67b37bfc-0ce9-11e8-995a-0454b55e2b4f.png)

**Comment by jiekang** [comment]
The code [1] suggests the error is being logged to console. @pmacik would it be possible to provide console logs for this? I'm having some trouble reproducing it; it just redirects me to the openshift.io landing page.

[1] https://github.com/fabric8-ui/fabric8-ui/blob/d94d6be421ff79d50666baca3fa5904085261062/src/app/space/wizard/space-wizard.component.ts#L82

**Comment by pmacik** [comment]
@jiekang Here's the Chrome console log: https://pastebin.com/kRWBvM3Y

**Comment by jiekang** [comment]
After a bit more investigating:

For whatever reason, after following the steps above, clicking logout triggers some part of the codebase to make another request to create the space that was created at the very beginning of the steps. This fails as it has already been created.

**Comment by jiekang** [comment]
Fix in progress. As an aside, this can be reproduced by creating a space and then logging out; you don't need to go through the whole process of creating the application.

**Comment by jiekang** [comment]
Closing: Fix has been merged, this should no longer occur on latest.
