### ISSUE TITLE
Unable to create new workitems (cards) on OSIO

### ISSUE THREAD

**Issue by dharmit** [openshiftio/openshift.io#2209]
I'm trying to create new card on our [OSIO space](https://openshift.io/bkundu@redhat.com/CentOS_Container_Pipeline/plan/board). Clicking on "+" sign under the "new" column does nothing. I tried on both Firefox and Chrome. 

Firefox version: Firefox Nightly 60.0a1 (2018-02-07) (64-bit)
Chrome version:  64.0.3282.140 (Official Build) (64-bit)

**Comment by bamachrn** [comment]
I am also facing the same issue here, not able to create cards.

**Comment by joshuawilson** [comment]
what is a card?

**Comment by dharmit** [comment]
@joshuawilson a workitem

**Comment by nimishamukherjee** [comment]
@dharmit please check. Fix on production

**Comment by dharmit** [comment]
It's working now. Thanks.
