### ISSUE TITLE
SpringBoot quickstarts are missing on prod-preview

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2211]
![screenshot from 2018-02-09 09-13-32](https://user-images.githubusercontent.com/642621/36033933-5364925c-0d80-11e8-86b4-adca88ce7070.png)

## Impacts
- [ ] #2084 Getting Started Quickly with a Framework - from Wizard, to IDE, to Deployment

**Comment by ldimaggi** [comment]
The SpringBoot quickstarts are not missing from production.

**Comment by sara-02** [comment]
@ldimaggi I guess the problem does not exists anymore, in the new launcher wizard you see `Vertx, Sprinboot and WildFly Swarm`.
Can you verfiy and close this issue?

**Comment by ldimaggi** [comment]
Verified - closing.
