### ISSUE TITLE
Store timestamps when tasks started and finished in worker_results table

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#2221]
# Description

Such a crucial information as when task started and when it finished is missing from our bookkeeping data in RDS. The same for package level data. We should add it.

The information needs to be available via Bookkeeping API.

**Comment by msrb** [comment]
This is done, let's  push it to prod.

**Comment by sivaavkd** [comment]
@jpopelka @msrb - Are we ready to push this to Prod ?  Is there something yet to be done ?

**Comment by jpopelka** [comment]
Has been pushed to prod with https://github.com/openshiftio/saas-analytics/pull/275 & https://github.com/openshiftio/saas-analytics/pull/276
