### ISSUE TITLE
Deployment card expansion non-discoverable

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2226]
When I see a collapsed deployment card, there is really no indication that it is expandable. Does UXD have an opinion on this?

![image](https://user-images.githubusercontent.com/16322190/36108323-9592d514-0fea-11e8-91ce-0c6c9762172c.png)

## Regarding
#287 
#2176

**Comment by andrewazores** [comment]
Would changing the cursor shape (from pointer arrow to "hand") when over the cards help with this?

**Comment by joshuawilson** [comment]
cc @catrobson

**Comment by qodfathr** [comment]
@andrewazores I don't think so (well, maybe just a very little), and also not mobile friendly (thinking to the future). `>` and `V` seem to universal symbols for collapse/expand...

**Comment by catrobson** [comment]
The new designs show that the whole row expands on the left of the application name, which should resolve this issue:  https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/288036406
