### ISSUE TITLE
Valid Space names which are invalid OpenShift project names might not trigger validation error

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2228]
1. Create a Space named '12345'
2. Add a QuickStart
3. Pick HTTP Booster (I don't think the choice of the booster matters)
4.  On Define Project step of AppWizard, note that `Next` button is disabled:
![image](https://user-images.githubusercontent.com/16322190/36111211-5ce53ce4-0ff3-11e8-9575-f198a8c89938.png)
5. The reason it is disabled is because the OpenShift Project name is invalid, but there is no indication that this is the reason.
6. Edit the project name slightly (e.g. add an 'a' to the end), and you get the validation error:
![image](https://user-images.githubusercontent.com/16322190/36111271-8e0efc60-0ff3-11e8-9632-9c5dbce9749a.png)

## Impacts
- [ ] #2084 Getting Started Quickly with a Framework - from Wizard, to IDE, to Deployment

**Comment by GeorgeActon** [comment]
Retested this today. This error is now trapped correctly 
closing the defect
