### ISSUE TITLE
Users configured on starter-us-east-2a directed to an invalid URL for the OSO console through OSIO

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2229]
Steps to recreate:
* Attempt to open the OSO console from OSIO - while logged in as a user configured on starter-us-east-2a (for example - from the pipeline page in OSIO)
* Observe this error:

![screenshot from 2018-02-12 13-00-59](https://user-images.githubusercontent.com/642621/36111709-0ce8cce0-0ff5-11e8-9b51-211e4fec83e8.png)

**Comment by alexeykazakov** [comment]
Removed auth and added platform and build-cd. This issue has nothing to do with Auth. It's OSIO UI issue which uses wrong cluster console URL.
@joshuawilson @dgutride

**Comment by joshuawilson** [comment]
I'll look into it.

**Comment by jfchevrette** [comment]
@ldimaggi issue title states 'starter-us-east-2a' but your browser shows 'starter-us-east-2'. Is this simply a bad link in OSIO?

**Comment by ldimaggi** [comment]
The URL presented to the user (who is provisioned on the new cluster) in OSIO is:  

https://console.starter-us-east-2.openshift.com/console/project/ldimaggi-osiotest3

The "a" is missing.

**Comment by aslakknutsen** [comment]
@ldimaggi Where is this link?

**Comment by ldimaggi** [comment]
Sorry to be vague - here is the path to take to recreate the bug:

![screenshot from 2018-03-06 09-10-13](https://user-images.githubusercontent.com/642621/37036711-7b8c90ac-211e-11e8-9800-c1452dce78f0.png)

**Comment by ldimaggi** [comment]
The link provided is:
https://console.starter-us-east-2.openshift.com/console/project/username/browse/pipelines

When the link should be:
https://console.starter-us-east-2a.openshift.com/console/project/username/browse/pipelines

**Comment by stooke** [comment]
some additional information.
curl 'https://api.openshift.io/api/user/services' -H "Authorization: Bearer $PROD"
returns nothing.
{  
   "data":{  
      "attributes":{  
         "created-at":"2018-03-01T18:22:15.949453Z"
      },
      "id":"d4dfa5e7-67a7-4276-84d2-5704c8231979",
      "type":"userservices"
   }
}

**Comment by andrewazores** [comment]
PipelinesComponent#updateConsoleLink - that fabric8UIConfig object is suspect

**Comment by joshuawilson** [comment]
These values are set in OSO via the SaaS-hearder. This file is for local development. (at least that is my best understanding of the magic we have for env var)

**Comment by stooke** [comment]
I think in general you need the environment variables as it's how apps get configured in the cloud.
However, OPENSHIFT_CONSOLE_URL will just lead to sadness and despair.  It must go, as must any other direct k8s/OSO URL in the UI.

**Comment by jiekang** [comment]
@ebaron @stooke Can the WIT backend be augmented to provide an API to acquire the base openshift console url? At the moment it does so for a specific deployment in a specific environment for a specific space. Here only the base is needed: <openshift-url>/console

**Comment by stooke** [comment]
You can ask /api/user/services (token req'd) and it'll give you an array of spaces:
{  
   "data":{  
      "attributes":{  
         "created-at":"2017-10-20T16:10:47.091847Z",
         "namespaces":[  
            {  
               "cluster-app-domain":"b542.starter-us-east-2a.openshiftapps.com",
               "cluster-console-url":"https://console.starter-us-east-2a.openshift.com/console/",
               "cluster-logging-url":"https://console.starter-us-east-2a.openshift.com/console/",
               "cluster-metrics-url":"https://metrics.starter-us-east-2a.openshift.com/",
               "cluster-url":"https://api.starter-us-east-2a.openshift.com/",
               "created-at":"2018-03-27T18:32:52.739544Z",
               "name":"stooke-preview1-jenkins",
               "state":"created",
               "type":"jenkins",
               "updated-at":"2018-03-27T18:32:52.739544Z",
               "version":"2.0.11"
            },

**Comment by ebaron** [comment]
Following up on @stooke's suggestion, you may want to choose the namespace with `type==user`. This will be where the builds shown on the Pipelines page are located, and in the multi-cluster case the namespaces may reside in different clusters.
