### ISSUE TITLE
Can't update workitems even relevant spaces are already removed

### ISSUE THREAD

**Issue by danieloh30** [openshiftio/openshift.io#223]
Can't update workitems[1] even relevant spaces are already removed[2] at user profile menu.
However it looks all fine once the page is reloaded and I think the workitem - select box - should be refreshed automatically when the relevant spaces are removed.
[1]
![screenshot from 2017-06-13 14-01-04](https://user-images.githubusercontent.com/14066977/27066738-38cdf552-5041-11e7-826c-f9eed5243f3d.png)

[2]
![screenshot from 2017-06-13 14-02-56](https://user-images.githubusercontent.com/14066977/27066744-3fb3e520-5041-11e7-875c-c28313733638.png)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1501

**Comment by joshuawilson** [comment]
Fixed in https://github.com/fabric8io/fabric8-ui/pull/1559. Closing.
