### ISSUE TITLE
Users configured on starter-us-east-2a seeing slow throughput

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2230]
Seeing this for OSIO users configured on starter-us-east-2a - throughput times > 30 min to create and build a quickstart:

![screenshot from 2018-02-12 13-32-14](https://user-images.githubusercontent.com/642621/36113596-5353c742-0ffb-11e8-87d4-288a60d3aca4.png)

## Impacts
- [ ] #2155 CI Experience placeholder

**Comment by ldimaggi** [comment]
Example of timing on old cluster:

[INFO] ------------------------------------------------------------------------
[INFO] Building Vert.x - HTTP 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.2:set (default-cli) @ test456 ---
EXITCODE   0[INFO] Searching for local aggregator root...
[INFO] Local aggregation root: /home/jenkins/workspace/ldimaggi_test456_master-BQGOFCVYPKB6YJPEGDWSDT6QEIVOWOWILTEEDXQSFA5SPZWS5YDQ
[INFO] Processing change of io.openshift.booster:test456:1.0.0-SNAPSHOT -> 1.0.1
[INFO] Processing io.openshift.booster:test456
[INFO]     Updating project io.openshift.booster:test456
[INFO]         from version 1.0.0-SNAPSHOT to 1.0.1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:49 min
[INFO] Finished at: 2018-02-13T01:36:57+00:00
[INFO] Final Memory: 10M/15M
[INFO] ------------------------------------------------------------------------

[INFO] --- maven-deploy-plugin:2.8.2:deploy (default-deploy) @ test456 ---
[INFO] Using alternate deployment repository local-nexus::default::http://content-repository/content/repositories/staging/
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:43 min
[INFO] Finished at: 2018-02-13T01:47:56+00:00
[INFO] Final Memory: 42M/57M
[INFO] ------------------------------------------------------------------------

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.472 s
[INFO] Finished at: 2018-02-13T01:48:33+00:00
[INFO] Final Memory: 7M/11M
[INFO] ------------------------------------------------------------------------

**Comment by ldimaggi** [comment]
Example in new cluster:

                                                                    
[INFO] ------------------------------------------------------------------------
[INFO] Building Vert.x - HTTP 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.2:set (default-cli) @ testforfeb12 ---
EXITCODE   0[INFO] Searching for local aggregator root...
[INFO] Local aggregation root: /home/jenkins/workspace/machine_testforfeb12_master-QRIQNKUXCUBFMI65WM24OYE6HQTLZLY427LXJYIEDGE4VRQGGYZA
[INFO] Processing change of io.openshift.booster:testforfeb12:1.0.0-SNAPSHOT -> 1.0.1
[INFO] Processing io.openshift.booster:testforfeb12
[INFO]     Updating project io.openshift.booster:testforfeb12
[INFO]         from version 1.0.0-SNAPSHOT to 1.0.1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:52 min
[INFO] Finished at: 2018-02-12T21:32:44+00:00
[INFO] Final Memory: 9M/13M


[INFO] --- maven-deploy-plugin:2.8.2:deploy (default-deploy) @ testforfeb12 ---
[INFO] Using alternate deployment repository local-nexus::default::http://content-repository/content/repositories/staging/
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17:15 min
[INFO] Finished at: 2018-02-12T21:50:17+00:00
[INFO] Final Memory: 42M/55M
[INFO] ------------------------------------------------------------------------

                                      
[INFO] ------------------------------------------------------------------------
[INFO] Building Vert.x - HTTP 1.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- stackinfo-maven-plugin:0.2:prepare (default-cli) @ testforfeb12 ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 42.197 s
[INFO] Finished at: 2018-02-12T21:51:24+00:00
[INFO] Final Memory: 7M/11M
[INFO] ------------------------------------------------------------------------

**Comment by pbergene** [comment]
Root cause is known, we're tracking the performance issues on a separate sev-1 internally. :)

**Comment by ldimaggi** [comment]
Srill seeing slow performance:

![screenshot from 2018-02-16 15-45-06](https://user-images.githubusercontent.com/642621/36328557-8aca4c90-1330-11e8-8ba8-717b9c0126d3.png)

**Comment by pbergene** [comment]
While there were some performance improvements done at the end of last week, especially affecting git operations, we are expecting that this networked storage backend will be slower than locally attached ebs volumes.

**Comment by ldimaggi** [comment]
Just saw 2 tests run in about 14 min:

https://ci.centos.org/view/Devtools/job/devtools-test-e2e-openshift.io-smoketest-cluster-two/37/
https://ci.centos.org/view/Devtools/job/devtools-test-e2e-openshift.io-smoketest-cluster-two/36/

In comparison, the same test on the old cluster ran in 8-10 min:
https://ci.centos.org/view/Devtools/job/devtools-test-e2e-openshift.io-smoketest-cluster-one/707/
https://ci.centos.org/view/Devtools/job/devtools-test-e2e-openshift.io-smoketest-cluster-one/706/

So - better performance than seen last week - but still slower that the old cluster.

**Comment by mmclanerh** [comment]
underlying storage is fine.  we need to explore optimizations within the body of what the builds are doing if we're finding the experience isn't in the satisfactory range.

**Comment by ldimaggi** [comment]
I think we can close this issue. The 2a cluster achieved parity (or even better) with the original (2) cluster several weeks ago. A quick test on the 1a cluster also showed no problem.
