### ISSUE TITLE
Reduce number of http requests for Deployments charts

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2233]
The observable for `DeploymentsService:getTimeConstrainedTimeseriesData` isn't cached so the page makes 3 http requests per deployment for the initial timeseries data. By storing it like the other http requests in `DeploymentsService`, we can reduce this to 1.

**Comment by aptmac** [comment]
I mistook the number of calls required to get the fifteen minutes of data; I was wrongfully thinking that each call to get a cpu or memory quota was a separate request. In reality, it's using the already existing functions getEnvironmentCpuStat and getEnvironmentMemoryStat, which are cached. So the number of requests required for the 15 minutes of data is 1 for the timeseries call, and potentially 1 for the environment response (but may be already cached).

I will add the caching functionality to the getTimeConstrainedTimeSeriesData() function though.
