### ISSUE TITLE
[prod] [2a] When clicking on "view logs" link from openshift.io, getting wrong login prompt from Jenkins 

### ISSUE THREAD

**Issue by mmclanerh** [openshiftio/openshift.io#2234]
This is on the 2A cluster:

```
		configmap.fabric8.io/update-on-change=jenkins
			fabric8.io/git-branch=release-v4.0.48
			fabric8.io/git-commit=ef84da3ac87276ca9401f9570baa93c345df9e68
```

When I click on the view logs link, I expect either to be taken into Jenkins or to a openshift-io auth redirect button.  Instead, I'm taken to the jenkins native login page.. and I have to know to click log in on the upper right.  This is a regression.

![image](https://user-images.githubusercontent.com/33727536/36119181-6ed19f34-0ffc-11e8-9644-b283c40c8308.png)

## Impacts
- [ ] #2155 CI Experience placeholder

**Comment by mmclanerh** [comment]
fyi -- when i did a environment reset, this went back to the normal behavior.

**Comment by aslakknutsen** [comment]
This is not specific to 2a. Seen on 2 as well.

**Comment by maxandersen** [comment]
Suggesting to close and remove this as there was a fix made to login handling that @mmclanerh probably did not have on Feb 12th before he update his tenants.

**Comment by mmclanerh** [comment]
\o/ thanks!

**Comment by rupalibehera** [comment]
we had fixed this in the issue, https://github.com/openshiftio/openshift.io/issues/1525

**Comment by mmclanerh** [comment]
@rupalibehera this was well after the release of code related to #1525.  not sure root cause, but this cropped up several times. i haven't seen this issue for a while now though, thanks.
