### ISSUE TITLE
CI pipelines erratic and/or crashing 

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#2235]
We again face erratic behaviour on the pipelines that seriously blocks us from reaching our sprint goals. The usual behaviour is one or more of the following:

- the job is just sitting there for >20m, nothing is happening [1].
- crashes [2]
- weird behaviour on the ci build environment compared to local build [3]

This is seriously blocking us. I am now trying to get a single PR thru since this morning. Debugging that stuff is also not fun given that I have to wait for almost an hour to get a single run completed. Local builds take <10m.

[1] https://jenkins.cd.test.fabric8.io/blue/organizations/jenkins/fabric8-ui%2Ffabric8-planner/detail/PR-2419/24/pipeline (stuck between functional tests and build fabric8-ui npm for >22m now, no log output, nothing, just sits there).

[2] https://jenkins.cd.test.fabric8.io/blue/organizations/jenkins/fabric8-ui%2Ffabric8-planner/detail/PR-2419/23/pipeline (see bottom of the log, I had to force-stop the build).

[3] https://jenkins.cd.test.fabric8.io/blue/organizations/jenkins/fabric8-ui%2Ffabric8-planner/detail/PR-2419/20/pipeline (this seriously looks like there is some residue left from previous builds. We are not re-using anything, right?) -> I admit that this one *could* be a problem in the code. But since I can not reproduce this locally, I would first think there is some caching issue there.

**Comment by sbose78** [comment]
CC: @pradeepto 
@rupalibehera Is there way to give other teams access to the resource monitoring ( CPU , Memory,.. etc ) to folks in other teams as well for our GKE jenkins infra ?

**Comment by pranavgore09** [comment]
@michaelkleinhenz yeah you are right, these are few other issues we found on CI
https://github.com/fabric8io/fabric8-build-team/issues?q=is%3Aopen+is%3Aissue+label%3A%22Build+Error%22

**Comment by michaelkleinhenz** [comment]
Where can we see the configuration the build is using, eg node/npm version, Chrome version etc..?

**Comment by pradeepto** [comment]
> CC: @pradeepto
@rupalibehera Is there a way to give other teams access to the resource monitoring ( CPU , Memory,.. etc ) to folks in other teams as well for our GKE jenkins infra ?

That is not for us to decide. You need to check with @jfchevrette We don't have the powers to do so. We can't even give access to GKE to our own team members.

cc @sbose78 @chmouel @michaelkleinhenz @pranavgore09 @pbergene

**Comment by rupalibehera** [comment]
is this really a SEV-1 are folks completely blocked due to this ?

**Comment by jarifibrahim** [comment]
Based on the discussion we had on the call, I tried to profile the memory usage of planner build.
It turns out we need about 1 GB of memory.
I ran planner build in a docker container with the memory limit of 1 Gb.

Note - I executed only the first 3 steps of planner builds. I did not execute `fabric8-ui` build and the `snapshot build` step.

[![asciicast](https://asciinema.org/a/163367.png)](https://asciinema.org/a/163367?speed=4)

**Comment by pbergene** [comment]
As discussed on a call, we have a workaround and it is not a 'complete' blocker, but needs to be worked out. Reducing the severity and hoping this will be worked through.

**Comment by michaelkleinhenz** [comment]
Update: the cause of [3] is found. It is apparently an inconsistency between npm 5.3 and later versions. Tested with npm 5.6, I can reproduce that lock files generated with 5.6 show that problem on *some* packages when used with 5.3. We will switch to 5.3 locally now as well as Platform is not ready to move to current stabel npm.

**Comment by jaseemabid** [comment]
@michaelkleinhenz  AFAIK, the current Jenkins master is running Node.js 0.10.30 which was released on 2014-07-31, almost 4y old. Would you like it to be upgraded to latest stable? I've a PR for that already. 

See https://github.com/fabric8-jenkins/jenkins-openshift-base/pull/13

**Comment by joshuawilson** [comment]
@jaseemabid everything should be on Node 8.3.0 and NPM 5.3.0. If you find something running a different version please let me know.

**Comment by jaseemabid** [comment]
@joshuawilson Alright! Thanks. I'll take a look at the images and let you know.

**Comment by piyush1594** [comment]
@michaelkleinhenz @joshuawilson @jaseemabid As the planner team has moved to GKE is this still a relevant issue?

**Comment by joshuawilson** [comment]
I don't think so but I'll let @michaelkleinhenz confirm.

**Comment by jarifibrahim** [comment]
@piyush1594 We can close this issue. The failures were on GKE and the planner team is no longer using GKE.
