### ISSUE TITLE
Enable sentry integration in workers

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#2236]
# Description

We'd like to try to enable sentry integration in workers. This should help us to catch bugs more easily.

**Comment by pkajaba** [comment]
It's running on both production and staging environment:
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-staging-kb/

After logging into Sentry deployment you can see that errors are reported.
