### ISSUE TITLE
CI Pipelines do not queue PR commits

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#2237]
PR updates are noch queued. If a build is currently being build, all commits done are ignored and the PR never gets approved. See this PR:

  https://github.com/fabric8-ui/fabric8-planner/pull/2419

Commit 0eacf5f was done while 5c7c652 was being built. So while the PR indicates that the PR is being built, it does not queue up the actual job, so the PR status remains dormant.

To retrigger the build, I need to do a "fake" commit that triggers a new run. Given that a build run takes ~1h, this is not really fun. But since a workaround exists, this is SEV-2.

**Comment by piyush1594** [comment]
@michaelkleinhenz with #2729 we have tried queuing the builds. Is this still the issue. cc @hrishin

**Comment by piyush1594** [comment]
@michaelkleinhenz Seems like this is something different and if this is related to the planner, can we close this, as the planner has moved out of GKE?

**Comment by hrishin** [comment]
@piyush1594 it should be good to close now. As planner team has moved PR builds to CICO CI.

@michaelkleinhenz @nimishamukherjee please confirm it once.
