### ISSUE TITLE
NPM has checksum failures on CI when using package-lock.json

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#2239]
When I use package-locks, NPM crashes with random checksum errors:

npm ERR! code EINTEGRITY
npm ERR! sha1-0/ObGV6F81Oa2djLZWCp0rYyl8Q= integrity checksum failed when using sha1: wanted sha1-0/ObGV6F81Oa2djLZWCp0rYyl8Q= but got sha1-yyGq9VKct972BQoU6yeeTlTk9+8=. (61966 bytes)

In this case, the package in question is protractor, but I had the issue on other packages as well. Locally, it works with current NPM stable (5.6.0). 

A workaround exists (remove package-lock.json files), but this workaround is not usable in the long run.

**Comment by michaelkleinhenz** [comment]
See https://github.com/npm/npm/issues/18957 for a similar behaviour.

**Comment by sthaha** [comment]
Since this issue seems to be not relevant anymore, I am going to close it . Please reopen it if that isn't the case.
