### ISSUE TITLE
[Bug]Clicking on some individual  Pipeline links take to Error page 

### ISSUE THREAD

**Issue by naina-verma** [openshiftio/openshift.io#224]
Clicking on some individual  Pipeline links take to Error page 
Steps to reproduce 
1. create a space / or take any existing space
2. create a pipeline and try browsing (clicking on the pipeline link)
It throws user to an Error page 
Video link : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COUGcwVGhXclVoaWs/view?usp=sharing

**Comment by sbose78** [comment]
Thanks @naina-verma for the report.

I'm guessing this wasn't implemented , the link "view pipeline runs" works at the moment.
CC: @jstrachan

**Comment by joshuawilson** [comment]
I can't see the video, doesn't play on my system. What are the exact steps to reproduce? What link did you click on?
