### ISSUE TITLE
Implement filtering for /bookkeeping/upstreams endpoint

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#2240]
# Description

We want to be able to filter records returned by `/bookkeeping/upstreams` endpoint. It should be possible to get records only for a specific package and/or only currently active records.

**Comment by jpopelka** [comment]
> It should be possible to get records only for a specific package

It is already
https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/f8a_jobs/swagger.yaml#L599

**Comment by msrb** [comment]
Cool, please promote the changes to prod 👍
