### ISSUE TITLE
Launcher apps (Boosters) fail 50% of the time during Build. 

### ISSUE THREAD

**Issue by pradeepto** [openshiftio/openshift.io#2244]
Apparently, they fail 50% of the time while passing through the build system. (this was a discussion at f2f in Westford)

Build team needs to dig into this and diagnose the failures. Are the failures due to a bug in the code or bug in build or something else? And report as such. If they are caused by a bug in build, we need to fix those. If not, file issues and assign to relevant team/group.

For starters, we need more information on these failures? Where do we get those? Do we have existing information that we can get from Service Delivery? 

cc @jfchevrette

**Comment by sthaha** [comment]
@pradeepto I am going to close this Epic since this isn't relevant anymore given the changes that has gone into various build components. 
Lets start a new issue/feature-request when we have more reliable data.
