### ISSUE TITLE
[Bug]Workspaces don't show up in rh-che dashboard

### ISSUE THREAD

**Issue by naina-verma** [openshiftio/openshift.io#225]
Workspaces don't show up in rh-che dashboard
In the rh-che (with keycloak) when trying to have access to the list of workspaces from the dashboard (workspaces in the left menu) no workspace show up.

https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COX1BGemg4V0F5ekE/view?usp=sharing

**Comment by ibuziuk** [comment]
Even though this looks like a bug, note that Dashboard is not going to be exposed to the end-user. In order to list workspaces "Codebases" view should be used on openshift.io side

**Comment by joshuawilson** [comment]
Works as designed.
