### ISSUE TITLE
Areas "Create Area" button should not be enabled after model reopened

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#2252]
Steps to reproduce : 
1. Create a new area, name it however you like, notice that once the name is provided the create button turns blue (going from disabled to enabled)
2. Create another area, notice that the button is still enabled

**Comment by chrislessard** [comment]
@catrobson While working on this I noticed another aspect of the modal I wanted to clear up: 
By default, when you open the modal to add a new area, the dropdown for selecting a parent area will default to the Space you're currently working in. As things are currently implemented, each time the modal is reopened again, this value will be set to whichever value was last put there.

**Comment by chrislessard** [comment]
@catrobson While working on this I noticed another aspect of the modal I wanted to clear up:

By default, when you open the modal to add a new area, the drop down field for selecting a parent area will default to the Space you're currently working in. As things are currently implemented, each time the modal is reopened again, this drop down value will be set to whichever value was last put there. E.g. if I create a new area with the Space as the parent, this will be the value for the drop down the next time I go to create another area. If I change it to "my-new-area", this will be the default value the next time I open the modal, and so on.

What behaviour do we want here ? Should the value always default to the space id ? Should it be whatever was chosen last ? Should it always default to a dummy placeholder bearing a message like "Please select a parent area" ?

**Comment by catrobson** [comment]
@chrislessard the design intent is if you use the top right "Add Area", the dropdown should always default to the parent-most area node (space id).  If you use a kabob menu to add a child on an existing node, the parent dropdown should default to the node that the child was being created from.  

We have a story in UXD for Dev to change the list view to a tree list view that we have available in the patternfly-ng repo, and at that point we can also consider if we should make the "add child" more obvious as well.  (https://github.com/fabric8-ui/fabric8-ux/issues/835)
