### ISSUE TITLE
BAD REQUEST http 400 error received from the OSO proxy for some very long GET requests

### ISSUE THREAD

**Issue by davidfestal** [openshiftio/openshift.io#2254]
When trying to run CHE6 on OSIO using the OSO proxy, it fails when the `openshift-client` tries to run some command in the workspace POD.
It appears that this is achieved by the `openshift-client` sends a very long http request such as the requests copied here: https://gist.github.com/davidfestal/7ba312b7e0d0c05fe6ecb4c71cd4126d

Thus it seems that there might be some underlying limitation on the length of GET URL in the OSO proxy that prevents CHE6 on OSIO to start a workspace.
And when it receives such URLs, the OSO proxy returns a 400 HTTP error with the following body:

```html
<html><body><h1>400 Bad request</h1> Your browser sent an invalid request. </body></html>
```

Those requests cannot even be found in the `f8osoproxy` POD logs on the prod-preview console: https://console.rh-idev.openshift.com/console/project/dsaas-preview

The fact that these requests don't even appear in the logs seems to indicate that they are rejected very early in the proxying process.

**Comment by aslakknutsen** [comment]
@davidfestal I've upgraded the proxy to latest upstream v, which 'might' have changed something... :) Not found anything specific yet. 

Just for the public record, this is a 75Kb URL, browsers tend to complain around 2kb.

**Comment by davidfestal** [comment]
@aslakknutsen Thanks !

In the meantime I split the command into several (1 command per WS installer), and a last command that concatenates the result of the previous commands.
This now seems to work (at least the proxy error disappears)
I think I will submit a PR for this since, as you say, 75kb seems really too big for a GET request URL.

**Comment by davidfestal** [comment]
This has been fixed by the commits mentioned in this issue
