### ISSUE TITLE
Error in Create Areas modal should result in highlighting of offending fields

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#2255]
As per this section of the [patternfly specification](http://www.patternfly.org/pattern-library/forms-and-controls/errors-and-validation/), when an error occurs in the Create Area modal, any offending fields should be highlighted in red to indicated to the user where they must correct their mistake.

**Comment by aslakknutsen** [comment]
@chrislessard Please let me know if the backend API's need to improve here
