### ISSUE TITLE
[User-Story] Improve login to feature toggles admin UI

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#2258]
belongs to [Epic: feature flags](https://github.com/openshiftio/openshift.io/issues/1165)

# Description
As a developer, I'd like to be able to access prod-preview unleash admin ui without the need to request login/password from ops team.
Besides, integrating oauth within unleash will allow the admin server to be able to track who did the action in the events history.
> Note: once we got role implemented we can switch to f8 auth service login.

# List of tasks:
- [x] update to unleash final 3.0.0 version and reuse auth-hook
- [x] use gh oauth2, setup app
- [x] update openshift deployment script
- [x] update fabric8-minishift kedge file with addition env variables.
- [x] remove existing `.htaccess` (on prod-preview)

**Comment by corinnekrych** [comment]
@aslakknutsen @alexeykazakov I'd like to start with gh auth. Really easy to impl using `passport` - PR ready.
We can move it to `auth` with impl of role.
cc @xcoulon

**Comment by corinnekrych** [comment]
@xcoulon shall we move that as done? we still got HK processing but the bulk of work mentioned in PR is done.

**Comment by joshuawilson** [comment]
This was demoed in prod.
