### ISSUE TITLE
Anonymmous browsing create duplicate menu error

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#2265]
This issue is in Prod:
![screenshot 2018-02-14 14 21 19_preview](https://user-images.githubusercontent.com/1395710/36206366-61345582-1192-11e8-951f-97267bf351d0.png)

Introduced by https://github.com/openshiftio/openshift.io/issues/1557 `FeatureAcknowledgementService` needs to work when no profile is provided (anonymous user)

**Comment by joshuawilson** [comment]
I think this is caused by a leakage styles from the Planner. 
@mindreeper2420 can you confirm?

**Comment by mindreeper2420** [comment]
@joshuawilson yes, there are still style leaks from Planner. I have a proposal that I'll be messaging you about to help with these leaks.
