### ISSUE TITLE
Intermittent, recurring server errors (500) when refreshing OSIO deployment page

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2268]
Started seeing this on February 14 - issue is not reproducible at will, but was seen 5+ times today.

Steps to recreate:
* Create more than one pipeline (ex. by creating a new quickstart)
* Navigate to the deployments page
* Refresh the page

![screenshot from 2018-02-14 13-22-07](https://user-images.githubusercontent.com/642621/36224497-ce5fe326-1195-11e8-8ee3-42e82584fedd.png)

![screenshot from 2018-02-14 13-10-51](https://user-images.githubusercontent.com/642621/36224498-ce720722-1195-11e8-8e36-0e134a3c40a4.png)

## Impacts
- [ ] #287 Deployments page

**Comment by jiekang** [comment]
@ebaron @stooke any ideas? `space label missing from deployment config` looks to be from `deployments_kubeclient.go`

I can't reproduce on my account though. I wonder if there's something wrong specifically with Len's deployment.

**Comment by jiekang** [comment]
If this error occurs once, I'd expect it to occur many many times; as far as I understand it the code producing the error is querying the same thing for the existence of some value. It shouldn't be possible for it to sometimes exist, and other times not exist.

**Comment by ldimaggi** [comment]
Not sure - the deployments that I used were simply from new quickstarts created in the OSIO UI on production.

The problem was intermittent - but I did see it numerous times.

**Comment by aptmac** [comment]
I ran into this problem once yesterday, although it logged me out at the same time and I thought that had something to do with it.

**Comment by ebaron** [comment]
If anyone can reproduce this again, could you verify that the DeploymentConfig is missing the space label? You can do this by running `oc -n <namespace> get dc/<app name> -o json`. The space label should be under metadata/labels.

**Comment by joshuawilson** [comment]
@ldimaggi have you been able to reproduce this?

**Comment by ldimaggi** [comment]
Closing - not reproducible.
