### ISSUE TITLE
Very slow (~10 seconds) to load/refresh page in Fabric8-ui

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2269]
Note: This issue was first logged against the Deployments page - it actually affects all pages in the UI.

In navigating to, or refreshing the Deployments page, it can take over 15 seconds for the page to load. 
The page loads ~2.4MB of data.

![screenshot from 2018-02-14 14-52-05](https://user-images.githubusercontent.com/642621/36224835-c0a6845a-1196-11e8-9076-bf57141b368f.png)

![screenshot from 2018-02-14 14-50-22](https://user-images.githubusercontent.com/642621/36224836-c0bd0d6a-1196-11e8-93a9-157804670490.png)

**Comment by aptmac** [comment]
That's a lot of calls to statseries, is this prior to https://github.com/fabric8-ui/fabric8-ui/pull/2531? After that PR got merged I'm seeing a reduction in the number of network requests for that data.

**Comment by ldimaggi** [comment]
This was in production - only a few min ago.

**Comment by joshuawilson** [comment]
just updated prod, please try again

**Comment by ldimaggi** [comment]
Just tried - still about the same speed:

![screenshot from 2018-02-14 16-09-29](https://user-images.githubusercontent.com/642621/36228152-750ad432-11a1-11e8-92d4-8a5d1926d721.png)

**Comment by andrewazores** [comment]
I notice you have your cache disabled while the dev console is open. How much of that 2.3-2.4MB transferred is actually unique to the Deployments page and how much of it is common OSIO code paths, and how long does refreshing the page take if chunks can be cached? How do these numbers compare to other pages?

**Comment by ldimaggi** [comment]
With caching disabled - the time to refresh the page is about 10 seconds.

With caching enabled, the time is about 11 seconds.

**Comment by aptmac** [comment]
Is that using a browser refresh? Or simply loading the page from another page?

I did a bit of digging using the Planner page as a guinea pig to test against the deployments page, here's what I got:

- Loading of Deployments from another page: just under 3 seconds
- Hard refresh of Deployments (cached): 21.47s, 26.9 KB transferred
- Hard refresh of Deployments (no-cache): 23.27s, 49.5 MB transferred
- Loading of Planner from another page: just over 4 seconds
- Hard refresh of Planner (cached): 21.35s, 26.8 KB transferred 
- Hard refresh of Planner (no-cache): 22.95s, 53.5MB transferred

From what I can see, refreshing an OSIO page using the browser (even the profile takes ~12 seconds for me) requires more work than simply loading the required information.

**Comment by ldimaggi** [comment]
That's interesting! I was doing a browser refresh. So - this is a more general problem. 53 seconds for the Planner?

**Comment by aptmac** [comment]
Errrr, those values I saw were a lot higher because I was looking at a local build targeting prod, my mistake. 

However, looking at prod, there is still a large amount of time being spend loading the page on a browser refresh. For example, refreshing the browser on the Planner page took 9 seconds and 2.8 MB (if uncached). Likewise, the Deployments page took almost the same amount of time (~9 seconds) and data to load (~2.5 MB).

**Comment by jiekang** [comment]
@ldimaggi

This is a common issue with Angular applications and slow initial page load time. I'm not sure how much tuning has been done before. Basically, a reload of the page constitutes a reload of the application and you should see long reload times on all pages.

**Comment by jiekang** [comment]
Can the issue be updated to reflect that this affects the entire f8-ui application? I'd like to remove it from being tracked under #287.

**Comment by joshuawilson** [comment]
I agree, I have updated it too.

**Comment by aslakknutsen** [comment]
Related https://github.com/fabric8-ui/fabric8-ui-openshift-nginx/pull/17

**Comment by alexeykazakov** [comment]
Outdated.
