### ISSUE TITLE
[Bug] Builds aren't complete "probably due to API whitelisting:sandbox.RejectedAccessException"

### ISSUE THREAD

**Issue by naina-verma** [openshiftio/openshift.io#227]
[Bug] Builds aren't complete "probably due to API whitelisting: org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException"

> git rev-list b5c37a97a783710fe7b9070d7dccaa580b6392fd # timeout=10
[Pipeline] echo
WARNING: Failed to invoke Environments.namespaceForEnvironment(environment) probably due to API whitelisting: org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: unclassified method java.lang.Class namespaceForEnvironment java.lang.String
[Pipeline] echo
WARNING: Failed to invoke Environments.namespaceForEnvironment(environment) probably due to API whitelisting: org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: unclassified method java.lang.Class namespaceForEnvironment java.lang.String
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
All nodes of label ‘maven.naina_verma_testingspace_master.10’ are offline
![screenshot from 2017-06-13 12-38-35](https://user-images.githubusercontent.com/19172870/27070165-67f42eb6-5035-11e7-8cd6-e47438bfa2ca.png)

**Comment by almightytest** [comment]
those warnings go away in the next Tenant release. I don't think thats any reason why the build isn't being started though.

I suspect it might be this is an old build from when jenkins was ran before; might be worth killing this job and restarting?

**Comment by joshuawilson** [comment]
You will need to clean up your old builds. With this being fixed in the new tenant release, I'm closing it.
