### ISSUE TITLE
Getting Started - Service and Unit Tests

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#2274]
### User Story: 
As a OSIO user I will be able to see the new flows of forge wizard (OSIO) as per new UXD. [Quick Start flow]

### Description:
Currently, in OSIO we don't have mission flow. With this addition, it helps us to merge the flow from Launcher (i.e the mission, tech stack flow and others).

### Acceptance Criteria:
OSIO user should be able to select mission, technology stacks and then can proceed with selecting release strategy, Authorize Git Provider.

##### Screen 1 (Missions) [Arun]
- [x] -  Mock service response as per swagger `/booster-catalog/missions`
- [x] - Test mock service with UI and make necessary changes if needed
    - [x] - Integrate with actual end-points
    - [ ] - Unit Test Cases
        - [ ] - Test Component
        - [ ] - Test Service
    - [x] - Toggle runtimes based on selection of mission.

##### Screen 1 (Runtimes) [Jai]
- [x] - Mock service response as per swagger `/booster-catalog/runtimes `
- [x] - Test mock service with UI and make necessary changes if needed
- [x] - Integrate with actual end-points
- [ ] - Unit Test Cases
    - [ ] - Test Component
    - [ ] - Test Service
    - [x] - Toggle missions based on selection of runtimes.

##### Screen 2 : Select Target Environment ( in case of OpenShift.io shouldn't be visible) [Jyasveer]
- [x] Handling UI changes
- [ ] Test cases to validate the flow

##### Screen 3 : Select Release Strategy [Jai]
- [x] - Mock service response as per swagger `/services/jenkins/pipelines`
- [x] - Test mock service with UI and make necessary changes if needed
- [ ] - Unit Test Cases
    - [ ] - Test Component
    - [ ] - Test Service

##### Screen 4 : Authorize Git Provider [Jai]
- [ ] - Services integration
    - [x] - Link github from OSIO using existing providerService
    - [x] - Consume gitHubToken from ngx-login-client
    - [x] - Creating service for getting user info
    - [x] - Creating service for getting user Orgs
    - [x] - Creating service for getting user repos
- [x] - Test mock service with UI and make necessary changes if needed
- [x] - Form request payload to make service call with git meta info
- [ ] - Unit Test Cases
    - [ ] - Test Component
    - [ ] - Test Service

##### Screen 5 : Confirm Application Summary & Setup [Jyasveer]
- [x] - Form request payload to make service call with all info `osio/launch`
- [x] - Next step based on response
- [ ] - Unit Test Cases
    - [ ] - Test Component
    - [ ] - Test Service

##### Screen 6 : Next Steps: Set Up New Application[Jyasveer]
- [x] - Next step based on response
- [ ] - Unit Test Cases
    - [ ] - Test Component
    - [ ] - Test Service

##### UI Tasks (UX related)
- [x] - Fix existing tests for each component
- [ ] - Runtime & Missions
    - [x] - Card title border need to be removed
    - [x] - Cancel has to be button

- [ ] - Target Environment
    - [x] - Card click should bind radio selection
    - [x] - Card selection highlight as per UX

- [ ] - Pipeline Screen
    - [x] -  Accordion list not opening in single click

- [ ] - Git provider
    - [ ] -  Login and authorize flow
    - [ ] -  Validation of repo name

**Comment by bartoszmajsak** [comment]
Shouldn't the tests be written together (if not first, but that's broader discussion) with the production code, not after? Doing it after is harder and also makes you miss the right moment to think about the design, making the code more modular and refactoring opportunities.

As for mocking external services please have a look at the concept of Contract Testing and [pact](https://docs.pact.io/) in particular. Having this in place we can ensure that client expectations (ui) are fulfilled by the backend without a need to call the actual service (so from unit tests). Both sides can use the same contract to validate. 

Benefits: fast feedback loop is one thing, but it also can serve as a communication / documentation platform. I can help you guys getting this setup. /cc @gastaldi @edewit

**Comment by arunkumars08** [comment]
Closing this as the work is being tracked here - https://github.com/openshiftio/openshift.io/issues/2440
