### ISSUE TITLE
Revamp UI : Dependency Editor

### ISSUE THREAD

**Issue by sanketpathak** [openshiftio/openshift.io#2275]
User Story:

As a OSIO user I will be able to see UI of Dependency Editor (OSIO) as per  UX Design.
https://redhat.invisionapp.com/share/4EFV8QUSPUD

Description:

Allowing the user to edit (add/remove) the project dependencies once he selected one of the boosters in the project creation wizard and providing stack report of the project he is building.
Showing recommendations on the dependencies user has selected.

Task List:

- [x] Displaying project info like metadata  etc. in `Current Project & metadata section`
    - [x] Displaying booster name and version with icon.
    - [x] Metadata information in form of box.
- [x] Allowing user to choose different dependencies like web etc. in `Add Dependencies section` 
    - [x] Search bar to search different dependencies with autocomplete facility.
    - [x] Area to show "selected dependencies" selected from searching or from Insights.
    - [x] Current Dependencies in form of labels .
- [x] Suggested companion packages by analytics insights section
    - [x] Packages are displayed in generic design suggested by the UX team which can be used in add dependencies section
    - [x] Click functionality for action buttons so that by clicking user can mark it to the add dependencies section or can remove it from the insights section.
- [x] To show CVE and security issue in `Security` section
    - [x] Making a card to show security health of project with a top-right flag to show condition of project.
- [x] To show License related information and issues  in `License` card
    - [x] Showing license name and other info in the form of card like security one.
- [x] Choosing additional dependencies from `Choose Dependency` modal
    - [x]  To show a modal through a `Browse all dependencies` button
    - [x] Choose Dependencies Section to see and add more dependencies which will be added to the "Recently added dependencies" part of the "Add Dependencies" section.
- [x] Proceeding to next section of OSIO flow through button.

**Comment by GeorgeActon** [comment]
@sanketpathak Is this story complete? All boxes are checked off so it looks like it is complete.

**Comment by sanketpathak** [comment]
I'm closing this user story since new revamped ux is introduced . The left over from this story is either redundant or are introduced in new design.
For reference refer to this story #2489
