### ISSUE TITLE
Pipeline page on https://openshift.io is corrupted - build pipelines cannot be promoted

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2276]
Steps to recreate:
* Create new quickstart, select release, stage, run as deployment strategy
* Observe the pipeline page display:

![screenshot from 2018-02-15 14-03-53](https://user-images.githubusercontent.com/642621/36275628-5caabbce-1259-11e8-89b1-0522ca00e629.png)

![screenshot from 2018-02-15 13-53-16](https://user-images.githubusercontent.com/642621/36275629-5cb71f5e-1259-11e8-9456-5b85f2bdc9b9.png)

Workaround - Promote the build to stage and run from the Jenkins log or the OSO console.

**Comment by qodfathr** [comment]
Is this a dupe of #2034? (If yes, we need to reopen it...)

**Comment by ldimaggi** [comment]
Nope - diff issue - and I think that Josh just fixed it.

**Comment by ldimaggi** [comment]
Fixed in production.
