### ISSUE TITLE
The check for payload presence and its content is misplaced in f8a-license-analytics module stack_license.py

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#2279]
The check is placed at line 107:

https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/blob/master/src/stack_license.py#L107

But it must be performed anywhere before line 102 (+ would be better to check for the presence of 'packages' entry):

https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/blob/master/src/stack_license.py#L102

The reproducer can be seed here:
https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/pull/69

**Comment by sunilk747** [comment]
closing this issue as this is taken care of in this PR - https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/pull/79
