### ISSUE TITLE
Broken link for work items under profile section

### ISSUE THREAD

**Issue by navidshaikh** [openshiftio/openshift.io#228]
I have a task assigned under my team space. 
The work items are listed under profile tab.
If I click on any work item, it prompts `404`

![screenshot from 2017-06-13 17-55-20](https://user-images.githubusercontent.com/2510184/27082339-f985d902-5061-11e7-83b0-9276e4875042.png)

**Comment by joshuawilson** [comment]
I just tried it and it works for me. Try a hard refresh ctr + shift + r

**Comment by joshuawilson** [comment]
If you have deleted the space that help that issue then you are seeing a remnant. A hard refresh should clear it up.

**Comment by navidshaikh** [comment]
It seems to be resolved for me.
