### ISSUE TITLE
Analytics Support for Boosters especially Redhat GA versions

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#2282]
Current boosters available at launch.openshift.io has upstream and downstream releases bundled. Since Redhat GA versions are not available on `maven central` (which our anlytics relies on to fetch the artifact from), we will have to ingest these pacakges from `redhat maven` in order to make the analytics available for the said dependencies.

**Comment by msrb** [comment]
This may seem trivial on surface, but adding support for 3rd party repositories (including our own RH Maven repository) will be far from trivial and it will require changes in many (all?) subsystems. It will also affect how we give recommendations.

Simple example:
The latest version of package X in Maven Central is V, but 3rd party Maven repository has version V+1. We will start recommending V+1 as the latest version, but if we do that, we should also tell developers that they need to enable the 3rd party repository first. I don't think we want to that.

**Comment by msrb** [comment]
Let's discuss this in cabal tomorrow.

**Comment by maxandersen** [comment]
I can imagine it being tricky, but this would need handling though as supported dependencies != community dependencies.  

This issue would also exist for container images where customers would be using red hat registries rather than i.e. dockerhub.

**Comment by maxandersen** [comment]
> Let's discuss this in cabal tomorrow.

i missed this - are there any followups ? I would like to attend and can help explain the workings of how this works for at least maven in red hat.

**Comment by msrb** [comment]
@maxandersen 

Thanks Max, we hold cabals irregularly, but I will definitely invite you to the next one :+1:

**Comment by krishnapaparaju** [comment]
@maxandersen Cabal is on devtools calendar, have forwarded the invite to you..

**Comment by miteshvp** [comment]
Closing this as new one is created https://github.com/openshiftio/openshift.io/issues/2481

**Comment by maxandersen** [comment]
> @maxandersen Cabal is on devtools calendar, have forwarded the invite to you..

yes I know when it is there - which cabal will you have this as a topic ?

**Comment by msrb** [comment]
@maxandersen ah, we could have discussed this today actually :/ I think we should set up a meeting dedicated just to this topic. I will try to schedule something later this week, if you guys are OK with that.
