### ISSUE TITLE
Planner: long iteration name overflows the column

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#2283]
1. open https://openshift.io/openshiftio/openshiftio/plan
2. navigate to `EE and Platform Tests` iteration
3. check the text in `Iteration` column

![osio_iteration_overflow](https://user-images.githubusercontent.com/445100/36309006-1fef09cc-1323-11e8-97d3-96c87bfcf304.png)

**Comment by ppitonak** [comment]
Still reproducible in prod

**Comment by SMahil** [comment]
This issue has been fixed
