### ISSUE TITLE
Planner: icon next to item title does nothing

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#2286]
1. open any project in planner with at least one item
2. hover over a work item
3. click on icon next to the work item title
![osio_item_icon](https://user-images.githubusercontent.com/445100/36310085-37cac7da-1327-11e8-8ee2-f6a467c88563.gif)

**Comment by sahil143** [comment]
@ppitonak @nimishamukherjee I'm not able to reproduce this. Can you verify?

**Comment by ppitonak** [comment]
@sahil143 I tried it again... it works fine in latest Chrome but doesn't work in Firefox 58

**Comment by debloper** [comment]
In the code, from `planner-list.component`
```
  onDetailPreview(id): void {
    event.stopPropagation();
    this.router.navigateByUrl(
      this.router.url.split('plan')[0] + 'plan/detail/' + id,
      { relativeTo: this.route }
    );
  }
```

From angular-router documentation, `router.navigateByUrl` is supposed to have the full URL only, and needn't have `relativeTo`. I'm unsure if that's causing the issue here, but this may lead to unusual behaviors in any case.

**Comment by nimishamukherjee** [comment]
Fix is on prod. Please re-open if you face the issue.
