### ISSUE TITLE
Planner: clicking on creator or assignee doesn't do anything

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#2287]
1. open any project in planner with at least one item
2. hover over creator/assignee avatar - mouse cursor changes
3. click on the avatar

Result:
* nothing happens

Expected:
* something happens, although I'm not sure what - open all items the given user created/are assigned to him? open his profile?
* if no action is expected, mouse cursor should not change

**Comment by nimishamukherjee** [comment]
@sahil143 disable the mouse cursor

**Comment by ppitonak** [comment]
Fixed for `Creator` field but NOT for `Assignee` field

**Comment by nimishamukherjee** [comment]
Raised PR https://github.com/fabric8-ui/fabric8-planner/pull/2763 to remove cursor for assignees
