### ISSUE TITLE
Planner: add item button next to items that cannot have children

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#2289]
1. open any project with at least one work item that cannot have children, e.g. `Task`

Result:
There is grey `+` icon which is inactive (correct behavior). It's easy to understand the meaning of this icon if there are tasks both that can and cannot have children (blue vs. grey `+` icon). However, it's confusing in views with only work items types that cannot have children, I suggest to stop using grey/inactive icon completely.

![osio_plus_icon](https://user-images.githubusercontent.com/445100/36310806-7885412c-1329-11e8-97f3-4da6fc5b5d55.png)

**Comment by muruGanesan** [comment]
@ppitonak , If I understand correctly,  you are suggesting to remove the (+) [add icons] for the last nodes i.e. work item type 'Task' - please confirm me the same.

**Comment by ppitonak** [comment]
@muruGanesan yes

**Comment by muruGanesan** [comment]
@ppitonak, We considered multiple aspects of the visual guidance and then decided on the current implementation. But still, we will evaluate your point and get back.  
NOTE: we may not change the current implementation if we don't find the best alternative solution.

**Comment by muruGanesan** [comment]
@ppitonak, We considered multiple aspects of the visual guidance and then decided on the current implementation. But still, we will evaluate your point and get back.  
NOTE: we may not change the current implementation if we don't find the best alternative solution.

**Comment by nimishamukherjee** [comment]
@muruGanesan any update on this.
We can close this if we are not changing the implementation.

**Comment by muruGanesan** [comment]
We are not changing any icons at this moment. We will close this issue
