### ISSUE TITLE
Getting started does not work with Safari

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#229]
I tried to launch OpenShift.io from Safari and followed the sign up process and the linking of the required accounts. I ended up on the page with the "Get Started" link:

![getting-started](https://user-images.githubusercontent.com/296354/27105068-7cf8a98c-508e-11e7-9f14-dabcd537bf8e.png)

Once I press the button, the following page stays empty:

![empty](https://user-images.githubusercontent.com/296354/27105086-8bb486f8-508e-11e7-999a-1e782d06e22c.png)

Took me a while to figure out that this is a browser thing. Doing the same in Firefox got me to the OpenShift.io homepage. 

Is Safari not supported? And if not, should I not be notified?

**Comment by joshuawilson** [comment]
Currently we are only testing against Chrome. We plan to support the other browsers moving forward.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1516

**Comment by hferentschik** [comment]
Maybe this should be mentioned somewhere. One could even have a little popup at some early stage telling me that my browser is not supported. It would have saved me some time, figuring out why I literally see nothing.

**Comment by joshuawilson** [comment]
Here is a list of support browsers and their versions. https://github.com/openshiftio/openshift.io/wiki/Supported-Browsers
