### ISSUE TITLE
Planner: iteration - set start/end date doesn't do anything

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#2292]
1. open any project in planner
2. create a new iteration with no start/end date
3. click `Set start date` in left panel

Result:
* nothing happens

Expected:
* either I can set the date or it is not displayed at all

![osio_date](https://user-images.githubusercontent.com/445100/36311329-3d4fc576-132b-11e8-9a45-8ef28f8429d5.png)

**Comment by ppitonak** [comment]
Update: clicking on `Set start date` or `Set end date` selects the iteration

**Comment by nimishamukherjee** [comment]
@Preeticp any suggestions on what we can change the text to?

**Comment by Preeticp** [comment]
@nimishamukherjee We can either change the text from: Set start date - Start end date to: 
* Start date - End date : But this could still mislead users into thinking they could click on the text to add the dates. So we may need an infotip in addition saying: Use the options menu to edit the iteration to add start and end dates. 

Or if we have enough place, use:
* No start date set - No end date set : This is more clear, but I would suggest having the above infotip here too.

Also, if a user does not add Start and End dates, how about simply not mentioning anything there?

**Comment by ppitonak** [comment]
I vote for not displaying anything.

**Comment by nimishamukherjee** [comment]
![dates](https://user-images.githubusercontent.com/1892722/48045947-6f292680-e1b8-11e8-9619-e04d3768e644.png)
@ppitonak @Preeticp have a look at the screenshot
I have tried various combination
- S1 has a start date and an end date
- S2 does not have a start date and an end date
- S3 has only the start date
- S4 has only the end date 

I find S3 and S4 a bit confusing. Thoughts?

**Comment by Preeticp** [comment]
@nimishamukherjee I think S2 in the first image makes the most sense, when user sets no date.
If we give users the option to set one of the dates (either start/end), then how about Start date: Nov 1, 2018 or End date: Nov 10, 2018

**Comment by nimishamukherjee** [comment]
Fix is on prod.
