### ISSUE TITLE
Planner: hide/remove non-functional search input

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#2293]
1. open any project in planner
2. there is an input box in left bar that doesn't do anything

Expected:
* either it should work or it shouldn't be displayed

![osio_search](https://user-images.githubusercontent.com/445100/36311438-9958306a-132b-11e8-9604-1513100cd9a8.png)

**Comment by nimishamukherjee** [comment]
Fix on prod preview

**Comment by ppitonak** [comment]
Looks ok in prod-preview
