### ISSUE TITLE
Planner: clicking on label doesn't filter properly

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#2295]
1. open any project with an item with a label and another item with different/no label
2. click on a label

Result:
* URL changes but the view contains also items without this label

![peek 2018-02-16 15-16](https://user-images.githubusercontent.com/445100/36311747-9146af7c-132c-11e8-9bde-59ef3732224b.gif)

**Comment by nimishamukherjee** [comment]
Fix on production.
