### ISSUE TITLE
GitHub project gets created without info message

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#230]
When going through the steps to setup a sample project with OpenShift.io, I selected to create a new sample project (Wildly Swarm based). I continued through the wizard and only after the project was full created, I noticed on the Codebases list, that an actual repository on Github got created. 

IMO this should not happen without an information dialog and confirmation. I was fully in evaluation mode and would for example have chosen different names, had I known that a GitHub repository gets created right away.

**Comment by joshuawilson** [comment]
We can add a warning to the wizard but the system needs to use real names to validate that it can do what it needs to.
@catrobson can you please look at this?

**Comment by catrobson** [comment]
Agreed that we need to be clearer to the user about what we're doing during the wizard creation process.  I'll look at this as part of the wizard improvements we tackle next week.

**Comment by qodfathr** [comment]
App Wizard is more explicit about what is happening. Closing.
