### ISSUE TITLE
Users on the new cluster are directed to an invalid URL when attempting to "View Log" for the Jenkins build log for a build

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2300]
Steps to recreate:
* Login to https://openshift.io as a user configured on the new cluster
* Create a new space, new quickstart - observe the build pipeline start
* Attempt to view the build log
* The link provided to the user for the build log is similar to:
https://jenkins.openshift.io/job/username/job/spacename/job/master/1/console

This URL returns this error:
{"Errors":[{"code":"500","detail":"Get http:///: http: no Host in request URL"}]}

The correct URL for the log can be located by the user in the OSO console and is similar to this:
https://jenkins-username-jenkins.b542.starter-us-east-2a.openshiftapps.com/job/username/job/spacename/job/master/1/console

**Comment by mmclanerh** [comment]
@ldimaggi  update tenant -- seems like this is fixed now?  my test is redirecting properly:  

https://jenkins-mmclane-osiotest2a-jenkins.....starter....openshiftapps.com/

**Comment by ldimaggi** [comment]
Verified fixed in production - closing.
