### ISSUE TITLE
Configure Deployments widgets

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#2301]
On the Analyze dashboard is a widget titled `Deployments`. This is the `Environments` widget renamed and relinked. 

The dashboards are all getting redesigned. But we need to get this one operational for now. The App/Env widget was made out of date with the removal of the App/Env pages. 

The old design should be good enough since everything is getting redesigned this train. It showed the application name and version number with a link to the app. Please have it reference the Deployments info instead of the Env info.

**Comment by catrobson** [comment]
Last set of UX designs.  This does not reflect the Deployments tab as we currently have it.  https://redhat.invisionapp.com/share/4WB1WXGK9#/screens/228703836

Would suggest, as Joshua says, that we use the "Deployments" header to link to the deployments page.  For each deployment, have the application name/version link to the app itself.  

We'll be replacing this with a more advanced codebases/pipelines/deployments combined widget soon - designs underway here:  https://redhat.invisionapp.com/share/DQFLCG4G9YK#/280720761_2_SpaceDash
