### ISSUE TITLE
Enable force_pull on Token API to validate Cluster Token on startup

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#2304]
This should help verifying that the token is valid.

**Comment by alexeykazakov** [comment]
BTW if you call /api/token with force_pull: `auth.openshift.io/api/token?for=openshift&force_pull=true` or 
get token status via `auth.openshift.io/api/status?for=openshift&force_pull=true` then Auth will verify token for you. With this param the auth service will try to load the user profile from OSO, so if 200 OK is returned then the token is valid.

**Comment by xcoulon** [comment]
thanks for the info, @alexeykazakov ! So, @aslakknutsen, do we still need the `whoami` function in `tenant`, then ?

**Comment by aslakknutsen** [comment]
@alexeykazakov A yeah, good point! @xcoulon hmmm.. Can't think of a case on top of my head. Let's rename this issue to enable force_pull on Cluster Tokens.

**Comment by xcoulon** [comment]
@aslakknutsen ok, thanks! So I'll remove the `WhoAmI` func and call the `api/token` endpoint on  `auth`, instead!
