### ISSUE TITLE
Creating new Che workspace failing on https://openshift.io (in production and prod-preview)

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2308]
This problem has been seen in the past and is back again. When creating a new Che workspace, this error is being seen: Start of environment 'default' failed. Error: Failed to get the ID of the container running in the OpenShift pod

Production:

![screenshot from 2018-02-19 21-50-48](https://user-images.githubusercontent.com/642621/36405645-c2218a00-15bf-11e8-91f4-5d69ac6aa3f2.png)

Prod-preview:
![screenshot from 2018-02-19 22-21-03](https://user-images.githubusercontent.com/642621/36406218-4049e6ae-15c3-11e8-991d-e957a0a6d2c4.png)

**Comment by ldimaggi** [comment]
Issue found/encountered by EE tests.

**Comment by kbsingh** [comment]
is this in prod or prod-preview ?

**Comment by ibuziuk** [comment]
@ldimaggi please provide more information - openshift events, che-server logs.

**Comment by ldimaggi** [comment]
Closing - the problem is not reproducible this morning. It was reproducible ~8 hours ago - was something changed? Thx!
