### ISSUE TITLE
Failed to find Jenkins URL: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by naina-verma** [openshiftio/openshift.io#231]
While adding pipeline to the space with updated tanent , this error occurred 

Video : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COSUp5WUtSOUE4ek0/view?usp=sharing

Log: https://gist.github.com/anonymous/11475c9173bf7a845e0d7740b6fcf651
![screenshot from 2017-06-15 15-40-15](https://user-images.githubusercontent.com/19172870/27179121-dd5df7a2-51ea-11e7-90b6-bbfb96845701.png)
![screenshot from 2017-06-15 16-07-52](https://user-images.githubusercontent.com/19172870/27179122-ddb0eaac-51ea-11e7-82fd-cce774325018.png)
![screenshot from 2017-06-15 16-08-35](https://user-images.githubusercontent.com/19172870/27179123-ddb28326-51ea-11e7-8c24-5d4326f0f563.png)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1524

**Comment by joshuawilson** [comment]
This hasn't been seen in a while. Closing, if you are still seeing this issue please reopen.
