### ISSUE TITLE
Current graph queries could be missing some package versions 

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#2313]
_From @tuxdna on February 19, 2018 18:16_

This is what I have noticed on production for few packages, for example `org.wildfly.swarm:odata`:

All analyzed versions for this package (using bookkeeping api):

```
    "analysed_versions": [
      "2012.12.0",
      "2017.12.0",
      "2017.12.1",
      "2018.1.0",
      "2018.2.0",
      "2018.2.0.Final"
      ]
```

Which of these versions are not yet synced to graph ? ( using graph_sync pending API):

```
{
  "data": [
    {
      "ecosystem": "maven",
      "name": "org.wildfly.swarm:odata",
      "version": "2017.12.0"
    }
  ]
}
```

Even after invoking the graph sync API, I still get the pending version as not synced to graph.

```
{
  "data": {
    "count_imported_EPVs": 0,
    "epv": [
      {
        "ecosystem": "maven",
        "name": "org.wildfly.swarm:odata",
        "version": "2017.12.0"
      }
    ],
    "message": "Nothing to be synced to Graph!"
  }
}
```

Notice the message above `"count_imported_EPVs": 0,`. This clearly means that we have atleast one of three issues:

 * Graph queries used to detect if a package is present in graph are incorrect
 * Graph queries used to actually sync this package to graph are incorrect
 * There is some other issue causing this behavior

_Copied from original issue: fabric8-analytics/fabric8-analytics-data-model#99_

**Comment by msrb** [comment]
_From @miteshvp on February 20, 2018 3:13_

> There is some other issue causing this behavior

@tuxdna - acutally the above is correct. I do not see any data in our S3 bucket for the said version of the package. Below is the snapshot for version data

<img width="199" alt="image" src="https://user-images.githubusercontent.com/17736013/36406009-daacad5c-1619-11e8-96e6-46c9352e3d3f.png">
Also, the package level data is in error state.
Maybe you want to try and analyze this package again so that we get the data in S3 and then sync to graph.

**Comment by msrb** [comment]
@tuxdna how do we obtain the list of packages that need to be synced? We indeed have no data for this packages in S3. I think what could have happened here is that we were analyzing this package, but the analysis was interrupted before the data reached S3. Therefore the record in RDS, but no data.

**Comment by tuxdna** [comment]
@msrb: We check `sync2graph` attribute of Version table. 

https://github.com/fabric8-analytics/fabric8-analytics-data-model/blob/8ea3c3bc023252701a6bd4ae4e84eb0629355d40/src/data_importer.py#L229-L258

By default the `synced2graph` attribute is set to `FALSE` and is only marked as `TRUE` we have added that version's data to graph as well.

https://github.com/fabric8-analytics/fabric8-analytics-data-model/blob/8ea3c3bc023252701a6bd4ae4e84eb0629355d40/src/data_importer.py#L109-L113


We could check if the data infact reached s3. How do we check that ?

**Comment by tuxdna** [comment]
I am looking for some marker in database that is set only when all workers for a package-version are completed.

**Comment by msrb** [comment]
I will move this forward.
