### ISSUE TITLE
Cannot access OSO console for prod-preview

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2317]
A 502 error is returned:  console.free-stg.openshift.com is currently unable to handle this request.
HTTP ERROR 502

**Comment by mmclanerh** [comment]
this is covered in hk 1336.

**Comment by ldimaggi** [comment]
Closing - verified on prod-preview:

![screenshot from 2018-02-25 10-13-05](https://user-images.githubusercontent.com/642621/36643038-899b7688-1a14-11e8-97b1-912cfc81bf28.png)
