### ISSUE TITLE
Planner Team does not own deployment to prod

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#2321]
# Abstract

* Planner team does not own deployment to prod for the UI. We do not own the full stack and are unable to make assumptions on features appearing on prod. We have a standing dependency with other teams to get new Planner UI versions deployed.

* There is a high package-level dependency between different UI deliverables by different teams, resulting in a high amount of work needed to resolve frequent dependency issues, sideeffects and conflicts.

* The architecture used for the UI and the UI integration is highly problematic, leading to a very complex dev, test and deploy setup that leads to frequent issues and huge velocity losses. This issue is connected to the above dependency/integration issue(s).

* When Planner wants to deploy a change, the whole UI application stack has to be deployed, something that is unacceptable in a high-scaling environment where deployment risk is an important aspect.

# Details

What we are building for the frontend is basically also a monolithic application, with all UIs for all functional areas combined into one big single page application. We made some serious and painful progress on segmenting the logical parts of the UI into Angular component libraries. The problem is that for example the Planner is not a simple component library like any other Angular component collection, it is merely a full application contained in a component library that performs requests against a backend, has a logical flow from ui component to ui component and has a navigation flow on its own.

What we are already experiencing are problems with that approach: the Planner as a library is much more complex than a “normal” component library, bringing in much more dependencies. The “monolithic” combined application is very complex, both in the runtime as well as the build. Isolated problems with singular dependencies for example in the Planner are able to bring down the whole application either on build time or runtime. In addition, due to the already high complexity of the Angular build with transpiling, module loader and other complex concepts included is an increasing difficult to find to cause of problems.

For the performance, the monolithic approach is also critical. The Planner alone brings in around 1000 dependencies and we already need advanced techniques (like tree shaking) to get the artifact size and execution times on the browser contained.

Furthermore, we’re just at the beginning of the product’s lifecycle, with much more features, complexity and code expected to be added in in the years to come. We are already struggling with artifact and development complexity here and we can expect this is getting worse over time.

So, what alternatives do we have for the current approach? Using iframes or other fragment consuming techniques may not be acceptable due to several other technical problems introduced with them, like problems on mobile devices, problems with the Angular framework when consuming external fragments etc.

What I propose would be a similar approach like I propose on the backend: decouple the logical parts and run them individually, connecting them by seamless session handover or sharing. The Planner would be a standalone application, with a standalone web application being served. The request routing, a shared session/AuthN and a common component library for creating the visual frame components would provide the seamless integration from the user point of view. With this approach, individual components such as the Planner, the Platform UI or other parts can be individually built and deployed, keeping the overall complexity small. Also, with this setup, the integration of existing components using different sets of technology is much easier (like Jenkins).

**Comment by michaelkleinhenz** [comment]
See https://docs.google.com/document/d/1fq3E5UQ5jVsHG6UNOedWmlAm-y_1MjZmi0WmBoh5tik/edit for some notes from the ongoing discussion. Results should probably end here.

**Comment by michaelkleinhenz** [comment]
As of discussion in the SoS, reducing to SEV-2, but be aware that this has the highest priority for Planner and is the reason for being red.

**Comment by maxandersen** [comment]
Thanks for writing it up @michaelkleinhenz !

One comment for now on this:
> Also, with this setup, the integration of existing components using different sets of technology is much easier (like Jenkins).

lets just be clear that goal is to actually *NOT* expose jenkins or even che as separate apps. If you look at jenkinsn at the moment it is also a good example of why having it separate is bad.

**Comment by joshuawilson** [comment]
Thanks for adding another reason to build the extensiblity framework that would fall under https://github.com/openshiftio/openshift.io/issues/354

**Comment by maxandersen** [comment]
I just recalled that we actually have  a specific label to call out critical dep issues - I think that is more apropriate and avoids the whole is it sev1 or 2 or even sev at all.

**Comment by ppitonak** [comment]
> lets just be clear that goal is to actually NOT expose jenkins or even che as separate apps. If you look at jenkinsn at the moment it is also a good example of why having it separate is bad.

Can somebody explain me what this means?

**Comment by joshuawilson** [comment]
now that we have moved the UI to the monorepo this is fixed.
