### ISSUE TITLE
Can create pipeline in another user's space

### ISSUE THREAD

**Issue by aptmac** [openshiftio/openshift.io#2324]
This could be related to: https://github.com/openshiftio/openshift.io/issues/1122

Here are two OSIO accounts side by side, for simplicity's sake I'll refer to the page on the left as user A, and the page on the right as user B. As user A, I can view user B's space and create a pipeline that shows up on the deployments page. User B does not see this, but it is view-able to User A viewing User B's contents.

Here are some pictures to better illustrate what I'm seeing:

Here is (left) User A looking at User B's analyze page, and (right) User B looking at their own analyze page.
![analyze](https://user-images.githubusercontent.com/10425301/36499134-514618e6-170e-11e8-88a8-10725621549e.png)

Here is (left) User A looking at User B's Create>Codebases page, and (right) User B looking at their own Create>Codebases page.
![codebases](https://user-images.githubusercontent.com/10425301/36499074-27b0c1e8-170e-11e8-980d-0deafa459143.png)

User A goes to Analyze>"Add to Space" and uses the wizard to create a new Vert.X HTTP booster with the name of "space1". The wizard continues to the final screen, and reports an error (but creates the repo in User A's [GitHub account](https://github.com/ume-studios/space1) [0] anyways). Space1 now shows up in the pipelines page, and can be built. 
(Side-note: User B's cmpt479 is a private repo that I had used for some school work and is not a maven project, so it won't build properly; I just wanted to see what happened if I added a private repo).
![pipelines](https://user-images.githubusercontent.com/10425301/36499085-307f30ac-170e-11e8-9c70-bf572a8f6ab3.png)

After User A has built the pipeline, it appears in the deployments page. User A cannot see User B's other deployments, but can see 'space1'. User B can see their deployments, but cannot see 'space1'.
![deployments](https://user-images.githubusercontent.com/10425301/36499092-34415f3a-170e-11e8-8331-dde83d606b09.png)

[0]  https://github.com/ume-studios/space1

**Comment by joshuawilson** [comment]
duplicate of https://github.com/openshiftio/openshift.io/issues/1122
If you check github you will see that B creates in B's github while looking at A's space. The UI appears to allow it but it is not possible. The UI needs to be cleaned up to prevent this as it is confusing.

**Comment by aptmac** [comment]
I wasn't sure it was recorded any where that in addition to creating the repo you can actually build the pipeline and visit the application [1], it even shows up in User A's OSO Console.

[1] http://space1-apmacdon-stage.8a09.starter-us-east-2.openshiftapps.com/

**Comment by aptmac** [comment]
@joshuawilson was nice enough to let me play around with his space, and I basically just recreated the above behaviour. I snapped a bunch of images to show the process I went through, and what I saw at each step. I'll add a short descriptor to each screenshot.

1. After visiting Gressland, I clicked the "Add to Space" button and added a new Vert.x HTTP booster called "notjoshsstuff". The wizard eventually hangs on this image and the browser console indicates a 403 permission error. However, in the pipelines widget (under the wizard) there is a build starting.
![1-wizard](https://user-images.githubusercontent.com/10425301/36506733-79b50474-1725-11e8-87ef-ddc5f4c51b36.png)
2. So I go over to the Pipelines page, and there isn't that exciting.
![2-pipelines-fresh](https://user-images.githubusercontent.com/10425301/36506734-79c82428-1725-11e8-9328-d8fae9d31f95.png)
3. But eventually it builds and asks for my approval to promote, so I do it.
![3-pipelines-approval](https://user-images.githubusercontent.com/10425301/36506737-79ddb1e4-1725-11e8-9afc-9b7c5fd8a789.png)
4. And now we have rolled out to Run.
![4-pipelines-finished](https://user-images.githubusercontent.com/10425301/36506738-79f06974-1725-11e8-9fa2-9188b67210e0.png)
5. I was already at my quota, so I had to scale down my other applications, so the deployments page originally greeted me with this:
![5-deployments-no-data](https://user-images.githubusercontent.com/10425301/36506739-7a08d2a2-1725-11e8-8e5b-5feaa0db3061.png)
6. And eventually the deployments page had data to display.
![6-deployments-final](https://user-images.githubusercontent.com/10425301/36506741-7aad1b96-1725-11e8-9696-65067d253f76.png)
7. Here's the OSO Console, showing notjoshsstuff along side my other applications. 
![7-oso-console](https://user-images.githubusercontent.com/10425301/36506743-7b25d464-1725-11e8-9067-48d04229e416.png)

**On another note** (not necessarily related to creating pipelines in other spaces, but relevant with respect to permissions), I was able to open a workspace in your codebases, edit the source, and hit run. Am I supposed to be able to do this? Do you think this would still work if the GitHub repo was set to private?

![1-codebases](https://user-images.githubusercontent.com/10425301/36507604-3f1d974c-1728-11e8-8563-8982ebc2f323.png)
![2-che-run](https://user-images.githubusercontent.com/10425301/36507614-4614d61e-1728-11e8-9a47-2ff13e7f8998.png)

**Comment by jiekang** [comment]
It looks like though you were in Josh's space, everything done was actually within your account. The UI will need some fixing but it looks like the backend and auth are behaving correctly.

**Comment by aptmac** [comment]
@jiekang, thanks for the insight!

**Comment by qodfathr** [comment]
@aptmac, today we do not permit you to link private repos.

**Comment by aptmac** [comment]
@qodfathr as in the UI shouldn't allow me to do it, or there isn't underlying functionality to handle them specifically? Because I have no troubles importing a private repo into my spaces at the moment.

**Comment by qodfathr** [comment]
@aptmac that's a bug. You should not be allowed to do it.

**Comment by aptmac** [comment]
This bug can be better tracked by other issues relating to what the UI should look like when viewing other user's spaces [[0]](https://github.com/openshiftio/openshift.io/issues/3634)[[1]](https://github.com/openshiftio/openshift.io/issues/3636). This issue doesn't concern actually creating pipelines in other users spaces as I had first thought, but rather that there is nothing in the UI from preventing you from thinking that is what you are doing.

[0] https://github.com/openshiftio/openshift.io/issues/3634
[1] https://github.com/openshiftio/openshift.io/issues/3636
