### ISSUE TITLE
Stack Report Dahboard card contents of licenses and insights need to be swapped

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#2325]
Currently the dashboard of a stack report shows three cards. Out of which summary for `Licenses` and `Insights` needs to be swapped. See below snapshot
<img width="867" alt="image" src="https://user-images.githubusercontent.com/17736013/36518911-7fff8384-17ae-11e8-84b6-b4014b034094.png">

**Comment by jyasveer** [comment]
fix is here https://github.com/fabric8-ui/fabric8-recommender/pull/441

**Comment by jyasveer** [comment]
closing as it is fixed
