### ISSUE TITLE
Closing stack report modal at space dash board screen disables entire screen

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2328]
Steps to reproduce (closing the stack report with MOUSE click DOES NOT reproduce this problem): 
<img width="1429" alt="screen shot 2018-02-22 at 1 19 31 pm" src="https://user-images.githubusercontent.com/15967765/36526359-f757ac5c-17d3-11e8-8a7f-32d1d8fedf97.png">

1. Open Stack report from 'stack report' link at space dashboard, all is good with this step, close the stack report with ESCAPE key
2. Go to pipelines screen and open the stack report , all is good with this step, close the stack report with ESCAPE key

3. Now back to space dashboard, stack report opens up, closing the stack report with ESCAPE key would freeze the entire UI screen.. Please check the screen shot:

**Comment by sivaavkd** [comment]
@jyasveer - I tried the steps, but could not reproduce the issue.  are you able to ?
cc @krishnapaparaju

**Comment by arunkumars08** [comment]
@krishnapaparaju I have tried the steps Krishna. Unable to reproduce it. 
Could you verify if it is still a problem?

**Comment by sivaavkd** [comment]
@krishnapaparaju - any update on this ? can you verify if this is still a problem ?

**Comment by aptmac** [comment]
I'm currently seeing this in production, I had filed it as another issue a couple days ago (so I've closed that one and re-opened this one).

I have made a gif to show exactly what I'm seeing:
![report-overlay-bug](https://user-images.githubusercontent.com/10425301/38994747-3e3f095a-43b5-11e8-8156-a8bec0f8ddac.gif)

If opening the report either by clicking the link or clicking one of the three cards, the dark screen overlay doesn't disappear when I close the modal. As a result, none of the page elements are click-able afterwards.

**Comment by jyasveer** [comment]
@aptmac does it happen even when you close the report modal with the close button ?

**Comment by aptmac** [comment]
@jyasveer Yes and no, I think this may be related to how the modal itself is opened.

If the modal is opened by clicking the "View complete stack report" link, then the overlay disappears as expected both when using the close button, or clicking a blank area outside the modal. 

However, if the modal is opened by clicking on either of the three cards for "Security Issues", "Licenses", or "Insights" then even closing the modal using the close button doesn't get rid of the overlay (and clicking outside of the modal doesn't close it either).

**Comment by arunkumars08** [comment]
Closing it as the changes are in production and things seem to work fine. Please feel free to re-open it in case it can still be seen.
