### ISSUE TITLE
Change in text: Replace 'Recommondations' with 'Insights'

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2329]
Please check the screenshot
<img width="861" alt="screen shot 2018-02-22 at 2 37 53 pm" src="https://user-images.githubusercontent.com/15967765/36529373-2be6b936-17de-11e8-9838-d37a9cedf9d8.png">

**Comment by jyasveer** [comment]
here is the fix https://github.com/fabric8-ui/fabric8-ui/pull/2564
