### ISSUE TITLE
[Bug]Build failed with "java.io.FileNotFoundException: /root/.mvnrepository/io/vertx/vertx-health-check/3.4.1/vertx-health-check-3.4.1.pom.part.lock "

### ISSUE THREAD

**Issue by naina-verma** [openshiftio/openshift.io#233]
Build failed with "Caused by: java.io.FileNotFoundException: /root/.mvnrepository/io/vertx/vertx-health-check/3.4.1/vertx-health-check-3.4.1.pom.part.lock "

Steps to reproduce 
- Create a space
- Add to space 
- chose Basic vertx 
This build fails due to error !
logs : https://gist.github.com/almightytest/2eeecafe969b165a6997f16fb59f440a

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1525

**Comment by joshuawilson** [comment]
This has not been seen in months, closing.
