### ISSUE TITLE
Frequent failures of e2e tests on production: /api/v1/liveness REST API call

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#2330]
In the last two days the success rate of e2e tests is lower than expected - just 78/100:
https://fabric8-analytics.github.io/dashboard/dashboard.html

Excerpt from log file:
https://ci.centos.org/job/devtools-test-end-to-end-prod-fabric8-analytics/1628/console

```
Scenario: Check the /api/v1/liveness response  # features/server_api.feature:18

    Given System is running                      # features/steps/common.py:38

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.openshift.io

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bayesian-jobs-bayesian-preview.b6ff.rh-idev.openshiftapps.com

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bayesian-gremlin-http-preview-b6ff-bayesian-preview.b6ff.rh-idev.openshiftapps.com

    When I wait 20 seconds                       # features/steps/common.py:125

    When I access /api/v1/liveness               # features/steps/server_api.py:11

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): recommender.api.openshift.io

    Then I should get 200 status code            # features/steps/common.py:74

      Assertion Failed: assert 504 == 200

       +  where 504 = <Response [504]>.status_code

       +    where <Response [504]> = <behave.runner.Context object at 0x7fdcc1ff9400>.response

Failing scenarios:

  features/server_api.feature:18  Check the /api/v1/liveness response
```

We got 504 status code before when the pod was frequently restored on openshift.

Please make sure whether this issue is related to issue #2323 found by @ldimaggi 

Note: I set `SEV1-urgent` because this issue affect our users.

**Comment by tisnik** [comment]
FYI: @jyasveer @msrb

**Comment by jyasveer** [comment]
@sivaavkd api e2e test cases is not somethiing i have worked on. This issue is for api e2e test cases. @tisnik is handling this from the very beginning.

**Comment by sivaavkd** [comment]
I understand @jyasveer.  Looks like these failures are because of #2323 and @tisnik already commented that these two may be related.  Please see if it the case or not.

**Comment by ldimaggi** [comment]
If this is the same bug - then it is also causing frequent/intermittent failures here:
https://ci.centos.org/view/Devtools/job/devtools-test-e2e-openshift.io-analyticstest-cluster-one/

**Comment by miteshvp** [comment]
@ldimaggi - do you have any build logs that you can share for the above failures? My guess is these two may not be related since Jenkins does not validate the response from stack-analyses. It will still show build as a success even if it gets 504 from stack-analyses.
cc @tisnik @sivaavkd @samuzzal-choudhury @jyasveer

**Comment by tisnik** [comment]
@miteshvp API e2e tests are now green, as you can see there: https://ci.centos.org/job/devtools-test-end-to-end-prod-fabric8-analytics/ Relevant logs can be displayed via Zabbix

**Comment by tisnik** [comment]
Fixed in https://github.com/fabric8-analytics/fabric8-analytics-server/pull/267

**Comment by tisnik** [comment]
I'm closing this issue, but for future similar issues we'd need to improve communication.

**Comment by miteshvp** [comment]
@tisnik - all I asked was more logs to validate if the link given by len (which does not talk why e2e tests failed) is because of 504 errors. What communication gap are you talking here?
