### ISSUE TITLE
Piepelines screen: 404 error on clicking name of the pipeline

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2333]
Please check this screen shot: Clicking on 'booster-test' results in HTTP 
<img width="125" alt="screen shot 2018-02-22 at 5 05 53 pm" src="https://user-images.githubusercontent.com/15967765/36536386-ca73f4c4-17f2-11e8-8afa-d7ba23f1c942.png">
404

cc @joshuawilson

**Comment by joshuawilson** [comment]
The build team owns the pipelines page. 

cc @chmouel @rupalibehera @pradeepto @sthaha

**Comment by chmouel** [comment]
unless @sthaha can be driving and get help with this, we don't have anyone who can work on that,

**Comment by andrewazores** [comment]
I can't reproduce this - following the steps as reported, I'm redirected to the OSO web console as expected. @krishnapaparaju can you share the URL that the link points to and which produces a 404?

**Comment by qodfathr** [comment]
@andrewazores did you try with a pipeline that has a `-` in its name, as in the screenshot?

**Comment by andrewazores** [comment]
Yes, the example I tried is called "app2-booster".

Interestingly I hit behaviour that looks like a different known issue (https://github.com/openshiftio/openshift.io/issues/2404), but I haven't seen the 404 described.

**Comment by krishnapaparaju** [comment]
@qodfathr Now this link takes user to 'https://openshift.io/_home' , I would think correct behaviour is  to direct user to 'OSIO space dashboard' as the link refers to a 'OSIO space name'

**Comment by joshuawilson** [comment]
@krishnapaparaju I just tried this and it takes you to the console on OSO.

**Comment by kishansagathiya** [comment]
Behaviour described in https://github.com/openshiftio/openshift.io/issues/2333#issuecomment-375656028 is same as described in https://github.com/openshiftio/openshift.io/issues/2744, which is recently fixed and closed.

While getting 404 is concerned, the issue is mostly obsolete since it wasn't reproduced. 
@joshuawilson Is this issue still relevant or should be closed?

**Comment by joshuawilson** [comment]
If this is reproducible, please reopen with steps needed.
