### ISSUE TITLE
Invalid link to a pipeline on space page

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#2334]
Link to Pipelines is ok (contains 'pmacik@redhat.com' which is right):
![image](https://user-images.githubusercontent.com/3263627/36540947-91748cd0-17dc-11e8-8910-123504a034f9.png)
While the actual pipeline link is invalid = contains only 'pmacik' which is wrong:
![image](https://user-images.githubusercontent.com/3263627/36541194-688546ba-17dd-11e8-8f25-791804ca9832.png)
and leads to:
![image](https://user-images.githubusercontent.com/3263627/36541213-7d6e90ea-17dd-11e8-9494-5b4d4b7201dc.png)

**Comment by pmacik** [comment]
Likely related to https://github.com/openshiftio/openshift.io/issues/2333

**Comment by joshuawilson** [comment]
cc @sthaha @chmouel

**Comment by qodfathr** [comment]
Likely dupe of #575 links to pipelines broken when username has special characters in it

**Comment by andrewazores** [comment]
I think this is a dupe of #575 but I don't think 575 has to do with special characters necessarily - the incorrect portion of the path is taken from the buildconfig namespace, rather than the OSIO username as I believe is actually required. For users who log in to OSIO with a non-email username, this probably lines up the same. For users who log in with an email address then this will be broken.

**Comment by andrewazores** [comment]
Where are the links supposed to point? Should "tttt-2" in this case link to the same place as the "Pipelines" card title, or is there some other place it's supposed to go?

**Comment by andrewazores** [comment]
Where are the links supposed to point? Should "tttt-2" in this case link to the same place as the "Pipelines" card title, or is there some other place it's supposed to go?

**Comment by joshuawilson** [comment]
@catrobson do you know what that link is supposed to do?

**Comment by qodfathr** [comment]
@joshuawilson do you think the fix for this also fixed #575? cc: @maxandersen @ldimaggi

**Comment by catrobson** [comment]
It is supposed to navigate to Pipelines page with it pre-filtered to pipelines with that application name - showing all builds of that application.  I don't think that filtering works on the pipelines page right now, however.

**Comment by andrewazores** [comment]
@catrobson is there an existing issue for the broken filtering on that page?

**Comment by joshuawilson** [comment]
@qodfathr there were 2 PRs that went in. One was to fix this and the other was to fix #575. 

@catrobson I thought it might be done that way.

@andrewazores I do not recall an issue for that.
