### ISSUE TITLE
[DRAFT] enable one pro cluster for osio

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#2336]
## User Story
As a user, I want to be able to use Pro tier of OSO on OSIO.

questions:
  - is there a way on OSO to upgrade starter to Pro ? 
  - can same user id on osio have multiple clusters ? 
  
## Acceptance criteria 
- [ ] add a pro cluster endpoint to osio #2337 
- [ ] add a link to sign up for Pro #2338 (stretch)

**Comment by maxandersen** [comment]
if the intent here is to just enable pro tier for specific users that we manually setup then we do not need link to sign up to pro.

Lets make sure we keep this as simple as possible.

**Comment by mmclanerh** [comment]
@pbergene / @joshuawilson this is from heather -- is this a priority this train?

**Comment by joshuawilson** [comment]
This is something we are talking about starting in J Train.
