### ISSUE TITLE
PR accepted creates odd UI artifact

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#234]
I accepted a PR to my github repo, via the github UI and that created this 2nd pipeline artifact in the UI.

https://screencast.com/t/4oHCawSph

**Comment by burrsutter** [comment]
We need a test case that looks for what happens when a PR is accepted at the github level.  A new build/pipeline run should kick-off, the question is does it look ok in our UI and/or does it actually run properly until deployment?

**Comment by jiekang** [comment]
@joshuawilson do you know if this has been looked into at all? Is it still valid?

**Comment by joshuawilson** [comment]
I think this just be a question that is considered by the Build team. @krishnapaparaju @chmouel

**Comment by chmouel** [comment]
@pradeepto i don't think we have anyone who are able to takes on UI works, isn't it ?

**Comment by joshuawilson** [comment]
@chmouel @pradeepto I think @jiekang is willing to work it. Can you validate it?

**Comment by jiekang** [comment]
Testing with upstream (local deployment), it looks like nothing happens now when a PR is merged into a repository that's a codebase + pipeline + deployment in OSIO.

**Comment by jiekang** [comment]
Tested with PR and build was triggered and I don't see the odd UI artifact. I'm closing this issue. Feel free to re-open if you have a reason otherwise.
