### ISSUE TITLE
Maintain parity while displaying iteration names

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#2344]
In the **Active Iteration** section, the last bits of the Iteration name strings are displayed, whereas in the **Iteration tree** section, the first bits are displayed. This leads to confusion in the identification of the right iteration in the two sections. 

e.g. iter1.3-shuaidgewiucdejvcdscvdsvcdscvds hjds hjds hj vds 
Its impossible to identify this iteration in the Active iteration section.

Expected: Iterations names should be displayed in a common fashion at all places to maintain consistency.

![iterations name display](https://user-images.githubusercontent.com/28748448/36582287-e5546770-1896-11e8-8d53-51187a7c434c.png)

**Comment by nimishamukherjee** [comment]
@openshiftio/uxd-team advice.
Note: The rationale behind the current implementation is that Active iterations shows the entire nested path. We decided to go with .../parent iteration/iteration name format so that the user can see the iteration name.
The iterations tree display only the iteration name as we can see the nested hierarchy for any iteration.

**Comment by muruGanesan** [comment]
@sunilmalagi, @Veethika,
If you have discussed and provided any recommendation, please share it here.

**Comment by christianvogt** [comment]
Any update from uxd?

**Comment by Veethika** [comment]
@rgarg1 @christianvogt I agree with @nimishamukherjee 
For the iterations the dynamic portion of the path has to visible else the users would possibly end up looking at the exact same truncated path for all the iterations. And in the tree, it is just the name being displayed which is unique anyway, so it makes absolute sense to display the starting characters of the name. Providing consistency here would skew the experience.

**Comment by joshuawilson** [comment]
It sounds like you are saying this is working the way it is designed. 

I'm going to close this. If you want to redesign it, please reopen it.
