### ISSUE TITLE
Remove any unwanted jenkins plugins

### ISSUE THREAD

**Issue by rupalibehera** [openshiftio/openshift.io#2347]
Remove plugins which may not require us now to help jenkins pod boot up faster in the jenkins tenant.

Currently, tenant Jenkins image has a boatload of Jenkins plugins that is perhaps not needed by anyone. We need to carefully audit what is required and what is not. Remove everything that is not required and create a lean tenant Jenkins image.

  - [ ] Audit plugins
  - [ ] Create a list of required ones
  - [ ] Build a new Jenkins tenant image

**Comment by rupalibehera** [comment]
Below is the list of plugins which can be removed immediately without much auditing 
- mercurial:2.2
-  jira:2.5 , 
- gitlab-merge-request-jenkins:2.0.0, 
- gitlab-oauth:1.0.9, 
- gitlab-plugin:1.5.2, 
- cloudbees-bitbucket-branch-source:2.2.7, 
- blueocean-jira:1.3.4

**Comment by chmouel** [comment]
Updating with your finding, we have 144 plugins, most of them are dependencies,

@rupalibehera any chance if you can attach the list (or an URL) of all plugins installed in our Jenkins image on this issue?

/cc @pbergene  @kbsingh

**Comment by rupalibehera** [comment]
> Updating with your finding, we have 144 plugins, most of them are dependencies,
> 
> @rupalibehera any chance if you can attach the list (or an URL) of all plugins installed in our Jenkins image on this issue?
list of plugins installed from the update center https://github.com/fabric8io/openshift-jenkins-s2i-config/blob/master/plugins.txt (138 plugins)
and few customized or build from source if not available on update center -> https://github.com/fabric8io/openshift-jenkins-s2i-config/tree/master/plugins (6 plugins)
> 
> /cc @pbergene @kbsingh

**Comment by rupalibehera** [comment]
> Below is the list of plugins which can be removed immediately without much auditing
> 
>     mercurial:2.2
>     jira:2.5 ,
>     gitlab-merge-request-jenkins:2.0.0,
>     gitlab-oauth:1.0.9,
>     gitlab-plugin:1.5.2,
>     cloudbees-bitbucket-branch-source:2.2.7,
>     blueocean-bitbucket-pipeline:1.3.4,
>     blueocean-jira:1.3.4

I removed the above plugins from the image but in the jenkins logs I see below : 
```
Feb 23, 2018 3:38:56 PM SEVERE jenkins.InitReactorRunner$1 onTaskFailed
Failed Loading plugin Bitbucket Pipeline for Blue Ocean v1.4.2 (blueocean-bitbucket-pipeline)
java.io.IOException: Bitbucket Pipeline for Blue Ocean v1.4.2 failed to load.
 - Pipeline implementation for Blue Ocean v1.3.4 is older than required. To fix, install v1.4.2 or later.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:513)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1065)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Feb 23, 2018 3:38:56 PM SEVERE jenkins.InitReactorRunner$1 onTaskFailed
Failed Loading plugin JIRA Integration for Blue Ocean v1.4.2 (blueocean-jira)
java.io.IOException: JIRA Integration for Blue Ocean v1.4.2 failed to load.
 - REST API for Blue Ocean v1.3.4 is older than required. To fix, install v1.4.2 or later.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:513)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1065)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Feb 23, 2018 3:38:56 PM SEVERE jenkins.InitReactorRunner$1 onTaskFailed
Failed Loading plugin Blue Ocean v1.3.4 (blueocean)
java.io.IOException: Blue Ocean v1.3.4 failed to load.
 - Bitbucket Pipeline for Blue Ocean v1.4.2 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:513)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1065)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
Not sure if I have removed the plugin why ask's me to install the latest version of the plugins and the Jenkins image after the removing the plugin is installed here http://jenkins.jenkins-pr-145-openshift-jenkins-s2i-config.tiger.fabric8.io/log/all

Note: 
- Link to the PR : https://github.com/fabric8io/openshift-jenkins-s2i-config/pull/145
- Link to the CI pipeline : https://jenkins.cd.test.fabric8.io/job/fabric8io-auto-rel/job/openshift-jenkins-s2i-config/job/PR-145/

I will continue working on this on Monday
cc: @pradeepto @chmouel

**Comment by lordofthejars** [comment]
Things that I have noticed while reviewing Jenkins log:

- https://stackoverflow.com/questions/49155218/startup-performance-in-jenkins (no solution yet)
- `organization scan action completed: SUCCESS in 6.5 sec` if we already know which project we are configuring, why organization scanning? Maybe better just branch scanning?
- Remove gravatar (it is not necessary and it takes 1 sec)
- Docker image is 1Gb  https://hub.docker.com/r/fabric8/jenkins-openshift/tags/ meanwhile the official one based on alpine is 168Mb. Reducing this size means also faster boot up

**Comment by lordofthejars** [comment]
About size I think I havefound the reason https://github.com/fabric8-jenkins/jenkins-openshift-base/blob/master/2/Dockerfile we are installing a lot of things, would be great to 1) check if we need all these programs installed and 2) can we use alpine based instead of centos? We will safe 150 Mb more or less.

**Comment by lordofthejars** [comment]
Also we can remove `subversion` plugin

**Comment by kbsingh** [comment]
@lordofthejars no, going alpine way solves the wrong problem - note that we are not trying to optimise for size, we just want to lose unusued and potentially hazard code from the content we ship

**Comment by lordofthejars** [comment]
@kbsingh yes I noticed then but downloading from internal registry 1Gb each time is a lot even for an internal registry, but yeah I figured out then that we need to stay in centos image.

**Comment by chmouel** [comment]
Is there anything else that needs to be done on this task, or we are happy that there is nothing more we can do ?

**Comment by lordofthejars** [comment]
Yes there are more things to do, it is not as easy as just remove plugins, because now we are getting some failures, so we need to figure out why they are happening and fix it. Currently, after talking with @rupalibehera we decided to update to latest Blue Ocean.

**Comment by chmouel** [comment]
Okay thanks, can we please make sure we capture the updates (i.e: those failures) and offline discussion on this issue? Since this is valuabe information we want to keep for proposperity

**Comment by lordofthejars** [comment]
https://github.com/fabric8io/openshift-jenkins-s2i-config/pull/151

**Comment by lordofthejars** [comment]
This issue can be closed since PR has been merged

**Comment by pradeepto** [comment]
Closing it. Thanks @lordofthejars @rupalibehera
