### ISSUE TITLE
add prod as a multicluster target for our stage env

### ISSUE THREAD

**Issue by kbsingh** [openshiftio/openshift.io#2348]
As a part of our goal to test our tenant env closer to thr prod environment, we should be able to add the production clusters as multi cluster OSO proxy targets, and have our developers just be able to create new accounts against that cluster.

this would mean free'ing up capacity in free-stg, however we would not lose free-stg as a tenant target - it would just be dev's working in or engaging with the tenant code that need accounts there.

- [ ] Add preview support to Registration app https://github.com/fabric8-services/fabric8-auth/issues/349
- [x] Configure Auth Service https://github.com/fabric8-services/fabric8-auth/issues/349
- [x] Configure OSO Proxy
- [ ] Enable "owning env" labeling support to Jenkins Idler (optional: allows namespaces owned by different envs to not report error on each other)
- [ ] Enable "owning env" labeling support to Tenant Service (required to enable optional above)
- [ ] Clean up free-stg / tenant db for old accounts

**Comment by kbsingh** [comment]
we need to retain testing on free-stg since we need to make sure we continue to validate the next-oso updates.

**Comment by sbose78** [comment]
Add preview support to Registration app : https://github.com/fabric8-services/fabric8-auth/issues/349

**Comment by alexeykazakov** [comment]
Stage 1.

- [ ] Create "How to get provisioned on preview to use prod cluster" dev guide doc for developers.
- [ ] Do not create/provision preview OSO accounts in prod OSIO/Auth if they were provisioned for preview env. No account sharing between prod and preview.
- [ ] Switch the default cluster in Auth preview to east-2a (update CM in Auth)
- [ ] Clean up free-stg tenant namespaces in both free-stg cluster and preview Tenant DB.
- [ ] Protect free-stg cluster capacity. Mark not-relevant existing users as "deprovisioned" in preview Auth DB

Stage 2 - https://github.com/fabric8-services/fabric8-auth/issues/349
- [ ] Fix OSO stg registration app so it use the same flow as prod OSO registration app.
- [ ] Make sure we can provision preview users to both free-stg and prod clusters in the stg OSO reg app.
- [ ] Switch OSIO UI (marketing page) to OSO stg reg app for signing up.

**Comment by pbergene** [comment]
Tenant spaces removed on free-stg

**Comment by pbergene** [comment]
update users set deprovisioned=true where email='$email'; for 137 users with cluster=free-stg done.

**Comment by pbergene** [comment]
Tenant DB remaining

**Comment by pbergene** [comment]
Tenant db cleaned for 276 namespaces and 58 tenants.

**Comment by kbsingh** [comment]
@alexeykazakov @pbergene do we want to take the stage-2 work to a new issue, and close this as done ?

**Comment by alexeykazakov** [comment]
Yes. Makes sense. I created a new issue for stage 2 - https://github.com/openshiftio/openshift.io/issues/2914

Closing this one.
