### ISSUE TITLE
 Precache maven dependencies with a tarball

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#2349]
We have observed some significant long times when starting a new build.

- Maven is trying to parse the dependencies.
- Maven try to do network access
- Maven do a lot of little writes for 'tracking'

One simple and quick solution we can have is to start precache all the maven dependencies in an externally available tarball and wget/untar it at the first run of the pod (in the script that start the slave) if the .mvn directory doesn't exist.

**Comment by joshuawilson** [comment]
what `type` is this?

**Comment by rohanKanojia** [comment]
We're trying cache all the maven dependencies in the container itself. We've made a tarball that consists of all the maven artifacts related to all Openshift.io booster projects, so after booting up it would download and extract this tarball to the local maven repository.
All this logic of fetching the tarball and extracting to the local maven repository directory(in our case `/root/.mvnrepository/` is bundled in the docker image itself. This should ideally stop maven from downloading artifacts in the first run.

**Comment by aslakknutsen** [comment]
@hrishin It's probably even just scoped to 1 OSIO booster since they all will run with different versions of the same stuff and different other stuff etc etc

**Comment by pradeepto** [comment]
@chmouel @hrishin @jaseemabid Do we need this any more post #2368?

**Comment by hrishin** [comment]
@pradeepto we don't need this now. Good to close considering all technical dept about this approach.
