### ISSUE TITLE
Idler should throttle and cap the rate at which it tries to idle things

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#2353]
As observed in the idler logs, it appears that it is currently trying to monitor and idle deployments as fast as possible (or every second?)

It is perfectly fine if the idler do this every 5 minutes or spread the tasks over 5 minutes so that we don't put too much pressure on the API endpoints.

**Comment by vpavlin** [comment]
The logs you are seeing are reactions to events, not Idler doing something in a loop.

But I agree we need to control the rate of idling retries.

There is already an issue for this in Idler https://github.com/fabric8-services/fabric8-jenkins-idler/issues/133

**Comment by jfchevrette** [comment]
Closing in favor of fabric8-services/fabric8-jenkins-idler#133
