### ISSUE TITLE
Idler sometimes not idling the jenkins properly

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#2354]
It looks like the idler is not idling the following jenkins properly.

- DC revision is 2, generation/observedGeneration is 3
- DC says desired=0, current=0
- RC # 1 still set to desired=1, current=1, ready=1
- RC # 2 seems scaled down to 0 as expected
- Jenkins pod from RC # 1 is still running and not being idler

```
NAME                    REVISION   DESIRED   CURRENT   TRIGGERED BY
dc/jenkins              2          0         0         config

NAME                      DESIRED   CURRENT   READY     AGE
rc/jenkins-1              1         1         1         30d
rc/jenkins-2              0         0         0         7d

NAME                            READY     STATUS             RESTARTS   AGE
po/jenkins-1-z76hw              1/1       Running            1          30d
```

**Comment by aslakknutsen** [comment]
This state has been observed before when doing tenant update and I believe it was the same we started seeing after some OS upgrade with Che Workspaces some time ago. Maybe @ibuziuk or @l0rd remember if there were any conclusion to what is actually happening here?

**Comment by piyush-garg** [comment]
Closing this as it is a very old one and also we are currently working on #4658 

cc @sthaha @hrishin @pradeepto
