### ISSUE TITLE
Investigate go-vcr for kubernetes package tests

### ISSUE THREAD

**Issue by ebaron** [openshiftio/openshift.io#2355]
Parent: #2636

By using https://github.com/dnaeon/go-vcr, we may be able to remove much of the test code used to mock Kubernetes/OpenShift/Hawkular API calls that communicate over the network. The existing JSON test files can be used as request/response bodies in the go-vcr cassette files.

**Comment by bartoszmajsak** [comment]
Somehow related https://github.com/openshiftio/openshift.io/issues/2261
