### ISSUE TITLE
when connecting accounts please ask show what accounts are connected

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#2357]
created a new user.
on login asked to connect github and openshift.
i click connect and UI without asking or showing *any* additional screens
says I have connected accounts.

It does not say *which* github account it took and I can tell I was not wanting it to take what account my browser currently are logged in with.

**Comment by alexeykazakov** [comment]
@catrobson @dgutride would need some help from the UX team here. I think we should show what GitHub user/account has been connected + show some tip how user could connect another account: “please re-login to GitHub using desired account and reconnect it in OSIO” or something like this.

**Comment by maxandersen** [comment]
what additionally surprised me is that i did not get screens from github confirming my acceptance of using openshift.io with this *other* account.

seems like a security hole.

**Comment by alexeykazakov** [comment]
If it’s a security hole then it’s a GitHub security hole :)
But actually most likely you have already granted OSIO access to your GitHub account. It won’t ask the second time until you explicitly revoke it. Have you ever connected this account to OSIO?

**Comment by qodfathr** [comment]
Agreed with @alexeykazakov on this one -- @maxandersen you must have already granted access to your currently logged in GitHub account. This is a real edge case. If you revoke OSIO from GitHub, I bet you'd see it working "properly" if you then try again.

**Comment by maxandersen** [comment]
i don't really see this is as an extreme edge case - I would have same situation if I had logged in with some of my bot accounts which are needed to setup automation on github. It would link my accounts together even though that is not at all the intention.

**Comment by ldimaggi** [comment]
I think that I have seen this too - it's an edge case as many (most?) users will not have a second github account (a "machine account" - permitted by github) configured, but people performing automated builds/tests might encounter this problem.

**Comment by alexeykazakov** [comment]
All we can do here is to show the GitHub account name which we have just linked.
Auth service already has all needed API to do so. It's just matter of adding UX/UI around this. @catrobson what should we do to make sure it's in your backlog? We would need a proper design/HTML/CSS for that. We (Auth team) can take care of the UI implementation.
We basically need to show what account we have just linked + some description how to re-link to a different account if needed: "please logout from GH and click on this button/link to re-link GitHub blah blah blah"

But we can't control GitHub UI. So, if GitHub doesn't ask you to grand permissions it means 1) you linked this account to OSIO before (most likely) 2) security issue in GitHub (very unlikely).

**Comment by catrobson** [comment]
@mindreeper2420 can we add the github username to the display of what github account is connected?  Can you work with @mceledonia on what this should look like?

**Comment by mindreeper2420** [comment]
@catrobson @alexeykazakov @maxandersen @qodfathr we currently show what GitHub account is connected to your OSIO profile on the profile page. When you revoke access to OSIO from GitHub (user settings area), it asks you to approve oath access to whatever GitHub account you are currently logged into on the browser you are performing the linking from.

I believe what currently exists matches the criteria? We no longer ask for GitHub connections when the user first logs in - that is only requested when they try to interact with a piece of OSIO that requires GitHub (such as adding/importing a codebase).

<img width="1282" alt="screen shot 2018-03-21 at 3 24 06 pm" src="https://user-images.githubusercontent.com/4032718/37732804-8996bf42-2d1c-11e8-9064-cd4e241203b2.png">

![screen shot 2018-03-20 at 4 34 03 pm](https://user-images.githubusercontent.com/4032718/37732817-92adafa0-2d1c-11e8-899f-550050e39f3a.png)

**Comment by maxandersen** [comment]
> We no longer ask for GitHub connections when the user first logs in

Where is that active ? when i click disconnect on profile page for github i'm asked immediatly on login again to connect to github.

**Comment by alexeykazakov** [comment]
> Where is that active ? when i click disconnect on profile page for github i'm asked immediatly on login again to connect to github.

I can't reproduce it even in prod. Maybe the refresh issue again.. Does it work as expected if you use incognito mode? I mean if you click disconnected in the profile you should stay disconnected until you click on "connect" again.

cc: @rohitkrai03

**Comment by joshuawilson** [comment]
@maxandersen can we close this?

**Comment by sbose78** [comment]
We don't force users to connect github account on login anymore. We only ask them to connect when needed. Closing this.
