### ISSUE TITLE
Event/Message bus mechanism for decoupled coordination and communication of plan, code, build, etc. 

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#2359]
WIP

# Description

To avoid coupling of the various system parts (especially che and jenkins) to the workitem tracker a mechanism to asynchrounsly be able to publish and subscribe to events should be added.

In other words, an event bus where for publishing and subscribing to things like:

1. when a build completes with its succes or failure info
2. when a work item is created, updated, etc.
3. when space is created etc. 

By having this setup this way parts of the system can be added/removed without affecting everyone else.

# Related topics

- can't we and users not just use webhooks in each subsystem ?  (current answer: no, each system could have webhooks but having every system implement custom webhook mechanism would be overkill. Ultimately we would want openshift.io mechanism to be generated from what goes on this event bus rather than every subsystem webhooks are exposed by default )
- will this event bus be used directly for UI getting async updates ? TBD. for now the event bus is primarily
to decouple and coordinate backend services - but for sure the UI will react to events on the eventbus; just not sure how directly that would be done.

# Background

At the moment openshift.io backends are working in silos and for each system we end up having to implement NxM interaction points which will not scale nor was never the intention. This issue is to capture the thoughts and intent around introducing event bus mechanism to fix this.

ref: https://openshift.io/openshiftio/openshiftio/plan/detail/2015

**Comment by alexeykazakov** [comment]
This is not only about notifying UI when some event happened but about some event notifications between backend services too, right?
For example we already have some events in Auth service like user updates we would like to share with other services.

**Comment by maxandersen** [comment]
> This is not only about notifying UI when some event happened but about some event notifications between backend services too, right?
> For example we already have some events in Auth service like user updates we would like to share with other services.

correct @alexeykazakov this is a event mechanism for decoupled communication in the backend between services.

**Comment by maxandersen** [comment]
Another usecase mentioned in context of idler/jenkins-proxy: incoming events from github is something the proxy would like to relay.

**Comment by maxandersen** [comment]
moved to planner https://openshift.io/openshiftio/openshiftio/plan/detail/2015
