### ISSUE TITLE
get idler enabled in production again

### ISSUE THREAD

**Issue by kbsingh** [openshiftio/openshift.io#2364]
We need to have idler back up in production

**Comment by kbsingh** [comment]
marking this across build and platform as one team takes over from the other

**Comment by maxandersen** [comment]
https://github.com/openshiftio/saas-openshiftio/pull/653

**Comment by joshuawilson** [comment]
Changing from `che/platform` to `platform`. Also, since only bugs can have Severity I change it to `crucial-dep`. Unless you see this as a bug.

**Comment by pbergene** [comment]
Re-enabled on prod - state is being closely tracked.

**Comment by pbergene** [comment]
Closing, can file bugs vs idler / proxy component as required.
