### ISSUE TITLE
Project can't be deleted from Codebases view -> Failed to retrieve codebases

### ISSUE THREAD

**Issue by cmoulliard** [openshiftio/openshift.io#2365]
My codebases contains 2 git hub repo (but one of them has been deleted on github)

![screenshot 2018-02-26 17 50 28](https://user-images.githubusercontent.com/463790/36683358-a680d194-1b1d-11e8-80fb-2168281962f1.png)

But if I click on the `codebases` button from the workspace, then I will be redirected to the codebases screen which is empty and where this error is reported - `Failed to retrieve codebases`

![screenshot 2018-02-26 17 37 06](https://user-images.githubusercontent.com/463790/36683420-d5cb5cd0-1b1d-11e8-82e3-f5fafcc37b67.png)

**Comment by jiekang** [comment]
Duplicate of https://github.com/openshiftio/openshift.io/issues/2365 which has been fixed via https://github.com/fabric8-ui/fabric8-ui/pull/2635
