### ISSUE TITLE
Intermittent/recurring issue being seen randomly - server (500) error seen while creating quickstart

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2369]
The net result to the user of this error is minor - he/she can simply close the app wizard dialog and continue. An error is not reported to the user in the OSIO UI - the error is only seen in the Chrome console.

Steps to recreate:
* Create a new quickstart
* Observe that at the last stage of the app creation dialog, the "OK" button is not operative - but - the quickstart is created and its build pipeline is started - no error is reported to the user.

![screenshot from 2018-02-15 14-13-24](https://user-images.githubusercontent.com/642621/36687905-dcc4b86c-1af8-11e8-9e14-da583f518a06.png)

This bug does not create a blocking situation for users - it does cause automated tests to fail.

**Comment by jiekang** [comment]
This just happened to me; can confirm it occurs intermittently in production.

**Comment by ldimaggi** [comment]
Issue found/encountered by EE tests.

**Comment by animuk** [comment]
Old legacy launcher is replaced with new improved launcher which should solved the above issue,
