### ISSUE TITLE
Remove test namespace from tenant config to reclaim resources

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#237]
the test namespace should not be available by default for openshift online free accounts. lets remove it.

ref: https://openshift.io/openshiftio/openshiftio/plan/detail/883

**Comment by jstrachan** [comment]
its been removed already from the latest Tenant.

We just need some mechanism to remove them from the current tenants who have `-test` namespaces

**Comment by joshuawilson** [comment]
@jstrachan is there an issue for that task?

**Comment by jstrachan** [comment]
see https://github.com/fabric8io/fabric8-init-tenant/issues/107

**Comment by maxandersen** [comment]
Marking as closed as it will not affect new users, the other is just cleanup.
