### ISSUE TITLE
Valid application name in fabric8-ui is invalid for Jenkins build and Kubernetes

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2370]
When adding an application to the space via the wizard, multiple '-' characters in a row are allowed in the UI but end up causing the Jenkins build to fail with:

```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default.svc/apis/image.openshift.io/v1/namespaces/jkang-jenkins/imagestreams. Message: ImageStream "arstazxcvwtzx---a" is invalid: metadata.name: Invalid value: "arstazxcvwtzx---a": must match "[a-z0-9]+(?:[._-][a-z0-9]+)*". Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.name, message=Invalid value: "arstazxcvwtzx---a": must match "[a-z0-9]+(?:[._-][a-z0-9]+)*", reason=FieldValueInvalid, additionalProperties={})], group=null, kind=ImageStream, name=arstazxcvwtzx---a, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=ImageStream "arstazxcvwtzx---a" is invalid: metadata.name: Invalid value: "arstazxcvwtzx---a": must match "[a-z0-9]+(?:[._-][a-z0-9]+)*", metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, 
```
Edit:

Steps to reproduce

1. Visit a space.
2. Click 'Add to space' to start the application wizard.
3. Select an application, for example, VertX HTTP Booster, Next.
4. Edit field 'OpenShift Project name' and enter, for example 'arst---a'. Wait for verification to pass. Next.
5. Select pipeline 'Release, Stage, Approve, and Promote', Next.
6. Wait for validation, Finish. Wait for Summary, Ok.
7. Wait for Jenkins build to fail and examine logs.

## Impacts
- [ ] #2084 Getting Started Quickly with a Framework - from Wizard, to IDE, to Deployment

**Comment by joshuawilson** [comment]
Where are you entering these dashes? What are steps tor reproduce it?

**Comment by jiekang** [comment]
I've added steps to reproduce. Interestingly, some locations in the UI will show the name with dashes truncated to 1, e.g 'arst-a', while others show the user inputted name 'arst---a'. It looks like the full name is given to the backend though.

**Comment by jiekang** [comment]
Also updated the issue to be more informative, sorry about the sparse initial write-up.

**Comment by qodfathr** [comment]
What's particular odd is the fact that the string **does** match the regex expression displayed in the error message. That regex does **not** prohibit multiple dashes in a row. Perhaps the final `*` shown in the regex in the error message is in error and does not coincide with the actual code. (e.g. the intent is one more more alphanums, then either `.`, `_` or, `-`, and then one or more alphanums. Remove the final `*` and you get exactly that match behavior.)

**Comment by jiekang** [comment]
The regex is:

`[a-z0-9]+(?:[._-][a-z0-9]+)*`

I believe the regex is correct and does not match against multiple dashes in a row.

The * is applying to the non-capturing group (?:[._-][a-z0-9]+).

Verbally, the entire pattern is: one or more alphanumeric characters, followed by zero or more instances of: a single period, underline, or dash followed by one or more alphanumeric characters.

E.g. a.b_c-c but not a..b__c--b

[1] Can be used to test matches  https://regexr.com/

**Comment by joshuawilson** [comment]
@qodfathr do you want it to allow multiple periods, underscores, and dashs?

**Comment by jiekang** [comment]
@joshuawilson 
To clarify some more: the error is coming from our request to a Kubernetes API endpoint. I think the requirement is from Kubernetes so it may not be something we can change. In theory, we could allow any name for external purposes and keep an acceptable 'id' that is used internally. I don't think this is valuable and can lead to a lot of issues down the road like hashing conflicts.

**Comment by joshuawilson** [comment]
I agree, if it is to match Kubernetes then we should just keep it to that.

**Comment by qodfathr** [comment]
If we have to match the naming rules of every underlying system (including systems to be added in the future), we'll essentially face  an impossible task. We should not be leaking underlying naming rules up to the topmost UI, we should assume those rules will continue to change, and we should simply be offering the best UX to our users.

As such,. in cases such as these, we need a safe way to translate between the naming systems -- even if that means using UUIDs in the remote systems and maintaining a mapping table of names to UUIDs. Yes, that makes it harder for a human to do the mapping manually (e.g. when in the OSO console) -- in instances like that, we should look for ways to mitigate (e.g. using UUIDs + partial name or adding more verbose text into Descriptions if available).

**Comment by qodfathr** [comment]
@jiekang you are correct -- I was misinterpreting the output I was seeing at a different online regex tester.

**Comment by animuk** [comment]
@GeorgeActon What @qodfathr has suggested is a nice approach to plan for to solve this kind of naming rules across the platform level at OSIO. We will initiate discussion on the same line. But It requires involvement with all the team.

So, I suggest at the moment, we would handle from the UI and start the discussion for the generic implementation. @arunkumars08

**Comment by arunkumars08** [comment]
@animuk @jiekang Changes are already moved in production. Closing this issue. Please feel free to open if you think it is happening again.
