### ISSUE TITLE
Workitem quick add dropdown loses context 

### ISSUE THREAD

**Issue by jarifibrahim** [openshiftio/openshift.io#2374]
Steps to reproduce
1. Go to planner on prod/prod-preview
2. Click on `Scenarios`

![download 6](https://user-images.githubusercontent.com/12949454/36722881-c21a8f82-1bd4-11e8-901c-d2ded5a29f7f.png)

Expected - Quickadd dropdown should have scenario, fundamental and papercut
Actual - Quickadd dropdown is empty

**Comment by rgarg1** [comment]
@michaelkleinhenz @nimishamukherjee This should be a must fix.

**Comment by jarifibrahim** [comment]
Fixed by https://github.com/fabric8-ui/fabric8-planner/pull/2441
