### ISSUE TITLE
Prod-Preview: Jenkins deployment fails with persistentvolumeclaim "jenkins-home" not found 

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#2375]
Jenkins : 4.0.56

![screenshot from 2018-02-27 16-24-12](https://user-images.githubusercontent.com/7047079/36725048-0f807c18-1bdb-11e8-8902-ce0c75b85303.png)

**Comment by aslakknutsen** [comment]
Same casue https://github.com/openshiftio/openshift.io/issues/2381

**Comment by qodfathr** [comment]
@aslakknutsen do you recommend closing as a dupe?

**Comment by sara-02** [comment]
@aslakknutsen Any update on this issue? I see #2381 is closed, and I myself have not faced this issue in the recent past. I am closing this for now, if you have any comments re-open it :)
