### ISSUE TITLE
Wrong link to the User Guide

### ISSUE THREAD

**Issue by pkettman** [openshiftio/openshift.io#2379]
Link to the User Guide (https://docs.openshift.io/user_guide.html) at the bottom of the Getting started page (https://docs.openshift.io/getting-started-guide.html) doesn't work.

BTW: Previously there was a 'Documentation' link from the drop-down menu leading to both guides. Any reason why it was removed? The Getting started doc is now available from the homepage which is good, but availability from the drop-down in addition would be quite handy.

**Comment by joshuawilson** [comment]
I'm unsure which link does not work. Can you please be specific. 

The links were changed when we were able to link to the new docs page.

**Comment by pkettman** [comment]
There is a sentence at the end of the Getting Started guide: "See the OpenShift.io User Guide for comprehensive information about OpenShift.io and its features." And the link to the User Guide in that sentence is broken.

**Comment by joshuawilson** [comment]
Ah, so it is in the doc. I misread the issue.

**Comment by joshuawilson** [comment]
cc @rkratky

**Comment by rkratky** [comment]
Thanks for the ping. This has been fixed in https://github.com/fabric8io/fabric8-online-docs/pull/191. Push to prod is in progress.
