### ISSUE TITLE
prevent anonymous execution of Pull requests

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#238]
Currently anyone can send anything as a PR and have it run with access to the users 'prod env'.  We need to prevent that somehow. 

Either remove the functionality for now or add some kind of whitelisting.

ref: https://openshift.io/openshiftio/openshiftio/plan/detail/951

**Comment by rawlingsj** [comment]
This is fixed and deployed to prod

**Comment by rawlingsj** [comment]
fix is in this commit https://github.com/fabric8io/fabric8-pipeline-library/commit/671d833a9a5f8db2b939b3808f3fdf18ac0d0c23
