### ISSUE TITLE
Che should support drag-and-drop and control/c+v for file import and export to a workspace

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2382]
Noticed this while working with Che - copying a local file to a project is an import action, and copying a file from a project to a local file system is a download action. Both actions work, but it would be simpler/easier for users if we also supported drag-and-drop and copy/past for files - these are typical actions supported by desktop apps and IDEs, Thanks!

**Comment by joshuawilson** [comment]
I agree. I was very surprise that it couldn't do this. These common features are important for adoption IMHO.

**Comment by rhopp** [comment]
I did quick search in che github repo and it seems that this was implemented (at least the "upload" part): https://github.com/eclipse/che/pull/75, but you are right it's not working right now (in rh-che based on che5).
I don't have running instance of che6 to try it in more recent version.
On the other hand... I've tried this in Theia and at least the "upload" part works there, so we have something to look forward to ;-)

Either way, @ldimaggi I suggest you to open issue upstream (eclipse/che).

**Comment by ldimaggi** [comment]
Excellent suggestion Radim - https://github.com/eclipse/che/issues/8943

**Comment by joshuawilson** [comment]
By "upload" do you mean the file menu "upload" or do you mean ctrl+v?

**Comment by ldimaggi** [comment]
Yup - the upload feature.

**Comment by joshuawilson** [comment]
This is a request for ctrl-c and ctrl-v to work.

**Comment by ldimaggi** [comment]
Closing this issue is not specific to OpenShift.io - as linked Che issue - https://github.com/eclipse/che/issues/8943 - was closed. Will open a new feature request for Theia.
