### ISSUE TITLE
Running OSIO on Chromebook - Che presents random blinking icons after creating new Java Class

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2385]
Upstream issue eclipse/che#8963 

On this model Chromebook: Lenovo Flex 11 Chromebook, Part Number:  ZA27, 11.6" HD IPS AntiGlare Multitouch (1366x768) 
Chrome 63.0.3239.140 (32 bit)

In Che - create a new Java class - observe presentation of random blinking icons:
https://youtu.be/D3GHHfe24AA
https://youtu.be/Zu7feDHD0OQ

**Comment by ibuziuk** [comment]
@ldimaggi please, create an issue on upstream che for this.

**Comment by ldimaggi** [comment]
https://github.com/eclipse/che/issues/8963

**Comment by qodfathr** [comment]
While annoying, this does not impact any functionality, so adjusting severity.

**Comment by ldimaggi** [comment]
Closing as no longer reproducible.
