### ISSUE TITLE
Unnecessary empty commit being pushed to codebase

### ISSUE THREAD

**Issue by containscafeine** [openshiftio/openshift.io#2387]
Even though I have unchecked the following option while adding a new codebase:

![screenshot from 2018-02-28 15-28-27](https://user-images.githubusercontent.com/9133660/36781573-3c86a8a6-1c9c-11e8-83a7-ef0e6a013958.png)

a new "empty" commit is still created to my repository:

![screenshot from 2018-02-28 15-31-13](https://user-images.githubusercontent.com/9133660/36781669-8dd6dcda-1c9c-11e8-9ad9-daf3902a6995.png)

This is wrong behavior and is pushing random commits and is polluting my git history even though I explicitly asked the wizard not to.

**Comment by bartoszmajsak** [comment]
On that note: I'm wondering how is it that we have both `jboss` and `openshift-io` as commiters? Shouldn't we have one account?

![image](https://user-images.githubusercontent.com/719616/36781840-6c080c98-1c77-11e8-8350-b22f40514773.png)

Screen above comes from my ["quickstart" repo](https://github.com/bartoszmajsak/wfswarm-booster-pipeline-test/commit/46db55ed5a891569a0a1684b857d94265eceec3a) created through OSIO.

**Comment by animuk** [comment]
"Override Jenkins and POM files" options were part of legacy launcher which replaced with new App Launcher. So, should be resolved by this. closing this.
