### ISSUE TITLE
Well, looks like a text box, but not really a text box

### ISSUE THREAD

**Issue by containscafeine** [openshiftio/openshift.io#2389]
Well, the text box right under "Repository name pattern" is not a text box. I clicked on it to search, like I would on any other website, but I could not, because... it's not a text box, but looks like one.

![screenshot from 2018-02-28 18-37-39](https://user-images.githubusercontent.com/9133660/36789188-a2044930-1cb6-11e8-9e1d-c810d192cb5c.png)

So, how do I search? By clicking on the funnel icon next to it, which gives me a text box with red boundary, as if it's an error, but it's not an error... it's a normal text box.

![screenshot from 2018-02-28 18-38-04](https://user-images.githubusercontent.com/9133660/36789192-a4f31fa4-1cb6-11e8-9e97-e8f01d715810.png)

This was very unintuitive, thanks!

**Comment by joshuawilson** [comment]
I agree it is not intuitive. There is a complete redesign of the wizard so this will not get changed as this version of the wizard is going to be replaced.
