### ISSUE TITLE
Bring back idling + agree on what limits to use for Jenkins

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#239]
idling of che and jenkins is needed to reduce resource usage.

resource usage should at least get from 3 GB to 2 GB.

**Comment by joshuawilson** [comment]
Who owns this? @jstrachan @rawlingsj or @kbsingh ?

**Comment by maxandersen** [comment]
Initially @kbsingh and we might want to get this split up separately for idling and resource constraints.

**Comment by kbsingh** [comment]
Do we need seperate issues for each ? che and jenkins ? for the che side, we will need @gorkem and @l0rd

**Comment by rawlingsj** [comment]
Yeah I think seperate issues is best and easier to track any blockers. FWIW I added an idleing
script to our current Jenkins which works in plain docker but not with the post shutdown kubernetes script I added. So hopefully there's not too much work here from the Jenkins side.

**Comment by kbsingh** [comment]
Do we need seperate issues for each ? che and jenkins ? for the che side, we will need @l0rd on there. 

Che does have idling working today, Jenkins however isnt.

We should also split out the conversation w.r.t Resources and Quota's from idling.

**Comment by l0rd** [comment]
For Che the status is: 
- workspace idling is implemented upstream and will be on osio by the end of current sprint
- server idling is already working on osio (after 30min of inactivity)

We have an issue to track that https://github.com/redhat-developer/rh-che/issues/154

**Comment by cctrieloff** [comment]
We should use the same trigger event we use to idle Jenkins to also Idle Stage.  If someone is not doing builds they don't need stage. Stage will then get restarted on the next build trigger from Jenkins

**Comment by joshuawilson** [comment]
@kbsingh what is the status of this?

**Comment by maxandersen** [comment]
closing as main gist of this around idling jenkins is tracked in https://github.com/openshiftio/openshift.io/issues/1245
