### ISSUE TITLE
Unable to import previously imported but deleted codebase

### ISSUE THREAD

**Issue by containscafeine** [openshiftio/openshift.io#2391]
I had imported the following codebase, but then deleted it, and now I'm trying to import it again, but getting the following error. Any idea why?

![screenshot from 2018-02-28 18-46-22](https://user-images.githubusercontent.com/9133660/36789499-bf63f15a-1cb7-11e8-8313-9498476c2c86.png)

**Comment by aslakknutsen** [comment]
How did you delete it?

**Comment by joshuawilson** [comment]
He deleted the space/app and tried to import the same existing codebase.

@containscafeine the codebase has been modified, revert the last change made by `openshift-io `

**Comment by sunilk747** [comment]
@containscafeine Can you please repeat the above steps with the new wizard flow.

**Comment by sunilk747** [comment]
This legacy issue is not present anymore. We have solved this by re-engineering the new launcher experience flow.
cc @animuk
