### ISSUE TITLE
User on cluster 2 (console.starter-us-east-2a) seeing random access/permissions problems

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2392]
Started seeing random access/login/permissions problems for a user account on cluster console.starter-us-east-2a - no pattern yet seen.

In one case, attempting to access OSO from OSIO resulted in this error:
![screenshot from 2018-02-28 10-18-51](https://user-images.githubusercontent.com/642621/36798683-46f0f198-1c79-11e8-817b-4f3267672ea8.png)

In another case, attempting to access the Jenkins build log (view log) failed with this error:
![screenshot from 2018-02-28 10-20-19](https://user-images.githubusercontent.com/642621/36798722-5a9afdd8-1c79-11e8-8adc-7b0c06a86ef7.png)

Will continue to retry and will attach logs if any errors are seen. Is anyone else seeing these types of issues?

Related issue - https://github.com/openshiftio/openshift.io/issues/2390

**Comment by jfchevrette** [comment]
Looks like there is something wrong with your route. I could not reproduce the following using my own jenkins route.

I will raise an issue with the openshift team

```
$ while true; do curl -s -m0 -o /dev/null -w "%{http_code} %{time_total}\n" https://jenkins-ldimaggi-osiotest3-jenkins.b542.starter-us-east-2a.openshiftapps.com/login ; sleep .5; done             
503 12.281556
503 12.279967
503 11.506489
200 0.258796
200 0.250423
503 12.267445
503 11.507735
503 12.284454
200 0.263009
200 0.252894
503 12.278660
503 11.508738
503 10.021516
200 0.261914
200 0.249270
503 12.278614
503 11.508196
503 12.274367
503 11.509746
200 0.249672
200 0.261278
503 12.287886
503 11.503998
503 12.293707
503 11.510469
200 0.273218
200 0.263775
```

**Comment by ldimaggi** [comment]
I was wondering why this was closed.   ;-)

**Comment by ldimaggi** [comment]
How does a user recover from this situation? An env reset does not seem to clear up the problem. Thx!

**Comment by ldimaggi** [comment]
The same account is seeing problems blocking build pipelines:

```
Caused by: io.fabric8.maven.core.service.Fabric8ServiceException: Unable to build the image using the OpenShift build service
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.build(OpenshiftBuildService.java:114)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.buildAndTag(BuildMojo.java:242)
	... 26 more
Caused by: org.apache.maven.plugin.MojoExecutionException: OpenShift Build testfeb29-s2i-1: Failed: PushImageToRegistryFailed
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.waitForOpenShiftBuildToComplete(OpenshiftBuildService.java:360)
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.build(OpenshiftBuildService.java:107)
```

**Comment by ldimaggi** [comment]
This account is the only user account that I have on cluster 2a - question - are other user accounts on cluster 2a also affected by this or only this account? Thx!

**Comment by jfchevrette** [comment]
The infra services have been restarted and the route is now working properly. Upstream are still investigating logs and data to try and pinpoint the root cause.

**Comment by ldimaggi** [comment]
The upstream bug is still open - but I am not seeing this issue on cluster starter-us-east-2a this weekend.

**Comment by ldimaggi** [comment]
Closing as non-reproducible.
