### ISSUE TITLE
Intermittent/recurring issue - PVC errors showing up after env reset 

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2395]
Started seeing these after an env reset late on Feb 28 - in production on first cluster - multiple retries before COntent Repo and Jenkins pods are back up.
```
11:35:29 PM | content-repository-2-rj7pz | Pod | Warning | Failed Scheduling | PersistentVolumeClaim is not bound: "content-repository" (repeated 78 times)8 times in the last minute
11:35:25 PM | jenkins-2-qn8pk | Pod | Warning | Failed Scheduling | PersistentVolumeClaim is not bound: "jenkins-home" (repeated 78 times)8 times in the last
```

**Comment by jfchevrette** [comment]
It appears a tenant reset has been done 60 minutes and the content-cache PV has been re-created.

**Comment by mmclanerh** [comment]
@ldimaggi can this be closed? we have moved off of ebs.

**Comment by ldimaggi** [comment]
Closing as no longer reproducible.
