### ISSUE TITLE
Issue found in the graph database - several properties are missing causing integration tests to fail

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#2396]
The following properties `cm_avg_cyclomatic_complexity`, `cm_loc`, `cm_num_files`, `dependents_count` can not be found for the tested package `io.vertx:vertx-core`, causing the integration tests to fail.

Reproducer:
https://github.com/fabric8-analytics/fabric8-analytics-common/pull/494

Logs:
https://ci.centos.org/job/devtools-e2e-fabric8-analytics/349/console

**Comment by miteshvp** [comment]
@msrb - are we even collecting this static code analysis data? If not,then I think the tests should also be removed accordingly. cc @tisnik

**Comment by msrb** [comment]
@miteshvp we don't collect those any more. Do we expect the properties to be always there, but values to be null or something?

**Comment by miteshvp** [comment]
Based on this https://github.com/fabric8-analytics/fabric8-analytics-data-model/blob/master/src/graph_populator.py#L78, it looks like we will not have those properties at all in the graph

**Comment by tisnik** [comment]
@miteshvp so if current data contains just leftovers, I'll update the test. Do you agree?

**Comment by miteshvp** [comment]
@tisnik - 👍

**Comment by tisnik** [comment]
thanks @miteshvp I'm on it

**Comment by tisnik** [comment]
Tests has been fixed in https://github.com/fabric8-analytics/fabric8-analytics-common/pull/497

**Comment by miteshvp** [comment]
Thanks @tisnik that was quick :+1
