### ISSUE TITLE
open up chat.openshift.io to non-red hat users

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#240]
chat.openshift.io should be made publically accessible.

Cannot just be done by opening up to everybody - we should make sure existing channels are for public consumption and if not those channels should be marked private.

ref: https://openshift.io/openshiftio/openshiftio/plan/detail/882

**Comment by maxandersen** [comment]
parts of this is in https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/289 (internal)

**Comment by joshuawilson** [comment]
Does this task belong to @kbsingh ?

**Comment by joshuawilson** [comment]
@kbsingh is this done or something you are not doing?

**Comment by kbsingh** [comment]
done

**Comment by joshuawilson** [comment]
thanks, I found the email related to it after I posted my question
