### ISSUE TITLE
Display feature-flagged component

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#2400]
belongs to [User story: Feature toggle for component](https://github.com/openshiftio/openshift.io/issues/2056)
# Description
As a user I want to be able to see if a page content feature-flagged components. Implement the visual scree as per UX design
https://redhat.invisionapp.com/share/KAF97RBGB#/screens/276638411_Options_Selection 
# Tasks
- [ ] UI display tooltip about list of feature per page

**Comment by corinnekrych** [comment]
@mceledonia how do we display a page where there are 2 beta features 1 experimental feature and 3 internal feature? ie: a page witha mix type of feature level.
cc @xcoulon @joshuawilson

**Comment by mceledonia** [comment]
@corinnekrych Stand by and I will create a concept today that shows how to display this!

**Comment by joshuawilson** [comment]
The view should build up, one on top of another. If you have 2 beta features, 1 experimental feature, and 3 internal feature then if you are set to Internal you get all of them. If you are set to beta you get only the beta.

It is the same for released/production features. We display them along with all the other changes. 

I'm not sure how we visually mark things on the page so users can know they are knew. But I have argued against such visual cues. As a user, I do **not** want to see a new feature highlighted until it gets released. I would like to know what the new feature is but not while I'm using it.

**Comment by corinnekrych** [comment]
@michaelkleinhenz what about something like: 
![screenshot 2018-04-03 16 50 04_preview](https://user-images.githubusercontent.com/1395710/38256812-6eeb352c-375f-11e8-8f0b-ce375f45e29e.png)

Here:
- the user consent is set to internal
- Planner as a main fetaure is beta
- Planner.Feature1 is internal, same for Planner.Feature2 (but could be beta) => then I'll display red as per internal because it is the smaller level.
 
cc @xcoulon

**Comment by corinnekrych** [comment]
@joshuawilson @mceledonia if we remove this button and there is no visual cues I don't even need to group per page therefore I don't need this backend ticket that @xcoulon is looking at:  https://github.com/openshiftio/openshift.io/issues/2857 

So pls guys let's make up your mind before we work further.

**Comment by mceledonia** [comment]
@corinnekrych I agree with @joshuawilson suggestion, having them stack into eachother works well. If the user is concerned with the exact stage a feature is in, that sounds more like a use case for documentation.

So just to clarify, the "type" of icon is whatever the user is currently opted into, and any features that fall in that category or below are listed as designed. So if the user was oped into experimental, they would have the experimental icon, and that list would contain all experimental and beta features.

**Comment by corinnekrych** [comment]
@mceledonia the list would contain all experimental, beta features and internal features (if RH). 
Oki so the color instead of matching the feautre level matches the user consent level.

@xcoulon I might need the extra information of the `user-level` returned by toggles-service.

**Comment by corinnekrych** [comment]
@mceledonia since the color matches the user-consent and not the feature anymore how do we display the icon for anonymous user?
