### ISSUE TITLE
Fix pipeline widget build links

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2404]
On production, the pipeline widget build links direct to openshift.io, which I believe is incorrect.

![pipeline-build](https://user-images.githubusercontent.com/5430520/36853781-55ea02e2-1d3d-11e8-968e-33d9a5d3c88a.png)

**Comment by andrewazores** [comment]
Not the case for me, so there's something weird going on. Maybe proxy related?

![screenshot from 2018-03-01 10-54-07](https://user-images.githubusercontent.com/3787464/36854468-15d054f2-1d3f-11e8-8a2e-6e7b6035553b.png)

**Comment by andrewazores** [comment]
Or maybe it has something to do with completed vs cancelled builds somehow?

**Comment by aslakknutsen** [comment]
This has to do with the config load order, sometimes it comes out correct some times it don't. Refresh a few times and it should be ok.There is another issue on it that I can't seem to find atm. @joshuawilson ?

**Comment by joshuawilson** [comment]
The `Build #6` link takes me to OSO. Where as the name `app2` takes me to the pipeline page in OSIO. What are you seeing that is different then this?

**Comment by andrewazores** [comment]
In Jie's screenshot, the "Build #3" link is hovered and in the bottom left, the browser preview shows that the URL points to simply "https://openshift.io".

**Comment by joshuawilson** [comment]
That is weird. I have not seen that before and can't reproduce it. @jiekang are you able to reproduce it?

**Comment by joshuawilson** [comment]
I was just now able to see this. I'm working on trying to reproduce it. I do know that refreshing cleared it and reset to the correct URL.

**Comment by jiekang** [comment]
Looks to be a race condition of some sort, as Aslak says. Sometimes it works and other times it doesn't; refreshing repeatedly helps.

**Comment by jiekang** [comment]
Closing as duplicate of https://github.com/openshiftio/openshift.io/issues/2744

Fix will be tracked in 2744
