### ISSUE TITLE
Pipelines filtering "filterQuery is undefined"

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#2405]
The filter box in the toolbar of the Pipelines page is broken. What appears to be a text box is actually a dropdown with one item, "*Filter by Application...*", and selecting this item does nothing on the page while causing an error to be printed in the browser console:

![screenshot from 2018-03-01 10-59-43](https://user-images.githubusercontent.com/3787464/36854724-a9831b30-1d3f-11e8-9aa1-a2766ee02a1d.png)

The expected behaviour is that this dropdown should be a text area, and entering a search term in this area should allow for the pipelines list to be filtered so that only applications with matching names are displayed.

Additionally, this filtering functionality should be linkable from other pages, to support the Pipelines and Recent Active Pipelines widgets linking to this page with only the previously selected pipeline visible: https://github.com/openshiftio/openshift.io/issues/2334#issuecomment-369594778

**Comment by andrewazores** [comment]
Reviewing the implementation, the dropdown is actually intentional - there are supposed to be filters for both "Filter by Application..." and "Filter by Codebase..."

**Comment by andrewazores** [comment]
Reviewing the implementation, the dropdown is actually intentional, and appears to be meant to pre-populate with lists of Applications or Codebases, depending on the type of filter selected in the toolbar. This list is never updated.

**Comment by andrewazores** [comment]
The function updating the toolbar's lists of Applications and Codebases iterates over known Build Configs and looks for labels "app" and "codebase" respectively. For my example pipelines at least, the only label present is "space". I think the Build Config properties "id" and "gitUrl" might be used as replacements (temporarily?).

**Comment by ldimaggi** [comment]
I am not able to recreate the problem that you are seeing - are you seeing this in production?

**Comment by andrewazores** [comment]
Yes, though as I mentioned above this seems to be a pipeline labels thing more than anything else. I'll try clearing out my old stuff and starting fresh and see if the correct labels are applied now.

**Comment by andrewazores** [comment]
No, doesn't seem to have helped any.

To confirm - @ldimaggi , you see populated values in this dropdown?

![screenshot from 2018-03-01 13-05-09](https://user-images.githubusercontent.com/3787464/36861213-474891d6-1d51-11e8-9afd-c7fdd47ea65b.png)

For me only the placeholder value is present in this dropdown (likewise when Codebase filtering is selected), and inspecting the build config objects received in the pipelines.component.ts, the configs do not contain the expected "app" and "codebase" labels - only "space" label.

**Comment by ldimaggi** [comment]
Ah - OK - +1 - I see the same thing.

**Comment by andrewazores** [comment]
I have a patch nearly ready which fixes the sorting and filtering functionality. I will open a separate bug report for the linkable filtering feature.

**Comment by joshuawilson** [comment]
It sounds like we need to get the designs from @catrobson and find out if they need to be updated.

**Comment by catrobson** [comment]
@joshuawilson There are no designs built for this page.  If this is about the filter control we would expect this to behave like the standard patternfly-ng filter, and we should use that filter exactly if we can:  https://rawgit.com/patternfly/patternfly-ng/master-dist/dist-demo/#/filters

I don't think it makes sense to a design exercise based on what we have there today, so if we want to just do clean up to this existing page and talk about how various things should act maybe a quick call and documented agreement would suffice.

**Comment by andrewazores** [comment]
I don't think we need designs or to discuss it - the pf-ng filter example is clear and the implementation's intent is clear (and matches the standard pf-ng design), it's just that the implementation is broken.

**Comment by catrobson** [comment]
I would have probably gone for text area, but I'm open to either.

**Comment by jiekang** [comment]
@andrewazores see above comment: looks like switching to text area is acceptable
