### ISSUE TITLE
After an env reset, seeing long delays in initial pipeline build pipeline - more detailed logging would help to debug

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2409]
Steps to recreate:
* Reset user env
* Create new quickstart - observe build pipeline
* When the pipeline completes, start it up again:

![screenshot from 2018-03-01 13-42-25](https://user-images.githubusercontent.com/642621/36868614-e26326ee-1d66-11e8-9409-15b844c0b690.png)

The disparity in time required makes sense, as the initial build provisions the jenkins slave. But - the scale of the difference is striking.

And - in examining the Jenkins pod log - I am finding gaps in the logging where nothing is written to the log for several minutes:

```

Mar 01, 2018 5:46:24 PM com.squareup.okhttp.internal.Platform$JdkWithJettyBootPlatform getSelectedProtocol
INFO: ALPN callback dropped: SPDY and HTTP/2 are disabled. Is alpn-boot on the boot class path?
Mar 01, 2018 5:46:29 PM org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1 launch
INFO: Skipping injection of procstarter cmdenvs due to JENKINS_HOME present
Mar 01, 2018 5:46:29 PM okhttp3.internal.platform.Platform log
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Mar 01, 2018 5:46:29 PM okhttp3.internal.platform.Platform log
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Mar 01, 2018 5:46:30 PM org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1 launch
INFO: Skipping injection of procstarter cmdenvs due to JENKINS_HOME present
Mar 01, 2018 5:46:30 PM okhttp3.internal.platform.Platform log
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Mar 01, 2018 5:49:18 PM org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1 launch
INFO: Skipping injection of procstarter cmdenvs due to JENKINS_HOME present
Mar 01, 2018 5:49:18 PM okhttp3.internal.platform.Platform log
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
```

What's happening in the 2.5 minute gap? Do we have a way to increase the logging level?

**Comment by ldimaggi** [comment]
Another example:

![screenshot from 2018-02-28 09-45-34](https://user-images.githubusercontent.com/642621/36868785-6b9d0ace-1d67-11e8-9bf0-08ff86d5de94.png)

**Comment by joshuawilson** [comment]
could this be the Jenkins Idler spinning up?

cc @hferentschik @aslakknutsen

**Comment by mmclanerh** [comment]
i think this is probably working fine and is a part of the un-idle process..  the first hit of a github hook is going to error on an idled jenkins -- it sometimes takes a few minutes for the retry hook to schedule, from what i've seen.  also github had undergone a bit of a ddos attack for a while..  was this during that event? githubengineering.com/ddos-incident-report/

**Comment by mmclanerh** [comment]
@ldimaggi can this be closed?

**Comment by ldimaggi** [comment]
Closing as all clusters are now off EBS.
