### ISSUE TITLE
Workitem title's font size is too small to view on a large screen

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#2412]
The workitem title's font size is set to 10.5 pts, whereas Github's title font size is 12 pts.

While viewing Planner backlog view on a large screen, this feels inadequate. We've more than sufficient whitespace to fill.
![font size compare](https://user-images.githubusercontent.com/28748448/36889035-201ab65c-1e1e-11e8-9278-9c8620d27b59.png)

**Comment by muruGanesan** [comment]
@rgarg1, let us discuss this issue and take it forward because I don't understand your point of view.  Anyway I will be reviewing the common elements for the UX enhancements, I will consider this point too.

**Comment by muruGanesan** [comment]
@rgarg1, I reviewed OSIO and various pages of the application. Font size is not too small i.e. there is no readability issue.
Moreover, if the dev/Eng team implemented  'Patternfly' style then the font-size is taken care.

@nimishamukherjee. @michaelkleinhenz , @SMahil, @sahil143 , Can anyone confirm me about the 'body' text CSS class?

**Comment by sahil143** [comment]
@muruGanesan @nimishamukherjee @michaelkleinhenz @rgarg1 
> Can anyone confirm me about the 'body' text CSS class?

current font size is 14px.
patternfly default font-size is 12px which is being overridden.

**Comment by muruGanesan** [comment]
@rgarg1, 
As per my understanding (since @SMahil is involved in front-end development) there should not be any readability issue. Because we would have followed the  Pattern fly typography (http://www.patternfly.org/styles/typography/). 

I recommend you to close this issue.

**Comment by muruGanesan** [comment]
I am closing this issue... because UX is not going to change base font/typography until we find some usability and accessibility issue -or- we may consider the change only if 'PatternFly' redefines the 'font/typography'.
