### ISSUE TITLE
Bring back the root iteration 

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#2414]
Provide an entry for the __root__ iteration in the left hand side-panel for iterations. This used to exist before and was later removed. All workitems that are not assigned to any particular iterations are, by default, assigned to root iteration and this option would enable a way to access those workitems.

**Comment by joshuawilson** [comment]
@rgarg1 Is this a bug or a feature request? If it is really a bug, please assign Severity

**Comment by rgarg1** [comment]
Since it was available earlier and removed later, I should call this a bug with Sev-3.

**Comment by GeorgeActon** [comment]
@rgarg1 I shared a repo with you. It looks like this is only a problem in the SDD template?  I can find everything except a task. But I find them in weird places:
In Scenario - I find Scenarios
In Experiences - I find experiences and Value props
In Requirements - I find Features and bugs (which makes no sense from a user perspective)

And it is easy to isolate them , all you have to do is delete the parent link and refresh.

**Comment by rgarg1** [comment]
Yes @GeorgeActon. The defect was logged against SDD template as due to type groups, orphan tasks went missing from the view. This problem does not exist in the Agile template as there are no type groups.

**Comment by nimishamukherjee** [comment]
Closing this as we are not supporting SDD now.
