### ISSUE TITLE
Che workspace for boosters is broken by OSIO creating OSO routes that are too long.

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#2417]
![image](https://user-images.githubusercontent.com/3263627/36900746-d32486be-1e24-11e8-83f5-6a1787569f6f.png)

The username was: devtools-automated-tests-osiotest1

Hostnames of OSO routes are generated by concatenating strings including deployment name and username. That can end up longer than the limit of 63 characters when the username is long.

![image](https://user-images.githubusercontent.com/3263627/36900235-c5af3ab2-1e22-11e8-8d9d-20e013ee4278.png)

The generated hostnames should be trimmed properly.

**Comment by eivantsov** [comment]
Should this be perhaps closed as a duplicate of https://github.com/openshiftio/openshift.io/issues/2318?

**Comment by pmacik** [comment]
Duplicate of https://github.com/openshiftio/openshift.io/issues/2318
