### ISSUE TITLE
Configure maven client, during pipeline build, to disable http keepalives.

### ISSUE THREAD

**Issue by mmclanerh** [openshiftio/openshift.io#2424]
It appears that there are issues with Maven's CDN provider which results in HTTP timeouts under some conditions when HTTP Keepalives are used.  See:  https://github.com/openshiftio/openshift.io/issues/2408#issuecomment-370037655 for details.

We should configure the Maven client, within the build pipeline, to not use HTTP Keepalives. 

This might be done (needs confirmation) through the following parameters: 
```
 -Dmaven.wagon.http.pool=false -Dhttp.keepAlive=false
```

Consulting @bartoszmajsak, we likely need to update at least two places (maybe more):
- https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/mavenCI.groovy#L34
- https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/mavenBuildSnapshot.groovy#L18

Goals here:
- Remove http keepalive connections from the maven client
- Measure if this improves or reduces timeouts to maven central during dependency download

Thanks!

**Comment by fche** [comment]
I opened a discussion with support@fastly.com about the situation.  They haven't quick acknowledged the problem yet, but we're going back & forth.  There isn't a public ticket URL AFAIK.  Will advise of further developments.

**Comment by mmclanerh** [comment]
Concurrently, I've opened GH issue #2424 to look at disabling keepalives in
the Maven client within the quickstart pipelines and see if this improves
the build times or at least, reduces/eliminates timeouts.   While we're
also investigating other avenues here, do we thinking we could commit to
picking up and getting that updated in prod-preview say, by early/mid next
week? This could be a great win here for new folks onboarding to OSIO.. and
certainly the service, overall.

[1] https://github.com/openshiftio/openshift.io/issues/2424


---
Mike McLane, Principal Software Engineer - Developer Tools (OpenShift.io,
Service Delivery)
mmclane@redhat.com | tel: 1-213-896-5548
Key ID: 4096R/061E6B88  2017-11-16

D7E8 6270 A6F4 BB25 DDAB
F250 680A FA71 061E 6B88

**Comment by joshuawilson** [comment]
What `type` is this?
