### ISSUE TITLE
Add distinct_license field to license recommendation API response

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#2428]
## Description 
Due to the presence of single license in different format, license graph in dependency editor showing redundant licenses. In order to resolve this a distinct_licenses field needs to be added in order to show distinct licenses in the graph.
## Task list
- [x] Add a `distinct_license` field in the license response which will show the distinct licenses present in the stack.

**Comment by joshuawilson** [comment]
What `type` is this?

**Comment by sunilk747** [comment]
Done. Closing this issue.
