### ISSUE TITLE
Intermittent/recurring 401 error being seen on quickstart creation

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2429]
This problem showed up over the weekend (March 3-4) - when creating a new quickstart - a 401 error is sometimes logged. There does not seem to be a functional impact as the quickstart is created.

![screenshot from 2018-03-05 12-25-15](https://user-images.githubusercontent.com/642621/36989703-79b161e4-2070-11e8-9ebe-2fbb37a66c6b.png)

![img_7428](https://user-images.githubusercontent.com/642621/36954351-4fda37e6-1fef-11e8-9ae7-5db9e25e8504.JPG)
![img_7427](https://user-images.githubusercontent.com/642621/36954352-4fea9ef6-1fef-11e8-9178-3fe926066a39.JPG)

**Comment by ldimaggi** [comment]
Downgrading to SEV3 as this problem has not been seen for at least a week - will close if not seen again.

**Comment by animuk** [comment]
Is this still reproducible or can we close this @ldimaggi ?

**Comment by arunkumars08** [comment]
@animuk @ldimaggi I just tried to run the flow again in prod to see if I can reproduce. I am successfully able to click setup and pipelines are getting started.

I don't seem to get that 401 error.

**Comment by ldimaggi** [comment]
Closing as non-reproducible.
