### ISSUE TITLE
Scenarios context is not set on navigating to Planner page

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#2432]
_with ngrx fixes..._

On navigating to the planner home page, the default context must be set to Scenarios, which is not happening. The URL displayed is fine, but the context in UI is missing.

![scenario not selected in left panel](https://user-images.githubusercontent.com/28748448/36965426-9f3211f2-207f-11e8-8abe-a04a1b98f8e5.png)

Manually selecting 'Scenarios' is also not setting the context.

**Comment by joshuawilson** [comment]
What `Severity` is this?

**Comment by rgarg1** [comment]
@joshuawilson Since we're using severity levels to track issues in production, I've not defined any severity here as these issues were reported against a build on planner-master, but not prod. Makes sense?

**Comment by joshuawilson** [comment]
Then it is not a `bug`, as bugs are things in prod or possibly prod-preview and all bugs need a severity. If this is just something that is unfinished but not released then make it a `type/task`. 

However, anything in planner master should also be in fabric8-ui master, which deploys to prod-preview, and can at anytime be pushed to prod. That would make it a bug and it needs severity.

**Comment by vikram-raj** [comment]
Fixed in this PR: https://github.com/fabric8-ui/fabric8-planner/pull/2488. @rgarg1 Can you please verify?

**Comment by rgarg1** [comment]
Cannot reproduce this issue with https://fabric8-ui-fabric8-ui-pr-2488-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
@rgarg1 please check on prod.

**Comment by vikram-raj** [comment]
This issue has been fixed. @rgarg1 If you find this issue again then feel free to reopen this.
