### ISSUE TITLE
Productionize Deep learning Models for Node ecosystem

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2434]
Insights for Node ecosystem are driven by Deep learning models, implemented on TensorFlow based  Neural networks. These are the following work items would need to closed before Insights for Node ecosystem can be exposed to OSIO users:

- [x] Ingest all the manifest files thru Jobs API of OpenShift

- [x] Graph database host all the known Node based dependencies

- [x] Make TensorFlow based training models work at AWS EMR

- [x] Work with SD team to get resources for hosting deep learning models

- [x] Integrate these models with Graph database filters

- [x] Write e2e functional tests for understanding OSIO user experience

- [x] Perform load testing (including deep learning models) to meet acceptable response times for OSIO users.

**Comment by msrb** [comment]
@miteshvp do we already know how should the GitHub query look like for NPM?

**Comment by msrb** [comment]
We ingested 400k+ NPM packages this sprint. @rootAvish @miteshvp how do we want to proceed?

**Comment by rootAvish** [comment]
@msrb, I ingested all the manifests that I wanted using Bigquery to speed up the process slightly, will create an issue around it so we can discuss whether we want to standardize that procedure in a worker. Will create an EPV list from those manifests for another round of ingestion. I think we should discuss this in detail in today's planning/tomorrow to sync up.

/cc @miteshvp

**Comment by msrb** [comment]
> discuss whether we want to standardize that procedure

Yeah, we need to do this. All previous GitHub manifest tasks were pretty much one-time jobs, without any clear refresh strategy.

**Comment by msrb** [comment]
Note there is ~600k unique packages in NPM registry and we ingested 2/3 of them already. Do we have specific versions in the data extracted from GH manifests?

**Comment by rootAvish** [comment]
This was completed long ago but issue isn't closed for some reason. Closing now.
