### ISSUE TITLE
Cannot add child workitems via inline-add

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#2435]
_with ngrx fixes..._

User cannot add a child workitem using the inline quick-add option as:
1. The workitem type selector drop-down menu is overlapping
2. The bottom layer is preventing the user from selecting the workitem type
![overlapping text and mislayering](https://user-images.githubusercontent.com/28748448/36966130-bba5cbe2-2081-11e8-8ef7-9f1eddd2015d.png)

**Comment by joshuawilson** [comment]
What `severity` is this?

**Comment by sanbornsen** [comment]
Fixed in this PR - fabric8-ui/fabric8-planner#2487

**Comment by rgarg1** [comment]
The issue is fixed in prod. Closing.
