### ISSUE TITLE
Need consistent placement for the results text

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#2436]
Without filter, the result text is left aligned
![nofilter](https://user-images.githubusercontent.com/1892722/36966220-1c2ae75e-2082-11e8-9c93-2043db352d8f.png)

With filter, the result text is right aligned
![withfilter](https://user-images.githubusercontent.com/1892722/36966226-216397fc-2082-11e8-92e2-a514eb5adbb0.png)

**Comment by joshuawilson** [comment]
What `severity` is this?

**Comment by sanbornsen** [comment]
This is how the UX was given. It's intentional.

**Comment by nimishamukherjee** [comment]
@SMahil please work with @sunilmalagi on this.

**Comment by sunilmalagi** [comment]
Here is the visuals for both

With Filters:
https://redhat.invisionapp.com/share/86FXSEWJ42P#/280309524_SaveFilter_01

Without Filters:
https://redhat.invisionapp.com/share/NVEWGDU4W#/268692030_Scenarios_01

**Comment by SMahil** [comment]
this has been fixed in https://github.com/fabric8-ui/fabric8-planner/pull/2532
