### ISSUE TITLE
[Planner] : Inline quickAdd workItem type dropdown broken  

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2437]
Steps:
![screenshot from 2018-03-05 14-33-29](https://user-images.githubusercontent.com/34271052/36966253-36c5563a-2082-11e8-85b2-4e9caec9613c.png)

- Navigate to palnner home page
-Select wit group Scenario
-Click on inline quick Add
-Click on inline workItemType dropdown

**Comment by vikram-raj** [comment]
Duplicate of https://github.com/openshiftio/openshift.io/issues/2435

**Comment by sanbornsen** [comment]
Fixed in this PR - https://github.com/fabric8-ui/fabric8-planner/pull/2487
