### ISSUE TITLE
Planner : Empty title can be saved in quick preview

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2438]
Steps:
-Click on Work item title to open quick preview
-Now remove the work Item title and try saving it.
-Error is not thrown.
![screenshot from 2018-03-05 14-46-20](https://user-images.githubusercontent.com/34271052/36966826-fd9b13f2-2083-11e8-8124-9ea3cea20e76.png)

**Comment by joshuawilson** [comment]
What `type` is this?

**Comment by vikram-raj** [comment]
Fixed in this PR https://github.com/fabric8-ui/fabric8-planner/pull/2491
