### ISSUE TITLE
Planner : Items are not filtered based on child workitem

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2441]
Steps:
- Create a workItem of type Scenario.
- Now create a child workItem of type Experience and change the state to Closed
And apply filter to filterBy state closed.

WorkItem is not displayed whereas if filter based on parent workitem then it works

**Comment by joshuawilson** [comment]
What `type` is this?

**Comment by nimishamukherjee** [comment]
Issue is fixed
![state](https://user-images.githubusercontent.com/1892722/48819840-07f2a100-ed78-11e8-92d1-bc3375c3ddb2.png)
