### ISSUE TITLE
Planner - Updating Iteration name doesn't update the workitem associated iteration

### ISSUE THREAD

**Issue by jarifibrahim** [openshiftio/openshift.io#2444]
Associated iteration name doesn't change in workitem quickpreview and list view

Step to reproduce
1. Associate a workitem with an iteration, say A
2. Rename iteration A to iteration B

Expected - The iteration associated with workitem should have title B
Actual - The iteration associated with workitem has title A

**Comment by rgarg1** [comment]
Also note that updating the iteration of a workitem, does not moves the workitem out of the current view, unless the page is either refreshed or user moves to another view.

**Comment by sahil143** [comment]
@jarifibrahim Please verify and close the issue.

**Comment by jarifibrahim** [comment]
This issue has been fixed. Closing it.
