### ISSUE TITLE
Horizontal scrollbar is missing, yet again

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#2445]
The horizontal scrollbar is not displayed, making it impossible to scroll to the right most column, without the help of a touch device.

![backlog view](https://user-images.githubusercontent.com/28748448/36969909-d0ede63c-208c-11e8-9881-69649f35e85f.png)

**Comment by joshuawilson** [comment]
What `severity` is this?

**Comment by vikram-raj** [comment]
Fixed in this PR: https://github.com/fabric8-ui/fabric8-planner/pull/2497

**Comment by nimishamukherjee** [comment]
@rgarg1 please verify

**Comment by vikram-raj** [comment]
This issue has been fixed and in prod.
