### ISSUE TITLE
Planner : Associating child and then its parent work item to Iteration shows 2(same id) workItem in Iteration

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2446]
Steps:
-Associate a workItem of type task to Iteration having heirarchy(Sceanrio->Experience->Bug->task)
-Now Associate task parent Bug to same Iteration
-It shows two workItem having same Id (see screenshot)
![screenshot from 2018-03-05 15-37-39](https://user-images.githubusercontent.com/34271052/36969900-cacf840e-208c-11e8-9a4d-9f4d5c37887f.png)

Now edit one workItem 2nd is not edited
![screenshot from 2018-03-05 15-50-55](https://user-images.githubusercontent.com/34271052/36969982-013ea218-208d-11e8-97d6-54ee209086a2.png)

**Comment by joshuawilson** [comment]
What `type` is this?

**Comment by sanbornsen** [comment]
This issue is resolved in this PR - https://github.com/fabric8-ui/fabric8-planner/pull/2488

**Comment by joshuawilson** [comment]
What `severity` is this?

**Comment by rgarg1** [comment]
Cannot reproduce the defect with https://fabric8-ui-fabric8-ui-pr-2488-fabric8-planner.badger.fabric8.io
