### ISSUE TITLE
Planner : Same filter condition can be applied many times

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2449]
Select filter By- state: new, same condition can be applied many times
![screenshot from 2018-03-05 16-06-55](https://user-images.githubusercontent.com/34271052/36970698-6fe291fa-208f-11e8-966e-54a60dfdc485.png)

**Comment by joshuawilson** [comment]
What `type` is this?

**Comment by sanbornsen** [comment]
This is a duplicate issue - https://github.com/openshiftio/openshift.io/issues/2451

Please close one of these two.
