### ISSUE TITLE
Planner : No option to clear all filters

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2450]
Apply 3-4 filters from Filter-By toolbar. Now if you want to remove all the filters there is no option

**Comment by joshuawilson** [comment]
What `type` is this?

**Comment by sanbornsen** [comment]
Someone, please assign me to this.

**Comment by joshuawilson** [comment]
you need to accept the invite to join the repo

**Comment by Raunak1203** [comment]
fixed with https://github.com/fabric8-ui/fabric8-planner/pull/2492
