### ISSUE TITLE
Applying a new filter value just appends to the existing one, instead of replacing it

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#2451]
_with ngrx changes_

Apply a filter, say Assignee=abc. When the results are displayed, change the value to Assignee=xyz.

Observe that instead of applying the filter Assignee=xyz, the new filter applied is:
Assignee=abc AND Assignee=xyz

![multiple filters](https://user-images.githubusercontent.com/28748448/36970981-58d58552-2090-11e8-9bd0-7298437ab97f.png)

**Comment by joshuawilson** [comment]
What `severity` is this?

**Comment by aptmac** [comment]
Isn't that how the patternfly toolbar filters are supposed to be applied? By visiting the pf-ng demo page [0] and applying the abc & xyz filters, they get added to each other. It's even described in the patternfly design documentation [1], that active filters are stackable (unless stackable filters is toggled off).

![filters](https://user-images.githubusercontent.com/10425301/36981019-fe292a36-2059-11e8-99a4-a5b3103a41ae.png)

[0] https://rawgit.com/patternfly/patternfly-ng/master-dist/dist-demo/#/toolbar
[1] http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/#design

**Comment by sanbornsen** [comment]
In our case, we do AND operation with these filters. So, imagine a filter with ```iteration: it1 AND iteration: it2```, no item will be selected in the list, so it's an invalid filter but also, you can do the same with assignees and then it's valid filter. So it's a matter of discussion.

**Comment by nimishamukherjee** [comment]
Closed the issue as it is the expected behaviour.
