### ISSUE TITLE
Planner : Description in quick preview is in edit mode when we move from one work item to other

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2453]
Steps:
-Click on work item title(here test1) to open quick preview
-Click on description and type "desc"
![screenshot from 2018-03-05 16-35-49](https://user-images.githubusercontent.com/34271052/36971927-5824938e-2093-11e8-8b19-af7400e9c2a2.png)

-Now click on other workitem it still shows "desc" in edit mode 
![screenshot from 2018-03-05 16-35-56](https://user-images.githubusercontent.com/34271052/36971934-5ce087ca-2093-11e8-9a16-05e1aac606e7.png)

**Comment by kwk** [comment]
Why is that considered a bug and not a feature? @michaelkleinhenz

**Comment by divyanshiGupta** [comment]
@Raunak1203 this issue can be closed

**Comment by Raunak1203** [comment]
fixed with PR https://github.com/fabric8-ui/fabric8-planner/pull/2509
