### ISSUE TITLE
Both 'log in' and 'log out' shown when logging in

### ISSUE THREAD

**Issue by rkratky** [openshiftio/openshift.io#2456]
Upon entering creds on the login page, the OSIO landing page is briefly shown before the personal starter page shows up.

On the briefly shown landing page, both the 'LOG IN' and 'LOG OUT' links are shown:

![login-logout-osio](https://user-images.githubusercontent.com/6623103/36990241-579e62ee-20a4-11e8-9b68-9c6af07a1273.png)

To me, that the 'LOG OUT' link is positioned 1 pixel above the 'LOG IN' one is even more distracting than the fact that it's there in the first place...

**Comment by muruGanesan** [comment]
@rkratky @joshuawilson, Though it is closed the GitHub status is not changed. 
I am closing it again... but if it is not fixed, please reopen.

**Comment by rkratky** [comment]
@muruGanesan I have tried it right now, and the issue is still there.

**Comment by joshuawilson** [comment]
@muruGanesan it was never closed, why did you close it?

**Comment by muruGanesan** [comment]
@joshuawilson,  there are duplicate issues #2771, #2772 that are in a 'closed' status. I misunderstand.

**Comment by joshuawilson** [comment]
Ah, yes. We close duplicates to keep the confusion down and the focus in one place.
