### ISSUE TITLE
Remove dummy data/fake screens

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#246]
Fix or remove bad data.

**Comment by qodfathr** [comment]
I think I only see 1 remaining: Developer Poll (https://openshift.io/_home)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1533

**Comment by maxandersen** [comment]
Found in planner punchlist is also to either remove of fix "Number of WIs in the Backlog - left panel" which at most times does seem to show a non-truthful number.

**Comment by joshuawilson** [comment]
Do you want it fixed or removed? to remove it would be a UX call, I think. Also as that is a specific issue and this is a generic task, it is worth creating an issue for it so that it is tracked.

**Comment by maxandersen** [comment]
If it is wrong we remove it. 

@joshuawilson please create specific tasks as you see fit for your team.

**Comment by joshuawilson** [comment]
@maxandersen I'm adding things as I find them. However, I do not see any issue with the number in the `my workitems` dashboard widget. It appears to work as designed.

**Comment by maxandersen** [comment]
See https://openshift.io/openshiftio/openshiftio/plan/detail/1291?iteration=%2Fopenshiftio%2FEnthusiasm

Enthusiasm is listed having 15 items but when clicking on it there is obviously more rendered (probably due to child iterations).

**Comment by joshuawilson** [comment]
I mis-understood what you were referencing, now I see it in the Iteration panel in the Planner. I was talking about an issue list widget on the main dashboard of the whole UI. So yes this needs fixing.

**Comment by joshuawilson** [comment]
@qodfathr you stated above that the only thing remaining was removing the Developer Poll. That has been removed. Closing this issue. 

Anyone, if there are other specific things that need to be cleaned up please reopen and specify them.

**Comment by corinnekrych** [comment]
Subtasks:
[] clean platform code https://github.com/fabric8-ui/fabric8-ui/issues/1629 
[] fix bug on count

**Comment by joshuawilson** [comment]
@corinnekrych I don't think that cleaning up the code in the UI counts as a Blocker. It is more a tech-debt level.

**Comment by maxandersen** [comment]
planner related items don't block at this time. thus closing as that is the only issue left.
