### ISSUE TITLE
Investigate duplicate calls to auth::/api/user/service

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2460]
The web application makes duplicate requests to https://auth.openshift.io/api/user/services when visiting the home page. This should be investigated to see if this is necessary, otherwise reduced to a single request with the data being reused.

![api-user-services](https://user-images.githubusercontent.com/5430520/37000020-f3022a46-208f-11e8-8450-dd5ffb15da8b.png)

**Comment by aptmac** [comment]
Similar to the issue where there are numerous calls to api/user [0], each one of these calls is a GET request accompanied by an OPTIONS request first.

![service-calls](https://user-images.githubusercontent.com/10425301/37488166-215ddef8-286a-11e8-954b-b262f5773b4f.png)

Furthermore, they get called in quick succession (once the OPTIONS are finished, GET is immediately requested).

![network-traffic](https://user-images.githubusercontent.com/10425301/37488288-823ca8ee-286a-11e8-81e8-36c3f8cdb7b7.png)

When I visit the home page, there are 8 requests and 4 of them are GET. Additionally, the calls are duplicated and are fetching the same information. The code responsible is the namespacedresource.store [1], and the namespaced.resource.service [2], each which get called twice. 

[0] https://github.com/openshiftio/openshift.io/issues/2458#issuecomment-373155049
[1] https://github.com/aptmac/fabric8-ui/blob/master/src/a-runtime-console/kubernetes/store/namespacedresource.store.ts#L15
[2] https://github.com/aptmac/fabric8-ui/blob/master/src/a-runtime-console/kubernetes/service/namespaced.resource.service.ts#L27

**Comment by jiekang** [comment]
@aptmac just a heads up in case: The OPTIONS requests are expected for CORS; it's just that there should be one OPTIONS + GET pair instead of 4 (if possible).

**Comment by aptmac** [comment]
Yup sounds good, on the surface it makes the number of calls look more intimidating than it actually is.

**Comment by jiekang** [comment]
A cache has been put in place so this won't occur. Closing.
