### ISSUE TITLE
Multiple instances of mobx in the UI

### ISSUE THREAD

**Issue by aptmac** [openshiftio/openshift.io#2461]
When running unit tests in the UI, I've been seeing the following warning:

![2018-03-05-162908_1440x116_scrot](https://user-images.githubusercontent.com/10425301/37000762-5a72dc32-2092-11e8-96e7-8c0678291b76.png)

> PhantomJS 2.1.1 (Linux 0.0.0) WARN: '[mobx] Warning: there are multiple mobx instances active. This might lead to unexpected results. See https://github.com/mobxjs/mobx/issues/1082 for details.'

There are supposedly multiple instances of mobx running, and I just wanted to verify if this is intended/proper behaviour. 

From rolling back commits, it appears this was introduced with the latest app-launcher commit [0]. There are some potential solutions provided by the mobx issue [1]. After a bit of digging, mobx is a dependency of angular-tree-component [2], which is a dependency for patternfly-ng.

[0] https://github.com/fabric8-ui/fabric8-ui/commit/f91cb7bf6e030e5e904d7738e5955febf1143fa8
[1] https://github.com/mobxjs/mobx/issues/1082
[2] https://github.com/500tech/angular-tree-component/blob/master/package.json#L67

**Comment by joshuawilson** [comment]
@dlabrecq this looks like a question for you.

**Comment by dlabrecq** [comment]
The Planner UI uses TreeList from patternfly-ng, which is a wrapper for angular-tree-component. The app-launcher only uses the toolbar and a truncation pipe from patternfly-ng. Will try to dig into it

**Comment by dlabrecq** [comment]
I believe there is a problem with how ngx-forge is built. I see a ngx-forge.js bundle with its own copy of patternfly-ng. The package.json also defines "module": "bundles/ngx-forge.js" -- that probably should be index.js.

This also appears to be why the platform build is slower. Instead of the build completing in 7:30, it only takes about 2:30 with the index.js change. Unfortunately, the tests fail to compile, so I'll see if that can be fixed.

**Comment by dlabrecq** [comment]
I believe this PR will resolve the warning.
https://github.com/fabric8-ui/fabric8-ui/pull/2610

**Comment by aptmac** [comment]
I'm still seeing a mobx warning, but that PR has made the build time much shorter.

**Comment by dlabrecq** [comment]
In that case, this is an issue with how ngx-forge.js is bundled. See: https://github.com/fabric8-launcher/ngx-launcher/issues/93

**Comment by aptmac** [comment]
Great, thanks for looking into it!

**Comment by gastaldi** [comment]
@edewit any thoughts?

**Comment by edewit** [comment]
I'm fine with moving the asciidoctor stuff back to launch created [issue 129](https://github.com/fabric8-launcher/launcher-planning/issues/129) to track that
