### ISSUE TITLE
User provisioned on starter-us-east-2a does not have OSO projects created

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2464]
Just noticed this for a new user account provisioned on starter-us-east-2a (The username is ldimaggi-osiotest5).

The account shows this in OSO:

![screenshot from 2018-03-05 20-25-29](https://user-images.githubusercontent.com/642621/37009348-8de221f0-20b4-11e8-8e85-fa74f62d0208.png)

**Comment by alexeykazakov** [comment]
@aslakknutsen it seems that OSIO provisioning failed?

**Comment by aslakknutsen** [comment]
Not seeing any issues with this account. Seems to have been provisioned just fine at March 6th 2018, 01:47:37.837 (GMT+1)

**Comment by ldimaggi** [comment]
Verified fixed in production - thanks!
