### ISSUE TITLE
Planner : creating new label closes the tree heirarachy

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2468]
Steps:

- Click on Scenario work item type group.
- Click on show child of a work item
- Now click on work item to open quick preview.
- Click 'Add Label' and create a new label
Tree heirarachy is collapsed

**Comment by joshuawilson** [comment]
What `severity` is this?

**Comment by sanbornsen** [comment]
This issue is fixed in following PR  - https://github.com/fabric8-ui/fabric8-planner/pull/2488

**Comment by rgarg1** [comment]
Cannot reproduce this issue with https://fabric8-ui-fabric8-ui-pr-2488-fabric8-planner.badger.fabric8.io
