### ISSUE TITLE
Define where users should open issues and how we triage them

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#247]

**Comment by joshuawilson** [comment]
I think we have already figured that out. 
Currently:
 - Open issues here in https://github.com/openshiftio/openshift.io/issues
 - I triage the issue and redirect them to the appropriate repo
Next:
 - Once Planner is fully functional they log issues in https://openshift.io/openshiftio/openshiftio/plan 
 - I don't mind continuing to triage them there either

Is this sufficient?

**Comment by joshuawilson** [comment]
We have made the current option the message we are sharing with new users during the on boarding. 

Closing.
