### ISSUE TITLE
Update the Jenkins plugins to latest version

### ISSUE THREAD

**Issue by rupalibehera** [openshiftio/openshift.io#2470]
- List all the plugins that needs be updated https://github.com/fabric8io/openshift-jenkins-s2i-config/blob/master/plugins.txt
- Test after the update

**Comment by sthaha** [comment]
@lordofthejars does the PR https://github.com/fabric8io/openshift-jenkins-s2i-config/pull/151 also address this issue?

**Comment by lordofthejars** [comment]
@sthaha  Yes it covers at the time I send the PR

**Comment by pradeepto** [comment]
@lordofthejars @rupalibehera I am closing this because of your above comment.

**Comment by sthaha** [comment]
@lordofthejars does the commit message refer this issue? I am guessing not. Lets make sure the commit messages refer to the issue in this message that it solves.

**Comment by lordofthejars** [comment]
@sthaha this is a problem that issues are opened in several places but yes this number refers in somewhere in any repo where this issue was opened as well.
