### ISSUE TITLE
Notify user that there are no pods available

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#2472]
I am able to create 2 applications and deploy them on staging environment. But the third is "successfully" deployed only there is no pod available. 

![pipeline_final_testmar61520344305338](https://user-images.githubusercontent.com/2078072/37036846-2c23b5bc-2151-11e8-95ce-ed3ed3084c52.png)

I think this is confusing. I understand that user has limited resources but some hint on what is going on and what he/she is supposed to do would be helpful. I am not even sure what "successful" actually means since in the end, there is no application running.

**Comment by ldimaggi** [comment]
So - to recreate this issue - did you:
* Create (3) new quickstarts - and the first 2 were successfully deployed while the 3rd was not actually successfully deployed, but was reported as successfully deployed? Thx!

**Comment by jiekang** [comment]
This is tied into: https://github.com/openshiftio/openshift.io/issues/2225

**Comment by andrewazores** [comment]
See #874 and #2629 . Closing this as a duplicate.
