### ISSUE TITLE
UI: Use API to delete deployments

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2474]
Parent: #1658 

The API to delete deployments is now available; the delete action should now use it instead of the current mock.

Note the UX has been updated for the delete function.

https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/273202263
https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/273548935
https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/273549059

I think it would be acceptable to initially support the delete action, followed by another issue to update the UX to follow the new design.

**Comment by andrewazores** [comment]
+1 for separating this into two tasks (make real request; update UX)

**Comment by aptmac** [comment]
Once merged, can close this issue too: https://github.com/openshiftio/openshift.io/issues/2633
