### ISSUE TITLE
Another issue found in the graph database - several properties are missing causing integration tests to fail

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#2475]
The `description` property can not be found for the tested package io.vertx:vertx-core, causing the integration tests to fail.

Reproducer:
fabric8-analytics/fabric8-analytics-common#499

Logs:
https://ci.centos.org/job/devtools-e2e-fabric8-analytics/354/console

Actual data read from the Gremlin DB:
```
 {'id': 7782404248,
       'label': 'vertex',
       'properties': {'declared_licenses': [{'id': 'bh7s74j-3kpfxjs-glc5',
                                             'value': 'apache 2.0'},
                                            {'id': 'bh7s6qb-3kpfxjs-glc5',
                                             'value': 'epl 1.0'}],
                      'pecosystem': [{'id': 'bh7s5jn-3kpfxjs-a9x',
                                      'value': 'maven'}],
                      'pname': [{'id': 'bh7s5xv-3kpfxjs-9hh',
                                 'value': 'io.vertx:vertx-core'}],
                      'version': [{'id': 'bh7s6c3-3kpfxjs-b2d', 'value': '3.4.2'}],
                      'vertex_label': [{'id': 'bh7s55f-3kpfxjs-1891',
                                        'value': 'Package'}]},
       'type': 'vertex'}
```

**Comment by msrb** [comment]
This is actually correct. We normally take descriptions from manifest files and there is no description in this pom.xml file: http://repo1.maven.org/maven2/io/vertx/vertx-core/3.5.1/vertx-core-3.5.1.pom

**Comment by msrb** [comment]
@tisnik is this a new test or something that started failing recently and unexpectedly?

**Comment by miteshvp** [comment]
@msrb @tisnik - can we have a small BJN session to understand the current tests and if there is a way to improve them further?

**Comment by humaton** [comment]
@msrb but that is not really ok. API responses should be consistent either insert empty string as a description or remove description at all.

**Comment by msrb** [comment]
@humaton AFAIK, we are doing raw queries to the database here. So the output represents what's really there.

**Comment by msrb** [comment]
> @msrb @tisnik - can we have a small BJN session to understand the current tests and if there is a way to improve them further?

Definitely.

**Comment by humaton** [comment]
@msrb that does mean we have wrong data in the database. It needs to be consistent.

**Comment by msrb** [comment]
@humaton imagine this:

You are using relational database and you decide to add new column to a table, because you will start collecting more data from now on. All the old rows will automatically inherit this "null" field, for free.

But I don't think graph databases work that way. This null property (if you decide to store the new data in a property) will not automatically appear in all vertices and you'd need to iterate over all of them and add it.
Should we do that? Maybe. Is there a single right answer here? I don't think so.

**Comment by humaton** [comment]
@msrb we should do it. Data consistency is one of the key things you want to have in any project. It does not matter if you have to iterate all the data in a graph.
It should not get stored inconsistently in the first place.

**Comment by tisnik** [comment]
@msrb @miteshvp the that fails (second time this sprint ;) is not new, but the failure is caused by new versions of the vertx.core package inserted into the Gremlin. And because vertx.core is one of the most important package we need to handle properly, I'd say it is perfectly ok that this test failed. At least we know that the DB contain 'garbage' ;)

I agree with @humaton, the DB consistency is very important for any project based on data processing. For me missing attributes are something like black magic - does it mean that the data import script is broken? Or did the function that fetched description failed for some reason? Or do we have any deeper problems on S3, RDS, Gremlin?

**Comment by miteshvp** [comment]
Good points, but I guess we need to treat RDBMS databases differently than a NoSQL or a Graph. There is always a scope of improvement in Graph management as well as our test cases.
BTW, I cleared the version entries from graph to see if it helps.

**Comment by msrb** [comment]
The pipeline is designed to work this way. If we don't have the data (pom.xml doesn't contain any description), then we don't create the property in graph. Whether this is good or bad approach is questionable, but this is how it is designed right now. Therefore, in my opinion, the tests shouldn't expect to find the property in graph, if the data is also missing in S3 (is null).

**Comment by tisnik** [comment]
Thanks @msrb for clarification. I'm going update the relevant integration test and then close this issue.

**Comment by tisnik** [comment]
Fixed by https://github.com/fabric8-analytics/fabric8-analytics-common/pull/507
