### ISSUE TITLE
goroutine leak in WIT around SQL package

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#2478]
Not sure what exactly is going on atm, but there is a slow goroutine leak happening somewhere in the usage of the sql package:

```golang
goroutine 267032 [chan receive, 1250 minutes]:
database/sql.(*Rows).awaitDone(0xc420b42f80, 0x27d9500, 0xc4206caac0)
	/usr/lib/golang/src/database/sql/sql.go:2121 +0x58
created by database/sql.(*Rows).initContextClose
	/usr/lib/golang/src/database/sql/sql.go:2116 +0x92

goroutine 128352 [chan receive, 1946 minutes]:
database/sql.(*Rows).awaitDone(0xc4203edd00, 0x27d9500, 0xc420870300)
	/usr/lib/golang/src/database/sql/sql.go:2121 +0x58
created by database/sql.(*Rows).initContextClose
	/usr/lib/golang/src/database/sql/sql.go:2116 +0x92

goroutine 99368 [chan receive, 2119 minutes]:
database/sql.(*Rows).awaitDone(0xc420673c00, 0x27d9500, 0xc4208fda40)
	/usr/lib/golang/src/database/sql/sql.go:2121 +0x58
created by database/sql.(*Rows).initContextClose
	/usr/lib/golang/src/database/sql/sql.go:2116 +0x92
```

![screenshot from 2018-03-06 23-47-34](https://user-images.githubusercontent.com/132158/37063446-b0b4c580-2199-11e8-8097-5c6969f905ac.png)

**Comment by surajssd** [comment]
@aslakknutsen how did you obtain this stack trace and the chart? And is this for the wit repo?

**Comment by surajssd** [comment]
@aslakknutsen don't we have pprof enabled in our applications?

**Comment by aslakknutsen** [comment]
@surajssd We have https://github.com/google/gops

**Comment by aslakknutsen** [comment]
> @aslakknutsen how did you obtain this stack trace and the chart? And is this for the wit repo?

Stacktrace via gops
Chart via local Grafana using PCP data

Yes, WIT

**Comment by aslakknutsen** [comment]
Related https://github.com/fabric8-services/fabric8-wit/pull/1986

**Comment by aslakknutsen** [comment]
After deployment:

![screenshot from 2018-04-06 22-32-06](https://user-images.githubusercontent.com/132158/38443087-b7569490-39ea-11e8-8744-9312f955576c.png)
