### ISSUE TITLE
Jenkins idler kicks in too early

### ISSUE THREAD

**Issue by sthaha** [openshiftio/openshift.io#2479]
I tried the following scenario 

## steps

1. created a quickstart project
2. wait for the initial pipeline to deploy to `run`
3. Submit a PR on my github
4. Wait for the PR Continous Intregration run to finish
5. Merge the PR on GH once the CI run finshed

## Expected result
 -  pipeline to start again to deploy the new version to `run` 

## Observed
- The idler shutdowns jenkins in spite of being active a minute ago
- The build fails to resume and I wasn't able to cancel the build on jenkins, through openshift console and  delete the pipeline

**Comment by joshuawilson** [comment]
Please add labels. Needs area, team, type.

**Comment by sthaha** [comment]
@piyush1594 lets close this issue since significant amount of changes have gone into idler and jenkins proxy.
