### ISSUE TITLE
[5] Identify changes needed for supporting 3rd party package repositories

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#2481]
# Description

In this spike, we want to document changes that we will need to make to our existing components, if we want to start supporting 3rd party repositories (like for example RH Maven repository). We will only focus on data ingestion part of the f8a pipeline here (s3+graph and corresponding components: workers, jobs, data-importer).

The output of this spike should be a document describing challenges that supporting 3rd party repositories brings and possible solutions how we could overcome those challenges (changes to DB schema, how to store the the new information in graph, new API endpoints, etc.)

**Comment by krishnapaparaju** [comment]
Will be using popularity metrics from upstream counterparts. This covers supporting RH dependencies which are part of OSIO RHOAR boosters

**Comment by msrb** [comment]
Will have to wait for Jirka with this one as he is still on a sick leave.

**Comment by sivaavkd** [comment]
@msrb This is a spill over which I am moving to 148.  Can you assign it to somebody else, since Jirika is not working on this anymore ?
