### ISSUE TITLE
Introduce API gateway with authentication

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#2484]
# Description

data-importer has no public route (no authentication in place) so we can't call its API directly. In this task, we will try to use jobs service as a gateway and will see how it goes.

**Comment by tuxdna** [comment]
This may depend on -Jobs API concurrency - https://github.com/openshiftio/openshift.io/issues/2220

**Comment by msrb** [comment]
@humaton please provide your time estimate

**Comment by msrb** [comment]
Replaced by https://github.com/openshiftio/openshift.io/issues/2045.
