### ISSUE TITLE
Implement Global Proxy for Maven Caching

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#2486]
SD team is  setting up a global proxy for Maven Caching.

This issue to implement this on the Build Side.

This would need to go on Maven `settings.xml` as documented [here (https://maven.apache.org/settings.html)

* [ ] We need setting.xml setup, this should be dynamic and using variables.
* [ ] We need some numbers attached to this issue with the improvement.

Build Team: This should be prioritized ASAP

@kbsingh Let us know when we can experiment this with the details

Planner: https://openshift.io/openshiftio/Openshift_io/plan/detail/345

**Comment by ppitonak** [comment]
@sthaha which issue is blocking this one?

**Comment by sthaha** [comment]
@ppitonak see the question from @chmouel to @kbsingh

**Comment by sthaha** [comment]
Closing this as the story has been moved to planner
