### ISSUE TITLE
Jenkins image contain rupalibehera  user

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#2490]
Seems like we have rupalibehera user on the jenkins image as reported [here](https://github.com/fabric8io/fabric8-build-team/issues/41)  : 

![image](https://user-images.githubusercontent.com/98980/37087578-f783fc04-21fa-11e8-91f5-f8fe28bba6e5.png)

```
Mar 01, 2018 10:01:54 AM io.jenkins.blueocean.autofavorite.FavoritingScmListener onCheckout
INFO: Automatically favorited jaseemabid/vertxapp/master for rbehera
```

**Comment by jfchevrette** [comment]
Saw the same for a different user

```
INFO: Automatically favorited jfctest1/benchapp4/master for chmouel
```

**Comment by pradeepto** [comment]
@lordofthejars Since you were investigating this issue earlier today, I added you as assignee. Please update the issue as you deem fit.

**Comment by lordofthejars** [comment]
Exploring a bit this issue, it seems it is something related to runtime and not build time. I arrived to this conclusion because I have checked what is in my `/var/lib/jenkins/users` and I don't have Rupali but others: `asotobu atarocch javajoshw noreply bartosz.majsak  joshuawilson`

It would be interesting to know what others have there to what is in common and what's not. To do it just connect to OSO and:

`oc project <user>-jenkins`
`oc get pods` and get the id of jenkins pod
`oc rsh jenkins-9-<id> ls /var/lib/jenkins/users`

**Comment by chmouel** [comment]
This is what I get

```
% oc rsh jenkins-2-xvtr5 ls /var/lib/jenkins/users                                                                                                                                |osio
cboudjna@redhat.com-edit  chmouel  noreply
```

**Comment by lordofthejars** [comment]
After more investigation I have seen this in my Jenkins instance:

![screen shot 2018-03-21 at 17 06 06](https://user-images.githubusercontent.com/1517153/37723130-f02b1882-2d2d-11e8-8601-873a45f12aee.png)

Notice that it says, "we are storing all users that has been doing something in anything of your projects" so at least now we know it is not a "bug" or something we are doing wrong. Now I am trying to figure out if this is a default behaviour of Jenkins or it is installed by a plugin

**Comment by lordofthejars** [comment]
I have run today locally my Jenkins and I have noticed exactly the same behaviour:

<img width="1229" alt="screen shot 2018-03-22 at 10 41 50" src="https://user-images.githubusercontent.com/1517153/37762856-c0b0a2bc-2dbd-11e8-9647-49f54ae7ecb6.png">

Having multiple users depending on the commits of the project I am importing into Jenkins. What I am going to do now is to just install a plain Jenkins without any plugin and see how it behaves.

**Comment by lordofthejars** [comment]
Ok now I have tried with plain (no autofav plugin) Jenkins. And I get the next thing, when I build a project with a change:

<img width="1136" alt="screen shot 2018-03-22 at 11 27 38" src="https://user-images.githubusercontent.com/1517153/37765310-2d977cec-2dc4-11e8-9b46-28f49f64383e.png">

Then this new user (git user) is reflected on `People` section:

<img width="1220" alt="screen shot 2018-03-22 at 11 27 49" src="https://user-images.githubusercontent.com/1517153/37765490-86996152-2dc4-11e8-8178-cd0086c77fa2.png">

So it is a behaviour that comes from Jenkins itslef. Nothing wrong from our side then.

**Comment by pradeepto** [comment]
In that case, as @chmouel said, "it would be nice to start a conversation with upstream about it cause those message looks ugly (and worrysome) in a multi jenkins per tenant environment " 

@lordofthejars Can you file an issue with the upstream?

I think we can close this. WDYT? @jfchevrette @pbergene @stevengutz

**Comment by stevengutz** [comment]
I vote to close it

**Comment by jfchevrette** [comment]
+1 to close. We now understand what is causing this and there is no impact to the service we provide.

**Comment by lordofthejars** [comment]
Since it is not an issue, it is a behaviour of Jenkins, I decided to open in `stackoverflow`, if I get no answers then I will sync with Jenkins devs.

https://stackoverflow.com/questions/49432149/avoid-jenkins-add-as-users-commmitters
