### ISSUE TITLE
Jenkins is configured to start builds only after a minute

### ISSUE THREAD

**Issue by sthaha** [openshiftio/openshift.io#2495]
I see that jenkins is configured to wait for a minute before it starts a build? See [quiet period][quiet]. There is a good reason to do this (see documentation) but do we want to preserve this behaviour for osio or should the builds start as soon as it is requested? 

[quiet]: https://jenkins.io/blog/2010/08/11/quiet-period-feature/

**Comment by joshuawilson** [comment]
The label `type/experience` is an SDD term and applies at a broader level. I tend to think of it as an `epic`. You may want a different `type`.
@qodfathr can you clarify?

**Comment by jfchevrette** [comment]
I've never observed this during my tests. Is it possible this is ignored for some reason?

Whenever I commit to github, it takes a couple of seconds for jenkins to pick up the webhook, then a build starts, then the slave, etc... I'm not seeing any artificial 1min wait anywhere before the build starts.

**Comment by sthaha** [comment]
@jfchevrette you are correct. @hrishin and I tested it again and like you said I see that the build starts right away for both manually triggered pipeline through osio and for a PR to github. Hence closing this issue.
