### ISSUE TITLE
[~2] Iteration date selector only allows selecting dates in the past

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#2506]
_with ngrx changes_

While creating or editing and iteration, user cannot select either current or a date in future.

The only option allowed is to select a date in the past, which is meaningless.
![calendar grayed](https://user-images.githubusercontent.com/28748448/37148557-e7e9036a-22f0-11e8-9c39-2e0ef37ea33e.png)

[not assigning severity as the issue neither exist in prod or prod-preview, but only in planner master]

**Comment by vikram-raj** [comment]
This issue has been fixed in PR: https://github.com/fabric8-ui/fabric8-planner/pull/2500

**Comment by nimishamukherjee** [comment]
@rgarg1 please check on prod.

**Comment by rgarg1** [comment]
@nimishamukherjee The fix is not in prod.

**Comment by vikram-raj** [comment]
@rgarg1 Fix for this issue is in prod. Can you please verify?

**Comment by rgarg1** [comment]
@vikram-raj The PR fixes the original issue, but a side-effect is observed. Once a date range is selected, editing the dates to chose a date in the future for an iteration is not possible.

**Comment by kwk** [comment]
Both, past and future MUST be allowed.

**Comment by rgarg1** [comment]
Fixed by #2648. Closing.
