### ISSUE TITLE
Filtering by workitem title is broken

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#2508]
Cannot filter down workitems by searching for keywords in the title field. The filter gets added but the results are meaningless. Try searching for a bug on openshiftio/openshiftio

Steps:

1. Browse to https://openshift.io/openshiftio/openshiftio/plan?q=(space:020f756e-b51a-4b43-b113-45cec16b9ce9%20$AND%20$WITGROUP:Requirements)

2. Select __Title__ from the filter dropdown
3. Enter any keyword, say _audit_ and create a filter
4. Observe that the results are not filtered.

**Comment by nimishamukherjee** [comment]
Fix is in prod.
