### ISSUE TITLE
No builds are moving; "Jenkin's  doesn't have label maven..."

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#251]
All of my pipelines are stuck. Each has the same problem; something similar to:

`Jenkins doesn’t have label maven.qodfathr_jenk_master.1`

This was preceded by:
`First time build. Skipping changelog.`
`[Pipeline] echo`
`WARNING: Failed to invoke Environments.namespaceForEnvironment(environment) probably due to API whitelisting: org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: unclassified method java.lang.Class namespaceForEnvironment java.lang.String`
`[Pipeline] echo`
`WARNING: Failed to invoke Environments.namespaceForEnvironment(environment) probably due to API whitelisting: org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: unclassified method java.lang.Class namespaceForEnvironment java.lang.String`
`[Pipeline] podTemplate`
`[Pipeline] {`
`[Pipeline] node`
`Still waiting to schedule task`

**Comment by joshuawilson** [comment]
@jstrachan @rawlingsj @kbsingh Any idea what is happening?

**Comment by rawlingsj** [comment]
I fixed a problem on Friday and released a new jenkins image however the PR https://github.com/fabric8io/fabric8-init-tenant/pull/104 on the tenant service needs to be merged /CC @aslakknutsen.  This needs to happen and whatever is needed for the tenant service to use the new version templates in prod.

FWIW if you want to try the fix out:
1. make sure there are no jenkins jobs running
2. delete any jenkins slave pods
3. `oc edit dc jenkins` and 
replace 
`image: fabric8/jenkins-openshift:foo` 
with 
`image: fabric8/jenkins-openshift:v37d000c `

Providing the OSO deploy trigger works correctly this will start you the new jenkins which includes a fix to the way jenkins starts build pods.

**Comment by sbose78** [comment]
To delete all jenkins slave pods , run 
`oc delete pods -l jenkins=slave`

**Comment by rawlingsj** [comment]
FWIW the two related fixes are https://github.com/fabric8io/jenkins-openshift-base/commit/3b1ad031cb086881d0c8d349ac6e802e14a16b43 and https://github.com/fabric8io/openshift-jenkins-s2i-config/commit/37d000cccc39b4fdad5649d7b801dedcb81a6fd0

**Comment by qodfathr** [comment]
Thanks, @rawlingsj ! My pipelines have concluded...screen is much cleaner now. :)

**Comment by rawlingsj** [comment]
phew :)

**Comment by joshuawilson** [comment]
This looks to be fixed. Closing.
