### ISSUE TITLE
[8](Getting Started): CICD and Semantic release

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#2516]
### User Story
As an OSIO developer, I will be able to see CICD being triggered for every PR. I will also be able to see a new version getting released when a PR is merged to master in this repo https://github.com/fabric8-launcher

### Acceptance Criteria
1. CI should trigger on every PR created.
2. CICD should trigger on every PR merged to master.
3. A new semantic sversion should be released on every PR merged to master.

### Task List
- https://github.com/openshiftio/openshift.io/issues/2945

**Comment by rkratky** [comment]
@jyasveer What's the documentation task in this issue?

**Comment by sivaavkd** [comment]
@jyasveer Where are we with this ?  Is this spilling over to 148 ? Please update accordingly.  cc @GeorgeActon 
@animuk - if this needs to be reassigned to somebody else, please review that.

**Comment by jyasveer** [comment]
@sivaavkd work is in progress. i am tracking this task here https://github.com/openshiftio/openshift.io/issues/2945
