### ISSUE TITLE
[13] (Getting Started): Integration tests for all the steps

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#2517]
### User Story
As an OSIO developer, I want to have integration tests for getting started flow in place in OSIO test suite.

### Acceptance Criteria
1. Getting started integration tests should run in the OSIO test suite.

### Task List
- [ ] Setup for integration tests.
- [ ] Increase integration tests coverage.

**Comment by sivaavkd** [comment]
@jyasveer - Where are we with this ?  Is this spilling over to 148 ?  Please update accordingly.

**Comment by animuk** [comment]
@jyasveer do we still need this? Closing it.

**Comment by jyasveer** [comment]
no we dont need this anymore. Thanks @anindya for closing this

Jyasveer Gotta

Software Engineer

Red Hat India <https://www.redhat.com>

jgotta@redhat.com
<https://red.ht/sig>

On Wed, May 9, 2018 at 11:06 AM, Anindya Mukherjee <notifications@github.com
