### ISSUE TITLE
[1] Deployment charts do not accurately reflect usage vs quota

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#2521]
Parent: https://github.com/openshiftio/openshift.io/issues/1658

# Task

![screenshot from 2018-03-08 13-09-29](https://user-images.githubusercontent.com/3787464/37168199-1b8b3d24-22d2-11e8-86f9-6ffc14bc0305.png)

Deployment charts should scale their Y axes to the stat quota.

# Notes

As seen in the screenshot above, the max Y value for the chart is simply taken to be the maximum Y value sample over the sample window (last 15 minutes). This leads to the memory chart looking like usage is pegged at 100% when the reality is that the memory usage simply has not changed appreciably in 15 minutes. Similarly, the CPU usage chart looks like there are massive intermittent usage spikes, when the usage is really 0.0005 cores' worth. The actual scenario becomes clear on mouseover for CPU usage, or by reading the usage label to the right of the chart for the memory usage, but I feel that the chart's maximum Y value should scale to the quota, so that at a glance users can see the usage trend with respect to the quota.

It's not entirely clear what's intended in the designs (https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/262786733) because the charts for metrics with quotas are shown trending upward and ending close to the quota value.

I have a prototype patch prepared which sets the maximum Y value according to the quota (or the largest Y value sample, since the quota can change if pod count changes), which looks like this for the same deployment:

![screenshot from 2018-03-08 13-17-14](https://user-images.githubusercontent.com/3787464/37168492-15a5469c-22d3-11e8-8557-57895bf1fc4d.png)

@catrobson what is the desired behaviour here?

**Comment by jiekang** [comment]
@catrobson

**Comment by catrobson** [comment]
@andrewazores your example with the Y value set to quota or highest Y value absolutely makes more sense, and is really what is intended with these graphs.  Sorry this wasn't specified or discussed before.  Please proceed with your prototype with the new Y values!
