### ISSUE TITLE
'Reset Selections' button in the launcher does not do reset selections

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#2524]
![image](https://user-images.githubusercontent.com/3263627/37207237-64497ac4-239c-11e8-8d50-2ab3f45956c6.png)

**Comment by invincibleJai** [comment]
@pmacik i guess you are trying it out in prod, recent changes have not been promoted to prod. It's in prod-preview and it works there.

https://prod-preview.openshift.io/jakumar/{space}/applauncher/createapp/

Not sure if logging issue here is right for in-progress task, it will be good to log it here https://github.com/fabric8-launcher/ngx-launcher/issues

@dlabrecq WDYT?

**Comment by pmacik** [comment]
@invincibleJai Ah, yes you are correct I was trying prod... I'll switch to the prod-preview, then. Thanks

**Comment by dlabrecq** [comment]
I tested by running the demo in the ngx-launcher repo. I had no issues resetting my selections. If you have trouble, check the browser console for errors.

Note that this feature has no relevance to being on prod or prod-preview.

**Comment by invincibleJai** [comment]
@dlabrecq what I meant was latest changes are in prod-preview in prod still we have https://openshift.io/_applauncher here reset selection is not working

**Comment by dlabrecq** [comment]
Sorry, I thought you were speaking about OSIO. I wasn't aware that there was an app-launcher deployed at https://openshift.io/_applauncher.

This looks like very old code. For example, the reset button should be disabled. It should also be located in a different spot. There is no cancel button at the top left and so on. We've made a lot of changes to the app-launcher component for the usability studies.

**Comment by invincibleJai** [comment]
It has been fixed, hence closing it. @pmacik pls reopen if you still see this.
