### ISSUE TITLE
Intermittent/recurring error that becomes almost constant at midnight UTC time  - attempts to open Che workspace fail - Start of environment 'default' failed (see #2154)

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2525]
This problem is a variation on #2154 

I am seeing a consistent pattern where, starting at 19:00 Boston time, this issue morphs from occurring intermittently, to happening approx. 90% of the time.

I have observed this problem on a daily basis for the past 5+ days.

**Comment by pbergene** [comment]
Backups of che master db are happening much later, is this observed in the e2e tests?

**Comment by ldimaggi** [comment]
I am seeing this manually and with automated tests. I am seeing it manually after about 19:00 daily.

**Comment by ldimaggi** [comment]
Closing - this pattern is no longer being seen.
