### ISSUE TITLE
Creating Che workspace - error: "Projects exists in workspace but does not exist in filesystem"

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2526]
This problem started showing up on March 9 - am currently seeing this about 50% of the time when creating a new Che workspace.

Steps to recreate:
* Create a new space
* Create a new quickstart
* Attempt to create a new workspace

![screenshot from 2018-03-09 07-14-15](https://user-images.githubusercontent.com/642621/37208328-02c0abb0-236f-11e8-9ad2-4853d8d7f311.png)

**Comment by ibuziuk** [comment]
@ldimaggi which stack have you been using for quickstart ?
@eivantsov any ideas (looks like an upstream issue) ?

**Comment by ldimaggi** [comment]
VertX - thx!

**Comment by ibuziuk** [comment]
@ldimaggi  if you just close the pop-up workspace is working correctly ?

**Comment by ldimaggi** [comment]
Yes - that seems to work.

But - I have not seen this bug before the past couple of days.

**Comment by ibuziuk** [comment]
@ldimaggi we are going to switch to che 6 next week, so it would be great to verify this issue against new version.

**Comment by ldimaggi** [comment]
Closing as not reproducible - the upgrade to Che6 seems to have solved this.
