### ISSUE TITLE
Space creation template choice must be real and have a list of relevant templates available

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#253]
Space Creation - Template must be “live” and result in different issue tracking types. All templates should work. (PR open for this at https://github.com/fabric8io/fabric8-ui/pull/1421)

Template - Looking at the template, we need to show a gap analysis of exactly what is working or not working for any particular template.
Only one that matters at the moment is the Scenario Driven Development Template, others can be addressed later as a separate task.

- [ ] Platform Space template https://github.com/fabric8-services/fabric8-wit/pull/1148

**Comment by maxandersen** [comment]
Can @michaelkleinhenz and @qodfathr verify if having SDD template is enough for first onboarding ?

**Comment by maxandersen** [comment]
@michaelkleinhenz I talked with @qodfathr and we are okey with having just the one available. importance is that we show the truth. additional templates can come later.

Is the work @kwk did to have the list reflect reality merged in ?

**Comment by joshuawilson** [comment]
Templates are not complete but the dropdown only shows "Scenario Driven Planning". 
Marking this as done.
