### ISSUE TITLE
Known, Unknown do NOT add up to total dependencies analysed

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2530]
At OSIO stack report, please check this screen shot:

<img width="1389" alt="screen shot 2018-03-11 at 10 22 29 am" src="https://user-images.githubusercontent.com/15967765/37249882-443f357c-2516-11e8-975d-0d465f2fdac4.png">

**Comment by miteshvp** [comment]
@sara-02 - please look into this. This looks to be based on the latest changes.

**Comment by sara-02** [comment]
![screenshot from 2018-03-14 20-02-39](https://user-images.githubusercontent.com/7047079/37408738-ba3ec824-27c2-11e8-87e2-be87959b3ce9.png)
