### ISSUE TITLE
Vert.x icon is not being displayed in Openshift.io

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/openshift.io#2531]
_From @gastaldi on March 11, 2018 19:51_

Probably caused by the latest catalog changes?

![screenshot_20180311-164656](https://user-images.githubusercontent.com/54133/37257791-4644fec0-254c-11e8-8e78-9cab433da9df.png)

_Copied from original issue: fabric8-launcher/launcher-booster-catalog#170_

**Comment by joshuawilson** [comment]
@gastaldi you marked this as an `integration` issue. Who are you having an issue integrating with?

**Comment by gastaldi** [comment]
@joshuawilson Fabric8-UI and the Fabric8-Launcher backend

**Comment by joshuawilson** [comment]
The `integration` label is meant to link `teams`. Please add the teams that you need to integrate with.

**Comment by gastaldi** [comment]
@edewit I still don't see the Vert.x icon, are you sure this is the right fix?

**Comment by edewit** [comment]
@gastaldi don't know what is wrong was it deployed? Don't see my changes on prod preview

**Comment by joshuawilson** [comment]
I'm going to guess that you didn't use the semantic commit syntax. Also, while you have the freedom to review and merge in fabric8-ui, you may still want to let someone else review it.

**Comment by joshuawilson** [comment]
There have been other commits merged, please see if you can see your change now?

**Comment by gastaldi** [comment]
I see the icons now, they are a bit strechted, but it is there. 

![screenshot from 2018-03-14 13-01-30](https://user-images.githubusercontent.com/54133/37414460-ea710d26-2787-11e8-9353-9c83643c834e.png)

Closing this issue
