### ISSUE TITLE
Notification issue while applying a filter condition and then adding a workItem( doesnt match filter condition)

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2532]
Steps:
-Click on Scenario work item group
-Select Filter By : WorkItemType- Scenario
-Now Add new workItem of type Fundamentals 
-Message is displayed "WorkItem is added"

So, There are 2 parts of this issue:
-  Should the work Item be displayed(because we already have some filter condition)
-  Or there could be a message that this workitem doesn't match filter condition but is added

**Comment by nimishamukherjee** [comment]
Let us discuss this in Cabal.

**Comment by nimishamukherjee** [comment]
In the current UI, work items are created in context of applied filters.
@Raunak1203 can we close this?
