### ISSUE TITLE
Suggestion issue with iteration dropdown

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2533]
Steps:
-Click on work item to open quick preview.
-Click on Iteration dropdown.
-Type Iteration name which doesn't match the condition
-Message displayed "No matches found"
-Click Cancel 
and again click on Iteration, It still shows "No matches Found" 

![peek 2018-03-12 13-16](https://user-images.githubusercontent.com/34271052/37271162-bbe8d8f8-25f7-11e8-883c-76d4cce18642.gif)

**Comment by vikram-raj** [comment]
This has been fixed in PR https://github.com/fabric8-ui/fabric8-planner/pull/2501
