### ISSUE TITLE
UI bug: board view display highlights backlog view

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#2536]
In the Planner, when we select the Backlog view, the Backlog tab should be highlighted to indicate that this is the current view and the Board view should look deselected since this is not the view, and vice-versa.

Currently, whether I am viewing the Backlog or Board view, the Backlog tab appears "selected". The following screenshots illustrate the problem:

When I click on `Backlog View`:
![backlogview](https://user-images.githubusercontent.com/926572/37275450-fb862a1e-262a-11e8-8c46-5eb1c421bd9f.png)

When I click on `Board View`:
![boardview](https://user-images.githubusercontent.com/926572/37275463-03cf6a1e-262b-11e8-86f4-834f34f1aaa4.png)

For both cases, the same tab is "highlighted" when the appropriate one should be highlighted when selected.

**Comment by joshuawilson** [comment]
Please add labels. What `area`, `team`, and `type` is this?

**Comment by mishaone** [comment]
I don't have the permissions to assign any labels to issues in this repo, AFAIK.

**Comment by michaelkleinhenz** [comment]
Board view is now legacy as we're refactoring it in Iris. The functionality described in the issue is not part of prod.
