### ISSUE TITLE
[~2] Empty comment can be saved in quick preview

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2538]
Steps 
- Click on Work item title to open quick preview
- Add a new comment
- Now edit a comment and try saving Empty comment

**Comment by nimishamukherjee** [comment]
@Veethika @sunilmalagi please comment on this issue

**Comment by Veethika** [comment]
@michaelkleinhenz @Raunak1203 @nimishamukherjee blank edits shouldn't be allowed to be saved by deactivating the confirmation button until user adds a minimum of one valid character. We are anyway going to give delete option in future so blank comments make no sense.

**Comment by nimishamukherjee** [comment]
Thanks @Veethika

**Comment by nimishamukherjee** [comment]
@vikram-raj please work on this issue
