### ISSUE TITLE
Create new work item should be guided rather than generic create "Anything"

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#254]
Main feedback from @qodfathr is that the creation of work items is not guided as all options are available to the user at all times. Proposal is to cleanup work item creation and the views around it to be more "guided" based on the context.

Details are in https://docs.google.com/document/d/1MnPB14tFRx3OoeK2AtxssINcna2GxBv3f8vxNzKXvgI/edit

Examples highlights are:
When creating items in an iteration X have that iteration be prefilled out to be Iteration X
When creating items when browsing Stories only allow creation of Tasks [1]

[1]: @maxandersen proposal is instead of removing other choices completely show the context relevant ones first, but still allow me to create any type from anywhere to avoid having users to find the right screen to create a specific type)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2012

**Comment by michaelkleinhenz** [comment]
Done in recent sprints.
