### ISSUE TITLE
Issue with child title

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2540]
Steps:

- Click on workItem to open quickPreview
- Edit the work Item and close the quick Preview
- Now add a child workItem.
- Click on child workitem title to open quick Preview
- Title is in edit mode.
- Click cancel. Title is updated to parent title
![peek 2018-03-12 16-38](https://user-images.githubusercontent.com/34271052/37280530-05f0f176-2614-11e8-8c3d-0526a5d0ac22.gif)

**Comment by Raunak1203** [comment]
@vikram-raj above issue is fixed, verfied in prod-preview...
But if the title is in edit mode in quick preview and we move from one workitem to other should it keep the edit mode?

**Comment by nimishamukherjee** [comment]
Closing this as the reported issue has been fixed.
