### ISSUE TITLE
DeploymentsService timeseries quotas are not truly historical

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#2543]
Parent: https://github.com/openshiftio/openshift.io/issues/1658

# Task

Modify service's timeseries data behaviour to include quota at time of each sample, rather than only current quota.

# Notes

`DeploymentsService` functions `getDeploymentCpuStat` and `getDeploymentMemoryStat` produce snapshot windows of the last 15 minutes of timeseries data muxed with the quota for the metric. This is currently done by overlaying the _current_ quota over all usage samples. This means that if the quota changes, for example after a pod scaling event occurs, then the next snapshot window will revise the history of the metric and claim that the new quota value was the quota value for all previous usage samples as well. This currently does not affect any visual component in any obvious way, however changes to this behaviour may be slightly visible through deployments Sparkline charts while a pod scaling event is at the end of the snapshot window due to https://github.com/openshiftio/openshift.io/issues/2521 .

**Comment by andrewazores** [comment]
This will likely require some backend support to implement nicely.

**Comment by jiekang** [comment]
I feel like the chart UX should be changed to where the Y max is auto and the quota is another line in the line chart by being another set of X points. This would also give users an indication of when things scaled in the last 15 minutes and resolve this issue. Thoughts?

**Comment by jiekang** [comment]
Might need some changes in the backend to support the above though.

**Comment by andrewazores** [comment]
Yea, that could work too, but it might be awkward that this makes the (relatively stable) quota as prominent and visible as the actual usage trend. It might be too much visual noise. Something worthwhile to ask designers anyway.
