### ISSUE TITLE
Codebases Page Fails to Load if GitHub Repo Removed

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#2548]
If a user removes a GitHub repo from GitHub before removing said repo link from OpenShift.io, the Codebases page fails to load any repos (even valid ones).

**Space Dashboard w/a List of Codebases**
<img width="1920" alt="screen shot 2018-03-12 at 8 15 46 pm" src="https://user-images.githubusercontent.com/4032718/37315861-3dc24960-2632-11e8-9ebe-c4773db7ce09.png">

**Create/Codebases Empty Page w/Console Error**
<img width="1915" alt="screen shot 2018-03-12 at 8 15 37 pm" src="https://user-images.githubusercontent.com/4032718/37315871-48b67af8-2632-11e8-98fb-b3a330e05358.png">

**Comment by joshuawilson** [comment]
@jiekang or @andrewazores do either of you have time to look at this?

**Comment by andrewazores** [comment]
@joshuawilson I can take a look
