### ISSUE TITLE
Browsing work items should be guided / contextual rather than generic

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#255]
Related to #254 but this is about browsing rather than creation of workitems.

The "Iteration panel" is considered not enough for users to be successful, instead of only having a way to browse iterations and their workitems the panel should (Based on the template) give some guided paths of navigation, especially using the parent/child relationships between work items.

Details at https://docs.google.com/document/d/1MnPB14tFRx3OoeK2AtxssINcna2GxBv3f8vxNzKXvgI/edit but examples are:

- The Iteration Panel for SDD would be in the pattern of Scenario>Feature>bug>Impediment
- Panel should allow browsing as Portfolio -> Requirements -> Iteration (like the inverse of what is there now)
- Left hand panel to reflect “Backlog Level”s 
- Board View should use same Panel (today they are similar, but separate) so board view is just another way of showing a list of workitems.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2011

**Comment by michaelkleinhenz** [comment]
Done in recent Sprints.
