### ISSUE TITLE
Jenkins pods failing to start on prod-preview

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2550]
Seeing this for the past hour or so - after an env reset:

![screenshot from 2018-03-12 22-55-19](https://user-images.githubusercontent.com/642621/37320128-a69af110-2648-11e8-8a79-38b725b43df8.png)

Not an issue in production.

**Comment by pbergene** [comment]
Should be a different story with new tenant test set-up and de provisioning a lot of free-stg users :)
