### ISSUE TITLE
Build pipelines no longer animated

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2551]
None of my running pipeline builds are showing the 'sliding blue line' animation to indicate the currently processing  stage. When I observe the pipeline directly in OSO, the animation is working properly.

**Comment by joshuawilson** [comment]
@mindreeper2420 do you know why this would stop working?

**Comment by mindreeper2420** [comment]
@joshuawilson I do not. From what I can see, the classes are still in the file under runtime-console, but I can't make much of it beyond that.

**Comment by joshuawilson** [comment]
@jiekang is it possible that something got missed when things were cleaned up in the runtime-console?

**Comment by jiekang** [comment]
I just checked the pipeline animation in OSO and I do not recall ever seeing that in OSIO, even prior to the removal of the runtime-console. I will investigate further.

**Comment by jiekang** [comment]
I tested a revert of the runtime console removal and I don't see the animations either. I'll ask others to try reproducing and move from there.

**Comment by joshuawilson** [comment]
I know I've seen it but I don't remember how long ago it was.

**Comment by hrishin** [comment]
@joshuawilson @jiekang this issue still persist considering following sreenshot? 

![image](https://user-images.githubusercontent.com/28615674/43378020-bc5e19c6-93e1-11e8-98f8-08db179c3fc4.png)

**Comment by jiekang** [comment]
This was fixed in https://github.com/fabric8-ui/fabric8-ui/pull/2970

Thanks for the notification, closing!
