### ISSUE TITLE
Fix fabric8-ui compilation error in my-spaces.component.spec.ts

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2552]
```
[at-loader] Checking finished with 21 errors
[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:172:18 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:176:25 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:178:25 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:185:18 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:189:25 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:191:25 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:483:25 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:485:25 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:488:25 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:490:25 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:503:25 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:505:25 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:520:25 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:522:25 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:536:42 
    TS2339: Property 'contextInformation' does not exist on type 'Profile'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:539:42 
    TS2339: Property 'contextInformation' does not exist on type 'Profile'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:541:42 
    TS2339: Property 'contextInformation' does not exist on type 'Profile'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:546:18 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:548:18 
    TS2339: Property 'showPin' does not exist on type 'Space'. 

[at-loader] ./src/app/profile/my-spaces/my-spaces.component.spec.ts:561:42 
    TS2339: Property 'contextInformation' does not exist on type 'Profile'.
[...]
```

The tests added for `my-spaces.component` don't compile. In fact, the code that it's testing is also very hacky.

In `myspaces.component.ts:restorePins` there is

```
    this.allSpaces.forEach((space: any) => {
      space.showPin = false; // Must set default boolean to properly sort pins
      if (pins !== undefined && pins.length > 0) {
        pins.forEach((id) => {
          if (space.id === id) {
            space.showPin = true;
          }
        });
      }
    });
```

This is a loop over `Space` objects, which are treated as type `any` so that `showPin` can be set, as this property is not defined in the `Space` interface. The test could be updated to use type `any`, disregarding types in typescript. It would be nice if the code could be revised to respect types, maybe introducing an extended class on `Space`, or a greater revision of the implementation.

In the case of the error for `Profile`, it think it should be type `ExtProfile` instead.

**Comment by jiekang** [comment]
@aptmac would you have time to take a look at this?

**Comment by aptmac** [comment]
@jiekang Ah, thanks for catching this. In the code, if the `showPins` attribute isn't present, then it gets appended to the profile. In my IDE, I was silencing these errors that were being brought up by lint by using a ts-ignore comment [0], and that unit test in particular was written to verify that `showPins` is undefined before calling `restorePins()`, and defined afterwards. This also happens in `savePins` when there is no contextInformation associated with the user [1]. I'll take a look into this.

[0] https://github.com/aptmac/fabric8-ui/blob/master/src/app/profile/my-spaces/my-spaces.component.spec.ts#L483
[1] https://github.com/aptmac/fabric8-ui/blob/master/src/app/profile/my-spaces/my-spaces.component.spec.ts#L535

**Comment by jiekang** [comment]
@aptmac in Typescript, you can't add attributes to an object of some Type; it will be a compilation error. The `Space` interface from ngx-fabric8-wit does not define `showPins`. You can bypass this by taking a `Space` object and typing it as `any`, and then setting the attribute, since it's valid Javascript. However, this is disregarding types which is the whole point of Typescript.

Your unit test types the object as `Space` instead of `any` so it sees an error, while the code types the `Space` as `any`, so successfully applies `showPins`. I don't think it's a very good thing to do though.

Hope this helps;

**Comment by jiekang** [comment]
Closing as this has been fixed with the above merge.
