### ISSUE TITLE
Fix fabric8-ui compilation error in app-launcher-project-progress.service.ts

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2553]
Compilation fails with:

```
[at-loader] ./src/app/space/app-launcher/services/app-launcher-project-progress.service.ts:8:14 
    TS2420: Class 'AppLauncherProjectProgressService' incorrectly implements interface 'ProjectProgressService'.
  Property 'progressMessages' is missing in type 'AppLauncherProjectProgressService'. 
```

It looks like the version of forge was updated and the interface was changed. 

Does Forge follow some kind of versioning like semantic versioning [1] where version updates that include breaking changes are clearly defined? When we update through a breaking change version of some dependency, it would be best to also include any fixes at the same time.

[1] https://semver.org/

**Comment by jiekang** [comment]
@joshuawilson would you be able to triage this? I'm not sure on the labels and who would be working in the area.

**Comment by jiekang** [comment]
Relevant PR: https://github.com/fabric8-ui/fabric8-ui/pull/2621

**Comment by jiekang** [comment]
Looks like this may be addressed in: https://github.com/fabric8-ui/fabric8-ui/pull/2615

**Comment by joshuawilson** [comment]
Thanks for writing it up and connecting the dots. Let's see if the fixes will set this right.

**Comment by jiekang** [comment]
Closing as it looks like it was fixed via: https://github.com/fabric8-ui/fabric8-ui/pull/2634
