### ISSUE TITLE
Hiearchial parent/child navigation needs to work

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#256]
Currently a work item list has two options: List vs hierarchal where the latter visualizes parent/child relationships between work items.

The hiearchy view has UI/UX glitches but is also not handling paging nor when the result has work items without "parents". These should be fixed.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2013

**Comment by michaelkleinhenz** [comment]
Dupe of #325. Will be in current sprint.

**Comment by joshuawilson** [comment]
Since #325 is the user-story, why not link to this as the task to cover that part of the user-story?
