### ISSUE TITLE
Booster configmaps should be applied automatically as part of deployment

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#2564]
Affected Boosters:
- [ ] Vertx ConfigMap
- [ ] Springboot ConfigMap
- [ ] WF Swarm ConfigMap

When trying to access a deployed configmap booster, it shows following error
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/17736013/37389808-b2e3dd44-278b-11e8-9ca6-20919e156c0d.png">

Further debugging shows no configmaps applied in the stage and run environment.

**Comment by slemeur** [comment]
Duplicate of : https://github.com/openshiftio/openshift.io/issues/2988

Should be fixed by: https://github.com/fabric8-launcher/launcher-backend/pull/216
