### ISSUE TITLE
New planner work items are not opened with "Add and Open" button applied

### ISSUE THREAD

**Issue by pkettman** [openshiftio/openshift.io#2567]
I've added a new work item in Planner with "Add and Open" button. The item was created but not opened as expected, instead an empty page and following errors in the browser console was displayed:
![newwi](https://user-images.githubusercontent.com/26871874/37408966-822c6646-279d-11e8-9810-f0d77db47734.png)

**Comment by hhovsepy** [comment]
It crashes also when clicking on "View full details" link of any work item.

![screenshot from 2018-03-14 16-05-12](https://user-images.githubusercontent.com/604313/37410735-839a0ebc-27a1-11e8-821c-b1601d0fd0fd.png)

**Comment by michaelkleinhenz** [comment]
@hhovsepy @pkettman which space on which deployment (prod/prod-preview)? Can you do a quick re-check if the problem is still there?

**Comment by hhovsepy** [comment]
Still happening on openshift.io, only with browser FF 58.0.2
I do not see errors in console, but in Chrome (it works on chrome) console it warns:

Mixed Content: The page at 'https://openshift.io/hhovsepy@redhat.com/myspace/plan/detail/11?q=(space:1de549ac-4dcd-4434-9962-042555dd919c%20$AND%20$WITGROUP:Scenarios)' was loaded over HTTPS, but requested an insecure image 'unsafe:null&s=20'. This content should also be served over HTTPS.
GET unsafe:null&s=20 net::ERR_UNKNOWN_URL_SCHEME

**Comment by nimishamukherjee** [comment]
Let us wait for #2285

**Comment by nimishamukherjee** [comment]
Fix on prod.
