### ISSUE TITLE
Clicking on a blue icon next to a work item leads to a blank page

### ISSUE THREAD

**Issue by pkettman** [openshiftio/openshift.io#2569]
When I click a blue icon next to a work item, I get to a blank page with a "XMLHttpRequest cannot load ..." message in the browser console, see pictures below. This scenario is from Chrome, on Firefox clicking on the icon is without any action. 

![wi-icon](https://user-images.githubusercontent.com/26871874/37410587-3e0f2f12-27a1-11e8-93a2-d209577d4eee.png)

![wi-click2](https://user-images.githubusercontent.com/26871874/37410598-42994c66-27a1-11e8-85b5-a102365cd7b2.png)

**Comment by nimishamukherjee** [comment]
The blue icon indicates work item details page. Fix works on prod (for sometime now).
