### ISSUE TITLE
Have text next to type icons to make it clearer what they represent

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#257]
Current UX state only icons should be shown for workitem types  - that is currently deemed as not working well and request is to show icon + text (i.e. "🐛 Bug" instead of just "🐛")

**Comment by joshuawilson** [comment]
This is done. Closing.

**Comment by joshuawilson** [comment]
It is in the Details view. It didn't work in the list view, they tried it there and it was a mess.

**Comment by mindreeper2420** [comment]
This would probably be best moved to the Planner list - the UX team there can take this up, in order to get it looking better/making sense in the list. The difficult part is showing that information in the cards on the Board.

**Comment by joshuawilson** [comment]
Let's see if @qodfathr approves of the current solution. If not we can open this with the Planner team.

**Comment by maxandersen** [comment]
> This would probably be best moved to the Planner list - the UX team there can take this up, in order to get it looking better/making sense in the list. The difficult part is showing that information in the cards on the Board.

please don't move the issue to planner - copy/link if need be.

@qodfathr can you tell if the current fix is sufficient for you (type is spelled out in details view) or if list view should have it too ?

**Comment by nimishamukherjee** [comment]
Currently how it looks on the detail's page:
![typename](https://user-images.githubusercontent.com/1892722/27370142-c356f4c6-564a-11e7-945f-67a022f01b55.png)

On the list view, we could display the type name on hover over the type icon.

**Comment by qodfathr** [comment]
It needs to be displayed in the list, not just the details, per our discussion a few weeks ago.

**Comment by maxandersen** [comment]
Planner items not blocking initial rollout. thus removing from first block list.

**Comment by michaelkleinhenz** [comment]
Note #804 deals with tooltips for the same problem.

**Comment by michaelkleinhenz** [comment]
Fixed for the detail view and quick preview. Will be part of #325 for the list. I'll close this when #325 is done.

**Comment by sdash-redhat** [comment]
Yes, the title of the WI type should be next to the icon in the list.. following is how it should look like-- 
Sunil will update the VD and provide the specs. 
![image](https://user-images.githubusercontent.com/27761023/30860399-9ef065c2-a2e4-11e7-8d37-b1d627202db2.png)

**Comment by sunilmalagi** [comment]
Done, included WI type title next to respective WI type icons, accordingly adjusted the spacing for each row.  Here is the invision link:
https://redhat.invisionapp.com/share/YZDOM6S2R

**Comment by rgarg1** [comment]
Isn't having both tooltip and type-text an overkill? Tooltips were added in the absence of the type-text, so should the tooltips be removed now?

**Comment by sunilmalagi** [comment]
Tooltips are also required to ensure we meet the accessibility . So we have to keep them. Also tool tip can provide the details or helpful info which type text can not provide upfront.

**Comment by joshuawilson** [comment]
Can this be closed?
