### ISSUE TITLE
Integration Test for Booster support: Pipeline

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#2571]
# Test case: Pipeline
A test case for the https://github.com/openshiftio/openshift.io/issues/2399#issuecomment-372520115 test suite.

## Steps after login:
- [x] Verify the completion of the build pipeline and deployment to stage and run.
- [x] Verify successful operation of the deployed booster endpoints at stage and run.

**Comment by sunilk747** [comment]
This PR addresses this issue - https://github.com/fabric8io/fabric8-test/pull/551
