### ISSUE TITLE
Integration Test for Booster support: Check for Stack/Analytic reports

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#2573]
# Test case: Check for Stack/Analytic reports
A test case for the https://github.com/openshiftio/openshift.io/issues/2399#issuecomment-372520115 test suite.

## Steps after login:
- [ ] Verify that build completion creates stack report.
- [ ] Verify report contents by comparing to expected results.

**Comment by joshuawilson** [comment]
@pmacik please don't assign anyone to an issue. You can assign yourself if you have started working on it. If you do then update the Milestone to the current Sprint.
If you want to make sure someone knows about an issue just @ mention there here.

**Comment by pmacik** [comment]
Done by https://github.com/fabric8io/fabric8-test/pull/612
