### ISSUE TITLE
Integration Test for Booster support: Build the project using Maven in the Che terminal window

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#2574]
# Test case: Build the project using Maven in the Che terminal window
A test case for the https://github.com/openshiftio/openshift.io/issues/2399#issuecomment-372520115 test suite.

## Steps after login:
- [x] Open Che workspace.
- [x] Execute `mvn clean install -Popenshift,openshift-it` command in Che terminal window.

**Comment by bartoszmajsak** [comment]
If you want to build with all tests executed you have to invoke a build `mvn clean install -Popenshift,openshift-it`.

**Comment by miteshvp** [comment]
+1 @bartoszmajsak 
@pmacik - I have modified the contents to correct the command that needs to be executed.

**Comment by pmacik** [comment]
@bartoszmajsak @miteshvp Thanks!

**Comment by bartoszmajsak** [comment]
@joshuawilson @ldimaggi does it really belong to `team/test`?

**Comment by joshuawilson** [comment]
@bartoszmajsak I don't think it is. Next time just remove your team.
This looks like something @gastaldi and the Launch team own since they own the boosters/quickstarts.

**Comment by gastaldi** [comment]
@ldimaggi do your e2e tests do that already?

**Comment by pmacik** [comment]
Done by https://github.com/fabric8io/fabric8-test/pull/534
