### ISSUE TITLE
Integration Test for Booster support: Verify that the preview URL provided in the Che terminal is correct and can be accessed

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#2575]
# Test case: Verify that the preview URL provided in the Che terminal is correct and can be accessed
A test case for the https://github.com/openshiftio/openshift.io/issues/2399#issuecomment-372520115 test suite.

## Steps after login:
- [ ] Open Che workspace.
- [ ] Execute:
  ```
  oc login
  oc project <oso-username>
  mvn clean install -Popenshift,openshift-it
  ```
  in the Che Terminal.
- [ ] Verify URL generated endpoint is reachable.
- [ ] Verify that the deployed Booster functions correctly.

**Comment by miteshvp** [comment]
@pmacik - I have just edited the contents to reflect correct command to be executed.

**Comment by pmacik** [comment]
@miteshvp Thanks!
