### ISSUE TITLE
[Che] Can't push commit in amend mode

### ISSUE THREAD

**Issue by jeffmaury** [openshiftio/openshift.io#2576]
I followed the workshop but when I commited I forgot the select the push option. Then I reran the git commit command and as nothing changed, the UI proposed the amend mode but I can't select the push option then

**Comment by eivantsov** [comment]
@jeffmaury You can push at Git > Remotes > Push.

**Comment by RanjithRV** [comment]
@jeffmaury @eivantsov Can we close this issue? Is the proposed solution a workaround or expected behaviour?

**Comment by gorkem** [comment]
closed, it looks like an acceptable solution and there was no further activity.
