### ISSUE TITLE
Integration Test for Booster support: Run the project's Junit tests from the Che menu

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#2579]
# Test case: Run the project's Junit tests from the Che menu
A test case for the https://github.com/openshiftio/openshift.io/issues/2399#issuecomment-372520115 test suite.

## Steps after login:
- [x] Open Che workspace.
- [x] Run the Booster Junit tests from the `Run` menu in Che.
- [x] Verify results.

**Comment by ldimaggi** [comment]
See:  https://github.com/fabric8io/fabric8-test/pull/535
