### ISSUE TITLE
Work Items in Iteration are lost after refresh

### ISSUE THREAD

**Issue by hhovsepy** [openshiftio/openshift.io#2583]
In a Backlog, check any of iterations.
Add new work items, Task or Feature. They are shown after save.
![screenshot from 2018-03-14 16-40-17](https://user-images.githubusercontent.com/604313/37413157-ae4f54d2-27a6-11e8-9398-59901b34a795.png)

Refresh the page, it will keep selected the iteration, but work items are gone.
![screenshot from 2018-03-14 16-40-46](https://user-images.githubusercontent.com/604313/37413220-d6f6ea8a-27a6-11e8-8061-96e6b5cb817f.png)

**Comment by michaelkleinhenz** [comment]
@hhovsepy which deployment (prod/prod-preview) and which space? Any errors in the browser console? Could be the same reason as #2567

**Comment by hhovsepy** [comment]
Happening in openshift.io over FF and Chrome on my custom 'myspace'.
No errors in console.

I do not see either request "https://api.openshift.io/api/spaces/1de549ac-4dcd-4434-9962-042555dd919c/workitems" to load work items in console.

**Comment by nimishamukherjee** [comment]
@hhovsepy this has been fixed can you please check.

**Comment by hhovsepy** [comment]
Verified on #1098
