### ISSUE TITLE
DeploymentsService function parameter orders are inconsistent

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#2586]
Parent: #2630

Some functions have param lists `spaceId: string, applicationId: string, environmentName: string` and others `spaceId: string, environmentName: string, applicationId: string`. The order and naming should be made consistent across all functions in the class.

**Comment by jiekang** [comment]
I'd prefer hierarchical order from the top: spaceId -> environmentName -> applicationId
