### ISSUE TITLE
'Add' button seems to do nothing, other non-intuitive behaviors

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#2588]
OSIO Test day scenario:

- Within new project, use planner and add some Iterations.
- Try to add a new Scenario, 'S1'.
- Attempting to finish the action by hitting 'Add' button results in no discernible action.

![image](https://user-images.githubusercontent.com/524520/37422453-233d1086-2789-11e8-8218-099e68ada732.png)

**Comment by RickJWagner** [comment]
Note:  A moment later (after I filled out the comment above) the 'Add' buttons disappeared and I was given the choice to 'Log in'.
Note that my Iterations are still present.

![image](https://user-images.githubusercontent.com/524520/37422561-61475d0a-2789-11e8-9275-99573959ec79.png)

**Comment by RickJWagner** [comment]
Following above, chose to Log in (again).  The next view shows no 'Recent Spaces', though it does show the new project ('osiotestday') in 'Recent Active Pipelines'.

![image](https://user-images.githubusercontent.com/524520/37422701-d0455784-2789-11e8-949d-d1d6b6668f5a.png)

**Comment by nimishamukherjee** [comment]
Not able to replicate this issue. Please re-open if you face the issue again.
