### ISSUE TITLE
Associating a Feature with an Iteration seems to do nothing

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#2591]
OSIO Test day scenario.
1)  Make a bunch of Scenarios, Experiences, etc.
2)  Edit one of the Features. Assign it (works).  Associate it with an Iteration. 
>> Nothing seems to happen.
Note in the screenshots below that the Feature is associated with /osio_testday/I3/I3.5, but nothing shows up when viewing that iteration.  I'd expect to see the Feature there.

![image](https://user-images.githubusercontent.com/524520/37423396-b6e86784-278b-11e8-800a-4221cbfffee1.png)

Dude, where's my Feature?

![image](https://user-images.githubusercontent.com/524520/37423530-0f0016ba-278c-11e8-9818-a6d02f94b2ce.png)

**Comment by michaelkleinhenz** [comment]
@RickJWagner does the WI show up in the iteration on the list view? The board view in general is currently legacy and will be disabled for GA until we have the new board view available in the I train.

Nevertheless, we need to make sure the WI shows up correctly in the list view.

**Comment by nimishamukherjee** [comment]
@RickJWagner closing this issue. Please feel free to re-open this issue if it requires further discussion.
