### ISSUE TITLE
Clicking OK after importing your own source code leaves you stuck in the Add Codebase Application Wizard, with no Codebase added, only a Pipeline

### ISSUE THREAD

**Issue by nickboldt** [openshiftio/openshift.io#2592]
From a space ( https://openshift.io/kleinhenz-1/osio-planner ) I tried to import some code from github.com/nickboldt and wanted to find the p2 projects I have (p2-browser or p2diff).

After picking some code to import (I picked github.com/nickboldt/p2-browser the first time, then github.com/nickboldt/p2diff the second time), I kept clicking OK to pick defaults...

![import-01](https://user-images.githubusercontent.com/227597/37424220-5c4861ca-2796-11e8-885a-67d1615acd26.png)
![import-02](https://user-images.githubusercontent.com/227597/37424221-5e3168ba-2796-11e8-9aff-fd52c5bab9c4.png)
![import-03](https://user-images.githubusercontent.com/227597/37424227-60084780-2796-11e8-9585-f104c8dd7384.png)
![import-04](https://user-images.githubusercontent.com/227597/37424232-620ecac2-2796-11e8-839b-05b97cc7881e.png)
![import-05](https://user-images.githubusercontent.com/227597/37424235-63d6db6a-2796-11e8-8f93-e90bd69d721d.png)

...  and then I noticed that I was just cycling between step 1, 2, 3, 1, 2, 3 ... The wizard never let me back to my space page. 

![import-06](https://user-images.githubusercontent.com/227597/37424260-72e9ae70-2796-11e8-8d7f-e316a5a909ef.png)

So I clicked cancel.  When I refreshed the page, I saw that I have two pipelines, but no code bases:

![pipeline-but-no-codebase](https://user-images.githubusercontent.com/227597/37423866-51977fe6-2795-11e8-8e4e-d191f4553d12.png)

So... this looks like two bugs:

[ ] a) when importing, wizard never completes
[ ] b) when importing, wizard successfully creates a pipeline, but no codebase

**Comment by nickboldt** [comment]
Additionally, when I click on the p2-browser link next to the 'in progress' icon... 

![pipelines 01](https://user-images.githubusercontent.com/227597/37424513-ff5b9ff8-2796-11e8-9efa-791079546647.png)

I get a 404 with ninjas and https://openshift.io/_error ... but then a couple minutes later the link works.

**Comment by nickboldt** [comment]
oh, and one more thing... the imported projects both fail to build... one because for no apparent reason the job decided to bump my poms from 1.0.1-SNAPSHOT to 1.0.1 (and didn't do the same for MANIFEST.MF and feature.xml files) so a version mismatch occurs with Tycho and the build fails.

In the other, it failed because it couldn't find the pom to build.

So... since the codebase isn't being imported correctly, how can I configure Jenkins to build correctly?

**Comment by animuk** [comment]
Old legacy launcher is replaced with new improved launcher which should solved the above issue,
