### ISSUE TITLE
Error 404 when trying to view build in openshift console  (March 14 Testing)

### ISSUE THREAD

**Issue by GeorgeActon** [openshiftio/openshift.io#2594]
Reset my environment 
Ran the scenario  "Hello World for Developers"
In step 4.5

I clicked on Build #1 to  view build in the OpenShift console

got 
404: Have you seen this page? Probably not.

closed tab
clicked on the same link in pipeline again ... same result (multiple times)
use browser refresh on the pipelines screen 
clicked on same link
OpenShift console opened

**Comment by ldimaggi** [comment]
George - can you include the text of the URL (that led to the 404 error) presented in the build? Thx!

**Comment by GeorgeActon** [comment]
I do not see this issue anymore
