### ISSUE TITLE
Pipelines Report Inaccurate Times

### ISSUE THREAD

**Issue by cassiussa** [openshiftio/openshift.io#2596]
Going through the helloworldvertx demo for beta, I'm seeing some pretty inaccurate times for the Jenkins pipeline status.

See attached image.
![screen shot 2018-03-14 at 3 31 46 pm](https://user-images.githubusercontent.com/16277810/37426507-1154938a-279d-11e8-9292-d784539ae319.png)

**Comment by ldimaggi** [comment]
Can you provide more details here - what is not accurate? The difference in time from the build summary to the individual build steps is related to the time that was required for the Jenkins pod to start. Thx!

**Comment by cassiussa** [comment]
Hi,

Sorry I didn't specify.  In the image, it shows that the Approve Stage is 25350931m 45s in length.  The Rollout to Stage also initially displayed a similar value but then fixed itself after a minute or so.

**Comment by ldimaggi** [comment]
Closing as a dup of #1378
