### ISSUE TITLE
Dead links in pipeline view needs fixing or attaching

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#260]
Pipeline view has some links that are not working and others that needs attaching.

This issue comes from notes from @michaelvirgil based on @qodfathr comments.

**Comment by jstrachan** [comment]
fixed by https://github.com/fabric8-ui/fabric8-runtime-console/pull/507 just needs the new fabric8-runtime-console version merged into fabric8-ui and a release

**Comment by jstrachan** [comment]
fixed, just needs a new release of fabric8-ui which I don't have karma to do nor any visibility in when it happens.

**Comment by joshuawilson** [comment]
Just released latest.

**Comment by jstrachan** [comment]
@joshuawilson don't see it yet on openshift.io - is the new release supposed to be live? (would be nice to have a UI version in the status widget ;)

**Comment by joshuawilson** [comment]
@jstrachan Oops, I got distracted and didn't push the button to finish it. Sorry,
As to the version, there is already info in the About dialog.

**Comment by jstrachan** [comment]
@joshuawilson looks great now thanks!

**Comment by jstrachan** [comment]
@joshuawilson BTW I'd love the CD pipelines to comment on issues when they are available for testing in production!
