### ISSUE TITLE
Build Pipeline won't talk to un-idled Jenkins

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#2600]
I built a new workspace, I think at a time Jenkins was idled.  (I didn't look first.)
After my project was established, a build would never start.  Looking at the $USER-jenkins space,I saw Jenkins was idled and manually re-started the pod.
The build still will not start, even if manually requested.
Screenshots below.

1 - The build view.  'No stages have started'.

![image](https://user-images.githubusercontent.com/524520/37427122-57b81466-2796-11e8-9bc0-cdc83354d67f.png)

2 - Current Jenkins log.  A few interesting snippets:

Mar 14, 2018 7:29:33 PM jenkins.metrics.api.Metrics$HealthChecker execute
 WARNING: Some health checks are reporting as unhealthy: [disk-space : Only 0.397 Gb free on (master)]

Mar 14, 2018 7:43:33 PM okhttp3.internal.platform.Platform log
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?

![image](https://user-images.githubusercontent.com/524520/37427189-91705d1c-2796-11e8-87d7-382a3687576a.png)

**Comment by piyush1594** [comment]
@RickJWagner this won't happen right now. If Jenkins is idled and you start a build, then first Jenkins get unidled and build starts. There is a case where it is not, that issue is already there #3517 

@sthaha @RickJWagner can we close this issue?

**Comment by RickJWagner** [comment]
Unreproduceable.  Let's hope there is no bug and everything works.

**Comment by piyush1594** [comment]
Thanks @RickJWagner
