### ISSUE TITLE
In Planner Backlog View - the kabob on right is not visible 

### ISSUE THREAD

**Issue by GeorgeActon** [openshiftio/openshift.io#2602]
All of the other action are on the left 
the kabob would be more useful/obvious if it was on the left as well

By having it on the right, it is invisible to the user.

<img width="1106" alt="screen shot 2018-03-14 at 4 04 18 pm" src="https://user-images.githubusercontent.com/19672343/37428668-6331764a-27a3-11e8-960f-4c64f3218806.png">

**Comment by nickboldt** [comment]
Is a kabob what you get when you rotate an elipsis through 90 degrees?

**Comment by sahil143** [comment]
@sunilmalagi please confirm that we need to remove the last column with the quick preview icon and kebab menu as they are redundant actions.

**Comment by nimishamukherjee** [comment]
Closing this as on the current UI we do not have the kebab menu.
