### ISSUE TITLE
Experience under a Scenario should have an obvious sort order

### ISSUE THREAD

**Issue by GeorgeActon** [openshiftio/openshift.io#2603]
<img width="1106" alt="screen shot 2018-03-14 at 4 04 18 pm" src="https://user-images.githubusercontent.com/19672343/37428918-1cebff2e-27a4-11e8-8578-280217c095db.png">

The sort order seems to be random. 

Sort by order of creation, or by Title would be preferable

**Comment by DhritiShikhar** [comment]
@GeorgeActon The workItems should be ordered according to order-of-execution. This is an open issue and tracked here -> https://github.com/fabric8-services/fabric8-wit/issues/1960

**Comment by GeorgeActon** [comment]
@DhritiShikhar Can you define what is meant by order of execution?

**Comment by joshuawilson** [comment]
That means the order you want to do the work. You can move the items up and down according to what you plan to work on first.

**Comment by nimishamukherjee** [comment]
Looping on @openshiftio/uxd-team

**Comment by joshuawilson** [comment]
I don't think this is a bug for UX but a validation of the intentional design by PM. @slemeur

**Comment by slemeur** [comment]
Yes, I don't think it is a bug. 
Users are ordering by drag&drop the WI, which should be reflecting the priority or order of execution.

**Comment by christianvogt** [comment]
Closing as order is defined by dnd.
