### ISSUE TITLE
Ninjas appear when adding codebase, when I expected an import wizard

### ISSUE THREAD

**Issue by nickboldt** [openshiftio/openshift.io#2605]
Tried to add a codebase while stack analysis was in progress by clicking the (+) icon on the Codebases panel:

![image](https://user-images.githubusercontent.com/227597/37431601-152cdc7e-27ac-11e8-9ad5-1937f748a0e3.png)

Rather than seeing the import wizard, I got this:

![image](https://user-images.githubusercontent.com/227597/37431645-2f0bca56-27ac-11e8-8eb4-2a1bc863978f.png)

If I close the right-side panel via the X in the top right corner, ninjas appear!

I was able to make this happen twice. Then I clicked back, and instead got to this page:

https://openshift.io/nickboldt/myspace/create

From there I could re-open the right panel with the (+) `Add Codebase` button... but still no import wizard. Having to guess at what to put in the import field is not as user-friendly as browsing the repo with the wizard (as per screenshots in https://github.com/openshiftio/openshift.io/issues/2592 )

**Comment by aslakknutsen** [comment]
@nickboldt Best issue Title ever :)

**Comment by nickboldt** [comment]
@aslakknutsen Hilarious AND accurate. Best kind of issue. :)

**Comment by aptmac** [comment]
The old add-codebases action has been updated to use the new app launcher as of https://github.com/fabric8-ui/fabric8-ui/pull/2839.

**Comment by rhopp** [comment]
@aptmac FYI: For few first seconds after page load/reload, the plus sign still redirects to wrong page: https://github.com/openshiftio/openshift.io/issues/3489
