### ISSUE TITLE
Usability: Create Pipeline Wizard's error messages appear below the fold

### ISSUE THREAD

**Issue by nickboldt** [openshiftio/openshift.io#2606]
I'm trying to attach a pipeline to an existing codebase in my space. 

Codebase was imported from https://github.com/nickboldt/p2-browser and generated a Jenkinsfile for me. I then added a Che workspace to edit the code, but have no way to run it (because no pipeline was created).

And as noted in https://github.com/openshiftio/openshift.io/issues/2592 ... this project won't import as a pipeline by itself, so I'm forced to find a workaround. Just to build a maven project. Geez.

Anyway... if after creating the Codebase and the Che Workspace, I then try to add a pipeline for the same github project, I get this:

![image](https://user-images.githubusercontent.com/227597/37432756-e0489c7e-27af-11e8-991a-f1eaa8211e17.png)

Why is the `Next` button greyed out? 

Because of this hidden-beneath-the-scrollbar error:

![image](https://user-images.githubusercontent.com/227597/37432789-f78d93bc-27af-11e8-892b-8fef55b799e3.png)

Solution: put the error message somewhere that the user can SEE it. :)

**Comment by animuk** [comment]
Old legacy wizard has been replaced with new improved wizard in prod. Should be handled for that.
