### ISSUE TITLE
Space Collaborators page allows to call delete action on space owner

### ISSUE THREAD

**Issue by dgolovin** [openshiftio/openshift.io#2610]
Collaborators page for space shows `Remove from space` menu for space owner
![image](https://user-images.githubusercontent.com/620330/37438568-9b1371d2-27b0-11e8-8109-7f9043fc6046.png)
When `Remove from space` item selected it show warning dialog
![image](https://user-images.githubusercontent.com/620330/37438577-b4f64ea8-27b0-11e8-8aad-480ca6f7149a.png)
But remove button does nothing.

**Comment by alexeykazakov** [comment]
> But remove button does nothing.

Yeah.. because our backend won't allow you to remove the space owner :) UI should be fixed though.

**Comment by andrewazores** [comment]
Closing as roughly a duplicate of https://github.com/openshiftio/openshift.io/issues/2610 , for which a fix has been merged.
