### ISSUE TITLE
Space Collaborators page `View User` action navigates to my personal profile instead of selected user

### ISSUE THREAD

**Issue by dgolovin** [openshiftio/openshift.io#2613]
On Cpace Collaborators page if I select 'View User' action (se below):
![image](https://user-images.githubusercontent.com/620330/37441578-5dd59322-27bf-11e8-9cec-a7105e95e978.png)
It navigates me to page below which is my profile page. The email in left upper corner is shown for selected user.
![image](https://user-images.githubusercontent.com/620330/37441624-9b686b7e-27bf-11e8-9b49-5cd1966e3983.png)
Viewed collaborator now appears in my spaces
![image](https://user-images.githubusercontent.com/620330/37443761-4e803d8a-27cb-11e8-83d6-3c947ed4b00e.png)

**Comment by alexeykazakov** [comment]
It's not your email. It's your username. Some old developers.redhat.com accounts have username == email :(
But we have a bigger problem here. If you are logged in and open any profile page for any user you will see your own profile.
Try open https://openshift.io/alexeykazakov for example.

**Comment by alexeykazakov** [comment]
@rohitkrai03 could you please take a look at this.

**Comment by dgolovin** [comment]
@alexeykazakov good catch :) I can confirm I see my profile when I opened yours and now I have your user name listed among my spaces.

**Comment by rohitkrai03** [comment]
@alexeykazakov Looking into it.

**Comment by rohitkrai03** [comment]
@alexeykazakov I've found the issue and fix for opening any user profile while logged in. But still need to figure out to update my spaces, work items and connected accounts section when navigating to another user profile from within the application.

**Comment by alexeykazakov** [comment]
@rohitkrai03 all these actions just open a user profile page (which is broken), no? Anyway. Just fix the profile page for now. If there are some issues in Planner and other places where the open user profile page action is broken then you can just file an issue(s) for that for now. And let the corresponding team (Planner for example if it's in planner) to fix it.

**Comment by rohitkrai03** [comment]
@alexeykazakov There is problem with profile page as well. So, with the current fix for example if I open your profile from the link above, it will show your profile data with your spaces and work items. But when i click on profile button from the top right dropdown, data on left (email id, name, bio) changes and not the spaces section. This is happening because each of these sections have separate components and don't share data within them. That is why when profile data changes, other sections don't change accordingly.

**Comment by alexeykazakov** [comment]
Ah ok. Yeah. we should fix the profile page.

**Comment by joshuawilson** [comment]
@rohitkrai03 please talk to @dgutride as he has been looking into storing context info.
cc @corinnekrych

**Comment by rohitkrai03** [comment]
[PR](https://github.com/fabric8-ui/fabric8-ui/pull/2646) raised.

**Comment by rohitkrai03** [comment]
@alexeykazakov Closing this one.
