### ISSUE TITLE
There is no way to navigate back to Space home page form Codebases page

### ISSUE THREAD

**Issue by dgolovin** [openshiftio/openshift.io#2615]
Space 'Home page' below let you navigate to other sub-pages, but not all of them provides UI element to navigate back to space 'Home page'. 
![image](https://user-images.githubusercontent.com/620330/37444650-f58aecc0-27cf-11e8-8522-c03eb932bfa8.png)
The only way back form Codebases page below is browser's 'Back' button.
![image](https://user-images.githubusercontent.com/620330/37444665-0e1d9f58-27d0-11e8-94e9-0f47760745f1.png)

**Comment by joshuawilson** [comment]
`account home` is in the context menu on the upper left. But as this is not obvious to you, we should have UX take a look at it.
@catrobson

**Comment by catrobson** [comment]
Getting back to the Space Homepage is actually something you would click "Analyze" to do.  I agree it is not terribly obvious today that I would find this under Analyze - we'll consider this into our navigation design effort.

**Comment by dgolovin** [comment]
@joshuawilson account home would not work, because then I would need to select space form the list. @catrobson has right answer for me, I did not realize "Analyze' is getting me back to space's dashboard.
Feel free to close the issue, thanks!

**Comment by joshuawilson** [comment]
I misunderstood what you were asking for. But thankfully @catrobson can read better then me. :)
