### ISSUE TITLE
Import Existing Code wizard fails after quick pressing 'Next' and then 'Back' buttons

### ISSUE THREAD

**Issue by dgolovin** [openshiftio/openshift.io#2616]
The result is in animated gif below.
![download](https://user-images.githubusercontent.com/620330/37445780-14738960-27d7-11e8-9f87-8922fa7d555d.gif)
Progress is always running and even closing and reopening the wizard does not help. Full page refresh resets wizard to normal state.

**Comment by dgolovin** [comment]
Same problem with Quickstarts, it looks like generic problem with wizard itself.

**Comment by animuk** [comment]
Old launcher is replaced now, closing this
