### ISSUE TITLE
Quickstart wizard should have a back button

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#262]
The 5 step wizard for the quickstart app menu has a next and finished option, but should have a back option as well to go to a former step in the process to change something if required. At the moment the only workaround for this is to quit the process and start again from scratch.

How to replicate:
1. Add to space > Create a quickstart project
2. Add project type information in step 1 of the 5 step wizard and click next
3. Try to go back to correct information in a previous step. There should be an option for previous as well as next here.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1555

**Comment by joshuawilson** [comment]
Closing as I believe the latest version has a `back` button.
