### ISSUE TITLE
'Create Work Item' pressed in small window navigates to 'Choose new work item type' page with the same scrolling position

### ISSUE THREAD

**Issue by dgolovin** [openshiftio/openshift.io#2620]
... that makes all work items almost invisible.
To replicate, make Space dashboard page smaller (see screenshot below)
![image](https://user-images.githubusercontent.com/620330/37448203-94ea08d4-27e2-11e8-9ed1-7897aec5590f.png)
Press 'New Working Item' and get the page on screenshot below:
![image](https://user-images.githubusercontent.com/620330/37448344-2a900ac8-27e3-11e8-946d-7297aded3414.png)
Not critical, but confusing.

**Comment by nimishamukherjee** [comment]
Same as #2840

**Comment by aptmac** [comment]
The add-work-items page from the dashboard has been removed as of https://github.com/fabric8-ui/fabric8-ui/pull/2855
