### ISSUE TITLE
404 page has three identical links 

### ISSUE THREAD

**Issue by rkratky** [openshiftio/openshift.io#2622]
The 404 page (https://openshift.io/_error):

![osio404](https://user-images.githubusercontent.com/6623103/37452943-77ced690-2836-11e8-960c-16b07944b4f0.png)

contains three links:

- Take me home (button)
- Spaces
- My Dashboard

All three links lead to https://openshift.io/_home

**Comment by joshuawilson** [comment]
@mindreeper2420 please keep this in mind when you update the page.

**Comment by mindreeper2420** [comment]
@joshuawilson yes, they'll be updated once the 404 page is updated.

**Comment by aptmac** [comment]
Fixed in https://github.com/fabric8-ui/fabric8-ui/pull/2654
