### ISSUE TITLE
Logo linked in notif. emails doesn't exist

### ISSUE THREAD

**Issue by rkratky** [openshiftio/openshift.io#2623]
Notification emails include some logo, but the file doesn't seem to exist:

![osioemail](https://user-images.githubusercontent.com/6623103/37453579-63536512-2838-11e8-9e80-40a718ebf199.png)

File URL: https://openshift.io/_openshiftio/assets/images/openshift_logo_black.png

**Comment by joshuawilson** [comment]
@mindreeper2420 do you know why the logo image isn't there?

**Comment by mindreeper2420** [comment]
@joshuawilson most likely because the referenced logo was removed/moved and the URL was not updated. I believe it is referencing images from https://github.com/openshiftio/openshift.io/tree/master/src/assets/images, but @aslakknutsen would know more than I.

**Comment by aslakknutsen** [comment]
/_openshiftio/assets/images/openshift_logo_black.png

**Comment by rkratky** [comment]
@mindreeper2420 Any update on this? Now that I'm getting tons of notifications from OSIO, I'd like them to be pretty :)

**Comment by mindreeper2420** [comment]
@rkratky I do not know why - the image is present, but isn't being sent. @joshuawilson any idea why am image that is available in the repo and directory is not being served by openshiftio? The URL https://openshift.io/_openshiftio/assets/images/openshift_logo_black.png send a 404.

**Comment by muruGanesan** [comment]
@rkratky, @mindreeper2420,  any updates on this issue?

**Comment by aslakknutsen** [comment]
Duplicate https://github.com/openshiftio/openshift.io/issues/1375
