### ISSUE TITLE
User Profile and Settings UI to reflect new UX

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#2625]
The user profile area has been a mix of profile, dashboard, and user settings information.  In an effort to separate these concerns and put them into logical places in the information architecture, the UX team has an updated user profile page design to include just user profile information and work items.  All settings have been moved to a new "Settings" page.

https://redhat.invisionapp.com/share/FWFGF7VXMB8#/screens

UI Changes:
- [x] 'Profile' in user dropdown in top right should navigate to new version of profile design
 https://github.com/openshiftio/openshift.io/issues/2660

- [x] Implement UI to follow Profile design in InVision
https://github.com/openshiftio/openshift.io/issues/2661

- [x] Add 'Settings' to user dropdown in top right
https://github.com/openshiftio/openshift.io/issues/2659

- [x] Implement UI to follow Settings design in InVision
https://github.com/openshiftio/openshift.io/issues/2662

- [x] Alert Corinne of Settings area being completed so Feature Flags can be added to the system according to design

API Changes:
- [x] Access environment quotas without space ID #2889 

- [ ] Add object counts to returned environment quotas #2890

**Comment by catrobson** [comment]
@joshuawilson The new UI Designs are captured here.  I think we need to change both User Profile and User Settings as one development effort so we don't have loss of functionality as we move to this new model.

**Comment by joshuawilson** [comment]
I agree. We should also try to use Feature Flags.

**Comment by joshuawilson** [comment]
cc @chrislessard

**Comment by alexeykazakov** [comment]
FYI @rohitkrai03

**Comment by rohitkrai03** [comment]
@catrobson I think ability to make your email private/public is missing from the update profile page.

**Comment by rohitkrai03** [comment]
@alexeykazakov I think i should work on the current profile page fix without changing much of the underlying logic and code because this new design implementation would need us to implement all the components with a lot of changes. What do you think?

**Comment by alexeykazakov** [comment]
@rohitkrai03 I agree. Just fix it without massive refactoring. The code will be refactored anyway when implementing the new design.

**Comment by chrislessard** [comment]
@catrobson don't we already have a "Profile" option in the top right dropdown ?

**Comment by catrobson** [comment]
@chrislessard you're right, I'm not sure why I wrote that in the description.  Must have been multi-tasking not so effectively :).  Updated description to reflect.

**Comment by catrobson** [comment]
@rohanKanojia thanks for catching that, I'll have the profile design updated with public/private email

**Comment by rohitkrai03** [comment]
@chrislessard Can you please share any docs/discussions around the implementation details and design decisions? I want to get a better understanding of implementation strategy. I'd be happy to join any discussion around it if it is still going on.

**Comment by corinnekrych** [comment]
@rohitkrai03 @chrislessard We also need to:

- [ ] refactor the profile PATCH in https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/getting-started/services/getting-started.service.ts#L51 instead of creating a profile from exiting user we could create a profile with all the fields from the from + the required information (user_id). This is a patch not an update.

**Comment by chrislessard** [comment]
@rohitkrai03 I dont have any on hand, you should talk to @catrobson about this if you're interested. @mindreeper2420 might be helpful as well.

**Comment by chrislessard** [comment]
@catrobson @joshuawilson I believe this work is done ? Discussion in #2890 suggests that the work was completed in https://github.com/fabric8-services/fabric8-wit/pull/2175.

**Comment by joshuawilson** [comment]
This appears done. @catrobson what do you think?

**Comment by catrobson** [comment]
Agree this appears complete.  Closing!
