### ISSUE TITLE
Filtering/Searching: Work Items should be searchable by title

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#263]
Work items can currently be filtered based on area, assignee and type, but this is not useful when searching to see if an existing issue has already been logged. Work Items should be searchable by strings or keywords to be able to tell if the new issue would just be a duplicate.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2023

**Comment by michaelkleinhenz** [comment]
This is done and on prod.
