### ISSUE TITLE
Removing a pipeline in OSIO does not remove the endpoints deployed by that pipeline

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2631]
Related to: https://github.com/openshiftio/openshift.io/issues/2629

Steps to recreate:
* Create a new quickstart
* Observe the build pipeline runs to completion and deploys to stage and run
* Verify that the quickstart's endpoints are available
* Delete the build pipeline
* Verify that the quickstart's endpoints are still available

At this point, the user cannot initiate a new build for the quickstart. We should give the user the option to have the deployments removed when the build pipeline is removed.

**Comment by joshuawilson** [comment]
This is either a duplicate or an expansion of https://github.com/openshiftio/openshift.io/issues/1746

**Comment by ldimaggi** [comment]
Closing - issue is no longer seen.
