### ISSUE TITLE
Deleting an endpoint from the OSIO Deployments page does not delete the endpoint

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2633]
Steps to recreate:
* Create a new quickstart 
* Observe the quickstart's build pipeline successful completion and deployment to stage and run
* Navigate to the Deployments page and delete a deployed endpoint:

![screenshot 24](https://user-images.githubusercontent.com/642621/37486736-c1fcccb6-2865-11e8-8b16-96c9f9cca82d.png)

* Observe that the deployed endpoint is not deleted:

![screenshot 25](https://user-images.githubusercontent.com/642621/37486756-cfefb05e-2865-11e8-8498-e1129d75e01b.png)

**Comment by aptmac** [comment]
The PR that introduces the delete functionality hasn't been merged yet: https://github.com/fabric8-ui/fabric8-ui/pull/2626
