### ISSUE TITLE
Iteration selected on Plan/Backlog page does not show working items added to it

### ISSUE THREAD

**Issue by dgolovin** [openshiftio/openshift.io#2637]
There is a working item assigned to 'Third Iteration'

![image](https://user-images.githubusercontent.com/620330/37493786-67fea1dc-2863-11e8-91e5-805f4eebc822.png)

But when iteration is selected on Backlog page it says 'No Working Items Available'

![image](https://user-images.githubusercontent.com/620330/37493813-837db6c8-2863-11e8-95e1-f7aec46ba360.png)

**Comment by nimishamukherjee** [comment]
@dgolovin please check on prod. This issue has been fixed.
