### ISSUE TITLE
Error marker in pom.xml does not propose valid version of dependency.

### ISSUE THREAD

**Issue by Ohrimenko1988** [openshiftio/openshift.io#2639]
**Steps to reproduce:** 
 - Do steps which described in the paragraph 6.1 of this document: https://docs.openshift.io/getting-started-guide.html#analyze_che_dependencies
 - Pay attention that tip in error marker does not include information about valid version of dependency.

**Attachments:**

![screenshot from 2018-03-14 17-18-31](https://user-images.githubusercontent.com/22724619/37511876-0d01bc00-2909-11e8-83df-c2e1da069897.png)

![screenshot from 2018-03-14 17-18-35](https://user-images.githubusercontent.com/22724619/37511900-20faf596-2909-11e8-962d-761c2808670a.png)

**Comment by ibuziuk** [comment]
![image](https://user-images.githubusercontent.com/1461122/48903798-d3a4e080-ee5c-11e8-9880-9163ce2a587a.png)
This problem is not reproducible against the latest version 6.13.1 deployed on prod. Closing
