### ISSUE TITLE
Cannot deselect checkbox options in QuickStart Wizard Step 4

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#264]
Step 4/5 in the Quickstart wizard offers two checkboxes for CI and triggering builds. Neither can be deselected. Deselecting either or both of these results in OSIO verifying and then re-selects both. Not sure why this is an option to change if it can't actually be changed.

![checkboxes](https://user-images.githubusercontent.com/926572/27368011-7453d3b4-5693-11e7-9656-14012d9b9ad9.png)

Additionally, both steps 4 and 5 are titled Build Configuration and appear to be the same.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1556

**Comment by corinnekrych** [comment]
This issue is not reproducible. it has been fixed.
