### ISSUE TITLE
Notification messages overlap page items. 

### ISSUE THREAD

**Issue by Ohrimenko1988** [openshiftio/openshift.io#2640]
**Steps to reproduce:**
 - Do steps which described in paragraph 4.2 of this document: https://docs.openshift.io/getting-started-guide.html#analyze_che_dependencies
 - Pay attention that notifications overlap page items and it is impossible to close it. It will be great to add ability to close this messages by "x" icon.

**Attachments:**

![screenshot from 2018-03-14 16-21-09](https://user-images.githubusercontent.com/22724619/37512038-9ad7d60e-2909-11e8-9817-63efc8c66b71.png)

**Comment by muruGanesan** [comment]
@Ohrimenko1988, it is similar to #2643. 
UX solution is provided in #2643 so, remove UX team from this issue

**Comment by muruGanesan** [comment]
@Ohrimenko1988, @joshuawilson, 
Can you please close this issue? Because this is will be addressed in #2643

**Comment by joshuawilson** [comment]
closing as a duplicate of #2643
