### ISSUE TITLE
Pipeline starts displaying in several minutes after it status is changed to "Running".

### ISSUE THREAD

**Issue by Ohrimenko1988** [openshiftio/openshift.io#2641]
**Steps to reproduce:**
 - Do steps which described in the paragraph 4.2 of this document: https://docs.openshift.io/getting-started-guide.html#analyze_che_dependencies
 - Wait until status of “helloworldvertx” is “Running” 
 - Click on this pipeline and wait until page is loaded
 - Make sure that progress of pipeline’s building is not displaying at least several minutes.  

**Expected result:**
Progress of building pipeline is immediately displayed after loading the page of pipeline which has “Running” status.

**Observed result:**
Newly created pipeline with just changed status to “Running” does not comply with current state of pipeline.

**Comment by piyush1594** [comment]
@Ohrimenko1988 Can you reproduce right now. I think this is not the case in current prod. Yes, there may be little bit delay as the sync happens at an interval of 5 sec. Can you try and if this is not the case, can you close? cc @sthaha

**Comment by Ohrimenko1988** [comment]
@piyush1594 Sorry, I have some problems with access to my openshift.io account, so I will check it a bit later.

**Comment by Ohrimenko1988** [comment]
@piyush1594 I can't reproduce this issue

**Comment by piyush1594** [comment]
Thanks a lot @Ohrimenko1988 for your feedback
