### ISSUE TITLE
Add Assignee widget is not closed after double clicking or pressing "Enter" key

### ISSUE THREAD

**Issue by Ohrimenko1988** [openshiftio/openshift.io#2642]
**Preconditions:**
 We should prepare scenario or experience on the Work Item page
**Steps to reproduce:**
 - Select the just created item. After opening the side bar click on ‘+’ Add Assignee button
 - Select the assigned person from toolbar and try to finish choosing by double click or Enter key, or clicking on outside widget area.

**Expected result:**
A user expects that item should be chosen, and widget should be closed.

**Observed result:**
We can only select an item from the dropdown and then click on 'x' label. For many users, this behavior may be a little bit unusual.

**Comment by rgarg1** [comment]
Assigned to @sahil143. Refer point 6, 7, 8 in the doc: https://docs.google.com/document/d/1SjzX_j6ZaEApGoY0gKgnvU_FqpNT6M3uu6O7JeUTfrc/edit

**Comment by nimishamukherjee** [comment]
Fixed.
