### ISSUE TITLE
Notification overlaps the icon which is closing the 'work items detail' form  

### ISSUE THREAD

**Issue by artaleks9** [openshiftio/openshift.io#2643]
**Reproduction Steps:**
* Go to the _Plan_ section and create a work item
* Select the work item for update details
* Update content of the work item

**Expected result:**
* the notification has not to overlap the close icon

**Actual result:** 
* the notification overlaps the icon of close the _work items details_ form
* also, the timeout of closing the notification is a too long

**Build**: #1064

**Additional information:**
* Related to the issue #2640 
* See the attachment:
![notific-close-icon](https://user-images.githubusercontent.com/5408906/37512984-46d7e794-290c-11e8-8097-4778e6172447.png)

**Comment by rgarg1** [comment]
Assigned to @SMahil for a fix.

**Comment by SMahil** [comment]
@rgarg1 Notification position is consistent on overall OSIO. If we want to change the position a bit left to it, it will reflect on all existences.

**Comment by rgarg1** [comment]
@SMahil And a close button to dismiss the notification ould also help a great distance.

**Comment by SMahil** [comment]
@rgarg1 This would be an enhancement to notification design and that will go to Patternfly

**Comment by SMahil** [comment]
@muruGanesan @sunilmalagi Please have a look into this too

**Comment by sunilmalagi** [comment]
@SMahil @artaleks9 
Toast Notifications will be there for only few seconds and vanishes, there are chances that you might get to see 2 or more notifications also, overlapping cannot be avoided and wont interrupt the user flow.  In addition to it we suggested to reduce the no. of notifications refer #1554 for the same.
Here is the reference for more than a Toast notification:
https://redhat.invisionapp.com/share/EVGO26JRSXD#/289056606_-2643

**Comment by artaleks9** [comment]
I only would like add, that the the main reason of registration this issue is a inconvenience and irritation, when the notification hangs several seconds (overlaps the close icon) the   and I cannot to to go to the next action. My colleagues also said abourt it, when did the manual testing of the planner.
So if there is a possibility to improve here, it would be nice for users.

**Comment by rgarg1** [comment]
@artaleks9 @sunilmalagi +1 to the irritation factor. Even though the delay is only for a few seconds, it interrupts the user's workflow as there is no way to dismiss the toast notification.

**Comment by muruGanesan** [comment]
@artaleks9, 
As Sukhvir and Sunil said, the notification position is fixed for the entire OSIO. i.e. We are maintaining the consistency. 
But, There are two ways to fix this issue, (1) reduce the toast notification time (2) provide a 'close' (button) option to 'toast notification'.
@nimishamukherjee, @SMahil @sunilmalagi, @Veethika  Please discuss the about below design: 

<img width="343" alt="image" src="https://user-images.githubusercontent.com/26006817/38414000-e8e2fa84-39aa-11e8-83d8-5ab77af1f8be.png">

**Comment by muruGanesan** [comment]
@rgarg1 , @mihaelkleinhenz , @SMahil 
Please close this issue once it is fixed.

**Comment by joshuawilson** [comment]
This is fixed in production.
