### ISSUE TITLE
Filter user names list is empty when only one user exists in a space

### ISSUE THREAD

**Issue by SkorikSergey** [openshiftio/openshift.io#2647]
**Steps to reproduce:**

1. Create a space.
2. Add some work items.
3. Try to filter the work items by **Creator** or **Assignee** in **Filter**.

**Expected result:**
Owner user name exists in users list.

**Actual result:**
Users list is empty.

**Screenshot:**
![plan backlog - openshift io - google chrome_213](https://user-images.githubusercontent.com/7760565/37522360-52735c3a-292c-11e8-9b36-79677d314ef9.png)

**Comment by aslakknutsen** [comment]
Duplicate https://github.com/openshiftio/openshift.io/issues/1983
