### ISSUE TITLE
Dialog Create Work Item: Interaction flow for saving broken

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#265]
When creating a Work Item, you can leave title unsaved and still save values for the following fields:
* Assignee
* creator
* Area
* Iteration

However, when you try to add a description and save it, it gives an error (see screenshot). I assume this is because the WI is not yet created (i.e. title is not yet created) but this behavior seems inconsistent. Either you should be able to fill in all fields and then have one save or create button at the end of the form to create the new WI with  that info, or no fields should be saveable unless we add a title and save it first. The difference in behavior is odd.

![description](https://user-images.githubusercontent.com/926572/27368412-b7ecab76-5695-11e7-9b20-5333ef3a1730.png)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2026

**Comment by sanbornsen** [comment]
We don't have dialog create anymore. Non contextual detail add serves the purpose and it works fine.

**Comment by joshuawilson** [comment]
closing, please reopen if this is still an issue
