### ISSUE TITLE
Button in Create Iteration widget is active when name is not set (improvement)

### ISSUE THREAD

**Issue by musienko-maxim** [openshiftio/openshift.io#2650]
**Steps to reproduce:**
1. Go to the planner ->  Select iteration on Navigation Bar and click ‘plus’ icon. From usability point it's better to disable the button when field is empty.

**Comment by Veethika** [comment]
@musienko-maxim @nimishamukherjee in reference to the attached screenshot, unless the mandatory fields contain some values, the 'Create' button should be disabled.

<img width="641" alt="screen shot 2018-06-11 at 12 11 35 pm" src="https://user-images.githubusercontent.com/35127763/41216179-d9391970-6d70-11e8-94bb-a1fa6246831a.png">

**Comment by muruGanesan** [comment]
Since UX solution is provided, I remove the UX labels.
