### ISSUE TITLE
Calendar widget dropped down after closing the Create Iteration widget

### ISSUE THREAD

**Issue by musienko-maxim** [openshiftio/openshift.io#2651]
Steps to reproduce:
1. Go to the planner ->  Select iteration on Calendar widget dropped down after closing the Create Iteration widget and click ‘plus’ icon.  Open calendars.
2.  Reopen Calendar widget.
Expected result: The widget should be empty and ready for the entering new data
Actual result: The Calendar widget still dropped down and overlapped Create and Cancel buttons

See also screencast: https://drive.google.com/file/d/1P8hj8iBPdx0tn0qbsfFsywlJ_l5obzfU/view?usp=sharing

**Comment by rgarg1** [comment]
@vikram-raj The calendar stays visible on reopening the create iteration dialog. Please have a look.

**Comment by nimishamukherjee** [comment]
Fix on prod
