### ISSUE TITLE
Cannot select scenario items in the navigation bar menu when cursor is not over the name item

### ISSUE THREAD

**Issue by musienko-maxim** [openshiftio/openshift.io#2652]
**Preconditions:**
 We should have some iteration items on the Navigation Bar of planner page.
**Steps to reproduce:**
1. Go to the planner  page and try to select the iteration item by clicking on area without the label with a name
See also screencast: 
https://drive.google.com/file/d/1pWpWwSXHWPyZSObAlOx4IkHhJle_9mKf/view?usp=sharing

**Comment by rgarg1** [comment]
@SMahil The entire Iteration are is not clickable, but just the iteration name. Kindly look at it.

**Comment by SMahil** [comment]
@sunilmalagi Please share your views on how we should select iteration (only name or whole iteration block)

**Comment by SMahil** [comment]
This issue has been fixed
