### ISSUE TITLE
Misleading error message in Create Iteration widget when we type invalid name - is not clear

### ISSUE THREAD

**Issue by musienko-maxim** [openshiftio/openshift.io#2653]
**Steps to reproduce:**
Go to the planner ->  Select iteration on Navigation bar and click + icon.
Type name more than 65 symbols long and click to Create button
Wrong:  The message like Something went wrong. is not informative for a user

The closed Column on Board page is not fully visible
**Steps to reproduce:**
 A user have monitor with 1680x1050 resolution. He go to the Board page and try to drop an item to closed status
**Expected result:** A user should have possibility to move items to closed column
**Actual result:** The column is not fully visible and is not scrollable
See also screenshot: https://drive.google.com/file/d/1UaD9SncnEE1kLwfyBjFBz6GqsqzBmrHh/view?usp=sharing

**Comment by rgarg1** [comment]
@michaelkleinhenz @kwk When do we implement error messaging from the backend?

**Comment by kwk** [comment]
@rgarg1 
> @michaelkleinhenz @kwk When do we implement error messaging from the backend?

We have error messages coming from the backend but they are not used by the client most of the time.

**Comment by michaelkleinhenz** [comment]
And all issues around the board view are now legacy because board view is no longer in prod and will be refactored in Iris.
