### ISSUE TITLE
Work item can't be added as a child node to the selected scenario (improvements)

### ISSUE THREAD

**Issue by musienko-maxim** [openshiftio/openshift.io#2654]
**Steps to  reproduce:** 
**Precondition:** A user has scenario  with name New Scenario and some child (Experience1). 
1. Select Experience field from navigation bar. Select the scenario.
2. Open dropdawn from Add Work Item section
3. Select Experience or Value  from the list. Set name and add this one.
**Expected result:** The user expects that just added work item set as child node for scenario. 
**Actual result:** But the item creates separately.
**Screencast here:** https://drive.google.com/file/d/1dsb3Kpe4QVECcsbSj12HDht0w44-SIAR/view?usp=sharing

**Comment by rgarg1** [comment]
@musienko-maxim Can you please list the exact steps that you took. Please note that A scenario can only have an _Experience_, or a _Value proposition_ as a child.

**Comment by musienko-maxim** [comment]
Sorry i fixed scenario.

**Comment by michaelkleinhenz** [comment]
Top level quick-add is only for adding new root-level work items. Childs are created using the contextual quick add (+-icon on the list element itself).
