### ISSUE TITLE
  Deployments -> POD the collapsing feature may be  not clear for some users (improvent)

### ISSUE THREAD

**Issue by musienko-maxim** [openshiftio/openshift.io#2658]
![selection_006](https://user-images.githubusercontent.com/1640058/37528096-621c82f0-293c-11e8-912a-c04c9a7ef4a9.png)

**Comment by aptmac** [comment]
Related to: https://github.com/openshiftio/openshift.io/issues/2226

**Comment by andrewazores** [comment]
Closing as duplicate of #2226 .
