### ISSUE TITLE
File Attachments for Work Items

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#266]
When using Work Items to report issues, it's very useful to be able to add an attachment to illustrate the problem or show the error, etc. At the moment, we can't do this. I would suggest this should be high priority otherwise work items are not as useful as intended.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2027

**Comment by debloper** [comment]
Track #795

**Comment by joshuawilson** [comment]
Closing as it is a duplicate.
