### ISSUE TITLE
Investigate sudden increase in rows returned in Core DB after deployment the 16.

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#2668]
![screenshot from 2018-03-17 14-01-54](https://user-images.githubusercontent.com/132158/37555698-db353c0e-29eb-11e8-9860-4b4f5bfde51b.png)

## Parent Scenario
#2016 OpenShift.io has best-of-breed performance

**Comment by maxandersen** [comment]
is that a 1000k rows returned constantly extra every few minutes ? thats pretty intense ;)

got a link to that diagram live btw.

**Comment by aslakknutsen** [comment]
No, but you can graph it via the OSD Monitor using: DB-f8core.postgresql.stat.database.tup_returned.postgres

**Comment by aslakknutsen** [comment]
Could seem like the root cause is https://github.com/openshiftio/openshift.io/issues/2666
A bit curious why it started showing up the 16. tho...

**Comment by aslakknutsen** [comment]
Fixed by https://github.com/fabric8-services/fabric8-wit/commit/02875f17b7051d569bd3f95a4dbce5b1ab443bb2

![screenshot from 2018-04-11 00-36-28](https://user-images.githubusercontent.com/132158/38587288-34a4a7d2-3d21-11e8-969d-271e21d4200f.png)
