### ISSUE TITLE
Detail View/Quick Preview: Area (possibly other fields) titles render badly if they are longish

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#267]
Children/grandchildren do not render well in the text boxes if they have long-ish names. See screenshot for examples.

![overlap](https://user-images.githubusercontent.com/926572/27368558-9fd47d06-5696-11e7-8a65-0bbf9a90630a.png)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2028

**Comment by sdash-redhat** [comment]
Here is a highlevel guideline on how much text we should display before we show ellipses (...) Slide -4 at . https://redhat.invisionapp.com/share/23CC7R3QZ

**Comment by sdash-redhat** [comment]
Some more guidelines also are on slide 6 : 

https://redhat.invisionapp.com/share/23CC7R3QZ#/screens/235814948

**Comment by SMahil** [comment]
This issue does not exist now
