### ISSUE TITLE
Docs: Update getting started flow 

### ISSUE THREAD

**Issue by dgutride** [openshiftio/openshift.io#2674]
Openshift is automatically connected for new users now and the getting started page will not show any longer.  Any documentation referencing the getting started page (with the checkboxes to connect openshift and github) should be removed.  The user will be automatically routed to OpenShift now to authenticate the OpenShift.io connection.

**Comment by joshuawilson** [comment]
@rkratky this change is currently in prod-preview. Since this appears to be mostly removal, do you know how long it will take.

**Comment by rkratky** [comment]
@joshuawilson This should be very straightforward. We'll try to have it done by tomorrow. We've been tracking this in https://github.com/fabric8io/fabric8-online-docs/issues/150

**Comment by mishaone** [comment]
Updated here: https://github.com/fabric8io/fabric8-online-docs/pull/213

@joshuawilson - question since I can't test this myself without a new account: Does the new user have to connect their GitHub account or is this no longer necessary as well?

**Comment by joshuawilson** [comment]
@mishaone you can disconnect your github account on your profile page in OSIO.

**Comment by mishaone** [comment]
Another PR to address the GitHub part: https://github.com/fabric8io/fabric8-online-docs/pull/216

**Comment by rkratky** [comment]
@joshuawilson The updated docs are now on prod-preview.

**Comment by joshuawilson** [comment]
thanks @rkratky @mishaone

**Comment by mishaone** [comment]
This looks like it's okay to close. Please reopen if further action is required.

**Comment by rkratky** [comment]
> @rkratky this change is currently in prod-preview.

@joshuawilson Do we have any mechanism that would allow us to check whether or not a feature has already been pushed to prod (besides actually going to test it manually in prod)? In other words, how do we know when to push respective docs to prod?

**Comment by joshuawilson** [comment]
you can ask me or look at the history of https://github.com/openshiftio/saas-openshiftio/blob/master/dsaas-services/fabric8-ui.yaml
