### ISSUE TITLE
Jenkins is not unidling on accessing openshift.io

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#2678]
Steps to reproduce:- 
1. Access openshift.io. If your jenkins is idled, you will get a grey mark for jenkins. Generally jenkins should unidle in 3-5 min, but let's wait for 10 mins.
(After 10 min it will still remain grey, thus jenkins is still idle)
2. Open jenkins.openshift.io. You will see a spinning wheel. It would last for a while (3-5 min) and then you will be redirected to your jenkins dashboard. (That mean jenkins is unidled)
3. Refresh openshift.io now. You will see a green tick on jenkins (Jenkins is unidled)

(I have confirmed this scenario with two different users)

I think this is a jenkins-proxy issue.

**Comment by jfchevrette** [comment]
Jenkins should only unidle on direct access, github webhook or new build. It should **not** unidle if the user is simply accessing openshift.io, planner, che, etc..

**Comment by hferentschik** [comment]
The behaviour is as expected. As @jfchevrette, the whole idea/design of the Idler is to un-idle on direct request, either through the UI or indirectly by a build. It does not and afaiu should not un-idle when accessing "only" openshift.io.

**Comment by kishansagathiya** [comment]
For the time being, we should put this in docs since it is a deliberate design decision. 
But this doesn't seem to be a good design decision to me since a lot of users thought of it as a bug.

Plus I would not expect people to put efforts to read the documentation to know about such things. The fact that I have to go to a different page to unidle Jenkins is also not a very graceful expirience.

This is what I would like to change here:- 

1. The grey icon which we see when jenkins is idle represents a bug or a failure. We need something that delivers the message that Jenkins has not failed, they are idled,  It's all good, this is how things should be. I would suggest some color lighter than green, but closer to it, instead of black, which is completely contrasting. Probably yellow.

2. If possible we can give a button to unidle Jenkins from the openshift.io page. And we don't have to anything magical there, that button can just redirect to jenkins.openshift.io.
Button (with appropriate text and message) could be shown whenever user hovers over the jenkins status.

**Comment by chmouel** [comment]
I like option 2. I think that would bring some better indiation to the user of what they need to expect, jenkins is idled and they need to click to unidled it

**Comment by kishansagathiya** [comment]
@chmouel They are not options. We can do both.

**Comment by chmouel** [comment]
@kishansagathiya yes we can but the type of colors this should be is the UI area so I'd rather let them comment on this

**Comment by mishaone** [comment]
The grey area seems correct. It represents the Idle state, correct? Once Jenkins starts to get out of the Idle state, the icon should change to the existing waiting icon. Users should be able to manually intervene if they see the waiting or Idle icon and want to nudge Jenkins awake manually. -1 to the button sending users to jenkins.openshift.io because that page is just a spinning icon, no action is clear to a user who doesn't know what they should be doing next. From a (novice) UX perspective, no clear direction or action seems like a bad idea.

**Comment by mishaone** [comment]
For clarity, what I mean by the waiting icon is this Jenkins icon: https://docs.openshift.io/images/tenant_status_waiting.png

**Comment by kishansagathiya** [comment]
> . -1 to the button sending users to jenkins.openshift.io because that page is just a spinning icon, no action is clear to a user who doesn't know what they should be doing next. From a (novice) UX perspective, no clear direction or action seems like a bad idea.

Makes sense. I have updated my comment.

**Comment by joshuawilson** [comment]
We need to UX involved on this, @catrobson. 
We might also want to un-idle when the user starts the wizard, if we don't already. Aside from the wizard, why would I want jenkins un-idled unless I'm going to the pipelines page. Those are really the only two places that touch Jenkins. 
Hmm. Maybe if we have a dashboard component for Pipelines, If the user touches that or if you really want an un-idle button it could go there.

**Comment by ldimaggi** [comment]
I think that we will want to add an "un-idle" button - we may not be able anticipate in advance EVERY user's action.

**Comment by jfchevrette** [comment]
Why would a user want to manually unidle jenkins? 

- All links to jenkins should point be https://jenkins.openshift.io/* which will get jenkins unidled by the idler proxy
- Any new builds created in OpenShift will also cause jenkins to unidle
- Webhooks sent to jenkins (through the jenkins.openshift.io endpoint) will unidle it

Where else would we want to have jenkins unidled?

**Comment by catrobson** [comment]
Agree we absolutely do not want an "un-idle" button for users, this is showing way too much of our system guts ;).  Thanks for a great explanation of when we should unidle programatically @jfchevrette!

**Comment by chmouel** [comment]
Cam we assume that if a user goes on openshift.io she would want to go eventually on jenkins.openshift.io and we can then help with that and do some work beforehand by unidling it ? I understand that the system guts should not be exposed to the end-user but the 5mn spining wheel experience is not that great either, (although if @jfchevrette tell us that it would add a huge performance strain on the system then i don't think we should not change anything there).

**Comment by jfchevrette** [comment]
@chmouel not all users browsing openshift.io will need the build pipelines right away. Some may (only) use the planner while some others will launch Che and write code. 

Do we know how many unique users login to OSIO everyday? How many concurrent logged-in users are browsing openshift.io at any given time?

**Comment by mishaone** [comment]
Would it make sense to trigger the unidle for Jenkins if the user clicks the the Analyze and Create tabs? Plan should not require it, as pointed out by others. I don't think we necessary need to expose our guts with an unidle button if we label it something like "manually reset Jenkins" or something to make it clear to users that this is a last resort for troubleshooting if Jenkins should be out of the idle state but isn't.

**Comment by kbsingh** [comment]
the right thing to do here is to  display an 'idled' status in the right drop down, when just a status is required to be displayed. Jenkins ( or any other assets ) should not be unidled for the sake of unidling.

**Comment by kbsingh** [comment]
added team/ux for recommendation on what is the best way to communicate this idled status

**Comment by aslakknutsen** [comment]
Didn't we plan to remove the Status's from the UI anyway? And Jenkins already unidle when it needs to. Close this issue?

**Comment by catrobson** [comment]
@aslakknutsen - I'm still trying to get concise feedback on whether we are going to make the status dropdown functional, or if we just want to remove it from the system completely for now.  I'm OK with either direction, but there seems to be some activity towards fixing it and some thoughts towards getting rid of it.  Can you help resolve in Platform Mtg Monday?  I'll be at SKO with Todd so I won't be able to attend.

**Comment by aslakknutsen** [comment]
@catrobson Sure. WIll do

**Comment by chmouel** [comment]
have fun at the SKO @catrobson

**Comment by mishaone** [comment]
Please add the decision here for visibility (and docs, if needed).

**Comment by qodfathr** [comment]
@kishansagathiya why did you remove the SEV2 label? All bugs need to have a severity label. Did you intend to replace with a different severity label?

**Comment by joshuawilson** [comment]
@catrobson We reviewed the status dropdown and do not have any services that makes to post there. Therefore, we recommend removing it.
Do you agree @qodfathr?

**Comment by kishansagathiya** [comment]
@qodfathr This is not really a bug, but a UX decision about status drop down. The issue title is misleading.

**Comment by qodfathr** [comment]
@joshuawilson if it's not doing anything, remove it.
@kishansagathiya I'm reacting to the fact that this is labeled 'type/bug'. If the type needs to change, we should change it. If it is a bug, is needs a severity.

**Comment by joshuawilson** [comment]
The `status` menu has been removed from production. This has no impact on idling. 

@kishansagathiya Is the removal of the menu enough to close this or is it still an issue?

**Comment by kishansagathiya** [comment]
I think we can close this.
