### ISSUE TITLE
Detail View/Quick Preview: clicking outside the 'Assignees' popup box should close it

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#268]
When an assignment selection is unchanged, clicking outside the pop-up box should auto-close it. No need to have an additional 'Cancel' button. 

Similarly, the first item in the drop-down list could remain empty and that would eliminate the need of the 'Unassign' button too, giving us a cleaner UI and lesser clicks.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2029

**Comment by sdash-redhat** [comment]
Any popup box, combo box flyout, info-tip , popover (without close icon too), should be closed as a general rule - 
1. when clicking outside the box..
2. Also pressing ESC key on keyboard. 
-------
In case of Modals, pressing ESC key on keyboard should also close it apart from clicking on X icon.

**Comment by nimishamukherjee** [comment]
OSIO issue - https://openshift.io/openshiftio/openshiftio/plan/detail/1528

**Comment by qodfathr** [comment]
The current implementation is a modal with an 'X' close button, so I'm not sure that "clicking outside the modal should dismiss it" is still valid or not (@sdash-redhat that's something for UXD to determine). However, `ESC` does not close the modal, and it should. That was mentioned earlier in this discussion. Do we want to modify this issue to also be about `ESC`, or should we open a new issue?

**Comment by rgarg1** [comment]
The issue is fixed in production for _Assignees_ and _Label(s)_ selectors. LGTM!

However, the escape key issue still exists as mentioned by @qodfathr and I'll track it via a separate issue.

**Comment by rgarg1** [comment]
Opened: https://github.com/openshiftio/openshift.io/issues/3502
