### ISSUE TITLE
Create Feature Flag for Active Development

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#2680]
In the current Feature Flag configuration, there does not exist a flag for items that are needed to be hidden behind active 'development' flag. This is causing multiple contributors on a given story to work on shared branches, which can not only cause merge and history problems, but issues with sharing work.

Ideally, there would be an active development toggle that would allow multiple developers to work on a component/improvement directly through prod-preview, rather than on shared branches.

**Comment by joshuawilson** [comment]
cc @corinnekrych @xcoulon

**Comment by joshuawilson** [comment]
While I know we want to use feature flags, have you considered doing one dashboard component at a time? This will keep your commits limited to just one thing, thus making merges easier. 

small commit == easy to review

I do understand this would mean delivering only part of the update, but I think it would be safer to deliver a partial feature that is fully complete and ready for merging.

**Comment by mindreeper2420** [comment]
@joshuawilson normally, I'd agree (and have done), but this is a new dashboard, not just new pieces.

This will become more of a thing, as we begin to create new pages and look to change out entire sections of the UI with updated components and designs that do not make sense on individual component levels. In the case of the Dashboards (and the driver for this issue), everything flows together and would not work as designed if only pieces were added individually.

**Comment by corinnekrych** [comment]
I'm closing it linked to the f8-feature-toggles rework
