### ISSUE TITLE
Prod-Preview 500 Error

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#2681]
When accessing prod-preview, I'm currently stuck on 'Internal Server Error' screens. On the off chance that I can access the application (every 20-30 minutes for about 1-2 minutes at a time), I receive multiple websocket errors in the console, as well as 500 errors.

I've also received the following screen for api.prod-preview:
![screen shot 2018-03-19 at 2 45 13 pm](https://user-images.githubusercontent.com/4032718/37615642-2d11f096-2b84-11e8-945a-7fb7f48abf7c.png)

These errors only occur after clicking 'Log In' on the landing page.

**Comment by ldimaggi** [comment]
It's not just Adam - I am seeing this too - March 19, 15:00 (EDT/US)

**Comment by pbergene** [comment]
Is this a preview account that used to exist targeting free-stg or from idev issues? I think it should all be in order now.

**Comment by mindreeper2420** [comment]
I no longer have this issue and have been able to successfully log in for a few days now.

**Comment by mmclanerh** [comment]
sounds like this is resolved. we can open a new issue if we encounter new problems.  thanks!
