### ISSUE TITLE
launcher-backend consuming 3GB of memory per pod - no resource limits

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#2683]
My understanding of what launcher-backend does makes it hard to justify why it requires to use so much memory... 

We should also add resource limits (cpu & memory) to the deploymentconfig.

![launcher-backend-memory](https://user-images.githubusercontent.com/3001/37618100-69977cd2-2b8b-11e8-9cdc-55d6e26009d0.png)

**Comment by krishnapaparaju** [comment]
@jfchevrette  NOW got memory limits calculated for launcher backend (currently no limits are in place). Planning to use 3 replicas each with limit of 1 vCPU and 1.5 GB.  @animuk can you promote these changes to prod-preview

**Comment by jfchevrette** [comment]
@krishnapaparaju 1.5GB still seem like a LOT of resources for something that seemingly do very little. Why do this need so much memory? My understanding of launcher-backend is that it clones quickstart repos, create zip files and sends them to users or openshift. 

Can we audit the service and try to understand/explain why it needs so much memory?

**Comment by aslakknutsen** [comment]
@alexeykazakov You got the JVM options for more aggressive GC etc that we used for KC?

**Comment by aslakknutsen** [comment]
> Can we audit the service and try to understand/explain why it needs so much memory?

Simply because Java won't spend CPU resources on cleaning up memory unless it has to because it needs more or you tell it to. There are options to configure that on startup. We did that with KC.

**Comment by alexeykazakov** [comment]
> You got the JVM options for more aggressive GC etc that we used for KC?

Yes we do: https://github.com/fabric8-services/keycloak-deployment/blob/master/openshift/keycloak.app.yaml#L132-L146
(inspired by https://developers.redhat.com/blog/2014/07/22/dude-wheres-my-paas-memory-tuning-javas-footprint-in-openshift-part-2/ )
See some graphics here - https://github.com/fabric8-services/keycloak/pull/71

With these settings Java releases some free memory even before

**Comment by krishnapaparaju** [comment]
sure. These resources were calculated based on assumption to have 500 concurrent users and Non-Git API return the response in around 1 second. @animuk  can you please work with @jfchevrette ..

**Comment by animuk** [comment]
Sure @krishnapaparaju . will be checking

**Comment by jfchevrette** [comment]
@animuk @krishnapaparaju right now a **single pod** uses 3.4GB of memory. This needs to be addressed before we even attempt to lower the memory limit to 1.5GB (which I still think is way too much for that this service does)

![launcher-backend-mem](https://user-images.githubusercontent.com/3001/37916332-8ad179c6-30e9-11e8-85d0-155bb95c8d0d.png)

**Comment by animuk** [comment]
@jfchevrette single pod uses 3.4 GB of memory right now because there is no hardware resource constraint available in the yml file which we are planning to add in order to reduce the memory usage upto 1.5 GB.

**Comment by animuk** [comment]
Once we add the resource contraint in the metadata yml, application limits its use upto 1.5 GB

**Comment by jfchevrette** [comment]
@animuk resource limits are not "hardware constraints" like a VM. The pod still reports the host's memory capacity (16GB per node in our case). What this will do however is if the process exceeds the limit, openshift will kill the pod (through OOM killer)

**Comment by jfchevrette** [comment]
@animuk maybe java has some magic that picks up the openshift/cgroups limits and will then limit the java process to whatever was set as a memory limit? Has this been tested/proven successfully yet?

**Comment by krishnapaparaju** [comment]
@animuk Promote changes related to resource limits that you have calculated along with improving resource numbers if possible.

**Comment by krishnapaparaju** [comment]
@jfchevrette Java inside a container is tricky. Followed instructions from this blog and could test application with the limits being discussed.  

https://developers.redhat.com/blog/2017/03/14/java-inside-docker/

**Comment by gastaldi** [comment]
Parent issue: https://github.com/fabric8-launcher/launcher-planning/issues/142

**Comment by gastaldi** [comment]
@krishnapaparaju the only thing that is kept in memory is the booster-catalog metadata, which is constantly queried, and that doesn't (or shouldn't) consume much memory (obviously not more than 3Gb). My bet is that the OSIO legacy addon may contain code with memory leaks (it uses caching intensively) - which IMHO is another big reason to get rid of it ASAP.

**Comment by gastaldi** [comment]
@krishnapaparaju @animuk we have updated the `Dockerfile.deploy` file to use the Fabric8 image, which (in theory) automatically adds the necessary parameters to tune the JVM according to the running container. We now must find a decent value for the resources entry in the `openshift/template.yaml`.

**Comment by gastaldi** [comment]
I added the aggressive GC settings used in KC in the launcher-backend and configured the template to use a minimum of 768 MB and maximum of 2 GB memory. Also to exit on OOM. 

Running on prod-preview ATM, let's see how it goes.

**Comment by gastaldi** [comment]
Updated production with 3 pods and configuration above. I think we can close this issue for now and reopen if the problem persists.
