### ISSUE TITLE
Change to RH maven artifacts alters expected results in analytics reports (Dependency Details)

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2684]
We have an automated test that runs several times per day and verifies the creation of a stack report. The test does not verify many contents of the report, but it does check the Dependency totals. 

Based on the test results for the Vert/X HTTP quickstart, the results that we are seeing are changing/inconsistent as the tests are frequently reporting unexpected results and are failing. 

The results that we're seeing are:

Prior to March 7: Total 2, Analyzed 0, Unknown 2
After March 7: Total 2, Analyzed 2, Unknown 0
Since March 16: Total 2, Analyzed 0, Unknown 2

For this Quickstart, shouldn't the results always be:  Total 2, Analyzed 2, Unknown 0   ?

**Comment by ldimaggi** [comment]
Issue found/encountered by EE tests

**Comment by msrb** [comment]
This looks really suspicious. @miteshvp any idea what may be going on there?

**Comment by ldimaggi** [comment]
Thanks for the rapid reply! One question - what should the results look like?

**Comment by msrb** [comment]
@ldimaggi I'd expect to see `Total 2, Analyzed 2, Unknown 0`, but quickstarts recently switched from pristine Maven artifacts to RH-branded ones. I guess that could be the reason why you get `Total 2, Analyzed 0, Unknown 2`.

**Comment by ldimaggi** [comment]
My expectation was always 2, 2, 0

We are currently seeing 2, 0, 2

But - is this change expected or a bug?

**Comment by miteshvp** [comment]
@ldimaggi - yes its because we changed the quickstart to pick RH ones. Those are unknown to us and 2, 0, 2 looks along the expected lines. cc @msrb

**Comment by ppitonak** [comment]
@miteshvp, when will be analytics able to handle RH artifacts? Can you link issue for that here?

**Comment by miteshvp** [comment]
@ppitonak - we are just getting started here - https://github.com/openshiftio/openshift.io/issues/2481

**Comment by krishnapaparaju** [comment]
Its related to mix of various approaches been tried ti support RH specific dependencies. @sara-02 is looking into this issue to resolve these inconsistencies around numbers for KNOWN, UNKNOWN dependencies..

**Comment by sara-02** [comment]
@krishnapaparaju This inconsistency is expected as the are downstream versions are unknown to us(as per the above discussion), the previous inconsistency introduced due to code change has been resolved here https://github.com/openshiftio/openshift.io/issues/2530

**Comment by sara-02** [comment]
@ldimaggi Thanks, this title reflects the problem better.

**Comment by ldimaggi** [comment]
@sara-02 

No worries! Question - will these values be consistent - or should we expect them to change again?

**Comment by msrb** [comment]
@ldimaggi it really should be `Total 2, Analyzed 2, Unknown 0`. What we don't know yet is how to get there. We will see after the meeting on Friday.

I think there are 2 options:
- either try quickly add support for 3rd party repositories to fabric8-analytics, just to make this work somehow
- or go back to pristine Maven dependencies in quickstart projects and switch to RH artifacts at some point in future, when analytics is ready

**Comment by msrb** [comment]
![screenshot from 2018-03-26 14-34-27](https://user-images.githubusercontent.com/3759039/37906606-fe3e8908-3102-11e8-9921-8683387826cf.png)

Adding screenshot of the issue.

**Comment by sara-02** [comment]
@ldimaggi Can you please test again for `Vert/X HTTP quickstart`

**Comment by ldimaggi** [comment]
Is this the expected result?

![screenshot from 2018-04-04 09-00-24](https://user-images.githubusercontent.com/642621/38309129-26d6ef14-37e7-11e8-83d9-4c09c55a3507.png)

**Comment by sara-02** [comment]
@ldimaggi Yes. The dependencies are not unknown anymore.

**Comment by ppitonak** [comment]
Was the root cause fixed or you just reverted back to community bits?

**Comment by sara-02** [comment]
The root cause was fixed for the production data.
