### ISSUE TITLE
f8osoproxy using causing >8GB memory, causing OOM

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#2685]
f8osoproxy pod quickly ramp up to >8GB memory usage after some time.

This has been observed on staging/preview ONLY.

The last few log entries shows logs of requests to **watch** buildconfigs on namespace **josh-6** at a rate of about 1 per second. Are we filling memory by establishing too many watches/spawning lots of goroutines?

```
GET /oapi/v1/namespaces/josh-6/buildconfigs?watch=true&access_token=REDACTED HTTP/1.1
```

![f8osoproxy-oom](https://user-images.githubusercontent.com/3001/37621392-2918ebfa-2b95-11e8-86e6-e62cd70f0e57.png)

**Comment by joshuawilson** [comment]
I shut down my one running page at 2306 EST / 0306 UTC. I had been on the final page of the old wizard. I did not shut down any pods, just the wizard and the UI.

**Comment by pbergene** [comment]
Still anecdotal, but we've had 3 OOM'd nodes this morning - all of which had an f8osoproxy running on them.

**Comment by aslakknutsen** [comment]
OSO Proxy reconfigured in preview. Stable since. Monitoring. https://github.com/openshiftio/openshift.io/issues/2693

**Comment by aslakknutsen** [comment]
Related "Centralize cluster configuration across services #1988"

**Comment by aslakknutsen** [comment]
Root causes identified and linked. The issue is no longer seen in preview. Closing this issue.
