### ISSUE TITLE
return JSONErrorResponse is unsafe to use within Transaction block

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#2687]
In the current form JSONErrorResponse hide the root error and avoid the transaction from rolling back on error.

typical usage:

```go
	err := application.Transactional(c.db, func(appl application.Application) error {
		err := appl.Comments().Delete(ctx.Context, cm.ID, *identityID)
		if err != nil {
			return jsonapi.JSONErrorResponse(ctx, err)
		}
		return ctx.OK([]byte{})
	})
        if err != nil {
        ....
        }
```

Inside JSONErrorResponse e.g. error.wrap(ctx.NotFound(err)) is called. NotFound will not return a error unless it fails to encode the error to json, and error.Wrap return nil if input is nil. Meaning the inside of the tx return nil and the x  is committed.  

A possible workaround is to only use JSONResponseError outside of tx, e.g. 

```go
	err := application.Transactional(c.db, func(appl application.Application) error {
		return appl.Comments().Delete(ctx.Context, cm.ID, *identityID)
	})
        if err != nil {
           return  jsonapi.JSONErrorResponse(ctx, err)
        }
        return ctx.OK([]byte{})
```

**Comment by pbergene** [comment]
No current production impact, but high priority issue. Can re-escalate if required.
