### ISSUE TITLE
Clicking just once on a Work item should not open it's detail view

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#269]
Clicking just once on a Wi should not open it. The WI name string could be a hyperlink and clicking only on that should open the WI details pane.

The current behavior leads to accidental opening of the detail view pane for the first WI in the list. This also makes scrolling up and down very annoying.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2030

**Comment by michaelkleinhenz** [comment]
Done. Behaviour was changed in recent versions.
