### ISSUE TITLE
Jenkins is idle, pipeline build fails

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#2690]
If I step away from my machine or do something that causes Jenkins to become idle, and then return and do something that Jenkins needs to be available for, such as creating a quickstart project for example, the pipeline build will start but will stay on the 'new' status forever because Jenkins did not start back up as it should. Attached are screenshots from the last times this happened.

![nobuild](https://user-images.githubusercontent.com/926572/37636230-936534de-2c4c-11e8-9be9-713d77a7a094.png)

![nojoy](https://user-images.githubusercontent.com/926572/37636239-a69584d2-2c4c-11e8-9778-6da8a33b6477.png)

**Comment by mishaone** [comment]
@sbose78 @kishansagathiya - please have a look and assign to the appropriate team/person. Thanks!

**Comment by joshuawilson** [comment]
@pradeepto @chmouel @rupalibehera do you think you can check if Jenkins is idle and start it or warn the user?

**Comment by chmouel** [comment]
#2678  is related

**Comment by ldimaggi** [comment]
Question - Does the build stay in the new state forever? I have seen similar problems where OSIO times out and reports that the build has failed after 2 hours.

**Comment by lordofthejars** [comment]
I have tried 3 times, twice has worked correctly, the last time it occurred as you describe here. As a detail I would add that I have gone to jenkins.openshift.io and after unidling Jenkins I could see that the job is not created.

cc/ @pradeepto @krishnapaparaju

**Comment by rgarg1** [comment]
I hit this issue today when the Jenkins pod my newly created project stayed Idle even after 40 minutes. I see some websocket errors in the browser console, but I'll not hazard a guess that they are related. Snapshot attached.
![build stuck](https://user-images.githubusercontent.com/28748448/39418347-8af4547e-4c77-11e8-9cf3-813757f5b322.png)

![screenshot from 2018-04-30 13-07-57](https://user-images.githubusercontent.com/28748448/39418350-92a4d9fa-4c77-11e8-8f1e-bae50259259f.png)

Note: The error in the above screenshot looks obvious. Why give the user an option to start the pod that results in this error toast.

**Comment by kishansagathiya** [comment]
@stooke https://github.com/openshiftio/openshift.io/issues/2690#issuecomment-385330686 looks similar to what happened in https://github.com/openshiftio/openshift.io/issues/3311?

**Comment by stooke** [comment]
I this it’s a different issue; in the error message the username and Jenkins names are the same. 
I will investigate more when i get in to work.

**Comment by kishansagathiya** [comment]
Thanks a lot @stooke

**Comment by stooke** [comment]
Could it be the application name?
I'm wondering if issue #2370 is the underlying issue.
https://github.com/openshiftio/openshift.io/issues/2370
@jiekang what do you think?

**Comment by jiekang** [comment]
I've had a similar problem where my Jenkins pod remained Idle even when a pipeline build was triggered.

I think it's supposed to unidle when that happens, otherwise nothing will be built (obviously). Sometimes this behavior occurs, other times it doesn't. I was able to workaround it by using the OSO console to manually unidle the Jenkins pod.

**Comment by jiekang** [comment]
I don't think the issue described here is related to #2730. That issue occurs during the build; here nothing has even started.

**Comment by kishansagathiya** [comment]
looking at https://github.com/openshiftio/openshift.io/issues/2690#issuecomment-385330686 it seems like this is a deployments related issue. 
@aslakknutsen @maxandersen which is the team responsible for that?

**Comment by jiekang** [comment]
The intermittent issue I've observed is:

When Jenkins is idled:

Trigger build:
  1. Jenkins unidles automatically and build starts. (expected behavior)
  2. Jenkins unidles automatically but build does not start. Trigger a build again and it works. (unexpected)
  3. Jenkins remains idled. You can manually unidle jenkins pod in OSO console. (very unexpected)
    3a. Build starts.
    3b. Build does not start, trigger build again and it works.

**Comment by ldimaggi** [comment]
What I am seeing today is:

1) With the production/old/legacy launcher:
* Reset user env
* After the Jenkins pod starts, wait ~90 min for Jenkins to idle (or firce an idle condition thru oc)
* Create a new quickstart
* Observe the Jenkins pod fail to automatically un-idle 
* I tested this with a user account provisioned on the starter-us-east-2 cluster

2) With the new cluster:

* Reset user env
* After the Jenkins pod starts, wait ~90 min for Jenkins to idle (or firce an idle condition thru oc)
* Create a new quickstart
* Observe the Jenkins pod automatically un-idle within 3 minutes
* I tested this with a user accounts provisioned on the starter-us-east-2 cluster, starter-us-east-1a cluster, starter-us-east-1b cluster

**Comment by qodfathr** [comment]
Did you mean "with new launcher," not "new cluster"?

**Comment by gastaldi** [comment]
So, in another words that means that the new Launcher works fine and the production/old/legacy does not? That's great news, another reason to get rid of that asap 😉

**Comment by ldimaggi** [comment]
Todd - yes - thanks - that was a tired typo.   ;-)

**Comment by ppitonak** [comment]
Pipeline didn't start for me even when using new launcher (I switched my accout to beta)

Jenkins was unidled but there are no pipelines when I go to https://jenkins.openshift.io. I'm not able to cancel Build 1 in OpenShift console - a notification about success is displayed but the build is not cancelled.

```
$ oc get pods
NAME                         READY     STATUS    RESTARTS   AGE
content-repository-1-h5492   1/1       Running   0          39m
jenkins-1-4hr6v              1/1       Running   0          39m
```

![osio_2690a](https://user-images.githubusercontent.com/445100/39564560-048f6960-4eb5-11e8-9242-bc152ba1c606.png)

![osio_2690b](https://user-images.githubusercontent.com/445100/39564561-04b0cb14-4eb5-11e8-9a8f-06d50da9cd33.png)

**Comment by kishansagathiya** [comment]
@krishnapaparaju This is a stale issue with no information on how to reproduce it. Without enough data, there is no way to tell why build fails in this case. This is very intermittent. Personally, I have never faced this.
I think as we move to a more robust, issues like these will be fixed. Should we still keep this open? Or should we mark it down?

**Comment by krishnapaparaju** [comment]
@kishansagathiya if this not reproducible, can we close this and reopen if this issue shows up again..
