### ISSUE TITLE
Intermittent/recurring error - Analytics report not generated after a successful build

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2694]
Planner ID: 2099

This issue has been seen in the past and is showing up again this week - after a build pipeline completes successfully, the stack report is not generated. No errors are seen.

Steps to recreate:
* Create new quickstart
* Observe build pipeline successful completion
* Observe stack report is not created

![screenshot from 2018-03-19 18-56-36](https://user-images.githubusercontent.com/642621/37654341-1f58173e-2c18-11e8-9eb5-91fd445762e5.png)

**Comment by miteshvp** [comment]
@ldimaggi - are you still able to reproduce this issue. I am not able to. Was this one-off? If you are  able to reproduce, can you please paste the console logs?

**Comment by ldimaggi** [comment]
The problem with this issue is that it is totally random and does not generate any logs. I will watch for it and close the issue if it is not appearing.

**Comment by ppitonak** [comment]
It happened to me 10 min ago on prod-preview.

**Comment by miteshvp** [comment]
@ppitonak @ldimaggi any console logs that you can share will be greatly appreciated. Also, stack report gets triggered as part of build process, maybe you can send those build logs too for better debugging. Thanks in advance.

**Comment by miteshvp** [comment]
@ldimaggi - any updates here? Can we close this if not recurring?

**Comment by ppitonak** [comment]
I observed it couple of minutes ago

**Comment by rootAvish** [comment]
@sivaavkd This should be a SEV-3, it's not breaking anything in prod.

**Comment by ldimaggi** [comment]
This problem is still happening randomly:

![1b7e8c89805f46aaf53fa0010abc3423](https://user-images.githubusercontent.com/642621/39483384-2e3f7cc6-4d40-11e8-8245-5d35ae421237.png)

Build logs were unfortunately over-written. Will try to capture error again - it seems to be totally random.

**Comment by miteshvp** [comment]
@ldimaggi - have you observed this behavior? I am still not able to reproduce this.

**Comment by miteshvp** [comment]
@ldimaggi - any updates here?

**Comment by ldimaggi** [comment]
OK to close - have not seen this issue recently - closing.

**Comment by ldimaggi** [comment]
Re-opening as this problem was seen again on July 9.

The full set of test results/artifacts is available here:

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/282

**Comment by GeorgeActon** [comment]
@ldimaggi This looks like a duplicate of #3744 
And all the work is being done in that bug. Can we close this as duplicate?

**Comment by ldimaggi** [comment]
Closing as duplicate of #3744
