### ISSUE TITLE
Planner - Catch Error or prevent it in work-item.service

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#2696]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-ui/issues/349/

```
Error: 
  at CatchSubscriber.selector (./node_modules/fabric8-planner/app/services/work-item.service.js:714:1)
  at CatchSubscriber.error (./node_modules/patternfly/dist/css/patternfly.min.css:1:5147)
  at MapSubscriber.Subscriber._error (./node_modules/patternfly/dist/css/patternfly.min.css:1:5147)
  at MapSubscriber.Subscriber.error (./node_modules/patternfly/dist/css/patternfly.min.css:1:5147)
  at RetryWhenSubscriber.OuterSubscriber.notifyError (./node_modules/patternfly/dist/css/patternfly.min.css:1:5147)
...
(24 additional frame(s) were not displayed)
```

**Comment by joshuawilson** [comment]
@nimishamukherjee @michaelkleinhenz error in `app/services/work-item.service.js:714:1`

```
            .patch(workItem.links.self, JSON.stringify({ data: workItem }))
            .map(function (response) {
            return response.json().data;
        }).catch(function (error) {
            _this.notifyError('Updating work item failed.', error);
            return Observable.throw(new Error(error.message));
        });
    };
```

**Comment by michaelkleinhenz** [comment]
Needs Sentry integration as well. See story https://openshift.io/openshiftio/openshiftio/plan/detail/1917 (stretch goal for Sprint#146, but will likely not be completed).

**Comment by aslakknutsen** [comment]
@michaelkleinhenz Why does Planner need its own Sentry? Sounds like a 'source' label in ErrorNotify/Error at best to more easily see the location in sentry UI (tho the exception stack should show the same)

**Comment by joshuawilson** [comment]
@michaelkleinhenz this error is from Sentry because the error was reported through the UI. The planner is integrated by default as the UI already has it. The only reason you would need your own Sentry integration is for Standalone functionality. But Sentry isn't used for local dev, so it would only help you if your were allowing users to access Planner Standalone. 

In this case there is an error getting thrown that needs to be dealt with.

**Comment by rgarg1** [comment]
Assigned to @sanbornsen

**Comment by joshuawilson** [comment]
@rgarg1 it is better to @ mention someone then to assign them. Assignment means they are working on it. Anyone looking at this issue will **not** consider working on it since it is assigned. Since you already did your planning, you are adding work to the sprint plan.

**Comment by christianvogt** [comment]
Very old sentry error, code has changed a lot since then.
