### ISSUE TITLE
If a user's session login token has timed out, errors are not raised in the OSIO UI when the user attempts to perform actions

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2697]
Steps to recreate:
* Login to OSIO
* Allow the login token to timeout (is this 24 hours?)
* Attempt to perform actions that require write/execute permissions 
* Observe no error raised to the OSIO UI
* Observe 401 error written to the chrome browser console - this error was generated when the user attempted to press the "promote button"

![screenshot 26](https://user-images.githubusercontent.com/642621/37669675-d88ed056-2c3d-11e8-942f-158a0c192978.png)

The user should be able to determine whether he/she is logged in by observing either their username or a "log in" option in the upper right hand corner of the OSIO UI, but people may miss this. Can we raise and error directly to the user in the OSIO UI?

**Comment by alexeykazakov** [comment]
> * Login to OSIO
> * Allow the login token to timeout (is this 24 hours?)

You won't be able to reproduce any session timeouts by these steps ^

The token is good for 30 days (not 24 hours). And browser currently refreshes the token every 10 minutes. So you should never get your OSIO token expired if you browser is opened. You would have to close your browser or logout and then open it/re-login in 30 days to get your session expired.

So, you are facing another issue here.
@ldimaggi as said many times before, could you please add details about the 401 errors from the network tab in your browser? :) Error logs from console do not help much.

**Comment by ldimaggi** [comment]
Thanks Alexey! Closing as non-reproducible - have not been able to recreate the error - will reopen if a sequence of actions can be defined to reliable recreate the error.
