### ISSUE TITLE
'Blocked' status for Work Items

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#270]
This will clearly display the task status for the team on the Kanban board, which otherwise right could see it as 'In-progress' and the blocked status could be retrieved only after opening the task. 

This is much needed to draw attention of the team to its blocked state.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2031

**Comment by qodfathr** [comment]
We will be addressing blocked work items differently; this should not be handled via the Status field. The semantic reasons for this are subtle, but the status is the current 'internal' state of the work item. A work item is never in a blocked state -- that's an external state imposed upon a work item. A work item can be an any internal state *and* externally blocked at the same time. As such, blocked should not be used as the internal state of a work item. Furthermore, this means that when a work item becomes unblocked, there is no confusion regarding to which state to return the item.

e.g. if `blocked` is used as a status, and work item `I` is blocked and then becomes unblocked, to which state should `I` be set? The only way to really know is to look at the history of `I` and see which state it was in prior to it becoming blocked. And that prior state may no longer be the proper state to which `I` should return.

Alternatively, if the fact that `I` is blocked is maintained independently of the status of `I`, the status of `I` can continued to be maintained while `I` is blocked (e.g. perhaps it goes from `in-progress` to `to-do`), and once `I` is unblocked, the status accurately reflects the internal status of `I`.
