### ISSUE TITLE
Deployment cards re-appear stuck in deleting state on re-creation

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#2701]
Parent: https://github.com/openshiftio/openshift.io/issues/1658

# Bug

## Description

After deleting a deployment via the Deployments page and then re-creating the same deployment, without leaving the view in the original tab where the deployment was deleted, the deployment card will re-appear stuck in its deleting state.

## Expected behaviour

The deployment card should re-appear in its standard interactive state, displaying the status icon and pod donut, and be expandable to view CPU/memory/network metrics as usual.

## Steps to reproduce

0. Create a deployment via importing a quickstart etc., if necessary
1. Open two tabs. One with Create > Deployments open, and the other Create > Pipelines
2. Click kebab > delete menu item on the deployment card
3. Wait for the view to update with the card removed
4. Switch to the Pipelines tab and restart the pipeline
5. Switch back to the Deployments tab and wait for some time. Eventually, the view will update again once the pipeline has re-created the deployment.

After step 5, the deployment card is re-created, but the deleting state persists indefinitely, so the deployment stats cannot be seen or the deployment card interacted with in any way. Leaving the Deployments view and revisiting it within the same browser tab (ie reloading the view) does properly reset the card state.

# Related
- [x] https://github.com/openshiftio/openshift.io/issues/2633

**Comment by andrewazores** [comment]
@chrislessard

**Comment by jiekang** [comment]
When the list of applications changes, the card is no longer shown, however the component instance remains and `ngOnDestroy` is not called. When the list changes again and the application reappears, the old instance is reused and the destroy boolean is still true. I'm surprised about the component reuse behavior.

**Comment by jiekang** [comment]
I think it has to do with the `active`' logic used. We aren't actually choosing not to load the card, just to hide it. This goes deeper into how we use *ngFor and *ngIf on the data we're getting to decide what to display. Maybe we want to refactor this.

**Comment by jiekang** [comment]
A quick fix should be to reset `deleting` when `active` goes from `false` to `true`.

**Comment by andrewazores** [comment]
@jiekang yea, that makes sense and does seem to work. I'm okay with just PRing that one-liner for now, and then post-Summit we can look at re-examining how we interact with Angular change detection, ngIf, ngFor, etc. and consider a larger refactor for better page performance.

**Comment by andrewazores** [comment]
Since I'm here anyway, I'm wondering about the scenarios and how this "Deleting" state appears. As it is now, the card switches to this state immediately after the user confirms the deletion via the modal dialog, and the card remains in this state until a point in the future where the deployment is actually no longer present in the data updates. A notification is also displayed once the request completes, which probably happens before the deletion actually occurs in OSO. If the request completes with an error, the notification is displayed and the card is left in the deleting state, possibly indefinitely. So, should we reset the "deleting" property on request error as well, so that the card becomes visible and interactive again, allowing the user to retry deleting the deployment? And should we also consider setting the "active" property to `false` a little more eagerly, as soon as the request successfully completes?

**Comment by jiekang** [comment]
@andrewazores Good points. I think your suggestions sound good to me.
