### ISSUE TITLE
UI becomes unresponsive after session times out

### ISSUE THREAD

**Issue by dgolovin** [openshiftio/openshift.io#2703]
After having openshift.io opened for a while in my browser I started sometimes to see this error shown below

![image](https://user-images.githubusercontent.com/620330/37688515-cd45c0a4-2c5d-11e8-8d74-f56829e6f054.png)

Most of Item in UI are not responding. It looks like UI stuck on the same page because of session timed out or connectivity issues.
Refresh does help to get over it, but would be good to see meaningful error message.

**Comment by joshuawilson** [comment]
@alexeykazakov do you want to work together on this or take care of it completely? I can see that we need better notifications and the system should handle being logged out better.

**Comment by ldimaggi** [comment]
Denis - can you tell me/us how long it took for you to see this issue? Hours? Days? Thx!

**Comment by dgolovin** [comment]
@ldimaggi openshift.io was opened in separate browser window since last testing session on Wednesday. I was suspending and waking up my notebook many times for several days and everything was working as expected until today. Last time I used openshift.io Friday, so it's been 3+ days since my last interaction with OSIO UI.

**Comment by alexeykazakov** [comment]
@joshuawilson not sure if it's an issue with login/auth.. Token is good for 30 days and there is no any login sessions... So, it should work fine. Can the platform/ui/ux team(s) investigate what's happening? If it's related to login or token refresh somehow then we will take a look at this too.
cc: @rohitkrai03

**Comment by sbose78** [comment]
Haven't come across this - closing. 
Please re-open if you encounter this again.
