### ISSUE TITLE
patternfly-ng: import individual modules

### ISSUE THREAD

**Issue by dlabrecq** [openshiftio/openshift.io#2704]
We should take advantage of patternfly-ng's (v3.x) individual modules and import only what’s used in the UI. For example, there is no need for Angular to build optional dependencies like swimlane/ngx-datatable, angular-tree-component, c3, and ng2-dragula if the UI is not using these components.

**Comment by andrewazores** [comment]
Does this fit as a child of https://github.com/openshiftio/openshift.io/issues/2499 ?

**Comment by dlabrecq** [comment]
I believe it does. Was not aware of the epic, but wanted to create an issue for tracking the PR fix.
