### ISSUE TITLE
Minor text modifications required in Stack Report

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#2707]
@jyasveer, @sivaavkd, the following textual modifications need to be made in Stack Report.

In Dependency details view:
1. Components Check > Dependency check, as decided earlier.
2. OSIO > Openshift.io.

In all detailed views:
1. Add full stops after all the explanatory text below the titles. For example, the explanatory sentence under 'Dependencies with security issues in your stack' is 'A list of...the issues' 
2. When you expand to see details of a dependency, Github staistics>GitHub Statistics.

In detailed views of Licenses, insights and dependency details
- Planner>planner
Over all, cases are mixed in all the labels, for example, Conflicting License details, Unknown license details. Either keep it title case or sentence case, we need to be consistent with whichever way we decide to go. In general I see title case being predominantly used in OSIO.

**Comment by miteshvp** [comment]
@sanketpathak - can you PTAL in this issue as well.

**Comment by sanketpathak** [comment]
Closing it as it is completed
