### ISSUE TITLE
'Open in OpenShift Console' link in Pipelines page leads to a wrong cluster

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#2709]
The OSIO account is connected and provisioned to 'starter-us-east-2a' cluster,
![image](https://user-images.githubusercontent.com/3263627/37704324-cb267886-2cf8-11e8-8160-07db4248d352.png)
but the link to open the OSO Console leads to the 'starter-us-east-2' cluster, which is wrong.
![image](https://user-images.githubusercontent.com/3263627/37704348-da53ca8e-2cf8-11e8-991a-269120614750.png)

**Comment by pmacik** [comment]
Likely a duplicate of https://github.com/openshiftio/openshift.io/issues/2229.

**Comment by sbose78** [comment]
@pmacik  this looks fixed to me.

**Comment by joshuawilson** [comment]
Closing. If you still see this please reopen.
