### ISSUE TITLE
Opened Work items do not close on clicking anywhere outside their detail view window

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#271]
The WI details pane remain on the screen, unless closed explicitly.

Expectation is that the detail view must close once the user clicks outside its window.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2032

**Comment by michaelkleinhenz** [comment]
The quick preview is supposed to stay open because the user should be able to select a different WI.

**Comment by joshuawilson** [comment]
I thought UX had said you should be able to click on the issue in the list that is the open one and it closes it. It even did that for a while.

I also feel like I want to click on the header area to close it. I still do that, but nothing happens and then in frustration have to go find the `x`.
