### ISSUE TITLE
Error 500 on Deployments screen

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#2710]
We've just encountered this error in E2E tests:

![pipeline_deployments](https://user-images.githubusercontent.com/2078072/37710265-68cabc46-2d0d-11e8-9576-67e27849e9b0.png)

The test simply runs quckstart with release strategy Release, stage, approve & promote. 
Please ask if you need additional info.

**Comment by ppitonak** [comment]
For the record, I experienced similar issue with my private account while running e2e tests locally.

**Comment by andrewazores** [comment]
@ebaron @stooke

**Comment by andrewazores** [comment]
@ljelinkova or @ppitonak , if you click the kebab menu on one of those cards and select "View OpenShift Console", do you see a result like this?

![screenshot from 2018-03-21 10-13-35](https://user-images.githubusercontent.com/3787464/37714681-8aef0ede-2cf0-11e8-9a29-07f8e80a3d63.png)

I see the same 500 errors on the Deployments page, and this seems to be affecting OSO as well.

**Comment by ebaron** [comment]
It appears that Hawkular Metrics are down for me and others on starter-us-east-2. I get this error on the OSO web console: "An error occurred getting metrics."

**Comment by ppitonak** [comment]
@andrewazores yes, I see this error in OpenShift console

**Comment by ldimaggi** [comment]
I am seeing the same error - this issue is not connected to automated tests - users see it when using OSIO manually too. Thx!

**Comment by aslakknutsen** [comment]
This should probably be handled a bit more gracefully with returning a 503 from Deployment API as well and UI handling that by showing the graph sections grayed out or similar.

**Comment by ebaron** [comment]
The underlying Hawkular outage seems to be resolved. As for making the error more user-friendly, we're going to track that effort in this issue: https://github.com/openshiftio/openshift.io/issues/2713

Feel free to re-open if you have further concerns.
