### ISSUE TITLE
Duplicated info labels when importing multiple codebases using wizard

### ISSUE THREAD

**Issue by aptmac** [openshiftio/openshift.io#2712]
Issue: when importing multiple codebases using the import wizard, on the final page the labels associated with each codebase are duplicated.

I've attached a screenshot as an example. I have made a new space, and used the import wizard to import 3 codebases: prod1, whyamigettingthisfar, and y-u-no-build. When I get to the final page of the wizard, it correctly creates a display for each of my three codebases, but the labels on the right-hand side all reference the codebase 'y-u-no-build'.

Screenshot:
![multiple import](https://user-images.githubusercontent.com/10425301/37715059-67313606-2cf1-11e8-9f2a-1b5723bf0767.png)

**Comment by sunilk747** [comment]
This legacy issue is not present anymore. We have solved this by re-engineering the new launcher experience flow.
cc @animuk
