### ISSUE TITLE
[10] (Deployments) Make error notifications from Deployments page user friendly

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2713]
Parent:

# Description

As a user, I would like to see less verbose and more user friendly error notifications that help me understand what the issue is and if needed, what actions I can take to address it.

# Notes

When an error is encountered, a notification message is displayed to the user. The current content is verbose and technical. For example:

```
{"errors":[{"code":"unknown_error","detail":"Hawkular returned status code 503, error message: Reply could not be parsed: invalid character '\u003c' looking for beginning of value","status":"500","title":"Unknown error"}]}
```

These should instead be user friendly messages like: `Error: Unable to retrieve stats for deployments` based on what error occurred.

# Acceptance Criteria

- [ ] Error notifications tell the user in simple terms what occurred
- [ ] Error notifications tell the user if and what action needs to be taken to resolve the issue
- [ ] Deployments API should indicate when Hawkular metrics are unreachable #2754

**Comment by andrewazores** [comment]
Can we create a user story for Deployments error handling and use that as a parent for this issue and https://github.com/openshiftio/openshift.io/issues/2714 ?

**Comment by jiekang** [comment]
@andrewazores I'm tempted to have each of them be their own story as they can both be described via 'As a user, I would ...'. Thoughts? I can go either way though so let me know and I'll set up the issue(s).

**Comment by andrewazores** [comment]
Sure, that works too.

**Comment by jiekang** [comment]
Closing as PR merged. 

https://github.com/fabric8-ui/fabric8-ui/pull/2941
https://github.com/fabric8-ui/fabric8-ui/pull/2953
