### ISSUE TITLE
[3] (Deployments) Show reasonable defaults for deployments statistics

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2714]
Parent: #287 

# Description

As a user, I would like to see reasonable defaults for statistics if they aren't available

# Notes

The defaults for deployments statistics are strange. This can be seen if stat requests fail.

![no-stats](https://user-images.githubusercontent.com/5430520/37719399-4ddf9648-2cfb-11e8-9041-1bb7c78841f8.png)

It should show something like 'N/A' instead.

# Acceptance Criteria

- [ ] In situations where stats aren't available, a default display that informs the user they aren't available is shown.

**Comment by dgolovin** [comment]
I see the same deployment stats behavior and also two error messages probably related to it. Note that resource usage looks good though:
![image](https://user-images.githubusercontent.com/620330/37728997-ff335360-2cf8-11e8-961e-7b91d0f2398b.png)

**Comment by andrewazores** [comment]
@dgolovin please see https://github.com/openshiftio/openshift.io/issues/2710
