### ISSUE TITLE
Can we add a note to the user guide to explain the differences in the account home deployments display?

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2716]
See:  https://github.com/openshiftio/openshift.io/issues/2711

Depending on the release strategy selected by the user, the deployments display on a user's home page will present different information to the user. A note in the user guide would help users to avoid confusion because of these different displays. Thx!

**Comment by mishaone** [comment]
Good point. Testing now to see what the three kinds of pipelines look like in the deployments dashboard and full view and documenting.

**Comment by mishaone** [comment]
Created PR to address this: https://github.com/fabric8io/fabric8-online-docs/pull/223

**Comment by mishaone** [comment]
Done and available on preview here: https://docs.prod-preview.openshift.io/user-guide.html#_dashboard_deployments_view

Will be pushed to public in a few days with other commits.
