### ISSUE TITLE
GitHub connection issue - space/quickstart creation

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#2717]
I'm testing the GitHub connect part by disconnecting my GitHub account and seeing what it lets me do without prompting for the GitHub connection. IMO, this should probably happen when we create the account as before because it's causing some weird issues to pop up. For example:

After disconnecting my GH, I tried to create a space. Results:
1. Once it prompted me for GH information.
2. Once it let me create a space with no issues.
3. Once it gave me an error (space could not be created) but created the space anyway and automatically connected my GH account back without me asking it to do so.

Split up from https://github.com/openshiftio/openshift.io/issues/2705

**Comment by joshuawilson** [comment]
@dgutride does your update, that is in prod-preview, touch on any of these?

**Comment by mishaone** [comment]
Closed https://github.com/openshiftio/openshift.io/issues/2718#issuecomment-375161445 as a duplicate, adding to this that for 2 in the report, I was finally prompted for GitHub credentials when trying to create a quickstart project in the space I created without being connected to GH.

**Comment by rohitkrai03** [comment]
PR raised - https://github.com/fabric8-ui/fabric8-ui/pull/2657

**Comment by joshuawilson** [comment]
@mishaone is this being tested against prod-preview? which has a fix/update for connecting to github

**Comment by rohitkrai03** [comment]
@joshuawilson Closing this one.
