### ISSUE TITLE
Resizing the browser window leads to overlapping UI elements

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#272]
Menu options and buttons display fine only when the browser window is open maximized. Re-sizing the browser windows leads to operlapping screen objects. 

Please refer to the attached screenshot for reference.

![overlapping menu options](https://user-images.githubusercontent.com/28748448/27371939-3923ac74-5652-11e7-913a-ec8a6fc356b6.png)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2033

**Comment by michaelkleinhenz** [comment]
Can not reproduce this. May be outdated.

**Comment by rgarg1** [comment]
Largely fixed, however some overlap still remains.
![overlap in ui](https://user-images.githubusercontent.com/28748448/30643555-1711b68a-9e2d-11e7-94a3-3606baf8db24.png)
