### ISSUE TITLE
Che workspace shows the flagged CVE but no suggestion for alternate secure version

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#2720]
I created a vertx project, started my Che workspace and added a dependency as per instructions here in step 4: https://docs.openshift.io/getting-started-guide.html#analyze_che_dependencies. 

Earlier we flagged a CVE and suggested an alternate secure version. However, I now see we are only flagging the CVE and not suggesting a replacement. See screenshot below.
![screenshot from 2018-03-22 16-17-04](https://user-images.githubusercontent.com/16647625/37769196-38267f14-2df6-11e8-9723-b0307491a9ab.png)

**Comment by miteshvp** [comment]
Changes are in prod and able to see the recommendations. Users may not be able to see any recommendation for a version if there is no better alternative version available. So in that case the original message is completely valid. But in the current context, it was a bug for this specific dependency.
<img width="650" alt="image" src="https://user-images.githubusercontent.com/17736013/39047769-c63db424-44b8-11e8-9405-502d15d16567.png">
