### ISSUE TITLE
unable to import and deploy the quickstart application 

### ISSUE THREAD

**Issue by hrishin** [openshiftio/openshift.io#2721]
Unable to deploy quick start application on https://openshift.io

### Steps to reproduce:

1. Open quickstart wizard
2. Try to import or add a new quickstart application

In next step its shows following error message
![image](https://user-images.githubusercontent.com/28615674/37769870-7ca7c600-2df8-11e8-81d5-d1987bc741d7.png)

https://github.com/openshiftio/openshift.io/issues/1832

This issue is reproduced on both clusters 2 and 2a

**Comment by ldimaggi** [comment]
Do you see an error/error code number generated in the chrome browser log?

**Comment by hrishin** [comment]
JS console logs:

![image](https://user-images.githubusercontent.com/28615674/37770050-2245c526-2df9-11e8-848c-cfd73df80970.png)

**Comment by ldimaggi** [comment]
Is the user account logged in ?

**Comment by rupalibehera** [comment]
I am facing the same issue on my account too, I did a `tenant update` and also a `reset`

**Comment by rupalibehera** [comment]
This should be a SEV-1 if everyone is facing this issue

**Comment by gastaldi** [comment]
It seems to be a CORS issue, since the logs don't show any errors. I have updated production with a CORS fix 30 min ago, can you give it a try again?

**Comment by pbergene** [comment]
Seeing a lot of these: 2018-03-23 13:57:36,872 WARN  [io.fabric8.forge.generator.github.GitHubFacade] (default task-26) Failed to create github client for user null: org.USERNAME.github.HttpException: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}

**Comment by gastaldi** [comment]
@pbergene that was probably caused because my Github credentials was disconnected in OSIO, I went to the Profile screen to connect them again

**Comment by gastaldi** [comment]
@rupalibehera Also, can you clear your browser cache, just in case?

**Comment by gastaldi** [comment]
Not sure if it's the same question as https://github.com/openshiftio/openshift.io/issues/2721#issuecomment-375286255, but can you confirm the Github account is connected in the profile screen?

**Comment by gastaldi** [comment]
@pbergene it works for me. @ldimaggi said he tested with users from different clusters and it works too. Can you please remove the SEV-1 priority since if we cannot recreate it for all users then I don't think it matches the SEV1 definition?

**Comment by gastaldi** [comment]
Ok, the CORS filter changes in https://github.com/fabric8-launcher/launcher-backend/commit/55dea55c90b7e9d0905d7296d3594dc079a24a51 fixed the problem. Closing
