### ISSUE TITLE
OpenShift.io supports multiple Git host providers

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2723]
Users and organizations desire the freedom to select their Git hosting provider. This is true for new development work and is especially true for existing development work which is currently hosted in Git.

Whenever an operation requires git and a git connection has not been established for that context, the service will prompt the user to choose a git repo -- the selection of which includes the git provider.

For example, when running the appwizard for a quickstart, the user will be asked to create a new git repo into which to store the code. This selection should include a list of known git accounts/locations plus the ability to define a new git account. The definition of a new git account requires the user to select a git provider (e.g. GitHub / GitLab / BitBucket / GOGS / etc.), potentially provide some additional metadata about the provider, and potentially choose a user account for the provider. Once this information has been established, it should be persisted in the user's profile so that they may easily reuse it in the future.

Under this model, a user may have multiple definitions even for a single git hosting provider -- for example, two different user accounts defined for GitHub or multiple host URLs for GOGS.

### Git providers to be implemented
- [ ] GitHub
- [ ] BitBucket

## Implementing Features
[ ] Allow for choice of git provider in Launcher when choosing where to store code
[ ] Allow for choice of git provider in Launcher when importing code
[ ] Allow for choice of git provider when adding codebases
[ ] Add bitbucket authentication
[ ] Add BitBucket

## Parent Scenario
#2722 Balancing choice and complexity in development toolchains

**Comment by qodfathr** [comment]
cc: @catrobson @slemeur 
This needs UX work first to fully scope out the experience.

**Comment by catrobson** [comment]
There are existing screens for handling multiple git providers during the launch experience.  We would use this same type of interaction for if the user was connecting to a git provider from the codebases page, but will need a UX story to capture that design and interaction fully to make sure we know what fields would be provided by each git provider we support, as well as how these is viewed outside of the launch experience for codebases.  Existing designs towards this effort:  https://redhat.invisionapp.com/d/#/console/12879000/275861027/preview

**Comment by aslakknutsen** [comment]
@catrobson No access to that design? Seems to redirect me back to 'Project'

**Comment by bdellasc** [comment]
@aslakknutsen I need to dig up the design and re-post it. I removed it from the current launcher flow, since we weren't offering it as part of the first flow design. I'll reply here (hopefully this afternoon) with a couple of mockups

**Comment by bdellasc** [comment]
I updated the original design so it takes the most current "Authorize Git Provider" screen content into account. Here's the [basic InVision flow](https://redhat.invisionapp.com/share/5SGLATJNYVA) to give you an idea of what we were thinking and how the section would transition from selecting the git provider to logging in as you do in the current design.

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/1954

**Comment by lwrigh** [comment]
Here is the Invision link to the user flow for adding multiple Git providers to a user's Openshift.io account via settings and the application launcher: https://redhat.invisionapp.com/share/3ZHTPE0ESWT#/294111200_Launcher_-_Git_Providers Any feedback on it is welcome. I can post it to the OSIO experience as well.
