### ISSUE TITLE
Users provisioned on prod-preview are always directed to free-stg when they access the OSO console

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2728]
All users on prod-preview, regardless of whether they are provisioned on free-stg or a different cluster, are directed to free-stg when they attempt to open the OSO console from the OSIO UI.

For example - for a user provisioned on a different cluster - here:

![screenshot from 2018-03-22 11-52-57](https://user-images.githubusercontent.com/642621/37781750-b32ae710-2dc7-11e8-951e-37cc7a237ae6.png)

The link is:
https://console.free-stg.openshift.com/console/project/username/browse/pipelines

**Comment by alexeykazakov** [comment]
Prod is broken too.
It looks like this URL is hardcoded. free-stg for preview and us-east-2 for prod.

**Comment by alexeykazakov** [comment]
So, it's broken for almost all external users.

**Comment by piyush1594** [comment]
@ldimaggi @alexeykazakov The related issue #2229 has been closed with the fix. I think we are good to close this.

Moreover, this issue is related to UI, if its still there can we drop the `build-cd` label. Thanks, cc @sthaha

**Comment by piyush1594** [comment]
Closing this as no response seems like fixed.
