### ISSUE TITLE
getting alot of notifcations for an workitem that does not seem to have changed

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#2730]
keep getting alot of notificiatnos from osio that I can't figure out why I receive them. i.e. https://openshift.io/openshiftio/openshiftio/plan/detail/1451 I got many mails about that they were updated within 5 minutes....any idea why ? it doesn't have any updates (according to wit ui) since aug 25 2017 ? 

![2018-03-22_17-27-31](https://user-images.githubusercontent.com/54129/37785086-8b5ecfc6-2df9-11e8-8064-42f81ff57866.png)

**Comment by aslakknutsen** [comment]
This seems to be the culprit: https://github.com/openshiftio/openshift.io/issues/2736

**Comment by nimishamukherjee** [comment]
Closing this as #2736 fixes this issue too.
