### ISSUE TITLE
Planner UI sends PATCH request to backend when no data changes

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#2736]
When pressing X in both cases and not changing any data the UI is sending 2 PATCH request to backend to update itself.

![screenshot from 2018-03-22 22-49-41](https://user-images.githubusercontent.com/132158/37800524-5226dd46-2e23-11e8-879e-10f5fd9f885a.png)
![screenshot from 2018-03-22 22-49-52](https://user-images.githubusercontent.com/132158/37800531-58e73a36-2e23-11e8-863c-446e72070918.png)

**Comment by aslakknutsen** [comment]
@kwk This begs the question; should WIT backend detect the 'no change' and ignore the change when no change occurs...

**Comment by rgarg1** [comment]
Assigning to @sahil143 for a fix.

**Comment by rgarg1** [comment]
Verified-fixed in prod. Closing the issue.
