### ISSUE TITLE
View user in collaborator shows current logged in user profile

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2737]
Steps:
- Create a new space
- Add collaborators to space
- Click on view user
- It shows current logged in user profile
![user](https://user-images.githubusercontent.com/34271052/37814354-91f8ca44-2e8f-11e8-89e6-d45e7f1cf924.gif)

**Comment by joshuawilson** [comment]
This issue has been raised and a fix is in review.

**Comment by alexeykazakov** [comment]
Duplicates https://github.com/openshiftio/openshift.io/issues/2613
