### ISSUE TITLE
404 error if we click on plan tab from choose a new work item type page

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2741]
Steps:
- Select a space
- Click on create work item (Analyze Tab)
- Now instead of 'Choose a new work item type' select plan tab
- It give 404 error
![404](https://user-images.githubusercontent.com/34271052/37817205-09506c4e-2e9c-11e8-93a2-03818f932f43.gif)

**Comment by michaelkleinhenz** [comment]
That widget there on the dashboard needs an overhaul, it does not match the new way WIs are created. We do not support the WI type selection screen anymore. There is another issue here: that type selection should not be there anymore at all.

**Comment by nimishamukherjee** [comment]
Closing this as we have removed the option to create a work item from the dashboard
