### ISSUE TITLE
Need to provide endpoints in fabric8-wit for deleting / stopping Che workspaces

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#2745]
stopping / deleting workspace can be done via
`self / ide` links from GET `codebaseID/workspaces` which is already available  (UI  calls che-server directly) but  the approach should be changed and endpoints for deleting / stopping workspace should be exposed from fabric8-wit

**Comment by ashumilova** [comment]
The preflight requests are not properly handled by Che, and thus OPTIONS requests fail with 403, when try to interact with Che server directly from UI.

**Comment by ibuziuk** [comment]
Closing as outdated
