### ISSUE TITLE
Collaborators input field should be clear after clicking cancel or Add

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2746]
Steps:
- Go to settings
- Add Collaborators
- click select 
- type a collaborator name 
- Now select and add a collaborator
-collaborator is added. Now again click on button 'Add Collaborators' still shows the input term.
![collab](https://user-images.githubusercontent.com/34271052/37824933-3311eaea-2eb4-11e8-80c8-587388830d35.gif)

**Comment by andrewazores** [comment]
@joshuawilson not sure who owns this page. Can I take this bug?

**Comment by joshuawilson** [comment]
This sits between Auth and Platform. You can fix it.
