### ISSUE TITLE
Login process is super slow and involves too many pages and redirects

### ISSUE THREAD

**Issue by jaseemabid** [openshiftio/openshift.io#2747]
Every time I login to osio, I go through all these steps and it could be a lot shorter.

1. Several network calls to auth.osio, sso.osio, developers.rh.com
2. Redirects to `_gettingstarted`
3. A white loading screen
4. A page that shows for a short time the accounts I'm connected to. There is no need to show this if I'm already connected to all the required pages
5. `_home`

**Comment by alexeykazakov** [comment]
Yes. We should improve it.
@catrobson we are removing the _gettingstarted page, right? Who is working on it? @dgutride?

cc: @rohitkrai03

**Comment by catrobson** [comment]
This has been implemented in prod-preview.  I'm not sure whether @jaseemabid's experience was on the existing Prod where you see a getting started page, or on prod-preview where we're doing a bunch of URL redirecting but taking action on behalf of the user instead of putting a page in front of them to manually take action on.

**Comment by alexeykazakov** [comment]
Sure. But users still see the redirect to _gettingstarted and back to home. It takes time.
Can we get rid of extra redirects?
While redirects to auth, sso, rhd are pretty quick the loading of getting started page and then back to home is noticeably slow.

This is what I see in preview:

http://youtu.be/GJRFDma9RkA

**Comment by mvulavak** [comment]
@alexeykazakov Is this still an issue?

**Comment by alexeykazakov** [comment]
@mvulavak yes.

**Comment by christianvogt** [comment]
Seems related to https://github.com/openshiftio/openshift.io/issues/4030
