### ISSUE TITLE
Deployments API should indicate when Hawkular metrics are unreachable

### ISSUE THREAD

**Issue by ebaron** [openshiftio/openshift.io#2754]
Parent: #2713

As pointed out in https://github.com/openshiftio/openshift.io/issues/2710, the API should provide a better response when OpenShift's metrics server is down. When the metrics server returns 503 - Service Unavailable, we should also return 503 status along with a more user-friendly error message.

**Comment by aslakknutsen** [comment]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-wit/issues/3819/

**Comment by ebaron** [comment]
The error type returned by hawkular-client-go should be of type HawkularClientError, which includes the status code for the HTTP response. It should be easy to check this for 503. We will have to add a new error type in WIT for 503 responses.
