### ISSUE TITLE
Stack analysis wrong API response 

### ISSUE THREAD

**Issue by luebken** [openshiftio/openshift.io#276]
If you request with an unknown id you get the misleading error that the analysis is in progress:  
```
$ curl -H "Authorization: Bearer $OSIO_TOKEN" https://recommender.api.openshift.io/api/v1/stack-analyses/someunkownid
{
  "error": "Analysis for request ID 'someunkownid' is in progress"
}
```
This is especially misleading as it is the same message if there is a legitimate analysis in progress. But that case should not be noted as an "error".

**Comment by samuzzal-choudhury** [comment]
@luebken @GeorgeActon this has been fixed. The new response is similar to -

```
{
    "error": "Invalid request ID 'someunkownid'."
}
```
with an HTTP status code 404 (Not Found).

I am closing this issue. Please feel free to reopen if you see otherwise.
