### ISSUE TITLE
Make all packages/versions known to fabric8-analytics

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#2761]
# Description

Probably the biggest limitation of the current ingestion/graph architecture is that it doesn't know anything about packages and versions that haven't been analyzed/scanned yet.

But in reality, we don't always need to scan packages to know things about them. Good example is CVEs, or being able to tell (reliably) what the latest version is. We don't need to scan package to discover that it is vulnerable. This information comes from other sources, not from scanning.
Also, without knowing all packages/versions that are there in a particular language ecosystem, we are not able to say whether a package that we found in user's manifest file is a private dependency (which only lives in his or hers content repository) or if the dependency is well known open source component that we just don't have in our system yet. All such dependencies are simply "unknown" and we can't tell the difference.

Therefore we need a mechanism how to populate our databases (Graph for user-facing stuff and RDS for future ingestion) with all currently available packages/versions. And then a way how to keep up with new packages and releases.

**Comment by msrb** [comment]
To put this simply, the end goal here is to have vertexes and edges for all packages and versions in our graph. Even if we don't have any other data for the packages. That way we will know what we don't know and we will not flag well-known packages as "unknown" in stack reports just because we don't have them in our system yet.

We will also be able to flag vulnerable packages without scanning them first. And we will be able to tell (much more reliably than now) what is the latest version of a package.

**Comment by msrb** [comment]
I will create user stories for this epic later today.

**Comment by miteshvp** [comment]
Done.
