### ISSUE TITLE
Question about Deployments

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#2762]
I've been testing Deployments in OSIO for a while and I have one question. Do you think that when an application has 'release' strategy that it should be counted as "Deployed" application on the dashboard?

It confused me a little because it is not actually deployed anywhere. I think it is not even necessary to list the application on the Deployments screen since there are no useful information at all. 

![dashboard](https://user-images.githubusercontent.com/2078072/37900532-bbcc5e6a-30ee-11e8-92fb-6f689929abb2.png)

**Comment by joshuawilson** [comment]
1. The deployment of an app in staging or run is a live URL. 
2. The dashboard widget should provide the link.
3. The entire dashboard is getting redesigned.

**Comment by jiekang** [comment]
Given the complete redesign of this dashboard, including pretty much all of the widgets displayed on it, can this issue be closed?

**Comment by joshuawilson** [comment]
This has been redesigned and is this view is deprecated.
