### ISSUE TITLE
Webpage redesign for jenkins proxy unidling waiting page

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#2763]
We are showing a "wait for it with a infinite spinning wheel" webpage currently when unidling a Jenkins deployment, the design is quite basic and currently look like this : 

![image](https://user-images.githubusercontent.com/98980/37907497-92ae7e66-3105-11e8-8c62-ab3cc56d43e4.png)

It would be nice to have a better looking wait page,

Planner: https://openshift.io/openshiftio/Openshift_io/plan/detail/342

**Comment by joshuawilson** [comment]
cc @catrobson

**Comment by catrobson** [comment]
@chmouel can you describe when and where this would display today?

**Comment by chmouel** [comment]
@catrobson When a Jenkins is idled (in sleep) and a user access to http://jenkins.openshift.io there is a wait page show by a software (fabric8-jenkins-proxy) to get the user to wait until her jenkins comes up. That waiting page is the one that need a rebrand, Here is the current HTML page : 

https://raw.githubusercontent.com/fabric8-services/fabric8-jenkins-proxy/master/static/html/index.html

Let me know if you need more details,

**Comment by catrobson** [comment]
@chmouel we just created some new loading page standards you can view here:  I think the full page loading bar is what we would ideally want here, but I'm not certain if we have enough information to show a determinate loading bar.  Let us know!

https://redhat.invisionapp.com/share/JKGR07DRUC3#/screens/289269774

**Comment by sthaha** [comment]
Closing this as the story has been moved to planner see: https://openshift.io/openshiftio/Openshift_io/plan/detail/342
