### ISSUE TITLE
Broken flow in Shared Workitems 

### ISSUE THREAD

**Issue by briandooley** [openshiftio/openshift.io#2764]
When I click on one of my work items ("Experience1"), I get taken to the "Experimental Features Opt-In" screen.  Pressing the yellow button takes me to my profile.

![image](https://user-images.githubusercontent.com/3627775/37910720-1c847406-3106-11e8-89af-daedecc112d0.png)
![image](https://user-images.githubusercontent.com/3627775/37910726-22366328-3106-11e8-82cf-c609fc681770.png)
![image](https://user-images.githubusercontent.com/3627775/37910729-28d14f4a-3106-11e8-9c70-fea6afcfa51f.png)

**Comment by joshuawilson** [comment]
on you profile you can change your `Feature Opt-in` level to `experimental` and then you can view the page you were trying to look at

**Comment by briandooley** [comment]
That fixed it, thanks.
