### ISSUE TITLE
Starter account on Central (Canada) mask access to US-east-2 created by IO.

### ISSUE THREAD

**Issue by numeyoga** [openshiftio/openshift.io#2768]
On mattermost, @maxandersen asked me to create an issue for my problem.
My account detail is a gmail box : wallartn 

On Openshift online, i have 2 active subscriptions : 
 * One on Starter : Canada(Central)
 * the other on Openshift.io.

I created the Starter before the IO one.

**The problem** : The automatic subscription for Starter on US-east-2 isn't accessible by the Openshift online dashboard. I need to use a link in the pipelines view.

**Comment by alexeykazakov** [comment]
It works as expected. Users are supposed to access OSIO clusters/plans (east-2 for example) via OpenShift.io UI only. Not via OpenShift Online (manage.openshift.com).

**Comment by joshuawilson** [comment]
Works as designed, closing.
