### ISSUE TITLE
[1] Apply resource limits for F8A services

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2769]
Resource limits would need to be applied to these services:

- [x]  bayesian-pgbouncer

- [x]  bayesian-data-importer

- [x]  f8a-firehose-fetcher

**Comment by sivaavkd** [comment]
@msrb - for more details, look for email thread with subject "Setting cpu and memory requests and limits for every service"

**Comment by msrb** [comment]
We already have limits for pgbouncer and firehose-fetcher. We just need to push the latest images to prod. data-importer is still missing though.

**Comment by msrb** [comment]
@tuxdna 

Saleem, could you please take a look into this once you're free? Thanks.

**Comment by sivaavkd** [comment]
@msrb - since @tuxdna is on vacation, who can take this up ?

**Comment by msrb** [comment]
@sivaavkd I will.

**Comment by msrb** [comment]
PR for data-importer: https://github.com/fabric8-analytics/fabric8-analytics-data-model/pull/149

**Comment by msrb** [comment]
Pushed to prod: https://github.com/openshiftio/saas-analytics/pull/303
