### ISSUE TITLE
Some of the basic dependencies at OSIO boosters are unknown

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2770]
Please see the screen shot:

<img width="1338" alt="screen shot 2018-03-27 at 9 09 14 am" src="https://user-images.githubusercontent.com/15967765/37945584-8e72a1a8-319e-11e8-9359-50c148ba6a38.png">

cc @miteshvp @sivaavkd

**Comment by sara-02** [comment]
@krishnapaparaju This is related to an earlier reported issue https://github.com/openshiftio/openshift.io/issues/2684, and the discussion on mailing list started by @msrb  regarding the same.
Can you share the pom.xml as well, or check if the versions used were upstream one or RH-specific. In case the community version were used and still they are unknown, escalate this to a  SEV-1.

**Comment by krishnapaparaju** [comment]
@sara-02 I have tried this at production OSIO. Easy to reproduce. We have discussed the approach to handle boosters  than full fledged ingest of RH dependencies. cc @miteshvp

**Comment by sara-02** [comment]
@krishnapaparaju Can you try once again, you should not be be getting unknown now.

**Comment by sara-02** [comment]
Thanks to @miteshvp for the time being we have fixed the unknown
![screenshot from 2018-03-27 20-33-09](https://user-images.githubusercontent.com/7047079/37976033-2f6c95d2-31fe-11e8-9d9b-0c5703b07025.png)

**Comment by krishnapaparaju** [comment]
Have tested this, looks good to me. Closing this issue..
