### ISSUE TITLE
Jenkin status icon 

### ISSUE THREAD

**Issue by sdash-redhat** [openshiftio/openshift.io#2773]
I don't see a description of the Jenkin status icon shown below .... what does this mean?

![image](https://user-images.githubusercontent.com/27761023/37948297-1c2b4ec4-31ad-11e8-8ab1-a524ce45c3f9.png)

The documentation only shows these icons 
![image](https://user-images.githubusercontent.com/27761023/37948324-4055c61c-31ad-11e8-9050-d869b99a0c27.png)

![image](https://user-images.githubusercontent.com/27761023/37948330-47c8da38-31ad-11e8-889c-a9aa8a12a16c.png)

![image](https://user-images.githubusercontent.com/27761023/37948350-5bb3fa78-31ad-11e8-8b34-d2acf18cfd78.png)

**Comment by joshuawilson** [comment]
The Status drop down is getting removed. The idler has made it no longer useful.

**Comment by sthaha** [comment]
Closing this issue as it isn't valid anymore.
