### ISSUE TITLE
   A way to mark areas as experimental features

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#278]
For launch Planner, Applications and Environment features should be marked as "experimental".

Proposal is to add a `[ ] Enable experimental features` checkbox under the users Profile page.

When this checkbox  is checked the tabs related to Planner, Applications and Environment should not be shown/active.

Unanswered question: What to do about deep links into these areas ? What about the public urls that are not behind a users login ? Would a "Under development" banner with a link to explain current state be an option for the public urls ? 

UX is being tracked at https://github.com/fabric8-ui/fabric8-ux/issues/510 

 - [ ] Design changes to profile and labels for sections to be "toggled" [fabric8-ui 1576](https://github.com/fabric8io/fabric8-ui/issues/1576)

**Comment by joshuawilson** [comment]
cc @catrobson

**Comment by maxandersen** [comment]
https://github.com/fabric8-ui/fabric8-ui/issues/1719

**Comment by maxandersen** [comment]
okey, confirmed by @qodfathr via Carl on email that current implementation is ok for launch thus closing this and leaving the active issues to do deep linking open to be fixed.
