### ISSUE TITLE
Dialog Create Work Item: Creating Work Items from empty List View should have context values prefilled

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#279]
I was testing iterations and noticed that when an iteration is started and is moved to the current iteration (while empty of Work Items), we see a big "Create a Work Item" option in the empty right pane (see screenshot 1). The expected and intuitive behavior here should be that when I click the plus to create a new Work Item it is intended to be for this current iteration and should have the current iteration as the default in the Iteration field but it doesn't.

The same should happen for the smaller + icon at the top right of the pane which is the only way to quickly create a Work Item for the current iteration (see screenshot 2). Expected behavior for this based on its context (being in the pane of the current iteration details view) is that it should create a new WI that has the iteration field == current iteration but this is not the case for either option.

![iteration_new](https://user-images.githubusercontent.com/926572/27468791-4b8539e4-582f-11e7-817d-bf14bfbbf832.png)
![iteration_created](https://user-images.githubusercontent.com/926572/27468816-774d0d7c-582f-11e7-80cf-250c6f00240f.png)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2040

**Comment by michaelkleinhenz** [comment]
Fixed with https://github.com/fabric8-ui/fabric8-planner/pull/2188.
