### ISSUE TITLE
Applications from deleted space can reappear

### ISSUE THREAD

**Issue by ebaron** [openshiftio/openshift.io#2798]
Deleting and recreating a space with the same name will cause any deployments left behind from the deleted space to show up in the dashboard for the new space.

Steps to reproduce:
1. Create space _x_
2. Create quickstart project _y_ and deploy to one or more environments
3. Delete space _x_
4. Create new space also named _x_
5. Observe project _y_ in Pipelines and Deployments pages, but not in Codebases

This can be mitigated by expanding the delete space functionality to also delete its OpenShift resources (https://github.com/openshiftio/openshift.io/issues/1746), but this is only part of the problem. We should also use the space ID instead of space name when associating these resources with spaces to guarantee uniqueness. See: https://github.com/fabric8-launcher/launcher-backend/issues/221.

**Comment by qodfathr** [comment]
Are we sure we want to classify this as a bug, especially when #1746  (which predates this by 3 months) is going to address the concern? Perhaps we should await #1746, and if this issue is occuring after that is implemented, at that time reopen this issue?

**Comment by ebaron** [comment]
Sure, we may want to move to using space IDs in labels anyways once we start sharing spaces between users in an organization, to prevent name collisions. I can create a user story for that instead.

**Comment by aslakknutsen** [comment]
It's not just 'delete space' the can cause this. If I view Todd's space and I happen to have a Space with the same name, I will see my content in "Todd's space" view.

And that is definitely a bug. Same cause, same fix. :)
