### ISSUE TITLE
Already logged in page has no action buttons

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#2799]
This is just a weird UX thing for me, and I thought I'd raise a bug in case the UX team agree: if you're already logged in and try to log in from a separate tab, you are correctly taken to the `You are already logged in` page:
![website_noaction](https://user-images.githubusercontent.com/926572/38003358-8c483d2a-327a-11e8-888b-ef74de8c7476.png)

However, it's odd that there is no button regarding what action the user should take next. I would expect adding something like a "Go to OpenShift.io Home" button under the "You are already logged in" message would be useful. As it stands, there are no buttons to indicate how the user can easily navigate to the correct place in OSIO next, just some links to privacy info, TOU, polices, etc.

**Comment by alexeykazakov** [comment]
Duplicates https://github.com/openshiftio/openshift.io/issues/2772
