### ISSUE TITLE
Build configuration appears twice in Create a new Starter project wizard

### ISSUE THREAD

**Issue by ppalaga** [openshiftio/openshift.io#280]
Create a new Starter  project
EXPECTED: Build configuration step appears just once
ACTUAL: Build configuration step appears twice
![image](https://user-images.githubusercontent.com/1826249/27473116-48f39170-57fe-11e7-84ed-5fc68ee99b04.png)

**Comment by joshuawilson** [comment]
@ppalaga this is a limitation of the Forge backend that requires a validation step. That said, we are aware of it and are looking for a better way to handle it.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1593

**Comment by jstrachan** [comment]
should be fixed now
