### ISSUE TITLE
Caddy server docker update for content-repository

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#2805]
Content-repository uses currently this caddy-server image : 

```yaml
image: fabric8/caddy-server:v6b386d6
```

CentOS is planning to update the caddy-server to a new minor version,

* [ ] Test the new image with a new booster build and check if the content-repository is properly filled up (a manual task unfortunately)
* [ ] Send a PR to https://github.com/fabric8-services/fabric8-tenant-jenkins to update https://github.com/fabric8-services/fabric8-tenant-jenkins/blob/684a0a2/pom.xml#L86 to the released version

**Comment by piyush1594** [comment]
@chmouel Is this done or still pending?
