### ISSUE TITLE
[f8a] error: Task with ID 'xyz' was already processed

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#2808]
In prod:

```
FatalTaskError: Task with ID 'c346bb19-1f40-40ce-af49-f5061cbe9508' was already processed
  File "selinon/task_envelope.py", line 114, in run
    result = task.run(node_args)
  File "f8a_worker/base.py", line 50, in run
    raise FatalTaskError("Task with ID '%s' was already processed" % self.task_id)
```

https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/486/

SQS has at-least-once delivery guarantees, but the number of these exceptions is way to big. We need to investigate.

**Comment by msrb** [comment]
Note this is SEV-3 because the system seems to be behaving correctly. It's just these duplicate tasks and and exceptions.

It is possible that we just need to tweak visibility timeout somewhere.

**Comment by sivaavkd** [comment]
@msrb can you please review this ?  I see that related issue #3181 is already closed by @humaton

**Comment by msrb** [comment]
This is not fixed yet.

**Comment by msrb** [comment]
This happens when worker container gets restarted. No real harm anywhere.
