### ISSUE TITLE
Attributes null in pipelines component

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2815]
A Context change will result in `TypeError: Cannot read property 'attributes' of undefined` in `pipelines.component.html` if the `updateSpace` modal is invoked prior to switching Contexts via visiting the Profile page, and then going back to the pipelines page.

Steps to reproduce:

1. Visit `create/pipelines` for a space.
2. Open `updateSpace` modal by clicking `Add to Space` from the top-right kebab across the filter/sorting toolbar. Close by clicking out of the modal or clicking the 'X' on the modal.
3. Visit profile page via top right username dropdown.
4. Return to `create/pipelines` for the space immediately via the 'Back' browser action
5. Observe completely broken application.

Edit: Fixed steps to reproduce

**Comment by jiekang** [comment]
Sample screenshot:
![broken-pipelines](https://user-images.githubusercontent.com/5430520/38043735-f258287c-3285-11e8-8d55-7993c331f98e.png)

**Comment by joshuawilson** [comment]
nice work

**Comment by jiekang** [comment]
Context interface from ngx-fabric8-wit is:

export interface Context {
    // The entity that this context is for
    user: User;
    space?: Space;
    team?: Team;
    type: ContextType;
    path: string;
    name: string;
}

Users of the Context object cannot assume space (or team) attributes are defined. There have been quite a few locations where this error has occurred that are fixed and I wouldn't be surprised if there are more.

I wonder if there could be a redesign of the Context setup such that clients would not need to worry about making sure things aren't null.

**Comment by joshuawilson** [comment]
that is the plan with storing the Context info in ngrx

**Comment by corinnekrych** [comment]
fixed with https://github.com/fabric8-ui/fabric8-ui/pull/2730
