### ISSUE TITLE
Creating a new app with the new launcher in OSIO fails with 400 error

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2819]
Steps to recreate:
* Enable internal features
* In add to space, select the new launcher
* Select HTTP/Vert.x for a new app
* Observe the application creation fail:

![screenshot 31](https://user-images.githubusercontent.com/642621/38053183-6a32213e-32a1-11e8-817e-eb998f44817d.png)

```
400 - Bad Request [{"message":"spaceId is required","source":"spaceId"},
{"message":"projectName should follow the same pattern as a DNS-1123 
subdomain and must consist of lower case alphanumeric characters, '-' or 
'.', and must start and end with an alphanumeric character","source":"projectName"}]
```

**Comment by invincibleJai** [comment]
@ldimaggi currently changes for new launcher should work only in Prod-preview as internal feature. Changes have not been promoted to prod yet. We are still working through it.

Changes couldn't move to prod as internal feature as there were some issues( Which is not fixed yet) , we are working on it https://github.com/openshiftio/openshift.io/issues/2816

**Comment by invincibleJai** [comment]
@ldimaggi pls try again , should not see 400 - Bad request

**Comment by invincibleJai** [comment]
closing it as app creation is happening fine now, feel free to reopen if you see it again.
