### ISSUE TITLE
Public GitHub Repos - Verify the free tier for users on OSIO

### ISSUE THREAD

**Issue by michaelvirgil** [openshiftio/openshift.io#282]
# Description
As an owner/operator, I need all the Github repos to be public since they are deployed on the free tier of OSO and OSIO.

# Acceptance Criteria
- [ ] The system should prevent users from connecting to a private Github repo. Everything has to be "open" - includes the user's source code
- [ ] The system should verify that when operating, building etc of an associated GitHub repo that is public, that it has not been converted to a private repo

**Note**: 
 All repos we are currently created on behalf of the user are public

# Relationships
_Put linked Team/Product story links here_

## Parent Experience
#2085 Getting Started Quickly with a Framework - from Import, to IDE, to Deployment

**Comment by qodfathr** [comment]
@joshuawilson @ldimaggi  has anyone verified that, today, OSIO prohibits access to private GitHub repos?

**Comment by joshuawilson** [comment]
I don't know that this has been proven yet. Do you have a private one to try?

**Comment by qodfathr** [comment]
I do not. @ldimaggi ?

**Comment by ldimaggi** [comment]
Sorry - I do not - private accounts seem to require $$$.   ;-)

**Comment by bartoszmajsak** [comment]
At this moment there is no difference from OSIO standpoint. I can import private repository to existing space by adding new codebase as well as while creating new space and importing existing repo. I can see it in the drop-down and successfully create a new space.

**Comment by aslakknutsen** [comment]
@qodfathr @catrobson Got any UX around this?

**Comment by catrobson** [comment]
@aslakknutsen nope, hadn't seen this issue before now.  We're already looking at importing a codebase in the following design story, so I'll link this issue up and make sure we're considering it in the validation of github repo linking.

https://github.com/fabric8-ui/fabric8-ux/issues/839

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2057
