### ISSUE TITLE
new GS workflow bug: Select Runtime is empty

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#2822]
After doing the steps (clicking `More` and `Less` to read text) and reporting the issue in https://github.com/openshiftio/openshift.io/issues/2821 I quit the wizard and started anew. In the **Select Mission & Runtime** step of the new workflow, my `Select Runtime` is completely blank. I've tried this twice so far, and get the blank runtime. I'll try logging out and back in, etc. but wanted to report this issue.

![3](https://user-images.githubusercontent.com/926572/38070824-3c8c7124-3361-11e8-844b-12207ac5a0d6.png)

**Comment by invincibleJai** [comment]
Possibly duplicate of https://github.com/openshiftio/openshift.io/issues/2755

**Comment by animuk** [comment]
closing this as this is a duplicate issue.
