### ISSUE TITLE
Work Item list should be updated for all work item edits

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2823]
Steps:
- Click on work item to open quick preview
- Edit work item say Change the state from new to closed(show completed unchecked)
- Workitem list should be refreshed

**Comment by rgarg1** [comment]
Assigned to @sanbornsen for a fix.

**Comment by Raunak1203** [comment]
linked to https://github.com/fabric8-ui/fabric8-planner/issues/2575

**Comment by nimishamukherjee** [comment]
Fix on prod.
