### ISSUE TITLE
Import existing github project doesn't get add to pipeline UI

### ISSUE THREAD

**Issue by hrishin** [openshiftio/openshift.io#2824]
### Steps:

1) create new space or navigate to existing space
2) click add to space or pipeline + icon to open quickstart wizard
3) select import project 
4) choose any repository from GitHub  
- any valid Java - maven project
- previously created repository OSIO quickstart wizard
5) In build step, either override or don't override Jenkins file (can choose any option)
5) complete the quickstart wizard steps

video:
[![openshift io import project pipeline issue
](https://i.ytimg.com/vi/ofN2VuCRt10/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBhBq5LA5MmoFPoQ7QmkFLeSh6xEw)](https://youtu.be/ofN2VuCRt10?t=35s "openshift io import project pipeline issue
")

### Expected :
1. A user should able see project build in pipeline view

### Actual:
1. OSIO doesn't show any build in pipeline view. On other hand, it creates new pipeline build for projects in OpenShift online platform

Is it desired behavior or bug?

**Comment by animuk** [comment]
As the legacy launcher flow is replaced with new App launcher, We should not see this behaviour now. Closing this.
