### ISSUE TITLE
OSIO Launcher: Updates never reach Browser

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2831]
Please see the screenshot
<img width="1335" alt="screen shot 2018-03-30 at 1 31 01 pm" src="https://user-images.githubusercontent.com/15967765/38129968-d8c11190-341e-11e8-91eb-e49befa8488b.png">

cc @GeorgeActon

**Comment by miteshvp** [comment]
I too am seeing the same error

**Comment by animuk** [comment]
. This is a intermittent issue.this behaviour seems to occur due to replica affinity issue. As per our finding, web socket needs to be replaced with SSE. Reference :https://github.com/fabric8-launcher/launcher-planning/issues/148

**Comment by animuk** [comment]
Sometimes, request is going to the other replica where state information is not present for the webhooks to call for web sockets.  closing this as we have the above reference issue
