### ISSUE TITLE
Pressing enter should update/create comment

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2835]
Steps:
- Click on workitem title to open quick preview
- Add a new comment
- Pressing enter should create a new comment

**Comment by rgarg1** [comment]
@sunilmalagi Please take a call on this.

**Comment by sunilmalagi** [comment]
@Raunak1203 @rgarg1 
No, Pressing enter should go next/below line in the comment box and not to create a new comment, because user might want to enter additional information in the next line.

**Comment by rgarg1** [comment]
I'm of the similar opinion, @sunilmalagi.
WDYT @Raunak1203?

**Comment by Raunak1203** [comment]
Agreed to sunil's opinion.Closing the issue
