### ISSUE TITLE
Edit in kebab menu comments section doesn't work

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2836]
Steps:

- Click on kebab menu(comment section)
- Click edit

**Comment by rgarg1** [comment]
@debloper Assigned to you for fixing. Remove the edit option form the kebab menu.

**Comment by debloper** [comment]
If I understand correctly, the in-textarea pencil icon does the job of editing where it's valid, so it doesn't make sense to have another kebab menu option (even if it worked); on top of which, according to the new implementation the kebab menu doesn't work so it's safer to just remove it altogether.

On that note, I'd like to propose removing the kebab menu altogether as well. The only thing it will hold is delete, which is a debatable feature to have enabled.

**Comment by Raunak1203** [comment]
@debloper we can discuss this in cabal today
