### ISSUE TITLE
mvn clean install fails on boosters

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#2837]
Affected boosters:
- [ ] VertX Healthcheck

When launching mvn build command from OSIO (openshift.io) Che Terminal it fails with the error - [Full Stacktrace](https://gist.github.com/spicemit/357ab27c7d90b7f7af3b30e4ad546803)

#### Steps Performed for Che Terminal
1. Go to new launcher experience
2. Create an quickstart application
3. Open Che workspace
4. execute `cd <project-root-dir>`
5. execute `mvn clean install -Popenshift,openshift-it`

#### Possible Resolution
Setting `Maven Artifact` with a `hyphen -` instead of a `dot .` should solve this. See below snaphsot
<img width="468" alt="image" src="https://user-images.githubusercontent.com/17736013/38187679-533fb9ae-3676-11e8-954b-de2b5add5afc.png">

**Comment by invincibleJai** [comment]
tried with @miteshvp  providing Maven Artifact as `d4-346` as suggested but looks like there is some issue with access 
```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:build (fmp) on project d4-345: Failed to execute the build: Unable to build the image using the OpenShift build service: Failure executing: GET at
: https://kubernetes.default.svc/apis/build.openshift.io/v1/namespaces/jakumar-che/buildconfigs/d4-345-s2i. Message: Forbidden!Configured service account doesn't have access.
```
<img width="1670" alt="screen shot 2018-04-02 at 3 11 19 pm" src="https://user-images.githubusercontent.com/5129024/38191988-6b06194a-3688-11e8-9ed1-3f5d17d7e4f0.png">

@animuk something you should have a look at.

**Comment by bartoszmajsak** [comment]
Which account and namespace are used when you are in the terminal? It should be as specified https://github.com/redhat-developer/rh-che/issues/541. I think this would be working with Che 6 (what you can see from the discussion there), otherwise, with Che 5, you have to login first to your user namespace.

**Comment by invincibleJai** [comment]
@bartoszmajsak This I observed in new launcher wizard flow. Not sure about the version of Che I just followed the steps as provided by @miteshvp above, in help-> about can see as below

<img width="611" alt="screen shot 2018-04-02 at 3 56 20 pm" src="https://user-images.githubusercontent.com/5129024/38193226-98bae0ae-368e-11e8-8b42-f944f3d699a2.png">

**Comment by bartoszmajsak** [comment]
This might be Che 5. See steps in https://groups.google.com/d/msg/fabric8-launcher/NypXPuyoCrg/iscd40_SCgAJ, especially the one "open codebase in Che and run tests from there" - that's a workaround before we have Che 6.

And also please read the discussion in the issue I linked above for better understanding.

**Comment by miteshvp** [comment]
@invincibleJai - can you perform the below steps again
1. Open Che Console
2. In the terminal window cd to project-root dir
3. execute oc project <user-namespace>
4. execute mvn clean install -Popenshift,openshift-it

see if it helps.

**Comment by invincibleJai** [comment]
Thanks @bartoszmajsak @miteshvp https://groups.google.com/d/msg/fabric8-launcher/NypXPuyoCrg/iscd40_SCgAJ helps and works as well :)

<img width="1675" alt="screen shot 2018-04-02 at 4 38 54 pm" src="https://user-images.githubusercontent.com/5129024/38194321-741d934e-3694-11e8-9554-27bf4ba0237c.png">

**Comment by invincibleJai** [comment]
@miteshvp changes suggested by you are in prod, am closing it. Please reopen if you still see it.
