### ISSUE TITLE
Quick preview is open even after switching work item type group

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2838]
![quickpreview](https://user-images.githubusercontent.com/34271052/34935716-d01a65ea-fa04-11e7-9375-90ff0dcc3353.gif)

**Comment by sunilmalagi** [comment]
- When the user switches between left navigation tabs, the quick preview window should get closed.
- If user try to switch to another tab on the left pane, In case of any unsaved changes on quick preview, user should be asked if he/she wants to save it before go to different tab.

**Comment by nimishamukherjee** [comment]
Duplicate of #2598
