### ISSUE TITLE
New Launcher Experience - Github Org selected and Pipelinse Source Repo does not match

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#2839]
When a user selects an organization other than github-id during the new-launcher experience, pipelines are triggered on a source repository which is different. Hence no builds gets triggered at all. See two images below.

#### Selection of Github Organization
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/17736013/38185838-a137662e-366d-11e8-80fe-2b19885e79fd.png">

#### Pipelines source repository
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/17736013/38185690-02215770-366d-11e8-8917-1595a0efaf5c.png">

**Comment by miteshvp** [comment]
I verified the same behavior by creating an application under user's github space directly and build gets triggered as expected.

**Comment by invincibleJai** [comment]
@animuk @jyasveer ^^

**Comment by ravsa** [comment]
this PR https://github.com/fabric8-launcher/launcher-backend/pull/251 fixes it, so closing this issue
