### ISSUE TITLE
Workflow:  Teams

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#2844]
Capture user flows for creating, editing, and removing teams from a space.  Also capture flows for how a user navigations in and out of teams in their views.  Understand all pages and experiences a user would have that we can implement in a train's duration.

PARENT:  https://github.com/openshiftio/openshift.io/issues/351

VERIFICATION CRITERIA
- [x] Flow created in sketch and posted to InVision
- [x] Sketch file exists in OSIO google drive
- [ ] InVision link posted to https://github.com/openshiftio/openshift.io/issues/351

**Comment by muruGanesan** [comment]
Please find the user flow diagram posted to InVision
https://redhat.invisionapp.com/share/V9GQIMX53RF#/289870482_Table_Of_Contents_Template
@catrobson, @lwrigh, @mceledonia  > Please review the same and add your review comments

**Comment by muruGanesan** [comment]
@Veethika, @sunilmalagi, @parvathyvr, @alexeykazakov, @SMahil please do a peer review and provide your inputs.

**Comment by alexeykazakov** [comment]
> Please find the user flow diagram posted to InVision
https://redhat.invisionapp.com/share/V9GQIMX53RF#/289870482_Table_Of_Contents_Template

@sbryzak @sbose78 @rohitkrai03 please take a look at the doc too ^

**Comment by sbose78** [comment]
Reviewed - read through all the comments/conversations and I agree with them, and added a couple of them.

@muruGanesan , let us know once you've made the changes.

**Comment by sbose78** [comment]
reviewed, thanks.

@qodfathr , `Association of teams with areas` wasn't part of the engineering design we've been working on. I'm adding  `Association of teams with areas` to the discussion agenda for our monday UX+PM+Engineering authorization meeting.

**Comment by muruGanesan** [comment]
Hi All, 

@catrobson, @lwrigh, @mceledonia, @Veethika, @sunilmalagi, @parvathyvr, @alexeykazakov, @SMahil, @sbryzak @sbose78 @rohitkrai03, @qodfathr 

I updated the "Teams" flow with permission (at a higher level). Please review the same.
https://redhat.invisionapp.com/share/DGGQJ04RC36
 
If there is no major change, I will start on the wireframe from tomorrow.

**Comment by alexeykazakov** [comment]
> @qodfathr , Association of teams with areas wasn't part of the engineering design we've been working on. I'm adding Association of teams with areas to the discussion agenda for our monday UX+PM+Engineering authorization meeting.

Related question is setting roles/permissions for areas. I thought we agreed on roles on Org and Space level in the first version.

**Comment by muruGanesan** [comment]
@here,  updated flow here: https://redhat.invisionapp.com/d/main#/projects/prototypes/13913619
Please review the same and close if it satisfies the requirements
