### ISSUE TITLE
Procedure for refreshing list of associated GitHub organizations

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#2849]
I am a member of a new GitHub organization, I'd like to use it in a new project.

When I go to 'Add to Space' a new Pipeline, I am presented with an Application Wizard that doesn't recognize the new organization.  (I have validated that my GitHub account properly shows the new org in my listed organizations.  OSIO must have an old cache somewhere.)

How can I get my new organization recognized?  The User Guide doesn't seem to have anything for this one.

![image](https://user-images.githubusercontent.com/524520/38213696-d75c97e6-3687-11e8-9802-325ece1e7f2e.png)

**Comment by joshuawilson** [comment]
If this isn't done automatically, I think it is more of a bug then a docs issue.
cc @krishnapaparaju

**Comment by mishaone** [comment]
+1 sounds like a bug, but following for any docs impact when the bug is fixed/workaround is established.

**Comment by sbose78** [comment]
@RickJWagner @joshuawilson @mishaone 

Here are the steps : 

1. Create a new organization on Github example `sbosetest1`
2. Go to https://github.com/settings/applications and click on "OpenShift.io" ( direct link could be https://github.com/settings/connections/applications/4010191b4f938fc02b76 )
3. click on "Grant" beside the the name of the organization you just created.

4. Login to OpenShift.io
5. Go to your profile --> `My connected accounts` and `reconnect` your Github account.

Now carry on business as usual with the wizard - your new github org should show up. It did take a while to show up though - but it did eventually.

**Comment by mishaone** [comment]
@sbose78 @joshuawilson is ^this the intended workflow or a workaround? Will add to docs but checking whether this is intentional (I suspect not, given that we have to reconnect GitHub to do it, which doesn't seem ideal for UX).

**Comment by sbose78** [comment]
Tried using the existing github token to get my organizations from the Github API  https://developer.github.com/v3/orgs/#list-your-organizations 

I found that github doesn't return the newly 'granted' organization unless I obtain a new token ( aka reconnect github ).

Therefore, re-connection is needed.

@mishaone We might make it easier to reconnect by having a button in the wizard itself - that would need some UX & UI magic :)

**Comment by mishaone** [comment]
Thanks, @sbose78. I'll add the current instructions for now and keep an eye on this issue for if/when something in the UI changes to make this workflow smoother.

**Comment by mishaone** [comment]
PR created and merged: https://github.com/fabric8io/fabric8-online-docs/pull/251

This should be okay to close if all that was required was documenting procedure.

**Comment by rkratky** [comment]
@joshuawilson Is this still tracked as a bug, or can it be closed now that the behaviour has been documented?

**Comment by joshuawilson** [comment]
I think it is still a bug. Leaving it up to @krishnapaparaju to work out.

**Comment by animuk** [comment]
closing this as this is already documented.
