### ISSUE TITLE
No scroll option on collaborators and areas page.

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#2850]
There is no scroll bar on the collaborators page. The same issue exists on the Area page.

![needascrollforcollaboratorspage](https://user-images.githubusercontent.com/1892722/38230661-a2fd94fa-372c-11e8-91ac-5c2943f09827.png)

**Comment by joshuawilson** [comment]
@alexeykazakov has Auth team taken ownership of the Collaborators page/feature? If so, maybe @rohitkrai03 can add this to his list. If not, that is fine too.

**Comment by alexeykazakov** [comment]
We (auth team) will refactor this page completely later. But for now let's just add this issue to the backlog and whoever has time to fix it (Auth or Platform team) will pick it up.

**Comment by joshuawilson** [comment]
sounds good

**Comment by christianvogt** [comment]
Scrolling works for me on both areas and collaborators pages. Scrolling appears on the body.
Must have already been fixed or a it was a css leak from another part of the app.
