### ISSUE TITLE
email notification for 'workitem updates' shows incorrect user name

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#2852]
![wi-baiju](https://user-images.githubusercontent.com/545280/38238166-ac57bdf4-3746-11e8-8d20-464e6c536de4.png)

This workitem was updated by the `openshiftio` user but email notification says that the workitem creator has updated it.

**Comment by aslakknutsen** [comment]
Will get fixed by https://github.com/openshiftio/openshift.io/issues/1990 when Revisions are taken into account.
