### ISSUE TITLE
Remove status dropdown (3)

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#2859]
Remove status dropdown from OSIO since services are not available to show relevant information on this for today.  The entire status dropdown should be removed from the navigation.  This does not need to be under a feature flag.

Verification Criteria:
- [x] Status dropdown removed and PR submitted to fabric8-ui
- [x] Inform documentation team of removal
- [x] PR merged

**Comment by joshuawilson** [comment]
this is done
