### ISSUE TITLE
Clicking a link to an invalid Context has inconsistent behaviour

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#2860]
# Description

When clicking on or otherwise visiting a link to an invalid Context, there are two possible outcomes. Either a notification is displayed that the context could not be found, or the user is routed to the _error 404 page.

# Expected outcome

This behaviour should always be consistent and work one way or the other.

# How to reproduce

We need to reliably trigger an invalid context load. An easy way to do this is to apply 
[this small patch](https://github.com/openshiftio/openshift.io/files/1872834/context-error-link.txt)
 and click the modified "your profile" link on the homepage banner. This will append "foo" to your username in the router link. For myself for example, the "your profile" link should point to `/aazores@redhat.com` , but after this patch it points to the invalid path `/aazores@redhat.comfoo` . The rest of the reproduction steps will assume this patch has been applied first.

### 1. Triggering notification

1.1. Visit OSIO homepage.

1.2. Navigate somewhere else within the application by clicking a link or button. For example, click the account name in the top left corner and visit the "View all spaces" state. Then use the "Account home" link under the same menu to return to the homepage.

1.3. Click on the "your profile" link, or any other link to an invalid context.

### 2a. Triggering _error state

2a.1. Visit OSIO homepage.

2a.2. Click on the "your profile" link, or any other link to an invalid context.

### 2b. Triggering _error state

2b.1 Visit link to invalid context directly, by entering the URL in the browser's location. ex. `localhost:3000/aazores@redhat.comfoo`.

# Notes

The _error reroute behaviour occurs due to this router configuration: https://github.com/fabric8-ui/fabric8-ui/blob/3b408f1e6561301a615a3feacdaef349df5d6f34/src/app/shared/context-resolver.service.ts#L23

This says that when a router navigation event encounters an error, the router should navigate back to the last successfully navigated state (ie. the state the user was already on before clicking on an invalid link). The `resolve` guard in the same class uses the ContextService to determine if the navigation can succeed. If the Context does not exist then an error is emitted and the navigation fails, triggering the error handler linked above. This is what typically keeps the user on the same page in reproduction method 1. The ContextService itself failing to retrieve the invalid Context is what produces the notification. However, if no successful routing events have yet occurred, then the _lastRoute is still '/_error' from the linked line, which causes the user to be sent to the _error state in reproduction methods 2a/2b.

Additional sidenote - IMO this router configuration should not live in context-resolver.service, since it actually is not specific to context resolution but applies to all routing events globally across the application. app.component seems more suitable since it also contains other application-wide routing logic.

**Comment by jiekang** [comment]
@andrewazores can you supply the text of the patch in a code block instead of a downloadable text file?

**Comment by andrewazores** [comment]
```
diff --git a/src/app/home/home.component.html b/src/app/home/home.component.html
index 65174ce6..7e4de0a9 100644
--- a/src/app/home/home.component.html
+++ b/src/app/home/home.component.html
@@ -143,7 +143,7 @@
                   Setup your profile
                 </h2>
                 <p class="card-pf-info">Let others know who you are by filling out
-                  <a [routerLink]="['/', loggedInUser.attributes.username]" class="home-banner-link">your profile</a>.
+                  <a [routerLink]="['/', loggedInUser.attributes.username + 'foo']" class="home-banner-link">your profile</a>.
                 </p>
               </div>
             </div>
```

This issue is resolved though - I apparently never assigned myself to it, and forgot to close it when the fix PR when in.
