### ISSUE TITLE
Add IDs to pipeline page for E2E tests

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#2863]
We are refactoring E2E tests for pipeline page and it would help the readability and stability if some of the elements on the page have added ids, e.g pipeline name, status, git repository.

**Comment by joshuawilson** [comment]
@ljelinkova are you planning on doing this? You know best what needs the IDs. The only IDs we have in the UI should be used exclusively for testing. Please remember they need to be unique for the entire system, not just the one page they get added to.

**Comment by ljelinkova** [comment]
@joshuawilson  I've already created PR last week (it is referenced above) - and you wanted me to create issue as well :-) 

As for the unique IDs - there are already many IDs in the code and they are not unique not only for the system, but sometimes they are not unique for the page. In general it is not problem for the E2E tests because we are searching for IDs within some specified elements (find element with id='build-number' in element with class='build-summary'). To make IDs unique we would need to create some page id that would be included in all element's IDs. And in case of iterated elements (e.g. the list of pipelines) we would need to distinguish IDs also by index.
