### ISSUE TITLE
Icons and colors for new work item states and groups

### ISSUE THREAD

**Issue by sunilmalagi** [openshiftio/openshift.io#2868]
@nimishamukherjee @kwk @baijum @michaelkleinhenz @sanbornsen @muruGanesan @SMahil 

Below is the list of Group type, Work Item and States for Scrum Template.  We already have the icons for many of them and I have marked as 'P' (pending) for which I need to suggest the icons.

Group Types for Scrum Template:
- [x] Epics
- [x] Features
- [x] Backlog Items
- [x] Execution (Iterations)

Here is the list of work item for Scrum Template:
- [x] Bug
- [x] Epic
- [x] Feature
- [x] Impediment ~~(P)~~
- [x] Product Backlog Item ~~(P)~~
- [x] Task

Here is the list of States/Colors:
New
In Progress
Open
Closed
Done (P) - Is this same as 'Resolved' ??? If yes, we have the icon for the same.
Approved (P)
Committed (P)
Removed (P)
To Do (P)

Please let me know If anything is missing from the above list

**Comment by kwk** [comment]
@sunilmalagi here's the scrum template so far: https://github.com/kwk/fabric8-wit/blob/spacetemplate/spacetemplate/assets/scrum.yaml

As you can see we cannot define colors or icons for states at the moment so I propose to remove them from the UI altogether and just have it render the text. @sanbornsen do you agree? I just don't want to be in a situation where the UI has hand-written code to show an icon for a dynamic value.

**Comment by sanbornsen** [comment]
@kwk I partially agree with you. I had a handwritten map for the existing states. I understand that space templates are extremely dynamic and we should have the color and icons coming from the backend, but for GA since we only have two templates and hand full of states, let's use the existing icon map we have. I can update the map with Sunil's input and we should be good for the GA. It won't break for any new state unknown for the map, just like it doesn't break now.

Post GA we can decide if we should remove the icons and colors from the states or we should trick the backend to serve it from there, just like work item types.

**Comment by kwk** [comment]
As for the product backlog item and impediment we have a resolution as of https://github.com/fabric8-services/fabric8-wit/pull/2067. Icons of work item types and side panel entries where changesd according to these designs: https://redhat.invisionapp.com/share/WJGSJ17SMHN#/screens/290540724.

**Impediment** (WIT):

Changed from `fa fa-question` to `fa fa-stumbleupon`  ![bildschirmfoto von 2018-04-30 13-04-52](https://user-images.githubusercontent.com/193408/39424456-1a76daa0-4c77-11e8-876b-3e977f7a1274.png)

**Product Backlog Item** (WIT) / **Backlog Items** (Sidepanel entry): 

Change from `fa fa-question` to `pficon pficon-image` ![bildschirmfoto von 2018-04-30 13-06-31](https://user-images.githubusercontent.com/193408/39424502-54bbd36e-4c77-11e8-93be-b6bd69d61880.png)

**Epic** (WIT) / **Epics** (Sidepanel entry):

Change from `fa fa-bolt` to `fa fa-bullseye` ![bildschirmfoto von 2018-04-30 13-09-15](https://user-images.githubusercontent.com/193408/39424597-b93835ee-4c77-11e8-9113-dbc086a33d02.png)

**Comment by sunilmalagi** [comment]
Scenario based Icons:
https://redhat.invisionapp.com/share/WJGSJ17SMHN#/290540723_Scenario_Based_Icons

Scrum Based Icons:
https://redhat.invisionapp.com/share/WJGSJ17SMHN#/290540724_Scrum_Based_Icons

States Icons:
https://redhat.invisionapp.com/share/WJGSJ17SMHN#/290540725_States_Icons

Common Icons:
https://redhat.invisionapp.com/share/WJGSJ17SMHN#/290557721_Planner_Generic_Icons

**Comment by Preeticp** [comment]
@sunilmalagi, @kwk, @sanbornsen,  what do we intend to do for the states in the Agile template, wrt icons and colors? I currently see this:
![screenshot from 2018-07-10 12-46-21](https://user-images.githubusercontent.com/16647625/42495301-5513b650-8440-11e8-8262-f478d92ea1ee.png)

Do we intend to retain this or add colors and icons to them as in the SDD template?
Fwiw, the states are the same as in the SDD template:
![screenshot from 2018-07-10 12-56-54](https://user-images.githubusercontent.com/16647625/42495467-c976d270-8440-11e8-9b1e-53d7e2a313be.png)

Apart from that, imho we should have Title case for the states in SDD template too, similar to the Agile template.

**Comment by kwk** [comment]
@Preeticp until we have a better way of annotation states in the template itself to provide an ID also, I'd say don't invest effort in finding a symbol for each state.

**Comment by Preeticp** [comment]
Ok @kwk and what about the cases for the state, we left that pending for GA, now that we are post that maybe we ought to change that (Reference: https://github.com/openshiftio/openshift.io/issues/3448)

**Comment by kwk** [comment]
@Preeticp just beware that the state is a field almost like any other field and potentially can be defined by a user at one point. But before that happens we can have icons pre-defined in the UI (@sanbornsen, @vikram-raj).

**Comment by Preeticp** [comment]
@kwk I was trying to ask about the cases used for the values of the State field, i.e title case (New, Open, In Progress, Resolved, Closed in Agile template) v/s small case (new, open, in progress, resolved, closed in the SDD template). Currently we are not consistent on the two templates (as pointed in #3448 ).

Even if the field is potentially customizable, should we not give optimal defaults for now?

**Comment by GeorgeActon** [comment]
@sunilmalagi Why have you removed all the labels.  Are you indicating this is closed?
If so please re-add the labels and mark it as closed

**Comment by sunilmalagi** [comment]
@GeorgeActon Yes, its done for now thank you..
