### ISSUE TITLE
Enhancement: OpenShift.io-Getting Started Guide documentation 

### ISSUE THREAD

**Issue by muruGanesan** [openshiftio/openshift.io#2869]
Currently, Getting Started Guide - covers first-time users entry with Happy Path... 
1) Can we also add few notes for those who come back after successful set-up? 
2) Can also add some trouble-shoot/workarounds steps for know error cases?

For e.g. 
**Sample-1: User has created a Space, but he/she refers the getting started guide.** [9.2. Creating a new space]

![getting-started-doc-review-v01-27mar18 001](https://user-images.githubusercontent.com/26006817/38305158-721ba720-3829-11e8-81a7-6e0f41991e3e.jpeg)

**Sample-2: User pipe-line > build failed** [4.4. Working with pipelines]

![getting-started-doc-review-v01-27mar18 002](https://user-images.githubusercontent.com/26006817/38305205-9ee9340c-3829-11e8-913b-67fe2e328449.jpeg)

**Sample-3: User pipe-line > build failed** [4.5. Viewing the build pipeline logs]

![getting-started-doc-review-v01-27mar18 003](https://user-images.githubusercontent.com/26006817/38305584-fbb197dc-382a-11e8-9f8e-1852ca3156cd.jpeg)

**Comment by mishaone** [comment]
@muruGanesan can you clarify about Sample-2: User pipe-line > build failed [4.4. Working with pipelines] please? The previous screenshot is for a running pipeline (i.e. no longer at "new") so the edit option should appear when it's running when the user goes to that page. Did I miss what you meant?

**Comment by mishaone** [comment]
Created and merged PR for two of the three suggestions. No response for #2 so closing this. Please re-open if there is additional work required.
https://github.com/fabric8io/fabric8-online-docs/pull/272

**Comment by muruGanesan** [comment]
@mishaone, sorry for the delayed response. 
point 2: e.g.
In the current scenario, when you delete the 'space' your builds and workspaces are not cleared from the 'space dashboard'.

Ideally, we need to fix this issue... if NOT possible...
as a temporary solution:  Can add some NOTE -or- Workaround in the documentation? So that the user can be aware of the next step.

I hope it clarifies your doubt.

**Comment by mishaone** [comment]
Hi @muruGanesan - no worries. I'm happy to keep this open till your feedback is satisfied. To clarify, when I referred to number 2, I meant *Sample-2: User pipe-line > build failed [4.4. Working with pipelines]*. My question about this was that the previous steps are about the pipeline indicator getting to *running*. In this case, it's unlikely the *edit pipeline* option would not appear. I'll add a note just in case.

**Comment by mishaone** [comment]
@muruGanesan the beedback you specified in the samples should be fixed now on https://docs.prod-preview.openshift.io

Is there any other feedback you have for this issue, or are we good to consider this closed?

**Comment by muruGanesan** [comment]
@joshuawilson, @mishaone, @rkratky,

Please close this issue and thanks

**Comment by mishaone** [comment]
Thanks @muruGanesan
