### ISSUE TITLE
Create UI Design Standard wiki

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#2872]
PARENT: #2871 

Create a location for a single source of truth for UI design standards for OSIO that designers can contribute to.  Set up in a wiki style so that any designer can edit, and any OpenShift.io developer or designer, even in the community, can view.

Verification criteria:
- [x] Wiki location of single source of truth for Design Standards established
- [x] Strawman IA built out so that designers know how to organize content on this wiki
- [ ] Each designer has been trained on how to contribute to the wiki, and ideally has made one edit on their own.

**Comment by mindreeper2420** [comment]
@catrobson currently, the URL is a long OpenShift URL - do we need to investigate creating a custom domain or attaching is as a subdomain to fabric8.io?

**Comment by catrobson** [comment]
Yeah, seeing if we can get a sub domain of fabric8.io probably makes sense. I'm not sure who owns that domain now, can you send something on devtools-saas?

**Comment by mindreeper2420** [comment]
Email sent out to devtools-sass for DNS configuration assistance. Waiting to hear back on next steps.
