### ISSUE TITLE
UI Implementation of Workspaces widget

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#2877]
As part of the new Home Dashboard work, a new Workspaces card was designed. This has already been created in HTML/CSS (issue #919 and PR https://github.com/fabric8-ui/fabric8-ui/pull/2648), but is not yet hooked up. This will need to be done before it can be pushed to production and flags removed.

Verification:
- [ ] Workspaces card matches [designs](https://redhat.invisionapp.com/share/VWGIFFNE69G#/screens/285593828)
- [ ] Internal Feature Flag and Development Flags removed from all components used by the Home Dashboard

**Comment by dlabrecq** [comment]
Created PR: https://github.com/fabric8-ui/fabric8-ui/pull/2720
