### ISSUE TITLE
UI issues with Chrome

### ISSUE THREAD

**Issue by pkettman** [openshiftio/openshift.io#2878]
I am experiencing issues with basic UI operations on Chrome (see browser logs on pictures below):

1) login got stucked, Chromium 56.0.2924.87 Fedora Project (64-bit)
![login_loop](https://user-images.githubusercontent.com/26871874/38310882-f84428c4-381d-11e8-90f2-d2193065884b.png)

2) selecting a space got stucked, Google Chrome Verze 61.0.3163.100
![select_space](https://user-images.githubusercontent.com/26871874/38310892-fd6dc12a-381d-11e8-94c2-40fa1a515b7f.png)

Both operations passed on Firefox. Which Chrome version and higher are supported on OSIO?

**Comment by ldimaggi** [comment]
Are you seeing the same issue in incognito windows with Chrome?

**Comment by ldimaggi** [comment]
I thought that I saw this same issue last night - but - cannot recreate it now:
![screenshot from 2018-04-04 10-25-36](https://user-images.githubusercontent.com/642621/38314021-5bd5e358-37f3-11e8-8048-5b332a84e184.png)

This is with:  Chrome - Version 65.0.3325.146 (Official Build) (64-bit)

**Comment by pkettman** [comment]
In incognito mode it works fine.

**Comment by alexeykazakov** [comment]
maybe the cache issue again.

**Comment by joshuawilson** [comment]
you can clear you cache with a hard refresh `ctl + shft + R`

**Comment by pkettman** [comment]
Yes, cache clearing helped! Isn't there a way to optimize the UI on server side so that the cache clearing is not necessary? If not or until then I'd at least mention it in the documentation (User Guide), adding @rkratky

**Comment by joshuawilson** [comment]
It is something we are working on and yes, adding it to the docs would be good until we can find a permanent solution.

**Comment by pkettman** [comment]
@rkratky could you please add to the user documentation a hint/note to clear browser cache in case UI gets stucked?

**Comment by rkratky** [comment]
@pkettman Yes, will do. Tracked in https://github.com/fabric8io/fabric8-online-docs/issues/262

**Comment by christianvogt** [comment]
Related to caching and https://github.com/openshiftio/openshift.io/issues/3312.
