### ISSUE TITLE
Routing to 404 vs showing a "not found" notification

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#2887]
When a user navigates to an invalid application path, either by clicking on an in-application link or by directly entering an invalid URL in the browser's address bar, there is some inconsistency as to how this is handled. Documentation on how to trigger specific cases is noted here https://github.com/fabric8-ui/fabric8-ui/pull/2686#issuecomment-378606033 and here https://github.com/openshiftio/openshift.io/issues/2860 .

The general question for all cases is "go to 404 page or show notification popup?". The follow-up question in the notification case is "what happens when the user directly enters this URL, and there is no previously valid view loaded?".

Cases:

- user goes to invalid user profile link, ex. `https://openshift.io/invalid_user@example.com`

- user goes to invalid space link, ex. `https://openshift.io/valid_user@example.com/nonexistent-space`

- user goes to invalid path, ex. `https://openshift.io/valid_user@example.com/some-space/create/nonexistent-compnent`

- user tries to go to what appears to be an application internal state but is not recognized, ex. `https://openshift.io/_homeA`

@joshuawilson @catrobson

**Comment by joshuawilson** [comment]
Based on the work you were doing, do you expect to change the URL to `https://openshift.io/_error` OR do you plan to keep them on the failed page with it's URL? 

I think it is better to stay on the URL that is wrong then to leave it. 
I like the Error page more then a toast notification. 

These are just my opinions. I'll let @qodfathr and @catrobson decide.

**Comment by andrewazores** [comment]
I agree. I think the error page should always display the attempted URL rather than `_error`. IMK showing this page rather than displaying a notification is the right thing to do in any situation where the URL would be changed as well - notifications seem suitable for informing the user that something within the view could not be loaded after navigation has already completed, not that the entire view could not be navigated to.

**Comment by joshuawilson** [comment]
Is it not possible to display the "error" page on a failed URL?

**Comment by andrewazores** [comment]
If by a "failed URL" you mean not just invalid paths but paths to things that do not exist (your `josh-6/my-app` for example), then yes it is possible. I have a prototype that does just that.

**Comment by andrewazores** [comment]
The prototype is here, hopefully the build succeeds and the badger link will be available for manual testing: https://github.com/fabric8-ui/fabric8-ui/pull/2695

It fits with what I personally think the "right" behaviour is wrt when to route to the 404 page. I think we agree on when it should be shown, and I have it implemented so that whenever the 404 page is shown it will always retain the attempted invalid URL, and never display `_error` to the user.

**Comment by joshuawilson** [comment]
What happens for invalid paths?

**Comment by andrewazores** [comment]
Same thing. The invalid URL is preserved in the address bar and the 404 page is displayed.

**Comment by andrewazores** [comment]
Pinging for feedback on the demo linked above - @joshuawilson @catrobson @mceledonia

**Comment by catrobson** [comment]
I don't think the toast notifications are needed or that helpful, so I would vote for removing them since we're taking you to a full page error experience.  Otherwise this looks good to me!

**Comment by andrewazores** [comment]
Okay, will remove the notification and finalize the PR. Thanks.
