### ISSUE TITLE
Access environment quotas without space ID

### ISSUE THREAD

**Issue by ebaron** [openshiftio/openshift.io#2889]
Currently the Deployments API only exposes environment quotas with the following endpoint:
`/deployments/spaces/{spaceID}/environments`. The space ID parameter is currently not used for anything important.

We need a way to retrieve resource quotas for all of a user's environments without supplying a space ID. The result would be a list of environments and the status of their quota and usage independent of OSIO spaces.

Parent: #2625

**Comment by ebaron** [comment]
The `fabric8-environments` config map doesn't know about che and jenkins namespaces. Perhaps we want our API to take a namespace type and look up the cluster URL and namespace name from `/api/user/services`.

**Comment by joshuawilson** [comment]
yeah, if you don't use spaceID then you need to use the User

**Comment by joshuawilson** [comment]
@aslakknutsen I don't know any APIs we have that work like this. Do you have a suggestion?

**Comment by ebaron** [comment]
It would be similar to how `/api/user/services` works, for example. You don't give it a user ID or user name, it determines your identity from the bearer token you provide.

**Comment by aslakknutsen** [comment]
@joshuawilson not quite following. What is the question?

**Comment by ebaron** [comment]
I should clarify what I wrote in the description. We know how to implement this in the API. The OpenShift ResourceQuotas represent the whole environment and do not correspond to a particular space. So the backend implementation will be the same, we just need to expose this through the API differently.

**Comment by andrewazores** [comment]
I think this ask should be canceled in light of recent design updates - see https://github.com/openshiftio/openshift.io/issues/3129 . We now do have a reason to pass the spaceId with the environment resource usage requests.

**Comment by ebaron** [comment]
For the resources page [1], we'll still need something to show environment quotas for whole namespaces. This will end up being a separate API method from the one used by the deployments page though.

[1] https://redhat.invisionapp.com/share/FWFGF7VXMB8#/screens/282415828

**Comment by jiekang** [comment]
For this I'd suggest `deployments/environments`. The `deployments/spaces/{spaceId}/environments` endpoint should remain for use in future design updates, as Andrew commented.

**Comment by jiekang** [comment]
I guess the endpoint name can also be discussed in the PR review process, it's not too hard to change :)

**Comment by ebaron** [comment]
Agreed, we should leave the existing endpoint and create a new one. `deployments/environments` makes sense to me.
