### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by michaelvirgil** [openshiftio/openshift.io#289]
# Description
As a user, I want to be able to collaborate with other users in a space.

# Acceptance Criteria
- [ ] The collaborators page should have advanced searching capabilities.
- [ ] The collaborators page should have an easier add functionality. 
- [x] Only collaborators may add new work items to a space https://github.com/almighty/almighty-core/issues/1358
- [ ] Collaborators in a space - username selections
- [ ] A user should get an email notification if they have been added/removed as a collaborator on a space.
- [ ] A user that is a collaborator should have permissions and access to components etc. This is Space level access vs. System.
- [ ] It should be possible to grant specific collaborators certain privilegs, like admin privileges, so they can add/remove collaborators without being the space ownder (short term until teams and roles are in place)

**Note**: 
 
# Relationships
_Put linked Team/Product story links here_

**Comment by qodfathr** [comment]
We have new epics and stories coming for a complete permissions model which supersedes this.
