### ISSUE TITLE
Add object counts to returned environment quotas

### ISSUE THREAD

**Issue by ebaron** [openshiftio/openshift.io#2890]
The settings page wants to show quotas and usage of the following objects per environment:
* Services
* Persistent Volume Claims
* Replication Controllers
* Secrets

We should query this information from Kubernetes' ResourceQuota API, and return it from our Deployments API alongside CPU and Memory quotas.

Parent: #2625

**Comment by jiekang** [comment]
Please make it a separate endpoint so the deployments page need not filter it for their use case.

**Comment by joshuawilson** [comment]
Is it the same information?

**Comment by jiekang** [comment]
This new part adds:
* Services
* Persistent Volume Claims
* Replication Controllers
* Secrets

These aren't used in the deployments page.

The old info is
* CPU
* Memory

Both settings page and deployments page use this data.

**Comment by joshuawilson** [comment]
I would think having one API makes more sense to maintain. Just display what you need in the UI that needs it. Am I missing something?

**Comment by jiekang** [comment]
Right; I forgot about #2086. Okay.

Having the UI filter out results is definitely doable, but I feel like it's unnecessary extra work if we have control of the API. In light of #2086 I withdraw my objection to augmenting the same API.

**Comment by ebaron** [comment]
This is essentially the same as https://openshift.io/openshiftio/openshiftio/plan/detail/2005, but this issue is from the perspective of the resources page instead of the deployments page.
