### ISSUE TITLE
Need support for Gopkg.lock file in mercator

### ISSUE THREAD

**Issue by abs51295** [openshiftio/openshift.io#2893]
Currently, we only support `glide.lock` file for Go ecosystem in [mercator](https://github.com/fabric8-analytics/mercator-go). Need to support `Gopkg.lock` file since the following OSIO repositories have it (which account for 50% of total repositories):

- https://github.com/fabric8-services/fabric8-tenant
- https://github.com/fabric8-services/fabric8-oso-proxy
- https://github.com/fabric8-services/fabric8-jenkins-proxy
- https://github.com/fabric8-services/fabric8-toggles-service
- https://github.com/fabric8-services/fabric8-jenkins-idler

**Comment by msrb** [comment]
I have to move this to the next sprint as I don't think we will have capacity to do it this sprint.

**Comment by msrb** [comment]
Implemented in: https://github.com/fabric8-analytics/mercator-go/pull/50
