### ISSUE TITLE
OSIO Launcher require few configurable options at Pipelines screen

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2894]
Currently at OSIO wizard, 'Trigger Build' and 'Add Integration webhoooks' are configurable (checkboxes). These options are missing at OSIO Launcher's pipelines screen..

Please see the screenshot for current OSIO wizard:

<img width="501" alt="screen shot 2018-04-05 at 2 08 10 pm" src="https://user-images.githubusercontent.com/15967765/38355626-208e86b8-38db-11e8-90bf-a0e520db7063.png">

cc @GeorgeActon @animuk

**Comment by invincibleJai** [comment]
@catrobson @gastaldi needed your inputs here as per UXDs and related docs we don't have these configuring options in the pipeline.

**Comment by catrobson** [comment]
I expect us to just go with the defaults in the background, have Jenkins named, automatically trigger build and add web hooks.  I don't think we need to expose these options to the user right now in OSIO, and as we grow we can decide if more configuration is needed.

**Comment by gastaldi** [comment]
I agree with @catrobson, if making the user experience better is a goal (like having a single version for each booster), these flags won't help achieving it

**Comment by invincibleJai** [comment]
@catrobson that was even my thought process to provide user with options which is needed  and subtracting what is default and obvious.  But looks like that was an useful feature 
CC @slemeur

**Comment by slemeur** [comment]
@catrobson + @gastaldi + @invincibleJai : Fine for me to keep those options enabled by default and not display the ability to configure those. But in term of clarity for the end-user, should we be explicit and explain that we are configuring this him? Something like: "Web hooks will be setup on the repository to automatically trigger the selected pipeline". 

BTW - At this moment, if those options are not configured, we don't have any option to start a pipeline or I have not been able to find it.

**Comment by catrobson** [comment]
@slemeur I feel like we're already saying this is how our system works overall in how we talk about it in marketing materials and what we're doing in our intro/getting started tour for OSIO.  It feels like extra information that just adds cognitive load at the time of creating a new application that isn't necessary to me.  Until someone brought up these previous selections, isn't this what you just naturally expected to happen given how we market OSIO?
