### ISSUE TITLE
Unable to reset environment via User profile

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#2901]
`User Menu`->`Profile`->`Update Profile`->`Reset Environment`->`Erase My OpenShift.io Environment`->`I understand my actions - erase my environment`

After a moment the UI says:
![image](https://user-images.githubusercontent.com/3263627/38372700-c413b16e-38ef-11e8-9865-1d9b1e1fc611.png)

The Console says:
```
DELETE https://api.openshift.io/api/user/services 504 (Gateway Time-out)
DELETE https://api.openshift.io/api/user/services 504 (Gateway Time-out)
Failed to load https://api.openshift.io/api/user/services: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://openshift.io' is therefore not allowed access. The response had HTTP status code 504.
```

**Comment by pmacik** [comment]
The account is provisioned on `starter-us-east-2` cluster.

**Comment by ldimaggi** [comment]
I think that this is part of the issue described in: https://github.com/openshiftio/openshift.io/issues/2895

**Comment by pmacik** [comment]
@ldimaggi Seems familiar, thx

**Comment by pmacik** [comment]
Today the issue is on both prod and prod-preview for the users provisioned on `starter-us-east-2a` cluster.
