### ISSUE TITLE
OpenShift project Name when creating from a template can be not valid with initial value and no validation available

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#2902]
I created a new space named 20180504 (yes with the date)
Then I choose to start form a template and choose SpringBoot one
on next steps, I have the "Next" button disabled without error message:
![image](https://user-images.githubusercontent.com/1105127/38373152-d8bcac0a-38f0-11e8-81e7-dfef1dadb4a2.png)

I found that the issue is that the OpenShift project name is not valid after modifying it

**Comment by sunilk747** [comment]
This legacy issue is not present anymore. We have solved this by re-engineering the new launcher experience flow. Please refer the attached image for reference.
![screenshot from 2018-04-24 16-33-47](https://user-images.githubusercontent.com/7105965/39183499-d7a5650e-47dd-11e8-9a1e-330acdee8b62.png)

cc @animuk
