### ISSUE TITLE
The link of "Build #" in pipelines view is redirecting to openshift.io instead of going to a page showing the build

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#2904]
![image](https://user-images.githubusercontent.com/1105127/38373932-b91419b8-38f2-11e8-9928-c0025ab821d5.png)

**Comment by joshuawilson** [comment]
I can confirm. It is not working the way it should.

**Comment by jiekang** [comment]
Closing as duplicate of https://github.com/openshiftio/openshift.io/issues/2744
