### ISSUE TITLE
Could not create workspace image spring-boot not found

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#2906]
I created a new workspace with a SpringBoot provided example and try to create a workspace:
![image](https://user-images.githubusercontent.com/1105127/38373985-e06f949c-38f2-11e8-9423-722d6bd6c3f3.png)

**Comment by apupier** [comment]
> I guess your account is provisioned on starter-us-east-2, right?

yes

**Comment by rhopp** [comment]
@apupier Please try now (and if it does not work, try reseting environment in OSIO and try once again). Now, when #2895 is closed, this should be solved also AFAIK.

**Comment by apupier** [comment]
working now.
