### ISSUE TITLE
Feature toggled user-level divs still have directives loaded

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2908]
Example:

`analyze-overview-component.html` has a `user-level` classed set of divs:
 `<div id="analyze-overview-dashboard" class="container-fluid analyze-overview-wrapper" user-level>`

These are not visible to most users. However, this is in the HTML, and for whatever reason, the angular directives *are* loaded. In this example,  `<fabric8-pipelines-widget (addToSpace)="openForgeWizard(addSpace)"></fabric8-pipelines-widget>` appears twice in the html, once within the `user-level` set, and once within the standard set.

Angular loads this directive twice, even though I can only see one instance of the widget in the HTML inspected via console. The components are loaded and make http requests, taking cpu/memory, while being 'hidden'.

To test:

Place a `console.log()` call in the `ngOnInit` of `pipelines-widget.component.ts` and/or `analytical-report-widget.component.ts`. Observe two instances of `ngOnInit` for the respective component. Comment out the `user-level` classed divs in `analyze-overview-component.html`. Observe one instance of `ngOnInit` for the respective component.

**Comment by jiekang** [comment]
@corinnekrych any ideas?

**Comment by corinnekrych** [comment]
@jiekang you can use dynamic load for component doc is here: https://github.com/fabric8-ui/fabric8-ui/wiki/fabric8-toggles#my-feature-is-a-component-i-want-to-dynamically-load
for new feature component.
Atm we don't have the "refator" (ie: if/else feature) for dynamic load.

**Comment by andrewazores** [comment]
@corinnekrych  https://github.com/openshiftio/openshift.io/issues/3629

**Comment by corinnekrych** [comment]
This closed by https://github.com/fabric8-ui/fabric8-ui/pull/3202
