### ISSUE TITLE
A diagnose pipeline to capture tenant status and metadata to help diagnose tenant issues

### ISSUE THREAD

**Issue by jstrachan** [openshiftio/openshift.io#291]
a pipeline job may be the easiest place to do nightly diagnosis reports on whats happening in the tenant space; what pods are running, restarts, memory usage and whatnot.

ultimately we'll have nice prometheus & elasticsearch to help; but a job we can trigger on a per user basis on demand might be the simplest thing to do.

Being able to login to tenants Jenkins might be handy too so we can noodle the diagnosis reports and historic ones

**Comment by sthaha** [comment]
I am not sure if this should be done as a jenkins job given that jenkins itself sometimes fails to start. I am closing this one year old issue. Please reopen if you disagree.
