### ISSUE TITLE
Wireframes: Space level permissions

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#2910]
### Description
Wireframes that cover the full set of designs needed for space permissions

### Parent Issue(s)
- #2075
- #2069

### Verification Criteria
- [x] Wireframes created in Sketch and posted on Google Drive with interaction notes for all behaviors
- [x] Wireframes posted to InVision
- [ ] Wireframes reviewed by UXD, Dev, PM

**Comment by lwrigh** [comment]
Here's the connected issue from Fabric8: https://github.com/fabric8-ui/fabric8-ux/issues/927

**Comment by lwrigh** [comment]
Current Invision prototype: https://redhat.invisionapp.com/share/MFGCA0W2ZQA

**Comment by lwrigh** [comment]
A user flow documenting the "invite users to space" path has been added to the Invision doc

**Comment by lwrigh** [comment]
Flows and wireframes to document the add teams and security groups flows are currently being worked on

**Comment by lwrigh** [comment]
Here's a current link to the prototype: https://redhat.invisionapp.com/share/QNGBDSOHP6K
