### ISSUE TITLE
Wireframes: Scrum Template in Planner

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#2912]
### Description
Wireframes for any changes required in the planner to support the Scrum template.  Visual designs where required.

### Parent Issue(s)
- https://openshift.io/openshiftio/openshiftio/plan/detail/1823

### Verification Criteria
- [x] Icons and colors for new work item states and groups identified and captured in InVision, any tracking spreadsheets
- [x] Consider any other impacts of the scrum template on the experience and how they should be handled.  Capture as docs, wireframes, or flows.

**Comment by Veethika** [comment]
Done: 
a. Discussion about the standard Scrum process types and their respective states with Scrum master
b. Competitor study and analysis

In Progress: To come up with initial set of sketches and wireframes for scrum template and discuss with the concerned people in the planner team and PM

**Comment by catrobson** [comment]
@Veethika thanks.  Any links for competitor study and analysis, requirements and states captured?

**Comment by Veethika** [comment]
@sunilmalagi @muruGanesan @catrobson here is the InVision link: https://redhat.invisionapp.com/share/CEHEDZGXNZJ
The screenshots from various apps do not follow the same pattern because each one of them have provided the choice of process in a different manner.

**Comment by Veethika** [comment]
https://redhat.invisionapp.com/share/CEHEDZGXNZJ

**Comment by catrobson** [comment]
Was there any work captured around improvements to the current scrum implementation in planner that can be linked to?  If not what are the next steps for this story?

**Comment by muruGanesan** [comment]
NOTE: Currently, Planner team implemented scrum template i.e. Scrum template is already available in Planner but we need to find the better way of implementing SDD, Scrum, and Agile template.
**Discovery:**
We need to discuss with Scrum masters, Agile coach and Planner team find the common template. This is more of discovery/Analysis phase.
I will update once I get more information from the above people. This is not targeted for the I-train.

**Comment by Veethika** [comment]
Creating a new story to capture the new set of evolved verification criteria #3733
