### ISSUE TITLE
Planner UI Cleanup and Consistency

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#2913]
### Description
Planner has many UI layout issues where there are several alignment, spacing, sizing, and other issues that make it look unrefined.  There are also many consistency issues within the planner and to the rest of OpenShift.io.  This story is to identify a list of all these issues, and resolve those that are minor fixes to HTML/CSS.

### Parent Issue(s)
- NONE

### Verification Criteria
- [x] Document capturing all areas of Planner layout, alignment, spacing, sizing, etc issues as well as consistency problems
- [x] PRs submitted and document updated to show which items have been resolved for minor fixes in HTML/CSS

**Comment by sunilmalagi** [comment]
UI cleanup done based on existing review feedback.
