### ISSUE TITLE
Work item preview panel is blank

### ISSUE THREAD

**Issue by SkorikSergey** [openshiftio/openshift.io#2918]
**Reproduction Steps:**
1. Create any work item in the **Planner**.
2. Go to the **Board** tab and return to the **Backlog** tab.
3. Open this work item preview panel by clicking on the work items title.

**Expected result:**
The work item preview panel is opened.

**Actual result:** 
The work item preview panel is blank.

**Screenshot:**
![plan backlog - openshift io - google chrome_226](https://user-images.githubusercontent.com/7760565/38419370-da9f1ff4-39a8-11e8-8805-16a377f6361d.png)

**Screencast:**
![nimbus-record-video-2018-04-06-14-47-40](https://user-images.githubusercontent.com/7760565/38419567-a28a9b60-39a9-11e8-87c6-0c76630c38a2.gif)

**Comment by nimishamukherjee** [comment]
@vikram-raj can you have a look. I'm not able to replicate the issue.

**Comment by SkorikSergey** [comment]
Not reproduced.
