### ISSUE TITLE
Cannot change work item state in the Board tab

### ISSUE THREAD

**Issue by SkorikSergey** [openshiftio/openshift.io#2919]
**Reproduction Steps:**
1. Create any work item.
2. Go to the **Board** tab.
3. Drag and drop created work item to other state.
4. Return to **Backlog** tab and check this work item state.

**Expected result:**
The work item state changed.

**Actual result:** 
The work item state not changed and there is "**ERROR [WorkItemService] Updating work item failed.** " error in browser console.

**Screencast:**
![nimbus-record-video-2018-04-06-15-02-39](https://user-images.githubusercontent.com/7760565/38420272-dd0067c8-39ab-11e8-9897-7ab9a3555e13.gif)

**Comment by nimishamukherjee** [comment]
We will be re-do the board view in I train.
