### ISSUE TITLE
TypeError when clicking anything to route on openshift.io that breaks application

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2922]
Steps to reproduce:

1. Visit openshift.io, log-in and click any links that go to other openshift.io pages, e.g. 'My Spaces', 'View All Spaces', a recent space or pipeline, etc.
2. See `TypeError: Object(...) is not a function`

![broken-osio](https://user-images.githubusercontent.com/5430520/38434142-572d13fe-399b-11e8-8111-aa5f512c7ab0.png)

**Comment by joshuawilson** [comment]
I think it is a duplicate of #2915 but the error is different, so we can keep this open for now. The fix for one might fix both.

@jiekang were you able to get past it with a refresh?

**Comment by jiekang** [comment]
@joshuawilson I wasn't able to get past it with a refresh. It's only affecting my Google Chrome browser though. I expect a manual cleanup of the cookies/storage/etc. via Google Chrome's settings may assist, but I'm keeping it for now for investigation purposes.

**Comment by joshuawilson** [comment]
try setting the `disable cache` option on the Network tab and doing a hard refresh `ctl + shft + R`

**Comment by jiekang** [comment]
Looks like the prod build has been updated and I can no longer reproduce this error; closing.
