### ISSUE TITLE
Appearance of misplaced text over title on adding filter

### ISSUE THREAD

**Issue by Veethika** [openshiftio/openshift.io#2923]
Problem:
Go to Plan>>Requirements>>Add any filter, misplaced text overlaps on "Add Work Item"
<img width="1675" alt="screen shot 2018-04-05 at 4 25 34 pm" src="https://user-images.githubusercontent.com/35127763/38434554-73b119d4-39ec-11e8-89e6-b67555f088bc.png">

**Comment by jiekang** [comment]
@joshuawilson noticed the team/platform label. Wouldn't this be something for team/planner instead?

**Comment by joshuawilson** [comment]
yes @jiekang thanks, updated.

**Comment by nimishamukherjee** [comment]
Issue fixed
![count](https://user-images.githubusercontent.com/1892722/48819967-ae3ea680-ed78-11e8-8e3c-4de7e3e2f0d0.png)
