### ISSUE TITLE
Left-hand navigation prototype needs edits (3)

### ISSUE THREAD

**Issue by Essjaysee** [openshiftio/openshift.io#2926]
The prototype for the left-hand navigation design needs a couple edits to match the design fully.

- [x] The text size for "My Dashboard", "My Work Items", "My Settings", "Help", and "Log Out" needs to be a bit larger
- [x] There's a drop-down below "My Work Items" that isn't in the prototype -- I think it's supposed to be a space selector
- [x] There are two instances of the email address at the top of the prototype

See https://redhat.invisionapp.com/share/N5F0DF7PY#/screens/270120613 and https://github.com/fabric8-ui/fabric8-ux/issues/884

**Comment by mindreeper2420** [comment]
- Updated text size from 14px to 16px.
- change the dropdown to a button, in order to match the context selector styling
- email address piece updated

**Comment by mindreeper2420** [comment]
- Updated text size from 14px to 16px.
- change the dropdown to a button, in order to match the context selector styling
- email address piece updated

**Comment by Essjaysee** [comment]
These are done, thanks.
