### ISSUE TITLE
disable the auto-creation of the Jenkins pod in the users main namespace

### ISSUE THREAD

**Issue by jstrachan** [openshiftio/openshift.io#293]
when we create a BuildConfig in the users main namespace, openshift automatically creates a Jenkins. Though there's also one in the `-jenkins` namespace ;)

So we need to disable OSO from automatically creating the jenkins in the main namespace

**Comment by aslakknutsen** [comment]
You mean something beyond deploying the dummy "Jenkins" service in the user namespace? Else this sounds fixed...

**Comment by joshuawilson** [comment]
Is this fixed or is there something else to do?

**Comment by aslakknutsen** [comment]
I believe this is a missing Openshift feature.

**Comment by jstrachan** [comment]
So long as there is a Jenkins service in the users namespace it seems to be resolved - that's how openshift decides on whether to create a Jenkins or not

**Comment by joshuawilson** [comment]
Once we get the namespace in OSO to be static, is this still a concern?

**Comment by jstrachan** [comment]
whether the namespace is static or not, users can remove the 'jenkins' service. So it'd be nice if we had another way to mark a namespace to disable the auto-creation of a jenkins DC. e.g. maybe if we could annotate the Project (since users can't normally annotate or change annotations on a Project due to security)?

would require a change in OSO mind you though

**Comment by aslakknutsen** [comment]
@jstrachan Do we have an Openshift issue reported for this?

**Comment by jstrachan** [comment]
no not yet. I wonder if our current f8tenant account has karma to add annotations to a Project?

**Comment by aslakknutsen** [comment]
@jstrachan Why not open an issue with Openshift and let them figure out a solution. If in the end that means annotating a Project we'll get the auth sorted.

**Comment by jstrachan** [comment]
https://github.com/openshift/origin/issues/15653

**Comment by rawlingsj** [comment]
@vpavlin  I think this has been done now?

**Comment by jstrachan** [comment]
AFAIK this has been fixed at the cluster level now?
