### ISSUE TITLE
Pipeline Build Failing for Wildfly healthcheck boosters

### ISSUE THREAD

**Issue by animuk** [openshiftio/openshift.io#2930]
In the new experience Getting Started Flow, Pipeline build is failing for Wildfly healthcheck boosters,
Please see the below failed log - 
https://gist.github.com/ravsa/b022b71bee5fda1f5dc5436b61c09609

**Comment by ravsa** [comment]
related issue: https://github.com/fabric8-launcher/launcher-booster-catalog/issues/189

**Comment by animuk** [comment]
closing this because it is tracked in https://issues.jboss.org/browse/SWARM-1701

**Comment by ldimaggi** [comment]
Duplicate of:  https://github.com/openshiftio/openshift.io/issues//3134
