### ISSUE TITLE
Jenkins is becoming Idle for pipeline build in OSIO launcher flow. 

### ISSUE THREAD

**Issue by animuk** [openshiftio/openshift.io#2931]
Due to this Jenkins issue, No build could not able to see the finish line.
This is a critical issue from the build pipeline endpoint. Please check the below screenshot.
![jekins_idle](https://user-images.githubusercontent.com/11207106/38484498-754ac61e-3bf4-11e8-9dfd-f82601e17d9b.png)

**Comment by pbergene** [comment]
If this was on 2a this morning at the time the issue was filed then the masters were out of order.  Please confirm if you are still seeing this. :)

**Comment by krishnapaparaju** [comment]
I am not seeing this problem at my account, confirmed with atleast 2 other OSIO users. downgrading to SeV-2

**Comment by piyush1594** [comment]
@animuk This is not the case in the current system. Can you please just confirm and close this issue? Build is working fine for me.

**Comment by animuk** [comment]
@piyush1594 , thing is that, this idling of the jenkins can be seen intermittently though this is not happening every time. this week also, for one of the request, jenkins build went to idle state for around 15 mins, after that I killed the build.

**Comment by piyush1594** [comment]
Yes, we are aware of the issue sometimes Jenkins is failing to become un-idle and that may be causing this issue. That issue is logged at #3517 and work is in progress. @animuk

**Comment by lordofthejars** [comment]
If this is already identified and tracked to another issue, maybe we could close it.

**Comment by sthaha** [comment]
@animuk This issue should be fixed with the recent changes to the jenkins image and deployment config. You should see jenkins getting unidled within 3 mins. Please reopen the bug if that isn't case.

Ref: https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/114
