### ISSUE TITLE
starter-us-east-2a: Could not start workspace - Image registry.devshift.net/che/vertx:latest not found.

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#2938]
![image](https://user-images.githubusercontent.com/3263627/38489465-c6bce2f6-3be6-11e8-85b0-7f439099788f.png)

**Comment by pmacik** [comment]
First affected a daily test executed on April 8th ~5:30 AM UTC

**Comment by joshuawilson** [comment]
cc @pbergene

**Comment by pbergene** [comment]
This is probably due to the master outage on east-2a this morning.  Closing - re-open and ping me if you still see it. :+1:
