### ISSUE TITLE
starter-us-east-2a: Unable to reset environment via User profile

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#2939]
`User Menu`->`Profile`->`Update Profile`->`Reset Environment`->`Erase My OpenShift.io Environment`->`I understand my actions - erase my environment`

After a moment the UI says:
![image](https://user-images.githubusercontent.com/3263627/38490280-f929d77e-3be8-11e8-814f-7ffb15e69d31.png)

The Console says:
```
DELETE https://api.openshift.io/api/user/services 504 (Gateway Time-out)
DELETE https://api.openshift.io/api/user/services 504 (Gateway Time-out)
Failed to load https://api.openshift.io/api/user/services: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://openshift.io' is therefore not allowed access. The response had HTTP status code 504.
```
It happens for both prod and prod-preview for the accounts provisioned on `starter-us-east-2a` cluster.

**Comment by rhopp** [comment]
Seems like this could be related to incident happening right now on starter-us-east-2a. (devtools-saas mailing list: "[prod][incident] Master controllers unavailable on starter-us-east-2a")

**Comment by joshuawilson** [comment]
cc @pbergene

**Comment by pbergene** [comment]
This is probably due to the master outage on east-2a this morning.  Closing - re-open and ping me if you still see it. :+1:
