### ISSUE TITLE
[Launcher] In GitHub Provider View Location dropdown should show User's ID as default

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#2942]
- In GitHub Provider View Location drop-down should show User's ID as the default value

![38372974-7b6f389e-38c6-11e8-9f0d-b9ac404b670b](https://user-images.githubusercontent.com/5129024/38495893-040e6d96-3c19-11e8-8b12-57f5ac5a0fac.png)

**Comment by gastaldi** [comment]
Can the `Select` option be removed from the UI?

**Comment by invincibleJai** [comment]
@gastaldi sorry, now I got it. So you meant default gitHub name should be selected and "select" option shouldn't be there in drop-down?

**Comment by gastaldi** [comment]
@invincibleJai yes, I see the first option is already done, it would be nice to have the second option too :smile:

**Comment by invincibleJai** [comment]
changes are in prod, hence closing.
