### ISSUE TITLE
[Launcher] New getting started User experience is not good in firefox

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#2944]
- New getting started User experience is not good in firefox
- Issue with navigation to next step
- Lots of extra spaces
<img width="1673" alt="screen shot 2018-04-09 at 5 41 09 pm" src="https://user-images.githubusercontent.com/5129024/38497113-9f42940a-3c1d-11e8-8689-4c3c0e17cab9.png">

**Comment by animuk** [comment]
@invincibleJai  is the aboce PR solved the issue?

**Comment by animuk** [comment]
@jyasveer can u please check this ?

**Comment by jyasveer** [comment]
alignment fix is here https://github.com/fabric8-ui/fabric8-ui/pull/2815

**Comment by invincibleJai** [comment]
Thanks @jyasveer, closing it works fine for me.
