### ISSUE TITLE
creator icon is not the right one

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#2946]
Used quick add to add a fundemental. 

The creator icon is not the same as the user logged in. 

![2018-04-09_15-40-16](https://user-images.githubusercontent.com/54129/38501038-4fe6ce50-3c0c-11e8-89f8-3404bc219918.png)

**Comment by catrobson** [comment]
Tried in planner, and it is showing the creator icon as my own when adding fundamental using quick add.  @sanbornsen @Veethika could you both verify as well by testing this flow and we can close if it is resolved?

**Comment by Veethika** [comment]
@catrobson this issue is resolved, we can close it.

**Comment by catrobson** [comment]
Closing issue as no longer reproducible, appears to be fixed in production.
