### ISSUE TITLE
When assignee doesn't exist, Add Assignee widget just vanishes

### ISSUE THREAD

**Issue by nickboldt** [openshiftio/openshift.io#2948]
From this page:

https://openshift.io/openshiftio/eclipse-che/plan/detail/41

I tried to assign this Fundamental to myself. But seems I'm not available as an assignee.

Tap + Add Assignee, start typing "nick"

![image](https://user-images.githubusercontent.com/227597/38502520-a2e363c2-3bdd-11e8-8ebe-c7633d4561dc.png)

When I hit the "c" which causes the filter to not match anyone, the widget vanishes:

![image](https://user-images.githubusercontent.com/227597/38502549-aaafbab0-3bdd-11e8-8de5-692f11d26bda.png)

And the only way to get it to reappear is to reload the page -- backspace obviously doesn't work.

So this fails in two ways:

a) I can't add myself, because I'm not in the system. But I can create new Fundamentals, even if I can't assign them to myself.
b) if I enter a typo when assigning an issue, I need to reload the page just to fix the typo. This is bad.

**Comment by rgarg1** [comment]
@nickboldt I was able to reproduce the issue where the modal auto-closes, but I cannot add a workitem without being a collaborator or space owner. The backend API throws a permission denied error when I try to do that, which is expected. What am I missing?

**Comment by nimishamukherjee** [comment]
Closing this issue as the steps mentioned by @rgarg1 have been addressed.
@nickboldt if you see this issue please re-open this issue.
