### ISSUE TITLE
Page title for a backlog board is "Loading..." not something more descriptive/useful

### ISSUE THREAD

**Issue by nickboldt** [openshiftio/openshift.io#2951]
Logging in to a planner board such as https://openshift.io/openshiftio/eclipse-che/plan?q=(space:7d747e1f-d66e-497c-b0f5-30dac9cc75bc%20$AND%20typegroup.name:Scenarios)&showTree=true I have to go through several steps (see https://github.com/openshiftio/openshift.io/issues/2950 )

Once logged in and looking at the backlog board, I thought, "that URL is super cumbersome to remember, I should bookmark it" and hit CTRL-D to bookmark it.

That's when I noticed the page title in Chrome is just "Loading..." instead of something useful like "eclipse-che backlog board". 

Surely a better page title is possible so when bookmarking these crazy-long URLs they're more meaningful?

**Comment by ppitonak** [comment]
Related to this... if you open a link to an issue (e.g. https://openshift.io/openshiftio/openshiftio/plan/detail/1873), browser window/tab title is "Plan: Detail - OpenShift.io" which is not usable for bookmarks.

**Comment by nimishamukherjee** [comment]
Closing as we are working on a new revamped board view.

**Comment by ppitonak** [comment]
@nimishamukherjee why not to leave it open until new board view is in place?

**Comment by ppitonak** [comment]
I suggest to change severity to sev2 because it's important if we want to use Planner.

**Comment by joshuawilson** [comment]
Bookmarking any space for planner has the title `Plan: Backlog - OpenShift.io`. This still needs to be fixed.

**Comment by joshuawilson** [comment]
It should use the name of the Space like `Foo: Backlog - OpenShift.io`.  Where `Foo` is the space name.

**Comment by nimishamukherjee** [comment]
@openshiftio/uxd-team need your input on the bookmark title format.

**Comment by ppitonak** [comment]
Github does the following, IMHO both are acceptable

browser title: `Description of an issue  · Issue #99999 · openshiftio/openshift.io`
email notification: `[openshiftio/openshift.io] Description of an issue (#99999)`

**Comment by christianvogt** [comment]
Title is still incorrect and should be `Plan: Board - <product name>` to align with the other pages.

**Comment by christianvogt** [comment]
@ppitonak I was just commenting that the board title is still incorrect. I agree that a title including the summary of an issue similar to github would be more useful for when accessing an issue directly.
