### ISSUE TITLE
direct links to items open a blank page 

### ISSUE THREAD

**Issue by gorkem** [openshiftio/openshift.io#2953]
When opening a link such as https://openshift.io/openshiftio/eclipse-che/plan/detail/41 the page comes blank.

![plannerblank](https://user-images.githubusercontent.com/82738/38505592-8c63c35a-3be5-11e8-80fb-63d022ba3707.gif)

**Comment by aptmac** [comment]
FWIW, direct links to details are working for me with Chrome/Chromium, but not with Firefox.

**Comment by aptmac** [comment]
duplicate: https://github.com/openshiftio/openshift.io/issues/2285

**Comment by rgarg1** [comment]
Assigned to @sahil143 as the original issue (https://github.com/openshiftio/openshift.io/issues/2285) is assigned to him too.

**Comment by joshuawilson** [comment]
closing duplicate
