### ISSUE TITLE
app chunks bloated by including planner multiple times

### ISSUE THREAD

**Issue by christianvogt** [openshiftio/openshift.io#2955]
Ran bundle analyzer and observed that planner was included in several chunks. Planner contributes 988kb (minified) in 6 chunks. rh-ngrx-datatables is also included 6 times at 222kb (minified).

In fact 3 chunks appear to be exactly the same.

![bundle analyzer](https://user-images.githubusercontent.com/14068621/38509887-352e017a-3bf1-11e8-9906-ceb9fb72744d.png)

**Comment by christianvogt** [comment]
Tree shaking should have reduced the inclusion of the planner library in several chunks.

Tree shaking with webpack has always been a source of problems. Add typescript to the mix to further complicate the issue. Webpack 4 has addressed a lot of historic issues. Since we are planning to move to angular 5 after summit, we can also upversion webpack at that time. We may want to hold off on investigating this issue until then.

**Comment by joshuawilson** [comment]
I agree, this should wait till after we upgrade to webpack 4.
