### ISSUE TITLE
cancelling work item "add label" or "add assignee" causes "Workitem updated." toast notification

### ISSUE THREAD

**Issue by christianvogt** [openshiftio/openshift.io#2959]
Even though no changes to a work item have occurred, the user is presented with a toast notification "Workitem updated" when cancelling the addition of a label or an assignee.

**Steps to reproduce:**

- Create a work item
- Open work item
- Click assign labels button
- Click the x button to close the popup

**Observe:** Toast notification saying "Workitem updated."
**Expected:** No toast notification and for dialog to close silently.

**Comment by aslakknutsen** [comment]
Probably related https://github.com/openshiftio/openshift.io/issues/2736

**Comment by debloper** [comment]
Duplicate of #2736

**Comment by joshuawilson** [comment]
this is fixed in production
