### ISSUE TITLE
Use Zabbix REST API to populate the status for Planner & Platform

### ISSUE THREAD

**Issue by jstrachan** [openshiftio/openshift.io#296]
this is for for OSIO - for fabric8 on premise we'd either disable or use something else?

Here's the code:
https://github.com/fabric8-ui/fabric8-runtime-console/blob/master/src/app/kubernetes/ui/status/status-list.component.html#L3-L9

**Comment by qodfathr** [comment]
We don't have a status widgets for Planner or Platform, but we do have relevant status widgets, so I feel this is safe to close. As we continue to componentize the major features of OSIO, it likely makes sense for each to be able to dynamically augment the status widget as part of the extension APIs.
