### ISSUE TITLE
Refactor EnvironmentWidget to use DeploymentApiService

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#2961]
Parent: https://github.com/openshiftio/openshift.io/issues/2921

# Task

The EnvironmentWidget currently consumes the DeploymentsService, which is being repositioned as specific to the Deployments page only. The new DeploymentApiService being introduced is intended as a generalized and simplified replacement for external consumers, such as the EnvironmentWidget.

# Relationships

- [x] https://github.com/openshiftio/openshift.io/issues/2924 Provide DeploymentApiService

**Comment by andrewazores** [comment]
Possibly obsoleted - the new Analyze dashboard appears to no longer use the EnvironmentWidget?

**Comment by jiekang** [comment]
Agreed as obsolete. @andrewazores I think you can close this issue.

**Comment by andrewazores** [comment]
Well the EnvironmentWidget either needs to be updated as this issue planned for, or it needs to be removed along with its corresponding DeploymentsService bits. I'll see what the timeline is for the new Analyze dashboard and update this issue accordingly.

**Comment by andrewazores** [comment]
Not obsolete after all. The widget may or may not end up being removed, so I'll assume it will be around for some time and move ahead on refactoring it.
