### ISSUE TITLE
stack report unknown link creates a work item

### ISSUE THREAD

**Issue by christianvogt** [openshiftio/openshift.io#2963]
Following through the getting started guide (https://docs.openshift.io/getting-started-guide.html#accessing_stack_reports) I get to a point where there are several dependencies listed in the dependency details. In the resulting table is a column titled "Action" and each row has a value of "
------", but it also happens to be a link. Clicking on this link results in a toast notification saying a work item was created.

Navigating away from this view and back shows the dashed link once again.

I do not expect there to be a link when dashes are displayed. Therefore clicking should not have any action taken.

![stackreport](https://user-images.githubusercontent.com/14068621/38522756-8b27649c-3c17-11e8-95b4-a7c7bda4e742.gif)

**Comment by sivaavkd** [comment]
@arunkumars08 @invincibleJai - is this still open ?  Do we want to move to 148 ?

**Comment by invincibleJai** [comment]
@sivaavkd issue has been already fixed by @arunkumars08 here is the PR https://github.com/fabric8-ui/fabric8-recommender/pull/442 , I don't think changes are in prod yet though.

**Comment by miteshvp** [comment]
@arunkumars08 - can we push these changes in the prod.

**Comment by arunkumars08** [comment]
@miteshvp @sivaavkd @invincibleJai The PR for the same in fabric8-ui is here - https://github.com/fabric8-ui/fabric8-ui/pull/2753

I will follow it up.
