### ISSUE TITLE
jenkins.prod-preview.openshift.io is broken

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/openshift.io#2964]
I get `502 - Bad Gateway` when trying to access https://jenkins.prod-preview.openshift.io.

![screenshot from 2018-04-09 18-37-41](https://user-images.githubusercontent.com/54133/38524481-1bfcbcd0-3c25-11e8-98ed-55ed4b0064e7.png)

**Comment by gastaldi** [comment]
Jenkins is working, since we can bypass the proxy and go direct to the route hostname and jenkins loads ok. It seems to be something in the proxy/idler

**Comment by gastaldi** [comment]
According to @aslakknutsen:

>it's definitely the proxy. it's panicing due to a bad cast. trying to case to a strut when it's a pointer in the 'cache'. Just add a * after ( here https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/master/internal/proxy/proxy.go#L325 assuming nothing else breaks. hehe

**Comment by chmouel** [comment]
duplicate with https://github.com/openshiftio/openshift.io/issues/2954

**Comment by kishansagathiya** [comment]
@gastaldi Fixed with https://github.com/fabric8-services/fabric8-jenkins-proxy/commit/1a3d28818c37d02dcd327fba1df1beef90acfca0
