### ISSUE TITLE
Service wide content repository

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#2967]
We currently have the content-repository service run on each tenant caching and providing the artifacts repository manager.

It would be much efficient to have a service wide content repository and use this.

- [ ] Provide a global content repository 
- [ ] make maven-builder using it (TODO: figure out how this is used)
- [ ] Remove old content-repository from tenants

**Comment by maxandersen** [comment]
lets make sure we are talking about the same things here.

There are having a global content repository used to proxy artifacts for reducing network latency and load - that could be a shared service backed by something like nexus or artifactory.

the other is about providing a way for jobs to share data between them, either raw cache data (like .m2) or artifacts (binaries) - those could go to a content repository; but it would need to be private for the jobs/config not globally shared.

Maybe something like cached paths or artifacts as gitlab does at https://docs.gitlab.com/ee/ci/yaml/#cache would be useful  ?

**Comment by chmouel** [comment]
yes but note that the content-repository is actually not used for that since the public route is disabled we only use it currently as a glorified cache, but i understand the supposed intent of the content-repo

**Comment by hrishin** [comment]
@sthaha its feature request.

**Comment by sthaha** [comment]
Closing this for now. lets open a new epic in planner if there is a need.
