### ISSUE TITLE
why are "workitem type" not "Type" when filtering ?

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#2972]
In filters "Workitem Type" stands out to everything else have single names: Assignee, creator, area, state, label and title.

![2018-04-10_09-58-25](https://user-images.githubusercontent.com/54129/38543747-b84f9a8c-3ca5-11e8-9189-0d56adaae57d.png)

Why not just Type ?

**Comment by catrobson** [comment]
+1 that this should just be 'Type'

**Comment by Veethika** [comment]
@maxandersen @nimishamukherjee can we go ahead with changing 'WorkItem Type' to 'Type'?

**Comment by maxandersen** [comment]
For me this looks like a visual bug that just needs fixing. Especially if its just the text string returned in the description from the backend. /cc @michaelkleinhenz @kwk in case that string is more than just a description ie. a key?

**Comment by kwk** [comment]
@maxandersen @Veethika @catrobson this is how my change looks in prod-preview. Please let me know if this is good to go into prod:

![bildschirmfoto von 2018-06-15 11-05-14](https://user-images.githubusercontent.com/193408/41460180-1227423e-708c-11e8-933b-3c566c8bcde8.png)

**Comment by Veethika** [comment]
Looks good to me 
@catrobson @maxandersen WDYT?

**Comment by catrobson** [comment]
@kwk @Veethika looks good.  Thanks!

**Comment by nimishamukherjee** [comment]
![consistentfilters](https://user-images.githubusercontent.com/1892722/41982535-53b65be2-7a49-11e8-804f-c021eec84fe8.png)

Closing this as fix is on production
