### ISSUE TITLE
Import -> delete -> import a quickstart should work

### ISSUE THREAD

**Issue by ppalaga** [openshiftio/openshift.io#2978]
@jfchevrette asked me to file this. So I am trying to recollect what I did not work for me.

In a clean OSIO account:

* Create a space called `spa1`
* Import any quickstart
* Wait for the first successful build and deployment
* Delete `spa1` in OSIO
* Create `spa1` again, import the same quickstart again

EXPECTED: the import of the quickstart should succeed incl. build and deploy
ACTUAL: OSIO was complaining that a so-and-so named BuildConfig already exists. I had to delete the BC manually.

**Comment by jfchevrette** [comment]
@ppalaga did you create a new app from quickstart both times or did you import from an existing repo the second time? Deleting a space will not delete the github repo so maybe that explains the error the 2nd time?

**Comment by ppalaga** [comment]
I think I was importing https://github.com/ppalaga/wildfly-camel-example-camel-cdi both times. I'd expect delete space operation to remove all openshift resources it has created itself.

**Comment by ldimaggi** [comment]
I have not been able to recreate this bug today - are you still seeing this?

**Comment by ppalaga** [comment]
Sorry, no time to look. Feel free to close if you cannot reproduce.

**Comment by ldimaggi** [comment]
Closing as not reproducible.
