### ISSUE TITLE
Create a new Quickstart project wizard failed to complete

### ISSUE THREAD

**Issue by piggyvenus** [openshiftio/openshift.io#298]
At the end of the Forge Wizard, I got an error like this:
<img width="837" alt="screen shot 2017-06-28 at 9 18 56 am" src="https://user-images.githubusercontent.com/15617833/27648844-bf277e94-5be4-11e7-9aaf-6763aeaab1f5.png">

**Comment by debianmaster** [comment]
+1 on this.   i'm on the same page.

**Comment by bartoszmajsak** [comment]
I saw it yesterday. I think updated tenant solved the problem.

**Comment by piggyvenus** [comment]
Yes, it did. Thanks! Tested and worked now.
