### ISSUE TITLE
"500 Internal Server Error" while fetching workitems on prod-preview

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#2981]
Request URL:https://api.prod-preview.openshift.io/api/search?page[limit]=200&filter[expression]={%22$AND%22:[{%22space%22:{%22$EQ%22:%22bbb1c8f0-29d2-4298-8fe0-997d175a5c58%22}},{%22typegroup.name%22:{%22$EQ%22:%22Scenarios%22}},{%22state%22:{%22$NE%22:%22closed%22}}],%22$OPTS%22:{%22tree-view%22:true}}

Request Method:GET

Status Code:500 Internal Server Error

**Comment by kwk** [comment]
Fixed with https://github.com/fabric8-services/fabric8-wit/pull/1997 . The URL returns a proper response now.
