### ISSUE TITLE
Duplicated codebases

### ISSUE THREAD

**Issue by pkettman** [openshiftio/openshift.io#2982]
It is possible to create duplicated codebases, see picture below.

Scenario:
1) add a pipeline by Importing existing codebase
2) delete the pipeline
Repeat both steps

Step 1) adds the pipeline and the corresponding codebase, no validation for codebase name is executed

![duplicatedcodebases](https://user-images.githubusercontent.com/26871874/38559049-425f5a92-3cd2-11e8-8300-c0ad15383624.png)

**Comment by ldimaggi** [comment]
Is there any functional impact? In other words, do the pipelines fail to run?

**Comment by aslakknutsen** [comment]
Fixed by https://github.com/fabric8-services/fabric8-wit/commit/02875f17b7051d569bd3f95a4dbce5b1ab443bb2
