### ISSUE TITLE
email-verification failing tests

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#2990]
The recent update to the email-verification has failing tests. I'm not sure how they passed the build but fail locally and in the master build.

The tests are at https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/email-verification/email-verification.spec.ts

**Comment by joshuawilson** [comment]
@SMahil can you please fix this.

**Comment by SMahil** [comment]
sure @joshuawilson

**Comment by nimishamukherjee** [comment]
https://github.com/fabric8-ui/fabric8-ui/pull/2724 fixed this issue.
