### ISSUE TITLE
List in work item description not displayed properly

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#2991]
Displaying markdown lists in work item description field is not working as desired.

If the list does not start from the 1st line, the list is not rendered.

E.g.
The following is displayed properly as a list:

```
This is a list:

- [ ] item1
- [ ] item2
```

The following is NOT displayed as a list:

```
This is a list:
- [ ] item1
- [ ] item2
```

**Comment by michaelkleinhenz** [comment]
Checkboxes are a GH-extension to Markdown that our used library does no support by default. Addig them would be rather easy (the same way we added the custom GH links to the markdown). The problem is in the persistence of the checked state for arbitrary checkboxes in Markdown values. That would require new functionality on the backend as well as frontend. I'd would even go so far that I would say that is not a 1 point change, but rather in the area of 8-10 points.

**Comment by michaelkleinhenz** [comment]
While there are a lot of different Markdown flavours, checkboxes are a GH invention that is not a part of the "common" Markdown - also because they don't make any sense without persistence. Therefore, this is not a bug rather than a new story.

**Comment by maxandersen** [comment]
this issue is about the formatting - not about persistence IMO.

We are literally talking here about that our markdown flavor requries a new line before the list where is github flavor does not.

Nothing else.

**Comment by michaelkleinhenz** [comment]
@maxandersen ah, yes, sorry, I was overreading the desc and was directly going from the Mattermost discussion here :-)

**Comment by maxandersen** [comment]
@rgarg1 updated the description so it uses verbatim so you can actually see and copy the exact text triggering the issue.

**Comment by rgarg1** [comment]
Thanks @maxandersen

**Comment by rgarg1** [comment]
Related to: https://github.com/openshiftio/openshift.io/issues/1837

**Comment by Preeticp** [comment]
This section in the User guide documentation https://docs.openshift.io/user-guide.html#adding_description_to_a_work_item  has a note with links to the standard markdown syntax provided by RH as well as the upstream library extensions used by Planner.
The note reads: "In addition to the [standard markdown syntax](https://access.redhat.com/help/markdown), refer to these [extensions](https://github.com/russross/blackfriday#extensions) for more information about the syntax."

**Comment by nimishamukherjee** [comment]
Thanks @Preeticp
