### ISSUE TITLE
Do not run dependency snapshot task if recursive limit is 0

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#2993]
# Description

Results of the dependency snapshot task are only used internally, during ingestion. However, if recursive limit parameter is set to 0, then the results are not needed and thus the task can be skipped.

**Comment by abs51295** [comment]
I think this is already done [here](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/dispatcher/flows/bayesianAnalysisFlow.yml#L104). @msrb WDYT?

**Comment by msrb** [comment]
@abs51295 nope: https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/dispatcher/flows/bayesianAnalysisFlow.yml#L85-L88

We still run dependency snapshot task even if recursive limit is set to 0.

**Comment by msrb** [comment]
Fixed in https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/697.
