### ISSUE TITLE
Planner GitHub icon should be always next to link text

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#2994]
1. add comment with multiple GitHub links and some long text

Result:
Since the text is long, lines are wrapped but the GitHub icon belonging to the link stays at the end of line instead of being placed next to the link on new line

![planner_github_icon](https://user-images.githubusercontent.com/445100/38598918-a0cd59d0-3d5e-11e8-93e8-7117b4f211fa.png)

**Comment by SMahil** [comment]
@nimishamukherjee in comments text and tags are getting rendered from the backend.

**Comment by ppitonak** [comment]
Still reproducible

**Comment by nimishamukherjee** [comment]
@ppitonak This is not an issue. It depends on the amount of text entered. We cannot dictate or "update" the user entered text.
If a user add a new line, the URL would come to a new line with the Git icon placed appropriately. 

1. Hanging Git icon
![hanginggiticon](https://user-images.githubusercontent.com/1892722/48820850-bac4fe00-ed7c-11e8-8e8d-9a380bf7baee.png)

2. No Git icon at the end
![longtext1](https://user-images.githubusercontent.com/1892722/48820858-c3b5cf80-ed7c-11e8-98fd-edb0e79511cc.png)

3. Each issue on a line

![newline](https://user-images.githubusercontent.com/1892722/48820895-ec3dc980-ed7c-11e8-98b1-3f51c594c657.png)

**Comment by joshuawilson** [comment]
I agree, this isn't a bug but word wrap.
I'm closing this. If you can come up with a user experience that fixes word wrap let us know.
