### ISSUE TITLE
Add and open does not open

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#2995]
Clicking Add and Open on workitems via quick add does not actually open the workitem.

It does add and I think I've seen it eventually open the workitem once or twice but it took a few seconds but here today it does not open within the first 5-10 seconds.

**Comment by nimishamukherjee** [comment]
Duplicate of #2567

**Comment by sahil143** [comment]
Not Duplicate of #2567

**Comment by nimishamukherjee** [comment]
Fix on production. Add and open UI functionality has been fixed. 
Firefox issue is being addressed in #2285
