### ISSUE TITLE
Have to click show more on even the simplest workitems - why not show all or at least allow scroll

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#2996]
On most issues and comments that are beyond a few lines I have to always click show more where as I'm naturally trying to scroll the text but nothing happens.

I would expect to either be able to scroll or that the show more/show less would be sticky since the screen is about 70% whitespace.

![2018-04-11_08-15-19](https://user-images.githubusercontent.com/54129/38599417-c7e9bb88-3d60-11e8-9d7d-5b76b32767c4.png)

**Comment by kwk** [comment]
@maxandersen, maybe consider switching to a smaller monitor ;)

**Comment by maxandersen** [comment]
> @maxandersen, maybe consider switching to a smaller monitor ;)

I get less whitespace in a smaller monitor but I still have to click show more to scroll in anything with more than a few lines. Very tedious.

**Comment by kwk** [comment]
@maxandersen I tried to make a joke and have said multiple-times that the "Show more" crap is trying to solve a problem we don't have yet. It is classic premature optimization.

**Comment by kwk** [comment]
Let's get rid of the pencil that is only showing on mouse hover as well and make it an always visible pencil as well. All those small details make the UI unusable on mobile.

**Comment by maxandersen** [comment]
yes, I know it was a joke - just wanted to point out that the amount of whitespace isn't the real issue ;)

**Comment by joshuawilson** [comment]
Closing as this is being tracked at https://openshift.io/openshiftio/Openshift_io/plan/detail/399
