### ISSUE TITLE
Left panel - items in iteration-tree clickable only on text

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#2998]
Items in left panel in iteration tree are clickable only on the text itself, even though the cursor indicates it should be possible to click anywhere in the `li` element (whole row).
Best shown on this gif:
![iteration-tree-bug](https://user-images.githubusercontent.com/1215011/38604013-7111d034-3d6f-11e8-9c28-744540401351.gif)

**Comment by nimishamukherjee** [comment]
@SMahil this is a duplicate right? Can you reference the original issue here?

**Comment by SMahil** [comment]
here is the PR: https://github.com/fabric8-ui/fabric8-planner/pull/2529

**Comment by SMahil** [comment]
@debloper We are not making entire block clickable as we already have three different action items inside the block

**Comment by debloper** [comment]
@SMahil I've submitted the fix here fabric8-ui/fabric8-planner#2564 - please take a look.
It also includes part of the style changes used in fabric8-ui/fabric8-planner#2529; thanks for that!

**Comment by SMahil** [comment]
This issue is fixed in prod
