### ISSUE TITLE
Planner have critical fixes in prod-preview that currentlty can't make it to prod

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#2999]
this issue is to link to to gather whatever is blocking it.

**Comment by jarifibrahim** [comment]
The planner team needs Github access token of centos-ci bot (previously we were using fabric8-cd bot) https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1715

**Comment by joshuawilson** [comment]
the issues have been fixed
