### ISSUE TITLE
can see other's spaces!

### ISSUE THREAD

**Issue by debianmaster** [openshiftio/openshift.io#300]
Logged in as cjonaga-io  but can see other's spaces too.?  it it on purpose?   ofcourse i could not delete them :) 

<img width="1263" alt="others" src="https://user-images.githubusercontent.com/1439169/27662148-83144ee6-5c11-11e7-9f93-fa239c477542.png">

**Comment by joshuawilson** [comment]
The Delete icon is being removed from ones you don't own to help clear up that part. This view allows you to search for spaces if you want to view one that is not your own. This is done on purpose.
