### ISSUE TITLE
Description Field Value goes missing when updating data on Quick Preview

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#3000]
When I update data on the Quick Preview (eg, add/remove Label, change title), the value of the decription field disappears. The value is still there on reload, but it vanishes from view.

**Comment by kwk** [comment]
@michaelkleinhenz can you add `env/prod` or `env/prod-preview` to tell where this issue occured?

**Comment by michaelkleinhenz** [comment]
Both prod and prod-preview yesterday. But since the latest deployment, it is no longer appearing for me. Closing.

**Comment by michaelkleinhenz** [comment]
Mhh..weird. It looks like it is only appearing sometimes. I just tested it and it worked, not it is not working again. Both on prod with 5 minutes between and no reload.

**Comment by michaelkleinhenz** [comment]
Possibly the same issue: when I open the quick preview of a WI, edit the title, then (without closing the qp), switch to a different WI, the title value gets "pinned" and is the one from WI#1 regardless of the selected WI.

**Comment by nimishamukherjee** [comment]
Closing this issue as fix is on production.
