### ISSUE TITLE
App launcher - on 2nd use in one login session - when user selections are complete - "Set up Application" button appears to fail - user is locked in the launcher

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3006]
Steps to recreate:
* Create a new app with the launcher - complete the process - observe the app build pipeline running
* Start to create a 2nd new app with the launcher
* At the completion of the selection process, the user presses the "Set up Application" button
* Nothing appears to happen - no errors are logged to the Chrome browser console 
* The "x" button to exit the launcher also appears to not be functioning
* If the user manually enters https://openshift.io into the browser URL, the pipeline page correctly shows that the app was created and the build pipeline is running

Workaround to this issue is to logout and then login.

**Comment by invincibleJai** [comment]
I have observed it once, it occurs when sockets won't give any response @jyasveer is working with @gastaldi on SSE once that is tested should resolve this.

**Comment by jyasveer** [comment]
Discussions are going on for this. Currently we are trying out other approaches other than WebSocket which would take care of of the multi pod support.

**Comment by gastaldi** [comment]
Just an update (probably does not belong to this issue): We're not going to migrate to Server Side Events. I don't know what is the relation of this bug with WebSockets x SSE. 

This needs to be investigated, as it seems to be a UI bug.

**Comment by jyasveer** [comment]
Ahh my bad. i saw the comment before and replied to it.
This was a known issue and the fix is here https://github.com/fabric8-ui/fabric8-ui/pull/2742

**Comment by jyasveer** [comment]
@ldimaggi fixes are available in prod now. can you please verify and close this. thanks

**Comment by jyasveer** [comment]
closing this for now. please reopen if the issue persists.
