### ISSUE TITLE
Duplicated "Create new space" header

### ISSUE THREAD

**Issue by bartoszmajsak** [openshiftio/openshift.io#301]
When creating new space from the **Profile**, modal has double "Create new space" label.

![image](https://user-images.githubusercontent.com/719616/27677169-081e8bde-5cb1-11e7-968c-79635be273a8.png)

It seems that first one is part of `<h4 class="modal-title">Create new space</h4>` and the other is nested in `<space-creator>`.

Chrome v59.0.3071.104

**Comment by joshuawilson** [comment]
This issue was moved to fabric8-ui/fabric8-ui#1627

**Comment by joshuawilson** [comment]
Fixed in https://github.com/fabric8-ui/fabric8-ui/pull/1636
