### ISSUE TITLE
Nav prototypes: View all spaces (3)

### ISSUE THREAD

**Issue by Essjaysee** [openshiftio/openshift.io#3010]
- [x] Update the centered nav prototype according to the designs: https://redhat.invisionapp.com/share/Z3GA73GQ5DC#/269795045_3_Homespace  and https://redhat.invisionapp.com/share/Z3GA73GQ5DC#/269795048_5_Spaceplan2
- [x] Double-check that all prototypes use the same icon to indicate individual space and the same icon to indicate view all spaces
- [ ] Take a screenshot of a spaces list page
- [ ] Link to it from the view all spaces/view more spaces/view spaces links/icons in all 3 prototypes

**Comment by mindreeper2420** [comment]
The icon for "View All Spaces" is `fa-th` (https://fontawesome.com/v4.7.0/icon/th/).

The icon for individual Spaces is `fa-th-large` (https://fontawesome.com/v4.7.0/icon/th-large/).
