### ISSUE TITLE
Nav prototypes: Search (5)

### ISSUE THREAD

**Issue by Essjaysee** [openshiftio/openshift.io#3011]
- [x] In left-hand nav prototype, add slide-out animation that reveals the search bar
- [x] In mega-menu prototype, double-check the colors used in the search box(the text seems really dark)
- [x] In centered nav prototype, add animation that slides the search open when the search icon is clicked

**Comment by mindreeper2420** [comment]
Leftnav updated: 
![screen shot 2018-06-04 at 1 56 16 pm](https://user-images.githubusercontent.com/4032718/40933329-1a7f1712-67ff-11e8-9979-66554e5fa85d.png)

**Comment by Essjaysee** [comment]
These are done.
