### ISSUE TITLE
Nav prototypes: Animation in Centered Nav (5)

### ISSUE THREAD

**Issue by Essjaysee** [openshiftio/openshift.io#3014]
- [x] Add animation for the various items to slide across (ltr/rtl) the header when they're selected in the centered nav prototype

**Comment by Essjaysee** [comment]
@mindreeper2420 and @bdellasc spoke about this today and plan to work together on it.

**Comment by bdellasc** [comment]
Met with @mindreeper2420 , @Essjaysee , @mceledonia on current state of prototype. Here's the to-do list coming out of that meeting. We'll regroup when Adam has something new to show:

**Notes on Centered Nav**:
- [ ] Remove carat & pipe from user piece. No menu under user when it’s not the focus
- [ ] Add carat to space icon
- [ ] No accompanying text when a section is not the focus
- [ ] Differentiate the background between nav bar and the dashboard top bar

**Comment by bdellasc** [comment]
@mindreeper2420 added the changes in the notes above. Animation ended up being a something we couldn't accomplish for Summit.
