### ISSUE TITLE
Nav prototypes: Space name (3)

### ISSUE THREAD

**Issue by Essjaysee** [openshiftio/openshift.io#3015]
UI Implementation into prototype of the following:

- [x] In the left-hand nav, add the space name to the space selector at the top (when you're in the context of the space)

**Comment by mindreeper2420** [comment]
@Essjaysee I've updated the space selector to show the appropriate name based on context: https://rawgit.com/mindreeper2420/leftnav-prototype/master/index.html

**Comment by Essjaysee** [comment]
I think this may need a tweak.  The screen I was referring to in Invision showed the space name here:

![screen shot 2018-06-29 at 4 18 08 pm](https://user-images.githubusercontent.com/3267889/42113089-2073e2c0-7bb8-11e8-9770-194d621f4229.png)

And this is where I'm seeing it:

![screen shot 2018-06-29 at 4 18 13 pm](https://user-images.githubusercontent.com/3267889/42113119-2b9e5b4e-7bb8-11e8-958a-c5d9506e216e.png)

unless I'm misinterpreting.
