### ISSUE TITLE
Nav prototypes: Dummy screen shots (5)

### ISSUE THREAD

**Issue by Essjaysee** [openshiftio/openshift.io#3016]
- [x] Come up with a set of space names, work item names, and user names to show in the dummy screen shots
- [x] Make the home dashboard show those things
- [x] Decide which menu items we're going to link to (Deployments w/ feature flags was mentioned today, user profile/settings page, first screen of create space)
- [x] Create space screen cap needs fade-in animation
- [x] Take screen shots (desktop)
- [x] Take screen shots (mobile)
- [x] Link these to the menu items in all 3 prototypes

**Comment by mindreeper2420** [comment]
Screen resolution for test environment will be 1366x768.

**Comment by mindreeper2420** [comment]
**Home Dashboard**
<img width="1357" alt="homedashboard" src="https://user-images.githubusercontent.com/4032718/39156522-85bb02ee-4724-11e8-84e2-86c8a1ffb25a.png">

**Space Dashboard (Analyze tab)**
<img width="1353" alt="spacedashboard" src="https://user-images.githubusercontent.com/4032718/39156563-b40dc1c2-4724-11e8-8b87-bd76c70968e9.png">

**Plan**
<img width="1369" alt="planner" src="https://user-images.githubusercontent.com/4032718/39156575-c9d6f33e-4724-11e8-8630-e70d3d78cf99.png">

**Create**
<img width="1367" alt="create" src="https://user-images.githubusercontent.com/4032718/39156587-dba3f27e-4724-11e8-8ea3-11ca5464cd58.png">

**Space Settings (Areas)**
<img width="1367" alt="spacesettings" src="https://user-images.githubusercontent.com/4032718/39156670-38e3768a-4725-11e8-8e93-901bf05b725f.png">

**View All Spaces**
<img width="1367" alt="viewallspaces" src="https://user-images.githubusercontent.com/4032718/39156714-78b27d2e-4725-11e8-8644-23d08996552a.png">

**User Settings (under user profile today)**
<img width="1366" alt="usersettings" src="https://user-images.githubusercontent.com/4032718/39156737-8fb0eb82-4725-11e8-864f-bfd79c2cbc03.png">

**Comment by mindreeper2420** [comment]
I also have the notification drawer added to the prototype. It slides in from the right when you click on the bell icon in the navbar.

<img width="1366" alt="screen shot 2018-04-23 at 6 44 51 pm" src="https://user-images.githubusercontent.com/4032718/39156940-6ecd6ca0-4726-11e8-81fe-ba03d2d6694e.png">
