### ISSUE TITLE
Bug: No /stack-analysis results for known stack 

### ISSUE THREAD

**Issue by luebken** [openshiftio/openshift.io#302]
I started a stack analysis for https://github.com/openshiftio-vertx-boosters/vertx-http-booster

The results seem broken:
``` 

curl -sH "Authorization: Bearer $OSIO_TOKEN" $API/stack-analyses/74703fe130004ce2aef674c4dd0dcb48
{
    "finished_at": "2017-06-29T10:59:10.516466",
    "recommendation": {
        "recommendations": {
            "component_level": null,
            "similar_stacks": []
        }
    },
    "request_id": "74703fe130004ce2aef674c4dd0dcb48",
    "result": [
        {
            "_audit": {
                "ended_at": "2017-06-29T10:59:10.516466",
                "started_at": "2017-06-29T10:59:10.494493",
                "version": "v1"
            },
            "_release": "None:None:None"
        }
    ],
    "schema": {
        "name": "stack_analyses",
        "url": "http://recommender.api.openshift.io/api/v1/schemas/api/stack_analyses/2-1-4/",
        "version": "2-1-4"
    },
    "started_at": "2017-06-29T10:59:10.494493"
}
```

**Comment by joshuawilson** [comment]
This issue was moved to fabric8-ui/fabric8-recommender#248

**Comment by joshuawilson** [comment]
@luebken I'm not sure who would work/own this. If it should go to a different repo, please let me know.

**Comment by luebken** [comment]
@joshuawilson Me neither. I'm only tracking my issues in this repo.

**Comment by invincibleJai** [comment]
@luebken tried recreating , have used same manifest file as yours https://github.com/invincibleJai/test-my-space19/blob/master/pom.xml

for this build in OSIO I was able to get recommendations as below , am i missing something here ??

curl -sH "Authorization: Bearer $STACK_API_TOKEN" https://recommender.api.openshift.io/api/v1/stack-analyses/b0e69d2876c44c5aacc5b7d38f400509

`{
    "finished_at": "2017-07-10T07:13:43.832196",
    "recommendation": {
        "recommendations": {
            "component_level": null,
            "similar_stacks": [
                {
                    "analysis": {
                        "missing_packages": [
                            {
                                "ch.qos.logback:logback-core": "1.2.3"
                            }
                        ],
                        "version_mismatch": [
                            {
                                "io.vertx:vertx-web": "3.4.1"
                            },
                            {
                                "io.vertx:vertx-core": "3.4.1"
                            }
                        ]
                    },
                    "similarity": 0.6599666666666667,
                    "source": "manually curated",
                    "stack_id": "cca357b72bb544f5908f62e186a5f6ac",
                    "stack_name": "Vert.x HTTP Booster",
                    "usage": 1.0
                }
            ]
        }
    },
    "request_id": "b0e69d2876c44c5aacc5b7d38f400509",
    "result": [
        {
            "_audit": {
                "ended_at": "2017-07-10T07:13:43.832196",
                "started_at": "2017-07-10T07:13:43.770632",
                "version": "v1"
            },
            "_release": "None:None:None",
            "analyzed_components": 2,
            "components": [
                {
                    "code_metrics": {
                        "average_cyclomatic_complexity": 1.23,
                        "code_lines": 38271,
                        "total_files": 240
                    },
                    "ecosystem": "maven",
                    "github_details": {
                        "forks_count": -1,
                        "issues": {
                            "month": {
                                "closed": -1,
                                "opened": -1
                            },
                            "year": {
                                "closed": -1,
                                "opened": -1
                            }
                        },
                        "pull_requests": {
                            "month": {
                                "closed": -1,
                                "opened": -1
                            },
                            "year": {
                                "closed": -1,
                                "opened": -1
                            }
                        },
                        "stargazers_count": -1
                    },
                    "id": "maven:io.vertx:vertx-web:3.4.2",
                    "latest_version": "3.4.1",
                    "licenses": [
                        "Apache 2.0",
                        "EPL 1.0"
                    ],
                    "name": "io.vertx:vertx-web",
                    "redhat_usage": {
                        "all_rhn_channels": [],
                        "all_rhsm_content_sets": [],
                        "all_rhsm_product_names": [],
                        "package_names": [],
                        "published_in": [],
                        "registered_srpms": [],
                        "rh_mvn_matched_versions": []
                    },
                    "security": {},
                    "version": "3.4.2"
                },
                {
                    "code_metrics": {
                        "average_cyclomatic_complexity": 1.33,
                        "code_lines": 82656,
                        "total_files": 446
                    },
                    "ecosystem": "maven",
                    "github_details": {
                        "forks_count": -1,
                        "issues": {
                            "month": {
                                "closed": -1,
                                "opened": -1
                            },
                            "year": {
                                "closed": -1,
                                "opened": -1
                            }
                        },
                        "pull_requests": {
                            "month": {
                                "closed": -1,
                                "opened": -1
                            },
                            "year": {
                                "closed": -1,
                                "opened": -1
                            }
                        },
                        "stargazers_count": -1
                    },
                    "id": "maven:io.vertx:vertx-core:3.4.2",
                    "latest_version": "3.4.1",
                    "licenses": [
                        "Apache 2.0",
                        "EPL 1.0",
                        "MIT License"
                    ],
                    "name": "io.vertx:vertx-core",
                    "redhat_usage": {
                        "all_rhn_channels": [],
                        "all_rhsm_content_sets": [],
                        "all_rhsm_product_names": [],
                        "package_names": [],
                        "published_in": [],
                        "registered_srpms": [],
                        "rh_mvn_matched_versions": []
                    },
                    "security": {},
                    "version": "3.4.2"
                }
            ],
            "distinct_licenses": [
                "Apache 2.0",
                "EPL 1.0",
                "MIT License"
            ],
            "ecosystem": "maven",
            "manifest_name": "pom.xml",
            "popularity": {
                "average_forks": "NA",
                "average_stars": "NA",
                "low_popularity_components": 0
            },
            "total_licenses": 3
        }
    ],
    "schema": {
        "name": "stack_analyses",
        "url": "http://recommender.api.openshift.io/api/v1/schemas/api/stack_analyses/2-1-4/",
        "version": "2-1-4"
    },
    "started_at": "2017-07-10T07:13:43.770632"
}`

**Comment by luebken** [comment]
@invincibleJai please format the output it's hard to read.

But the bug could be fixed meanwhile.

**Comment by invincibleJai** [comment]
@luebken sorry it was bit large , have created a gist https://gist.github.com/invincibleJai/6cb6039381e75ed20b7aebafb3c878d1

**Comment by luebken** [comment]
@invincibleJai looks like this bug is fixed. But please note that the recommendations section should be empty according to Test-1704E516-01 https://docs.google.com/spreadsheets/d/1ULvQzG1YZk1TwU3KaqiMXiD4FBGpmOLO0jqybE6Y7tk/edit#gid=2133453270

**Comment by invincibleJai** [comment]
@luebken thanks , will look into this.

**Comment by samuzzal-choudhury** [comment]
@luebken during the summit demo, one additional component "ch.qos.logback:logback-core 1.2.3" was added to the stack "Vert.x HTTP Booster" which is recommended as a missing component in the response.

Also, the version mismatch in the recommendation is because of the fact that the reference stack has got dependencies io.vertx:vertx-web/3.4.1 and io.vertx:vertx-core/3.4.1 whereas your pom.xml is configured with the version 3.4.2.

![image](https://user-images.githubusercontent.com/17740190/28209378-ea5ea3da-68af-11e7-8999-12c81009b1d2.png)

So, the recommendation is perfect in your case.

I am closing this issue. Please feel free to reopen if you think otherwise.

**Comment by samuzzal-choudhury** [comment]
@joshuawilson I can't close an issue here. Would you please do that for me?

**Comment by luebken** [comment]
If you close this issue please open a new one for  https://github.com/openshiftio/openshift.io/issues/302#issuecomment-314066880 

The recommendation of adding a new dependency (e.g. ch.qos.logback:logback-core 1.2.3) on a fresh booster stack is generally wrong. Even if that has been showed in some demo.

**Comment by miteshvp** [comment]
@luebken @samuzzal-choudhury - done all the necessary changes in the back-end. Can you test this and let me know it works as expected. Thanks in advance.

**Comment by samuzzal-choudhury** [comment]
@miteshvp I find this working for me. @luebken can you try this out?

**Comment by joshuawilson** [comment]
I'm closing this as requested. @luebken if you still need it, re-open it.
