### ISSUE TITLE
Better error reporting is needed if a build fails at roll out to stage step due to the user being over quota

### ISSUE THREAD

**Issue by jarifibrahim** [openshiftio/openshift.io#3024]
On production, the build failed at roll out to stage. Here's[0] the log

```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default/api/v1/namespaces/ijarif-stage/services. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. services "app-test-1" is forbidden: exceeded quota: object-counts, requested: services=1, used: services=5, limited: services=5.
```
[0] - https://jenkins.openshift.io/job/jarifibrahim/job/clickParty1/job/master/1/console

**Comment by ldimaggi** [comment]
The error message has the answer in it - your account is over quota.

**Comment by ldimaggi** [comment]
Are you requesting a better way to provide this error message to the user?

**Comment by jarifibrahim** [comment]
@ldimaggi There should be better error reporting. A would user would never be able to figure out how/why the quota error was thrown.

**Comment by piyush1594** [comment]
@jarifibrahim @ldimaggi Seems like this is duplicate of #3346 Can we close this as the other one has more visibility and work is going on there?

**Comment by jarifibrahim** [comment]
@piyush1594 The error I saw was `Forbidden!Configured service account doesn't have access`. I don't think this is related to https://github.com/openshiftio/openshift.io/issues/3346

**Comment by piyush1594** [comment]
@jarifibrahim If you see the error 

```
 services "app-test-1" is forbidden: exceeded quota: object-counts, requested: services=1, used: services=5, limited: services=5.
```

This is about exceeded quota limits

**Comment by jarifibrahim** [comment]
Thanks @piyush1594. It looks like a duplicate of https://github.com/openshiftio/openshift.io/issues/3346

Closing this one.
