### ISSUE TITLE
Adding label in quick preview and opening detail page throws error "There was problem adding label"

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3028]
![label](https://user-images.githubusercontent.com/34271052/38658989-f60ffede-3e44-11e8-8928-72de52dd33f1.gif)

**Comment by jarifibrahim** [comment]
I was able to reproduce this error.

**Comment by nimishamukherjee** [comment]
On the UI, if we follow the steps mentioned above, an additional POST call on labels is made when we navigate from quick preview to detail page

**Comment by Raunak1203** [comment]
Issue is fixed with PR https://github.com/fabric8-ui/fabric8-planner/pull/2675
