### ISSUE TITLE
Clicking on analyze multiple times when coming from planner distorts the toobar

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#3029]
1. Open Planner
2. Now click on analyze
3. Get frustrated while it loads, click a second time
4. Click a third time for good measure

<img width="1654" alt="screen shot 2018-04-12 at 11 52 02 am" src="https://user-images.githubusercontent.com/5445560/38659700-3a5a3b74-3e48-11e8-8924-86ffc5b590eb.png">

**Comment by nimishamukherjee** [comment]
@sahil143 are you able to replicate this issue? I'm not able to replicate this issue.

**Comment by sahil143** [comment]
@nimishamukherjee No, I'm not able to reproduce this issue on prod.

**Comment by corinnekrych** [comment]
@nimishamukherjee I think this is a duplicate of https://github.com/openshiftio/openshift.io/issues/2339

**Comment by joshuawilson** [comment]
closing duplicate
