### ISSUE TITLE
new users does not get che + jenkins setup

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#303]
issue at https://github.com/fabric8-ui/fabric8-ui/issues/1606

means new users don't have the right setup is thus a blocker.

**Comment by jstrachan** [comment]
this is the underlying issue https://github.com/fabric8io/fabric8-init-tenant/issues/122

**Comment by aslakknutsen** [comment]
Fixed by https://github.com/fabric8io/fabric8-init-tenant/pull/144
