### ISSUE TITLE
Faced a capacity issue while at Click Party 

### ISSUE THREAD

**Issue by ashmitha7** [openshiftio/openshift.io#3031]
![screenshot from 2018-04-12 11-27-19](https://user-images.githubusercontent.com/28265276/38659868-e4bb9f2c-3e48-11e8-896a-efb63450c045.png)

Followed all the steps mentioned in the google doc for using OSIO - https://docs.google.com/document/d/1KDx05WAk5omKXi7OosRfDTMRDorOt1k6iJrozWWRKZ4/edit

Was facing a build issue (It was starting and could not view any logs) so tried to view the status in OSO and found that there is no capacity.
This is the first space I have ever created.

**Comment by aslakknutsen** [comment]
east-1 is not a OSiO Cluster. We have east-2 and 2a.

**Comment by aditya-konarde** [comment]
I agree with @aslakknutsen here. We don't use the `starter-us-east-1` cluster for OSIO. 

@ashmitha7 if you have the logs or can reproduce failing builds, please add in a separate issue.
