### ISSUE TITLE
Wildfly health check booster build fails with possible out of memory error

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#3032]
```
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ app-test-1 ---
[INFO] Surefire report directory: /home/jenkins/workspace/sio-test-click-party_master-Z7C62X3AW7O2EYBYU4AVW6CCDBSDAZOLTAIXKZ6S53XOMGQQM5RQ/target/surefire-reports
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.openshift.boosters.GreetingServiceTest
Resolving 665 out of 896 artifacts
Picked up _JAVA_OPTIONS: -Duser.home=/root/ -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
Thu Apr 12 06:05:14 UTC 2018 INFO [org.wildfly.swarm.bootstrap] (main) Dependencies not bundled; resolving from M2REPO.
/home/jenkins/workspace/sio-test-click-party_master-Z7C62X3AW7O2EYBYU4AVW6CCDBSDAZOLTAIXKZ6S53XOMGQQM5RQ@tmp/durable-3f2c788a/script.sh: line 2:    93 Killed                  mvn clean -B -e -U deploy -Dmaven.test.skip=false -P openshift
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 137
Finished: FAILURE
```

I did "reset environment" before I ran this.

**Comment by animuk** [comment]
Duplicate issue :https://github.com/fabric8-launcher/launcher-booster-catalog/issues/189

**Comment by animuk** [comment]
known issue. degrading to sev3

**Comment by animuk** [comment]
Known issue
reference issue: #3134
Updates from the wildflyswarm team : There will be no release of WF Swarm Boosters based on 7.1.0 until the end of May, any environment, anywhere
Only the community boosters have this fix, it's only the product boosters that are affected

**Comment by kenfinnigan** [comment]
They already are:
https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-health-check-redhat/tree/7.1.0-redhat-1
https://github.com/fabric8-launcher/launcher-booster-catalog/blob/master/wildfly-swarm/redhat/health-check/booster.yaml

**Comment by bartoszmajsak** [comment]
Thanks @kenfinnigan, the reason I asked is that the issue was closed on 31st of May whereas those updates happened 2 weeks earlier. I also recall 31st being mentioned on several issues - hence the ask.

Moreover with the `7.1.0-redhat-1` we are still facing hanging tests on OSIO which work perfectly fine with the community version so I wonder if there is another issue.

**Comment by bartoszmajsak** [comment]
We are going to stick with the community versions hence closing this issue as it's related to a particular version of the runtime and OSIO infra.
