### ISSUE TITLE
No stages started in any of the recent runs 

### ISSUE THREAD

**Issue by ashmitha7** [openshiftio/openshift.io#3033]
![screenshot from 2018-04-12 12-00-47](https://user-images.githubusercontent.com/28265276/38659969-4988c9a2-3e49-11e8-8f07-7df5296a9755.png)

It took forever to assign a jenkin's slave, no stages started and eventually it all failed. Blocked at this point.

**Comment by ldimaggi** [comment]
Can you retry this now? And - watch the Jenkins pod log - perhaps this was caused by resource contention with many people performing builds at the same time?

**Comment by rohanKanojia** [comment]
Let me try to reproduce

**Comment by rohanKanojia** [comment]
@piyush1594 : Sorry but I'm not getting what you're saying. Perhaps you could elaborate on how this is duplicate of #3095 .

**Comment by ravsa** [comment]
@rohanKanojia two builds have started one with the ApplicationName `app-test-1` and another one with repository name `OSIO-clickParty-2`

**Comment by ravsa** [comment]
It's happening because of `applicationName !- githubRepoName`

**Comment by rohanKanojia** [comment]
@ravsa : ah, cool. Thanks. I think we can close it then.

**Comment by piyush1594** [comment]
Duplicate of #3095

**Comment by rohanKanojia** [comment]
Closing as duplicate

**Comment by rohanKanojia** [comment]
@ashmitha7 @ldimaggi : Just sharing my reproduction attempt. I tried to reproduce it but Jenkins slave came up on time. 
![screenshot from 2018-04-27 13-17-11](https://user-images.githubusercontent.com/13834498/39351003-90c1db26-4a1d-11e8-97f9-a07a08abb8e0.png)

**Comment by piyush1594** [comment]
@rohanKanojia This happens in new Launcher UI, not the legacy UI which I think you are using

**Comment by rohanKanojia** [comment]
How can I access launcher UI?

**Comment by ldimaggi** [comment]
In your account "Settings" - under opt-in, select Beta and you will see the new launcher.
