### ISSUE TITLE
Failed to login to Jenkins

### ISSUE THREAD

**Issue by ashmitha7** [openshiftio/openshift.io#3034]
![screenshot from 2018-04-12 11-49-55](https://user-images.githubusercontent.com/28265276/38660183-fcdb1406-3e49-11e8-93da-7349edc7e02d.png)

My build was released and 'roll out to stage' took 10 sec after this in the 'approve' state, I clicked on 'Input required' and the 'promote' option would not work. Eventually, the screenshot is the error I received when trying this twice.

**Comment by ldimaggi** [comment]
Is this problem reproducible now?

**Comment by rohanKanojia** [comment]
Possible duplicate of #3026

**Comment by joshuawilson** [comment]
closing duplicate
