### ISSUE TITLE
continues page reload loop

### ISSUE THREAD

**Issue by debianmaster** [openshiftio/openshift.io#304]
Goto:  https://openshift.io/cjonagam-io/_spaces     `replace cjonagam-io` with your yousername

and click `New` button   page goes into infinite loop of   Reload -> New -> Reload

**Comment by joshuawilson** [comment]
This issue was moved to fabric8-ui/fabric8-ui#1628

**Comment by joshuawilson** [comment]
Fixed in https://github.com/fabric8-ui/fabric8-ui/pull/1713
