### ISSUE TITLE
App never deployed on stage and run environment

### ISSUE THREAD

**Issue by nurali-techie** [openshiftio/openshift.io#3040]
**Issue:**
After successful completion of build pipeline, app didn't deployed, neither on stage nor on run environment.

**Steps:**
In Click Party Bangalore, I created space, created app and pipeline triggered automatically.  After successful completion of build for pipeline, I was expecting that the app will be deployed on stage and run environment but app deployment not happened after 15 mins also.

The issue has happened around 10:45 IST to 11:10 IST on 12-april-2018.

Below is the link where app should have been deployed.
stage - http://node-manager-nvirani-1-stage.8a09.starter-us-east-2.openshiftapps.com/
run - http://node-manager-nvirani-1-run.8a09.starter-us-east-2.openshiftapps.com/

**Other details:**
User - nvirani@redhat.com
Space - avatar
App - node-manager

**Comment by ldimaggi** [comment]
Are you able to recreate this issue? The build log and Jenkins pod log might provide some clues to the causes of the delay.

**Comment by nurali-techie** [comment]
The issue has happened around 10:45 IST to 11:10 IST on 12-april-2018.
Let me know if you want me to re-trigger the pipeline for the app to re-try deployment.

**Comment by jiekang** [comment]
Can you provide screenshots of pipelines page, build and pod logs and screenshots of OSO stage/run project consoles?

**Comment by andrewazores** [comment]
Related / same bug? https://github.com/openshiftio/openshift.io/issues/2985

**Comment by miteshvp** [comment]
@nurali-techie - this looks like you are out of quota for the app to be deployed. Can you go to openshift console and paste the stage and run projects overview?

**Comment by nurali-techie** [comment]
@miteshvp yup my bad, I was checking resource quota for preview/default rather stage/run.  I have removed app from stage and run and re-trigger pipeline my my new app "node-manager" and now I can see it's coming up in stage and run.

Thanks for all the help and sorry for the trouble caused by my mistake.  Closing the issue.
