### ISSUE TITLE
Planner: Moving table attributes using gear icon distorts alignment of the list view columns

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#3041]
When you move attributes from Available to Displayed using the gear icon, the table columns in the list view get distorted. 
![screenshot from 2018-04-12 13-09-25](https://user-images.githubusercontent.com/16647625/38663098-84674d64-3e53-11e8-9a88-9f7ba1d130c5.png)
![screenshot from 2018-04-12 13-09-37](https://user-images.githubusercontent.com/16647625/38663106-891bd78a-3e53-11e8-9b27-c703dca1473c.png)
![screenshot from 2018-04-12 13-09-02](https://user-images.githubusercontent.com/16647625/38663114-8ef9700e-3e53-11e8-971c-3ed84c0aa7c3.png)

**Comment by xstefank** [comment]
Not sure if the same problem. Steps to reproduce:

* In Experiences tab create 3 items
* In Scenarios tab create 2 or less items
* In Experiences tab - Move some columns from Displayed to Available
* Switch to Scenarios
* Switch back to Experience
* Move the columns back to Displayed

![2018-04-12_1915x600](https://user-images.githubusercontent.com/9353101/38702921-277fb0c4-3ea2-11e8-9ada-a78d72830a63.png)

**Comment by nimishamukherjee** [comment]
@sahil143 try the following:
- deselect columns
- view the table
- add back the columns
- view the table
The columns are distorted.

**Comment by nimishamukherjee** [comment]
Fix is on prod. Please re-open if you face the issue.
