### ISSUE TITLE
Planner: Applying a filter overwrites labels 

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#3042]
To reproduce:

1. Click Experiences or Requirements in the left pane. Note this is not seen when you click Scenarios on the left pane.
2. Apply the work item type filter. 

This is what you will see:
![screenshot from 2018-04-12 14-13-12](https://user-images.githubusercontent.com/16647625/38666143-e4778874-3e5b-11e8-8b6b-4f03de040efc.png)
![screenshot from 2018-04-12 14-12-46](https://user-images.githubusercontent.com/16647625/38666171-f01eacc0-3e5b-11e8-8211-c122c421dfef.png)

A refresh, even a hard refresh failed to resolve this.

**Comment by miteshvp** [comment]
@nimishamukherjee - able to reproduce the same on chrome

**Comment by Preeticp** [comment]
Chrome @nimishamukherjee

**Comment by SMahil** [comment]
here is the PR for this issue : https://github.com/fabric8-ui/fabric8-planner/pull/2532

**Comment by Preeticp** [comment]
@SMahil I still see this behavior, hopefully it will be updated soon. However I also see another issue in the same scenario:
1. Click Experiences or Requirements in the left pane. Note this is not seen when you click Scenarios on the left pane.
2. Apply the work item type filter.
![screenshot from 2018-05-24 15-29-35](https://user-images.githubusercontent.com/16647625/40481628-9fd49f56-5f6f-11e8-9fdd-1fbd15af274b.png)
![screenshot from 2018-05-24 15-28-37](https://user-images.githubusercontent.com/16647625/40481637-a58021dc-5f6f-11e8-8829-a8e20d91ca1d.png)

The numbers displayed in the top right corner '1 in' should be 1 in Experiences/1 in Requirements to be consistent with the message in Scenarios where it says 1 in Scenarios. 
![screenshot from 2018-05-24 15-29-58](https://user-images.githubusercontent.com/16647625/40481662-b8189022-5f6f-11e8-969c-cf494963aac4.png)

However, we might want to reconsider the usage of the words 'in scenarios/Experiences/Requirements' too. It would probably be better to say 'n workitem(s)' only. Do we want to emphasize the WIT group here? The user can see the left pane as well as knows the filters he has chosen to apply.

**Comment by SMahil** [comment]
@Preeticp The text 1 in Experiences/1 in Requirements is overlapped with quick add which is fixed in the above-mentioned PR.
Afa the text 'n workitem(s)' is concerned, I think the current text makes better sense to me. Although we may reverify it with UX for better clarification

**Comment by Preeticp** [comment]
> @Preeticp The text 1 in Experiences/1 in Requirements is overlapped with quick add which is fixed in the above-mentioned PR.

Cool.

> Afa the text 'n workitem(s)' is concerned, I think the current text makes better sense to me. Although we may reverify it with UX for better clarification

I agree, let's check with UX. 
These are my 2 cents:
'1 in Scenarios' raises the question 1 'what' in my mind. 
Secondly, if we want to repeat Scenarios, Requirements etc., though the context is visible to the user, then we probably would be better off saying 'n work item(s) in Scenarios' something similar to:
![screenshot from 2018-05-25 12-04-03](https://user-images.githubusercontent.com/16647625/40529803-05b76098-6014-11e8-8824-fc24a9d8b682.png)
![screenshot from 2018-05-25 11-59-02](https://user-images.githubusercontent.com/16647625/40529812-0dc22516-6014-11e8-83ad-03ab061e31bc.png)

**Comment by SMahil** [comment]
This issue has been fixed in  prod
