### ISSUE TITLE
Migration to CHE workspace took more than 15 minutes

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#3043]
Steps : 
- create a new space
- Select new launcher flow
- Create codebase
- go through all steps
- trigger build
- go to dashboard 
- click create
- click codebases
- click open codebase

Migration to CHE workspace took more than 15 minutes, but it works.

<img width="1678" alt="screen shot 2018-04-12 at 10 53 01 am" src="https://user-images.githubusercontent.com/5129024/38667214-7b834170-3e5e-11e8-82da-a4e6fd962b87.png">

**Comment by invincibleJai** [comment]
@rgarg1 pls check labels if it's correct.

**Comment by ibuziuk** [comment]
@invincibleJai could you please share your openshift events ?
there might be infra related problems such as volume mount which makes the migration long-running.
Anyway, it is good that it was successful as I understand

**Comment by invincibleJai** [comment]
yes @ibuziuk it works just fine, it just took longer. Can't see any events though. Am I checking at the right place?

<img width="1594" alt="screen shot 2018-04-12 at 2 43 31 pm" src="https://user-images.githubusercontent.com/5129024/38667792-fccad44a-3e5f-11e8-9595-cfa587854a24.png">

**Comment by invincibleJai** [comment]
@ibuziuk thanks monitoring i checked it's blank there as well. This is what I can see here 

<img width="1680" alt="screen shot 2018-04-12 at 3 01 46 pm" src="https://user-images.githubusercontent.com/5129024/38668925-ae117b62-3e62-11e8-8b27-e472c8414020.png">

**Comment by ibuziuk** [comment]
@invincibleJai migration pods completed successfully, but still strange that there are no events which would explain long-running execution...

**Comment by ibuziuk** [comment]
Migration of workspaces from che5 to che6 have finished a few month ago. Closing
