### ISSUE TITLE
Creating new application stuck at "Working Through Setup"

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3045]
1) Reset my environment
2) Created a new space
3) Using the new launcher, selected REST API mission and the Spring Boot runtime 
4) Rest of the selections were the default
5) Clicking on _Set up application_ button resulted in nothing, except a wait spinner at the top of the page labeled "Working Through Setup"

![working thriugh setup](https://user-images.githubusercontent.com/28748448/38670097-82b2676c-3e65-11e8-9b97-7ffe96b90c0c.png)

Note 1: The wait spinner is at the top of the page, which is too far from the _Set up application_ button
Note 2: The text is also overlapping here as you can see in the screenshot.

**Comment by rgarg1** [comment]
Note 3: Cannot even cancel this through the X button on the top-right corner of the page. The button as no effect

**Comment by jyasveer** [comment]
Fix is here https://github.com/fabric8-ui/fabric8-ui/pull/2742

**Comment by jyasveer** [comment]
@rgarg1 fixes are available in prod now. can you please verify and close this issue.

**Comment by animuk** [comment]
@rgarg1 Closing this for now. If you experience again, you can reopen.
