### ISSUE TITLE
"Feature flags" with 'dev' flag set show up in prod

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#3048]
Only show flags that can be seen in online v

![screenshot from 2018-04-12 12-06-06](https://user-images.githubusercontent.com/132158/38674175-d7a8ef14-3e53-11e8-83f3-c4ccfccb32b0.png)

**Comment by corinnekrych** [comment]
After further discussion with @xcoulon we think it's better to remove the flag `restricted='dev'` and replace it by an implementation on `fabric8-toggles-service`. The proposal is to use a different strategy. Istead of using `enableByLevel` in admin ui, you will use `byUserEmail`. See https://github.com/openshiftio/openshift.io/issues/3116
We think this is a more robust and flexible approach to serve WIP feature.

Once #3116 is implemented, I'll use this ticket to migrate Adam's code to the new configuration and update the documentation (wiki page) accordingly.

**Comment by mindreeper2420** [comment]
@corinnekrych this sounds good - the Home Dashboard has already been merged to master, and the Space Dashboard is in PR. I believe those are the only two pieces that had the `restricted='dev'` flag.
