### ISSUE TITLE
Launcher: Space Path field entry overflows outside the space provided 

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#3049]
The entry in the Space Path field overflows the Application Information space, this could be a problem when we have big Space names.
![screenshot from 2018-04-12 10-51-16](https://user-images.githubusercontent.com/16647625/38675980-321ed210-3e77-11e8-8901-631fe1ad5985.png)

**Comment by invincibleJai** [comment]
@Preeticp this appears to be fixed, I tried can see as below 

<img width="1060" alt="screen shot 2018-04-13 at 2 26 24 pm" src="https://user-images.githubusercontent.com/5129024/38726092-c9babc42-3f26-11e8-9826-a72dfd8ed556.png">

Let me know if you still see this.

**Comment by Preeticp** [comment]
Is this on prod? 
I still see this, had I added one more word to the space name, I think it would spill over.
![screenshot from 2018-04-13 14-36-02](https://user-images.githubusercontent.com/16647625/38726543-14e9f556-3f28-11e8-9903-2170d73d2845.png)

**Comment by invincibleJai** [comment]
@sanketpathak can you see if you can reproduce it?

**Comment by sanketpathak** [comment]
@Preeticp @invincibleJai  I'm also not seeing this issue. I've tried in prod as well as Prod-preview, working fine for me

**Comment by animuk** [comment]
As not able to reproduce, closing this atm
