### ISSUE TITLE
UX request -- enabling che seems to be not very User friendly

### ISSUE THREAD

**Issue by debianmaster** [openshiftio/openshift.io#305]
As a first time user i found it difficult to locate the button to enable che in openshift.io.    
Not sure how but looks like if we can enable it by default or more UX friendly messaging should be done

**Comment by joshuawilson** [comment]
Are you referring to the "update tenant" button. If so, we plan to make it automatic or make it very obvious that it needs to be done.

**Comment by joshuawilson** [comment]
Closing. If this is still a concern, please reopen and be more specific.
