### ISSUE TITLE
No need for a caret on the work item tree leaves

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#3052]
If an item ahs no child element, why showing a caret to expand the item and then a `disabled` cursor when moving over it ? what about hiding the caret instead ?

**Comment by nimishamukherjee** [comment]
@sunilmalagi please answer.

**Comment by Veethika** [comment]
@xcoulon @nimishamukherjee 
Please follow up on the solution and let's close if resolved.

**Comment by nimishamukherjee** [comment]
@sunilmalagi @Veethika can you summarise what is the recommendation?

**Comment by rhopp** [comment]
I would also vote for removing the arrow, when the item is not expandable. I cannot agree with this sentence: `it was looking visually imbalanced and looked mis aligned`. To me, the screenshot without arrows seems completely normal. And I think this is pretty normal to not show the arrow, when the item is not expandable.

Few examples of how this is done in other applications:
Google material design:
![image](https://user-images.githubusercontent.com/1215011/43306557-dd87f5bc-917b-11e8-80b9-e0e7b6b59b68.png)
Eclipse IDE:
![image](https://user-images.githubusercontent.com/1215011/43306575-eb3ff790-917b-11e8-8560-5772ae412c9a.png)
VSCode:
![image](https://user-images.githubusercontent.com/1215011/43306604-fc55b9de-917b-11e8-82c8-f2b1c0c42bb7.png)
I don't see any arrows in non-expandable items there...

**Comment by sunilmalagi** [comment]
@nimishamukherjee @Veethika 
Our recommendation is to go with current design that is, showing with caret (enable them when there is child WI and disable when there is no child WI).

**Comment by nimishamukherjee** [comment]
Closing based on UX comment.
