### ISSUE TITLE
Confusing message in iteration page

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#3062]
After creating an iteration and selecting it, I should have no work item assigned to it yet, which is correct, but the page displays a confusing message: `14 in Iteration 1`, although I can't see any:

<img width="1279" alt="screenshot 2018-04-12 16 06 19" src="https://user-images.githubusercontent.com/178502/38682536-9eca2268-3e6b-11e8-9440-742ae4a53584.png">

**Comment by nimishamukherjee** [comment]
@sahil143 can we display the correct number?

**Comment by sahil143** [comment]
Fixed in PR https://github.com/fabric8-ui/fabric8-planner/pull/2569. Closing.
