### ISSUE TITLE
Unable to re-import github project after deleting workspace

### ISSUE THREAD

**Issue by bostrt** [openshiftio/openshift.io#3064]
I created workspace A, successfully imported a codebase from my github, then deleted the workspace. After creating workspace B, I'm not able to import that same codebase and I see error:

`The repository tomcat-static-hello has already a build config, please select another repo.`

When deleting a workspace, am I truly starting from a clean slate?

**Comment by qodfathr** [comment]
Likely related: #2191

**Comment by ibuziuk** [comment]
@bostrt was not able to reproduce ? Could you please re-try and provide details if you still facing this issue ?

**Comment by bostrt** [comment]
@ibuziuk I'm no longer seeing this issue.
