### ISSUE TITLE
Provide help for markdown syntax

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#3065]
A link to the documentation for the supported Markdown syntax would be helpful when editing the description or a comment on a work item

**Comment by nimishamukherjee** [comment]
@Preeticp do we have any help for markdown syntax?

**Comment by Preeticp** [comment]
No, not at the moment @nimishamukherjee . I will explore this.

**Comment by Preeticp** [comment]
@xcoulon can you please expand on this?
Are you asking for a help link to the supported markdown syntax in our User Guide - https://docs.openshift.io/user-guide.html#adding_description_to_a_work_item ?

**Comment by Preeticp** [comment]
@xcoulon as discussed on mail, as an immediate action point I have added the note below to the 'Adding Comment' (https://docs.prod-preview.openshift.io/user-guide.html#adding_comments_to_a_work_item) and 'Adding description' topics in the user guide(https://docs.prod-preview.openshift.io/user-guide.html#adding_description_to_a_work_item) via PR https://github.com/fabric8io/fabric8-online-docs/pull/271: 

NOTE: In addition to the standard markdown syntax (link:https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet), refer to these extensions (link:https://github.com/russross/blackfriday#extensions) for more information about the syntax.
You should see it in Prod once the docs are pushed to prod. 

For the UX related part of this issue - a direct help link from Description/Comments to Markdown documentation, I will raise a separate issue for this referring to this issue.

**Comment by Preeticp** [comment]
@rkratky, thanks, I was unaware of this help page. We can definitely change the first link to point to https://access.redhat.com/help/markdown.

For the extensions link, https://github.com/russross/blackfriday was used by @xcoulon as a library with a number of extensions, https://github.com/fabric8-services/fabric8-wit/blob/master/rendering/markdown.go#L12-L29
Tables for example weren't rendering properly using the normal syntax. Hence the additional mention of extensions link.

**Comment by rkratky** [comment]
> For the extensions link

@Preeticp I'm not sure I follow. Does OSIO support some special  MD extensions?

**Comment by xcoulon** [comment]
Blackfriday is a library that supports Markdown, but the "problem" with Markdown itself is that it was initially limited in term of supported syntax (eg: tables, etc.), so there have been several "flavors" of MD developed to enrich the syntax. Note that there's a work in progress to provide a "common markdown" to avoid the diversity of those flavours.
Back to BlackFriday: it is a good library that was easy to integrate in `fabric8-wit` since it's written in golang, and it supports a lot of features, which is why we chose it.

**Comment by xcoulon** [comment]
@Preeticp yes, this looks good to me, thanks!
