### ISSUE TITLE
Unable to delete pipelines

### ISSUE THREAD

**Issue by debianmaster** [openshiftio/openshift.io#307]
How to replicate:
Create -> Pipelines ->  Select pipeline -> Select `Delete` from Popup
EX:- https://openshift.io/cjonagam-io/test/create/pipelines 

Expected:
Pipeline should be deleted

Actual result:
Pipeline is not getting deleted nor any showing any acknowledgement.

**Comment by debianmaster** [comment]
This may be because of stale records.   should order of deleting of objection matter?

**Comment by joshuawilson** [comment]
The feature, to delete, has not be implemented yet.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8-services/fabric8-wit#1464

**Comment by joshuawilson** [comment]
Duplicate of https://github.com/fabric8-ui/fabric8-ui/issues/1355
