### ISSUE TITLE
Planner filter does not work right away

### ISSUE THREAD

**Issue by soltysh** [openshiftio/openshift.io#3070]
I'm trying to filter resources in the Backlog view by specifying Title and picking some name that exists and nothing actually happens. Only when I switch tabs on the left (Experiences and then back to Scenarios) the filtering is applied. The same applies to clearing the filters:
![image](https://user-images.githubusercontent.com/576341/38683480-da4dd51c-3e6d-11e8-92a8-d80ea2441df7.png)

**Comment by nimishamukherjee** [comment]
Closing this issue as the board view will be re-done completely.
