### ISSUE TITLE
Drag&Drop items on the planner does not persist item moving

### ISSUE THREAD

**Issue by soltysh** [openshiftio/openshift.io#3072]
I've created several items in the new list of Scenarios. I've moved some of them to open, in progress and resolved list (using drag&drop). Then I switch the tab to Experiences and back to Scenarios and all the items are back in the new list.

**Comment by nimishamukherjee** [comment]
@soltysh were the changes (open, in progress, etc) done on the board view?

**Comment by soltysh** [comment]
Yes, it was all done on the board view. The initial state looked like the one linked to https://github.com/openshiftio/openshift.io/issues/3070. Then I moved some cards to open, other to in progress, then I changed the panes on the left (Experiences, Requirements) and when I got back to Scenarios I was again presented with that linked image, which was quite unexpected, tbh.

**Comment by michaelkleinhenz** [comment]
Board view is now legacy and no longer part of production.
