### ISSUE TITLE
Cannot create "Experience" work item

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#3073]
Go to experiences
 click on the blue +
fill both entries:
![image](https://user-images.githubusercontent.com/1105127/38684011-0487344e-3e6f-11e8-8309-1cc849480582.png)

click on the  check button to create it
--> nothing happens in UI
there is an http 400 error in network:

> Request URL: https://api.openshift.io/api/spaces/7e21ba9c-7a62-4ca8-9098-7e67cbbdbef2/workitems
> Request Method: POST
> Status Code: 400 Bad Request
> Remote Address: 52.86.72.46:443
> Referrer Policy: no-referrer-when-downgrade
> Access-Control-Allow-Credentials: true
> Access-Control-Allow-Origin: https://openshift.io
> Access-Control-Max-Age: 600
> Content-Encoding: gzip
> Content-Length: 179
> Content-Type: application/vnd.api+json
> Date: Thu, 12 Apr 2018 14:32:27 GMT
> Set-Cookie: b2c7c4d8013d0faf3d6bc4a99018e01f=a643a74e73ff02658103e884556a935c; path=/; HttpOnly; Secure
> Vary: Origin
> Accept: application/json, text/plain, */*
> Accept-Encoding: gzip, deflate, br
> Accept-Language: en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7,es-US;q=0.6,es;q=0.5
> Authorization: Bearer ...
> Connection: keep-alive
> Content-Length: 187
> Content-Type: application/json
> Host: api.openshift.io
> Origin: https://openshift.io
> Referer: https://openshift.io/apupier@redhat.com/secondspace/plan/board?q=(space:7e21ba9c-7a62-4ca8-9098-7e67cbbdbef2%20$AND%20typegroup.name:Experiences)
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
> {data: {,…}}
> data
> :
> {,…}
> attributes
> :
> {system.state: "new", system.title: "a work item", system.description: "super description"}
> system.description
> :
> "super description"
> system.state
> :
> "new"
> system.title
> :
> "a work item"
> hasChildren
> :
> false
> relationships
> :
> {baseType: {}}
> baseType
> :
> {}
> type
> :
> "workitems"

**Comment by nimishamukherjee** [comment]
Closing this issue as the board view will be re-done completely.
