### ISSUE TITLE
UI is not responding anymore to any clicks

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#3075]
I have several errors in console log:

![image](https://user-images.githubusercontent.com/1105127/38684630-68736ec2-3e70-11e8-9aeb-2fa96b4549c3.png)
![image](https://user-images.githubusercontent.com/1105127/38684652-75a41e0c-3e70-11e8-8435-f39b6b58bc39.png)

**Comment by apupier** [comment]
if I go to the root page by hand, and click create space, the Ui is frozen with a slightly black transparent shape:
![image](https://user-images.githubusercontent.com/1105127/38684971-2ff53cfa-3e71-11e8-8f85-c5543bef012a.png)

**Comment by rhopp** [comment]
I'm also impacted by this (rhopp@redhat.com account). 
I've successfully reproduced this in incognito mode in chrome browser.
Also deleting cookies, resetiing environment, logging off and back in does not help.
We are basically stuck.

**Comment by joshuawilson** [comment]
This has been fixed. I had to do a hard refresh `ctl + shft + R` and under the network tab had to `disable cache`.
