### ISSUE TITLE
Same code base shown multiple times 

### ISSUE THREAD

**Issue by debianmaster** [openshiftio/openshift.io#308]
I started from scratch and created a booster springboot application.  
Screen now redirected to my app namespace. but code base is shown 3 times ( please see picture) 

<img width="708" alt="screen shot 2017-06-29 at 4 27 59 pm" src="https://user-images.githubusercontent.com/1439169/27714709-89938558-5ce7-11e7-8e89-807e59440dde.png">

fyi: i may have hit create button three times on booster creation screen

**Comment by aslakknutsen** [comment]
Related https://github.com/fabric8-services/fabric8-wit/issues/1294

**Comment by joshuawilson** [comment]
Closing as this should be fixed, please reopen if needed.
