### ISSUE TITLE
Avoid horizontal scrollbar by default when creating a scenario

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#3084]
![horizontalscrollbarbydefaultalthouttherearelotofspace](https://user-images.githubusercontent.com/1105127/38685892-524e69c8-3e73-11e8-8e27-26c9536057bc.png)

**Comment by ldimaggi** [comment]
Can you provide some context here? What is the bug? Thx!

**Comment by apupier** [comment]
the problem is that there is an horizontal scrollbar  (and so some information is hidden) although there is a lot of blank space.

**Comment by ppitonak** [comment]
duplicate of #2296
