### ISSUE TITLE
[~?] Plannner: Cannot expand out Scenario tree after navigating away and coming back

### ISSUE THREAD

**Issue by mattd72** [openshiftio/openshift.io#3085]
From the Scenario window, created test_scenario.  Underneath that created a test_experience.  Under the test_experience created a feature and a bug, with task for each.  Navigated away to Experiences tab.  Came back to Scenario tab and expand arrow beside the scenario is no longer active.

Created a new test_scenario_2 with test_experience_2 with test_bug_2, bug_task_2, test_feature_2, feature_task_2.  Went to Experiences tab, came back to Scenarios tab.  Now the arrow to expand test_scenario_2 is inactive.  I can expand the original test_scenario, but it lists the resources for test_scenario_2 underneath (test_experience_2, test_bug_2, but_task_2, test_feature_2, feature_task_2) instead of the resource created for Scenario 1.

![screen shot 2018-04-12 at 11 02 26 am](https://user-images.githubusercontent.com/1047546/38685937-2525359e-3e41-11e8-84b1-2666937159a8.png)

**Comment by nimishamukherjee** [comment]
@sahil143 can you replicate this issue? I tried and could not replicate the issue.

**Comment by sahil143** [comment]
@nimishamukherjee No, I'm not able to reproduce this on prod.

**Comment by michaelkleinhenz** [comment]
Can not be replicated. @rgarg1 will try it.

**Comment by rgarg1** [comment]
The issue cannot be reproduced by following the steps provided. Neither the expand arrow was seen disabled nor the work item parent relationship was mangled. 

@mattd72 Do you still see this issue? If yes, please provide us more information to reproduce it.

**Comment by michaelkleinhenz** [comment]
Can not be replicated.
