### ISSUE TITLE
Icons are not aligned in dropdown in planner

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#3086]
I noticed here but I think it is in several places

![notalignedicons](https://user-images.githubusercontent.com/1105127/38688151-a9f0a07e-3e78-11e8-98fd-d772837d18ad.png)

**Comment by Preeticp** [comment]
Are you referring to these drop-downs?
![screenshot from 2018-04-12 21-06-59](https://user-images.githubusercontent.com/16647625/38687996-9f58ed8e-3e95-11e8-82be-9f422dc02c50.png)
![screenshot from 2018-04-12 21-06-17](https://user-images.githubusercontent.com/16647625/38688012-aa389984-3e95-11e8-87a5-92928ab3822e.png)

**Comment by apupier** [comment]
yes, I provided the wrong screenshot :s

**Comment by SMahil** [comment]
https://github.com/fabric8-ui/fabric8-planner/pull/2560

**Comment by nimishamukherjee** [comment]
Fix in prod
