### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS when accessing builds on jenkins.openshift.io

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#3087]
![toomanyredirectswhenaccessingjenkinsinstanceeveniffinallyredirectedtojenkinsautomatically](https://user-images.githubusercontent.com/1105127/38686345-616bcbb6-3e74-11e8-9fc5-cfc88b3ef5d1.png)

it finally redirects to the correct place but this page shows up for few seconds

**Comment by sthaha** [comment]
This issue should be (almost) fixed with the recent changes to Jenkins image (see: https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/114) . I am going to close the issue. 

Kindly file a new one if you continue to face this issue.
