### ISSUE TITLE
[production] Using experimental quicklaunch, stale pipelines are generated when choosing non-default app name

### ISSUE THREAD

**Issue by mmclanerh** [openshiftio/openshift.io#3088]
Steps:
- enabled all internal/experimental features
- went through quickstart (new ui) added new workspace "clickparty0412b"
- quickstart prompts seemed to default to app-test-1 instead of clickparty0412b..  chose "shinytest1" for repo name.
- renamed app-test-1 field during one of the quicklaunch dialogs, to shinytest1
- ended up with 1 pipeline in openshift.io view but a mis-named + abandoned pipeline in openshift online console view

openshift online console view:
![image](https://user-images.githubusercontent.com/33727536/38686434-24f9b314-3e29-11e8-82d0-12d2a4dae1fe.png)

openshift.io view:
![image](https://user-images.githubusercontent.com/33727536/38686471-3cf6d15e-3e29-11e8-9cd9-5a9ed2a3ba38.png)

**Comment by invincibleJai** [comment]
@mmclanerh thanks Mike , so if am understanding it correctly osio is showing it correct only 1 pipelines but in os console you see 3 pipelines?

**Comment by invincibleJai** [comment]
it seems to be duplicate of https://github.com/openshiftio/openshift.io/issues/3095

**Comment by animuk** [comment]
since it is duplicate , I am closing this. will track #3095
