### ISSUE TITLE
Usability:   unable to locate application url from Che

### ISSUE THREAD

**Issue by debianmaster** [openshiftio/openshift.io#309]
After launching workspace for a Springboot application i did following steps
-> Build 
-> Run

Console shows my app is running on 8080  but i'm not able to locate URL which i can use for testing the application.    it be difficult to go openshift.com and then figure out what url  i need to use for testing.    A helper message which shows complete application url may be helpful

**Comment by ldimaggi** [comment]
You might have run into this issue:
https://github.com/fabric8-ui/fabric8-ui/issues/1619

The links displayed on the pipeline page will take you to the deployed app - but it requires some time until the app is reachable.

**Comment by joshuawilson** [comment]
@debianmaster are you having an issue from within Che or getting to Che?

**Comment by l0rd** [comment]
@debianmaster  the preview url for spring-boot run command has been fixed. Can we close that issue?

**Comment by benoitf** [comment]
closing as issue has been fixed.
