### ISSUE TITLE
Typo "Atrributes" in settings to add a work item scenario in Planner 

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#3090]
![typoatrributes](https://user-images.githubusercontent.com/1105127/38686850-97e89dee-3e75-11e8-9439-8d1780cfc7ad.png)

**Comment by nimishamukherjee** [comment]
@sahil143 please correct the use the correct spelling - "Attributes"

**Comment by nimishamukherjee** [comment]
Closing issue as it has been fixed on production.
