### ISSUE TITLE
Useless up/down arrow to "Add Assignee"

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#3092]
with a single name, it is fully visible no need of it and if it is just a one pixel thing, just increase size of the dialog

![uselessupdown](https://user-images.githubusercontent.com/1105127/38686950-db50a6e4-3e75-11e8-832a-f1df201a5415.png)

**Comment by nimishamukherjee** [comment]
@SMahil can we hide the arrows if there is only a single user?

**Comment by SMahil** [comment]
is this issue reproducible on Linux/windows only?

**Comment by SMahil** [comment]
PR: https://github.com/fabric8-ui/fabric8-planner/pull/2561

**Comment by rgarg1** [comment]
LGTM @SMahil
