### ISSUE TITLE
OSIO asks me to Log in at odd times in the workflow

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#3096]
Example:  Today I started a new workspace, then clicked the link to go view the Build Pipeline-- this resulted in a trip to the Log In screen.
Can we please reduce the workflow to only 1 Log in?

**Comment by alexeykazakov** [comment]
View build pipeline where? openshift.io buiild/view tab? Jenkins? OpensShift console?
Need more details :)

**Comment by RickJWagner** [comment]
Hi @catrobson,
I can't reproduce, unfortunately.  (But this is not an uncommon bug for me to hit, I've seen it several times.)
Related thought:  It's difficult to remember the exact (and complete) series of clicks that lead to some particular bug.  I wish I had a good way to record (or find) my click trail so I'd have a better chance of reproducing bugs.  Any suggestions?
Thanks,
Rick

**Comment by sbose78** [comment]
From what I am aware of - whenever a request from the UI ends up with a 401 response, the UI logs out the user and sends him to the login page. So, if you can open the Developer console --> Network, and record the requests, you might be able to catch something.

CC: @rohitkrai03

**Comment by muruGanesan** [comment]
@RickJWagner,  
Thanks for your inputs. I understood your points.
IMO: this is a technical (implementation) issue.
If we know the exact scenario then we may propose an alternate UX flow.
Question: who should review & fix this issue? 

CC:@joshuawilson, @catrobson  @serenamarie125

**Comment by sbose78** [comment]
This couldn't be reproduced. Please re-open if you see this again @RickJWagner .
