### ISSUE TITLE
"Start Coding" button to seamlessly start coding from a Work Item

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#310]
# Description
As a user, I want to go seamlessly from a logged issue to the sourcecode with the intention of directly being able to work on resolving that issue.

# Acceptance Criteria
- [ ] In the Planner, in the detail view, there is a function that links to the Che workspace associated with the current project.
- [ ] Activating that link opens a new window that loads the associated Che workspace, with the associated codebase, at a specific path.
- [ ] The metadata for adressing the workspace, codebase, and path is stored either on the specific Work Item or on the Area of the Work Item, with the Work Item metadata taking precedence.
- [ ] The metadata is part of the stored data of the Space and can be created and updated like any other entity. For example, Analytics can create a new Work Item using the API, submitting the metadata along with the Work Item creation.

**Note**: The functionality at some point will extend to beyond the Planner detail view, enabling the "Start Coding" button being available in other locations. The implementation should reflect this.
 
# Relationships
_Put linked Team/Product story links here_

**Comment by ldimaggi** [comment]
Just to confirm - the user would add this metadata to the workitem that identifies the bug? (metadata for adressing the workspace, codebase, and path)

**Comment by qodfathr** [comment]
I propose closing this issue in favor of the more complete Experience outlined in #2715.
