### ISSUE TITLE
Import code base attempt gives 404 error

### ISSUE THREAD

**Issue by sudsen** [openshiftio/openshift.io#3100]
I tried to import a codebase but can't see the modal where I could paste the Github URL and import as repository. Rather it takes to a 404 if I follow a particular path. 

Steps to reproduce - 
1. Go to a space page - `https://openshift.io/{username}/{spacename}`
2. Click on `Import Codebase` - It goes to `/(action:add-codebase)`
3. Nothing happens 
4. Next try the `+` button in the corner of that widget. It goes to - `(create/(action:add-codebase)//action:add-codebase)` with 404

**Comment by catrobson** [comment]
Thanks @joshuawilson.  We do want to remove this option and change this to be "Create an Application" which will open the launcher experience where users can add just codebases, or applications that have pipelines and deployment capabilities built into them as well.
