### ISSUE TITLE
Manually deleting/starting Builds doesn't work smoothly

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#3101]
Noticed Build2 wasnt working, so deleted it (and Build 3).  Tried to manually start a Pipeline, it added Build 4 but it didn't start.
![buildwontstart](https://user-images.githubusercontent.com/524520/38688273-4741f9c6-3e3e-11e8-8af4-fa6307067bfc.png)

**Comment by piyush1594** [comment]
hey @RickJWagner 

I just tried to reproduce this and it works fine for me. Can you please check and if everything is fine. Can you please close? cc @sthaha 

Thanks

**Comment by RickJWagner** [comment]
Unreproduceable.  Let's hope there is no bug and everything works.

**Comment by piyush1594** [comment]
Thanks @RickJWagner
