### ISSUE TITLE
Slick new workspace wizard doesn't allow scrolling to completion button

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#3102]
Using new setup wizard, could not scroll to action button (Had to refresh screen, then I could use down arrow button to scroll).

The screenshot below was taken while the page could not be scrolled down.

![setupdoesntscroll](https://user-images.githubusercontent.com/524520/38688336-6b3a70e2-3e3e-11e8-8366-56db05a09ca8.png)

**Comment by invincibleJai** [comment]
@animuk this related to https://github.com/openshiftio/openshift.io/issues/3045 @jyasveer is already looking into this. It happens on socket call from the client at times.

**Comment by jyasveer** [comment]
Fix is here https://github.com/fabric8-ui/fabric8-ui/pull/2742

**Comment by jyasveer** [comment]
@RickJWagner fix is available in prod now. can you please verify and close this issue.

**Comment by RickJWagner** [comment]
I've confirmed this issue is fixed.  Thanks!
