### ISSUE TITLE
Profile - URL input eror checking

### ISSUE THREAD

**Issue by evanshortiss** [openshiftio/openshift.io#3105]
On the user profile screen (https://openshift.io/$USERNAME/_update?bio=true) if you enter a URL such as `abc.com` it turns red and won't let you update your profile until it's prefixed with `https://`. It'd be a better UX to explain the error.

**Comment by sbose78** [comment]
Thanks, this has to be addressed application-wide. CC: @catrobson @rohitkrai03 @alexeykazakov

**Comment by catrobson** [comment]
@sbose78 we should be following PatternFly standards as much as possible here:  http://www.patternfly.org/pattern-library/forms-and-controls/errors-and-validation/

While errors across the application should be handled in the same sort of pattern for communication, the way to get the whole application to have error handling is field by field ;).  Hoping you can look at how we handle verification of this field and provide the right error messages. 

@joshuawilson @christianvogt we do need to talk about error messages regarding the architecture and whether we hold the text for these in a centralized place for internationalization/localization efforts.

**Comment by christianvogt** [comment]
The specific issue has been fixed now by fabric8-ui/fabric8-ui#2978

Error handling will be field by field. We should make an effort to reuse our validation code for fields of the same data.

Even though fields may take the same data, the error messages may be specific to their use case. We certainly could look at sharing error messages and I believe that would be done by sharing the same validation code.
