### ISSUE TITLE
Page for full detail of work item is cut off at the top, large gray bar at the bottom, cannot scroll

### ISSUE THREAD

**Issue by csheremeta** [openshiftio/openshift.io#3107]
I cannot see the top of the full detail pages for work items - the text is cut off. Also, I have a large gray bar at the bottom. It looks like the page isn't aligning correctly.
![selection_540](https://user-images.githubusercontent.com/4502875/38701614-59d59bbe-3e6c-11e8-8da2-83dd8f282d86.png)

**Comment by nimishamukherjee** [comment]
Duplicate of #3082

**Comment by SMahil** [comment]
already PR submitted: https://github.com/fabric8-ui/fabric8-planner/pull/2548
