### ISSUE TITLE
When filtering workitems by type, sometimes text is on top of other text

### ISSUE THREAD

**Issue by csheremeta** [openshiftio/openshift.io#3109]
Specifically, "Experiences" shows up where "Add Work Item" is. Screenshot attached:
![selection_541](https://user-images.githubusercontent.com/4502875/38702131-d01b411a-3e6d-11e8-9f3d-5b87133aa3a4.png)

**Comment by Preeticp** [comment]
Duplicate of #3042

**Comment by SMahil** [comment]
This issue has been fixed in production
