### ISSUE TITLE
Support and Customer Service for external users

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#311]
# Description
As an external user, I want to get timely help on problems or issues I have with the OpenShift.io service. As a developer, I want to get feedback from external users in a structured, manageable way to use it to improve the offering.

# Acceptance Criteria
- [ ] The system has monitoring support that allows components to send monitoring information to a central storage for further processing. The components also include the tenant services.
- [ ] There is a mechanism to communicate to onboarded users about known issues in the form of an FAQ linked to from OpenShift.io.
- [ ] There is a submission system where users can submit bugs and suggestions.
- [ ] Submissions to the submission system will be added as a Work Item in a specific Space on OpenShift.io.
- [ ] There is a process for handling of incoming issues by the org and teams.
- [ ] External users are able to engage in a realtime chat with the dev team using a chat service like Mattermost. The dev team is engaging in a helpful way in these chats. 
- [ ] External users are able to get support for blockers or critical issues on a timely manner. 
- [ ] External users are able to engage in a mail conversation over a mailinglist.
- [ ] External users are able to engage in a forum conversation, for example on stackoverflow.com.

**Note:** A precondition for making the submission system work is a notification system. 

**Note:** Critical issues need to be addressed in a timely manner with a higher priority. Focus here is on the quickstarts boosters.

**Comment by ldimaggi** [comment]
We will also want to be able to generate metrics on customer issues - mean/average time to resolve customer issues, counter for instances of the same issue being reported, regressions if problems are reported, resolved, and then recur, etc.   

And - some measure of customer satisfaction too - such as - https://www.getfeedback.com/blog/measure-customer-satisfaction-with-csat/

**Comment by joshuawilson** [comment]
This is related to https://github.com/fabric8-ui/fabric8-ui/issues/492 
https://redhat.invisionapp.com/share/CFC91QFHU

**Comment by joshuawilson** [comment]
@michaelkleinhenz can you move this to https://openshift.io/openshiftio/openshiftio

**Comment by michaelkleinhenz** [comment]
Not relevant anymore. Needs more req's.
