### ISSUE TITLE
Deployment charts can be rendered improperly if redirecting to a different page while charts are initializing

### ISSUE THREAD

**Issue by aptmac** [openshiftio/openshift.io#3110]
Occasionally, the deployment charts can be rendered in such a way that the chart lines and graphics don't show, but the data points & tooltips still work.

When on the deployments page, if another page is visited (e.g., codebases, pipelines) while the charts are being initialized (a good indicator of this is when the donut charts are white and haven't been filled in blue yet), then upon re-visiting the deployments page the charts will not render correctly. The following error message is shown in the console:

![console-error](https://user-images.githubusercontent.com/10425301/38703687-f05e25ba-3e71-11e8-87d1-7269f9c0b623.png)

Example:
![weird-sideeffect](https://user-images.githubusercontent.com/10425301/38699003-db99cea2-3e64-11e8-8ae3-de1bbd1eee8a.png)

Gifs:
Here's what it looked like one time when I encountered it:
![process](https://user-images.githubusercontent.com/10425301/38700572-84ddaa2a-3e69-11e8-9533-da82bcc2e8a7.gif)

And what the charts look/function like after:
![blank-charts](https://user-images.githubusercontent.com/10425301/38700503-46886f1c-3e69-11e8-9c6f-a0c65fa88d6d.gif)

**Comment by andrewazores** [comment]
This looks suspiciously similar to some c3 async loading stuff we've run into before, but I can't remember what the context for that was last time. @jiekang do you remember?

**Comment by jiekang** [comment]
Yes now that you mention it. I think we've looked at this before. c3js runs some timers async and doesn't clean things up properly, so this behavior is 'expected' for c3js.

**Comment by jiekang** [comment]
I wonder if I ever filed an issue for it.. Dang.

**Comment by aptmac** [comment]
Yeah it looks to be an async problem. The function where the null value is showing up is `c3.convertDataToTargets()` [0], which is being called after loading the new chart data at `DeploymentsDonutChartComponent.updateChart()` [1]. If I put a breakpoint at [1] (or a console log at [0], I haven't been able to put breakpoints into node_modules), I haven't been able to see a null value because it gets resolved by then, but c3 is seeing null. 

fwiw if I replace [1] to regenerate the chart instead of loading like: `this.chart = c3.generate(this.config);` then I stop seeing the error, but it's not as nice a solution.

[0] https://github.com/c3js/c3/blob/master/c3.js#L5548
[1] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.ts#L147

**Comment by jiekang** [comment]
Ah found it:
https://github.com/fabric8-ui/fabric8-ui/pull/2359

https://github.com/c3js/c3/issues/1205
https://github.com/bcbcarl/react-c3js/issues/22


See my comments in pull request, and there was a mitigation. I'm not sure if this is the same error as you reported, but I expect it to be similar.

**Comment by jiekang** [comment]
The mitigation isn't as good when the charts are in the process of loading, unfortunately. I'm not sure how much we can do on our side.

**Comment by aptmac** [comment]
Ah yes, it seems to be the same error as the c3 issue you've linked above.

**Comment by aptmac** [comment]
Yeah I was able to reproduce it just now - changing the page while the donut chart is transitioning from white to blue will cause the error still.

**Comment by andrewazores** [comment]
Okay, that's unfortunate.

The c3 bug we had seen was closed, but this recent and still open one looks the same: https://github.com/c3js/c3/issues/2187

**Comment by alexeykazakov** [comment]
Outdated.

**Comment by aptmac** [comment]
This can still reproduced, but the bug is in the c3js repo. Even if/when it gets fixed in c3js it may be a headache to update patternfly to the latest version.
