### ISSUE TITLE
OSIO Click Party error: "set up new application" phase failed, "no user namespace found for <username>"

### ISSUE THREAD

**Issue by goodwinos** [openshiftio/openshift.io#3112]
During the OSIO Click Party (APAC session), the "setup new application" phase failed (attempted 5 times, same result every time). I was instructed to reset my profile, which I did, and then repeated the steps. Same error. I checked on github, and the repo was correctly created, e.g. https://github.com/goodwinos/attempt6 but the OSIO user-interface reports "No user namespace found for rhn-support-mgoodwin", and no further progress is possible after that.

Also, why is it trying to use my access.redhat.com user name? (rhn-support-mgoodwin)? I logged into OSIO as mgoodwin@redhat.com and would prefer to use that username. Note: I also tried explicitly logging OUT of the access portal, but it made no difference.

Screen shot of the OSIO user interface at the point of the error is attached.

![image](https://user-images.githubusercontent.com/4495123/38711363-84fe4024-3f08-11e8-99d0-6b320b4dbcca.png)

**Comment by jyasveer** [comment]
Fix is here https://github.com/fabric8-ui/fabric8-ui/pull/2742

**Comment by jyasveer** [comment]
@goodwinos changes are in prod now. can you please test and close this. thanks

**Comment by goodwinos** [comment]
Hi @jyasveer I just tested, and exactly the same result. See attached image. Maybe it isn't quite in prod yet??

![image](https://user-images.githubusercontent.com/4495123/38794122-57d5362a-4197-11e8-9c0d-2ac2b13b8aa2.png)

**Comment by animuk** [comment]
@jyasveer Could you please let me know whether this is taken cared of. If yes, close this.

**Comment by goodwinos** [comment]
@animuk @jyasveer 
I just retried yet again, and the problem is not resolved. EXactly the same result as re-reported 2 days ago (see above).

Regards
-- Mark

**Comment by jyasveer** [comment]
@goodwinos let me check it again. i think i have to dig this more.

**Comment by jyasveer** [comment]
@goodwinos if possible can you please send me the payload for the http request to set up the application. This could help me to understand the issue

**Comment by animuk** [comment]
@goodwinos  could you please reply on the query that @jyasveer has asked ?

**Comment by sbose78** [comment]
The username returned to OpenShift.io by Red Hat Developers ( via the registration-app ) is `rhn-support-mgoodwin` ( this is what is reflected in OSIO keycloak ). Hence, in OpenShift.io's knowledge your username is `rhn-support-mgoodwin` and we don't support changing that.

**Comment by sbose78** [comment]
@aslakknutsen , any way to check if the tenant namespaces were not created https://auth.openshift.io/api/users/5bb67c14-90b7-4552-9761-e24f0b15a67e ?

**Comment by goodwinos** [comment]
Hi all, regarding my username - yes it seems OSIO wants to use rhn-support-mgoodwin despite me logging in as mgoodwin@redhat.com (I also tried logging in as rhn-support-mgoodwin) - both get the same result.
There doesn't seem to be any way for me to deprecate rhn-support-mgoodwin and this seems to be related to the issue at heart. The GH repo for the project gets created correctly, but the tenant namespace does not. Can we perhaps just delete rhn-support-mgoodwin and re-register me as mgoodwin@redhat.com or something?

**Comment by sbose78** [comment]
@goodwinos Which namespaces do you see when you login to https://console.starter-us-east-2.openshift.com/console/ ?

**Comment by alexeykazakov** [comment]
Just for clarification. @goodwinos your username is rhn-support-mgoodwin and your email is mg***@redhat.com
You can use both username or email when logging.
In the past the usernames where auto-generated during registration. This is why you got this username. It's fixed now and new users can choose their own usernames during registration.

But it's not the problem here. I suspect tenant service failed to initiate namespaces. @aslakknutsen can give more details.

**Comment by sunilk747** [comment]
@sbose78 Is this issue related to auth team? If it is, can we change the label here?

**Comment by sbose78** [comment]
@sunilk747 , Not related to the auth team - I've added the appropriate label.

**Comment by aslakknutsen** [comment]
@sbose78 Seems tenant provision related. checking

**Comment by goodwinos** [comment]
@aslakknutsen seems l8ikely. let me know if/when I should re-test (I'm in AEST timezone, currently 7:30pm)

**Comment by goodwinos** [comment]
@jyasveer @aslakknutsen here's the launch request headers, response and following form, request / frame from the browser debug. Is this the payload you're after? (I've trimmed the Authorization: Bearer data). 

```
General

Request URL: https://forge.api.openshift.io/api/osio/launch
Request Method: POST
Status Code: 200 OK
Remote Address: 54.210.220.218:443
Referrer Policy: no-referrer-when-downgrade

Response

Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://openshift.io
Access-Control-Expose-Headers: Content-Disposition
Content-Encoding: gzip
Content-Length: 87
Content-Type: application/json;resteasy-server-has-produces=true
Date: Fri, 27 Apr 2018 00:34:38 GMT
Set-Cookie: 4268e54556cc2de1152cc0d314e1281b=26ff5bb81c32894be3609a8107524a34; path=/; HttpOnly; Secure

Request Headers

Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-AU,en-GB;q=0.9,en-US;q=0.8,en;q=0.7
Authorization: Bearer <.... trimmed ....>
Connection: keep-alive
Content-Length: 285
Content-Type: application/x-www-form-urlencoded
Host: forge.api.openshift.io
Origin: https://openshift.io
Referer: https://openshift.io/rhn-support-mgoodwin/attempt9/applauncher/createapp/app-test-1
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
X-App: osio
X-Execution-Step-Index: 0
X-Git-Provider: GitHub

Form Data

mission: health-check
runtime: vert.x
runtimeVersion: redhat
pipeline: maven-releasestageapproveandpromote
projectName: app-test-1
projectVersion: 1.0.0
groupId: io.openshift.booster
artifactId: app-test-1
spacePath: /attempt9
gitRepository: app-test-1
space: 18de159c-72b8-4b3f-a62e-922a776cbae1


.. and after that:

[{GITHUB_CREATE: "Creating your new GitHub repository"},…]
0
:
{GITHUB_CREATE: "Creating your new GitHub repository"}
GITHUB_CREATE
:
"Creating your new GitHub repository"
1
:
{GITHUB_PUSHED: "Pushing your customized Booster code into the repo"}
GITHUB_PUSHED
:
"Pushing your customized Booster code into the repo"
2
:
{OPENSHIFT_CREATE: "Creating your project on OpenShift Online"}
OPENSHIFT_CREATE
:
"Creating your project on OpenShift Online"
3
:
{OPENSHIFT_PIPELINE: "Setting up your build pipeline"}
OPENSHIFT_PIPELINE
:
"Setting up your build pipeline"
4
:
{GITHUB_WEBHOOK: "Configuring to trigger builds on Git pushes"}
GITHUB_WEBHOOK
:
"Configuring to trigger builds on Git pushes"


.. followed by:

{id: "9e362430-fff3-4ac4-9ab6-6bc1b971c3cb",…}
data
:
{error: "No user namespace found for rhn-support-mgoodwin"}
error
:
"No user namespace found for rhn-support-mgoodwin"
id
:
"9e362430-fff3-4ac4-9ab6-6bc1b971c3cb"
statusMessage
:
null

```

**Comment by goodwinos** [comment]
After I repo'd the issue again, I was notified of an illegal state exception:
IllegalStateExceptionio.fabric8.launcher.osio.client.Tenant in lambda$getDefaultUserNamespace$0

Looks like getDefaultUserNamespace failed, so maybe I have a weird account with no default namespace or something? Here's the exception event URL :
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/3827/events/185257/

If nobody can diagnose this, perhaps we should just delete my entire account, and I'll start again by re-registering from scratch?

**Comment by aslakknutsen** [comment]
@goodwinos Reprovisioned your user. Please retest.

**Comment by aslakknutsen** [comment]
Excellent! The broken frame unrelated to this/and reported elsewhere. Closing.
