### ISSUE TITLE
Planner - what is the use of "Add and Open" button

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#3115]
In Planner for any work-item there is `Add and Open` button displayed.
It results in the same behavior as `Add` button. Is this expected? Or is it suppose to open the newly created work-item as well. If its latter then its a bug.

**Comment by ppitonak** [comment]
@michaelkleinhenz @nimishamukherjee  can you comment on this?

**Comment by vikram-raj** [comment]
@miteshvp @ppitonak ```Add and open``` button will open the detail page of the newly created work item.

I verified it on production and it is working as expected.

**Comment by joshuawilson** [comment]
I can confirm it works as designed. I'm going to close this. If you have further questions please reopen it.
