### ISSUE TITLE
TypeError in recent-workspaces-widget.component.ts

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#3119]
```
console.js:32 ERROR TypeError: Cannot read property 'length' of null
    at RecentWorkspacesWidgetComponent.webpackJsonpac__name_../src/app/dashboard-widgets/recent-workspaces-widget/recent-workspaces-widget.component.ts.RecentWorkspacesWidgetComponent.initWorkspaces (recent-workspaces-widget.component.ts:180)
```

I ran local ui against prod and visited the home page.

```
  private initWorkspaces(): void {
        if (codebase.workspaces === undefined) {
          continue;
        }
        for (let k = 0; k < codebase.workspaces.length && this._workspaces.length < this.limit; k++) {
          this._workspaces.push(codebase.workspaces[k]);
        }
```

undefined and null are distinct. The code should check for both. It could possibly be simplified to:

```
if (codebase.workspace) {
  for [...]
}
```

**Comment by jiekang** [comment]
@dlabrecq Can you take a look at this? Your commit https://github.com/fabric8-ui/fabric8-ui/commit/944420daee3131a0bba040d7b18a87c5daced387 introduced it.

**Comment by jiekang** [comment]
@mindreeper2420 when you reviewed https://github.com/fabric8-ui/fabric8-ui/pull/2720, was this not seen? I wonder what special case you need to hit this scenario.

**Comment by mindreeper2420** [comment]
@jiekang When I reviewed, it was all local, so the new Dashboard rendered and not the one that is currently seen in production. Could that be the case? I didn't notice any console errors and the build didn't have issues for me.

**Comment by dlabrecq** [comment]
I had pushed this fix below and I'm no longer able to reproduce it with a space that has no codebases. If you still see the error after pulling the latest, please reopen.
https://github.com/fabric8-ui/fabric8-ui/pull/2739

**Comment by jiekang** [comment]
@dlabrecq I still see this. It's not related to a unit test.

**Comment by jiekang** [comment]
![recent-workspaces-null](https://user-images.githubusercontent.com/5430520/38745409-7646de2e-3f12-11e8-8ff0-94382f6753b1.png)

**Comment by jiekang** [comment]
The original comment on this issue highlights the problematic code and suggested fix.

**Comment by jiekang** [comment]
@dgutride 

I'm on revision ed18ecde1cc573ccf27aace7ce2d5ba2233b1f73 which is one commit ahead of your fix. You need a space with a codebase in it. Having no codebases won't hit the problem as the for loop won't iterate at all.

I've asked others to run local f8-ui against production and they have the issue as well.

If I log the codebase in `initWorkspace` like so:
``
  private initWorkspaces(): void {
    this._workspaces = [];
    for (let c = 0; c < this.recent.length; c++) {
      let space = this.recent[c];
      if (space.codebases === undefined) {
        continue;
      }
      for (let i = 0; i < space.codebases.length; i++) {
        let codebase = space.codebases[i];
        console.log(codebase);
        if (codebase.workspaces === undefined) {
          continue;
        }
```

```
export class ExtCodebase extends Codebase {
  workspaces?: Workspace[];
}
```

If your function that sets the workspaces field does not set it, the default value looks to be 'null', not 'undefined'. Then your check:

```
        if (codebase.workspaces === undefined) {
          continue;
        }
```
will still pass even when it's null because 'null' and 'undefined' are distinct values.

I've pointed out the problematic code and the suggested fix but it feels like we're not talking about the same thing. Is there something confusing about my statements?

**Comment by jiekang** [comment]
I added some more console logs in the code that sets the workspaces:

```
  private fetchCodebases(spaceId: string): Observable<ExtCodebase[]> {
    return this.codebasesService.getCodebases(spaceId).flatMap(codebases => {
      if (codebases.length === 0) {
        return Observable.of([]);
      }
      console.log('blah', codebases);
      return Observable.forkJoin(codebases.map((codebase: ExtCodebase) => {
        return this.workspacesService.getWorkspaces(codebase.id)
          .map(workspaces => {
            console.log('hi', workspaces);
            codebase.workspaces = workspaces;
```

These are the outputs for my account:

![workspaces-null](https://user-images.githubusercontent.com/5430520/38755113-8c1ffaee-3f32-11e8-816b-115cb33b01e1.png)

Looks like I was wrong, the defaults could be undefined (need to verify), but the code is actually setting workspaces to null for me.

**Comment by jiekang** [comment]
Going further, the workspaces api has response:

```
{"data":null,"links":{"create":"https://api.openshift.io/api/codebases/3931a8e0-87f8-4f4b-8f3e-bff194eb29af/create"}}
```

Looks like on the API side, it would be preferable to have an empty state instead of a null state. On the UI side, it would be nice to be robust against 'bad' data.

**Comment by joshuawilson** [comment]
I found the PR the fix is in, I merged it.

**Comment by jiekang** [comment]
https://github.com/fabric8-ui/fabric8-ui/pull/2740
