### ISSUE TITLE
Add item already exists error code to areas/{id} POST when user attempts to create duplicate area

### ISSUE THREAD

**Issue by dgutride** [openshiftio/openshift.io#312]
In order for PR https://github.com/fabric8-ui/fabric8-ui/pull/1616 to be merged and to fix https://github.com/fabric8-ui/fabric8-ui/issues/921, we need to be able to know definitively that a duplicate area was created.  Ideally, an application specific error code would be added to the JSON API in order to determine that an area already exists.  The current PR is looking at the human-readable description to infer this.

API: POST -> areas/{id}
Swagger link: http://swagger.goa.design/?url=github.com%2Falmighty%2Falmighty-core%2Fdesign#!/area/area_create_child

**Comment by aslakknutsen** [comment]
The backend should probably return HTTP 409 Conflict on the POST to the collection in these cases.

**Comment by joshuawilson** [comment]
@aslakknutsen do you have an issue for working this or do you want me to copy this to fabric8-wit?

**Comment by joshuawilson** [comment]
This issue was moved to fabric8-services/fabric8-wit#1484

**Comment by dgutride** [comment]
UI work and backend work has been completed already on this - moving to closed.
