### ISSUE TITLE
Che6 is not automatically stopping workspaces when users attempt to open a new workspace

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3121]
Related to https://github.com/redhat-developer/rh-che/issues/629

Steps to recreate issue:
* Create and open a Che workspace in OpenShift.io
* While that workspace is open, attempt to create a 2nd workspace
* The 2nd workspace's browser tab opens, but Che does not automatically stop the first workspace and open the 2nd workspace as was the case in Che5:

![screenshot from 2018-04-13 10-29-26](https://user-images.githubusercontent.com/642621/38740862-90040456-3f06-11e8-9eea-44f724571afb.png)

The workaround is to manually stop the first workspace and then start the 2nd workspace. It woudl be more helpful to users if Che could take care of stopping the first workspace and switching the user into the 2nd workspace.
#

**Comment by ibuziuk** [comment]
@ldimaggi is it consistently reproducible or interminate ?

**Comment by l0rd** [comment]
I have checked and not been able to reproduce. The first workspace is stopped automatically and the second one starts with no user action needed. Closing.

**Comment by ldimaggi** [comment]
I am able to recreate this issue 100% of the time by following these steps:
* In Che dashboard, remove all old workspaces
* In OSIO, reset user environment
* Create a new OSIO space
* Create a new OSIO quickstart/app
* From the quickstart, create a new Che workspace
* After the workspace is crated, return to OSIO
* And create a second Che workspace
* Observe the second workspace fail to open:

**Comment by ldimaggi** [comment]
Closing - it looks like the root cause of the issue is: https://github.com/openshiftio/openshift.io/issues/3135
