### ISSUE TITLE
Settings: Adding collaborators must distinguish identical names

### ISSUE THREAD

**Issue by stooke** [openshiftio/openshift.io#3122]
Many organizations have more than one person with the same name, or the same person in the system more than once.  The list of collaborators shows only name, but needs to show more information (perhaps email) in the case of duplicate names.

**Comment by andrewazores** [comment]
This wasn't Planner, this was the Collaborators page, ex. `https://openshift.io/aazores@redhat.com/test-space/settings/collaborators`.

**Comment by stooke** [comment]
Thanks, @andrewazores.

**Comment by sbose78** [comment]
Hi @catrobson , Would you be able to suggest how to make the 'add collaborators' type-ahead's search results less confusing? @rohitkrai03 could then add it to his queue for fixing this :)
CC: @alexeykazakov .

**Comment by catrobson** [comment]
@lwrigh could you take a look at this?

**Comment by lwrigh** [comment]
@catrobson Yup I can take a look at it.

**Comment by lwrigh** [comment]
@andrewazores Can you share a screenshot of what you're seeing?

**Comment by andrewazores** [comment]
It's about this screen:

![screenshot from 2018-05-16 11-18-02](https://user-images.githubusercontent.com/3787464/40126227-d49977aa-58fa-11e8-8230-8a3ca978cdfb.png)

I don't know any people with identical names off the top of my head to illustrate the behaviour Simon's talking about, but the point is that only displaying the names here makes it hard to figure out who you're selecting if there are two people by the name of "John Doe". Presumably they would have some other unique identifier like an email address which could be used to distinguish them.

**Comment by alexeykazakov** [comment]
I would expect Full name + username in the list.

**Comment by lwrigh** [comment]
### Profile photo + email 
![avatar email](https://user-images.githubusercontent.com/20227374/40133281-466f3524-590d-11e8-96dd-d157f2df82e8.png)
### Just email 
![just email](https://user-images.githubusercontent.com/20227374/40133285-4bec249e-590d-11e8-8468-3c0df10424f6.png)

My suggestions include adding the user's email below their name or including both their profile picture and email in the list of results to distinguish between them. I would also suggest having the search results appear in alphabetical order if possible.  

 If having the profile picture of the user appear with the search results isn't possible, I think having the user's email appear and having the search results appear in alphabetical order would help to improve the experience of adding and searching for collaborators.   

@andrewazores @catrobson @sbose78 @alexeykazakov @rohitkrai03

**Comment by stooke** [comment]
I suspect having a profile picture there could get slow really quickly.

Another alternative is 
    User Name <email@address>
similar to what's used in mail clients - it's familiar and succinct.

I'd also like to point out that the search box will need to match both username and email address.  THis is probably fairly straightforward.

**Comment by alexeykazakov** [comment]
Emails can be private and not available for browsing. Let’s use usernames instead.

**Comment by lwrigh** [comment]
@alexeykazakov +1 That's a good point

**Comment by stooke** [comment]
Agreed.  (In fact, if it were only usernames I'd be happy - I just want to ensure uniqueness in the list)

**Comment by joshuawilson** [comment]
Only space owners can see the collaborators page. But collaborators can get the list from within the planner. 

There are several things to think about here.
1. While "adding" you are looking at all users of OSIO, currently over 11k. That is a lot, so images would be bad here. Does the search work on name, username, or both/either? I would like to search on both.
2. The display list in the collaborators page could/should have the user's profile 
3. The display list in the Planner collaborators picker drop down could/should have the user's profile image since it is limited.
4. What will the Planner collaborator picker drop down search/filter on? Name, username, or both/either? I would like to search on both.

**Comment by stooke** [comment]
Is there any hope of having one people-picker widget and reusing it in different scopes?  Easier to code, easier to train...

**Comment by alexeykazakov** [comment]
As I said we are completely re-doing our permission/collaboration model right now. So, let’s not make any significant changes in UI right now. Some cosmetic changes like adding usernames/avatars can be done now though.

Regarding searching for an OSIO user. Search API searches on names, usernames and public emails. The search result is limited to 30 users or something like this (don’t remember the exact number). If there are more matching users the first 30 will be returned.

Searching for an existing collaborator (in planner) is a pure UI thing. We need to ask the Planner team how it works.

**Comment by joshuawilson** [comment]
That makes sense. Let's keep it simple then.

**Comment by rohitkrai03** [comment]
@joshuawilson For the dropdown multiselect option we use an open source angular component - https://github.com/softsimon/angular-2-dropdown-multiselect. This component doesn't provide any way to actually customize the options as per our need. So, basically its just limited to a simple list of names and nothing else. For our needs i found a good component which offers a lot of customization and flexibility - https://github.com/CuppaLabs/angular2-multiselect-dropdown. If you think that its okay to replace the old component with this one then i'll work on it and raise a corresponding PR.
Also, the search result from API sends profile pic data as well so its not a problem to actually include a small user avatar with name and username. cc: @alexeykazakov

**Comment by joshuawilson** [comment]
It looks like the only place using it is in `AddCollaboratorsDialogComponent`, so you should be fine to swap them out. But you should do a search for some of the keywords to make sure you don't break something by removing it.

@openshiftio/uxd-team do we have any other `dropdown multi-selects` in the current UI or in future designs?

**Comment by alexeykazakov** [comment]
@joshuawilson most likely we will need dropdown multi-selects in the new versions of Permissions/Team management UI too.

**Comment by mindreeper2420** [comment]
As Alexey stated, the Permissions/Team Management will definitely have the multi-selects. A multi-select may also be in use in the Planner filtering (for applying filters/labels), but I am not 100% sure on that.

Regarding a new/different library, will the suggested one work with the planned Angular upgrade, or will it prevent us going beyond Angular 4?

**Comment by joshuawilson** [comment]
@rohitkrai03, @mindreeper2420 has a good point. If you look at the source you can see that https://github.com/softsimon/angular-2-dropdown-multiselect already supports Angular 6.

It is also a lot more active and has more contributors. I think it is a healthier project. 

Can you look at submitting a PR to it to get add the features you need?

**Comment by rohitkrai03** [comment]
@joshuawilson I looked into adding features to https://github.com/softsimon/angular-2-dropdown-multiselect but it seems like a lot of work since the main architecture is written in a way assuming that the options in the dropdown cannot be customized. I also found another component - https://github.com/ng-select/ng-select which supports Angular 6 already and very actively maintained with all the features we need now or may need in future.

**Comment by dlabrecq** [comment]
If you end up using @ng-select/ng-select, we have a stylesheet contribution to make that look more like PatternFly. https://github.com/patternfly/patternfly-ng/pull/343

Typically we wrap components, not provide stylesheets for 3rd party libraries -- probably will wrap it. The team still needs to decide if @ng-select/ng-select is a good fit for Patternfly, but it has a lot of potential.

This is also an Angular 6 implementation, so not certain we can build with Angular 4 due to the breaking changes in rxjs. Might need to include rxjs-compat as a dependency?

**Comment by rohitkrai03** [comment]
> Latest version targets Angular v6 since it uses new RxJS which has breaking changes. If you are using Angular v5 you could use ng-select v1.x or install rxjs-compat compatability package. We will support v1.x with latest bug fixes to allow easier migration. For v1.x you can refer the 1.x branch.

@dlabrecq We can also use 1.x version now and move to 2.x when we migrate to Angular 6.

**Comment by dlabrecq** [comment]
Yes, I was on the fence about taking an older version. Just don't get the latest bug fixes and features, if any.

**Comment by joshuawilson** [comment]
we are moving to angular 6 shortly
