### ISSUE TITLE
[2] Deployments view should have an empty state for "No Applications"

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#3126]
Parent: https://openshift.io/openshiftio/openshiftio/plan/detail/2144

# Task

https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/286564374

Deployments view should have an empty state for "No Applications"

# Related

https://github.com/openshiftio/openshift.io/issues/2188

**Comment by aptmac** [comment]
This functionality was introduced in: https://github.com/fabric8-ui/fabric8-ui/pull/2917
