### ISSUE TITLE
[6] Deployments view should have an empty state for "None of your applications have been deployed yet"

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#3127]
Parent: https://openshift.io/openshiftio/openshiftio/plan/detail/2144

# Task

https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/286564375

Deployments view should have an empty state for "None of your applications have been deployed yet"

# Related

https://github.com/openshiftio/openshift.io/issues/2188

**Comment by jiekang** [comment]
The layout of this is a little more complicated to execute than expected.

**Comment by andrewazores** [comment]
Yea, I can see that it could be. Feel free to bump up the points on this if you've been looking at it and have a better estimate.

**Comment by aptmac** [comment]
This empty-state screen was added in https://github.com/fabric8-ui/fabric8-ui/pull/2935
