### ISSUE TITLE
[4] Deployments API for environment quota should report usage from other spaces as well

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#3129]
Parent: https://openshift.io/openshiftio/openshiftio/plan/detail/2145

# Task

Response from `/environments` endpoint should include data about not only the user's total resource quota and the current usage, but should also divide the usage into usage by the queried spaceId and usage by all other spaces.

# Related

- [ ] https://github.com/openshiftio/openshift.io/issues/3128

**Comment by jiekang** [comment]
```
{
  spaceUsage: {
    ResourceUsageJSON
  },
  otherUsage: {
    ResourceUsageJSON
  }
}
```

**Comment by jiekang** [comment]
I believe current progress is in https://github.com/chrislessard/fabric8-wit/tree/spaceid-end-endpoint

**Comment by chrislessard** [comment]
Current progress, just needing review : https://github.com/chrislessard/fabric8-wit/tree/space-id-endpoint
