### ISSUE TITLE
Doc link broken from 'home' page

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#313]
The 'Home' page is divided into 3 panes:
- Recent spaces
- My work items
- Recent active pipelines

'My work items' has a link, 'Learn how to get started in the documentation.'  The link is broken, it leads to a 404.

![image](https://user-images.githubusercontent.com/524520/27807436-657dff96-6006-11e7-97b4-884f1a0256e5.png)

**Comment by RickJWagner** [comment]
![image](https://user-images.githubusercontent.com/524520/27807448-80ddb07e-6006-11e7-9870-f081f0f996c7.png)

**Comment by joshuawilson** [comment]
duplicates https://github.com/fabric8-ui/fabric8-ui/issues/1378

**Comment by joshuawilson** [comment]
@mindreeper2420 can you please take a look at this.

**Comment by joshuawilson** [comment]
@rkratky can you look into this please?

**Comment by rkratky** [comment]
@joshuawilson, that link never went live because it was decided not to have docs on the RH Customer Portal. Could you please just remove until we have acks to publish docs on docs.osio? (I asked Catherine to remove the link many months ago, but I guess it got lost in some noise.)

**Comment by joshuawilson** [comment]
I've moved this to the Platform backlog since it is a code change to the dashboard UI.

**Comment by alexeykazakov** [comment]
I don't see this link anymore. Looks like it has been already removed?

**Comment by joshuawilson** [comment]
So it has, closing.
