### ISSUE TITLE
New Launcher: default choices and placeholders

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#3138]
We are missing default choices and placeholder names, so the user could complete the flow quicker, faster and with less efforts. For example, user is asked to setup a name for a repository, but we could pre-fill this one with the name of the application.

**Comment by animuk** [comment]
@invincibleJai It looks to be relevant in the only new app launcher flow and not affecting the import flow. because in import flow, user need to choose the repo explicitly.
cc @slemeur

**Comment by invincibleJai** [comment]
@animuk makes sense for create flow i.e Quickstarts as user need not have to retype repo name if app name value good otherwise he can edit it.
One scenario I can think of is if user types app_name as "app-123" and we prefill repo name with "app-123"  but if user already has that repo name in his org then we'll be as well showing error message below i.e `Duplicate: app-123 already exist as user/app-123`

Let me know it makes sense , we can go ahead and make this change in UI.

CC @catrobson @slemeur

**Comment by slemeur** [comment]
If we pre-fill information on behalf of the user, we should not pre-fill with values that cause errors. We should take care of that for the user - but inform him that we did change the repo name.

If `app-123` repo is already taken, then why not moving forward with `app-123-2` and display a message bellow: `user/app-123 repository already exist, renamed the repository to user/app-123-2`

@catrobson : what is the default ux pattern for that? would it work?

**Comment by animuk** [comment]
@catrobson any further status update on the above for the UX team point of view.

**Comment by slemeur** [comment]
We have only few things to handle on this:
- We should have a placeholder for the project name. Then, use that name for the repository too.
- We should default the "personal" organization of the user.

The flow should be very fast to execute and requires as less as possible of interaction. The user should be freed to input text.

@animuk why don't you move forward on the proposal I gave?

**Comment by invincibleJai** [comment]
Thanks @slemeur for inputs, we are working on it.

> We should have a placeholder for the project name. Then, use that name for the repository too.

we currently have Project name prefilled with "app-test-1", by placeholder you mean should not have it prefilled but have a placeholder message like "Please enter Project Name"?

> We should default the "personal" organization of the user.

We have handled it.

**Comment by slemeur** [comment]
@invincibleJai : Sorry for the confusion. We need to prefill the two fields:
- project name
- repository name (with the project name)

(placeholders should be there, but we are looking to help the user to get started as fast as possible, so we need to povide prefilled values).

**Comment by catrobson** [comment]
If we're going to check their repo and create a unique name, we would just fill the field in with a unique name without any message below it.  

I think we have 2 'naming' fields:
Application name:  Don't pre-fill.  Users usually make this unique.  This is filled out on one of the dark screens before the launcher flow shows.  Don't restrict this to the rules of OpenShift, git, etc.
Project name should then be pre-filled with 'application name' given by the user, but transformed to meet the rules of application names.  This is used for OpenShift + Git repository.  If needed we can append something onto the application name but I don't know that we need this.

Example:
User names application "My First Project"
We name project in git "myfirstproject"
We name stuff in Openshift "myfirstproject_stage" "myfirstproject_run" etc.

Does this make sense?

**Comment by invincibleJai** [comment]
Changes are in prod, repo name in create flow is getting prefilled with application name provided by the user and are editable. Let me know if we can close this?

**Comment by slemeur** [comment]
Just tested and found the following bug:
When the application name is the name of an already existing repository, it is handled (ie we are not calculating another name for the repository, so the flow is blocked and user has to provide an input)
![screen shot 2018-04-25 at 09 11 16](https://user-images.githubusercontent.com/1636769/39230982-dce1b212-4868-11e8-92fc-e34783096f07.png)

Otherwise it worked well.

**Comment by invincibleJai** [comment]
@slemeur yes for App name we are providing default name always as "app-test-1". Can we have some better default value i.e something meaningful and suffix it with the timestamp that will make it unique as well (eg : app-test-1524641623081)

It would help with repo name as well as it would be prefilled with app name which would have timestamp suffixed?

**Comment by slemeur** [comment]
As discussed today @invincibleJai I don't think the timestamp is a good approach for the end-user. That would be kind of confusing to see that timestamp displayed everywhere in the UI.

Could we just increase the number at the end by `1` when we detect that the default name is already taken?

**Comment by invincibleJai** [comment]
> Could we just increase the number at the end by 1 when we detect that the default name is already taken?

@slemeur incrementing App name by 1 won't be possible as there is no APIs as of now which would help to check uniqueness for App name.

**Comment by slemeur** [comment]
@invincibleJai : I created a separate issue for this particular item which will need research from UXD team: https://github.com/openshiftio/openshift.io/issues/3372

Otherwise, I think all the issues from this issue have been addressed.

**Comment by invincibleJai** [comment]
Thanks @slemeur , closing this.
