### ISSUE TITLE
New Launcher: Navigation to next section is unclear

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#3139]
As a user, I'm struggling a little bit with what I have to do, to go for the next section in the new Launcher flow. 
We have a lot of empty space in the flow and the "next arrow" is hard to find. Users have to scroll to be able to find it. I imagine quite a lot of the users could be a bit confused by that.

**Comment by animuk** [comment]
@catrobson any further status update on the above for the UX team point of view.

**Comment by slemeur** [comment]
@animuk : I think here you can start by reducing the space between each sections.

**Comment by invincibleJai** [comment]
have taken off extra space from runtime/missions screen and have taken off spaces between the cards in summary screen.

**Comment by catrobson** [comment]
@invincibleJai I'm not seeing this in production yet, any chance you could share a PR and/or screenshot?

**Comment by joshuawilson** [comment]
Is this a bug or a question? If it is a bug, what Severity is it?

**Comment by invincibleJai** [comment]
@catrobson changes are prod now.

<img width="1484" alt="screen shot 2018-04-25 at 11 08 57 am" src="https://user-images.githubusercontent.com/5129024/39227989-54b11f52-4879-11e8-96f0-cad55e3d6e3a.png">

**Comment by catrobson** [comment]
Thank you, this is great!

**Comment by catrobson** [comment]
@slemeur Let's go forward with this for summit, and start watching users trying it there to make sure the next action is visible and understood.  We can then make further modifications if needed on the next button/capability if still needed.  Ok to close this?

**Comment by slemeur** [comment]
Thanks. Yes agree @catrobson , let's do that.
