### ISSUE TITLE
Wireframes: Teams (8)

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#3142]
Wireframes for creating, editing, and removing teams from a space based on the workflow identified in #2844.

PARENT: #351

VERIFICATION CRITERIA:
- [x] Wireframes created in sketch and posted to InVision
- [x] Sketch file exists in OSIO google drive
- [ ] InVision link posted to #351

**Comment by muruGanesan** [comment]
Discussed with Todd (PM) to understand the requirement of 'Teams+Security group+ Areas+Space'
date: 20 April 2018
Recording link: https://bluejeans.com/s/BJl4C/

**Comment by muruGanesan** [comment]
@catrobson, @lwrigh, @mceledonia, @qodfathr 
Please review the draft version of 'Teams' wireframe' 
https://redhat.invisionapp.com/d/main#/console/14140360/294364488/preview

**Comment by qodfathr** [comment]
@muruGanesan just me or is that link wrong?

**Comment by muruGanesan** [comment]
@qodfathr, 
Sorry! it may be a private link.

Could you please try the below links?
https://redhat.invisionapp.com/share/DZHR8H0SJH4#/294364488_1-Dashboard_Option-1
https://redhat.invisionapp.com/share/KAHR8RU5GQZ

**Comment by muruGanesan** [comment]
Here is the latest Invision link: 
https://redhat.invisionapp.com/d/#/console/14290293/297713090/comments/98120452

**Comment by muruGanesan** [comment]
Currently, we delivered the minimum viable product (MVP) for Teams...

**Comment by ldimaggi** [comment]
The most recent link is private - can you open it up for reviewers? Thx!

**Comment by AshishDurgude** [comment]
This is the latest Invision link: 
https://redhat.invisionapp.com/share/GTJ4AJG8A3K
This will allow comments on the prototype.

**Comment by AshishDurgude** [comment]
Hi, @ldimaggi.  I have updated the wireframes with the team description.
Here is the link: https://redhat.invisionapp.com/share/RDJ7172Q9N3

**Comment by muruGanesan** [comment]
Moved to:  https://github.com/openshiftio/openshift.io/issues/3654
Here is the final version of 'the team flow'
https://redhat.invisionapp.com/share/9UKW89QM3ZH#/screens/302986109
