### ISSUE TITLE
Router redirect doesn't work if there is some `error` param in the previous URL

### ISSUE THREAD

**Issue by rohitkrai03** [openshiftio/openshift.io#3144]
Clicking the `Take me home` button on 

- https://openshift.io/_error works fine.
- https://openshift.io/_error?error=some_error it doesn't.

**Comment by andrewazores** [comment]
@joshuawilson I can look into this since I've been dealing with the router and other navigation tasks lately.

**Comment by andrewazores** [comment]
This was done intentionally:

https://github.com/fabric8-ui/fabric8-ui/blame/master/src/app/shared/login.service.ts#L86

but I don't know the context of why this choice was made. The login service sees the "error" parameter, sends a notification, and then simply stops. This leaves the `openShiftToken` property of the service undefined, which presumably is why the "Take me home" button doesn't work - probably a lot of things wouldn't work.

@joshuawilson @dlabrecq I see your names in the log for this file, albeit some time ago. Do you have any opinions on what the expected flow is here? I don't know what the intended use of the "error" param is - presumably something like a failed login that redirects back to OSIO with a specific error code for the failure?

**Comment by dlabrecq** [comment]
I know that when the error param is provided, the message is displayed as a notification message. Although, the _error page message is probably no longer appropriate for that?

"404: You've found something, but not the page you're looking for"

At one time, LoginService set a message via ErrorService, prior to navigating to _error, but that no longer appears to be used. I suspect that a REST API provides the error param because I don't see it being used anywhere in fabric8-ui.

**Comment by andrewazores** [comment]
Would it make sense in this case to just make the error param check into its own standalone if-statement, removing the "else" after it? So instead of (paraphrasing):

```
if (error) {
  sendNotification();
} else if (login) {
  doLogin();
} else if (loggedIn) {
  handleLoggedIn();
}
```

it would simply become:

```
if (error) {
  sendNotification();
}

if (login) {
  doLogin();
} else if (loggedIn) {
  handleLoggedIn();
}
```

This should allow the login service to resume its normal flow so that it remains in a good state regardless of the error parameter, but the error is still reported. Again, not sure what the context of the error parameter is supposed to be, but this seems to make sense to me.

**Comment by rohitkrai03** [comment]
@andrewazores @patternfly-build This scenario was not specific to login page. We have a page for verification of email which will be having some error param if needed. Something like this - https://openshift.io/_verifyEmail?verified=false&error=some_error 
And there is a button for redirect to home which doesn't work because of the bug.

**Comment by dlabrecq** [comment]
I was logged in as @patternfly-build

Considering that the verification email has its own error page, we should probably remove the error param code from the login service. We don't want to display that as an additional notification message.

**Comment by rohitkrai03** [comment]
@andrewazores @dlabrecq We do need to handle the error param because /_verifyEmail doesn't send the notification. Also, just had a talk with @alexeykazakov that we might need to handle errors for login as well (probably in future). So, removing it altogether is not a good idea. 
I did try the logic @andrewazores mentioned above for splitting `if...else` for error handling and it solves the problem.

**Comment by andrewazores** [comment]
@rohitkrai03 sorry, didn't see your offer to open the PR yourself. I'd be okay with that, if you'd like to reassign this issue to yourself and take ownership.

We're talking about a patch like this, right?

```
diff --git a/src/app/shared/login.service.ts b/src/app/shared/login.service.ts
index 3f039588..41dc1c94 100644
--- a/src/app/shared/login.service.ts
+++ b/src/app/shared/login.service.ts
@@ -78,9 +78,12 @@ export class LoginService {
       let item: any = part.split('=');
       result[item[0]] = decodeURIComponent(item[1]);
     });
+
     if (result['error']) {
       this.notifications.message({ message: result['error'], type: NotificationType.DANGER } as Notification);
-    } else if (result['token_json']) {
+    }
+
+    if (result['token_json']) {
       // Handle the case that this is a login
       this.authService.logIn(result['token_json']);
       this.authService
```

I think this seems to make sense from what we understand about the context of this `error` URL param.

**Comment by andrewazores** [comment]
PR opened: https://github.com/fabric8-ui/fabric8-ui/pull/2779
