### ISSUE TITLE
Roundabout work item linking process

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#3147]
Currrent behavior:
1. We have a huge plus sign with the following text -'Work Item Links' and 'There are no items linked to this issue'. All of this seems redundant as the number highlighted in blue, next to links, mentions 0.
![screenshot from 2018-04-16 15-06-16](https://user-images.githubusercontent.com/16647625/38803825-01387fec-418e-11e8-9ff4-14e7f052fdda.png)

2. Then there is a Create link button which takes you to the what is shown in the screenshot below:
![screenshot from 2018-04-16 15-06-37](https://user-images.githubusercontent.com/16647625/38803836-06e9db02-418e-11e8-98b0-5fe2dd152173.png)

Suggested behavior:
Similar to the assign labels, we could probably have 2 sections: Create links and Existing links. Create links could have the information shown in the Screenshot above. Existing links (currently 'links') could display the existing links for the WI.  
If required, to maintain consistency it was suggested that the labels section too could have the create label on top and existing labels below it.

**Comment by rgarg1** [comment]
I agree with @Preeticp POV that this section needs a UX rethink.

**Comment by Veethika** [comment]
@Preeticp @rgarg1 @sunilmalagi 
Proposed solution:
1. For the very first time the user has to be introduced to the concept of linking, hence the following should appear:
<img width="667" alt="screen shot 2018-05-10 at 10 16 14 pm" src="https://user-images.githubusercontent.com/35127763/39985064-d543a904-577a-11e8-855c-363a428fab11.png">
[This screenshot is consistent with the new design language]
Clicking on 'Create Link' will take them to another layer where they could link items.


2. However, if the user has created a link once, next time they should directly be able to link without seeing the previous layer, and it would be followed by the list of existing links:
<img width="671" alt="screen shot 2018-05-10 at 11 32 33 am" src="https://user-images.githubusercontent.com/35127763/39985357-0b72e2d2-577c-11e8-8c2b-22f4e09871f7.png">

**Comment by Preeticp** [comment]
@Veethika, the overall solution seems fine.
Regarding Point No. 1.  - Happy to see the big plus sign going away.
However, imho the text 'Work Item Links' can be done away with too. It is clear to the user that the preview or detailed view is for the work item. In the other fields we do not say work item assignee, work item labels etc. So it would be consistent with the rest of the preview too, plus it would reduce the need for the user to unnecessarily scroll down.

Suggestion - Remove 'Work Item Links' from the screen and modify 'There are no items linked to this issue' to 'There are no work items linked to this issue', that is, if we really want to emphasize that the linking refers to work items.
Wdyt?

**Comment by Veethika** [comment]
I agree to your suggestion @Preeticp . 'There are no work items linked to this issue' gives more clarity, and we could do away with 'Work Item Links'.
Unless its a consistent structure we're following here @catrobson?

**Comment by Veethika** [comment]
Removing myself and assigning @sunilmalagi as he's been actively working on this story:
(a work in progress) - https://redhat.invisionapp.com/share/BAN4UOBQHSN#/314308013_AddLink_01

**Comment by Veethika** [comment]
Removing UX tags as the UX solution has been provided and discussed with the team.

**Comment by nimishamukherjee** [comment]
The updated link creation is on prod.
