### ISSUE TITLE
"My work items" in dashboard rendering badly

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#315]
Right after logging in, we're take to the dashboard with Recent Spaces, My work Items and recent active pipelines. The "My work items" part of this is rendering oddly. The first screenshot shows how the title of the work items seems to be overwriting a hash. The second shows multiple work items doing the same. I highlighted the title to see what exactly it said.

![workitemerror](https://user-images.githubusercontent.com/926572/27844640-8f28b842-6167-11e7-91e8-235f4dabe745.png)

![workitemsrendering](https://user-images.githubusercontent.com/926572/27844644-94f647d0-6167-11e7-9ff7-c36a79de6bbb.png)

**Comment by joshuawilson** [comment]
This issue was moved to fabric8-ui/fabric8-ui#1630

**Comment by michaelkleinhenz** [comment]
Already fixed. Was incorrect usage of id vs issue number.
