### ISSUE TITLE
Wireframe:  Feature flags revisit (5)

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#3150]
Revisit the feature flags placement on pages that have features that are under a flag.  The floating action button has been identified as not the best design for this purpose, so explore a few other placements and experiences for it.

Verification Criteria:
- [x] Create wireframes for new designs in Slack, upload to Google Drive
- [x] Upload to InVision.  Share with UXD, Eng, PM.
- [ ] Come to conclusion on which design to move forward with, and archive all other options.
- [ ] Create UI development stories for implementation of the new design

**Comment by stooke** [comment]
I'm not sure if this is the best place for me to make this comment, but the feature flag is more useful than has been articulated.   In fact, with a different user interface, this can be used to enable 'pro' features or other such user category-enabled features.  So the user interface is crucial, but also  should be as non-intrusive as possible.

**Comment by corinnekrych** [comment]
@mceledonia recently we've introduced a new rollout strategy with @xcoulon see: https://github.com/fabric8-ui/fabric8-ui/wiki/fabric8-toggles#enable-by-emails we can display a WIP feature to a set of users only. Should those features be displayed in the floating icon? 
note that atm, we display only enableByLevel features.

**Comment by corinnekrych** [comment]
@catrobson the features (enableByEmail) will be retrieved from the backend API call from fabric8-toggles-service but atm will not be displayed in the UI FAB button as they do not match any "level". It's either you use the enableByLevel strategy or the enabeByEmail.
Note that the anableByEmail was created for WIP feature. so it might just be ok not to have them displayed int he FAB button.
cc @xcoulon

**Comment by catrobson** [comment]
+1 - I think we can just not show these features in the FAB.

**Comment by mceledonia** [comment]
This has been abbreviated for Summit here #3332 and will be revisited/refined further post-summit.
