### ISSUE TITLE
On an issue's detail page, the links aren't links

### ISSUE THREAD

**Issue by nickboldt** [openshiftio/openshift.io#3162]
On a page like https://openshift.io/openshiftio/eclipse-che/plan/detail/57 I see there's a link to its parent issue in the details pane on the right side. But that link isn't a clickable link -- I can highlight it, but I can't click on it to get back to https://openshift.io/openshiftio/eclipse-che/plan/detail/41

This is kinda lame, since if I look in the preview view, the links DO work:

![image](https://user-images.githubusercontent.com/227597/38830622-ea80b06a-418a-11e8-8aca-fee6c9df1c07.png)

**Comment by GeorgeActon** [comment]
@nickboldt can you recheck this. I tested using your example and the links worked.

**Comment by nimishamukherjee** [comment]
Closing this issue as PR https://github.com/fabric8-ui/fabric8-planner/pull/2652 fixed this issue.
