### ISSUE TITLE
Re-examine refresh flows for connected accounts

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#3164]
The refresh flows for connected user accounts - namely Github and Openshift - were discussed in [this PR](https://github.com/fabric8-ui/fabric8-ui/pull/2711) and are being formalised here. 

Regarding Github, when a user refreshes their account, this necessarily causes a page redirect. Why was this done ? Need it always be this way ? The current behaviour at the time of writing is defined [here](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/connected-accounts/connected-accounts.component.ts#L71). Notice that one method, refreshGitHub(), simply calls connectGithub() then returns. Is there no semantic difference between the two ? 

Regarding Openshift, as @alexeykazakov pointed out in the linked PR, when refreshing Openshift, OSIO should redirect the user to OpenShift Online. If the user is already logged in to OSO then the user should be redirected back to OSIO. If not, then OSO should redirect them to developers.redhat.com for logging and then back to OSO and OSIO. There should not be any temporary or permanent inaccessibility of the account during this process.

At the time of writing, the implementation for refresh can be seen [here](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/connected-accounts/connected-accounts.component.ts#L84). This involves disconnecting Openshift, which contradicts the earlier description of the desired behaviour.

It seems like the correct functionality would involve making an immediate redirect to Openshift, determining whether or not the user was logged in, then taking the appropriate route from there, as oppose to automatically disconnecting the user and having them enter their credentials.

**Comment by alexeykazakov** [comment]
GitHub and OSO account linking is basically a regular OAuth2 login flow.
It involves redirecting users to GH/OSO to login then back to OSIO.
We don't control logins on the OSO or GitHub sides. It's up to OSO/GitHub to handle it.

Please note that re-connecting an account users the same flow/API as connecting it the very first time. If the connection already exists then we will update the stored token. So, it works as re-connection.

**Comment by chrislessard** [comment]
@alexeykazakov Understood. Are the words "refresh" and "reconnect" interchangeable in this context ? Also, do you think the current approach for refreshing OSO - in which the user is disconnected first, then reconnected - should be changed ?

**Comment by alexeykazakov** [comment]
> Are the words "refresh" and "reconnect" interchangeable in this context ? 

Yes.

> do you think the current approach for refreshing OSO - in which the user is disconnected first, then reconnected - should be changed ?

The disconnection step is just not needed here. It doesn't break anything but it's just not needed. It used to be required but not anymore.
