### ISSUE TITLE
Update Documentation for Status Dropdown Removal

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#3165]
As part of https://github.com/openshiftio/openshift.io/issues/2859, the Status Dropdown will be removed from the OpenShift.io UI. This needs to be reflected in the documentation.

**Comment by mishaone** [comment]
PR created and merged to remove the references and screenshots of the tenant status: https://github.com/fabric8io/fabric8-online-docs/pull/279
