### ISSUE TITLE
The audit log data for failed workers is not in DB

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#3166]
_From @tuxdna on March 22, 2018 13:7_

We have BookKeeping API to retrieve worker results for give EPVs. However when a worker fails, all we get is None for `started_at` / `ended_at`.

Here is an example when GraphImporterTask fails:

https://gist.github.com/tuxdna/b49a3ea484177a0cb53c4960ef9b6c59#file-gantt_charts-ipynb

We need a way to store worker audit log irrespective of whether a worker succeeded or not. This is essential for monitoring, inspection and debugging.

_Copied from original issue: fabric8-analytics/fabric8-analytics-worker#589_

**Comment by CermakM** [comment]
The root cause of this issue has been localized and the solution is in progress.

**Comment by msrb** [comment]
PR merged, thanks :wink:
