### ISSUE TITLE
Sort filter values in alphabetical order

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3169]
Area/Assignee/Creator/Label names listed in the Planner's filter toolbar are not sorted in any order and looking up an area in a big list could be user unfriendly.

The lists should be sorted in an alphabetical order for easy accessibility.

**Comment by debloper** [comment]
Duplicate of #2604

**Comment by debloper** [comment]
Can you please verify the PR https://github.com/fabric8-ui/fabric8-planner/pull/2524
If this works for you for the WI types, I can just extend it for other filters and update the PR.

**Comment by jarifibrahim** [comment]
Fixed via https://github.com/fabric8-ui/fabric8-planner/pull/2524
