### ISSUE TITLE
Intermittent issue - attempting to view Jenkins build log fails 

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3176]
Seeing this issue intermittently today - when attempting to view a running build pipeline's Jenkins build log:

```
{"error":"invalid_request","error_description":"The request is missing a required 
parameter, includes an invalid parameter value, includes a parameter more than 
once, or is otherwise malformed.","state":"MDUxYWVhYzMtOGNlNy00"}"}
```
Workaround - trying a second time seems to work every time.

**Comment by quintesse** [comment]
I'm getting the exact same thing, but trying a second time (or third or ...) never works for me. I haven't been able to get into Jenkins for over a week now making testing nigh on impossible.

**Comment by ldimaggi** [comment]
Are you seeing an error? Or, are you presented with a Jenkins login page through which you cannot login? Can you attached a screenshot? Thx!

**Comment by ldimaggi** [comment]
Can you try this with an incognito window?

**Comment by quintesse** [comment]
I always work with an incognito window because the user used for OSIO conflicts with my regular users I use everywhere else. So everything I've said here is using incognito windows.

**Comment by ldimaggi** [comment]
Closing as duplicate of #2752

**Comment by ldimaggi** [comment]
The issues that Tako is seeing are unique to his user account in OSO - there is no Jenkins project. He will log a separate issue to track his account problem.
