### ISSUE TITLE
Quick Preview for Work Items in Planner

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#318]
# Description
As a user, I want to use a quick preview of the details of a work item from the query result in either the list or board view.

# Acceptance Criteria
- [ ] The user can navigate to the quick preview from list entry in the list view.
- [ ] The user can navigate to the quick preview from the card entry in the board view.
- [ ] The interaction for opening the quick preview does not interfere with list or board operations on the respective context views.
- [ ] The quick preview is displayed while leaving the source view (list view or board view) displayed and open for interaction.
- [ ] The quick preview contains all editable and non-editable information as the existing quick preview.
- [ ] The quick preview can be closed by the user. Upon closing, the original context (list view or board view) remains unchanged.

**Note**: The existing detail view becomes the quick preview. The story is listed here because the change of context for this component as well as the change in ways of opening the quick preview.

**Note**: Opening the quick preview may not interfere with list or board operations. Therefore, opening the quick preview must be implemented using an icon, doubleclick or a different mechanism as a single click will only select the entry (see the list view and board view stories for details).
 
# Relationships
_Put linked Team/Product story links here_

**Comment by sdash-redhat** [comment]
Refer Interaction Design notes 
slide 110 -> 117 - https://redhat.invisionapp.com/share/6RCWHA1TX

Visual Design Notes: 
https://redhat.invisionapp.com/share/HTCX31SWC
(VD work in progress)

Note: the text, data points were shown are for reference purpose to illustrate the interaction, based on actual data points there may be changes on how the screen might appear in real time post implementation.
