### ISSUE TITLE
Discussion on optimizations on ngrx implementation

### ISSUE THREAD

**Issue by debloper** [openshiftio/openshift.io#3184]
Participants: @christianvogt @sanbornsen @joshuawilson @rohitkrai03 @debloper

- Caching/concurrency issue with data store (needs SSE/Socket.IO)
- Transformation of fetched data and at which level (computed values)
- Normalization of data to avoid unnecessary re-renders
- Whether it's worth moving away from 2-way data binding to unidirectional data (Joshua)

**Comment by sanbornsen** [comment]
We are ahead of this discussion and things are in place right now. We don't need this thread anymore.
