### ISSUE TITLE
Query Language for Entities

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#319]
# Description
As a user, I want to use a powerful yet flexible query language to query for Work Items in the Planner.

# Acceptance Criteria
- [ ] There is a query language available for creating complex search expressions.
- [ ] The query language can use all attributes of Work Items as keys in expression terms, this includes Area, Assignee, Work Item Type, Iteration, Work Item State, Iteration Path, Area Path and IDs.
- [ ] The query language supports logical NOT, AND and OR of expression terms.
- [ ] The query language supports bracketing.
- [ ] The query language is human-readable.

**Note**: The query language is the base of the query-based approach of the Planner. This story is the base of the approach to make the Planner modelled around a query model, with all filtering and selecting being normalized to queries and all browsing normalized to query result displays.

**Note**: The query language is only used in the API communication between the client and service, but **may** be exposed at some point to the user for creating powerful search expressions without UI overhead. So the query language should be human-readable to make debugging and development easier, but it being human-writable is an optional goal. There may be a mapping of some kind in the future. For now, development speed is more important here, so we need something that is easily readable and writable by software.
 
# Relationships
_Put linked Team/Product story links here_

**Comment by xcoulon** [comment]
Once a grammar has been defined, we could look at https://github.com/mna/pigeon/ on the server-side to parse the query.

**Comment by ldimaggi** [comment]
Just to confirm, the query language provides READ-ONLY access to data - it will not support UPDATE or DELETE operations, either within the API or later on when we expose it to end-users, yes?

**Comment by ldimaggi** [comment]
Will the query language function as the "engine" for any queries performed in the UI, for example the display and/or filtering of workitems? The point I am making is that it would be best if the query language was the single means by which queries were performed.

**Comment by joshuawilson** [comment]
I think that is the plan

**Comment by michaelkleinhenz** [comment]
Yes it is. The Planner becomes more or less a browsing tool. Everything is centered around the query.
