### ISSUE TITLE
Create new Space is broken

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/openshift.io#3191]
I am getting errors when creating a new space in prod-preview: 
HTTP Error 500: `{"errors":[{"code":"unknown_error","detail":"EOF","status":"500","title":"Unknown error"}]}`

**Comment by gastaldi** [comment]
@sbose78 can you have a look at this? This is breaking our integration tests

**Comment by gastaldi** [comment]
Sentry issue: https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-wit/issues/3247/

**Comment by alexeykazakov** [comment]
Caused by https://github.com/fabric8-services/fabric8-wit/commit/f704d8cbd38e1ef04e923a0127cc176f96e165c6
