### ISSUE TITLE
Add support for package-lock.json in mercator

### ISSUE THREAD

**Issue by abs51295** [openshiftio/openshift.io#3192]
Currently, we only support `npm-shrinkwrap.json` in mercator as a [lock file](https://github.com/fabric8-analytics/mercator-go/blob/master/handler_templates/handler_npm#L6) for `package.json`. Since npm@5 a new lock file [package-lock.json](https://docs.npmjs.com/files/package-lock.json) was introduced and hence we need to support that as well.

**Comment by msrb** [comment]
This should be easy. According to the docs, `package-lock.json` and `npm-shrinkwrap.json` should be identical: https://docs.npmjs.com/files/shrinkwrap.json.

**Comment by abs51295** [comment]
@msrb while we work on adding support in mercator, I worked on a hack to add support for `package-lock.json` in https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/612.

**Comment by GeorgeActon** [comment]
@msrb is this closed?

**Comment by pkajaba** [comment]
@GeorgeActon PR is still waiting for review. From mercator point of view, it should be complete. @abs51295 can you elaborate?

**Comment by abs51295** [comment]
PR has been merged. Closing the issue @pkajaba. Thanks for the fix 👍
