### ISSUE TITLE
Different toast notifications in Analytics and Planner 

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3193]
The notifications used in Analytics and Planner look different and are also different functionally. From the user experience perspective, the look and feel across OSIO pages should be uniform.

# Analytics notifications
- Gray and white in color
- Close button

# Planner notifications
- Green and white in color
- No close button

![analytics notification](https://user-images.githubusercontent.com/28748448/38975985-6852a630-43cd-11e8-9f43-34b9569babed.png)

![planner notification](https://user-images.githubusercontent.com/28748448/38975987-6c7c34e2-43cd-11e8-9272-1653e6e28e45.png)

**Comment by rgarg1** [comment]
Cc @catrobson @SMahil

**Comment by catrobson** [comment]
We should be taking notifications directly from patternfly-ng for all UI components of OpenShift.io:
https://rawgit.com/patternfly/patternfly-ng/master-dist/dist-demo/#/toastnotification

**Comment by miteshvp** [comment]
@jyasveer @invincibleJai @arunkumars08 - can one of PTAL here?

**Comment by sivaavkd** [comment]
Is this really a Sev2?  There is some inconsistency reported, but no loss of functionality.  Seems more like a Sev3 to me, may be with more priority than other Sev3s.

**Comment by rgarg1** [comment]
@sivaavkd I agree that this is a Sev-3, but in the absence of a priority metric, I had to tag it with Sev-2 to attract faster traction. The Sev metric that we use for OSIO is a confused mix of Severity and Priority :(

**Comment by sivaavkd** [comment]
@miteshvp I just tested this and feedback submission is not showing any notification.  And notification when creating work item is consistent with planner notification.  I think we can close this, can you please review ? cc @rgarg1

**Comment by rgarg1** [comment]
@sivaavkd 

With the changes, the analytics notification may appear similar to the Planner one, but it is not the same. (e.g. The Planner notification don't allow manual close, whereas Analytics one does).
This defect was raised to ensure we provide a consistent experience to our users, irrespective of the component they use. I don't intend to say that which one is better, just that we should have consistency in user experience.

**Comment by invincibleJai** [comment]
@rgarg1 I feel both are consistent with patternfly specification as mentioned by @catrobson.

https://www.patternfly.org/pattern-library/communication/toast-notifications/

In Stack report toast notification has an action associated i.e "View Work item" so close icon would be appropriate here I believe as we just can't hide it after few seconds. Unlike Planner Toast notification which is more like info sharing not intended to take any associated action.

Let me know your thoughts cc @sivaavkd 

<img width="1656" alt="screen shot 2018-08-31 at 12 28 00 pm" src="https://user-images.githubusercontent.com/5129024/44897474-75fb6f00-ad19-11e8-9037-7abf009cbb7a.png">

**Comment by miteshvp** [comment]
@sivaavkd - any updates here?

**Comment by Bob-Davis** [comment]
This looks good - Thanks.

Bob

**Comment by sivaavkd** [comment]
Closing the issue after discussing with PM (Bob) -- Thanks,
