### ISSUE TITLE
Analytics 'thumb' feedback button has no feedback

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3194]
The detailed stack analysis reports has _Thumbs up_ & _Thumbs down_ buttons to register user feedback, but clicking on those two buttons result in no feedback from the buttons that the feedback was actually registered. The only feedback is in form of the toast notification that shows up on top of the page, far from the buttons itself.

Expectations:
The buttons can either turn solid, to indicate a feedback was registered, or whatever UX suggests

Cc @catrobson

**Comment by rgarg1** [comment]
Additionally, it would help if it has an info-tip that explains how that feedback is going to be used? Is that going to reflect on the dependency's Github page? Or it's purely internal for analytics consumption purposes. This needs to be made explicit.

**Comment by sara-02** [comment]
@rgarg1 Currrently we are just storing the feedback per stack_id. We are currently not running any analysis on the feedback, but it will be purely for internal purpose/internal analytics consumption. 
As for the UI changes @arunkumars08 should be able to help you.

**Comment by catrobson** [comment]
@parvathyvr Can you take a look at this?

**Comment by parvathyvr** [comment]
@catrobson @arunkumars08 @rgarg1 
The behaviour of the feedback button is defined in this Invision link.
https://redhat.invisionapp.com/share/JTF8802X6#/272279341_ScreenV2_02
The feedback buttons change colors as shown in the link when the user clicks on it.

**Comment by arunkumars08** [comment]
@rgarg1 As per UX, the intention is to turn the clicked thumbs solid. I think that is missed.
But to your other point of how it is used, as @sara-02 has already mentioned, currently it is just for internal references and purposes.

**Comment by rgarg1** [comment]
@arunkumars08 Thanks for confirming the _feedback_ defect.

As far as the feedback usage is concerned, I raised that question because we are not letting our users know what this feedback means. We need to insert an info-tip (maybe) to indicate the meaning and usage of the feedback.

**Comment by arunkumars08** [comment]
@rgarg1 Oh, I understand that point. @parvathyvr is there something we can do here?

**Comment by parvathyvr** [comment]
@rgarg1 @arunkumars08 I feel the feedback button is self explanatory and since the usage of the user feedback at this point is only for internal analytics consumption,i am not sure if we should show an info tip to the user about it.So may be we can drop the idea for now.
Also after validating with some real users,if a need arises to show the info tip we can introduce that
at a later point in time.
@catrobson is this approach fine?

**Comment by sara-02** [comment]
@parvathyvr +1, we don't have any formula or usage information to display as this moment, and we don't know yet how many users will feedback for us to have any useful to start with.

**Comment by sara-02** [comment]
As fas as UI changes are concerned, instead of showing the info-bar that comes at the top we can simply turn the color solid, a green for thumbs up, and read for thumbs down.

**Comment by catrobson** [comment]
@parvathyvr - All icons should have at least a basic info tip for accessibility reasons.  Even if doesn't really explain the formula impact, having a user friendly description of what this icon is will be necessary.

**Comment by arunkumars08** [comment]
Closing this as changes are pushed to prod long time back.
