### ISSUE TITLE
Extra space in header when moving from settings to plan tab

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3200]
Steps:
- Click settings
- Now click Plan tab
![screenshot from 2018-04-19 16-55-20](https://user-images.githubusercontent.com/34271052/38988892-7fb3e4c2-43f2-11e8-98f8-3921d85bf90e.png)

**Comment by sunilmalagi** [comment]
Looks like the issue got resolved, I dont see any extra space when you toggle from 'Settings' to Plan tab.. UI issue got fixed.

**Comment by Raunak1203** [comment]
Issue is fixed. Hence, closing this issue
