### ISSUE TITLE
While waiting for a build to finish, i seem to have been logged out without any user notice.

### ISSUE THREAD

**Issue by mmclanerh** [openshiftio/openshift.io#3204]
Appears I am logged out after ~10 minutes, while waiting for build to complete:

![image](https://user-images.githubusercontent.com/33727536/38994446-b49c52c0-43e6-11e8-86aa-9dcf65d59d28.png)

**Comment by alexeykazakov** [comment]
@mmclanerh by any chance you can tell what request returned this 401? In network tab.

**Comment by mmclanerh** [comment]
hmm. unfortunately no, was about a week ago.  i should get in the habit of running a constant inspection when testing.  this might also be good to tie into the errortracker (sentry) via breadcrumb logging on exception:
https://sentry.io/features/breadcrumbs/

**Comment by alexeykazakov** [comment]
First at all I'm sure it's not Auth service issue. 
Looks like an issue in pipeline UI. And https://github.com/openshiftio/openshift.io/issues/3325 on top of that.
@mmclanerh Pipeline UI has changed a few times for the last week. It's really hard to say what request caused that 401 error. I'm going to close this issue but please re-open it if/when you see it again. Debug info from network tab could help a lot.

The issue with logging out users if 401 is received is tracked here - https://github.com/openshiftio/openshift.io/issues/3325
