### ISSUE TITLE
Shortcut Query Type Hierarchy UI Section in Sidebar of Planner

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#321]
# Description
As a user, I want to use meaningful shortcuts derived from the type hierarchy based on the current Space template to be available in all view contexts to make it easy to get to commonly used views of my Work Items. 

# Acceptance Criteria
- [ ] In the sidebar, there is a section containing type hierarchy criterias.
- [ ] The section contains a criteria "Portfolio" that, when activated, filters WIs for WITs of the Portfolio level of the type hierarchy.
- [ ] The section contains a criteria "Requirements" that, when activated, filters WIs for WITs of the Requirements level of the type hierarchy.
- [ ] There is no way of resetting/unsetting the current selection. The user needs to choose another option of the sidebar resulting in a different query to leave/reset the type hierachy query section.
- [ ] Clicking on an option/criteria resets the current contexts (list view or board view) search/filter criteria and sets the selected Work Item Type(s) as the sole criteria for the context view.
- [ ] Clicking on an criteria highlights the value and the criteria header.
- [ ] Only one single criteria can be active at any one time. If a new criteria is selected, the prior criteria gets deselected.
- [ ] The selected criteria is also displayed on the search/filter toolbar as a criteria.
- [ ] Adding additional criterias using the search/filter toolbar deselects the active criteria.

**Note**: The described section is only one of a few ways of specifiying a search request.

# Relationships
* Type hierarchy story: #331

**Comment by sdash-redhat** [comment]
Refer Interaction Design notes
slide 22 -> 31 - https://redhat.invisionapp.com/share/6RCWHA1TX

Visual Design Notes:
https://redhat.invisionapp.com/share/HTCX31SWC
(VD work in progress)

Note: the text, data points were shown are for reference purpose to illustrate the interaction, based on actual data points there may be changes on how the screen might appear in real time post implementation.

**Comment by sdash-redhat** [comment]
Refer Interaction Design notes 
slide 110 -> 117 - https://redhat.invisionapp.com/share/6RCWHA1TX

Visual Design Notes: 
https://redhat.invisionapp.com/share/HTCX31SWC
(VD work in progress)

Note: the text, data points were shown are for reference purpose to illustrate the interaction, based on actual data points there may be changes on how the screen might appear in real time post implementation.
