### ISSUE TITLE
Create a new quickStart project alignment issue(in application wizard)

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3210]
Steps:

- Click on create new application
- Create a new quickStart project
- In application wizard Steps1, "Spring Boot Health Check" is not align properly
![screenshot from 2018-04-20 11-02-44](https://user-images.githubusercontent.com/34271052/39032387-e5cd3356-448a-11e8-8ca0-14ee059e0cbb.png)

**Comment by invincibleJai** [comment]
closing it as new launcher flow is in production now.
