### ISSUE TITLE
Work Item Overview is not updating when selecting other spaces(analyze dashboard)

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3217]
Steps:

- Click on Analyse tab
- It shows workitem
- Now select other space 
WorkItem are not updated in analyze tab
![analyse](https://user-images.githubusercontent.com/34271052/39170908-c1a41534-47ba-11e8-80f6-cf2466b90e85.gif)

**Comment by rgarg1** [comment]
Cc @joshuawilson

**Comment by joshuawilson** [comment]
This is under the Internal Feature flag (under development and should not be reported on). Closing.
