### ISSUE TITLE
Newly added area is not in quick preview area dropdown

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3220]
Steps:
 -Open setting
- Add a new child area
- Now click on plan tab
- Click on work Item title to open quick preview
- Click area dropdown
- Newly created are is not in the list..
Now refresh the page and again try adding, area is in the list

**Comment by jarifibrahim** [comment]
@Raunak1203 I cannot reproduce the bug. Can you please try reproducing it again?
This https://github.com/fabric8-ui/fabric8-planner/pull/2622 was merged few hours ago and it might have fixed it.

**Comment by Raunak1203** [comment]
Yes working now.
Closing the issue
