### ISSUE TITLE
Space name does not persist while switching to new space wizard

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3224]
While creating a new space, the switch from old wizard to the new wizard is not smooth and has a few issues:

- [ ] Not entering any space name on the old wizard and directly clinking the option _New Create Space Experience_ leads to an error _Name is required for space_. User should be allowed to switch to the new wizard without the error
- [ ] Clicking on the option _New Create Space Experience_ for the second time takes the user successfully to the new wizard. What happened to the error in the previous step?
- [ ] Any name that the user entered on the old space wizard, before clicking the option _New Create Space Experience_, does NOT reflect on the new wizard. The space name provided is lost and has to be re-entered

See the attached GIF for a peek into all the issues mentioned above.
![new space wizard](https://user-images.githubusercontent.com/28748448/39042838-8508fc7a-44a9-11e8-851f-7d8097f6db12.gif)

**Comment by nimishamukherjee** [comment]
Closing this as  there is a single experience now.
