### ISSUE TITLE
Adding new Work Items using Dialog Add in Planner

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#323]
# Description
As a user, I want to add new Work Items to my current Space using a dialog that offers all settings and attributes that are available on the new Work Item and it's selected Work Item Type.

# Acceptance Criteria
- [ ] The user can navigate to a New Work Item dialog.
- [ ] using the dialog, the user can add new Work Items.
- [ ] The dialog is displayed full screen and without context view (board view/list view).
- [ ] For the new Work Item, there will be no context honored or recognized.
- [ ] All changeable or initial attribute values, including the Work Item Type, are selected in the dialog.

**Note**: This story describes a dialog-based way of adding new Work Items. This differs from the quick add as this provides a "full fledged" create dialog that is not recognizing the current context. Therefore this dialog is also full-screen and (possibly) re-using the full-screen detail view.

**Note**: The attributes of Work Items are different based on the selected Work Item Type. To make this dialog easy to use, we need a proper UX for making this work. The current way of a "two-step-process" with selecting the type first is not user friendly.
 
# Relationships
_Put linked Team/Product story links here_

**Comment by sdash-redhat** [comment]
This is no more valid. There are only 2 ways to add item 
1. Through quick add at the top of the details panel
2. child item for any item 

However, the user can edit the item and add / modify the item


Refer Interaction Design notes 
slide 68 -> 94 - https://redhat.invisionapp.com/share/6RCWHA1TX

Visual Design Notes: 
https://redhat.invisionapp.com/share/HTCX31SWC
(VD work in progress)

Note: the text, data points were shown are for reference purpose to illustrate the interaction, based on actual data points there may be changes on how the screen might appear in real time post implementation.

**Comment by michaelkleinhenz** [comment]
Sorry, but this does not make any sense. I, as a user of the system want a proper editor to edit my issue while creating it. It does not make sense at all to force the user to cram the full description into a short one-line input field or force him to do a two-step process by first creating an item, then opening it again to get into a proper editor. This does not follow a normal developer or product manager workflow.

**Comment by sdash-redhat** [comment]
As per our discussions with Todd, remember he specifically wanted to remove the detailed entry option as it was more common to 'quickly create' and later if wanted can edit to add more flesh to it in a detailed view. The quick add can have the description field an text area initially single line and incrementally grow to some extent. But fully rich editing would be possible in the detailed view.  Would you like to have a follow up on this with him?
