### ISSUE TITLE
[worker-scaler] the API version in the data (extensions/v1beta1) does not match the expected API version (apps.openshift.io/v1)

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#3233]
# Description

version: 9f3d9230c2c96f47ad23c670be25e63b71035685

I can see following error message in both staging and prod:

```
error: Scaling the resource failed with: the API version in the data (extensions/v1beta1) does not match the expected API version (apps.openshift.io/v1); Current resource version Unknown
```

**Comment by humaton** [comment]
I have found this BZ https://bugzilla.redhat.com/show_bug.cgi?id=1543357

**Comment by humaton** [comment]
The latest master build should have a correct version of origin-clients and this issue should be resolved.

**Comment by humaton** [comment]
@msrb can you please verify and close if that is the case?

**Comment by msrb** [comment]
This is in prod already, closing.
