### ISSUE TITLE
Config map - vert.x  quickstart/booster fails to build

### ISSUE THREAD

**Issue by animuk** [openshiftio/openshift.io#3235]
When, pipeline build is completed and user clicks on the application link, the sample service is not behaving as expected. It says "unable to read the configuration" in prod.
![un](https://user-images.githubusercontent.com/11207106/39116121-37e7c534-4701-11e8-87fa-07db43a77dcd.png)

**Comment by gastaldi** [comment]
Prod is not updated yet: https://github.com/openshiftio/saas-launchpad/pull/94

**Comment by gastaldi** [comment]
@animuk production was updated. Please retest

**Comment by joshuawilson** [comment]
@animuk please do NOT assign issues to people unless they are actively working it. If you want to get someones attention, please use @ mentions in the comments.

**Comment by gastaldi** [comment]
Assigning back to @animuk

**Comment by animuk** [comment]
thanks @gastaldi . This is working now in prod. closing this
