### ISSUE TITLE
Context Views for Planner

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#324]
# Description
As a user, I want to view my Work Items in a structured way. I want to have different visual representations for different usecases on the same data.

# Acceptance Criteria
- [ ] The user can switch between a list view and a board view of Work Items using the menu navigation.
- [ ] The current query/filter context is persistent when switching between context views. This includes the query/filter toolbar as well as the sidebar query sections.
- [ ] All of the context views present the same data in the same context, but with a different visual representation and possibly different ways of interaction.

**Note**: There might be more context views at a later point.
 
# Relationships
_Put linked Team/Product story links here_

**Comment by sdash-redhat** [comment]
Refer Interaction Design notes 
slide 42 & 44 - https://redhat.invisionapp.com/share/6RCWHA1TX

Visual Design Notes: 
https://redhat.invisionapp.com/share/HTCX31SWC
(VD work in progress)
