### ISSUE TITLE
Wrong code metrics data found for the following E/P/V on STAGE S3: maven/io.vertx:vertx-core/3.3.3

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#3243]
The code_metrics.json contains just the following entry, nothing else:

```
{
  "version_id": "7sh8WzgCKPVMXH_VzLE0TMvaeAxYiWtr"
}
```

Expected content:

something similar to:

```
{
  "_audit": {
    "ended_at": "2017-03-04T01:23:28.404808",
    "started_at": "2017-03-04T01:23:08.793921",
    "version": "v1"
  },
  "_release": "maven:io.vertx:vertx-core:3.3.3",
  "details": {
    "languages": [
      {
        "blank_lines": 9187,
        "code_lines": 42374,
        "comment_lines": 27876,
        "files_count": 440,
        "language": "Java"
      },
      {
        "blank_lines": 0,
        "code_lines": 18,
        "comment_lines": 0,
        "files_count": 1,
        "language": "JSON"
      }
    ]
  },
  "schema": {
    "name": "code_metrics",
    "version": "1-0-0"
  },
  "status": "success",
  "summary": {
    "blank_lines": 9187,
    "code_lines": 42392,
    "comment_lines": 27876,
    "total_files": 441,
    "total_lines": 79455
  }
}
```

**Comment by tisnik** [comment]
@msrb WDYT? Is it anything that could be easily verified & fixed?

**Comment by miteshvp** [comment]
@msrb since we are no longer using the code metrics statistics, WDYT of tweaking the integration tests to remove them?

**Comment by msrb** [comment]
+1 for not checking code metrics data on S3. We don't collect the data any more. It's perfectly fine to report these kind of issues, we can clean them up in future (ideally all at once).

**Comment by tisnik** [comment]
Thanks @miteshvp @msrb for clarification, I've comment out the tests accordingly :)

**Comment by tisnik** [comment]
@msrb @miteshvp I've found the same issue for digests metadata (the same E/P/V). Would you recommend to create new issue for this? Presumably other metadata will be empty as well (but tests are not finished yet).

**Comment by miteshvp** [comment]
Closing this since we use different set of E/P/V for testing.
