### ISSUE TITLE
Planner SCRUM template is confusing

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3245]
Now that the space templates are ready, the new SCRUM template is available for use in Planner, at least for now in Prod-preview. Here is a peek into how the hierarchy looks like currently:

![scrum_template_issue](https://user-images.githubusercontent.com/28748448/39128163-b3f5fd12-4724-11e8-87b5-ca636aad7816.png)

I've been a SCRUM user for many years, but this template confuses me due to following reasons:

- **Themes** are missing and _Epics_ are at the highest level of granularity
- **Stories** are missing and I see a little known (alright VSO uses it) work item type _Product Backlog Item_ in its place
**Sources:** 
https://www.scruminc.com/product-backlog/ 
https://www.scrum.org/resources/what-is-a-product-backlog

- The page itself is labeled as _Backlog_, so having a work item type _Product Backlog Item_ does not makes sense

- I don't know what Features mean

- The heirarchy that is most popular:
Themes
           |
           Epics
                   |
                   Stories

Using a heirarchy that does not uses popular terms adds an additional requirement for me to learn yet another template, whereas the purpose of implementing SCRUM template was to cater to existing SCRUM users.

**Comment by michaelkleinhenz** [comment]
https://www.scruminc.com/product-backlog-item-pbi/ talks about PBI being a generic term for all entities in the backlog, like Epic, Story etc. 

But apart from any specific naming of entities, the template we offer should resemble a "best-of-breed" approach that matches the most common use of a backlog and the most commonly used WITs.

**Comment by kwk** [comment]
@rgarg1 I'm just the messenger. The grouping was done here: https://docs.google.com/presentation/d/18xKQmkf3UKlGoP7qLqUnrIYiflza674n_paUZXKuepA/edit#slide=id.g3758dca8f8_0_53

**Comment by qodfathr** [comment]
See also http://www.scrumguides.org/scrum-guide.html#artifacts-productbacklog

**Comment by stevengutz** [comment]
I definitely don't object to using a product backlog and sprint backlog (also potentially a defect backlog), but I do think the scrum template that has been proposed is not anything close to what the industry uses.  Normally teams will create epics/stories and drop them into the product backlog and then simply pull those into sprint backlogs during sprint planning.  I have done some form of agile process for 2 decades and I have no idea what a "Product Backlog Item" is.

The right way to do this is to just give me as a user the power to define my own work item types and the relationship between them.  Then I can create any process I want.

Take a look at https://www.openproject.org for example.  It lets a user define anything they want.  While I hate the UI, we should really consider using it's backend.

**Comment by nimishamukherjee** [comment]
Closing as we have a single Agile template now.
