### ISSUE TITLE
Provide copy for dependency screen in Launcher

### ISSUE THREAD

**Issue by stacymcauliffe** [openshiftio/openshift.io#3247]
Provide copy for dependency screens in the Launcher:
https://redhat.invisionapp.com/share/4UGJPFTM8NC#/screens/287586356

**Comment by AshishDurgude** [comment]
Hi Stacy, Thanks for the copy. There is one page missing. I need one more copy of the same project but for a different page. It is an Error State of dependency editor:
https://redhat.invisionapp.com/share/4UGJPFTM8NC#/screens/291489396
I have added comments for you on 17 April.

**Comment by stacymcauliffe** [comment]
Sent review request to @slemeur

**Comment by slemeur** [comment]
Done - other than my comments, it looks great.
Thanks @stacymcauliffe
