### ISSUE TITLE
The supported browser list still refers to the need to use incognito mode

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3248]
The reference to incognito mode should be removed from:

https://github.com/openshiftio/openshift.io/wiki/Supported-Browsers

**Comment by rkratky** [comment]
I updated the wiki page.

@qodfathr On a related note, should the docs team assume responsibility over this wiki? I now see other pages need updates, too -- so I guess we should pay ore attention to it.

**Comment by joshuawilson** [comment]
@rkratky we should coordinate wiki changes. It might makes sense to have Docs own it. So far it has been roughly maintained by Eng.

**Comment by qodfathr** [comment]
@rkratky I'm happy to have docs own the wiki, but I really feel this is a decision between ENG and Doc. PM supports whatever is decided.

**Comment by rkratky** [comment]
@joshuawilson Yes, let's. So far, the docs team was pretty much ignorant of the wiki. We'll try to keep it mind from now on and coordinate with you.

**Comment by joshuawilson** [comment]
@rkratky thanks, that works for me.
