### ISSUE TITLE
Pipelines not shown on space dashboard

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#3253]
- From the home page, accessing my space shows that I have [1] pipeline but it is not listed.
- Refreshing my space dashboard then shows I have [0] pipelines.
- The Create/Pipelines section shows that I have 1 pipeline.

Recording: https://youtu.be/2H2PJ1wlDuI

**Comment by ldimaggi** [comment]
Isn't this the same issue as:  https://github.com/openshiftio/openshift.io/issues/3315

**Comment by joshuawilson** [comment]
This change https://github.com/openshiftio/saas-openshiftio/pull/817 fixed the issue of pipelines not displaying. The reason is being researched but everything should work now.
