### ISSUE TITLE
Application Wizard repository name filter should be enabled by default

### ISSUE THREAD

**Issue by bostrt** [openshiftio/openshift.io#3256]
There is a blank text box to the left of the filter button that I expected to be the filter text input but it was not click-able:

![screenshot from 2018-04-23 13-08-28](https://user-images.githubusercontent.com/215290/39142011-70929242-46f7-11e8-9b47-94911bcc62d8.png)

However, I have to click the filter button first and then it drops down a second text input.

![screenshot from 2018-04-23 13-03-25](https://user-images.githubusercontent.com/215290/39142054-8a7ec57c-46f7-11e8-84a2-ef5c190af095.png)

I expect that the filter text input would be enabled by default and there would only be a single input box next to the filter button.

**Comment by animuk** [comment]
closing this as this was for old wizard.
