### ISSUE TITLE
Creating application with new launcher may create 2 build configs

### ISSUE THREAD

**Issue by ebaron** [openshiftio/openshift.io#3258]
When using the new launcher experience to create an application by importing an existing codebase, I ended up with 2 new build configs. This seems to be due to the application name (app-test-1) differing from the Maven artifact ID (mynewvertx) in the repository. I believe the former is created by the launcher and the latter is created by Jenkins.

Steps to reproduce:
1. Using new launcher experience, select "Import an existing codebase".
2. Either choose a GitHub repository with Maven artifact ID different from the application name, or change the application name in the wizard to something else.
![screenshot from 2018-04-18 17-28-14](https://user-images.githubusercontent.com/4326090/39143072-b0fdd906-46fa-11e8-89ed-45a96577fd76.png)
3. Wait for pipeline to start, observe 2 build configs (one named after application, one named after Maven artifact ID)
![screenshot from 2018-04-18 17-30-09](https://user-images.githubusercontent.com/4326090/39143282-78e947c0-46fb-11e8-84f3-707f6bca35e7.png)
4. Application is built through pipeline twice in build config named after artifact ID:
![screenshot from 2018-04-18 17-42-41](https://user-images.githubusercontent.com/4326090/39143364-bbe93fa8-46fb-11e8-903f-c77b2d6fd124.png)
5. Application is finally built through pipeline in build config named after the application:
![screenshot from 2018-04-18 17-50-47](https://user-images.githubusercontent.com/4326090/39143535-302b34f2-46fc-11e8-81a3-cb356d1c4562.png)

Some consequences of this are that only the build config created by the launcher (named after the application) has the appropriate space label attached to it. Thus, this is the only pipeline that is reported to the user in the OSIO pipelines page.

**Comment by ebaron** [comment]
This also occurs when selecting "Create a new codebase", where you name the repository something different from the application name. I have updated the issue title to reflect this.

**Comment by joshuawilson** [comment]
What severity would you set this to?

**Comment by ebaron** [comment]
I think SEV-2, since although the build eventually occurs in the expected build config (named after the application), you first have to manually approve builds in the other build config (named after the artifact ID). Since the pipelines view doesn't know about this other build config, you wouldn't know about it unless you visited the OSO web console.

**Comment by ebaron** [comment]
@joshuawilson It seems to. The build shown in the Pipelines view (import-test) seems to wait for the other build (mynewvertx) to finish before it starts. 
![screenshot from 2018-04-24 19-53-29](https://user-images.githubusercontent.com/4326090/39219568-4b3f8326-47f9-11e8-868a-c132fe6a57b3.png)
![screenshot from 2018-04-24 19-53-47](https://user-images.githubusercontent.com/4326090/39219571-4ec14fc0-47f9-11e8-82e6-fab32e89a172.png)
Without approval, the mynewvertx build will timeout, followed shortly by import-test.

After a few attempts, I've occasionally had the import-test build run first. When that happens, the build shown in the pipelines view should succeed.

**Comment by joshuawilson** [comment]
@ebaron if this means the build never completes, then this would be a SEV1?

**Comment by ebaron** [comment]
@joshuawilson Perhaps? This only occurs with the new launcher via "Try our new Getting Started experience", which only appears for me as an internal experimental feature. I'm not sure if that qualifies as SEV1.

**Comment by piyush1594** [comment]
is this same/like #3095 ?

**Comment by ebaron** [comment]
@piyush1594 Yes it is. Closing as duplicate of #3095.
