### ISSUE TITLE
"bobross_925" is displayed on user's dashboard

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3261]
![screenshot from 2018-04-23 15-02-28](https://user-images.githubusercontent.com/642621/39147494-c0b67a08-4707-11e8-9a27-f5a084ba0b8e.png)

**Comment by aptmac** [comment]
From Mattermost #fabric8-ui channel last Friday:

> Q: why am I seeing bobross_925 next to the space name in prod-preview? 

> @mindreeper2420: Yup, still in progress and a placeholder. A few widgets are in progress and will be transitioned to live elements during this Sprint.

**Comment by joshuawilson** [comment]
This is an internal view. Closing as it is still under development.
