### ISSUE TITLE
Non-functional "add collaborator" button displayed on user dashboard

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3262]
The "add collaborator" button is missing - clicking on the icon does nothing.

![screenshot from 2018-04-23 15-02-28](https://user-images.githubusercontent.com/642621/39147587-0e46ee24-4708-11e8-97b2-11ec517d0130.png)

**Comment by joshuawilson** [comment]
Internal view, this is still under development.
