### ISSUE TITLE
Total of "59" collaborators displayed on user's dashboard - seems to be hardcoded number

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3263]
![screenshot from 2018-04-23 15-02-28](https://user-images.githubusercontent.com/642621/39147735-7bf12cd2-4708-11e8-8b93-9f07a05c6c6c.png)

**Comment by qodfathr** [comment]
@ldimaggi make sure you are not set to "Internal" on your profile. In general, we should not be reporting bugs against Internal or Experimental. (And please no Internal reports/discussions in public forums.)

**Comment by joshuawilson** [comment]
@mindreeper2420 is this left over from your set up?
@qodfathr should we just close it?

**Comment by mindreeper2420** [comment]
@joshuawilson - correct. It is not a bug at this time.
