### ISSUE TITLE
Build urls direct to OSIO homepage

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#3265]
Build URLs in 'my namespace page' (something like this https://prod-preview.openshift.io/ksagathi-preview/sample) points to OSIO homepage

https://github.com/openshiftio/openshift.io/issues/2744 was closed recently. I saw this happen when I was checking the behaviour after https://github.com/openshiftio/openshift.io/issues/2744 being fixed 
This issue is same as https://github.com/openshiftio/openshift.io/issues/2744, except that it is not on the dashboard.
cc @joshuawilson @jiekang

**Comment by joshuawilson** [comment]
I'm unsure what link you are clicking on. Can you please post a screen shot with the link circled?

**Comment by kishansagathiya** [comment]
![screenshot from 2018-04-24 11-13-30](https://user-images.githubusercontent.com/10185999/39168203-970df9a2-47b0-11e8-8d06-6f2c25fbc2af.png)
@joshuawilson The link is selected

**Comment by joshuawilson** [comment]
Clicking that link takes me to OpenShift Online. Can you try it in incognito, it might be a cache issue. 
(note: incognito is only used to test for a cache issue, not regular daily use)

**Comment by jiekang** [comment]
The workaround PR https://github.com/fabric8-ui/fabric8-ui/pull/2759 only fixes the pipelines page. The race will still occur on the pipelines widget and the recent pipelines widget. I will write a workaround that shares code for that and use this issue to track.

**Comment by joshuawilson** [comment]
@kishansagathiya this is a build issue but @jiekang has been working in this area and it looks like he has a fix for it.

**Comment by kishansagathiya** [comment]
> @kishansagathiya this is a build issue but @jiekang has been working in this area and it looks like he has a fix for it.

Thanks a lot to @jiekang  and @joshuawilson
