### ISSUE TITLE
openshift jenkins-sync-plugin is generating too much noise

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#3266]
This is to followup on this issue #3240 

Openshift sync plugin is simply generating a humongous amount of data in a very stupid way. From what was observed it tries to synchronise the Jenkins jobs with OpenShift plugin by simply writing again and again without looking if there was previous changes.

This stress the system pretty badly and generate load on the system exponentially to the number of users we have on the system.

Project issue: https://github.com/fabric8io/jenkins-sync-plugin/issues/19

*Raising this as P0 since this is getting worse and worse and need to get this fixed ASAP*

**Comment by bmicklea** [comment]
Is this the sync plugin from DevStudio?  Or something else?

**Comment by piyush1594** [comment]
FYI Issue and related repo https://github.com/fabric8io/jenkins-sync-plugin/issues/19

**Comment by chmouel** [comment]
updated the title,

**Comment by chmouel** [comment]
The proper way and would be long term is openshift but we should come up with a workaround (which should be doable)

**Comment by piyush1594** [comment]
May be this one also https://github.com/openshift/jenkins-sync-plugin/commit/53ce3f4a12f1b246967a90bd6b08c4d429bb3d0b#diff-b9ed119c66ed02d31e9cb3377f727207 can resolve our problem

**Comment by bmicklea** [comment]
Is this waiting on other tasks before being tackled?

**Comment by chmouel** [comment]
@piyush1594 can you update this issue with what you have been done ? pull-requests and deps etc.. ? We need to keep an update on the P0 every day,

**Comment by piyush1594** [comment]
Hey @chmouel @bmicklea 

PR on sync plugin is merged https://github.com/fabric8io/jenkins-sync-plugin/pull/21 and PR on openshift-jenkins-s2i-config is there https://github.com/fabric8io/openshift-jenkins-s2i-config/pull/159

**Comment by bmicklea** [comment]
Excellent!
-- 

Brad Micklea // Director, Product Management // Developer Tools //
416.707.0792

**Comment by piyush1594** [comment]
UPDATE:

This issue has been fixed in Jenkins sync plugin by the PR mentioned above. This is blocked on tenant wise update and issue related to this is #3393 

Thanks

**Comment by piyush1594** [comment]
As #3393 is closed and according to https://github.com/openshiftio/openshift.io/issues/3422#issuecomment-386921153, seems like this has been done. Closing this.
