### ISSUE TITLE
Don't show anything in my namespace if I am not logged in 

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#3267]
![screenshot from 2018-04-24 11-46-20](https://user-images.githubusercontent.com/10185999/39169388-3c066e0e-47b5-11e8-8844-295e5e96df22.png)
@joshuawilson Went directly to https://prod-preview.openshift.io/ksagathi-preview/sample in incognito and found this. 
Is this a bug? Or is it by design?

**Comment by joshuawilson** [comment]
This is by design. It should act like github. You can view my profile and my projects on github.
