### ISSUE TITLE
Arrow in What's new doesn't do anything

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3270]
1. open dashboard
2. click on arrow next to the text "What's New?"

result:
* nothing happens

![osio_whats_new_1](https://user-images.githubusercontent.com/445100/39173848-2e246f8e-47a6-11e8-81ae-8812ed008efd.png)

**Comment by joshuawilson** [comment]
this is under experimental and not ready for review

**Comment by aptmac** [comment]
The "What's New?" functionality has been commented out [[0]](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/home/home.component.html#L14) in [[1]](https://github.com/fabric8-ui/fabric8-ui/commit/194bd11c759aeb3cc23e4144f07fd427774cf28e), and is no longer visible. 

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/home/home.component.html#L14
[1] https://github.com/fabric8-ui/fabric8-ui/commit/194bd11c759aeb3cc23e4144f07fd427774cf28e
