### ISSUE TITLE
'No thanks' link in What's new doesn't do anything

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3271]
1. open dashboard
2. click 'No thanks' link in What's New? section

result:
* nothing happens

![osio_whats_new_1](https://user-images.githubusercontent.com/445100/39173930-6552352c-47a6-11e8-85e1-c3f69f845fb9.png)

**Comment by joshuawilson** [comment]
this is an issue under Experimental and is not ready for review

**Comment by aptmac** [comment]
The "No thanks" link was removed in https://github.com/fabric8-ui/fabric8-ui/pull/2930/files#diff-eca39dd916df44977c2db3c73f7d7cb7L28
