### ISSUE TITLE
Handle long running Jenkins builds

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#3274]
Following discussion on #2352 

We currently don't have any timeout on Jenkins, we would have hope the `completionDeadlineSeconds` seconds would work but that's not supported on openshift for jenkins build. I have logged a feature request here : 

https://github.com/openshift/origin/issues/19481

but in the meantime we need to try to figure out an alternative to this since this would take some time before getting this fixed and shipped to us.

- Can we do that in Jenkins internally ?
- Can we do that with sync-plugin ?
- Can we do that in the pipeline ?

This  will be mitigated with idler idling handling long running job but this would still consume resources when unidling.

**Comment by bmicklea** [comment]
Removing the P0 label because this seems to make our resource utilization inefficient (and therefore costs higher) but won't negatively impact user experience.

**Comment by bmicklea** [comment]
@chmouel if you or others disagree please let me know what the user impact is.

**Comment by chmouel** [comment]
I believe this was reported by the SD team, i 'll let them decide if it's a P0 or not /cc @kbsingh

**Comment by chmouel** [comment]
This is deployed to prod,  while i have .a long running job waiting for approval for more than 3h : 

![image](https://user-images.githubusercontent.com/98980/39400658-081caf3a-4b35-11e8-80be-4c08b2ad31ee.png)

my jenkins got idled
