### ISSUE TITLE
Launcher: Select mission and runtime section too big

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3275]
1. open space dashboard in Firefox 59
2. click "Create an Application"
3. click "Try our new Getting Started experience"
4. choose some name and click "Create a new codebase", click Continue

result:
* section with "Choose a mission" and "Choose a runtime" is too big (too high)

![osio_choose_mission](https://user-images.githubusercontent.com/445100/39175429-91e58018-47aa-11e8-9df4-e4d1e968f229.png)

**Comment by GeorgeActon** [comment]
Closing as duplicate
It is being addressed as part of #3141

**Comment by invincibleJai** [comment]
This has been taken care of changes are in prod.

**Comment by ppitonak** [comment]
@invincibleJai I still see this problem in prod.

**Comment by invincibleJai** [comment]
@ppitonak ah try hard refresh `ctr+shift+r`, I tried now

<img width="1484" alt="screen shot 2018-04-25 at 11 08 57 am" src="https://user-images.githubusercontent.com/5129024/39235514-ae84d202-4893-11e8-893a-eede324a1b37.png">

**Comment by ppitonak** [comment]
@invincibleJai neither `ctrl+shift+r` nor Incognito mode helped

**Comment by invincibleJai** [comment]
not sure what's wrong as am not able to see "section with "Choose a mission" and "Choose a runtime" is too big (too high)" am in chrome. @animuk can you pls try once.

**Comment by ppitonak** [comment]
@invincibleJai it's a problem in __Firefox__
