### ISSUE TITLE
Launcher: chevron button doesn't work in Firefox

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3276]
1. open space dashboard in Firefox 59
2. click "Create an Application"
3. click "Try our new Getting Started experience"
4. choose some name and click "Create a new codebase", click Continue
5. scroll a bit and click blue round icon with down chevron in it

result:
* "Select pipeline" is highlighted in left navigation menu but the page doesn't scroll to the correct section
* click it again and "Authorize Git Provider" will be highlighted but again, not scrolled to correct section
* might be related to #3273 

![osio_launcher_chevron](https://user-images.githubusercontent.com/445100/39175717-54034496-47ab-11e8-9b66-892af28ad353.png)

**Comment by animuk** [comment]
duplicate issue :https://github.com/openshiftio/openshift.io/issues/2944

**Comment by animuk** [comment]
closing this as you can track in : https://github.com/openshiftio/openshift.io/issues/2944
