### ISSUE TITLE
Space dashboard: multiple icons not clickable

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3277]
1. create new space
2. create new project
3. wait for a pipeline to start

result:
* pipeline shows up in space dashboard but there are 4 icons that are not clickable

![osio_new_dashboard_pipeline2](https://user-images.githubusercontent.com/445100/39176449-26810db2-47ad-11e8-92b3-bbe1152533a7.png)

**Comment by joshuawilson** [comment]
This is under the Experimental flag and therefore is considered still in development.

**Comment by aptmac** [comment]
These features were added in https://github.com/fabric8-ui/fabric8-ui/pull/2812
