### ISSUE TITLE
Space dashboard: scroller always visible

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3278]
1. create new space
2. create new project
3. wait for a pipeline to start

result:
* scroller is visible even though all data can easily fit in page

![osio_new_dashboard_pipeline3](https://user-images.githubusercontent.com/445100/39176558-63e4a57e-47ad-11e8-9377-04efbdc4cb46.png)

**Comment by aptmac** [comment]
I'm not seeing this anymore, can you confirm @ppitonak?

It looks to have been taken care of in: https://github.com/fabric8-ui/fabric8-ui/commit/c62508f72fd8a2475b2251a2aa9dfad518ada84e

**Comment by ppitonak** [comment]
Yes, it's ok now. Feel free to close this issue.
