### ISSUE TITLE
User-defined Custom Filters in Planner

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#328]
# Description
As a user, I want to store custom filter expressions to be used as shortcuts. I want to be able to derive those stored filters from view configurations I made using the common filter features in the Planner.

# Acceptance Criteria
- [ ] The user can store a current configuration of the query/filter toolbar to a custom criteria.
- [ ] The user can give a name for the new custom criteria.
- [ ] In the sidebar, there is a section containing shortcuts to the stored custom criterias of this user.
- [ ] The user can delete a custom criteria from the sidebar section.
- [ ] Clicking on an criteria resets the current contexts (list view or board view) search/filter criteria and sets the selected custom criteria on the query/filter toolbar and the context view.
- [ ] Clicking on an criteria highlights the value and the criteria header.
- [ ] Only one single criteria can be active at any one time. If a new criteria is selected, the prior criteria gets deselected.
- [ ] There is no way of resetting/unsetting the current selected criteria. The user needs to choose another option of the sidebar resulting in a different query to leave/reset the criteria section.
- [ ] Adding additional criterias using the search/filter toolbar deselects the active criteria.

**Note**: The described section is only one of a few ways of specifiying a search request.
 
# Relationships
_Put linked Team/Product story links here_

**Comment by sdash-redhat** [comment]
The story needs to avoid the descriptions of "where" and "how" of the interaction to avoid defining the user experience - unless the experience and layout with interaction expected is pre-decided. For example "In the sidebar, there is a section containing shortcuts to the stored custom criteria of this user." - this defined the UX element of where on UI certain elements will appear ... This will restrict the design and the experience. We can define the user needs and keep the design aspect open to explorations.

**Comment by michaelkleinhenz** [comment]
I sort of agree, but keep in mind that this story is the input for the engineering team - and that team needs to know where that function has to go. This story is the bridge from the abstract experience to the actual engineering tasks.

**Comment by sdash-redhat** [comment]
Refer Interaction Design notes 
slide 106 -> 109 - https://redhat.invisionapp.com/share/6RCWHA1TX

Visual Design Notes: 
https://redhat.invisionapp.com/share/HTCX31SWC
(VD work in progress)

Note: the text, data points were shown are for reference purpose to illustrate the interaction, based on actual data points there may be changes on how the screen might appear in real time post implementation.

**Comment by sdash-redhat** [comment]
Here is the updated version. 
https://redhat.invisionapp.com/share/KRDF4GH8V

Added one more option based on feedbacks on earlier option 1. The benefit of this solution is that implementing a MyFilters will not require additional control on the filter bar.

**Comment by qodfathr** [comment]
@michaelkleinhenz @sdash-redhat is this now being tracked in the Planner? Or are we still using this GitHub issue?

**Comment by michaelkleinhenz** [comment]
Yes, it is tracked in Planner. Closing.
