### ISSUE TITLE
Failed login

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#3280]
I am having trouble logging in - I am getting An internal server error. Also, the loading of login page is very slow. Note that it does not happen every time, but quite often in the last hour. 

![failed-login](https://user-images.githubusercontent.com/2078072/39176800-ffef62f6-47ad-11e8-91b7-5e3f50126989.png)

**Comment by alexeykazakov** [comment]
developers.redhat.com had some issues today. It should work fine now. Please reopen if you still see this error.
