### ISSUE TITLE
[8]Support Nodejs Booster in Launcher Flow

### ISSUE THREAD

**Issue by animuk** [openshiftio/openshift.io#3282]
OSIO Users should be able able to select NodeJS boosters as a part of launcher flow and proceed with creating the project out of it.

Acceptance Criteria

-  OSIO Users should able to select NodeJS as a runtime for the boosters available in the launcher flow.
- OSIO Users can proceed in the launcher flow till completion of the project setup with the selected NodeJS Booster.
- Websocket event update should also work fine before triggering the pipelines
- Out of Scope: - N/A

**UI Tasks**

- [ ] - Handling initial load of default runtime dependencies
- [ ] - Testing and integration.

**Backend Tasks**
- [ ] Enable node support in openshift.io.
- [ ] Testing and integration.

**Comment by bartoszmajsak** [comment]
@animuk Can you elaborate what you mean by

> Websocket event update should also work fine before triggering the pipelines

**Comment by animuk** [comment]
@bartoszmajsak this means setup application should work when user choose node js boosters. setup application triggers subsequent web socket event calls in parallel in the launcher backend.

**Comment by sbose78** [comment]
Works now.
