### ISSUE TITLE
[8]Support Blank Booster in build pipeline

### ISSUE THREAD

**Issue by animuk** [openshiftio/openshift.io#3286]
#### User Story: https://openshift.io/openshiftio/openshiftio/plan/detail/2232
As an openshift.io user, He should able to build blank mission booster in the pipeline build.

**Acceptance:**
- Once OSIO Users setup app new application/import Blank Boosters in the launcher flow, all the pipeline stages should start like the existing boosters - 
**Build Release** --> **Rollout To Stage** --> **Approve** --> **Rollout To Run**
- End to End Pipeline Build Workflow should support building and deploying NodeJS boosters properly in the Openshift Namespaces and Jenkins.
- After successful builds, deployed application links for the stage and prod should be visible in the pipeline screen.

**Out of Scope:**
- N/A

**Comment by rupalibehera** [comment]
closing this in Github as this story is already moved to Planner.
