### ISSUE TITLE
Work Item Labels for Planner [3]

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#329]
# Description
As a user, I want to create labels and add them to Work Items to have an easy way of categorizing Work Items. I also want to be able to filter for labels using the filter UI features.

# Acceptance Criteria
- [ ] The user can create labels from a dialog view.
- [ ] The user can delete labels from a dialog view.
- [ ] The user can set a color and a title on a label.
- [ ] In the detail view, the user can view, assign and unassign labels to/from Work Items.
- [ ] In the quick preview, the user can view, assign and unassign labels to/from Work Items.
- [ ] In the list, the user can view labels of Work Items.
- [ ] In the board view, the user can view labels of Work Items.
- [ ] When assigning a label, the user can also create a new label on the fly.
- [ ] Label names/titles are uniqe.
- [ ] In the board view, the labels are displayed as part of the shown entry attributes.
- [ ] Deleting a label removes the label from all Work Items that are associated with the label.
- [ ] The user can create query/filter expressions from the toolbar that have one or more label value criterias in the expression.

**Note**: Label titles need to be unique to make them meaningful for searching/filtering.

**Note**: The labels may be something we later want to be available/used cross-component. This should be honored by the implementation.

**Note**: This is an example for a story that adds a new feature across Planner that adds new sub-features to several components like the sidebar, the list view or the board view. The story in encapsulated and builds on the existing foundation of stories and implementation that is already there.

**Note**: Labels are flat, not hierarchical. 

# Relationships
_Put linked Team/Product story links here_
_Group req's to OSIO tasks_

**Comment by sbose78** [comment]
How similar would this be , wrt to Github labels? Asking for a better understanding.


> The labels may be something we later want to be available/used cross-component. This should be honored by the implementation

Is this a hint that later on, we *might* want to co-relate this with kubernetes/openshift labels?

**Comment by michaelkleinhenz** [comment]
It is much more like the GitHub lables and just for user reference. The note was about that the user may add labels to other things, like builds - and that we may want to have one single "label repository".

**Comment by sdash-redhat** [comment]
Listing some of UX Questions: 

Is there a predefined list of labels ?
Does the user can also choose from a list of labels.. 
Can a label be part of filter criteria?
Please elaborate "n the board view, the labels are displayed as part of the shown entry attributes." -- what attributes typically expected to be shown in card ?

**Comment by michaelkleinhenz** [comment]
TODO: discuss if the lable title should be unique. Might be needed for filtering (having multiple equal titles in the value list is odd).

**Comment by sdash-redhat** [comment]
First draft UX wireframe based on the grooming discussion is available for planning now at https://redhat.invisionapp.com/share/2AD855HNS

Please review and share your thoughts. 

@michaelkleinhenz

**Comment by sdash-redhat** [comment]
Here is an updated version draft based on the feedback and alternative approach. 
https://redhat.invisionapp.com/share/QSD8LKRAM

@michaelkleinhenz
