### ISSUE TITLE
going to deployments page logs you out

### ISSUE THREAD

**Issue by surajssd** [openshiftio/openshift.io#3290]
In a clean environment (which is reset from the update profile page), I created a sample project whose builds were still in progress:
![1](https://user-images.githubusercontent.com/5815795/39193679-c0de0daa-47f9-11e8-8618-a2af988b2796.png)

Then you can see builds in progress here
![2](https://user-images.githubusercontent.com/5815795/39193712-d3747b2a-47f9-11e8-91e0-907e17d5c3b6.png)

from there if I go to the deployments page i get errror as shown in following screenshot

![3](https://user-images.githubusercontent.com/5815795/39193768-e4a49df8-47f9-11e8-9c49-cec6753850bf.png)

also i get logged out for some reason, i there click the login button to get log in automatically, I wait until the build is complete and then promote it to prod.

![9](https://user-images.githubusercontent.com/5815795/39193848-0cd15974-47fa-11e8-94dc-77af94ce72cb.png)

even after that when i goto deployments page same errors

![11](https://user-images.githubusercontent.com/5815795/39193879-1d0d9e9c-47fa-11e8-8336-de36fc07bf6d.png)

and got logged out again, also from there if I goto pipelines page same error

![12](https://user-images.githubusercontent.com/5815795/39193909-2cf7ef38-47fa-11e8-8cc3-9659730fe83e.png)

**Comment by jiekang** [comment]
@surajssd can you provide network request images. I'd like to see which part actually failed.

**Comment by surajssd** [comment]
The error that I got on the dashboard one was:

```
Request failed: 401 (Unauthorized) {"errors":[{"code":"unauthorized_error","detail":"openshift token","status":"401","title":"Unauthorized error"}]}
```

@jiekang on it!

**Comment by jiekang** [comment]
I just realized this is in production since WIT was updated there as well. The requests for deployments related info are actually getting 401's.

**Comment by surajssd** [comment]
following are scrolled down snapshots of what you want, you might wanna open image in new tab to look closer

![screenshot from 2018-04-24 20-22-57](https://user-images.githubusercontent.com/5815795/39195433-769a2e5a-47fd-11e8-9d36-b32724ebf8e8.png)
![screenshot from 2018-04-24 20-23-26](https://user-images.githubusercontent.com/5815795/39195434-76fbbc2e-47fd-11e8-94d7-634de15059a8.png)
![screenshot from 2018-04-24 20-23-39](https://user-images.githubusercontent.com/5815795/39195435-7744e50c-47fd-11e8-91c1-1604479365a0.png)

**Comment by jiekang** [comment]
Thanks.

It looks it's intended behavior to log out if there is a 401 response. This isn't handled by the Deployments page.

The WIT API should not be returning 401. @stooke will be working on this.

**Comment by alexeykazakov** [comment]
There should not be 401 at all in the first place but even if there is some 401 it should not always cause logout from OSIO. This is fundamentally wrong to logout when receiving 401 for any request.

@rohitkrai03 can you please create a separate issue for this 401 error handling and work with platform team to address it? Not sure if we already have it filed..

**Comment by andrewazores** [comment]
@alexeykazakov agreed. This faulty behaviour occurs like this. First, the UI class providing `Http` delegates to `ngx-login-client`'s `HttpService`, which broadcasts `authenticationError` whenever a response comes back with 401 status: https://github.com/fabric8-ui/ngx-login-client/blob/master/src/app/shared/http.service.ts#L50 .

This is then handled in `fabric8-ui` `LoginService` here: https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/login.service.ts#L38 , which is an explicit logout whenever `authenticationError` broadcasts are received. I don't know why this choice was made. The commit responsible is here https://github.com/fabric8-ui/fabric8-ui/commit/dd13c8711 , but the commit message doesn't really give context for the decision.

**Comment by andrewazores** [comment]
Adding the `HttpModule` from `@angular/http` to the DeploymentsModule imports array works around the logout issue, since (I believe) this will override the customized `Http` provider and remove the delegation to the `ngx-login-client` `HttpService`, meaning the `authenticationError` will not be broadcast. Quite a few modules in the fabric8-ui codebase also import HttpModule and so override the customized `Http` as well. I think these modules should *not* be overriding the customized `Http`, and instead the customized class should provide sane default behaviour for all consumers. If the LoginService needs some extra 401-unauth logic on its own then it should be implemented on its own, not as a global broadcast receiver.

**Comment by andrewazores** [comment]
@joshuawilson do you know what the reasoning is for handling all 401s with an authService logout? Was it intended only to catch 401s on login requests perhaps?

**Comment by alexeykazakov** [comment]
> The commit responsible is here fabric8-ui/fabric8-ui@dd13c87 , but the commit message doesn't really give context for the decision.

It was added as a quick solution more than one year ago for handling token expiration and other similar cases. We crated a lot of technical debt back then.

We should limit logout to some particular cases only... When OSIO user token is expired for example. Or has been revoked... Let's create a separate issue for that where we can discuss it.

cc @rohitkrai03

**Comment by joshuawilson** [comment]
@andrewazores I think we need to look at removing it from `ngx-login-client`. I don't want a hack here. It was a hack that put us in the situation we are in now. 

Please work with @rohitkrai03 and check with @dgutride as he has the most experience with the code.

**Comment by sbose78** [comment]
There was a similar situation faced when we introduced the GET /api/token endpoints , where a legit 401 had caused a log out in the Getting Started page - the fix to avoid that was this https://github.com/fabric8-ui/ngx-login-client/commit/5e4a6a3b305030b162658b151358a2b6c026eeab .

**Comment by ldimaggi** [comment]
This looks good in production - I am able to access the 'deployments' page without being logged out:

![screenshot from 2018-04-26 09-02-40](https://user-images.githubusercontent.com/642621/39307381-a6c74ee4-4930-11e8-906f-cacc13aacd67.png)

**Comment by andrewazores** [comment]
@alexeykazakov I have created issue #3325 to track the 401 handling root cause.

**Comment by andrewazores** [comment]
@joshuawilson @rohitkrai03 @dgutride ^
