### ISSUE TITLE
Space dashboard: applications section shows Loading

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3291]
1. create a space
2. create a new project
3. go to space dashboard

result:
* bottom-right section called "Applications" shows "Loading..." for long time (indefinitely?)

![osio_apps_loading](https://user-images.githubusercontent.com/445100/39194053-214feff4-47dd-11e8-8860-efcbc54fd723.png)

**Comment by joshuawilson** [comment]
@andrewazores @jiekang I have seen this too. Do you know what is causing it?

**Comment by andrewazores** [comment]
That widget uses the DeplotmentApiService, so it's probably the same root cause as #3290 .

**Comment by andrewazores** [comment]
Confirmed, this is happening due to 401s on the requests to the Deployments API backend, so same root cause. I'm looking into why the 401s from this widget do not trigger a logout (see comment for explanation here https://github.com/openshiftio/openshift.io/issues/3290#issuecomment-384259304 ).

**Comment by ldimaggi** [comment]
Issue found/encountered by EE tests.

**Comment by ldimaggi** [comment]
Note - this bug is causing the E2E tests to fail.

**Comment by ppitonak** [comment]
This issue might get irrelevant when new dashboard is finished.

**Comment by andrewazores** [comment]
There should be a Deployments backend fix in place before that point, which will make this widget work as expected again.

**Comment by aslakknutsen** [comment]
Probable root casue: https://github.com/openshiftio/openshift.io/issues/3290

**Comment by andrewazores** [comment]
@aslakknutsen yes, that is the root cause

**Comment by jiekang** [comment]
This should also be fixed now. Can anyone else confirm?

**Comment by ppitonak** [comment]
@jiekang, it no longer shows "Loading" but the name of application

**Comment by ldimaggi** [comment]
![screenshot from 2018-04-26 09-36-49](https://user-images.githubusercontent.com/642621/39309179-5eae59c2-4935-11e8-9734-0ded267dd384.png)
