### ISSUE TITLE
Is there a way to pull the redhat container catalog images from UI (Not using oc client)?

### ISSUE THREAD

**Issue by anshulbehl** [openshiftio/openshift.io#3292]
on the link below 

https://access.redhat.com/containers/?tab=images&platform=openshift#/registry.access.redhat.com/rhcertification/redhat-certification-management

It says:

Container images that are made to run with OpenShift platforms can either be pulled from the command line (using the oc command) or from the OpenShift Dashboard GUI interface. The following is one command line you could use to pull the rhcertification/redhat-certification-management container image to the local system for use with OpenShift:

I am concerned with the statement

**or from the OpenShift Dashboard GUI interface**

Just want to know is there a way to do this yet?

**Comment by joshuawilson** [comment]
Where did you get to this? This issue tracker is for issues in https://openshift.io

**Comment by joshuawilson** [comment]
maybe try asking on https://chat.openshift.io/developers/channels/town-square to get direction where to post the question

**Comment by aditya-konarde** [comment]
Thinking that this question is towards 'OpenShift' as opposed to 'OpenShift.io'. @anshulbehl please note that the two are different products. Can you please confirm that you're asking this in the context of 'OpenShift.io'(https://openshift.io/)?

**Comment by anshulbehl** [comment]
@aditya-konarde Should be OpenShift, where to file the relevant bugs?

**Comment by aditya-konarde** [comment]
@anshulbehl Bugzilla for Bugs, Internal IRC for discussions (sent channel name in chat.)
