### ISSUE TITLE
New Feature Flag settings do NOT refresh

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#3295]
It appears that changing the feature flag does not get stored. It does, in fact, get stored but the UI doesn't refresh and so the UI change is lost without a refresh.

**Comment by joshuawilson** [comment]
@chrislessard @corinnekrych can you please take a look at this.

**Comment by xcoulon** [comment]
After looking at the requests/responses, I could see that the feature level change is correctly persisted in the backend (as a consequence, features are enabled/disabled as expected). 
The problem is at the `Feature Opt-In` page which keeps showing the older level of the user.

**Comment by corinnekrych** [comment]
@xcoulon @joshuawilson yeap I've noticed that yesterday while working on #2402 it's a UI regression brought by the settings PR.
it is fixed in the WIP PR for 2402.

**Comment by joshuawilson** [comment]
This is fixed.
