### ISSUE TITLE
Case mismatch between State options shown in Filter by type drop-down and the preview

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#3298]
State options in the filter drop-down should be in Title case similar to the state options shown in preview.

![screenshot from 2018-04-25 14-25-16](https://user-images.githubusercontent.com/16647625/39235972-0da1b8c6-4895-11e8-98b7-277e50adbea7.png)

![screenshot from 2018-04-25 14-25-28](https://user-images.githubusercontent.com/16647625/39235981-14fc674c-4895-11e8-8163-81b10d60aa10.png)

**Comment by kwk** [comment]
Please use whatever is in the `system.state` enum of the work item type and don't modify it in any way.

**Comment by kwk** [comment]
> Please use whatever is in the system.state enum of the work item type and don't modify it in any way. Title casing is not correct.

@nimishamukherjee @Preeticp I'm sorry but I've changed my mind about this. You can display whatever you want but please only sent the states that the backend defined.

**Comment by nimishamukherjee** [comment]
Fix is on prod
![filterstates](https://user-images.githubusercontent.com/1892722/48822004-71c37880-ed81-11e8-9b42-cb903a167137.png)

![witstates](https://user-images.githubusercontent.com/1892722/48822007-7556ff80-ed81-11e8-8a74-fbf6062f2bc8.png)
