### ISSUE TITLE
Can't create a work item

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#3300]
1. Open any space (https://openshift.io/ksagathi/myspace)
![screenshot from 2018-04-25 14-49-42](https://user-images.githubusercontent.com/10185999/39236999-e76e759c-4897-11e8-98ff-cf6b9194f2e2.png)

2. Click on create work item, that will get you ->(https://openshift.io/ksagathi/myspace/(action:add-work-item)
![screenshot from 2018-04-25 14-51-52](https://user-images.githubusercontent.com/10185999/39237097-3787742a-4898-11e8-9d5a-11962ba2a10c.png)
)
You might want to scroll up in the black page. you will see
![screenshot from 2018-04-25 14-53-27](https://user-images.githubusercontent.com/10185999/39237203-71ceea64-4898-11e8-89d4-1b01d5af4ed2.png)

3. `Create work item` took me to `Choose a new work item type`. With this blank page I don't know how to do that, but I still want to try, so I click on `plan`. So I get 404.
![screenshot from 2018-04-25 14-56-23](https://user-images.githubusercontent.com/10185999/39237331-d7daf668-4898-11e8-8335-cb43ff8757ed.png)

Note: I was able to reproduce this several times today.
@nimishamukherjee

**Comment by aptmac** [comment]
Regarding: # 2
- The add-work-items page is getting a 404 when trying to retrieve the list of work item types.

Regarding # 3:
- This behaviour is a known issue and is documented here: https://github.com/openshiftio/openshift.io/issues/3021

**Comment by mishaone** [comment]
+1 to this. Reproduced it several times (also in incognito mode) today to get around it but no joy

**Comment by aptmac** [comment]
The add-work-items page from the dashboard has been removed as of https://github.com/fabric8-ui/fabric8-ui/pull/2855
