### ISSUE TITLE
"Legacy" Scenario should be renamed back to: Scenario Driven Development

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3305]
![screenshot from 2018-04-25 08-56-18](https://user-images.githubusercontent.com/642621/39247178-b0135e68-4866-11e8-83d4-fb27f63a930a.png)

The correct name of the scenario is:   Scenario Driven Development

**Comment by ppitonak** [comment]
+ Scrum should be available only as an Experimental feature

**Comment by kwk** [comment]
@ppitonak did request Scrum.

**Comment by kwk** [comment]
> Can we wait to close this until the change is actually present and verified in production? Thanks!

Apparently we can ;) GH closed the issue because of my commit message automatically. Sorry about that. I will try to only say `See https://github.com/openshiftio/openshift.io/issues/3305` next time insteaf of `Fixes https://github.com/openshiftio/openshift.io/issues/3305`.

**Comment by kwk** [comment]
For prod-preview you can see that it has been updated properly:

```
$ curl -s https://api.prod-preview.openshift.io/api/spacetemplates | jq '.data[] | .attributes | .name, ."can-construct"'
"Openshift.io Base Space Template"
false
"Scenario Driven Development"
true
"Scrum"
true
```

**Comment by kwk** [comment]
![bildschirmfoto von 2018-04-25 17-11-52](https://user-images.githubusercontent.com/193408/39255040-d8ce4738-48ab-11e8-9b4d-162894b770ea.png)

@ldimaggi prod is updated but apparently the space creation dialog sorts space templates and doesn't select a default one. That makes Scrum the default choice.

@qodfathr is there a template you want to default to?

@michaelkleinhenz @nimishamukherjee @sanbornsen

**Comment by Preeticp** [comment]
Docs for the Scrum template have been added to the User Guide: https://docs.openshift.io/user-guide.html#using_scrum_guided_hierarchy

**Comment by kwk** [comment]
@qodfathr, thanks to @arunkumars08 as of https://github.com/fabric8-ui/fabric8-recommender/pull/447 analytics  can also handle the scrum template.
