### ISSUE TITLE
profile bio character count exceeded and saved

### ISSUE THREAD

**Issue by christianvogt** [openshiftio/openshift.io#3309]
It's possible to exceed the bio character count in the user profile. If the user pastes a large chunk of text into the bio, although the textarea is truncated to 245 characters (only if pasting view keyboard shortcuts), and then immediately saves, then the bio includes the full text.

![bio](https://user-images.githubusercontent.com/14068621/39256192-427f8bf4-487c-11e8-9b1e-fef5cafb0d24.gif)

**Comment by sbose78** [comment]
@rohitkrai03 , could you please take a look at this?

**Comment by rohitkrai03** [comment]
@christianvogt We use a patternfly-ng [directive](https://rawgit.com/patternfly/patternfly-ng/master-dist/dist-demo/#/remainingcharscount) for limiting max chars in textarea. I can see in the [code](https://github.com/patternfly/patternfly-ng/blob/master/src/app/remaining-chars-count/remaining-chars-count.directive.ts) that it only handles keyup event and not the right click paste. 
So, I've handled this in our code and raised a PR - https://github.com/fabric8-ui/fabric8-ui/pull/2908 for it.
