### ISSUE TITLE
Guided Type Selection for new Work Items in Planner

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#331]
# Description
As a user, I want to have new Work Items created following a type hierarchy that is custom for the current space template. I want to be guided based on the current space template on which types of Work Items I can create using the quick add or the dialog based new Work Item feature.

# Acceptance Criteria
- [ ] The Work Item Types of a Space template are part of a defined structure that defines parent Work Item Types and child Work Item Types.
- [ ] The Work Item Types are organized in a list of lists of WITs.
- [ ] Each list on a level can contain any number of WITs.
- [ ] The list of lists is ordered.
- [ ] If the user has selected a WI of a WIT that is in a list, the quick add guidance is adjusted so that the WITs on the **next level down** is the list of possible WITs to choose from for creating child WIs.
- [ ] If no context is selected (no WI selected), then the topmost (first) list is used as the set of possible WITs.
- [ ] If a WI is chosen of which the WIT is in the last list, then creating children is not possible.
- [ ] WITs can appear on one level of the list. 

**Note**: At a later point, we want to have WITs appear on multiple levels of the list of lists, making it more complex to find out the context level of the selected WI. At this point, we need a solution for that, possibly by storing the original context level on newly created WIs. Though that would mean storing UI-only information on the WI.

**Note**: This story applies only to the quick add feature, not the full dialog-based add Work Item feature.

**Note**: This is supposed to be used as a "guidance" for the user. Any parent-child relationship can be created using the "full" create link dialog. 

**Note**: In the whiteboards below, the levels have names "Portfolio", "Requirements" or "Iteration", but the names are purely internal and do not show up in the UI.

# Relationships
_Put linked Team/Product story links here_

**Comment by michaelkleinhenz** [comment]
![2017-07-12 16 36 42](https://user-images.githubusercontent.com/7101098/28138905-630f71ce-6720-11e7-9a63-cf98881bb3ff.jpg)

**Comment by michaelkleinhenz** [comment]
![img_20170714_101051](https://user-images.githubusercontent.com/7101098/28217632-cbedc664-6883-11e7-8798-34d487c91c3f.jpg)

**Comment by pranavgore09** [comment]
@michaelkleinhenz Do we need to guide the user on "Detail View" as well.
I believe it is only for "quick add"

**Comment by pranavgore09** [comment]
> Note: In the whiteboards below, the levels have names "Portfolio", "Requirements" or "Iteration", but the names are purely internal and do not show up in the UI.

@michaelkleinhenz we are showing it on UI now.....

**Comment by sdash-redhat** [comment]
Refer Interaction Design notes 
slide 18 
& slides 22, 23, 24, (left hand panel grouping are indicative )  - https://redhat.invisionapp.com/share/6RCWHA1TX

Visual Design Notes: 
https://redhat.invisionapp.com/share/HTCX31SWC
(VD work in progress)
