### ISSUE TITLE
Viewing deployments fails with 500/server error - configmaps "fabric8-environments" is forbidden

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#3311]
This is Prod
Getting this on clicking on going to deployments after building the VertX HTTP Booster

![screenshot from 2018-04-25 22-14-46](https://user-images.githubusercontent.com/10185999/39260222-7abaad64-48d6-11e8-8269-7e8a6439c2c2.png)

**Comment by ldimaggi** [comment]
I am seeing this issue too - on production.

**Comment by qodfathr** [comment]
Notice that it's giving an error that you cannot access the stuff of **some other user**. I am seeing this, too -- my Deployments screen seems to be trying to load data for ldimaggi and lwright

![image](https://user-images.githubusercontent.com/16322190/39269244-5bd3bc82-48a0-11e8-8d53-0472167e1d0a.png)

**Comment by ldimaggi** [comment]
So - it seems to be persisting a reference to the previous user that accessed their own deployments?

**Comment by ebaron** [comment]
@stooke is fixing this bug with this PR: https://github.com/fabric8-services/fabric8-wit/pull/2057

**Comment by kbsingh** [comment]
Impact on prod, raised to sev1

**Comment by aslakknutsen** [comment]
This should be fixed. Please retest.

**Comment by jiekang** [comment]
This is fixed for me on production. Can anyone else confirm?

**Comment by ldimaggi** [comment]
We can't verify this fix in production until this issue is resolved - https://github.com/openshiftio/openshift.io/issues/3315
