### ISSUE TITLE
Launch Experience - Add cluster selection into existing flow

### ISSUE THREAD

**Issue by bdellasc** [openshiftio/openshift.io#3313]
**Verification Conditions**
- [x] Verify use cases with UXD and Dev teams, get answers to questions, verify scenarios we need to support [27 Apr Meeting Notes](https://docs.google.com/document/d/1gZJiW_AhMQOr9jlOj0bz_qimttKY48ahEpDNaGNgxjw/edit?usp=sharing)
- [x] As promised in the meeting, provide design for [.ZIP download instructions page](https://redhat.invisionapp.com/share/6BEZL73M7#/286892654_Title_-_RHD_Launch_-_Select_Target_Env_-ZIP-_4)
- [x] Add selection of a cluster to the standalone launch design for the defined scenarios in the meeting notes, then post designs to [InVision](https://redhat.invisionapp.com/share/67HOQB7UCB9)
- [x] Link to @stacymcauliffe 's [content doc - our content starts on page 12](https://docs.google.com/document/d/1PRKPlg9zOgG9Eu5GZr96GCADPhPnLwZte0jkVx5q3KQ/edit?usp=sharing)
- [x] Worked with @Essjaysee and added informational inline & popover text for unavailable clusters in the Target Environment section. Added to @stacymcauliffe 's [content doc - on page 15](https://docs.google.com/document/d/1PRKPlg9zOgG9Eu5GZr96GCADPhPnLwZte0jkVx5q3KQ/edit?usp=sharing)
- [x] Gather feedback in InVision and iterate, if necessary
- [ ] Work with dev to answer any design questions as they work on implementation

**Summary of the current problem**
- Some boosters cannot be used with some clusters. 
- Users who have access to multiple clusters run the risk of choosing a booster that is incompatible with their preferred cluster or vice versa.
- Some clusters might already be used for other purposes, and may not have enough resources to handle new requirements for boosters.
- The booster lists should be:
   - driven by what the user has access to 
   - enabled/disabled based on the chosen their target environment/cluster and available resources of that cluster

**Current existing conversations/resources RE: clusters in the target environment screen**
  - [GitHub issue with discussion](https://github.com/fabric8-launcher/launcher-frontend/issues/302)
  - [Google chat](https://groups.google.com/forum/#!topic/fabric8-launcher/nfqzsIMjiK0)

**Open Questions/Issues/Thoughts**
- Design Intent of Launch Experience
This UI is designed to "play" and users may fill section in a non-linear order. Just moving the cluster information to the first panel does not guarantee that every user will select from a filtered booster list. They could still end up jumping to the second panel, making a Booster Selection, then select their OSO/Cluster combo. Moving it first increases the odds they will do it in that order, but does not guarantee it.

**Comment by bdellasc** [comment]
- Met with @gastaldi @quintesse @catrobson @mindreeper2420 @Essjaysee @dlabrecq @ALRubinger this morning to discuss the current state of what is needed to support clusters in the new standalone launcher. 
- Linked to meeting notes, related InVision files, @stacymcauliffe 's content document
- Posted the design based on this morning's discussion, please comment in InVision with any feedback
- We'd like Adam and Dan to synch up with Erik on Monday RE: the implementation

**Comment by joshuawilson** [comment]
This should wait till after Summit unless this is fixing a P0 issue.

**Comment by catrobson** [comment]
@joshuawilson this is for the Launcher for their summit usage.  It shouldn't affect OSIO at all.  We've already warned the Launcher team that they should be careful and not mess up anything that would affect OSIO and Todd's demos.  I think we'll be OK here though as they are only modifying a part of the launcher that OSIO doesn't even use.
