### ISSUE TITLE
Retrieve all features of fabric8-ui without specifying name as input.

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#3316]
Task belong to [UserStory User consent profile screens revisited](https://github.com/openshiftio/openshift.io/issues/2402)

We need en endpoint:
- to retrieve all features with that use strategy `enableByLevel` ie; all features defined for fabruc8-ui feature-flag 
- similar to the endpoint `https://api.prod-preview.openshift.io/api/features?group=Analyze` that retrieve features per group, here we need `https://api.prod-preview.openshift.io/api/features` to that should retrieve all features with enableByLevel strategies in the following format:
```
{
  "data": [
    {
      "attributes": {
        "description": "main dashboard view",
        "enabled": true,
        "enablement-level": "released",
        "user-enabled": true
      },
      "id": "Analyze",
      "type": "features"
    },
    {
      "attributes": {
        "description": "new home dashboard experience",
        "enabled": true,
        "enablement-level": "experimental",
        "user-enabled": true
      },
      "id": "Analyze.newHomeDashboard",
      "type": "features"
    },
    {
      "attributes": {
        "description": "new space dashboard experience",
        "enabled": true,
        "enablement-level": "experimental",
        "user-enabled": true
      },
      "id": "Analyze.newSpaceDashboard",
      "type": "features"
    }
  ]
}
```
cc @xcoulon

**Comment by corinnekrych** [comment]
Tasks:
- [ ] list feature by strategy on unleash-go SDK
- [ ] list feature by strategy in toggles-service
- [ ] remove hardcoded ui in here:
 - https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/context.service.ts#L235 
- https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/settings/feature-opt-in/feature-opt-in.component.ts#L113

**Comment by joshuawilson** [comment]
Is this done? Can we close it?

**Comment by corinnekrych** [comment]
@joshuawilson nope, PR are done for backend. we mis ui one. I'll do that in this sprint.
