### ISSUE TITLE
Build is not working while creating a quickstart in an organization

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#3319]
While creating a quickstart I found that build is not working when we use a git organization though it's working when we select the github username.
![s](https://user-images.githubusercontent.com/7105965/39300431-46eeed86-4969-11e8-811c-b664a1b51d28.png)

**Comment by ldimaggi** [comment]
It sounds like you are also seeing this issue - https://github.com/openshiftio/openshift.io/issues/3315

If this is the case - can you close #3319 as a duplicate of #3315?  Thx!
