### ISSUE TITLE
Linking Work Items in Planner

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#332]
# Description
As a user, I want to be able to link Work Items using named/semantic links.

# Acceptance Criteria
- [ ] Work Items can be linked together not regarding the Work Item Types on the source or target Work Item.
- [ ] All other UI and semantic behaviour of the current implementation is unchanged.

**Note**: The important requirement of this story is the removal of the current restrictions on types on both ends of a Link Type, making it possible to link anything to anything.
 
# Relationships
_Put linked Team/Product story links here_

**Comment by kwk** [comment]
@michaelkleinhenz this can be closed as we have no work item type restrictions on link ends any more since https://github.com/fabric8-services/fabric8-wit/pull/1444.
