### ISSUE TITLE
use RHEL7 in base images for all production images

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#3321]
Work on getting RHEL7 images used for base images.
Using this issue as overall tracker.

- [x] [openshiftio/openshift.io](https://github.com/openshiftio/openshift.io/pull/3317) 
- [x] fabric8-auth
- [x] keycloak
- [x] [fabric8-tenant](https://github.com/fabric8-services/fabric8-tenant/pull/572)
- [x] [fabric8-notification](https://github.com/fabric8-services/fabric8-notification/pull/68)
- [x] [fabric8-oso-proxy](https://github.com/fabric8-services/fabric8-oso-proxy/pull/13)
- [x] [fabric8-admin-proxy](https://github.com/fabric8-services/fabric8-admin-proxy/pull/2)
- [x] [fabric8-wit](https://github.com/fabric8-services/fabric8-wit/pull/2004)
- [x] [fabric8-toggles](https://github.com/fabric8-services/fabric8-toggles/pull/27)
- [x] [fabric8-toggles-service](https://github.com/fabric8-services/fabric8-toggles-service/pull/45)
- [x] [fabric8-jenkins-idler](https://github.com/fabric8-services/fabric8-jenkins-idler/issues/211)
- [x] [fabric8-jenkins-proxy](https://github.com/fabric8-services/fabric8-jenkins-proxy/pull/229)
- [x] [fabric8-online-docs](https://github.com/fabric8io/fabric8-online-docs/pull/297)

Others at https://docs.google.com/spreadsheets/d/1VHHnxeb_8ricpay6GoiRG0e3Jlg5klO5eTMMVWeTWBQ/edit#gid=1147758271 

General approach should be:
- The build script has changed, make sure that there are no obvious
mistakes, and that it continues to the same thing essentially, but
pushes to a different place if TARGET=rhel
- There is a new Dockerfile.rhel (or Dockerfile.deploy.rhel), this
should be compared against the existing one, based on CentOS
- The OpenShift template has been changed to parametrize the IMAGE parameter
- Make sure we are OK with the fact that by merging this PR it will be
deployed in staging with a RHEL based container

It is somewhat a hard PR to address because the build scripts and
makefiles are generally copy/pastes from other projects with patched
parts. This is something very close to OpenShift that developers don't
usually touch.

**Comment by jmelis** [comment]
For the [openshiftio/openshift.io](https://github.com/openshiftio/openshift.io/pull/3317) we would also need this merge: https://github.com/openshiftio/openshift.io/pull/3323

**Comment by surajssd** [comment]
@maxandersen @jmelis aren't we porting wit service to RHEL? I don't see any rhel deploy Dockerfile there?

**Comment by maxandersen** [comment]
> @maxandersen @jmelis aren't we porting wit service to RHEL? I don't see any rhel deploy Dockerfile there?

that is at https://github.com/fabric8-ui/fabric8-ui/pull/2805 (just added to list above)

**Comment by alexeykazakov** [comment]
Added fabric8-auth (done) and keycloak (currently run in prod-preview, will push to prod if no issues found in preview)

**Comment by aslakknutsen** [comment]
@maxandersen @surajssd It's here: https://github.com/fabric8-services/fabric8-wit/pull/2004 updated list

**Comment by maxandersen** [comment]
> @maxandersen @surajssd It's here: fabric8-services/fabric8-wit#2004 updated list

sorry for my bad copy/paste  :) thanks for fixing it.

**Comment by alexeykazakov** [comment]
Keycloak has been deployed to prod. Do we still have anything left?

**Comment by cctrieloff** [comment]
Have we also changed the image the pipeline builds, or is that another issue #?

**Comment by kbsingh** [comment]
@cctrieloff were handling that as a seperate issue

**Comment by bmicklea** [comment]
Everything is checked off here, should the issue be closed?

**Comment by jmelis** [comment]
The following is a list of services that have been deployed to staging but not to prod, alongside with the PRs that will promote them to prod:

- f8-wit: https://github.com/openshiftio/saas-openshiftio/pull/830
- f8-jenkins-proxy: https://github.com/openshiftio/saas-openshiftio/pull/840
- f8-notification: https://github.com/openshiftio/saas-openshiftio/pull/832
- f8-oso-proxy: https://github.com/openshiftio/saas-openshiftio/pull/833
- f8-admin-proxy: https://github.com/openshiftio/saas-openshiftio/pull/834
- f8-jenkins-idler: PR to be sent

I have unchecked those from the top as I think they should be checked only when they're deployed to prod.

**Comment by jmelis** [comment]
PR to promote jenkins-idler to prod has been sent: https://github.com/openshiftio/saas-openshiftio/pull/847

As soon as that is merged, we can close this issue.

**Comment by jmelis** [comment]
All the services are now running on RHEL. Closing issue.
