### ISSUE TITLE
401 response on any request may cause user to be logged out

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#3325]
# Bug

As seen in #3290 and explained in the linked comment [here](https://github.com/openshiftio/openshift.io/issues/3290#issuecomment-384259304), any response with status 401 to any request may trigger a user logout action, if the requesting service/component uses the `Fabric8UIHttpService` (which provides `Http` in app.module (!)). This was apparently intended to catch cases such as a user's token expiring, which would cause requests to result in 401s, and the forced logout would send the user back to the login page and allow the token to be refreshed. However, it also inadvertently catches 401s returned by other APIs which may not always occur due to the user being unauthenticated for OSIO itself but rather unauthenticated for some external API, such as the Deployments backend as seen in #3290, in which case a forced logout is jarring and does not help in any way.

**Comment by christianvogt** [comment]
It's a common pattern to intercept calls and check for _something_ to know when the user need to login again to complete the request. However the 401 check is too broad. Consider including some extra payload to give context that the 401 is due to the token in which case we can look for this additional payload in conjunction with the 401 status code.

**Comment by joshuawilson** [comment]
@dgutride please look at this when you have time.

**Comment by alexeykazakov** [comment]
cc: @rohitkrai03

**Comment by sbose78** [comment]
Some history - We had had to put in a hack to avoid this for token retrieval https://github.com/sbose78/ngx-login-client/blob/b55792302c4dde458df52722b236256c589d38c1/src/app/shared/http.service.ts#L49
