### ISSUE TITLE
Home page chat link should be generic

### ISSUE THREAD

**Issue by kbsingh** [openshiftio/openshift.io#3327]
At this time we have a link on https://openshift.io/, it should be called simply ' chat with us' and it should link to chat.openshift.io

note: it is only visible if you are logged out!

**Comment by joshuawilson** [comment]
cc @catrobson

**Comment by catrobson** [comment]
Let's call them both "Chat with us"

**Comment by catrobson** [comment]
Logged out marketing page updates with this:  https://github.com/openshiftio/openshift.io/pull/3420

**Comment by joshuawilson** [comment]
this is in production, closing

**Comment by catrobson** [comment]
We also need to change the logged in user dropdown to say 'Chat with us' to match.
