### ISSUE TITLE
Notifications for Events on Work Items

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#333]
# Description
As a user, I want to receive notifications for events on Work Items.

# Acceptance Criteria
- [ ] The user receives a notification for events on Work Items via the platform notification service.
- [ ] A user can be added to a "follower" list of users on a Work Item.
- [x] A user gets added to the follower list when he is the creator of the Work Item.
- [x] A user gets added to the follower list when he commented on the Work Item.
- [x] A user gets added to the follower list when he is assigned to the Work Item.
- [ ] The user receives notifications on action on a Work Item when he is member of the "follower" list.
- [ ] The user receives a notification for any change to the Work Item or the relationships.

**Note**: This story only describes a very narrow feature set for notifications. There will be stories on inbox notifications on the system and further events later.

**Note**: Notifications are a global infrastructure for OSIO and should not be considered Planner-only.
 
# Relationships
- [ ] Create initial notification service https://github.com/fabric8-services/fabric8-notification/issues/1
- [ ] Publish events on WorkItem/Comment Create/Update for Notifications https://github.com/fabric8-services/fabric8-wit/issues/1488

**Comment by joshuawilson** [comment]
This is already in the Platform Backlog at #285, can you please update that one.

**Comment by michaelkleinhenz** [comment]
Lets talk about that in the Consolidation meeting today. But yes, this is an example of a crossover story. We need to consolidate this into one single story.

**Comment by pranavgore09** [comment]
And I found the ticket :)

@aslakknutsen My idea for followers was to treat them as "assignees". So each work item will have a list of "followers" returned to UI similar to assignees. When a user creates/updates/comments he will be added to that list if already not there.
But as I see, this is not the way we should do it.

Please let me know how do we deal with "followers", is there any specific reason not to go with above flow?

One down side I can think of is, followers are creaters+commenters+updaters+....whatever comes in future. If we go with this model then there might be more 10 lists of users.

**Comment by qodfathr** [comment]
In #285, I've proposed the need for a new epic that covers Notifications broadly. If that is accepted, this will likely get revised to be some form of child of the new epic.

**Comment by nimishamukherjee** [comment]
Closing this as we have https://openshift.io/openshiftio/Openshift_io/plan/detail/288 on OSIO.
