### ISSUE TITLE
Cannot reach external REST API from east-2

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#3331]
I'm writing a small vert.x app that attempts to call a REST API hosted outside of OSO. The DNS resolution of the remote host names is not working properly (at least, when run in Che). For example, if I try to reach https://api.github.com, I get:

```
Search domain query failed. Original hostname: 'api.github.com' failed to resolve 'api.github.com.us-east-2.compute.internal' after 3 queries 
```

I'm seeing this with both HttpClient and WebClient. e.g., code like this:

```
      WebClient client = WebClient.create(vertx);
      
      client
        .get(443,"api.github.com", "/users/qodfathr")
        .ssl(true)
        .send(ar -> {
            if (ar.succeeded()) {
                HttpResponse<Buffer> response = ar.result();
                rc.response().end(response.bodyAsString());
            } else {
                rc.response().end(ar.cause().getMessage());
            }
        });
```

When I tried adding a dot to the end of the host name, in order to stop automatic augmentation of the host name, both HttpClient and WebClient fail with

```
java.lang.IllegalArgumentException: Server name value of host_name cannot have the trailing dot
```

**Comment by qodfathr** [comment]
@slemeur for your visibility. I think SEV3 is about right, but this is impacting my ability to get demos ready.

**Comment by qodfathr** [comment]
Also, maybe my code is wrong. I welcome any corrections!

**Comment by qodfathr** [comment]
curl works from Che terminal window, so now I think it is related to my usage of vert.x and the vert.x router.

**Comment by christianvogt** [comment]
@qodfathr what happens if you set this property before your request:
`System.setProperty ("vertx.disableDnsResolver", "true");`

**Comment by qodfathr** [comment]
@christianvogt  I tried that but it did not help. I tried doing it in start() and also right before I create/use WebClient. Thanks for the suggestion.

**Comment by slemeur** [comment]
@qodfathr Could you push your code on your repo and share the link to it here? We might be able to find someone to help.

**Comment by qodfathr** [comment]
Resolved thanks to @maxandersen. Here is my modified Run command

```
scl enable rh-maven33 'mvn compile vertx:run -f ${current.project.path} -Dvertx.runArgs="-Dvertx.disableDnsResolver=true"'
```
