### ISSUE TITLE
14.000 auth errors during stresstest in launcher backend

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#3334]
I noticed sentry had seen 24K errors reported during the stress testing.

![2018-04-26_22-20-25](https://user-images.githubusercontent.com/54129/39333758-53bb3df6-49ac-11e8-8927-51ab1f74c20f.png)

14.000 of those are auth errors in launcher backend:
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/?query=+event.timestamp%3A%3E%3D2018-04-26T14%3A00%3A00++event.timestamp%3A%3C2018-04-26T15%3A00%3A00+

specifically https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/3750/

"Failed to create github client for user null" 

@pmacik was there anything in your tests that could explain why launcher backend didn't have proper credentials ? i.e. was there tests users without github linking setup or similar ? 

/cc @gastaldi

**Comment by gastaldi** [comment]
On a related topic, why are tests still running on the legacy Launcher UI?

**Comment by sbose78** [comment]
@gastaldi because we are gonna wait for a while before we set the feature flag of the new Launcher UI to 'released' for public. It's 'internal' for now.

**Comment by miteshvp** [comment]
@pmacik - this happens when load originates from single IP or single token as well.

**Comment by sbose78** [comment]
Any way to tell Github that this is legit traffic :)

**Comment by miteshvp** [comment]
In order to avoid that, we may have to follow their guidelines. https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits

**Comment by maxandersen** [comment]
> @maxandersen Hi, most of the failures here were caused by the abuse detection mechanism of GitHub:

thanks - that explains the amount of failures and makes it less of a concern; but also means our tests aren't able to scale up to concurrent users without rethinking/restructuring how this work.

> In order to avoid that, we may have to follow their guidelines. https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits

The key in here is:

```
Make requests for a single user or client ID serially. Do not make requests for a single user or client ID concurrently.
```

which is what I reckon are happening here - thus we don't really have any way out that creating test accounts for each concurrent user we need.

**Comment by animuk** [comment]
@maxandersen can it be closed at the moment.

**Comment by animuk** [comment]
closing this
