### ISSUE TITLE
Linking to GitHub from Markdown Fields

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#334]
# Description
As a user, I want to be able to put links to GitHub issues into the description fields or comments so that they directly link to the GitHub issue.

# Acceptance Criteria
- [ ]  The user can add a GitHub issue link to the description field by pasting the GitHub URL into the field.
- [ ]  The user can add a GitHub issue link to a comment field by pasting the GitHub URL into the field.
- [ ]  A GitHub link will be shortened in the rendered view to the form "#GH:XYZ" with "XYZ" the issue number.
 
# Relationships
_Put linked Team/Product story links here_

**Comment by sbose78** [comment]
Are we planning to have a working URL in the text fields - in that case all url strings in the text fields should be working url.

Or, we looking at rendering the urls in a fancy way ... Something like this - " https://github.com/fabric8io/fabric8-init-tenant/issues/105 "

**Comment by xcoulon** [comment]
I assume this will need some processing on the server-side, to convert from a syntax such as `#123` to an actual link.

**Comment by ldimaggi** [comment]
Will this take the form of URLs entered into the description and/or comment fields? Or, will we provide a dedicated field (arrary, etc.) to track github issues?

**Comment by joshuawilson** [comment]
It should be in the actual comment, like here in github.

**Comment by michaelkleinhenz** [comment]
TODO: we should discuss the format of the rendered link, like does it need to contain the type of external system ("GitHub") or the whole unique inf (org, project)?

**Comment by debloper** [comment]
This should provide some context on which all cases to cover: https://help.github.com/articles/autolinked-references-and-urls/

One advantage that GitHub has is that it doesn't require any identifier to mark it for GitHub itself, but for our case we will need an identifier to tag it for the site we're linking issues to (considering GitHub isn't going to be the only linkable external issue site).
