### ISSUE TITLE
Deployments page should not allow users to scale up when quota is reached

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#3345]
Parent: https://github.com/openshiftio/openshift.io/issues/3344

# Task

Disable the "Scale Up" button within deployment cards when the resource quota for the environment has been reached.

**Comment by joshuawilson** [comment]
@andrewazores, @qodfathr said this is not a P0.

**Comment by andrewazores** [comment]
OK. Do we want to close the PR or continue to merge this? FWIW I can see the argument against including the Launcher changes, but the change here to disable the Scale Up button in Deployments still seems to make sense IMO.

**Comment by qodfathr** [comment]
How does the OpenShift Console handle this? We probably should at least be consistent.

**Comment by andrewazores** [comment]
It allows the user to attempt to scale up, but then fails the action and links to the Events tab where it provides more detail on the cause of the failure. We don't have the ability to listen for these events from the Deployments page yet so we can't follow that pattern yet - this is discussed briefly in #2629 and the issue for it is #2380 .

**Comment by qodfathr** [comment]
Will the disabling of the scale up be reactive? i.e. if I'm on the deployments page and I do something, say in another browser tab, to free up resources, will the button enable automatically?

Also, what's the determination for disabling? If I'm out of RAM quota, sure -- that's a valid reason. But I could also have a little bit of RAM left yet it's not enough to scale up. In that case, doesn't the problem remain? I'm happy with fixing a common use case, but I want to ensure that it is, in fact, common.

**Comment by andrewazores** [comment]
Yes, it will enable/disable automatically, but only following the next polling cycle within whichever tab or client you're interested in. These cycles occur once per minute. Once a polling cycle occurs the data model will reflect that the environment quota has been reached (or not), and the button state will be updated to reflect this. This is completely independent of whether or not the tab or client instance you're using is the one that initiated the scale request.

The disable criteria in the PR is when either CPU or Memory quotas have been reached or exceeded for the environment. If you had your configs set up so that with 1024MB of quota you had allocated 1023MB to one pod, the button would still be enabled since you could technically allocate one more pod with 1MB of memory, even if this is not doable in practice.

**Comment by joshuawilson** [comment]
@catrobson we need confirmation from you as @andrewazores has a PR for this.

**Comment by andrewazores** [comment]
@catrobson tracking it here: https://openshift.io/openshiftio/openshiftio/plan/detail/2240 . I will file issues for individual fabric8-ui and fabric8-wit tasks for this feature and add them to the comments there.
