### ISSUE TITLE
s2i pods stuck in "Completed" status after a build

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#3349]
I have .a terminated pods completed stuck there waiting for over 20h : 

```
% oc get pod -n cboudjna-jenkins | grep Completed
space2-s2i-7-build           0/1       Completed   0          21h
```

It seem that they are still running (i.e: consume resources)

I am not really sure what is the cause of the issue why it is keeps it that way and we may want to investigate why.

- [ ] Check with SD team if this happen often or just an isolated case
- [ ] Investigate the root cause of the problem (why is s2i keeps it like this?) contact openshift folks if needed.
- [ ] See if we can workaround this in idler, we can easily add another check in the loop to see if these completed s2i pods are there for x amount of time and kill them as needed

<details><summary>Full JSON of stuck pod</summary>
<pre>
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "annotations": {
            "kubernetes.io/limit-ranger": "LimitRanger plugin set: cpu, memory request for container sti-build; cpu, memory limit for container sti-build; cpu, memory request for init container git-clone; cpu, memory limit for init container git-clone; cpu, memory request for init container manage-dockerfile; cpu, memory limit for init container manage-dockerfile",
            "openshift.io/build.name": "space2-s2i-7",
            "openshift.io/scc": "privileged"
        },
        "creationTimestamp": "2018-04-27T14:26:12Z",
        "labels": {
            "openshift.io/build.name": "space2-s2i-7"
        },
        "name": "space2-s2i-7-build",
        "namespace": "cboudjna-jenkins",
        "ownerReferences": [
            {
                "apiVersion": "build.openshift.io/v1",
                "controller": true,
                "kind": "Build",
                "name": "space2-s2i-7",
                "uid": "ef59cd9f-4a26-11e8-9d3a-02d7377a4b17"
            }
        ],
        "resourceVersion": "1097588225",
        "selfLink": "/api/v1/namespaces/cboudjna-jenkins/pods/space2-s2i-7-build",
        "uid": "ef60e7a7-4a26-11e8-826b-02e52a0be43d"
    },
    "spec": {
        "activeDeadlineSeconds": 3600,
        "containers": [
            {
                "args": [
                    "--loglevel=0"
                ],
                "command": [
                    "openshift-sti-build"
                ],
                "env": [
                    {
                        "name": "BUILD",
                        "value": "{\"kind\":\"Build\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"space2-s2i-7\",\"namespace\":\"cboudjna-jenkins\",\"selfLink\":\"/apis/build.openshift.io/v1/namespaces/cboudjna-jenkins/builds/space2-s2i-7\",\"uid\":\"ef59cd9f-4a26-11e8-9d3a-02d7377a4b17\",\"resourceVersion\":\"1097587986\",\"creationTimestamp\":\"2018-04-27T14:26:11Z\",\"labels\":{\"app\":\"space2\",\"buildconfig\":\"space2-s2i\",\"group\":\"io.openshift.booster\",\"openshift.io/build-config.name\":\"space2-s2i\",\"openshift.io/build.start-policy\":\"Serial\",\"provider\":\"fabric8\",\"version\":\"1.0.1\"},\"annotations\":{\"openshift.io/build-config.name\":\"space2-s2i\",\"openshift.io/build.number\":\"7\"},\"ownerReferences\":[{\"apiVersion\":\"build.openshift.io/v1\",\"kind\":\"BuildConfig\",\"name\":\"space2-s2i\",\"uid\":\"711a98d4-43e6-11e8-826b-02e52a0be43d\",\"controller\":true}]},\"spec\":{\"serviceAccount\":\"builder\",\"source\":{\"type\":\"Binary\",\"binary\":{}},\"strategy\":{\"type\":\"Source\",\"sourceStrategy\":{\"from\":{\"kind\":\"DockerImage\",\"name\":\"registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.2\"},\"forcePull\":true}},\"output\":{\"to\":{\"kind\":\"DockerImage\",\"name\":\"docker-registry.default.svc:5000/cboudjna-jenkins/space2:1.0.7\"},\"pushSecret\":{\"name\":\"builder-dockercfg-5287l\"}},\"resources\":{},\"postCommit\":{},\"nodeSelector\":{},\"triggeredBy\":null},\"status\":{\"phase\":\"New\",\"outputDockerImageReference\":\"docker-registry.default.svc:5000/cboudjna-jenkins/space2:1.0.7\",\"config\":{\"kind\":\"BuildConfig\",\"namespace\":\"cboudjna-jenkins\",\"name\":\"space2-s2i\"},\"output\":{}}}\n"
                    },
                    {
                        "name": "ORIGIN_VERSION",
                        "value": "v3.9.14"
                    },
                    {
                        "name": "ALLOWED_UIDS",
                        "value": "1-"
                    },
                    {
                        "name": "DROP_CAPS",
                        "value": "KILL,MKNOD,SETGID,SETUID"
                    },
                    {
                        "name": "PUSH_DOCKERCFG_PATH",
                        "value": "/var/run/secrets/openshift.io/push"
                    }
                ],
                "image": "registry.reg-aws.openshift.com:443/openshift3/ose-sti-builder:v3.9.14",
                "imagePullPolicy": "Always",
                "name": "sti-build",
                "resources": {
                    "limits": {
                        "cpu": "1",
                        "memory": "512Mi"
                    },
                    "requests": {
                        "cpu": "60m",
                        "memory": "307Mi"
                    }
                },
                "securityContext": {
                    "privileged": true
                },
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "FallbackToLogsOnError",
                "volumeMounts": [
                    {
                        "mountPath": "/tmp/build",
                        "name": "buildworkdir"
                    },
                    {
                        "mountPath": "/var/run/docker.sock",
                        "name": "docker-socket"
                    },
                    {
                        "mountPath": "/var/run/crio/crio.sock",
                        "name": "crio-socket"
                    },
                    {
                        "mountPath": "/var/run/secrets/openshift.io/push",
                        "name": "builder-dockercfg-5287l-push",
                        "readOnly": true
                    },
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "builder-token-cts26",
                        "readOnly": true
                    }
                ]
            }
        ],
        "dnsPolicy": "ClusterFirst",
        "imagePullSecrets": [
            {
                "name": "builder-dockercfg-5287l"
            }
        ],
        "initContainers": [
            {
                "args": [
                    "--loglevel=0"
                ],
                "command": [
                    "openshift-git-clone"
                ],
                "env": [
                    {
                        "name": "BUILD",
                        "value": "{\"kind\":\"Build\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"space2-s2i-7\",\"namespace\":\"cboudjna-jenkins\",\"selfLink\":\"/apis/build.openshift.io/v1/namespaces/cboudjna-jenkins/builds/space2-s2i-7\",\"uid\":\"ef59cd9f-4a26-11e8-9d3a-02d7377a4b17\",\"resourceVersion\":\"1097587986\",\"creationTimestamp\":\"2018-04-27T14:26:11Z\",\"labels\":{\"app\":\"space2\",\"buildconfig\":\"space2-s2i\",\"group\":\"io.openshift.booster\",\"openshift.io/build-config.name\":\"space2-s2i\",\"openshift.io/build.start-policy\":\"Serial\",\"provider\":\"fabric8\",\"version\":\"1.0.1\"},\"annotations\":{\"openshift.io/build-config.name\":\"space2-s2i\",\"openshift.io/build.number\":\"7\"},\"ownerReferences\":[{\"apiVersion\":\"build.openshift.io/v1\",\"kind\":\"BuildConfig\",\"name\":\"space2-s2i\",\"uid\":\"711a98d4-43e6-11e8-826b-02e52a0be43d\",\"controller\":true}]},\"spec\":{\"serviceAccount\":\"builder\",\"source\":{\"type\":\"Binary\",\"binary\":{}},\"strategy\":{\"type\":\"Source\",\"sourceStrategy\":{\"from\":{\"kind\":\"DockerImage\",\"name\":\"registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.2\"},\"forcePull\":true}},\"output\":{\"to\":{\"kind\":\"DockerImage\",\"name\":\"docker-registry.default.svc:5000/cboudjna-jenkins/space2:1.0.7\"},\"pushSecret\":{\"name\":\"builder-dockercfg-5287l\"}},\"resources\":{},\"postCommit\":{},\"nodeSelector\":{},\"triggeredBy\":null},\"status\":{\"phase\":\"New\",\"outputDockerImageReference\":\"docker-registry.default.svc:5000/cboudjna-jenkins/space2:1.0.7\",\"config\":{\"kind\":\"BuildConfig\",\"namespace\":\"cboudjna-jenkins\",\"name\":\"space2-s2i\"},\"output\":{}}}\n"
                    },
                    {
                        "name": "ORIGIN_VERSION",
                        "value": "v3.9.14"
                    },
                    {
                        "name": "ALLOWED_UIDS",
                        "value": "1-"
                    },
                    {
                        "name": "DROP_CAPS",
                        "value": "KILL,MKNOD,SETGID,SETUID"
                    }
                ],
                "image": "registry.reg-aws.openshift.com:443/openshift3/ose-sti-builder:v3.9.14",
                "imagePullPolicy": "Always",
                "name": "git-clone",
                "resources": {
                    "limits": {
                        "cpu": "1",
                        "memory": "512Mi"
                    },
                    "requests": {
                        "cpu": "60m",
                        "memory": "307Mi"
                    }
                },
                "stdin": true,
                "stdinOnce": true,
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "FallbackToLogsOnError",
                "volumeMounts": [
                    {
                        "mountPath": "/tmp/build",
                        "name": "buildworkdir"
                    },
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "builder-token-cts26",
                        "readOnly": true
                    }
                ]
            },
            {
                "args": [
                    "--loglevel=0"
                ],
                "command": [
                    "openshift-manage-dockerfile"
                ],
                "env": [
                    {
                        "name": "BUILD",
                        "value": "{\"kind\":\"Build\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"space2-s2i-7\",\"namespace\":\"cboudjna-jenkins\",\"selfLink\":\"/apis/build.openshift.io/v1/namespaces/cboudjna-jenkins/builds/space2-s2i-7\",\"uid\":\"ef59cd9f-4a26-11e8-9d3a-02d7377a4b17\",\"resourceVersion\":\"1097587986\",\"creationTimestamp\":\"2018-04-27T14:26:11Z\",\"labels\":{\"app\":\"space2\",\"buildconfig\":\"space2-s2i\",\"group\":\"io.openshift.booster\",\"openshift.io/build-config.name\":\"space2-s2i\",\"openshift.io/build.start-policy\":\"Serial\",\"provider\":\"fabric8\",\"version\":\"1.0.1\"},\"annotations\":{\"openshift.io/build-config.name\":\"space2-s2i\",\"openshift.io/build.number\":\"7\"},\"ownerReferences\":[{\"apiVersion\":\"build.openshift.io/v1\",\"kind\":\"BuildConfig\",\"name\":\"space2-s2i\",\"uid\":\"711a98d4-43e6-11e8-826b-02e52a0be43d\",\"controller\":true}]},\"spec\":{\"serviceAccount\":\"builder\",\"source\":{\"type\":\"Binary\",\"binary\":{}},\"strategy\":{\"type\":\"Source\",\"sourceStrategy\":{\"from\":{\"kind\":\"DockerImage\",\"name\":\"registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.2\"},\"forcePull\":true}},\"output\":{\"to\":{\"kind\":\"DockerImage\",\"name\":\"docker-registry.default.svc:5000/cboudjna-jenkins/space2:1.0.7\"},\"pushSecret\":{\"name\":\"builder-dockercfg-5287l\"}},\"resources\":{},\"postCommit\":{},\"nodeSelector\":{},\"triggeredBy\":null},\"status\":{\"phase\":\"New\",\"outputDockerImageReference\":\"docker-registry.default.svc:5000/cboudjna-jenkins/space2:1.0.7\",\"config\":{\"kind\":\"BuildConfig\",\"namespace\":\"cboudjna-jenkins\",\"name\":\"space2-s2i\"},\"output\":{}}}\n"
                    },
                    {
                        "name": "ORIGIN_VERSION",
                        "value": "v3.9.14"
                    },
                    {
                        "name": "ALLOWED_UIDS",
                        "value": "1-"
                    },
                    {
                        "name": "DROP_CAPS",
                        "value": "KILL,MKNOD,SETGID,SETUID"
                    }
                ],
                "image": "registry.reg-aws.openshift.com:443/openshift3/ose-sti-builder:v3.9.14",
                "imagePullPolicy": "Always",
                "name": "manage-dockerfile",
                "resources": {
                    "limits": {
                        "cpu": "1",
                        "memory": "512Mi"
                    },
                    "requests": {
                        "cpu": "60m",
                        "memory": "307Mi"
                    }
                },
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "FallbackToLogsOnError",
                "volumeMounts": [
                    {
                        "mountPath": "/tmp/build",
                        "name": "buildworkdir"
                    },
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "builder-token-cts26",
                        "readOnly": true
                    }
                ]
            }
        ],
        "nodeName": "ip-172-31-65-225.us-east-2.compute.internal",
        "nodeSelector": {
            "type": "compute"
        },
        "restartPolicy": "Never",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "builder",
        "serviceAccountName": "builder",
        "terminationGracePeriodSeconds": 30,
        "tolerations": [
            {
                "effect": "NoSchedule",
                "key": "node.kubernetes.io/memory-pressure",
                "operator": "Exists"
            }
        ],
        "volumes": [
            {
                "emptyDir": {},
                "name": "buildworkdir"
            },
            {
                "hostPath": {
                    "path": "/var/run/docker.sock",
                    "type": ""
                },
                "name": "docker-socket"
            },
            {
                "hostPath": {
                    "path": "/var/run/crio/crio.sock",
                    "type": ""
                },
                "name": "crio-socket"
            },
            {
                "name": "builder-dockercfg-5287l-push",
                "secret": {
                    "defaultMode": 384,
                    "secretName": "builder-dockercfg-5287l"
                }
            },
            {
                "name": "builder-token-cts26",
                "secret": {
                    "defaultMode": 420,
                    "secretName": "builder-token-cts26"
                }
            }
        ]
    },
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2018-04-27T14:26:18Z",
                "reason": "PodCompleted",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2018-04-27T14:26:24Z",
                "reason": "PodCompleted",
                "status": "False",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2018-04-27T14:26:12Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "containerStatuses": [
            {
                "containerID": "docker://ba8096145e2a92474e4cfd686d963457f2dd8760005f4e4534f5e364646de662",
                "image": "registry.reg-aws.openshift.com:443/openshift3/ose-sti-builder:v3.9.14",
                "imageID": "docker-pullable://registry.reg-aws.openshift.com:443/openshift3/ose-sti-builder@sha256:e8ca49689b4ddf2775bf65c63e9b5c764731c3feca1e246942ff8cc68074e37f",
                "lastState": {},
                "name": "sti-build",
                "ready": false,
                "restartCount": 0,
                "state": {
                    "terminated": {
                        "containerID": "docker://ba8096145e2a92474e4cfd686d963457f2dd8760005f4e4534f5e364646de662",
                        "exitCode": 0,
                        "finishedAt": "2018-04-27T14:26:24Z",
                        "reason": "Completed",
                        "startedAt": "2018-04-27T14:26:18Z"
                    }
                }
            }
        ],
        "hostIP": "172.31.65.225",
        "initContainerStatuses": [
            {
                "containerID": "docker://72be3fb3d133a27ce8423d47540ead1c1bba66ac4d6fcb6733cce5a56fbf7b15",
                "image": "registry.reg-aws.openshift.com:443/openshift3/ose-sti-builder:v3.9.14",
                "imageID": "docker-pullable://registry.reg-aws.openshift.com:443/openshift3/ose-sti-builder@sha256:e8ca49689b4ddf2775bf65c63e9b5c764731c3feca1e246942ff8cc68074e37f",
                "lastState": {},
                "name": "git-clone",
                "ready": true,
                "restartCount": 0,
                "state": {
                    "terminated": {
                        "containerID": "docker://72be3fb3d133a27ce8423d47540ead1c1bba66ac4d6fcb6733cce5a56fbf7b15",
                        "exitCode": 0,
                        "finishedAt": "2018-04-27T14:26:16Z",
                        "reason": "Completed",
                        "startedAt": "2018-04-27T14:26:14Z"
                    }
                }
            },
            {
                "containerID": "docker://efd1c841aeced6555b0598be4f7f9318805eebe61336cd0d731a569648370f5a",
                "image": "registry.reg-aws.openshift.com:443/openshift3/ose-sti-builder:v3.9.14",
                "imageID": "docker-pullable://registry.reg-aws.openshift.com:443/openshift3/ose-sti-builder@sha256:e8ca49689b4ddf2775bf65c63e9b5c764731c3feca1e246942ff8cc68074e37f",
                "lastState": {},
                "name": "manage-dockerfile",
                "ready": true,
                "restartCount": 0,
                "state": {
                    "terminated": {
                        "containerID": "docker://efd1c841aeced6555b0598be4f7f9318805eebe61336cd0d731a569648370f5a",
                        "exitCode": 0,
                        "finishedAt": "2018-04-27T14:26:18Z",
                        "reason": "Completed",
                        "startedAt": "2018-04-27T14:26:17Z"
                    }
                }
            }
        ],
        "phase": "Succeeded",
        "podIP": "10.130.94.68",
        "qosClass": "Burstable",
        "startTime": "2018-04-27T14:26:12Z"
    }
}
</pre>
</details>

<br>
/cc @pbergene @kbsingh @jfchevrette

**Comment by chmouel** [comment]
Same for those : 

```
jenkins-slave-48fhs-40l2h   0/2       DeadlineExceeded   0          17d
```

Should we do something about it ?

**Comment by bartoszmajsak** [comment]
Just was hit by the same issue. So maybe it is not P4 @GeorgeActon

**Comment by chmouel** [comment]
This should get better with the new Gluster deployment, I am going to close this for now,
