### ISSUE TITLE
Fixed Attributes on Work Items

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#335]
# Description
As a user, I want to have a set of fixed attributes on all Work Item Types. These attributes describe mandatory information that is used in the semantic behavior of the Planner and OSIO.

# Acceptance Criteria
- [ ] All fixed attribute fields existing in the current implementation are unchanged.
- [ ] The user can set an attribute field "state" that describes the current state of a Work Item. The field is an enumeration. The possible values are defined by the current Space Template and are local to the specific Work Item Type.
- [ ] The user can set an attribute field "reason" to further describe the last state change. The field is an enumeration. The possible values are defined by the current Space Template and are local to the specific Work Item Type.
 
# Relationships
_Put linked Team/Product story links here_

**Comment by maxandersen** [comment]
> states are now stable across all Work Item Types
You mean list of states are global for the whole system or just per space template ?  
is that any different from what is there now ?

**Comment by michaelkleinhenz** [comment]
Yeah, that is an open question I also had. As we don't have a sane way of configuring or storing "system wide space-crossing" settings of types, those should go into the Space template.
