### ISSUE TITLE
Workitems missing from users' space dashboard if account is set to 'production'

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3352]
If the user account is set to opt-in 'production' workitems are missing from the space dashboard:

![screenshot from 2018-04-29 09-48-37](https://user-images.githubusercontent.com/642621/39407346-aada9540-4b92-11e8-801c-6925badf903a.png)

**Comment by joshuawilson** [comment]
Haha! It works!
That is the planner widget and Planner is still Experimental. That means you must be on Beta or Released.

This is working as designed.

**Comment by joshuawilson** [comment]
@qodfathr @catrobson if you want something done please reopen.
