### ISSUE TITLE
Fix release pipeline for Jenkins image 

### ISSUE THREAD

**Issue by rupalibehera** [openshiftio/openshift.io#3353]
https://jenkins.cd.test.fabric8.io/job/fabric8io-auto-rel/job/openshift-jenkins-s2i-config/job/master/34/console
https://jenkins.cd.test.fabric8.io/job/fabric8-services/job/fabric8-tenant/job/master/224/console
https://github.com/fabric8-services/fabric8-tenant-jenkins/blob/master/release.groovy#L50

**Comment by rupalibehera** [comment]
This issue blocks release of jenkins-sync-plugin and jenkins image

**Comment by jaseemabid** [comment]
@rupalibehera Good catch. Hopefully this wont be difficult with the recent fixes (https://github.com/openshiftio/openshift.io/issues/3324) on pipeline library.

**Comment by rupalibehera** [comment]
https://github.com/fabric8io/openshift-jenkins-s2i-config
https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/81
