### ISSUE TITLE
Are Add Codebase and Launcher workflows going to be synced

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#3354]
Hi, I am documenting the add codebase section. I have 3 questions/observations:

1. On the Dashboard(Analyze tab) in the Codebase section, we have 2 buttons Add codebase and Import codebase.
Add codebase takes you to new launcher wizard. Import codebase however has a slider as follows:

![screenshot from 2018-04-30 12-14-40](https://user-images.githubusercontent.com/16647625/39417599-03e2d66c-4c73-11e8-908d-23018aeffd65.png)

This has the same workflow as the import codebase from within new launcher wizard. As such is this section being redesigned to provide an uniform workflow. Are we planning to remove the Import codebase and have a single button (Add or Import codebase) which takes you to the launcher flow?

2. On the dashboard(Analyze tab) in the Codebase section, when you click the plus sign(+) next to codebase, it takes you to Create>Codebase section and again shows you the slider, will this section be modified/synced too?

![screenshot from 2018-04-30 12-38-06](https://user-images.githubusercontent.com/16647625/39417653-6d906e30-4c73-11e8-8cd4-592357d838f6.png)

3. In the Create>Codebase section, clicking Add Codebase(center one or on the top right)shows you the slider again? Which is not consistent with my experience of seeing the Launcher wizard when I click Add Codebase in the dashboard(analyze). We need to have an uniform/consistent experience for this too?

AFAIU, both the slider and the new launcher workflow help the user achieve the same end result. As such, the current flow will surely confuse the end user. Please correct me if I am wrong.

**Comment by invincibleJai** [comment]
@Preeticp yes makes sense to me , we are tracking this work here https://github.com/openshiftio/openshift.io/issues/3363

**Comment by joshuawilson** [comment]
@Preeticp it looks like your question has been answered, I'm closing this. Please reopen if you need still have questions.
