### ISSUE TITLE
[5] Add support for multiple repositories to graph layer

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#3358]
Planner: https://openshift.io/openshiftio/openshiftio/plan/detail/2338

# User Story

As a consumer of data from graph layer, I want to know in which repositories a particular package or version can be found. Knowing that information could help me to decide whether I want to use the package/version in my project or not.

# Description

In order to support multiple repositories, graph layer needs to be modified so it is aware of the fact that particular EPV or EP could belong to one or multiple repositories. The information about repositories in which a particular package can be found needs to be captured so it can be later propagated to other components/services which query graph and may be interested in that information. 

This will require changes to the current graph schema.

data-importer also needs to be modified so it takes multiple repositories into account, wherever applicable.

# Tasks
TBD

**Comment by GeetikaBatra** [comment]
@msrb Can we close this?

**Comment by msrb** [comment]
Yes.
