### ISSUE TITLE
UX for Threaded Comments

### ISSUE THREAD

**Issue by Veethika** [openshiftio/openshift.io#3360]
OSIO Planner link for the task : https://openshift.io/openshiftio/openshiftio/plan/detail/2192
(All the InVision prototype links are regularly updated on Planner)
Define interaction rules for how to create, display, delete and edit comments and nested comments.

**Comment by joshuawilson** [comment]
I find it annoying that the order is display newest at the top. While this may be easier to read if you are keeping up with it. But in most cases you need to read from the beginning, that would mean I would have to scroll to the bottom and read up. This is very un-natural.

**Comment by Veethika** [comment]
@joshuawilson thanks for your inputs. These decisions were taken over a long period of time with several considerations in picture and any changes made might affect many other elements as well. That said, very soon we'd be carrying out a user-testing session to validate those decisions/ understand the user concerns better.

InVision link: https://redhat.invisionapp.com/share/PQJOF87V4G6#/294300421_Title
