### ISSUE TITLE
[5] Ability to register packages/versions in graph without analyzing them first 

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#3361]
Planner: https://openshift.io/openshiftio/openshiftio/plan/detail/2339

# User Story

As a consumer of data from graph layer, I want to know if packages/versions exist and if so, in which repositories they are available. Having this information can help me to decide, among other things, what is the latest version of a package in repositories that I care about, even without the need to analyze all the packages first.

# Description

In graph, we currently only have information about packages that we've already analyzed. Therefore significant portion of packages is always "unknown" to us. This can lead to situations when we incorrectly identify for example latest available version of a package, simply because we haven't analyzed the truly latest one yet. This will become even more trickier when we start supporting multiple repositories per ecosystem. We will assume that EPVs are globally unique (at least on graph layer), but we need to know in which repositories those EPVs are. When we first discover a package in Maven Central, we want to inform graph layer about that. And when we later discover the same package in for example MRRC, we want to inform graph layer as well, but this time graph should just update the existing EPV and note the occurrence in another repository.

This could be implemented by adding a new endpoint to data-importer which would enable other services to register newly discovered EPVs, together with information about a repository it was discovered in. It should be possible to call the endpoint twice for the same REPV (repository-ecosystem-package-version) and endpoint should recognize that the REPV already exist and do nothing. I.e. the operation should be idempotent.

# Tasks
TBD

**Comment by GeetikaBatra** [comment]
@msrb. This one can also be closed, right?
