### ISSUE TITLE
Linking a work item to another parent displays duplicate entries of a work item

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3364]
1) Select a parented work item and manually change its parent to another work item, using the link field
2) Observe that the edited work item is displayed under the old parent, and as well as under the new parent
3) Refresh the page but the behavior persists
4) Clicking on the work item under old parent makes the list view jump and hop as the entry even though displayed, is actually not clickable

![links and list view issues](https://user-images.githubusercontent.com/28748448/39422904-1b384e2c-4c8d-11e8-858b-ed210b5b5495.gif)

**Comment by rgarg1** [comment]
p0? @qodfathr

**Comment by qodfathr** [comment]
Yes.

**Comment by rgarg1** [comment]
Hard refresh does not solve the problem @baijum

**Comment by baijum** [comment]
@rgarg1 Thanks for the confirmation!

This could be a backend issue probably with some misaligned data which requires data-migration. @kwk  Do you have any suggestion to make here?

**Comment by baijum** [comment]
There is no data discrepancy. @DhritiShikhar has send a PR to fix it: https://github.com/fabric8-services/fabric8-wit/pull/2075

**Comment by baijum** [comment]
I think QE might need to verify it. Reopening now.

**Comment by DhritiShikhar** [comment]
@rgarg1 can you please confirm?

**Comment by rgarg1** [comment]
@DhritiShikhar Issue is fixed in prod-preview. Close this issue once the fix is in prod.

**Comment by kwk** [comment]
Reopening because not yet verified in prod.

**Comment by jarifibrahim** [comment]
The issue no longer exists on Prod/Prod-preview.

Fixed via https://github.com/fabric8-services/fabric8-wit/pull/2075
