### ISSUE TITLE
Visual Design for Intro to OpenShift.io (8)

### ISSUE THREAD

**Issue by Veethika** [openshiftio/openshift.io#3366]
Create visual design assets and animations needed for Intro to OpenShift.io - Content and Interaction Design work was done in issue #2886 

VERIFICATION CRITERIA:

- [ ] Discuss with front-end developers to decide on the most relevant format for deliverable
- [ ] Discuss with front-end developers and writers to explore the process to house content in a separate file and pull into UI -- pull Robert Kratky into this conversation, launcher and planner teams have both explored ways to do this. 

- [ ] Design carousel cards for the four Value-propositions listed here: https://docs.google.com/document/d/1PmDC1r5I1iUpX7Euz-1wUO-2v_z_sJdesZtDNNIk4Jo/edit#heading=h.k74zicuk52ap

- [ ] Create required animations and decide on the transitions in between

- [ ] Push the content for development

**Comment by AshishDurgude** [comment]
I have started working on the above referenced issue #4070 . So I am removing (unassigning) myself from this issue.

**Comment by ldimaggi** [comment]
Is this the same issue referenced here:   https://openshift.io/openshiftio/Openshift_io/plan/detail/508

**Comment by Veethika** [comment]
The direction for this task has largely deviated. The validity of the solution would be questionable in the newly proposed architecture. @serenamarie125 Should this be closed?

**Comment by joshuawilson** [comment]
@serenamarie125 should this be closed?

**Comment by serenamarie125** [comment]
Closing as this widget has been removed from OSIO
