### ISSUE TITLE
504 gateway timeout using new launcher during stress test 

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#3367]
from @pmacik:
" test was able to show that especially in the Launcher (the new one), there were a lot of services whose endpoints timed out under load (Errors 504 (Gateway Time-out). You can find it in the [report](https://docs.google.com/spreadsheets/d/1A0R_7wdviAO2JJeirr8-U5NTb5m1CwmVa9rE6do6hgM/edit) around create-quickstart-ngx.* steps."

If you can't access repot here is an extract of what I could find - see full list in the report

491 |   | https://forge.api.openshift.io/api/services/git/user - Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
-- | -- | --
449 |   | https://forge.api.openshift.io/api/services/jenkins/pipelines - Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
557 |   | "https://forge.api.openshift.io/api/launchpad/commands/fabric8-import-git - Failed to load resource: the server responded with a status of 504 (Gateway Time-out)" and "https://openshift.io/<user_name>/<app_name> - Failed to load https://forge.api.openshift.io/api/launchpad/commands/fabric8-import-git: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://openshift.io' is therefore not allowed access. The response had HTTP status code 504."
558 |   | "https://forge.api.openshift.io/api/launchpad/commands/fabric8-new-project - Failed to load resource: the server responded with a status of 504 (Gateway Time-out)" and "https://openshift.io/<user_name>/<app_name> - Failed to load https://forge.api.openshift.io/api/launchpad/commands/fabric8-new-project: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://openshift.io' is therefore not allowed access. The response had HTTP status code 504."
1 |   | https://forge.api.openshift.io/api/services/git/organizations - Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
-- | -- | --
30 |   | https://forge.api.openshift.io/api/services/git/user - Failed to load resource: the server responded with a status of 504 (Gateway Time-out)

Marking as sev1 as this is indicating we got load issues.

**Comment by gastaldi** [comment]
@maxandersen here is my analysis so far: 

- the `/services/git/user`, `/services/git/repositories` and `/services/git/organizations` all query GitHub for data, which may indicate a consequence of GitHub denying requests due to https://github.com/openshiftio/openshift.io/issues/3334. 

One solution that I can see is to change the frontend to no longer call these endpoints directly and call the GitHub API directly to fetch this data.

- As for the https://forge.api.openshift.io/api/launchpad/commands/fabric8-new-project and https://forge.api.openshift.io/api/launchpad/commands/fabric8-import-git, they shouldn't have been called since as @pmacik described, they are testing the new Launcher UI, and this endpoint belongs to the legacy flow

- I'm investigating what may cause `https://forge.api.openshift.io/api/services/jenkins/pipelines - Failed to load resource: the server responded with a status of 504 (Gateway Time-out)` to happen.

**Comment by gastaldi** [comment]
Worth checking if the changes introduced in https://github.com/fabric8-launcher/launcher-planning/issues/148 might cause 504 errors due to high load on a single node

**Comment by gastaldi** [comment]
I have pushed a change to the backend which should fail-fast the request if any GitHub limit is reached: https://github.com/fabric8-launcher/launcher-backend/commit/84039e280d059c83c6b65d0731d96abe64241c86

That should prevent requests from waiting for the GitHub retry period according to https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits

**Comment by krishnapaparaju** [comment]
@animuk I guess the earlier load tests excluded all the APIs involving GitHub. How many GitHub accounts been used to for these simulated OSIO users for load testing ?

**Comment by gastaldi** [comment]
@ldimaggi @pmacik when can we re-run these tests again? I have pushed my changes in my previous comment to production.

**Comment by gastaldi** [comment]
Action items for this issue: 

- [x] Update production to run the fix introduced in fabric8-launcher/launcher-backend@84039e2 - @gastaldi
- [ ] Update the frontend to query the Github API directly when retrieving the organizations and repositories - @edewit 
- [ ] Verify if the `haproxy.router.openshift.io/balance=source` route annotation may cause 504 timeout errors - @animuk

**Comment by ALRubinger** [comment]
This to me looks like we're trying to stress test external services, which would constitute a violation of the terms for these services.  There is a reason that GitHub, for example, puts rate limits in place.  When our tests exceed these limits, we get errors thrown.

Recommend stress testing our own services and mocking the GitHub and other external calls when we're putting our stuff under load.

**Comment by gastaldi** [comment]
@maxandersen I guess the fix in https://github.com/fabric8-launcher/launcher-backend/commit/84039e2 is what the launcher can do, we can't prevent tests from violating the GitHub terms by making multiple requests with the same account

**Comment by maxandersen** [comment]
@ALRubinger we are stress testing the flow exposed in launcher/start wizard - that flow fails. Does not matter if its github or jenkins or forge itself failing  - end result is we have a problem we'll need to handle somehow.

btw. not all of these has to do with github limits afaics.

**Comment by edewit** [comment]
Sure, but the problem is that with a limited set of github users doing the
same requests is like a denial of service attack on github. And github will
react accordingly. If the goal of these tests is to see how Launch can
handle the possible load github should not be called

**Comment by animuk** [comment]
@edewit @krishnapaparaju yes. This 504 issue occurs due to limited set of github unique user token used during stress tests executed for the launcher GIT APIs as those third party GIT Native APIs has limitation implemented per user and throttles the incoming request.

**Comment by animuk** [comment]
closing this for now.
