### ISSUE TITLE
Selecting on spring-boot runtime on new launcher disabled mission wrongly.

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#3370]
Basically, if any mission is not

Steps to reproduce:

1. Create a new codebase using New LAuncher flow
2. In the first screen, select spring boot runtime radio button without selecting any missions
3. You can see last 2 missions getting disabled.

This is not expected as they both are valid.

**Comment by ldimaggi** [comment]
This bug blocks users from creating new SpringBoot REST and SpringBoot HealthCheck quickstarts.

**Comment by invincibleJai** [comment]
@ldimaggi am not sure how it's blocking as if you select mission first than runtimes it should work just fine. Above issue appears if you select Runtimes first and then select the mission.

**Comment by ldimaggi** [comment]
Ah - sorry - thanks.

**Comment by invincibleJai** [comment]
@arunkumars08 is looking into this on priority, fix will be in place soon.

**Comment by sunilk747** [comment]
@arunkumars08 I tested it and it's working fine for me. We are good to go here. Please go ahead and merge it.
