### ISSUE TITLE
Update OpenShift.io landing page content

### ISSUE THREAD

**Issue by AdamJ** [openshiftio/openshift.io#3373]
As part of the upcoming updates, the OpenShift.io landing page content needs to be updated. This includes new screenshots, content, button information and any additional information as governed by PM and UXD.

- [x] Review content/copy with Stacy
- [x] Review updates with Cat
- [x] File PR for PM review and include screenshots of updates

**Comment by mindreeper2420** [comment]
Updates:
- Added a page ribbon for callouts
- Updated screenshots as directed
- Updated content/copy per requests
