### ISSUE TITLE
Wireframes: Multiple Git providers 

### ISSUE THREAD

**Issue by lwrigh** [openshiftio/openshift.io#3374]
### Description
Wireframes that cover the full set of designs needed for adding multiple Git providers to a user's Openshift.io account. 

### Parent Issue(s)
- #2841
- #2723

### Verification Criteria
- [x] Wireframes created in Sketch and posted on Google Drive with interaction notes for all behaviors
- [x] Wireframes posted to InVision
- [ ] Wireframes reviewed by UXD, Dev, PM

**Comment by lwrigh** [comment]
Here are in progress wireframes: https://redhat.invisionapp.com/share/ZUHTZODRGME#/294127344_Settings-_Multiple_Git_Providers @catrobson

**Comment by lwrigh** [comment]
Wireframes have been updated to reflect BitBucket as another supported Git provider

**Comment by lwrigh** [comment]
@catrobson @alexeykazakov @aslakknutsen @qodfathr 
What are your thoughts on these wireframes for integrating BitBucket into the Launcher and the user settings? 

Here's the latest link: https://redhat.invisionapp.com/share/KWKMUW7CJT3

**Comment by catrobson** [comment]
@lwrigh @mceledonia can you help explain if we should be looking at these or looking at @mceledonia's latest designs?  Are these being combined in some way?

**Comment by lwrigh** [comment]
@mceledonia Have you been working on multiple Git providers too?

**Comment by catrobson** [comment]
@lwrigh oh shoot - sorry, my fault.  I was looking across too many tabs.  This is independent work from @mceledonia.  Will review and comment in InVision!

**Comment by lwrigh** [comment]
Here are the most recent wireframes: https://redhat.invisionapp.com/share/9SL3BF2PUCM

**Comment by lwrigh** [comment]
Here are the most recent wireframes with interaction notes included: https://redhat.invisionapp.com/share/U7LVS3QQF9K

**Comment by serenamarie125** [comment]
@catrobson is there additional work that needs to be accomplished as part of this issue?

**Comment by catrobson** [comment]
No, I think this is ready to close.  This has been deprioritized from engineering standpoint, so we can set these wireframes to the side until this comes back around as a priority later.  Closing issue.
