### ISSUE TITLE
Some user accounts are seeing a continuous stream of - f8osoproxy 401 errors

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3377]
This problem started on my user account on April 27. After logging in, I was unable to create a new quickstart. 

The Chrome console showed a continuous stream of these errors:
```
WebSocket connection to 'wss://f8osoproxy-test-dsaas-
production.09b5.dsaas.openshiftapps.com/oapi/v1/namespaces/ldimaggi/builds?
watch=true&access_token=...' failed: HTTP Authentication failed; no valid credentials available
```
NOTE: In the above example - I removed the text of the token and username.

The resolution for the problem was to refresh the OpenShift Online connection:
![screenshot from 2018-04-30 09-29-48](https://user-images.githubusercontent.com/642621/39429973-87995e7c-4c5a-11e8-8799-63ee9a5d40bc.png)

The cause for the problem is unclear - is this happening to older accounts because a token is expiring? My account was created on:  2017-04-24

**Comment by alexeykazakov** [comment]
Yes. Old accounts had OSO token which expires and needs to be refreshed. New users should not have this problem. Closing it. Please reopen if it still an issue for new accounts.

**Comment by sbose78** [comment]
@rohitkrai03 , in this above page, do we use https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/account/provider.service.ts#L68  `force_pull=true` for getting the OSO token status ? In that case, an expired OSO token would be red flagged in this page.
