### ISSUE TITLE
Update Home Dashboard "Whats New" Carousel

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#3379]
As part of the Experimental Features, the Home Dashboard will have a "Whats New" section at the top of the page. This content needs to be updated and functionality altered in order to accommodate the current information.

- [x] Remove expand/collapse button
- [x] Update indicator styling
- [x] Update 2nd section information

**Comment by mindreeper2420** [comment]
**Updated slide 1 of the carousel**

<img width="1920" alt="screen shot 2018-04-29 at 12 24 27 pm" src="https://user-images.githubusercontent.com/4032718/39432091-9519fdb2-4c60-11e8-97f5-0685cbba5f71.png">

**Updated slide 2 of the carousel**

![screen shot 2018-04-30 at 10 54 51 am](https://user-images.githubusercontent.com/4032718/39433868-f9c618aa-4c64-11e8-8a93-d4866ff72b30.png)

**Comment by mindreeper2420** [comment]
At a smaller screen size, the informational paragraph will be hidden, allowing the user to still click on the "Learn more" button, without making the banner any larger.

<img width="887" alt="screen shot 2018-04-30 at 6 31 03 pm" src="https://user-images.githubusercontent.com/4032718/39453618-a9a2bd8e-4ca4-11e8-84db-4767cfad5222.png">

<img width="888" alt="screen shot 2018-04-30 at 6 29 24 pm" src="https://user-images.githubusercontent.com/4032718/39453610-9f32bbf6-4ca4-11e8-9919-712f334299d1.png">

**Comment by catrobson** [comment]
We don't actually have space avatars, only user avatars, as far as I know @mindreeper2420 - shouldn't the first one just be about allowing you to have your personal avatar as a user?

**Comment by mindreeper2420** [comment]
Ah, yup. I'll update the header and description.

**Comment by mindreeper2420** [comment]
@catrobson Update to remove "Space Avatars" and replace with "User Avatars".

![screen shot 2018-05-01 at 8 58 36 am](https://user-images.githubusercontent.com/4032718/39473671-eef66466-4d1d-11e8-9072-56b3c2329bf0.png)

The text has been updated to "Breathe life into your user profile with custom avatars. A favorite picture? A whimsical image? It's up to you!".

**Comment by mindreeper2420** [comment]
Completed with the merged PR.
