### ISSUE TITLE
Space-Level Authorization

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#338]
As a User, I want to have full control of my owned Spaces, including defining who has access to them and in what way

**Comment by michaelkleinhenz** [comment]
- The user can view and update the collaborators list using a dialog view.
- The user can add new collaborators from a list of users known to the system (having an account on OSIO).
- The default role for newly added users on the list of collaborators is "developer".
- The user can remove collaborators from the list of collaborators.
- The user can update the role of a user on the list of collaborators.
- The available roles are fixed and given by the system.
- There is a role "developer" with the access rights of ....
- There is a role "admin" with the access rights of ....
- Role changes take effect immediately.

-> The roles system may be a different story as it may be too "big" to put it in here.

**Comment by alexeykazakov** [comment]
To be clear. We plan to implement some backend for this and switch the current collaborator functionality to the new backend. But father integration with OSIO clients/components and UI will go to the next train. We can't build a massive new backend and adopt it across OSIO in the same train.

**Comment by qodfathr** [comment]
Closing in favor of #2075. There are actually two issues hidden in this one: (1) what is the scope of control for a Space-level permission and (2) which Space-levels permissions do we need to define across all the various parts of OpenShift.io. (And that second one is really a whole bunch of issues -- we'll need to start creating lists of permissions for Planner, for Pipelines, for Environments, etc. etc.)
