### ISSUE TITLE
My Spaces page is Displayed Awkwardly

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#3381]
Currently, the My Spaces page is displayed in a manner that centers the header and causes the Space name and owner to be displayed with a large white space to the left, while the underlying description is left justified.

Everything on the page in the list should be left justified, as per all of the lists.

![screen shot 2018-04-30 at 11 54 52 am](https://user-images.githubusercontent.com/4032718/39436980-8dca3c90-4c6d-11e8-96e9-078294bbaf65.png)

**Comment by christianvogt** [comment]
@joshuawilson I'll take care of this.
