### ISSUE TITLE
OSIO Stack report does not display information

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#3382]
Clicking on 'Stack report' link result in ever spinning modal (please see the screenshot). All is good with the response from recommender API. Wanna check any recent UI based PRs..

<img width="1277" alt="screen shot 2018-04-30 at 11 12 37 pm" src="https://user-images.githubusercontent.com/15967765/39441707-67a6d6fe-4ccc-11e8-8a9c-84426559218a.png">

cc @miteshvp

**Comment by ldimaggi** [comment]
I am not seeing this error - do you see any errors in the browser console log?

![screenshot from 2018-04-30 13-55-46](https://user-images.githubusercontent.com/642621/39442190-70efdbdc-4c7e-11e8-8f4b-18027f2aa8cb.png)

**Comment by jiekang** [comment]
Does https://github.com/openshiftio/openshift.io/issues/3380 relate to this at all?

**Comment by maxandersen** [comment]
is this really a SEV1 that needs daily triagning by SE team ? seems more like a SEV2 possibly p0  ?

**Comment by krishnapaparaju** [comment]
rested again, not seeing this problem. Closing this issue, will reopen if required..
