### ISSUE TITLE
Limit app name length to 40 characters to avoid jenkins plugin limits

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#3391]
As seen in https://github.com/openshiftio/openshift.io/issues/2527 there is a yet to be identified plugin in jenkins or pipeline libraries that prevent long names (>40) to be used.

Opening this as limiting in UI is the most feasible short term fix.

/cc @qodfathr

**Comment by qodfathr** [comment]
Let's just make sure we coordinate this change with all copy (both in the service and in docs)

**Comment by stooke** [comment]
Because this is a P0, I created a small PR for the bandaid.
I don't know where the docs are, so if someone can give me a pointer, I'll get those updated too.

**Comment by joshuawilson** [comment]
@rkratky can you tell us when you can update the docs? Then we can look at when we merge this change. This needs to be coordinated, so we are not merging it yet.

**Comment by joshuawilson** [comment]
@Preeticp Can you please check the docs to for any reference to the length of characters for the app name. This change is in prod now.

**Comment by Preeticp** [comment]
Will do @joshuawilson

**Comment by Preeticp** [comment]
@joshuawilson, docs have been updated via PR: https://github.com/fabric8io/fabric8-online-docs/pull/351
