### ISSUE TITLE
Find a way to update plugins in jenkins image

### ISSUE THREAD

**Issue by rupalibehera** [openshiftio/openshift.io#3393]
create a checksum while shipping the plugins and check if the plugins needs to be updated.
In the current situation we cannot update a plugin as we are copying the plugins only if it is empty
https://github.com/fabric8-jenkins/jenkins-openshift-base/pull/18/files

https://github.com/openshiftio/openshift.io/issues/2612#issuecomment-373798131

**Comment by pradeepto** [comment]
cc @aslakknutsen @maxandersen @krishnapaparaju

**Comment by pradeepto** [comment]
Related to https://github.com/openshiftio/openshift.io/issues/3266

**Comment by msrb** [comment]
Note it's very likely that we will need to update Bayesian Jenkins plugin due to housekeeping/issues/845.

**Comment by yzainee** [comment]
This affects the release of https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/845.

**Comment by maxandersen** [comment]
this currently blocks fix for https://github.com/openshiftio/openshift.io/issues/2729 and https://github.com/openshiftio/openshift.io/issues/3266

**Comment by krishnapaparaju** [comment]
https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/845 require end to end solution for transitioning to user tokens..

**Comment by rupalibehera** [comment]
https://github.com/fabric8io/openshift-jenkins-s2i-config/pull/164 and https://github.com/fabric8-jenkins/jenkins-openshift-base/pull/27

**Comment by maxandersen** [comment]
> https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/845 require end to end solution for transitioning to user tokens..

@krishnapaparaju how does this related to this issue ?
