### ISSUE TITLE
Newlines cause undesirable behaviour when setting description in add space dialogue

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#3395]
When a user creates a new space, choosing Scenario Driven Development as their development process, they are initially asked to provide a name and description for the space. When choosing a name, attempts to add a newline by pushing the return key are ignored. When adding a description, however, such attempts are allowed and leave undesirable overlap between the prompts and user input.

An example can be seen here :
![new-space-description](https://user-images.githubusercontent.com/17230733/39488940-e441462e-4d51-11e8-9a5d-d54cc2e667a8.gif)

**Comment by aptmac** [comment]
The element for adding a description was changed from a `div` to an `input` in a recent commit [0], new lines no longer cause this effect.

[0] https://github.com/fabric8-ui/fabric8-ui/commit/0a0bb576324541bb1c642a8d8102b7b754b293ec#diff-2b298216067bc6e473a1141f508b2d3a
