### ISSUE TITLE
Space dashboard shows empty space

### ISSUE THREAD

**Issue by dlabrecq** [openshiftio/openshift.io#3398]
The "my work items" card is hidden when feature flags are set to production. This is because the work items card is tied to Planner, which is only shown with beta features. Although the space dashboard and feature flags are working as expected, it would be best if we don't show empty space so this doesn't appear as a bug. Instead, we would like the other cards (pipelines and applications) to fill up the empty space.

![screen shot 2018-05-01 at 9 08 01 am](https://user-images.githubusercontent.com/17481322/39491359-23340454-4d5a-11e8-8c3c-4cb1a2e7d9b4.png)

**Comment by catrobson** [comment]
Already fixed.
