### ISSUE TITLE
Updating Jenkins image with /_tenant does not work.

### ISSUE THREAD

**Issue by jaseemabid** [openshiftio/openshift.io#3408]
As part of testing a PR, I tried to update my tenant Jenkins and it failed. The pod template got partially updated (metadata.fabric8.io/git-branch, labels.version etc) but the image is still pointing to an old version. 
The final pod template is inconsistent and wrong. 

Ref: https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/86

**Comment by aslakknutsen** [comment]
Actual/expected?
