### ISSUE TITLE
Token storage service

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#341]
We need a service where we can store user's OpenShift and GitHub tokens.
This service will need to provide REST API to:
1. Link GitHub and OpenShift accounts to the main user account
2. Obtain GitHub and OpenShift user tokens

**Comment by michaelkleinhenz** [comment]
This should go into the team's backlog as it is a detail story describing the specific implementation. The story here should be about the users (or PMs) point of view. For this example:

Story: Authentication over Community Sites 
-> As a user, I want to register and log in using my GitHub, (...) account to access OSIO as fast and as convinient as possible.

Story: Access to GitHub data from OSIO
-> As a user, I want to be able to access my data and projects on GitHub from OSIO.
(This would describe the AuthN part of that, there need then be other stories that describe action flows, like "Remote Tracking of Issues in GitHub from Planner" that use this kind of groundwork).

**Comment by alexeykazakov** [comment]
Part of https://github.com/openshiftio/openshift.io/issues/371

**Comment by qodfathr** [comment]
@alexeykazakov given the recent new capabilities, is the issue complete?

**Comment by alexeykazakov** [comment]
Oh yes, this is done.
