### ISSUE TITLE
Launcher not showing progress step but application is getting created 

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#3410]
Launcher not showing progress step but the application is getting created.

<img width="1635" alt="screen shot 2018-05-02 at 2 13 53 pm" src="https://user-images.githubusercontent.com/5129024/39513937-758a1978-4e13-11e8-9fa4-427d9a3054f1.png">

**Comment by animuk** [comment]
@sunilk747 as far as I know, we have tested with load before. Can you check and comment

**Comment by sunilk747** [comment]
@animuk Yes. I tested it with load before. I didn't encounter this while testing. Let me check. Meanwhile @gastaldi any idea why this is happening again.

**Comment by gastaldi** [comment]
I remember reproducing this bug with multiple replicas, but the annotation in the route should have redirected the user to a single pod

Can you confirm if the forge.api.openshift.io endpoint is used when /osio/launch and the Websocket is invoked or is it using the frontend-proxied `/launch` endpoint instead?

**Comment by invincibleJai** [comment]
@gastaldi yes it was working till yesterday, today I observed twice. Am hitting prod i.e `forge.api.openshift.io`

**Comment by gastaldi** [comment]
@invincibleJai I have observed the logs and I can confirm that your WebSocket connected to to a different pod than the launched, meaning that the route annotation may have not worked

**Comment by sunilk747** [comment]
@gastaldi If you are sure the route annotation doesn't worked, do you have any other workaround in mind.

**Comment by gastaldi** [comment]
@sunilk747 @invincibleJai I think we could move the number of pods in launcher-backend back to 1 if we want to avoid this issue for now (configured with a higher memory/processor quota if necessary)

**Comment by sunilk747** [comment]
@gastaldi Where do you see the logs? Can I have access to that?

**Comment by gastaldi** [comment]
@sunilk747 I have accessed the pod logs directly in the OpenShift console (https://console.dsaas.openshift.com/console/project/launchpad-production/browse/pods/launcher-backend-65-f6jns?tab=logs). I have pasted them here if you don't have access to it (look for the projectile ID - `0e9f1b5e-cf16-4b6a-b3da-12dadbd50d05`):

- [launcher-backend-65-f6jns.log](https://gitlab.cee.redhat.com/snippets/381)
- [launcher-backend-65-rxg24.log](https://gitlab.cee.redhat.com/snippets/382)

**Comment by gastaldi** [comment]
Replicas moved back to 1. This issue shouldn't happen anymore. Feel free to close it and reopen if the problem persists

**Comment by invincibleJai** [comment]
Thanks @gastaldi, closing it.

**Comment by animuk** [comment]
@gastaldi I think for summit, It was good to live with one replica. It was more like an contingency plan. But, Once, marketing is planning for GA, we need to increase the replica count for load. As off now, we are thinking of changing existing websocket implementation to Ajax polling .

**Comment by gastaldi** [comment]
@animuk Ajax polling won't resolve the issue. The point is that if you do another request, it's highly likely that another replica will be called. 

The only solution I see is to introduce a mechanism that shares the state of a projectile launch between multiple replicas in the backend (a distributed cache or a distributed temporary queue)

**Comment by animuk** [comment]
@gastaldi As the polling keeps generating new requests, eventually it will call the original replica again in subsequent calls. As we are targeting for 500 concurrent requests, We might go into issue with scalability with only one pod. As per our last analysis, It is recommended to go with 3 replicas.
