### ISSUE TITLE
Too many requests while redirecting to a running Jenkins (Bad Caching)

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#3412]
Spawning it from https://github.com/openshiftio/openshift.io/issues/3390

when jenkins is idled the proxy logs a single line indicating its looking up info every ~10 second or so...but when jenkins is unidled you get like 100+ log messagess which definitely seems overkill and if anything it should be in reverse (jenkns up, redirect = fewer logs, jenkins down = more logs tracking the state)
![2018-05-02_08-55-12](https://user-images.githubusercontent.com/10185999/39515913-137c6f32-4e19-11e8-978b-955f56998634.png)

**Comment by kishansagathiya** [comment]
The reason could be 
```
{"component":"proxy","level":"info","msg":"Could not find cache, redirecting to re-login","ns":"","request-hash":2960151885,"time":"2018-05-02T16:52:39+05:30"}
```

Bad caching.

**Comment by kishansagathiya** [comment]
@krishnapaparaju @maxandersen 

Was investigating on this. This isn't really an issue. Each request is the request that is made by Jenkins. Let's say it requires a css, js or some jpeg, all these things are going through proxy and all those time we see logs. And it requires a lot of such things. Since everything goes through proxy we will see these many logs.
The behaviour is same even if I go to Jenkins directly instead of using proxy.

![screenshot from 2018-05-03 13-38-24](https://user-images.githubusercontent.com/10185999/39565955-8f5c9e38-4ed7-11e8-94df-7c05d0a9204f.png)

Sample Proxy logs here https://gist.github.com/kishansagathiya/448988118eb19730ab00a15c7f6ba495


Why do I not see these logs the first time(right after jenkins is unidled) is still a question

**Comment by maxandersen** [comment]
> Why do I not see these logs the first time(right after jenkins is unidled) is still a question

lets get that answered and we can then close or evolve this issue if an issue found.

**Comment by sthaha** [comment]
> Why do I not see these logs the first time(right after jenkins is unidled) is still a question 

You will start to see the logs only after proxy determines that jenkins is up and running properly and starts to forward the requests to actual jenkins. 

Closing this as the implementation has changed a lot since the bug was filed.
