### ISSUE TITLE
Update Notification Email Templates

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#3419]
The Email Notification templates need to be updated so that they are responsive to the email client that is used, as well as the device that the email is read on.

Additionally, the email notifications need to be readable when all HTML is stripped out, in the case of plain text clients and/or security concerns.

Support Criteria:
- [ ] Readable on the standard set of desktop clients (Gmail on web, Apple Mail, Microsoft Outlook, Thunderbird)
- [ ] Readable on the standard set of mobile clients (Gmail [iOS and Android], iOS Mail, Outlook [iOS and Android], web-based)
- [ ] Web clients (Chrome, Firefox, Safari, Edge)
- [ ] All templates tested
  - [ ] Work item creation
  - [ ] Work item updates
  - [ ] Invitations
  - [ ] Build issues

Verification Criteria:
- [ ] Reviewed by UXD
- [ ] Shared on appropriate mailing lists
- [ ] Reviewed by PM

**Comment by mindreeper2420** [comment]
These are the current email templates:

**Creating a Work Item**
<img width="809" alt="screen shot 2018-05-02 at 10 30 58 am" src="https://user-images.githubusercontent.com/4032718/39529147-00018b7e-4df4-11e8-8c4f-dc8c833b100c.png">
<img width="811" alt="screen shot 2018-05-02 at 10 31 09 am" src="https://user-images.githubusercontent.com/4032718/39529151-02b50f44-4df4-11e8-82ee-639ad4096c34.png">

**Updating a Work Item**
<img width="814" alt="screen shot 2018-05-02 at 10 31 15 am" src="https://user-images.githubusercontent.com/4032718/39529179-123c8ee2-4df4-11e8-86bb-37afec5bfea9.png">

**Request Notification**
<img width="814" alt="screen shot 2018-05-02 at 10 30 44 am" src="https://user-images.githubusercontent.com/4032718/39529209-1f488f28-4df4-11e8-824d-424928a582d8.png">

**Comment by christianvogt** [comment]
Here are a couple of services for testing email templates across a broad range of clients.

- https://litmus.com/
- https://www.emailonacid.com/

**Comment by mindreeper2420** [comment]
Potential starting point for templates: http://tedgoas.github.io/Cerberus/
