### ISSUE TITLE
Triggering any build with a git push runs all pipelines not just the one related to the repo

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#342]

**Comment by maxandersen** [comment]
@ldimaggi @qodfathr mentioned you seen this - can you point to details/steps to reproduce ?

**Comment by ldimaggi** [comment]
See here:
https://github.com/fabric8-ui/fabric8-ui/issues/1642

**Comment by joshuawilson** [comment]
@ldimaggi can you please confirm this is still an issue?

**Comment by joshuawilson** [comment]
@rgarg1 while @ldimaggi can you please try to verify this.

**Comment by burrsutter** [comment]
We are still seeing this with the https://github.com/openshiftio/openshift.io/issues/447

**Comment by rawlingsj** [comment]
This should be fixed with Jenkins 3.0.81 https://github.com/fabric8io/jenkins-sync-plugin/commit/db03e025f3519b6ad8dd75c7ed05d03847f920fd please reopen if not.
