### ISSUE TITLE
ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#3424]
![screenshot from 2018-05-03 11-42-32](https://user-images.githubusercontent.com/10185999/39562160-ce4bc78c-4ec7-11e8-8273-351512f2cbd4.png)

Have been seeing this in my local proxy setup. Not sure if this happens on prod or prod-preview.

Since this happens on redirecting to auth service, @sbose78 do you already know about this?

**Comment by kishansagathiya** [comment]
@alexeykazakov 

> Use https://auth... Not http://

In the image I see http**s**

**Comment by invincibleJai** [comment]
Can it be related to https://github.com/openshiftio/openshift.io/issues/2755 ?

**Comment by kishansagathiya** [comment]
Seems to be duplicate of #2755 Thanks @invincibleJai
