### ISSUE TITLE
Before creating / starting workspace via Codebases UI need to check cluster capacity, show error message and prevent workspace startup

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#3426]
Before creating / starting workspace via Codebases UI need to check cluster capacity, show error message and prevent workspace startup if cluster is full. `api/codebases/che/state` currently provides the following payload:

`{"clusterFull":false,"multiTenant":true,"running":true}`

**Comment by ibuziuk** [comment]
@corinnekrych do you happen to know if someone from UI team would be able to help with this one ?

**Comment by jiekang** [comment]
I think a UX change needs some review from the UX team. @catrobson 

If this is truly P0 that needs to be addressed, I recommend in the short term that:

1. In every location in UI that it's possible to create workspace (I hope it's one spot, the codebases page?), a request is made to above API and if `clusterFull` is `true`, the normal request to create does not occur and a warning notification is triggered via the `NotificationsService` service. Many parts of the codebase use it so it should be easy to recreate.

**Comment by ibuziuk** [comment]
@jiekang yeah, I believe it is P0 since it is a subtask of https://github.com/openshiftio/openshift.io/issues/3320 

thanks for the pointers with `NotificationsService`

**Comment by jiekang** [comment]
As far as the warning message something like:

Workspace capacity is reached, new workspace cannot be started.

However, it would be best if it also included a note on how users can proceed to a state where they can start the workspace that they originally wanted to start. Is there something actionable for the user in this state?

**Comment by ibuziuk** [comment]
@jiekang in terms of message smth. like this should be good:

> Cannot start a workspace. OpenShift Online cluster is currently out of capacity [1]

> However, it would be best if it also included a note on how users can proceed to a state where they can start the workspace that they originally wanted to start. Is there something actionable for the user in this state?

I believe there is nothing "actionable" could be done from the user perspective. So, just showing message and preventing workspace startup should be just enough

[1] https://github.com/redhat-developer/rh-che/pull/661/files#diff-f2821ac62d8158e3bafa443f0876cddeR146

**Comment by jiekang** [comment]
Yes that message makes more sense. Thanks!

**Comment by catrobson** [comment]
@mceledonia can you take a look at this since it relates to the other quota messages we're looking to have in OpenShift.io?

**Comment by ibuziuk** [comment]
@jiekang thank you for looking at this, but @corinnekrych already provided a PR with a fix - https://github.com/fabric8-ui/fabric8-ui/pull/2870
