### ISSUE TITLE
vert.x dnsresolver does not work in che

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#3428]
if you run vert.x without use of fmp on openshift - need to set Dvertx.disableDnsResolver=true to make it work on che or in any other IDE using pods.

possible fixes:
change https://github.com/redhat-developer/rh-che/blob/master/assembly/fabric8-stacks/src/main/resources/stacks.json#L476 to have this flag set

OR

change booster pom's to have it set for vertx:run

OR

change the booster to have a main to set the flag early

**Comment by ibuziuk** [comment]
seems relevant to add this flag to command if it does not have side effects.
Or is it planned to have a fix from quickstart side ? there is already one update pending for quickstart - https://github.com/openshiftio/openshift.io/issues/2988#issuecomment-386076481

**Comment by maxandersen** [comment]
@cescoffier what do you guys prefer ? seems fixing it in the pom.xml would be the best/most complete option ?

but if not then lets fix it in the stacks. And yes @ibuziuk it does not have any sideeffects as far as we know except actually making it work reliably ;)

**Comment by ibuziuk** [comment]
@cescoffier we are going to make rollout (hopefully last before summit) on prod, so please let me know if we should update the command

**Comment by ibuziuk** [comment]
@cescoffier ok, lemme provide PR with command update.
Could you please tell if any more quickstart updates are planned before summit ? each update could potentiallyintroduce subtle bugs and might require rebuilding our stacks. So, please give me a heads-up about this

**Comment by ibuziuk** [comment]
PR is sent https://github.com/redhat-developer/rh-che/pull/662

**Comment by ibuziuk** [comment]
PR for rh-che is merged - should be soon on prod-preview
Also send a PR to upstream - https://github.com/eclipse/che/pull/9611

**Comment by ibuziuk** [comment]
@maxandersen @cescoffier @slemeur  fix is available on prod:

![image](https://user-images.githubusercontent.com/1461122/39637787-5452f790-4fc4-11e8-9cb8-7b94a1d5d3fd.png)


are you ok to close ?

**Comment by cescoffier** [comment]
Ok for me
