### ISSUE TITLE
Disable  Jenkins idling for a OSIO user

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#3429]
Script out / pass in thru environment variable / API level disabling of Jenkins idling for a OSIO user.

**Comment by jaseemabid** [comment]
This is feature work, and should be a SEV3 instead of a P0 one working day before the demo.

**Comment by maxandersen** [comment]
why is this now put as top priority over actual p0s ?

**Comment by maxandersen** [comment]
user or someone else can refresh/curl  jenkins.openshift.io to keep it a live. rejecting until actual usecase provided for having this change in idler.
