### ISSUE TITLE
Space overview UI is slightly broken

### ISSUE THREAD

**Issue by jaseemabid** [openshiftio/openshift.io#3431]
See the screenshot. 
![2018-05-03-165428_620x596_scrot](https://user-images.githubusercontent.com/601714/39573911-c193a804-4ef2-11e8-8c49-e8c88e9a83bc.png)

PS: I've no idea what 'bobross_925' is, but googling for that gives just one result, @ldimaggi's github account. 

The 59 collaborators might be a problem as well.

**Comment by jaseemabid** [comment]
cc: @joshuawilson Is there a `team/` tag for UI?

**Comment by piyush1594** [comment]
![ui](https://user-images.githubusercontent.com/19270240/39574080-774fb980-4ef3-11e8-86f7-b898a6fdfd4a.png)
I am also seeing the same

**Comment by jiekang** [comment]
These components are currently on 'Internal' level. It's a work in progress and is known. People on Production, Beta and even Experimental should not see these.

**Comment by aptmac** [comment]
Similar bugs have been reported a few times already, but because it's currently behind the internal feature-flag these issues will be closed until the feature is completed.
