### ISSUE TITLE
Have same value for application name and repo name In new Launcher flow

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#3432]
Have same value for the application name and repo name as part of contingency plan with changes at Launcher. 

### Create Flow
- [x] Pass value of App name provided by User as repo Name.
- [x] Change in repo Name should be reflected on Application Name.
- [x] Change in App Name in Step Indicator should be reflected in repo Name.
- [x] Change in App Name in Summary View should be reflected on repo Name.
- [x] Validation of repo name for all above scenario
- [x] If repo name is invalid it should show error message in GitHub screen and GitHub card should be incomplete in the Summary screen

### Import Flow
- [x] Change in repo Name should be reflected on Application Name.
- [x] Change in App Name in Step Indicator should be reflected on repo Name.
- [x] Change in App Name in Summary View should be reflected on repo Name.
- [x] Validation of repo name for all above scenario
- [x] If repo name is invalid it should show error message in GitHub screen and GitHub card should be incomplete in the Summary screen

**Note** : These Changes are temporary once the fix for this https://github.com/openshiftio/openshift.io/issues/3095 is in place, needs to be taken off.

**Comment by sunilk747** [comment]
@invincibleJai  I tested it and it's working fine for me. We are good to go here. Please go ahead and merge it.

**Comment by slemeur** [comment]
can we close this issue ?

**Comment by sunilk747** [comment]
@slemeur Yes. We can close this now.
