### ISSUE TITLE
[~1] Label filter disabled in select filter dropdown

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3433]
Steps-
- Create a new space
- Create 2-3 workitem
- Select Filter By Option
- Click on Label 
- Label is disabled(We don not have label)
- Now Click on workItem 
- Create a new label
- Assign it to workitem
- In Filter-By label is still disabled
![screenshot from 2018-05-03 21-31-26](https://user-images.githubusercontent.com/34271052/39588418-5f34a286-4f19-11e8-9baf-2255d2d47c34.png)

**Comment by jarifibrahim** [comment]
@Raunak1203 I cannot reproduce it. Can you please try again?
The `label` option is `filter-by` dropdown is always enabled for me (even when there are no labels)

**Comment by Raunak1203** [comment]
@jarifibrahim click on label in dropdown(when there are no labels)

**Comment by jarifibrahim** [comment]
> @jarifibrahim click on label in dropdown(when there are no labels)

Thanks! I was able to reproduce it now.
