### ISSUE TITLE
Tests fail at Che for WF-Swarm -- HTTP (Community)

### ISSUE THREAD

**Issue by animuk** [openshiftio/openshift.io#3434]
In the Che editor, booster builds are failing. Tests has been failing.
But, We can build the booster at Che by invoking command : mvn install -DskipTests
![today1](https://user-images.githubusercontent.com/11207106/39589050-be76afae-4f1a-11e8-80c9-bc5b557b4a2e.png)

**Comment by animuk** [comment]
Here is the complete stacktrace:
https://gist.github.com/animuk/fa4b27dd71172ba0400c73b80221d99d

**Comment by ibuziuk** [comment]
@animuk several questions:
- does community version is used on osio ?
- isn't it a duplicate of https://github.com/openshiftio/openshift.io/issues/2152 ?

**Comment by animuk** [comment]
@ibuziuk yes, community version of wildflyswarm is used. and It looks to be duplicate.

**Comment by ibuziuk** [comment]
@animuk thanks for the info. Closing as a duplicate of https://github.com/openshiftio/openshift.io/issues/2152
