### ISSUE TITLE
Fix type column width(Scrum template)

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3435]
![screenshot from 2018-05-03 21-39-08](https://user-images.githubusercontent.com/34271052/39589058-c943ff04-4f1a-11e8-8b04-382a87cbcb0a.png)

**Comment by kwk** [comment]
@sanbornsen Is the width of the columns statically defined?

**Comment by michaelkleinhenz** [comment]
The width percentage of a column is fixed. We should just use a proper name for the user story. Would fix this and the confusion around "where are user stories in this 'scrum' tempate??".

**Comment by sahil143** [comment]
Closing this because this was fixed in https://github.com/fabric8-ui/fabric8-planner/pull/2614 and we no longer have a `Planner Backlog Item` type.
