### ISSUE TITLE
Tests fail at Che for WF-Swarm -- healthcheck (Community)

### ISSUE THREAD

**Issue by animuk** [openshiftio/openshift.io#3436]
In the Che editor, booster builds are failing. Tests has been failing.
But, We can build the booster at Che by invoking command : mvn install -DskipTests
![today2](https://user-images.githubusercontent.com/11207106/39589441-d27337d8-4f1b-11e8-8c7b-e66ad7f8e1b7.png)

**Comment by animuk** [comment]
Here is complete stacktrace from che - 
https://gist.github.com/animuk/801ea1c7d52a51788f43c258c7857b0a

**Comment by ibuziuk** [comment]
@animuk several questions:

- does community version is used on osio ?
- isn't it a duplicate of #2152 ?

**Comment by animuk** [comment]
@ibuziuk yes, community version of wildflyswarm is used. and It looks to be duplicate.

**Comment by ibuziuk** [comment]
@animuk thanks for the info. Closing as a duplicate of https://github.com/openshiftio/openshift.io/issues/2152
