### ISSUE TITLE
fabric8-ui: Header component has unknown method in html

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#3438]
`header.component.html` has snipped contents:

```
        <!-- user profile dropdown -->
        <ul id="header_rightDropdown" class="nav navbar-nav navbar-right">
          <li id="header_documentation" dropdown class="dropdown icon-dropdown icon-dropdown-documentation" placement="top" tooltip="Documentation" (onShown)="onDocumentationListVisible(true)" (onClose)="onDocumentationListVisible(false)">
            <a (onHidden)="onDocumentationList(false)" class="dropdown-toggle" dropdownToggle>
              <span class="pficon pficon-help pficon-white"></span>
            </a>
```

`onDocumentationListVisible` exists but there is a reference to `onDocumentationList` which does not exist. Maybe it's a typo?

**Comment by jiekang** [comment]
@mindreeper2420 Any ideas?

**Comment by christianvogt** [comment]
@mindreeper2420 i'm inclined to simply remove the code associated with `documentationListVisible` as it currently does nothing unless you can remember anything.

**Comment by mindreeper2420** [comment]
@christianvogt @jiekang I can't recall anything about that - see what happens when it is removed I guess?
