### ISSUE TITLE
Filter dropdown for WorkItemType also supports Impediements and Scrum Common Type

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3447]
![screenshot from 2018-05-04 11-18-07](https://user-images.githubusercontent.com/34271052/39614398-2319d374-4f8d-11e8-97a7-b0dff92f2fc0.png)

**Comment by rgarg1** [comment]
This should be p0.

**Comment by kwk** [comment]
Yes, they should be filtered out. @sanbornsen I think I've seen a PR from you somewhere around that filters on `can-construct`. This filter should be applied here as well. @michaelkleinhenz @nimishamukherjee shall we mark the impediment also with `can-construct=false`? The ScrumCommonType already is marked this way.

**Comment by michaelkleinhenz** [comment]
Yes, we can't create impediments for now and the discussion at https://docs.google.com/presentation/d/18xKQmkf3UKlGoP7qLqUnrIYiflza674n_paUZXKuepA/edit?ts=5ad650b4&pli=1#slide=id.g3758dca8f8_0_53 has not come to a conclusion yet.

**Comment by kwk** [comment]
@michaelkleinhenz I thought we've agreed to having the impediment type in the system but don't "invite" the user to create by having a dialog or quick add somewhere? My proposal with the `can-construct` flag would disallow creation of impediments for starters. If @sanbornsen then filters on this flag, we should be good.

**Comment by michaelkleinhenz** [comment]
Yes, that is what I mean :-)

**Comment by kwk** [comment]
Screenshot from prod-preview:

![bildschirmfoto von 2018-05-04 14-52-22](https://user-images.githubusercontent.com/193408/39629006-0e3ca81e-4fab-11e8-8c6b-dcd517f4ca31.png)

**Comment by kwk** [comment]
Fix verified in prod:

![bildschirmfoto von 2018-05-04 20-04-21](https://user-images.githubusercontent.com/193408/39643900-7dba5d8c-4fd6-11e8-9345-2d035e69ff32.png)

**Comment by kwk** [comment]
@Raunak1203 @sanbornsen it's a bit odd though that we need a scrolling drop down for the WITs in the SDD template:

![bildschirmfoto von 2018-05-04 20-07-02](https://user-images.githubusercontent.com/193408/39644576-ce200376-4fd6-11e8-8f33-6233849f2572.png)
