### ISSUE TITLE
Planner: Use consistent case for state options between templates

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#3448]
The work item states are in lower case for the SDD template
![sdd_states](https://user-images.githubusercontent.com/1892722/39614579-97f3e756-4f8e-11e8-9eb9-c6ea601015c3.png)

The work item states start with a capital letter in the scrum template
![scrumstates](https://user-images.githubusercontent.com/1892722/39614604-bb70ffc0-4f8e-11e8-8954-e0d99d00d195.png)

We need to use a consistent format - @Preeticp what do you recommend?

**Comment by Preeticp** [comment]
@nimishamukherjee this was raised earlier, @kwk says these need to be fixed at backend, do I have that right @kwk.
I recommend title case, that is New, Open, In-Progress and so on, to keep it consistent with rest of OSIO UX.
Please note, if we change this, we need to ensure that they are changed in the 'Filter by state' options too.

**Comment by Preeticp** [comment]
Also please note this needs to be reflected in the list view too, currently though in the detailed view the state drop-down says "New", the list view says 'new'

**Comment by kwk** [comment]
@Preeticp well, the old states for SDD are all lowecase in the backend and the new states are sort of camel cased. Changing those state now in the backend would require a big migration and we don't know if we break any client that filters on states or creates work items (e.g. analytics) and specify a state.

Long story short: changing the backend is not an option.

@Preeticp but you're right that I did ask you somewhere to please use the states as they are and not modify them.

If we want consistency in the states @nimishamukherjee the UI needs to either start each new word in a state with an upper-case letter or make everything lowercase. @Preeticp I know that this is somewhat contradictory to what I said before but I don't know any other solution and my main concern was that the UI **sends** states to the backend in a form that doesn't match the backend's definition.

Again, long story short: The UI can **render** (but not send) anything as wished.

@nimishamukherjee we should be good by reverting this PR, shouldn't we? https://github.com/fabric8-ui/fabric8-planner/pull/2611

**Comment by kwk** [comment]
I've unassigned myself because I don't think I'm the right person to make any changes here.

**Comment by nimishamukherjee** [comment]
Fix on prod

![filterstates](https://user-images.githubusercontent.com/1892722/48822066-a800f800-ed81-11e8-9880-557012b4d480.png)

![witstates](https://user-images.githubusercontent.com/1892722/48822074-aafbe880-ed81-11e8-9a38-5a92fee9a18e.png)
