### ISSUE TITLE
drop the number of pv's in -jenkins quota to 2 from the 3

### ISSUE THREAD

**Issue by kbsingh** [openshiftio/openshift.io#3452]
```
spec:
  hard:
    persistentvolumeclaims: "3"
```
now that we've lost the mvn-local-cache from each -jenkins namespace, we should reduce the quota for that namespace down to 2 from the present 3 across the cluster, and for new tenants.

**Comment by xcoulon** [comment]
@kbsingh @aslakknutsen I opened https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/92 to change the "base" template that is used to generate the deployment template which is itself applied when a tenant is created or updated. However, I'm not sure how to update the existing tenants. Do we have a batch procedure for that ?
