### ISSUE TITLE
Build also triggered when promoting in Jenkins and OSO with full promote pipeline

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#3455]
A second build is triggered when using 'promote'.

Steps taken:

1. Reset env (optional?)
2. Import vertx booster codebase with full promote pipeline.
3. Once builds complete, press promote via Pipelines page.
4. See promotion occur **and** another build triggered, images below:

Another build was triggered in Jenkins. In OSO, the first build completed was Build #2, and then Build #1 ran after. Is this expected behavior after pressing 'Promote'? I have never seen this before...

![jenkins-builds](https://user-images.githubusercontent.com/5430520/39631602-a3feaad0-4f80-11e8-882b-97e2434afa24.png)
![oso-pipelines](https://user-images.githubusercontent.com/5430520/39631604-a52f7a4c-4f80-11e8-93a7-c933012358ee.png)

**Comment by miteshvp** [comment]
Looks like duplicate of #3095

**Comment by jiekang** [comment]
This is the same pipeline.  #3095 is about two different pipelines being created for the same application.

**Comment by jiekang** [comment]
Has anyone been able to look at this? It still occurs and makes some of the UI confused.

![double-build](https://user-images.githubusercontent.com/5430520/40920605-126390ae-67db-11e8-9c34-358dad28d5ce.png)
![double-promote](https://user-images.githubusercontent.com/5430520/40920607-141137d0-67db-11e8-95bb-5f89fda59a55.png)

**Comment by jiekang** [comment]
Closed in favor of https://github.com/openshiftio/openshift.io/issues/3742

The issue is not limited to just 'Promote'. It looks like two builds are being queued, the 'second' build will run after the first completes (success or failure).
