### ISSUE TITLE
Widget Loading behavior for Account Home (5)

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#3458]
### Description
If a widget is loading in a dashboard, the loading experience should be replaced with the widget loading experience that is documented in the new standards. That widget loading experience includes disabling the title of the widget, including a spinner, and a context specific loading message that gives the user a better sense of what is loading.

Link to updated standards: https://redhat.invisionapp.com/share/JKGR07DRUC3
Link to design Github issue: #2870

### Parent Issue(s)
https://github.com/openshiftio/openshift.io/issues/3009

### Verification Criteria
- [ ] UI implementation created and reviewed with @lwrigh for Account Home Dashboard
- [ ] Unit tests created for loader
- [ ] PR submitted with new loading bar that follows designs

**Comment by dlabrecq** [comment]
Created PR: https://github.com/fabric8-ui/fabric8-ui/pull/2936
