### ISSUE TITLE
Account Dashboards

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#346]
When a user logs into OpenShift.io, they are show their primary account dashboard. The primary account dashboard is one of potentially many account dashboards; these dashboards display information about the user's account, resource usage, Spaces, etc.. The information is displayed via a number of widgets.

When a new user account is created, a single, default dashboard is automatically created with a predefined set of widgets. The user can customize the layout of the dashboard, adding, removing and rearranging widgets. The user may also create additional account dashboards, using each to provide different views across the user's Spaces (both owned Spaces and other user's Spaces in which the user is collaborating).

## Implementing Features
_Put linked Team/Product story links here_

## Parent Scenario
 #2026 Finding meaningful and actionable information within a large development project

## See also
#2033 Extending the capabilities of OpenShift.io

**Comment by qodfathr** [comment]
This should be rewritten to match the current set of UXD designs, with links to those designs.

**Comment by joshuawilson** [comment]
@qodfathr Can you please update it to what you want and move this to the train backlog? This is a goal for H train.

**Comment by qodfathr** [comment]
@joshuawilson not much for me to do here -- UXD owns this and is creating the designs. I'm just signing off on them. :)  I think we just need to update the description with links to the designs.

**Comment by joshuawilson** [comment]
cc @catrobson

**Comment by catrobson** [comment]
New account homepage designs:  https://redhat.invisionapp.com/share/E9FH915D3U7

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/1993
