### ISSUE TITLE
[~?] Homepage "My Work Items" widget shows wrong links to work items

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#3462]
![screenshot_2018-05-04_11-46-08](https://user-images.githubusercontent.com/3787464/39637377-cdfc291a-4f90-11e8-8ae7-9d6042af429f.png)

The work item displayed has the linked URL `https://openshift.io/aazores@redhat.com/openshiftio/plan/detail/2240`, which is incorrect. This work item belongs to the `openshiftio/openshiftio` user/space - my user account owns no such space named `openshiftio` as suggested by the URL. In other words the linked URL should really be `https://openshift.io/openshiftio/openshiftio/plan/detail/2240`, if this item should be shown at all.

The top-right dropdown box also defaults to an empty entry. If I manually select the "Select a space to work with..." entry, then the widget updates to the expected empty state. After this point the only entries that can be selected are the "Select a space to work with..." (which probably should not be re-selectable?) and the names of my own actual spaces.

**Comment by michaelkleinhenz** [comment]
Looks like an issue with the manual assembly of URLs in the widget.

**Comment by michaelkleinhenz** [comment]
The widget also has UX issues. What should the dropdown on the top right do?

**Comment by michaelkleinhenz** [comment]
Possible story that is connected to this issue: https://openshift.io/openshiftio/openshiftio/plan/detail/1914

**Comment by catrobson** [comment]
@fabric8-ui/uxd FYI

**Comment by joshuawilson** [comment]
@dlabrecq can you take a look at this when you have time

**Comment by dlabrecq** [comment]
The router links are generated using WorkItemService from Planner, like so:

[routerLink]="[contextPath | async, 'plan', 'detail', workItem.attributes['system.number']]"

During my test, this routed me to the Planner page and showed the expected work item. If this is not a valid router URL, please advise?

**Comment by andrewazores** [comment]
The CreateWorkItemWidget does it that way, but the links look like this:

`[routerLink]="['/', loggedInUser.attributes.username, currentSpace.attributes.name, 'plan', 'detail', workItem.id]"`

in the WorkItemsComponent and WorkItemWidgetComponent. Without digging into it further this looks like it would match the bug description I gave - my username should not be part of the created workitem URL.

**Comment by dlabrecq** [comment]
The CreateWorkItemWidgetComponent is shown on the home dashboard, which only shows "My Work Items".

The WorkItemWidgetComponent is shown on the space dashboard, which shows a summary for all work items; total open, resolved, etc. It doesn't provide links to individual work items. The only link takes you directly to Planner -- it doesn't take you to a specific work item.

**Comment by andrewazores** [comment]
I don't really know much about these widgets - there appear to be three separate ones in the codebase, so I don't know which is meant to be displayed where or why. I have marked them A/B/C/D in their titles in my local build here so I can try to understand this.

This is what my homepage looks like:

![screenshot_2018-05-18_13-49-58](https://user-images.githubusercontent.com/3787464/40249909-8b310bb0-5aa2-11e8-925b-24639e087daa.png)

This contains some Work Items widget which has a link to a specific work item, and the link is incorrect because it is a workitem in the openshiftio/openshiftio planner, but the URL is constructed as if openshiftio is a space under my user account (as seen in the bottom left hover indicator).

Here is what I see in the Analyze dashboard for my own test-space:

![screenshot_2018-05-18_13-50-40](https://user-images.githubusercontent.com/3787464/40249992-d2b73d88-5aa2-11e8-94d1-8c39e3878eb8.png)

This widget does also contain a link to the specific work item, as seen again in the bottom left. This one's URL is correctly constructed.

**Comment by dlabrecq** [comment]
Seems there are two WorkItemWidgetComponent components. Found one under dash-board-widgets and another under home.

**Comment by andrewazores** [comment]
I have the same widgets on production openshift.io as well, with the same behaviour.

**Comment by andrewazores** [comment]
$ ag -l "my work items"
src/app/profile/overview/work-items/work-items.component.html
src/app/home/work-item-widget/work-item-widget.component.html
src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.html

There are three different components providing what appears to be various forms or versions of the work items widget. The work-item-widget-component actually contains two, at two different feature flag levels. So there are four total.

**Comment by dlabrecq** [comment]
Just to clarify. The WorkItemWidgetComponent (doesn't work), displayed on the home dashboard, uses this router link:

[routerLink]="['/', loggedInUser.attributes.username, currentSpace.attributes.name, 'plan', 'detail', workItem.id]" class="f8-list-group-item-link">

While CreateWorkItemWidgetComponent (reported to work), displayed on the old space dashboard, uses this router link:

[routerLink]="[contextPath | async, 'plan', 'detail', workItem.attributes['system.number']]"

I believe these two are constructing similar links, so I don't believe that is the problem. The main difference being that WorkItemWidgetComponent forces the user to choose from a dropdown of recent spaces. Thus, the currentSpace.attributes.name must be used Vs contextPath.

**Comment by dlabrecq** [comment]
Looking at the screenshot, I don't see a space name selection -- the menu is blank. However, it appears that the component is showing work items for a recently visited space. The work items should be filtered by the logged-in user. Regardless, the component shouldn't show any work items that don't belong to the user.

Note that we still don't have an API to retrieve the spaces a user owns, so we have to rely on recent spaces.

**Comment by dlabrecq** [comment]
Are there any errors in the console that might help reproduce your scenario?

**Comment by andrewazores** [comment]
No, I don't see any errors in the console or the Network tab. There are a few CORS warnings like this:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.openshift.io/api/spaces/ffe748e6-3625-45de-94ed-995175f27b5d/codebases. (Reason: CORS request did not succeed).
```

but I'm not sure if these are actually related.

**Comment by dlabrecq** [comment]
Is your menu truly empty without any options? Both screen shots look like that.

Wondering what happens if you're able to make a selection. Maybe you can also try visiting another space to see if the menu is populated?

Sorry for all the questions, but having a hard time reproducing the problem.

**Comment by andrewazores** [comment]
Yes, the menu dropdown really does come up empty. If I do click on it there are items for my spaces, as well as the "Select a space" text item. It seems that this occurs when the most recently visited space was not one that I own. If I visit the openshiftio/openshiftio space for example and then go back to my account home, the widget will be in the state pictured. If I visit one of my own spaces or manually select one of them with the dropdown then the widget updates and correctly displays my own work items from the selected space.

**Comment by dlabrecq** [comment]
I'm able to reproduce after assigning myself to a work item in the openshiftio/openshiftio space.

**Comment by dlabrecq** [comment]
In order to navigate to a work item correctly, we need to construct a link using the space owner -- not the logged in user. Otherwise, this widget can only show "My Work Items" for "My spaces".

The widget only understands what space the work item belongs to, but not who owns the space. (This is also why the menu shows a blank selection.) Unfortunately, WorkItem objects contain no information about the owner/space it belongs to -- there's no API to provide that information.

That said, I can limit the component to show only the user's spaces. That will ensure links work correctly, but we won't be able to show the user's work items across all spaces.

**Comment by dlabrecq** [comment]
See PR: https://github.com/fabric8-ui/fabric8-ui/pull/2925

**Comment by michaelkleinhenz** [comment]
@dlabrecq This is an interesting issue. It tackles the architecture in fact. So here's the key: you should not use an assembled router link for referring to the detail page of a work item. This is not (yet) supported or recommended. The router link resembles the URL and both might and can change. There is a story for providing a deep link URL for a WI on the JSONAPI structure: https://openshift.io/openshiftio/openshiftio/plan/detail/1914 but this will not make it into Iris.

But as we need to use the router here (and I would think there is no sane way of using the above URL here anyway), we should think about how we do this kind of deep-level integration. I don't think assembling the router path on the "client" side it the right way to do this. I would rather provide a service from the Planner side that returns the router link when given a WI id and Space id - for example.

**Comment by michaelkleinhenz** [comment]
We should do a new story for this.
