### ISSUE TITLE
Pipelines widgets are sometimes empty

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#3465]
When visiting the pages that have pipelines widgets, the list is sometimes empty even though it displays the correct count.

When inspecting the html, the ngFor over the list has:

```
<!--bindings={
  "ng-reflect-ng-for-of": null
}-->
```

in the normal case it's:
```
<!--bindings={
  "ng-reflect-ng-for-of": "[object Object]"
}-->
```

I don't yet understand why it's null.

![empty-pipelines](https://user-images.githubusercontent.com/5430520/39647410-e175078e-4fac-11e8-9c38-31262354f9f5.png)

**Comment by ldimaggi** [comment]
Duplicate of https://github.com/openshiftio/openshift.io/issues/3461

**Comment by jiekang** [comment]
Closing as duplicate. Thanks!
