### ISSUE TITLE
Scale Idler with more replicas

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#3468]
Currently only one replica is being used to serve OSIO user traffic, this is single point of entry for the entire traffic. Scaling, testing Idler (with state maintained at PG) is critical to scale Build platform for higher number of concurrent OSIO users.

**Comment by jaseemabid** [comment]
We have done nothing that even remotely resembles performance benchmarking and we don't have any numbers available to talk about this issue meaningfully. If we have no idea how many req/s one instance can handle, how can you say what N instances would do?

There is effort required in making any service scale horizontally, let's do that only if required. Any conversation regarding scale and performance should be based on numbers and numbers alone.

**Comment by sthaha** [comment]
@krishnapaparaju may I request that we remove the P0? Assigning it to you so that no else need to take a look at this issue.

**Comment by chmouel** [comment]
This issue will take a lot of time to implement (even if we have numbers or not)

**Comment by sthaha** [comment]
closing this as this can be tracked in planner if there is a real need for scaling idler.
