### ISSUE TITLE
Planner: Unable to update work item on the detail page

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#3470]
From Mattermost:

> e.g., I created a new work item and assigned to myself. As soon as I did the assignment, I got that error.
>  Also, I edited the description and as soon as I hit the checkmark to save my edit, I got that error.
>  Understanadbly, we don't want to see that during the demo.
> Related, perhaps: zone.js:2933 PATCH https://api.openshift.io/api/workitems/2dee657a-3343-4a2a-ae70-2596380d6d98 409 (Conflict)
> FYI, seems to be an issue mainly when editing full details. Quick view seems to be able to update better.

The UI is not updating the version number in the patch call

**Comment by jarifibrahim** [comment]
Fixed via https://github.com/fabric8-ui/fabric8-planner/pull/2618
