### ISSUE TITLE
Planner: Newly added collaborators do not show up in the assignee drop down

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#3471]
Issue reported on Mattermost by Todd:

> @here another issue: I've added collaborators to my space, but when I go to assign someone to a work item, the only choice I get is to assign myself.

If you add collaborators and navigate to planner, the collaborators get added 
If you are on planner, navigate away to add collaborators, and come back to planner, the list does not get updated with the newly added collaborators.

**Comment by jarifibrahim** [comment]
This has been fixed via https://github.com/fabric8-ui/fabric8-planner/pull/2619
