### ISSUE TITLE
My Work Items showing closed WIs

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#3473]
Very quickly, this list will be full of nothing but closed WIs. The purpose of this list is to quickly show me my To Dos. Closed WIs should not be in this list.
![image](https://user-images.githubusercontent.com/16322190/39669116-da572fae-50b0-11e8-8cb4-686f984c2bfc.png)

**Comment by sanbornsen** [comment]
Hi @qodfathr, can provide me the URL for this list?

**Comment by qodfathr** [comment]
You need to be at Beta level, and then it's on ether your account home page (https://openshift.io/_home) or a Space home page (e.g. https://openshift.io/tmancini/SentimentShift for me).
