### ISSUE TITLE
Toolbar breaks when switching back to Planner from areas/collaborators

### ISSUE THREAD

**Issue by SMahil** [openshiftio/openshift.io#3475]
Steps to reproduce:

- Navigate to planner
![nav1](https://user-images.githubusercontent.com/1892722/39671525-8d53c370-5137-11e8-85f6-8e2ec00f5752.png)

- Navigate to areas/collaborators (pipe icon)
- Do some action
- Navigate back to the planner
- Extra gray bar at the top in toolbar
![nav2_extragrey](https://user-images.githubusercontent.com/1892722/39671528-931c0e02-5137-11e8-9bcf-428648d7dc4a.png)

**Comment by nimishamukherjee** [comment]
@qodfathr P0?

**Comment by joshuawilson** [comment]
I don't think this is a P0. I think it might be a SEV3.

This is likely due to the difference in how CSS is handled/done in Planner vs the rest of the UI. @SMahil you may want to talk to @mindreeper2420 and @christianvogt on this.

**Comment by SMahil** [comment]
PR: https://github.com/fabric8-ui/fabric8-ui/pull/2885

**Comment by joshuawilson** [comment]
@SMahil if that fixes this issue, please close this.
