### ISSUE TITLE
Does Planner tree view have too much white space?

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#3477]
I cannot fit all of the columns of Planner on my laptop screen, which makes it more difficult to use. Notice that there is a lot of horizontal white space in the Planner:
![image](https://user-images.githubusercontent.com/16322190/39672687-2f580e78-50fd-11e8-9b55-0f785c6375a6.png)
For example, the indenting under **Title** perhaps could be reduced by a lot, yet still be clean and unambiguous about the hierarchy.
The vertical whitespace is not as concerning, because it helps with drag-and-drop, but even this could perhaps be slightly reduced.

**Comment by qodfathr** [comment]
cc: @catrobson

**Comment by rgarg1** [comment]
Cc @sanbornsen

**Comment by sunilmalagi** [comment]
@qodfathr @rgarg1 @nimishamukherjee @sanbornsen I agree with you Todd, the indentation space should be only 20px as shown in the visuals:

https://redhat.invisionapp.com/share/NVEWGDU4W#/268923363_Requirements_01

I discussed with eng team (Sahil) and he will be able to fix with the help of Sudipto
<img width="440" alt="screen shot 2018-05-07 at 11 58 04 am" src="https://user-images.githubusercontent.com/25147584/39687951-301335da-51ee-11e8-81fd-9167285a0963.png">

**Comment by muruGanesan** [comment]
@sahil143, @sunilmalagi, please update this issue with an appropriate status.

**Comment by sahil143** [comment]
Closing this issue because this was fixed with PR https://github.com/fabric8-ui/fabric8-planner/pull/2768. Now, the indentation in the tree view is 20px.
