### ISSUE TITLE
WIT detail page is blank

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#3478]
![image](https://user-images.githubusercontent.com/16322190/39673434-2273d7fc-510a-11e8-98cd-7d63c35b8d83.png)

**Comment by vikram-raj** [comment]
@qodfathr Which browser you are using?

**Comment by vikram-raj** [comment]
I checked in Chrome and Firefox. And it's visible for me.

**Comment by qodfathr** [comment]
Seems to only happen when I start from the My Work Items widget.

**Comment by qodfathr** [comment]
If I go to Planner and open details from there, it works. Also, it **then** works from the My Work Items widget.

If I log in -- which shows me My Work Items widget -- and click on a WI from there, I get blank details.

**Comment by vikram-raj** [comment]
Found it. Working on it.

**Comment by nimishamukherjee** [comment]
Fix on prod
