### ISSUE TITLE
Space - dashboard / overview

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#348]
# Description
As a user, I want to be able to use a space to work in.

# Acceptance Criteria
- [x] The space dashboards should only show information for that space. https://github.com/fabric8-ui/fabric8-ui/issues/1746

**Comment by ldimaggi** [comment]
The UI features that deletes a space, and its projects, should provide the user with the option of also deleting the projects:

    github repo
    Che workspace
    OpenShift resources

Unless we provide this option to the user, he/she will have to delete these assets manually.
