### ISSUE TITLE
Pipeline stages not animated like OSO (3)

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#3480]
Is there a reason why individual pipeline stages in OSIO do not have the same "active" animation as OSO?
![image](https://user-images.githubusercontent.com/16322190/39675438-2147138e-5129-11e8-96a3-a03ea9d99e89.png)
vs
![image](https://user-images.githubusercontent.com/16322190/39675457-44a82dcc-5129-11e8-8562-d66e612074d9.png)

They used to be animated in OSIO.

**Comment by joshuawilson** [comment]
cc @openshiftio/uxd-team

**Comment by mindreeper2420** [comment]
@ldimaggi I cannot view a log for that specific build (one has not been generated), but when I open logs from previous builds, Jenkins says that it is idling and currently starting (though never starts).

**Comment by ldimaggi** [comment]
What do you see in the OpenShift console? Are the Jenkins and Content Repo pods idle? I have seen this problem intermittently in the past week too. 

Is this the same problem that you are seeing?

https://github.com/openshiftio/openshift.io/issues/3517

**Comment by mindreeper2420** [comment]
From what I can see, the classes and styles are still present in the code - the colors are being applied as they should (i.e. for the different states of In Progress, Paused/Pending, Failed and Success), but the animations attached to them are not working as expected.

There are actually two files that have duplicate code in them, so determining which is the proper file will need to be done before any fixes/adjustments can be applied.

**Comment by dlabrecq** [comment]
Can you please check the applications widget? That borrows some code from the pieplines page.

**Comment by mindreeper2420** [comment]
@dlabrecq I checked the applications widget (both in new and old dashboards), and they only showed the spinning progress icon.
