### ISSUE TITLE
To many links in pipeline

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#3483]
![screenshot from 2018-05-07 10-39-29](https://user-images.githubusercontent.com/10185999/39685883-2f455cce-51e3-11e8-9fac-9c7e6e8bb73d.png)
That's a lot of links
(on Prod)

**Comment by kishansagathiya** [comment]
Everything was duplicate. Doing a refresh fixed it, but, I shouldn't see this. Is there an issue for this already?

**Comment by kishansagathiya** [comment]
I click on view last build, gets me 404

**Comment by ldimaggi** [comment]
Under what circumstances should "last build" appear? I am not seeing it after 1-2 build are created:

![screenshot from 2018-05-07 07-26-47](https://user-images.githubusercontent.com/642621/39699691-456f3a3a-51c8-11e8-8d25-42ae9a7fc30f.png)

**Comment by kishansagathiya** [comment]
@joshuawilson Don't remember exact steps, sorry.

**Comment by joshuawilson** [comment]
closing, if you can reproduce please reopen or start a new issue
