### ISSUE TITLE
Unnecessary gray space when clicking on infotip

### ISSUE THREAD

**Issue by jarifibrahim** [openshiftio/openshift.io#3485]
![screenshot from 2018-05-07 11-47-26](https://user-images.githubusercontent.com/12949454/39687574-ad57d714-51ec-11e8-9fd2-8c279bd45e72.png)

Notice the huge gray area at the bottom of screen

Steps to Reproduce -
Click on the infotip for scenario

**Comment by divyanshiGupta** [comment]
@jarifibrahim I cannot recreate this issue. Can you please confirm again?

**Comment by jarifibrahim** [comment]
@divyanshiGupta I can reproduce it.

**Comment by aptmac** [comment]
Neat! I'm seeing the same issue too, here's a gif of it in action:

![planner-tooltip-grayspace](https://user-images.githubusercontent.com/10425301/39761820-14bf4dfa-52a7-11e8-8a53-340d98854085.gif)

**Comment by jarifibrahim** [comment]
@divyanshiGupta It's on prod and prod-preview

**Comment by nimishamukherjee** [comment]
Issue fixed. No gray space is seen now.
Please re-open is otherwise.
