### ISSUE TITLE
First draft terminology audit OSIO/OpenShift (5)

### ISSUE THREAD

**Issue by stacymcauliffe** [openshiftio/openshift.io#3491]
PARENT: #3457 

Create the first draft of a terminology audit focused on areas of overlap between OSIO and OpenShift  

- [x] Identify areas of overlap
- [ ] Generate terminology index and suggestions for those areas
- [ ] Identify next steps

**Comment by stacymcauliffe** [comment]
Completed first review of terms and identified several issues of overlap and interest between OSIO, OSO, and Tectonic - scheduling review with OSO team (Colleen and Serena). Will begin working to consolidate feedback and recommendations

**Comment by catrobson** [comment]
Can we close this issue and open another one when you have action to take after reviews?

**Comment by stacymcauliffe** [comment]
Presented first draft review - meeting set for Friday to ID action items.
