### ISSUE TITLE
Dropdown in Create a new Space is using white font on white background

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/openshift.io#3494]
![screenshot from 2018-05-07 12-43-26](https://user-images.githubusercontent.com/54133/39710938-9e725e74-51f4-11e8-8bd3-84f0fee32140.png)

**Comment by aptmac** [comment]
I believe this is a duplicate/related to: https://github.com/openshiftio/openshift.io/issues/3341

**Comment by gastaldi** [comment]
@aptmac indeed, I just couldn't find it because the title wasn't too clear :wink: 

Closing this in favor of #3341
