### ISSUE TITLE
Not able to see deployed Tenant applications 

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#3498]
Clicking on Staging / Production applications at OSIO build pipelines would not show deployed applications.. This been observed for '(1) VertX-HealthCheck, (2) WFarm-HTTP, (3) WF-HealthCheck. Did not see this problem for SBoot-HTTP and Vertx-HTTP boosters. Might be happening for other boosters as well...

<img width="1398" alt="screen shot 2018-05-07 at 11 28 02 am" src="https://user-images.githubusercontent.com/15967765/39718119-2a9517c6-51ea-11e8-9440-e6b6ab32771b.png">

cc @animuk @GeorgeActon

**Comment by bmicklea** [comment]
I've noticed that some apps are slower to become available than others. Did you wait awhile for those you found to be failing?

**Comment by ldimaggi** [comment]
It can take a few min - I am seeing this:

Stage:
![screenshot from 2018-05-07 15-09-52](https://user-images.githubusercontent.com/642621/39719969-d2de672a-5208-11e8-929d-2c70bd6f3383.png)

Run:
![screenshot from 2018-05-07 15-10-21](https://user-images.githubusercontent.com/642621/39719974-d7de1b76-5208-11e8-9f2b-bc95310021f6.png)

**Comment by ldimaggi** [comment]
Are you seeing any errors in the Jenkins build or pod logs?

**Comment by sthaha** [comment]
@krishnapaparaju by any chance did you inspect the state of the pods?

**Comment by krishnapaparaju** [comment]
I could still reproduce this error , this time with WFSwam HealthCheck. Earlier I was able to reproduce this problem with 3 boosters, this time with one booster (WFSwarm HealthCheck)

Here is the Jenkins log : https://gist.github.com/krishnapaparaju/c999d73a73d1e507197ba648b3301a11

I do see slight delay in deploying most of the boosters. However this issue covers 'not able to see deployed application at stage & production' for more than 25 minutes.. (please see the two screenshots with time that I had to wait before taking another screenshot .. top right corner)

<img width="1396" alt="screen shot 2018-05-07 at 11 04 20 pm" src="https://user-images.githubusercontent.com/15967765/39741507-0c87dd9e-524f-11e8-9228-255da65cd601.png">
<img width="1396" alt="screen shot 2018-05-07 at 11 25 58 pm" src="https://user-images.githubusercontent.com/15967765/39741508-0cc8545a-524f-11e8-8ad7-8aeea2a1aa9c.png">

**Comment by ldimaggi** [comment]
I still cannot recreate this error - Wildfly Swarm/Healthcheck:

![screenshot from 2018-05-08 10-51-39](https://user-images.githubusercontent.com/642621/39764575-ea84c068-52ad-11e8-806a-4c4d30878be0.png)
![screenshot from 2018-05-08 10-50-52](https://user-images.githubusercontent.com/642621/39764576-ea923ad6-52ad-11e8-82c8-d7ff78b8a3e1.png)

**Comment by joshuawilson** [comment]
no one can reproduce this, downgrading to SEV2

**Comment by bartoszmajsak** [comment]
@krishnapaparaju can you verify if that is still a problem? If so could you provide more details - such as state of your pods, build logs etc. This would help us analyze the problem further.

**Comment by gorkem** [comment]
I am closing this as it did not see any action for a while and can not be reproduced
