### ISSUE TITLE
Organizations

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#350]
The creation of a new organization must be initiated by an existing user. **UXD work to be done here** The user goes to the Organizations screen of their user Settings and performs the `New Organization` operation.

An organization requires a unique name, following the same naming restrictions for a user account. This name is be used to navigate the service, using URLs of the form https://openshift.io/*{orgname}*. See #351 for more URL examples.

When a user creates an organization, they are immediately added as the owner of the organization. An organization must have at least one owner, but may have multiple owners. Owners are granted broad rights within an organization. (See Permissions)

### Permissions
Permissions within an organization are ultimately defined in #2068. When a user is an owner of an organization, that grants them a set of irrevocable rights within the organization. The following is a list of Organization-level permissions; Organization owners **always** have all of these rights within the organization.

These rights may be granted, on a permission-by-permission basis, to any user.

- Create a new Space within the Organization; creator of the Space is the owner of the Space
- Change the owner of an existing Space within the Organization
- Delete any existing Space within the Organization
- Delete the Organization
- Add a user to the Organization
- Set a user in the Organization as an Organization owner
- Remove Organizational ownership from an owner in the Organization (but there must always be at least 1 owner)
- Set a Space within the Organization to only allow Organizational users

### Security Groups
Security Groups may be defined at the Organization level. These are simply named collections of users. These Security Groups, in turn, may be granted permissions within Spaces contained within the Organization.

### Rights within Organization Spaces

When a user is a member of an Organization, that does **not** automatically grant that user any particular rights within Spaces owned by the organization. Moreover, a user need not be a member of an Organization to be granted permissions within a Space within the Organization -- unless the Space has been explicitly set to only permit Organizational users.

### Example
User `U1` creates organization `O1`.
`U1` adds a new Space `S1` to `O1`
> `U1` is automatically set to be the owner of `S1`. Within `S1`, `U1` has full administrative rights.

`U1` invites `U2` to join `O1`
`U2` accepts the invitation
> `U2` is now a member of `O1`, but has very few rights in `O1`. Initially, `U2` may see the list of Spaces in `O1`, but can do little else.

`U1` changes the ownership of `S1` to be `U2`
> `U2` now has full administrative rights within `S1`.  `U1` has lost all rights *within* `S1`, although `U1` can always take back ownership of `S1` as they are an owner of `O1`.

`U1` creates a new Security Group in `O1` named `Space Admins`
`U1` grants the `Create a Space` permission to `Space Admins`
`U1` adds `U2` to `Space Admins`
> `U2` can now creates new Spaces within `O1`

`U1` creates a new Security Group in `O1` named `Space Contributors`
`U1` invites `U3` to join `O1`
`U3` accepts the invitation
`U1` adds the special security user `[All Organization Members]` to `Space Contributors`
> Note that at this point, `U3` still has essentially no rights within `O1`

`U2` creates a new Space `S2` in `O1`
In `S2`, `U2` grants collaborator permissions to `O1/Space Contributors`
> Here, `U2` is making use of an Organizational-level Security Group within a Space contained within the Organization
At this point in time, `U3` now has contribution rights within `S2`
Alternatively, `U2` could have granted collaborator permissions to `O1/[All Organization Members]` and achieved the same result

### Environments
When an Organization is created, it does **not** automatically get any Environments (#2278), nor is an associated account created in OpenShift Online. Note that if an Organization was automatically given one or two free Environments *and* a user is permitted to created endless Organizations, then a user would effectively be able to get an unlimited supply of free Environments.

Organizations do have the ability to define their own Environments, per the capabilities of #2278. These may be any valid Environment, including Environments defined in user accounts and other Environments such as ones from OpenShift Online Pro. Once defined, these Environments are valid deployment targets for Pipelines defined within the Organization's Spaces.

Note that if no Environments are defined then any Pipelines will have (null) deployment targets. In other words, the Pipelines can execute, but they will have no destination into which to deploy.

## Parent Scenario
#2751 Managing a software development project owned by an organization

**Comment by qodfathr** [comment]
We need a higher level scenario. I will create.

**Comment by qodfathr** [comment]
Added info on Environments relative to Organizations.

**Comment by alexeykazakov** [comment]
The description doesn't say anything about invitations. User may be invited to an org. User is added to the org only when the invitation is accepted by the user.

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2066
