### ISSUE TITLE
[UI] shows old launcher screen on pipeline view

### ISSUE THREAD

**Issue by hrishin** [openshiftio/openshift.io#3501]
**Steps to produce:**

1. navigate to pipeline view -> https://openshift.io/username/spacename/create/pipelines
2. click on right-hand corner breadcrumb menu and click `Add to Space` option as shown in below screenshot
![screenshot from 2018-05-08 10-41-34](https://user-images.githubusercontent.com/28615674/39739156-119c014e-52ad-11e8-9491-950812ff4a68.png)
3.  It shows the following launcher wizard
![screenshot from 2018-05-08 10-41-14](https://user-images.githubusercontent.com/28615674/39739188-42ef9116-52ad-11e8-826b-edd5565de1d1.png)

Is it desired behaviour?

It would be better to show new launcher wizard to give consistent user experience.

**Comment by joshuawilson** [comment]
these buttons and links need to be updated but also the difference should be behind a feature flag.
