### ISSUE TITLE
Work item title showing escaped in the link section

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3507]
1) Create a work item (say, Scenario) with a title having special chars e.g. `"hello"`
2) Create another Scenario with any title, say B
3) Create a child of B, say C
4) Open the quick-preview of C and browse to the Link section
5) Edit the links to make C a child of work item titled `"hello"`. Don't click on the _Link_ button yet.

Observe that the work item titled "hello" is displayed with escaped special characters like below:
![escaped char in link bar](https://user-images.githubusercontent.com/28748448/39745963-89f614ae-52c6-11e8-816b-ba7f74c314a0.png)

**Comment by sahil143** [comment]
Assigning to @sanbornsen. Fixed in his PR.

**Comment by joshuawilson** [comment]
@sahil143 please don't assign work to people. Using the @ mention in comments is sufficient.

**Comment by nimishamukherjee** [comment]
Issue fixed.
![specialchars](https://user-images.githubusercontent.com/1892722/48822318-a126b500-ed82-11e8-9974-047fc6364e95.png)

Please re-open is you find the issue.
