### ISSUE TITLE
Teams (Overview)

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#351]
## Overview
As the number of people involved with a development project increases, it is natural to divide the members into logical Teams. Some people may even be a part of multiple Teams.

In OpenShift.io, Teams serve  a primary purposes: to filter the display of development artifacts to those relevant to the members of team. For example, seeing only the backlog items for the team or only the pipelines for the team. In a sense, Teams are a mechanism to divide a Space into logical 'subspaces'.

## Handling in URLs
Teams are a first class construct in OpenShift.io and impact both URLs and navigation. As such, Teams add a new convention to URL paths:

- https://openshift.io -- marketing page with auto-redirect for logged in users to account home page
- https://openshift.io/{account} -- the profile page for Account *{account}* (either a user or an org)
- https://openshift.io/_home -- the account home page for current logged in user
- https://openshift.io/{account}/_home -- the account home page for Account *{account}* (mainly used to see account home page for an org)
- https://openshift.io/{account}/{space} -- team home page for the default Team of Space *{space}* in Account *{account}*
- https://openshift.io/{account}/{space}/_{screengroup} -- default Screen of Screen Group *{screengroup}* for default Team of Space *{space}* in Account *{account}*
- https://openshift.io/{account}/{space}/_{screengroup}/{screen} -- Screen *{screen}* of Screen Group *{screengroup}* for default Team of Space *{space}* in Account *{account}*
- https://openshift.io/{account}/{space}/{team} -- team homepage for Team *{team}* of Space *{space}* in Account *{account}*
- https://openshift.io/{account}/{space}/{team}/_{screengroup} -- default Screen of Screen Group *{screengroup}* for Team *{team}* of Space *{space}* in Account *{account}*
- https://openshift.io/{account}/{space}/{team}/_{screengroup}/{screen} -- Screen *{screen}* of Screen Group *{screengroup}* for Team *{team}* of Space *{space}* in Account *{account}*

## Relationship with Areas
A given Team `T` is mapped to one or more Areas. One of these Areas is the default Area for the Team. When a user navigates OpenShift.io, the navigation is via Teams, not Areas, per the previously defined URLs. As a general rule of thumb, the contents displayed on a Screen in OpenShift.io is filtered to only contained items which are associated with one of the Areas mapped to the Team.

An Area may be mapped to zero or more teams.

For example, https://openshift.io/foo/bar/_plan would show the Planner for Space *bar* in Account *foo*. All of the Planner items would be displayed. However, https://openshift.io/foo/bar/uxd/_plan would show the Planner filtered down to the work items associated to any Area that has been mapped to the *UXD* Team. In effect, this is the UXD Team's backlog. (Exactly how and which items are filtered is more complex than this, but this high-level example is meant to give a general understanding of the behavior.)

Since Areas are hierarchical, when a Team is mapped to an Area, it may be mapped to just that specific Area, or to that Area and all of its children. In either case, the default Area for a Team is always a specific Area.

### Example
```
S
+--A1
|  |
|  +--A1-1
|  |
|  +--A1-2
|  
+--A2
   |
   +--A2-1


T1 : {A1*}, default A1
T2: {A1}, default A1
T3: {S*}, default S
T4: {A1, A2}, default A2
T5: {A1-1, A2-1}, default A2-1
T6: {A1*, A2}, default A1-1
```
The top diagram shows a hierarchical arrangement of Areas in Space `S`. The bottom list is a mapping of Teams to Areas. In this mapping, `*` is used to represent "this area and all children." As such, Team `T1` is mapped to areas `A1`, `A1-1` and `A1-2`. Team `T3` is mapped to **all** Areas in the Space. Team `T6` is mapped to A1 and all of its children, and also A2 but **not** the children of A2.

### Default Area
The default Area for a Team is the Area which should be automatically associated to any development artifact created when in the context of that Team. For example, if Team `T` has a default Area of `A`, then when looking at the Planner for Team `T` and creating a new work item `W`, the Area associated with `W` should be set to be `A` by default. The user is free to change the Area of `W`.

Similar actions should occur when creating or importing Codebases, when creating Pipelines, etc.

## Default Team
Every Space has a default Team. When a Space is first created, a Team with the same name as the Space is created. This Team is to be used as the Team for displaying data when no Team is specified in the URL. For example, if the default Team is named `dt`, then the two URLs are functionally the same:

- https://openshift.io/foo/bar/_plan
- https://openshift.io/foo/bar/dt/_plan

The default Team of the Space may be set to be another Team, and the automatically created default Team may even be deleted -- provided that there is always a default Team specified. 

Teams may be renamed.

## Parent Scenario
#2026 Finding meaningful and actionable information within a large development project

**Comment by sbose78** [comment]
> For example a team can have admin access

Does admin access here imply privileges to administer a space, or privileges to administer the team?


Similar to Github Organization, are teams a subset of an organization? Or can a team be defined without the context of an organization.

Example,
I create a team called "CI experts" and add the same team to multiple orgs.

**Comment by qodfathr** [comment]
We need a higher level scenario. I will create.

**Comment by alexeykazakov** [comment]
To be clear. Not everything from this epic is double for train/heather. We plan to implement some backend for this but UI most likely will go to the next sprint.

**Comment by qodfathr** [comment]
Complete rewrite. :) There were aspects of the original write-up which are going to be exposed in peer Experiences to this one.

**Comment by qodfathr** [comment]
@catrobson here is some first pass info on Teams (in terms of Features, not security). I do not think this impacts UX directly, but it does imply that every screen in the service needs to have a 'Team aware' version of the screen. In essence, right now OSIO is behaving as if there is just one, unnamed team. This expands upon that so individual screens have filtering applied to only show stuff for the Team (which really means to only show stuff in the Areas associated with the Team).

**Comment by qodfathr** [comment]
Added info on the default Team for a Space.

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/1994
