### ISSUE TITLE
Disallow leading digit or embedded spaces in application names

### ISSUE THREAD

**Issue by stooke** [openshiftio/openshift.io#3516]
The current UI validates names via a regex that allows leading digits and embedded spaces.
I would like to remove both of those; leading digits cause issues with DNS in Kubernetes, and spaces may cause unknown problems at some point.

First, I would like to ask for the _actual_ naming requirements; my proposed change is just a common-sense guess.

The "ideal" architecture disconnects the application name (or space name, etc.) from the code, and passes through an identifier such as a UUID or other short form.  Again, this issue is just a bandaid ona deeper problem.

current regex:
    const pattern = /^[a-zA-Z0-9][a-zA-Z0-9-_\s]{2,38}[a-zA-Z0-9]$/;

proposed regex:
    const pattern = /^[a-zA-Z][a-zA-Z0-9-_]{2,38}[a-zA-Z0-9]$/;

**Comment by stooke** [comment]
Kubernetes:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md

**Comment by joshuawilson** [comment]
I'm guessing this is the Space name?

**Comment by stooke** [comment]
Yes, the regex is very permissive.  If we were passing UUIDs throughout, this would be fine, but we pass names, and not just names, names with extra strings tacked on - so it's hard to determine the exact limitations on any given identifier.

In particular, the existing pattern allows spaces, and there have been issues (resolved) around spaces.  There may still be more unsidcovered issues - it's not clear.

**Comment by jiekang** [comment]
Related https://github.com/openshiftio/openshift.io/issues/3503

**Comment by jiekang** [comment]
Closing as fix has been merged.
