### ISSUE TITLE
Deployments request to https://api.openshift.io/api/deployments/spaces/<spaceId> fails

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#3524]
Seen on production, requests to `https://api.openshift.io/api/deployments/spaces/<spaceId>` fail with:

Request failed: 500 (Internal Server Error) {"errors":[{"code":"internal_error","detail":"could not retrieve space arst: failed to GET url http://f8osoproxy/oapi/v1/namespaces/jkang/builds?labelSelector=openshift.io%2Fbuild-config.name%3D0123456789012345678901234567890123456789012345678901234567890123%2Cspace%3Darst due to status code 400","status":"500","title":"Internal error"}]}

400 is bad request. What changed?

**Comment by jiekang** [comment]
@ebaron @stooke any ideas?

**Comment by stooke** [comment]
Yes, but do you have any entity with that long string in its name? 0123456789012345678901234567890123456789012345678901234567890123 application

**Comment by jiekang** [comment]
Ah... right. Yes that was created when testing the 64 character limit and demonstrating the ability to start an application name with a number via the new wizard (but not via the old wizard)

Maybe this is a good reason for https://github.com/openshiftio/openshift.io/issues/3516 and the 40 character limit?

**Comment by stooke** [comment]
almost certainly.  Can you still make a 64 character name in the new wizard?

**Comment by jiekang** [comment]
This was done before your change went in. I can't anymore.

**Comment by jiekang** [comment]
I guess this is in a round-about way a duplicate for #3516 but it does highlight why that needs to be done.

**Comment by ebaron** [comment]
Perhaps we should add a check for the 63 character limit in the deployments API, so we fail with a better error?

**Comment by stooke** [comment]
The deployments API takes UUIDs for space IDs.
What we could do is (on failure from k8s calls) check the length and if it's too long add a message into the error response passed back from k8s.
In that way, we're not adding any restrictions of our own.

How does that sound?

**Comment by ebaron** [comment]
When I send this request using a cURL, I noticed there is a Kubernetes Status resource returned in the response body. 
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "unable to parse requirement: invalid label value: \"0123456789012345678901234567890123456789012345678901234567890123\": must be no more than 63 characters",
  "reason": "BadRequest",
  "code": 400
}
```
We should probably check the response body for this and extract the message from it. This would improve our error messages throughout, without us needing to check each condition ourselves.

**Comment by ebaron** [comment]
Should we propagate the 400 Bad Request here, or stick with 500 Internal Server Error? I'm a bit concerned about any unintended side effects of doing so, such as when returning 401 logged the user out from OSIO.

**Comment by stooke** [comment]
I'd take chance with the 400.  Recently I bubbled up some other errors that were hidden like that and it helped us catch the issue (the reused osio client object) right away.

**Comment by ebaron** [comment]
Sounds good, thanks for the input!

**Comment by jiekang** [comment]
If this issue doesn't affect all the results, is there some response that indicates that some parts are faulty but the rest are usable? E.g. if I have 5 applications, 1 of them is malicious, we could still get the right data for the 4 back to the front-end to display, and handle the 5th as an error and maybe have some UX around that.
