### ISSUE TITLE
User accounts provisioned on 1a and 1b cluster are seeing No 'Access-Control-Allow-Origin' errors

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3527]
Steps to recreate issue:
* Login to https://openshift.io with a user account provisioned on the 1a or 1b cluster
* Observe the browser console log - the error is seen frequently while performing operations such as creating a new build pipeline:

```
Failed to load https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/oapi/v1/namespaces/username/buildconfigs: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'https://openshift.io' is therefore not allowed access.
```
Note - is this issue related to this problem:  https://github.com/openshiftio/openshift.io/issues/3461?
#3461 seems to happen very frequently with accounts provisioned on the 1a and 1b clusters.

**Comment by ldimaggi** [comment]
It looks as though issue #3461 is being seen 100% of the time for user accounts on the 1a and 1b clusters - See: #3527

**Comment by jfchevrette** [comment]
The CORS issue seem to be between the frontend and the f8osoproxy, not on the cluster side

**Comment by jiekang** [comment]
Right. I think the f8osoproxy should respond with `Access-Control-Allow-Origin` for `https://openshift.io`.

**Comment by joshuawilson** [comment]
What is the status on this?

**Comment by ldimaggi** [comment]
This problem look like it has been resolved. The user on the 1a cluster was successful late last week and the 1b cluster started working over the weekend.

One big question before we close this issue - what exactly was changed by whom and when? Thx!

https://ci.centos.org/view/Devtools/job/devtools-test-e2e-openshift.io-logintest-cluster-1a/
https://ci.centos.org/view/Devtools/job/devtools-test-e2e-openshift.io-logintest-cluster-1b/

**Comment by ldimaggi** [comment]
Closing - verified fixed in production.
