### ISSUE TITLE
Hovering a recent space link in home component can introduce an unneccessary scrollbar

### ISSUE THREAD

**Issue by aptmac** [openshiftio/openshift.io#3529]
When hovering a link in the recent spaces widget of the home component, a scrollbar can appear on the highlighted list group. This currently only occurs in feature-flag >= experimental, because the trigger for this is the addition of a tooltip when highlighting the space link [0].

Here's an example:
![scrollbar](https://user-images.githubusercontent.com/10425301/39837269-fdd8e972-53a3-11e8-9c7c-4d94b397d24b.png)

After a bit of digging, what seems to be happening is that the tooltip is causing a text overflow, which is causing a scrollbar to be shown. The f8-card has a `overflow-x: hidden` [1], which when removed stops the scrollbar from appearing, but has a side-effect of lightening the colour of the card border so it's not as quick a stylesheet fix as that.

![scrollbar-removed](https://user-images.githubusercontent.com/10425301/39837477-a09fce6e-53a4-11e8-9607-ceadb5255c16.png)

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/home/home.component.html#L92
[1] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/assets/stylesheets/shared/_cards.less#L20

**Comment by aptmac** [comment]
Additionally, the tooltip [0] has a fixed max width [1] so space names that are large will be cut-off prematurely.

Example:
![cutoff](https://user-images.githubusercontent.com/10425301/40926945-7480334a-67eb-11e8-9048-ecb9b6a19a50.png)

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/home/home.component.html#L94
[1] https://github.com/twbs/bootstrap/blob/be3aa437a11dbe625ba401ad3c1ea3b57af30f78/scss/_tooltip.scss#L109

**Comment by christianvogt** [comment]
We should consider tooltips that mount on the body or use fixed display. Something to ensure pf4 addresses.

**Comment by aptmac** [comment]
The recent-spaces card was updated [[0]](https://github.com/fabric8-ui/fabric8-ui/pull/3166/commits/7d054dabd80738267b3d5e657746f3a0fc3308f7) to fill the component with spaces instead of overflowing with a scrollbar.

[0] https://github.com/fabric8-ui/fabric8-ui/pull/3166/commits/7d054dabd80738267b3d5e657746f3a0fc3308f7
