### ISSUE TITLE
Clean up Python CVE false positives in S3 and graph

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#3530]
# Description

We tried to use multiple tools/sources of CVE data in the past. None of them was particularly good and graph queries reveal that there is quite a lot of false positives. We want to get rid of them and only use curated CVE data for Python that we have now. We want to clean up both S3 and graph.

**Comment by miteshvp** [comment]
@msrb - any updates?

**Comment by msrb** [comment]
Done :wink:
