### ISSUE TITLE
Logon issue

### ISSUE THREAD

**Issue by stevef1uk** [openshiftio/openshift.io#3538]
When I logon as the Id I registered with for openshift.io get the message that:

User with email ****@****.com already exists. How do you want to continue?

When I select 'Add to existing account' I get asked for the password, which isn't accepted for the ****@****.com ID. I know I haven't forgotten it as I have just changed it using this link: https://www.redhat.com/wapps/sso/lostPassword.html

I do have an openshift.com account

How do I logon?

**Comment by sbose78** [comment]
@stevef1uk could you try logging in with just the username instead of the email ?

**Comment by sbose78** [comment]
Similar to https://github.com/openshiftio/openshift.io/issues/2332

**Comment by stevef1uk** [comment]
Whatever I did made no difference until I registered the email address it was complaining about and used that one
