### ISSUE TITLE
Mockup for automated generation of documentation strings

### ISSUE THREAD

**Issue by abs51295** [openshiftio/openshift.io#3546]
## Description

The analytics team would like to do an experiment regarding how we can reduce the burden of developers by auto generating documentation strings/JavaDoc for every possible class/method definition. As a first step towards, the task here is to create mockups for the same which are required by the PM to visualize the workflow.

Link to planner issue: https://openshift.io/openshiftio/openshiftio/plan/detail/2255

## Task List

- [x] Help UX team visualize the whole workflow.
- [x] Create mock up for this feature inside Che to showcase the value of this new feature.

**Comment by parvathyvr** [comment]
Invision mockup link: https://redhat.invisionapp.com/share/V3J3MK8Y2M8#/298265078_Table_Of_Contents  
Feel free to comment for any changes.

**Comment by abs51295** [comment]
Closing this since we got the feedback from PM team. Will be creating a new one to incorporate the suggestions received.
