### ISSUE TITLE
*errors.StatusError: configmaps "fabric8-environments" not found

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#3556]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-wit/issues/3699/

```
*errors.StatusError: configmaps "fabric8-environments" not found
  File "/tmp/go/src/github.com/fabric8-services/fabric8-wit/sentry/sentry.go", line 101, in func1
  File "/tmp/go/src/github.com/fabric8-services/fabric8-wit/sentry/sentry.go", line 75, in loop

configmaps "fabric8-environments" not found
```

**Comment by ebaron** [comment]
With https://github.com/fabric8-services/fabric8-wit/pull/2110, the deployments API no longer queries this config map. The information about environments comes directly from the tenant API instead.
