### ISSUE TITLE
Need to add labels for specifying quickstart runtime owner

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#3557]
Currently there are no labels for defining concrete `runtime` in the issue, so it might be handy to specify the following runtime labels

`area/launcher/runtimes/vertx` 
`area/launcher/runtimes/wildfly`
`area/launcher/runtimes/spring-boot`
`area/launcher/runtimes/node.js`

Also, it is not straight forward who are the runtime key contacts. Please, correct me if I'm wrong but AFAIK those are:

@kenfinnigan for `wildfy`
@cescoffier for `vertx`
@cmoulliard (?) for `spring-boot`
@lholmquist  for `node.js`

NOTE: label description should be also added to wiki - https://github.com/openshiftio/openshift.io/wiki/Labels

**Comment by ibuziuk** [comment]
@gastaldi wdyt ?

**Comment by gastaldi** [comment]
@ibuziuk :+1: don't forget `area/launcher/runtimes/node.js` with @lholmquist

**Comment by lholmquist** [comment]
that is the most important runtime :)

**Comment by ibuziuk** [comment]
@lholmquist @gastaldi added to the description ;-)

**Comment by ibuziuk** [comment]
labels have been added & wiki updated. Closing
