### ISSUE TITLE
Login flow ends up in "already logged in"  and still user has to manually login twice

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#356]
This tend to happen after some 8-24hr+ of non openshift.io or any developers.redhat.com usage at all - meaning, I see it almost every morning.

CURRENT BEHAVIOR:

1) Open Browser on openshift.io or manage.openshift.com and gets told I need to login
2) click on login, fill in credentials
3) Presented with page saying "Already logged in" (no buttons available to do *anything*
4) Repeats Open Browser on openshift.io or manage.openshift.com and gets told I need to login
5) Repeats click on login, fill in credentials
6) Now shown the relevant openshift.io / openshift.com page

What I would OPTIMALLY EXPECT if I'm truly already logged in:

1) Open Browser on openshift.io or manage.openshift.com 
2) shown the relevant openshift.io/openshift.com

If I am not actually logged in, and the "Already logged in" is a fluke then I would EXPECT:

1) Open Browser on openshift.io or manage.openshift.com and gets told I need to login
2) click on login, fill in credentials
3) Now shown the relevant openshift.io / openshift.com page

screenshot of the "Already logged in" UI:
![Uploading You_are_already_logged_in____Red_Hat_Developer_Program.png…]()

**Comment by maxandersen** [comment]
whoops - adding to kill list was mistake.

**Comment by alexeykazakov** [comment]
Related issue in RHD JIRA - https://issues.jboss.org/browse/RHDENG-1523

**Comment by alexeykazakov** [comment]
![you_are_already_logged_in____red_hat_developer_program](https://user-images.githubusercontent.com/620087/28035913-2663a184-656b-11e7-8bfc-b15b34219f0a.png)

**Comment by joshuawilson** [comment]
There was a long discussion on https://github.com/fabric8-ui/fabric8-ui/issues/726 and it was decided that the current flow is the best option. However, if you want to pick things up here we should add @catrobson to this thread.

**Comment by alexeykazakov** [comment]
@joshuawilson this issue is actually not about login workflow. It's just a bug when you login via developers.redhat.com but after filling in credentials you see a screen saying that you are already logged in instead of redirecting you.

**Comment by joshuawilson** [comment]
I see that now, thanks for clearing it up.

**Comment by qodfathr** [comment]
Closing as it looks like this has been addressed. Reopen if needed.
