### ISSUE TITLE
Removed IDs from feature flags

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#3569]
The features IDs on Features Opt-in page have been removed last night / this morning what broke smoke E2E tests. Please put it back :-)

It used to be
```
<input type="radio" id="beta" class="ng-untouched ng-pristine ng-valid" /> </div>
```
And now is just
```
<input type="radio" value="item.selected" />
```

@joshuawilson

**Comment by jiekang** [comment]
Do you happen to know which file this is? My text searches for variations of `<input type="radio" value="item.selected" />` don't return anything. Maybe this isn't `fabric8-ui` repository?

**Comment by ljelinkova** [comment]
I guess this is the file but I do not know why there is no <input>

https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/settings/feature-opt-in/feature-opt-in.component.html

**Comment by kpiwko** [comment]
I believe removed of ids in radio buttons is associated with this commit @corinnekrych:

https://github.com/fabric8-ui/fabric8-ui/commit/b77269ec64208d9ddc118216ab84ded5d47e3c61#diff-b52fb93fcd8263f583abf5f4b6c65c3f

**Comment by kpiwko** [comment]
That's unfortunate but likely - e2e tests would need to use input@name - unless we want to fix patternfly lists to support ids:

https://github.com/patternfly/patternfly-ng/blob/a23d41d04b8ed607ddcdc6d3d69a873966edeb53/src/app/list/basic-list/list.component.html

**Comment by ppitonak** [comment]
Do I understand it correctly that patternfly doesn't support IDs?

@kpiwko what do you mean by saying that tests need to use input@name? Attribute "name" is not defined.

**Comment by kpiwko** [comment]
I mean input@value, sorry.

From what I see here, Patternfly does not support id for input lists - https://rawgit.com/patternfly/patternfly-ng/master-dist/dist-demo/#/list . Definitely something that should be considered to be added to patternfly to make patternfly projects easier to test.

**Comment by kpiwko** [comment]
With my limited understanding of angular, I believe that a quickfix would need to have 2 steps:

1/ Add item.value for every option here: https://github.com/fabric8-ui/fabric8-ui/blob/b77269ec64208d9ddc118216ab84ded5d47e3c61/src/app/profile/settings/feature-opt-in/feature-opt-in.component.ts#L83
2/ Update tests to use item@value to navigate

More complicated fix would be to modify patternfly lists to add id to list elements and afterwards add item.id to feature-opt-in.component.ts file. I've created an upstream issue for that here: https://github.com/patternfly/patternfly-ng/issues/348

**Comment by joshuawilson** [comment]
I'm not sure why the ID was removed. We need @corinnekrych to comment on that. 

I will say that `beta` is not a unique ID and therefore violates HTML. We should only be using IDs for tests. They should also be unique across the entire application. This can be done by prefixing the ID with the file name as a namespace.

Now we need to know if Tests need this radio button to have an ID or if they can work with the above methods.

**Comment by ldimaggi** [comment]
I don't think that we can rely on the @value attribute - it seems to be selected for all (4) of the feature levels:

![screenshot from 2018-05-16 12-03-27](https://user-images.githubusercontent.com/642621/40129453-55732982-5902-11e8-8127-dfeda56674e1.png)

**Comment by aptmac** [comment]
For a bit of background, there had been a structural change to the list in a commit yesterday [0]. 

Previously, the radio button was manually included into the pfng-list and it wasn't using pfng expansion logic as intended. Recently, a commit [1] was made to the pfng-list to include radio buttons as an option, and this change was incorporated into the commit [0] that got pushed yesterday.

[0] https://github.com/fabric8-ui/fabric8-ui/commit/b77269ec64208d9ddc118216ab84ded5d47e3c61
[1] https://github.com/patternfly/patternfly-ng/commit/d128e200e95b90f27fe6c1dccac03c5b13d38027

**Comment by ldimaggi** [comment]
Any idea why all 4 radio buttons are designated as 
`
<input type="radio" value="item.selected" class="xh-highlight">
`

**Comment by ppitonak** [comment]
@joshuawilson we don't need ID, it can be value or name of the input tag. We just need it to be page-unique (application-unique is even safer).

**Comment by corinnekrych** [comment]
Like @aptmac and @kpiwko said the id were removed bc we now used [patternfly-ng radio button](https://github.com/patternfly/patternfly-ng/blob/master/src/app/list/basic-list/list.component.html#L70). In `fabric8-ui` we don't control the HTML content of the input anymore. 
cc @ppitonak @joshuawilson 

* option1: I could add an `id` (in red) but you have to do a CSS xpath query like: give me the input whose sibling descendant has an id of `experimental`.... not easy I must admit:

![fabric8-ui__list-pf](https://user-images.githubusercontent.com/1395710/40355711-6fbe4f4c-5db7-11e8-868a-a02a40033072.png)

* option2: we add those id in `patterfly-ng` sth like:
![patternfly-ng__list-pf](https://user-images.githubusercontent.com/1395710/40355815-b0c51192-5db7-11e8-819c-702aa2aaf5a6.png)

For option2, I need @dlabrecq review, I've done PR https://github.com/patternfly/patternfly-ng/pull/358 as a suggestion...

**Comment by corinnekrych** [comment]
Closing https://github.com/patternfly/patternfly-ng/pull/358 as per @kpiwko suggestion, it leaves us with optiuon1 you can write test with: give me the input whose sibling descendant has an span with class of `icon-experimental`.

**Comment by corinnekrych** [comment]
@joshuawilson both, but if you think we need the issue to track the test change, feel free to re-open.
In the end the change is not going to happen in fabric8-ui.

**Comment by joshuawilson** [comment]
If this still needs to be fixed, it doesn't matter where it get's fixed, then we should keep it open, right?
Or do we need a user-story to plan to fix it?

**Comment by ppitonak** [comment]
We created a workaround in tests but, in general, we should always address this kind of issues. Patternfly-ng not having a feature is not a reason to close this issue - we either workaround it in fabrid8-ui or ideally fix it in patternfly-ng.

**Comment by kpiwko** [comment]
@ljelinkova can we close this one? I believe it has been already worked around, wasn't it?

Thanks!

**Comment by ljelinkova** [comment]
Sure, closing it now.
