### ISSUE TITLE
Cannot login to openshift.io anymore

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#3571]
when I try to access openshift.io, I'm redirected to this page:
![image](https://user-images.githubusercontent.com/1105127/40107381-5aa58ab2-58f8-11e8-945b-22e6d37e1af3.png)

if I click "Sign up for OpenShift Online", i'm redirected to this page:
![image](https://user-images.githubusercontent.com/1105127/40107409-6deb6d6c-58f8-11e8-9eed-838edc0e7160.png)

I already tried in incognito mode and same results
it was working something like 3 or 4 weeks ago

**Comment by sbose78** [comment]
@apupier Your account was de-provisioned because you had posted sensitive data in https://github.com/openshiftio/openshift.io/issues/3073 

Please create a new RHD account and start from the scratch.
