### ISSUE TITLE
[~?] Browser support, beyond Chrome

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3573]
Need full support for the following browsers:

- [ ] Firefox
- [ ] Safari

**Comment by rgarg1** [comment]
@qodfathr What does this stand in the order of priorities?

**Comment by joshuawilson** [comment]
This is a bug. We have said from the beginning that we support all major browsers at the current version -2.

**Comment by rgarg1** [comment]
Cc @michaelkleinhenz

**Comment by ldimaggi** [comment]
See the supported browser list here:
https://github.com/openshiftio/openshift.io/wiki/Supported-Browsers

**Comment by rgarg1** [comment]
@nimishamukherjee As you are aware, the focus pre-summit was always Chrome. Now that summit is over, detailed validation of other browsers will start. Hence, the placeholder. I originally created a task.

**Comment by joshuawilson** [comment]
Who said that the focus was to be Chrome? For 2 yrs now we have said it should work on all major browsers. It might be that any issue regarding FF or Safari was marked at a lower priority but that doesn't mean we didn't have it as a requirement from day 1.

**Comment by debloper** [comment]
> See the supported browser list here:
https://github.com/openshiftio/openshift.io/wiki/Supported-Browsers

@ldimaggi that list is gonna get obsolete really fast and will need continuous docs update to stay relevant, and I think the better way to express the supported versions by saying it the way Joshua explained it `current version -2`.

> Who said that the focus was to be Chrome?

@joshuawilson I believe @rgarg1's point was, _"even though we target to make it work on all the latest modern browsers, but we couldn't manage to fully ensure/testify that, so we needed to ensure it at least works well on Chrome for the sake of Summit Demo."_ It wasn't about excluding out (or pointing fingers for excluding out) other browsers. And the current ask is, to compensate for the missing testification/ensurance for the app to work across browsers. At least that's what it reads to me.

**Comment by michaelkleinhenz** [comment]
A consequence is that we need to run the tests on all supported browsers then, not only Chrome. For functional as well as unit tests. That would mean we need to work on the test framework (again).

**Comment by michaelkleinhenz** [comment]
I wouldn't consider this a bug, it is an architectural issue. On the implementation as well as on the ci/cd side. We create a Fundamental for this. This will take a *lot* of work.

**Comment by joshuawilson** [comment]
@michaelkleinhenz I've added an Experience here for you to add user stories for this. https://openshift.io/openshiftio/openshiftio/plan/detail/2397

**Comment by michaelkleinhenz** [comment]
Can we please close this issue in favour of specific issues with the browser compatibility? Planner is generally working on Firefox and Safari, we need more specific issues here.

**Comment by joshuawilson** [comment]
@michaelkleinhenz we can close it since we have the link I added above to track it.
