### ISSUE TITLE
Should be able to use Planner using keyboard 

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3574]
As of today, keyboard support in Planner is sporadic and inconsistent. 

Planner needs to provide full and consistent keyboard support for its users.

**Comment by rgarg1** [comment]
@qodfathr Where does this stands in the order of priorities?

**Comment by joshuawilson** [comment]
Please file user stories under https://openshift.io/openshiftio/openshiftio/plan/detail/2009

**Comment by rgarg1** [comment]
https://openshift.io/openshiftio/openshiftio/plan/detail/2352

**Comment by qodfathr** [comment]
@joshuawilson it should be added to bottom of backlog (under the relevant experience) and PM will prioritize as appropriate.

There may need to be a new Fundamental regarding accessibility, with a child Experience for keyboard operation/navigation in OSIO, as this feels like a cross-cutting concern.

**Comment by nimishamukherjee** [comment]
Closing this issue. Duplicate of #1840
