### ISSUE TITLE
Unable to edit or delete comments added by a non collaborator

### ISSUE THREAD

**Issue by jaseemabid** [openshiftio/openshift.io#3575]
The screenshot shows a comment added by me, but I've no way of editing or deleting it. 

![2018-05-17-141748_793x579_scrot](https://user-images.githubusercontent.com/601714/40166821-238d0fa6-59dd-11e8-9c33-f79c429cccb9.png)

**Comment by jaseemabid** [comment]
btw, the comment author is not seen as well but @sanbornsen says its a known issue.

**Comment by christianvogt** [comment]
Non-collaborators can edit their own comments.
