### ISSUE TITLE
Create space button opens old dialog when in My spaces

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3576]
1. click on top-left menu -> My spaces
2. click "Create Space" button in top-right corner

expected:
* new dialog opens

actual: 
* old dialog opens

![osio_create_space](https://user-images.githubusercontent.com/445100/40169397-3397d960-59c6-11e8-9393-5af1ca7b34c9.gif)

**Comment by ppitonak** [comment]
@joshuawilson when will be this in prod? can we leave this issue open unitl it gets to production?

**Comment by joshuawilson** [comment]
it should be in prod

**Comment by ppitonak** [comment]
Works in prod.

@joshuawilson when will we completely remove old wizard?

**Comment by andrewazores** [comment]
I believe that work is tracked here: https://github.com/openshiftio/openshift.io/issues/3629

**Comment by ppitonak** [comment]
@andrewazores yes, it's tracked in that issue but I don't see **when** it will be delivered.

**Comment by andrewazores** [comment]
Perhaps that issue is a better place to ask?
