### ISSUE TITLE
Evaluate Travis CI 

### ISSUE THREAD

**Issue by rupalibehera** [openshiftio/openshift.io#3578]
Evaluate Travis Ci to check if it can be the next build service we are looking for

**Comment by pradeepto** [comment]
@rupalibehera Is this done? Can you articulate your findings in this issue and close it. And then move it to done.

**Comment by rupalibehera** [comment]
Here are the findings for Travis CI
https://docs.google.com/document/d/1OyKgfGeJRTm9DV2eVhoo7NkQZljabWiZjZYsxZaRShg/edit#heading=h.yawr4cpp0hdr

**Comment by rupalibehera** [comment]
Two Major reason why further evaluation does not make sense:
1. Installing locally : I could not find any docs for installing travis ci locally, they do provide on-prem service but that is enterprise version of it link to the docs https://docs.travis-ci.com/user/enterprise/. They don’t have anywhere in the documentation about installing it locally the complete setup. So how we could we install it on Openshift/Kubernetes.
2. Github integration: It is only integrated with Github, we cannot use in future to integrate with any other code hosting service.

Though we can take ideas of how they do the builds.
