### ISSUE TITLE
Feature Toggle

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#358]
# Description
As a user, I want to be able to turn on new features without being required to use/view them.

# Acceptance Criteria
- [x] The user can activate an experimental feature easily.
- [x] The user can deactivate an experimental feature easily.
- [x] An experimental feature can be a whole page. [1576](https://github.com/fabric8-ui/fabric8-ui/issues/1576)
- [ ] An experimental feature can be as specific as a field or button.
- [ ] The user should have fine grain control of the features.
- [ ] The controls of the features should be a dynamic list can be update with each build. 
- [ ] An experimental feature can be backend only, though most will have a UI component to them that is not required to have a feature toggle for it.

**Note**:

# Relationships
_Put linked Team/Product story links here_

**Comment by maxandersen** [comment]
Tried the feature and noticed a few things:

Visiting deep links like https://openshift.io/openshiftio/openshiftio/plan/detail/cb15f74f-1211-474b-bdd7-d0fe3976bf92 gives various surprising behaviour.

Not logged in: 404 error
Logged in with or without flag enabled: page shows, no warning/info.

**Comment by qodfathr** [comment]
Superseded by #1165 (this could potentially be a child of that epic)

**Comment by qodfathr** [comment]
It looks like #1165 is really capturing all of the use cases, so this can be considered to be a dupe. Reopen if needed.
