### ISSUE TITLE
Evaluate Jenkins for Container CI and CD platform

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#3581]
this issue covers evaluation of Jenkins for container CI/CD. Here are the criteria going to be evaluated against criteria mentioned at #3570

**Comment by jaseemabid** [comment]
Adding a few Jenkins specific questions @sthaha asked on the channel here, which
is on top of what we have in the [Evaluation
Criteria](https://github.com/fabric8io/buildnext/blob/master/Evaluation.md)

1. How are the deployments of multiple masters orchestrated
2. What plugins are required
3. How are logs from the builds streamed to the user
4. How are jobs defined (dsl/jenkinsfile)
5. How are tenants isolated
6. How are logs stored and retrieved
7. If master is created on demand and then deleted, how do we preserve the old builds?
8. Isn't jenkins resource consumption to run a build too high already?
9. Are we going to expose jenkins to user?

**Comment by jaseemabid** [comment]
Adding a few of my own questions. 

1. How are we going to control the number of concurrent builds? Previous attempts failed badly. #2729 
2. How will we cleanup the dead slaves? The k8s plugin has failed innumerable times before.

**Comment by krishnapaparaju** [comment]
1) * how are the deployments of multiple masters orchestrated --> Multiple masters , slave nodes are all multiple replicas on a K8 system. I do not think multiple masters would need to co-ordinate as an individual job always taken care by one master. Multiple masters are more meant for HA setup to avoid SPOF.

2)  what plugins are required ?? If this question is related to master management, I need to figure out. Don't know yet
3) how are logs from the builds streamed to the user ? Logs are maintained at master (not at slaves), this require security be in place to have clear separation, am exploring various options available. Either way (wherever the logs are maintained), these logs would be need to fed to the storage of Build.Next platform. From the storage of Build.Next, the logs would be streamed to users  /downstream services like OSIO analytics
4) how are jobs defined (dsl/jenkinsfile) ? both are possible options, from OSIO point of view, DSL are the only viable option
5) how are tenants isolated ? Tenant specific information got multiple parts (information e.g.: logs stored at master, secrets, pipeline steps). For logs at master, there are options at Jenkins to isolate + secrets with proper controls at K8S would be fed to slave nodes / slave pods can pick up secrets from a DB (encrypted). Slave pods get started and die with a specific tenant's job. Along with this, required isolation would need to be in place at K8S for separating tenants. This discussion (at Build engine and K8S) is more general discussion than specific to Jenkins
6)  how are logs stored and retrieved ? Please see (3)
7)  if master is created on demand and then deleted, how do we preserve the old builds ? Masters are not created per each job, slave pods are. persevering the build logs require we store the logs (as they appear) to OSIO Infra. Please see (3)
8)   isn't jenkins resource consumption to run a build too high already? +1 Jenkins is resource heavy. Only comfort with multi tenant system is that, we can reuse slave pods / resources for multiple tenants. This is not the case currently and having huge impact on resource consumption.
* are we going to expose jenkins to user? My IMO is NO, as user can trigger jobs, view status/logs directly from Build.next. If we encapsulate this way, the front ending components of the architecture would not have any assumptions specific to Jenkins / any build engine. We do have a use case of letting a customer bring their down build engine..

**Comment by krishnapaparaju** [comment]
9) * How will we make the service commercially viable if we have to run a Jenkins per user?
      Current target to multi tenant setup with Jenkins / any engine on a cluster

10) * How are we going to control the number of concurrent builds? Previous attempts failed badly.  Build Blocker plugin is doing the trick. please follow the conversation at #2729 

11) How will we cleanup the dead slaves? The k8s plugin has failed innumerable times before.
        Can you please point me to any existing k8s plugin issue for this case.

**Comment by jaseemabid** [comment]
> Can you please point me to any existing k8s plugin issue for this case.
>> How will we cleanup the dead slaves? The k8s plugin has failed innumerable times before.

This was a common issue for the build team every other day. The only solution was to periodically restart the GKE instances and it was silly. This is observed on prod as well.

**Comment by jaseemabid** [comment]
On 31 May 2018 at 17:42, SriKrishna <notifications@github.com> wrote:

>
>    1.
>       - How will we make the service commercially viable if we have to
>       run a Jenkins per user?
>       Current target to multi tenant setup with Jenkins / any engine on a
>       cluster. Namespaces coupled with IP network micro segmentation is currently
>       I am experimenting.
>
>
Isolation still doesn't the problem of resource consumption and deluge of
horrible hacks we have to throw on top of it like Idler and Proxy. A single
Jenkins master will never be able to handle 2 customers that are
potentially malicious. This is a dead end.


>    1.
>       -
>    2.
>       - How are we going to control the number of concurrent builds?
>       Previous attempts failed badly. Build Blocker plugin is doing the trick.
>       please follow the conversation at #2729
>       <https://github.com/openshiftio/openshift.io/issues/2729>
>
>
As of now we still haven't solved that issue and "throwing yet another
plugin" is not a viable solution to the problem. Each plugin is more code
and issues we have to deal with down the line.


-- 
Senior {Jenkins Babysitter | Software Archaeologist | Wiki Writer}

**Comment by jaseemabid** [comment]
On 31 May 2018 at 17:35, SriKrishna <notifications@github.com> wrote:
>
>
>    1.
>
>    if master is created on demand and then deleted, how do we preserve
>    the old builds ? Masters are not created per each job, slave pods are.
>    persevering the build logs require we store the logs (as they appear) to
>    OSIO Infra. Please see (3)
>    2.
>
>    isn't jenkins resource consumption to run a build too high already? +1
>    Jenkins is resource heavy. Only comfort with multi tenant system is that,
>    we can reuse slave pods / resources for multiple tenants. This is not the
>    case currently and having huge impact on resource consumption.
>
> This is exactly what we do right now -  master per tenant, slaves spawned
on demand. The solution you propose is what we have on prod since ages.
This will not work as the resource usage of master alone will make the
solution commercially infeasible and an engineering nightmare.

-- 
Senior {Jenkins Babysitter | Software Archaeologist | Wiki Writer}

**Comment by jaseemabid** [comment]
An example where Jenkins is stuck and cannot make progress because all executor slaves went into odd states. 

![image pasted at 2018-6-4 14-11 png](https://user-images.githubusercontent.com/601714/40908272-e36f2b0e-6803-11e8-8516-da24dfa84ef4.jpg)

**Comment by sthaha** [comment]
@krishnapaparaju I am going to close this issue as it doesn't seem relevant anymore given that we will continue to support the current build engine - Jenkins for quite some time.
