### ISSUE TITLE
Semantic release for ngx-launcher fails to publish release notes on github

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#3585]
- Post commit build for https://github.com/fabric8-launcher/ngx-launcher is releasing a new version to npm registry but it is failing to publish the release notes on github for the same.

Here is the build logs to refer :-
https://ci.centos.org/view/Devtools/job/devtools-ngx-launcher-npm-publish-build-master/48/console

**Comment by joshuawilson** [comment]
the log says:

```
Failed to exec semantic-release script
Error: ngx-forge@0.0.0-development semantic-release: `semantic-release pre && npm run build && cp -r .git dist && npm publish dist/ && semantic-release post`
```

**Comment by jyasveer** [comment]
closing this as this will be handled here https://github.com/fabric8-launcher/ngx-launcher/issues/261
