### ISSUE TITLE
vanity url has internal system id for work items - in the past displayed work it Numbers, now displays UUIDs

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#359]
When browsing issues you end up with urls like https://openshift.io/openshiftio/openshiftio/plan/detail/cb15f74f-1211-474b-bdd7-d0fe3976bf92 instead of https://openshift.io/openshiftio/openshiftio/plan/detail/1393

Also https://openshift.io/openshiftio/openshiftio/plan/detail/1393 gives not give the actual result nor a 404.

**Comment by joshuawilson** [comment]
Who owns this?

**Comment by ldimaggi** [comment]
Just noticed this - we have to change this so that URLs displayed to users are meaningful to users. Thx!

**Comment by joshuawilson** [comment]
@ldimaggi what is the "this"? We have to change this issue or we have to do what this issue says to fix this problem?

**Comment by aslakknutsen** [comment]
@joshuawilson The URL in the browser should use the wi.Number not wi.ID (int vs UUID)

Backend issue is here: https://github.com/fabric8-services/fabric8-wit/issues/1490

**Comment by ldimaggi** [comment]
Reply to Josh: Yes - this issue is THE issue - we have to change the operation of the system BACK to provide meaningful workitem ID's to the users.

**Comment by sanbornsen** [comment]
I can take this up for UI side having a dependency on a core issue - https://github.com/fabric8-services/fabric8-wit/issues/1582

**Comment by qodfathr** [comment]
Fixed.
