### ISSUE TITLE
Improve code coverage in fabric8-geminy-server to at least 90%

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#3592]
Repository https://github.com/fabric8-analytics/fabric8-gemini-server

## Current status:
```
Name                Stmts   Miss  Cover   Missing
-------------------------------------------------
src/__init__.py         2      0   100%
src/auth.py            44     20    55%   19-38, 50, 60, 63-64, 69
src/exceptions.py       5      0   100%
src/rest_api.py        79     57    28%   31-33, 45-111, 118-143, 155
src/utils.py          139     93    33%   53, 61-82, 87-91, 98-106, 129-134, 147-157, 166-185, 194-214, 224-231, 236-241, 249-268
-------------------------------------------------
TOTAL                 269    170    37%
```

## Acceptance criteria:

- [x] unit test are setup to run on each pull request
- [x] code coverage is measured for all unit tests
- [x] unit test code coverage over 90%
- [x] code coverage report is displayed on the QA Dashboard

## Links

QA Dashboard: https://fabric8-analytics.github.io/dashboard/dashboard.html
CI job to run unit tests and measure code coverage: https://ci.centos.org/job/devtools-fabric8-gemini-server-fabric8-analytics/

**Comment by abs51295** [comment]
Ongoing PR: https://github.com/fabric8-analytics/fabric8-gemini-server/pull/66. Current coverage 67%

**Comment by abs51295** [comment]
@tisnik can this issue be closed?

**Comment by tisnik** [comment]
everything's green, TYVM @abs51295
