### ISSUE TITLE
Visuals: Indicate validation error in previous steps

### ISSUE THREAD

**Issue by bdellasc** [openshiftio/openshift.io#3596]
- [x] Provide visual guidance for use case in [this story](https://github.com/fabric8-launcher/ngx-launcher/issues/209)
- [x] Post an InVision prototype showing the design

**Comment by catrobson** [comment]
@bdellasc can you link in your design and then I think this is ready to close.

**Comment by bdellasc** [comment]
I posted the mockups to InVision: https://redhat.invisionapp.com/share/V6JPJW7PW7B
