### ISSUE TITLE
Creating a new project in a space results in new builds being created for all other projects in the space

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#360]
Steps to recreate:
* Create a space, create a project in that space - observe the pipeline/build for that project:
![screenshot from 2017-07-06 11-16-00](https://user-images.githubusercontent.com/642621/27918625-854f2da2-623d-11e7-914c-09f31b94193c.png)

* Create a second project in the space - observe that a 2ns build/pipeline for the first project is also created:
![screenshot from 2017-07-06 11-18-29](https://user-images.githubusercontent.com/642621/27918675-ad29b50e-623d-11e7-8640-1c00dcf5f9b9.png)

And - observe that this second build for the first project is executed BEFORE the first build for the 2nd project:
![screenshot from 2017-07-06 11-20-40](https://user-images.githubusercontent.com/642621/27918718-c851f38c-623d-11e7-888f-a0b28d821050.png)

**Comment by ldimaggi** [comment]
Originally logged here:
https://github.com/fabric8-ui/fabric8-ui/issues/1642

**Comment by joshuawilson** [comment]
why duplicate it?

**Comment by maxandersen** [comment]
@joshuawilson do you believe this issue is for fabric8-ui ? It looks to be some backend/cross cutting issue thus does it not make more sense to have it here where CD team will see it more easily ?

**Comment by rawlingsj** [comment]
I think this is an issue with the jenkins multi branch plugin.  When a github org scan is triggered it uses config to say which branches to auto trigger, we say `master|PR.*` but if the job already exists then we'd want the multi branch plugin to NOT auto trigger the existing master + PR jobs.

That's my guess without having looked into it yet. @sathishvj did you want to see if you can reproduce using the steps above and see if you can track down if indeed https://github.com/jenkinsci/workflow-multibranch-plugin that needs to only auto trigger NEW jobs?

**Comment by sathishvj** [comment]
yes @rawlingsj let me try it out.  just am trying to figure it out.  thanks for the lead.

**Comment by rawlingsj** [comment]
great @sathishvj

**Comment by rawlingsj** [comment]
BTW @joshuawilson I agree with @maxandersen this is not a ui issue and most folks are tracking this repo for general openshift.io issues not fabric8-ui.  Issues raised there are easily missed by anyone not working directly on fabric8-ui.

**Comment by maxandersen** [comment]
> I think this is an issue with the jenkins multi branch plugin. When a github org scan is triggered it uses config to say which branches to auto trigger, we say master|PR.* but if the job already exists then we'd want the multi branch plugin to NOT auto trigger the existing master + PR jobs.

This makes sense and was similar to my guess on the fault here - but is this is recent change or has it just always been like this but noone noticed it  ?

**Comment by joshuawilson** [comment]
@rawlingsj I agree.

**Comment by rupalibehera** [comment]
@rawlingsj, you are correct whenever new pipeline triggers the  "GitHub Branch Source Plugin"  checks "Repository name pattern" which includes the name of all spaces we create. and then "Branch Api Plugin" is ".*". In the scan logs I found that it is checking for 'Jenkinsfile' and 'Master Branch' for all the spaces and hence triggers the build for all the existing jobs too.

**Comment by rawlingsj** [comment]
This was fixed with this commit https://github.com/fabric8io/jenkins-sync-plugin/commit/1eeaed5c6dd1f87a622a39fcfeaeacd610d466dc
