### ISSUE TITLE
Planner - not listing all the fundamentals under an iteration

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#3600]
Planner does not list all the fundamentals for a selected iteration.

1. Select Scenarios
2. Filter by `Area Analytics`
3. See Fundamental 2097 listed.
4. Quick view to see Fundamental belongs to `Iteration Iris`
5. Select Iteration Iris
6. Filter by `Area Analytics`
7. Fundamental `2097` is not listed even the iteration is set correctly to `Iris`

See below snapshots

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/17736013/40341941-8847baec-5da5-11e8-9a08-146c3c7ba8a3.png">

 
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/17736013/40342014-034227d2-5da6-11e8-880f-8d1e348a218d.png">

**Comment by joshuawilson** [comment]
@qodfathr this is exactly the problem I had. The current layout makes the user think the iteration is a filter that can be applied to all levels.

@miteshvp currently the iteration only displays Features, Tasks, and Bugs. Adding the iteration to the Experience has no value. I agree with you, it should be enough to appear there so we can plan the next train by putting the Experience, without any children, into the Iteration (that is just my opinion and how I would use it). @qodfathr suggested adding Iteration to the filter and @nimishamukherjee and @michaelkleinhenz are aware of that.

**Comment by miteshvp** [comment]
@joshuawilson - thanks for the explanation

**Comment by michaelkleinhenz** [comment]
@miteshvp Yes, as @joshuawilson said, the Iteration tree is considered "Execution Level" and only shows Features, Tasks and Bugs. Refer to the type level diagram to see how the levels are structured: https://docs.google.com/presentation/d/1t-WQvqrIlOjW6qTzpFFkzGtwgjQU72ex4uOiiJB9sUM/edit#slide=id.g2c696f2514_0_14

**Comment by nimishamukherjee** [comment]
Closing this as we do not have the SDD template.
