### ISSUE TITLE
Evaluate Drone for build.next

### ISSUE THREAD

**Issue by hrishin** [openshiftio/openshift.io#3603]
[Drone](http://drone.io) from #3570

**Comment by joshuawilson** [comment]
Please add labels.

**Comment by pradeepto** [comment]
@kishansagathiya Did you say yesterday that you wanna have a stab at this?

@jaseemabid Do you have any findings to report?

**Comment by kishansagathiya** [comment]
@pradeepto Yes, but first I have to spend more time evaluating spinnaker as asked by @krishnapaparaju

**Comment by sthaha** [comment]
Closing as there isn't any support for openshift
