### ISSUE TITLE
Iteration issue if the iteration name is long

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3613]
2 issues:

- Iteration breaks in side panel if name is long
- Iteration column in data table breaks

![screenshot from 2018-05-23 11-40-13](https://user-images.githubusercontent.com/34271052/40406411-31c535a8-5e7e-11e8-9f16-fc37e1f16e60.png)

**Comment by joshuawilson** [comment]
please add a `severity` label
