### ISSUE TITLE
Add workItem input field should be disabled for non collaborator

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3615]

**Comment by joshuawilson** [comment]
please add a `severity` label

**Comment by nimishamukherjee** [comment]
@Raunak1203 can you please add the current behaviour?

**Comment by Raunak1203** [comment]
@nimishamukherjee we are getting error while adding workitem ,"Problem adding work item." 
![add](https://user-images.githubusercontent.com/34271052/41581117-144fd7f6-73bb-11e8-85fc-d06893f131b1.gif)

**Comment by Raunak1203** [comment]
@nimishamukherjee should we disable workitem input field? because in openshift.io space non-collaborator can create a work item.

**Comment by divyanshiGupta** [comment]
@nimishamukherjee do we disable the input field for non-collaborators because as @Raunak1203 mentioned in openshift.io space non-collaborators can create work-items.
