### ISSUE TITLE
Should non collaborator be able to link a workitem ?

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3616]

**Comment by joshuawilson** [comment]
please add a `type` label

**Comment by serenamarie125** [comment]
This again is a larger question around permissions which needs to be addressed at a higher level.

**Comment by serenamarie125** [comment]
Based on a conversation held on 2019-Jan-04 including Dev, PM and UX, the UX team will not be providing support for planner items. Removing the team/ux label and un-assigning UX folks. If priorities are changed in the future, please add the team/ux label

**Comment by joshuawilson** [comment]
I'm going to say that no, they should not do this. I wouldn't want an unapproved person changing what is the parent or child of a work item. 

Since this can't be done, I'm closing this.
