### ISSUE TITLE
Evaluate Spinnaker for build.next

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#3617]
https://www.spinnaker.io/

Sub issue of https://github.com/openshiftio/openshift.io/issues/3570

**Comment by kishansagathiya** [comment]
Since Spinnaker requires cluster root access, I am trying to install it on minikube. Minikube gives up in some time (i.e., stops working). I get something like this every once in a while, so that makes it really difficult to test
```
spinnaker@694f566ca6e1:/workdir$ kubectl get pods
Error from server (ServerTimeout): the server cannot complete the requested operation at this time, try again later (get pods)
spinnaker@694f566ca6e1:/workdir$ kubectl get pods
Unable to connect to the server: dial tcp 192.168.42.151:8443: getsockopt: no route to host
```

So everytime this happens, I restart minikube. But deploying spinnaker still fails
```
spinnaker@694f566ca6e1:/workdir$ hal deploy apply
+ Get current deployment
  Success
+ Prep deployment
  Success
Problems in default.provider.kubernetes.my-k8s-account:
- WARNING You have not specified a Kubernetes context in your
  halconfig, Spinnaker will use "minikube" instead.
? We recommend explicitly setting a context in your halconfig, to
  ensure changes to your kubeconfig won't break your deployment.
? Options include: 
  - /192-168-42-132:8443/admin
  - /192-168-42-132:8443/developer
  - minikube
  - minishift
  - myproject/192-168-42-132:8443/developer
  - myproject/192-168-42-132:8443/system:admin

Problems in default.security:
- WARNING Your UI or API domain does not have override base URLs
  set even though your Spinnaker deployment is a Distributed deployment on a
  remote cloud provider. As a result, you will need to open SSH tunnels against
  that deployment to access Spinnaker.
? We recommend that you instead configure an authentication
  mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker
  securely, and then register the intended Domain and IP addresses that your
  publicly facing services will be using.

+ Preparation complete... deploying Spinnaker
+ Get current deployment
  Success
- Apply deployment
  Failure
Problems in Global:
! ERROR Unexpected exception:
  io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for
  kind: [Service]  with name: [spin-redis-bootstrap]  in namespace: [spinnaker] 
  failed.

- Failed to deploy Spinnaker.
````

**Comment by kishansagathiya** [comment]
To give an idea of how much work should be required for Spinnaker to work well on OpenShift checkout https://github.com/spinnaker/clouddriver/pulls?q=is%3Apr+author%3Alwander+is%3Aclosed
See all the PRs starting with fix(provider/kubernetes)

**Comment by kishansagathiya** [comment]
So far I don't find Spinnaker to be the right tool for us. So I am going to stop evaluating this with following reasons
- Spinnaker is not sufficient for us since it only does Continous Delivery and does not have code check in and Continous Integration. Refer https://medium.com/netflix-techblog/global-continuous-delivery-with-spinnaker-2a6896c23ba7
- Since it is written for Kubernetes and doesn't have OpenShift support, it would require cluster root access to run. Refer this mattermost chat with @aslakknutsen https://chat.openshift.io/developers/pl/jhxdjtfhmtfmpbwic6snu37puc
- To make Spinnaker run smoothly, we would have to contribute a lot to their clouddriver repo. To get an idea of work take a look at https://github.com/spinnaker/clouddriver/pulls?q=is%3Apr+author%3Alwander+is%3Aclosed. All the PRs starting with fix(provider/kubernetes) are added for kubernetes. The project has similar PRs for aws, gcloud etc.
- The company strategy might be against Spinnaker. Refer https://www.reddit.com/r/devops/comments/8hiwxi/spinnaker_equivalent_for_openshift/dykeomn/
 We also have zuul which is trying to solve some of the similar problems https://techcrunch.com/2018/05/21/openstack-spins-out-its-zuul-open-source-ci-cd-platform/
- It seems to me that if we are to use Spinnaker, we would need to partner with Spinnaker folks somehow.

**Comment by pradeepto** [comment]
@kishansagathiya If this is done, can you move close this and move it to done?

**Comment by kishansagathiya** [comment]
As asked by @krishnapaparaju on 13 June's standup, I will be evaluating this more.

**Comment by kishansagathiya** [comment]
From what I have read (https://www.spinnaker.io/ebook/ContinuousDeliveryWithSpinnaker.pdf, https://thenewstack.io/ci-cd-with-kubernetes-ebook-free-download-on-the-new-stack/), it is meant for individual companies to do their deployments. 
Spinnaker does not have an end to end CICD System. If anyone were to use Spinnaker, they will have to use something like Jenkins or TravisCI for CI(https://stackoverflow.com/questions/37936967/compare-spinnaker-with-jenkins-2-0-as-a-continuous-delivery-tool). The CI tool that best fits with Spinnaker is Jenkins. Spinnaker was developed with Jenkins as CI in mind (The company that build Spinnaker, uses Jenkins for all their builds). 
For these and all above reasons(https://github.com/openshiftio/openshift.io/issues/3617#issuecomment-393780683), I don't think Spinnaker is the right tool for us and we should end this investigation here.

**Comment by kishansagathiya** [comment]
https://chat.openshift.io/developers/pl/nd1snhhfzf8nzjk73byj1bzdae

**Comment by lordofthejars** [comment]
@sthaha can we close this issue? I guess that for now and in middle term we are going to be stick to Jenkins, so maybe in the future, if we want to change/investigate another thing we could open a new issue or reopen this one.
