### ISSUE TITLE
List View for Work Items in Planner (without Parent) [13]

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#362]
# Description
As a user, I want to view query results of Work Items in a list view that enables me to browse the resulting Work Items, open views on specific items and letting me update items in a meaningful way.

# Acceptance Criteria
- [ ] The user can switch to a list view of the current context. See the Context Views story for details on the context.
- [ ] The list view displays the Work Items in the context in a list form using entries.
- [ ] The displayed list contains all matching Work Items of the selected criteria with only the matching items of the highest order. For example if A has two children B and C and A, B and C are matching the criteria, only A is returned. B and C can be explored by exploration. Items without parent are also considered "highest order".
- [ ] Each entry can be explored (is expandable) with a normal exploration that shows all childs regardless of an applied criteria.
- [ ] Each entry has meaningful attribute views that identifies the Work Item represented by the entry. This is not changed from the current implementation.
- [ ] The user can open the quick preview view from an entry.
- [ ] The user can open the detail view from an entry.
- [ ] The user can delete a Work Item from an entry.
- [ ] The user can select an entry, setting the context for the quick add (see details on the context in connection to the quick add in the quick add story).
- [ ] Entries are sorted by order-of-execution by default, but only in the context of the expansion level. For example, all items on root level are sorted, then all childrens of an entry are sorted locally only.
- [ ] Entries can be reordered by drag-and-drop, changing the order of execution. This also applies to expanded child lists. Reordering is only allowed in the context of the expansion level.

**Note**: This story does not describe the final feature set of the list view. As the list view is one of the central views in the Planner, this will evolve over time. The current story is the feature set we can provide in the first step of that journey.

**Note**: This story describes the "no parent view". There is also a "with parents" view (story #325).
 
**Note**: This story explicitly does not describe multi-selects and bulk operation. There will be a seperate story on this.

**Note**: This story does not touch the attributes displayed on an entry. This will be unchanged from the current implementation. There will be a seperate story on a more dynamic approach on this later.

# Relationships
_Put linked Team/Product story links here_

**Comment by michaelkleinhenz** [comment]
![2017-07-12 14 31 21](https://user-images.githubusercontent.com/7101098/28133737-f0b4e3cc-670e-11e7-9f5d-ad4ca635cb0f.jpg)

**Comment by maxandersen** [comment]
> Entries can be reordered by drag-and-drop, changing the order of execution. This also applies to expanded child lists.

if it is a flat list how can is have nested/expanded child lists ? and how are expanded child lists shown if things are ordered by order of execution ? children don't by definition adhere to the parents order of execution.

**Comment by maxandersen** [comment]
> See the Context Views story for details on the context.

got a link ? :)

**Comment by ldimaggi** [comment]
Followup question:

Will the totals value shown reflect the total number of top level workitems only? Or a total of top level + lower level workitems? (I think that the total should only reflect the total of the top level workitems.)  Thx!

**Comment by sdash-redhat** [comment]
Refer Interaction Design notes 
slide 22 -> 26 - https://redhat.invisionapp.com/share/6RCWHA1TX

Visual Design Notes: 
https://redhat.invisionapp.com/share/HTCX31SWC
(VD work in progress)

Note: the text, data points were shown are for reference purpose to illustrate the interaction, based on actual data points there may be changes on how the screen might appear in real time post implementation.

**Comment by sdash-redhat** [comment]
Listing some of UX Questions: 
Please elaborate - "Each entry has meaningful attribute views that identifies the Work Item represented by the entry. This is not changed from the current implementation."

What are the attributes that can be showed for each entry ? Do we have the list of attributes available for an entry?

As the implementation will be actually a list ..can we show column lines (using background image etc. )? 

Can we provide inline edit for any entry related attributes in the list ?

**Comment by michaelkleinhenz** [comment]
Obsoleted by story #325.
