### ISSUE TITLE
Add collaborator dropdown shows Nothing found before any search

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3622]
![screenshot from 2018-05-23 14-40-49](https://user-images.githubusercontent.com/34271052/40414948-4d8bf268-5e97-11e8-96a9-f45ad46b3ebe.png)

**Comment by aptmac** [comment]
For context, the multiselect-dropdown that we're using is displaying "Nothing Found ..." because it's the default text [1] when there the search returns an empty result. If you scroll, you can see the full message.

![nothing-found](https://user-images.githubusercontent.com/10425301/40624015-14e3260e-6278-11e8-9cce-a3843350423a.png)

[0] https://github.com/softsimon/angular-2-dropdown-multiselect
[1] https://github.com/softsimon/angular-2-dropdown-multiselect/blob/485a0dfb1b54ddce1e7c88c461c15ddaae6f3977/src/dropdown/dropdown.component.ts#L157

**Comment by joshuawilson** [comment]
@openshiftio/uxd-team do you have any guidance here? I'm not sure we want to show everyone. We currently have 11K users. I guess we could page it and show the first 25.

**Comment by mindreeper2420** [comment]
IMO, no users should be shown, outside of those that are either part of a team attached to the Space (not possible now), or are not collaborators on an issue in the Space (also not possible now).

For the time being, I would show just a search bar with informative text on what to do, and then only show a filtered list once the user enters a certain number of characters (2-3). This would cut down on the amount of users that would need to be shown, thus cutting down on resource requirements.

**Comment by sdash-redhat** [comment]
I somewhat agree with the direction of  @mindreeper2420 

Here is a quick initial thoughts/representation that might be a temporary approach inline with the above... with some improvements I believe (like showing some search results loading icons etc.) 
In long term, I think for such scenarios where the source list is too big or we do not want to show the whole list, and similar reasons, use of a selection widget pattern (where user can select items from an available column and then add them to selected column/bucket ) might be a potential candidate for exploration.  

![3622](https://user-images.githubusercontent.com/27761023/41087596-bc73f44a-6a5a-11e8-8f1b-406ffdf0f10f.png)

@muruGanesan @catrobson

**Comment by muruGanesan** [comment]
@sdash-redhat, please check with development team i.e. are they going to develop "Teams"  if yes, then we may we propose 'Teams'... or propose something similar to "teams flow"

**Comment by sdash-redhat** [comment]
@muruGanesan makes sense... will check.

**Comment by joshuawilson** [comment]
The Auth team will most likely be developing `Teams` but I don't expect them to start until J train. 
cc @alexeykazakov

**Comment by sdash-redhat** [comment]
Thanks, @joshuawilson  ..this is helpful. 
@muruGanesan , I think as Adam suggested we can go with a temporary fix till the team is implemented. Any thoughts?

**Comment by alexeykazakov** [comment]
The collaborators page will go away as soon as we implement permissions/roles page in UI. The UI part is planned for J train. So, it doesn't make much sense to spend a lot of time on improving the current collaborators overall UX. But we will need to use very similar dropdown dialog for searching users in the new UI too. And @rohitkrai03 is working on finding a better component for that.

We still can do minor changes in the current UI as temporal solution until we switch to the new UI.

**Comment by muruGanesan** [comment]
thanks, @alexeykazakov.
