### ISSUE TITLE
Cannot resolve rh-ngx-datatable after recent f8-planner update

### ISSUE THREAD

**Issue by aptmac** [openshiftio/openshift.io#3623]
As noted in the comments of a recent f8-ui [PR](https://github.com/fabric8-ui/fabric8-ui/pull/2932) [0] to update the planner version, the f8-ui build now fails when trying to find the rh-ngx-datatable, possibly from the updated dependency that was introduced in a recent planner [commit](https://github.com/fabric8-ui/fabric8-planner/commit/0ac13013bcd9419c6c4d82a503808e845f42f0d1) [1].

`ERROR in ./node_modules/fabric8-planner/app/components/planner-list/planner-list.module.js
Module not found: Error: Can't resolve 'rh-ngx-datatable'`

[0] https://github.com/fabric8-ui/fabric8-ui/pull/2932
[1] https://github.com/fabric8-ui/fabric8-planner/commit/0ac13013bcd9419c6c4d82a503808e845f42f0d1

**Comment by joshuawilson** [comment]
My best guess at this point is that the main repo being used https://github.com/sahil143/ngx-datatable is at version 12.0.11 and the npm release included is at 12.0.16. The mis-match is causing some kind of disconnect in the build. 

Currently version 12.0.19 is in npm. I suggest that @sahil143 update the version in the package.json and release again, ensuring they match.

cc @nimishamukherjee @michaelkleinhenz @sanbornsen

**Comment by jiekang** [comment]
The update introducing this was reverted via https://github.com/fabric8-ui/fabric8-ui/pull/2937

If the responsible parties are tracking this elsewhere, I recommend this issue be closed. Thoughts?

**Comment by joshuawilson** [comment]
I'm good with closing it.
