### ISSUE TITLE
Get Applications api is giving status `500` in PROD

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#3626]
This api is failing in prod  :-

```
https://api.openshift.io/api/deployments/spaces/f26b63b7-de83-4c16-bd4e-e375ca573fbc
```

**Response**
```
{"errors":[{"code":"unknown_error","detail":"configmaps \"fabric8-environments\" not found","status":"500","title":"Unknown error"}]}
```

**Comment by jyasveer** [comment]
@joshuawilson

**Comment by joshuawilson** [comment]
@jyasveer how do you reproduce this?

@andrewazores @jiekang please look into this.

**Comment by jyasveer** [comment]
@joshuawilson I get this whenever i go to any space dashboard ?
As well as when i go to the `Create app overlay screen` in Getting Started flow

**Comment by andrewazores** [comment]
I can't reproduce this, everything looks OK to me on prod.

Anyway, this looks the same as this older bug: https://github.com/openshiftio/openshift.io/issues/3556

**Comment by jyasveer** [comment]
> Anyway, this looks the same as this older bug: #3556
looks like it

**Comment by ebaron** [comment]
@jyasveer If you still get this error, could you check whether the config map exists in your user namespace? (i.e. _username_ without -che, -jenkins, -run, etc.) 

You can check this in either the OpenShift web console, or by using `oc`:
```
$ oc get configmap/fabric8-environments
```
