### ISSUE TITLE
Should space owner be able to delete comment of non collaborator?

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3628]

**Comment by serenamarie125** [comment]
This is a larger question around permissions in general.

**Comment by serenamarie125** [comment]
Based on a conversation held on 2019-Jan-04 including Dev, PM and UX, the UX team will not be providing support for planner items. Removing the team/ux label and un-assigning UX folks. If priorities are changed in the future, please add the team/ux label

**Comment by joshuawilson** [comment]
closing as this will not be answered
