### ISSUE TITLE
[8]Clean up legacy launcher code and new launcher flow should be default

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#3629]
**PLANNER LINK** :- https://openshift.io/openshiftio/openshiftio/plan/detail/2447

#### User Story: 

As an OSIO Developer, I will be able to clean up legacy launcher code and new launcher flow should be default i.e not under feature flags.

#### Description:
In `OSIO` we are having the legacy launcher as default flow and new launcher in production feature via toggle service. We need to clean up legacy launcher code and new launcher flow should be default i.e not under toggle service.

**Acceptance:**
- Clean up legacy launcher code
- New launcher flow should be default i.e not under feature flags.

**Comment by invincibleJai** [comment]
This story should take care of below

* https://github.com/openshiftio/openshift.io/issues/3576 
* https://github.com/openshiftio/openshift.io/issues/3489

**Comment by ppitonak** [comment]
When is this issue planned to be resolved?

**Comment by jyasveer** [comment]
@aptmac i am re-assigning to myself as it is on the critical path.

**Comment by GeorgeActon** [comment]
@jyasveer this needs link to the feature in planner

**Comment by aptmac** [comment]
@jyasveer sounds good, let me know if there's anything I can do to help. I had opened a PR [0] on Friday that ripped out the instances of the old launcher & app import slider if you want to take a look at it or incorporate it into your planning.

[0] https://github.com/fabric8-ui/fabric8-ui/pull/2980

**Comment by jyasveer** [comment]
thanks @aptmac for the PR reference. i will have a look

**Comment by animuk** [comment]
@GeorgeActon We already have link feature : https://openshift.io/openshiftio/openshiftio/plan/detail/2447

**Comment by jyasveer** [comment]
This is available in prod-preview now. We have to wait until it is available in prod
