### ISSUE TITLE
Not able to open list of Tasks in the Board

### ISSUE THREAD

**Issue by dharmit** [openshiftio/openshift.io#363]
This was working till yesterday but today, under the "Board" view, when I click on the "Currently Showing" dropdown, it doesn't work. It shows the "Bugs" and I'd like to switch to "Tasks". But that ain't working. 

As a workaround, I switched to the "Backlog" view to get a view of all the cards so that I can access ones I'm working on.

**Comment by aslakknutsen** [comment]
Possible broke with release bbf4418379c9060a40b18bcaa284fadc75759e9c

**Comment by aslakknutsen** [comment]
fixed by https://github.com/fabric8-ui/fabric8-ui/pull/1728 ? Not in prod yet

**Comment by maxandersen** [comment]
this seem to affect all kind of dropdown boxes thus putting on kill list as blocker.

@mindreeper2420 do you have an ETA ?

**Comment by mindreeper2420** [comment]
@maxandersen it is fixed in PR https://github.com/fabric8-ui/fabric8-ui/pull/1728 that was merged to Master. No idea on deploy time to production.

**Comment by maxandersen** [comment]
this have been pushed and verified to work in prod.
