### ISSUE TITLE
Empty row in Scrum template on clicking Add child work item

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3630]
Steps:

- Select workitem group(say, Features) in scrum template
- Click to Add child workitem
-First row is Empty
![screenshot from 2018-05-24 11-59-16](https://user-images.githubusercontent.com/34271052/40468822-249d7b50-5f4c-11e8-9d93-b4ff4615d398.png)

**Comment by nimishamukherjee** [comment]
@Raunak1203 do you still face this issue? If yes, please list the steps and browser details.

**Comment by Raunak1203** [comment]
The issue is not reproducible.
