### ISSUE TITLE
"View All Spaces" list cannot be reset

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#3631]
# Bug / Question

When initially visiting the "View all spaces" view via the top-left dropdown menu > "View all spaces", (ie. `/username/_spaces`), the list displays the names of all spaces owned by the username in the path. After the user enters some search text, the list changes to displaying spaces matching the search text, owned by any user. After clearing the search text, the list now displays paginated results of what appears to be all spaces, in no obvious order. This flow doesn't seem to make sense - if the list initially shows one specific user's spaces, why does the search operate over all spaces, not just those displayed? If the initial search term is empty and this displays one user's spaces, why does setting and clearing the search term not reset the list to the same state?

**Comment by mindreeper2420** [comment]
@catrobson can we add this to the overall navigation/IA work that is being done?

**Comment by jiekang** [comment]
From https://github.com/openshiftio/openshift.io/issues/3536#issuecomment-390823742 it sounds like once the page that list spaces has a search feature, this 'View all Spaces' can be removed.

Are there other outstanding requirements, if any blocking this removal? I wouldn't mind submitting the PR that removes this page.

**Comment by aptmac** [comment]
The "View All Spaces" page was removed in: https://github.com/fabric8-ui/fabric8-ui/pull/3374
