### ISSUE TITLE
Remove screenshots from new updates banner

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#3633]
I'd like to discuss the current design decision for the new feature banner. As it stands, we are including screenshots of the features along with a textual description and a link to the feature itself. Examples of this are :

![image](https://user-images.githubusercontent.com/17230733/40504196-9c575a46-5f5e-11e8-88c6-8e6f89cbf796.png)

![image](https://user-images.githubusercontent.com/17230733/40504190-96840d80-5f5e-11e8-825b-e6b4aaf9637e.png)

I personally find these screenshots hard to read given how small they are, so I would be tempted to remove them. I know its only anecdotal, but I'm used to simply clicking the link to see the feature and would personally be ok with that if we did it here. Could someone please clarify why the design was made to include screenshots ? 

@mindreeper2420 @catrobson

**Comment by mindreeper2420** [comment]
@chrislessard from your screenshots, it appears that you are also using a viewport size that is smaller than 1000px wide. Due to that, you are also not seeing the description of what the feature actually is. Would that make the screenshot more informative in any way?

**Comment by mindreeper2420** [comment]
@mceledonia Do you want to keep the screenshots and make them larger/more prominent, or remove them? I'm also open to other ideas but, as you were the original designer of this, I wanted to make you aware of this instance.

**Comment by chrislessard** [comment]
@mindreeper2420 Yes that would certainly help ! Otherwise I feel as though I'm left guessing. I didn't realise that I was seeing that particular viewport, thanks for catching that.

**Comment by stacymcauliffe** [comment]
Presented some ideas for how we might minimize this banner and make better use of this space:
https://redhat.invisionapp.com/share/X4N6UEVJKWA#/310993205_Desktop

Comments from the team so far - 
Does this conflict with the experimental features button? 
Would use of a modeless overlay for this conflict with other ways we use it in the UI? (yes) 
How would this work with the getting started experience proposed by Veethika?

Michael's original wires for reference: https://redhat.invisionapp.com/share/VWGIFFNE69G#/screens/285593826

**Comment by serenamarie125** [comment]
@stacymcauliffe are you still working on this issue?  Can you provide an update?  Thanks!

**Comment by stacymcauliffe** [comment]
@serenamarie125 - yes sorry! Got wrapped up in work for another project, but I'll pick this back up this week. Thanks

**Comment by serenamarie125** [comment]
@serenamarie125 to create a new Issue to capture "How do we introduce a new feature", and then close this issue.

**Comment by joshuawilson** [comment]
Is this even still in the header? I can't find it.

**Comment by aptmac** [comment]
It was removed in https://github.com/fabric8-ui/fabric8-ui/pull/3361
