### ISSUE TITLE
Features should not be available when visiting another user's profile

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#3635]
If you visit another user's space under /<username> (for example /jiekang@redhat.com), you are presented with a link allowing you to "Add a url" to the profile. This causes a console error, with no discernible effect in the UI to make the user aware of the failure. Foreign user's should not be able to even attempt this.

Screenshot :

<img width="1440" alt="screen shot 2018-05-24 at 3 18 00 pm" src="https://user-images.githubusercontent.com/17230733/40507814-dca581b6-5f65-11e8-8e4d-3d63ce1064f6.png">

Parent: https://github.com/openshiftio/openshift.io/issues/3638

**Comment by rohitkrai03** [comment]
@chrislessard This issue was solved with https://github.com/fabric8-ui/fabric8-ui/pull/2777. Closing it.
