### ISSUE TITLE
Deep link to plan/board does not show any data

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#364]
https://openshift.io/openshiftio/openshiftio/plan/board

Changing iteration etc does not work at this point. Going to Backlog and then back to Board works.

**Comment by joshuawilson** [comment]
@michaelkleinhenz do you want this moved to fabric8-planner or will you track it here?

**Comment by michaelkleinhenz** [comment]
Not reproducible. Looks like outdated. Works now.
