### ISSUE TITLE
Searching the Label is case sensitive

### ISSUE THREAD

**Issue by sivaavkd** [openshiftio/openshift.io#3640]
When creating a new Planner item, do the following in openshiftio space:
1.  Click on Assign Labels
2.  In the seach box, type "ana" - no search results
3.  Now, type "Ana" - you will find "Analytics"

This is taking additional time to remove "ana" and type "Ana".. why the label is case sensitive ?  It should not be.

**Comment by vikram-raj** [comment]
This issue has been fixed.
