### ISSUE TITLE
Planner Item # 2173 description went missing

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#3641]
Created a Fundamental with Planner ID 2173. Created with all the description necessary. 
Description was modified as necessary. But when I checked yesterday, all the description went missing. Is there a way to get those description back? Is it even possible to get an audit trail of who modified the line item last? Because ir-respective of who modifies a line item, by default the email says Modified by `<creator-name>` . Also, email trail does not take into account all the changes made e.g. it does not list say the contents(description) of the item in an email notification.

**Comment by nimishamukherjee** [comment]
@miteshvp we are working on introducing audit trail this sprint - https://openshift.io/openshiftio/openshiftio/plan/detail/1915

**Comment by nimishamukherjee** [comment]
- Removing sev2 as this is a one of case and not reproducible.
- Removing bug as audit trail is a feature request

**Comment by nimishamukherjee** [comment]
Closing this issue as it is not reproducible.
