### ISSUE TITLE
Cannot remove all spaces with one click

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3648]
1. create multiple spaces
2. go to "My spaces" page
3. delete all spaces

result:
* it's possible to only delete a single space at the time which is annoying, let the user delete more than one space

![osio_remove_all_spaces](https://user-images.githubusercontent.com/445100/40541413-f50cfeee-601b-11e8-9a11-4f9f34fa239b.png)

**Comment by chrislessard** [comment]
Potentially related to https://github.com/openshiftio/openshift.io/issues/2097, which still needs to go through design and PM.

**Comment by ppitonak** [comment]
Yes, it's a duplicate of #2097, closing.
