### ISSUE TITLE
New app creation in launcher - syntax error for title displayed

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3649]
Steps to recreate:
* Login to https://openshift.io
* Create a new space
* Start to create a new app/quickstart
* Observe that as user starts to enter app name, a syntax error is displayed - observe that the error message remains visible even if a name is entered using valid sytnax:
![screenshot from 2018-05-25 07-24-31](https://user-images.githubusercontent.com/642621/40542135-d361053a-5fec-11e8-9ec8-e43dff235a83.png)

Note - this seems to happen only for the first time (after login) that a new space is created.

**Comment by pmacik** [comment]
Probably related: https://github.com/openshiftio/openshift.io/issues/3227

**Comment by ldimaggi** [comment]
Closing as no longer reproducible - maybe related to:  https://github.com/openshiftio/openshift.io/issues/3639

**Comment by ldimaggi** [comment]
Seeing it again in production. Reopening.

**Comment by ldimaggi** [comment]
Fixed in production - closing.
