### ISSUE TITLE
Cancel button in new app wizard fails after user resets env

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3657]
Steps to recreate:
* Log in to https://openshift.io
* Reset user env
* Create a new space
* After the space is created. the user is placed on the 'Create an Application' page:
![screenshot from 2018-05-25 11-17-40](https://user-images.githubusercontent.com/642621/40552316-536500e0-600d-11e8-8a98-15e4594733c1.png)

![myimage](https://user-images.githubusercontent.com/642621/40552615-418911b2-600e-11e8-9528-4103b691f99d.gif)

* Attempt to exit this page by clicking on the cancel ("x") button - the button fails to respond, no error is written to the browser console.log, and the user is left ont he 'Create an Application' page. 
* In order to leave this page, the user must directly edit the URL displayed in the browser

**Comment by ldimaggi** [comment]
This bug is causing E2E test failures as the setup for the tests creates a space, then attempts to exit the launcher, before creating a quickstart.

**Comment by joshuawilson** [comment]
might be related to #3589

**Comment by ldimaggi** [comment]
Related to #3658

**Comment by jyasveer** [comment]
@ldimaggi this is fixed now in prod-preview. once the prod is updated, you can see the same in prod

**Comment by aptmac** [comment]
fixed in https://github.com/fabric8-ui/fabric8-ui/pull/2945

**Comment by ldimaggi** [comment]
Closing - verified fixed in production.
