### ISSUE TITLE
Deployments API for user requesting info for space that they do not own is inconsistent

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#3660]
When visiting another users space and deployments page:

`https://api.openshift.io/api/deployments/spaces/<spaceId>`
If a user makes a request for deployments info for a space they do not own, the request comes back as 200 OK with an empty response.

`https://api.openshift.io/api/deployments/spaces/<spaceId>/environments`
If a user makes a request for environments info for a space they do not own, the request comes back as 200 OK with the response for my own environment usage.

I'm guessing somewhere in the server-side, there is an unauthorized access attempt leading to the empty response for deployments API. I think for most APIs the current behavior of GET requests is to not authorize protected. Other users should be able to see it. I'm not sure if that applies here, but regardless the responses should be consistent. Either 401 for both, or 200 with the correct information for both.

**Comment by jiekang** [comment]
@ebaron @stooke Could you guys take a look at this?

**Comment by andrewazores** [comment]
It seems that when I view another user's space, the Environments data I receive is actually data about my own Environments - this makes sense, although the UI doesn't necessarily reflect it well, and the `spaceId` request parameter is unused/confusing.

**Comment by jiekang** [comment]
Ah right, the spaceId is unused for the environments. Good catch.

**Comment by ebaron** [comment]
For the space data, we translate the space ID into space name using the WIT API, and then search for deployments matching that space name in the user's (specified by bearer token) OpenShift namespaces. We could query the WIT API further to determine if the user has appropriate permissions for the space.

We probably do not want to return a 401 though, we had trouble with that before where it logged the user out.

**Comment by jiekang** [comment]
Right... Another fix would be on the UX side to not make the request if we're in a space that isn't owned by the user but I'm not sure that's a great idea. 

Either way I think we should show different content in this situation. Something for the UX team I suppose.

**Comment by andrewazores** [comment]
re 401 handling: https://github.com/openshiftio/openshift.io/issues/3325

**Comment by alexeykazakov** [comment]
Outdated.
