### ISSUE TITLE
Resolution field in the Scrum template has 'Default Header Text' and is not aligned correctly

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#3664]
![screenshot from 2018-05-29 14-23-37](https://user-images.githubusercontent.com/16647625/40648657-97b903bc-634c-11e8-99a6-c12c89d1f967.png)
The header should say 'Update Resolution' this applies to the Severity field too.

**Comment by nimishamukherjee** [comment]
Issue fixed.
![header](https://user-images.githubusercontent.com/1892722/48856377-399d5380-eddc-11e8-8089-af60ec164070.png)
