### ISSUE TITLE
"Features Opt-in" tab shows 0 features

### ISSUE THREAD

**Issue by rkratky** [openshiftio/openshift.io#3665]
All the categories on the **Features Opt-in** tab in personal **Settings** show "0 features", incl. **Production-Only Features**.

![osio-features](https://user-images.githubusercontent.com/6623103/40652427-84fc14d0-6338-11e8-9346-d27aac67a216.png)

**Comment by andrewazores** [comment]
@joshuawilson @corinnekrych

**Comment by aptmac** [comment]
The current response I'm seeing from the unleash server is `{"data":[]}`

The relevant lines of code here are in the [feature opt in](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/settings/feature-opt-in/feature-opt-in.component.ts#L139) where the [service](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/feature-flag/service/feature-toggles.service.ts#L123) is called to retrieve the features by level.

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/settings/feature-opt-in/feature-opt-in.component.ts#L139
[1] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/feature-flag/service/feature-toggles.service.ts#L123

**Comment by joshuawilson** [comment]
Since we know we have things at various stages, I can only assume that we are missing something in the call to unleash.

**Comment by andrewazores** [comment]
Reading back through the latest commits to the component and service, it looks like the call is being made correctly. It's going to what seems to be the correct endpoint and with the correct parameter - @corinnekrych even posted example curls that matched the same request format being made here, and receiving a correctly populated response. Maybe something changed on the backend side and the corresponding frontend update was missed?

**Comment by corinnekrych** [comment]
Indeed prod-preview is fine whereas production miss the endpoint `GetFeaturePerStrategy` in prod. Here is a PR https://github.com/openshiftio/saas-openshiftio/pull/897 to push to prod.

**Comment by joshuawilson** [comment]
I merged the PR. It should be in prod now.

**Comment by rkratky** [comment]
Works as expected.
