### ISSUE TITLE
Evaluating Flux

### ISSUE THREAD

**Issue by lordofthejars** [openshiftio/openshift.io#3667]
https://github.com/weaveworks/flux

**Comment by lordofthejars** [comment]
At the time of writing this issue, I have not been able to deploy Flux into OpenShift, it seems some security problems regarding the creation of SSH keys, but after trying several things, no luck. So it seems that Flux and OpenShift are not going to work pretty well together, but there are some features that are great:

* Git as single source of truth
* Any change in the operation means a new PR (which can be reviewed, check if works or compare the desired state vs current state)
* 1 repo = 1 service 1 branch = 1 environment/namespace so move something from staging to production implies a git merge from staging branch to master branch
* Everything happens within git, so if current service is breaking something, you only need to do a git reverse and everything is back to normal state
* Since everything is in git you have exactly in an atomic way the sequence of states of the cluster
* You've got the desired state of the cluster in git.

**Comment by lordofthejars** [comment]
After trying to run Flux, it seems that it is using one volume mapping feature that only works in kubernetes 1.10 (Openshift 3.10). Since Openshift 3.10 is not released yet, we can stop taking a look on how to run flux in Openshift.

**Comment by markottaviani** [comment]
@lordofthejars with 3.10 now GA'd are there any plans to take a fresh look at flux?

**Comment by harshajith** [comment]
Now it is already at 3.11, Flux is supported there yet?

**Comment by tl-alexandre-kaskasoli** [comment]
Flux supported yet?

**Comment by sideeffffect** [comment]
@lordofthejars OpenShift 4.1.0 is already released. would it work Flux?
