### ISSUE TITLE
The new create space wizard is not so usable

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#3668]
It is very difficult to use the new Create Space wizard. 
- The transparent background, along with the white italics texts makes strain my eyes to read the instructions
- My focus goes on the yellow box instead of creating my space
- I'm not sure where to focus on
![createspace](https://user-images.githubusercontent.com/1892722/40654545-3afcb050-635c-11e8-9247-28997233148f.png)

Also, during the create space flow, the background changes which is disturbing.
I'm on the page where the spaces are listed. I create a new space and I'm taken to the space home page.
As the wizard background is transparent, I can see the background changing.
![backgrounmovement](https://user-images.githubusercontent.com/1892722/40654832-08008162-635d-11e8-8831-bdb9eebfb46e.gif)

**Comment by aptmac** [comment]
> Also, during the create space flow, the background changes which is disturbing.

It's the page navigating to the new space that you made, so that when the app wizard opens you can directly add to your new space. IIRC the old space wizard redirected the users like this too, this would be intentional behaviour.

**Comment by joshuawilson** [comment]
cc @openshiftio/uxd-team

**Comment by mindreeper2420** [comment]
@bdellasc Do you have an existing issue that you can link this to for tracking purposes?

**Comment by bdellasc** [comment]
We're planning to create some UX-specific issues around Summit feedback. We can reference this issue as part of that. Thanks!

**Comment by aptmac** [comment]
@bdellasc is this the issue you were referring to about the summit feedback? https://github.com/openshiftio/openshift.io/issues/3704

If so, it largely concerns the create app wizard while this issue concerns the create space wizard. Was there any specific feedback that could be useful for this issue in particular?

**Comment by muruGanesan** [comment]
@nimishamukherjee, @joshuawilson,
This is addressed in #4185 and #4191.
Please review the same and close if it is addressed properly.
https://redhat.invisionapp.com/share/E7O609F8T9W#/screens/321098831

**Comment by joshuawilson** [comment]
@muruGanesan the github issues are designs and do not fix the issue listed here, they only propose a solution. They do link to items in the planner and we might close this and point to one of them. Additionally, I have commented on the design you shared.

**Comment by muruGanesan** [comment]
@joshuawilson, Thanks.
I saw your review comments in Invision, thanks again.
I believe @christianvogt has taken this issue to the planner.

**Comment by joshuawilson** [comment]
So if you want to close this then we need to link to the issue in the planner. 

Closing as this issue is being tracked at:
https://openshift.io/openshiftio/Openshift_io/plan/detail/788 
https://openshift.io/openshiftio/Openshift_io/plan/detail/785
