### ISSUE TITLE
[RFE] Option to show all items under planner board

### ISSUE THREAD

**Issue by navidshaikh** [openshiftio/openshift.io#367]
RFE for Space->Plan->Board  

(Sample URL -> https://openshift.io/bkundu%40redhat.com/CentOS_Container_Pipeline/plan/board )

If we go to `Plan` and then hit `Board` layout to check the items under given space, on top it shows 
`Currently showing:`  with a drop down. The drop down has types (Bug, Features, Task, etc) of items that can be created.
Once a board is populated with different items card, and we would like to update the cards per progress, it is tough to find the cards, we have to navigate multiple times from drop down to locate the cards.

What if we can have an item in drop down to list `All` types of cards created and we can see all the items in one go ?

Use case being, during standups, while individual updates, other folks can check progress on card / reference it.

**Comment by joshuawilson** [comment]
The problem is that the each type has different states/stages and therefor different columns. Until we can find a better way to combine the views they must remain separate.

**Comment by maxandersen** [comment]
To be clear - the current board is known to not be the right way to go. We will get  a board that shows logical list of columns and the list of "cards" will be of any mix of types.

**Comment by michaelkleinhenz** [comment]
This will be adressed in the board revamp with #330
