### ISSUE TITLE
New app creation failing on prod-preview

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3672]
Steps to recreate:
* Reset user env
* Create new space
* Create new app - observe 500/server error in browser console 

```
api.prod-preview.openshift.io/api/deployments/spaces/c3e3d814-3442-4a20-8d6b-7643c100fe66:1 
GET https://api.prod-preview.openshift.io/api/deployments/spaces/c3e3d814-3442-4a20-8d6b-7643c100fe66 500 (Internal Server Error)
_body: "{"errors":[{"code":"unknown_error","detail":"confi…found","status":"500","title":
"Unknown error"}]}↵", status: 500, ok: false, statusText: "Internal Server Error", headers: Headers, …}
```

This problem is not being seen on production.

**Comment by jiekang** [comment]
The truncated text in `"detail":"confi…found"` section is kind of awkward hahah. I wouldn't be surprised if this is related to the configmap missing issue.

**Comment by ldimaggi** [comment]
Not reproducible today on prod-preview - closing.
