### ISSUE TITLE
The space dashboard should only show information for that space.

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#368]
1. create a new quickstart on SpaceA, name it `everywhere`
2. Select the pipeline to be displayed on OSO (opehsift online)
3. On left side Actions | Edit yaml
```
metadata:
  name: everywhere
  namespace: ckrych
  selfLink: /oapi/v1/namespaces/ckrych/buildconfigs/corinnef
  uid: 03dafd98-6afe-11e7-ad51-02d7377a4b17
  resourceVersion: '261772736'
  creationTimestamp: '2017-07-17T14:41:27Z'
  labels:
    space: SpaceA
``` 
remove the label space (`space: SpaceA`)
3. Switch to SpaceB or any space

* Actual Result: 
The pipe `everywhere` is displayed on SpaceB and SpaceA or any space.

* Expected Result:
Once the pipeline`everywhere`'s BuildConfig has lost its space label, it should not be displayed in any space.

**Comment by joshuawilson** [comment]
This was moved to https://github.com/fabric8-ui/fabric8-ui/issues/1746
