### ISSUE TITLE
fabric8-ui webpack config ignores nested node_module packages

### ISSUE THREAD

**Issue by christianvogt** [openshiftio/openshift.io#3686]
The current webpack configuration is setup to resolve node_modules only at the root level in fabric8-ui. This means that when libraries that depend on another library, fabric8-ui must also ensure it has an equivalent dependency so that it gets installed at the root (unless it's the only library of that version in the install). This means that a library cannot depend a version of a library that differs in version from fabric8-ui because the one defined by fabric8-ui will be forced to be used. This may have runtime consequences such as incompatible API.

Changing the current module resolution will impact:
 - bundle size if multiple versions of libraries are defined in components and their package.json dependencies aren't specified correctly with ranges
 - `npm link` for testing downstream components within fabric8-ui

The bundle size, although important to keep small, can be addressed as we find dependency discrepancies. We should aim to ensure that we correctly use ranges for dependencies so that libraries can be shared correctly.

Linking libraries for inclusion into fabric8-ui for development must continue to work.

* [x] Create PRs for all projects to use peer dependencies
* [x] Merge all PRs that update project peer dependencies
* [ ] All projects that depend on other project(s) whose dependencies are moving to peer dependencies should update their dependency versions to point to the latest.
* [ ] Update fabric8-ui with latest versions of related projects
* [ ] Merge fabric8-ui webpack changes

**Comment by arunkumars08** [comment]
@christianvogt Sure Christian, let me check that. 
Also, one thing to note - "fabric8-analytics-dependency-editor" appears as a 2nd level dependency to "fabric8-ui".
It sits inside "ngx-forge" which in turn sits inside "fabric8-ui".

**Comment by arunkumars08** [comment]
Sorry, accidentally closed the issue.

**Comment by christianvogt** [comment]
@arunkumars08 by fixing our webpack config, you should no longer need to add the alias in fabric8-ui to point to the nested fabric8-analytics-dependency-editor.

I'll start posting PRs. Unfortunately there are 8 of them because of all the different repos where dependencies need to be updated.

**Comment by arunkumars08** [comment]
@christianvogt Thanks, Christian. I understand there are many places to be updated.
Just curious to know when this all will be ready?
Because the PR of mine will introduce a new feature inside fabric8-ui which is highly critical for a few other sprint related items of "Getting Started" to proceed.

**Comment by joshuawilson** [comment]
@christianvogt if you are confident in the `npm link` change, please update the README files for each lib. There should be a section describing how to do that.

Changing to use peer deps is good, thanks for figuring it out.

**Comment by christianvogt** [comment]
@joshuawilson I'll update the README files.

I installed and linked (`npm link --production`) the 8 libraries above into fabric8-ui and I was able to successfully run a local dev server.

@michaelkleinhenz I did not try running standalone planner (never ran it before). I may want to do a screen share with you and run through confirm the change is working with standalone planner.

@arunkumars08 I'll start posting the PRs tonight. Unfortunately there'll be 9 PRs in different repos to merge to complete the task.

**Comment by arunkumars08** [comment]
@christianvogt Since "Fixes" has been used in all the PRs, it closes this issue on every merge. Could you remove that "Fixes"?

**Comment by christianvogt** [comment]
@arunkumars08 oops... changed them all

**Comment by christianvogt** [comment]
All projects that depend on other project(s) whose dependencies are moving to peer dependencies should update their dependency versions to point to the latest.

Once all projects have been updated I will update fabric8-ui to use the latest versions.

**Comment by joshuawilson** [comment]
alternatively, make this a `user-story` and add tasks for each of the points listed

**Comment by arunkumars08** [comment]
@joshuawilson @christianvogt Any info on how long this might take, just curious to know? The reason is that this PR - https://github.com/fabric8-ui/fabric8-ui/pull/2962 is totally dependent on these changes.
Thanks.

cc: @GeorgeActon @animuk

**Comment by joshuawilson** [comment]
This is being worked through on all the child repos. Not all have been merged. Then we can update the f8-ui repo.

**Comment by animuk** [comment]
@joshuawilson Could you please expedite the merging process as this causes delays dependency editor integration with getting started launcher.

**Comment by joshuawilson** [comment]
The PR for this is blocked by https://github.com/fabric8-ui/fabric8-planner/pull/2659 
@michaelkleinhenz @nimishamukherjee can you please get this reviewed and hopefully merged?

**Comment by christianvogt** [comment]
Waiting to resolve https://github.com/fabric8-launcher/ngx-launcher/pull/265 before updating fabric8-ui webpack changes.
