### ISSUE TITLE
Editing comment in Planner resulted in screen corruption

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3688]
Steps to recreate:
* I added a comment to https://openshift.io/openshiftio/openshiftio/plan/detail/2112
* After saving the comment, clicking on the edit/cancel button produced this display:
![screenshot from 2018-05-30 13-54-54](https://user-images.githubusercontent.com/642621/40739215-897a95d2-6413-11e8-8548-bc53b721e165.png)

I have not been able to recreate this issue with other workitems. In further editing of https://openshift.io/openshiftio/openshiftio/plan/detail/2112, I have also seen this:

![screenshot from 2018-05-30 14-14-02](https://user-images.githubusercontent.com/642621/40739266-b9ca402a-6413-11e8-8398-6db023777fea.png)

**Comment by nimishamukherjee** [comment]
@rgarg1 can you replicate this issue?

**Comment by rgarg1** [comment]
@nimishamukherjee I cannot reproduce this issue. Looks like a corner case for which, we don't know the trigger.

**Comment by nimishamukherjee** [comment]
Closing as the issue is not reproducible.
@ldimaggi please re-open if you face this issue again.
