### ISSUE TITLE
We need an "undo button" for drag and drop operations

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#369]
If a user inadvertently moves a workitem - for example in the bacllog view, or within an iteration, there is no undo button so that he can revert the drag-and-drop operation. Thx!

**Comment by joshuawilson** [comment]
cc @michaelkleinhenz

**Comment by michaelkleinhenz** [comment]
Undo in general is is quite complicated given the async multi-user model. I'd vote for having no undo operation. Does Jira and other systems have undo?

**Comment by joshuawilson** [comment]
I don't know what you can drap-n-drop in Jira but in Trello, you can NOT "undo" a drag-n-drop.

**Comment by joshuawilson** [comment]
recommend closing as, will not fix.
