### ISSUE TITLE
Work items for spaces created under user openshiftio are not editable via UI

### ISSUE THREAD

**Issue by Bob-Davis** [openshiftio/openshift.io#3690]
https://openshift.io/openshiftio/tools/plan/detail/4

As an example. 

I can't edit anything in this work item that I created.

**Comment by joshuawilson** [comment]
You are trying to edit a work item that you are not the owner of. If you log in as `openshiftio`, you can edit it.

I logged in and updated the description of the issue. I also added you as a collaborator so you can now work in the `tools` space.

**Comment by joshuawilson** [comment]
If that explains it, please close this.

**Comment by Bob-Davis** [comment]
So you're saying that if I create an issue (which only gives you the ability to add a title and type), I can't add a description because I am not the owner of the issue?

**Comment by joshuawilson** [comment]
If we are planning on letting non-contributors create issues then it is a bug.
If we don't want non-contributors to create issues then it is a bug.
Looks like we have a bug. I'll update the labels.

@michaelkleinhenz are you aware of this?

**Comment by rgarg1** [comment]
I tried adding work items to spaces that I don't own but was not successful. But, the _tools_ space is different and I was able to add a work item to it.

https://openshift.io/openshiftio/tools/plan/detail/6

What's so special about this space? Could be an auth issue.

**Comment by joshuawilson** [comment]
what is special is that you have not been added as a collaborator yet

**Comment by rgarg1** [comment]
@alexeykazakov WDYT?

**Comment by alexeykazakov** [comment]
Currently only collaborators are allowed to create new Work Items in spaces. Which is IMO wrong.
But openshiftio space is special (good) - https://github.com/fabric8-services/fabric8-wit/blob/master/controller/workitems.go#L76
Editing should be allowed by the Work Item creator.

So, my suggestion is: let's allow create Work Items for any OSIO users in any space.
Edit should be allowed by collaborators or Work Item creators only (as it is for openshiftio space right now).

It's not Auth issue anyway. It's up to Planner (Work Item Tracker) to accept or reject user requests based on information from Auth (collaborator or not).
Planner team feel free to fix it.

**Comment by alexeykazakov** [comment]
@michaelkleinhenz it's related to what we discussed recently ^

**Comment by nimishamukherjee** [comment]
@michaelkleinhenz @alexeykazakov looping in UX (@Veethika ) for addressing create and edit rights on work items.

**Comment by Veethika** [comment]
@alexeykazakov @nimishamukherjee @michaelkleinhenz  I have my doubts if these 'rights' could be looked at in isolation. Shouldn't there be a larger story around it?

**Comment by nimishamukherjee** [comment]
@muruGanesan @catrobson do we have a story around permissions at an OSIO level.

@Veethika we need to work with the auth team, align with the overall OSIO permission model and arrive at Planner's permission model.

**Comment by muruGanesan** [comment]
@nimishamukherjee, @Veethika 

Here are the relevant stories: 
Master story from PM: https://github.com/openshiftio/openshift.io/issues/2068
UX story: https://github.com/openshiftio/openshift.io/issues/2910
Additional UX story: 
- https://github.com/openshiftio/openshift.io/issues/3599
- https://github.com/openshiftio/openshift.io/issues/3654

-----
@Veethika 
I would request you to keep @alexeykazakov, @sbose78 in the loop if you are making any changes to the permission flow
[this is latest WF: https://redhat.invisionapp.com/share/QNGBDSOHP6K]

**Comment by alexeykazakov** [comment]
> Master story from PM: #2068

This story is outdated.

**Comment by sbose78** [comment]
> Edit should be allowed by collaborators or Work Item creators only 

@sanbornsen @baijum  Let's ensure this works at the API level, and if not, we'll understand where to put in a fix.

**Comment by alexeykazakov** [comment]
> [this is latest WF: https://redhat.invisionapp.com/share/QNGBDSOHP6K]

This is not the latest WF. This is the latest: https://redhat.invisionapp.com/share/CDKUE8V795H#/screens

> are we considering #2080 this requirement?

No. We don't have the whole userstory in GitHub. We have some in planner - https://openshift.io/openshiftio/openshiftio/plan/detail/2353 (with sub-work items) but there is no much of description unfortunately. Please see to my latest presentation in the Integration Cabal.

**Comment by Veethika** [comment]
@joshuawilson @nimishamukherjee UX would be creating a story for Planner Permissions for the next sprint. Please assign this story to the relevant person who would be taking care of the momentary fix.

**Comment by rgarg1** [comment]
@nimishamukherjee @sbose78 @sanbornsen 

I tested by patching the work item in question via APIs and observed that the API _allows_ editing the work item. I was able to add a description test to the work item. So, the restriction is enforced by the Planner UI, which needs to be handled.

**Comment by sanbornsen** [comment]
For the time being, we'll be allowing the `collaborators` and the `non-collaborator creators` to edit a work item.

**Comment by alexeykazakov** [comment]
@sanbornsen this is what WIT is already supposed to do as far as I remember. Maybe it was changed since we implemented it though.

**Comment by sanbornsen** [comment]
@alexeykazakov maybe, but we don't have a proper generic permission model in place to look for what is allowed and what is not from the front end. We assumed non-collabs can't add a work item thus, all the checks in front end were based on that.
