### ISSUE TITLE
[5] Make caching and storage subsystems work with multiple repositories per ecosystem

### ISSUE THREAD

**Issue by humaton** [openshiftio/openshift.io#3699]
Planner [2449](https://openshift.io/openshiftio/openshiftio/plan/detail/2449)
Caching and storage subsystems currently often make ecosystem-specific decisions based on Ecosystem name. This works fine if we only want to support single repository per ecosystem. However, in order to support multiple repositories per ecosystem, we need to start doing ecosystem specific decisions based on EcosystemBackend. Note both Ecosystem and EcosystemBackend are tables in our existing Postgres database. Support for multiple repositories per ecosystem needs to be tested and fixed where necessary.

**Comment by GeorgeActon** [comment]
@humaton @msrb what is the status of this. It is marked as resolved in planner??

**Comment by msrb** [comment]
This is [resolved], but the changes are not yet in production. It makes more sense to wait for [planner/2448] to be resolved as well and then promote both of them to production at the same time.

[resolved]: https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/676
[planner/2448]: https://openshift.io/openshiftio/openshiftio/plan/detail/2448
