### ISSUE TITLE
[RFE] When a user deletes a space - and therefore the space's projects - the projects' resources should also be deleted

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#370]
The UI features that deletes a space, and its projects, should provide the user with the option of also deleting the projects:
* github repo
* Che workspace
* OpenShift resources

Unless we provide this option to the user, he/she will have to delete these assets manually.

**Comment by joshuawilson** [comment]
This already exists in the user story https://github.com/openshiftio/openshift.io/issues/348
Can you update that as needed.

**Comment by joshuawilson** [comment]
closing as a duplicate
