### ISSUE TITLE
Cannot remove profile bio

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#3701]
As it stands, you can modify your profile bio, but erasing it completely will not register upon clicking save. Steps to reproduce:

1. Navigate to your profile
2. Make sure you have a bio at least one character long; if you don't, add one and save changes
3. Edit your profile again, this time remove your bio entirely and save
4. Notice that the bio will still be present

**Comment by andrewazores** [comment]
I can't reproduce this on current prod, with either Production or Experimental feature opt-in.

**Comment by alexeykazakov** [comment]
I can reproduce it if I do the following:

1. Navigate to your profile
2. Make sure you have a bio at least one character long; if you don't, add one and save changes
3. Go to the Edit profile page again,
**4. Refresh the page** 
5. this time remove your bio entirely and save
6. Notice that the bio will still be present 

I can't reproduce it if I skill the step 4 - refresh

**Comment by alexeykazakov** [comment]
@rohitkrai03 please take a look

**Comment by andrewazores** [comment]
Ah yes, I wasn't refreshing the page. Thanks.

**Comment by chrislessard** [comment]
@alexeykazakov @andrewazores That's strange, I didn't need to refresh to experience the bug. What browser are you using ? I'm on Chrome.

**Comment by andrewazores** [comment]
Hmm. I tried it on both Chrome and Firefox.

**Comment by andrewazores** [comment]
Interestingly, replacing the bio text with a non-empty whitespace string (ex a single space) results in the text being removed.

**Comment by alexeykazakov** [comment]
I suspect the problem is that empty strings are just ignored as unchanged values.
We had this issue in the old user profile UI and it looks like we inherited it in the new UI.

**Comment by rohitkrai03** [comment]
PR raised - https://github.com/fabric8-ui/fabric8-ui/pull/2978. It fixes a bunch of other validation related issues.
