### ISSUE TITLE
Analyze page: "Create an Application" button missing

### ISSUE THREAD

**Issue by dlabrecq** [openshiftio/openshift.io#3702]
After pulling the latest source, I noticed that the "Create an Application" button is missing from the analyze page (i.e., space dashboard) -- confirmed this with prod as well.

There is still a button provided via the application widget's empty state. However, after an application has been created, users have no way to create additional applications.

Note that I'm logged-in and have experimental features enabled.

Before:
![screen shot 2018-05-31 at 10 42 12 am](https://user-images.githubusercontent.com/17481322/40790448-f5e8246e-64c2-11e8-8720-9b0549226977.png)

After:
![screen shot 2018-05-31 at 10 43 34 am](https://user-images.githubusercontent.com/17481322/40790469-0667d514-64c3-11e8-8e42-64ffb8c651b4.png)

**Comment by aptmac** [comment]
I think this is an async issue. The button is supposed to be displayed if `userOwnsSpace()` returns true.

`userOwnsSpace()` compares the value of the current logged in user to the `owned-by` attribute of the `context.space` [[0]](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/analyze/analyze-overview/analyze-overview.component.ts#L84).  The `context` variable is set in the `ngOnInit()` [[1]](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/analyze/analyze-overview/analyze-overview.component.ts#L40) from a subscription; there isn't a guarantee that it will have the proper value by the time the HTML `ngIf*` [[2]](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/analyze/analyze-overview/analyze-overview.component.html#L9) is evaluated. 

@chrislessard thoughts?

FWIW I think it looks better this way; the blue button ruins the aesthetic of the masthead, but that's just my opinion :)

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/analyze/analyze-overview/analyze-overview.component.ts#L84
[1] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/analyze/analyze-overview/analyze-overview.component.ts#L40
[2] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/analyze/analyze-overview/analyze-overview.component.html#L9

**Comment by chrislessard** [comment]
Yes, @aptmac has got this one right. It's an async issue coupled with the fact that the ngIf is bound on a function call, not a boolean [0]. I'll play around with this to resolve it.

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/analyze/analyze-overview/analyze-overview.component.html#L9
