### ISSUE TITLE
Iteration should show Active on the last and first day of month

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3703]
-If I create a new iteration with start date 1st day of month and end date last day of month, it should be automatically activated but If Iteration is created on last day it is not activated.

Discussion from backened team:
UI request contains the startAt and endAt values as "2018-04-01T12:00:00Z" and "2018-04-30T12:00:00Z" respectively. The date is fine but the time is ALWAYS set to "12:00:00Z". It does not send the exact time when the user actually sends the request.

**Comment by kwk** [comment]
> It does not send the exact time when the user actually sends the request.

And it should not send the exact time. If I remember correctly, we can only select dates and not times in the UI. So the UI should not care about any time in my humble opinion. 

Does it make sense to start an iteration on any other time than midnight or end at midnight? Do we have usecases for this? If not, then maybe the backend needs to interpret the date and ignore the time maybe.

Also, when given an end date, do we expect that the iteration is active until the end of the end date is reached or is it an exclusive date?

**Comment by joshuawilson** [comment]
I agree that it should be set to midnight. 

I suggest that the backend only use the date since we control data there. 
Then as a convenience the frontend should only send the date or set the time to midnight.

**Comment by christianvogt** [comment]
Agree with @joshuawilson that the backend should ignore the time altogether and only use the date. That being said from the UI, if we require sending the time along with the date value, we should set the startAt to be `00:00:00Z` and endAt to be `23:59:59Z`.
