### ISSUE TITLE
Adjust initial launcher screen based on Summit feedback (5)

### ISSUE THREAD

**Issue by Essjaysee** [openshiftio/openshift.io#3704]
From the feedback that I got from showing the OSIO launcher to attendees as Summit, there were a few things for us to address to help the usability.

![screen shot 2018-05-31 at 11 48 52 am](https://user-images.githubusercontent.com/3267889/40797390-02ae453a-64d6-11e8-8ffe-257e8fe27645.png)

- The "Continue" button fell below the fold, and users did not get the hint from the button turning blue that they had selected something and could proceed.
- The image above shows a hover box around one of the selections.  This or something similar to show the selection would be helpful.  The radio button being selected was too small and subtle to confirm to the user that they had successfully selected one of the items.
- The body text (i. e. the explanations of the options) was difficult to read.  Maybe it was because the right font wasn't being used, but the text was thin and faint -- maybe bumping it up to a semi-bold or similar would help.

Separately, through PM and ENG feedback, we know that the dark screen is causing some concern for users since it is very different from other visuals across the application.

**Comment by parvathyvr** [comment]
The invision link with the VD explorations of the 'initial launcher screen' considering the feedback points is captured in this task.
-But putting the 'status' as blocked since this task will be moved ahead only based on the outcome of the design thinking sessions for the launcher experience.

**Comment by muruGanesan** [comment]
Since it covered under #4191, I am closing this issue.
