### ISSUE TITLE
Widgets show loading state after environment reset (3)

### ISSUE THREAD

**Issue by dlabrecq** [openshiftio/openshift.io#3705]
After resetting my environment, the home dashboard widgets appear to be stuck in the loading state. I expect that the following subscription returns empty spaces so the loading state can be changed. However, debugging shows the code does not always reach here. 

```
this.subscriptions.push(spacesService.recent.subscribe(spaces => {
      this.recentSpaces = spaces;
      this.fetchRecentSpace();
      this.loading = false;
    }));
```

Note that after creating a new space, the code behaves as expected. After briefly loading, the widgets show the empty state as expected.

Note that a timeout will also correct the problem.

```
    setTimeout(() => {
      this.loading = false; // Failed to load
    }, 2500);
```

Screenshot 1: Widgets continuously show the loading state after resetting environment
![screen shot 2018-05-31 at 1 59 45 pm](https://user-images.githubusercontent.com/17481322/40799193-eb0c5f20-64da-11e8-9ab5-e57a53f65f2e.png)

Screenshot 2: After creating a space -- showing empty state
![screen shot 2018-05-31 at 2 04 42 pm](https://user-images.githubusercontent.com/17481322/40799471-ae62c6f8-64db-11e8-84a2-40ecb514043f.png)

**Comment by jiekang** [comment]
Possible rework:

The widgets should have a default empty state. The loading state should be enabled when an http request to acquire data is made (after the spaces are acquired), and disabled when it returns, possibly after some time out.0

If there are no spaces then no http request will be made and the loading state need not trigger.
