### ISSUE TITLE
[RFE] Enable multiple github accounts to share a single OSIO account

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#371]
At present, each OSIO account requires a one-to-one relationship with a github account. Will we someday enable users to link multiple github accounts to a single OSIO account?

**Comment by alexeykazakov** [comment]
Part of https://github.com/openshiftio/openshift.io/issues/341

**Comment by alexeykazakov** [comment]
I guess the issue actually is about supporting using the same GH account in multiple OSIO account. This is done. Closiing.
