### ISSUE TITLE
PatternFly-Next Upgrade: Convert Less to Scss

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#3710]
In order to convert the Platform (fabric8-ui) to use PatternFly-Next, the current Less code needs to be converted to Sass (scss).

- [ ] All Less dependencies will need to be swapped out for Sass dependencies
- [ ] Webpack configurations are updated for Sass
- [ ] Shared stylesheets are converted
- [ ] Component stylesheets are converted and typescript component.ts files updated to point to the new .scss files
- [ ] Code Guidelines are updated to reflect the changes

Ideally, all updates would be kept under a feature flag so that users are not affected by the change until all components have been swapped over.

**Comment by joshuawilson** [comment]
@mindreeper2420 This feels like a user-story, please add the bullets as `type/tasks` under it. 
I would also ask that you not start on it until we upgrade to latest Angular and Webpack.

**Comment by mindreeper2420** [comment]
- [ ] All Less dependencies will need to be swapped out for Sass dependencies
- [ ] Webpack configurations are updated for Sass
- [ ] Shared stylesheets are converted
- [ ] Component stylesheets are converted and typescript `component.ts` files updated to point to the new `.scss` files

**Comment by ppitonak** [comment]
@mindreeper2420 is it a all-or-nothing change or can we upgrade components gradually?

**Comment by mindreeper2420** [comment]
@ppitonak these are all-or-nothing (all at once) upgrades, as the builder/bundlers need to be updated to support the sass compilation.

Having done conversions in the past, it should only take about 2-3 days to update something like fabric8-ui to sass, with the build processes updated as well.

**Comment by christianvogt** [comment]
Closing as we want to consume PF4 using react. We also want to create common components rather than updating the existing codebase which writes components from html and css.
