### ISSUE TITLE
Convert stylesheets to use Sass (scss)

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#3714]
As a task of https://github.com/openshiftio/openshift.io/issues/3710, the shared stylesheets for OpenShift.io need to be converted to use Sass (scss).

As part of this conversion, the variables and formulas need to be updated, as they are not compatible with the Less code methods.

**Comment by christianvogt** [comment]
Too broad of a task to sweep the entire code base. Need to do on an individual case basis.
