### ISSUE TITLE
Upgrade Angular, Webpack, RxJS, Typescript, and other libs

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#3715]
We need to upgrade to Angular 6 and Webpack 4. 
This is a great time to update all the other libs too.

**Comment by gastaldi** [comment]
Cc @edewit @ia3andy

**Comment by joshuawilson** [comment]
After a webpack change we are making I will work my through all the libs. If anyone plans to work on this for their own lib, please coordinate with me.

**Comment by joshuawilson** [comment]
Otherwise I will be submitting PRs to do the updates.
