### ISSUE TITLE
Convert Component stylesheets to Sass and Update component.ts files

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#3716]
As a task of https://github.com/openshiftio/openshift.io/issues/3710, the component stylesheets for OpenShift.io need to be converted to use Sass (scss), with their common typescript files updated to reference `*.component.scss` files rather than `*.component.less` files.

**Comment by christianvogt** [comment]
Too broad of a task. Will need to do individual tasks.
