### ISSUE TITLE
User accounts that have zero spaces fail to fully load dashboard page after login (blocking automated tests)

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3718]
Steps to recreate:
* Login to https://openshift.io

Expected results:
![screenshot from 2018-06-01 12-47-14](https://user-images.githubusercontent.com/642621/40853341-bcfcbadc-659b-11e8-9a99-dc69c7e95e65.png)

Error being seen by multiple user accounts - accounts used by automated tests:
![screenshot from 2018-06-01 12-30-07](https://user-images.githubusercontent.com/642621/40853365-cd6fd336-659b-11e8-816a-87f2b0c52630.png)

The result of this is that the tests fail as the dashboard page is never fully loaded.

An environment reset does not resolve this error. 

No errors are seen in the browser console or network tab.

**Comment by ldimaggi** [comment]
It looks as though this issue is only present if a user has zero defined spaces.

**Comment by ldimaggi** [comment]
The problem is still there in production:

![screenshot from 2018-06-01 17-33-16](https://user-images.githubusercontent.com/642621/40864455-efaf2afc-65c1-11e8-84ec-d831b2493125.png)

**Comment by ldimaggi** [comment]
You can recreate the issue by:
* Login to https://openshift.io
* Reset user env
* Go to 'account home' page

**Comment by joshuawilson** [comment]
Is this not a duplicate of #3705? The PR mentioned above has not been merged yet.

**Comment by ppitonak** [comment]
IMHO it is a duplicate of #3705

**Comment by ldimaggi** [comment]
Correct - it is the same issue as #3705.
