### ISSUE TITLE
email notification posts the wrong person

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#3719]
The email notifications for work items in Planner only state the creator as the one that makes the change.

If someone else changes it is still lists the creator as the one that made the update.

**Comment by joshuawilson** [comment]
@mindreeper2420 were you the one that worked on this?

**Comment by mindreeper2420** [comment]
@joshuawilson I just made the template - I believe Aslak would have a better idea on why it isn't showing the correct info.

**Comment by joshuawilson** [comment]
cc @aslakknutsen

**Comment by alexeykazakov** [comment]
Fixed in prod. Closing as resolved.
