### ISSUE TITLE
Deployments Toolbar Placeholder Text is Cut Off

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#3723]
On the Deployments page, the placeholder text for the Application Filter is cut off, leaving only 'Filter by Applicati'. This does not change no matter viewport size or zoom level.

![screen shot 2018-06-01 at 4 43 13 pm](https://user-images.githubusercontent.com/4032718/40862617-147b6e1a-65bb-11e8-8230-b6e5e7233964.png)

**Comment by andrewazores** [comment]
Comparing this toolbar to the ones in the Codebases and Pipelines views, it seems as though that first divided section of the toolbar is fixed width. These are all just using the `pfng-toolbar` component. Should this toolbar specific to the Deployments page be customized to increase the width of this first section? Or perhaps the "Application Name" filter label can simply be renamed shorter, to keep the toolbar consistent with the others?

**Comment by mindreeper2420** [comment]
I don't have an issue with adjusting the width of the input to fit the placeholder text. There will probably be a good number of applications with longish names, so having extra space before it begins to move horizontally wouldn't be bad either.

**Comment by jiekang** [comment]
Yes we can adjust for this but it really feels like this something the pfng-toolbar component should be handling, no?

**Comment by aptmac** [comment]
> Yes we can adjust for this but it really feels like this something the pfng-toolbar component should be handling, no?

I'm having flashbacks, I had looked into [this](https://github.com/fabric8-ui/fabric8-ui/pull/2422) [0] before and gotten a bit stuck so I opened an [issue](https://github.com/patternfly/patternfly-ng/issues/311) [1] on the pf-ng repo hoping for some feedback .. and forgot about it haha.

[0] https://github.com/fabric8-ui/fabric8-ui/pull/2422
[1] https://github.com/patternfly/patternfly-ng/issues/311

**Comment by jiekang** [comment]
In my experience it's pretty unreliable to communicate via GH issues and @ tags... Some people respond, others don't. Best would be to ping someone who works on patternfly-ng in mattermost and make sure it's on their plate.

**Comment by jiekang** [comment]
I wouldn't mind seeing something like https://github.com/fabric8-ui/fabric8-ui/pull/2422 merged though. If it ever gets resolved in the library we can change to accomodate easily enough.
