### ISSUE TITLE
Jenkins pod stuck in initialising and recreate mode

### ISSUE THREAD

**Issue by pjlcastro** [openshiftio/openshift.io#3725]
Hello, my Jenkins pod is stuck into recreating phase for the last 2 days, and since my user doesn't have permission for any action like deleting the pod, I am unable to do much in order to solve this.

Am I missing something here?

Best regards

<img width="570" alt="screen shot 2018-06-03 at 14 41 24" src="https://user-images.githubusercontent.com/39656243/40889403-5362743e-673c-11e8-905e-6212a19ed328.png">

**Comment by RickJWagner** [comment]
Hi.  Have you tried 'resetting' your environment?
This is done by going to your account Profile (upper right hand corner of the screen, select 'Profile'), then using the 'Edit Profile' button on the left.  The next screen will have a 'Reset Environment' button, please give this one a try.
You will lose your Space artifacts, but they can easily be rebuilt. (GitHub is not affected.)
Good luck,
Rick

**Comment by pjlcastro** [comment]
Hello, thanks a lot, that did the trick, now everything is as it should be :)

Best regards,
PJ
