### ISSUE TITLE
Loader for Che - Final Design Exploration

### ISSUE THREAD

**Issue by bdellasc** [openshiftio/openshift.io#3732]
VCs:

- [ ] Meet with @slemeur 's team RE: research they needed to do and was discussed in the last meeting. [Meeting notes here](https://docs.google.com/document/d/1UBudUth8GGfPRlyw9jkke3bGbZNgjCNx6ZUFwK3yoFc/edit).
- [ ] Based on the discussion, narrow down animations for final design push
- [ ] Share designs with Stevan's team, gather any additional feedback, verify final requirements
- [ ] One feedback is integrated, deliver final files to his team for implementation

**Comment by bdellasc** [comment]
After meeting last week, this work will be back-burnered for the time being.

**Comment by serenamarie125** [comment]
@slemeur are you still waiting on anything related to this Issue?

**Comment by slemeur** [comment]
Not at this moment.
