### ISSUE TITLE
Planner Process Templates

### ISSUE THREAD

**Issue by Veethika** [openshiftio/openshift.io#3733]
## Description
The different process template will have an impact on various aspects of Planner as well as on other areas in OpenShift.io. Map the various dependencies and provide a solution in the form of wireframes.

## Verification Criteria

- [x] Explore how the change in process template can possibly impact other sections within Planner and also beyond. Capture as screenshots/sketches in InVision

- [x] Capture the design of scrum template that also takes care of 'impediments' & facilitates the creation of 'issues' from within the template

- [ ] Evaluate the impact of using a scrum and agile template on the board view of Planner

- [ ] Understand the relevant data visualization, report generation requirements for a Scrum and agile template user and come up with sketches/wireframes

**Comment by muruGanesan** [comment]
@Veethika, verification criteria look good to me... if needed we will add later. 
I will work on this.

**Comment by catrobson** [comment]
Is there any activity on this story to date?

**Comment by muruGanesan** [comment]
@catrobson, I am started working on Scrum but as per current status, the OSIO Planner will have "Agile template".
So, the current focus is to create a common template for all the process method (tools).
I will add the draft version soon and hold this issue (for some time).

**Comment by muruGanesan** [comment]
This is an initial concept based on engineering team's review we may proceed or drop. 

https://docs.google.com/presentation/d/1UxeI0xj_ShQ4yMLbnS9nnKQlOPIORrCNaf43gd3lIXY/edit?usp=sharing

@Veethika please update the status of this issue based on planner goal & priority, we can reconsider this story again.

**Comment by Veethika** [comment]
> @Veethika please update the status of this issue based on planner goal & priority, we can reconsider this story again.

@muruGanesan I have added 'Agile' along with Scrum to make the description more relevant
It would be helpful if you could add more comments to the slides as it's a bit difficult to figure as of now which section relates to which point of the listed verification criteria. Captions for the screenshots could also be help bring some more clarity.

**Comment by muruGanesan** [comment]
@Veethika, 
I updated the document with interaction notes & I also proposed for the "process template" switching in (Slide-9).
It is a proposal, but feel free to modify/change anything based on 'planner' scope.

https://docs.google.com/presentation/d/1smpjYQJDmOXbJfEMZOP0-IQCuPj5SeeRWxfXBbMroLk/edit?usp=sharing

**Comment by muruGanesan** [comment]
@Veethika , @GeorgeActon , @serenamarie125 ,
I am closing this issue because Planner team is tracking in the planner.
