### ISSUE TITLE
Deployments loading page layout distorts elements at small screen size

### ISSUE THREAD

**Issue by aptmac** [openshiftio/openshift.io#3735]
When navigating to the Deployments page using a small screen size (which happens to me when my browser is at half-size of my screen on my 1920x1080 monitor), the layout of the loading screen elements are distorted. The cards are too large for the row, and appear to overflow onto the next row.

![before](https://user-images.githubusercontent.com/10425301/40923943-0edbd8a2-67e4-11e8-8b47-82ea8c85865e.png)

**Comment by joshuawilson** [comment]
@mindreeper2420 did you know about this?

**Comment by joshuawilson** [comment]
fixed in https://github.com/fabric8-ui/fabric8-ui/pull/2982
