### ISSUE TITLE
Creating a new label and pressing Enter key closes the label dropdown

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3738]
- Click on a workItem title to open quick Preview
- Click Assign Label
- Create a new label -> Enter text
- Press Enter Key 
Dropdown is closed
![peek 2018-06-05 12-33](https://user-images.githubusercontent.com/34271052/40960320-f81c688c-68bc-11e8-8b18-86aa6758fc22.gif)

**Comment by rgarg1** [comment]
Pressing Enter key should:
- Create label
- Clear the label field
- Allow the next label to be created

**Comment by sahil143** [comment]
@rgarg1 I'm not able to reproduce this on prod-preview. Please, Can you verify?

**Comment by Raunak1203** [comment]
@sahil143 issue can be recreated only if you have comments

**Comment by sahil143** [comment]
Thanks @Raunak1203, I can reproduce it with comments

**Comment by sahil143** [comment]
Fixed in https://github.com/fabric8-ui/fabric8-planner/pull/2691. Closing.
