### ISSUE TITLE
Unable to complete wizard if github not connected

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#3743]
1. Disconnect Github account from https://openshift.io/username/_settings , Or login as a new user.
2. Create a space and attempt creation of an app using the wizard.
3. Try 'authorize github'. 

Observe that the UI does not respond. The console has a 
```
401 - Unauthorized {"errors":[{"code":"jwt_security_error","detail":"missing header \"Authorization\"","id":"4B1ZalIB","status":"401","title":"Unauthorized"}]}

```
This is because the UI is not sending the `Authorization: Header <>` in the request.

![screenshot from 2018-06-06 00-21-50](https://user-images.githubusercontent.com/545280/40996922-260c598a-6914-11e8-8803-a3936715a372.png)

**Comment by invincibleJai** [comment]
thanks @sbose78 , will look into this on priority.

**Comment by invincibleJai** [comment]
Have verified changes are in prod-preview.

**Comment by sbose78** [comment]
Works in prod-preview. Good to go, @joshuawilson .

**Comment by invincibleJai** [comment]
Thanks, closing it as changes are in prod.
