### ISSUE TITLE
401 (Unauthorized) on Token Refresh with seemingly no issue in UI

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#3746]
Failed to load resource: the server responded with a status of 401 (Unauthorized) https://auth.prod-preview.openshift.io/api/token/refresh"

UI Took no action to relogin.

Happened after a long period of not logging into prod-preview, entered the main page and got redirected to user profile as if everything was fine. UI showed me as logged in, but the console was showing a failure to refresh token.

Expected the UI to take some action.

**Comment by alexeykazakov** [comment]
Related to https://github.com/openshiftio/openshift.io/issues/3736
