### ISSUE TITLE
Cannot run unit tests in fabric8-ui after ngx-forge update

### ISSUE THREAD

**Issue by aptmac** [openshiftio/openshift.io#3748]
After a recent [commit](https://github.com/fabric8-ui/fabric8-ui/commit/cd48fa472b8347e3e16be05af494fe956cc59497) [0] to update the ngx-forge version, the unit tests in fabric8-ui cannot be ran. The `fabric8-analytics-dependency-editor` cannot be found, and halts the running of tests.

Here's an example of what is printed to the console when running `npm run test:unit`:
```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  Error: Cannot find module "fabric8-analytics-dependency-editor"
  at config/spec-bundle.js:222556
06 06 2018 15:41:50.241:WARN [karma]: Test suite was empty.

Finished in 1.418 secs / 0 secs @ 15:41:50 GMT-0400 (EDT)

SUMMARY:
✔ 0 tests completed
```

[0] https://github.com/fabric8-ui/fabric8-ui/commit/cd48fa472b8347e3e16be05af494fe956cc59497

**Comment by andrewazores** [comment]
This is resolved, isn't it?

**Comment by aptmac** [comment]
Yes, this cannot be reproduced any more - closing.
