### ISSUE TITLE
[1] Add a check for code coverage threshold to all CI jobs for analytics repositories

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#3750]
## Issue in Planner

https://openshift.io/openshiftio/openshiftio/plan/detail/2588

## Problem description

We have defined a threshold (90% ATM) for the code coverage. In order to keep the required code quality, the CI jobs needs to be updated to check if the threshold has been reached or not. It needs to be done for all analytics repositories.

## Acceptance criteria

Check is added to `runtest.sh` script to all following repositories:

- [x] f8a-server-backbone
- [x] fabric8-analytics-api-gateway
- [x] fabric8-analytics-auth
- [x] fabric8-analytics-data-model
- [x] fabric8-analytics-ingestion
- [x] fabric8-analytics-jobs
- [x] fabric8-analytics-license-analysis
- [x] fabric8-analytics-npm-insights
- [x] fabric8-analytics-nvd-toolkit
- [x] fabric8-analytics-server
- [x] fabric8-analytics-stack-analysis
- [x] fabric8-analytics-tagger
- [x] fabric8-analytics-version-comparator
- [x] fabric8-analytics-worker
- [x] fabric8-gemini-server

**Comment by abs51295** [comment]
@tisnik could we also a coverage badge to every repository and maybe also have a bot like centos-ci to comment the coverage on every commit added to the PR?

**Comment by tisnik** [comment]
@abs51295 re coverage badge: it's in progress. re centos-ci bot: it'd need more investigation, but it is doable, of course :)

**Comment by tisnik** [comment]
Check was added, but the threshold was not set to 90% for all repositories right now. It could be configured later.
