### ISSUE TITLE
Deployments card status icons always initially appear as "OK"

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#3757]
When the Deployments page is visited, the status icons on Deployment cards always initially appear with the green "OK" (pficon-ok) icon. After some time has passed and detailed information about the resources of a Deployment have been received, the icon may change, ex. to a yellow warning triangle (pficon-warning-triangle-o). For Deployment cards where the resource usage is always at or above the warning level, the icon therefore always switches from "OK" to "Warning" visibly with a delay. Should there instead be a different default state than "OK" for the icon to display while loading resources data? Perhaps pficon-in-progress at first, and then pficon-ok/pficon-warning-triangle-o/pficon-error-circle-o once data is received?

**Comment by joshuawilson** [comment]
@openshiftio/uxd-team

**Comment by catrobson** [comment]
pficon-in-progress is an actual state, not a loading state, so it shouldn't be used for this.

We would show a spinner in the place of the icon until it gets to the point where we can show the status I would think, but I'm not sure if this would end up with spinners all over the place and be a bit too active on the page (distracting over helpful).  @serenamarie125 do you have any situations where the status icon takes a moment to load in from other products and how they handled it?

**Comment by andrewazores** [comment]
@catrobson @serenamarie125 ping

**Comment by catrobson** [comment]
@andrewazores There isn't an existing, clean, solution for this in PatternFly after some investigation. I'd suggest that we leave this as it is implemented for right now, and we'll put a story into the UXD backlog to investigate the creation of an indeterminate state icon until the actual state loads to replace that icon with.

**Comment by joshuawilson** [comment]
@catrobson do we convert this to a `task` or do you want to create a new issue and we close this one?

**Comment by catrobson** [comment]
Updated to type:task.
