### ISSUE TITLE
Bug: Che is not showing CVE error

### ISSUE THREAD

**Issue by luebken** [openshiftio/openshift.io#376]
Adding a vulnerable dependency in Maven doesn't show a CVE anymore.

How to reproduce:
* open pom.xml in Che
* add
```
<dependency>    
<groupId>commons-collections</groupId>    
<artifactId>commons-collections</artifactId>    
<version>3.2.1</version>
</dependency>
````
Expected results: 
* Error shown next to vulnerable dependency
* Message shows CVE

Test-Case Id: Test-1704E468-01

**Comment by invincibleJai** [comment]
@luebken we are working on it , more details can be found here https://github.com/redhat-developer/rh-che/issues/218

**Comment by GeorgeActon** [comment]
@luebken @invincibleJai  https://github.com/redhat-developer/rh-che/issues/218 is closed now. Should this be retested?

**Comment by invincibleJai** [comment]
@GeorgeActon CVE's are being flagged now for all three ecosystem, but still we face issue with certain pom.xml i.e based on content. Details can be seen here - https://github.com/eclipse/che/issues/5843

**Comment by GeorgeActon** [comment]
@invincibleJai @samuzzal-choudhury Those bugs have no severity on them. Does this impact Burr workshops? Should it be on the hit list for that to get more attention to it?

**Comment by invincibleJai** [comment]
@luebken it's working fine now , let me know if it looks good.
CC @GeorgeActon

**Comment by GeorgeActon** [comment]
@luebken Can this be closed?

**Comment by GeorgeActon** [comment]
Tested multiple times. So we are closing this issue. If you encounter it again, re-open the issue
