### ISSUE TITLE
Create API endpoint for retreiving list of spaces where a user is a collaborator

### ISSUE THREAD

**Issue by aptmac** [openshiftio/openshift.io#3760]
Following discussion regarding the work-item-widget [0] , it would be ideal if there was an API endpoint for retrieving a list of spaces that a particular user is a collaborator on. 

The work-item related components should display work items for spaces that the user is designated as a collaborator [1]. At the moment, this information cannot be easily retrieved and the components are displaying information for 'recent' spaces instead.

[0] https://github.com/fabric8-ui/fabric8-ui/pull/2966#issuecomment-396264010
[1] https://github.com/fabric8-ui/fabric8-ui/pull/2966#issuecomment-396257894

**Comment by alexeykazakov** [comment]
We are deprecating collaborators API. We are moving to teams and orgs. So, we are not going to add anything new to the existing collaborators API but we might want to have similar functionality in our new permission API.

**Comment by joshuawilson** [comment]
@alexeykazakov do you want to keep it open to remember or just create a new issue to track it as a task?

**Comment by alexeykazakov** [comment]
We have bunch of issues in https://openshift.io/openshiftio/openshiftio/plan plus some UX taks in GitHub which are overlapping with this request.

But we can keep this GH issue open just because it's more specific.
