### ISSUE TITLE
Remove 'View all spaces'

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3763]
There are similar views - `My spaces` and `View all spaces`

* they both show the same data
* `_spaces` feels more outdated
* `_spaces` shows huge profile photo and user name which doesn't make sense

**Comment by andrewazores** [comment]
@catrobson was there an issue for tracking this already? I know it's been brought up before.

**Comment by joshuawilson** [comment]
Duplicate of #3536
