### ISSUE TITLE
It's impossible to distinguish users when adding collaborator

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3766]
1. open space
2. click settings -> collaborators
3. add collaborators

result:
* if multiple users have the same/similar name, it's impossible to distinguish them

![peek 2018-06-12 13-05](https://user-images.githubusercontent.com/445100/41286905-54ddaa16-6e41-11e8-904f-808bca12ad37.gif)

**Comment by andrewazores** [comment]
Duplicate of https://github.com/openshiftio/openshift.io/issues/3122
