### ISSUE TITLE
Add collaborators dialog too big

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3767]
1. go to space -> settings -> collaborators -> add collaborators
2. select multiple users

result:
* both before and after selecting user, the dialog contains a lot of empty space

![peek 2018-06-12 13-09](https://user-images.githubusercontent.com/445100/41287068-da0ae64a-6e41-11e8-9a4f-b4798394b4a3.gif)

**Comment by joshuawilson** [comment]
I'm not sure this will get worked. We are deprecating the collaborators page in favor of teams.

**Comment by alexeykazakov** [comment]
Closing as “won’t fix”. As Joshua said we are depreciating the collaborators page.
