### ISSUE TITLE
Add collaborators: focus is not in search field

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3768]
1. open space -> settings -> collaborators -> add collaborators
2. click `Select` dropdown

expected:
* focus is in search input so that I can immediately type

**Comment by joshuawilson** [comment]
I'm not sure this will get worked. We are deprecating the collaborators page in favor of teams.

**Comment by alexeykazakov** [comment]
Closing as “won’t fix”. As Joshua said we are depreciating the collaborators page.
