### ISSUE TITLE
Features toggles changes are not taken into account

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#3771]
Any new change made in the unleash admin console is not reflected in the `toggles-service` API. This is due to a bug in the forked client, where the `timer` used to performed the data sync between the toggles server (unleash) and the toggles-service is performed only once (by definition, a `timer` only sends an event *once* on its channel). The solution is to replace the timer with a ticker which will deliver an message on its channel every `n` seconds to trigger a new data sync.

Once the client is updated, the `toggles-service` will need to pick the new version of the dependency.

**Comment by joshuawilson** [comment]
what severity is this?
