### ISSUE TITLE
"View Log" (Jenkins build log) returns 502 (Bad Gateway) error 

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3774]
Steps to recreate:
* Create a new app
* On the pipelines page, clock on "View Log"
* Observe the 502 error:

![myimage](https://user-images.githubusercontent.com/642621/41311446-4fd4bcc4-6e52-11e8-888f-620b53101cf1.gif)

**Comment by jiekang** [comment]
Any chance you can get the response information, does the body contain anything?

Were you able to visit the jenkins instance?

**Comment by ldimaggi** [comment]
Closing as not reproducible.

**Comment by piyush1594** [comment]
@ldimaggi I think you forgot to close. Can we close or its still an issue?

**Comment by piyush1594** [comment]
No response. Closing this.

**Comment by ldimaggi** [comment]
Sorry for the delay - yes - this should be closed.
