### ISSUE TITLE
Title bar style of "Dependencies" is not matching as per UX input

### ISSUE THREAD

**Issue by AshishDurgude** [openshiftio/openshift.io#3775]
Steps to access the feature
1. Login into prod-preview.openshift.io
2. Go to Top right username -> Settings -> Features opt-in
3. Select 'Internal Experimental Features'
4. Go to Home screen
5. Create a new space or pick an existing space
6. Create a new application
7. Select quick start flow
8. You should see dependency editor as a 2nd step

Initially, it will be just with a button to let the user select mission and runtime.

Select mission and runtime (eg. Health-check and Wildfly)

You can see Dependency editor showing up in the second step.

Change needed:
**Follow the title bar style of "Application Summary" to "Dependencies".**

![screen shot 2018-06-13 at 2 43 41 pm](https://user-images.githubusercontent.com/13097334/41341799-3a036eba-6f18-11e8-97bb-a69f6eead395.png)

**Comment by stevengutz** [comment]
This is not a SEV2.  It's a SEV3.  There isn't anything major failing here.

**Comment by arunkumars08** [comment]
Changes for the same are available in prod-preview. Please feel free to reopen if things are not as expected.
