### ISSUE TITLE
UI acceptable project name is not accepted by API

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#3781]
Steps to reproduce:

1. Attempt to create application with name "0123 3210" which is accepted by the UI.
2. See API fail when hitting "Set Up Application" button.

![name-fail](https://user-images.githubusercontent.com/5430520/41356739-7d8f0732-6ef2-11e8-886f-44f51468dc99.png)

**Comment by invincibleJai** [comment]
@animuk it has already been fixed thanks to @jiekang can see the changes https://github.com/fabric8-ui/fabric8-ui/pull/3025 . Have tried locally looks good to me. @joshuawilson can we get changes promoted to prod?

**Comment by joshuawilson** [comment]
I've promoted it.

**Comment by jiekang** [comment]
The bug described here can no longer occur; closing. @invincibleJai can you see also https://github.com/openshiftio/openshift.io/issues/3818

It is related.

**Comment by invincibleJai** [comment]
sure @jiekang
