### ISSUE TITLE
Signing in to OSIO and/or going to Account Home - Recent spaces displays spinning wheel

### ISSUE THREAD

**Issue by GeorgeActon** [openshiftio/openshift.io#3788]
When I sign into OSIO/ or select Account Home the Recent spaces never refreshes 
- just shows the spinning wheel 
I can go to my account and select any workspace and immediately see the workspace

**Comment by ldimaggi** [comment]
Duplicate of:
* https://github.com/openshiftio/openshift.io/issues/3705
* https://github.com/openshiftio/openshift.io/issues/3718

**Comment by GeorgeActon** [comment]
closing as a duplicate
