### ISSUE TITLE
The cursor should not change when hovering over another user's space's description

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#3790]
Unfortunately screenshot tools don't capture the cursor, so you'll need to take the following steps to recreate this potential issue:

1) Log into OSIO
2) Visit another user's space, preferably one with a description to make life easier (ATTOW openshift.io/almacdon/SuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuperLongSpaceName works)
3) Hover over the description
4) Notice the change in cursor

In my opinion, the cursor change suggests to the user that clicking the description will have an effect. Of course, this is not the case when visiting another user's space. I think maintaining a consistent cursor in this scenario would make for better UX. Thoughts ? 

@catrobson @aptmac

**Comment by joshuawilson** [comment]
@openshiftio/uxd-team

**Comment by mindreeper2420** [comment]
Nope, the cursor should not change to give the user the idea that another users Space is editable. Users should only see the 'pointer' cursor over the description when they are an admin/owner of the Space.

**Comment by andrewazores** [comment]
@aptmac can this be closed? Your related PR was merged but didn't contain the "magic words" in the commit message to autoclose this.

**Comment by aptmac** [comment]
@andrewazores Ah yes this can be closed, I didn't realize that it was the commit messages that autoclosed issues - that's pretty neat.
