### ISSUE TITLE
Design for additional deployment metrics (8)

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#3791]
### Description
Additional deployment metrics should be added to the Deployments page to help capture any metric that might influence an app not being deployed successfully.

### Parent Issue(s)
- https://openshift.io/openshiftio/openshiftio/plan/detail/2598

### Verification Criteria
- [x] Requirements for which metrics need to be added captured and added to this work item
- [ ] Designs created for additional metrics in Sketch, shared in InVision, and posted here
- [ ] Full design specs shared with UXD, Mario's team, and devtools-saas

**Comment by joshuawilson** [comment]
I'm not sure @l0rd is the right person. Maybe @ebaron and @andrewazores could help.

**Comment by andrewazores** [comment]
Elliott listed all of the metrics here:

https://github.com/openshiftio/openshift.io/issues/2086#issuecomment-371984005

(plus CPU and Memory, which we already have)

**Comment by parvathyvr** [comment]
Keeping this story on hold since the design for 'deployments page' will be affected by the new design efforts in the following stories: 
https://github.com/openshiftio/openshift.io/issues/4064
https://github.com/openshiftio/openshift.io/issues/4065

**Comment by sdash-redhat** [comment]
Refer to https://github.com/openshiftio/openshift.io/issues/4065 regarding the ideation on Deployments page. 
Also some associated useful links: 
https://docs.google.com/presentation/d/1bRn63ZVxb24unGGOTscs72UGtUQocgb3Hxhx9w7XCNQ/edit?usp=sharing

**Comment by sdash-redhat** [comment]
There is a question as to if showing deployments should be available in OSIO, and if so couldn't we just link out to OpenShift.

Based on the number of discussions, we have consensus to stop the design work regarding the deployments page. 

Closing this issue. 
@serenamarie125 @muruGanesan @joshuawilson @aslakknutsen @sunilmalagi
