### ISSUE TITLE
Document launcher use cases and designs with OpenShift wizard (5)

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#3792]
Today OpenShift and OpenShift.io have two different getting started experiences that look and feel very different.  Start document with OpenShift team about the launcher experience vs. Service Catalog wizard overlay experience.  Start with use cases to understand how the use cases are the same or differ.  Then capture designs from OpenShift.io vs. OpenShift and what the pros and cons are from each's viewpoint (have OpenShift designer contribute OpenShift pros/cons).  See if we can consolidate the design experience between these two into one design proposal in any way.

Verification Criteria:
 - [x] Document created and use cases captured and document is linked in this issue
 - [x] Pros/cons of OpenShift.io launcher design added to the document 

Future Stories:
- [ ] Mtg between OpenShift and OpenShift.io team completed to discuss experiences in detail and see if there are shared outcomes we could find for a more consistent design
- [ ] More consistent design direction captured in document
- [ ] Stories created for any additional design work for OpenShift.io given this information

**Comment by muruGanesan** [comment]
@catrobson, @serenamarie125 , Could you please point me to the stakeholders & designers of Openshift, So that I can initiate the discussion.

**Comment by serenamarie125** [comment]
@muruGanesan, the OpenShift stakeholders will be myself, Colleen Hart, Chris Shinn & Brie Mignano.  The OpenShift team hasn't been able to prepare their use cases yet, but it would be great if we could have some time set for you to share your findings with us.  If possible, could we set something up for Monday the 25th ?  A number of the OpenShift designers will be OOO starting the 26th and 27th for a couple of weeks.

**Comment by muruGanesan** [comment]
@serenamarie125 thanks for your input. 
Sure, I will prepare some documentation around the finding and share it with you.

**Comment by muruGanesan** [comment]
1) I did some initial study on Wizard with hierarchy & without hierarchy...
https://docs.google.com/presentation/d/1fTqtX3wTW5MZzhcIl0PEVJYpiE7yGp5cUinzWBjTEbM/edit?usp=sharing
2) I will get more use-case details of OSIO & Openshift Online and provide UX recommendation.

**Comment by muruGanesan** [comment]
Here is the latest file:
https://docs.google.com/presentation/d/1hu-9_-7FvDQkz5kVM3XDMH2U_gAfr1BLSFCercgnWvw/edit?usp=sharing

**Comment by muruGanesan** [comment]
I am closing this issue because we would be relooking at this E2E as part of K train.
