### ISSUE TITLE
Audit Trail Changes

### ISSUE THREAD

**Issue by Veethika** [openshiftio/openshift.io#3794]
Re-look at the following areas for 'Audit Trails' interaction rules:

- [x] Sequence for the nested comments
- [x] Deletion rules for primary and secondary rules
- [ ] Accommodate edited comments history
- [x] Permisson to edit/delete

**Comment by muruGanesan** [comment]
@Veethika, If you have any planner reference please paste the "ID" & "Link". If you have completed in Planner then I request you to close this issue by providing 'Invision link'

**Comment by Veethika** [comment]
This is currently blocked by #3849

**Comment by Veethika** [comment]
Permissions: https://docs.google.com/spreadsheets/d/1ALVEMyI_i5dvOwx_0ChN9WvlyGhHkCwchylje2SrpdQ/edit#gid=0
Solution https://redhat.invisionapp.com/share/N7IH5I3QWZU
