### ISSUE TITLE
Pipeline: Maven Central artifacts downloading from wrong URL

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3796]
Build of my Vert.x HTTP project failed because of this error:
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project e2e-0615-072415: Could not resolve dependencies for project io.openshift.booster:e2e-0615-072415:jar:1.0.1: Could not transfer artifact org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-impl-javaee:jar:2.0.0 from/to central (https://repo1.maven.org/maven2): GET request of: org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-impl-javaee/2.0.0/shrinkwrap-descriptors-impl-javaee-2.0.0.jar from central failed
```

Although this seems to be just a random network issue, [Maven documentation](https://maven.apache.org/guides/mini/guide-mirror-settings.html) says that a different URL is official one:
> The official Maven 2 repository is at http://repo.maven.apache.org/maven2 hosted in the US, or http://uk.maven.org/maven2 hosted in the UK. 

Implementation of #2486 might prevent this kind of issues

**Comment by joshuawilson** [comment]
Please add labels

**Comment by bartoszmajsak** [comment]
@ppitonak If it's a random network issue how come it is SEV-2 then? 

@sthaha which version of Maven are we using in our build pods? According to Maven changelog as of 3.0.4 the default URL has been changed from http://repo1.maven.org/maven2 to http://repo.maven.apache.org/maven2. Can you check if there is something in `settings.xml` on the build side?

**Comment by ppitonak** [comment]
It's a random issue occuring very often, severity increased for visibility.

**Comment by bartoszmajsak** [comment]
I understand your reasoning and it is fine to increase the visibility, but I don't think this is really something for `area/app-wizard`  `area/launcher` to explore. This is more likely build / infra problem.

**Comment by hrishin** [comment]
In maven settings its

``` xml
    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2</url>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2</url>
            <releases>
                <enabled>true</enabled>
            </releases>
        </pluginRepository>
    </pluginRepositories>
```

If thats the case we could update it. Maven settings https://github.com/fabric8-services/fabric8-tenant-jenkins/blob/master/apps/jenkins/src/main/fabric8/jenkins-maven-settings-secret.yml#L4

**Comment by hrishin** [comment]
@ppitonak is it blocking the builds? Could you please share the complete log?

**Comment by ppitonak** [comment]
Yes, pipeline fails.

Example 1:
* Jenkins log http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/379/05-01-jenkins-log.html
* Pipeilne http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/379/05-02-afterEach.png

Example 2:
* Jenkins log http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/373/05-01-jenkins-log.html
* pipeline http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/373/05-02-afterEach.png

Example 3:
* Jenkins log http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2a-beta/385/05-01-jenkins-log.html
* pipeline http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2a-beta/385/05-02-afterEach.png

**Comment by hrishin** [comment]
@ppitonak thanks for sharing logs. Let us confirm if its an issue with maven repository setting or network issue.

**Comment by ppitonak** [comment]
@hrishin I'm not aware of a way to reliably reproduce this issue

How can I try it in prod-preview?

**Comment by hrishin** [comment]
@ppitonak 

Could you https://openshift.io/_profile/_tenant?jenkinsVersion=PR-v80e5cd9-3&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging update the tenant and test it?
This one is prod. 

My bad, I thought we could update the prod-preview in same but it doesn work there.

**Comment by piyush1594** [comment]
Maven central URL has been fixed and is available in prod. Use Jenkins version 4.0.106 Thanks, closing the issue.
