### ISSUE TITLE
On new project creation - user is presented with an error dialog that only states "Error" - if Forge service is down

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#380]
Steps performed:
* Created a 100% new user account (osiotest3141@yahoo.com) in github, and OSIO
* Logged into OSIO
* Created new space
* Created new project - from Vert.X basic quickstart - accepted all defaults in project creation wizard
* This dialog was displayed:

![screenshot from 2017-07-20 10-26-37](https://user-images.githubusercontent.com/642621/28422666-bc2853f4-6d36-11e7-9a36-d05ff7e89496.png)

Retrying the project creation was successful.

Screencast:
https://drive.google.com/open?id=0B1s-ZoxD8FjUeVQ5V3dmbGNCSzg

**Comment by ldimaggi** [comment]
This problem was been seen intermittently - not clear if this is related to only new user accounts.

**Comment by ldimaggi** [comment]
See:  https://github.com/fabric8-ui/fabric8-ui/issues/1764

Is this error more likely to be seen on a new user account as the the Forge service may still be starting up?

**Comment by joshuawilson** [comment]
@ldimaggi This should have been fixed in https://github.com/fabric8-ui/fabric8-ui/pull/1769. Please verify.

**Comment by ldimaggi** [comment]
Closing as this issue has not been seen this week.
