### ISSUE TITLE
Initial Setup for the Design Standard Wiki

### ISSUE THREAD

**Issue by sdash-redhat** [openshiftio/openshift.io#3800]
## Description:
Setting up initial environments for Design Standard Wiki using Wordpress

Refer: Design Standards Wiki #3799

**Comment by mindreeper2420** [comment]
Environment is configured at www.uxd.fabric8.io

**Comment by mindreeper2420** [comment]
I believe this has been completed by https://github.com/openshiftio/openshift.io/issues/2872.

**Comment by sdash-redhat** [comment]
Ok. Please close this.. But there may be some changes to the menu structure etc.. depending on the scope and what items are going to be covered. For that if required we can create another quick task and will update that one.
