### ISSUE TITLE
Initial Explorations of the Commonly Used Components & Patterns Across the Applications [13]

### ISSUE THREAD

**Issue by sdash-redhat** [openshiftio/openshift.io#3801]
## Description:
Initial explorations on the applications to identify and list out the commonly used patterns and components across the applications namely _Openshift.io_  . 
This activity will include: 

- Review the applications in terms of various aspects and attributes to identify and list the commonly used patterns/components/widgets etc.
- Review the applications and identify the areas of inconsistencies in terms of visual and interactions
- Scan through the issues list to identify and list the commonly reported issues that might impact the designs. 
- Compare the collection against the list of PatternFly standards and guidelines. 
- Compare the collections against standard principles and standards/best practices. 
 

Refer: Design Standards Wiki #3799

**Comment by sdash-redhat** [comment]
@muruGanesan @mindreeper2420 
Can we look into the OSIO and list down the inconsistencies?

**Comment by AshishDurgude** [comment]
I am currently working on OSIO review for design standards.

**Comment by sdash-redhat** [comment]
We went through the identified list by Catherine and Serena. Along with this, Ashish captured some points in his quick scanning of OSIO. Then based on the common affected areas/components, it looks like the following can be the structure of the Wiki to be fixed in alphabetical order): 
 
https://drive.google.com/open?id=1iUWRui7Y2KFd_dG7l0h3J0Idu95o1Qq8


![wiki-structure-0 1](https://user-images.githubusercontent.com/27761023/41965226-bc5b85c6-7a19-11e8-805f-1e2bce9b3947.png)

Now each of these can be addressed as different stories and be solved. 


@catrobson @mindreeper2420 @muruGanesan @AshishDurgude @serenamarie125

**Comment by AshishDurgude** [comment]
### **1. Spreadsheet for standardization research:**
There are 6 pages in a spreadsheet.
Page 1: List of PatternFly Components
Page 2: Initial draft of wiki
Page 3: OSIO Comparison with Patternfly and Consistency
Page 4: OpenShift Online Comparison with Patternfly and Consistency
Page 5: iPass Comparison with Patternfly and Consistency (Not done)
Page 6: Common Component flow (Work in progress)
Here is the Spreadsheet link:
https://docs.google.com/spreadsheets/d/1xsU6u1DOoOZC0o3MSM1aEkiCEBDnXSQXqIw5Ss1CbSc/edit?usp=sharing

### **2. Invision for standardization (Finding patterns & inconsistency):**
There are 6 screens in a spreadsheet.
Screen 1-5 : Visiting OpenShift.io for finding patterns and inconsistencies
Screen 6: Visiting OpenShift Online for finding patterns and inconsistencies
Here is the InVision link:
https://redhat.invisionapp.com/share/KMMGT6VW3SE

**Comment by AshishDurgude** [comment]
@mindreeper2420 Hi Adam. Can you update wiki website's left sidebar (Vertical Navigation) based on the hierarchy mentioned in the below document?

https://docs.google.com/spreadsheets/d/1A41zIQV3qqqx_TtPCjBI4KILHm7pRH23Y0rwccsdT34/edit?usp=sharing

**Comment by sdash-redhat** [comment]
@mindreeper2420 @AshishDurgude 
I will update the menu. We can later make changes based on any further feedback we receive in coming times, and it can evolve over the time.

**Comment by sdash-redhat** [comment]
We have identified the list of issues and created stories against each of them, (will be adding some more) under this parent epic https://github.com/openshiftio/openshift.io/issues/3799
We can now focus on the individual stories that are created. 

So closing this issue.
