### ISSUE TITLE
Recent spaces lists non-existing spaces

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3803]
1. create space `aaa`
2. create space `bbb`
3. go to My spaces and remove `aaa`
4. go to Account home

expected:
* Recent spaces card contains only `bbb` (and other previously visiting spaces that still exist)

actual:
* Recent spaces card contains both `aaa` and `bbb`
* clicking on `aaa` results in 404

**Comment by ldimaggi** [comment]
Looks like a duplicate of: https://github.com/openshiftio/openshift.io/issues/3783  ?

**Comment by ppitonak** [comment]
Yes, duplicate
