### ISSUE TITLE
Evaluating Argo

### ISSUE THREAD

**Issue by lordofthejars** [openshiftio/openshift.io#3805]
https://applatix.com/open-source/argo/
#3570

**Comment by joshuawilson** [comment]
please add labels

**Comment by lordofthejars** [comment]
I have no rights for doing it nor add myself as assignee

**Comment by joshuawilson** [comment]
invite sent, accept and you will ;)

**Comment by sthaha** [comment]
Closing this as this can be tracked in planner if need be
