### ISSUE TITLE
Dependecy Editor : unable to scroll to next section from dependency editor

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#3809]
- unable to scroll to next section from dependency editor with arrow

Steps : 

1. Login to http://prod-preview.openshift.io/
2. Opt-in for internal feature
3. Select Mission and Runtimes
4. Move to Dependency editor section
5. Click down Arrow 
6. Move to next section
7. Scroll up to Dependency Editor section
8. Click Down arrow ( Can't scroll to next screen )

<img width="1680" alt="screen shot 2018-06-15 at 11 53 57 pm" src="https://user-images.githubusercontent.com/5129024/41483644-73a09b08-70f7-11e8-9323-c9464b4458f9.png">

**Comment by arunkumars08** [comment]
Changes for the same are available in prod-preview. Please feel free to reopen if things are not as expected.
