### ISSUE TITLE
Che preview link for new Vert.x Basic app does not work

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#381]
1. Create new space.
2. Add vert.x basic project with all defaults.
3. Create workspace
4. Go into Che
5. Run the app (from Che)
6. Preview URL is offered; click it
7. I get the generic "Application is not available" response from OpenShift (even if I wait a really long time). Expectation is that I see the basic vert.x app.
7a. A curl command from Che terminal to http://localhost:8080 does return valid data (i.e. the app is running correctly)

**Comment by l0rd** [comment]
This issue is tracked [here](https://github.com/redhat-developer/rh-che/issues/92) and we should are currently working on that. The workaround for now is to replace `server-8080-tcp` with `tomcat` in the URL.

**Comment by l0rd** [comment]
[PR](https://github.com/eclipse/che-dockerfiles/pull/111) to fix the problem provided. Will update as soon as the fix will be available on OSIO.

**Comment by l0rd** [comment]
@kbsingh @dharmit the PR that fix this issue has been merged 12 hours ago but the new image (registry.centos.org/che-stacks/vertx) has not been built by the CentOS Container Pipeline yet. Is there a way to have more visibility about what is going on?

**Comment by l0rd** [comment]
This is solved now: the preview URL should work fine. There is no need to update Che version to verify it, you just need to start a new workspace.

We had some feedback about the URL naming: it contains the word `tomcat` even if there it's not served by tomcat. We should address that too in current sprint (c.f. https://github.com/redhat-developer/rh-che/issues/92).

I'm closing that. Feel free to reopen if needed.
