### ISSUE TITLE
UX changes for Dependency Editor

### ISSUE THREAD

**Issue by AshishDurgude** [openshiftio/openshift.io#3813]
steps to access the feature

Login into prod-preview.openshift.io
Go to Top right username -> Settings -> Features opt-in
Select 'Internal Experimental Features'
Go to Home screen
Create a new space or pick an existing space
Create a new application
Select quick start flow
You should see dependency editor as a 2nd step
Initially, it will be just with a button to let the user select mission and runtime.

Select mission and runtime (eg. Health-check and Wildfly)

You can see Dependency editor showing up in the second step.

- [ ] **Change 01: "Browse All Dependencies" link font should be "Open Sans SemiBold" Currently it's "Open Sans Regular". (Image 01)**

**

> **Image 01**

**
![test2](https://user-images.githubusercontent.com/13097334/41526383-b3926384-7301-11e8-8b62-604e3d4c8aeb.png)

- [ ] **Change 02: Search button in modal is not aligned with the search box. (Image 02)**

**

> **Image 02**

**
![test1](https://user-images.githubusercontent.com/13097334/41526177-06a358e0-7301-11e8-9e0b-b484d842be60.png)

- [ ] **Change 03: Search bar has different placeholder text style. Follow the "Select Dependencies" page search bar to refer a placeholder style. (Image 03)**

- [ ] **Change 04: Spacing between placeholder text and the search box is not same. Follow the "Select Dependencies" page search bar to refer spacing. (Image 03)**

- [ ] **Change 05: Search icon of search buttons are not same. Follow the "Select Dependencies" page search bar to refer search icon style. (Image 03)**

**

> **Image 03**

**
![test3](https://user-images.githubusercontent.com/13097334/41530254-3bd9f8d2-730d-11e8-8095-12f985668a7f.png)

- [ ] **Change 06: "Choose Dependency" text size should be 16px. (Image 04)**

- [ ] **Change 07: Side navbar is not following a patternfly's active menu state.(Image 04)**

- [ ] **Change 08: There should not be any space (padding) between sidebar and "Dependencies selected" card. (Image 04)**

- [ ] **Change 09:  The text should be "0 Dependencies selected" instead of "Dependencies selected". (Image 04)** 

- [ ] **Change 10:  Search bar alignment is not proper. (Image 04)**

**

> **Image 04**

**
![test4](https://user-images.githubusercontent.com/13097334/41529005-5ab7f2a8-7309-11e8-937e-4c7a4b861542.png)

- [ ] **Change 11:  Toast notification should appear on the right-end side. (Image 05)**

- [ ] **Change 12:  There should be a spacing of atleast 15px to 20px between "Dependency tag" and “Added” status. (Image 05)**

**

> **Image 05**

**
![test5](https://user-images.githubusercontent.com/13097334/41531590-6c5d997e-7311-11e8-9ebc-67a24809bf22.png)

- [ ] **Change 13:  "No Insights Found" should be a heading (h1) with 24px font size. (Image 06)**

**

> **Image 06**

**
![test6](https://user-images.githubusercontent.com/13097334/41531985-dda5de38-7312-11e8-840e-8ec3fd110d23.png)

**Comment by AshishDurgude** [comment]
One more issue related to UX changes in Dependency editor
https://github.com/openshiftio/openshift.io/issues/3775

**Comment by arunkumars08** [comment]
Changes for the same are available in prod-preview. Please feel free to reopen if things are not as expected.
