### ISSUE TITLE
Extract feature-flag service out of fabric8

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#3815]
so that Planner can use the service

**Comment by joshuawilson** [comment]
@corinnekrych this feels like a story level thing, can you list out tasks that are needed to complete it.

**Comment by corinnekrych** [comment]
not sure about the tasks yet. we'll need to decide where/what we need to move. Once I got a closer look I'll add.

**Comment by corinnekrych** [comment]
After further thinking, here a rough idea of different tasks associate to the work:
- [ ] Create `ngx-feature-flag` (`ngx-toggles` already used on npm)
- [ ] Build: run test, demo, make a new npm release
- [ ] Add demo like [ngx-launcher](https://github.com/fabric8-launcher/ngx-launcher)
- [ ] Add CI/DD
- [ ] Make fabric-ui uses ngx-feature-flag + clean code
- [ ] Move documentation from fabric8-ui(leave a note of newly hosted doc) to ngx-feature-flag README
- [ ] Use `ngx-feature-flag` in Planner standalone

For each of them, Iet's create separate GH issue as we go implement them.
cc @joshuawilson @nimishamukherjee
