### ISSUE TITLE
Prod-preview gettingstarted page is empty

### ISSUE THREAD

**Issue by Katka92** [openshiftio/openshift.io#3816]
When I login into prod-preview.openshift.io the only thing I can see is header and empty space. 

![screenshot from 2018-06-18 14-45-52](https://user-images.githubusercontent.com/29278800/41537579-33b0e656-7309-11e8-8e2d-80d04b21208e.png)

**Comment by sbose78** [comment]
I changed the url to `/_home` and that allowed me to move on. The auto-redirect isn't working at the moment.

**Comment by sbose78** [comment]
There's a 400 being returned while fetching the oso token.

```
Request URL:https://auth.prod-preview.openshift.io/api/token?force_pull=true&for=https://api.starter-us-east-2a.openshift.com/
Request Method:GET
Status Code:400 Bad Request
```
```
{"errors":[{"code":"bad_parameter","detail":"Bad value for parameter 'for': 'https://api.starter-us-east-2a.openshift.com/' (expected: 'URL to a github.com or openshift.com resource') - ","status":"400","title":"Bad parameter error"}]}
```

and then a 400 when trying to link - 

```
Request URL:https://auth.prod-preview.openshift.io/api/token/link?for=https://api.starter-us-east-2a.openshift.com/&redirect=https%3A%2F%2Fprod-preview.openshift.io%2F_gettingstarted%3Fwait%3Dtrue
Request Method:GET
Status Code:400 Bad Request
```

```
{"errors":[{"code":"bad_parameter","detail":"Bad value for parameter 'for': 'https://api.starter-us-east-2a.openshift.com/' (expected: 'URL to a github.com or openshift.com resource') - ","status":"400","title":"Bad parameter error"}]}
```

**Comment by sbose78** [comment]
calling 'https://auth.prod-preview.openshift.io/api/token?for=openshift'
returns a "{"errors":[{"code":"internal_error","detail":"unable to load provider for cluster URL https://api.starter-us-east-2a.openshift.com","status":"500","title":"Internal error"}]}
"

Looks like a problem with looking up the cluster config.

**Comment by joshuawilson** [comment]
I see a 404 that is CORS related but I don't have an issue using prod-preview. 

Can you try a hard refresh? (ctl + shft + R)
maybe logout and login. Sometimes you get logged out on the service but the app in the browser doesn't know it.

**Comment by ppitonak** [comment]
Neither `Ctrl + Shift + R` nor logout & login helped

**Comment by pbergene** [comment]
On it.

**Comment by alexeykazakov** [comment]
The issue was caused by wrong OSO cluster config secret update in preview. The secret was updated (to wrong value) by mistake.

**Comment by pbergene** [comment]
Confirmed restored correct values.  Got preview working for me.
