### ISSUE TITLE
Prod-preview could not start workspace

### ISSUE THREAD

**Issue by Katka92** [openshiftio/openshift.io#3817]
When trying to start workspace, there is an internal error.

![screenshot from 2018-06-18 15-16-08](https://user-images.githubusercontent.com/29278800/41538069-94157416-730a-11e8-922a-b26d8e2c70f3.png)

**Comment by ibuziuk** [comment]
@Katka92 could you please try now when rh-che is running against latest `6.7.1` ? is it still reproducible ?

**Comment by Katka92** [comment]
@ibuziuk Today I've tried it several times and seems it is not reproducible anymore.

**Comment by ibuziuk** [comment]
@Katka92 ok, going to close - feel free to reopen if it occurs again
