### ISSUE TITLE
Application name validation can be bypassed via existing github repository when importing codebase

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#3818]
The application name should not start with a number, but this can be bypassed when importing a codebase by selecting a GitHub repository that has a name starting with a number. 

This eventually leads to a failed Jenkins build. See https://github.com/openshiftio/openshift.io/issues/3784

Steps to reproduce:

1. Have an existing GitHub repository with a name that is valid for GitHub but invalid for OSIO (e.g. `1234-4321`)
2. Import a new application with a name such as `abcd`.
3. Select the GitHub repository.
4. Observe application name is now set to the GitHub repository name and validation is not triggered.

Expected:
- Application name is invalid and user should not be allowed to continue.

Actual:
- Application name is accepted and user is able to continue.

Also bonus:

1. Write an invalid application name.
2. Select a GitHub repository with a valid application name (e.g. `abcd`)
3. See Application name changed to be GitHub repository name, but validation is not triggered so user cannot continue.

Expected:
- Application name is valid and user should be allowed to continue.

Actual:
- Application name is still considered invalid and user is not allowed to continue.

**Comment by joshuawilson** [comment]
why remove 'team/analytics'? it is the parent that makes for easier searches

**Comment by invincibleJai** [comment]
we mostly filter by `team/analytics/wizard` for launcher task as we have separate scrum/planning for it, `team/analytics` i felt is more to do with core analytics work. If you feel that makes search easier, will re-add it. :)

**Comment by joshuawilson** [comment]
I'll leave that to @sivaavkd and @GeorgeActon to decide. Then we can all follow that direction.

**Comment by invincibleJai** [comment]
Changes are in prod. In Import/create flow both repo name and app name shouldn't be dependent on each other i.e shouldn't be same. It can be closed
