### ISSUE TITLE
Vaildation of unique project name fails to allow user to select alternate project name

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#382]
Steps to recreate:
* Create a new space
* Create a new project in that space
* Attempt to create a 2nd project with the same name as the first project - this error is correctly trapped
* But - after changing the name of the project, the Next/Finish keys are not enabled

**Comment by ldimaggi** [comment]
![screenshot from 2017-07-20 16-24-12](https://user-images.githubusercontent.com/642621/28437387-694b9844-6d68-11e7-8b0c-2caa4f320c32.png)

**Comment by ldimaggi** [comment]
Workaround - Create a new space for each project.

**Comment by corinnekrych** [comment]
fixed in https://github.com/openshiftio/openshift.io/issues/966
