### ISSUE TITLE
[8] Performance Improvement for Dependency Editor APIs

### ISSUE THREAD

**Issue by animuk** [openshiftio/openshift.io#3820]
## User Story

Dependency Editor API response are currently not efficient and takes longer response times. Plan is to  - 

1. implement Caching mechanism in the APIs
2. Optimize Front API calls to remove the redundancy and error handling.
3. Stress testing the analytics APIs list for the dep editor for the optimal performance.

**Comment by animuk** [comment]
@invincibleJai fyi

**Comment by invincibleJai** [comment]
Have handled below pointers in dependency editor from UI side:

- On addition of dependencies from insights as well as from modal it shows up twice.
- On addition of dependencies from insights as well as from modal it gets added to core dependencies as well.
- On addition/removal of added dependencies insights API call is not having the correct payload.
