### ISSUE TITLE
Issue while filtering workitem

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3822]
Steps:

- Open https://openshift.io/openshiftio/openshiftio/plan?q=(space:020f756e-b51a-4b43-b113-45cec16b9ce9%20$AND%20typegroup.name:Requirements)
- Click WorkItemGroup Requirements
- Select filter-By Title 'notification' i'm getting loading
- And if you Toggle "Show Tree" on and off more "Filters" are added to the 'enabled filters

**Comment by rgarg1** [comment]
This is certainly Sev-1 as I reach a point of no return. See below:

![planner s1](https://user-images.githubusercontent.com/28748448/41601498-45d531b4-73f6-11e8-819a-263ee0029d90.png)

**Comment by joshuawilson** [comment]
Do we have a fix for this? If not, is someone working on it?
cc @nimishamukherjee @michaelkleinhenz

**Comment by nimishamukherjee** [comment]
@DhritiShikhar can you confirm if the work item creator can update the work item

**Comment by nimishamukherjee** [comment]
@joshuawilson we are looking into this.

**Comment by DhritiShikhar** [comment]
^ Creator which is non-collaborator.

@nimishamukherjee looking into it

**Comment by pbergene** [comment]
Auto-closed, re-opening once verified in prod.

**Comment by nimishamukherjee** [comment]
@Raunak1203 @rgarg1 please verify the fix on production

**Comment by Raunak1203** [comment]
Closing the issue,  verified in production
