### ISSUE TITLE
Mobile view of the deployments page could use some help.

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#3824]
On a mobile view (simulated with Chrome), interpreting the deployments page becomes very difficult. 
It would appear as though some icons are rendering outside of their cards, and the labels no longer match up with them in a logical fashion.

Screenshot:

![2018-06-19-103713_1919x991_scrot](https://user-images.githubusercontent.com/17230733/41604309-e7d20c16-73ac-11e8-9145-7347e3a82c62.png)

**Comment by aptmac** [comment]
Related: https://github.com/openshiftio/openshift.io/issues/1909

But this issue is mobile specific, and may require additional/different discussion than just generic small screen sizes.

**Comment by joshuawilson** [comment]
I don't think we have any designs from @openshiftio/uxd-team on mobile screens for the Deployments page.

**Comment by mindreeper2420** [comment]
Correct - but I'll also add that there are no mobile specific screens for any of the pages. Ideally, each page would/should use the built-in responsive nature of Bootstrap.

**Comment by muruGanesan** [comment]
@joshuawilson,
I agree with @mindreeper2420,  
(1) I am not sure OSIO screens are responsive in nature
(2) We also need to understand the PM's point of view or requirements  

FYI: @catrobson & @serenamarie125
