### ISSUE TITLE
Visiting Planner changes HTML header font-sizes on the Deployments page

### ISSUE THREAD

**Issue by aptmac** [openshiftio/openshift.io#3825]
Currently, visiting the Planner and then viewing the Deployments page results in the h3/h4 font-sizes to be decreased by roughly ~1px. The [f8ui _typography.less](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/assets/stylesheets/shared/_typography.less) [0] rules get overshadowed, and for example, the h3 font-size goes from 1.3em to 15px.

![css](https://user-images.githubusercontent.com/10425301/41607128-43a3d3ac-73b3-11e8-8237-d6fee7137c03.png)

Deployments page:
![before](https://user-images.githubusercontent.com/10425301/41606956-e718a3a6-73b2-11e8-801e-123ce529751d.png)

Deployments page after visiting Planner:
![after](https://user-images.githubusercontent.com/10425301/41606952-e54882e4-73b2-11e8-9a1e-2e47ca17e880.png)

Side-by-side comparison:
![sidebyside](https://user-images.githubusercontent.com/10425301/41606834-9a24b3b4-73b2-11e8-8b15-10cb9e9c636d.png)

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/assets/stylesheets/shared/_typography.less

**Comment by joshuawilson** [comment]
Over time we have had several issues on this. This is due to how Planner handles CSS. We hope to align them as we move to extensibility.

**Comment by aptmac** [comment]
fixed in: https://github.com/fabric8-ui/fabric8-planner/pull/2701
