### ISSUE TITLE
Keyboard Access for Planner(5)

### ISSUE THREAD

**Issue by Veethika** [openshiftio/openshift.io#3829]
To come up with a keyboard access guideline for Planner in OSIO.
(Related to #1840 #3502)

### **Verification Criteria**

- [x] Map the Planner controls to existing keyboard commands listed here: https://www.ssa.gov/accessibility/keyboard_nav.html

- [x] Identify areas/controls within Planner that would require additional commands

- [x] Propose additional set of commands if needed

- [x] Get the controls reviewed 

- [x] Provide customization roadmap for single letter keyboard shortcuts

- [x] Check for conflicts with other areas within OSIO

**Comment by Veethika** [comment]
@serenamarie125 @nimishamukherjee @muruGanesan here is the new story I'll be using to track the progress.

**Comment by mindreeper2420** [comment]
This is also an important resource: https://www.w3.org/WAI/WCAG21/Understanding/character-key-shortcuts.html. 

Per WCAG guidelines, any interface that has custom keyboard shortcuts that only use a single letter (such as C to create or D to delete), it must allow users to turn them off, remap them or only apply the shortcut when the component is in focus.

**Comment by Veethika** [comment]
> Map the Planner controls to existing keyboard commands listed here: https://www.ssa.gov/accessibility/keyboard_nav.html

@michaelkleinhenz @nimishamukherjee @mindreeper2420 @catrobson @serenamarie125 Here is the spreadsheet with control  to command mapping for Planner: https://docs.google.com/spreadsheets/d/1cATzs0UyUgeZ_cn32LCTQlVHJLsPcfmw3KUTYQN6n-E/edit#gid=0 (Please look at both the sheets enclosed)
