### ISSUE TITLE
Review new e-mail templates for team and space invitations

### ISSUE THREAD

**Issue by sbryzak** [openshiftio/openshift.io#3836]
This PR in the notification service requires review of the wording and layout for the two new e-mail templates it adds:

[https://github.com/fabric8-services/fabric8-notification/pull/72/files](https://github.com/fabric8-services/fabric8-notification/pull/72/files)

New templates:

- [template/invitation.space.noorg](https://github.com/sbryzak/fabric8-notification/blob/a0c70d4071f873813b225d97870e3f2484c1092e/template/invitation.space.noorg/body.html)

- [template/invitation.team.noorg](https://github.com/sbryzak/fabric8-notification/blob/a0c70d4071f873813b225d97870e3f2484c1092e/template/invitation.team.noorg/body.html)

**Comment by sbryzak** [comment]
Related issues:

[https://github.com/fabric8-ui/fabric8-ux/issues/941](https://github.com/fabric8-ui/fabric8-ux/issues/941)

[https://github.com/fabric8-services/fabric8-auth/issues/507](https://github.com/fabric8-services/fabric8-auth/issues/507)

**Comment by sbose78** [comment]
Hi @mindreeper2420 , could you please review the email templates.
CC: @lwrigh @muruGanesan

**Comment by sbryzak** [comment]
A couple of screenshots also, which might be useful:

![image](https://user-images.githubusercontent.com/165507/41651916-1b9f4388-74c5-11e8-80fc-0025f27e0cdd.png)
![image](https://user-images.githubusercontent.com/165507/41651945-31095d8a-74c5-11e8-9829-364f4fc7dba7.png)

**Comment by muruGanesan** [comment]
@sbryzak, @sbose78,

Please see the proposed design from UXD team:
https://redhat.invisionapp.com/d/main#/console/13657683/298638714/preview



<img width="1509" alt="image" src="https://user-images.githubusercontent.com/26006817/41661947-881b342a-74bd-11e8-8f07-1544c624958c.png">

**Comment by lwrigh** [comment]
@sbryzak @sbose78 @muruGanesan @mindreeper2420  The screenshot above is what I had suggested for the space invite email template. The copy on it needs to be reviewed but the general layout was informed by some of the other emails that Openshift.io sends out. I can add the space invite email template back into the wireframes ( https://redhat.invisionapp.com/share/3WLEP2NCDRT ) for reference.

**Comment by sbose78** [comment]
Thanks @muruGanesan .
"..you will be able to complete these sort of actions.." , @lwrigh , are we implying that we are gonna put the list of scopes that this role is gonna give the user in the email. ( "example, "create workitem" ) ?

CC: @sbryzak

**Comment by sbryzak** [comment]
@lwrigh I have a similar query as @sbose78 - currently we don't have any easy way to describe the privileges that will be gained by the user if they accept the invitation, as per the above screenshot.  Also, it is possible for a user to be invitied to accept multiple roles - how should this be reflected in the first sentence of the e-mail?  For example, a user might be offered both the contributor and administrator roles - how would the wording look in this case?

**Comment by lwrigh** [comment]
@sbose78 @sbryzak In that case, for the first iteration we can omit that part of the copy. I've been designing with the intention that a user can only have one role per space invite so in that case a user might have to receive multiple multiple space invites if they were to have multiple roles in space since I thought we had discussed users not having multiple roles in a space. 

Here's an updated Invision link to the email space invite template: https://redhat.invisionapp.com/share/T3LMTHC7GRU#/304813100_Space_Invite_Email I got rid of the text about the specifics of the role.

**Comment by sbryzak** [comment]
Here are the updated templates - I modified the design from the wireframes to take into account multiple roles. The first one is for a team invite, the second one is for a space invite.

![image](https://user-images.githubusercontent.com/165507/42139950-b84f5baa-7dda-11e8-804b-b180b684a358.png)

![image](https://user-images.githubusercontent.com/165507/42139957-d4109142-7dda-11e8-8738-11a08382aa8d.png)

**Comment by sbryzak** [comment]
There don't seem to be any further comments here, so closing this issue.
