### ISSUE TITLE
Update User Settings Heading to Match Location

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#3839]
Currently, the User Settings page has a heading that just states "Settings" with a gear icon. I believe it would be more beneficial to have this say "User Settings", without the gear icon, to better identify where the user is and what that page is nested under.

<img width="655" alt="screen shot 2018-06-21 at 10 08 55 am" src="https://user-images.githubusercontent.com/4032718/41724255-2901a072-753b-11e8-97d8-c041f965fffc.png">

**Comment by mindreeper2420** [comment]
@mceledonia I wanted to add this issue in, as it looks like this pattern may become used by @lwrigh as well. I think we could make these clearer for the user and give some more context.

**Comment by mceledonia** [comment]
@mindreeper2420 This sounds good to me. Let's make the changes you listed above, we can also carry this design over into "Space Settings" in the same fashion as discussed earlier.

**Comment by mceledonia** [comment]
@mindreeper2420 This sounds good to me. Let's make the changes you listed above, we can also carry this design over into "Space Settings" in the same fashion as discussed earlier.

**Comment by kwk** [comment]
Why is this closed? Can you verify this in the deployment (prod/prod-preview) and not close it with a commit?

**Comment by mindreeper2420** [comment]
It is on prod-preview
<img width="350" alt="screen shot 2018-06-26 at 11 11 36 am" src="https://user-images.githubusercontent.com/4032718/41921812-b917483e-7931-11e8-9212-79506e6cdb6a.png">
