### ISSUE TITLE
allow the E2E tests to be run inside a CI pipeline 

### ISSUE THREAD

**Issue by jstrachan** [openshiftio/openshift.io#384]
we need a way to reuse the E2E tests inside a CI pipeline so that we can:

* create a PR image of the service the PR is against
* deploy fabric8 to a test namespace with the updated image applied
* create a new user + tenant for the PR
* run the E2E tests as the new user
* report the E2E test results to the build log
* when the PR is closed, tear down the fabric8 system and associated tenants

This will then allow the result of the PR to be tested automatically - but also manually while the PR is open.

One issue is going to be each PR is going to use a fair amount of resources. So we may wish to eagerly tear down resources for each commit in a PR; so that there's only 1 environment per PR.

If the tests all pass we may want to eagerly tear them all down too (maybe with a timeout or folks could maybe comment on the PR to disable teardown until after the PR closes).

**Comment by joshuawilson** [comment]
I think we are going to need to coordinate between @ldimaggi @kbsingh @aslakknutsen and @alexeykazakov to make this happen.

**Comment by jstrachan** [comment]
its more the case of just figuring out the necessary Jenkinsfile pipeline steps; we've already got the E2E tests which we can run using the fabric8-ui source via node. So I'd have thought its more of a James issue really - but sure anyone is free to dive in and help @rawlingsj

**Comment by joshuawilson** [comment]
Your description sounds like it needs resources not just a script. Am I missing something?

**Comment by jstrachan** [comment]
its a pipeline running in fabric8, like all of our other CI / CD pipelines and during its execution it creates kubernetes/openshift resources (just like when we deploy a new fabric8 console for a PR).

So yes - it requires the resources of the kubernetes/openshift cluster in which fabric8 CD is running

**Comment by joshuawilson** [comment]
ok, thanks

**Comment by jstrachan** [comment]
we've made some progress running the E2E tests in a Jenkins pipeline on fabric8:
https://github.com/fabric8io/fabric8-test/blob/master/Jenkinsfile

then we're close to having the E2E tests parameterisable by PRs now
https://github.com/fabric8io/fabric8-test/issues/129

 so we're getting close!

**Comment by jstrachan** [comment]
the above works great for testing booster PRs or che/jenkins/team YAML PRs - to test UI + forge changes we'll need to also deploy a new forge service per forge PR that we can keep around until the UI PR is also tested - and having the custom UI service point at the PR of the forge

**Comment by ldimaggi** [comment]
See:

https://github.com/fabric8-ui/fabric8-ui/pull/1873 
https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/909

**Comment by ldimaggi** [comment]
Closing - the related issues and PRs are:

- https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/909 (closed)
- https://github.com/fabric8-ui/fabric8-ui/pull/1873 (closed - made obsolete by 2341)
- https://github.com/fabric8io/fabric8-pipeline-library/pull/371  (merged)
- https://github.com/fabric8-ui/fabric8-ui/pull/2341 (Dec 22 - not yet merged - tests are now running on PR)
- https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-ui/view/change-requests/job/PR-2341/
