### ISSUE TITLE
Recent Active Pipelines link in Homepage is invalid

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#3841]
Recent pipelines link in Homepage is invalid and to lead to 404:

![image](https://user-images.githubusercontent.com/3263627/41762637-a9492140-75fb-11e8-9eed-33a79c62c3bd.png)

The correct Pipelines page is:
`https://openshift.io/osio-ci-ee9/osio-ci-ee9-BDD-space-2018-06-21T17-42-02/create/pipelines`

![image](https://user-images.githubusercontent.com/3263627/41762757-1384c168-75fc-11e8-833c-6b914b891d11.png)

But the link leads to the wrong link leads to:
`https://openshift.io/_home/undefined/osio-ci-ee9-BDD-space-2018-06-21T17-42-02/create/pipelines`
which is invalid.

**Comment by pmacik** [comment]
The recent pipelines show Build 3 while the Pipelines page show Build 1.

Likely caused by https://github.com/openshiftio/openshift.io/issues/3840 (https://github.com/openshiftio/openshift.io/issues/3742).

**Comment by aptmac** [comment]
The `contextPath` portion of the URL is listed as undefined from the `Contexts.current` [0]. From a bit of playing around, the line of code that sets the `contextPath` [0] is not being hit. As a result, the URL for the link is broken in the component [1].

I'm wondering .. is it necessary to retrieve the value from the Contexts when the namespace can be retrieved from the same config that is used to generate the rest of the hyperlink? For example, I whipped up a commit that does this [2] and it seems to be working fine; is there a particular reason that the `Contexts.current` is required, and is the value for `namespace` always correspond to the account name like this? @jiekang thoughts?

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/dashboard-widgets/recent-pipelines-widget/recent-pipelines-widget.component.ts#L37
[1] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/dashboard-widgets/recent-pipelines-widget/recent-pipelines-widget.component.html#L59
[2] https://github.com/aptmac/fabric8-ui/commit/dfd49a59056e58ea97a5aa9be2c7cb61dd094406#diff-0f9f68d891087e9b7384f274b6eb0bd7R59

**Comment by jiekang** [comment]
I'm not sure. I don't know the history behind `Contexts.current`. It seems to be a regression that it's no longer being set.

**Comment by jiekang** [comment]
This must have been broken for a long time otherwise? Since the recent pipelines widget is on _home, the context will not have an associated space. I think your solution is fine.

**Comment by sthaha** [comment]
I am going to remove the build-cd tag since it seems like a UI issue. Please add it back if you think that isn't the case.

**Comment by joshuawilson** [comment]
@sthaha the Platform team is not the UI team. While we do help, this is ultimately the Build team's responsibility, even if all you can do is work with a UI dev from Platform. You still own it.

**Comment by sthaha** [comment]
@aptmac thanks for helping us. 

@joshuawilson 
 >  this is ultimately the Build team's responsibility

Agreed, I am adding the label back
