### ISSUE TITLE
404 error on clicking View full details

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3845]
Steps:

- Open https://openshift.io/nmukherj/fabric8-planner/plan?q=(space:e0e8e630-ecce-497f-b394-0061a18edb22%20$AND%20typegroup.name:Work%20Items)&showTree=true
- Click on workitem title to open quick preview
- In the quick preview, click on  "View full details "
- 404 error is thrown

![404](https://user-images.githubusercontent.com/34271052/41830741-5a3139e6-7860-11e8-8ce8-51a62b658a2c.gif)

**Comment by vikram-raj** [comment]
This issue has been fixed and in prod.
