### ISSUE TITLE
restrict few specific cluster to be default backend for oso-proxy

### ISSUE THREAD

**Issue by nurali-techie** [openshiftio/openshift.io#3846]
There is a difference in how the 2 and 2a cluster work compared to 1a and 1b. It's being investigated (HK Issue), but 1a and 1b can't be used as a 'default' cluster for the CORS stuff (it returns unauth on all CORS requests). Since we're currently 'randomly' selecting a cluster there is a certain chance we kill the UI on redeploy. Until the root cause is found, maybe we should add a "don't use 1a or 1b as default"

Here,
1a = https://api.starter-us-east-1a.openshift.com
1b = https://api.starter-us-east-1b.openshift.com

**Comment by piyush1594** [comment]
@nurali-techie Seems like the PR tagged is merged, can we close this? If not please add the respective labels and severity
