### ISSUE TITLE
allow the E2E tests to be run for a single quickstart version

### ISSUE THREAD

**Issue by jstrachan** [openshiftio/openshift.io#385]
once we can easily run the E2E tests in a CI pipeline
https://github.com/openshiftio/openshift.io/issues/384

it would be nice to do the same thing for a given quickstart and version. We can then use this in the pipelines whenever a quickstart changes.

The main difference to https://github.com/openshiftio/openshift.io/issues/384 is that we'd need to:

* parameterise the quickstart in the E2E test script
* configure the Forge wizard to be able to load a specific quickstart + version

We could share the same fabric8 installation for many of these tests, since we only need to test that a new project can be created and that this new project is built OK.

The only issue is to ensure the forge wizard can be parameterized correctly to return the given quickstart + version inside the test. I guess the best test may be to try do a PR against the forge docker image, then use this new forge docker image in the E2E test. 

To optimise resource usage we could maybe just have a custom fabric8 console + forge for each quickstart CI test - but reuse all the other resources (e.g. share keycloak, wit, tenant and the tenant services across CI tests)

**Comment by qodfathr** [comment]
@ldimaggi another old one. Did this get done, or, if not, is it still worth doing?

**Comment by ldimaggi** [comment]
We should keep this one open - I started looking at doing this for the RHOAR boosters, we should do the same for the OSIO quickstarts.

**Comment by sthaha** [comment]
@ldimaggi any updates on this? are we good to close this?

**Comment by ppitonak** [comment]
it's possible to configure e2e tests to run with a specific booster, closing
