### ISSUE TITLE
Git commit and Push Not Triggering Pipeline

### ISSUE THREAD

**Issue by piyush1594** [openshiftio/openshift.io#3851]
When you go to che workspace and do some changes, then git commit and git push, it is not triggering a pipeline

Steps to reproduce:

1. Create a booster application.
2. Open Che Workspace.
3. Do some changes, do git commit and push.

See no pipeline get triggered.

**Comment by sthaha** [comment]
Closing this as this seems to work fine. The thing is that you won't see that under `Pipeline` page in os.io as expected.
