### ISSUE TITLE
Navigation bar header Backlog needs css color change

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3858]
Color of Navigation bar backlog looks fine in detail page 
![screenshot from 2018-06-26 10-27-11](https://user-images.githubusercontent.com/34271052/41890074-8212ef10-792b-11e8-92e2-269a20019f38.png)

but in the list display it needs some changes ( as header and side panel color is different)
![screenshot from 2018-06-26 10-29-23](https://user-images.githubusercontent.com/34271052/41890145-cfdb6772-792b-11e8-812e-9a44c1eb9143.png)

**Comment by joshuawilson** [comment]
@openshiftio/uxd-team

**Comment by mindreeper2420** [comment]
Discussions are currently taking place around this. The only area affected (at the moment) is Planner. I will try to find the previous issues and link them to this.

**Comment by catrobson** [comment]
Is the same component/code used for the secondary navigation in this situation and the secondary navigation in situations with a header such as Profile ({username}/_profile) or Space Settings ({spacename}/_settings)?  Ideally I think we want the secondary navigation where there is no header in use (Planner, Dashboards, etc) to be the dark gray they always were.  Only when we have that additional header ABOVE the navigation do we want the navigation to swap to a light gray like shown here.  @joshuawilson who can we work on this with from the platform team?

**Comment by joshuawilson** [comment]
@catrobson I'm unsure what you want from us. This sounds like a styles change. Do you want something more dynamic? 

You can work with @christianvogt and/or me on this.

**Comment by GeorgeActon** [comment]
@catrobson couldn’t decide if this was a feature request or a bug. Feel free to change it.

**Comment by catrobson** [comment]
@joshuawilson I want to understand if the secondary navigation already is, or can be, broken into two distinct implementations:

Implementation 1:  Used for any time the secondary navigation is directly attached to the primary navigation (sits right below it).  We would use a dark gray navigation in these situations.

Implementation 2:  Used for any time the secondary navigation is shown below a header area, not attached directly to the primary navigation (ie. User Profile).  Would use a light gray navigation in these situations.

**Comment by joshuawilson** [comment]
They can be independent if you want them that way.

**Comment by sunilmalagi** [comment]
@Raunak1203 I am not working on this issue right now and I am taking out my name and please include me if required later...

**Comment by muruGanesan** [comment]
@Raunak1203,
UX team addressed this issue in #4375. 
Please review the same and close if it addressed.
https://redhat.invisionapp.com/d/main#/console/15579519/323634781/preview

**Comment by Raunak1203** [comment]
@muruGanesan removed UX labels.
Thanks!

**Comment by joshuawilson** [comment]
@muruGanesan I can't view the invision link.

**Comment by joshuawilson** [comment]
Does this PR fix this issue? 
https://github.com/fabric8-ui/fabric8-ui/pull/3364

**Comment by muruGanesan** [comment]
@joshuawilson,
Please try this link:
https://redhat.invisionapp.com/share/MBOEF1JX4VD#/323634781_Space_Plan

**Comment by aptmac** [comment]
@muruGanesan I think @joshuawilson meant along the lines of does the PR that was merged meet the criteria to close this issue. There are attached screenshots in the PR that match the mock-ups you've posted.

**Comment by muruGanesan** [comment]
@aptmac, the implementation matches with #4375  recommendation.

**Comment by aptmac** [comment]
Great, then this is closed as of: https://github.com/fabric8-ui/fabric8-ui/pull/3364
