### ISSUE TITLE
sso.openshift.io redirected you too many times.

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#386]
When clicking on the Create Workspace link/button and when it is attempting to open the next tab for Che.

The workaround is to always use an Incognito window in Chrome.

**Comment by joshuawilson** [comment]
@dlabrecq could this be related to the change you made to the codebases?

**Comment by dlabrecq** [comment]
Possibly, but not sure why an incognito window would be a workaround -- same http request. I've seen this in the past, but clearing the browser cache had always resolved it.

**Comment by dlabrecq** [comment]
Actually, I no longer have a retry statement for the http request. It's the same request, just a longer timeout.

**Comment by dlabrecq** [comment]
Did some testing on openshift.io, but I'm not able to reproduce. 

Che opens in a new tab for me. Che fails to start the workspace, but I can at least get that far -- a different issue.

**Comment by ibuziuk** [comment]
I also can not reproduce so far. I had this problem just after update - cleaning cookies and cache helped and I was not able to reproduce redirect issue ever after. @burrsutter could you do cache / cookies clean-up and give it another go ?

**Comment by burrsutter** [comment]
I have been cleaning browser history with
https://screencast.com/t/9sJR1ciqZ

It turns out that Incognito is an imperfect workaround.
https://screencast.com/t/kmTRU1PDbQg
This happened after I had let Che stay open (in an Incognito window) and let the machine sleep overnight.  Attempting to interact with the UI again caused
"
This page isn’t working

che-burrsutter-che.8a09.starter-us-east-2.openshiftapps.com redirected you too many times.
Try clearing your cookies.
"

Or perhaps I need to more aggressively "reset" Chrome, for instance, it might be inheriting history from other instances of Chrome on other devices (phone, tablet, etc)?

**Comment by ibuziuk** [comment]
@burrsutter what is the che version ?

**Comment by ibuziuk** [comment]
@burrsutter is it still reproducible for you?

**Comment by l0rd** [comment]
@burrsutter I am closing this issue since haven't seen this since a long time (and I'm not using icognito). Feel free to re-open
