### ISSUE TITLE
[5] Dependency Editor UX Change list

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#3863]
Planner Feature: https://openshift.io/openshiftio/openshiftio/plan/detail/2678

The following document has the change list based out of feedback - https://docs.google.com/document/d/1cO1GEMnetAcONnuQTR2AEohyfT0JNtoPJQaQS5ToHXA/edit

Tasks:

- [x] - Error handling [missed Feature]
- [x] - Count of dependencies shown against 'All' is wrong. [Bug]
- [x] - Tooltips [Feature]
- [x] - addition of description for each packages [Feature]
- [x] - Is it ok to suggest the dependencies which are already a part of the core dependencies?
- [x] - change of the appearance of dependencies in case of multiple categories [Feature]
- [x] - Multiple list of dependencies
- [x] - Lazy loading of modal as it takes longer time [Improvement] - https://github.com/openshiftio/openshift.io/issues/3885
- [x] - Titlecase has to be followed [bug]
- [x] - Font styles [bug]
- [x] - Text vertical alignment [bug]
- [x] - Removal of suggested insights [https://github.com/openshiftio/openshift.io/issues/3874][discussion required]

**Comment by arunkumars08** [comment]
@parvathyvr @AshishDurgude Regarding tooltips, I have implemented them in this way. Please let me know if this sounds ok.

Content can be refined as well.

<img width="373" alt="screen shot 2018-06-28 at 2 21 10 pm" src="https://user-images.githubusercontent.com/7880465/42023929-aeb099d2-7ade-11e8-8547-7de5038f2270.png">
<img width="379" alt="screen shot 2018-06-28 at 2 21 01 pm" src="https://user-images.githubusercontent.com/7880465/42023930-aee15248-7ade-11e8-939c-10695794f2e3.png">
<img width="388" alt="screen shot 2018-06-28 at 2 20 48 pm" src="https://user-images.githubusercontent.com/7880465/42023931-af127fa8-7ade-11e8-91db-5ad25226c51c.png">

**Comment by arunkumars08** [comment]
Thanks @AshishDurgude. I think documentation and content changes for dependency editor is done by @Preeticp. I will get in touch.

**Comment by bmicklea** [comment]
This is a list of bugs, not a bug itself so I've changed the label from `bug` to `task`.

**Comment by arunkumars08** [comment]
@bmicklea Yes Brad. I think I missed that. Thanks for the change :)

**Comment by arunkumars08** [comment]
Things are in prod-preview. Closing this
