### ISSUE TITLE
Create space button sometimes not visible and not working

### ISSUE THREAD

**Issue by Katka92** [openshiftio/openshift.io#3864]
When having no space created and clicking "My spaces", I can see only white screen without the "Create space" button. 

![screenshot from 2018-06-26 12-50-37](https://user-images.githubusercontent.com/29278800/41906916-96ebc45c-793f-11e8-8db8-d1d6b6c8dd73.png)

Up right button still works, so I created space via this one. Then I click "My spaces" again and removed the space. Now the "Create space" button appears, but doesn't work.

![screenshot from 2018-06-26 12-56-15](https://user-images.githubusercontent.com/29278800/41907174-5b845ee6-7940-11e8-9ecd-6bee7599405a.png)

I can't see anything in browser console.

This behaviour is same for me on production and prod-preview too.

**Comment by jiekang** [comment]
From `my-spaces.component.ts`. Empty state seems to be part of `pfng-list` behavior. This would be something to resolve in Patternfly.

**Comment by jiekang** [comment]
@dlabrecq @dgutride could you take a look here? Maybe the empty state config is wrong, otherwise I think the patternfly component will need to be updated. If an empty state config exists, it might be okay as the default start state of the list.

**Comment by dlabrecq** [comment]
The reason the empty state is not displayed is that the `get spaces()` accessor is never called. The spaces subscription never initializes the _spaces variable.

It's possible that the pfng-list could display the empty state for undefined items, but think we can handle this differently in the my spaces component.

**Comment by dlabrecq** [comment]
The reason why the empty state button doesn't work is that the onActionSelect was removed from pfng-list. The line below was removed when the new space overlay was enabled?

`(onActionSelect)="handleAction($event)"`

**Comment by dlabrecq** [comment]
This method was also removed from the my spaces component.

```
 handleAction($event: Action): void {
    if ($event.id === 'createSpace') {
      this.openForgeWizard(this.createSpaceTemplate);
    }
  }
```

**Comment by jiekang** [comment]
@dlabrecq will you have time to fix these? Otherwise I can take this on. Thanks for the analysis!

**Comment by dlabrecq** [comment]
I'll be working on a similar (spaces subscription) issue regarding widget loading behavior on the home dashboard. I can take a look after that one, but don't wait for me.
