### ISSUE TITLE
Cannot promote application in firefox

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#3865]
Steps to reproduce
1. Create space
2. Create new application with "Rollout to Run" strategy
3. Go to pipeline page and wait until the "Input required" link is shown
4. Result on Firefox: the dialog appears but remains in 'Loading' state
5. Result on Chrome: the dialog appears and user is able to promote to Run

Firefox:
![firefox](https://user-images.githubusercontent.com/2078072/41907923-a0414326-7942-11e8-8144-b8685e833180.png)

Chrome:
![chrome](https://user-images.githubusercontent.com/2078072/41907938-a7d4e7aa-7942-11e8-87c3-712b7bd11d4f.png)

**Comment by invincibleJai** [comment]
thanks @ljelinkova

**Comment by invincibleJai** [comment]
Fix is in Prod, closing it.
