### ISSUE TITLE
Link to Recent Active Pipeline does not work

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#3866]
When you go to Account home and click some of the recent pipelines, you get _404: You've found something, but not the page you're looking for._ It seems that the linked URL contains the space twice.

`https://openshift.io/ljelinko@redhat.com/My_space/My_space/create/pipelines`

When I manually change the link to the following it works

`https://openshift.io/ljelinko@redhat.com/My_space/create/pipelines`

**Comment by jiekang** [comment]
Possible duplicate of: https://github.com/openshiftio/openshift.io/issues/3841

See also: https://github.com/fabric8-ui/fabric8-ui/pull/3071

**Comment by piyush1594** [comment]
@jiekang Can we close this as other issue is closed
