### ISSUE TITLE
Recent spaces is blank

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#387]
on "openshift.io/_home"
https://screencast.com/t/JQLHjFhZCb5

https://screencast.com/t/mxSc8sRBDte

## Impacts
- [ ] #2133

**Comment by burrsutter** [comment]
It is working today (July 22) 
https://screencast.com/t/ZYnOqKbo0

**Comment by joshuawilson** [comment]
I think our current implementation is imperfect. However, can you try to visit a space and then go to the dashboard and refresh? Does it appear then?

**Comment by qodfathr** [comment]
I think we've got a broader problem that touches this and some other product areas. It appears that we are maintaining some these "recent" lists in the browser cache/local storage. If I change browsers, or machines, or got incognito, etc., this information is lost or inconsistent. It would be better if "recent" lists were determined via a platform API call, such that the results are always consistent across browser sessions.

**Comment by joshuawilson** [comment]
The solution is to fix our caching issues, get control of refreshing, and push updates where needed. These are all things we are working on to one degree or another.

**Comment by alexeykazakov** [comment]
We changed a lot in this area. @burrsutter could you please reopen this issue with latest details if you still have any issues with that?
