### ISSUE TITLE
Custom Attributes in Detail/Quick Preview View don't have "nil" Values

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#3870]
The extra custom fields on the detail views always initialize with the first value in the enum and are not showing "nil" value even if the value on the Work Item is not set.

**Comment by nimishamukherjee** [comment]
@sanbornsen can you check this.

**Comment by sanbornsen** [comment]
The backend sets the default value. True that we don't handle `null` as well which I can fix but still once created enum field will have a default value from the backend. @kwk please verify.

**Comment by sanbornsen** [comment]
Well, I verified that UI has a check for null value. So nothing to change from UI side.

**Comment by nimishamukherjee** [comment]
Thanks @sanbornsen 
@michaelkleinhenz @kwk please check.

**Comment by kwk** [comment]
> The extra custom fields on the detail views always initialize with the first value in the enum and are not showing "nil" value even if the value on the Work Item is not set.

@michaelkleinhenz to my best knowledge every work item that was created with the work item repository has a default value for every enum field. I think I can proof this by showing the "path" we take when creating a new work item:

1. When you create a work item, the [`GormWorkItemRepository.Create`](https://github.com/fabric8-services/fabric8-wit/blob/67a3d3a631e1e2a92cd7ce833eb64573f30f0fa0/workitem/workitem_repository.go#L636) method is called. Inside that method we then:
   1. [load the work item's type definition](https://github.com/fabric8-services/fabric8-wit/blob/67a3d3a631e1e2a92cd7ce833eb64573f30f0fa0/workitem/workitem_repository.go#L639)
   1. [iterate over the WIT's field](https://github.com/fabric8-services/fabric8-wit/blob/67a3d3a631e1e2a92cd7ce833eb64573f30f0fa0/workitem/workitem_repository.go#L688) - NOTICE that we thereby handle ALL fields of a type and not only the ones that are set on the work item
   1. take the field definition and call a general [`ConvertToModel`](https://github.com/fabric8-services/fabric8-wit/blob/67a3d3a631e1e2a92cd7ce833eb64573f30f0fa0/workitem/workitem_repository.go#L694) function
      1. [`ConvertToModel`](https://github.com/fabric8-services/fabric8-wit/blob/67a3d3a631e1e2a92cd7ce833eb64573f30f0fa0/workitem/field_definition.go#L102:26) then takes the field's type (which is an interface) and calls [`DefaultValue(value)`](https://github.com/fabric8-services/fabric8-wit/blob/67a3d3a631e1e2a92cd7ce833eb64573f30f0fa0/workitem/field_definition.go#L105) on it. This function is meant to return a proper default when called with a `nil` value. Currently the only field type structure that does more than returning `nil`  is the [`EnumType`](https://github.com/fabric8-services/fabric8-wit/blob/67a3d3a631e1e2a92cd7ce833eb64573f30f0fa0/workitem/enum_type.go#L23). The `ListType` for example implements `DefaultValue` as a [`nil`-in-`nil`-out stub](https://github.com/fabric8-services/fabric8-wit/blob/67a3d3a631e1e2a92cd7ce833eb64573f30f0fa0/workitem/list_type.go#L25).
   1. [save](https://github.com/fabric8-services/fabric8-wit/blob/67a3d3a631e1e2a92cd7ce833eb64573f30f0fa0/workitem/workitem_repository.go#L708) the work item

@michaelkleinhenz please confirm if this issue can be closed.

**Comment by michaelkleinhenz** [comment]
Is fixed with the default value feature.
