### ISSUE TITLE
Changes in the UI to point to /api/booster-catalog/ instead of /api/booster-catalog/booster for getting github information

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#3873]
Currently in ngx-launcher, we hit /api/booster-catalog/booster for getting github information associated with the mission and runtime combination selected by the user.

Since the backend has migrated that to make things more effective, the necessary changes needs to be handled in the UI as well to consume the correct response.

This task tracks those changes.

**Comment by jyasveer** [comment]
closing this as this is fixed
