### ISSUE TITLE
/render and POST on WIs with Description Markup does not get Quotes right

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#3875]
When adding a code area to a description field, markup does not get rendered correctly. See https://github.com/fabric8-ui/fabric8-planner/issues/2351.

When looking at the queries, it looks like `/render` queries return the correct quoting and the preview ui is displaying the content correctly:

```
<pre><code class="prettyprint"><span class="typ">Markup</span>↵<span class="pun">&lt;</span><span class="kwd">this</span><span class="pun">&gt;</span> <span class="pun">&lt;</span><span class="kwd">is</span><span class="pun">&gt;</span> <span class="pun">&lt;</span><span class="pln">markup</span></code></pre>
```

But on a PATCH on system.description, the response rendered markup appears to be double quoting:

```
<pre><code class="prettyprint"><span class="typ">Markup</span>↵<span class="pun">&amp;</span><span class="pln">lt</span><span class="pun">;</span><span class="kwd">this</span><span class="pun">&amp;</span><span class="pln">gt</span><span class="pun">;</span> <span class="pun">&amp;</span><span class="pln">lt</span><span class="pun">;</span><span class="kwd">is</span><span class="pun">&amp;</span><span class="pln">gt</span><span class="pun">;</span> <span class="pun">&amp;</span><span class="pln">lt</span><span class="pun">;</span><span class="pln">markup</span>↵</code></pre>
```

This is a backend issue, not an issue on the UI.

**Comment by jarifibrahim** [comment]
From https://github.com/fabric8-ui/fabric8-planner/issues/2351

Single/double quotes do not get rendered properly when writing in code-blocks.

![screenshot from 2017-11-23 15-20-48](https://user-images.githubusercontent.com/713521/33468945-d8154ffa-d685-11e7-8975-0aced1b7bb17.png)
