### ISSUE TITLE
Old WIT shall not run on new DB

### ISSUE THREAD

**Issue by kwk** [openshiftio/openshift.io#3880]
In https://github.com/openshiftio/openshift.io/issues/3879 we had a problem with importing a space template. The database was migrated and a field with type (*integer*) was removed from a particular work item type during that migration.

The space template import then wanted to reconstructed the field with a different type (*string*). But it never got to that point and failed before.

We assume that since the core couldn't start up we started an old core again. That in turn saw that there was a field missing field and created it with the old type (*integer*) during the space template import.

That means that we essentially have to do the db migration again. :(

In the future we might want to not use old cores on a new database. But in order to fix what is described here https://github.com/openshiftio/openshift.io/issues/3879#issuecomment-401300861 we need to execute the DB migrations again.

We (@michaelkleinhenz and @kwk) now double checked all the changes in https://github.com/fabric8-services/fabric8-wit/pull/2133/files#diff-ef9bca69129f8d8e357ad2ba0192455aL25 that initially caused the problems and are pretty sure that it should work now.

**Comment by kwk** [comment]
To mitigate the danger of starting an old core on a newer database we could ensure that the old core also fails by doing two things:

1. Each core should know against which DB version is shall run. This can be figured out by inspecting the number of migrations a core is aware of. 
2. When a core starts up and finished it's migration it MUST abort if the DB version is not exactly as the one it expects.

@bartoszmajsak I think this will at least help us with destroying the DB but it might give us some downtime. @aslakknutsen any thoughts?

**Comment by sbose78** [comment]
@kwk I think your assumption is correct.

> We assume that since the core couldn't start up we started an old core again. That in turn saw that there was a field missing field and created it with the old type (integer) during the space template import.

**Comment by sbose78** [comment]
> When a core starts up and finished it's migration it MUST abort if the DB version is not exactly as the one it expects.

This should not cause a downtime, there might one replica less. The others should keep receiving traffic.

**Comment by kwk** [comment]
> When a core starts up and finished it's migration it MUST abort if the DB version is not exactly as the one it expects.
> 
> > This should not cause a downtime, there would be n - 1 replicas running. The others should keep receiving traffic.

@sbose78 well there's a high chance of the old core to fail when operating on a new DB. This is actually another problem. Hm...

**Comment by bmicklea** [comment]
I'm not sure this is an issue that PM can effectively set the SEV on. Can someone more technical please add a SEV label?

**Comment by sbose78** [comment]
> When a core starts up and finished it's migration it MUST abort if the DB version is not exactly as the one it expects.

>> This should not cause a downtime, there would be n - 1 replicas running. The others should keep receiving traffic.

>>> @sbose78 well there's a high chance of the old cores to fail when operating on a new DB. This is actually another problem. Hm...

Yes, would be wrong to assume that the old code would be compatible.

**Comment by sbose78** [comment]
Added a sev2 @bmicklea .

@kwk , based on your meeting with @aslakknutsen , Could you comment/close the issue, please ?

**Comment by kwk** [comment]
@sbose78 @bmicklea . We can close this issue as @aslakknutsen, @michaelkleinhenz and I have figured out a way to update our database by following the approach described in [
Migrating to Microservice Databases: From Relational Monolith to Distributed Data](https://developers.redhat.com/promotions/migrating-to-microservice-databases/). To keep it short: we agreed to make it a two-step update process in order to change the database. That ensures that WIT core's with an understanding of the old database (version N-1) can still operate and only after the new WIT cores are fully deployed, we make the final change (e.g. rename or add a column for example).

@aslakknutsen pointed out that it is quite normal for old cores to run on a new database because that's what happens every time we update prod with a new WIT core. The next time a database migration is needed we all need to pay special attention to this.

@bartoszmajsak can we maybe get ike to require an extra sign of if for example the `migration` or `spacetemplate/assets` directory updates? That would at least remind us to do the extra validation.

**Comment by bartoszmajsak** [comment]
> @bartoszmajsak can we maybe get ike to require an extra sign of if for example the migration or spacetemplate/assets directory updates? That would at least remind us to do the extra validation.

That sounds helpful @kwk. How would you envision this sing-off to look like?

**Comment by kwk** [comment]
> > @bartoszmajsak can we maybe get ike to require an extra sign of if for example the migration or spacetemplate/assets directory updates? That would at least remind us to do the extra validation.
> 
> That sounds helpful @kwk. How would you envision this sing-off to look like?

It can be as simple as the `/ok-without-tests` comment, so initially when the critical files under a directory are modified, this needs a `/sign-off` (just a though) comment to get rid of this status. So potentially in a PR with no tests and files in `spacetemplate/assets` modified it would require 2 comments for the PR to pass: `/ok-without-tests` and `/sign-off`.

**Comment by bartoszmajsak** [comment]
@kwk Isn't `/sign-off` effectively the same as approving the PR by the reviewer? My thinking was more in the direction of a checklist, so assuming we have changes in the given location such as `spacetemplate/assets`, we can define a checklist so that every PR which touches those files will have automatically added a comment with a checklist of extra things to consider.

**Comment by kwk** [comment]
> Isn't /sign-off effectively the same as approving the PR by the reviewer?

Yes and no. If a reviewer just approves a PR with GH's board tools then the PR should not be mergable if it touches a file in e.g. `spacetemplate/assets` and hasn't received a `/sign-off` comment.

> My thinking was more in the direction of a checklist, so assuming we have changes in the given location such as spacetemplate/assets, we can define a checklist so that every PR which touches those files will have automatically added a comment with a checklist of extra things to consider.

As much as this sounds reasonable I think people WILL NOT read the comment. I've heard so many people asking what they can do about IKE complaining about missing tests. They simply didn't read the comment that says "Comment with `/ok-without-tests`".

So my suggestion is that a user should be required to actually DO something ON TOP of the comment that you suggested.
