### ISSUE TITLE
Launcher: npm link not working for ngx-forge to fabric8-ui

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#3886]
- at present npm link from ngx-launcher to fabric8-ui is not working.

**Comment by GeorgeActon** [comment]
@jyasveer @animuk please set type, and if bug set severity

**Comment by GeorgeActon** [comment]
@jyasveer label this correctly & set Severity

**Comment by bartoszmajsak** [comment]
@GeorgeActon is your team going to work on it this sprint? @vikram-raj stumbled upon the same issue and might help to sort this out. 

See #4078

**Comment by jyasveer** [comment]
@GeorgeActon i have updated the labels now

**Comment by GeorgeActon** [comment]
@bartoszmajsak that explains Anindya's comment that Vikram was goig to work on this.

@animuk  if this is a duplicate of the one that @vikram-raj then one of these should be closed as a duplicate. Coordinate with Vikram

**Comment by bartoszmajsak** [comment]
I don't see it as a user facing bug, it's engineering tooling problem. Shall we keep it as bug for your aggregation @stevengutz @GeorgeActon?

**Comment by invincibleJai** [comment]
it's a duplicate of https://github.com/openshiftio/openshift.io/issues/4078 , and @vikram-raj was looking into it. I think this can be cosed.

**Comment by animuk** [comment]
Closing as it is duplicate of #4078
