### ISSUE TITLE
Users provisioned on starter-us-east-1a are unable to start Jenkins and Content Repo pods after an env reset

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3888]
Steps to recreate:
* Login to https://openshift.io with a user account provisioned on the starter-us-east-1a cluster
* Reset user env
* Observe that Jenkins and Content Repo pods fail to start
* Observe in OpenShift console that pods' status indicates that rollouts are paused:

![screenshot from 2018-07-02 11-13-09](https://user-images.githubusercontent.com/642621/42172984-a3253aea-7deb-11e8-8ab4-211fcd5e7405.png)

* Observe that resuming rollouts does not resolve this issue.

**Comment by ldimaggi** [comment]
Issue found/encountered by EE tests.

**Comment by sbose78** [comment]
@michaelkleinhenz @sunilmalagi has encountered this as well.

**Comment by mmclanerh** [comment]
this should be working again. there was a configuration present on starter-us-east-1a, applied friday, that was reverted today. may need to issue a new tenant reset to re-create pvcs.
