### ISSUE TITLE
[RFE] Automated PV cleanup tool needed to support users over time

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#389]
As a user makes use of OSIO over time, hie/her PVs can become full - once this happens manual steps must be performed to "clean up" space and enable the user to create new projects.

What is needed is something similar to a garbage collector - to ensure that the user's account has sufficient free space.

Related issues:
https://github.com/openshiftio/openshift.io/issues/375
https://github.com/fabric8-ui/fabric8-ui/issues/1526
https://github.com/fabric8-ui/fabric8-ui/issues/1560

**Comment by joshuawilson** [comment]
Is this still an issue?

**Comment by ldimaggi** [comment]
Closing - this problem has not been seen for months.
