### ISSUE TITLE
Can't Comment on a Work Item Using Firefox

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#3894]
I tried to comment on a work item that I was linked to, but am unable to using Firefox. I verified that I am logged into OpenShift.io correctly. There did not appear to be any errors in the console.

When I switched over to Chrome, I was able to add my comment without issue.

I am using Firefox v60.0.2 on macOS High Sierra.

**Firefox**
<img width="572" alt="screen shot 2018-07-03 at 3 06 06 pm" src="https://user-images.githubusercontent.com/4032718/42239699-b132ec30-7ed2-11e8-8a9b-57b4da6059e6.png">

**Chrome**
<img width="641" alt="screen shot 2018-07-03 at 3 06 17 pm" src="https://user-images.githubusercontent.com/4032718/42239705-b6ad2356-7ed2-11e8-81ad-a70629ee1c57.png">

**Comment by mindreeper2420** [comment]
@rgarg1 - what version of Firefox on Fedora? I know that on Red Hat builds, the default Firefox install is locked to the LTS version, which is far behind the public releases.

**Comment by rgarg1** [comment]
57.0.1 (64-bit)

**Comment by aptmac** [comment]
![firefox-planner](https://user-images.githubusercontent.com/10425301/42455882-6f6eebd0-8361-11e8-98b6-fab96403d31d.png)

I'm using v60.0.2 on Fedora and am seeing the same behaviour as the issue reports.

**Comment by jarifibrahim** [comment]
This issue has been fixed via https://github.com/fabric8-ui/ngx-widgets/pull/153 (and updated in planner via https://github.com/fabric8-ui/fabric8-planner/pull/2772) but the fix is not yet on prod

**Comment by jarifibrahim** [comment]
This issue has been fixed. Closing it.
