### ISSUE TITLE
Handle the network outage gracefully when pushing artefacts to content-repository

### ISSUE THREAD

**Issue by sthaha** [openshiftio/openshift.io#3895]
Currently  `init-container` hack (wait for content-repository) in jenkins image is causing more problems that what it solves. Hence lets 

- [x] remove the init container hack from the image. Done with https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/107
- [ ] check if some sort of pre-hook can be added to kubernetes-plugin so that  when the jenkins slave comes up it tries  reach jenkins-master and if it doesn't report an error instead of waiting forever  as it currently does.
- [x] decide if we really require `content-repository`. If we need it, handle the failure to reach content-repository in the pipeline script itself ; see: 
    * https://github.com/fabric8io/fabric8-pipeline-library/blob/85f09de8110c180f47d9fb6e305d793e4438e1d9/vars/canaryRelease.groovy#L66
    * https://github.com/fabric8io/fabric8-pipeline-library/blob/85f09de8110c180f47d9fb6e305d793e4438e1d9/vars/mavenCanaryRelease.groovy#L79
    * https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/contentRepository.groovy
In case we don't really need content repository (since the contents aren't accessible to the user anyway and can't be cleared) we may be able to allocate its resources to jenkins. 
Work for removing content repository: 
https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/108
https://github.com/fabric8io/fabric8-pipeline-library/pull/409
Some work is also required to be done in idler for this. Here is the subissue for that https://github.com/openshiftio/openshift.io/issues/4127

**Comment by chmouel** [comment]
on another topic of removing content-repo this is something i have been trying to do for many times, the argument from max was that entreprise devs needs it since they need a certain point of time with all the dependencies stored and browseable.

It's not browseable anymore since we removed the public route due of security issue and I am not so sure *any people using it.

This probably warrant a new issue to be open where we can track this,

and max is on a long term PTO anyway (so he snoose he loose 😆)

**Comment by chmouel** [comment]
While working on multi language support, I had a bit of an experiment last night with this : 

https://github.com/chmouel/space2/blob/90bb1b308d45ff9c1c61ad712039455371c54ed5/Jenkinsfile#L13-L23

Unfortunately the node() still have to come up with a slave so it's actually not working,

If the kubernetes-plugin doesn't work (as my guts feeling think this is going to be complex way) I wonder if instead we could just use this https://wiki.jenkins.io/display/JENKINS/SiteMonitor+Plugin plugin, it's old and don't know if it still maintained so we may have to do some cleanup but that may be another (easier) way to achieve what we want to do,

**Comment by kishansagathiya** [comment]
Adding the registered issue on the OpenShift side https://bugzilla.redhat.com/show_bug.cgi?id=1552373

**Comment by kishansagathiya** [comment]
some more thought from @chmouel 

> by the way we could as well just improve https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/contentRepository.groovy to do a http check that it is running properly as well 
something like this ? https://stackoverflow.com/questions/34682099/how-to-call-rest-from-jenkins-workflow
no need the whole thing just checking if it's coming back with a 2xxx

**Comment by kishansagathiya** [comment]
Updated the description as per recent developments
