### ISSUE TITLE
Figure out what are we using jenkinsci/kubernetes-pipeline-plugin or fabric8io/kubernetes-pipeline-plugin or fabric8-jenkins/fabric8-pipelines-plugin

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#3897]
Figure out what are we using https://github.com/jenkinsci/kubernetes-pipeline-plugin or https://github.com/fabric8io/kubernetes-pipeline-plugin

If we are not using https://github.com/fabric8io/kubernetes-pipeline-plugin, archive it

**Comment by kishansagathiya** [comment]
Found one more https://github.com/fabric8-jenkins/fabric8-pipelines-plugin

**Comment by hrishin** [comment]
this plugin is used https://github.com/jenkinsci/kubernetes-pipeline-plugin

**Comment by kishansagathiya** [comment]
@hrishin or @rupalibehera 
Can you please archive unused pipeline-plugins?

**Comment by hrishin** [comment]
@rupalibehera can do it.

**Comment by rupalibehera** [comment]
@lordofthejars , @kishansagathiya means that that archive the repository which is not in use

**Comment by lordofthejars** [comment]
@rupalibehera in GitHub you mean right?

**Comment by hrishin** [comment]
@lordofthejars @rupalibehera @kishansagathiya I've archived the https://github.com/fabric8io/kubernetes-pipeline-plugin.

This issue would be addressed in a better way with https://openshift.io/openshiftio/Openshift_io/plan/detail/343.

**Comment by lordofthejars** [comment]
@hrishin @kishansagathiya @rupalibehera Ok I have no rights to do it so, I unassign this issue.
