### ISSUE TITLE
Design Standardization : Layout > List View

### ISSUE THREAD

**Issue by sdash-redhat** [openshiftio/openshift.io#3900]
This story addresses the standardization aspect of List View. 

Some earlier explorations/pointers to that need to be addressed : 
- Should we support a grouping title around some of the list view?  OpenShift has this in the project overview.  CloudForms actually has this too
- OpenShift should have the top panel be white, not grey
- Let’s see if we can get optional column headers for list views

### Verification Criteria
The following activities need to be performed and completed: 
- Review the usage across the different existing applications.
- Compare ones from Patternfly.
- Provide the proposal 
- Review the Proposal with the team (UX, Engg., PM)
- Draft initial guidelines and engage with the team in the review process.
- Update the content and guidelines to the DSW

### Parent Issue / Reference
Design Standardization : Layout #3899
Design Standards Wiki #3799

**Comment by serenamarie125** [comment]
Closing out Design Standardization tasks as related to the wiki
