### ISSUE TITLE
Design Standardization : Layout > Card View

### ISSUE THREAD

**Issue by sdash-redhat** [openshiftio/openshift.io#3901]
This story addresses the standardization aspect of Card View. 

Some earlier explorations/pointers to that need to be addressed : 
- Card selection for single select and multi-select is confusing 
- Checkboxes? Currently, OSIO has an idea for radio button selection
- Cards being used on a white background? 

### Verification Criteria
The following activities need to be performed and completed: 
- Review the usage across the different existing applications.
- Compare ones from Patternfly.
- Provide the proposal 
- Review the Proposal with the team (UX, Engg., PM)
- Draft initial guidelines and engage with the team in the review process.
- Update the content and guidelines to the DSW

### Parent Issue / Reference
Design Standardization : Layout #3899
Design Standards Wiki #3799

**Comment by serenamarie125** [comment]
Closing out Design Standardization tasks as related to the wiki
