### ISSUE TITLE
Design Standardization : Layout > Empty States

### ISSUE THREAD

**Issue by sdash-redhat** [openshiftio/openshift.io#3902]
This story addresses the standardization aspect of Empty States. 

Some earlier explorations/pointers to that need to be addressed : 
- PF - Should test empty states - Catherine says that in some cases people are clicking the larger icons
- Could the pattern be extended to allow for an icon OR an image? 

 
### Verification Criteria
The following activities need to be performed and completed: 
- Review the usage across the different existing applications.
- Compare ones from Patternfly.
- Provide the proposal 
- Review the Proposal with the team (UX, Engg., PM)
- Draft initial guidelines and engage with the team in the review process.
- Update the content and guidelines to the DSW

### Parent Issue / Reference
Design Standardization : Layout #3899
Design Standards Wiki #3799

**Comment by AshishDurgude** [comment]
Here is the initial research for an empty state for OSIO:
https://redhat.invisionapp.com/share/A9LH2EXE2CG#/304437808_4

**Comment by sdash-redhat** [comment]
Based on the explorations, it looks like the solution to this should address the following aspects of the Empty States [Refer to a quick diagram I made to start with ] 

If you have any thoughts regarding any of these aspects please add as a comment below -- That I will take care while in design: 


![layout-emptystates-3902-mm](https://user-images.githubusercontent.com/27761023/42874937-063e6802-8aa0-11e8-9ce2-f77f58f52d33.jpeg)

@muruGanesan @catrobson @serenamarie125 @joshuawilson @bdellasc @sunilmalagi 
[Please feel free to add anyone to this thread whom you think might help]

**Comment by sdash-redhat** [comment]
Empty State Info types -- 

Info - is standard information that is expected in the beginning or the first run 

Alert - In the scenario of empty space which is the result of beyond the result of something that needs user's specific attention  (e.g. in case of no result when some alert level info is shown to the user inline), when a specific message that may appear with an alert icon.  This can be applied to the cards that supposed to show some results, but some dependent information requires to be set by the user ..such a scenario is when we might need to show an inline alert to the user ...

Error - if the empty state is the result of some error.

**Comment by sdash-redhat** [comment]
Here is the initial observation and proposed draft for review by the team to share their thoughts:
https://redhat.invisionapp.com/share/UEN434JGF72

Please review and share your feedback. 
Based on that we will improve it and come up with a VD, that would finally be added to the Wiki 

@catrobson @serenamarie125 @muruGanesan @sunilmalagi @AshishDurgude @bdellasc @Essjaysee

**Comment by sdash-redhat** [comment]
Thanks for the feedback in invision, Have updated with some minor tweaks. 
https://redhat.invisionapp.com/share/UEN434JGF72#/310256253_Slide01

**Comment by catrobson** [comment]
Your recommendations look good to me @sdash-redhat!  I'd like to see the title capitalization be contributed back into PatternFly 3 specifications.  Otherwise I think much of this is ready for our wiki!

**Comment by catrobson** [comment]
To contribute this to PatternFly - create an issue referencing the missing information in the current empty state here to alert people that this is being addressed and you're doing the work:
https://github.com/patternfly/patternfly-design/issues

Then start a PR with your improvements to the documentation on this page that will go through review:
https://github.com/patternfly/patternfly-design/blob/master/pattern-library/communication/empty-state/design/design.md

Thanks!

**Comment by sdash-redhat** [comment]
The wiki has been updated with the design 
refer to the link to the Wiki page here: https://uxd.fabric8.io/layout/empty-state/
Marking as complete.
