### ISSUE TITLE
Design Standardization : Layout > Mastheads

### ISSUE THREAD

**Issue by sdash-redhat** [openshiftio/openshift.io#3905]
This story addresses the standardization aspect of Mastheads. 

Some earlier explorations/pointers to that need to be addressed : 

- Fuse Ignite should get an SVG from visuals for the product
- Username w/ icon (generic user icon vs. avatar)
- OSIO allows you to customize, but cannot share this info back because of keycloak
- iPaaS - add Name of User next to drop-down - is it there already?
- Help menu - Catherine to investigate help vs. status, if we can combine these into one menu like OpenShift.
- Full status design: https://redhat.invisionapp.com/share/ZFEP5QKXA#/screens
- See if we can contribute the status in masthead color background
- Would be nice if you could optionally re-flash to indicate the fact that status remains the same, but some kind of condition updates ( e.g. 2 errors, versus 1 error )
- Goal : have a consistent masthead
- Can OSIO include the product name in the top banner

### Verification Criteria
The following activities need to be performed and completed: 
- Review the usage across the different existing applications.
- Compare ones from Patternfly.
- Provide the proposal 
- Review the Proposal with the team (UX, Engg., PM)
- Draft initial guidelines and engage with the team in the review process.
- Update the content and guidelines to the DSW

### Parent Issue / Reference
Design Standardization : Layout #3899
Design Standards Wiki #3799

**Comment by serenamarie125** [comment]
Closing out Design Standardization tasks as related to the wiki
