### ISSUE TITLE
Run Command: scl enable rh-maven33 'mvn vertx:run -f ${current.project.path}'

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#391]
Should be
scl enable rh-maven33 'mvn compile vertx:run -f ${current.project.path}'

As the "compile" is needed to get the hot redeploy working.

**Comment by l0rd** [comment]
PR provided. I will update when the fix will be available in production.

**Comment by l0rd** [comment]
I've tested on version `1.0.253` on osio and is fixed. @burrsutter feel free to re-open if needed.
