### ISSUE TITLE
Design Standardization : Navigation > Breadcrumb

### ISSUE THREAD

**Issue by sdash-redhat** [openshiftio/openshift.io#3910]
This story addresses the standardization aspect of Breadcrumb. 

Some earlier explorations/pointers to that might need to be addressed : 

- May want to consider combining Page Titles with Breadcrumbs as shown in the Breadcrumbs Combined with Page Title (Optional) section
-  http://www.patternfly.org/pattern-library/navigation/breadcrumbs/#design/

### Verification Criteria
The following activities need to be performed and completed: 
- Review the usage across the different existing applications.
- Compare ones from Patternfly.
- Provide the proposal 
- Review the Proposal with the team (UX, Engg., PM)
- Draft initial guidelines and engage with the team in the review process.
- Update the content and guidelines to the DSW

### Parent Issue / Reference
Design Standardization : Navigation #3906
Design Standards Wiki #3799

**Comment by serenamarie125** [comment]
Closing out Design Standardization tasks as related to the wiki
