### ISSUE TITLE
Create a new project - Secured Spring Boot Tomcat Quickstart - fails

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#392]
_From @ldimaggi on July 7, 2017 15:45_

Steps to recreate:
* Create a new project - in either a new or existing space - select Secured Spring Boot Tomcat
* Project fails in rollout to stage

Error is: no openshift.yaml found

See attached build log file. 
[Secured_Spring_Boot_Tomcat_log.txt](https://github.com/fabric8-ui/fabric8-ui/files/1131505/Secured_Spring_Boot_Tomcat_log.txt)

_Copied from original issue: fabric8-ui/fabric8-ui#1660_

**Comment by gastaldi** [comment]
@ldimaggi where is this openshift.yaml supposed to exist? The booster doesn't have this file and that's not used in launcher: https://github.com/openshiftio-vertx-boosters/vertx-secured-http-booster.

**Comment by gastaldi** [comment]
Removed booster from list of supported boosters in prod-preview. We will add back when the booster is certified to work in OSIO
