### ISSUE TITLE
Design Standardization : Notifications > Notification Drawer

### ISSUE THREAD

**Issue by sdash-redhat** [openshiftio/openshift.io#3920]
This story addresses the standardization aspect of Notification Drawer. 

  
Some earlier explorations/pointers to that need to be addressed :
- Notification Drawer - OS has it
- Notification Drawer - OSIO plans: https://redhat.invisionapp.com/d/main#/projects/prototypes/11914584
- OS is moving inline to toast notifications
- Are the styles of our inline/toast matching PF ?
- OS customized the toast notification for truncation/expansion - AI to contribute this back to PatternFly
- iPaaS - if we use both inline notifications and toast notifications, when do we use each.
- iPaas - check styling of inline notifications (see screenshot in Coleen’s deck)
- PatternFly - Be more specific about the X to close and timing of toast messages disappearing
- 

### Verification Criteria
The following activities need to be performed and completed: 
- Review the usage across the different existing applications.
- Compare ones from Patternfly.
- Provide the proposal 
- Review the Proposal with the team (UX, Engg., PM)
- Draft initial guidelines and engage with the team in the review process.
- Update the content and guidelines to the DSW

### Parent Issue / Reference
Design Standardization : Notification #3919
Design Standards Wiki #3799

**Comment by serenamarie125** [comment]
Closing out Design Standardization tasks as related to the wiki
