### ISSUE TITLE
Create a new project - Secured Vertx - Rest & Red Hat SSO Quickstart - fails

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#393]
_From @ldimaggi on July 7, 2017 17:51_

Steps to recreate:
* In a new or existing space, create a new Quickstart project of type: Secured Vertx - Rest & Red Hat SSO
* Rollout to stage fails - error logged is:
```
[Pipeline] { (Rollout to Stage)
[Pipeline] kubernetesApply
no openshift.yml found
```

See attached build log.
[Secured_VertX_REST_RH_SSO_log.txt](https://github.com/fabric8-ui/fabric8-ui/files/1131850/Secured_VertX_REST_RH_SSO_log.txt)

_Copied from original issue: fabric8-ui/fabric8-ui#1664_

**Comment by gastaldi** [comment]
Removed booster from list of supported boosters in prod-preview. We will add back when the booster is certified to work in OSIO
