### ISSUE TITLE
Intermittent error - Jenkins log reports success - but promote button is not displayed in the OSIO UI

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3935]
Steps to recreate (this issue is not reproducible at will):
* Create new project
* Observe build success and option to promote to run in Jenkins log
* Observe promote button is not displayed in OSIO UI

![05-02-jenkins-log-failed](https://user-images.githubusercontent.com/642621/42384688-ab70fb06-8108-11e8-9025-02d5ea03c615.png)

![05-01-pipeline-failed](https://user-images.githubusercontent.com/642621/42384689-ab84f2d2-8108-11e8-8872-2014b1ccbb6c.png)

Full set of test artifacts (logs, screenshots) are available here:
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/262/

**Comment by piyush1594** [comment]
@ldimaggi Can you also check if its there in openshift console or not? It remains like that for a long time or short time because Jenkins-sync-plugin's sync interval time is 5 sec.

**Comment by ljelinkova** [comment]
@piyush1594 Could you be more specific what we should check in openshift console? 

The timeout for E2E tests to finish the whole pipeline is 30 minutes, so it stays in the state where Promote option is in Jenkins but not in OSIO UI at least 15 minutes. 

This error occurred also in the following build (full Jenkins log):
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/327/05-02-jenkins-log-failed.html

**Comment by ljelinkova** [comment]
This issue is still occurring
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/1916/05-01-pipeline-failed.png

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/1916/05-02-jenkins-log-failed.html

**Comment by piyush1594** [comment]
@ljelinkova Thanks for bringing this up. The thing I am asking you to check this in openshift console is that pipeline looks like this in openshift-console also means no promote or abort button in openshift console or only it is showing like this in OSIO. TIA

**Comment by ljelinkova** [comment]
Ok, we'll need to add this to the E2E tests - I'll update this issue once we have results.

**Comment by piyush-garg** [comment]
This issue seems like coming from Jenkins-sync plugin

**Comment by joshuawilson** [comment]
I've also added this to a story to track the e2e bugs at https://openshift.io/openshiftio/Openshift_io/plan/detail/802

**Comment by ljelinkova** [comment]
These are screenshofts from today's run:
OSIO
![openshiftio](https://user-images.githubusercontent.com/2078072/46798069-244ef700-cd51-11e8-82a9-8171ece5ef2f.png)
OS
![openshift](https://user-images.githubusercontent.com/2078072/46798117-4ba5c400-cd51-11e8-828a-1f568417d4d6.png)

**Comment by alexeykazakov** [comment]
Looks like a pure build issue. Removed team/platform.

**Comment by hrishin** [comment]
### Update

### Issue:
Sometimes back we introduced a patch that updates OS `Build` resources at the certain condition to reduce the unnecessary build updates in the openshift-sync plugin. Which might have introduced a side effect where despite the necessity it won't update build status.

### Solution:
Fix that issue by making right update condition so it would not miss any build status.

**Comment by hrishin** [comment]
### Update

To fix this issue, the patch has been sent on [openshift-sync-plugin](https://github.com/fabric8io/jenkins-sync-plugin/pull/41) project. In nutshell, this patch updates openshift build state as soon it receives a build state event from Jenkins. In the previous approach, it was polling for build state at fixed interval time.

**Comment by piyush-garg** [comment]
This has been fixed in prod using https://github.com/openshiftio/saas-openshiftio/pull/1122 Closing this.

**Comment by hrishin** [comment]
@ljelinkova @ldimaggi feel free to open another ticket if E2E still face this issue.
