### ISSUE TITLE
Capture end-to-end UXD improvements [13]

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#3938]
### Description
Capture end to end UXD improvements we should consider to make the user experience of the path of using OSIO with current capabilities more smooth.

### Verification Criteria
- [ ] Capture document with areas of improvement
- [ ] Capture designs as they exist today into a single place
- [ ] Prioritize areas we want to fix
- [ ] Capture issues for things that should be worked on

**Comment by muruGanesan** [comment]
Here is the approach document:
https://docs.google.com/presentation/d/1w3cCZDRpYeoBK9_5b47NfdXNeHIGoFbKdRq4ExZ25ow/edit#slide=id.g403892b45a_0_0

**Comment by serenamarie125** [comment]
@muruGanesan this should move out of In Progress since it's not part of the J Train Goals.  Thank you

**Comment by muruGanesan** [comment]
@serenamarie125, since you are working on new IA for OSIO (version 1.5), we can close this issue if it is irrelevant.

**Comment by serenamarie125** [comment]
This should be closed since it's no longer applicable
