### ISSUE TITLE
Create a new project - Vert.x CRUD - fails

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#394]
_From @ldimaggi on July 7, 2017 19:22_

Steps to recreate:
* In a new or existing space, create a new project based on a Vert.x-CRUD quickstart.

The build is successful, but the stage and run pods never come up. This is reproducible - saw it 3 out of 3 times, all OpenShift assets (builds, stage/run pods, etc.) deleted between attempts.

Stage deploy log:

```
--> Scaling july7-1 to 1
--> Waiting up to 10m0s for pods in rc july7-1 to become ready
error: update acceptor rejected july7-1: pods for rc "july7-1" took longer than 600 seconds to become ready
```

Build log attached. 
[VertX_CRUD_log.txt](https://github.com/fabric8-ui/fabric8-ui/files/1132074/VertX_CRUD_log.txt)

_Copied from original issue: fabric8-ui/fabric8-ui#1667_

**Comment by qodfathr** [comment]
Vert.x CRUD is no longer an approved OSIO quickstart and has been removed from the catalog. Also, #1667 is closed.
