### ISSUE TITLE
Creating new app blocked on prod-preview - no boosters are available

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3944]
Steps to recreate:
* On prod-preview, attempt to create a new app
* Observe 503 errors - observe that no boosters are available

Failed to load https://forge.api.prod-preview.openshift.io/api/services/jenkins/pipelines: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://prod-preview.openshift.io' is therefore not allowed access. The response had HTTP status code 503.
2zone.js:2933 OPTIONS https://forge.api.prod-preview.openshift.io/api/booster-catalog/ 503 (Service Unavailable)

![screenshot from 2018-07-10 08-05-45](https://user-images.githubusercontent.com/642621/42509221-35d93c00-8419-11e8-9810-600937b051b8.png)

**Comment by ldimaggi** [comment]
Looks like this issue was caused by an problem with a planned upgrade.

**Comment by bartoszmajsak** [comment]
@ldimaggi can we close it then?

**Comment by ldimaggi** [comment]
Yes - this is resolved - closing.
