### ISSUE TITLE
Launcher got an unknown response from WIT

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/openshift.io#3947]
According to https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/6361/, something changed in WIT that caused launching of applications to `/osio/launch` to fail:

```
got unknown response: {"status":"success","summary":"Report for https://github.com/osiotestmachine/e2e-0710-184407.git is being generated in the background. You will be notified via your preferred openshift.io notification mechanism on its completion."}
```

This is the code that validates the response, it should be updated as well:
https://github.com/fabric8-launcher/launcher-backend/blob/067edfd4307f1c36af834894d273f73f869ec2dc/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/client/OsioWitClient.java#L197-L218

**Comment by aslakknutsen** [comment]
@surajssd https://github.com/fabric8-services/fabric8-wit/blob/master/codebase/analytics-gemini/client.go#L181 check status instead of the summary?

**Comment by surajssd** [comment]
Here is the PR which will fix this issue https://github.com/fabric8-services/fabric8-wit/pull/2159
