### ISSUE TITLE
fabric8-jenkins-proxy: Invesigate if `osio` command is required, get rid of it if not

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#3949]
In proxy we do not use sso.openshift.io for login
However I see it being used for setting proxy locally 
A quick search for sso gives me a few other occurrences (https://github.com/fabric8-services/fabric8-jenkins-proxy/search?q=sso&unscoped_q=sso)

but they are being used in osio command.
What does this osio command?

proxy has two commands. one is fabric8-jenkins-proxy and the other one is osio. I never looked into osio command, because it never created any problems for me. Now that I do, I realize that it is a utility command to create to create OSIO tokens. From the first look it seems completely useless to me.

**Comment by sthaha** [comment]
Closing this since the utility seems useful to run tests locally.
