### ISSUE TITLE
Create a new project - Spring Boot CRUD - fails

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#395]
_From @ldimaggi on July 7, 2017 20:4_

Steps to recreate:
* Create a new project - Select Spring Boot CRUD

Error raised is:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project july7: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```

Build log attached.
[Spring_Boot_CRUD_log.txt](https://github.com/fabric8-ui/fabric8-ui/files/1132178/Spring_Boot_CRUD_log.txt)

_Copied from original issue: fabric8-ui/fabric8-ui#1668_

**Comment by qodfathr** [comment]
I suspect this quickstart will not be OSIO compatible without significant work. How do we get it removed from the catalog, like we did with the Vert.x CRUD?

**Comment by joshuawilson** [comment]
cc @gastaldi

**Comment by gastaldi** [comment]
+1, I'll remove it

**Comment by ldimaggi** [comment]
The quickstart builds - but when it is deployed to stage, the stage pod fails to start and repeatedly fails with this error:

```
2018-01-16 20:53:08.784 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application startup failed
--
  |  
  | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]


```

**Comment by ldimaggi** [comment]
[testtodd2-1-dprgd.log](https://github.com/openshiftio/openshift.io/files/1636764/testtodd2-1-dprgd.log)

**Comment by gastaldi** [comment]
@ldimaggi that´s most likely because the cluster requires more resources to boot (CPU, Memory, Disk, etc)
