### ISSUE TITLE
content-repository update with latest caddy server update

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#3952]
Caddy has been rebased and updated,  we need to rebase the content-repository against it

**Comment by rupalibehera** [comment]
we just need to push an empty commit to repo like this https://github.com/fabric8io/caddy-server/pull/3, it will build the new image and push it.
and then change the image version like this https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/71

**Comment by hrishin** [comment]
@rupalibehera if we are going to drop the content repository is it worth to manage the lifecycle of it?

@kishansagathiya @chmouel

**Comment by rupalibehera** [comment]
@hrishin , not sure but the image is already updated. Below are the respective PR's 
Image - https://github.com/fabric8io/caddy-server/pull/4
fabric8-tenant - https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/71
saas-openshiftio to promote to prod - https://github.com/openshiftio/saas-openshiftio/pull/977

**Comment by hrishin** [comment]
@rupali yeah somehow missed PR links, no worries :)

**Comment by rupalibehera** [comment]
closing it , merged to prod.
