### ISSUE TITLE
Can't login to jenkins.openshift.io

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#3954]
I see this after entering my login details. 
![screenshot from 2018-07-11 17-19-12](https://user-images.githubusercontent.com/10185999/42569597-a87ed7cc-852e-11e8-9dc6-eee840e661ee.png)

Keep trying further with `review profile` or `add to existing account` is also hopeless.

**Comment by kishansagathiya** [comment]
@sthaha @hrishin @rupalibehera If any of you can reproduce this, I will tag this as `SEV1`

**Comment by sthaha** [comment]
For the record, @kishansagathiya and I tried it with my account and I am able to login in both incognito mode and otherwise.

**Comment by chmouel** [comment]
No problem here too with a lot of different accounts,

**Comment by kishansagathiya** [comment]
Thanks a lot @chmouel

**Comment by piyush1594** [comment]
@kishansagathiya I tried it and its working fine for me. Assigning the severity SEV-4

**Comment by kishansagathiya** [comment]
Clearly no one else is facing this except me, but I still face this. 
I wonder if it could be because me having elevated access to my Jenkins! 
![screenshot from 2018-07-23 16-02-06](https://user-images.githubusercontent.com/10185999/43071907-debf422e-8e91-11e8-9e01-8601bc01e839.png)

**Comment by rupalibehera** [comment]
@kishansagathiya , it works for me as well.

**Comment by lordofthejars** [comment]
It works for me as well, @kishansagathiya maybe we can close and reopen if necessary?
