### ISSUE TITLE
Cannot query closed work items without checking 'Show Completed' checkbox

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3955]
1) Go to osio space in osio

2) Select 'State' from the filter drop-down and select 'closed' from the available states.
Observe that no results are displayed.

3) Start over (refresh the page) and this time select the 'Show Completed' checkbox before starting with step 1.
Observe that closed work items are displayed.

Expectation: Explicit filter query for work items by the state should include all closed work items too

**Comment by rgarg1** [comment]
Cc @vikram-raj

**Comment by GeorgeActon** [comment]
@rgarg1 I just verified this is fixed in production. re-open this defect if you are not satisfied
