### ISSUE TITLE
Cannot start a new Che workspace on prod-preview

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3957]
Started seeing this issue 100% of the time on prod-preview last night. Steps to recreate:
* Create a new space on prod-preview
* Create a new app
* Attempt to create a new Che workspace - observe that Che is never able to start the workspace:

![screenshot from 2018-07-11 10-41-42](https://user-images.githubusercontent.com/642621/42580852-750377a2-84f9-11e8-92bc-744e0ead949e.png)
![screenshot from 2018-07-11 10-41-27](https://user-images.githubusercontent.com/642621/42580853-7516814e-84f9-11e8-8821-4bcb142e91d4.png)

**Comment by ibuziuk** [comment]
@ldimaggi please provide more info (openshift events / logs). Creating an issue with no details makes it utterly difficult to investigate.

**Comment by ibuziuk** [comment]
Was able to repro against the user provisioned on `us-east-2a` oso cluster. Workspace startup is failing due to `Failed Mount` problem :

![image](https://user-images.githubusercontent.com/1461122/42614687-3d92fe42-85a7-11e8-89d3-12392b50a4d2.png)

Adding SD team

**Comment by ldimaggi** [comment]
Sorry for the lack of detail - the problem is that the workspace creation was failing 100% of the time. The user account that I used is provisioned on the starter-us-east-2 cluster.

**Comment by ibuziuk** [comment]
@ldimaggi any ideas about the reasons of failure ?

**Comment by ppitonak** [comment]
@ibuziuk @ldimaggi didn't we agree that a serious bug in prod-preview should be labeled as SEV1?

**Comment by ldimaggi** [comment]
Closing as not reproducible - after several days of failing - this just starting working again - thx!
