### ISSUE TITLE
Delay in Launcher feedback to user can cause user to create failure in app creation

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3959]
Steps to recreate:
* Create a new app in the launcher - observe the 6-10 second delay in providing feedback to the user after the project is created but before the user is provided with a button to view the app:
![wait](https://user-images.githubusercontent.com/642621/42582832-10c06a2a-84fe-11e8-89c1-db65114e2a19.gif)

* Create a new app in the launcher - But, this time, don't wait for the UI to respond - after pressing the button to create the app, wait a few seconds and then press it again - observe the error that results as the github repo for the app was created after the first time the button was pressed:
![no_wait](https://user-images.githubusercontent.com/642621/42583074-5a99eeb4-84fe-11e8-9915-c7b64c98799c.gif)

This error results:
![screenshot from 2018-07-11 11-15-01](https://user-images.githubusercontent.com/642621/42583135-6dd9b554-84fe-11e8-82fd-2da68b45568d.png)

The button should be disabled after the user presses it the first time - thx!

**Comment by nimishamukherjee** [comment]
@vikram-raj please disable the button after it has been clicked once.

**Comment by sanketpathak** [comment]
@ldimaggi @vikram-raj  I'm not able to reproduce the issue, so closing it.

**Comment by bartoszmajsak** [comment]
@sanketpathak generally speaking we should ask issue creator to confirm that. @ldimaggi could you try and see if that still affects the use case you described?

**Comment by vikram-raj** [comment]
@ldimaggi This is has been fixed and in prod. Can you please verify.

**Comment by ldimaggi** [comment]
Closing - this issue is no longer present in production.
