### ISSUE TITLE
Create a new project - Wildfly CRUD - fails

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#396]
_From @ldimaggi on July 7, 2017 23:46_

Steps to recreate:
* In a new or existing space, create a new project from the Wildfly CRUD quickstart.

The build fails with this error:
```
[ERROR] Failed to execute goal on project july7: Could not resolve dependencies for project com.example:july7:war:1.0.1: The following artifacts could not be resolved: org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1, org.jboss.openjdk-orb:openjdk-orb:jar:8.0.4.Final: Could not find artifact org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1 in nexus (http://central.maven.org/maven2/) -> [Help 1]
```

See attached build log.

[Wildfly_CRUD_log.txt](https://github.com/fabric8-ui/fabric8-ui/files/1132606/Wildfly_CRUD_log.txt)

_Copied from original issue: fabric8-ui/fabric8-ui#1670_

**Comment by qodfathr** [comment]
Wildfly has been removed from the quickstart catalog.
