### ISSUE TITLE
Productize analytics notification service

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#3961]
## Description
The service to provide analytics notification for user repositories have to be productized and the code quality is ensured so that OSIO users start getting notification emails for any identified CVE in the application stack with minimal errors.

## Acceptance Criteria
1. openshift.io users get an email notification with the list of CVE associated with their application stacks when
    - A user adds a new codebase to an OSIO space.
    - A user explicitly sets the switch "Security Alert" her/his OSIO space's codebases section.
    - A change in the user's security monitored repository triggers a pipeline build on OSIO.
    - OSIO analytics identifies that a CVE is associated with a user repository for which security alerts are on.
2. Only OSIO admin user of a repository are able to switch on/off the security notification for that repo.

## Checklist
- [x] Have segregation of direct and transitive dependencies for user flow. 
- [x] Pass the effective pom generated during the build to gemini server.
- [x] Remove the logic to generate effective pom in case of user initiated scan.
- [x] Complete the development of unit tests for API server `user-repo/*` endpoints.
- [x] Auth changes for validating user tokens against auth service public keys in gemini service.
- [ ] ~~Productize the CVE ingestion flow to call analytics notification.~~
- [ ] ~~Productize the Build pipeline flow to call analytics notification.~~
- [ ] ~~Complete the development of integration tests for the `/user-repo/*` service workflows.~~
- [ ] ~~Add functionality to `user-repo/drop` endpoint.~~

## Reference
[OSIO Analytics Notification](https://docs.google.com/document/d/1tar8Czb4WEajzHufdgNvnW5qzOzmhDJ88wqwyj42tMQ/edit)

**Comment by abs51295** [comment]
The remaining tasks were re-prioritized and will be taken as a part of Sprint 153. Follow up issue: https://github.com/openshiftio/openshift.io/issues/3982. /cc: @yzainee @sivaavkd @miteshvp @samuzzal-choudhury

**Comment by abs51295** [comment]
Closing the issue since it's completed ;)

**Comment by GeorgeActon** [comment]
@samuzzal-choudhury where is the corresponding link to planner story?
and where is the estimate
incomplete stories do not get closed
they move to next sprint

**Comment by abs51295** [comment]
@GeorgeActon There is a follow up issue for this: https://github.com/openshiftio/openshift.io/issues/4108. Can we close this issue now?

**Comment by sivaavkd** [comment]
Yes, please close this @abs51295
