### ISSUE TITLE
"User story" should be the default instead of "impediment" when creating a child item of an epic in the scrum template of planner.

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#3963]
IDK if a survey is required around this but I'm pretty sure people create user stories much more frequently than they create impediments. I can't imagine a scenario where the number of impediments you have is more than the number of stories you have to work on.

I created 3 user stories as impediments because I wasn't looking the first time I used planner to create them. I assume the same would happen to customers.

![screen shot 2018-07-12 at 11 55 53 am](https://user-images.githubusercontent.com/5445560/42616131-b610fff4-85ca-11e8-9811-c9abd657d2e4.png)

**Comment by GeorgeActon** [comment]
@michaelkleinhenz My input: I would prefer a mechanism like a right click on the + sign which then lets me choose the type of child I want to add instead of immediately popping open a line which requires a second click to select the correct type of child.

**Comment by rootAvish** [comment]
Right, this is fixed for me too.
