### ISSUE TITLE
Create a new project - Wildfly Swarm - fails

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#397]
_From @ldimaggi on July 8, 2017 0:3_

To recreate:
* In a new or existing space, create a new project from the Wildfly swarm - Config Map Quickstart.

This error is logged:

```
[ERROR] Failed to execute goal on project july8: Could not resolve dependencies for project com.example:july8:war:1.0.1: The following artifacts could not be resolved: org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1, org.jboss.openjdk-orb:openjdk-orb:jar:8.0.4.Final: Could not find artifact org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1 in nexus (http://central.maven.org/maven2/) -> [Help 1]
```
[Wildfly_Swarm_config_map_log.txt](https://github.com/fabric8-ui/fabric8-ui/files/1132621/Wildfly_Swarm_config_map_log.txt)

Build log attached.

_Copied from original issue: fabric8-ui/fabric8-ui#1671_

**Comment by qodfathr** [comment]
Wildfly has been removed from the quickstart catalog.
