### ISSUE TITLE
Markdown component layout breaks on copy-paste

### ISSUE THREAD

**Issue by jarifibrahim** [openshiftio/openshift.io#3972]
![screenshot from 2018-07-12 18-19-15](https://user-images.githubusercontent.com/12949454/42634216-3df3f9b4-8600-11e8-9179-9216392ce024.png)

NOTE - The extra whilte space cannot be removed by delete/backspace key

Steps to reproduce 
1. Copy any json from https://github.com/fabric8-services/fabric8-wit/blob/68996d1555a29a9ef310403403855b47559d5a71/controller/test-files/work_item_type/list/ok_agile.res.payload.golden.json#L690
2. Paste it in the description field.

**Comment by jarifibrahim** [comment]
@SMahil I've assigned it to you. Feel free to assign it to someone else.

**Comment by SMahil** [comment]
@DhritiShikhar @baijum Please provide your input on this issue as the description content will be accessed from backend

**Comment by jarifibrahim** [comment]
>@DhritiShikhar @baijum Please provide your input on this issue as the description content will be accessed from backend

This issue has nothing to do with the backend. The markdown component breaks on copy paste. That's the issue.

**Comment by christianvogt** [comment]
We should look at making this a normal text area instead of a `contenteditable` element.
