### ISSUE TITLE
Selecting an Iteration also shows WIs in Childs now, but doesn't apply the query

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#3974]
https://openshift.io/openshiftio/Openshift_io/plan?q=(space:e8864cfe-f65a-4351-85a4-3a585d801b45%20$AND%20typegroup.name:Execution%20$AND%20iteration:eeb1f690-7258-4bcf-a09f-22aaf3e71216%20$AND%20workitemtype:2c169431-a55d-49eb-af74-cc19e895356f)

..shows the Epics from J and below, but *also non-Epics from child iterations*.

**Comment by michaelkleinhenz** [comment]
No workaround exists and this severely impacts the query ability, setting this to SEV-1.

**Comment by jarifibrahim** [comment]
Fixed via https://github.com/fabric8-services/fabric8-wit/pull/2168

**Comment by jarifibrahim** [comment]
Reopening this since the fix is not yet on prod.

**Comment by baijum** [comment]
This has been addressed here: https://github.com/fabric8-services/fabric8-wit/pull/2182
