### ISSUE TITLE
The problem with Pagination in Planner

### ISSUE THREAD

**Issue by DhritiShikhar** [openshiftio/openshift.io#3978]
The Planner UI doesnot support pagination where as the backend returns paginated response. If a workitem does not lie in the first page, the workitem could not appear in the UI (refer: https://github.com/openshiftio/openshift.io/issues/3973)

The UI could not implement pagination because it messes up the table tree view experience.

It is not the best idea to fetch all the work items at once from backend.

A temporary fix is to increase the page limit in wit repo (Refer PR: https://github.com/fabric8-services/fabric8-wit/pull/2166) 

This needs more discussion and a proper fix.

**Comment by kwk** [comment]
My suggestion for the client is to fetch as many pages as it needs (possibly all) or can handle (maybe 1000 work items?) and then render the tree or the list. There's no need to implement pagination that is visible in the UI. 

While collecting the pages from the backend the UI should consider a maximum limit that it wants to show. If that limit is reached it should tell the user to narrow down the search.

**Comment by baijum** [comment]
If we implement the idea suggested by @kwk the chance for displaying the warning message by default is very high. For example, in the agile template we display work items belongs to all work item types. A space like "Openshift_io" will have hundreds of open issues by default.

My suggestion is to avoid all kinds of nested tree structures, not even exploration. And introduce proper pagination.

Few points from [UX stackexchange](https://ux.stackexchange.com/questions/102490/organization-hierarchy-vs-labels/112647):

    There are some nasty issues with hierarchical trees in my opinion:

    * Searching for items in a tree is problematic. The user would expect you to show only
      relevant results. But this leaves out important information, as to where in the 
      hierarchy items belong.

    * To address this, you might want to display a subset of the tree with the direct
      ancestors of a highlighted item. This leads to a confusing search result,
      that asks users to filter out irrelevant information by them self.
     
    * If the tree becomes large, you might not want to load all items into the user
      interface at once. This is usually addressed using pagination. But for trees
      pagination is awful. Where do you break a page, and how do you indicate
      where the next page starts in relation to the hierarchy?
     
    * To reduce loading time, you might instead initially collapse some parts of
       the tree, but this again leads to confusing behavior when searching for items
       that might be in the collapsed parts of the tree.  Furthermore, browsing for items
       becomes a pain, where the user needs to do a lot of clicking.

**Comment by rgarg1** [comment]
Please consider if _Keyset-based Pagination_ is useful in this case:
https://blog.philipphauer.de/restful-api-design-best-practices/#keyset-based-pagination-aka-continuation-token-cursor

**Comment by Veethika** [comment]
UX solution for New work-item browsing: https://redhat.invisionapp.com/share/D7N6MW8YBPW
Unassigning myself until further UX work is required on this.

**Comment by Veethika** [comment]
@DhritiShikhar many of the concerns were addressed here #4082 
Should this discussion be closed now?

**Comment by DhritiShikhar** [comment]
@Veethika I will close this issue.
