### ISSUE TITLE
Create a new project - Wildfly HTTP - fails

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#398]
_From @ldimaggi on July 8, 2017 0:11_

To recreate:
* In a new or existing space, create a new project from the Wildfly HTTP quickstart

This error is logged:

```
[ERROR] Failed to execute goal on project july8: Could not resolve dependencies for project com.example:july8:war:1.0.1: Could not find artifact org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1 in nexus (http://central.maven.org/maven2/) -> [Help 1]
```
[Wildfly_Swarm_HTTP_log.txt](https://github.com/fabric8-ui/fabric8-ui/files/1132625/Wildfly_Swarm_HTTP_log.txt)

Build log is attached.

_Copied from original issue: fabric8-ui/fabric8-ui#1672_

**Comment by joshuawilson** [comment]
_From @corinnekrych on July 10, 2017 7:45_

@ldimaggi @joshuawilson this is typically NOT a UI issue. I *think* we should not track backend/templates issue in fabric8-ui repo. Let's close it here an open it in relevant repo.

**Comment by joshuawilson** [comment]
_From @jstrachan on July 10, 2017 7:59_

the place to raise issues about quickstarts are here:
general issues:
https://github.com/openshiftio/appdev-planning/issues/
vertx quickstarts:
https://github.com/openshiftio-vertx-boosters 
wildfly quickstarts:
https://github.com/wildfly-swarm-openshiftio-boosters 
spring quickstarts:
https://github.com/snowdrop

I do hope we can setup E2E testing to automatically remove failing quickstarts from the forge wizard so that users can only create working quickstarts on OSIO

**Comment by qodfathr** [comment]
Wildfly has been removed from the quickstart catalog.
