### ISSUE TITLE
Notification Service: Check for newer versions (Build Flow)

### ISSUE THREAD

**Issue by yzainee** [openshiftio/openshift.io#3983]
**Planner:** https://openshift.io/openshiftio/Openshift_io/plan/detail/236

- [x] Modify the aggregator API - Redirect the call for newer version notification

- [x] Use the stack data for version comparison & license compatibility

- [ ] Generate report

- [ ] Test Cases

- [ ] Test [ When the api is called, it should return back correct report in json format ]

**Comment by yzainee** [comment]
Refer to : https://docs.google.com/presentation/d/1QOYGmtw-YsfymjEr902_XQDF-_i-HYSKBzaieX9f1SQ/edit#slide=id.g3cfd439a6e_0_120

**Comment by GeetikaBatra** [comment]
@yzainee. Where would this endpoint be running `user-repos/versions-notify`.

**Comment by GeetikaBatra** [comment]
@yusuf, Can you add epic corresponding to this workitem. Thanks :)

**Comment by yzainee** [comment]
Closing the issue as the flow for newer versions is going to be triggered only via the cron job. The build flow is no longer required.
