### ISSUE TITLE
Notification Service: Enhance the logic to check for license

### ISSUE THREAD

**Issue by yzainee** [openshiftio/openshift.io#3984]
As a notification application, i should get the additional data for the license conflict, so that the report can contain details of it

Description
For all the newer versions recommended to the user, the report should also contain if any of the newer versions contains any conflicts related to the licenses.

Acceptance Criteria
The report generated should contain license conflict details

**Comment by GeetikaBatra** [comment]
This one is covered by https://github.com/openshiftio/openshift.io/issues/4114
