### ISSUE TITLE
Calls to https://recommender.api.openshift.io/api/v1/stack-analyses endpoint fail with unexpected error

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3987]
The problem is that if I attempt an API call to the https://recommender.api.openshift.io/api/v1/stack-analyses/ endpoint, and reference a github repo for an existing booster - such as https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-rest-http - the call is successful.

However, if I make the same API call and reference another repo - for example, a repo that is the result of building a new app in OpenShift.io  - this repo - https://github.com/ldimaggi/test123 - I see this error in the response:
"error": "Error processing request. Please upload a valid manifest files."

So - my question is - what are the manifest requirements that must be met in order for the API call to be successful?

**Comment by miteshvp** [comment]
@ravsa - can you PTAL here?

**Comment by miteshvp** [comment]
Its an expected behavior and git repo can only be supported for boosters currently. Hence removing it as bug and closing this.

**Comment by ravsa** [comment]
@miteshvp correct, And if user wants run stack-analyses on other maven project,  that project should contains effective-pom and do not need to pass ‘source=osio’ in payload.

**Comment by ldimaggi** [comment]
In order to perform this action on any maven project that is not an existing booster, these conditions must be met:

1) The project should contain effective POM file else response will be empty insights.
mvn help:effective-pom -f <input-pom.xml> -Doutput=<output-file>

2) payload ->
         a) Don't need to pass `source=osio`
         b) `github_ref` = 'branch name or release version'
       ```

   payload = {
            'github_url': 'https://github.com/ldimaggi/test123',
            #  'source': 'osio',
            'github_ref': 'master'
        }


```

**Comment by msrb** [comment]
Note it seems like the `source` param is not documented:
https://docs.openshift.io/analytics-integration-api-guide.html#_parameters

@ldimaggi how did you discover about the param?
