### ISSUE TITLE
Jenkins Fabric8 is still using Centos as base image

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#3989]
We need it update to a RHEL image,

**Comment by arilivigni** [comment]
@chmouel I think it is ok to use the CentOS image I think this is part of using the OpenShift Jenkins CentOS image.

**Comment by lordofthejars** [comment]
Can we close this issue? For now I leave as some work to be done, but if we agree on no changes then we can close it.

**Comment by chmouel** [comment]
Probably not! Jaime was the one who did the update of all OSIO to rhel
images maybe check with him and PO if it's okay for this one to leave it to
centos?

**Comment by chmouel** [comment]
Jaime == @jmelis

**Comment by jmelis** [comment]
I think this can be closed. The tenant resources are all based on CentOS due to licensing issues, I don't think they will be migrated to RHEL at any point.

@chmouel are there other RHEL based tenant resources?

**Comment by chmouel** [comment]
all good thanks for the clarification,
