### ISSUE TITLE
Two linked github accounts

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#399]
Somehow I have two github accounts associated with my one OSIO account of "burr@redhat.com".  Right now, when I create a new project via the Forge Wizard, it creates a new project on github under "burrgit", when I perform a git commit and push in Che, it shows that activity as "burrsutter".

as an example:
https://github.com/burrsutter/hothvertx6/graphs/contributors

**Comment by alexeykazakov** [comment]
Burr has two accounts:
#1 username - burrsutter, email - burr@redhat.com, linked to burrsutter GitHub.
#2 username - rhn-engineering-bsutter, email - bsutter@redhat.com, linked to burrgit GitHub.

For some reason, when Burr is logged in as burrsutter the initial github commit is created using his GitHub from the second account.

cc: @aslakknutsen @jstrachan

**Comment by alexeykazakov** [comment]
Aslak is right. In Keycloak burr@redhat.com email is associated with "burrsutter" user. But in GitHub this emails is associated with burrgit. This is why burrgit is recognized by GitHub as the author of the commit pushed by burrsutter (we use the Keycloak user's email when committing).

**Comment by joshuawilson** [comment]
This appears to be an issue with @burrsutter listed email accounts on RHD and on github. Since the fix is to create a new account or clean the existing ones, can we close this?

**Comment by alexeykazakov** [comment]
> Since the fix is to create a new account or clean the existing ones, can we close this?

It's not really a fix. It's a workaround. A proper fix would be to obtain the GitHub email via GitHub API and use it to create commits instead of relaying on the email from the Keycloak account.

**Comment by joshuawilson** [comment]
@alexeykazakov you want to keep it open and try to fix it?

**Comment by l0rd** [comment]
cc @ibuziuk

**Comment by ibuziuk** [comment]
@l0rd I'm going to improve email search on che-starter side, but this is not going to fix this issue -  it will just allow to get user's primary email even if it is private.

**Comment by ibuziuk** [comment]
PR for che-starter - https://github.com/redhat-developer/che-starter/pull/203

**Comment by alexeykazakov** [comment]
We need to fix it in the app wizard too. Or whatever is creating the very first commit.

**Comment by bmicklea** [comment]
Looks like the correct solution to this is https://github.com/fabric8io/fabric8-generator/issues/32. That issue should be prioritized to avoid a similar situation with external users in the early access program.

**Comment by l0rd** [comment]
Removing `area/che` label since it's has been fixed in che-starter

**Comment by joshuawilson** [comment]
@l0rd what team is doing this work?

**Comment by l0rd** [comment]
@joshuawilson my understanding is that even if Che is able to infer the right github account now we still need to make sure that "app-wizard or whatever does the first commit" infer the right github account too.

**Comment by joshuawilson** [comment]
Thanks @l0rd

**Comment by burrsutter** [comment]
Closing, I believe Aslak fixed this up
