### ISSUE TITLE
Outdated references to groovy in repos generated for new apps by OSIO 

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3990]
Steps to recreeate:
* Create a new app in OSIO - select Vert.X/REST 
* Observe the reference to groovy 2.4.9 in /src/licenses/licenses.xml

This should be updated to 2.4.12

**Comment by ppitonak** [comment]
duplicate of #4001?

**Comment by ldimaggi** [comment]
Yup - closing as a duplicate of #4001 - let's track the issue in #4001.
