### ISSUE TITLE
Work item sequence in quick inline-add drop-down could be improved for usability

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3991]
The first item in the list should be the child WIT, followed by Defect and then impediments.

For example:

**Theme**
  - Epic
  - Defect
  - Impediment

**Epic**
  - Story
  - Defect
  - Impediment

**Story** is already displaying the correct order.

**Comment by rgarg1** [comment]
Cc @Veethika

**Comment by Veethika** [comment]
@rgarg1 looks like this has already been taken care of. Please verify and close.

<img width="304" alt="screen shot 2018-10-08 at 12 45 07 pm" src="https://user-images.githubusercontent.com/35127763/46595893-17839680-caf8-11e8-8830-3ab573ff1614.png">

<img width="262" alt="screen shot 2018-10-08 at 12 45 31 pm" src="https://user-images.githubusercontent.com/35127763/46595894-17839680-caf8-11e8-933f-4870fbaca57f.png">

**Comment by joshuawilson** [comment]
This is fixed, closing.
