### ISSUE TITLE
[8] Ingestion support for Golang

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#3992]
#### Planner link:https://openshift.io/openshiftio/Openshift_io/plan/detail/97

The analytics platform should have all the raw data ingested for the packages present in the manifest files used to train the recommendation model so that it can show the users component information.

#### **Description**

Need to ingest golang packages to graph and S3 so that we can show license/CVE information, version information etc. The packages that we need to ingest would come from the manifest files we collect to train the model. Would also maybe require topics from Github in case we decide to use the CVAE model for the recommendations.

#### **Acceptance Criteria**

- Mercator should support gopkg.lock
- Golang package data should be ingested into S3 and graph sync must go on.

**Comment by msrb** [comment]
Mercator subtask: https://github.com/openshiftio/openshift.io/issues/2893

**Comment by miteshvp** [comment]
Closing this and all the necessary support was introduced and the ingestions completed.
