### ISSUE TITLE
Prod-preview change on codebases page

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#3995]
I've noticed that there is change on Codebases page on prod-preview (actually, E2E tests started to fail on that change). When you have no workspaces and click "Create workspace", normally a new tab with Che would open. But now it does not and you have to click Open manually. Is that expected?

**Comment by aptmac** [comment]
This would have been introduced in a PR relating to opening workspaces with ad-blocker [[0]](https://github.com/fabric8-ui/fabric8-ui/pull/2972#issue-191572823), in response to issue 3565 [[1]](https://github.com/openshiftio/openshift.io/issues/3565)

[0] https://github.com/fabric8-ui/fabric8-ui/pull/2972#issue-191572823
[1] https://github.com/openshiftio/openshift.io/issues/3565

**Comment by ljelinkova** [comment]
OK, so that is a feature. In that case, this behavior should be introduced also when you click the right menu and select "Create workspace". At the moment, this opens a new tab.
