### ISSUE TITLE
UX for Change Type Operation on UI

### ISSUE THREAD

**Issue by sunilmalagi** [openshiftio/openshift.io#3996]
Come up with visual proposal for 'Change Work Item type'.  The user should be allowed to change the Work Item type in both Quick preview and Detailed page.

**Comment by sunilmalagi** [comment]
https://redhat.invisionapp.com/share/27MZUP44AK5#/309101360_01_Existing_Change_Type_Operation

**Comment by joshuawilson** [comment]
This is in production.
