### ISSUE TITLE
Design enhancement for detailed-view in Planner

### ISSUE THREAD

**Issue by Veethika** [openshiftio/openshift.io#3998]
For a more seamless and intuitive experience, while working on Planner, the design for the detailed view needs to be revisited in terms of layout, information, interactions and navigation.

### **Verification Criteria**
- [ ] Revisit the content and information displayed in the detailed view
- [ ] Define interactions for adding/updating/removing info for the final content, wherever applicable
- [ ] Work on the layout and typography variations for the final page keeping in consideration the technical constraints for faster loading
- [ ] Get the concept reviewed by the UX and Planner team

**Comment by Veethika** [comment]
@nimishamukherjee @michaelkleinhenz 
This is a larger story that would also affect the following: #3448 #3951 #3066 #2838 #3786 #3147

**Comment by serenamarie125** [comment]
Based on a conversation held on 2019-Jan-04 including Dev, PM and UX, the UX team will not be providing support for planner items. Closing this issue since this was solely around gathering requirements.
