### ISSUE TITLE
Design enhancement for quick preview for Planner

### ISSUE THREAD

**Issue by Veethika** [openshiftio/openshift.io#3999]
Revisiting the quick preview panel design to ensure the feature serves the expected primary functions without hindering the users from performing other quick actions.

### **Verification Criteria**
- [x] Revisit the content and information displayed in the quick preview - look at different ways of presenting contents such as links, timeline, the title, and description.
- [ ] Define the basic difference between the detailed view and quick preview.
- [ ] Behavior of the panel - appearance, exit, the area covered on list view, toggle b/w different sections and the quick preview
- [x] Standardize the interactions for all the fields inside the panel
- [x] Make the visual feedback for editable fields clear at every stage of editing
- [ ] Sync the interactions and visual design with #3998
- [ ] Look for conflicts in interaction with other quick actions in list view and board view

**Comment by muruGanesan** [comment]
@sunilmalagi, @Veethika:  based on our design review discussion: please find out the necessity of visual changes Vs interaction changes.
i.e. let us fix the interaction flaws from the end-user perspective and then fix the visual issues.

**Comment by Veethika** [comment]
1st draft: https://redhat.invisionapp.com/share/TFNWY6LZJ3Q#/317272289_Low_Fidelity_Wireframe_Template_With_Side_Notes_Copy_17

**Comment by Veethika** [comment]
Because of the changed priorities for the K-train moving this issue back to the backlog.

**Comment by serenamarie125** [comment]
Based on a conversation held on 2019-Jan-04 including Dev, PM and UX, the UX team will not be providing support for planner items. Closing this issue since this was solely around gathering requirements.
