### ISSUE TITLE
Create new project - WildFly Swarm - Health Checks - fails

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#400]
_From @ldimaggi on July 8, 2017 0:17_

To recreate:
* In a new or existing space, create a new project from the WildFly Swarm - Health Checks quickstart

This error is logged:

```
[ERROR] Failed to execute goal on project july8: Could not resolve dependencies for project com.example:july8:war:1.0.1: The following artifacts could not be resolved: org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1, org.jboss.openjdk-orb:openjdk-orb:jar:8.0.4.Final: Could not find artifact org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1 in nexus (http://central.maven.org/maven2/) -> [Help 1]
```

Build log is attached.
[Wildfly_Swarm_health_checks_log.txt](https://github.com/fabric8-ui/fabric8-ui/files/1132631/Wildfly_Swarm_health_checks_log.txt)

_Copied from original issue: fabric8-ui/fabric8-ui#1673_

**Comment by heiko-braun** [comment]
I guess it's missing the jboss maven repositories

**Comment by ldimaggi** [comment]
FYI - the WildFly quickstart is no longer in the new project quickstart list:

Vert.X Basic
Vert.x - ConfigMap
Spring Boot - Basic
Spring Boot - HTTP
Vert.x Health Check Example
Spring Boot - Health Check

**Comment by joshuawilson** [comment]
Closing this as it is not an option for OSIO right now.
