### ISSUE TITLE
Scan report: missing image in header

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#4000]
1. create a new application - http vert.x
2. wait for scan report in your email

result:
* there is an image missing in email header

![osio_scan_report](https://user-images.githubusercontent.com/445100/42755405-501db79c-88f8-11e8-9069-c7c711979d09.png)

**Comment by miteshvp** [comment]
Related to https://github.com/openshiftio/openshift.io/issues/2623

**Comment by aslakknutsen** [comment]
Duplicate https://github.com/openshiftio/openshift.io/issues/1375
