### ISSUE TITLE
Revisit version ranges in CVEjob

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#4004]
**Planner Link:** https://openshift.io/openshiftio/Openshift_io/plan/detail/94

Pull requests with CVE records should, if possible, contain information about which versions of a package are affected by given vulnerability.

**Description:**

We've tried to implement this functionality in the past, but it turned out that versions in NVD often don't match versions from upstream repositories. Therefore we need to revisit our previous approach and fix it.

Example:

1.1.0 (NVD), 1.1.0.Final (Maven Central)

1.17 (NVD), 1.17.0 (PyPi)

**Acceptance Criteria:**

CVEjob is able to prefill "Affected" field in CVE records

**Comment by rootAvish** [comment]
Hey so what do you guys think about putting in a commented version string, like we were discussing it on chat? Also can you please tell me which other ways you were considering?

**Comment by CermakM** [comment]
@msrb can we close this?
