### ISSUE TITLE
Perform network checks while Jenkins spin's new slave agent

### ISSUE THREAD

**Issue by hrishin** [openshiftio/openshift.io#4007]
**Problem:**
Sometimes Jenkins fails to execute job because of slaves not able to communicate with peer services (e.g. content-repo) or master.  

As Jenkins spinup's new slave pod, execute network checks if is pod able to communicate with master or peer services.
This check would help to execute a job reliably and prevent Jenkins slaves to enter into a zombie state.

**Tasks:**
- [ ] Add hook to perform network checks in kubernetes Jenkins plugin delay execution of pod until it reaches master node

related to #3895, #2351

**Comment by kishansagathiya** [comment]
@hrishin I feel like this is same as https://github.com/openshiftio/openshift.io/issues/2973 and https://github.com/openshiftio/openshift.io/issues/2351, but in the form of a task

**Comment by hrishin** [comment]
yes @kishansagathiya they are related. However, #2351 is about handling this problem in OpenShift territory. While this one is about resolving the problem in Jenkins through kubernetes-plugin.

**Comment by kishansagathiya** [comment]
@sthaha had suggested to use slave docker image's ENTRYPOINT to check if it can reach master or not. What I am trying to find is how would slave find the master Jenkins' URL.

**Comment by hrishin** [comment]
Many slave images could have some fixed `entrypoint`. Instead, can we run init containers here to check if the master is reachable? Unlike previous Jenkins case if init container fails here with `restartPolicy: never` then pod will not try to start and the pod lifecycle can be delegated to  Kubernetes/OpenShift.

**Comment by sthaha** [comment]
@hrishin didn't go that path already with jenkins -> content repository and fail? Could you please help me understand why adding this functionality to the the entrypoint script of jnlp container is sub-optimal?

**Comment by sthaha** [comment]
>  had suggested to use slave docker image's ENTRYPOINT to check if it can reach master or not. What I am trying to find is how would slave find the master Jenkins' URL.

@kishansagathiya I meant add the code [here](https://github.com/fabric8-jenkins/jenkins-openshift-base/blob/master/slave-base/contrib/bin/run-jnlp-client) in case it wasn't clear

**Comment by sthaha** [comment]
> Then are we supposed to change the JNLP or other images entrypoint to perform the network checks? > Then do we need to maintain one more image?

No, we should submit the patch upstream. 

> What and how the corrective actions it going to execute once entrypoint function fails to perform network checks?

Just because we are going to do this in the `entrypoint` script doesn't mean it should  be any different to how it would be done in `initContainer`. I.E bail out after some retries. 



> Becasue looking at this cases it feels better to have initcontainer script then entrypoint for couple of reasons

Do you realise the whole point of doing this **NOT** in `initContainer` is because it was [tried once for Jenkins](https://github.com/fabric8-services/fabric8-tenant-jenkins/commit/09073be5fe3090d1effa0618b142f6802ce95991) and created more trouble than any good?

**Comment by kishansagathiya** [comment]
@sthaha @hrishin 
I am planning a check similar to what we had for initContainer. Let me know if this works.
```
for i in {1..100}
    do sleep 1;
    if curl -L -m 4 jenkins:8080
    then
        exit 0
    else
        exit 1
    fi
done; 
```

**Comment by kishansagathiya** [comment]
@sthaha not sure what should be the right course of action if we find that network is faulty

**Comment by chmouel** [comment]
Just exit 1 IMHO should be fine, at least it would come back to the user as fail instead of stucks,

**Comment by hrishin** [comment]
> Do you realise the whole point of doing this NOT in initContainer is because it was tried once for Jenkins and created more trouble than any good?

Yes, unlike Jenkins in this case event if` initContainer` fails to execute (assuming worst case) anyways pod won't come-up and Jenkins will try to spin up new slave pod I guess. Isnt it?

**Comment by kishansagathiya** [comment]
Resolved with 
https://github.com/fabric8io/osio-pipeline/pull/50
https://github.com/fabric8io/fabric8-pipeline-library/pull/434
https://github.com/fabric8-jenkins/jenkins-openshift-base/pull/47
