### ISSUE TITLE
Prod-preview: Cannot create an application

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4008]
When I try to create a new space on prod-preview, I get the following error:
![space](https://user-images.githubusercontent.com/2078072/42800962-111f48ac-899e-11e8-9dec-e2969f038a14.png)

The space is created and I am able to continue to create an application, but it fails with the following error:
![app](https://user-images.githubusercontent.com/2078072/42800989-26ac6c72-899e-11e8-8951-94aad646bf14.png)

**Comment by ppitonak** [comment]
works for me

**Comment by ljelinkova** [comment]
Works for me too and also E2E tests on Jenkins and prod-preview passed.
