### ISSUE TITLE
Create new project - WildFly Swarm - REST and RH SSO - fails

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#401]
_From @ldimaggi on July 8, 2017 0:23_

To recreate:
* In a new or existing space create a new project from the WildFly Swarm - REST and RH SSO  quickstart

This error is logged:
[Wildfly_Swarm_REST_and_RH_SSO_log.txt](https://github.com/fabric8-ui/fabric8-ui/files/1132633/Wildfly_Swarm_REST_and_RH_SSO_log.txt)

```
[ERROR] Failed to execute goal on project wfswarm-rest-http-secured: Could not resolve dependencies for project com.example:wfswarm-rest-http-secured:war:1.0.1: Could not find artifact org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1 in nexus (http://central.maven.org/maven2/) -> [Help 1]
```

_Copied from original issue: fabric8-ui/fabric8-ui#1674_

**Comment by joshuawilson** [comment]
_From @bobmcwhirter on July 10, 2017 12:19_

The -jbossorg suffix indicates that the JBoss Nexus needs to be configured either via pom.xml or your personal settings.xml mayhap.

**Comment by qodfathr** [comment]
Wildfly has been removed from the quickstart catalog.
