### ISSUE TITLE
Launcher UI - can we avoid a 3-step display?

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#4018]
In the Launcher today, the user is navigated from the Launcher's black background, to the user's dashboard, to the Launcher:

![myimage](https://user-images.githubusercontent.com/642621/42856199-169fd070-8a12-11e8-9c0d-2e129e380109.gif)

Can we avoid the 2nd step and not display the user's dashboard?

**Comment by vikram-raj** [comment]
@ldimaggi This issue has been fixed and in production. Can you please verify?

**Comment by ldimaggi** [comment]
This issue is no longer present in production - clsoing.
