### ISSUE TITLE
Error while creating application

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4019]
The E2E tests ran into this error today - what does the error message mean? Could you change the message to something meaningful?

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-released/329/03-01-afterEach.png

**Comment by nimishamukherjee** [comment]
@ljelinkova can you confirm if this only happens during E2E tests. Have you encountered this when using the UI?

**Comment by bartoszmajsak** [comment]
@ljelinkova can you close that issue if the problem is not occurring anymore?

**Comment by ljelinkova** [comment]
Ok, closing the issue.
