### ISSUE TITLE
Setup CI/CD process in CICO for jenkins-openshift-base,  openshift-jenkins-s2i-config, fabric8-tenant-jenkins and fabric8-tenant

### ISSUE THREAD

**Issue by rupalibehera** [openshiftio/openshift.io#4023]
This current process is confusing to remember check if we can reduce the jobs or automate in a better way

- [ ] learn how to setup Job in CICO

- [ ] Figure out how/where to move secrets if any

- [ ] jenkins-openshift-base: write CI/CD pipeline and move to CICO

- [ ] openshift-jenkins-s2i-config: write CI/CD pipeline and move to CICO

- [ ] fabric8-tenant-jenkins: write CI/CD pipeline and move to CICO, check if we can replace this https://nexus.cd.test.fabric8.io/ with something else in CICO or just remove it 

- [ ] fabric8-tenant: write CI/CD pipeline and move to CICO

**Comment by GeorgeActon** [comment]
Sev numbers are only used for defects. This is planned work and should be a story or task.

**Comment by sthaha** [comment]
Closing this as this task is moved to Planner.
