### ISSUE TITLE
Setup CI/CD process in CICO for builder-clients, maven-builder and caddy-server

### ISSUE THREAD

**Issue by rupalibehera** [openshiftio/openshift.io#4024]
- [x] Learn how to setup Job in CICO
- [x] Figure out how/where to move secrets if any
- [x] Setup job for builder-clients
- [x] Setup job for maven-builder
<strike>- [ ] Setup job for caddy-server</strike>

**Comment by GeorgeActon** [comment]
Sev numbers are only used for defects. This is planned work and should be a story or task.

**Comment by sthaha** [comment]
Closing this issue as it is moved to planner.

**Comment by chmouel** [comment]
Done for maven and builder clients, archived caddy-server since not used anymore,
