### ISSUE TITLE
Work item tree auto-expanding on work item update

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#4025]
Planner backlog view represents data in tree form. It is observed that while working and updating a work item in a particular tree, the collapsed tree auto-expands and the user loses track of the work item in focus.

The auto-expanding tree creates a clutter of too many work item and makes using the system extremely difficult.

See it in action here (keep an eye on the collapsed Theme with ID=200):

![auto tree expanded](https://user-images.githubusercontent.com/28748448/42931494-7889207e-8b5d-11e8-9d81-6f87442f2c91.gif)

**Comment by joshuawilson** [comment]
I can also reproduce this. 
@sahil143 what is the status on this.

**Comment by sahil143** [comment]
> @sahil143 what is the status on this.
Fixed in the referenced PR

**Comment by joshuawilson** [comment]
this does not appear fixed yet

**Comment by rohitkrai03** [comment]
@joshuawilson This has been fixed and demoed.
