### ISSUE TITLE
Closed work items are being displayed in the list view

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#4026]
By default, closed work items should be filtered away from the list view, but apparently, due to some defect, the closed work items are being displayed. See here:

![closed wi displayed](https://user-images.githubusercontent.com/28748448/42939878-08e3623a-8b75-11e8-8b56-b72bb3a3f233.png)

**Comment by baijum** [comment]
This state value is `Closed` (capitalized) in Agile space template. Whereas in SDD, it is lower case, `closed`.

**Comment by kwk** [comment]
@rgarg1 in your screenshot you have toggled on "Show Completed" and so you should expect to see closed items. Right @michaelkleinhenz @baijum @sanbornsen ?

**Comment by michaelkleinhenz** [comment]
Yes, indeed.

**Comment by kwk** [comment]
@rgarg1 also, next time please paste a URL so we can see the ourselves.

**Comment by rgarg1** [comment]
@kwk Ignore the selected "Show completed" checkbox; it doesn't makes a difference.

**Comment by kwk** [comment]
@baijum is right. The executed query to the backend contains a hard-coded list of states to exclude: 

```https://api.openshift.io/api/search?page[limit]=200&filter[expression]={"$AND":[{"space":{"$EQ":"8469e18f-d49c-47b1-b45e-e96ff18fbcdf"}},{"typegroup.name":{"$EQ":"Work%20Items"}},{"state":{"$NE":"closed"}},{"state":{"$NE":"Done"}},{"state":{"$NE":"Removed"}}],"$OPTS":{"tree-view":true}}```

@sanbornsen please make sure to include all the reasonable states from all the templates.

**Comment by jarifibrahim** [comment]
This one has been fixed. Please reopen if this issue persists.
