### ISSUE TITLE
'Meta State' drop-down and warning showing up in all work items

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#4027]
**Meta States** are meant to be used internally by Planner to keep track of the various states of a work item. This should not be exposed to the user. Also, a sticky warning message is showing up, which looks ugly:

![metastate error](https://user-images.githubusercontent.com/28748448/42932291-89b9effc-8b5f-11e8-88d1-172205125869.png)

**Comment by Raunak1203** [comment]
https://github.com/fabric8-ui/fabric8-planner/pull/2729/commits/f1dce40ee2c93b88ad349b7d965d89ae76524f69 removes meta state field from the detail page

**Comment by jarifibrahim** [comment]
This issue has been resolved. Closing this.
