### ISSUE TITLE
Underscores "_" in the space name are replaced with spaces on Account home page

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#4028]
All underscores in a space name are replaced with spaces on the Account home page. Either don't allow underscores in space name or display the exact name on all pages. Changing space names automatically causes confusion to users. See here:

![space name underscores not displayed](https://user-images.githubusercontent.com/28748448/42932513-187c05b8-8b60-11e8-8bb7-025263afa460.png)

**my_space** is displayed as **my space**

**Comment by jiekang** [comment]
Similar to https://github.com/openshiftio/openshift.io/issues/3793

This is being worked on.
