### ISSUE TITLE
Documentation for fabric8-auth service

### ISSUE THREAD

**Issue by humaton** [openshiftio/openshift.io#4029]
The new authentication service is not well documented.
What is the difference between Service account token and regular user token?
What specific info do we store in user token?
How do you identify the public key? (keycloak provided us URL that returned one clearly identifiable key https://sso.openshift.io/auth/realms/fabric8/)

**Comment by sbose78** [comment]
> What is the difference between Service account token and regular user token?

This is already documented here: https://fabric8-services.github.io/fabric8-auth/reference.html#_service_accounts

> How do you identify the public key? (keycloak provided us URL that returned one clearly identifiable key https://sso.openshift.io/auth/realms/fabric8/)

Every token has a "kid" claim. Validate the token with the public key having the similar "kid" https://auth.openshift.io/api/token/keys?format=pem . 
Usually languages/frameworks have a JWT 'middleware' which takes care of validation if configured with a set of one of more public keys.

( will also document )
