### ISSUE TITLE
Collect and normalize feedback data

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#4032]
**Planner Link:** https://openshift.io/openshiftio/Openshift_io/plan/detail/227

In order to improve analytics support for Maven, we need to collect feedback from users, normalize it and store it on S3 where other components can find it and make use of it.

**Acceptance criteria:**

* normalized feedback data is available in S3

**Comment by sara-02** [comment]
The normalized data format that will be added under the `hpf-insights/maven/training/feedback.json` is :
```
[
{"recommendation_type": "alternate/companion",
"recommended_package_name":"only name no version info needed"
"feedback": "positive/negative(maybe 0/1 in the RDS table that is also fine)"
"input_package_list": ["package_name1", "package_name2"," only name no version info needed"]
 },
]
```
The bucket name and file path is loaded from env.
The current feedback will use only `recommendation_type`: `companion`. So the Postgres query to collect and normalize data should be parameterized for getting `only alternative or only companion or both`.

**Comment by humaton** [comment]
@sara-02 any updates on this? Is the entry point in server useful for you? 
Can we close it?

**Comment by humaton** [comment]
sample data output can be found here https://paste.fedoraproject.org/paste/siSDNTwoq-UjN8d-to5O8g
