### ISSUE TITLE
Accommodate the feedback logic into the current training module

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#4034]
**Planner Link:** https://openshift.io/openshiftio/Openshift_io/plan/detail/229

Accommodate the feedback logic implemented in https://openshift.io/openshiftio/Openshift_io/plan/detail/228 into the current training module.

**Tasks:**

* Refactor the feedback logic as per the changes in the training and scoring logic.
* Test the workflow.

**Acceptance Criteria:**

* Test the workflow.

**Comment by sara-02** [comment]
Covered in the commits to PR https://github.com/fabric8-analytics/f8a-hpf-insights/pull/30/commits/9a8ecdb9cfad87e117b1ac8d0aa569c94f37e389 and https://github.com/fabric8-analytics/f8a-hpf-insights/pull/30/commits/2dd8b9433890fe6d20f9a9171f605e7d8f4bc900
