### ISSUE TITLE
Notification URL issue

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#4037]
Steps:

- Update/ Create a work item in production.
- A mail is sent to your user account.
- Go to mail and click on the link to the work item [userName/spaceName]
- It shows busy indicator

![peek 2018-07-23 11-27](https://user-images.githubusercontent.com/34271052/43059800-d228ec7a-8e6b-11e8-94f4-80b254eb98ba.gif)

**Comment by rohitkrai03** [comment]
@Raunak1203 Is that the work item link or area link? When i tried it, work item link opened fine but the area link seems to be broken.

Current link is being formed in the format `https://openshift.io/<username>/<spacename>/plan?area=<areaname>`

I even tried something like `https://openshift.io/<username>/<spacename>/plan?q=(area:<areaname>)` which gives 0 work items in the result.

I think working format for the link should be something like `https://openshift.io/<username>/<spacename>/plan?q=(area:<area_id>)`

This is where the URL is formed for email template - 
- https://github.com/fabric8-services/fabric8-notification/blob/master/template/workitem.update/body.html#L76
- https://github.com/fabric8-services/fabric8-notification/blob/master/template/workitem.create/body.html#L80

**Comment by Raunak1203** [comment]
@rohitkrai03 area link is broken.
So, when we are in planner URL is https://openshift.io/<username>/<spacename>/plan?q=(space:<space_id>AND%20typegroup.name:Scenarios)&showTree=true

@vikram-raj  @sanbornsen can comment more on this.

**Comment by rohitkrai03** [comment]
@sbose78 This one has been idle for a week now. Maybe you can point it to someone who can work on notification-service to refactor the URL formation.
