### ISSUE TITLE
Running tests in Che workspace for project created from "Vert.X ConfigMap" workspace = Syntax error in test code

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#404]
_From @ldimaggi on July 10, 2017 20:0_

_Copied from original issue: fabric8-ui/fabric8-ui#1700_

**Comment by joshuawilson** [comment]
_From @ldimaggi on July 10, 2017 20:2_

The OpenShiftIT test contains this code:

```
   @Test
    public void testDThatWeServeErrorWithoutConfigMap() {
        get("/api/greeting").then().statusCode(200);
        assistant.client().configMaps().withName("app-config").delete();
        await().atMost(5, TimeUnit.MINUTES).catchUncaughtExceptions().until(() ->
                get("/api/greeting").then().statusCode(500)
        );
    }
```
Which results in a syntax error as the returned ValidatableResponse cannot be converted to a boolean. This code change seems to work:

```

   @Test
    public void testDThatWeServeErrorWithoutConfigMap() {
        get("/api/greeting").then().statusCode(200);
        assistant.client().configMaps().withName("app-config").delete();

        await().atMost(5, TimeUnit.MINUTES).catchUncaughtExceptions().until(() -> {
        ValidatableResponse response = get("/api/greeting").then();
            response.statusCode(500);
    });

    }

```

**Comment by joshuawilson** [comment]
_From @ldimaggi on July 12, 2017 17:49_

Tests were run in the UI, from the Run->Test menu.

**Comment by l0rd** [comment]
@joshuawilson removing label `area/che` because it doesn't look Che related. 

I have the exact same issue if I open the project with another IDE (IntelliJ):

![image](https://user-images.githubusercontent.com/606959/28568711-0a3ec6be-7137-11e7-932a-65ccb90d0cfa.png)

**Comment by gastaldi** [comment]
Is this still happening?

**Comment by qodfathr** [comment]
cc: @slemeur

**Comment by ldimaggi** [comment]
I recommend closing this issue in favor of the quickstart/documentation issue logged here: https://github.com/openshiftio/openshift.io/issues/3120

Also - there are more recent (April 2018) quickstart issues that supercede this issue.
