### ISSUE TITLE
[2] Effort field populates incorrect value

### ISSUE THREAD

**Issue by tinakurian** [openshiftio/openshift.io#4047]
Enter the value 11111111111111111.51 in the effort field. On save, this value is converted to 11111111111111112

Enter the value 111111111111111111111111.51 and it will save as 1.1111111111111111e+23. However, attempting to re-save this value will result in the following error message: "Invalid value for the field type float"

**Comment by stevengutz** [comment]
Nice defect.  I was trying to convince people that this field should be an integer.  Time to say "I told you so" ;-)

**Comment by nimishamukherjee** [comment]
@kwk would your work around default values address this issue?

**Comment by jarifibrahim** [comment]
This is failing from the frontend for now. The field type `effort` and `storypoints` are of kind `float` and we cannot have a float with more than `17 digits` (computational limits). We should restrict this on the UI. Allow something like max 5 digits.

**Comment by nimishamukherjee** [comment]
@jarifibrahim so integer should also be restricted to 5 digits?

**Comment by jarifibrahim** [comment]
@nimishamukherjee yes. Every field should have some kind of limitations. 5 digits on an integer or float field should be more than enough.

**Comment by abhinandan13jan** [comment]
currently effort field will only allow values between (-2147483647) and (+2147483648). Closing this issue.
