### ISSUE TITLE
Moving focus off of some fields does not force the editing icons to disappear

### ISSUE THREAD

**Issue by tinakurian** [openshiftio/openshift.io#4049]
When moving focus off of the description field, the 'check mark' and 'x' icons do not disappear the same way they do with the title field. 

Other fields that behaves this way is the effort field and comments field.

These fields should function the same way as the title field.

**Comment by divyanshiGupta** [comment]
@sanbornsen @sahil143 we don't want to close dynamic fields on outside-click, right? If yes, then there are two ways to fix this issue :-

1. Remove close on outside-click from title field.
2. Add close on outside-click on all text-fields including the dynamic-fields.

**Comment by divyanshiGupta** [comment]
@Veethika do we close all the text-fields on outside-click including the dynamic-fields?

**Comment by Veethika** [comment]
@tinakurian can you confirm if the issue still exists? I cannot reproduce it.
