### ISSUE TITLE
[RepoDependencyFinderTask] duplicate key value violates unique constraint "worker_results_worker_id_key" 

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#4050]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/5742/

Happens quite frequently.

```
IntegrityError: duplicate key value violates unique constraint "worker_results_worker_id_key"
DETAIL:  Key (worker_id)=(9e1da3c6-373a-42e9-b59b-0b7b979dc2de) already exists.

  File "sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
```

**Comment by GeorgeActon** [comment]
@msrb I set this to p4 which is 'normal' if it is more urgent than that then change the prioirity to either p2 or p3

**Comment by msrb** [comment]
We fixed couple of IntegrityError issues in the past two months. I don't see this one in the logs any more.
