### ISSUE TITLE
Running tests in Che workspace for project created from "Vert.X HTTP +  ConfigMap" workspace = Syntax error in test code

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#406]
_From @ldimaggi on July 10, 2017 21:26_

_Copied from original issue: fabric8-ui/fabric8-ui#1704_

**Comment by joshuawilson** [comment]
_From @ldimaggi on July 10, 2017 21:27_

The same error as described in this issue is seen:
https://github.com/fabric8-ui/fabric8-ui/issues/1700

**Comment by joshuawilson** [comment]
_From @ldimaggi on July 12, 2017 17:48_

Tests were run in the UI, from the Run->Test menu.

**Comment by l0rd** [comment]
@joshuawilson as for #404 I'm removing label `area/che` because it doesn't look Che related.

**Comment by gastaldi** [comment]
You need the `openshift` maven profile enabled for that to work correctly

**Comment by qodfathr** [comment]
cc: @slemeur

**Comment by ldimaggi** [comment]
I recommend closing this issue in favor of the quickstart/documentation issue logged here: https://github.com/openshiftio/openshift.io/issues/3120

Also - there are more recent (April 2018) quickstart issues that supercede this issue.
