### ISSUE TITLE
Validate environments flows

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4064]
Verify that the flows documented [here](https://redhat.invisionapp.com/share/MSMWAR0WX8P#/screens/290869534) are accurate and cover all use cases we need for J Train.

Previous Issue based on which the above flow is made:https://github.com/openshiftio/openshift.io/issues/2845

Met with the OSIO architects, Serena & Catherine (optional) to validate that the flows are accurate.  Note that Aslak is the primary stakeholder for this story.

Background:
Currently when you create an application, part of the process is selecting a pipeline, where stage & run are hardcoded to online.  We need to provide a mechanism where the developer can select which instance is utilized for each.

**Comment by serenamarie125** [comment]
@catrobson please review content of this issue

**Comment by catrobson** [comment]
@serenamarie125 - edited one line.  Otherwise looks good to me.

**Comment by serenamarie125** [comment]
@parvathyvr this is the story we discussed on Monday.  Let us know if you have any questions!

**Comment by parvathyvr** [comment]
The updated OSIO Environment flow after the discussion with the stakeholders:
https://redhat.invisionapp.com/share/HQNBB7SUNTM#/312253087_Table_Of_Contents
