### ISSUE TITLE
Deployments page - brainstorm on how to visualize when a DB exists

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4065]
Investigate methods to visualize when databases exist in an app environment on the deployments page.

Background:
Currently we have too simplistic of a view of what an application really is.  The dev team is suggesting that we investigate having a single card for the code, but an additional card for a database.

- Touch base with Chris Shinn to see if any of the design thoughts and concepts from the application topology view can be utilized here as well.
- Brainstorm on design concepts
- Share design concepts with Catherine & Serena

**Comment by serenamarie125** [comment]
@catrobson please review

**Comment by serenamarie125** [comment]
@sdash-redhat this is the story we discussed yesterday.  Please let us know if you have any questions.  Thanks!

**Comment by sdash-redhat** [comment]
Thanks @serenamarie125, will connect with Chris today. Will keep you updated.

**Comment by sdash-redhat** [comment]
I have collated some of my thoughts and understanding as a mindmap in the following InVision link:

**https://redhat.invisionapp.com/share/DRN7CQASTJ7#/311139340_Deployments_Page-4065-Understanding-0-1_**

Please review and share your thought/comment on any node of thought ...this will help me understand the context better. 

Also please feel free to point out if any other angle, issues perspectives we need to see.

Please add them as comments, I will collect them and update the document that we can use in coming times to refer in discussions and help us set some expectations from the deployments page.

**Comment by sdash-redhat** [comment]
Thanks, @bartoszmajsak  for pointing this out. Keeping a note of it. 

Can you also help in reviewing the scenarios and understanding mentioned in this link ?**https://redhat.invisionapp.com/share/DRN7CQASTJ7#/311139340_Deployments_Page-4065-Understanding-0-1_**

Please feel free to add your thoughts as a comment against any point mentioned there.

**Comment by sdash-redhat** [comment]
Added a slide with the 4 basic questions to know the common understanding https://docs.google.com/presentation/d/1bRn63ZVxb24unGGOTscs72UGtUQocgb3Hxhx9w7XCNQ/edit?usp=sharing

**Comment by catrobson** [comment]
This solution should extend beyond just a Database, and also be able to handle other "Auxiliary" pods in an application such as a message queue, topic queue, etc.

**Comment by sdash-redhat** [comment]
Based on the last meeting with reference to https://docs.google.com/presentation/d/1bRn63ZVxb24unGGOTscs72UGtUQocgb3Hxhx9w7XCNQ/edit?usp=sharing helped in pointing to one aspect that the current deployments page should be considered from Ops perspective, that will allow us to handle entities in multi container scenarios. 

In the similar line, the developer's perspective would be more geared towards application perspective, which would need in the line of what we are currently having in deployments page.. for example the application and environment relationships. I am exploring this dimension also and will update soon with  a highlevel data points list that would try to distribute the data points from both the angles. Mostly this would mean that we may need 2 views ..one application view (from what developer would expect) and other the deployments view (from Ops perspective)

Based on that we can meet and discuss if these are making sense to the team or something needs to be tweaked. Based on that we can take the design forward. 

@aslakknutsen @joshuawilson @serenamarie125 @catrobson @muruGanesan @parvathyvr

**Comment by sdash-redhat** [comment]
There may be 2 personae having user goals as follows -- 

**1: Web/Application Developer goals:** 

- Anything critical of notice from developer's  perspective.
- Application associated CI/CD pipelines
- Application health  -- 
     -- as mapped with the environments (run, stage, prod etc. ) 
     -- mapping of each environment and associated containers
- Application and associated services / Storage/ DB mapping & basic info --  
    -- type (storage types like gluster, rds etc. ), 
    -- ports & ips  they are associated with. 
- other…
- Intra Application Messaging Queue – 
    -- JMS Queue etc.
    -- JMS topic etc.


**2: Ops  goals:** 
 
- Anything critical of notice from Ops perspective of Deployment.
- How many replicas are running & how their health. 
- The health and status of the associated containers. 
- What are the services / Storage/DB are connected & basic info --  
     -- type (storage types like gluster, rds etc. ), 
    -- ports & ips  they are associated with. 
    -- other…
- Ingress/load balancer related info. 
- From cluster angle some info like deployment running in which nodes(?) & any other related info…
- I can take some action to change the deployment parameters 
 

So there can be application page that focuses from the first goals set where as the deployment page can address the goals set in the 2nd persona (i.e. the Ops perspective)

Based on this approach we can explore the data points.

@aslakknutsen @joshuawilson @bartoszmajsak  @serenamarie125 @catrobson @muruGanesan @parvathyvr

**Comment by sdash-redhat** [comment]
![image](https://user-images.githubusercontent.com/27761023/43678020-9fb9cd6e-9829-11e8-9989-0608fec121a4.png)

**Comment by sdash-redhat** [comment]
Updated the Google slides https://docs.google.com/presentation/d/1bRn63ZVxb24unGGOTscs72UGtUQocgb3Hxhx9w7XCNQ/edit?usp=sharing 
... Especially in slide 5 and 6, I have listed down a sample set of data-points that might reflect 

Please have a look and share your thoughts.

@aslakknutsen @joshuawilson @bartoszmajsak @serenamarie125 @catrobson @muruGanesan @parvathyvr

**Comment by sdash-redhat** [comment]
Applications View entities ...
![image](https://user-images.githubusercontent.com/27761023/43681612-2e062a4e-9876-11e8-9294-226f33607efe.png)

**Comment by sdash-redhat** [comment]
Deployments View entites ...
![image](https://user-images.githubusercontent.com/27761023/43681617-661788ec-9876-11e8-89e8-01671a71cef4.png)

**Comment by sdash-redhat** [comment]
Based on the last discussion, these explorations we will use for a long-term solution. Looking at the current scope of 'J' train I will provide designs for the existing implementation that will address the requirements of J train. 

@serenamarie125 @catrobson @muruGanesan @joshuawilson @aslakknutsen

**Comment by sdash-redhat** [comment]
Here is a first draft of explorations with 4  concepts/approaches:
**https://redhat.invisionapp.com/share/2YNHLNXMKR8**
Please feel free to review and share your thoughts. 
@serenamarie125 @catrobson @joshuawilson @aslakknutsen @bartoszmajsak

**Comment by serenamarie125** [comment]
@aslakknutsen @joshuawilson a few questions to help provide clarity:
1. is it possible for you to share what the Deployments view of one of your spaces would look like (add an image here) 
2. currently when you "expand" an application, the card expands.  If there are a number of cards (db, message queue, etc) associated with a single application, would you assume that they would want all expanded at the same time OR is it ok to view details of one card at a time?  This will answer the question if a sidebar panel to view details is a viable option

Currently i feel like option #1 is the most viable, but still needs more work.  Could others weigh in with their thoughts?

**Comment by sdash-redhat** [comment]
@joshuawilson 
Thanks or sharing useful feedback!
Looks like the first options is getting more votes and seems more practical to go after as it also aligns with the existing implementation (for sure with some tweaks based on the feedback received) 
Can you help to identify the data points we are showing on the preview panel or cards? 
Can we list what attributes and parameters/data points we want to show during J train implementation...? This would help to refine the design...
Also is it ok to have all these 4 types of cards to use ? or will there be a limited scope for J train?
@aslakknutsen @serenamarie125 @muruGanesan @sunilmalagi @catrobson

**Comment by sdash-redhat** [comment]
A quick option based PF expanded (similar usage can be seen in Satelite project) preview as a 5th option with of @sunilmalagi I have added   https://redhat.invisionapp.com/share/2YNHLNXMKR8#/316534512_-4065_-_Exploration_3_4_-_3_Copy

**Comment by sdash-redhat** [comment]
Based on the last whiteboarding session, here is the link to the 2 high-level concepts work in progress   **https://redhat.invisionapp.com/share/G6NW31BAC59#/318220539_Slide01**
 @aslakknutsen @joshuawilson @alexeykazakov  @serenamarie125 @catrobson @muruGanesan @parvathyvr  @sunilmalagi

**Comment by sdash-redhat** [comment]
Link to updated WF (0.3) :
**https://redhat.invisionapp.com/share/Y5O30X9AKWV**
@serenamarie125 @aslakknutsen @joshuawilson @muruGanesan @catrobson

**Comment by sdash-redhat** [comment]
There is a question as to if showing deployments should be available in OSIO, and if so couldn't we just link out to OpenShift.

Based on the number of discussions, we have consensus to stop the design work regarding the deployments page. 

Closing this issue. 
@serenamarie125 @muruGanesan @joshuawilson @aslakknutsen @sunilmalagi
