### ISSUE TITLE
For user provisioned on starter-us-east-2, stage and run pods are not starting

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#4067]
Steps to recreate:
* Login to https://openshift.io with user account provisioned on starter-us-east-2
* Reset user env, verify that Jenkins and Content Repo pods start
* Create new space
* Create new app in Launcher
* Observe successful deployment to stage and promotion to run in OpenShift.io UI
* Observe stage and run endpoints are not accessible:

![screenshot from 2018-07-24 10-36-03](https://user-images.githubusercontent.com/642621/43145445-6297dca0-8f2d-11e8-9016-e5f020794472.png)

Observe stage and run pods fail to start - from the stage pod log (token text removed for logging this issue):

```
10:28:53 AM	july23test2-1-fpk4k	Pod	Normal	Back-off 	Back-off pulling image "172.30.98.11:5000/ldimaggi-jenkins/july23test2@sha256:"
6 times in the last 2 minutes
10:28:53 AM	july23test2-1-fpk4k	Pod	Warning	Failed 	Error: ImagePullBackOff
6 times in the last 2 minutes
10:28:51 AM	july23test2-1-fpk4k	Pod	Normal	Sandbox Changed 	Pod sandbox changed, it will be killed and re-created.
7 times in the last 2 minutes
10:28:45 AM	july23test2-1-fpk4k	Pod	Warning	Failed 	Failed to pull image "172.30.98.11:5000/ldimaggi-jenkins/july23test2@sha256:": rpc error: code = Unknown desc = unauthorized: authentication required
2 times in the last 2 minutes
10:28:45 AM	july23test2-1-fpk4k	Pod	Warning	Failed 	Error: ErrImagePull
2 times in the last 2 minutes
10:28:45 AM	july23test2-1-fpk4k	Pod	Normal	Pulling 	pulling image "172.30.98.11:5000/ldimaggi-jenkins/july23test2@sha256:"
2 times in the last 2 minutes
10:28:32 AM	july23test2-1-fpk4k	Pod	Normal	Scheduled 	Successfully assigned july23test2-1-fpk4k to ip-172-31-67-200.us-east-2.compute.internal

```

**Comment by ldimaggi** [comment]
Still happening:

```
Error: ImagePullBackOff
113 times in the last 

```

**Comment by ldimaggi** [comment]
This looks like it was fixed in the last 30 min - no longer seeing this issue.

**Comment by ppitonak** [comment]
Missing env variable after cluster was upgraded to OpenShift 3.10
