### ISSUE TITLE
Improve the launcher experience to enable the user to get full feedback of the setup

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4070]
Currently when the launcher flow completes, you are shown a page in the wizard which shows a number of steps, but then you are brought back to OSIO dashboard with no indication of what's going on.

Design a solution which improves this experience, allowing the user to view what was done in the launcher, get feedback at any time, and understand next steps.

Investigate the following as design alternatives:
- move the last 'setup' page from the launcher and moving it into OSIO navigation, and adding OSIO actions (not just launcher actions) to it so that the user has a better idea of progress of their app being set up.  Right now the launcher actions are nearly instantaneous, but then you go back to the OSIO space dashboard and OSIO still has a lot of work to do so it seems like something went wrong/your app isn't getting set up.  Next steps aren't clear due to this.
- currently, there is an empty state - maybe this empty state should include a link to what was the last 'setup' page.  If we did this, it would allow links to multiple pages which were "in progress", and give the user the ability to view progress of them individually
- possibly show "hints" or "guided tour" like bubble hints as things are continuing to be set up.  For example "We’re setting up your app - Here’s your code in git - you can edit it here … "
- Should provide quick actions from the setup to easily jump into common actions (edit code, view pipeline, view logs were the ones identified so far)

**Comment by serenamarie125** [comment]
@catrobson please take a look

**Comment by catrobson** [comment]
@serenamarie125 added one final bullet point.  Otherwise looks good!

**Comment by GeorgeActon** [comment]
@serenamarie125 please label with team and story or task etc.

**Comment by muruGanesan** [comment]
linking the relevant GH issue #3366 [https://github.com/openshiftio/openshift.io/issues/3366](url)

**Comment by muruGanesan** [comment]
UXD team with PM and Eng will be doing a design thinking workshop (30 Jul - 2 Aug 18) to find the specific UX improvement area of 'OSIO Launcher'. This story will be updated after the workshop.

**Comment by muruGanesan** [comment]
First-cut concept: (but will undergo change)
https://redhat.invisionapp.com/d/main#/projects/prototypes/15079718

**Comment by bartoszmajsak** [comment]
@muruGanesan I can't access the link - can you make it public?

**Comment by muruGanesan** [comment]
Please try this link:
https://redhat.invisionapp.com/share/WXNFWU4M7UV#/313564466_Launcher-2

**Comment by bartoszmajsak** [comment]
Thanks @muruGanesan I can view this one, but can't really comment as it asks me for login, so I will share my feedback here.

One thing I would like to bring up is "go to codebases" part. As a user this gives a view on something I might not be familiar with yet (I don't know what is a workspace when I come to OSIO as the first timer). How about we jump directly to Che instead?

**Comment by muruGanesan** [comment]
@bartoszmajsak, Thanks for your feedback. I will consider this point in the next design iteration.

**Comment by muruGanesan** [comment]
@serenamarie125 @catrobson @joshuawilson @bartoszmajsak 

Please see the updated link:

https://redhat.invisionapp.com/share/WXNFWU4M7UV#/screens/313564466_Launcher-2

**Comment by serenamarie125** [comment]
Please find my feedback in this GDoc : https://docs.google.com/document/d/199NSMJUOCyjbO-BBtW0rIomO33ITn43O3VRiYJ8KobU/

**Comment by muruGanesan** [comment]
I am closing the issue since it is tracked under #4197
