### ISSUE TITLE
license-recommender API endpoint returns HTTP code 500 for wrong input

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#4071]
## Actual behaviour:

For the wrong input, ie. missing attributes in JSON payload, the `license-recommender` API endpoint returns HTTP code 500 with the message written in HTML:

```
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>

  </body>
</html>
```

## Reproducer:

Reproducer: https://github.com/fabric8-analytics/fabric8-analytics-common/pull/581

## Expected behaviour:

Any meaningful 4xxx code with JSON containing status + error message:
https://blog.restcase.com/rest-api-error-codes-101/

**Comment by GeorgeActon** [comment]
@tisnik please assign a severity to this bug

**Comment by sunilk747** [comment]
This PR - https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/pull/118 fixes this issue.
