### ISSUE TITLE
User Avatar shows clickable pointer

### ISSUE THREAD

**Issue by DhritiShikhar** [openshiftio/openshift.io#4073]
The user avatar shows a "hand pointer" which means that it should either be clickable component or show a infotip neither of which happens as of now.

![screenshot_2018-07-11_13-31-33](https://user-images.githubusercontent.com/6303309/42558640-80f06f3c-850f-11e8-808e-a4b1fd2afbc2.png)

![screenshot_2018-07-11_13-31-46](https://user-images.githubusercontent.com/6303309/42558641-8126a3e0-850f-11e8-9f10-5ce364d84a4e.png)

**Comment by SMahil** [comment]
Closing this issue as User Avatars have info-tip now
