### ISSUE TITLE
Long title is not rendered properly in the Timeline

### ISSUE THREAD

**Issue by DhritiShikhar** [openshiftio/openshift.io#4074]
![screenshot_2018-07-11_15-13-41](https://user-images.githubusercontent.com/6303309/42564091-75ba8766-851d-11e8-86f3-7d516fdbeafd.png)

**Comment by sunilmalagi** [comment]
@SMahil @nimishamukherjee Truncate the title to two lines.

**Comment by joshuawilson** [comment]
I think it would be nicer to have a fixed length so the user doesn't think their very long title will work. 

I would rather have the field stop at 56 char or 200 char and I know I need to change my text to fit.

**Comment by nimishamukherjee** [comment]
@openshiftio/uxd-team @Veethika need your input here.
Do we fix the length at, say 200 characters? Or do we try something like GitHub where they truncate the title and add the rest of the title text to the description?

**Comment by christianvogt** [comment]
Closing because the text is no longer cut off. Truncation can occur as a broader feature request overall in the UI.
