### ISSUE TITLE
Problems with Iteration Hierarchy

### ISSUE THREAD

**Issue by DhritiShikhar** [openshiftio/openshift.io#4076]
Iteration Hierarchy more than level 4 is not supported.

Iteration at 5th level appears at the 2nd level.

Refer:
https://youtu.be/lt9C3IDfc-Q

**Comment by nimishamukherjee** [comment]
@DhritiShikhar refer to https://github.com/openshiftio/openshift.io/issues/2046
This is the intended behaviour.

**Comment by joshuawilson** [comment]
closing since it works as designed
