### ISSUE TITLE
Linking of ngx-launcher with fabric8-ui is not working

### ISSUE THREAD

**Issue by vikram-raj** [openshiftio/openshift.io#4078]
For local development, we need to link ngx-launcher with fabric8-ui to see the changes that we made in ngx-launcher and it is broken now. There is one workaround

Steps:
After making any change I have to do
1. npm run build
2. In dist folder run npm pack. After npm pack .tgz file will be created
3. In fabric8-ui run npm install <path of .tgz file>
4. npm start

And it takes 4 to 5 mins.

**Comment by joshuawilson** [comment]
Were you able to get past this?

**Comment by vikram-raj** [comment]
After upgrade to angular 6 there is no link command is define in ```ngx-launcher```. So, this issue is not valid anymore.
