### ISSUE TITLE
Notification service fails to equate the SSH and HTTPS url for the same git repo

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#4080]
## Steps to recreate
1. Create a fork of the repo - 'https://github.com/spicemit/maven-simple-2-1.git'.
2. On prod-preview.openshift.io, create a space and import the newly forked repo during the set up.
3. Opt in for 'Internal Experimental Features' if not done already.
4. Go to the codebases link in the new space and switch on the 'SECURITY ALERT'.
5. You will receive the scan report for the repository in a mail.
6. Go to pipelines page and wait until the build completes.
7. Start the pipeline all over again and wait for its completion.
8. You are not going to get a scan report email.

## Analysis
We figured out that the reason for not receiving emails lies in the fact that the notification service failed to recognize the SSH and the HTTPS URL for the test GitHub repo as the same one. We get a mail when the ID in the payload is set as the GitHub HTTPS URL but not when that's set as the SSH URL.

**Comment by nurali-techie** [comment]
While analyzing the issue, I have observed that there is an attempt made to send_email even there are zero_receiver.  Please add check in f8-notification not to call send_email in case of zero_receiver. [code_link](https://github.com/fabric8-services/fabric8-notification/blob/master/email/notifier.go#L74)

**Comment by GeorgeActon** [comment]
@samuzzal-choudhury please assign a severity to this issue

**Comment by mvulavak** [comment]
@samuzzal-choudhury  Could you please assign the team to which this belongs to?
