### ISSUE TITLE
Cannot access documentation of Eclipse Che from links inside it

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#4084]
if i click on a link "learn more", I have this kind of message:

![image](https://user-images.githubusercontent.com/1105127/43313835-7d6b8d40-9191-11e8-9f69-bf84120396b1.png)

I tried from
![image](https://user-images.githubusercontent.com/1105127/43313849-87b14bdc-9191-11e8-9849-5d2eef410f92.png)
and
![image](https://user-images.githubusercontent.com/1105127/43313858-8e8147b4-9191-11e8-9e50-9bdaf77d60ed.png)

**Comment by rhopp** [comment]
Already reported in rh-che repository: https://github.com/redhat-developer/rh-che/issues/747

**Comment by ibuziuk** [comment]
PR https://github.com/redhat-developer/rh-che/pull/830 is merged to master and soon will be available on prod

**Comment by ibuziuk** [comment]
Fix is available on prod. Closing
