### ISSUE TITLE
Spring Boot quickstarts fail, "Non-resolvable import POM: Could not find artifact me.snowdrop:spring-boot-bom:pom"

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#4086]
Attempting a vanilla Spring Boot application (Health Check) gets this:

[rickjwagner_july27_master-NMD3WWQMIQSUK63AP7NZGLDTGROS56JMNKFRHDWGWSIBNORAECMQ] Running shell script
+ mvn org.codehaus.mojo:versions-maven-plugin:2.5:set -U -DnewVersion=1.0.1
Picked up _JAVA_OPTIONS: -Duser.home=/root/ -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
[INFO] Scanning for projects...
EXITCODE   0[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact me.snowdrop:spring-boot-bom:pom:${spring-boot-bom.version} in central (https://repo1.maven.org/maven2) @ line 46, column 19
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-web:jar is missing. @ line 73, column 17
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-actuator:jar is missing. @ line 77, column 17
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-devtools:jar is missing. @ line 81, column 17
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ line 102, column 17
[ERROR] 'dependencies.dependency.version' for org.assertj:assertj-core:jar is missing. @ line 117, column 17
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.openshift.booster:july27:1.0.0 (/home/jenkins/workspace/rickjwagner_july27_master-NMD3WWQMIQSUK63AP7NZGLDTGROS56JMNKFRHDWGWSIBNORAECMQ/pom.xml) has 6 errors
[ERROR]     Non-resolvable import POM: Could not find artifact me.snowdrop:spring-boot-bom:pom:${spring-boot-bom.version} in central (https://repo1.maven.org/maven2) @ line 46, column 19 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-web:jar is missing. @ line 73, column 17
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-actuator:jar is missing. @ line 77, column 17
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-devtools:jar is missing. @ line 81, column 17
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ line 102, column 17
[ERROR]     'dependencies.dependency.version' for org.assertj:assertj-core:jar is missing. @ line 117, column 17
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
[Pipeline] }

**Comment by ibuziuk** [comment]
@RickJWagner does it happen only when building project in Che or it is in general the quickstart issue and it is not possible to build it locally ?

**Comment by piyush1594** [comment]
@ibuziuk AFAIK, this is a booster issue which happens in Jenkins build or locally also. Have seen this in past.

**Comment by ibuziuk** [comment]
@cmoulliard could you please take a look ? This problem is also results in redhat  che-dockerfiles build failures where up-to-date versions of the quickstarts are pre-build - https://github.com/redhat-developer/rh-che/issues/780

**Comment by ldimaggi** [comment]
I'm seeing this problem too.

**Comment by ldimaggi** [comment]
Seeing the same issue for the SpringBoot/REST quickstart.

**Comment by ibuziuk** [comment]
@ldimaggi do you happen to know who is the key contact for spring boot runtime on osio ?

**Comment by piyush1594** [comment]
@geoand can help us here.

**Comment by geoand** [comment]
@RickJWagner is this error still occurring? We fixed a similar issue this morning, but I'm not certain that it's related

**Comment by RickJWagner** [comment]
Hi @geoand 
The problem is still there, I just replicated it.
Thanks,
Rick

**Comment by bartoszmajsak** [comment]
@geoand how did you fixed that? I believe we are on older version here https://github.com/fabric8-launcher/launcher-booster-catalog/blob/master/spring-boot/current-redhat/health-check/booster.yaml#L11

**Comment by geoand** [comment]
@bartoszmajsak I fixed it by deleting the tag and recreating it with the correct release. I did that because that course of action didn't require a PR to the launcher so I thought it would be faster.

Does the launcher "cache" the repos? If so, is there any way to un-"cache" them or do I have to do a new release of the boosters?

**Comment by bartoszmajsak** [comment]
Yes, it caches it. I don't have enough karma to trigger `reindex`. Summon @gastaldi

**Comment by geoand** [comment]
@bartoszmajsak Thanks!

**Comment by gastaldi** [comment]
@geoand Yes Launcher caches the repositories (that's why it's not a good idea to force push a tag) :)

I triggered a reindex in production, let me know if that works

**Comment by geoand** [comment]
@gastaldi Understood, thanks! I did it thinking that it would speed up the resolution of the issue, obviously it had the opposite effect:(

**Comment by geoand** [comment]
@RickJWagner @ldimaggi @piyush1594 the error should be gone, can you verify please?

**Comment by ibuziuk** [comment]
FYI, redhat-che-dockerfiles build is back to normal [1] whicildableh means all quickstarts used on osio are buildable

[1] https://ci.centos.org/job/devtools-eclipse-che-build-dockerfiles/

**Comment by geoand** [comment]
Thanks for the update @ibuziuk

**Comment by ldimaggi** [comment]
Looks good to me - Rick can you verify and close?

**Comment by RickJWagner** [comment]
I've just made a new workspace, the problem is gone.  Thanks!

**Comment by geoand** [comment]
Awesome!
