### ISSUE TITLE
Too many errors and they are also not placed correctly

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#4089]
![screenshot from 2018-07-31 12-06-00](https://user-images.githubusercontent.com/10185999/43442187-e5311b3a-94ba-11e8-987b-6e6dad10a421.png)
Seems like a bug to me

**Comment by aptmac** [comment]
Neat, how'd you get that to happen?

**Comment by kishansagathiya** [comment]
I think, this is what I did

1. By default, `Create a new codebase` is selected. Typed the project name.
2. I remember that I have the project already and I want to import it. I select `Import and existing codebase` and that's when I saw it.

That's all the information I have.

**Comment by stevengutz** [comment]
Any idea what team/area this belongs to?

**Comment by kishansagathiya** [comment]
Let me know if you can't reproduce it. I see it regularly(almost all the time)

**Comment by vikram-raj** [comment]
@kishansagathiya I follow your steps but not able to reproduce this issue. and Is ```create a new codebase``` is selected by default for you when you land to ```Create an Application``` page?

**Comment by kishansagathiya** [comment]
> Is create a new codebase is selected by default for you when you land to Create an Application page?

Just tried. It's not selected by default. My bad. Let me remove that part from the description.

**Comment by nimishamukherjee** [comment]
@kishansagathiya do you still face this error?

**Comment by christianvogt** [comment]
This appears to have been fixed.
