### ISSUE TITLE
In Planner, linking of workitems is broken

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#409]
Steps to recreate:
* Attempt to link workitems
* Observe that the link types pulldown is empty

![screenshot from 2017-07-25 08-01-56](https://user-images.githubusercontent.com/642621/28571207-cd3a8694-710f-11e7-8e3d-a6d3f3f14fb9.png)

**Comment by joshuawilson** [comment]
cc @michaelkleinhenz

**Comment by michaelkleinhenz** [comment]
Can not reproduce this. Looks like outdated.
