### ISSUE TITLE
Add telemetry to the registration flow

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#4095]
Find out how the user reached the RHD login/reg page

"we are interested in all accounts created from the page here: openshiftio/openshift.io#3814 and should be using the referrer to know if the user was coming from a factory or not"

( Update this space based on discussion in https://github.com/redhat-developer/rh-che/issues/749 )

**Comment by ibuziuk** [comment]
IMO the woopra registration event should not be limited to Che factory usecase but rather track in general, from which page the user was redirected to the registration page (I believe it would be quite easy to do via `document.referrer`[1] on the registration side and super useful from the marketing perspective) 

[1] https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer

**Comment by sbose78** [comment]
@slemeur As far as I see, this information is already available in woopra. Closing.
