### ISSUE TITLE
User account is unable to create a new project - build is not started

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#410]
Steps to recreate:
* Login to OSIO
* Create new space
* Create new project
* Apply workaround defined in https://github.com/openshiftio/openshift.io/issues/383 to label buildconfig
* Pipeline is not started automatically - after starting manually in OpenShist, results are:

Githuib repo and webhook are created: 

![screenshot from 2017-07-25 09-39-25](https://user-images.githubusercontent.com/642621/28575342-a6ecb494-711e-11e7-8957-d2246d62b10d.png)
![screenshot from 2017-07-25 09-40-00](https://user-images.githubusercontent.com/642621/28575343-a6f5c05c-711e-11e7-8659-f8e563ef3dc0.png)

Build never starts - no logging written:

![screenshot from 2017-07-25 09-39-07](https://user-images.githubusercontent.com/642621/28575423-df5ecd3a-711e-11e7-9f99-4b2849a810fc.png)

Jenkins job for build not created:

![screenshot from 2017-07-25 09-39-41](https://user-images.githubusercontent.com/642621/28575437-e96df15c-711e-11e7-97b6-b19ebc00c9f8.png)

**Comment by jstrachan** [comment]
could you attach the log of your jenkins pod (via the openshift console)? I can't use your account so am flying blind

**Comment by ldimaggi** [comment]
[jenkins_pod_log.txt](https://github.com/openshiftio/openshift.io/files/1173451/jenkins_pod_log.txt)

**Comment by ldimaggi** [comment]
[jenkins_pod_log.txt](https://github.com/openshiftio/openshift.io/files/1173780/jenkins_pod_log.txt)

**Comment by aslakknutsen** [comment]
There are no BC's in the ldimaggi namespace

**Comment by ldimaggi** [comment]
The problem was caused by out of date tenant service. Closing.

See:  https://github.com/openshiftio/openshift.io/issues/411
