### ISSUE TITLE
Shouldn't the placeholder be light?

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#4101]
Looking into this page, I don't see any difference between a real value and placeholder value.
I get the part where first is not italicized and second is, but then why is `scenario driven development` in italicized.
I think to make placeholders look like placeholders they should be light and not italicized
![screenshot from 2018-07-31 19-58-05](https://user-images.githubusercontent.com/10185999/43465971-2793fd80-94fc-11e8-9f2c-9960cb56f295.png)

But of course, this is just a suggestion

**Comment by aptmac** [comment]
@openshiftio/uxd-team

**Comment by kishansagathiya** [comment]
May be @catrobson @muruGanesan can help here

**Comment by muruGanesan** [comment]
@kishansagathiya, thanks for your inputs. 
We are working on UX enhancement (esp. launcher experience), this issue will also be addressed in any one of the UX GitHub tasks. 
ref: #4191 
https://github.com/openshiftio/openshift.io/issues/4191
#4192

**Comment by christianvogt** [comment]
Latest impl has a lighter font color and uses patternfly styling which applies an italic.
