### ISSUE TITLE
Refactor email-verification page into a generic landing page for various other redirects

### ISSUE THREAD

**Issue by rohitkrai03** [openshiftio/openshift.io#4102]
Related UX issue - https://github.com/openshiftio/openshift.io/issues/3929

Currently we have status pages for redirects coming from verification of emails.
- Success - https://prod-preview.openshift.io/_verifyEmail?verified=true
- Error - https://prod-preview.openshift.io/_verifyEmail?verified=false&error=some_error

Now we need a similar landing page for invitations API. Based on the comments by @catrobson  https://github.com/openshiftio/openshift.io/issues/3929#issuecomment-405682187 we can reuse the current email verification landing pages. But that is very specific to verify email scenario, so we need to refactor the current component to cater to various redirect status scenarios.

One of the task is deciding the new URL pattern for a landing page which is generic enough for different redirect scenarios. Something like - 
- `https://openshift.io/_redirects/_verifyEmail?success=true`
- `https://openshift.io/_redirects/_verifyEmail?success=false&error=some_error_msg`
- `https://openshift.io/_redirects/_acceptInvitation?success=false&error=some_error_msg`

@joshuawilson @catrobson  We would need your inputs here. What do you think would be a suitable URL pattern here.

cc: @sbose78 @sbryzak @xcoulon 

Note: Tracking it here so that UX team can give inputs.

**Comment by catrobson** [comment]
@rohitkrai03 proposal looks good to me!

**Comment by joshuawilson** [comment]
that looks like it should work
