### ISSUE TITLE
[RFE] Difficult to debug specific users issues - need a tool to capture user environment

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#411]
As components are updated frequently, it is possible for arbitrary users to have different sets of components installed.

What we need is an issue reporting UI that automatically captures the users tenant versions, jenkins pod log, quota reports, and running pods in namespaces, etc. and makes it easy for users to report this information into an issue/workitem.

**Comment by joshuawilson** [comment]
@pbergene more content for your idea.

**Comment by qodfathr** [comment]
This is a fairly open-ended RFE, so it's going to be very hard to close. I propose that we author a new top-level Fundamental with some specific Experiences, and then close this Issue referencing that new Scenario.

**Comment by ldimaggi** [comment]
Closed in favor of:  https://openshift.io/openshiftio/openshiftio/plan/detail/2587
