### ISSUE TITLE
Platform support for new template for newer version

### ISSUE THREAD

**Issue by yzainee** [openshiftio/openshift.io#4112]
**Planner Link:**  https://openshift.io/openshiftio/Openshift_io/plan/detail/325

- [x] Add the logic to supprt a new template "analytics.notify.version"

- [x] Add logic to populate the html template with the json information for the email

- [x] Test cases

**Comment by GeetikaBatra** [comment]
This [PR](https://github.com/fabric8-services/fabric8-notification/pull/84) covers this task.
