### ISSUE TITLE
New intermittent issue seen - promote to run dialog not displayed for user - no other error apparent

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#4115]
Steps to recreate:
* Login to https://openshift.io (production)
* Reset user env, verify that Jenkins and Content Repo start successfully
* Create new OSIO space
* Create new OSIO quickstart (REST/Vert.X), select run/promote release strategy
* Observe build pipeline starts ans deploys successfully to stage
* Observe in Jenkins build log that promote to run is prompted:
![screenshot from 2018-08-01 11-28-39](https://user-images.githubusercontent.com/642621/43532340-d43b023a-957f-11e8-8816-618cfd3ddc67.png)

* Observe that promote dialog is not displayed for user:
![screenshot from 2018-08-01 11-28-17](https://user-images.githubusercontent.com/642621/43532368-e60a8602-957f-11e8-9783-5d37f20e3092.png)

**Comment by ldimaggi** [comment]
The E2E tests are also starting to see this error:

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/426/05-01-pipeline-failed.png

**Comment by ljelinkova** [comment]
It just happened to me too.

**Comment by piyush1594** [comment]
@ljelinkova @ldimaggi This seems like the same as #3935

**Comment by ldimaggi** [comment]
Yes - I think that this is the same bug. 

Closing as a duplicate of #3935 

Thanks!
