### ISSUE TITLE
Move FeatureFlagResolver from fabric8-ui to ngx-feature-flag library

### ISSUE THREAD

**Issue by rohitkrai03** [openshiftio/openshift.io#4116]
- `ngx-feature-flag` library was extracted out of `fabric8-ui` so that external libraries such as `fabric8-planner` would be able to use feature flags.
- But there is still one piece of code `FeatureFlagResolver` inside `fabric8-ui` which needs to move to `ngx-feature-flag` so that the other libraries do not need to write it all over again.

**Comment by stevengutz** [comment]
Is this a bug? The work item needs a type

**Comment by rohitkrai03** [comment]
@stevengutz I was not sure about the type here. I guess this will be a task. This one is needed to enable other external libraries like planner to use feature flags.
