### ISSUE TITLE
Intermediate pages on any task

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#4117]
In general, there are several use cases where you try to open a page(or do something which is supposed to get you to some page), instead of directly taking you to that page, it will take you to some other page(mostly dashboard). 
For example

- I just created a new space and added name for the application, selected `import codebase`. Ideally it is supposed to take me to a page where I select a repo from GitHub, but it wouldn't directly do that. It would load the dashboard and go to that page. In some cases, it gets stuck at intermediate page. I am right now stuck at dashboard in this flow.

- You are logged in to OSIO already. Open openshift.io. It will not load the dashboard directly. It will go to the intro page(one which we see when we are not logged in, one which has a intro video about OSIO). It will show me `log in` and `log out` next to each other. And then it will go to dashboard.

- There could be several other situations like this.

- One other weird thing that I see is that, when I open any page, I don't see things instantly. For example open codebase page or spaces page. Initially the page shows no codebases and spaces, after sometime code bases and spaces will show up.

**Comment by christianvogt** [comment]
Cannot reproduce the import flow issue.

Login issue covered by: https://github.com/openshiftio/openshift.io/issues/4030

async loading state is a general issue we have and is being addressed through various architectural changes.
