### ISSUE TITLE
[RFE] Difficult to debug specific users issues - need a tool to review user account and diagnose potential issues

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#412]
We are seeing user accounts get put into states where the user is not able to create/manage projects. 

To date, we have manually "cleaned" these accounts through the OpenShift console to re-enable the users, but this is an error prone, manual process. In some cases, we have removed resources that have resulted in additional problems for the users.

What we need is a tool that can examine a user account, diagnose problems, and either repair the account - or make recommendations to the user to enable him/her to repair the user account.

**Comment by joshuawilson** [comment]
@pbergene looks like there is already an issue for your idea. :-)
cc: @maxandersen @kbsingh @aslakknutsen

**Comment by alexeykazakov** [comment]
This issue is too broad. I'm going to close it. We need to discuss some concrete features/tools instead.
