### ISSUE TITLE
[RFE] Provide users with notifications when software updates are available

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#413]
It would be very useful/helpful to users if we could provide them with a notification as to when they should perform an "update tenant" operation - in order for users to avoid situations caused by running out of date software.

Related to: https://github.com/openshiftio/openshift.io/issues/412

**Comment by qodfathr** [comment]
The preferred solution is to not have users manage their tenants; tenant updating should be automatic and we want to remove the update tenant button.
