### ISSUE TITLE
Move kubernetes-model CD job to CICO

### ISSUE THREAD

**Issue by rupalibehera** [openshiftio/openshift.io#4136]
Planner: : https://openshift.io/openshiftio/Openshift_io/plan/detail/295

**Comment by sthaha** [comment]
@rupalibehera the story related to this is https://openshift.io/openshiftio/Openshift_io/plan/detail/295 

I have updated the description

**Comment by rupalibehera** [comment]
@rohanKanojia , should I close this one as we are going to merge model and client ?

**Comment by rohanKanojia** [comment]
@rupalibehera : ah, yeah. makes sense. Sorry for wasting your time

**Comment by rupalibehera** [comment]
closing this issue as kubernetes-model is merged with kubernetes-client details - https://github.com/fabric8io/kubernetes-client/issues/1216
