### ISSUE TITLE
Should we change the way we handle long work item descriptions ? 

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#4138]
I've looked at a few work items now with lengthy descriptions and I've been confused each time. ATM, if a work item description is too long, then a button bearing the words "show more" is displayed below it, to the right. Clicking this will show the rest of the text. 

As it stands there is no functional issue here, but I do wonder a bit about the design. Normally, as a dev, I will read the item description and then go on to read the comments. Each time I've been in this scenario, I haven't noticed the little "show more button". In my mind, it would have been nice if there was some kind of indicator in the text itself (i.e. three dots, or a written description in a different font and colour) indicating that there was more to read. The way things are currently formatted, the text preview fits the text box perfectly, which could be misinterpreted as the entirety of the content. 

Here's a photo showing what I'm describing : 

![2018-08-07-110859_1120x779_scrot](https://user-images.githubusercontent.com/17230733/43784826-04bd2930-9a33-11e8-91b7-1c093ec2ea26.png)

What do you think ?

**Comment by joshuawilson** [comment]
Closing as this is being tracked at https://openshift.io/openshiftio/Openshift_io/plan/detail/399
