### ISSUE TITLE
Pipeline selection not updated after changing the runtime

### ISSUE THREAD

**Issue by bartoszmajsak** [openshiftio/openshift.io#4140]
When enabling new runtimes, such as NodeJS, pipeline selection is not updated and always point to Maven. This results in wrong `Jenkinsfile` being seeded in the generated repository.

Related to https://github.com/openshiftio/openshift.io/issues/3282

**Comment by bartoszmajsak** [comment]
PR fabric8-ui/fabric8-ui#3242 fixes only "Create App" part of the flow exposing all the pipelines available in https://github.com/fabric8io/fabric8-jenkinsfile-library for the user to select.  

![image](https://user-images.githubusercontent.com/719616/43916520-07d1f984-9c0e-11e8-811f-7e7a8c0be2d1.png)

Import flow improvements reported in https://github.com/openshiftio/openshift.io/issues/4154

**Comment by sbose78** [comment]
Works now.
