### ISSUE TITLE
No feedback to user if Repository name is not available

### ISSUE THREAD

**Issue by piyush-garg** [openshiftio/openshift.io#4142]
Steps to recreate 

1. Click `Create Application`
2. Choose `Application Name` same as one of your already existing repositories
3. Choose `Create Codebase`
4. Proceed further, choose mission and runtime, pipelines etc.
5. When you reach the repository name page, you will get no feedback and not be able to proceed further.

![github-repo-name](https://user-images.githubusercontent.com/19270240/43825019-352e9822-9b11-11e8-8387-8c376e9accb9.png)

It's not a nice user experience. Here you should throw some inputs to the user about the mistake or not autofill by the application name in case the repo already exists.

**Comment by bartoszmajsak** [comment]
It seems that validation is triggered at the wrong time - after you try to click on grey-outed `>>` icon. See screencast (somewhat oddly "optimized" though):

![existing_repo-opt](https://user-images.githubusercontent.com/719616/44024482-aefbafc0-9eed-11e8-8002-047a869ace0c.gif)

**Comment by piyush1594** [comment]
Yes, @bartoszmajsak its shows validation after clicking on the box or if you type something in that box. Otherwise, the user keeps waiting for that to allow to proceed further. That not a nice user experience for me at least. If it does not look relevant to you, feel free to close this. Thanks

**Comment by bartoszmajsak** [comment]
I just wanted to clarify the current behavior - it's not that you don't get any feedback, you have to click hard around to get one ;) 

I agree with you that it's a bad experience. We will improve that. Again - thanks for reporting it.

**Comment by muruGanesan** [comment]
@vikram-raj, @bartoszmajsak, @piyush-garg, anyone addressed this issue? 
Do you need any support from the UX team?

**Comment by vikram-raj** [comment]
@muruGanesan I addressed this issue and raised the PR https://github.com/fabric8-launcher/ngx-launcher/pull/374

**Comment by muruGanesan** [comment]
@vikram-raj, thanks.

**Comment by bartoszmajsak** [comment]
@piyush-garg PR has been merged to ngx-launcher `master`. Once it lands on prod please verify.

**Comment by vikram-raj** [comment]
This issue has been fixed and on prod. Feel free to reopen if you see this issue again.
