### ISSUE TITLE
Filters should not show "filter by ___" in dropdown

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#4144]
In any planner filters, the "filter by _<attribute>__" item should not be shown in the dropdown as a selectable item.

![image](https://user-images.githubusercontent.com/3739227/43837662-376f1de8-9ae7-11e8-91f5-b2cba10624a2.png)

@Veethika FYI

**Comment by Veethika** [comment]
@catrobson - @sunilmalagi has redesigned the drop-down and taken care of the mentioned problem. Here's the InVision link: https://redhat.invisionapp.com/share/E6MUSNDBAQT

Here's the linked GitHub issue: https://github.com/openshiftio/openshift.io/issues/3772
@SMahil shall be able to tell the status.

**Comment by nimishamukherjee** [comment]
@sunilmalagi how should the selected filters be displayed?
![filters](https://user-images.githubusercontent.com/1892722/44310893-7cc1e200-a3fb-11e8-8e91-95f90527f661.png)

**Comment by nimishamukherjee** [comment]
@Veethika note the original issue reported by @catrobson is in Patternfly-ng (https://www.patternfly.org/patternfly-ng/#/filters)
The same text is displayed as a placeholder text as well as the first element for the selected drop down.

**Comment by Veethika** [comment]
@nimishamukherjee noted.
@catrobson this makes it an issue that the PF-NG should take care of. Which should be the right team to be assigned this task?

**Comment by catrobson** [comment]
Closing this issue as we will need to resolve through PatternFly.
