### ISSUE TITLE
Implement shared PVC for build artifacts 

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#4145]
in order to get ride of the content-repository we nee dto be able to share artifacts created in previous build and the best way seems to use a PVC between the build system : 

- [ ] Create a PVC with ReadWriteMany for jenkins-openshift
- [ ] Have jenkins-pipeline mounting this pvc on every build when starting a new pod
- [ ] Make f-m-p write to a local file instead of a remote http for content-repo
- [ ] Make sure tenant cleanup cleans it

**Comment by msrb** [comment]
Please note that local Maven repo is not concurrent-safe: https://issues.apache.org/jira/browse/MNG-2802.

**Comment by rhopp** [comment]
Wouldn't this approach have the same troubles with mounting PVC in che workspaces? I guess at least maven repo will probably bloat to few thousands of files quite easily.

**Comment by chmouel** [comment]
that's something we have to consider!

**Comment by GeorgeActon** [comment]
@chmouel please label this correctly

**Comment by sthaha** [comment]
Closing this since openshift build doesn't support it
