### ISSUE TITLE
Wildfly Red Hat Boosters Fail on Jenkins PR Build

### ISSUE THREAD

**Issue by tinakurian** [openshiftio/openshift.io#4146]
When enabling Red Hat Wildfly boosters Jenkins builds fail for pull requests.

See attached logs.

[wildflyredhat-http.txt](https://github.com/openshiftio/openshift.io/files/2270700/wildflyredhat-http.txt)
[wildflyredhat-config.txt](https://github.com/openshiftio/openshift.io/files/2270698/wildflyredhat-config.txt)
[wildflyredhat-health.txt](https://github.com/openshiftio/openshift.io/files/2270699/wildflyredhat-health.txt)

**Comment by tinakurian** [comment]
@ldimaggi  Hey Len, this is for boosters with Red Hat Wildfly enabled, not for REST/Thorntail.

**Comment by bartoszmajsak** [comment]
@ldimaggi PR builds will fail regardless, because they are executed in the wrong namespace https://github.com/fabric8io/fabric8-pipeline-library/pull/412

Tina's work is based on the patched pipeline running tests in user namespace instead and usng Red Hat boosters, not community ones we expose on OSIO right now.

**Comment by stevengutz** [comment]
@sthaha @pradeepto This is blocking Tina's progress on booster so I'm bumping the priority to P2.  This needs to get fixed ASAP (next sprint or sooner)

**Comment by bartoszmajsak** [comment]
@stevengutz It is not a problem of build team per se. This is a particular version of a runtime which is having a problem with our limited infra. I think it's not worth an effort looking at those as we can live with Thorntail (community version of WF Swarm) which have those issues fixed. 

@slemeur can correct me if I'm wrong here.

**Comment by bartoszmajsak** [comment]
We are going to stick with the community versions hence closing this issue as it's related to a particular version of the runtime and OSIO infra.
