### ISSUE TITLE
TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by kwk** [openshiftio/openshift.io#4147]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-ui/issues/6717/

```
TypeError: Cannot read property 'map' of null
  at None (./node_modules/fabric8-planner/app/models/event.model.js:151:30)
  at Array.map (<anonymous>)
  at MapSubscriber.project (./node_modules/fabric8-planner/app/models/event.model.js:134:1)
  at MapSubscriber._next (./node_modules/patternfly/dist/css/patternfly.min.css:1:5147)
  at MapSubscriber.Subscriber.next (./node_modules/patternfly/dist/css/patternfly.min.css:1:5147)
...
(45 additional frame(s) were not displayed)
```

**Comment by kwk** [comment]
@sanbornsen let's talk about this tomorrow, okay? For now we should be good but in order to get the new event responses in we need to improve code like this:

**./node_modules/fabric8-planner/app/models/event.model.js at line 151:30**
```ts
                                return _this.areaQuery.getAreaObservableById(item.id);
                            }) });
                    case 'system.assignees':
                        return __assign({}, event, { modifier: _this.userQuery.getUserObservableById(event.modifierId), newValueRelationship {snip}
                                return _this.userQuery.getUserObservableById(item.id);
                            }), oldValueRelationshipsObs: event.oldValueRelationships.map(function (item) {
                                return _this.userQuery.getUserObservableById(item.id);
                            }) });
                    case 'system.labels':
                        return __assign({}, event, { modifier: _this.userQuery.getUserObservableById(event.modifierId), newValueRelationship {snip}
                    default:
```

**Comment by kwk** [comment]
see @vikram-raj's comment: https://chat.openshift.io/developers/pl/sabkhiyambrzjmipdfntd4dyce

> Yes @Konrad Kleine we should check for null value.

**Comment by GeorgeActon** [comment]
@kwk @sanbornsen please assign a severity to this defect.

**Comment by kwk** [comment]
> @kwk @sanbornsen please assign a severity to this defect.

@GeorgeActon currently the severity is low because we were able to revert the change that broke the planner ui. But before that it was a SEV1-high.

**Comment by stevengutz** [comment]
@kwk It would be preferable is a defect was owned by only one person/team at a time.  This one has three owners, which doesn't really make sense to me.  Who's actually working on it?

**Comment by stevengutz** [comment]
No doubt defects sometimes need input from more than one person, but I doubt that more than one of you is writing on at the same time.  It would be clearer if you do your part and assign it to the next person.  This way I/anyone knows who to ask about the status.

**Comment by kwk** [comment]
Closed through https://github.com/fabric8-services/fabric8-wit/pull/2239 (backend) and https://github.com/fabric8-ui/fabric8-planner/pull/2751 (frontend).
