### ISSUE TITLE
Two codebases, two workspaces

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#415]
Clicking on the Create Workspace on the 2nd Codebase results in a "toast" of "workspace created" but no change to the label on the screen.

https://screencast.com/t/ZRxIhkPY3Aue

The 2nd workspace for the 2nd codebase does seem to be running after having stopped the first one.

**Comment by aslakknutsen** [comment]
The screen is not auto updated no, but a popup taking you to the workspace you just created should happen.. Probably related to the two popup warnings firefox is showing.

**Comment by burrsutter** [comment]
Related to https://github.com/fabric8-ui/fabric8-ui/issues/1825

**Comment by bmicklea** [comment]
Closing - associated issues and PRs are closed/merged.
