### ISSUE TITLE
Planner table elements formatting is out of sync 

### ISSUE THREAD

**Issue by aptmac** [openshiftio/openshift.io#4152]
I recall seeing this issue before a while ago (I believe it was fixed), but cannot find the issue for it. The Planner table elements are out of sync with each other, and are not rendering in a proper orientation. 

Screenshot:
![2018-08-09-113652_1578x631_scrot](https://user-images.githubusercontent.com/10425301/43909583-aeb0102e-9bc8-11e8-8f40-e141b0232167.png)

**Comment by bartoszmajsak** [comment]
I confirm that it happens to me constantly.

**Comment by aptmac** [comment]
I found the issue that I made reference to in my description at the top of this issue; it is still open: https://github.com/openshiftio/openshift.io/issues/3650 [1]

At the time, this formatting behaviour was not default and could be triggered by playing with the settings [[1]](https://github.com/openshiftio/openshift.io/issues/3650). Presently, this seems to be the default when I view using both Chrome and Firefox.

[1] https://github.com/openshiftio/openshift.io/issues/3650

**Comment by GeorgeActon** [comment]
Added severity and Priority. Please evaluate and revise if you disagree

**Comment by michaelkleinhenz** [comment]
Increased the SEV. @SMahil is aware and already working on it.

**Comment by SMahil** [comment]
This issue has been fixed in https://github.com/fabric8-ui/fabric8-planner/pull/2759
