### ISSUE TITLE
Che: Error: Unable to access jarfile /projects/tatooineboot1/target/*.jar

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#416]
For Spring Boot Basic, the Che Run command is not correct and it fails.

A better option is
scl enable rh-maven33 'mvn compile spring-boot:run -f ${current.project.path}'

**Comment by l0rd** [comment]
Ok thanks @burrsutter I've created PRs https://github.com/redhat-developer/rh-che/pull/227 and https://github.com/eclipse/che/pull/5809 to fix that. Now building. Should be deployed to OSIO when you log in this morning.

**Comment by joshuawilson** [comment]
Is this fixed? Can we close it?

**Comment by l0rd** [comment]
@joshuawilson no. Run command has been partially fixed. If there was an already running spring-boot application run command will fail. To solve that we are going to use [Spring Boot Developer tools](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html):

To address that we will add the following profile to the global setting.xml in the [spring-boot docker image](https://github.com/eclipse/che-dockerfiles/blob/master/recipes/centos_spring_boot/Dockerfile)

```xml
    <profile>
        <id>devtools</id>
        <dependencies>
            <!-- Spring Boot Developers tools -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-devtools</artifactId>
                <optional>true</optional>
            </dependency>
        </dependencies>
    </profile>
```
and changing the command to 

```bash
scl enable rh-maven33 'mvn compile spring-boot:run -f ${current.project.path} -Pdevtools'
```

**Comment by burrsutter** [comment]
This is running well enough to start workshops but we also need a debug option for Spring Boot based apps in the future, not sure if there is an issue to track that progress.

**Comment by bmicklea** [comment]
This is now fixed.

**Comment by burrsutter** [comment]
I have verified we have Run support.
