### ISSUE TITLE
Redirect to the new documentation

### ISSUE THREAD

**Issue by bartoszmajsak** [openshiftio/openshift.io#4162]
Based on the conversation in #1548 URL `https://openshift.io/osiogettingstarted.pdf`, even though not exposed currently, has been heavily promoted in emails. 

We should redirect to official and live docs instead - https://docs.openshift.io/

**Comment by bartoszmajsak** [comment]
@joshuawilson is that simply a matter of nginx rewrite URL?

**Comment by jiekang** [comment]
The pdf is located at [1] and loaded via webpack at [2].

[1] 
https://github.com/openshiftio/openshift.io/blob/master/src/assets/documents/osiogettingstarted.pdf
[2]
https://github.com/openshiftio/openshift.io/blob/master/webpack.config.js#L149

**Comment by bartoszmajsak** [comment]
@jiekang thanks for all the details. Corrected the issue description too.

**Comment by GeorgeActon** [comment]
@bartoszmajsak then it should be assigned to that team. If it is not them they will replace the tag with the correct team

**Comment by bartoszmajsak** [comment]
@joshuawilson is there any progress on this?

**Comment by stevengutz** [comment]
@adisakala Is this really P1?  This means we drop what we are doing and focus on it.  Isn't it better described as a P2?  High priority rather than critical?

**Comment by corinnekrych** [comment]
@alexeykazakov I see different ways of doing it:
- either modify osio build script to fetch pdf from https://docs.openshift.io/getting-started-guide.pdf (as it seems this is the place the document is published) and make it available thro osio website via https://github.com/openshiftio/openshift.io/blob/master/webpack.config.js#L149 , we can remove deprecated pdf in https://github.com/openshiftio/openshift.io/blob/master/src/assets/documents/osiogettingstarted.pdf as suggested by @jiekang 
- or change nginx config in https://github.com/openshiftio/openshift.io/blob/master/nginx.conf#L78 with something like http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect  (I'm not familiar with those config).
- or we remove this PDF link altogether and add a text explaining how to collaborate to the doc repo, and point directly to the repository as @bartoszmajsak suggested, it's more in the "open source" contribution spirit. 

I think the last option is the best and easier to implement too. If we go for this option, we just have to agree on the wording / presentation of the link.
@bartoszmajsak @alexeykazakov @rkratky wdyt? any other options, I'd have missed?

**Comment by alexeykazakov** [comment]
I would get rid of PDF doc completely. But we promoted https://openshift.io/osiogettingstarted.pdf link in our welcome emails. So, while it's fine to kill the doc we need to keep https://openshift.io/osiogettingstarted.pdf link alive but it should redirect to https://docs.openshift.io/

@sbose78 do you know if we now use https://docs.openshift.io/ in our welcome emails?

**Comment by sbose78** [comment]
Agreed, let's get rid of that. ( Sooner the better ).
We do use https://docs.openshift.io now in our welcome emails.
