### ISSUE TITLE
Workitem component should display spaces where user is a collaborator

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#4165]
Why?
It is very difficult to find out as an end user workitem assigned to me where I am a collaborator, not a space owner.

**Comment by rohitkrai03** [comment]
@Raunak1203 Duplicate issue - https://github.com/openshiftio/openshift.io/issues/3760
Auth team is working on the API for this issue currently.

**Comment by joshuawilson** [comment]
closing as dup
