### ISSUE TITLE
Stack analytics has identified a potentially version upgrade

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#417]
On the Vert.x Basic, this is a Stack Analytics Report hits the dashboard after a pipeline run.

"a potentially version upgrade" is not proper English.

https://screencast.com/t/DoaRGsJv

And why am I getting this warning to begin with?  I just generated this project today and already getting warnings/recommendations. :-)

**Comment by arunkumars08** [comment]
Linked here: https://github.com/fabric8-ui/fabric8-recommender/issues/244

**Comment by joshuawilson** [comment]
@arunkumars08 that issue is closed. Is this fixed?

**Comment by miteshvp** [comment]
I guess not. I can still see https://github.com/fabric8-ui/fabric8-recommender/blob/226e4dfd649da6d7b4fb7f4e9f403409f6cb8fc6/src/app/stack/stack-details/stack-details.component.ts#L195

**Comment by invincibleJai** [comment]
it's fixed in this PR https://github.com/fabric8-ui/fabric8-recommender/pull/260 
cc @arunkumars08 @jyasveer

**Comment by arunkumars08** [comment]
@burrsutter When you run the starter application, the pipeline triggers a build and once the build is done, you start seeing the recommendations, if any, automatically. 
Stack analysis gets triggered during build stages.

**Comment by burrsutter** [comment]
Looks fixed to me 
https://screencast.com/t/Ghx0wzcQCEM
