### ISSUE TITLE
Dropdown autocomplete covered by the browser one

### ISSUE THREAD

**Issue by bartoszmajsak** [openshiftio/openshift.io#4175]
##### Issue Overview

When searching for the repository to import I am not able to see my existing repositories, as browsers autocomplete covers the actual values. Refocusing the element (e.g. hitting `esc` or switching window back and forth) shows the actual value.

**Note**: It might not be only an issue of this particular component - worth to check if that's a problem with component we are using or the way we use it across the OSIO front-end.

##### Expected Behaviour

Actual repositories displayed.

##### Current Behaviour

Repositories covered by the browser autocomplete.

##### Steps To Reproduce

1. Import project
2. Try to select the repository to import (first wizard step)

##### Additional Information

I do clean-up my GH account from throw-away repositories, so the browser remembers more than I actually have. 

Browser:  `Google Chrome 68.0.3440.106 `
Env: prod

##### Screenshots

![image](https://user-images.githubusercontent.com/719616/44157637-38f57280-a0b3-11e8-87e6-08273d76e69d.png)

![image](https://user-images.githubusercontent.com/719616/44157678-50346000-a0b3-11e8-80b4-5cca6da34c46.png)

**Comment by vikram-raj** [comment]
@bartoszmajsak I am not able to reproduce this in prod. I think Its already fixed in this PR https://github.com/fabric8-launcher/ngx-launcher/pull/352. Can you please check it again?

**Comment by bartoszmajsak** [comment]
Looks like. Cannot reproduce anymore. Closing. Thanks for the heads up.
