### ISSUE TITLE
Filter in Planner not working as expected

### ISSUE THREAD

**Issue by sivaavkd** [openshiftio/openshift.io#4177]
##### Steps To Reproduce

1. Goto https://openshift.io/openshiftio/Openshift_io
2. Click on "Work items" and filter by Area:AppAnalytics
3.  You can see all AppAnalytics work items including User story 78.
4.  Now, Click on "Jonquil[Active] from Side panel.   You can still see user story 78.
5.  Now, Filter Area by "AppAnalytics"
6.  You CANNOT see 78.
7.  Note that 78 is a user story with area "AppAnalytics" and it is associated to Sprint 153 which is part of J train.

**Comment by joshuawilson** [comment]
is this still an issue?

**Comment by nimishamukherjee** [comment]
@sivaavkd do you still face this issue?

**Comment by sivaavkd** [comment]
Tried various filters and seems to be working fine.  Closing this.
