### ISSUE TITLE
Stack Report Recommendations are doubled

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#418]
https://screencast.com/t/WWywj8Ffy
https://screencast.com/t/DTyNN6zia

And what does "Report title on Application" mean?

And the Path to Manifest file does not make sense to me (the end-user), that location is something internal to the system.

**Comment by burrsutter** [comment]
And the font/word-wrap is a mess for longer Java package names
https://screencast.com/t/gIttAIMpsGt

**Comment by arunkumars08** [comment]
Linked here: https://github.com/fabric8-ui/fabric8-recommender/issues/257

**Comment by samuzzal-choudhury** [comment]
@burrsutter Thanks for reporting this.

The dropdown was added to change reports for multiple manifest files in a multi-module application and path was the natural choice. The intention was that the path shall point users to the appropriate manifest file in the codebase.

But, I agree that we should not show the full path of the temporary build location in the dropdown. Rather we have to figure out the portion of the path that will make more sense to a user. I have opened one issue https://github.com/fabric8-ui/fabric8-recommender/issues/258 to address that.

**Comment by samuzzal-choudhury** [comment]
@burrsutter The _Stack Report Recommendations_ block on the space dashboard is for preview only purpose and does not have the corresponding links to create work items. That block has a link to get the full stack report if the users are fine with recommendations and wish to take action on those.

**Comment by samuzzal-choudhury** [comment]
@burrsutter The **Stack Report Recommendations** block on the space dashboard is for preview only purpose and does not have the corresponding links to create work items. That block has a link to get the full stack report if the users are fine with recommendations and wish to take action on those.

**Comment by arunkumars08** [comment]
@burrsutter When we add the quick starters, pipeline gets triggered automatically and hence you see the recommendations shown up. This is kind of preview to users to have some information.

**Comment by arunkumars08** [comment]
Issue on text-overflow is fixed and is in production. @burrsutter You can verify once if things are fine and close if ok.

**Comment by burrsutter** [comment]
@samuzzal-choudhury "does not have the corresponding links to create work items." then please remove the button that does not work from the UI :-)

If you give me buttons, I tend to click on them.

**Comment by burrsutter** [comment]
We still need to address the doubling
https://screencast.com/t/nloagmuhS
https://screencast.com/t/C4YDt899nJlM
