### ISSUE TITLE
Idler is going crazy when there is no dc/jenkins in -jenkins namespace

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#4180]
Getting `TOO_MANY_REDIRECTS` when there is no dc in -jenkins namespace (manual reset for example) ![image](https://user-images.githubusercontent.com/98980/44206340-bb387200-a159-11e8-8751-6574030dc566.png)

**Comment by hrishin** [comment]
`bananas` ?

**Comment by chmouel** [comment]
![image](https://user-images.githubusercontent.com/98980/44253290-6fd89f00-a1ff-11e8-8ad6-f787152d37e5.png)

**Comment by chmouel** [comment]
maybe related https://github.com/fabric8-services/fabric8-jenkins-proxy/commit/99399c90d426140e31f442ab1c34eb77cc58471c

**Comment by chmouel** [comment]
weird that when trying this locally i am getting the right error handling : 

![image](https://user-images.githubusercontent.com/98980/44662637-a6d45f00-aa0e-11e8-9d7e-5e0c83e8ab09.png)

maybe that's just not deployed to master,

**Comment by ppitonak** [comment]
This error breaks E2E tests quite often

http://artifacts.ci.centos.org/devtools/e2e/devtools-saas-openshiftio-e2e-smoketest-released/129/05-03-jenkins-direct-log.png
http://artifacts.ci.centos.org/devtools/e2e/devtools-saas-openshiftio-e2e-smoketest-beta/127/05-03-jenkins-direct-log.png
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1b-released/653/05-01-jenkins-log-failed.png

**Comment by ppitonak** [comment]
Could this be related?
![image](http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-released/843/05-06-jenkins-log-failed.png)

**Comment by chmouel** [comment]
@ppitonak any chances you can give us a bit more context to this error message?

**Comment by ppitonak** [comment]
@chmouel everything looks the same as in `too many redirects` case but the actual content of http://jenkins.openshift.io is what you see on screenshot

**Comment by sthaha** [comment]
> Could this be related?
> ![image](https://camo.githubusercontent.com/d74e73f5ab2748a493ccae07fafc456138b6fb1e/687474703a2f2f6172746966616374732e63692e63656e746f732e6f72672f646576746f6f6c732f6532652f646576746f6f6c732d746573742d6532652d6f70656e73686966742e696f2d736d6f6b65746573742d75732d656173742d31612d72656c65617365642f3834332f30352d30362d6a656e6b696e732d6c6f672d6661696c65642e706e67)


@chmouel seems to me like an openshift n/w issue again  - 5432 AFAICT is the postgres port.

**Comment by sthaha** [comment]
@ppitonak could you please explain why this is a P1 ?

 namespaces missing DC for Jenkins must be a very rare case and is related to E2E tests resetting workspaces. How are you validating if the reset environment has worked?

**Comment by chmouel** [comment]
But that issue only is about when resetting environment not sure if that can be postgresql related,

agree with you @sthaha `oc delete all` is only for people who have -edit rights on -jenkins and does that kind of things withouth going by the tenant reset call,

**Comment by chmouel** [comment]
I tried again to confirm and looking at the logs it is indeed the deletion that makes the issues : 

```
% oc delete all --all -n $T-jenkins
replicationcontroller "jenkins-8" deleted
replicationcontroller "jenkins-9" deleted
service "bayesian-link" deleted
service "jenkins" deleted
service "jenkins-jnlp" deleted
deploymentconfig.apps.openshift.io "jenkins" deleted
route.route.openshift.io "jenkins" deleted
````

access jenkins.opebshift.io

```
{"cluster":"https://api.starter-us-east-2.openshift.com/","component":"proxy","level":"info","msg":"found ns : \"cboudjna2-jenkins\", cluster: \"https://api.starter-us-east-2.openshift.com/\"","ns":"cboudjna2-jenkins","part":"token_json","request-hash":3682938397,"time":"2018-10-15T08:15:17Z"}
{"cluster":"https://api.starter-us-east-2.openshift.com/","component":"proxy","level":"info","msg":"Fetched OSO token from OSIO token","ns":"cboudjna2-jenkins","part":"token_json","request-hash":3682938397,"time":"2018-10-15T08:15:17Z"}
{"cluster":"https://api.starter-us-east-2.openshift.com/","component":"proxy","level":"error","msg":"Error when starting Jenkins: 2: openshift client error: got status 404 Not Found (404) from https://api.starter-us-east-2.openshift.com/oapi/v1/namespaces/cboudjna2-jenkins/deploymentconfigs/jenkins","ns":"cboudjna2-jenkins","part":"token_json","request-hash":3682938397,"time":"2018-10-15T08:15:17Z"}
{"component":"proxy","level":"info","msg":"returned: |key: \"\" |ns: \"cboudjna2-jenkins\" |fwd: false|","request-hash":3682938397,"time":"2018-10-15T08:15:17Z"}
```

**Comment by sthaha** [comment]
@chmouel good find! Any thoughts in case of `404` what the proxy should do?

**Comment by chmouel** [comment]
return a 404 ? user would know that "jenkins dc cannot be found" ?

**Comment by chmouel** [comment]
@ppitonak We are working on that issue,

But it came to my attention that it has been estimated as critical for running the E2E, from my understanding with the chat we had on mattermost, you don't do a tearUp or tearDown of the environment  (i.e: resetting the env), can you please confirm ? 

Because if you don't do the whole `oc delete --all all` of the -jenkins tenant following by a call to the fabric8-tenant service to recreate them you would not see this issue, (as per my paste earlier)

I am going to set this issue as p2 as it should be, please feel free to convince me otherwise,

**Comment by ppitonak** [comment]
@chmouel we reset the environment (i.e. click "Erase My OpenShift.io Environment on https://openshift.io/myuser/_cleanup) after test run

**Comment by chmouel** [comment]
@ppitonak well right so can you please let us know if there is objects i.e: `oc get all -n $USER-jenkins` before running the start of a test, and run that would be very useful so we can make sure what is your issue, the `oc get ev -n $USER-jenkins` and `oc logs jenkins/dc -n $USER-jenkins` and the time the test has been started so we  can correlate inside the idler logs,

Thanks a lot,

**Comment by ppitonak** [comment]
I will provide all data when I see this error next time.

**Comment by ppitonak** [comment]
We have failed job

* [console log](https://ci.centos.org/job/devtools-saas-openshiftio-e2e-smoketest-released/246//console)
* [artefacts](http://artifacts.ci.centos.org/devtools/e2e/devtools-saas-openshiftio-e2e-smoketest-released/246/)
* [logs from OpenShift before run](http://artifacts.ci.centos.org/devtools/e2e/devtools-saas-openshiftio-e2e-smoketest-released/246/oc-jenkins-logs-before-all.txt)
* [logs from OpenShift after run](http://artifacts.ci.centos.org/devtools/e2e/devtools-saas-openshiftio-e2e-smoketest-released/246/oc-jenkins-logs.txt)

**Comment by ppitonak** [comment]
> I am going to set this issue as p3 as it should be, please feel free to convince me otherwise,

Setting the priority back to P1 because it caused PR check to saas-openshiftio failure, affects whole OSIO team.

**Comment by chmouel** [comment]
@ppitonak your log indicate you haven't run it inside the jenkins namespace, would it be possible to run it there instead? 

Looking at the events (although ideally i'd like to do the whole content inside the jenkins user namespace) it seems that the jenkins does have a deploymentConfig, so can you please create a new issue with these logs. 

This issue as suspected has nothing to do with your problem, it is just another issue (which can be set as P1)

**Comment by chmouel** [comment]
And FYI the error in the console.log that you see : 
```
No resources found.

Error from server (NotFound): deploymentconfigs.apps.openshift.io "jenkins" not found
```

is because you haven't run the "./oc-get-project-logs.sh script  in the proper namespace,

**Comment by chmouel** [comment]
Removing my previous comment about not being run in jenkins namespace which indeed does,

it seems that the tenant service don't recreate properly the jenkins namespace after tenant reset or this wasn't done properly,

(either way this should be another issue)

**Comment by chmouel** [comment]
Removing P1 from this issue,

**Comment by chmouel** [comment]
@ppitonak maybe related to your issue https://github.com/openshiftio/openshift.io/issues/4121#issuecomment-410648540

**Comment by chmouel** [comment]
We have merged https://github.com/fabric8-services/fabric8-jenkins-proxy/pull/334#issuecomment-432577825 and now errrors should be more explicit i.e: for our issue when there is no dc inside jenkins namespace we are now showing a 500 : 

![image](https://user-images.githubusercontent.com/98980/47427814-c202e700-d791-11e8-8d1a-67fd714c9310.png)

@ppitonak this may affects your tests (in a good way), you are not going to have a redirect loop but an error message, let us know how it goes,
