### ISSUE TITLE
Provide richer information to set context.

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4185]
Updated Description
Provide richer content on the Create Space and Create Application screens.  This should help novice users to understand OSIO concepts.

Historical
As part of the design thinking session around _Goal A - Improve Onboarding for novice_, **providing richer information to set context** was prioritized as an issue to address.  The following suggestions should help provide context on the design direction:
- Provide richer content describing concepts during the user flow
- Would potentially like more context around the status screen
- On Create New Space: Replace the warning notification box by explanations about what is a space and what steps will be following
- Explain in the create space wizard, what is in the wizard.

**Comment by sdash-redhat** [comment]
The first draft of WF/concept is available here for review: 
**https://redhat.invisionapp.com/share/AVO07M22SPQ#/319408218_Slide01**
@serenamarie125 @muruGanesan @catrobson @sunilmalagi

**Comment by sdash-redhat** [comment]
Updated wireframe here 0.2. 👍 
This story is addressed in the following first draft wireframe/concept
https://redhat.invisionapp.com/share/F9O152GZN8D
Related to the stories -- #4185, #4186, #4187 and #4189

**Comment by muruGanesan** [comment]
@serenamarie125, @catrobson, @sdash-redhat , @AshishDurgude 
Please review our UX proposal
https://redhat.invisionapp.com/share/E7O609F8T9W#/321098831_Proposed_Screen_Create-Space

**Comment by catrobson** [comment]
@parvathyvr @Veethika FYI for your review as well.

I've added a few comments on the InVision document.

**Comment by serenamarie125** [comment]
@muruGanesan this needs to be reviewed during one of our Mon/Thu Review meetings as well, please add it as an agenda item.

**Comment by serenamarie125** [comment]
@AshishDurgude @sunilmalagi can we get an updated Invision file which has 
- the "This space will be public" should remain on the right using the info icon
- the modal backgrounds should be black

Thank you

**Comment by christianvogt** [comment]
dev story: https://github.com/openshiftio/openshift.io/issues/4185

**Comment by joshuawilson** [comment]
dev story https://openshift.io/openshiftio/Openshift_io/plan/detail/788

**Comment by christianvogt** [comment]
@serenamarie125 there's still outstanding asks for the invision update before we can assign the dev work.

**Comment by muruGanesan** [comment]
> @AshishDurgude @sunilmalagi can we get an updated Invision file which has
> 
>     * the "This space will be public" should remain on the right using the info icon
> 
>     * the modal backgrounds should be black
> 
> 
> Thank you

@serenamarie125, based on 'OpenShift.io Sprint Demo' held on 26th Sep 2018 & 11 Oct 2018, we decided to keep the "public space" warning info on top of the action button. Because later, the user will have an option to choose "private | public"  so the message near the action button would be an appropriate placement.

1) Please let us know if you would like to move "This space will be public" information to right?
2) "the modal backgrounds should be black" - could you please explain this point? are you mentioning about the 'gray mask' below the modal? -or-  do you wanted to change the background of the modal?

**Comment by serenamarie125** [comment]
@muruGanesan there is a bunch of confusion at the moment as to what is being proposed by this design.  For example:

- does this only affect the Create Space modal?
- I think the main poin is to add a right column to provide contextual information (shown below)
![screen shot 2018-11-09 at 12 12 58 pm](https://user-images.githubusercontent.com/12504403/48277535-f7a60200-e418-11e8-88b3-1e7d83b6202a.png)
- should it be a 50/50 split?

Re: the public Info message, I am trying to get clarification from PM

**Comment by muruGanesan** [comment]
@serenamarie125, thanks for your info. 
@sunilmalagi can help us to change the split to 50:50.

**Comment by joshuawilson** [comment]
I've commented on the design. I like Option 1 more.

**Comment by muruGanesan** [comment]
@joshuawilson, thanks. 
This story and UX proposal overlap with #4191. I will discuss this point with the team (in today's UX design review meeting) and conclude.

**Comment by muruGanesan** [comment]
@vikram-raj,
As discussed,
Please look at our UX recommendation below, this covers 'Space & application' creation pages ONLY.
[The story #4191 covers visual aspects of the OSIO flow so for the current implementation you can refer the below recommendation]

https://redhat.invisionapp.com/share/E7O609F8T9W#/332319129_4185_Proposed_SpaceCreation

CC: @nimishamukherjee, @joshuawilson, @christianvogt

**Comment by vikram-raj** [comment]
@muruGanesan Please see my comment on invision screen.

**Comment by muruGanesan** [comment]
@vikram-raj, I saw your comments about the error case. I will refer PatternFly and add those additional screens.

**Comment by muruGanesan** [comment]
@vikram-raj, based on yesterday's UX design review meeting, we decided to handle the 'error case' -or- 'form validation' in a different story.  Moreover, we would like to look at those 'error cases' in a holistic way (across OSIO).

**Comment by joshuawilson** [comment]
That kind of error handling/display is very common. There should be lib for it but if not, we either add it to PF or make our own. We need to do a bit of research to see what is available for the tech stack we are using.

**Comment by muruGanesan** [comment]
@serenamarie125, @joshuawilson, @christianvogt, @vikram-raj 
I have seen this implementation as part of SOS demo (on 4Dec18) & stakeholder review meeting (5Dec18) stakeholder's meeting.

If required we can close this story.

**Comment by serenamarie125** [comment]
Looks great, since there is an associated planner item, i am closing
