### ISSUE TITLE
Provide "here's what you can do now!" once completing a task

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4187]
As part of the design thinking session around _Goal A - Improve Onboarding for novice_, **here's what you can do now** was prioritized as an issue to address.  The following suggestions should help provide context on the design direction:
- Once the flow is completed (of creating an application), provide actions to guided the user on what he can do next

**Comment by sdash-redhat** [comment]
This story is addressed in the following first draft wireframe/concept
https://redhat.invisionapp.com/share/F9O152GZN8D
Related to the stories -- #4185, #4186, #4187 and #4189

**Comment by serenamarie125** [comment]
closing since this is already addressed by 2 other issues
