### ISSUE TITLE
Nonreproducible SSO/Forge failures seen

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#419]
Encountered the following errors in trying to add a new app to a space:

![screenshot from 2017-07-25 22-52-37](https://user-images.githubusercontent.com/642621/28602504-6df00dc6-718c-11e7-90b9-39c74e1eebbe.png)
![screenshot from 2017-07-25 22-50-33](https://user-images.githubusercontent.com/642621/28602505-6dfdcd94-718c-11e7-9303-22b9d906ddba.png)

**Comment by ldimaggi** [comment]
And then this error on a retry of the same operation - is Forge simply down? 

![screenshot from 2017-07-25 22-53-45](https://user-images.githubusercontent.com/642621/28602519-81d572ea-718c-11e7-83f5-754884de4a4b.png)

**Comment by ldimaggi** [comment]
10 min later - and the error is not being seen. Need to investigate just what happened...

**Comment by joshuawilson** [comment]
Once you try it again, if it doesn't fail we should close it.

**Comment by ldimaggi** [comment]
Closing. It happened only once...
