### ISSUE TITLE
Address animation consistency issues

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4192]
As part of the design thinking session around _Goal A - Consistency of Design Patterns_, **Address animation consistency issues** was prioritized as an issue to address.  The following suggestions should help provide context on the design direction:
- Creation & naming should be smoother than it is today 
- Improve the transition between the pages, we should not see the “space dashboard” between the screen

**Comment by muruGanesan** [comment]
There are two parts
Part-1:  'Space dashboard' appears during the application creation flow. - should be removed 
Here is the first-cut draft for correcting the screen 
https://redhat.invisionapp.com/share/U7O4E0W3A6V

Part-2: Application Creation (Launcher) has some glitches in animation - I will capture the issue and provide UX recommendation soon

**Comment by muruGanesan** [comment]
There are two parts
Part-1: 'Space dashboard' appears during the application creation flow. - should be removed
Here is the first-cut draft for correcting the screen
https://redhat.invisionapp.com/share/U7O4E0W3A6V

Part-2: Application Creation (Launcher) has some glitches in animation - I will capture the issue and provide UX recommendation soon
https://redhat.invisionapp.com/share/U7O4E0W3A6V#/320755488_Part-2_4192-Consistancy_Animation_Issue

**Comment by serenamarie125** [comment]
@muruGanesan @AshishDurgude thank you for taking the time to capture this!  I'm asking a few devs about next steps.

**Comment by serenamarie125** [comment]
@mindreeper2420 might you be able to look into the issues that we mention above and the suggested solution?  I spoke with @catrobson earlier today and we were wondering if you could take a quick look to scope the effort, and then discuss with Catherine to see if you had time to address this in the next week or so.

**Comment by mindreeper2420** [comment]
@serenamarie125 I can take a look. I know that this process uses two different modules, so that will have to be taken into account for solutions/effort. I'll speak with Dan L. too, as he worked with me on the initial implementation of the two Creation and Naming overlay screens.

**Comment by mindreeper2420** [comment]
@serenamarie125 a couple of things I noticed:

1) I'm not seeing any odd animations when starting in a Space and adding a Codebase. The animation from the overlay to the Launcher is smooth, and I was unable to witness the awkward sliding motion of the vertical step indicator that was noted in the doc. This could just be my browser, but I'm not sure. Leaving the Launcher and returning to the Space dashboard is also smooth.

2) When creating a new Space (start on the _home page) and proceeding through the Create Space/Add Codebase overlays, the screen changes behind the overlays as expected (the design always called for the Space dashboard to load behind the overlays). When transitioning to the Launcher, I do not see any hiccups in animation or odd transitions.

3) When I refresh the Launcher, I do see that the vertical step indicator does animate in a slide down transition from the Application Name input. This doesn't seem to add the extra spacing, as described in the doc, but it can be an attention grabber. This is outside of the OSIO Platform, so I will need to investigate further in the Launcher itself.

**Comment by serenamarie125** [comment]
Just re-tested as well @mindreeper2420.  No longer reproducible - maybe someone fixed it purposefully or inadvertently ?  Regardless, i will close.  Thanks for looking into it!
