### ISSUE TITLE
Analyze Dashboard : Improve home page empty state for on boarding

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4194]
1. Improve the Home page empty state for onboarding

![home02](https://user-images.githubusercontent.com/12504403/46923708-d0ab0a80-cfe9-11e8-99a4-43be18bd9eb4.png)

1. Space Name text field should have default focus
<img width="1326" alt="screen shot 2018-10-16 at 8 22 59 am" src="https://user-images.githubusercontent.com/12504403/47016144-d5bca680-d11c-11e8-87ea-e0446ad491d8.png">

1. Application Name text field should have default focus
1. Appropriate radio button should be selected, based on which CTA is selected from the empty space
<img width="1319" alt="screen shot 2018-10-16 at 8 23 32 am" src="https://user-images.githubusercontent.com/12504403/47016153-d9502d80-d11c-11e8-99ca-b79c441afc62.png">

@andrewazores @joshuawilson this description now covers the proposed design.  Please review

**Comment by Veethika** [comment]
Thank Samir!

**Comment by serenamarie125** [comment]
For this task, we should be focusing on the scenario where we are onboarding a new user, thus don't worry about the error states for part of this.

**Comment by muruGanesan** [comment]
@serenamarie125, I believe that new user flow would start from 1. 'Space creation' and then 2. Application creation. - correct me if I am wrong.

@Veethika, I believe you might have finalised the empty state and starting points. 
I am curious to know what direction we are heading towards .i.e. as per your discussion with Serena, Steve Speicher and Steve Gutz, are we going to start with "an application creation" from 'the empty state'?

**Comment by Veethika** [comment]
Based on discussions with various stakeholders, it was understood that users should at least have one application created by the time they land on the space dashboard. This implies that there would never be a situation when the dashboard would have empty states(except the work-item widget that requires to create a work-item in Planner). 

Following are the new flows proposed by @serenamarie125 and I, to ensure the user's prime focus after onboarding is on 'creating an application'.


Option 1- welcome them, explain that there are 2 ways to get started, and provide 2 CTAs ... the difference here could be that we preselect the appropriate radio button ( if that's possible )
<img width="1222" alt="screen shot 2018-09-18 at 9 05 59 pm" src="https://user-images.githubusercontent.com/35127763/46071907-b5916b80-c19e-11e8-8db1-70399c214b48.png">


Option 2 - welcome them, explain that they can get started by creating a sample app or importing existing code, and provide a single CTA which brings up the space modal, app modal, followed by the launcher
![emptystate 1](https://user-images.githubusercontent.com/35127763/46074800-399b2180-c1a6-11e8-8bed-c1665e6539b2.png)


Option 3 - Keeping the 'Import Codebase' as secondary CTA to 'Create Codebase'
![osio-001](https://user-images.githubusercontent.com/35127763/46074874-76671880-c1a6-11e8-8c04-9be6003b466f.png)

**Comment by sdash-redhat** [comment]
Nice explorations!I am assuming the user has created a space name and this flow is engaged after that. 

Just one thought that came to my mind was that as creation of work item is there as the part of the dashboard, a user might want to start defining a set of tasks to some team members before even creating a an application -- for example let's say one of the tasks he creates might be about creating an application which is expected to be carried out by a more knowledgeable technical member of the team of that space. If this use case persists, the user may post creation of space might want to skip the application creation process (post the creation of space for the first timer) and rather start with work item creation. If this use-case is not applicable to our flow, then, I vote for Opt 3. 

@serenamarie125 @muruGanesan @Veethika

**Comment by muruGanesan** [comment]
"option-3" looks better.

@serenamarie125, @Veethika,  
I too believe that the user is inside the space (i.e. either created or part of a contributor) before starting this application flow.

**Comment by Veethika** [comment]
@stacymcauliffe That's right. With the new flow, the user would be making that choice of choosing between creating and importing upfront.
@muruGanesan @sdash-redhat letting the users define work-items before creating an app might lead to them using Planner as a mere issue tracker, which is a problem we need to address as well. Space is definitely needed for an application to be created, we are yet to define the complete flow for how space creation would be handled. But it would definitely be taken care of in the same flow (would most probably be pre-defined with a default name and template that will be editable).  @serenamarie125 correct me if I'm wrong.

**Comment by Veethika** [comment]
Invision Doc: https://redhat.invisionapp.com/share/3NODELM7JKQ#/323294967_Cover_Page_Template

**Comment by AshishDurgude** [comment]
Hi, @serenamarie125 @Veethika I have completed the visual design for this issue. below is the InVision link: https://redhat.invisionapp.com/share/G2OFKWK4MKX

Also, I am giving Google folder link for this issue: https://drive.google.com/drive/folders/1TaRwpr3o4i88hTe7XNNaauDGsA1Ye1_D?usp=sharing

Question for @serenamarie125 : we decided to create launcher flow in Modal view. In the wireframe that veethika provided was not modal view. SO my question is do I need to create the same visuals for the Modal view? I have another question. If you open InVision link, you will see "home option 01" and "home option 02". both are same except the middle icon. in "home option 01", I used the icon where are being used in OSIO for showing codebase. In "home option 02" the icon you are seeing is the icon which I created for showing codebase. What do you think about this new icon? If you liked then we can also include it in Patternfly for future use.

**Comment by serenamarie125** [comment]
@AshishDurgude please update the invasion file to just have what you did for Slide 4 which shows the new empty state with the preferred icon.  We don't need to show the flow in the invision.

**Comment by serenamarie125** [comment]
@AshishDurgude can you also create the necessary icon?  Have we done this in the past and gotten it added to the pf-icon set?

**Comment by AshishDurgude** [comment]
@serenamarie125 The newly created icon is not added in pf-set. We can add it but I do not know the process of adding an icon to Patternfly. I will add that SVG icon link here.
https://drive.google.com/open?id=1tFoWCGOCjlxZN5-SRYs36YOl8J32t6NX

**Comment by joshuawilson** [comment]
@serenamarie125 it appears there are at least place that need design but only one has been provided.

1. empty state for application (getting started) https://openshift.io/openshiftio/Openshift_io/plan/detail/840
2. empty state codebases widget https://openshift.io/openshiftio/Openshift_io/plan/detail/842
3. empty state for stack report widget https://openshift.io/openshiftio/Openshift_io/plan/detail/841

**Comment by joshuawilson** [comment]
There also appears that the context menu has changed. This is not within the scope of this change.

**Comment by andrewazores** [comment]
I need to clarify some parts of this design before development work can get started.

First, please confirm where this new empty state will be displayed. There are a lot of references to "dashboard" in the preceding discussion, which makes it seem as if this is an empty state for the Analyze Dashboard. However, I'm not sure I understand how that flow is supposed to play out - the Analyze Dashboard implies a Space context, yet the invision design implies that this is the *Home* page (via the context menu).

Second, if this is truly on the Home page and the later slides in the Invision design are to be taken at face value, then can the scope of this specific task be defined as adding this new empty state to the Home page, which does nothing more than summon the existing Launcher overlay UI? Any visual changes to the Launcher itself should be treated as separate and unrelated to this empty state.

Third, again assuming all the above is correct, could somebody define when exactly this empty state is displayed on the Home page? Is it displayed if and only if the current logged in user owns 0 Spaces? What if they own 0 Spaces but are a Collaborator on at least 1?

**Comment by serenamarie125** [comment]
> @serenamarie125 it appears there are at least place that need design but only one has been provided.
> 
> 1. empty state for home page (before getting started) https://openshift.io/openshiftio/Openshift_io/plan/detail/840
> 2. empty state codebases widget https://openshift.io/openshiftio/Openshift_io/plan/detail/842
> 3. empty state for stack report widget https://openshift.io/openshiftio/Openshift_io/plan/detail/841

@joshuawilson this only covers your #1 for on boarding

**Comment by andrewazores** [comment]
I am still looking for clarification on my questions above.

**Comment by andrewazores** [comment]
I have a fourth question. Why does the main action button on the empty state card read "Create New Codebase", but the modified Launcher flow on the next slide starts with a new step that appears to both create a new Space as well as a Codebase (Application Name) to belong to the Space? Is this intentional?

**Comment by serenamarie125** [comment]
@andrewazores 

> First, please confirm where this new empty state will be displayed. There are a lot of references to "dashboard" in the preceding discussion, which makes it seem as if this is an empty state for the Analyze Dashboard. However, I'm not sure I understand how that flow is supposed to play out - the Analyze Dashboard implies a Space context, yet the invision design implies that this is the Home page (via the context menu).

This empty state is is for the "Home" page

> Second, if this is truly on the Home page and the later slides in the Invision design are to be taken at face value, then can the scope of this specific task be defined as adding this new empty state to the Home page, which does nothing more than summon the existing Launcher overlay UI? Any visual changes to the Launcher itself should be treated as separate and unrelated to this empty state.

The desire is to have defaults changed & default focus on certain items in the Space & Application modals as well ... 
1. Select AGILE by default on the Space creation modal
1. Default focus should be on the Space Name text field
1. Select the appropriate radio button on the Application creation modal (Create New or Import based on selection of Primary CTA button or secondary CTA link)
1. Default focus should be on the Application Name text field

> Third, again assuming all the above is correct, could somebody define when exactly this empty state is displayed on the Home page? Is it displayed if and only if the current logged in user owns 0 Spaces? What if they own 0 Spaces but are a Collaborator on at least 1?
This empty state is displayed if they own 0 spaces and are not a collaborator.  Reasoning is that the Recent Spaces should include references to spaces that users are collaborators on.

> I have a fourth question. Why does the main action button on the empty state card read "Create New Codebase", but the modified Launcher flow on the next slide starts with a new step that appears to both create a new Space as well as a Codebase (Application Name) to belong to the Space? Is this intentional?
Please ignore the launcher modifications as part of this Issue.  I will get these updated.

**Comment by andrewazores** [comment]
Thanks, that clears it up a lot.

```
1. Select AGILE by default on the Space creation modal
```

This is doable, but it means that the overlay code will need to be modified so that it makes assumptions about what templates exist and are available, which makes it more fragile and require dev time for maintenance (and an application redeploy) any time this is changed again in the future. Currently it makes no such assumptions and the list is populated from a backend service, and the default selection is simply the first template returned by this backend. It should be possible to achieve this change by simply changing the backend to reorder the list so that the desired default is listed first, though I don't know if there may be some unintentional side-effects elsewhere to changing this ordering. @joshuawilson any thoughts on that? The API in question is `${WIT_API_URL}spacetemplates`.

**Comment by serenamarie125** [comment]
@andrewazores if it's not a "quick" fix, let's drop that from the scope of this Issue.

**Comment by andrewazores** [comment]
It should be quick to implement on the backend but the difficulty is in verifying that no other API consumer relies on the current ordering. Implementing it on the frontend is possible and can be done very quickly, but I would call it a hacky solution.

I can work around it on the frontend by either simply reversing the returned list (currently just SDD and Agile) or sorting the elements by name, and then continuing to select the first element. This isn't as fragile as making an assumption that an "Agile" element exists, but it still leaves the default selection prone to changing inadvertently in the future if the backend does change its response order or contents.

**Comment by andrewazores** [comment]
That may be best.

**Comment by serenamarie125** [comment]
I updated the Description to pull it :)  and added another GH Issue here: https://github.com/openshiftio/openshift.io/issues/4427

**Comment by joshuawilson** [comment]
There is already a PR to make Agile the default and remove it as a selection. It initially used only the UI to make the change but I've requested the change to be started in the backend. 
https://github.com/fabric8-ui/fabric8-ui/pull/3371
