### ISSUE TITLE
Analyze Dashboard : Re-evaluate in progress states in the dashboard

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4198]
As part of the design thinking session around _Goal B - Providing better guidance for the next steps once an application is created - Improve dashboard page, to include more obvious actions_, **re-evaluate in progress states in dashboard** was prioritized as an issue to address.

**Comment by sdash-redhat** [comment]
@serenamarie125 @catrobson @muruGanesan 
Appears that it has overlap with  #4197 - 'Analyze Dashboard: Address issues with after app creation'

**Comment by serenamarie125** [comment]
@sdash-redhat 
Yes!  #4197 deals with the applications card, so avoid that
Re: #4187 I wouldn't think that affects the content of the dashboard cards themselves, do you?

**Comment by sdash-redhat** [comment]
Thanks, @serenamarie125 for confirming :) Will avoid #4197 part. 

True, regarding #4187, it won't impact the dashboard card themselves, but only the state transitioning to that dashboard. Will explore and share.

**Comment by sdash-redhat** [comment]
Here is the first draft for internal UX review
https://redhat.invisionapp.com/share/2FO931J79ZU
@muruGanesan @serenamarie125 @catrobson

**Comment by sdash-redhat** [comment]
Based on the last discussion a comparison among the current state and proposed states provided in the WF for internal UX review. 
https://redhat.invisionapp.com/share/EXODVV9BYRK

@muruGanesan @serenamarie125

**Comment by sunilmalagi** [comment]
Here you go for HiFi visuals for #4198:
https://redhat.invisionapp.com/share/VYOHSD2WKQZ#/324695043_Analyze_Dashboard
&
Sketch file:
https://drive.google.com/open?id=1iKktrrwLreMqQV2DmQXOEeUQ_94L9lhu

@sdash-redhat @serenamarie125 @muruGanesan

**Comment by sunilmalagi** [comment]
@sdash-redhat @serenamarie125 @muruGanesan

Updated the visuals based on yesterdays discussion, links remains same as mentioned above..

**Comment by sdash-redhat** [comment]
The annotation is added to the Final visual. 
https://redhat.invisionapp.com/share/VYOHSD2WKQZ#/330469956_-4198-Analyze_Dashboard_-_Re-Evaluate_In_Progress_States_In_The_Dashboard-pdf_1


Also adding the image inline below: 

![artboard 1](https://user-images.githubusercontent.com/27761023/48262328-1f608e80-e448-11e8-8721-e25ed824733b.png)


Marking this story as complete.

**Comment by serenamarie125** [comment]
@sdash-redhat please put this on the stakeholder meeting for December 19th

**Comment by muruGanesan** [comment]
@serenamarie125, @sdash-redhat,
This git story is overlapping with #4193, I created the flow, reviewed with stakeholders, and closed.
This story can be closed...

Invision link:
https://redhat.invisionapp.com/share/MHP7TIO3XYK#/332556491_Proposed_Change-_Space_Dashboard

**Comment by serenamarie125** [comment]
This work was incorporated into #4193 so closing this story.
