### ISSUE TITLE
Wireframes:Managing the Openshift instances that user can connect to OSIO from User ‘Settings’

### ISSUE THREAD

**Issue by parvathyvr** [openshiftio/openshift.io#4199]
DESCRIPTION
Wireframes that cover the all screen flows needed for adding openshift instances the user can connect to OSIO from user settings.Also capture the 'resources' tab where the user can view the overview of the openshift instances connected to OSIO.

PARENT: https://github.com/openshiftio/openshift.io/issues/4064

VERIFICATION CRITERIA

- [ ] Wireframes created in Sketch and posted on Google Drive with interaction notes for all behaviors
- [x] Wireframes posted to InVision
- [ ] Wireframes reviewed by UXD, Dev, PM

**Comment by parvathyvr** [comment]
@serenamarie125 below is the Invision link to the wireframes made:
https://redhat.invisionapp.com/share/D7NSUDLB25Z#/318449533_Table_Of_Contents

**Comment by serenamarie125** [comment]
Closing, this work is being tracked by #4540
