### ISSUE TITLE
Unexpected results seen in space query

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#420]
In querying for the word "test" in space titles - results are as follows - how did Muru's space name match the query?

![screenshot from 2017-07-25 22-20-45](https://user-images.githubusercontent.com/642621/28603682-8c391a00-7193-11e7-8dc8-b936c2c8c336.png)

**Comment by joshuawilson** [comment]
Because the search looks at the Space name and the Space description. So unless we want to change that, it works the way it is supposed to.

**Comment by ldimaggi** [comment]
Ah - OK - thanks - I thought that it was the title only. Closing.
