### ISSUE TITLE
Wireframes:Defining Environments from ’Space Settings’

### ISSUE THREAD

**Issue by parvathyvr** [openshiftio/openshift.io#4200]
DESCRIPTION
Wireframes that cover the all screen flows needed for defining environments from space settings.Capture screens for both scenarios ie,while a space already exists and while creating a new space
PARENT: https://github.com/openshiftio/openshift.io/issues/4064

VERIFICATION CRITERIA
- [ ] Wireframes created in Sketch and posted on Google Drive with interaction notes for all behaviors
- [ ] Wireframes posted to InVision
- [ ] Wireframes reviewed by UXD, Dev, PM

**Comment by serenamarie125** [comment]
Note: This design work is to be done in the J Train, although development will follow in a later release.

**Comment by parvathyvr** [comment]
The first cut wireframes are posted in invision: https://redhat.invisionapp.com/share/A7NWVO8KZ2S#/318447884_Table_Of_Contents
**Note: These wireframes are under review and not final.**

**Comment by serenamarie125** [comment]
Closing, this work is being tracked by #4540
