### ISSUE TITLE
License conflict reported but no conflicting license details provided in stack report

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#4202]
##### Issue Overview

When I trigger stack analysis for a real-world Vaadin repository through the IDE extensions (since there is now support for full Maven) I don't get any supporting information around license conflicts.

##### Expected Behaviour

There should be some information in the stack report that tells you where the license conflicts actually are.

##### Current Behaviour

See screenshot, there is no information around what/where the license conflict is occurring.

##### Steps To Reproduce

1. Trigger stack analysis for https://github.com/vaadin/dashboard-demo
2. Go to the license tab.

##### Additional Information

https://giphy.com/gifs/1dQ8bTKm6sFmTGBiid/fullscreen

**Comment by miteshvp** [comment]
@rootAvish - can you PM me your stack-id please?

**Comment by sunilk747** [comment]
I triggered stack analyses call for the above mentioned repo and in response I am getting the details of conflicting license. I don't know why it's not coming up in stack report.

**Comment by sunilk747** [comment]
@miteshvp The messaging part is done. I have added reason for each case where the stack license is none or unknown and for the above issue conflicting licenses is not showing up because of a bug in stack-report code. I guess jai is working on this. He can add more. cc @invincibleJai

**Comment by invincibleJai** [comment]
thanks @sunilk747 , yes I need to look into it. Not started with it yet. Will update once I start with this.

**Comment by invincibleJai** [comment]
@sunilk747 changes have been done, it's live in extension. Pls verify

**Comment by GeorgeActon** [comment]
@rootAvish Can we close this?

**Comment by rootAvish** [comment]
Verified as working.
