### ISSUE TITLE
No option to add comments in planner stories

### ISSUE THREAD

**Issue by yzainee** [openshiftio/openshift.io#4207]
##### Issue Overview
Not able to add any comments on the planner stories as the tick mark is disabled

##### Expected Behaviour
IT should allow the user to add comments.

##### Current Behaviour
Tick mark is diabled and hence cannot submit (add) comments

##### Steps To Reproduce

1. Click to open a story in planner.
2. Click on the comment box, add some comments

##### Additional Information
Browser - Chrome, Mozilla Firefox
![image](https://user-images.githubusercontent.com/37098367/44273113-24081300-a25c-11e8-9f50-2f214e96fb6c.png)

**Comment by GeorgeActon** [comment]
@yzainee Is it just work item 326 or are there other work items where you have the same problem? 
    I was unable to replicate your problem.

Did you click the edit 'pencil' to add the comment or did you click in the comment box?

what version of Chrome are you on?

What feature Opt-in level have you selected in OSIO?

**Comment by yzainee** [comment]
@GeorgeActon 
Whether i use pencil or the dialogue box, in both the cases, i dont see an option to click on tick mark

Chrome - Version 66.0.3359.117 (Official Build) (64-bit)
Mozilla Firefox Quantum - 59.0.2 (64-bit)

Features Opt in - Internal Experimental Features

**Comment by jarifibrahim** [comment]
This is similar to https://github.com/openshiftio/openshift.io/issues/3894
We seem to have an issue with firefox.

>Chrome - Version 66.0.3359.117 (Official Build) (64-bit)

@yzainee can you please update to latest chrome (v68.0) and try again? I cannot reproduce this on latest chrome.

**Comment by yzainee** [comment]
@jarifibrahim 
install google-chrome-stable gives me this
google-chrome                                                                                                                                                                       49 kB/s | 3.8 kB     00:00    
Last metadata expiration check: 0:00:00 ago on Thu 23 Aug 2018 11:07:48 AM IST.
Package google-chrome-stable-66.0.3359.117-1.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

I think it has something to do with google chrome browser version support for fedora. Try checking in some laptop with fedora in it once.

**Comment by jarifibrahim** [comment]
@yzainee can you please try downloading from here https://www.google.com/intl/en_in/chrome/? Choose rpm 64 bit.

>I think it has something to do with google chrome browser version support for fedora. Try checking in some laptop with fedora in it once.

I am on fedora using chrome 68

**Comment by yzainee** [comment]
@jarifibrahim Yes it works on the latest version of chrome.
