### ISSUE TITLE
Improper object name in the `fabric8-analytics-data-model` repository

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#4214]
##### Issue Overview

The problem has been found in the `utils.module` in `execute_gremlin_dsl` function:
https://github.com/fabric8-analytics/fabric8-analytics-data-model/blob/master/src/utils.py#L33

##### Expected Behaviour

- `resp` object to be used in the function
- unit tests has the full coverage for the `execute_gremlin_dsl`

##### Current Behaviour

- `response.status_code` is used on line 43
- there's no good unit tests coverage

##### Steps To Reproduce

Run the following script that is already included in the repository"
`./detect-common-errors.sh`

or look at QA Dashboard that is updated daily:
https://fabric8-analytics.github.io/dashboard/dashboard.html

**Comment by GeorgeActon** [comment]
@msrb @yzainee is this being worked on? It is assigned to you

**Comment by yzainee** [comment]
@GeorgeActon I will look into this.

**Comment by yzainee** [comment]
@tisnik https://github.com/fabric8-analytics/fabric8-analytics-data-model/pull/193

**Comment by GeorgeActon** [comment]
@tisnik @yzainee if it is being worked on please change the status to in-progress
