### ISSUE TITLE
Potential Resource Leaks

### ISSUE THREAD

**Issue by tinakurian** [openshiftio/openshift.io#4216]
##### Issue Overview

There are some places in launcher backend where resources are not closed. These resources can be closed using try-with-resources. 

OsioWitClient.java --> deleteSpace(final String spaceId)
HttpClient.java --> parseJson(Function<JsonNode, T> jsonNodeFunction, Response response)
KeycloakIdentityProvider.java --> parseIdentity(Response r)
OpenShiftController.java --> checkNamespace(String namespaceName)
JenkinsConfigParser.java --> parse()
JenkinsConfigParserTest.java --> parseTestXml(String exampleXmlFilename)

##### Expected Behaviour
Expect that these resources are closed. 

##### Current Behaviour
It appears that these resources are not closed.

**Comment by piyush1594** [comment]
@tinakurian Are you seeing any error because of this. If so, can you paste that error? Thanks

**Comment by bartoszmajsak** [comment]
Links to actual codebase on GH would be helpful

**Comment by tinakurian** [comment]
@piyush1594 No, no errors that I know of. The PR can be found here: https://github.com/fabric8-launcher/launcher-backend/pull/512

**Comment by tinakurian** [comment]
@bartoszmajsak 

https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/jenkins/JenkinsConfigParser.java#L80

https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/test/java/io/fabric8/launcher/osio/jenkins/JenkinsConfigParserTest.java#L108

https://github.com/tinakurian/launcher-backend/blob/master/base/src/main/java/io/fabric8/launcher/base/http/HttpClient.java#L98

https://github.com/fabric8-launcher/launcher-backend/blob/master/core/core-impl/src/main/java/io/fabric8/launcher/core/impl/identity/KeycloakIdentityProvider.java#L95
