### ISSUE TITLE
Platform support to display CVEs for transitive dependencies

### ISSUE THREAD

**Issue by yzainee** [openshiftio/openshift.io#4218]
Planner link : https://openshift.io/openshiftio/Openshift_io/plan/detail/446

- [x] Change the template to add another table for transitive dependencies CVEs

- [x] Change the Gemini logic to populate the table for transitive dependencies CVEs

- [x] Modify test cases

- [x] Test

**Comment by GeetikaBatra** [comment]
Covered by this [PR](https://github.com/fabric8-services/fabric8-notification/pull/91)
