### ISSUE TITLE
Changes in newer version notification flow to support transitive dependencies

### ISSUE THREAD

**Issue by yzainee** [openshiftio/openshift.io#4219]
Planner Link: https://openshift.io/openshiftio/Openshift_io/plan/detail/447

- [x] Changes in the graph query to generate the newer versions for transitive dependencies as well

- [x] Platform changes to add additional table for transitive 

- [x] Changes in platform logic to populate the new table

- [x] Test cases / test in platform repository

**Comment by GeetikaBatra** [comment]
covered by this [PR](https://github.com/fabric8-services/fabric8-notification/pull/91)
