### ISSUE TITLE
Can't build any projects

### ISSUE THREAD

**Issue by cctrieloff** [openshiftio/openshift.io#422]
I can get any project to build with pipelines.
on latest jenkins version 3.0.71

Always get the following error in Jenkins console logs

First time build. Skipping changelog.
[Pipeline] echo
Loaded PipelineConfiguration PipelineConfiguration{jobNameToKindMap={}, ciBranchPatterns=[PR-.*], cdBranchPatterns=[master], cdGitHostAndOrganisationToBranchPatterns={}, disableITestsCD=false, disableITestsCI=false}
[Pipeline] echo
Loaded the useDockerSocket flag false
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
Jenkins doesn’t have label maven.cctrieloff_vertxdemo2_master.1

Have 
- updated tenant after deleting Jenkins
- created a new space/ project
- for a redeploy of jenkins
- forced a manual build
- deleted all other pods in OSO to try get more quota.

**Comment by ldimaggi** [comment]
I have not seen this exact error message - Jenkins doesn’t have label maven.cctrieloff_vertxdemo2_master.1 - but have seen issues related to old/stale/dormant Jenkins jobs blocking the creation of builds.

Are you seeing old/existing Jenkins jobs:

![screenshot from 2017-07-26 08-02-29](https://user-images.githubusercontent.com/642621/28620105-8608c54a-71d9-11e7-838e-d3bdc32a6be2.png)

And - have you tried removing the contents of this field?

![screenshot from 2017-07-26 08-02-50](https://user-images.githubusercontent.com/642621/28620127-9a54f2b2-71d9-11e7-904c-91c74a822719.png)

I am not sure if this will have any effect - maybe it's worth a try.

**Comment by jstrachan** [comment]
you could attach your jenkins master pod log? (You should be able to grab it from the -jenkins namespace in the OSO console and find the jenkins pod etc

**Comment by joshuawilson** [comment]
@cctrieloff are you still seeing this? Can you reproduce it?

**Comment by qodfathr** [comment]
This is pretty old and I'm pretty sure fixed long ago. Reopen if you are concerned.

**Comment by gtema** [comment]
Have similar situation
![screenshot_20180119_132155](https://user-images.githubusercontent.com/16461884/35150987-d8ad2c22-fd1c-11e7-9ee1-2aec1f001d0b.png)

Jenkins log:
[jenkins-1.log](https://github.com/openshiftio/openshift.io/files/1646486/jenkins-1.log)

**Comment by sbose78** [comment]
Build made progress after a `reset environment`.
