### ISSUE TITLE
CI jobs are not setup for the fabric8-analytics-notification-scheduler repository

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#4225]
CI jobs needs to be setup for the following repository:

https://github.com/fabric8-analytics/fabric8-analytics-notification-scheduler

##### Expected Behaviour

- All three jobs (tests, pylinter, pydoc checker) are setup.
- All three jobs are run for each PR

##### Current Behaviour

- Nothing is displayed on the GitHub

**Comment by msrb** [comment]
@tisnik I see all those jobs in CI: https://ci.centos.org/view/Devtools/search/?q=devtools-fabric8-analytics-notification-scheduler&Jenkins-Crumb=455bf5cf6008e3dcbf5525b400ede64c

**Comment by miteshvp** [comment]
@tisnik @msrb - is this a bug?

**Comment by msrb** [comment]
It is not in my opinion. The invitation to collaborate was sent so there is nothing we can do now (and I can see it has been accepted already).
