### ISSUE TITLE
Code used during testing has been merged into master branch in fabric8-analytics-notification-scheduler repository

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#4226]
please see:
https://github.com/fabric8-analytics/fabric8-analytics-notification-scheduler/blob/master/f8a_notification/entryscript.py#L70

Either:
- document the purpose of this line - why it was added (demo?), when it will be removed etc
- remove this line so the code on pre-prod/prod would be correct

If you really need this functionality, is not it better to use env. variables setup properly for the OS deployment?

**Comment by msrb** [comment]
Related PR: https://github.com/fabric8-analytics/fabric8-analytics-notification-scheduler/pull/25

**Comment by yzainee** [comment]
@tisnik The code has been reverted already.
https://github.com/fabric8-analytics/fabric8-analytics-notification-scheduler/pull/25
Currently have removed this. We will definitely include it as a env variable when we need this value again.
