### ISSUE TITLE
Research on identifying security patches

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#4228]
**Planner Link:** https://openshift.io/openshiftio/Openshift_io/plan/detail/460

**Comment by CermakM** [comment]
@msrb 
The research results have been presented in this [Jupyter Notebook](https://github.com/fabric8-analytics/fabric8-analytics-POCs/blob/master/cves/security_patches/research_cve_patch_identification.ipynb).

The decision about further approach and acceptance of the proposal is yet to be made.
