### ISSUE TITLE
Repository Name Pattern field is not being automatically cleaned

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#423]
See attached screenshot - the Repository Name Pattern field is not being cleaned - the only repos that should be listed here are the currently active repos.

![screenshot from 2017-07-26 08-02-50](https://user-images.githubusercontent.com/642621/28620797-88ffbbac-71dc-11e7-9ccc-45121ab572a0.png)

**Comment by ldimaggi** [comment]
Is this only an issue for user accounts that were created before a certain date? ~2 weeks ago?

**Comment by joshuawilson** [comment]
@dlabrecq can you take a look at this?
@aslakknutsen @alexeykazakov do you know what is being stored and any requirements on it?

**Comment by aslakknutsen** [comment]
Not been able to reproduce this today.

**Comment by joshuawilson** [comment]
@ldimaggi is this still an issue?

**Comment by ldimaggi** [comment]
Closing - this is no longer a problem.
