### ISSUE TITLE
License "EPL 1.0 is shown as unknown"

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#4237]
##### Issue Overview

The license EPL 1.0 is unknown and because of that recommended stack license cannot be calculate wherever this license is present.

##### Expected Behaviour

The license EPL 1.0 should be known.

##### Current Behaviour

See screenshot:
![screen shot 2018-08-24 at 11 59 38 am](https://user-images.githubusercontent.com/5445560/44568684-7cc43800-a795-11e8-9b78-21b8ea8208d8.png)

##### Steps To Reproduce

1. Generate stack report for the repository: https://github.com/fabric8-launcher/launchpad-backend/

**Comment by sunilk747** [comment]
@rootAvish Can you DM me the stackid for this stackrepot.

**Comment by sunilk747** [comment]
This PR accommodate this missing license.

**Comment by rootAvish** [comment]
@sunilk747 You forgot to link the PR 😄
