### ISSUE TITLE
When working with multiple Che workspaces - moving between workspaces presents user with unclear error

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#424]
If a user creates multiple Che workspaces, it is possible to move between workspaces, but only one can be active at one time. When a user attempts to move from one workspace to another, this error is displayed:

```
Could not start workspace ywtdyvzz. Reason: Start of environment 'default' failed. Error: Pod with deployment name che-ws-4a8n37trdtfqgax5 not found
```

![screenshot from 2017-07-26 08-45-15](https://user-images.githubusercontent.com/642621/28621808-2defb2ae-71e0-11e7-8c6a-8ea4f82f9c51.png)

Usually, the user is able to select "OK" and activate/move to the other Che workspace.

**Comment by ldimaggi** [comment]
From the linked Che issue - https://github.com/redhat-developer/rh-che/issues/217

When a user creates a new workspace but one is already running the correct behaviour should be:
* the old workspace is stopped and then...
* the new workspace is created

**Comment by ibuziuk** [comment]
@ldimaggi are you creating workspaces from "Codebases" or Dashboard ?

```
When a user creates a new workspace but one is already running the correct behaviour should be:
the old workspace is stopped and then...
the new workspace is created
```
This scenario is supposed to work only if workspaces are created via "Codebases"

**Comment by ibuziuk** [comment]
@ldimaggi could you please tell what version of che are you using ?

**Comment by ldimaggi** [comment]
Always in the 'Create Codespace' in the OSIO UI - thanks!

**Comment by ldimaggi** [comment]
![screenshot from 2017-07-26 09-57-41](https://user-images.githubusercontent.com/642621/28624986-e55f0fae-71e8-11e7-9f72-6dc0610e22ba.png)

**Comment by ibuziuk** [comment]
@ldimaggi this is old version, could you please update to the latest one http://central.maven.org/maven2/io/fabric8/online/apps/che/1.0.253/ ?

**Comment by ldimaggi** [comment]
Very nice! The error message is not there with the new (1.0..253) Che.

Closing.

**Comment by ibuziuk** [comment]
@ldimaggi awesome! thanks for verification
