### ISSUE TITLE
"Not correct pom" error in effective pom generation

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#4244]
While generating stack report for the repository https://github.com/alibaba/Sentinel using VSCode fabric8 services extension, the error "Not correct pom" was observed during the effective pom generation step.

/cc @sara-02

**Comment by stevengutz** [comment]
@samuzzal-choudhury @GeorgeActon Putting priority back since defects have to have one. 

Since there is no description here, I don't see how this is justified as a SEV2.  What is the major system failure here?

**Comment by samuzzal-choudhury** [comment]
@stevengutz Added a description. The system failed to generate an application stack report for a real-world application.

**Comment by rootAvish** [comment]
@samuzzal-choudhury I'm not getting this error on my end.

**Comment by invincibleJai** [comment]
Thanks @rootAvish closing it.
