### ISSUE TITLE
Effective POM generation taking too long

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#4245]
For the repository:https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin, effective pom generation took well over five-ten minutes. Can be a possible bandwidth issue.

/cc @GeetikaBatra Might want to add more details here.

Comments:
https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/144#issuecomment-414143485

https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/144#issuecomment-416173998

**Comment by GeetikaBatra** [comment]
@miteshvp, on it

**Comment by GeetikaBatra** [comment]
@miteshvp, It didn't take that long, but the insights are zero.


![screenshot from 2018-09-26 10-19-19](https://user-images.githubusercontent.com/8664238/46057887-a518cb00-c175-11e8-9c59-e75ce08a3f17.png)

**Comment by GeetikaBatra** [comment]
Also, one more observation that @invincibleJai brought to my notice is that if we first time open this project in vscode, it takes around 7 minutes to run.
