### ISSUE TITLE
The thumbs up and thumbs down feedback buttons do not work

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#4247]
The buttons have no feedback, not sure whether they're really sending any feedback either. Bug with http://github.com/fabric8-analytics/fabric8-analytics-stack-report-ui

**Comment by stevengutz** [comment]
This isn't a SEV2 since it's just a minor usage issue rather than a failure of any sort

**Comment by invincibleJai** [comment]
It has been fixed, hence closing.
