### ISSUE TITLE
Current status of Che workspaces not reliably reflected  in OSIO UI

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#425]
Steps to recreate:
* Created 3 new apps (Vert.X, Spring Boot, Spring Boot Healthcheck
* Created a new Che workspace for each
* As expected - only (1) workspace is active at one time

However - the workspace that is listed as active in the OSIO UI:

![screenshot from 2017-07-26 08-43-30](https://user-images.githubusercontent.com/642621/28621987-d4f6c15a-71e0-11e7-914d-273c5680aae5.png)

Is not the active workspace:

![screenshot from 2017-07-26 08-43-51](https://user-images.githubusercontent.com/642621/28621994-e053e5e6-71e0-11e7-93d5-27433682cec8.png)

**Comment by ldimaggi** [comment]
Also - note that while these 2 workspaces were created - the existence of the workspaces is not reflected in the OSIO UI - and the user is prompted to create them:

![screenshot from 2017-07-26 08-43-30](https://user-images.githubusercontent.com/642621/28622229-cc003120-71e1-11e7-9570-a05747a72892.png)

**Comment by ldimaggi** [comment]
Followup:

* Created one new workspace - after the workspace is up and running - the running state is not reflected in the OSIO UI:

![screenshot from 2017-07-26 09-29-33](https://user-images.githubusercontent.com/642621/28623832-1fd0cea6-71e5-11e7-9480-f08d407c0b8f.png)
![screenshot from 2017-07-26 09-29-10](https://user-images.githubusercontent.com/642621/28623833-1fde2754-71e5-11e7-8809-969b5d678108.png)
![screenshot from 2017-07-26 09-28-53](https://user-images.githubusercontent.com/642621/28623834-20011c46-71e5-11e7-8f66-050dd47665cd.png)

**Comment by ldimaggi** [comment]
The user can easily get into a state where there extra/unneeded workspaces are created:

![screenshot from 2017-07-26 10-24-38](https://user-images.githubusercontent.com/642621/28627223-2c068170-71ef-11e7-9259-0f84aa2a60c5.png)
![screenshot from 2017-07-26 10-24-22](https://user-images.githubusercontent.com/642621/28627224-2c21d33a-71ef-11e7-8e9d-0fa4f770af10.png)

**Comment by l0rd** [comment]
Removing label `area/che` because related to the codebase
Related to https://github.com/openshiftio/openshift.io/issues/514

**Comment by l0rd** [comment]
@ldimaggi that should be fixed now. Can we close it?

**Comment by ldimaggi** [comment]
No longer a bug - closing.
