### ISSUE TITLE
Stack report failure when there is a folder name with a space

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#4250]
_From @rootAvish on August 24, 2018 6:46_

Stack analysis fails to generate stack report when there is a space in the folder name anywhere in the directory structure.

_Original issue: fabric8-analytics/fabric8-analytics-vscode-extension#153_

**Comment by stevengutz** [comment]
@samuzzal-choudhury I don't think this fits the criteria for a SEV2.  It's not a failure in a major feature.  This is probably a SEV3

**Comment by samuzzal-choudhury** [comment]
@invincibleJai can this be closed?

**Comment by invincibleJai** [comment]
yes associated PR https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/157

Closing it.
