### ISSUE TITLE
Analysis stuck on "generating application stack report"

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#4251]
_From @rootAvish on August 24, 2018 6:47_

While trying out stack report generation with the VSCode extension for the repository https://github.com/codecentric/spring-boot-admin, @ravsa @sunilk747 observed that the application's stack analysis got stuck with the message "generating application stack report" on the VSCode status bar.

_Original issue: fabric8-analytics/fabric8-analytics-vscode-extension#154_

**Comment by samuzzal-choudhury** [comment]
_From @invincibleJai on August 24, 2018 8:38_

The challenge here with `trigger stack analysis at workspace level` as above repo has both `pom.xml` and `package.json` which we don't support multiple ecosystems as of now. 

To start with an ideal approach would be to check for root level pom, if any consider it as maven project and proceed.

NOTE: User can still trigger stack analysis on particular manifest file be it pom.xml, package.json.

cc @samuzzal-choudhury @miteshvp any inputs/suggestions.

**Comment by samuzzal-choudhury** [comment]
_From @miteshvp on August 25, 2018 6:23_

@invincibleJai - can we based on the filename, be able to generate either effective pom or npm list? Generally speaking, we will know in advance what are the supported manifest filename, and based on that, we come up with an approach? Would that be too complicated? Then, whatever approach you suggested also looks ok to me, but we may loose to generate stack report for package json

**Comment by samuzzal-choudhury** [comment]
_From @invincibleJai on August 27, 2018 5:36_

Sure @miteshvp I agree we need to support `package.json` as well in this scenario we'll discuss it and take it as the enhancement. For time  I feel we can have my approach.

**Comment by samuzzal-choudhury** [comment]
@invincibleJai can we close this?

**Comment by invincibleJai** [comment]
yes associated PR https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/157

Closing it.
