### ISSUE TITLE
In Planner, incorrect user name is reported in email notifications for work item updates

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#4257]
Steps to recreate:
* Create a new Planner workitem
* Assign more than one ~owner~ assignee to the workitem
* Edit the workitem description
* Observe that the email notification reports the incorrect username:

![screenshot from 2018-08-27 15-17-49](https://user-images.githubusercontent.com/642621/44681046-704a1480-aa0d-11e8-8438-88d312c79d25.png)

![screenshot from 2018-08-27 15-18-08](https://user-images.githubusercontent.com/642621/44681047-704a1480-aa0d-11e8-8c66-2f75120d01fb.png)

**Comment by aptmac** [comment]
similar https://github.com/openshiftio/openshift.io/issues/3719 ?

**Comment by nimishamukherjee** [comment]
@jarifibrahim can you please do an initial investigation on this.

**Comment by jarifibrahim** [comment]
>@jarifibrahim can you please do an initial investigation on this.

Yes @nimishamukherjee . Thank you

**Comment by jarifibrahim** [comment]
>similar #3719 ?

Yes, it's a duplicate of https://github.com/openshiftio/openshift.io/issues/3719

**Comment by aptmac** [comment]
closed as duplicate of https://github.com/openshiftio/openshift.io/issues/3719
