### ISSUE TITLE
Che: git commit dialog does not auto-check changed files

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#426]
Though both files changed, it seems to randomly auto-check one or the other file
https://screencast.com/t/JHxMZhCS

**Comment by bmicklea** [comment]
Adding as P1 since it's a very visible part of the workshop path.

**Comment by burrsutter** [comment]
This one could be a lack of understanding on my part.  Now that I have used this dialog a dozen times, it seems to check the file that is current in view/focus in the editor.  The logic being that you only wish to commit your actively edited file, not all your files as those might be in separate commits.   If this behavior was intentional then we should keep it :-)

**Comment by bmicklea** [comment]
It's intentional. If you click on the package and do the commit it'll commit any changes to files in the package. If you select the project root it'll commit everything.
