### ISSUE TITLE
Column separators in Planner are not aligned

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#4261]
Observe the following in the Planner backlog display - note the column separators:

![screenshot from 2018-08-27 22-43-10](https://user-images.githubusercontent.com/642621/44728582-dfc21180-aaaa-11e8-96fa-b38f1fac2d7b.png)

**Comment by aptmac** [comment]
similiar: https://github.com/openshiftio/openshift.io/issues/4241

**Comment by aptmac** [comment]
This should be fixed once https://github.com/fabric8-ui/fabric8-ui/commit/c5c2a6168943aad1f86eec278b5bd806de932c74 hits production. It contains a commit (https://github.com/fabric8-ui/fabric8-planner/pull/2759) that fixes the alignment - the table looks okay to me when running local fabric8-ui.

**Comment by stevengutz** [comment]
Changing this to SEV2.  Annoying but hardly severe

**Comment by aptmac** [comment]
fixed in prod after planner update
