### ISSUE TITLE
Unknown licenses in stack report

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#4264]
##### Issue Overview

Stack report generated from VS Code shows some unknown licenses for https://github.com/jvm-operators/abstract-operator. 

Dependency name: `org.reflections:reflections:0.9.11`
License(s) used: The New BSD License, WTFPL

##### Expected Behaviour

Well known licenses are recognized by license analysis services.

##### Current Behaviour

License analysis service doesn't recognize BSD and WTFPL license.

**Comment by stevengutz** [comment]
This looks like a duplicate of https://github.com/openshiftio/openshift.io/issues/4265

**Comment by samuzzal-choudhury** [comment]
@sunilk747 PTAL

**Comment by sunilk747** [comment]
This PR - https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/pull/131 fixes this issue.
