### ISSUE TITLE
Recommended license shown as Unknown when declared license is not found for a package

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#4265]
## Issue Overview
When for a analyzed package no declared license is found from graph database the recommended license is shown as unknown.

## Expected behaviour
Is should be shown as `None` with some appropriate message.

## Current Behaviour
![scsc](https://user-images.githubusercontent.com/7105965/44776653-3bb59480-ab96-11e8-89e6-5a7074ca73c6.png)

### Steps to reproduce
Generate stack report for https://github.com/apache/incubator-dubbo/tree/master/dubbo-cluster

cc @rootAvish @samuzzal-choudhury

**Comment by miteshvp** [comment]
@sunilk747 - can you PTAL?

**Comment by sunilk747** [comment]
We can close this issue. I addressed this issue in my last PR.
