### ISSUE TITLE
Different response for same pom.xml on prod and prod-preview

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#4266]
## Issue Overview
Different response for same pom on prod and prod-preview. In response from prod there is stack level license but on prod-preview it's showing one of the license as unknown.

prod-preview response - https://gist.github.com/sunilk747/d134b3ef6992bc4600fa029d9a3e0bcb

prod response - https://gist.github.com/sunilk747/2b4beca149811452d453ee7a1c26c739

### Steps to reproduce
Perform stack analyses call on this pom :- https://github.com/iluwatar/java-design-patterns/blob/master/strategy/pom.xml

cc @miteshvp

**Comment by stevengutz** [comment]
This looks like a duplicate of https://github.com/openshiftio/openshift.io/issues/4265

**Comment by sunilk747** [comment]
@stevengutz No. Both the issues are different.

**Comment by msrb** [comment]
I think this could be because the environments don't share data and staging is basically a subset of prod?

**Comment by miteshvp** [comment]
@sunilk747 License in prod-preview has a `white-space`. Maybe license analysis code should strip the license fields while evaluating the license. Plus, this looks to be a case where data needs correction in staging. 
On prod-preview
```
"distinct_licenses": [
                    " GNU Lesser General Public License",
                    "MIT License",
                    "Eclipse Public License - v 1.0"
                ]
```
On Prod
```
"distinct_licenses": [
                    "GNU Lesser General Public License",
                    "MIT License",
                    "Eclipse Public License - v 1.0"
                ]
```

**Comment by miteshvp** [comment]
Data corruption is fixed in staging. @sunilk747 please make sure to handle such whitespaces at the code level

**Comment by sunilk747** [comment]
Thanks @miteshvp . I will do the required changes to handle such cases in future.
