### ISSUE TITLE
There should be a upper limit for story points and effort field of workitem in planner

### ISSUE THREAD

**Issue by DhritiShikhar** [openshiftio/openshift.io#4267]
##### Expected Behaviour

1. There should be an upper limit to story points and effort fields of workitem. Such large values do not make much sense for story points. 

##### Steps To Reproduce

1. Enter a large float value in story point text area

![screenshot_2018-08-29_17-16-28](https://user-images.githubusercontent.com/6303309/44785789-b4751a80-abaf-11e8-848b-cc09fadf6d20.png)

2. Save the value

![screenshot_2018-08-29_17-16-41](https://user-images.githubusercontent.com/6303309/44785797-bb039200-abaf-11e8-99b4-b0120e628dd6.png)

**Comment by nimishamukherjee** [comment]
@RanjithRV @stevengutz what would be the upper limit for story points and efforts?
cc @openshiftio/uxd-team

**Comment by serenamarie125** [comment]
Looks like JIRA tops out at 1e+14 for story points.  @stevengutz should we do the same here ?

**Comment by joshuawilson** [comment]
Who would ever need `100000000000` story points? That is 100 Billion. :-)

**Comment by abhinandan13jan** [comment]
After the PR (https://github.com/fabric8-ui/fabric8-planner/pull/2816), the input limit for all float fields have become -2^32 to 2^32. As story-point and Effort are float fields, this range will apply to these fields as well.

**Comment by joshuawilson** [comment]
That is a good point, we now have the javascript limit on the field. However, I think it would be reasonable to limit it further. 

Easier to user, easier to test.

**Comment by serenamarie125** [comment]
Based on a conversation held on 2019-Jan-04 including Dev, PM and UX, the UX team will not be providing support for planner items. Closing this issue since this was solely around gathering requirements.

**Comment by joshuawilson** [comment]
Fixed in  fabric8-ui/fabric8-planner#2816
