### ISSUE TITLE
After logging in to the OSIO for the first time after user registration the UI flow freezes at _gettingstarted page

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#4268]
##### Issue Overview

Recently I registered 2 RHD accounts and signed up to the `starter-us-east-2a` cluster. After verifying email and receiving the 'Welcome to OpenShift.io' email indicating that the OSIO environment is ready I wanted to log in to OSIO to continue with linking the GH account. But the page freezes at empty `https://openshift.io/_gettingstarted` page.

##### Expected Behaviour

After logging in to the OSIO for the first time I expected I should link the github account.

##### Current Behaviour

The page freezes at empty `https://openshift.io/_gettingstarted` page.
In the browser history there are several 401 Errors:
![image](https://user-images.githubusercontent.com/3263627/44787607-e37f9200-ab97-11e8-82cc-e90a862f7a14.png)

##### Steps To Reproduce

1. Register RHD account
2. Sign up to the `start-us-east-2a` cluster at `https://manage.openshift.com/openshiftio?cluster=starter-us-east-2a`
3. Log in to `http://openshift.io/`

##### Additional Information

The new RHD accounts:

* `osio-ci+boost2@redhat.com`
* `osio-ci+boost3@redhat.com`

**Comment by sbose78** [comment]
- After logging in, this is the behaviour https://github.com/openshiftio/openshift.io/issues/4030#issuecomment-406325715
- Also, as a suggestion: you could use 1a or 1b cluster, capacity-wise they are doing well.

**Comment by pmacik** [comment]
> Also, as a suggestion: you could use 1a or 1b cluster, capacity-wise they are doing well.

Thanks for the suggestion, but our other account `osio-ci+booster1@redhat.com` is already on the 2a cluster, and we want the group to stick together.

**Comment by rohitkrai03** [comment]
@sbose78 This seems to be related to latest changes for `HttpClient`.

**Comment by sbose78** [comment]
Some observations on the issue:

1) On the getting started page: the authorization header is being passed while fetching the token - and therefore, we get the right response header. ( which is why my `/_gettingStarted` page works fine where account is connected, but not for Florent)

2) Fetching the token doesn't work in the Settings page. And there, I've noticed that the authorization header isn't being passed.

3) Seems like the same service as (2) also does all the account linking calls - which again because of no authorization header was being passed.

**Comment by jiekang** [comment]
I posted this on a related PR, but posting here for visibility:

The cause of this is primarily around the use of `HttpClient` over `Http`. The `fabric8-ui` application provides a custom `Http` client in `app.module.ts` first via

```
    {
      provide: Http,
      useClass: Fabric8UIHttpService
    },
```

and then in the same file, afterwards via

```
    HttpService,
```

The `HttpService` comes from `ngx-login-client` and appends an auth header for any request that it touches. The `Fabric8UIHttpService` routes to that for certain requests via

```
    if (urlStr.startsWith(this.witApiUrl) || urlStr.startsWith(this.ssoApiUrl) ||  urlStr.startsWith(this.authApiUrl)) {
      // Only use the HttpService from ngx-login-client for requests to certain endpoints
      return this.httpService.request(url, options);
    }
```

I assume any upgrades from `Http` to `HttpClient` will be affected by the missing custom service and we need to watch out for it. We also may want to look at replicating what `Fabric8UIHttpService` does for a `HttpClient` instance. The deployments API just sets the auth header itself regardless, so I think the change here is fine too.
