### ISSUE TITLE
Win10, Edge: was blank, then crashes on openshift.io

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#427]
https://www.screencast.com/t/F8Ekdi7c

I tried visiting openshift.io via Edge and first it went blank after login and then it would crash and not come up.  See video above.

I never use Edge (or Win10 for that matter) so I have no idea where to find the inspector nor logs

**Comment by ldimaggi** [comment]
I am seeing the blank screen, but not the crash, with Edge version 38.14393.1066.0 on Windows 10.

**Comment by qodfathr** [comment]
Closing in favor of #2018.
