### ISSUE TITLE
Unable to delete some Che workspaces from Che dashboard

### ISSUE THREAD

**Issue by benoitf** [openshiftio/openshift.io#4271]
##### Issue Overview

Unable to delete che workspaces.

##### Expected Behaviour

I should be able to delete my workspaces

##### Current Behaviour

I have errors when trying to remove some workspaces

##### Steps To Reproduce

Go into dashboard and delete workspaces
![removal-workspaces-failure](https://user-images.githubusercontent.com/436777/44843005-90fdae80-ac47-11e8-80a0-e00fc18030b1.gif)

##### Additional Information

Anything relevant to help us resolving the problem, such as your OSIO user name, email and error message you see on the screen. 

username: fbenoit-1 / Red Hat

**Comment by ibuziuk** [comment]
related rh-che issue - https://github.com/redhat-developer/rh-che/issues/728

**Comment by benoitf** [comment]
The good news is that I was able to remove them with the latest update of Che !

**Comment by ibuziuk** [comment]
ah, awesome!
