### ISSUE TITLE
Kubernetes authorization checking API enhancement

### ISSUE THREAD

**Issue by stooke** [openshiftio/openshift.io#4272]
This issue covers an enhancement to WIT (and eventually to UI) to optionally check k8s permissions when for k8s objects.

The basic proposal is to add a new optional parameter to several endpoints (currently 'qp=true') that causes WIT to interrogate k8s permissions for an object and return those permissions as an array of valid HTTP request types for that object.
The WIT sub-issue is #2268 (Provide optional checking of k8s permissions on a space or deployment).

**Comment by alexeykazakov** [comment]
Outdated. Closing.
