### ISSUE TITLE
Planner can get stuck in a loading state when visiting without a direct url

### ISSUE THREAD

**Issue by aptmac** [openshiftio/openshift.io#4274]
##### Issue Overview

Trying to visit the planner without a direct url link may cause the planner to load forever. I've currently tried `refresh -> home -> space -> planner` and `refresh -> space -> planner` and they both cause the planner to get stuck in a loading state. However, using a url to go straight to the planner will display it as normal.

##### Expected Behaviour

The planner should load work items and display the board.

##### Current Behaviour

The planner can get stuck in a loading state.

##### Steps To Reproduce

1. Accessing the planner by going from home -> space -> planner seems to result in a loading state
![planner-stuck](https://user-images.githubusercontent.com/10425301/44860351-fe0f4500-ac43-11e8-87b4-4e80fd549072.gif)

There are also a lot of warning messages in the console.
![console warnings](https://user-images.githubusercontent.com/10425301/44860395-0ff0e800-ac44-11e8-8940-20b73b14f17b.png)

##### Additional Information

It seems that accessing the planner by a URL doesn't cause this issue, and the planner is viewable as normal.
![planner-loading](https://user-images.githubusercontent.com/10425301/44860509-534b5680-ac44-11e8-9a2c-ce198df5f5a2.gif)

**Comment by joshuawilson** [comment]
Are you still getting this? I can not reproduce this.

**Comment by aptmac** [comment]
No I haven't seen this for at least a few weeks, this can be re-opened if it occurs again in the future.
