### ISSUE TITLE
[RFE] Implement user OpenShift reset/reprovision

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#428]
related to https://github.com/fabric8-services/fabric8-tenant/issues/75

**Comment by ldimaggi** [comment]
What is needed is a simple way for a user to delete his/her projects in OpenShift, and then recreate them so that the user account is restored to clean provisioned state.

**Comment by burrsutter** [comment]
It is fairly common to find lots of "extra" stuff in an end-user's OSO account.  This feature needs to clearly warn the end-user he is taking the nuclear option but by default almost all early OSIO end-users will just wish to "start over" in a pristine newly provisioned state.   Some examples of "extra" stuff:
1) Sometimes an extra Jenkins shows up in the user namespace
2) Sometimes lots of extra dead zombie Jenkins slaves are clogging things up
3) Often rolling updates fail in either -stage or -run and are in limbo, clogging things up (note: this is out of quota, just hung/stuck state)
4) Often the end-user is out of quota on -stage and -run therefore additional pipeline runs fail

**Comment by burrsutter** [comment]
related to 440

**Comment by joshuawilson** [comment]
Do we want the user to be able to do this themselves with a button?
