### ISSUE TITLE
jenkins image generation repositories: write CI/CD pipeline and move to CICO

### ISSUE THREAD

**Issue by sthaha** [openshiftio/openshift.io#4286]
Planner: https://openshift.io/openshiftio/Openshift_io/plan/detail/305

**Comment by chmouel** [comment]
Submitted : 

https://github.com/fabric8-jenkins/jenkins-openshift-base/pull/40
https://github.com/openshiftio/openshiftio-cico-jobs/pull/792
https://github.com/openshiftio/openshiftio-cico-jobs/pull/793
https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2284

**Comment by chmouel** [comment]
jenkins-openshift-base move to CiCO is fully working for CI and CD and updateDownstream shenanigans thing (which is useful i think)

Doing now s2i-config, PR here: https://github.com/fabric8io/openshift-jenkins-s2i-config/pull/199

**Comment by chmouel** [comment]
Blocked by https://github.com/fabric8-services/fabric8-tenant/pull/634 until it is merged

**Comment by sthaha** [comment]
@chmouel isn't this closed now?

**Comment by chmouel** [comment]
yup! thanks,
