### ISSUE TITLE
Link sub-menu unable to search for work item titles with special characters

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#4288]
##### Issue Overview
On Prod-preview:

Link sub-menu unable to search for work item titles with special characters. So for example, there is a work item with title __'planner wi1'__, and the user types in the string _'planner_ in the search bar, the planner fails to look up the work item. However, if you type the exact same string along with the ending quote, the work item is found e.g. _'planner wi1'_.

Typing without the quote works. The problem lies while searching with the quotes.

##### Expected Behaviour
Work items should be searchable, with or without quotes.

##### Current Behaviour
Typing without the quote works. The problem lies while searching with the quotes.

##### Steps To Reproduce

1. Create a work item with title __'planner wi1'__
2. Create another work item with any title, say hello
3. In the quick-preview screen of work item _hello_, create a new link and do as mentioned in the description

Gif is here:

https://drive.google.com/open?id=13UfhY80bxTF4PkR4Nk55PUc1PSaDS0si

**Comment by rgarg1** [comment]
The search failure in Link section is also resulting in multiple sentry errors like this: https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-wit/issues/2320/

**Comment by kwk** [comment]
@rgarg1 I'm trying to address this in https://github.com/fabric8-services/fabric8-wit/pull/2272

**Comment by kwk** [comment]
@rgarg1 the bug is fixed in prod-preview now. Once we get an approval from UI to update prod it should be fixed in prod as well.

**Comment by rgarg1** [comment]
@kwk Issue is verified to be fixed in prod-preview.

**Comment by kwk** [comment]
> @kwk Issue is verified to be fixed in prod-preview.

@rgarg1 I'm talking about this issue which has no information: https://github.com/openshiftio/openshift.io/issues/4309

**Comment by joshuawilson** [comment]
Can we close this?

**Comment by kwk** [comment]
@rgarg1 here's the visual proof that searching from the link section on production works fine:

## Search without quotes:
![bildschirmfoto von 2018-10-29 10-14-07](https://user-images.githubusercontent.com/193408/47640273-84bca180-db63-11e8-982e-ad1f6fef6867.png)

## Search with quotes:
![bildschirmfoto von 2018-10-29 10-14-21](https://user-images.githubusercontent.com/193408/47640323-a0c04300-db63-11e8-8484-1fdf82dcb598.png)

@sanbornsen I noticed that the same item is found when searching but somehow it is only rendered in bold for the search without a quote in it. Is this on purpose?

**Comment by rgarg1** [comment]
@kwk I can confirm that the issue is fixed on prod as well.

And, I also observed the issue that you noticed, regarding the search results not displaying in bold.

**Comment by joshuawilson** [comment]
Can we close this since it is fixed. And open a new issue regarding the boldness?

**Comment by rgarg1** [comment]
@joshuawilson Yes this could be closed now.
