### ISSUE TITLE
Seeing inconsistent behavior related to pipeline animation stopped working today - not reproducible

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#429]
Since about noon on July 26, I have been seeing (3) varieties of behavior exhibited by pipelines:

1) Normal behavior - Creating a new app/quickstart results in the successful creation and operation of the pipeline. The pipeline is created and shown in both the OSIO UI and the OpenShift online console. The pipeline starts automatically and runs through to successful deployment to stage and run from the OSIO UI.

2) The pipeline is created, but it is only shown in the OpenShift online console. It is not visible in the OSIO UI. The pipeline starts automatically and runs through to successful deployment to stage and run from the OpenShift online console.

3) The pipeline is created and shown in both the OSIO UI and the OpenShift online console. The pipeline is not automatically started. The pipeline can be started manually from either the OSIO UI or the OpenShift online console and it runs through to successful deployment to stage and run.

**Comment by ldimaggi** [comment]
Jenkins pod log attached:
```
Jul 26, 2017 4:38:54 PM io.fabric8.kubernetes.client.utils.InputStreamPumper run
--
  | SEVERE: Error while pumping stream.
  | java.io.IOException: Pipe broken
```

**Comment by ldimaggi** [comment]
[jenkins_pod_log.txt](https://github.com/openshiftio/openshift.io/files/1177392/jenkins_pod_log.txt)

**Comment by jstrachan** [comment]
I can't reproduce - whenever I create an app I see the pipeline animate in the OSIO console

**Comment by ldimaggi** [comment]
Just saw this variation on this:

![screenshot from 2017-07-26 13-02-53](https://user-images.githubusercontent.com/642621/28633800-fa25bd74-7202-11e7-9e50-5bc7940ef874.png)
![screenshot from 2017-07-26 13-02-31](https://user-images.githubusercontent.com/642621/28633801-fa326ff6-7202-11e7-8872-32baa75447fd.png)

**Comment by ldimaggi** [comment]
Failed for 3 consecutive tries - working now.

**Comment by ldimaggi** [comment]
Steps to recreate:
* Create new app - Vert.X basic
* Observe the pipeline in OpenShift online, but not in OSIO

![screenshot from 2017-07-26 12-36-45](https://user-images.githubusercontent.com/642621/28632994-4a153b14-7200-11e7-9002-236c88f31558.png)

![screenshot from 2017-07-26 12-37-26](https://user-images.githubusercontent.com/642621/28633005-5476aad4-7200-11e7-9309-a9dacc91d6e2.png)

**Comment by jstrachan** [comment]
this sounds like some kind of JavaScript / network issue. The next time you can reproduce this any chance you could:
* open the `JavaScript console`, anything recent in Red? You could try navigate to the `Codebases` page, clear the log and go back to the `Pipelines` page - anything  red?
* open the` Networks` tab, again go to `Codebases`, clear the network log, then go back to `Pipelines`. Any requests red? Also can you filter by 'builds' and 'buildconfigs' in the filter box on the `Network` tab and look at the last GET request for those 2 resources; what was the status code and what was the response? 

I'm guessing this is some temporary network glitch where your browser gets back garbage?

**Comment by bmicklea** [comment]
FWIW I'm no longer seeing this issue.

**Comment by joshuawilson** [comment]
@ldimaggi can we close or can you reproduce this?

**Comment by ldimaggi** [comment]
This is no longer an issue - closing.
