### ISSUE TITLE
Pipeline option in select option is disappear after authorize GitHub from app creation flow.

### ISSUE THREAD

**Issue by vikram-raj** [openshiftio/openshift.io#4295]
##### Issue Overview
Pipeline options in select pipeline section disappears when the user connects GitHub account from app creation flow.

##### Expected Behaviour
Pipeline option in select pipeline section should not disappear.

##### Current Behaviour
Pipeline option in select pipeline section disappears.

![screenshot from 2018-09-05 11-20-06](https://user-images.githubusercontent.com/2561818/45073615-aff3b900-b0fd-11e8-8e76-a7eba8362a0e.png)

##### Steps To Reproduce

1. Revoke your OpenShift.io account from github.
2. Go to app creation -> select booster -> select pipeline -> Login and Authorize github account.
When you come back to openshift.io after authorization you will see the pipeline option in select pipeline is dissappear.

**Comment by joshuawilson** [comment]
@vikram-raj is this fixed?

**Comment by vikram-raj** [comment]
This issue has been fixed and on prod.
