### ISSUE TITLE
Fields are getting duplicated in quick preview

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#4296]
Steps:
Login to OSIO
Open home page
Click on recent space
Now click on plan tab
Planner get stuck in loading state
Now refresh and 
Try clicking on any workitem to open quickpreview, fields are getting duplicated in quick preview

space: -https://prod-preview.openshift.io/rbajpai-preview/test_space/plan?q=(typegroup.name:Scenarios)&showTree=true

**Comment by jarifibrahim** [comment]
@Raunak1203 can you please verify it again? fabric8-ui was pushed to production 3 days ago and it should have the fix for this issue.
