### ISSUE TITLE
WIT: Integration tests fail randomly

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#4299]
Both master and PR jobs started to fail very often due to various integration test failures.
Most common one is: 
`level=panic msg="failed to populate the database with common types" err="pq: duplicate key value violates unique constraint \"work_item_link_categories_pkey\""`
For example - https://ci.centos.org/view/Devtools/job/devtools-fabric8-wit-build-master/537/console

I tried to run tests locally (make test-integration-no-coverage) many times (+10) and it failed every time! It failed on different tests though but all of them seems to be related to some test data leftovers in DB. I also got the same test failure (duplicate key value violates unique constraint) as we see in Jenkins. So, it's not a Jenkins problem for sure. I removed/re-built/re-start f8-wit-db image/container and cleaned go test cache before every attempt to make sure there is no leftovers from the previous run.

My guess would be that it's caused by test data not being cleaned up properly (or asynchronously - race condition).

@kwk could you please take a look?

**Comment by jarifibrahim** [comment]
I don't think the failures are because of leftover test data. I ran the following script and tests still failed. 
` docker rm -f $(docker ps -aq)` removes all the containers.
```sh
for run in {1..5}
do
    docker rm -f $(docker ps -aq) \
    && docker-compose up -d db-auth auth db \
    && make test-integration-no-coverage
done > result.txt
```

**Comment by kwk** [comment]
@jarifibrahim it can still be left over test data that exists and isn't erased.

**Comment by jarifibrahim** [comment]
>@jarifibrahim it can still be left over test data that exists and isn't erased.

@kwk `docker rm ... ` wiped off the container entirely. How can there be test data when the test DB container doesn't exist :confused: ?

**Comment by kwk** [comment]
@jarifibrahim not from a previous execution of the same job but it could be that some tests don't clean up properly and influence other tests.
