### ISSUE TITLE
[nodejs] Improve spawn api

### ISSUE THREAD

**Issue by piyush1594** [openshiftio/openshift.io#4300]
Right now in new pipeline, spawn api looks like 

```
spawn(image: "oc") {
          sh """
              npm --version
              oc version
          """
}
```

Improve it to have the following functionality also

```groovy
spawn image: "oc", command: """
         npm --version
         oc version
 """
```
and

``` groovy
spawn image: "oc", script: "path to file"
```

Planner https://openshift.io/openshiftio/Openshift_io/plan/detail/547

**Comment by sthaha** [comment]
@piyush1594 the empty closure isn't needed .. so I have corrected it

**Comment by piyush1594** [comment]
We are not going with script thing right now, we are only implementing command. If there requirement will come for the script then we will have it.

**Comment by piyush1594** [comment]
Fixed with https://github.com/fabric8io/fabric8-pipeline-library/pull/424
