### ISSUE TITLE
Login is unstable/dashboard doesn't load

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#4302]
##### Issue Overview

Our e2e test for login is unstable

##### Current Behaviour

dashboard is not loaded resulting in

![osio_login_1](https://user-images.githubusercontent.com/445100/45223147-c5601300-b2b6-11e8-99c3-fc9666384bea.png)

or

![osio_login_2](https://user-images.githubusercontent.com/445100/45223155-cb55f400-b2b6-11e8-989f-9080770029ec.png)

##### Steps To Reproduce

1. login to openshift.io
2. wait for dashboard to load

##### Additional Information

reproducible also locally (1 of 5 runs fails with this error)

**Comment by ldimaggi** [comment]
On which cluster are you seeing this?

**Comment by pmacik** [comment]
I saw it, too... at a third attempt. The account is at the `2a` cluster.

**Comment by ldimaggi** [comment]
I am not seeing this on the starter-us-east-2 cluster - are you on 2a?

**Comment by alexeykazakov** [comment]
It's developers.redhat.com issue. Has nothing to do with cluster. I can't reproduce it, so, maybe RHD had some outage... I see a lot of errors in Zabbix regarding RHD status.

**Comment by xcoulon** [comment]
Login works for me this morning. @ppitonak could you check to confirm it works for you too, now ?

**Comment by ppitonak** [comment]
Yes, it seems to be solved now.
