### ISSUE TITLE
Not able to access jenkins.openshift.io

### ISSUE THREAD

**Issue by piyush1594** [openshiftio/openshift.io#4305]
##### Not able to access jenkins.openshift.io

Accessing jenkins.openshift.io throwing 
```
{"Errors":[{"code":"500","detail":"Get http://jenkins-idler:8080/api/idler/status/pgarg-1-jenkins?openshift_api_url=https%3A%2F%2Fapi.starter-us-east-2.openshift.com%2F: dial tcp 172.30.83.238:8080: getsockopt: no route to host"}]}
```

This error is also thrown in between the ongoing build also and no further logs get printed. This error goes after 3-4 times of refresh. But after some time happens again.

##### Expected Behaviour

should be able to access jenkins.openshift.io

##### Current Behaviour

not able to access jenkins.openshift.io

##### Steps To Reproduce

1. start a build
2. either do `view logs` or go to `jenkins.openshift.io`

##### Additional Information

![jenkins-idler](https://user-images.githubusercontent.com/19270240/45292187-09028900-b512-11e8-9cb0-f27c7348ce32.png)

username: pgarg-1
environment: prod
cluster: 2
jenkins-version 4.0.106

**Comment by piyush1594** [comment]
I am not anymore seeing this issue now.

**Comment by kishansagathiya** [comment]
> I am not anymore seeing this issue now.

@piyush1594 Let's close this. Will reopen if this happens again.

**Comment by piyush1594** [comment]
Yup, not seeing it now. Closing this. Thanks
