### ISSUE TITLE
Che: scl command not found

### ISSUE THREAD

**Issue by burrzinga** [openshiftio/openshift.io#432]
I tried to use the Forge Wizard to Import this project
https://github.com/burrzinga/07-vertx-paint
and that seemingly worked 
and then Create Workspace and that seemingly worked, but the project was not imported.  So I manually imported it.  And tried to add the command to run it
https://screencast.com/t/K4azI0rUp9E

**Comment by l0rd** [comment]
Will be fixed by https://github.com/redhat-developer/rh-che/issues/147

**Comment by ibuziuk** [comment]
@l0rd should we close this one ?

**Comment by l0rd** [comment]
@ibuziuk yes I've just verified that is not reproducible anymore
