### ISSUE TITLE
Update the upstream nodejs boosters with the application.yaml as required

### ISSUE THREAD

**Issue by piyush1594** [openshiftio/openshift.io#4321]
https://openshift.io/openshiftio/Openshift_io/plan/detail/580

**Comment by bartoszmajsak** [comment]
I'm not really sure what exactly is the goal of this task, but @piyush1594 please get in touch with @gastaldi and his team about that - best through their mailing list https://groups.google.com/forum/#!topic/fabric8-launcher, as they already have such descriptor files in place.

**Comment by piyush1594** [comment]
Hey, @bartoszmajsak Thanks for raising the concern. The title of the issue was not clear and I have updated it. This issue is regarding the nodejs boosters and I have already raised the PR https://github.com/bucharest-gold/nodejs-health-check/pull/124 here. Hope this clarifies. Thanks

**Comment by piyush1594** [comment]
PR merged, closing this.

**Comment by piyush1594** [comment]
Boosters to be updated
 - [ ] https://github.com/bucharest-gold/nodejs-rest-http-redhat (master)
 - [ ] https://github.com/bucharest-gold/nodejs-rest-http-redhat (8.x)
 - [ ] https://github.com/bucharest-gold/nodejs-health-check-redhat (master)
 - [ ] https://github.com/bucharest-gold/nodejs-health-check-redhat (8.x)

**Comment by piyush1594** [comment]
PR's

- https://github.com/bucharest-gold/nodejs-health-check-redhat/pull/50
- https://github.com/bucharest-gold/nodejs-health-check-redhat/pull/51
- https://github.com/bucharest-gold/nodejs-rest-http-redhat/pull/49
- https://github.com/bucharest-gold/nodejs-rest-http-redhat/pull/50

**Comment by piyush1594** [comment]
All the 4 patches merged, closing this.
