### ISSUE TITLE
Cannot import user profile image from GitHub

### ISSUE THREAD

**Issue by sbryzak** [openshiftio/openshift.io#4322]
On the user profile page, clicking the "Import from GitHub" link returns an error, "Unable to Link Image".  Link to GitHub is up to date.

![image](https://user-images.githubusercontent.com/165507/45466735-485eee80-b739-11e8-9102-a956211e959d.png)

**Comment by rohitkrai03** [comment]
@sbryzak I could not reproduce this issue on prod-preview and local. It seems that there is already a fix in place but has not reached prod yet.

**Comment by rohitkrai03** [comment]
This is fixed in prod now. Closing it.
