### ISSUE TITLE
Remove duplicate of spaces

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4325]
There are 2 "spaces" pages available to the user.  Only one of these should exist
<img width="284" alt="screen shot 2018-09-14 at 8 10 08 pm" src="https://user-images.githubusercontent.com/12504403/45580012-4771ae00-b85a-11e8-8b82-2d83d418bcf7.png">

**Comment by serenamarie125** [comment]
Up for internal OSIO UX review before sharing with external stakeholders: https://redhat.invisionapp.com/share/APO2SX65VSZ

FYI @muruGanesan @sdash-redhat @AshishDurgude @parvathyvr @Veethika @sunilmalagi

**Comment by serenamarie125** [comment]
@AshishDurgude @sunilmalagi please be sure to call the entry "Spaces" and use fa-th as the icon  - my initial invision needs to be updated, with the format of the "My Spaces" page.

Please add these mocks to the GDrive as well

**Comment by serenamarie125** [comment]
This illustrates what I was talking about above.
![osio-006](https://user-images.githubusercontent.com/12504403/46328570-1e7d4700-c5d6-11e8-8633-1d18d9d6fd06.png)

**Comment by serenamarie125** [comment]
Please include 3 screens
[1] Home selected, showing Home selected in the drop-down
<img width="771" alt="screen shot 2018-10-02 at 12 03 05 am" src="https://user-images.githubusercontent.com/12504403/46328688-bf6c0200-c5d6-11e8-9115-0c4bc32f33fd.png">

[2] Spaces selected, showing Spaces selected in the drop-down
<img width="776" alt="screen shot 2018-10-02 at 12 02 39 am" src="https://user-images.githubusercontent.com/12504403/46328695-c430b600-c5d6-11e8-90f0-20a8b2ea3da7.png">

[3] The drop-down open showing menu items

**Comment by AshishDurgude** [comment]
Hi @serenamarie125 below is the InVision link for Visuals
https://redhat.invisionapp.com/share/5SODKG576EU

Also, I am attaching a sketch file google drive link below:
https://drive.google.com/open?id=1iYNbi--p1FS8JEaRa0iK80w2WSEiW5Vb

Please review it. Thanks.

**Comment by serenamarie125** [comment]
Very minor change needed - change "Account home" to "Home".  Thanks @AshishDurgude

**Comment by AshishDurgude** [comment]
@serenamarie125 I made changes. 
InVision link: https://redhat.invisionapp.com/share/5SODKG576EU

Google Drive Link: https://drive.google.com/open?id=1UfdMQSUW2FLBJu45eSA9O7iF7Tep9F4b

**Comment by christianvogt** [comment]
dev story: https://openshift.io/openshiftio/Openshift_io/plan/detail/782

**Comment by aptmac** [comment]
@serenamarie125 this issue seems to encompass two parts: the removal of `View all Spaces` and updating the `Spaces` page.

As posted on the OSIO dev story for this issue:

> "Does the removal of `View all spaces` depend on the `spaces` page supporting the new features in the UXD invision?" 

Does the `spaces` page need to be updated before (or at the same time) as the removal of `view all spaces`? Or is it okay to remove the `view all spaces` page and have the `spaces` page be the sole page for the immediate future?

**Comment by rohitkrai03** [comment]
@aptmac Are you working on this? Please assign yourself to planner Work Items that you plan to work on so that we do not duplicate any work.

**Comment by aptmac** [comment]
I can work on this, but wanted to firm up details before I begin.

**Comment by rohitkrai03** [comment]
I think its better to split both of work into separate PRs. The changes in `My Spaces` will need a bit more work that the first part.

**Comment by aptmac** [comment]
I agree, it's listed in the OSIO Planner as being two different issues. My question is does the completion of the new page for Spaces block the story to remove the duplicate pages, or can they be done in any order?

**Comment by rohitkrai03** [comment]
Removing `View All Spaces` page should not be an issue here since that page actually doesn't show all of the spaces user is a collaborator. That APi was added recently in the Auth Service.

**Comment by joshuawilson** [comment]
I would suggest that only one of you work on this and take both tasks since they are related.
