### ISSUE TITLE
Chat with Us should be under Help menu

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4327]
The Chat with Us menu item should be under the Help menu, not the user menu.

**Comment by serenamarie125** [comment]
Note: Need to validate this is ok before moving forward

**Comment by AshishDurgude** [comment]
@serenamarie125 @muruGanesan Here is the invision link:
https://redhat.invisionapp.com/share/9EO4OU7FWAM

please review it. Thanks.

**Comment by serenamarie125** [comment]
![helpmenucontents](https://user-images.githubusercontent.com/12504403/46082295-c7f2b180-c16c-11e8-8a41-e4582bed09a7.png)

**Comment by serenamarie125** [comment]
@joshuawilson @christianvogt can we get this on the dev backlog?  Once confirmed, I'll pull off the UX tags.

**Comment by joshuawilson** [comment]
Add this to the plan at https://openshift.io/openshiftio/Openshift_io/plan/detail/688
