### ISSUE TITLE
NAME column in Codebases page should not be bold

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4328]
NAME column in Codebases page should not be bold

**Comment by AshishDurgude** [comment]
@serenamarie125 @muruGanesan 
Here is the invision link: https://redhat.invisionapp.com/share/K2O4OSTQB5M
please review it. Thanks.

**Comment by muruGanesan** [comment]
@AshishDurgude, I believe the below screen address this issue:
https://redhat.invisionapp.com/share/9EO4OU7FWAM#/320723982_Screen_Shot_2018-09-19_At_11-30-38_AM

**Comment by christianvogt** [comment]
Dev story: https://openshift.io/openshiftio/Openshift_io/plan/detail/780
