### ISSUE TITLE
Collaborators page needs headings and NAME column shouldn't be bold

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4329]
Provide designs for this view:
- include column headings
- NAME column should not be bold
- Data should be in columns

**Comment by christianvogt** [comment]
dev story: https://openshift.io/openshiftio/Openshift_io/plan/detail/781

**Comment by christianvogt** [comment]
@serenamarie125 

We currently display the full name adjacent to the user name. The full name is bold to make a distinction between the two pieces of information. The ask is the remove the bold which makes the full name and username read as if they are one piece of data. The issue description only mentions a name column whereas the mockup has a name and ID column.

Please confirm that you want this:

![image](https://user-images.githubusercontent.com/14068621/46672312-16f50980-cba5-11e8-9308-cc182069b3ac.png)

Over this:
![image](https://user-images.githubusercontent.com/14068621/46672326-207e7180-cba5-11e8-9379-fec11523244b.png)

**Comment by sunilmalagi** [comment]
@serenamarie125 @christianvogt @AshishDurgude 
Here is one example we have provided to display Assignee Name and ID for the Planner:
https://redhat.invisionapp.com/share/E6MUSNDBAQT#/308269814_Proposed_Assignnee_List
I propose to follow the same style.  If you all agree on that, Ashish can change the visuals and update you all.

**Comment by christianvogt** [comment]
We need to be consistent. If we already had a proposal for planner I don't understand why we have something different proposed for another part of the application.

If the planner designs were approved, I say we accept it everywhere. IMO it's clearly better than the ask in this issue.

**Comment by joshuawilson** [comment]
I like what was designed for Planner.

**Comment by muruGanesan** [comment]
@sunilmalagi, As discussed, please provide your design to @AshishDurgude and he will update the 'username' display as per planner standard.

**Comment by AshishDurgude** [comment]
@joshuawilson @christianvogt @sunilmalagi Here is the updated InVision file based on above changes:
https://redhat.invisionapp.com/share/N6O4OYX89RG

**Comment by joshuawilson** [comment]
@AshishDurgude I left a comment on the design.
