### ISSUE TITLE
Extra weird Import Codebase

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#433]
https://screencast.com/t/oeE3KD5mALg

opens a oddball thing on the right of the screen

https://screencast.com/t/VhmW3OfhPS

why not just open the main dialog that has Import and Add/Quickstart on it?

https://screencast.com/t/Tzu1EUCZ5Q7

**Comment by burrsutter** [comment]
Turns out this a Feature and I have now been educated

**Comment by joshuawilson** [comment]
@burrsutter can we close this?

**Comment by burrsutter** [comment]
This serves as a quick imported to getting going with Che. It does not seem to support pipelines as if the end-user had come through the Forge Wizard.
