### ISSUE TITLE
Allow workspace creation according to factory configuration

### ISSUE THREAD

**Issue by gorkem** [openshiftio/openshift.io#4332]
When we are creating a workspace for a repository with `.factory.json` in it.  Create workspace according to the definiton of `.factory.json`.

**Comment by garagatyi** [comment]
@gorkem do you mean the creation of a workspace using OSIO flow or directly in Che?

**Comment by gorkem** [comment]
This is for OSIO flow. Right now we are always creating workspace according to passed ID but if we start putting `factory.json` or any other devfile that we are starting to work on, it will be ignored when opening from OSIO. I think we should prioritize devfile/factory.json over anything else.

**Comment by ibuziuk** [comment]
@gorkem is it planned to support both `factory.json` & `dev-file` [1] ?

[1] https://github.com/openshiftio/openshift.io/issues/4538

**Comment by ibuziuk** [comment]
@gorkem during today's call with  @skabashnyuk and @mshaposhnik it was discussed that potentially `devfile` would be a replacement for `factory.json / chefile` and be the only portable format for workspace generation. Taken this into account I'm wondering if it really makes sense to have this issue in the osio backlog, or the only focus should be on `devfile` integration as part of osio flow - https://github.com/openshiftio/openshift.io/issues/4538

**Comment by gorkem** [comment]
Ultimately, all the integration from Toolchain to Che should become based on `devfile` meaning that the old `stack_id` based integration should go away. Are we tracking it somewhere?  #4538 seems to be very import specific. 

What is the plan to support/convert existing `factory.json` users?

**Comment by ibuziuk** [comment]
> Ultimately, all the integration from Toolchain to Che should become based on devfile meaning that the old stack_id based integration should go away. Are we tracking it somewhere? #4538 seems to be very import specific.

There is a separate issue `Workspace creation from WIT in che 7 without stackID` 
 - https://github.com/openshiftio/openshift.io/issues/4536  

> What is the plan to support/convert existing factory.json users?

Could you please clarify what are `factory.json` users in the context of openshift.io flow ? currently `factory.json` is not supported on osio flow at all, so there is nothing to support. The question is should we bring the support of both `factory.json` and `devfile`, or focus only on `devfile` integration (AFAIK, eventually it is planned that `devfile` would be the only portable format for workspace generation and would replace `factory.json` / `chefile`.  @skabashnyuk @mshaposhnik is it the right assumption ?)

**Comment by gorkem** [comment]
Something openshift.io flow did not support in the past does not mean it does not exist. 

Do we think there is a significant number of users of `factory.json` that we want to support on che.openshift.io? @slemeur 
Of course this is assuming there is a migration path, compatibility for `factory.json` upstream

**Comment by slemeur** [comment]
I don't think we have a significant number of users of `factory.json`. 

The work on the devfile has been progressing nicely and it should now be possible to use the devfile to create Che 7 based workspaces with the factory flow. 
That could be something to experiment @skabashnyuk @mshaposhnik to validate the work currently in progress on the devfile.

**Comment by ibuziuk** [comment]
@slemeur @gorkem so, are you ok if we close this issue and focus on devfile support in openshift.io flow - https://github.com/openshiftio/openshift.io/issues/4538 ?

**Comment by slemeur** [comment]
Yes, fine for me.

**Comment by ibuziuk** [comment]
Closing in favour of dev file support - https://github.com/openshiftio/openshift.io/issues/4538
dev file is supposed to be the only portable format for workspace generation in future
