### ISSUE TITLE
Github linking fails in the UI

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#4333]
1. Login to an OSiO account.
2. If github is connected, disconnect it.
3. Create App -> Try to connect Github. Notice that the code fails.

![screenshot from 2018-09-18 11-47-26](https://user-images.githubusercontent.com/545280/45668766-9f026900-bb3b-11e8-8738-2c93936f285c.png)
![screenshot from 2018-09-18 11-48-25](https://user-images.githubusercontent.com/545280/45668778-a3c71d00-bb3b-11e8-9a25-830f26411f0b.png)

**Comment by rohitkrai03** [comment]
@sbose78 Raised a PR  - https://github.com/fabric8-ui/fabric8-ui/pull/3324

**Comment by sbose78** [comment]
Thanks @rohitkrai03 ! @corinnekrych could you please help review and merge this?
