### ISSUE TITLE
Not able to link organisation with test account

### ISSUE THREAD

**Issue by sanketpathak** [openshiftio/openshift.io#4334]
My test account is already linked with my GitHub account. Now for testing purpose I want the repositories to be created under the test organisation. But I'm not able to link organisation with my account.

   Steps:
1. Go to setting
2. Disconnect Github account.

![issue](https://user-images.githubusercontent.com/10252230/45676801-3e315b80-bb50-11e8-850e-35c1a16b8b45.png)

3. Connect account.

![issue1](https://user-images.githubusercontent.com/10252230/45676837-586b3980-bb50-11e8-9040-91d3284d841b.png)

4. Its connecting with the same account details.

What could be done for linking organisation?

**Comment by sbose78** [comment]
![screenshot from 2018-09-18 15-33-03](https://user-images.githubusercontent.com/545280/45680294-31186a80-bb58-11e8-9c24-176541c2c83d.png)

Could you look for the organization in the "Location" dropdown?

**Comment by sanketpathak** [comment]
Well, I was not able to see this a moment before but now after deleting the existing organisation, creating a new one, removing third party restrictions and re-logging with github; now able to see this option. Thanks for the help.
