### ISSUE TITLE
[Intermittent issue][Planner]: The planner screen gets stuck with a spinner on the left and no work items 

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#4338]
The planner screen gets stuck with a spinner on the left and no work items.

**Comment by jarifibrahim** [comment]
I think this has been already been fixed by @sahil143. @Raunak1203 can you please check if this is still reproducible.

**Comment by Raunak1203** [comment]
No @jarifibrahim this issue is not reproducible always

**Comment by sahil143** [comment]
@Raunak1203 I'm not able to reproduce this issue. Tried many times.

**Comment by Raunak1203** [comment]
Closing the Issue, It is not reproducible now.
