### ISSUE TITLE
Search Spaces seems to see all spaces for all users

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#434]
https://screencast.com/t/6XbuUe5d

http://www.screencast.com/t/ffMhKppHTky

**Comment by ldimaggi** [comment]
Logged already here:

https://github.com/fabric8-ui/fabric8-planner/issues/2054

**Comment by joshuawilson** [comment]
We have a user story for this at https://github.com/openshiftio/openshift.io/issues/348 
This is currently under a redesign by UX. I'm closing this as a duplicate.
