### ISSUE TITLE
"Runtime is already started" error.

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#4342]
##### Issue Overview

OSIO won't start workspace.

##### Expected Behaviour

Workspace can be started and used.

##### Current Behaviour

OSIO reports "Runtime is already started".

##### Steps To Reproduce

1. Make a new project, based on a Java Maven project
2. Use it.  At end of day, close browser.
3.  Next day, try to start workspace again.

##### Additional Information

A Google search of the likely key phrase "Runtime is already started" does not turn up any useful results.  Can we please document the right place to look in similar scenarios?

**Comment by RickJWagner** [comment]
![image](https://user-images.githubusercontent.com/524520/45887653-e5490980-bd81-11e8-81d8-346346c855c7.png)

**Comment by ibuziuk** [comment]
@RickJWagner hmm.. workspace should have been idled. Does it help if you try to stop / start the workspace via dashboard ?

**Comment by RickJWagner** [comment]
Hi Ilya,
Thanks for the quick response.  
The Che dashboard didn't offer my any workspaces to operate on (as seen in picture above).
I tried going to the oc command line to kill the Che pod, as expected a new one restarted.  This one failed as well.
I next tried deleting the OSIO codespace and making a new workspace (re-importing my code from Github), but I get a message that OSIO knows the workspace already exists.  (Picture below.)

![image](https://user-images.githubusercontent.com/524520/45891355-f5191b80-bd8a-11e8-8f35-de4f21a92609.png)

**Comment by ibuziuk** [comment]
looks like you are hitting - https://github.com/redhat-developer/rh-che/issues/899
Could you try to login into your oso to  `*-che` namespace and provide info about what resources do you have there ?

**Comment by RickJWagner** [comment]
Hi @ibuziuk ,
Sure.  Here's what I've got:

Using project "rhn-support-rick-che".
[rick@DESKTOP-C47TI0G ~]$ oc get all
NAME                                           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/workspacegxf1bu4fi8qx2z3s.dockerimage   1         0         0            0           36m
deploy/workspacesg8b7x4b0sllbass.dockerimage   1         1         1            1           19h

NAME                                                  DESIRED   CURRENT   READY     AGE
rs/workspacegxf1bu4fi8qx2z3s.dockerimage-5947c6fb4    1         0         0         36m
rs/workspacesg8b7x4b0sllbass.dockerimage-74474f7b65   1         1         1         19h

NAME                   HOST/PORT                                                                     PATH      SERVICES                     PORT          TERMINATION     WILDCARD
routes/route1thjt81i   route1thjt81i-rhn-support-rick-che.8a09.starter-us-east-2.openshiftapps.com             server51n32nfn-dev-machine   server-4411   edge/Redirect   None
routes/route8maw85no   route8maw85no-rhn-support-rick-che.8a09.starter-us-east-2.openshiftapps.com             server51n32nfn-dev-machine   server-4403   edge/Redirect   None
routes/routeogiar8i3   routeogiar8i3-rhn-support-rick-che.8a09.starter-us-east-2.openshiftapps.com             server51n32nfn-dev-machine   server-8080   edge/Redirect   None
routes/routeys0gpdin   routeys0gpdin-rhn-support-rick-che.8a09.starter-us-east-2.openshiftapps.com             server51n32nfn-dev-machine   server-4412   edge/Redirect   None
routes/routezulducwm   routezulducwm-rhn-support-rick-che.8a09.starter-us-east-2.openshiftapps.com             server51n32nfn-dev-machine   server-4401   edge/Redirect   None

NAME                                                        READY     STATUS    RESTARTS   AGE
po/workspacesg8b7x4b0sllbass.dockerimage-74474f7b65-6f2zz   1/1       Running   0          40m

NAME                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                        AGE
svc/server51n32nfn-dev-machine   ClusterIP   172.30.135.246   <none>        4401/TCP,4412/TCP,8080/TCP,4403/TCP,4411/TCP   19h

Thanks,
Rick

**Comment by ibuziuk** [comment]
@RickJWagner due to rh-che issue with idling during rollout update there are some untracked deployments in the `*-che` namespace. Am I correct that `https://che.openshift.io/dashboard/` shows that you have no workspaces running? If this is the case, please, try to execute the following command in order to cleanup the untracked workspace resources:

`oc delete all -l che.workspace_id`

**Comment by RickJWagner** [comment]
HI @ibuziuk,
Thank you for the above suggestion.  I gave it a try, unfortunately it did not clean up the failing workspace.
I am 'off the beaten path' here, I am trying to use a workspace for an unusual use case.  (I am trying to do some Fuse development with a Che recipe that I think is probably not a good fit.)  I am trying to learn more about workspace startup and the objects and processes that are involved.
So I will now close this case and mess around with it a little further before wiping the environment and starting anew.  I don't need to distract you as I go through this process.
Thanks again for your help.
Rick

**Comment by dneary** [comment]
This is the same symptom I have observed. Glad to hear there is some understanding of the cause, concerned that it was not an isolated incident for me.
