### ISSUE TITLE
Remove reference of planner in stack-report for VSCode extension

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4349]
- In VSCode extension currently, we have the reference  of planner as below

> Take corrective action by creating a work item in planner or leave us feedback.

![change-display-text](https://user-images.githubusercontent.com/5129024/45994032-6c162300-c0af-11e8-9ef9-7c9864507ca5.png)

Below are the files which needs to be changed

- https://github.com/fabric8-analytics/fabric8-analytics-stack-report-ui/blob/master/src/app/stack/card-details/card-details.component.ts#L85

- https://github.com/fabric8-analytics/fabric8-analytics-stack-report-ui/blob/master/src/app/stack/card-details/card-details.component.ts#L93

**Comment by invincibleJai** [comment]
It closed due to fixes in PR description, opening it. It has been fixed. Will close once changes move to prod.

**Comment by stevengutz** [comment]
@invincibleJai @sivaavkd I'm not sure what a status/competed is.  Is this bug now supposed to be closed?

**Comment by sivaavkd** [comment]
@stevengutz - It is fixed and is available in staging.  Once we move it to Prod (after saas-analytics PR is merged), we will close.
