### ISSUE TITLE
Work Item Widget Improvements

### ISSUE THREAD

**Issue by Veethika** [openshiftio/openshift.io#4351]
Here are a couple of suggested quick improvements for the work-item widget in the space dashboard:

1) The space work-item widget is not displaying correct data and the bar chart:
<img width="535" alt="screen shot 2018-09-25 at 2 23 03 pm" src="https://user-images.githubusercontent.com/35127763/46003668-bb1f8080-c0ce-11e8-8412-9a53addee513.png">

2) The states should have a direct link to navigate to the specific page where all the work-items with a particular state could be viewed

**Comment by Veethika** [comment]
@sahil143 @sanbornsen is it possible to provide a link to the states(Resolved, In progress, Open) that directly takes the user to the respective query page where the list of work-items in that particular state would appear?
+ @serenamarie125

**Comment by stevengutz** [comment]
This doesn't sound like a bug to me.  If it's an impediment of some sort we should probably track it in Planner

**Comment by joshuawilson** [comment]
Since the chart is fixed I'm closing it. If you want to create a new design to update how the widget works, please open a new issue.
