### ISSUE TITLE
Status combo shows yellow status for Che and Jenkins and no version

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#436]
Status combo shows yellow status for Che and Jenkins and no version

![screenshot 2017-07-28 16 35 21](https://user-images.githubusercontent.com/30131/28733980-0528415c-73b5-11e7-9653-30aff7e9424a.png)

**Comment by joshuawilson** [comment]
This is something we are actively working on.

**Comment by burrsutter** [comment]
Also the Power symbol

**Comment by joshuawilson** [comment]
This has been fixed, if you update your tenant.

**Comment by bmicklea** [comment]
I saw this issue again this morning but is now working for me. @burrsutter continues to have this with one of his accounts (burr@redhat.com).

**Comment by bmicklea** [comment]
Also happening for users like Daniel Oh (RH)

**Comment by joshuawilson** [comment]
If an account gets cleaned and working with an updated tenant, then this shows correct. Having these icons do not indicate an error in the UI but something is broken in the account. 

This should be closed.

**Comment by bmicklea** [comment]
That makes sense thanks.
