### ISSUE TITLE
App Creation: Pipeline section does not show up

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#4362]
**The pipeline options do not show up for some users.**
The users were first time users
They used machines like Mac or Windows
One user who faced this issue was on Safari + Mac
Solution: Refresh the page, and the pipeline options show up.

**Comment by vikram-raj** [comment]
@nimishamukherjee Please verify. This issue has been fixed and on prod.

**Comment by christianvogt** [comment]
I will test on mac and close if cannot reproduce.

**Comment by christianvogt** [comment]
Cannot reproduce
