### ISSUE TITLE
Quotas exceeded by creating multiple projects sets up a 1-hour termination intervals for pods 

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#437]
We managed to get Jenkins into a state where new app/quickstarts could not be run. This happened over time as we ran multiple tests and performed the steps in the demo.

The issue here is that with Jenkins in this state, the only way that we could clear things up and enable us to create a new project was to delete all builds, pipelines, etc, in OpenShift and then scale Jenkins down to zero and back up to one.

Open question - see attached screenshots and Jenkins pod log - what caused the termination of some (jenkins slave) pods at 1-hour intervals? And - why wouldn't the termination of these pods free up enough resources for a new project to start?

![screenshot from 2017-07-28 23-23-06](https://user-images.githubusercontent.com/642621/28741871-894f89d4-73ee-11e7-968d-28a7d05f8469.png)
![screenshot from 2017-07-28 23-11-03](https://user-images.githubusercontent.com/642621/28741872-8959ee42-73ee-11e7-8198-33022ae7616e.png)
![screenshot from 2017-07-28 23-10-20](https://user-images.githubusercontent.com/642621/28741873-896a0aa2-73ee-11e7-9e79-4da6cfe96310.png)
![screenshot from 2017-07-28 23-10-01](https://user-images.githubusercontent.com/642621/28741874-896e925c-73ee-11e7-8879-167e7d13a4b5.png)
![screenshot from 2017-07-28 23-09-42](https://user-images.githubusercontent.com/642621/28741875-89751492-73ee-11e7-9aaa-b59feb539dcd.png)
![screenshot from 2017-07-28 23-09-08](https://user-images.githubusercontent.com/642621/28741876-898fdf02-73ee-11e7-9dc0-7146ad45a7a9.png)
[jenkins_pod_log.txt](https://github.com/openshiftio/openshift.io/files/1184616/jenkins_pod_log.txt)

**Comment by ldimaggi** [comment]
Jenkins pod log is attached

**Comment by jstrachan** [comment]
this is probably due to the bug where creating a new project triggers a build for all existing projects; so as you keep creating new projects without removing old ones, it'll keep getting slower and slower to run each build since you've only quota to run 1 build at once

**Comment by jstrachan** [comment]
once #342 is fixed I'm hoping this one gets resolved too

**Comment by qodfathr** [comment]
Fixed.
