### ISSUE TITLE
Build Team OSD Support: Integrations plans

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#4370]
Provide architecture document for how the build tools are going to integrate with the multi environment OSD support.

Doc: https://docs.google.com/document/d/1SRFH_keOjOaHUxPlKyxwLTAxKfKvYMI9Bm3IK1iJYQI/edit#

Planner: https://openshift.io/openshiftio/Openshift_io/plan/detail/720

**Comment by pradeepto** [comment]
cc @alexeykazakov @gorkem
