### ISSUE TITLE
Stack Report button doesnt appear for imported node project

### ISSUE THREAD

**Issue by yzainee** [openshiftio/openshift.io#4371]
##### Issue Overview

Once the build is successful, we can see the stack report from the dashboard but the stack report button doesnt appear on the build pipeline for imported node projects

##### Expected Behaviour
Stack report button should appear on UI

##### Current Behaviour
Button works fine for maven projects, but doesnt work on node project.

##### Steps To Reproduce

1. Login to openshift.io
2. Fork and Import a sample node project [https://github.com/bucharest-gold/nodejs-health-check-redhat]
3. Change the jenkins file to point to the correct pipeline. See example here [https://github.com/yzainee/nodejs-health-check-redhat/blob/master/Jenkinsfile ]
4. Select any build pipeline.
5. Once build is successful, the annotations are getting set, but the stack report button doesnt show.

##### Additional Information

Also, while importing the repo, no matter which pipeline we select, it selects the default build pipeline.
![screenshot from 2018-10-01 09-23-47](https://user-images.githubusercontent.com/37098367/46288964-325c8500-c5a5-11e8-8b41-47ff0c31b811.png)

**Comment by miteshvp** [comment]
@yzainee - who is supposed to work on this? Does it belong to Analytics or other team?

**Comment by yzainee** [comment]
@miteshvp @invincibleJai This issue was raised when the npm list command was executed in the build, and we were using the generated json file to do the further stack analysis computation. As this flow is changed now and we are no longer using build for the deps, i am closing this issue as this cannot be even tested.
