### ISSUE TITLE
Remove unnecessary onboarding area on the home page

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4376]
Remove the dark "onboarding" area on the home page.  
 
<img width="1440" alt="screen shot 2018-10-01 at 9 47 17 pm" src="https://user-images.githubusercontent.com/12504403/46324864-ac036b80-c5c3-11e8-83bf-095edac712f4.png">

**Comment by serenamarie125** [comment]
@sunilmalagi @AshishDurgude please create a version of this page without the "dark on boarding" area & put the sketch file into the GDrive, thanks!

**Comment by sunilmalagi** [comment]
@serenamarie125 here is the invision link for the visuals review:
https://redhat.invisionapp.com/share/FHODIIRR3X5#/323334634_-4374_01
&
Here is the sketch file in GDrive:
https://drive.google.com/open?id=1oKYBJifW8xxKp4I0aPe7AwzmCSRHUt7Y

**Comment by christianvogt** [comment]
dev story: https://openshift.io/openshiftio/Openshift_io/plan/detail/792
