### ISSUE TITLE
Analytics: Stack Reports Recommendation of upgrade from 3.4.2 to 3.4.1

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#438]
https://screencast.com/t/gIsq5dxBv

The current recommendation is to upgrade from 3.4.2 to 3.4.1, that does not sound like an upgrade to me.

**Comment by krishnapaparaju** [comment]
3.4.2 got published in the month of June'2017. 
Reason, fix: The data being hosted has not been updated (since last month), as of end of next week, platform would have latest data show up (along with on going incremental refresh of the data).

For now (with pre-cooked reference stacks), I think the immediate fix can be not recommend lower version if user got latest version + Construct this english sentence to factor in the current user's version compared to the recommended version.

Good catch :)

**Comment by burrsutter** [comment]
I would like this to be a P1 because it makes us look pretty foolish.   Recommending an "upgrade" by downgrading the version.

**Comment by GeorgeActon** [comment]
@krishnapaparaju @samuzzal-choudhury Please update this to assign to the person working on it. Is Sarah leading for this?

**Comment by samuzzal-choudhury** [comment]
This is due to the fact that the Anitya server is not updated with the latest version of the components. @msrb can Anitya server be refreshed to get the latest versions of components?

**Comment by msrb** [comment]
@samuzzal-choudhury I will check what's going on there. Do we take the information directly from Anitya? No graph?

**Comment by samuzzal-choudhury** [comment]
@msrb graph is involved.

**Comment by SaketJNU** [comment]
I don't why are we using this; but the fact is "libio_latest_version" from graph is being used as a latest version recommendation, which is responsible to reflect the above mentioned the latest version mismatch. 
Attaching two files containg data in graph [1] http://pastebin.test.redhat.com/506334  [2] http://pastebin.test.redhat.com/506335 ; Both has latest_version values, but in UI latest_version for one missing as: libio_latest_version  data is not present.

**Comment by miteshvp** [comment]
@SaketJNU - this is for stack-analyses and not `v2`

**Comment by samuzzal-choudhury** [comment]
@msrb You will be able to find the latest version in the file `/maven/io.vertx:vertx-core/3.4.2.json` of S3 bucket `prod-bayesian-core-data`.

**Comment by msrb** [comment]
This is going to be fixed by switching to new `stack-analyses` version 2 endpoint. The endpoint takes data from a different source, so this issue will disappear. The new endpoint should be deployed to production in upcoming days. Thanks @samuzzal-choudhury 😉

**Comment by GeorgeActon** [comment]
@msrb Is this fixed with the deployment of the new stack analysis endpoint?

**Comment by samuzzal-choudhury** [comment]
@burrsutter This has already been addressed and the fix is on prod. Closing this issue. Please reopen if you think otherwise. CC: @GeorgeActon @sivaavkd @krishnapaparaju @miteshvp
