### ISSUE TITLE
Move to upstream Maven image

### ISSUE THREAD

**Issue by arilivigni** [openshiftio/openshift.io#4383]
We want to stay in sync with the upstream image of maven.  We need to convert to using the upstream images and patch any issues upstream if possible or make a subsequent image in the meantime downstream based on the upstream maven image.

**Comment by arilivigni** [comment]
https://github.com/fabric8io/fabric8-pipeline-library/pull/435

**Comment by arilivigni** [comment]
This is fixed fabric8io/fabric8-pipeline-library#435

**Comment by piyush-garg** [comment]
This has been done. Closing this.
