### ISSUE TITLE
ExecuteForgeCommandError The forge-quick-start :: execute :: 2 command failed or only partially succeeded

### ISSUE THREAD

**Issue by danieloh30** [openshiftio/openshift.io#439]
During to create a space, I got an issue.
![screenshot from 2017-07-31 11-23-02](https://user-images.githubusercontent.com/14066977/28760530-dfae7a10-75e2-11e7-8061-33aa337ee8a8.png)

**Comment by joshuawilson** [comment]
Try cleaning up your account and resetting things. Also, make sure you have updated your tenant. https://github.com/openshiftio/openshift.io/wiki/FAQ#how-do-i-clean-up-all-apps-and-builds-in-my-openshift-online

**Comment by aslakknutsen** [comment]
Regardless of that, IndexOutOfBoundsException shouldn't happen and be presented to user.

**Comment by joshuawilson** [comment]
Agreed. But I need to know if cleaning up fixes it and if it repeatable (and how).

**Comment by mishaone** [comment]
I have a similar error, but a slight variation (see attached error screenshot). Clearing tenant as recommended now and will update if that fixed the issue.
![error_forge](https://user-images.githubusercontent.com/926572/29107305-e510fe9c-7d1c-11e7-89f1-4eb30543dbee.png)

**Comment by jpopelka** [comment]
I'm seeing this after pressing 'Finish' button:

![screenshot from 2017-08-21 16-05-40_](https://user-images.githubusercontent.com/288686/29523027-ce3f8bde-868b-11e7-8a3c-08d59c504be3.png)

Neither `Update profile` -> `Clean tenant` nor `gofabric8 tenant delete` helped.
