### ISSUE TITLE
Unbork a User's Account

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#440]
We need a new "feature" to be used by RH Engineering or myself.
To put a user's account back into pristine state as if they never clicked on their welcome email, logged in the first time and interacted with _gettingstarted (never linked their github/OSO accounts)
However, leave their github repos alone as they may have code that they would like to keep.  The end-user is responsible for manually unborking their github account.

**Comment by rgarg1** [comment]
This could be a handy tool, if nothing else works. I experienced it first hand today.

**Comment by rgarg1** [comment]
My experience:

I was borked. I performed all steps mentioned in https://github.com/openshiftio/openshift.io/issues/443, but that didn't help me. My Jenkins pod was throwing up error related to an already deleted space.
After I was unborked, only then I was able to proceed.

**Comment by burrsutter** [comment]
The current theory on the unborking process (aka partial factory reset) - needs further verification 

oc login https://console.starter-us-east-2.openshift.com/
oc delete project username-run
oc delete project username-stage
oc delete project username-che
oc delete project username
oc delete all -all -n username-jenkins

Update Tenant
https://vimeo.com/227963758

**Comment by burrsutter** [comment]
Related to https://github.com/openshiftio/openshift.io/issues/375

**Comment by joshuawilson** [comment]
After working through this with the OSIO and OSO teams we think we have a script that works. 

Replace `username` with your username.
```
oc login https://console.starter-us-east-2.openshift.com/
oc delete all,pvc,cm,secrets,sa --all -n username-run
oc delete all,pvc,cm,secrets,sa --all -n username-stage
oc delete all,pvc,cm,secrets,sa --all -n username-che
oc delete all,pvc,cm,secrets,sa --all -n username
oc delete all,pvc,cm,secrets,sa --all -n username-jenkins
```
Then Update Tenant to reset everything
https://vimeo.com/227963758

**Comment by joshuawilson** [comment]
@burrsutter once this is tested to your satisfaction please close.

**Comment by rgarg1** [comment]
I used these commands today and it helped me to get rid of all 'Wights'. Was able to proceed with workshop script post cleanup. So far so good. Will update if I run into issues.

**Comment by ldimaggi** [comment]
Just ran these commands - and updated tenant.  After a few min, saw these results - the Jenkins + Content Registry pods are not starting - and are not writing to their logs:

![screenshot 42](https://user-images.githubusercontent.com/642621/29027782-1e34d730-7b50-11e7-983e-1ff5d0deca3d.png)
![screenshot 43](https://user-images.githubusercontent.com/642621/29027781-1e332d36-7b50-11e7-8fcc-be40ad534338.png)
![screenshot 44](https://user-images.githubusercontent.com/642621/29027783-1e35d0e0-7b50-11e7-8328-624c8d7e4813.png)

**Comment by ldimaggi** [comment]
Then - after trying update tenant again - seeing this:

![screenshot 45](https://user-images.githubusercontent.com/642621/29027854-66ca3fe4-7b50-11e7-80ca-96066980f6c5.png)

**Comment by aslakknutsen** [comment]
Back-off pulling image \"registry.ops.openshift.com/openshift3/ose-deployer:v3.5.5.19\"

**Comment by ldimaggi** [comment]
These^ (August 7) errors were due to an OpenShift issue - the deletion commands seem to be working fine. "Update Tenant" restores the user's account to a working condition in about 2-3 min.
