### ISSUE TITLE
OSIO ReBranding Design - Planning

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4401]
In order to prepare for the OSIO Rebranding effort, this story is focused on 
- [ ]  identify a list of affected screens.  Use this document as a reference: https://docs.google.com/document/d/1KojlYvu2tOGIe6qsEWBuZH-wcbhpN8P4Wl3gbk7zMdg/edit#
- [ ]  bring each of the screens into a sketch file so that once we have the appropriate visual assets, they will be easy to apply

**Comment by sunilmalagi** [comment]
@serenamarie125 I went through the details you have provided, I need more clarity on the same.  

1. There is a Gitlab link in the document, in which I tried go through the requirement, but its not clear that which are the screens that needs to be worked on and where do I find them?

2. Once I get the list of screens, I will be able to work on the ReBranding effort, 

3. Is it finalised on the rebranding content/info (Opshift.io = Red Hat CodeReady Toolchain for OpenShift)?  There is also official name and common name, which one I should consider.

4. Do we already have any existing sketch file which I can reuse? 

It would be great if we can discuss it out in the coming meeting and get my assumptions cleared.

**Comment by sunilmalagi** [comment]
I have collected all the required screens and uploaded them into Invision, wherever there is only text updation is required, those ones are taken care off.  I will be updating the remaining screens when I get the updated logo:
https://redhat.invisionapp.com/share/4EP3YNNUVSB

**Comment by joshuawilson** [comment]
@serenamarie125 The rebranding has been requested to be done as soon as possible. We will look at what we can do without image updates, but I think most of what is needed falls under that. 

cc @christianvogt

**Comment by serenamarie125** [comment]
@joshuawilson @christianvogt the official word is that the logo won't be available til after the new year.  The short term resolution will be to create an image with "CodeReady Toolchain" in the Interstate font.  We are awaiting access for the font now - prioritizing so that we can make this available today.

**Comment by serenamarie125** [comment]
This is already complete, so closing :)
