### ISSUE TITLE
Infotips text are not displayed for Agile template 

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#4403]
env - production

![screenshot from 2018-10-10 23-34-53](https://user-images.githubusercontent.com/34271052/46756505-490d8500-cce5-11e8-84d8-5db369c2778b.png)

**Comment by nimishamukherjee** [comment]
@divyanshiGupta please have a look and add your comments. Infotips appear on the quick add. They do not appear on the side panel.

**Comment by jarifibrahim** [comment]
The infotips are available on prod-preview and docs haven't been updated on prod in the last 4 months. That's why we don't have infotips for agile on prod. 

Removing workitem-tracker label since there's nothing to be done on the backend.

**Comment by jarifibrahim** [comment]
@Preeticp is there a reason for using old (4 months old) version of docs on prod? Can we push the latest version of docs to prod?

**Comment by divyanshiGupta** [comment]
@Preeticp last time I checked with you, you told me that there was a problem with Centos CI but this issue is 4 months old. Can you check why the doc is still not updated on prod?

Removing ui label since this is a docs issue.

**Comment by Preeticp** [comment]
@jarifibrahim you are right there has been an issue with updating docs in the prod and @rkratky has been trying to get it resolved. I have been following it up with him and Piyush. Piyush mentioned a workaround, we will give it a try and try to get this resolved ASAP.

**Comment by Preeticp** [comment]
@divyanshi, the workitems infotip was added in the yaml file 2 months back: https://github.com/fabric8-services/fabric8-wit/pull/2266/files
Yesterday I added it to the glossary too as per the old method and it is merged, can you please check why it's still not reflected as an infotip?

**Comment by divyanshiGupta** [comment]
@Preeticp as I mentioned in the mattermost chat that we had, I cannot see the description field in the attributes of work items typegroup response that means the correct response in not coming from the backend or there is some problem in the way the infotip was added in the yaml file. 
![screenshot from 2018-11-14 10-15-51](https://user-images.githubusercontent.com/20724543/48572926-d4a3b280-e930-11e8-9f13-a4d0e9564599.png)

**Comment by Preeticp** [comment]
@Raunak1203 @nimishamukherjee this is now available in prod-preview and should be seen on prod as soon as the prod is updated with latest changes.
See below for changes in prod preview:
![screenshot from 2018-11-19 14-15-55](https://user-images.githubusercontent.com/16647625/48695756-043f0d00-ec06-11e8-8691-d7d25c970d5d.png)

**Comment by Raunak1203** [comment]
@Preeticp @divyanshiGupta for Iterations I can still see UUID
![screenshot from 2018-11-19 14-49-03](https://user-images.githubusercontent.com/34271052/48697392-7fa2bd80-ec0a-11e8-8703-1311c105b1dc.png)

**Comment by Raunak1203** [comment]
verified fixed in prod-preview.
Closing this issue
