### ISSUE TITLE
Stack report link not appearing in pipelines view 

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4405]
Stack report link not appearing in pipelines view as in below screenshot. 

<img width="1607" alt="screen shot 2018-10-11 at 12 56 25 am" src="https://user-images.githubusercontent.com/5129024/46760815-afe46b80-ccf0-11e8-8f2c-adc3ef762345.png">

**Comment by joshuawilson** [comment]
What configuration gets a build with a report? I just tried Spring and REST and got no report.

**Comment by invincibleJai** [comment]
changes are in prod, hence closing it.
