### ISSUE TITLE
Security Alert Feature button wouldn't set to `On`

### ISSUE THREAD

**Issue by GeetikaBatra** [openshiftio/openshift.io#4407]
##### Issue Overview
I am trying to use the feature cve notification. Since, it requires setting the security alert button to `on` state. Doing so, it is automatically setting to `off` state with an error.

`Status: undefined, Unable to update security alert subscription for codebase https://github.com/GeetikaBatra/hellovertx .`

##### Current Behaviour
Here is the image for reference.
![screenshot from 2018-10-11 12-17-01](https://user-images.githubusercontent.com/8664238/46785586-cff74780-cd4f-11e8-96bf-f20474873ecc.png)

##### Steps To Reproduce

1. Log In to Openshift.io
2. Opt for internal features from settings.
3. Create a code base.
4. Go to codebase list
5. Set cve alert button to `On` state.

**Comment by abs51295** [comment]
I can reproduce this on prod-preview except I don't see any error while turning the feature flag on, but the feature flag gets turned off automatically:

<img width="1267" alt="screen shot 2018-10-11 at 12 24 24 pm" src="https://user-images.githubusercontent.com/13438222/46785880-c15d6000-cd50-11e8-8537-2b6436f85063.png">
<img width="1248" alt="screen shot 2018-10-11 at 12 24 36 pm" src="https://user-images.githubusercontent.com/13438222/46785887-cc17f500-cd50-11e8-9693-cbd187b0d5d5.png">

**Comment by rohitkrai03** [comment]
There was a frontend issue due to which API calls were not going on change of state. After fixing that i am getting `500: Internal Server Error`

```
{
   "errors":[
      {
         "code":"unknown_error",
         "detail":"unknown error, got response: {\"status\":\"failure\",\"summary\":\"git-url cannot be empty\"}\n",
         "status":"500",
         "title":"Unknown error"
      }
   ]
}
```

**Comment by aslakknutsen** [comment]
Fixed by https://github.com/openshiftio/openshift.io/issues/4150
