### ISSUE TITLE
Unable to create application

### ISSUE THREAD

**Issue by pradeepitm12** [openshiftio/openshift.io#4414]
I am trying to create an application on openshift.io and every time getting  message "**There was a problem fetching results, please try again**" 
1. Select space
2. Click on create an application.
3. Select mission as REST Api Level 0
4. Select run time as Spring Boot
5. Select Red Hat suggested pipeline
6. Click on Select application.

I repeated this multiple time and observed that every time when I was putting underscore in app name issue was reproducible. e.g demo_app_1

But when I tried same thing with a name like demo-app-1 worked fine.

**Comment by joshuawilson** [comment]
@bartoszmajsak do you think this is a bug in the backend in handling underscores? Or in how the frontend handles the name to begin with?

**Comment by bartoszmajsak** [comment]
@gastaldi is it the same as https://github.com/fabric8-launcher/launcher-backend/issues/553 ? If so we might close that one once a new version of Launcher Backend goes live.

**Comment by gastaldi** [comment]
@bartoszmajsak I don't think they are related. I can't even proceed if I type `demo_app_1` as the application name in https://developers.redhat.com/launch/wizard. Maybe this validation is not being applied in OSIO?

**Comment by bartoszmajsak** [comment]
@gastaldi do you mean using `_` is illegal and should be validated in the UI? What's the reason behind that?

**Comment by gastaldi** [comment]
Underline is not part of the naming requirements:
![screenshot from 2018-10-11 17-40-42](https://user-images.githubusercontent.com/54133/46832588-cfc17100-cd7c-11e8-9c3f-6f6695c36971.png)

**Comment by bartoszmajsak** [comment]
So here's OSIO side of things

![image](https://user-images.githubusercontent.com/719616/46832825-5c812480-cda7-11e8-99c9-6bff1a1e70fb.png)

So now the question of the day is - why is that different if we are presumably using the same `ngx-launcher` component? @vikram-raj any clue?

**Comment by bartoszmajsak** [comment]
> Underline is not part of the naming requirements:

@gastaldi this still does not answer "why" part of my question btw :P

**Comment by joshuawilson** [comment]
If underscore is illegal then we should catch it in the UI. But it would be nice for the backend to respond with the reason things failed. "Underscores are not allowed"

**Comment by vikram-raj** [comment]
> So now the question of the day is - why is that different if we are presumably using the same ngx-launcher component? @vikram-raj any clue?

@bartoszmajsak It is different because we are not using the same create application modal component in OSIO. We have our own validation in OSIO.

**Comment by bartoszmajsak** [comment]
@vikram-raj why is that so? Shouldn't we share validation logic in the frontend? Backend relies on those restrictions so if we don't do that - we face issues exactly like this one.

@gastaldi is there a validation on the backend too? as @joshuawilson suggests - more contextual error messages would be handy here :)

**Comment by gastaldi** [comment]
@bartoszmajsak yes, there is validation in the backend too, using the Bean Validation annotations in https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/projectiles/context/OsioProjectileContext.java

**Comment by hrishin** [comment]
> Underline is not part of the naming requirements:

@bartoszmajsak jsak we are accepting only characters that are valid to form DNS URL. Since the project names used to construct DNS names; if invalid DNS characters appear then kubernetes/OpenShift fails to create service, route.

**Comment by hrishin** [comment]
> there a validation on the backend too?

This is how backend responds right with HTTP 401 status.

```json
[{"message":"projectName should follow the same pattern as a DNS-1123 subdomain and must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character","source":"projectName"}]
```

**Comment by joshuawilson** [comment]
I just looked over the code in the UI. It does not allow you to start with an underscore (or anything not alpha). It will allow you to use underscores in the name, just not doubled together). 

So you can create the space with that name but when you try to create an the backend doesn't allow it. 

We want to allow underscores in the name but we don't want to start with them. The reason is that the names are used in the URL and we use a leading underscore to indicate a special case. 

@gastaldi can you confirm that the backend blocks all underscores?

**Comment by joshuawilson** [comment]
> @bartoszmajsak yes, there is validation in the backend too, using the Bean Validation annotations in https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/projectiles/context/OsioProjectileContext.java

checking for `null` is not what i would call validation

**Comment by gastaldi** [comment]
@joshuawilson the following RegExp is used to validate the project name: https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/projectiles/context/OsioImportProjectileContext.java#L33

AFAIK underscores are not valid, so that may need to change

**Comment by joshuawilson** [comment]
Thanks. That regex line is the reason I think.

I don't know if there is an OpenShift or Che reason for not allowing underscores at all. I only know for sure we can't have them be the first character. 

@gorkem @aslakknutsen @jfchevrette @jmelis @pbergene can one you confirm what is allowed on OS?

**Comment by jfchevrette** [comment]
@joshuawilson k8s object names must meet rfc1123 DNS names specifications

ValidateNamespace
https://github.com/kubernetes/kubernetes/blob/6c9b854542619e2bdac0cfe489e9dd5dd89fb8a3/pkg/apis/core/validation/validation.go#L5052-L5059

https://github.com/kubernetes/apimachinery/blob/ed135c5b96450fd24e5e981c708114fbbd950697/pkg/api/validation/generic.go#L62

https://github.com/kubernetes/apimachinery/blob/ed135c5b96450fd24e5e981c708114fbbd950697/pkg/api/validation/generic.go#L44-L49

**Comment by joshuawilson** [comment]
ok, so I looked at the links and the spec and it doesn't appear to block/ban underscores

**Comment by joshuawilson** [comment]
If they are allowed then the backend should allow them, right?

**Comment by joshuawilson** [comment]
OK, we will update the UI to disallow underscores.
