### ISSUE TITLE
Lower the CPU request from 1 to .75 CPU

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#442]
Lower the CPU request from 1 to .75 CPUs
Leave the CPU limit at 1

related to https://github.com/openshiftio/openshift.io/issues/441

**Comment by kbsingh** [comment]
if we can, lets leave the cpu ask alone - let the cluster orchestration infra take care of scheduling and cpu assignment, and just focus on managing the RAM limit / ask.

**Comment by bmicklea** [comment]
@burrsutter, the suggestion from KB makes sense to try first. I'm going to lower this to P2 and we should re-evaluate once the RAM demands for projects are lowered.

**Comment by burrsutter** [comment]
Unable to fix.  The CPU setting is relative to the Memory setting.  They seem to mirror each other and @rawlingsj says that you can only change memory on OSO and CPU adjusts accordingly.
