### ISSUE TITLE
Consider making AGILE the default on the Space creation modal

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4427]
Consider making AGILE the default on the Space creation modal

**Comment by andrewazores** [comment]
Context: https://github.com/openshiftio/openshift.io/issues/4194#issuecomment-430224866

**Comment by jarifibrahim** [comment]
This was fixed in UI via https://github.com/fabric8-ui/fabric8-ui/pull/3371 and backend via https://github.com/fabric8-services/fabric8-wit/pull/2323.
