### ISSUE TITLE
Verify the Cleaning Steps

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#443]
Guaranteed Cleaning Steps - these steps put you back into a state that guarantees that the Helloworld Demo script and the Workshop Script will run again and again
- Manually delete all Che Workspaces
- Manually delete all Spaces
- Manually scrubs PVs (related to #375 James Strachan’s gofabric8 tool)
- download CLI from https://console.starter-us-east-2.openshift.com/console/command-line
oc login https://console.starter-us-east-2.openshift.com/
oc delete build --all -n burrzinga
oc delete bc --all -n burrzinga
oc delete cm burrzinga -n burrzinga
oc delete all --all -n burrzinga-stage
oc delete all --all -n burrzinga-run

**Comment by joshuawilson** [comment]
Do we need all the steps in #440 or a subset to clean up?

**Comment by jstrachan** [comment]
see https://github.com/openshiftio/openshift.io/wiki/FAQ#how-do-i-clean-up-all-apps-and-pipelines-in-my-openshift-online

**Comment by ldimaggi** [comment]
We are still having a disconnect here. 

* This issue lists the set of oc commands that clean a user's account. 
* The link that James referenced has the user execute the "gofabric8 tenant delete" command. 

Which approach do we want our users to follow?

(After executing either of commands, the user must perform an update tenant operation.)

**Comment by burrsutter** [comment]
All new cleaning steps

```
oc login https://console.starter-us-east-2.openshift.com/
oc get projects # this will tell you the project names to replace “burrzinga” below
oc delete all,pvc,cm,secrets,sa --all -n burrzinga-stage
oc delete all,pvc,cm,secrets,sa --all -n burrzinga-run 
oc delete all,pvc,cm,secrets,sa --all -n burrzinga-che
oc delete all,pvc,cm,secrets,sa --all -n burrzinga
oc delete all,pvc,cm,secrets,sa --all -n burrzinga-jenkins
```

**Comment by ldimaggi** [comment]
Also referenced here:
https://github.com/openshiftio/openshift.io/issues/440#issuecomment-320322604
