### ISSUE TITLE
Profile page: Clicking on Change password should open Reset your password screen

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#4434]
##### Expected Behaviour: 
On clicking Change password'  in the Edit profile page  (_Username_>Profile>Edit Profile) user should be directed to the 'Reset your password' screen directly 
![screenshot from 2018-10-16 15-43-58](https://user-images.githubusercontent.com/16647625/47079540-68e00400-d223-11e8-839b-224f4fd459f1.png)

##### Current Behaviour: 
When we click 'Change Password' in the profile page we see the 'Login page'. On clicking 'Forgot password' we see the 'Reset your password' screen.
![screenshot from 2018-10-16 15-43-12](https://user-images.githubusercontent.com/16647625/47079567-772e2000-d223-11e8-9751-8b321a85ea1e.png)

**Comment by alexeykazakov** [comment]
This issue seems to be outdated.
It currently opens https://developers.redhat.com/auth/realms/rhd/account/password which is exactly Change Password page.
Closing.
