### ISSUE TITLE
Beta: deployments page confusing when app has no deployments

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#4439]
##### Issue Overview

Deployments page (BETA feature) is confusing when containing just one application using the simplest pipeline (containing just "Build Image" step)

##### Expected Behaviour

Deployments page shows only space-related stats or explicitly says that it is about global resource usage.

##### Current Behaviour

Deployments page shows two resource usage widgets, none of them provides any clue of what data it shows. Probably displays data for stage & run env from different space even though this app doesn't deploy anything.

![osio_deployments](https://user-images.githubusercontent.com/445100/47084360-89a05d80-d213-11e8-8568-49786d91cd1b.png)

##### Steps To Reproduce

1. create space A and app with full pipeline
2. create space B and app with shortest pipeline (only "Build Image" step)
3. go to Create -> Deployments

##### Additional Information

Probably related to https://github.com/openshiftio/openshift.io/issues/3128

**Comment by joshuawilson** [comment]
@serenamarie125 how do you want to handle this?

**Comment by serenamarie125** [comment]
@joshuawilson based on the email thread held this week, there's been a decision to remove this Deployments page.  If that's the case, I assume we can close this?
