### ISSUE TITLE
Verify the recommendation of Chrome Guest or Incognito mode 

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#444]
We must work our way down from Guest, to Incognito, to everyday browser.
At this moment, end-users will face the recommendation that they should blow away all browser history for all time (hence the recommendation of Guest).
We have also seen that Che required Incognito for debugger to work

**Comment by burrsutter** [comment]
Incognito (not Guest) is needed for Che's Debugger.  The next question is does Incognito provide enough protection from having cached various openshift.io UI?

**Comment by joshuawilson** [comment]
I think the biggest risk with Incognito is that it shares session info across instances of Incognito. If you always close your Incognito window or at least only ever have one open at a time it should be enough to give you a clean browser.

**Comment by bmicklea** [comment]
+1 for incognito. @burrsutter and @joshuawilson - can we close this as confirmed?

**Comment by burrsutter** [comment]
+1 always close and re-open your Incognito browser between tests
