### ISSUE TITLE
Update Applications Tab status to reflect reality

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#445]
Green Check when:
- Pod is live and ready

Spinning when:
- a new Pod is being deployed

Red X when:
- Pod has failed its liveness probe 
- Pod has failed its readiness probe

Note: the pod may never pass its readiness probe related to #414

**Comment by bmicklea** [comment]
Relabelling as an enhancement

**Comment by joshuawilson** [comment]
cc @catrobson

**Comment by catrobson** [comment]
Will work on this as part of https://github.com/fabric8-ui/fabric8-ux/issues/655

**Comment by jstrachan** [comment]
BTW I've seen cases where the Service is created, the pod is Ready but the URL doesn't work. I think there may be some OSO load balancer issue too for new users maybe?

**Comment by bmicklea** [comment]
@jstrachan from a user POV "ready" would mean that the URL works so we'd want some way to identify if load balancer or other issues were preventing a seemingly ready pod from being user reachable.

**Comment by joshuawilson** [comment]
@catrobson how are the designs doing for this?
@burrsutter @qodfathr @burrsutter This is now a part of the Ginger train goals.

**Comment by catrobson** [comment]
@joshuawilson in progress on designs.  We'll have something to show this week to get review on.

**Comment by qodfathr** [comment]
Closing, as Application screen is going away in favor of revised Deployments screen.
