### ISSUE TITLE
UI calls Launcher Backend without X-App header causing JWT validation to fail

### ISSUE THREAD

**Issue by bartoszmajsak** [openshiftio/openshift.io#4453]
##### Issue Overview

We introduced [JWT validation in Launcher Backend](https://github.com/fabric8-launcher/launcher-backend/pull/557) and it seems Launcher Backend is called outside of the "wizard flow" without proper headers - causing token validation logic to fail.

A bit of a background here. Launcher Backend works in two modes - as a service for OSIO and Standalone Launcher. For this purpose `X-App` header is sent with `OSIO` or `Launcher` values accordingly. If no header is set it's defaulted to `Launcher`.

Now with the JWT validation, we have two different Auth solutions in place depending on the caller. For OSIO it's `fabric8-auth` and for Standalone Launcher it's RHD keycloak. Based on the `X-App` header, the proper key provider is called to validate the token's signature.

##### Expected Behaviour

Validates token against proper key provider - Fabric8 Auth in this case

##### Current Behaviour

Calls RHD keycloak to validate token signed by `fabric8-auth` resulting in "key not foud for kid" error

##### Steps To Reproduce

Try to promote app in pipeline view.

##### Additional Information

Error events https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/8970/ (notice no `X-App` header)

**Reverted from prod.**

**JWT logic in still on prod-preview.** (errors about missing `zD-57oBFIMUZsAWqUnIsVu_x71VIjd1irGkGUOiTsL8` key seen in sentry)

/cc @gastaldi

**Comment by bartoszmajsak** [comment]
Related issue https://github.com/openshiftio/openshift.io/issues/2093#issuecomment-430879277

**Comment by ppitonak** [comment]
@bartoszmajsak this looks like it should be covered by a contract test.

**Comment by bartoszmajsak** [comment]
Or any kind of test
