### ISSUE TITLE
Creating a project on Openshift.io throws 404

### ISSUE THREAD

**Issue by GeetikaBatra** [openshiftio/openshift.io#4459]
##### Issue Overview
Creating a project on Openshift.io throws 404.

##### Steps To Reproduce

1. Log In to Openshift.io
2. Click on Create
3. Click on a`add a code base`
4. Fill in the name of the project and select the checkbox `import an existing codebase`
5. Click on continue and you will see the following

![screenshot from 2018-10-18 13-50-14](https://user-images.githubusercontent.com/8664238/47140787-c4ba9380-d2dc-11e8-9fa1-2f8b00b8139c.png)

**Comment by GeetikaBatra** [comment]
Also, inspecting the source I see the following `{errors: [{code: "not_found", detail: "space with id 'Openshift_io' not found", status: "404",…}]}
errors: [{code: "not_found", detail: "space with id 'Openshift_io' not found", status: "404",…}]`

This is coming when it doesn't import the code.

**Comment by invincibleJai** [comment]
@GeetikaBatra are you using space "Openshift_io" intentionally? try with creating one of your own space

**Comment by vikram-raj** [comment]
Yes, @GeetikaBatra ```Add Codebase``` button should not be visible if the user is not an owner of the space.

Related: https://github.com/openshiftio/openshift.io/issues/2324

**Comment by GeetikaBatra** [comment]
Thanks @vikram-raj

**Comment by aptmac** [comment]
There's an open issue for this at: https://github.com/openshiftio/openshift.io/issues/3634

**Comment by joshuawilson** [comment]
closing as a duplicate
