### ISSUE TITLE
Che workspace name should come from IO when started from IO

### ISSUE THREAD

**Issue by bmicklea** [openshiftio/openshift.io#446]
When I create a workspace in IO for a codebase it is still given a random name in Che. It would be much more user friendly if the workspace name included the codebase name first. If necessary we could follow that with a dash and UID.

Today:
- OpenShift.io codebase name: `bradvertx`
- Associated Che workspace name: `nomjqa2c`

Should be:
- OpenShift.io codebase name: `bradvertx`
- Associated Che workspace name option 1: `bradvertx`
- Associated Che workspace name option 2: `bradvertx-nomjqa2c`

**Comment by l0rd** [comment]
@ibuziuk how hard would it be to implement that on che-starter?

**Comment by ibuziuk** [comment]
@l0rd codebase name is not passed to che-starter from wit, so it is not possible to implement without updating wit and changing API contract. What can be done easily it the following:
- project name + branch + workspace name `spring-boot-demo-master-nomjqa2c`

**Comment by l0rd** [comment]
@bmicklea would @ibuziuk proposal be ok?

**Comment by bmicklea** [comment]
@ibuziuk Where does workspace name come from?

**Comment by ibuziuk** [comment]
@bmicklea currently name is randomly generated on che-starter side

**Comment by bmicklea** [comment]
It's an improvement.

What's wit and is changing its API contract impactful to anything outside OSIO?

**Comment by ibuziuk** [comment]
@bmicklea wit = https://github.com/fabric8-services/fabric8-wit/, and API contract is used only between wit & che-starter e.g. can be changed on demand, so technically it is not a problem to make che-starter aware of codebase info:

> OpenShift.io codebase name: bradvertx
> Associated Che workspace name option 1: bradvertx
> Associated Che workspace name option 2: `bradvertx-nomjqa2c`
 
I would probably opt for option 2 with random postfix. WDYT ?

**Comment by bmicklea** [comment]
@ibuziuk yes let's go with option 2, it's safer.

**Comment by ibuziuk** [comment]
@bmicklea one last question to make sure that we are on the same page. Codebase name = repository name ?
![image](https://user-images.githubusercontent.com/1461122/30020502-4a7d1300-9164-11e7-9b57-e4bc3b791b9e.png)

e.g. for `redhat-developer/che-starter` expected workspace name is `che-starter-f8zbl2is`

**Comment by bmicklea** [comment]
Yes exactly

**Comment by ibuziuk** [comment]
@bmicklea firstly workspace name validation pattern should be changed upstream - https://github.com/eclipse/che/issues/6130

**Comment by ibuziuk** [comment]
PR[1] on che-starter side is merged but not updated on prod yet  (need to add workaround until new workspace name validation is changed upstream)

[1] https://github.com/redhat-developer/che-starter/pull/221

**Comment by ibuziuk** [comment]
workaround is pushed in prod. Workspace name = `repository name + random prefix` in general case,  but if the length of repository is more than 15 chars only random prefix is used as a name

**Comment by joshuawilson** [comment]
@bmicklea is this good enough? Can we close it?
