### ISSUE TITLE
I cannot see spaces where I am a collaborator on Spaces page

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4464]
##### Issue Overview

When I open Spaces page, there are only my spaces. I cannot see spaces where I am a collaborator. 

##### Expected Behaviour
I would like to see all spaces - mine and where I am a collaborator. They should be distinguished. 
##### Current Behaviour
I can see only mine spaces.

**Comment by aptmac** [comment]
Will be addressed by: https://github.com/openshiftio/openshift.io/issues/4326

**Comment by joshuawilson** [comment]
Closing as a dulicate
