### ISSUE TITLE
Running the Forge Wizard 3 times in a space results in zombie pipeline runs/builds

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#447]
https://www.screencast.com/t/XwqOMpunceBb

We have seen this bug in a few different iterations.  In this specific case, in a single Space, run the Wizard 3 times.  On the 2nd wizard execution, go have lunch, then Promote any outstanding pipelines that are hanging about.  Wait a moment, make sure it does not "come back to life" on its own.  
On the 3rd wizard run, you should see all 3 pipelines running when only the last one should be running

**Comment by burrsutter** [comment]
A different account, same problem 
https://screencast.com/t/ivIbQryxDP1

**Comment by rgarg1** [comment]
I've experienced a weirder problem. Running forge wizard twice in a space, first with quick-start, second with import-existing, brought back to life even deleted pipelines!! So a delete from OSO UI actually is not a delete.

**Comment by joshuawilson** [comment]
@rgarg1 that is correct, we have issues and stories about how we need to implement deleting.

**Comment by jstrachan** [comment]
think this is essentially a duplicate of #342

**Comment by rawlingsj** [comment]
This should be fixed with Jenkins 3.0.81 https://github.com/fabric8io/jenkins-sync-plugin/commit/db03e025f3519b6ad8dd75c7ed05d03847f920fd please reopen if not.
