### ISSUE TITLE
power icons for che and jenkins in the status menu are confusing

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#448]
Using the power off (greyed out power on/off icon) is IMO confusing for users. The expectation for this icon is that it is an actionable part of the UX. We click the icon/button to toggle power for the relevant instance. In this case, unless I'm mistaken, it's used to indicated the status of the instance and is static (cannot be clicked or otherwise toggled from this part of the UX at all), which is confusing. I would expect that we would use a status indicator (maybe a green tick mark icon or a red cross to indicate ready to use or not ready respectively) instead.

![power_button](https://user-images.githubusercontent.com/926572/28808599-b69eed7e-76c0-11e7-93d1-22a605fabdbc.png)

**Comment by qodfathr** [comment]
@catrobson @joshuawilson can you confirm that this has been addressed via new design, implemented, and released to prod?

**Comment by qodfathr** [comment]
Please also see #770 for related discussions.

**Comment by joshuawilson** [comment]
@catrobson I can you confirm?

**Comment by jiekang** [comment]
This has been completely removed in production. I think this issue can be closed. @joshuawilson Thoughts?

**Comment by joshuawilson** [comment]
This was removed. Closing.
