### ISSUE TITLE
Archive repos with dependences issues

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#4488]
We have been receiving a "GitHub security alert digest" on old repositories that
has security issues, afaik those are not used anymore.

Here is the list :

http://github.com/fabric8io/fabric8/network/alerts
http://github.com/fabric8io/shootout-docker-maven/network/alerts
http://github.com/fabric8io/data-mapper/network/alerts
http://github.com/fabric8io/insight/network/alerts
http://github.com/fabric8io/fabric8-ipaas/network/alerts
http://github.com/fabric8io/fabric8-devops/network/alerts
http://github.com/fabric8io/docker-client/network/alerts
http://github.com/fabric8io/kubeflix/network/alerts
http://github.com/fabric8io/django/network/alerts
http://github.com/fabric8io/mockwebserver/network/alerts
http://github.com/fabric8io/fabric8-profiles/network/alerts
http://github.com/fabric8io/fabric8-acceptance-tests/network/alerts
http://github.com/fabric8io/fabric8-jenkins-workflow-steps/network/alerts

Some of them are listed as critical, so unless there is a good reason to keep
those repos we should remove or fix them,

**Comment by chmouel** [comment]
@piyush-garg @hrishin @sthaha @rupalibehera @kishansagathiya 

any chances you go over this list and see if there is anyone used,

**Comment by chmouel** [comment]
I have archived all those repos,

**Comment by chmouel** [comment]
I am thinking to just have an empty commit there so nobody can actually depends on it,

**Comment by chmouel** [comment]
This is emptied and rearchived, here is the script used : 

```bash
set -x
set -e

LISTFILE=/tmp/list-of-repo-to-blank-archive.txt

base=/tmp/security
for i in $(cat ${LISTFILE});do
    b=$(basename $i)
    if [[  -e ${base}/${b} ]];then
        continue
    fi

    git clone ${i} ${base}/${b}

    cd ${base}/${b}
    git checkout -b archived-and-blanked
    find . -maxdepth 1 -not -name '.git' -not -name '.' -print0|gxargs -r0 rm -rf
    cat <<EOF>README.md
<aside class="notice">
This repository has been archived and resetted, you can still look at the git history for the old reference.
</aside>
EOF
    git add .
    git commit -a -m "Add information about archived repository"
    git push origin -u archived-and-blanked
    hub pull-request -o  -m "Archive repository and all its files"
done
```

**Comment by chmouel** [comment]
Unarchived [shootout-docker-maven](https://github.com/fabric8io/shootout-docker-maven/) since used,

**Comment by chmouel** [comment]
Archived more : 

https://github.com/fabric8-jenkins/fabric8-pipelines-plugin
https://github.com/fabric8-jenkins/fabric8-declarative-pipeline-step-functions-plugin
https://github.com/fabric8io/django-examples
https://github.com/fabric8io/fabric8-console

**Comment by chmouel** [comment]
archived as well : 

https://github.com/fabric8io/kubernetes-model/

**Comment by chmouel** [comment]
https://github.com/fabric8io/fabric8-e2e-pipeline-prod-preview/

**Comment by fkorotkov** [comment]
@chmouel `kubernetes-model` is used by `kubernetes-client`. Should it be still archived? What it the status of `kubernetes-model`?

**Comment by hrishin** [comment]
@fkorotkov its moved to [kubernetes-client](https://github.com/fabric8io/kubernetes-client/tree/master/kubernetes-model) repository it self.
