### ISSUE TITLE
Jenkins Proxy: ui_requests.go doesn't have unit tests

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#4490]
It is a critical part of the proxy code and we don't have unit test there.

I have added [some minimal test](https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/master/internal/proxy/ui_requests_test.go) for a PR sent but that's need proper unit testing.

Fabric8 Jenkins Proxy issue: https://github.com/fabric8-services/fabric8-jenkins-proxy/issues/336

**Comment by kishansagathiya** [comment]
Resolved with https://github.com/fabric8-services/fabric8-jenkins-proxy/pull/335
