### ISSUE TITLE
Blank page after login to prod-preview

### ISSUE THREAD

**Issue by jarifibrahim** [openshiftio/openshift.io#4493]
#### Issue Overview

Tell us briefly what the problem is about.

After login I see just a blank page

##### Steps To Reproduce

1. [step 1] - Login to prod-preview.openshift.io
2. [step 2] - Notice you get a blank page

Console log shows
![screenshot from 2018-10-25 12-31-52](https://user-images.githubusercontent.com/12949454/47481710-24bbb780-d852-11e8-8a99-e7bce26e3ca1.png)

**Comment by chmouel** [comment]
I am getting this as well 
![image](https://user-images.githubusercontent.com/98980/47482139-f92ad400-d835-11e8-8582-ca89a4194d98.png)

**Comment by joshuawilson** [comment]
I'm looking at it.

**Comment by jarifibrahim** [comment]
>@jarifibrahim how is this a SEV1? It is prod-preview. I understand and agree with it being a P1.

So is this a SEV 2? We have no workaround for the issue and I thought if an issue doesn't have a workaround it is a SEV 1.

**Comment by chmouel** [comment]
It's 3h30AM on the east coast, let's move it to SEV2 ;)

**Comment by ljelinkova** [comment]
@joshuawilson @chmouel  It was agreed some time ago that broken prod-preview is SEV-1.

**Comment by joshuawilson** [comment]
Severity is only for users of the system. They can only use production. This should be a SEV4 and P1.

**Comment by joshuawilson** [comment]
We are following https://access.redhat.com/support/policy/severity
It is a Users point of view not a devs point of view.

I could argue that prod-preview doesn't even get severity, just priority.

**Comment by ljelinkova** [comment]
@joshuawilson Let me quote you:
_We also agreed that something in prod-preview can be a SEV1 if pushing to prod will break prod._
https://github.com/openshiftio/openshift.io/issues/3853

**Comment by joshuawilson** [comment]
I concede.

**Comment by joshuawilson** [comment]
It's fixed.
