### ISSUE TITLE
Project name link under pipeline is broken

### ISSUE THREAD

**Issue by siamaksade** [openshiftio/openshift.io#450]
The link on the project name under the pipeline is broken. The link is specified as:
https://openshift.io/ssadeghi/vertexicator/create/pipelines

Clicking on **Pipelines** works though:
https://openshift.io/ssadeghi%40redhat.com/vertexicator/create/pipelines

<img width="445" alt="screen shot 2017-08-01 at 08 31 04" src="https://user-images.githubusercontent.com/1174934/28825385-f2413dd2-7693-11e7-9c48-dd8e78c2bb01.png">

**Comment by joshuawilson** [comment]
Thanks for pointing that out.

**Comment by c-koehler** [comment]
@siamaksade This may have been fixed, I'm able to follow the link when I run the latest version. Does this still happen for you?

**Comment by joshuawilson** [comment]
Closing as it appears fixed. If you continue to see this, please reopen.
