### ISSUE TITLE
Inner vertical scroll bar to view spaces list is broken

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#451]
1) Login to Openshift.io
2) Browse to the 'View all spaces' page by selecting the drop-down from the top left corner of the dashboard screen
3) Create more than 10 spaces
4) See that the page can only display 10 spaces. Rest of the spaces cannot be scrolled or viewed as the inner vertical scroll bar is greyed out.

**Comment by rgarg1** [comment]
![inner scroll bar disabled](https://user-images.githubusercontent.com/28748448/28828686-0a1e4f70-76ef-11e7-9269-ddccc17d14d6.png)

**Comment by joshuawilson** [comment]
@mindreeper2420 are we going to be putting this screen into the user profile?

**Comment by catrobson** [comment]
@joshuawilson We need to update the design to this page to allow users to see all spaces.  I expect we'll be doing views that equivalent to "spaces that I created or am a collaborator in", "spaces I have created", and "All public spaces" all on this page.

**Comment by joshuawilson** [comment]
ok, sounds good

**Comment by chrislessard** [comment]
This is an issue with our infiniteScroll component not getting triggered. It's brought up in https://github.com/openshiftio/openshift.io/issues/629 and there's a fix under review in https://github.com/fabric8-ui/fabric8-ui/pull/2324.

**Comment by chrislessard** [comment]
Can this be closed ? @joshuawilson

**Comment by joshuawilson** [comment]
This appears fixed, if this is still an issue please reopen.
