### ISSUE TITLE
Route flapping on 1a cluster results in broken e2e tests for Che

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#4511]
##### Issue Overview

Che workspace starts up, but agents are not responding (503 on all routes) and in a while,  "Workspace agent is not running" pops up.

Browser log: https://pastebin.com/8f5ELVxu

One of the interesting messages from browser console could be this:
```
/rhopp-osiotest2/wksp-36i3?uid=771334#uid=771334:1 Access to XMLHttpRequest at 'https://routeyeaztzae-rhopp-osiotest2-che.9a6d.starter-us-east-1a.openshiftapps.com/api/project-type' from origin 'https://che.openshift.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Also there is this error in che-server logs:
<details>

```
Unable to inject workspace workspaceb27pr7e5u9vr3s1t public keys. Error: java.io.IOException: Failed access: https://route7ydmddiw-rhopp-osiotest2-che.9a6d.starter-us-east-1a.openshiftapps.com/process?token, method: POST, response code: 503, message: <html>   <head>     <meta name="viewport" content="width=device-width, initial-scale=1">    <style type="text/css">   /*!    * Bootstrap v3.3.5 (http://getbootstrap.com)    * Copyright 2011-2015 Twitter, Inc.    * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)    */   /*! normalize.css v3.0.3 \| MIT License \| github.com/necolas/normalize.css */   html {     font-family: sans-serif;     -ms-text-size-adjust: 100%;     -webkit-text-size-adjust: 100%;   }   body {     margin: 0;   }   h1 {     font-size: 1.7em;     font-weight: 400;     line-height: 1.3;     margin: 0.68em 0;   }   * {     -webkit-box-sizing: border-box;     -moz-box-sizing: border-box;     box-sizing: border-box;   }   *:before,   *:after {     -webkit-box-sizing: border-box;     -moz-box-sizing: border-box;     box-sizing: border-box;   }   html {     -webkit-tap-highlight-color: rgba(0, 0, 0, 0);   }   body {     font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;     line-height: 1.66666667;     font-size: 13px;     color: #333333;     background-color: #ffffff;     margin: 2em 1em;   }   p {     margin: 0 0 10px;     font-size: 13px;   }   .alert.alert-info {     padding: 15px;     margin-bottom: 20px;     border: 1px solid transparent;     background-color: #f5f5f5;     border-color: #8b8d8f;     color: #363636;     margin-top: 30px;   }   .alert p {     padding-left: 35px;   }   a {     color: #0088ce;   }    ul {     position: relative;     padding-left: 51px;   }   p.info {     position: relative;     font-size: 15px;     margin-bottom: 10px;   }   p.info:before, p.info:after {     content: "";     position: absolute;     top: 9%;     left: 0;   }   p.info:before {     content: "i";     left: 3px;     width: 20px;     height: 20px;     font-family: serif;     font-size: 15px;     font-weight: bold;     line-height: 21px;     text-align: center;     color: #fff;     background: #4d5258;     border-radius: 16px;   }    @media (min-width: 768px) {     body {       margin: 4em 3em;     }     h1 {       font-size: 2.15em;}   }    </style>   </head>   <body>     <div>       <h1>Application is not available</h1>       <p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>        <div class="alert alert-info">         <p class="info">           Possible reasons you are seeing this page:         </p>         <ul>           <li>             <strong>The host doesn't exist.</strong>             Make sure the hostname was typed correctly and that a route matching this hostname exists.           </li>           <li>             <strong>The host exists, but doesn't have a matching path.</strong>             Check if the URL path was typed correctly and that the route was created using the desired path.           </li>           <li>             <strong>Route and path matches, but all pods are down.</strong>             Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.           </li>         </ul>       </div>     </div>   </body> </html>

```

</details>

Running query in kibana shows this startet happening two days ago (6.13 update was done 2 days ago):
https://logs.dsaas.openshift.com/goto/518ab9ab83e8611300c3e79757cc8630
![image](https://user-images.githubusercontent.com/1215011/47779182-c894df80-dcf8-11e8-865e-db330c2acee9.png)

##### Steps To Reproduce

1. Start workspace using user provisioned on 1a cluster
2. Observe workspace not working correctly (e.g. project is not imported, errors in browser console)

This issue is also affecting e2e tests (that's why the P1/SEV1 labels)

**Comment by ibuziuk** [comment]
This looks like an infrastructure issue for me since the tests are failing only against this particular cluster and passing on others, so rh-che update to 6.13.0 does not seem to be related to this problem.

@rhopp could you please deploy some app with a route to the dev cluster in order to figure out after how much time it becomes accessible ? some time ago I used the following project / resources [1] to identify the route flapping ?

@pbergene @jfchevrette do you happen to be aware of any known route related infra issues on `1a` ?

[1] https://github.com/ibuziuk/route-flapping/tree/master/resources

**Comment by rhopp** [comment]
I've reproduced this with my user on 1a and che workspace:
It seems, that the route is somewhat flapping:
Simple script:
```
#!/bin/bash
while true; do
    curl -s -o /dev/null -I -w "%{http_code}"  https://route7ydmddiw-rhopp-osiotest2-che.9a6d.starter-us-east-1a.openshiftapps.com
done
```

Output:
```
─rhopp@rhopp ~/Downloads  
╰─$ ./myScript.sh  
401
401
401
401
401
503
401
503
503
401
401
503
503
401
401
503
503
503
503
401
401
```

I'll try to deploy some simple pod with route to try to replicate that in simpler setup.

**Comment by rhopp** [comment]
Ok. The same thing happened with default Wildfly app deployed there:
```
╭─rhopp@rhopp ~/Downloads  
╰─$ ./myScript.sh  
503
503
200
200
503
503
200
200
503
503
200
200
503
503
200
200
503
503
200
200
503
```
It definitely seems like infra issue (@pbergene )

**Comment by pbergene** [comment]
Do you know what time perspective until it stabilizes? What is the current wait in che for the routes to become ready? 

Doing some bz archaeology turned up https://bugzilla.redhat.com/show_bug.cgi?id=1519918 from about a year ago, adding it in for completeness

**Comment by pbergene** [comment]
https://github.com/openshiftio/openshift.io/issues/1304 was the relevant osio issue at the time

**Comment by pbergene** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1522812 also

**Comment by pbergene** [comment]
Requested a router restart to see if that can help point in a direction.

**Comment by rhopp** [comment]
@pbergene The pod with wildfly app in it is currently running for ~37 minutes and the route flapping is still there.

**Comment by pbergene** [comment]
Ah, that's not the same then.  This sounds like one of the routers is out of sync permanently. Excellent issue description and reporting :)

**Comment by rhopp** [comment]
This seems to be resolved.

@pbergene Could that be prevented somehow? Does the team taking care of OSO clusters have some checks in place to catch such issues as soon as possible?

**Comment by pbergene** [comment]
Excellent. Thanks.  This "shouldn't" have happened.  I've asked for clarification whether or not monitoring catches this and will suggest they add it.

**Comment by ibuziuk** [comment]
@rhopp do you think we can close this issue now ?

**Comment by rhopp** [comment]
@ibuziuk Yes. Closing.

**Comment by pbergene** [comment]
Turns out the starter clusters have all been set in maintenance mode due to the ongoing upgrades, so this alert had been missed.

**Comment by ppitonak** [comment]
There were many 504s recently on cluster 1a since this issue was closed resulting in either creating a workspace in OSIO UI
![osio](http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1345/04-01-afterEach.png)
or when inside IDE waiting for workspace to start
![workspace](http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1351/04-01-afterEach.png)

Failed jobs:
* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1331
* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1345
* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1346
* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1350
* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1351
* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1352
* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1353
* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1354

**Comment by rhopp** [comment]
@ppitonak What you are reporting seems more like https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2400 to me.

**Comment by ppitonak** [comment]
OK
