### ISSUE TITLE
Failed mounts in tenant spaces - "invalid character 'm' looking for beginning of value"

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#4514]
##### Issue Overview

E2E tests are intermittently failing on jenkins not being woken up. 

After further investigation, it seems, that idler works correctly, but openshift fails to mount volume to jenkins pod with this message:
```
1m          12m          13        jenkins-1-s5gpt.1562de0340f3e687   Pod                                 Warning   FailedMount                   kubelet, ip-172-31-70-174.us-east-2.compute.internal   MountVolume.SetUp failed for volume "8b05f5c1-8ea6-4ce5-9b9b-aa04b8d8a9bb-03-ca" : invalid character 'm' looking for beginning of value
1m          10m          5         jenkins-1-s5gpt.1562de1fd42f1977   Pod                                 Warning   FailedMount                   kubelet, ip-172-31-70-174.us-east-2.compute.internal   Unable to mount volumes for pod "jenkins-1-s5gpt_osio-ci-e2e-005-jenkins(1166a22a-dd7b-11e8-867f-02d7377a4b17)": timeout expired waiting for volumes to attach or mount for pod "osio-ci-e2e-005-jenkins"/"jenkins-1-s5gpt". list of unmounted volumes=[jenkins-home]. list of unattached volumes=[jenkins-home jenkins-config jenkins-token-9rkb4]
```

Looking into kibana for this message it seems, that it affects not only jenkins unidling/starting, but there is also one instance, where the same error prevented che workspace to start (thus it's not only jenkins issue, but OSO one)
Kibana logs: https://logs.dsaas.openshift.com/goto/2b0092f33b9f624a69a8a6618101e433

First occurence of this is at 29. oct according to kibana.

I've tried to query few affected users - most of them are on cluster 2, but I've also seen some on other clusters - so it seems cluster independent (maybe I'm seeing most cluster 2, as this cluster has most active users on it?)

##### Expected Behaviour
PVC mount succeeds in 100% cases ;-)

##### Current Behaviour
PVC mount sometimes fails.

##### Additional Information

@pbergene I guess that's SD team responsibility, right? If not, please change labels to more appropriate team.

**Comment by pbergene** [comment]
Good find though! That error does look like something is explicitly going wrong.

**Comment by pbergene** [comment]
Adding the kubernetes.host field to your log query above shows that this seems to be happening on two nodes only.  This may be a bad assumption, but indicates that there could be storage client issues on those hosts.

**Comment by ldimaggi** [comment]
Is this the same problem as is described in:  #4451   ?

**Comment by rhopp** [comment]
@ldimaggi That seems like a different issue. #4451 has `exceeded quota` errors, this one is about `invalid character 'm' looking for beginning of value`

**Comment by JohnStrunk** [comment]
I haven't found a reference to that error message (kibana url doesn't work for me), but I have found a problem w/ one of the fuse mounts on the compute node. Currently awaiting node-level logs.

**Comment by pbergene** [comment]
There has been movement not reflected here.  The storage client had run into a segfault on a couple of nodes.  As there was an upgrade happening the nodes have been rebooted and this should be resolved.

**Comment by ppitonak** [comment]
@rhopp can we close this issue?

**Comment by rhopp** [comment]
@ppitonak I guess so. Kibana show no occurrence of this. Closing.
