### ISSUE TITLE
Deployments API responding 500s on some requests

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#4515]
### Issue Overview

Requests to the `https://openshift.io/api/deployments/spaces/{spaceId}/applications/{appName}/deployments/{envName}/statseries` are (at least in some scenarios - it's 100% on my deployments, ex. `https://openshift.io/api/deployments/spaces/7ac6e4be-dcf2-4635-9ca1-1ae3a69e2ff9/applications/demo-2/deployments/stage/statseries?start=1541098721220&end=1541099621220`) responding with 500s, rather than 200 and a meaningful JSON response body. This causes the timeseries charts within the expanded Deployment cards to be blank.

### Steps to reproduce:

1. Create a Space, an Application, etc., and wait until a deployment makes it through the pipeline to at least the Stage environment
2. Visit the Deployments page. If a deployment already existed prior to step 1, then ensure that the deployment has at least 1 pod scaled

![deployments-500](https://user-images.githubusercontent.com/3787464/47874427-29e8ab80-ddea-11e8-907f-72ed578b5a3c.png)

**Comment by alexeykazakov** [comment]
Outdated. Closing.
