### ISSUE TITLE
Importing an existing repo does not show up in the dashboard

### ISSUE THREAD

**Issue by siamaksade** [openshiftio/openshift.io#453]
When importing an existing GitHub repository, the project gets imported correctly and a pipeline gets created on OpenShift but in the openshift.io dashboard it does not show up. 

Here is the pipeline that is created and executed:
<img width="1052" alt="screen shot 2017-08-01 at 09 15 31" src="https://user-images.githubusercontent.com/1174934/28831233-0b33d288-76a7-11e7-8454-939c61417ac3.png">

No trace of it in the openshift.io dashboard:
<img width="1371" alt="screen shot 2017-08-01 at 10 44 13" src="https://user-images.githubusercontent.com/1174934/28831260-1c1cd0ea-76a7-11e7-9388-9d00b1493690.png">

The existing GitHub repo is originally generated by openshift.io going through the **Create new quickstart project** flow: https://github.com/siamaksade/osio-test-vertexicator

**Comment by joshuawilson** [comment]
This is something we are working on and is related to #430.

**Comment by ldimaggi** [comment]
See:  https://github.com/fabric8-ui/fabric8-ui/issues/1678

**Comment by jstrachan** [comment]
it should be working now; is this still an issue for you? 

Can you look at the imported project in the openshift console to find the underlying `BuildConfig` and see its labels and see if it has a `space` label? 

If so the value of the `space` label is the Space you need to be inside in the OpenShift IO console to see the Pipeline. Right now the OpenShift IO console filters all Pipelines by the `space` label; so you can only see pipelines with the same space label that you have selected to view in the OpenShift IO console

**Comment by joshuawilson** [comment]
Closing, if this is still an issue please reopen.
