### ISSUE TITLE
Changes in WIT/Che-starter for using stacks in Che 7 

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#4537]
OSiO Che team and ToolChain backend team to discuss changes needed for Che 7 to work with OSiO

**Comment by ibuziuk** [comment]
I have created an issue on che-starter side - https://github.com/redhat-developer/che-starter/issues/316
Basically, first thing that needs to be done is defining API endpoints on che-starter side. Currently, any work  related to che 7 support in che-starter is not planned and is not a priority for the upcoming sprints. I will comment once Che OSIO team will start planning this work

**Comment by sbose78** [comment]
Thanks @ibuziuk .
I wouldn't mind dedicating engineering time on our side to make changes on che-starter if needed, as long as we have a 'todo' list of changes in place.

**Comment by ibuziuk** [comment]
Closed accidentally. Reopening

**Comment by ibuziuk** [comment]
@sbose78 wdyt about closing this issue as outdated / won't fix?

**Comment by ibuziuk** [comment]
@sbose78  @jarifibrahim Closign as won't fix. Feel free to reopen with details
