### ISSUE TITLE
Add Che debug commands for IO quick start project types

### ISSUE THREAD

**Issue by bmicklea** [openshiftio/openshift.io#454]
We have two project types that users can start with in IO: Vert.x and spring boot. We need to add debug commands that appear by default when a Che workspace is started from IO.

Tasks:
- [ ] Add new "Debug" command to Vert.x projects
- [ ] Add new "Debug" command to Spring Boot projects

**Comment by bmicklea** [comment]
@l0rd I think you were working on this but didn't want to assign it to you explicitly in case I was wrong.

**Comment by l0rd** [comment]
@bmicklea No I'm not working on that. I was working on a couple of PRs [1](https://github.com/eclipse/che/pull/5835)[2](https://github.com/redhat-developer/rh-che/pull/236) that are now (almost) done so I will probably fix [this one tomorrow](https://github.com/openshiftio/openshift.io/issues/416).

@bmicklea I don't know if that applies here but we open che related issues [here](https://github.com/redhat-developer/rh-che/issues). Or we duplicate them there if there is a need to have it on openshift.io. That makes it easier to include them in our [sprint backlog](https://github.com/redhat-developer/rh-che/issues/197).

**Comment by bmicklea** [comment]
Thanks @l0rd - I've cross-posted to the rh-che repo: https://github.com/redhat-developer/rh-che/issues/238

**Comment by benoitf** [comment]
https://github.com/redhat-developer/rh-che/issues/238 is closed so this issue should be closed as well ?

**Comment by joshuawilson** [comment]
@bmicklea can you confirm?

**Comment by l0rd** [comment]
Debug commands for both vertx and spring-boot stacks are available on OSIO. I'm closing this issue @bmicklea feel free to reopen.
