### ISSUE TITLE
Creating a new workspace is requiring user to login again

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#4545]
##### Issue Overview
When a user adds a new project to a space in OpenShift.io, the user is given the option of creating a new workspace in Che. If the user opts to create that new workspace in Che, the user is prompted to login to OpenShift.io again. This is a change to the path/flow in the UI.

##### Expected Behaviour
The expected, and previous behavior is that the user, when creating a new Che workspace, is not prompted to re-login to OpenShift.io.

##### Current Behaviour
When the user creates a new workspace in Che, the user is prompted to login to OpenShift.io again, even though he/she is already logged in.

##### Steps To Reproduce

1. Create new space, add project to space in OpenShift.io
2. Attempt to create a new Che workspace

##### Additional Information

![screenshot from 2018-11-14 15-59-18](https://user-images.githubusercontent.com/642621/48512740-3f1cfb80-e828-11e8-9d9a-30824968d276.png)

![screenshot from 2018-11-14 15-59-35](https://user-images.githubusercontent.com/642621/48512743-3f1cfb80-e828-11e8-92e6-a1922c6ddc16.png)

**Comment by ibuziuk** [comment]
@ldimaggi I can not reproduce. Does it happen every single time for you ?

**Comment by ibuziuk** [comment]
Probably the issue is simlar to  https://github.com/openshiftio/openshift.io/issues/2587 but currently I can reproduce none of them

**Comment by ldimaggi** [comment]
Closing as no longer reproducible.
