### ISSUE TITLE
Creating a new Thorntail project fails with a Forge error

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#4546]
##### Issue Overview
Creating a new project with the Thorntail runtime fails with a 500/server error.

##### Expected Behaviour
It should be possible for users to create new projects configured with the Thorntail runtime.

##### Current Behaviour
This error results:
```
Http failure response for https://forge.api.openshift.io/api/osio/launch: 500 Internal Server Error
```

##### Steps To Reproduce

1. Create new space and new project
2. For the project, select Mission = REST, and runtime = Thorntail
3. When the user starts the project creation, after selecting runtime, mission, and release strategy, the error results.

##### Additional Information
Seeing this on production - not seeing this on prod-preview.

![screenshot from 2018-11-14 16-38-44](https://user-images.githubusercontent.com/642621/48514461-5bbb3280-e82c-11e8-85ff-86f2d47bd558.png)

**Comment by ldimaggi** [comment]
If, after encountering this issue, the user attempts to then create a Vert.x or Springboot app, the same error occurs. Logging out and then back in seems to clear the error.

**Comment by joshuawilson** [comment]
@gastaldi is this an error you recognize?

**Comment by gastaldi** [comment]
@joshuawilson I just redeployed a new backend version. @ldimaggi Can you please try to reproduce the error again?

**Comment by gastaldi** [comment]
I see this error in Sentry: https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/9275/ is the Analytics Service down?

**Comment by gastaldi** [comment]
Looks like https://github.com/fabric8-launcher/launcher-backend/pull/564 can be merged now

**Comment by ldimaggi** [comment]
Seems to be working now - I wonder why only thorntail was affected?

**Comment by gastaldi** [comment]
No clue, but feel free to close this issue and reopen if the problem
reappears

Em Qua, 14 de nov de 2018 21:34, Len DiMaggio <notifications@github.com
escreveu:

**Comment by ldimaggi** [comment]
Closing in favor of:
https://github.com/openshiftio/openshift.io/issues/4547

**Comment by piyush-garg** [comment]
Seems like duplicate of #4539
