### ISSUE TITLE
Create -Pipelines view does not show the link to URL for "Rollout to Stage"

### ISSUE THREAD

**Issue by VeerMuchandi** [openshiftio/openshift.io#456]
I am following this video https://vimeo.com/227620767
At 5:05 mins into this video there is a URL for "Rollout to Stage". I don't see that on my screen. 

But, the URL for "Rollout to Run" at 5:25 comes up!!

**Comment by VeerMuchandi** [comment]
![pipelineview](https://user-images.githubusercontent.com/6510975/28849808-ddd69038-76e6-11e7-92d2-faf6f2e4fc07.jpeg)

This is the view on my screen You won't see the URL for "Rollout to Stage"

**Comment by qodfathr** [comment]
xref #508

**Comment by ldimaggi** [comment]
The E2E tests do look for the link - it sounds like this problem pops up now as multiple people have seen it...infrequently.

This issue is a dup of #456

**Comment by qodfathr** [comment]
@ldimaggi did you mean #508 or #585? I don't think this issue is a dupe of itself. :)

**Comment by ldimaggi** [comment]
Yes - that is #508.
