### ISSUE TITLE
Sometimes namespace of type 'user' is missing for some, which results in failures during workspace startup 

### ISSUE THREAD

**Issue by tolusha** [openshiftio/openshift.io#4564]
##### Issue Overview
When I start workspace I observe such an error:
`Failed java.lang.RuntimeException: No namespace with type 'user' was found in the user tenant`
Resetting env didn't help me. It seems to be problem with my account.

##### Steps To Reproduce

1. Go to che.openshift.io
2. Start workspace from any stack

##### Additional Information

 * Google Chrome | 67.0.3396.99 (Official Build) (64-bit)

![screenshot from 2018-11-20 12-03-32](https://user-images.githubusercontent.com/1640675/48766111-60646880-ecbc-11e8-8723-24d11b09e16a.png)

@ibuziuk @garagatyi

**Comment by sbose78** [comment]
Looks like your initial account setup didn't complete.

**Comment by gorkem** [comment]
@sbose78 @tolusha This needs some labels

**Comment by ibuziuk** [comment]
@alexeykazakov we have similar issue in - https://github.com/redhat-developer/rh-che/issues/1043 
Could someone form the platform team investigate the root cause ?

**Comment by alexeykazakov** [comment]
@MatousJobanek please take a look.

**Comment by alexeykazakov** [comment]
@tolusha what's your username?

**Comment by tolusha** [comment]
@alexeykazakov 

`abazko`

**Comment by ibuziuk** [comment]
@tolusha could you please try this again and let me know if you can start a workspace ?

**Comment by tolusha** [comment]
Everything works fine.

The list of namespaces:
- `abazko`
- `abazko-che`
The workspaces are being created under `abazko-che` namespace.
