### ISSUE TITLE
Build: Check that environment is present before creating a pipelineenv

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#4566]
We currently have a function for this but this doesn't check for environment :

https://github.com/fabric8-services/fabric8-build/blob/ae6e40cb34a75f477e5d25dd8e37dfc2ffbc050d/controller/pipeline_environments.go#L30-L38

We would need to query fabric8-env for this.

We may need to have to solve openshiftio/openshift.io#4561 first to be able to
pass a JWT token to fabric8-env

Fabric8 Build issue: https://github.com/fabric8-services/fabric8-build/issues/93

**Comment by piyush-garg** [comment]
Fixed with https://github.com/fabric8-services/fabric8-build/pull/123
