### ISSUE TITLE
Optimise plugin disk space in Jenkins

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#4568]
The plugins directory consume over 383Mb out of 478mb and is copied over and over everywhere which cause a scale issue on the gluster volumes,

Longer discussion here :

https://chat.openshift.io/developers/pl/ic6z8bppkbf8jb78z8bhsoispe

**Comment by chmouel** [comment]
More discussions and investigation here: 

https://chat.openshift.io/developers/pl/sm4bacg41iye3bwn3cau4hwr7r

patch to symlink the hpi/jpi instead of copying https://github.com/fabric8-jenkins/jenkins-openshift-base/pull/49 saves around 187mb

**Comment by chmouel** [comment]
Symlink directory into the image saves us 358MB in total,

**Comment by ppitonak** [comment]
"In total" is confusing... Is it 358 MB per user or per cluster?

How will symlink handle various versions of Jenkins?

**Comment by chmouel** [comment]
> "In total" is confusing... Is it 358 MB per user or per cluster?

there is no global plugins 'folder' in our infrastructure so it is per user,

> How will symlink handle various versions of Jenkins?

I am not sure i understand your question, did you read the patch?

**Comment by hrishin** [comment]
Some observations for the [sym link](https://github.com/fabric8-jenkins/jenkins-openshift-base/pull/49) patch

**Plugin management:**
1) installed artifcatory plugin from plugins.txt
plugin worked :heavy_check_mark: 
plugins size

First boot
```
sh-4.2$ du -hs /var/lib/jenkins/plugins/
247M    /var/lib/jenkins/plugins/
```



2) installed prometheous plugin (without restart option) from Jenkins admin conosle 
plugin worked :heavy_check_mark:  
plugins size

First boot (without restarting jenkins)
```
sh-4.2$ du -hs .
216M	
```



3) installed MSBuild plugin (with restart option) from jenkins admin console
Plugin worked :heavy_check_mark: 
plugins size

After the first boot  but jenkins process restarted in running pod
```
217M	/var/lib/jenkins/plugins/
```

------------------------------------------------------------------------
after second boot (scaling jenkins pod down and up)

without `rm -rf  plugins`

```
sh-4.2$ du -hs /var/lib/jenkins/plugins/
26M     /var/lib/jenkins/plugins/
```

with `rm -rf  plugins`

```
sh-4.2$ du -hs /var/lib/jenkins/plugins/
247M    /var/lib/jenkins/plugins/
```

**Basic test**
1) Run the pipeline builds 
In all cases it worked well :heavy_check_mark:

**Comment by hrishin** [comment]
Yes @chmouel we have tested by deploying a new version of `sync-plugin`, Jenkins was able to pick it up.

I was not able to run pipelines, as jenkins is behaving wiredly due to idler issue. Rest of behavior stays same as per previous observation.

**Comment by piyush-garg** [comment]
Tenant update has been done. Closing this,

**Comment by hrishin** [comment]
@pbergene could we confirm if this issue has fixed with recent tenant update? It should drop the gluster storage usage(Not able to make grasp looking at Zabbix). If not feel free to reopen this issue. Thank you

**Comment by hrishin** [comment]
Can see some reduction in gluster storage usage.

@chmouel @sthaha 

![image](https://user-images.githubusercontent.com/28615674/51324513-f0424b00-1a90-11e9-9fff-0610b9f051e3.png)

**Comment by chmouel** [comment]
Really nice! 😍 

Great work 💪

**Comment by pbergene** [comment]
Good job indeed! We have a couple of graphs which show it even more dramatically.  The device space also contains snapshots and is not a direct measure of space used by PVs, but we can clearly see the updates go in with this one :)

**Comment by hrishin** [comment]
Thanks @pbergene ! for giving confimation.

**Comment by chmouel** [comment]
@hrishin We need to plan for merging a better looking (i.e: not hack) patch to jenkins upstream, since they are affected as well and we want to consume their images asap, 

/cc @arilivigni
