### ISSUE TITLE
Application is created in wrong space

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4569]
##### Issue Overview
When you are on the dashboard of some space and create a new space and a new application (using top left menu), the new application is created in the old space. 
##### Expected Behaviour
The application should be created in the new space
##### Current Behaviour
The application is created in other (old) space
##### Steps To Reproduce
1. Create new Space_A and using the same wizard create ApplicationA
2. On the result page of launcher press "Return to Dashboard"
3. In the top left popup menu select Create space
4. Create Space_B and using the same wizard create ApplicationB
5. On the result page of launcher press "Return to Dashboard"
6. You are taken to the dashboard of Space_B (correct) but there is no application or pipeline. 
7. Show dashboard of Space_B
8. Application and pipeline for ApplicationB is on Space_A dashboard

**Comment by joshuawilson** [comment]
Confirmed. That is very odd.

**Comment by joshuawilson** [comment]
@sbose78 @bartoszmajsak This looks like it is something not getting reset in the getting started launcher.

**Comment by joshuawilson** [comment]
I think this has to do with the UI holding the Context of the space and not refreshing it.
