### ISSUE TITLE
Create - Pipelines Pipeline inputs not taken

### ISSUE THREAD

**Issue by VeerMuchandi** [openshiftio/openshift.io#457]
Running the example as in this video https://vimeo.com/227620767
It includes a step where pipeline waits for user input at 05:21 mins. When I do it in my OSIO "Create->Pipelines" view, pressing on "promote" button does nothing. I tried many times.
Ultimates, I had to go to Jenkins using "Build Logs" and press on "Promote" link there to move the pipeline forward.

**Comment by VeerMuchandi** [comment]
Of course, I am running with Chrome Incognito

**Comment by qodfathr** [comment]
This is an old issue and seems to be fixed. Please reopen if you disagree.
