### ISSUE TITLE
Remove the tables cleanups

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#4576]
This code :

https://github.com/fabric8-services/fabric8-build/blob/17be754902018aec1f789cf6a7023fd6de133aff/controller/pipeline_environments_blackbox_test.go#L51-L56

and this code :

https://github.com/fabric8-services/fabric8-build/blob/17be754902018aec1f789cf6a7023fd6de133aff/build/pipelineenv_blackbox_test.go#L34-L39

is not needed anymore, since DBTestSuite row cleanup works properly now,

**Comment by piyush-garg** [comment]
Closed in https://github.com/fabric8-services/fabric8-build/pull/102
