### ISSUE TITLE
Email - Task update email notification has hexadecimal value for comment

### ISSUE THREAD

**Issue by navidshaikh** [openshiftio/openshift.io#458]
Email notifications is useful, would like to report few things I noticed.
Every time I add a comment to card, OSIO sends notification email with `Comment` field, though it has value not exactly what commentator has put, but a hexadecimal value.

Here are sample strings I received in email 
```
0xc4204674b0
0xc42044bf60
```

Tried checking the string,
```
In [1]: int("0xc4204674b0", 16)
Out[1]: 842355078320

In [2]: int("0xc4204674b0", 8)
```

Also the commentator photo in email needs scaling!

**Comment by joshuawilson** [comment]
@aslakknutsen can you please take a look at this

**Comment by navidshaikh** [comment]
Started getting emails with correct comment value. Also +1 for not sending user image but only name. Closing the issue.

**Comment by aslakknutsen** [comment]
The comment issue was fixed as part of https://github.com/fabric8-services/fabric8-notification/issues/29, tracking the profile image size here; https://github.com/fabric8-services/fabric8-notification/issues/31
