### ISSUE TITLE
 The Add Collaborator feature in the dashboard should be Add Collaborators

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#4580]
For consistency:

We should have 'Add Collaborators' on the dashboard instead of 'Add Collaborator' to keep it consistent with the dialog box which says 'Add collaborators'. Keeping it plural makes sense since we can add multiple collaborators at once.
In the dialog box 'collaborators' should be 'Collaborators'.
add_collaborators
![add_collaborators](https://user-images.githubusercontent.com/16647625/48944611-658c1680-ef4d-11e8-8adb-06ca1cbe925c.png)

**Comment by rohitkrai03** [comment]
Fixed in https://github.com/fabric8-ui/fabric8-ui/pull/3426
