### ISSUE TITLE
Add Pin feature in the Spaces page does not work

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#4581]
The Add Pin option in the kebab menu to the right of a space, does not pin the space nor move it to the top of my list:

![screenshot from 2018-11-23 18-28-58](https://user-images.githubusercontent.com/16647625/48944735-fb27a600-ef4d-11e8-808c-bce9d03564cc.png)

**Comment by joshuawilson** [comment]
@sbose78 do we have a way to store/save this info? Just asking if there is an API to support it yet. 

cc @alexeykazakov

**Comment by rohitkrai03** [comment]
@joshuawilson We are using `contextInformation` in profile data to save pinned space info. But it seems pinning logic is broken and its not sending proper data back to backend for saving. I'll look into it.
cc: @sbose78
