### ISSUE TITLE
Build: Permission denied when deploying the dockerfile binary

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#4585]
Getting this when deploying the docker image on openshift :

```
pmcd: PID = 7, PDU version = 2
pmcd request port(s):
sts fd   port  family address
=== ==== ===== ====== =======
ok     5       unix   /var/run/pcp/pmcd.socket
ok     3 44321 inet   INADDR_ANY
ok     4 44321 ipv6   INADDR_ANY
[Mon Nov 26 12:47:45] pmcd(7) Info: PMNS file "DEFAULT" is unchanged
/fabric8-build+pmcd.sh: line 52: /usr/local/build/bin/fabric8-build: Permission denied
```

intersingly this only happen on openshift and not when running with docker directly,

Fabric8 Build issue: https://github.com/fabric8-services/fabric8-build/issues/116

**Comment by sbose78** [comment]
I had done this as a workaround to proceed.
https://github.com/fabric8-services/build-tool-detector/commit/8495051288dd8e289a396be9a4be19ba571fcde2

**Comment by chmouel** [comment]
@sbose78 I have already that script set as 0755, It seems that because I get the directory create as 0700 owned to the build user, 

since k8/openshift runs don't respect the USER direcive,it with use random uuid and we can't access it 

Not sure why i didn't have this before, but moving the binary to /bin 'fixed' the issue,

**Comment by chmouel** [comment]
Ah perhaps that's a behavior from 'buildah'! since i didn't have that when building with 'docker'
