### ISSUE TITLE
Jenkins Idler: Remove regexp based free starter cluster detection

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#4588]
We now have an API :

https://github.com/fabric8-services/fabric8-cluster/issues/31

which we can use and remove the [regexp based](https://github.com/fabric8-services/fabric8-jenkins-idler/blob/ebf73b784db1341c44307c8424eb51ac1f679769/internal/cluster/service.go#L22-L28) filtering

There is other things to do in this area, we want to have idler only enabled for those OSO clusters
but we don't want to simply ignore the others, we want to be able to pass thru the  requests
still  but instead of going to idler we want to go to the user jenkins directly.

See details here: https://github.com/openshiftio/openshift.io/issues/4574

this is a work for jenkins-proxy and jenkins-idler

Fabric8 Jenkins Idler issue: https://github.com/fabric8-services/fabric8-jenkins-idler/issues/306

**Comment by kishansagathiya** [comment]
Instead of using fabric8-clusters API directly, we can make changes to the `/clusters` endpoint of f8-auth that proxies to f8-clusters. That would be the right thing to do and will also save a lot of work for idler and proxy

**Comment by piyush-garg** [comment]
Closed with https://github.com/fabric8-services/fabric8-jenkins-idler/pull/329
