### ISSUE TITLE
The pipeline page on OSO is flickering

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#459]
Send this defect to OSO, but first watch the video. Using chrome in Incognito mode and this started after running gofabric8 cleanup tool.

**Comment by rgarg1** [comment]
[flickering.webm.zip](https://github.com/openshiftio/openshift.io/files/1193523/flickering.webm.zip)

**Comment by rgarg1** [comment]
Play with VLC or any other supported player.

**Comment by rgarg1** [comment]
The problem lies with 'internal-clean-mvn-local-repo' as it keeps disappearing and reappearing.

**Comment by joshuawilson** [comment]
@kbsingh how do we log bugs with OSO?

**Comment by joshuawilson** [comment]
This is not OSO, please log the issue with them. Closing.
