### ISSUE TITLE
Remove redundant API calls in my spaces page

### ISSUE THREAD

**Issue by karthikjeeyar** [openshiftio/openshift.io#4597]
##### Issue Overview

My spaces page calls the same API endpoints multiple times, causing the lag in the page load time.

##### Expected Behaviour

There should not be redundant calls to the same API endpoints from the same component and page load time should be decreased.

##### Current Behaviour

Multiple calls to the same API endpoint resulting in slower page loads.

![image](https://user-images.githubusercontent.com/9964343/49291210-85808480-f4cf-11e8-9435-786f126c974c.png)

##### Steps To Reproduce

1. navigate to spaces page from top navigation menu.

**Comment by joshuawilson** [comment]
Please talk to @christianvogt about this.
