### ISSUE TITLE
jenkins throws 401 even when the user is logged in.

### ISSUE THREAD

**Issue by jarifibrahim** [openshiftio/openshift.io#4599]
##### Issue Overview
Clicking on `view log` (or any other jenkins URL) fails with 
```json
{
  errors: [
    {
    code: "unauthorized_error",
    detail: "unauthorized access",
    status: "401",
    title: "Unauthorized error"
    }
  ]
}
```
The above error was thrown by auth.prod-preview.openshift.io

##### Expected Behaviour
User should automatically be logged in (or shown a login page) when clicked on a jenkins URL.

##### Current Behaviour
Login on jenkins fails with `unauthorized` error

##### Steps To Reproduce

Not sure if the following steps caused the error (they don't seem related)

1. Import codebase (I was using https://github.com/nodeshift-starters/nodejs-rest-http-crud)
2. Replace Jenkinsfile with https://github.com/fabric8io/fabric8-jenkinsfile-library/blob/master/node/ReleaseStageApproveAndPromote/Jenkinsfile
3. Once the builds starts click on `view logs`. 

##### Additional Information

I tried to open jenkins via the URL in openshift console but that too fails with the same `unauthorized` error.

**Comment by jarifibrahim** [comment]
I could access jenkins in incognito mode. 

This could be because old session/cookie data being used by the UI.

**Comment by christianvogt** [comment]
I tried to reproduce this without success.
Moving to auth team to further investigate as this is apparently an intermittent issue.

**Comment by alexeykazakov** [comment]
Auth can’t investigate every 401. Really. We get too many of them and that’s expected. If it works In incognito mode it means there is an issue in UI somewhere most likely. Or in jenkins login since as I know it uses cookies too.  
@jarifbrahim could you please provide more details. What endpoint returns 401. Any missing or invalid Autherization headers in the request?

Meanwhile I’m assigning it to build-cd to see if they can spot any issue in Jenkins login.

**Comment by jarifibrahim** [comment]
@alexeykazakov I can't reproduce it right now but I've seen this failure more than a few times.

**Comment by piyush-garg** [comment]
@jarifibrahim If you are not able to reproduce this, can we close this. Maybe we reopen it whenever happens again with all the details. Thanks

**Comment by jarifibrahim** [comment]
@piyush-garg Thanks
