### ISSUE TITLE
Dashboard expects a pipeline with the same name as the space name

### ISSUE THREAD

**Issue by siamaksade** [openshiftio/openshift.io#460]
When creating a new project from a quickstart, the default github repo name is the space name (awesome-space in my test). If I change the github repo name (to osio-test-wheretex in my test), the repository is created correctly but two pipelines gets created on openshift, one with the github repo name and another with the space name. The OSIO dashboard expects a pipeline with the same name as the space name and there is confused about the status of the pipeline:

<img width="451" alt="screen shot 2017-08-02 at 07 37 14" src="https://user-images.githubusercontent.com/1174934/28872731-7119e89c-7758-11e7-8d7b-9d31aff1f01c.png">

Two pipelines get created and the one with the repo name is triggered while the dashboard shows the one with the space name:

<img width="1023" alt="screen shot 2017-08-02 at 07 53 26" src="https://user-images.githubusercontent.com/1174934/28872773-a427d28a-7758-11e7-9de4-471039a66adf.png">

**Comment by joshuawilson** [comment]
cc @burrsutter @jstrachan

**Comment by qodfathr** [comment]
Fixed.
