### ISSUE TITLE
Space name is not cleared in Create space dialog and you cannot create second space

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4612]
##### Steps to reproduce
1. Create new space with name XYZ (with or without application)
2. Open Create new space dialog again - the space name is filled with name XYZ
3. You are not able to create any space even if you change the name (the Create Space buttons are disabled)

**Comment by ppitonak** [comment]
@vikram-raj caused by your recent commits.

**Comment by vikram-raj** [comment]
I am looking into.
