### ISSUE TITLE
Create and app: form state is not reset on cancel

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#4616]
##### Issue Overview

The state of dialog "Create an Applicatiion" is not reset on cancel.

##### Expected Behaviour

State of form is reset

##### Current Behaviour

State is not reset, causes unexpected behavior

![osio_create_app](https://user-images.githubusercontent.com/445100/49581318-cc4bff80-f951-11e8-8b94-a82b6f01d4f2.gif)

##### Steps To Reproduce

1. open https://prod-preview.openshift.io
2. create a space
3. click "Add to Space", type some name, click "Create a new codebase"
4. click Cancel
5. click "Add to Space", type some name - **it's possible to click on Next because it remembers the "Create a new codebase" option"**
6. click "Next" - **spinner is diplayed, never finishes"**
7. close the dialog
8. click "Add to Space" - **spinner in the Next button is still spinning**

##### Additional Information

@vikram-raj @joshuawilson

**Comment by ljelinkova** [comment]
Would it be possible to use modal dialog events to reset the form? Like it is described here:

https://valor-software.com/ngx-bootstrap/#/modals#directive-events

You reset the form on various places and that is very error prone.

**Comment by ppitonak** [comment]
@stevengutz IMHO it makes sense to fix it now while @vikram-raj is working on this component. It's much better than completely re-creating context in couple of weeks/months.

**Comment by christianvogt** [comment]
Instead of trying to reset the state of the modal, the component should be unmounted and destroyed when the modal is not opened. This would automatically create a new state when the modal reopens. This will also reduce the DOM because right now the modal and all it's contents are in the DOM but hidden.

**Comment by joshuawilson** [comment]
@vikram-raj can you work on this?

**Comment by vikram-raj** [comment]
@joshuawilson I am working on this.
