### ISSUE TITLE
No focus in create space and create app modal

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#4617]
##### Issue Overview

When "Create space" or "Create an Application" modal dialog is rendered, the `name` input should be focus

##### Expected Behaviour

Input is focused

##### Current Behaviour

Input is not focused

##### Steps To Reproduce

1. open https://prod-preview.openshift.io
2. click top-left menu and click `Create Space`

result: input is not focused, the same behavior is observed in create an application dialog

##### Additional Information

@vikram-raj @joshuawilson 

code responsible for setting focus 
https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/add-space-overlay/add-space-overlay.component.ts#L61
https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/add-app-overlay/add-app-overlay.component.ts#L85

**Comment by christianvogt** [comment]
If the modal is mounted in the dom upon open (as oppose to changing css `display) use the `autofocus` attribute on the input.

**Comment by christianvogt** [comment]
Wait for https://github.com/openshiftio/openshift.io/issues/4616 to be fixed.

**Comment by christianvogt** [comment]
@vikram-raj can you fix this next?

**Comment by ppitonak** [comment]
When is the next deployment to production planned?

**Comment by joshuawilson** [comment]
shortly

**Comment by joshuawilson** [comment]
in prod now

**Comment by ppitonak** [comment]
Fixed in prod, closing.
