### ISSUE TITLE
Close button is obsolete

### ISSUE THREAD

**Issue by sanketpathak** [openshiftio/openshift.io#4620]
##### Issue Overview

In application setup window of launcher when selecting close button it asks you to leave without saving changes when selecting leave it does not give the intended result i.e.the application is created. This leaves its use as obsolete

##### Expected Behaviour
Application should not be created

##### Current Behaviour
Application is created

##### Steps To Reproduce

1. open https://prod-preview.openshift.io
2. create a space
3. click "Add to Space", type some name, click "Create a new codebase"
4. click next
5. select mission, runtime, pipeline and validate git repository
6. select set up application in `Confirm Application Summary & Setup` step.
7. Setup window will openas shown in the picture below.
![err1 1](https://user-images.githubusercontent.com/10252230/49645573-786d1380-fa42-11e8-9415-3dd4beafc6fa.png)

8.Select cancel on top right, it will ask you 
```
Are you sure that you want to navigate away from this page? You will lose any information entered thus far.

Do you want to leave?

```
select `yes leave` option.

![err1](https://user-images.githubusercontent.com/10252230/49645727-fe895a00-fa42-11e8-9f08-2bb99efd870e.png)

9. But it does'nt work application will be created. So I find this close button of no use hence should be removed.

**Comment by sanketpathak** [comment]
@vikram-raj  Please have a look

**Comment by joshuawilson** [comment]
This whole page is about to get updated. There is a new design for it. 
The new design is here https://redhat.invisionapp.com/share/MHP7TIO3XYK#/screens/332556493_ExistingFlow-_Start and was tracked at https://github.com/openshiftio/openshift.io/issues/4193
I'm going to close this as we are already working this under different issues.
