### ISSUE TITLE
Different Che workspace name generated based on aplication name length

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4625]
I've noticed that there is different workspace name generated based on the length of application name. 
1. if application name length is < 15 characters -> the workspace name is application name + hash, e.g ```a1234567891011-fgdrg```
2. if the application name length >= 15 characters -> only hash is used as workspace name

Please see screenshot (see the combobox values)
![codebases](https://user-images.githubusercontent.com/2078072/49731505-e2243200-fc7b-11e8-831a-43bee299caaa.png)

I do understand that from technical point of view this is correct. However, as a user, I was confused why there are two different workspace formats and it seemed as a bug first. Also, the "long" version does not really fit into the combobox. 

So I'd like to see what UX things about this.

**Comment by ibuziuk** [comment]
currently, it is expected. Related to https://github.com/redhat-developer/che-starter/issues/225

**Comment by ibuziuk** [comment]
@tinakurian this is trivial issue, if you are interested in smth. to work in che-starter are ;-)
cc: @sbose78

**Comment by ibuziuk** [comment]
Fixed on prod. Closing
