### ISSUE TITLE
Jenkins Idler: Test that the token is valid before adding watches

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#4628]
When the token is expired or invalidated idler would not check it and would
still try to use it again and again, it should see if there it's usuable and
back off from that cluster.

Fabric8 Jenkins Idler issue: https://github.com/fabric8-services/fabric8-jenkins-idler/issues/311

**Comment by sthaha** [comment]
@chmouel does this result in memory leak as well? If so I suspect https://github.com/fabric8-services/fabric8-jenkins-idler/blob/master/internal/openshift/client/openshift_client.go#L301 

2 things

1. the `if err != nil` should be checked before checking `resp`
2. Must call `resp.Body.Close()` before continuing

With regards to OP, we need a way to be notified (zabbix?) if idler chooses to ignore a cluster.

**Comment by chmouel** [comment]
@sthaha yup and yup, when idler goes out of control it usually goes all the way and just grow and grow until crashing by the OOM and get restarted by idler,

We need to fix what you pointed but perhaps, test the token before as well (there is some whoami and probably being bugged by a bad error check) at the time of getting it from the clusters list and then completely ignore everything that happen on that cluster,
