### ISSUE TITLE
URL link is broken in work item creation email notification.

### ISSUE THREAD

**Issue by danieloh30** [openshiftio/openshift.io#463]
When I create a workitem then I got an email[1] and the link of space is broken[2] 
[1]Email notification
![screenshot from 2017-08-03 09-41-17](https://user-images.githubusercontent.com/14066977/28901955-cc9f1ba4-7836-11e7-95ba-a98ba892cb9d.png)

[2]404 error when I hit the link in the email.
![screenshot from 2017-08-03 09-41-28](https://user-images.githubusercontent.com/14066977/28901966-dfdc7234-7836-11e7-814d-f8f65d65eca4.png)

**Comment by aslakknutsen** [comment]
Note: There is no link in the email template at that location, but the email client is picking up the email-adr/space-name as a user@domain.com/path URL and attempting to auto link it.

This is mostly a temporary issue until we can open up for user select OSiO usernames and not rely on RHD usernames which can be an email. Still, there might be someone out there that would like their username to be an email, so the question is, is there anything we can do to avoid it. 

One follow up question would be; What email client are you using?

**Comment by bmicklea** [comment]
Wouldn't it be helpful to the user to have that be a purposeful link and drop them into the planner for that space with the specific work item opened?

**Comment by joshuawilson** [comment]
we would need to pull the whole URL, not just the user/space ref

**Comment by aslakknutsen** [comment]
@bmicklea Sure, there are already 4 links or so that does that.. :) We could make that a link to the Space dashboard to workaround the issue.

**Comment by qodfathr** [comment]
Fixed
