### ISSUE TITLE
ContentRepo pods on prod

### ISSUE THREAD

**Issue by gorkem** [openshiftio/openshift.io#4632]
I see 3 ContentRepo pods dangling as l reported by Zabbix. I expect no ContentRepo pods to show up anymore. I am not sure if it is Zabbix or we actually have some left over pods but we should resolve this.

[1] https://zabbix.devshift.net:9443/zabbix/charts.php?graphid=8774

**Comment by piyush-garg** [comment]
@pbergene @jfchevrette can you please take a look and also lets us know if anything is required from build side

**Comment by pbergene** [comment]
Ah, nice catch :)

**Comment by pbergene** [comment]
Pods are 21 days old.  Probably coincides with latest upgrade and they got rescheduled. Familiar names on all the namespaces.  DCs have been removed manually, but this state should be managed.

**Comment by gorkem** [comment]
When should we start seeing the zabbix chart to reflect the change?

**Comment by pbergene** [comment]
The pods were left in terminating for a while, and still are.  I've done a delete pod --now, to see if this helps.  If not they'll go away when os decides to kill them, but not picking this up as a priority.
