### ISSUE TITLE
ToolTip not showing up in attributes table

### ISSUE THREAD

**Issue by abhinandan13jan** [openshiftio/openshift.io#4633]
##### Issue Overview
ToolTip not showing up in attributes table

##### Expected Behaviour
ToolTip should show up in attributes table

##### Current Behaviour
ToolTip is not showing up in attributes table

https://drive.google.com/file/d/1pyAWzk4H5pZe347OU7sP01JSO8sKw-Il/view?usp=sharing

##### Steps To Reproduce

1. Open any 'space' in prod-preview
2. Move to 'Plan' page
3. From right corner, click on settings button.
4. Hover over '<' and '>' icon between displayed attributes and available attributes

##### Additional Information

  * browser in use: Google Chrome 70.0.3

**Comment by christianvogt** [comment]
@abhinandan13jan did you mean that the cursor isn't switching to a pointer to indicate a clickable button?

**Comment by abhinandan13jan** [comment]
@christianvogt I see that there is a 'tooltip' attribute added to the icons but tooltip is not showing on hover as the required modules have not been imported. I am adding the required Tooltip module so that the tooltip feature shows up once we hover the icons.
