### ISSUE TITLE
Drag & Drop in Planner backlog not working, unable to reorder Work items

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#4637]
##### Issue Overview

Drag and drop feature on Planner backlog is not functioning, unable to reorder work items.

##### Expected Behaviour
Drag and drop should let me reorder my WIs
##### Current Behaviour
Drag and drop does not work. I am able to drag but not drop.
##### Steps To Reproduce

1. Create WIs
2. Drag and drop to reorder.
![screenshot from 2018-12-12 12-25-20](https://user-images.githubusercontent.com/16647625/49852722-edf22e80-fe0a-11e8-8340-c7c1b6658bca.png)

**Comment by joshuawilson** [comment]
I can reproduce this on the latest.
