### ISSUE TITLE
Shortcut for Iterations in Sidebar of Planner

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#464]
# Description
As a user, I want to see the current iteration from the context views and I want to switch the context between iterations.

# Acceptance Criteria
- [ ] In the sidebar, there is a section containing iterations criterias.
- [ ] The section contains a tree display of criterias for the Iterations of the Space.
- [ ] Nodes of the tree are expandable/collapsable if the specific Iteration has children.
- [ ] There is no way of resetting/unsetting the current selection. The user needs to choose another option of the sidebar resulting in a different query to leave/reset the iteration section.
- [ ] Clicking on an option/criteria resets the current contexts (list view or board view) search/filter criteria and sets the selected Work Item Type(s) as the sole criteria for the context view.
- [ ] Clicking on an criteria highlights the value and the criteria header.
- [ ] Only one single criteria can be active at any one time. If a new criteria is selected, the prior criteria gets deselected.
- [ ] The selected criteria is also displayed on the search/filter toolbar as a criteria.
- [ ] Adding additional criterias using the search/filter toolbar deselects the active criteria.
 
# Relationships
_Put linked Team/Product story links here_

**Comment by sdash-redhat** [comment]
Refer Interaction Design notes 
slide 63 -> 67 - https://redhat.invisionapp.com/share/6RCWHA1TX

Visual Design Notes: 
https://redhat.invisionapp.com/share/HTCX31SWC
(VD work in progress)

Note: the text, data points were shown are for reference purpose to illustrate the interaction, based on actual data points there may be changes on how the screen might appear in real time post implementation.
