### ISSUE TITLE
Broken CSS (LESS compilation) in Table Config component

### ISSUE THREAD

**Issue by abhinandan13jan** [openshiftio/openshift.io#4645]
##### Issue Overview

CSS broken in Table Config component
(Local setup of master - fabric8-ui)

##### Expected Behaviour
Table should be listed properly with appropriate width
##### Current Behaviour
Available attribute portion appears to be broken

##### Additional Information
![screenshot from 2018-12-17 12-08-44](https://user-images.githubusercontent.com/24852534/50070748-3a67b080-01f5-11e9-813a-5cb109c14dce.png)

```

**Comment by abhinandan13jan** [comment]
Will be fixed for this component with PR #3450( https://github.com/fabric8-ui/fabric8-ui/pull/3450 ), there might be LESS related issue in other components as well.

**Comment by vikram-raj** [comment]
Currently, all style is broken where we are using ```width: ~'calc(e("100% - 30px"))';```. I should be this ```width: ~'calc(100% - 30px)';```.
