### ISSUE TITLE
New dashboard: confusing navigation

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#4649]
##### Issue Overview

In the old space dashboard it was possible to navigate from the dashboard to codebases, planner and pipelines page easily. Now the user needs to use menu (i.e. he needs to know where to find these views).

##### Expected Behaviour

Widget name is a hyperlink that takes the user to the corresponding view, as in old dashboard

##### Current Behaviour

New dashboard:
![crt_new_dashboard](https://user-images.githubusercontent.com/445100/50099324-1cfb0c80-021e-11e9-8956-809eaec106d9.png)

Old dashboard:
![crt_old_dashboard](https://user-images.githubusercontent.com/445100/50099325-1cfb0c80-021e-11e9-8367-740d4ec24c26.png)

##### Steps To Reproduce

1. create a space
2. create a new app

**Comment by joshuawilson** [comment]
@openshiftio/uxd-team please advise.

**Comment by joshuawilson** [comment]
Thanks @serenamarie125
