### ISSUE TITLE
Deployments: CPU usage is nearing capacity

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#4651]
##### Issue Overview

User sees a warning that CPU usage is nearing capacity in prod-preview (cluster 2a)

##### Expected Behaviour

Page reports status OK

##### Current Behaviour

![deployments](https://user-images.githubusercontent.com/445100/50157278-50e33a00-02d1-11e9-83fd-01dccd295a53.png)

##### Steps To Reproduce

1. create a space and new app
2. wait for pipeline to finish
3. go to Deployments page

##### Additional Information

https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/4544/console
https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/4549/console
https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/4550/console
https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/4551/console

**Comment by joshuawilson** [comment]
Not sure what the issue is here, can you please explain?

**Comment by ppitonak** [comment]
I'm not sure if it is an issue or not... it's just strange that it uses so much resources on one account and not on others.

**Comment by ppitonak** [comment]
It's not specific to cluster 2a
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1882/console

**Comment by sanketpathak** [comment]
The build is failing due to CPU usage problem: https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1966/console
