### ISSUE TITLE
Remove mention of reset environment from onboarding doc

### ISSUE THREAD

**Issue by bmicklea** [openshiftio/openshift.io#4656]
Users shouldn't be using reset environment except in the most extreme cases (when guided by a community helper).

As a result the onboarding doc needs to be checked to ensure that we are not pointing new users to reset environment as part of the onboarding experience.

**Comment by ibuziuk** [comment]
Note I have found so far:
- https://docs.openshift.io/optimizing-ct-resources.html#resetting_your_ct_account

**Comment by Preeticp** [comment]
A PR removing all references to reset environment in all guides has been pushed to docs prod-preview: https://github.com/fabric8io/fabric8-online-docs/pull/475#issuecomment-448918270
This will be updated on prod ASAP.

**Comment by Preeticp** [comment]
Docs with the above changes have been updated to Prod.
