### ISSUE TITLE
Add a specific page where token can be retrieved after login

### ISSUE THREAD

**Issue by jeffmaury** [openshiftio/openshift.io#466]
In order to tools (DevStudio/JBossTools) to integrate the auth phase, the landing page should allow for easy tokens retrieval (like OpenShift does).
So it would be nice if there will be a landing page where tokens can be easily retrieved. Provision for status should also be added.
Page could be:

- a JSON one with well defined fields

- an HTML one (like OpenShift) with well defined div for fields retrieval

**Comment by joshuawilson** [comment]
@jeffmaury if I create a blank page can you add the content?

**Comment by joshuawilson** [comment]
Does it need UX or just a field?

**Comment by jeffmaury** [comment]
Fields are OK as we could close the browser when we reach this page and retrieved the tokens

**Comment by jeffmaury** [comment]
This is an absolute requirement because the current solution, based on the JSON transmitted as an URL parameter, is a blocker for the Eclipse / Windows implementation because Windows navigators (IE/Edge) limit the length of the URL that is displayed in the URL bar and the API we use in Eclipse is based on this.

**Comment by samuzzal-choudhury** [comment]
@joshuawilson we can collaborate to create the contents of the landing page if you could create a blank page. cc: @jeffmaury  @invincibleJai 

@jeffmaury do you have a UX in mind for that page?

**Comment by joshuawilson** [comment]
@samuzzal-choudhury I get the idea this is more of an API type of call. He said we can just use JSON.

**Comment by jeffmaury** [comment]
To be honest, I plan to close the browser as soon as I enter this page so UX design is not that relevant for me.
Maybe copy what's OpenShift does for OAuth login but with well defined ids and div to retrieve the info through DOM parsing

**Comment by invincibleJai** [comment]
I agree but it would be good to have some basic view in place where user can see the refresh token as we show access token under profile tab in OSIO

**Comment by jeffmaury** [comment]
Another argument for the landing page: on Linux; I tested with Firefox embedded in Eclipse and the last URL (/api/status) is not processed by Firefox so user is being asked to save (cause of the content type and the callback I expect is not being called in the UI Browser Eclipse framework

**Comment by jeffmaury** [comment]
![image](https://user-images.githubusercontent.com/695993/30709562-f9544974-9f02-11e7-8201-f5af373275b2.png)

Example of OpenShift display after OAuth login

**Comment by joshuawilson** [comment]
I think for now we can just copy that.

**Comment by jeffmaury** [comment]
OK but we need all fields not a single one:

- access token
- refresh token
- access token expires in
- refresh token expires in

**Comment by alexeykazakov** [comment]
The only thing you really need is the refresh token. You can use the refresh token to get a new access token. And expiry are encoded in tokens too.

**Comment by alexeykazakov** [comment]
And btw, the OSIO tokens will be much bigger than in OSO. Some nice "copy" button on that page would help.

**Comment by joshuawilson** [comment]
Why not get the token from local storage?

You can use this code in any browser console `localStorage.getItem('refresh_token');`

**Comment by jeffmaury** [comment]
Don't we need the access token @alexeykazakov ?

**Comment by alexeykazakov** [comment]
You need an access token to use it against our API. But you can get it via refresh token. We have already discussed it a few times, right? :)
http://swagger.goa.design/?url=github.com%2Ffabric8-services%2Ffabric8-auth%2Fdesign#!/token/token_refresh

And as far as I remember it's possible to run a JavaScript snippet in the browser from Eclipse. If so, then you could use `localStorage.getItem('refresh_token');` as mentioned by Joshua as soon as browser finishes login.

**Comment by jeffmaury** [comment]
We just logged in so sourds natural to get the access token to use osio services rather than making another round trip.
Parsing the dom would be much easier than dealing with Javascript and we want to manage several osio accounts per ide install

**Comment by joshuawilson** [comment]
I don't really like the idea of adding an extra page just for this. I'm just feels like a hack.

**Comment by jeffmaury** [comment]
Maybe but the curent solution does not work for all use cases

**Comment by samuzzal-choudhury** [comment]
@jeffmaury @alexeykazakov  @joshuawilson @invincibleJai 

Just to be on the same page:

1.  The landing page provides a refresh token which is going to be used within the IDE either by reading the DOM or by running JS `localStorage.getItem('refresh_token');` from Eclipse. We do not know the mechanism to be used in VSCode currently.

2.  The refresh token will be used to generate the access token for making OSIO API calls. The API endpoint for doing that is `http://openshift.io/api/token/refresh`.

3.  The refresh token has an expiry of 30 days before which a new refresh token has to be generated using the old refresh token (API?)

Anything that I missed here?

**Comment by alexeykazakov** [comment]
@samuzzal-choudhury looks good. Here are the refresh token API (https://auth.openshift.io/api/token/refresh) details btw - http://swagger.goa.design/?url=github.com%2Ffabric8-services%2Ffabric8-auth%2Fdesign#!/token/token_refresh

Regarding refreshing tokens.. I recommend refresh tokens once in 24 hours. No really need to do it more often and it will guarantee if user start the IDE at least once in a month then token will never expire.

**Comment by jeffmaury** [comment]
I have a temporary solution based on a static page hosted on github. Will see if we can host it on DevStudio web site. Would be usable by VSCode as well

**Comment by invincibleJai** [comment]
thanks @jeffmaury , let me know if it works

**Comment by invincibleJai** [comment]
Thanks @jeffmaury

**Comment by invincibleJai** [comment]
@joshuawilson have raised a PR with the basic HTML view as we're looking for landing/redirect screen for IDE users (https://github.com/openshiftio/openshift.io/pull/1025)

CC @jeffmaury @samuzzal-choudhury @alexeykazakov

**Comment by alexeykazakov** [comment]
It looks like the landing page is not required anymore. Can we close this issue?

**Comment by invincibleJai** [comment]
@alexeykazakov yes i think we are good on this. CC @jeffmaury

**Comment by joshuawilson** [comment]
@jeffmaury I'm closing this, if there is something else to do please reopen it.
