### ISSUE TITLE
Analytics report not generated in prod

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#4667]
##### Issue Overview

Analytics report is not generated in prod

##### Expected Behaviour

report appears in space dashboard after couple of minutes

##### Current Behaviour

![crt_analytics](https://user-images.githubusercontent.com/445100/50590484-853b2680-0e8b-11e9-9459-bf3a0a37a814.png)

##### Steps To Reproduce

1. create new space and new app in it
2. wait for pipeline to finish
3. go back to space dashboard

##### Additional Information

**Works fine in prod-preview**

**Comment by sivaavkd** [comment]
@yzainee is this related to what you told me about maven pipelines changes which are in prod-preview and not in prod yet ?

**Comment by yzainee** [comment]
@sivaavkd No this is not related to that. I was debugging it last night. There was some connection problem between the worker and the celery due to which none of the calls were reaching the worker and hence the reports were not getting generated. I dont exactly know why this happened. From the logs, the reports were generated till 12:33.. After this time, none of the reports were getting generated due to the problem i mentioned above.

**Comment by yzainee** [comment]
![screenshot from 2019-01-03 13-03-18](https://user-images.githubusercontent.com/37098367/50627132-17106580-0f58-11e9-96e1-694ac5a4fe8b.png)
![screenshot from 2019-01-03 13-03-29](https://user-images.githubusercontent.com/37098367/50627133-17106580-0f58-11e9-88a4-52bfd2f956e6.png)
![screenshot from 2019-01-03 13-03-44](https://user-images.githubusercontent.com/37098367/50627135-17a8fc00-0f58-11e9-8ef3-e4f7fea3fb70.png)
The stack report is generated in prod.

**Comment by yzainee** [comment]
@invincibleJai @sivaavkd 
Please verify the same

**Comment by jyasveer** [comment]
I am still not able to see stack report - wheel is spinning forever.  I used Maven repo (https://github.com/apache/maven <https://github.com/apache/maven>)

Here is the stack id - f085749b778a4c75a6c5a92e4b3283a7

Thanks, Siva Kumar

**Comment by sivaavkd** [comment]
I am still not able to see stack report - wheel is spinning forever.  I used Maven repo (https://github.com/apache/maven <https://github.com/apache/maven>)

Here is the stack id - f085749b778a4c75a6c5a92e4b3283a7

Thanks, Siva Kumar

**Comment by ljelinkova** [comment]
The e2e tests works now OK - the analyses is generated. The tests started to pass approximately since 6 AM UTC.

**Comment by yzainee** [comment]
Closing the issue as the report is generating properly.
