### ISSUE TITLE
Analyze Page Pipeline Link broken/incorrect

### ISSUE THREAD

**Issue by utherp0** [openshiftio/openshift.io#467]
The named pipeline in the 'pipelines' widget always returns a 'no such pipeline' with the generic url ..../create/pipelines.

![screen shot 2017-08-04 at 08 53 04](https://user-images.githubusercontent.com/2233236/28959512-a8d7549a-78f2-11e7-8a64-03daf7337ce5.png)

**Comment by joshuawilson** [comment]
What is the URL for the Pipelines page?
What is your username?

**Comment by sbose78** [comment]
@utherp0 did you update your username in OSIO from `ilawson` to `Ilawson@redhat.com` ?
I checked our SSO server and I see your username is `Ilawson@redhat.com`.

If you logged in to `http://console.starter-us-east-2.openshift.com` , do you see a project with the name `ilawson` ?

**Comment by sbose78** [comment]
same as https://github.com/openshiftio/openshift.io/issues/465

**Comment by alexeykazakov** [comment]
closing as duplicate
