### ISSUE TITLE
Pipelines stage names are not consistent across

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4671]
##### Issue Overview

Pipelines stage names are not consistent

##### Expected Behaviour

Pipelines stage names should be consistent for launcher wizard and pipelines view

##### Current Behaviour

Pipelines stage names are not consistent

<img width="1323" alt="screen shot 2019-01-03 at 5 49 29 pm" src="https://user-images.githubusercontent.com/5129024/50637518-518df880-0f80-11e9-8b86-f1f3d46f1733.png">

<img width="1649" alt="screen shot 2019-01-03 at 5 49 53 pm" src="https://user-images.githubusercontent.com/5129024/50637527-5a7eca00-0f80-11e9-8e0c-b4b51d62579b.png">

**Comment by hrishin** [comment]
![image](https://user-images.githubusercontent.com/28615674/50676183-0673f400-1019-11e9-94d9-c69cb4386149.png)

Fixed now.
