### ISSUE TITLE
Show OSO status and quotas in IO

### ISSUE THREAD

**Issue by bmicklea** [openshiftio/openshift.io#468]
The status button in IO should be expanded to show two new items at the end of list:

"OpenShift Online"
  - Status symbol should be used: green check = available; red x = unavailable

"OpenShift Quotas"
  - Status symbol should be used: green check = no quota warnings; yellow warning = quota warning
  - If there's a quota warning we should include a link to the OSO console quota page (link text "Details")

![screen shot 2017-08-04 at 11 54 54 am](https://user-images.githubusercontent.com/7644938/28976539-46b3f89e-790c-11e7-82cf-3af11c473299.png)

**Comment by qodfathr** [comment]
Let's not over use the status widget. OSO is not a part of OSIO, so this feels semantically wrong to me. Eventually we'll have multiple deployment targets, so this recommendation is not reasonably extensible in that model.

**Comment by bmicklea** [comment]
But GitHub isn't part of IO either :)  The status widget is meant to show status of the various components that are required to make IO function properly and OSO is part of that.  If there's a better place to highlight quota issues in OSO let me know but users get bit by quotas in OSO frequently when using IO and right now those problems are invisible to them.

**Comment by bmicklea** [comment]
@joshuawilson I don't see this as something we have to do for the workshop so I've removed the P1 designation. Once Todd's back we can bring him up to speed on the discoveries over the past few days and discuss how best to proceed from there.

There should be no action on this until we've had that discussion. Sorry if I wasn't clear on the lower priority of this.

**Comment by qodfathr** [comment]
Quota information is making its way into OSIO, but the current UXD design does not call for it to go to the status widget (@catrobson feel free to correct me). Closing for now; reopen if needed.
