### ISSUE TITLE
OSIO and OSO accounts are not shared

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#469]
If you have an account on OSO then you can not have one on OSIO. The inverse is true too.

This either needs to be stated as intentional since RH is paying for the resources or we need to find a way to allow users to move between them.

**Comment by alexeykazakov** [comment]
It's fixed.

**Comment by alexeykazakov** [comment]
To be clear. It's not possible to have both OSIO and OSO accounts using the same RHD account.
