### ISSUE TITLE
Build: Document the state of union

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#4698]
Document the Build Team state of the union for January 2019 F2F Arch meeting.

**Comment by chmouel** [comment]
https://docs.google.com/presentation/d/17PdIMbDh2W7lgpR87eF6V5XnASG3jC25LoQGianzPcM/edit#slide=id.g4bfa7c6dff_0_10

**Comment by pradeepto** [comment]
@chmouel Closing this since you were done presenting it yesterday. Please reopen if need be.
