### ISSUE TITLE
Booster application is not deployed on 1a cluster

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4699]
Deployment of the booster application failed several times on cluster 1a. They seem to have been caused by the same error - _no route to host_

```
Failed to pull image "docker-registry.default.svc:5000/osio-ci-e2e-002-run/booster-mission-runtime@sha256:ab916472e7b477d9b4ef3edb97163be374ae9a9903ea94e37efe22278cb7c179": rpc error: code = Unknown desc = Get https://docker-registry.default.svc:5000/v2/: dial tcp 172.30.51.107:5000: getsockopt: no route to host
```
You can see the full oc log here:
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/2142/oc-run.txt

This is the list of affected jobs:
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/2145/console
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/2142/console
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-released/1386/console
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-released/1385/console

This issue seems very similar to https://github.com/openshiftio/openshift.io/issues/4685

**Comment by GeorgeActon** [comment]
@ljelinkova Bug? severity?

**Comment by ljelinkova** [comment]
I haven't seen this issue for over a week, so I am closing it.
