### ISSUE TITLE
Network outages/issues causing some updates to fail

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#470]
Network outages/issues causing some updates to fail to do readiness probes failing

We think this is something that OSO will need to fix.

**Comment by joshuawilson** [comment]
One solution that @rawlingsj proposed was to turn off readiness checks for Quickstarts.

**Comment by burrsutter** [comment]
I think this is fixed based on the arp cache being cleared on our cluster.  We were getting 100+ readiness probe failures
