### ISSUE TITLE
Reindex Booster Catalog (Nodejs Booster out of sync)

### ISSUE THREAD

**Issue by jarifibrahim** [openshiftio/openshift.io#4701]
##### Issue Overview

I recently updated one of the Nodejs boosters https://github.com/nodeshift-starters/nodejs-health-check/pull/128 but the changes aren't reflected on OSIO. This is because the `launcher-backend` caches all the boosters locally and this cache needs to be updated.

The boosters need to be reindexed by calling the `/reindex` API on launcher-backend

@gastaldi Can you please reindex the boosters with the correct access token?

**Comment by jarifibrahim** [comment]
Looks like the pipelines are also out of sync. https://github.com/fabric8io/fabric8-jenkinsfile-library/pull/45 was merged yesterday but https://forge.api.prod-preview.openshift.io/api/services/jenkins/pipelines doesn't show the new pipelines.

**Comment by gastaldi** [comment]
Changes to the Jenkins files require a rebuild, so I bumped the launcher-backend build and you should see the change soon

**Comment by gastaldi** [comment]
@jarifibrahim you may already know, but just to remind you that changes in the booster repositories are only reflected in the production catalog when the booster is tagged and updated in the booster-catalog repository

**Comment by gastaldi** [comment]
@jarifibrahim I believe this has been fixed, can you confirm?

**Comment by sbose78** [comment]
Thanks @gastaldi ,

> so I bumped the launcher-backend build

Could you point me to this, please.

> when the booster is tagged and updated in the booster-catalog repository

Could you point me to an example, please.

**Comment by gastaldi** [comment]
@sbose78 here is an example: https://github.com/fabric8-launcher/launcher-booster-catalog/pull/310

**Comment by jarifibrahim** [comment]
> Could you point me to this, please.
> 
> > when the booster is tagged and updated in the booster-catalog repository
> 
> Could you point me to an example, please.

So when we update a booster, the booster tag (https://github.com/nodeshift-starters/nodejs-rest-http-crud/releases) should also be updated and the booster-catalog should have the right tag (https://github.com/fabric8-launcher/launcher-booster-catalog/blob/master/nodejs/v10-community/health-check/booster.yaml#L15)

**Comment by jarifibrahim** [comment]
>@jarifibrahim I believe this has been fixed, can you confirm?

I see newer pipeline in launcher-backend https://forge.api.prod-preview.openshift.io/api/services/jenkins/pipelines/golang-releaseandstage/jenkinsfile . We can close this issue.

But we'll still have to release a new version of the booster and update the tag.
@gastaldi Who can help us release a new version? I don't have access to the booster repository and I don't think even @sbose78 can release (tag) a new version.

**Comment by gastaldi** [comment]
@jarifibrahim you need to talk to the Node.js team: @lholmquist may be able to help you

**Comment by jarifibrahim** [comment]
Thanks @gastaldi :)

**Comment by lholmquist** [comment]
@jarifibrahim i need to create a new release on that health-check repo with that commit, then i'll send the request to the catalog to point to that new release
