### ISSUE TITLE
Launcher-backend: 504 Gateway Timeout

### ISSUE THREAD

**Issue by jarifibrahim** [openshiftio/openshift.io#4705]
##### Issue Overview

The launcher-backend (https://forge.api.prod-preview.openshift.io/api/booster-catalog) is returning 504 for all the requests.
```
➜  ~ curl 'https://forge.api.prod-preview.openshift.io/api/booster-catalog'           
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

```

From the deployments logs
```
2019-01-11 20:00:58,131 INFO  [NativeGitBoosterCatalogPathProvider] (EE-ManagedExecutorService-default-Thread-1) Executing: git clone https://github.com/thorntail-examples/cache  --branch 4 --recursive --depth=1 --quiet -c advice.detachedHead=false /tmp/booster-catalog5563327170158679452/.boosters/thorntail_community_cache_booster_staging
--
  | 2019-01-11 20:00:58,747 INFO  [AbstractBoosterCatalogService] (EE-ManagedExecutorService-default-Thread-1) Pre-fetching boosters...
```
it looks like it's stuck at pre-fetching boosters

**Comment by jarifibrahim** [comment]
A redeploy would fix the issue for now but we should try to find the root cause. My guess is launcher-backend is stuck in an infinite loop here https://github.com/fabric8-launcher/launcher-booster-catalog-service/blob/master/src/main/kotlin/io/fabric8/launcher/booster/catalog/AbstractBoosterCatalogService.kt#L139

**Comment by rgarg1** [comment]
This log message is interesting:
```
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
```
Was the server configuration changed recently?

**Comment by jarifibrahim** [comment]
> This log message is interesting:
> 
> ```
> * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
> * ALPN, server did not agree to a protocol
> ```
> Was the server configuration changed recently?

I don't think so. The `ALPN, server did not agree to a protocol` warning is related to SSL/TLS protocol and that shouldn't cause a 503 :)

**Comment by jarifibrahim** [comment]
@gastaldi @sbose78 Shall we redeploy launcher-backend on prod-preview?

**Comment by jarifibrahim** [comment]
Launcher-backend was redeployed 2 hours ago because of config change and this issue is no longer reproducible.
