### ISSUE TITLE
Create Application wizard must mention application name should be in lowercase

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#4707]
##### Issue Overview

When a user creates an application with title case in the name, example 'Title',  by default it renders T as t and shows red (error) without telling the user what is wrong. Also user can create a space with a title case name but Application name only allows for lowercase. 
This should clearly be mentioned in the warning. 

##### Expected Behaviour
We need to add the word lowercase in it: Name must contain 4-40 characters, contain only  lowercase letters, numbers, hyphens, not start with a number, and not start or end with hyphens.

##### Current Behaviour
Currently the warning says: Name must contain 4-40 characters, contain only letters, numbers, hyphens, not start with a number, and not start or end with hyphens.

##### Steps To Reproduce

1. Create space. 
2. In the subsequent create app wizard, add a title case name in the Name field.

![screenshot from 2019-01-14 12-33-41](https://user-images.githubusercontent.com/16647625/51100968-9cb8ce80-17fe-11e9-860b-e0114a7a8e9d.png)

**Comment by vikram-raj** [comment]
This issue has been fixed.
