### ISSUE TITLE
Home dashboard is not loaded on prod-prev

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4709]
When I login into prod-preview I get thw following screen. The home page is not loaded. However, I can navigate to some other page via top menut and when I go back to home page it is loaded properly. 

![home](https://user-images.githubusercontent.com/2078072/51183440-77e15b80-18d1-11e9-8f1c-c2b45976b8a3.png)

**Comment by joshuawilson** [comment]
Please try a hard refresh `cntl + shift + r` OR `cmd + shift + r` on Mac.

**Comment by ppitonak** [comment]
`Ctrl + F5` in Firefox helped.

**Comment by joshuawilson** [comment]
looks intermittent and refresh does not fix it

**Comment by christianvogt** [comment]
anyone still encountering this issue?

**Comment by piyush-garg** [comment]
Just faced the same issue

**Comment by sbose78** [comment]
Faced this, refreshed and it worked.
