### ISSUE TITLE
Low RC quotas and bad error handling

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#471]
Right now we have a Max number of builds/pipeline runs == RCs which 20. 

Low quotas and bad error handling makes it really hard to actually use.

We might try to get the quickstarts configured to use less resources and add better error handling  AND/OR get more quotas.

These will clear stage and run if they get full and don't automatically get emptied.
```
./oc delete all,pvc,cm,secrets --all -n burrzinga-stage
./oc delete all,pvc,cm,secrets --all -n burrzinga-run 
```

Quota issues:
Max. 20 RC’s (1 RC per build/pipeline run)
From @smarterclayton: We can set maxbuildcomplete and maxfailed

**Comment by rawlingsj** [comment]
There's a PR waiting to be merged https://github.com/fabric8io/fabric8-maven-plugin/pull/1025 which once released will mean all our tenant apps + boosters will have a default revision history limit on DCs which means old RCs won't be kept around.

**Comment by bmicklea** [comment]
PR merged so closing.
