### ISSUE TITLE
UI calls incorrect build tool detector URL

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#4711]
When the UI tries to detect the build tool , it fails to do so because the request returns a 404

```
someapp2:1 Failed to load https://detector.api.prod-preview.openshift.io//api/detect/build/https%3A%2F%2Fgithub.com%2Fsbose78%2Fspace-for-ingress: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://prod-preview.openshift.io' is therefore not allowed access. The response had HTTP status code 404.
```

The URL called needs to be `https://detector.api.prod-preview.openshift.io/api/detect/build/https%3A%2F%2Fgithub.com%2Fsbose78%2Fspace-for-ingress`
instead of `https://detector.api.prod-preview.openshift.io//api/detect/build/https%3A%2F%2Fgithub.com%2Fsbose78%2Fspace-for-ingress`

**Comment by sbose78** [comment]
CC @nimishamukherjee @vikram-raj

**Comment by joshuawilson** [comment]
this is still in prod-preview and is being actively worked

**Comment by vikram-raj** [comment]
Build tool detector is not working on prod-preview.
This PR fix this issue https://github.com/fabric8-ui/fabric8-ui/pull/3490

**Comment by vikram-raj** [comment]
This has been fixed. @sbose78 do check it out on prod-prev.

**Comment by sbose78** [comment]
Verified, works great. Thank you.
