### ISSUE TITLE
[New navigation]: User can not navigate back from 404 error page

### ISSUE THREAD

**Issue by vikram-raj** [openshiftio/openshift.io#4717]
##### Issue Overview
If a user gets 404 error then he/she can not navigation back any other page using the side navigation

Tell us briefly what the problem is about.

##### Expected Behaviour
A user should navigate back to any other page using the side navigation.

##### Current Behaviour
A user can not navigation to other page once he/she gets 404 error using side navigation

**Comment by vikram-raj** [comment]
cc: @christianvogt

**Comment by christianvogt** [comment]
I believe this will be fixed once issue https://github.com/openshiftio/openshift.io/issues/4715 is addressed.
