### ISSUE TITLE
Jenkins slaves in DeadlineExteeded state

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#472]
Jenkins slaves in DeadlineExteeded state, stopping new slaves from launching.

Possible solution is to set a Revision History Limit.

**Comment by aslakknutsen** [comment]
@rajdavies Also mentioned a possible update to the Jenkins Kubernetes Plugin

**Comment by bmicklea** [comment]
What's the status of this?  I haven't had issues with slaves launching so is this fixed?

**Comment by joshuawilson** [comment]
@jstrachan I think this was something you reported. Can you expound on it.

**Comment by rawlingsj** [comment]
I've not seen this for a while, my guess it was related to multiple builds being triggered when new quickstarts were created.  That's been fixed now https://github.com/openshiftio/openshift.io/issues/360 so closing this but please reopen if we start seeing it again.
