### ISSUE TITLE
Codebases: Che workspace not created in prod-preview

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#4720]
##### Issue Overview

When user clicks "Create workspace" button in Codebases page, nothing happens

##### Expected Behaviour

Button changes to a combo box and user can open newly created Che workspace

##### Current Behaviour

Button/link still visible

![crt_che](https://user-images.githubusercontent.com/445100/51378531-c11def00-1b0d-11e9-81a2-ee716bae532f.png)

##### Steps To Reproduce

1. create new project (e.g. Spring Boot HTTP)
2. navigate to codebases page
3. click "Create workspace"

##### Additional Information

More details e.g. in this job:
http://artifacts.ci.centos.org/devtools/e2e/devtools-saas-openshiftio-e2e-smoketest-beta/477/
* no errors in [browser log](http://artifacts.ci.centos.org/devtools/e2e/devtools-saas-openshiftio-e2e-smoketest-beta/477/04-01-che-failed.log)
* button clicked at 09:12:53.740, no HTTP requests around that time
* Neither me nor @ljelinkova  managed to reproduce locally

**Comment by ppitonak** [comment]
Still appearing in multiple Jenkins jobs

**Comment by ibuziuk** [comment]
@ppitonak workspace creation via codebase UI seems to work fine for me on prod-preview. Is this problem still reproducible ?

**Comment by ppitonak** [comment]
@ibuziuk yes, Jenkins jobs are still failing. We implemented a workaround in tests so will know more after couple of runs.

**Comment by ppitonak** [comment]
We tried two things in e2e test, none of them helped
1. browser.sleep for 5s before clicking the button
2. when clicking on button doesn't do anything, refresh the page and click again

This error was observed for the first time in https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-released/5262/ at Jan 16, 2019 11:10:00 PM UTC

**Comment by rohitkrai03** [comment]
@ppitonak This is the error it seems ` SEVERE https://prod-preview.openshift.io/api/user/spaces - Failed to load resource: the server responded with a status of 500 (Internal Server Error)` which means that the space is not getting loaded. The server is returning 500 error which might be the reason why even after refreshing the page tests are failing.

**Comment by ibuziuk** [comment]
@alexeykazakov @MatousJobanek ^

**Comment by ppitonak** [comment]
@rohitkrai03 we have observed these errors for long time so I'm not sure if they are connected to this issue.

**Comment by ibuziuk** [comment]
@ppitonak the PR has been merged [1], wondering if the issue is fixed now ?
[1] https://github.com/fabric8io/fabric8-test/pull/1241

**Comment by ppitonak** [comment]
Yes, last 8 runs or so passed the problematic point in test. Closing.
