### ISSUE TITLE
Osio Pipeline: Private GIT repo

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#4722]
We are currently only supporting github public repo,

We need to support private git repo.

We need to be able to reference a git secret and pass it to openshift :

https://docs.openshift.com/container-platform/3.5/dev_guide/builds/build_inputs.html#source-clone-secrets

Osio Pipeline issue: https://github.com/fabric8io/osio-pipeline/issues/113

**Comment by chmouel** [comment]
May be dependent of #115

**Comment by sthaha** [comment]
On hold until we figured out how we defined an environment on OpenShift4 and OSD bits
