### ISSUE TITLE
Lack of monitoring

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#473]
In order to find issues and track down problems we need extensive monitoring set up.

**Comment by joshuawilson** [comment]
cc @jfchevrette @kbsingh @rawlingsj

**Comment by kbsingh** [comment]
this isnt very helpup in scope or definition. I propose we close this and actually do either a broad story on where we want to get to ( ie, split supportability / maintainability / lifecycle / ci test suites for components etc ) or do specific end goal pieces.

**Comment by rawlingsj** [comment]
> this isnt very helpup in scope or definition. I propose we close this and actually do either a broad story on where we want to get to ( ie, split supportability / maintainability / lifecycle / ci test suites for components etc ) or do specific end goal pieces.

+1

**Comment by joshuawilson** [comment]
@kbsingh you can edit this into a story OR you can open a new issue with the details you want, reference it here and then close it. This was a starting point based on the discussion we had.

**Comment by joshuawilson** [comment]
@rawlingsj can you please edit the main description since this was your request as I recall? Or close it.

**Comment by mmclanerh** [comment]
@rawlingsj grooming some decaying issues in the backlog -- if this is still needed, please open a new issue with details.  thanks!
