### ISSUE TITLE
Routes created on cluster 2a are not accessible - users cannot access deployed apps (bad request 400 error returned for all apps)

### ISSUE THREAD

**Issue by jarifibrahim** [openshiftio/openshift.io#4735]
##### Issue Overview

Routes created on https://console.starter-us-east-2a.openshift.com/ aren't accessible from outside. 

##### Expected Behaviour
Routes should work
##### Current Behaviour
Routes created return `400 Bad Request` 

![desktop screenshot](https://user-images.githubusercontent.com/12949454/51825786-8a18bc00-230b-11e9-915a-4a78b20913aa.png)

##### Steps To Reproduce

1. Create a new application in your `stage` namespace.
2. Create a public route and try to access it

**Comment by pbergene** [comment]
Can confirm - doing some further investigations

**Comment by ppitonak** [comment]
FYI we regularly test in e2e jobs how long it takes to create a route and last three runs failed to create a route in 5 minutes

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/1499/test-routes.txt
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/5560/test-routes.txt
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-released/5559/test-routes.txt

**Comment by pbergene** [comment]
Thanks.  Can confirm it's still an issue.

**Comment by ppitonak** [comment]
Any news?

**Comment by pbergene** [comment]
So - the sdn pod logs indicate that the routers can't reach the services. Cluster sre gas reached out to edge networking for assistance.

**Comment by pbergene** [comment]
This should now be sorted.

**Comment by ibuziuk** [comment]
@pbergene reopening for two reasons:
1. There is route flapping on 2a
2. first time route becomes accessible after ~1 minute

**Comment by pbergene** [comment]
Are we seeing 400s?

**Comment by ibuziuk** [comment]
503s

**Comment by pbergene** [comment]
Would be good if we could have a separate issue for that, this one is specifically related to the router returning 400s.

**Comment by ibuziuk** [comment]
@pbergene ok, whatever works. But what I think is that:
- issues with `e2e-test` labels should be closed by osio QA in charge of tests e.g. @ppitonak @ldimaggi @ljelinkova 
- just closing issue when one problem (400s) is replaced with 503s + route flapping does not really a good approach

**Comment by pbergene** [comment]
they have different solutions and causes and trace back to different snow issues etc, so want to keep the history / audit trial separate.
