### ISSUE TITLE
github webhook not working

### ISSUE THREAD

**Issue by hrishin** [openshiftio/openshift.io#4737]
Jenkins is not triggering a job upon the change in code. Maybe some issue with GitHub webhook.

**Comment by piyush-garg** [comment]
#4739 is the same issue and has the same effects. Closing this and will continue there.

**Comment by piyush-garg** [comment]
As per comment https://github.com/openshiftio/openshift.io/issues/4739#issuecomment-458496671, this has also been resolved, confirmed with my account. Please reopen if it happens again
