### ISSUE TITLE
Stack report analyses is not shown on the dashboard

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4740]
In the last few days the e2e tests face issue that the analyses is not shown on the dashboard. The tests wait 10 minutes. 

![Dashboard screenshot](http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-released/1503/06-01-afterEach.png)

When I look into Jenkins build config I can see that the bayesian url is generated:
`fabric8.io/bayesian.analysisUrl: https://recommender.api.openshift.io/api/v1/stack-analyses/3c7e8e7c054d43fd982ea3a72e343ad4`

When I look into dashboard network logs, I can see that request for that URL has been made
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-released/1503/06-01-afterEach.perf.log

But no results are shown.

**Comment by miteshvp** [comment]
@yzainee - can you PTAL here

**Comment by yzainee** [comment]
@ravsa FYI

**Comment by invincibleJai** [comment]
I checked the stackID and response is null as in 

```
{
    "version": null,
    "release": null,
    "started_at": null,
    "result": [],
    "finished_at": null,
    "request_id": "3c7e8e7c054d43fd982ea3a72e343ad4"
}
```

it is similar to issue https://github.com/openshiftio/openshift.io/issues/4718

@ravsa

**Comment by invincibleJai** [comment]
Looks fine to me, can see stack-report in the dashboard. @ravsa can u pls verify.

**Comment by ppitonak** [comment]
@miteshvp e2e jobs fail most of the time on other issues. It won't get that far so I cannot tell you if the fix helped or not. Please leave this issue open for one or two days.

**Comment by miteshvp** [comment]
@ppitonak @ljelinkova - any updates here? Are you still seeing this issue?

**Comment by ppitonak** [comment]
There are three other issues so test won't get that far.

**Comment by ljelinkova** [comment]
The other issues preventing the e2e to finish on some clusters are long term so I think we could close this one for now and re-open in case it appears again.
