### ISSUE TITLE
Implement new logout endpoint

### ISSUE THREAD

**Issue by sbryzak** [openshiftio/openshift.io#4742]
We are in the process of removing support for OSIO Keycloak from the auth service, and instead authenticating the user directly against RHD.  As part of this, the logout process must change slightly in order to invalidate all of the user's tokens which are now managed by the auth service instead of KC.

Instead of calling the `/api/logout` endpoint (which currently returns a 302 redirect response) the new `/api/logout/v2` endpoint will invalidate the current user's tokens, then return a payload in the response (now with http code 200) for which the client must extract the redirect location URL from the payload and set the `window.location` to this URL.

See swagger docs for the new logout endpoint [here](http://swagger.goa.design/?url=github.com%2Ffabric8-services%2Ffabric8-auth%2Fdesign#!/logout/logout_logoutv2).

The "Log Out" link in the UI will need to be updated to follow the new logout procedure to ensure that all of the user's tokens are invalidated correctly.

**Comment by rohitkrai03** [comment]
@sbryzak So, instead of client redirecting to `/api/logout?redirect_url='something'` we need to send an http request to `/api/logout/v2`?
Also, `redirect_url` is sent by client itself so why do we need to extract that from response payload?

**Comment by sbryzak** [comment]
@rohitkrai03 that's really strange, is that against prod-preview?  The only difference with the new logout endpoint is that it is invalidating all tokens belonging to the user.  @alexeykazakov is there any way to get access to the prod-preview database to test some queries there?

**Comment by alexeykazakov** [comment]
I tested it in prod.

**Comment by alexeykazakov** [comment]
https://github.com/fabric8-services/fabric8-auth/pull/766 fixed the issue with slow response.

**Comment by sbryzak** [comment]
@rohitkrai03 the endpoint should be more responsive now.  Your earlier comment about sending an http request to the new endpoint (instead of redirecting the client there) is correct.  The `redirect_url` that the client has though is the local redirect, it is different to the redirect returned by the auth service (which itself does contain the client's redirect url value).
