### ISSUE TITLE
Can't access Jenkins

### ISSUE THREAD

**Issue by jarifibrahim** [openshiftio/openshift.io#4746]
##### Issue Overview
I'm unable to access the route created for jenkins deployment. The pod is running but the public route doesn't who anything. The page keep loading for about 10 minutes and then crashes. I've retried to reset my account multiple times but it doesn't seem to help.

This particular line seems to be interesting
```
INFO: OpenShift OAuth returning true with namespace ijarif-preview-jenkins SA dir null default /run/secrets/kubernetes.io/serviceaccount SA name null default jenkins client ID null default system:serviceaccount:ijarif-preview-jenkins:jenkins secret null default eyJhb....... redirect null default https://api.starter-us-east-2a.openshift.com  server null default https://openshift.default.svc 
Feb 01, 2019 11:30:07 AM org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults
```

The complete log can be found here - https://gist.github.com/jarifibrahim/a00e61d4a3d2bd18b580a22bbee54833

NOTE - I even tried to start a build but the pod crashed with an exception from the git plugin (I'm guess that was because of authentication issues).

##### Expected Behaviour
Jenkins should be accessible

##### Current Behaviour
Jenkins is not accessible

##### Steps To Reproduce

1. Reset your environment
2. Wait for jenkins to be ready
3. Try to access the public route

**Comment by rupalibehera** [comment]
On which cluster do you face the issue ?
The logs looks fine.

**Comment by jarifibrahim** [comment]
I'm on cluster 2a.
Interestingly, I have a Grammarly chrome extension which seems to be messing with the page source code. 
```
chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/Grammarly.js:1 Uncaught TypeError: Cannot read property 'dataset' of null
    at HTMLDocument.c (chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/Grammarly.js:1)
(index):1 Failed to load resource: the server responded with a status of 403 (Forbidden)
(index):1 Error in event handler for extension.onRequest: TypeError: Cannot read property 'removeEventListener' of null
    at bindShortcuts (chrome-extension://nlipoenfbbikpbjkfpfillcgkoblgpmj/javascripts/content_script.js:1:12003)
    at chrome-extension://nlipoenfbbikpbjkfpfillcgkoblgpmj/javascripts/content_script.js:1:13937
Navigated to https://jenkins-ijarif-preview-jenkins.b542.starter-us-east-2a.openshiftapps.com/securityRealm/commenceLogin?from=%2F
```

Jenkins seems to be working in incognito mode. 
Closing this issue. :sweat_smile:
