### ISSUE TITLE
`resources` user settings link returns 404 error page

### ISSUE THREAD

**Issue by christianvogt** [openshiftio/openshift.io#4748]
All deployments related pages have been removed by PR#3502. However there is a navigation link that remains and refers to a page that no longer exists:

![image](https://user-images.githubusercontent.com/14068621/52233410-03c12480-288d-11e9-86db-50b41db2578d.png)

Remove the `Resources` link in the sub navigation of the user settings.

**Comment by joshuawilson** [comment]
Is this fixed?
