### ISSUE TITLE
Cannot run pipeline on prod-prev

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4752]
When I create a new space and a new application on prod-prev, the pipeline screen looks like this and the pipeline is never executed. 

![pipelines](https://user-images.githubusercontent.com/2078072/52270958-af787c00-2942-11e9-964b-4577fa979983.png)

When I navigate to dashboard, it says that pipeline status is _Unknown_

![dashboard](https://user-images.githubusercontent.com/2078072/52270965-b43d3000-2942-11e9-81fa-5009b0f734f1.png)

When I navigate to openshift the pipeline looks like this

![os](https://user-images.githubusercontent.com/2078072/52270992-c28b4c00-2942-11e9-8609-57eed3511c03.png)

When I click Start Pipeline it starts normally

![os2](https://user-images.githubusercontent.com/2078072/52271056-e8b0ec00-2942-11e9-8ccc-2754205eb0c7.png)

**Comment by jarifibrahim** [comment]
[Kibana logs](https://logs.dsaas-stg.openshift.com/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-05T11:10:29.280Z',mode:absolute,to:'2019-02-05T12:31:29.280Z'))&_a=(columns:!(kubernetes.labels.deploymentconfig,msg),index:'project.dsaas-preview.6e520a9f-d097-11e8-9fb7-121499db9246.*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'request-hash:643527145')),sort:!('@timestamp',desc))) for the webhook from pipelineapp git repo.

The webhook was proxied through jenkins-proxy but still didn't start the build

**Comment by chmouel** [comment]
Maybe the pods had issues to come up? Environment issue ? Can we have the dump of all the logs/pods/pvc event in there?

**Comment by ljelinkova** [comment]
I do not have logs after the build was triggered because the test fail before they are retrieved. However, this is the log that is retrieved at the beginning of the tests. There are some readiness probe failures. 

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/5733/oc-jenkins-logs-before-all.txt

If you want to debug the issue the easiest way is to simulate it on your account - it happens 100% for me.

**Comment by ppitonak** [comment]
@chmouel were you able to reproduce?

**Comment by piyush-garg** [comment]
Hey @ppitonak,

@hrishin was able to reproduce this issue and working towards the fix. Maybe we will get the further update.

His last comments were -
```
Issue: webhook event is occurring before jenkins finish settling up (workflow) job for the project completely.

In order to create jenkins workflow job for a quickstart project, launcher creates  buildconfig of type jekinsfile. Jenkins Sync plugin sense this change and create jenkins project. So before it create jenkins project/job, webhook is gets delivered and jenkins simply ignores it.
```

**Comment by hrishin** [comment]
We had a discussion within @jarifibrahim about how we can fix this ATM. We are going to try a few fixes and update on this issue further.
