### ISSUE TITLE
Stack Report is failing for vscode and build flow if CVEs exist in transitive deps

### ISSUE THREAD

**Issue by yzainee** [openshiftio/openshift.io#4759]
There is a problem in the code for the unknown dependencies due to which the stack report generation is failing.

Tested on dev cluster and on staging.

Scenario1
eco: maven
repo: https://github.com/yzainee/maven-simple

Scenario2
eco: node
repo: https://github.com/yzainee/node-js-sample

Jai:
i verified and seeing similar behavior, response is as below

```
{
    "result": [],
    "release": null,
    "version": null,
    "request_id": "7f93c5d1448343f1aef41abf040952ba",
    "started_at": null,
    "finished_at": null
}
```

**Comment by animuk** [comment]
@yzainee Could you please send some error logs you are getting which proves that the exception comes from unknown dependency flow?

**Comment by miteshvp** [comment]
@animuk - yesterday Yusuf and myself debugged this bits by bits with lots of debug statements. We found that it gets stuck at this line https://github.com/fabric8-analytics/f8a-server-backbone/blob/master/src/stack_aggregator.py#L524 . This is because key used here is wrong. The same line when changed to 
`if k == knowndep['version']['pname'][0] and v == knowndep['version']['version'][0]` worked fine.

**Comment by animuk** [comment]
@miteshvp Ok. Let me check

**Comment by yzainee** [comment]
@animuk Basically, there is no 'package' in the data which is retrieved for the transitive deps (which is having CVEs). Also, https://github.com/fabric8-analytics/f8a-server-backbone/blob/b3058b8c8813e743182bfbf2e72f500b25e5af93/src/stack_aggregator.py#L565 This should be re ordered, so that even if some problems happen during the unknown call, the stack report gets stored in the db successfully and is available for retrieval

**Comment by animuk** [comment]
@yzainee I understand for the particular scenario where CVE exists for the transitive dep, package node will be absent. So, we need to parse the version name for 'version' node. 
Regarding the reordering of ingestion flow need not required as we can ignore the scenario where stack report is successfully generated, but we have ingestion issue in the background which prevent the unknown dep ingestion

**Comment by miteshvp** [comment]
@animuk - I agree with @yzainee here. We cannot fail a stack aggregator because of some issues in worker flows. Its better to invoke worker flows once the data is persisted in DB. Looking at the source code, it does not look like its difficult.

**Comment by animuk** [comment]
degrading to Sev2 as this issue is affecting to a particular scenarios where CVE exists in transitive dep flow.

**Comment by yzainee** [comment]
@animuk We pick the transitive deps only when CVEs are associated with it otherwise we ignore them. So basically, the transitive deps support is affected by it. 
For the reordering, i dont understand why we should fail stack analyses if ingestion is having some issue? whats the relation between the 2?

**Comment by animuk** [comment]
@yzainee I mean to say that if we generate successful stack report in spite of ingestion issue happened in the background, we will not be aware of the ingestion issue looking at the displayed report. Ok. Any case, Let me look at the source, how do we de couple it.

**Comment by yzainee** [comment]
@animuk The job of /aggregator and /recommender is to generate stack report. The ingestion is a kind of hack that we are adding to it to sanitize data. These APIs in no way guarantee sanity of data nor do they speak or guarantee about the ingestion. The APIs are supposed to generate report and once its generated, it should be stored in the db. Why do you want to kill the whole process for a subsidiary item? Stack report is something which the customer are using even in the vscode extension, they dont really care what data we have or we dont have in our graph.

cc: @miteshvp @invincibleJai

**Comment by msrb** [comment]
Why is the structure of the response for transitive dependencies different from direct dependencies? If @animuk fixes the issue by accessing different keys in the dictionary, will it continue to work for direct dependencies?

I think we should plan to move away from having those crazy raw string graph queries scattered all over the repositories. It's incredibly error-prone and not really maintainable.

@yzainee has a point with the unknown dependency ingestion. The process is asynchronous so this service merely sends messages to SQS and doesn't care about results, but surrounding the functionality with try/except cannot hurt.

**Comment by msrb** [comment]
cc @tisnik 

Pavel might have some ideas how to prevent such bugs in future.

**Comment by yzainee** [comment]
@msrb the structure is different because we dont need package details in case of transitive data. Going via the package node would increase the query execution time as the number of transitives is always very high.
In both, direct and transitive, we retrieve the version data and you can always get the package name from the 'pname' field

**Comment by animuk** [comment]
verified with the stack yusuf has mentioned in the description. Issue is resolved. closing this.
