### ISSUE TITLE
Cleanup process depends on 'Update Tenant' - but that does not provide feedback to user

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#476]
Related to:  https://github.com/openshiftio/openshift.io/issues/440

Our user account cleanup process depends on the user performing an 'Update Tenant' operation. However, pressing the Update Tenant button does not provide any feedback to the user to indicate success/failure. At the very least, we should provide the user with a "tenant updated" dialog or toaster popup.

![screenshot from 2017-08-07 08-54-50](https://user-images.githubusercontent.com/642621/29027392-85c60bc8-7b4e-11e7-88b6-b25680f798ce.png)

**Comment by aslakknutsen** [comment]
Note: The call to the backend is async, so when the call returns all that has happened is that it's been received. There is currently no way to tell when it's actually done. Message could read something like "Tenant being updated/Tenant update in process"

**Comment by ldimaggi** [comment]
I think that even that message would be helpful - at present, when the user presses the button, it appears that nothing is happening.

**Comment by joshuawilson** [comment]
We can add some feedback to the button so the user knows it was clicked.

**Comment by aditya-konarde** [comment]
+1

**Comment by joshuawilson** [comment]
A task has been created to fix this. #1566

**Comment by qodfathr** [comment]
Fixed.
