### ISSUE TITLE
[prod-preview] Che workspace stuck in stopping state and cannot be deleted

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4767]
Our e2e user account `osio-ci-e2e-002` has workspace that has been stopping for 11 days. This means that the user cannot start any other workspace and use Che. The workspace name is `e2e-0221-1653-8932-vh8cr`

This has already happen before, more in issue https://github.com/openshiftio/openshift.io/issues/4391

**Comment by ibuziuk** [comment]
@ljelinkova @ppitonak could you please confirm if the issue is still there?

**Comment by ppitonak** [comment]
There are no workspaces in Che dashboard for `osio-ci-e2e-002`

**Comment by ibuziuk** [comment]
@ppitonak ok, are you ok to close ?
