### ISSUE TITLE
Internal server error when trying to reset my account on openshift.io

### ISSUE THREAD

**Issue by atrebla** [openshiftio/openshift.io#4770]
This happened the first time I've tried to reset my account on https://openshift.io

![image](https://user-images.githubusercontent.com/23000235/54523514-01fc7d80-4970-11e9-9278-d6edc34fa43b.png)

**Comment by ibuziuk** [comment]
CC @alexeykazakov

**Comment by MatousJobanek** [comment]
This can happen when the openshift is too slow while resetting some objects in the namespaces. Another reset should help. 
Unfortunately, this is something out of our control.

**Comment by ibuziuk** [comment]
btw, I can not repro - reset env works for me against both prod-preview / prod

**Comment by atrebla** [comment]
thanks this work for me
