### ISSUE TITLE
"Forge Wizard" dialog title is confusing

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#479]
We should change the displayed title for the (new project creation) Forge Wizard to be simpler/more informative for the users. Suggestion for a new title: "New Quickstart Project Creation"

![screenshot from 2017-08-07 10-30-42](https://user-images.githubusercontent.com/642621/29031376-0d9d7a2e-7b5c-11e7-91b0-4a0104ec9522.png)

**Comment by omajid** [comment]
Also applies to the import wizard.

**Comment by joshuawilson** [comment]
@catrobson what do you want here?
cc @corinnekrych

**Comment by catrobson** [comment]
"Application Wizard"

As defined by the latest wireframes here:  https://redhat.invisionapp.com/share/DUD3OHBMP#/249199298_Select_Stack_Unselected
