### ISSUE TITLE
After successfully creating a new quickstart project, "Git repositories:    [object Object]

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#483]
See attached screenshot - this is new as that field was not displayed ion the past:

![screenshot from 2017-08-08 10-54-31](https://user-images.githubusercontent.com/642621/29078561-bd0c7510-7c28-11e7-961c-a0ee019ddf99.png)

**Comment by joshuawilson** [comment]
Which quickstart did you use? 
Does happen on every quickstart?

**Comment by ldimaggi** [comment]
This was with any quickstart.

**Comment by corinnekrych** [comment]
fixed in https://github.com/openshiftio/openshift.io/issues/966
