### ISSUE TITLE
Replace the namaspace: username by space: <name of space>

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#484]
The last screen of the Wizard forge shows "Namespace: <username>", since it's an OSO namespace, it doesn't make sense. We should replace it by "Space: <name of the space>".

![screenshot 2017-08-08 10 58 36](https://user-images.githubusercontent.com/30131/29078590-cd09ca3a-7c28-11e7-8122-1b10af15163a.png)

Note the screen shows Namespace: rbenevid and it should show Space: myspace instead.

**Comment by corinnekrych** [comment]
fixed in https://github.com/openshiftio/openshift.io/issues/966
