### ISSUE TITLE
First build/application version created is 1.0.1 - why not 1.0.0

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#485]
Small point, but the first build/application version created is assigned a version number of 1.0.1

Why isn't this 1.0.0?

![screenshot from 2017-08-08 11-06-33](https://user-images.githubusercontent.com/642621/29078975-e619f1e8-7c29-11e7-93eb-841e03e7fb7e.png)

**Comment by joshuawilson** [comment]
@jstrachan @rawlingsj any ideas?

**Comment by qodfathr** [comment]
Closing by design. As you said in the title, it's the *first* build, and first == 1. :)

Yes, that's a lame answer, but it will be sufficient for now.

**Comment by joshuawilson** [comment]
It is designed to be `1.0.1` for the first version instead of `1.0.0`?
