### ISSUE TITLE
Scale option is present in Applications view - but it fails

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#487]
See attached screenshot - This option fails and should be removed from the UI. Thx!

![screenshot from 2017-08-08 11-21-23](https://user-images.githubusercontent.com/642621/29079733-efc3578c-7c2b-11e7-8eff-9b73726840de.png)

This erorr is raised in the Chrome console log when the user attempts to scale the app:

```
patternfly.min.css:1 ERROR SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at CatchSubscriber.selector (main.0c8809c….bundle.js:1)
    at CatchSubscriber.error (patternfly.min.css:1)
    at MapSubscriber.Subscriber._error (patternfly.min.css:1)
    at MapSubscriber.Subscriber.error (patternfly.min.css:1)
    at MapSubscriber.Subscriber._error (patternfly.min.css:1)
    at MapSubscriber.Subscriber.error (patternfly.min.css:1)
    at XMLHttpRequest.a (main.0c8809c….bundle.js:1)
    at ZoneDelegate.invokeTask (polyfills.f49acb8….bundle.js:1)
    at Object.onInvokeTask (patternfly.min.css:1)
    at ZoneDelegate.invokeTask (polyfills.f49acb8….bundle.js:1)
    at Zone.runTask (polyfills.f49acb8….bundle.js:1)
    at XMLHttpRequest.ZoneTask.invoke (polyfills.f49acb8….bundle.js:1)
defaultErrorLogger @ patternfly.min.css:1
ErrorHandler.handleError @ patternfly.min.css:1
next @ patternfly.min.css:1
t.object.o @ patternfly.min.css:1
SafeSubscriber.__tryOrUnsub @ patternfly.min.css:1
SafeSubscriber.next @ patternfly.min.css:1
Subscriber._next @ patternfly.min.css:1
Subscriber.next @ patternfly.min.css:1
Subject.next @ patternfly.min.css:1
EventEmitter.emit @ patternfly.min.css:1
NgZone.triggerError @ patternfly.min.css:1
onHandleError @ patternfly.min.css:1
ZoneDelegate.handleError @ polyfills.f49acb8….bundle.js:1
Zone.runTask @ polyfills.f49acb8….bundle.js:1
ZoneTask.invoke @ polyfills.f49acb8….bundle.js:1
```

**Comment by rgarg1** [comment]
The Scale option the Environment page too has no effect.

**Comment by joshuawilson** [comment]
I don't think the error is related, as I get it when I go to the Create tab.
@jstrachan is this feature broken or just some mocked up UI?

**Comment by jstrachan** [comment]
The feature has been working for many months. Is suspect this is related to the DNS/IP issues OSO that Aslak has been taking about lately - temp fix is bounce f8ui pods to flush DNS cache and longer term fix is in OSO AFAIK

**Comment by ldimaggi** [comment]
James - which pods are these pods? We are already dropping and recreating everything in the user's OSO account.

_temp fix is bounce f8ui pods to flush DNS cache and longer term fix is in OSO AFAIK._

**Comment by jstrachan** [comment]
The fabric8-UI pods that host the web console & nginx proxy to the OSO rest api

**Comment by jstrachan** [comment]
Is this now fixed? Could have been the same issue that broke Delete too?

**Comment by aslakknutsen** [comment]
@jstrachan It's possible. I think I only checked DELETE. But I'm guessing PUT would be 405 on a 'static webroot' in nginx as well.

**Comment by jstrachan** [comment]
its working fine for me in prod - I guess its fixed. Gonna close this - we can reopen if it can be reproduced
