### ISSUE TITLE
"Settings" option does not work

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#490]
See attached screenshot:

![screenshot from 2017-08-08 11-57-22](https://user-images.githubusercontent.com/642621/29082010-45b31af0-7c32-11e7-9f65-f950679535a7.png)

**Comment by joshuawilson** [comment]
Where did you go to find that?
@dgutride once he can show you how to reproduce it, can you please take a look.

**Comment by ldimaggi** [comment]
It's here:

![screenshot from 2017-08-09 13-08-50](https://user-images.githubusercontent.com/642621/29134289-2f23e86e-7d04-11e7-97df-aa24cc594442.png)

But - it's not behaving the same today. I think than we can close this bug.

**Comment by joshuawilson** [comment]
Please reopen if you can reproduce this.
