### ISSUE TITLE
Errors when creating Work items

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#493]
When you create the work item using the following button (that is only available on empty work items screen)

![screenshot 2017-08-09 12 31 16](https://user-images.githubusercontent.com/30131/29132602-bf8fa5f6-7cfe-11e7-9ff9-9f95a7b57f56.png)

It only allows you to add a title, but not a description. When you save the work item, it gives the following error message: "/rbenevid%252540redhat.com/myspace/plan?q=(space%3A5866d924-2026-4e7e-bd74-d383dc838a19%20%24AND%20workitemtype%3Ab9a71831-c803-4f66-8774-4193fffd1311%2C3194ab60-855b-4155-9005-9dce4a05f1eb%2C71171e90-6d35-498f-a6a7-2083b5267c18%2Cee7ca005-f81d-4eea-9b9b-1965df0988d0%2C6d603ab4-7c5e-4c5f-bba8-a3ba9d370985) not found"

The following video shows how to reproduce it.

https://www.dropbox.com/s/d858mtwq1xwm4ee/work%20items%20errors.mov?dl=0

**Comment by michaelkleinhenz** [comment]
This will be addressed with #265
