### ISSUE TITLE
Che Workspace restarts anyway 

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#502]
My workspace stopped responding, while I was trying to type/edit/click on the editor. It showed this message: 

https://drive.google.com/open?id=0BwLIZeed5jyKWWdRMUZLazByWmc

I selected 'CLOSE', still my workspace restarted anyways! That 'Close' button' is a bug as its not expected to restart the workspace.

**Comment by l0rd** [comment]
@eivantsov do the close button works fine on Docker? Do you think is an OpenShift connector specific issue?

**Comment by eivantsov** [comment]
@l0rd close button causes workspace to stop and snapshot is created (if snapshotting is configured).

@rgarg1 How did you workspace restart? I've just tried killing ws agent in a running workspace and swa the same behavior - workspace was stopped.

**Comment by l0rd** [comment]
I haven't seen that lately. I should have been fixed. @rgarg1 please let me know if we can close this issue.

**Comment by rgarg1** [comment]
@l0rd You can close it for now. Will reopen if I see it again.
