### ISSUE TITLE
Overlapping text in Che editor

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#503]
Observed overlapping text in Che editor when the workspace was loaded. Notice the red X icon on the vertx project, indicating https://github.com/redhat-developer/rh-che/issues/230:

https://drive.google.com/open?id=0BwLIZeed5jyKQzg1WmRKWThtTUk

This issue is intermittent in nature and cannot be reproduced at will, at least as of now.

**Comment by l0rd** [comment]
@eivantsov are you aware of any issue of this kind?

**Comment by eivantsov** [comment]
@l0rd it looks like the file was opened twice somehow. This is a similar issue in Che and I have reopened it https://github.com/eclipse/che/issues/4952

**Comment by l0rd** [comment]
@eivantsov @rgarg1 does this issue still exist? If yes how can we reproduce it?

**Comment by l0rd** [comment]
@l0rd <https://github.com/l0rd> yes, it can be reproduced in Che

How? :-)

**Comment by eivantsov** [comment]
https://github.com/eclipse/che/issues/4952 when trying to open the same file twice

**Comment by eivantsov** [comment]
Should be fixed by https://github.com/eclipse/che/pull/6478

**Comment by joshuawilson** [comment]
Can we close this?

**Comment by eivantsov** [comment]
I think so. The issue's fixed in the upstream.
