### ISSUE TITLE
Post successful login, OSIO user is sometimes not redirected to the 'home' page

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#504]
After users enter their's userID and Passwords into the login windows of OSIO, they are usually redirected to the home page, with their user-name showing up on the top-right corner of the window.

This indicates a successful login.

However, sometimes even after entering the (correct) login credentials, the user is not redirected to the home page and is left staring at the login screen. Instead of his user-name, the top-right corner of the window shows 'Login', giving an impression that the login failed.

However, if the user clicks on the login button once more (just a click. Re-entering credentials is not needed), he is successfully logged in and redirected to the OSIO home page.

The behavior is intermittent.

**Comment by ldimaggi** [comment]
Ruchir - can you add a screenshot of what this looks like? Thx!

**Comment by joshuawilson** [comment]
@alexeykazakov I have seen this too. I don't know if it is a UI thing completely or an Auth thing partly. Do you have any ideas?

**Comment by rgarg1** [comment]
@ldimaggi I tried many times to reproduce this issue while I was recording the screen, but seems like the issue is a little camera shy. Will provide a video proof as soon as I can catch it.

**Comment by rgarg1** [comment]
Got lucky! Here is the proof:
https://drive.google.com/open?id=0BwLIZeed5jyKbHg5Rm5DaV9lcEU

**Comment by joshuawilson** [comment]
@dgutride can you please take a look at this too.

**Comment by joshuawilson** [comment]
Closing as this has been fixed for a while and we have a new flow in place too.
