### ISSUE TITLE
Build Configuration window of the Forge Wizard should not have the 'Next' button

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#505]
While importing an existing repository from GitHub, I observed that on the Forge Wizard's 'Build Configuration' page, it is possible to make the 'Next' button enabled, even though this is the last page of the wizard and the 'Next' button should not even exist.

Method to make the Next button enabled: Check and uncheck any of the checkbox and the Next button should be enabled.

Clicking the Next button brings the user back to the same Build Configuration page. Just remove the Next button.

**Comment by rgarg1** [comment]
![forge noneditable fields](https://user-images.githubusercontent.com/28748448/29108790-0fcb5b42-7cfe-11e7-8a23-c885607037c9.png)

**Comment by corinnekrych** [comment]
fixed in https://github.com/openshiftio/openshift.io/issues/966
