### ISSUE TITLE
Suggestion looks like error on the Forge Wizard's 'Github repository' page

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#506]
While importing an existing repository from GitHub, I observed that on the Forge Wizard's 'Github repository' page, the suggestion regarding repository name pattern is:

1) Not too intuitive for a user
2) The Red color makes it look like an error has occurred
3) The message doesn't go away even after a repository is successfully selected

**Comment by rgarg1** [comment]
![forge notice](https://user-images.githubusercontent.com/28748448/29108968-c97c8bc4-7cfe-11e7-9cde-11a086c58a67.png)

**Comment by corinnekrych** [comment]
fixed in https://github.com/openshiftio/openshift.io/issues/966
