### ISSUE TITLE
The field to specify 'Jenkins space' in the Forge Wizard is non-editable, but appears unlike it

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#507]
The field to specify 'Jenkins space' in the Forge Wizard is non-editable, but it appear like a mandatory and editable field. The user only realizes its non-editable when a mouse-over displays a not-allowed symbol.

Suggestion: Make this filed greyed-out to remove confusion. Or just remove it.

Also, the field labels aligned toward the right don't make a pretty sight.

**Comment by rgarg1** [comment]
![forge noneditable fields](https://user-images.githubusercontent.com/28748448/29109073-530c482a-7cff-11e7-95a8-bd929042f734.png)

**Comment by corinnekrych** [comment]
fixed https://github.com/openshiftio/openshift.io/issues/966
