### ISSUE TITLE
Pipeline page should wait to display the Stage/Run stage as complete, until the POD is up and ready

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#508]
The Pipeline page i OSIO displays the Rollout to Stage/Rollout to Run as complete, even when the POD is actually being built. This leads to the user trying to open a page that does not exists. The status update on OSIO should be in sync with the POD status in OSO.

**Comment by jstrachan** [comment]
yeah, this is a known issue - hoping to have a fix soon

**Comment by qodfathr** [comment]
This is still an issue, but I'm not sure I 100% agree with the proposed solution of not displaying the stage until the pod is up and ready. ((1) What if it never becomes ready? (2) in Jenkins, the next stage will have already started running and we want to show that.) I think instead we need some additional visual cues -- e.g. don't show the link to the application until the pod is ready (and perhaps some other form of text or spinner while the pod is starting. Or maybe the stage needs another color (e.g.: gray -- starting; blue -- running; purple -- waiting for external stuff to finish but rest of pipeline not blocked; green -- fully done; red -- failed; yellow -- needs approval))

@catrobson does UXD have any pipeline proposals which would address this?

**Comment by catrobson** [comment]
We don't have any updated proposals around the pipeline page yet.  I do think you're right @qodfathr that we'll want there to be a distinction around status/completeness of the stage vs. things that are linked off of that stage.  The pipeline might progress while work is still being done on elements in a previous stage.  

For now, if we could complete the stage, but use a spinner and a notice that the Pod is still building beneath that step that would be desirable.  We could do a soft cleanup of this UI page that doesn't look to evolve it, but just clean up UI issues like this, if there are resources who could pick up the work from a UI Dev standpoint.

**Comment by joshuawilson** [comment]
@qodfathr I think we should downgrade this to SEV3. Is this something you want fixed by GA?

**Comment by qodfathr** [comment]
@joshuawilson I think SEV3 is correct for now.

**Comment by qodfathr** [comment]
Per #884 , which should apply the solution/logic in the Promotion modal dialog box, which also has a link to view the application and suffers the same problem today.

**Comment by piyush1594** [comment]
@rgarg1 This is very old and not the case now. Can you please confirm and close?

**Comment by sthaha** [comment]
@rgarg1 I am going to close this issue as this isn't the case anymore. Please reopen if you see otherwise.
