### ISSUE TITLE
Running build info inconsistencies between various pages  

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#509]
Have a project 'hellovertx1' and the OSIO dashboard was showing that:
- Build#4 is in progress

The Pipeline page in OSIO displayed:
- Only Build#1 as active

The Pipelines in OSO show that:
- Build#2,3,4 in a state where no stages have started
- Build#1 as active

The Jenkins console shows only:
- Build#1

There has to be some consistencies between what data is displayed to the users. If we choose to show only active builds, then why do we display Build#4 in OSIO Dashboard? For that matter, even OSO pipeline page.

**Comment by rgarg1** [comment]
![pipeline in osio dashboard](https://user-images.githubusercontent.com/28748448/29114653-92db0be0-7d12-11e7-8deb-bb49ba610f41.png)

OSIO Dashboard

**Comment by rgarg1** [comment]
![pipeline in osio](https://user-images.githubusercontent.com/28748448/29114682-a7554c16-7d12-11e7-82b2-d4eba2d64449.png)
Pipeline page in OSIO

**Comment by rgarg1** [comment]
![pipeline in oso](https://user-images.githubusercontent.com/28748448/29114703-b99fa632-7d12-11e7-9132-3ed5aa2d09c4.png)
Pipelines in OSO

**Comment by rgarg1** [comment]
![builds in jenkins](https://user-images.githubusercontent.com/28748448/29114719-c572fef0-7d12-11e7-9612-8d7c2b51c77f.png)
Builds in Jenkins

**Comment by joshuawilson** [comment]
This appears to be related to zombies #447

**Comment by rawlingsj** [comment]
This should be fixed with Jenkins 3.0.81 https://github.com/fabric8io/jenkins-sync-plugin/commit/db03e025f3519b6ad8dd75c7ed05d03847f920fd please reopen if not.
