### ISSUE TITLE
'Open in IDEA' tooltip needs to be fixed

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#510]
In OSIO, browse to the Pipeline page and select the kebab menu to display more options for the repository. Hover the mouse of the option 'Open in IDEA' and view the tooltip. It has a '\n' from the code included.

**Comment by rgarg1** [comment]
![intellij tooltip](https://user-images.githubusercontent.com/28748448/29115535-9d7b0d72-7d15-11e7-8068-e0ed0dddb0b6.png)

**Comment by joshuawilson** [comment]
I think the whole line should be removed since we are not doing anything with IDEA.

**Comment by qodfathr** [comment]
@joshuawilson you are correct that we decided to remove this. Does someone own that or is there a type/task which exists for getting that done?

**Comment by joshuawilson** [comment]
@qodfathr there is no task for this.
@chrislessard do you want to fix this?

**Comment by chrislessard** [comment]
@joshuawilson on it

**Comment by chrislessard** [comment]
Fix under review here https://github.com/fabric8-ui/fabric8-ui/pull/2452

**Comment by qodfathr** [comment]
Reopening because this fix is not live in prod yet.

**Comment by chrislessard** [comment]
@qodfathr ah, sorry about that :)

**Comment by qodfathr** [comment]
**Now** it's fixed. :)
