### ISSUE TITLE
Codebases widget and page are showing the same repo twice

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#511]
After creating a new space and creating a new project from the forge wizard, I have 2 repositories shown:
- In "codebase widget" displayed on the space's dashboard:
![screen shot 2017-08-09 at 11 48 16](https://user-images.githubusercontent.com/1636769/29115917-84972f82-7cf9-11e7-81a7-d457e97e6af4.png)

- In the codebase page:
![screen shot 2017-08-09 at 11 52 17](https://user-images.githubusercontent.com/1636769/29115926-88144c3a-7cf9-11e7-8da1-57c07cf72e2e.png)

**Comment by slemeur** [comment]
This error happened only one time. When I was refreshing the browsing, I was still having 2 repos displayed.

I created another space+project - that time it is displaying the repo only one time.

**Comment by joshuawilson** [comment]
It sounds like a caching issue. When you can reproduce it please post how. Until then, I'm closing this as not reproducible.
