### ISSUE TITLE
Triggering any build with a git push launched 3 builds at a time

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#512]
Triggered a build with a git push, which launched 3 builds at the same time. 

Repo: https://github.com/rgargosiotest1/hellovertx1

Snapshot attached. Kindly see the time-stamp, which indicates that all three builds started at the same time. The trigger was a git push from the Che Workspace.

**Comment by rgarg1** [comment]
![3 builds triggered](https://user-images.githubusercontent.com/28748448/29117199-ff9c93fe-7d1a-11e7-92ed-6d09ce0ff2a3.png)

**Comment by ldimaggi** [comment]
See:
https://github.com/openshiftio/openshift.io/issues/342

**Comment by rgarg1** [comment]
In this case, the 3 builds were simultaneously triggered in the intended pipeline only.

**Comment by rawlingsj** [comment]
This should be fixed with Jenkins 3.0.81 https://github.com/fabric8io/jenkins-sync-plugin/commit/db03e025f3519b6ad8dd75c7ed05d03847f920fd please reopen if not.
