### ISSUE TITLE
Che: File downloaded during "Starting workspace runtime" is empty

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#513]
Starting che workspace (Burr's demo workflow) I clicked Download outputs in Che UI. The downloaded file has only "null" in it.
![image](https://user-images.githubusercontent.com/1215011/29119379-31a7a768-7d06-11e7-9c51-390a9e052e35.png)

**Comment by l0rd** [comment]
I confirm that this is reproducible on OSIO right now

**Comment by ibuziuk** [comment]
I believe this functionality have never worked with OpenShiftConnector

**Comment by ibuziuk** [comment]
rh-che issue - https://github.com/redhat-developer/rh-che/issues/360

**Comment by benoitf** [comment]
Fix has been merged in upstream che, it will be included in che 5.0.20

**Comment by joshuawilson** [comment]
Closing, if this is still an issue please reopen.
