### ISSUE TITLE
Che: Editor detects changes while no edition is done which fire autosave

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#516]
**Reproduction Steps:** 
- Use Vert.x sample and run the project from Che
- Open 'HttpApplocation.java' file
- Start editing the file
- Stop editing the file
- File is automatically saved by Che and hot redeploy is triggered

**Expected Behaviour:** Once the edition is done, the editor detects that there are no changes in the source code file. 

**Current Behaviour:** The editor keeps seeing changes in the file which trigger an autosave of the file and a hot redeploy. This is turning into infinite loop until the file is closed.

See attached video:
![autosave-in-loop](https://user-images.githubusercontent.com/1636769/29122486-cc11a586-7d12-11e7-9700-12586fd94cf7.gif)

**Comment by ibuziuk** [comment]
@slemeur is it still reproducible against 1.0.294 ?

**Comment by l0rd** [comment]
@slemeur I cannot reproduce this. Can we close?

**Comment by slemeur** [comment]
I confirm I cannot reproduce it either.
