### ISSUE TITLE
Sort option on the Pipeline page is broken

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#520]
The sorting option on the Pipeline page is broken and has no effect on the displayed results.

See attached video for reference.

https://drive.google.com/open?id=0BwLIZeed5jyKTGVtTEVKbnVUbWM

**Comment by rgarg1** [comment]
Sorting is also broken on the 'Applications' page.

**Comment by joshuawilson** [comment]
It is fake, there is no implementation yet.
Duplicate of #489
Closing.
