### ISSUE TITLE
Codebases page scroll bars acting funny

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#521]
The scroll bars on the Codebases page appear and go for no reason at all. They should not appear unless there are too many entries to scroll on the page in first place. Have a look:

https://drive.google.com/open?id=0BwLIZeed5jyKVDlQLTc1TV96cDQ

**Comment by joshuawilson** [comment]
@mindreeper2420 can you look at this too, please.

**Comment by qodfathr** [comment]
Fixed.
