### ISSUE TITLE
Intermittent issue - project builds fail -  Unexpected error when retrieving changeset

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#522]
Seeing an intermittent issue where project builds fail. 

The Jenkins pod log reports this error:

SEVERE: Unexpected error when retrieving changeset
hudson.plugins.git.GitException: Error launching git whatchanged

It's not clear what is causing this - timing or network issues?

![screenshot from 2017-08-09 09-33-57](https://user-images.githubusercontent.com/642621/29124479-06a7894e-7ce7-11e7-98cc-44020014fb7a.png)

[build_log.txt](https://github.com/openshiftio/openshift.io/files/1211576/build_log.txt)

[jenkins_pod_log.txt](https://github.com/openshiftio/openshift.io/files/1211573/jenkins_pod_log.txt)

**Comment by joshuawilson** [comment]
I saw this several days ago too. Are you still seeing it? It works for me now.

**Comment by ldimaggi** [comment]
I have not seen this for a few days 0 closing this issue - will re-open if the issues returns.
