### ISSUE TITLE
Project created in github shows committed with ?

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#524]
![screenshot 2017-08-09 10 33 30](https://user-images.githubusercontent.com/30131/29127145-39817058-7cee-11e7-8f16-de725f03a38d.png)

**Comment by rhopp** [comment]
Yep. I saw this one too, but made just comment about that into demo document.

**Comment by ppitonak** [comment]
It would be nice if user could choose email for commits on Forge wizard (user can have different email in OSIO account and GitHub account)

**Comment by joshuawilson** [comment]
@ppitonak can you write that up as a request for enhancement. Adding it to a bug will get it lost.

**Comment by joshuawilson** [comment]
@aslakknutsen @alexeykazakov do you know why the username isn't being used? Or whatever is supposed to be used.

**Comment by alexeykazakov** [comment]
It's an issue with our app generator/wizard. It's supposed to obtain the user's email from github using the github token. @aslakknutsen should know details.

**Comment by aslakknutsen** [comment]
https://github.com/fabric8io/fabric8-generator/issues/32

A possible workaround/normal solution would be to make the commit as some 'OSiO user' as opposed to the user. Similar to how a CI/CD bot would do.

**Comment by l0rd** [comment]
Opened issue https://github.com/redhat-developer/rh-che/issues/299 to address that in next sprint

**Comment by aslakknutsen** [comment]
@l0rd this issue is for the Wizard and is fixed: fabric8io/fabric8-generator#32

@rafabene Can you verify?

**Comment by l0rd** [comment]
@aslakknutsen ok thanks. Note that I was able to reproduce it during thursday workshop (2 days ago). But only the first initial commit had the question mark. The commits done via Che didn't had the issue. This confirm that it's a wizard only issue.

**Comment by aslakknutsen** [comment]
@l0rd @rafabene Ah, the updated generator-backend is not in prod yet.

**Comment by rafabene** [comment]
Still waiting for going to prod to check it.

**Comment by joshuawilson** [comment]
@rafabene please validate.

**Comment by rafabene** [comment]
It still happening

![screenshot 2017-09-07 17 58 48](https://user-images.githubusercontent.com/30131/30189464-f447877c-9401-11e7-91b5-0174fad62db5.png)

**Comment by rafabene** [comment]
This doesn't happen anymore. Closing
