### ISSUE TITLE
Stack Analysis is missing from the UI

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#528]
After a build pipeline runs, a stack analysis should be displayed, regardless of whether the build was successful or not.

It is missing from the UI as of August 9:

![screenshot from 2017-08-09 13-34-15](https://user-images.githubusercontent.com/642621/29135371-dd9feee4-7d07-11e7-9cf8-9398aec99dd3.png)
![screenshot from 2017-08-09 13-31-04](https://user-images.githubusercontent.com/642621/29135372-dda0dbb0-7d07-11e7-898a-e8f05df2c44e.png)

**Comment by samuzzal-choudhury** [comment]
@ldimaggi Thanks for reporting. We are looking into this.

**Comment by samuzzal-choudhury** [comment]
@ldimaggi could you please recheck? The stack report on space dashboard and a stack report link in the Pipelines tab should be available now (as of Aug 11). 

![image](https://user-images.githubusercontent.com/17740190/29206043-cc3e1594-7e9d-11e7-86be-1898ecec8d84.png)

**Comment by samuzzal-choudhury** [comment]
![image](https://user-images.githubusercontent.com/17740190/29206069-eb1d3332-7e9d-11e7-8840-636a9bdcc41d.png)

**Comment by samuzzal-choudhury** [comment]
IMO, this issue was caused by https://github.com/openshiftio/openshift.io/issues/545.

**Comment by joshuawilson** [comment]
I'm now seeing analytics reports. @ldimaggi can you please confirm.

**Comment by ldimaggi** [comment]
I am seeing analytics in the UI - but no reports:

![screenshot from 2017-08-13 23-04-11](https://user-images.githubusercontent.com/642621/29256900-e028d1ea-807b-11e7-9317-ac5af468d214.png)

Should a report be generated for each and every build?

**Comment by samuzzal-choudhury** [comment]
@ldimaggi a report should be generated for every build. I can see from the screenshot that your `aug13-build#1` build was still in progress. Could you please check your pipelines status for `aug13-build#1`?

Here is the related issue https://github.com/openshiftio/openshift.io/issues/545. So, it will be really interesting to check your build log for the error 503. Could you please share your build report or search for the word `bayesian-link` in your build report and verify if you are getting an HTTP error 503?

**Comment by jyasveer** [comment]
@ldimaggi There was a issue here. If pipelines were not ready or in progress, it would show a blank widget. Now this is fixed now. Please find the screenshot below
<img width="1440" alt="screen shot 2017-08-19 at 8 01 09 am" src="https://user-images.githubusercontent.com/5430080/29482722-a2b6aa20-84b4-11e7-913e-61223940e581.png">

Can I close this issue now ?

**Comment by ldimaggi** [comment]
Closing - fix confirmed. Thx!
