### ISSUE TITLE
Importing existing code results in multiple build pipelines - should be only 1

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#529]
Steps to recreate:
* Fork https://github.com/burrsutter/vertx-eventbus
* In a clean OSIO user account, create a new space, and import the forked github repo

Observe that multiple build pipelines are initiated - all at the same time:

![screenshot from 2017-08-09 13-28-54](https://user-images.githubusercontent.com/642621/29135528-6f1bfb74-7d08-11e7-817b-4d61521beac1.png)

![screenshot from 2017-08-09 13-25-41](https://user-images.githubusercontent.com/642621/29135554-83d4c67c-7d08-11e7-98a1-d12675baadf7.png)

**Comment by ldimaggi** [comment]
Seeing 5 this time:

![screenshot from 2017-08-09 14-42-08](https://user-images.githubusercontent.com/642621/29138223-02badc8a-7d11-11e7-8b22-9852c4d74a61.png)

**Comment by ldimaggi** [comment]
Is this issue caused by the project being imported having a JenkinsFile before the import is performed?

**Comment by ldimaggi** [comment]
Yup - this issue seems to be tied to the Jenkins file in the event bus repo:

![screenshot from 2017-08-09 15-13-51](https://user-images.githubusercontent.com/642621/29139594-78ce9228-7d15-11e7-969a-217fdf31a315.png)

**Comment by rgarg1** [comment]
Similar to #512 ?

**Comment by rafabene** [comment]
This also causes Jenkins to complain about quota

> io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/api/v1/namespaces/rbenevid-jenkins/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "jenkins-slave-plv20-gl2kl" is forbidden: exceeded quota: compute-resources-timebound, requested: limits.cpu=2500m,limits.memory=1280Mi, used: limits.cpu=2500m,limits.memory=1280Mi, limited: limits.cpu=4,limits.memory=2Gi.

**Comment by rawlingsj** [comment]
This should be fixed with Jenkins 3.0.81 https://github.com/fabric8io/jenkins-sync-plugin/commit/db03e025f3519b6ad8dd75c7ed05d03847f920fd please reopen if not.

**Comment by rgarg1** [comment]
I saw this today once. Will come back with proof.
