### ISSUE TITLE
Users can view existing github repos that do not belong to them during import - but the import fails

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#530]
Steps to recreate:
* In a clean OSIO user account, create a new space and select 'import existing code'
* Observe that repos that are not owned by the user are displayed
* Attempting to import one of these repos not owned by the user fails with this error:

![screenshot from 2017-08-09 13-03-11](https://user-images.githubusercontent.com/642621/29135761-356f15cc-7d09-11e7-953a-7e8fb67bd996.png)

**Comment by joshuawilson** [comment]
This is related to the other "import" issues.

**Comment by jstrachan** [comment]
the UI currently lets you pick from organisations you are a member of; however it doesn't have a way currently of knowing if you have write access to the repo you pick. A stack trace might help; am guessing its failing to commit/push changes? 

I guess the forge back end could query permissions in github and if there's no write access create a PR instead

**Comment by jstrachan** [comment]
@corinnekrych fancy experimenting with this one? We may want to modify the git push code https://github.com/fabric8io/fabric8-generator/blob/master/src/main/java/io/fabric8/forge/generator/git/GitCommitAndPushStep.java#L64 to for github check if a user has write access and if not do a commit and create a PR instead (then store the PR details in the results so that we can display the PR links to the UI).

I guess we may also want to allow users always doing PRs too rather than direct commits; so we may need a boolean flag being added to the wizard

**Comment by corinnekrych** [comment]
@jstrachan I think there are different ways of getting this error.
Here is the flow how I get it:
1. start import wizard
2. select default organisation (ie: corinnekrych), next
3. all repositories from all organisations are disaplayed (other 600 for me)
this is wrong:
expected: only the repo that belongs to corinnekrych should be displayed
4. select `3musket33rs.github.com` that belongs to `3musket33rs` organisation, finish
Error displayed:
```
ExecuteForgeCommandError
The fabric8-import-git :: execute :: 4 command failed or only partially succeeded
message
Failed to clone repository https://github.com/corinnekrych/3musket33rs.github.com.git due to org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
```
indeed `https://github.com/corinnekrych/3musket33rs.github.com.git` does not exist.
I've opened an issue some time ago on this topic: https://github.com/fabric8io/fabric8-generator/issues/17 (although closed I think this is still an issue)

@ldimaggi is it your use-case?

**Comment by jstrachan** [comment]
@corinnekrych ah thanks - I thought we'd fixed that `only show repos for the selected org` bug a while back - I guess its back

**Comment by corinnekrych** [comment]
fixed
