### ISSUE TITLE
The 'Codebases' tab should display the repo imported date too

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#539]
Right now the Codebases page only shows data taken from Github, but not the date when the repository was actually imported into OSIO. Knowing when a repo actually was imported into the system may add value to the user.

**Comment by rgarg1** [comment]
![no imported date column](https://user-images.githubusercontent.com/28748448/29159304-84527794-7d9d-11e7-9b82-924fb52f7faf.png)

**Comment by slemeur** [comment]
@rgarg1 In your latest screenshot, it seems you have the same repository displayed twice as I described in the following issue #511. Do you confirm ?

**Comment by rgargosiotest1** [comment]
No. The duplicate repos are intentional in my case. I added same repo twice using different methods.

**Comment by rgarg1** [comment]
No. The duplicate repos are intentional in my case. I added same repo twice using different methods.

**Comment by slemeur** [comment]
Ok thanks.

**Comment by aslakknutsen** [comment]
@rgarg1 What value does that bring?

**Comment by aslakknutsen** [comment]
@catrobson Not sure if this value has been considered during Codebase redesign? Personally, I'm not sure why I would want/need to know that information, but it's a UX call.

**Comment by catrobson** [comment]
@aslakknutsen @rgarg1 I agree with Aslak that this is not valuable information for this view.  We'll eventually be heading towards @slemeur's suggestions for the list view here which will only show the last commit along with some other more relevant daily metrics for the user to see.  https://redhat.invisionapp.com/share/94CH0VNV5#/screens/241681656

**Comment by joshuawilson** [comment]
I do not see the value to the dev. Maybe some value in testing the app to verify that the codebase was added. 

Since this page is being rewritten I'm closing this. You can still post your reasons/value gained and it can be incorporated into the new design.
