### ISSUE TITLE
Failed to import a spring boot project generated via launch.openshift.io

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#541]
1) Generated this Spring boot project https://github.com/rgarg1/osio-springboot using launch.openshift.io
2) Forked it to https://github.com/rgargosiotest1/osio-springboot
3) Imported it using the Add codebase wizard of OSIO
4) Even though no errors were displayed, the Forge wizard hung at the final screen and the codebase was never added.

Video: https://drive.google.com/open?id=0BwLIZeed5jyKV0taYWJyWHE0YzQ

**Comment by joshuawilson** [comment]
The 2 projects are not compatible. At least not yet. 
Why did you try this? Did someone ask for it? 
@burrsutter @ldimaggi did you want this tested and tracked? OR can we close this?

**Comment by ldimaggi** [comment]
I did not think that we were testing with launch.openshift.io - I thought that we were importing "vanilla" projects as specified by Burr.

But - users may try this - if we cannot support this, then we should make this clear to users. How are the projects not compatible? Thx!

**Comment by joshuawilson** [comment]
They use a different OSO structure. We are working on making them compatible and so it should be tested. But only after we let you know it works.

**Comment by krishnapaparaju** [comment]
@rgarg1 I could not reproduce this issue.. Wizard is doing good, build pipelines are kicking in, could see stack report. Can you please recheck and close this issue..

cc @qodfathr

**Comment by rgarg1** [comment]
The issue is not reproducible anymore. Closing this.
