### ISSUE TITLE
Menu Application -> Delete isn't working

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#542]
I've tried to remove an Application from Stage by clicking the following menu and nothing happens.

![screenshot 2017-08-10 09 19 58](https://user-images.githubusercontent.com/30131/29172200-380636e0-7dad-11e7-92dd-b1bd5f1bebe5.png)

**Comment by joshuawilson** [comment]
@jstrachan do you know if this is supposed to work? What does it delete?

**Comment by jstrachan** [comment]
yes its supposed to work; it currently deletes the BuildConfig (i.e. the pipeline).

It looks like the nginx proxy in fabric8-ui is not allowing DELETE so we get a 405 when we try to delete anything in OpenShift.

**Comment by aslakknutsen** [comment]
I think this is related to the wwwopenshiftio proxy. It never seems to reach the f8ui proxy.

Suspect it's related to the 'try_files' directive set in place to return index.html on 404, it tries to delete on local fs first, but fail with 405 and return without going to the proxy pass.

**Comment by jstrachan** [comment]
@aslakknutsen ah cool thanks

**Comment by aslakknutsen** [comment]
@jstrachan and it tried to delete the DeploymentConfig not the BuildConfig ;)

**Comment by jstrachan** [comment]
depends on which page you click Delete; the Pipelines page deletes BuildConfigs, the Apps page deletes DeploymentConfigs and the Environments page deletes whatever tab you've got open (Services / Pods / DeploymentConfigs / Routes / ConfigMaps etc)

**Comment by aslakknutsen** [comment]
@jstrachan Yes of course. But in the context of this issue.. :)

**Comment by aslakknutsen** [comment]
Fix pushed to prod and can verified

**Comment by jstrachan** [comment]
@aslakknutsen awesome! Tried `Delete` on `Pipelines` and `Apps` pages in prod and both now worked perfectly now!

**Comment by joshuawilson** [comment]
Thanks @aslakknutsen
