### ISSUE TITLE
Importing two projects at the same time gives me empty screen and the ok button doesn't work

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#544]
I've selected two projects to import and the following empty screen appears. 
![screenshot 2017-08-10 09 25 18](https://user-images.githubusercontent.com/30131/29172444-fd6afff6-7dad-11e7-928c-a9f0910a6b7b.png)

We have three problems here. 

1 - The message should say "Your application(s) has/have been imported"

2 - The projects name should appear

3 - The ok button doesn't work

**Comment by corinnekrych** [comment]
Related to https://github.com/fabric8io/fabric8-generator/issues/40
if you import a project twice forge add-on backend return an empty result

**Comment by rgarg1** [comment]
@rafabene I see the empty screen with just one project too: https://drive.google.com/open?id=0BwLIZeed5jyKV0taYWJyWHE0YzQ

**Comment by rafabene** [comment]
I've tried it now and it only shows the latest selected project.

**Comment by corinnekrych** [comment]
fixed in https://github.com/openshiftio/openshift.io/issues/966
