### ISSUE TITLE
Intermittent issue - Codebase is not created when a new quickstart project is created

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#547]
This issue is similar to:  https://github.com/openshiftio/openshift.io/issues/517

Steps to recreate:
* Create a new project from a quickstart, and...
* Sometimes a codebase is not created:

![screenshot from 2017-08-10 10-42-25](https://user-images.githubusercontent.com/642621/29179144-986ec966-7dc1-11e7-9987-c0281a1ba881.png)

**Comment by joshuawilson** [comment]
Are there any errors when this happens?

**Comment by ldimaggi** [comment]
I don't think that there is anything in the log - will verify when it happens next.

**Comment by ldimaggi** [comment]
Closing - I think that this issue is the root cause:
https://github.com/openshiftio/openshift.io/issues/595
