### ISSUE TITLE
Planning/Board "currently showing" should have 'all' option (as default?)

### ISSUE THREAD

**Issue by pilhuhn** [openshiftio/openshift.io#551]
I set up (as first and only thing) a task to do something. Whenever I come to to Plan/Board, it basically shows empty all over the place because 'Bug' is pre-selected.

Perhaps add a "All" category to the "Currently showing" dropdown.
Or on the left don't show 0 for All, but something like 0/1 to indicate that there are (hidden) items.
(Actually it looks like it always shows 0).

On the backlog tab, it shows the task.

**Comment by joshuawilson** [comment]
cc @michaelkleinhenz

**Comment by slemeur** [comment]
+1 with the proposal.

I got trapped with that issue too.

**Comment by rgarg1** [comment]
@pilhuhn Kindly check now with the latest version, where All is the default.

**Comment by michaelkleinhenz** [comment]
In the current way the boead is working, an "All" selection is not possible as the states may be different for different WITs. That is the reason for the dropdown in general. But we're re-visiting the way the board is working anyway, so the dropdown will go away, showing multiple WITs will be possible by default.

**Comment by michaelkleinhenz** [comment]
This will be addressed with #330.
