### ISSUE TITLE
Board View: Switching "Currently showing" sets menu to "Backlog"

### ISSUE THREAD

**Issue by pilhuhn** [openshiftio/openshift.io#552]
Go to Plan -> Board
See "Board" in blue
Switch "Currently showing" from Bug to Task
See "Backlog" in blue even if still in the board:

![bildschirmfoto 2017-08-11 um 11 46 56](https://user-images.githubusercontent.com/208246/29208561-d366e7a0-7e8a-11e7-841e-d2dc4892151b.png)

**Comment by joshuawilson** [comment]
cc @michaelkleinhenz

**Comment by joshuawilson** [comment]
@nimishamukherjee has this been fixed?

**Comment by qodfathr** [comment]
Given the huge change to the Planner UI, I'm closing this as it's referring to controls which do not even exist anymore. If you find similar problems with the new Planner once it drops the Experimental flag, please open new issues. Thx!
