### ISSUE TITLE
Sidebar: Work Item Count is broken

### ISSUE THREAD

**Issue by pilhuhn** [openshiftio/openshift.io#553]
The All counter in Plan / Backlog and Plan / Board always shows 0 no matter how many entries are in Backlog / Board

**Comment by joshuawilson** [comment]
cc @michaelkleinhenz

**Comment by michaelkleinhenz** [comment]
The counter is broken as we now have to deal with different WITs that are being displayed.

**Comment by nimishamukherjee** [comment]
The count does not display 0 now.
We do have another issue related to work item counts - https://openshift.io/openshiftio/openshiftio/plan/detail/1533
