### ISSUE TITLE
Pipelines display on space main page wrongly shows "no pipelines have run"

### ISSUE THREAD

**Issue by pilhuhn** [openshiftio/openshift.io#554]
Clicking on the pipelines link in the top left of this box leads to the pipeline page, which shows that pipelines have indeed run in the past.

![bildschirmfoto 2017-08-11 um 12 36 58](https://user-images.githubusercontent.com/208246/29210072-054b1078-7e92-11e7-9eec-858a674bd05f.png)

**Comment by joshuawilson** [comment]
This works for me. Have you cleaned and started fresh, as @burrsutter has outlined?

**Comment by pilhuhn** [comment]
Yes, also works for me now after a force-reload. Closing this one.
