### ISSUE TITLE
Applications Tab no longer responding

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#558]
Two users (myself and another) noticed the Applications Tab would not respond today - I ran through 2 different accounts, fully cleaned in-between. 

https://screencast.com/t/7crcXh0qk

This tab is an important part of the story arc for our developer-focused console

Che version 1.0.275
Jenkins version 3.0.81

**Comment by aslakknutsen** [comment]
@burrsutter Not seen this after the DNS proxy fix correct?

**Comment by bmicklea** [comment]
Things have been working properly for the last couple of weeks. Closing.
