### ISSUE TITLE
Intermittent issue - Jenkins and Che version/status icons are missing

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#559]
Just noticed this:

![screenshot from 2017-08-11 21-07-18](https://user-images.githubusercontent.com/642621/29236516-530612c6-7ed9-11e7-821f-20edd4f0e307.png)

What happened to the Jenkins and Che staus icons?

**Comment by ldimaggi** [comment]
Not reproducible - closing.

**Comment by aslakknutsen** [comment]
@joshuawilson Note: the underlying issue to them 'missing' is still there even if the 'common' problem is fixed with the proxy. The Status API is still not able to report if the status is horrible bad (e.g. oso is down).

**Comment by joshuawilson** [comment]
@aslakknutsen agreed, we need to fix the status widget.
