### ISSUE TITLE
"Create" blocks all actions in UI if Che is idling

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#560]
Steps to reproduce:

* Idle CheHost
* Go to https://openshift.io/openshiftio/openshiftio/create
  * See network tab n blocking calls to 'Edit' in state pending (eventually 504)

Until 504, the rest of the UI is unresponsive, e.g. Plan/Analyze

**Comment by dgutride** [comment]
@aslakknutsen  - I think this was meant for @dlabrecq

**Comment by aslakknutsen** [comment]
@dgutride yes :)

**Comment by dlabrecq** [comment]
Can you please elaborate a little more? For example, does this happen upon entering the page or when you open/create a workspace?

If you open/create a workspace, we keep trying until Che starts up -- it can take 2-3 min if Chie is idle. Are you attempting to navigate elsewhere after selecting that?

**Comment by aslakknutsen** [comment]
If you just go to the page, when che is idling, nothing will work in the ui until the edit reponse timeout(504)

**Comment by joshuawilson** [comment]
@dlabrecq if you are working this, go ahead and assign it to yourself.

**Comment by dlabrecq** [comment]
Yes, but this is really a dup of https://github.com/fabric8-ui/fabric8-ui/issues/1825

**Comment by aslakknutsen** [comment]
@dlabrecq Not so much a dup as "if fabric8-ui/fabric8-ui#1825 is implemented properly it would fix this"

**Comment by dlabrecq** [comment]
Yes, integrating the CheStarter API with the codebases page would resolve the issue with the worksapce menu as well.

**Comment by joshuawilson** [comment]
fixed
