### ISSUE TITLE
[RFE] Provide users with a "user environment/account" health report feature

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#561]
I think we should provide users with an easy way to diagnose potential problem situations by generating a report of the current condition of their account - OSO resources consumed, quotas, installed service versions, etc. 

Users could then be able to include this in formation when they file problem reports,. Thx!

**Comment by joshuawilson** [comment]
@catrobson this might fit with the work you are doing on the clean up page.

**Comment by catrobson** [comment]
@joshuawilson thanks.  @ldimaggi we'll want your feedback on the system utilization and status pages that we're working through now.  We can then also talk about how to include this information into what we attach to feedback that users provide in-app in the user feedback capability we'll be looking to add soon.

**Comment by ldimaggi** [comment]
Thx! Send a link to the system utilization and status pages when they ready for review.

**Comment by qodfathr** [comment]
@ldimaggi can you please review https://redhat.invisionapp.com/share/YSDL0KRKW and close this issue if you are satisfied?

**Comment by ldimaggi** [comment]
Closing - the new 'deployments' page will satisfy this feature request - thx!
