### ISSUE TITLE
OSO: Broken link to jenkins on the Pipelines detail page

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#565]
This is an issue related to OSO. Kindly forward.

Logging it here as the users are most likely to see this in the workshop workflow.

The link to Jenkins displayed is broken and leads the user to a page that does not exists.

Broken link: http://jenkins/job/rgargosiotest1/job/vertx-paint/job/master/
Working link: https://jenkins-rgarg-osiotest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/job/rgargosiotest1/job/vertx-eventbus/job/master/

Where: rgarg-osiotest1 is the user id

**Comment by joshuawilson** [comment]
@kbsingh @jstrachan who can we pass this to?

**Comment by jstrachan** [comment]
fixed in prod
