### ISSUE TITLE
Importing multiple projects place multiple builds for each project in queue

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#566]
1) For the workshop doc and import all 3 vertx projects into OSIO
2) Post successful import, open the OSO pipelines page and observe that multiple builds are in queue for each project. Sometime 3, or may be 5 if your are indeed in luck

This is happening with Jenkins build 3.0.81 and 3.0.82 as well.

**Comment by rgarg1** [comment]
![3 builds triggered](https://user-images.githubusercontent.com/28748448/29270804-11fd08ae-8116-11e7-98ec-1ece826399ca.png)

**Comment by rgarg1** [comment]
Video proof: https://drive.google.com/open?id=0BwLIZeed5jyKcVNsOGR2MTRZWTg

**Comment by ldimaggi** [comment]
A simple way to recreate this bug is:
* Create a new project (add to space - Quickstart)
* Then, import that same project's git hub repo as a new project

**Comment by jstrachan** [comment]
wanna try retest this? think its fixed - there should be now only 1 webhook after an import

**Comment by rgarg1** [comment]
You fixed it! Works fine with 3.0.88. Success logs attached.

**Comment by rgarg1** [comment]
[jenkins-1-nr98q.txt](https://github.com/openshiftio/openshift.io/files/1228511/jenkins-1-nr98q.txt)

**Comment by jstrachan** [comment]
awesome thanks!!!!
