### ISSUE TITLE
Stack report on dashboard - does not allow user to select pipeline

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#568]
The pipeline dropdown is not being populated with pipeline names - the dropdown is always empty:

![screenshot 61](https://user-images.githubusercontent.com/642621/29274190-efe16198-80d4-11e7-88ed-03f6833e063c.png)

Related to:
https://github.com/openshiftio/openshift.io/issues/563

**Comment by rawlingsj** [comment]
Maybe this pipeline isn't annotating the builds for some reason.  Can you attach the jenkins log for that build please?

**Comment by jstrachan** [comment]
its it still empty if you reload? wondering if its just not watching for new pipelines being created; or if it never populates

**Comment by GeorgeActon** [comment]
@samuzzal-choudhury is this related to the work Arun is doing?

**Comment by samuzzal-choudhury** [comment]
@GeorgeActon not really. 
@ldimaggi,  The pipeline dropdown will not populate if Bayesian call fails during a build. It will be helpful to check the build log for that pipeline run to validate the status of the Bayesian call. As you know, many OSIO users had run into the error 503 time and again (https://github.com/openshiftio/openshift.io/issues/545) which prevented a successful recommender API call from happening.

**Comment by jyasveer** [comment]
@GeorgeActon @samuzzal-choudhury i checked this on my side. everything works fine now. If the pipelines are not annotated with with bayesian. Currently if we don't any annotated pipelines for bayesian we show a message that there are no results.
@ldimaggi Can you please confirm and close this ?

**Comment by ldimaggi** [comment]
Closing - fix verified.
