### ISSUE TITLE
[RFE] Provide link to Che dashboard in OSIO UI

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#569]
It would be helpful for users to be able to easily locate/access their Che dashboard directly from the OSIO UI. This would help in the near-term, as we are facing issues managing Che workspaces. This would also help users in the future as they manage and use multiple Che workspaces. Thx!

**Comment by joshuawilson** [comment]
There is a plan in place to create a workspaces page like the codebases page to manage Che.
It is being tracked at https://github.com/fabric8-ui/fabric8-ui/issues/1528
Closing as a duplicate.
