### ISSUE TITLE
Intermittent issue - Create new workspace fails to import external libraries

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#570]
Steps to recreate:
* From a clean user account:
* Create new space
* Add to space - Vert.X quickstart
* Create Che workspace

See the error highlighted - the problem is that the external libraries are not imported:

![screenshot 63](https://user-images.githubusercontent.com/642621/29276385-773cdd78-80dc-11e7-8457-c315719897ac.png)

**Comment by ldimaggi** [comment]
And - here is a successful run:

![screenshot from 2017-08-14 10-21-52](https://user-images.githubusercontent.com/642621/29276530-e306ec7e-80dc-11e7-923e-7e3199d8ea11.png)

**Comment by ldimaggi** [comment]
Che pod log from failed attempt:

[che_pod_log.txt](https://github.com/openshiftio/openshift.io/files/1222526/che_pod_log.txt)

**Comment by ldimaggi** [comment]
Another che log file:

[che_pod_log.txt](https://github.com/openshiftio/openshift.io/files/1222558/che_pod_log.txt)

**Comment by ldimaggi** [comment]
Seeing lots of these errors - haven't seen these before

WARNING: A connection to https://kubernetes.default.svc/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

**Comment by l0rd** [comment]
"Red cross" problems should have been solved. @ldimaggi can you confirm?

**Comment by ldimaggi** [comment]
This problem has not been seen recently - closing.
