### ISSUE TITLE
Che deployments are not being removed by cleaning script

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#571]
Just noticed that these deployments were not removed by the cleaning script:

![screenshot 65](https://user-images.githubusercontent.com/642621/29276731-88cc1c56-80dd-11e7-8e9c-69063a799450.png)

**Comment by joshuawilson** [comment]
So after you delete everything in the Che namespace, they are still there?
These are the workspaces, right?

**Comment by joshuawilson** [comment]
@jstrachan @kbsingh @aslakknutsen if he ran a complete delete, why are these still here?

**Comment by ldimaggi** [comment]
+1

But - the workspaces don't seem to exist.

**Comment by aslakknutsen** [comment]
@ldimaggi Are you sure you ran the clean up on that namespace? Have any logs? Did you refresh the UI?

**Comment by ldimaggi** [comment]
Yes - the cleanup was run - and the UI was refreshed. Will try to recreate and get any logs.

**Comment by ldimaggi** [comment]
Closing as no longer reproducible.
