### ISSUE TITLE
When a new Che workspace is not fully/correctly created, error details are not reported to user

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#572]
See: https://github.com/openshiftio/openshift.io/issues/570

When the error occurs, a red "x" character is shown in the project navigator, but the user is not informed as to the cause of the error.

**Comment by joshuawilson** [comment]
Not a solution but for anyone else reading this; if you refresh the error goes away.
I know that the Che team is aware of this, but I don't know what issue they are tracking it on.

**Comment by l0rd** [comment]
"Red cross" problems should have been solved. @ldimaggi can you confirm?

**Comment by ibuziuk** [comment]
@ldimaggi red "x" issue is supposed to be fixed. Could you please verify & close ?

**Comment by ldimaggi** [comment]
Have not seen this recently - closing.
