### ISSUE TITLE
Logging into Openshift.io first time does not work on Firefox

### ISSUE THREAD

**Issue by jjohnstn** [openshiftio/openshift.io#574]
Using Firefox 45.4 on RHEL 7.3, logging into openshift.io routes me to the _gettingstarted page.  This page does not show anything on Firefox.  It works with Chrome, but it should also work with Firefox.

**Comment by joshuawilson** [comment]
@mindreeper2420 can you please verify the supported version of FF. I think that might be too old.

**Comment by mindreeper2420** [comment]
@joshuawilson you are correct. OpenShift.io has not been tested on Firefox below version 51 (released January 24, 2017). The latest supported release for OpenShift.io is 54.0.1 (June 13, 2017).

Chrome is the recommended browser, per our Browser Guidelines (https://github.com/openshiftio/openshift.io/wiki/Supported-Browsers).

**Comment by joshuawilson** [comment]
@catrobson any idea what we can do for the standard configuration on RHEL? Is it fare to tell all our internal RHEL users to install Chrome?

**Comment by ppitonak** [comment]
There is Firefox ESR 52.3 available on RHEL 7.2 so I guess that similar version is available on RHEL 7.3 and 7.4. In my opinion, OSIO should support and be tested on latest Firefox ESR.

**Comment by qodfathr** [comment]
@ldimaggi @joshuawilson can anyone confirm that the latest available Firefox for RHEL (I assume installed from SCL) does, in fact, work with OSIO?

**Comment by ldimaggi** [comment]
It looks OK with Firefox 52.3.0

**Comment by joshuawilson** [comment]
this is fixed, closing
