### ISSUE TITLE
links to pipelines broken when username has special characters in it

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#575]
I have user `manderse@redhat.com` meaning my base url is `https://openshift.io/manderse%40redhat.com` but links in the Pipelines widget uses `https://openshift.io/manderse/mirror3/create/pipelines` as opposed to the correct url at `https://openshift.io/manderse%40redhat.com/mirror3/create/pipelines`

**Comment by maxandersen** [comment]
No I don't think this is the same issue nor related to osio username != github usernames.

Issue is that my user has a @ in the name (i.e. `manderse@redhat.com`) which should be encoded as `%40` but for some reason the links to pipelines cuts off at this symbol instead.

**Comment by alexeykazakov** [comment]
I'm removeing team/auth and area/auth. This issue with pipeline UI. Not Auth.

**Comment by qodfathr** [comment]
@maxandersen is this bug still valid?

**Comment by maxandersen** [comment]
yes, still not fixed.

**Comment by andrewazores** [comment]
@qodfathr I think this has been resolved with the PRs for #1048 and #2334 - when working in those areas I didn't see any issue relating to special characters in particular, simply mishandling of usernames vs namespaces.

**Comment by qodfathr** [comment]
@maxandersen care to verify if fixed?

**Comment by maxandersen** [comment]
missed this update - but yes its actually fixed now!
