### ISSUE TITLE
Build is running - No stages have started

### ISSUE THREAD

**Issue by jpopelka** [openshiftio/openshift.io#576]
Created 'New Quickstart project' with 'Vert.x - Basic' and 'Release' pipeline strategy.
Build has not started, log says 'Application is not available'.

https://console.starter-us-east-2.openshift.com/console/project/jpopelka/browse/pipelines/osio-test-15-8-1

Firefox: 55.0

**Comment by joshuawilson** [comment]
I don't think the upgrade of OSO has been fully fixed. Can you go in an update your tenant and try again.

**Comment by jpopelka** [comment]
Tried again, but still no luck:

- updated tenant, waited 
- checked Jenkins version, it's 3.0.88
- removed all spaces
- deleted all pipelines
- Scaled the "jenkins" service to 0 pods and then to 1
- created new space
- checked Jenkins logs: http://pastebin.test.redhat.com/508766

Should I try to [clean-up all apps and pipelines](https://github.com/openshiftio/openshift.io/wiki/FAQ#how-do-i-clean-up-all-apps-and-pipelines-in-my-openshift-online) and update the tenant again ?

**Comment by joshuawilson** [comment]
yes, please run a complete clean up

**Comment by jpopelka** [comment]
[How do I clean-up all apps and pipelines in my OpenShift Online](https://github.com/openshiftio/openshift.io/wiki/FAQ#how-do-i-clean-up-all-apps-and-pipelines-in-my-openshift-online) followed by [How do I update my tenant ?](https://github.com/openshiftio/openshift.io/wiki/FAQ#how-do-i-update-my-tenant-) helped, closing. Thanks.
