### ISSUE TITLE
importing project using same repo as already used resulting in duplicate codebases

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#577]
I had an old space using a git repo but all builds etc. was gone. I used import existing repo and end result was things seemed to work again but I now have two codebases for the same repo.

I would have expected it to use the existing codebase/repo, not add another one.

<img width="1277" alt="menubar_and_banners_and_alerts_and_create_-_openshift_io" src="https://user-images.githubusercontent.com/54129/29310862-c526e92e-81af-11e7-88b4-592adee3f393.png">

**Comment by qodfathr** [comment]
Fixed.

**Comment by maxandersen** [comment]
fixed without code changes ?
