### ISSUE TITLE
unidling Che takes longer than the route timeout will tolerate

### ISSUE THREAD

**Issue by kbsingh** [openshiftio/openshift.io#579]
We have effective idle for che turned on, this is a huge resource win for us - however there seems to be a problem wherein the first time its unidled due to activity, the time it takes for the servie to restore is longer than the tolerance on the router for an idled app. 

Needs investigation as to where the correct fix might be, and if we can perhaps optimise the unidle process.

**Comment by kbsingh** [comment]
Manually testing this, against the wall clock it looks like we need ~ 3 min from first hit request to when the che-dashboard will load up.

**Comment by joshuawilson** [comment]
@ibuziuk @aslakknutsen @dlabrecq is this something we can deal with in the CheStarter?

**Comment by ibuziuk** [comment]
from @aslakknutsen comment on mattermost: 

> I think the CheStarter CheHost 503 I saw today is related to this new issue: https://bugzilla.redhat.com/show_bug.cgi?id=1481603
> the workaround for now would be to expand the Che Starter startup check to include the endpoint resource, and not just assume becasue the pod is health it can be called

**Comment by ibuziuk** [comment]
from @kbsingh comment:
`the endpoints problem[1] should get fixed today as well,  it looks specific to our cluster`

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1481603

**Comment by ibuziuk** [comment]
Fixes for endpoint delay is now available on prod. However, the whole unidling UX will be changed as part of https://github.com/fabric8-ui/fabric8-ui/issues/1825

**Comment by ibuziuk** [comment]
fabric8-ui/fabric8-ui#1825 is done and available on prod. Closing
