### ISSUE TITLE
Stacks recommendation build # shows a hash

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#583]
The Stacks recommendation shows dialog title shows Report title on Application, Build #3403b809c7e045ff820da4756a56c180.

It should be Report title on application-name, Build 3 

![screenshot 2017-08-15 14 46 38](https://user-images.githubusercontent.com/30131/29330916-c15ca1ee-81c8-11e7-963a-92d4c9206eb6.png)

**Comment by jyasveer** [comment]
This is fixed now. I am closing this.
