### ISSUE TITLE
Stacks recommendation problems after a second run of the pipeline.

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#584]
In the first execution of the pipeline, everything was fine.

In the second execution, the report is missing/blank with a message: "There was a problem and we couldn't build a full stack overview analysis."

![screenshot 2017-08-15 14 50 18](https://user-images.githubusercontent.com/30131/29331015-19be7858-81c9-11e7-984a-c9ab500e44e3.png)

**Comment by arunkumars08** [comment]
@rafabene I have tried this in local as well as in my openshift account, I am unable to reproduce this issue. Could you give me more information so that I can try even better?

**Comment by arunkumars08** [comment]
@rafabene I am able to reproduce the scenario now. The fix for the same is in the pipe.

**Comment by jyasveer** [comment]
@rafabene Can you please confirm and close this issue ? Thanks

**Comment by rafabene** [comment]
I confirm that it's working. Thanks
