### ISSUE TITLE
Short pipeline does not show link to staging

### ISSUE THREAD

**Issue by pilhuhn** [openshiftio/openshift.io#585]
I am using the middle of the 3 pipeline options to only roll out to staging (to save time).

Unlike the long one, there is no link to the app on staging, so I need to leave OSIO and go over to OSO and into the -stage project to find my app.

OSIO version : Jenkins version 3.0.87

![bildschirmfoto 2017-08-15 um 21 00 46](https://user-images.githubusercontent.com/208246/29331516-fb9cddea-81fc-11e7-8889-31c529ff9bb4.png)

**Comment by pilhuhn** [comment]
Update: it may be that this is hidden in the context menu under "stage:demo" - I certainly did not expect this.

**Comment by adisakala** [comment]
The issue seem to be more related to issue with our Pipeline UI. @rajdavies suggest get this addressed by somebody in CD team

**Comment by qodfathr** [comment]
Close as dupe #456.
