### ISSUE TITLE
Clicking on project name in pipelines widget shows warning that this is not found

### ISSUE THREAD

**Issue by pilhuhn** [openshiftio/openshift.io#586]
I clicked on the myspace-demo link in the Recent-active-pipelines view and got an orange warning box

![bildschirmfoto 2017-08-15 um 21 19 31](https://user-images.githubusercontent.com/208246/29332208-8ebdfd96-81ff-11e7-887c-0da310e81364.png)

Same happens from within the space.

**Comment by qodfathr** [comment]
Fixed.
