### ISSUE TITLE
"Can not contact Jenkins-slave-xxx" in Jenkins output

### ISSUE THREAD

**Issue by pilhuhn** [openshiftio/openshift.io#588]
My build log has twice:

`Cannot contact jenkins-slave-mvd45-51hk7: java.io.IOException: corrupted content in /home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-feae4093/pid: java.lang.NumberFormatException: For input string: ""`

<details>
[Pipeline] stage (Build Release)
Using the ‘stage’ step without a block argument is deprecated
Entering stage Build Release
Proceeding
[Pipeline] sh
[pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ] Running shell script
Executing shell script inside container [maven] of pod [jenkins-slave-mvd45-51hk7]
Executing command: sh -c echo $$ > '/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-0a495830/pid'; jsc=durable-3ab6e41b0bbe856563dcca8b2d891bc7; JENKINS_SERVER_COOKIE=$jsc '/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-0a495830/script.sh' > '/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-0a495830/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-0a495830/jenkins-result.txt' 
[?1034hsh-4.2$ cd "/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYY 
BWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ"
sh-4.2$ sh -c echo $$ > '/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEI 
CNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-0a495830/pid'; jsc 
=durable-3ab6e41b0bbe856563dcca8b2d891bc7; JENKINS_SERVER_COOKIE=$jsc '/home/jen 
kins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7 
KG2NUN4UKVNAQWQ@tmp/durable-0a495830/script.sh' > '/home/jenkins/workspace/pilhu 
hn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/ 
durable-0a495830/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/workspace/pilhu 
hn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/ 
durable-0a495830/jenkins-result.txt' 
sh-4.2$ exit
exit
+ git checkout -b pilhuhn/myspace-demo/master-1.0.11
Switched to a new branch 'pilhuhn/myspace-demo/master-1.0.11'
[Pipeline] sh
[pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ] Running shell script
Executing shell script inside container [maven] of pod [jenkins-slave-mvd45-51hk7]
Executing command: sh -c echo $$ > '/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-feae4093/pid'; jsc=durable-3ab6e41b0bbe856563dcca8b2d891bc7; JENKINS_SERVER_COOKIE=$jsc '/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-feae4093/script.sh' > '/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-feae4093/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-feae4093/jenkins-result.txt' 
[?1034hsh-4.2$ cd "/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYY 
BWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ"
sh-4.2$ sh -c echo $$ > '/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEI 
CNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-feae4093/pid'; jsc 
=durable-3ab6e41b0bbe856563dcca8b2d891bc7; JENKINS_SERVER_COOKIE=$jsc '/home/jen 
kins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7 
KG2NUN4UKVNAQWQ@tmp/durable-feae4093/script.sh' > '/home/jenkins/workspace/pilhu 
hn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/ 
durable-feae4093/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/workspace/pilhu 
hn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/ 
durable-feae4093/jenkins-result.txt' 
+ mvn org.codehaus.mojo:versions-maven-plugin:2.2:set -U -DnewVersion=1.0.11
Cannot contact jenkins-slave-mvd45-51hk7: java.io.IOException: corrupted content in /home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-feae4093/pid: java.lang.NumberFormatException: For input string: ""
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot - Health Check 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.2:set (default-cli) @ demo ---
[INFO] Searching for local aggregator root...
[INFO] Local aggregation root: /home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ
[INFO] Processing change of com.example:demo:1.0.0-SNAPSHOT -> 1.0.11
sh-4.2$ exit
exit
[INFO] Processing com.example:demo
[INFO]     Updating project com.example:demo
[INFO]         from version 1.0.0-SNAPSHOT to 1.0.11
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.786 s
[INFO] Finished at: 2017-08-16T09:43:30+00:00
[INFO] Final Memory: 12M/491M
[INFO] ------------------------------------------------------------------------
[Pipeline] sh
[pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ] Running shell script
Executing shell script inside container [maven] of pod [jenkins-slave-mvd45-51hk7]
Executing command: sh -c echo $$ > '/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-9cf9f9f4/pid'; jsc=durable-3ab6e41b0bbe856563dcca8b2d891bc7; JENKINS_SERVER_COOKIE=$jsc '/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-9cf9f9f4/script.sh' > '/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-9cf9f9f4/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-9cf9f9f4/jenkins-result.txt' 
[?1034hsh-4.2$ cd "/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYY 
BWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ"
sh-4.2$ sh -c echo $$ > '/home/jenkins/workspace/pilhuhn_myspace-demo_master-EEI 
CNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-9cf9f9f4/pid'; jsc 
=durable-3ab6e41b0bbe856563dcca8b2d891bc7; JENKINS_SERVER_COOKIE=$jsc '/home/jen 
kins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7 
KG2NUN4UKVNAQWQ@tmp/durable-9cf9f9f4/script.sh' > '/home/jenkins/workspace/pilhu 
hn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/ 
durable-9cf9f9f4/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/workspace/pilhu 
hn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/ 
durable-9cf9f9f4/jenkins-result.txt' 
+ mvn clean -e -U deploy -Dmaven.test.skip=false -P openshift
Cannot contact jenkins-slave-mvd45-51hk7: java.io.IOException: corrupted content in /home/jenkins/workspace/pilhuhn_myspace-demo_master-EEICNF735FRJKBYYBWFBQPA2UIYCRGQMZLOI7KG2NUN4UKVNAQWQ@tmp/durable-9cf9f9f4/pid: java.lang.NumberFormatException: For input string: ""
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                        

</details>

**Comment by rawlingsj** [comment]
This is due to a jenkins plugin upgrade but doesn't cause any issues AFAIK.  Should be fixed in a future plugin upgrade.  There's more info here https://issues.jenkins-ci.org/browse/JENKINS-42048

**Comment by qodfathr** [comment]
Fixed.
