### ISSUE TITLE
Collapsible sidebar in Planner 

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#589]
# Description
As a user, I want to be able to collapse the shortcut sidebar when not needed.

# Acceptance Criteria
- [ ]  The user can collapse the sidebar when in expanded (shown). The rest of the UI adapts to the collapsed sidebar.
- [ ]  The user can expand the sidebar when in collapsed state. The rest of the UI adapts to the collapsed sidebar.
 
# Relationships
_Put linked Team/Product story links here_

**TODO**: the collapsing might work the same way the collapsing of the right hand preview panel is working. But then, we again have the animation problem. We might want to look at these both for a general solution.

**Comment by sdash-redhat** [comment]
Please find the first draft for GH#589  Collapsible sidebar in Planner
https://redhat.invisionapp.com/share/R9D8MJ0QB

**Comment by sdash-redhat** [comment]
As per feedback from the Dev, there is a limitation to implement the nav icon in the header as there is dependency from planner, on request for alternate design to implement the icon within the planner controlled area, here is the updated design - https://redhat.invisionapp.com/share/TRDA41HGN

**Comment by SMahil** [comment]
Fixed: https://github.com/fabric8-ui/fabric8-planner/pull/2152
