### ISSUE TITLE
import project creates a new webhook; leading to duplicate webhooks on repeated imports

### ISSUE THREAD

**Issue by jstrachan** [openshiftio/openshift.io#590]
which then leads to duplicate builds triggered via duplicate github push events

**Comment by rgarg1** [comment]
Will this fix #566 ?

**Comment by jstrachan** [comment]
@rgarg1 I really hope so yes! Should be live in a production in an hour or so - will close this issue when its there then we can retest if #566 is fixed

**Comment by rgarg1** [comment]
Thank you @jstrachan for tracking this problem down and fixing it. Appreciate it.

**Comment by jstrachan** [comment]
fixed in prod
