### ISSUE TITLE
The import dialog for more than one project is not aligned

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#591]
I've imported three projects. In the last page of the dialog, the third repository is not aligned.

![screenshot 2017-08-16 11 56 12](https://user-images.githubusercontent.com/30131/29372755-063c1f4a-827a-11e7-9c3f-c0e355fe0580.png)

**Comment by corinnekrych** [comment]
fixed https://github.com/openshiftio/openshift.io/issues/966
