### ISSUE TITLE
Importing three projects makes Jenkins Pipeline to create two builds for one of them.

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#592]
I have imported three projects at the same time forked from 

- https://github.com/burrsutter/vertx-eventbus 
- https://github.com/burrsutter/vertx-paint  
- https://github.com/burrsutter/vertx-wiki2 

The project vertx-wiki2 has two builds

![screenshot 2017-08-16 13 00 59](https://user-images.githubusercontent.com/30131/29375431-f6dbe40a-8282-11e7-9ead-7dc749f3478f.png)

**Comment by jstrachan** [comment]
could you double check the webhooks at https://github.com/burrsutter/vertx-wiki2/settings/hooks and check that there is only 1 webhook. If there are more than one what are the URLs it triggers? 

We fixed an issue yesterday so that importing / creating a project removes all the old webbooks for the URL before it creates a new one so there should not be any duplicates.

If thats not the issue - attaching the log of your jenkins master would be handy

**Comment by rafabene** [comment]
I checked the following repos: 
- https://github.com/rafabene/vertx-paint/settings/hooks
but it created two builds. 

![screenshot 2017-08-18 11 32 17](https://user-images.githubusercontent.com/30131/29465924-ef162eb0-8408-11e7-8d3e-83f91326d17e.png)

The repo https://github.com/rafabene/vertx-paint/settings/hooks has also a single webhook but also created two builds

![screenshot 2017-08-18 11 33 41](https://user-images.githubusercontent.com/30131/29465962-1a911168-8409-11e7-9c41-0d0d74301f37.png)

**Comment by rhopp** [comment]
I just encountered this one importing https://github.com/rhopp/vertx-wiki2 (one webhook), but two builds spun up.
I've imported this project multiple times in past few days, but this is first time this happened.

**Comment by bartoszmajsak** [comment]
I have faced the same issue. Created quickstart and ended up with two builds

![image](https://user-images.githubusercontent.com/719616/32268982-5dae21d4-bef1-11e7-91fb-f720b6cd980f.png)

Repo: https://github.com/bartoszmajsak/bartosz-sdp-test-01

Single hook pointing to: https://jenkins-bartosz-1-jenkins.8a09.starter-us-east-2.openshiftapps.com/github-webhook/

**Comment by qodfathr** [comment]
I believe this to be fixed, @rafabene , but please reopen if you can still reproduce.
