### ISSUE TITLE
Second Che workspace is not starting

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#594]
When I try to start a second instance of Che 286, I get the following message and then it asks to restart.

![screenshot 2017-08-16 13 30 42](https://user-images.githubusercontent.com/30131/29376641-3a5d15e2-8287-11e7-82f1-65bf7630e2bf.png)

After clicking on the restart button I get the following message:

![screenshot 2017-08-16 13 32 24](https://user-images.githubusercontent.com/30131/29376682-61fa70f4-8287-11e7-8f78-efa4055644b0.png)

**Comment by l0rd** [comment]
Hello @rafabene can you provide the steps to reproduce this? It will help us investigating.

**Comment by ibuziuk** [comment]
@rafabene can still reproduce this problem ?

**Comment by rafabene** [comment]
Now the message is a little bit different: "Could not start workspace myspringboot-gjzcu. Reason: Start of environment 'default' failed. Error: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot."

**Comment by ibuziuk** [comment]
@rafabene could you please tests it again after cluster update ? there were quite a few infra issues fixed

**Comment by l0rd** [comment]
Cannot reproduce it anymore after this week OSO upgrade. @rafabene please reopen if you are able to reproduce.
