### ISSUE TITLE
Intermittent and recurring issue - Jenkins and Che fail to start within 10 minutes after a tenant update

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#595]
Update - August 18

Steps to recreate:
* Clean a user account
* Update the tenant
* Observe the Che and Jenkins pods in the OSO web console
* I am seeing pods fails to deploy about 30% of the time - logs are not generated

-------------------------------------------------------------------
Original problem description:

Seeing this about 20-25% of the time today:

Steps to recreate:
* Create a new space
* Create a new project - quickstart - Vert.x
* Observe that a pipeline is not created:

![screenshot from 2017-08-16 15-43-36](https://user-images.githubusercontent.com/642621/29382372-5f23a432-829a-11e7-803a-4f897a4216a2.png)

Jenkins log shows this error:

```
Aug 16, 2017 7:44:36 PM io.jenkins.blueocean.autofavorite.FavoritingScmListener onCheckout
SEVERE: Unexpected error when retrieving changeset
hudson.plugins.git.GitException: Error launching git whatchanged
```

Jenkins pod log is attached. 

[Jenkins_pod_log.txt](https://github.com/openshiftio/openshift.io/files/1229343/Jenkins_pod_log.txt)

**Comment by jstrachan** [comment]
did the forge wizard complete successfully?  does `oc get project -n ${ID}` find it?

**Comment by ldimaggi** [comment]
Yes - the OSO projects are created:
```
oc get project -n ldimaggi-osiotest1
NAME                         DISPLAY NAME   STATUS
ldimaggi-osiotest1                          Active
ldimaggi-osiotest1-che                      Active
ldimaggi-osiotest1-jenkins                  Active
ldimaggi-osiotest1-run                      Active
ldimaggi-osiotest1-stage                    Active
```

**Comment by ldimaggi** [comment]
Finally found a pattern to explain this.

I am seeing this problem both running manually and automated tests. The automated tests update the tenant, and then wait for the Jenkins and Che status icons to go green, before the test is run.

What seems to be happening is that the Jenkins pods are stopping and restarting randomly.  I noticed this by cleaning the user account, updating the tenant, and then watching:

![screenshot from 2017-08-17 12-14-31](https://user-images.githubusercontent.com/642621/29422612-c55b5298-8346-11e7-878c-bb12341c5b2f.png)
![screenshot from 2017-08-17 12-13-19](https://user-images.githubusercontent.com/642621/29422609-c555c7b0-8346-11e7-8d69-10465fe15b8e.png)
![screenshot from 2017-08-17 12-09-04](https://user-images.githubusercontent.com/642621/29422608-c555055a-8346-11e7-957e-4bcaeda039f7.png)
![screenshot from 2017-08-17 12-07-18](https://user-images.githubusercontent.com/642621/29422610-c5564618-8346-11e7-85e7-23a656b94d76.png)
![screenshot from 2017-08-17 12-06-47](https://user-images.githubusercontent.com/642621/29422611-c5586fba-8346-11e7-920c-5500acbc88e3.png)

**Comment by ldimaggi** [comment]
![screenshot from 2017-08-17 12-56-17](https://user-images.githubusercontent.com/642621/29423896-87bb0672-834b-11e7-8edd-031c54374a3c.png)

![screenshot from 2017-08-17 12-56-04](https://user-images.githubusercontent.com/642621/29423897-87bf03c6-834b-11e7-86bb-345d7c19b185.png)

![screenshot from 2017-08-17 12-55-48](https://user-images.githubusercontent.com/642621/29423898-87c10c3e-834b-11e7-8b41-d7320d00ef89.png)

**Comment by ldimaggi** [comment]
Seeing this > 75% of the time on August 17.

**Comment by ldimaggi** [comment]
To recreate problem:
* Clean the user's OSO account
* Update tenant
* Watch/observe the Jenkins* pods

**Comment by joshuawilson** [comment]
@ldimaggi can you confirm this is blocking the EE tests from passing?

**Comment by ldimaggi** [comment]
Yes - this causes the tests to frequently fail.

**Comment by aslakknutsen** [comment]
@ldimaggi Do you have the Jenkins logs or Events log when this happen?

**Comment by ldimaggi** [comment]
It seems to happen randomly. The logs are lost as the failed pods are deleted/recreated.

**Comment by ldimaggi** [comment]
Will try to grab part of a log - or screenshot it.

**Comment by ldimaggi** [comment]
Related to:
https://github.com/openshiftio/openshift.io/issues/547
https://github.com/openshiftio/openshift.io/issues/517

**Comment by maxandersen** [comment]
I was mentioned yesterday on platform call that status of jenkins/che was hard to get reliably - is this the issue here ?   and is this happening because it is an automatic test where things goes normally faster than if a human goes through the steps ?

**Comment by ldimaggi** [comment]
The issue that I am seeing is that Jenkins/Che seem to fail to start reliably - are you seeing the pods started in the OSO web console, but that status is not being reflected in the OSIO UI?

**Comment by ldimaggi** [comment]
The problem that I am seeing - sometimes - is not a matter of a status not being reported correctly - the problem that I am seeing is that after an account is cleaned - the Jenkins and/or Che pod simply fails to start.

**Comment by l0rd** [comment]
@ldimaggi I'm adding the label `area/che` to keep it under our radar even if I've never noticed that for Che (but I haven't done as much tenant deployment as you do for sure). 

By the way Che and Jenkins have distinct OpenShift deployments. Can you confirm that failures happen for Che too?

**Comment by ldimaggi** [comment]
Yes - I am seeing problems with both Che and Jenkins. In the past couple of days, Che seems to have more problems than Jenkins in starting reliably after a cleanup/update.

**Comment by fche** [comment]
Have the OSD/OSO ops people tried to reconfigure elasticsearch or whatnot in order to avoid immediately losing logs of dead pods?

**Comment by ldimaggi** [comment]
From Mattermost thread:

CHANNEL: openshiftio-saas
aslak - 21:12 UTC, August 25

@ldimaggi The errors I see, that might be what you refer to is EBS Mount/sync issues that last for about 20min but it eventually come up

**Comment by ldimaggi** [comment]
This problem also seems to be happening more and more frequently in the past few days.

**Comment by ldimaggi** [comment]
![screenshot from 2017-08-25 23-19-51](https://user-images.githubusercontent.com/642621/29738237-03250d52-89ec-11e7-96a3-25f8738db1f5.png)

**Comment by ldimaggi** [comment]
It looks like Jenkins is failing to update the status icon - Che seems to be OK.

**Comment by ldimaggi** [comment]
Closing as a duplicate of:  https://github.com/openshiftio/openshift.io/issues/666
