### ISSUE TITLE
Awakened Workspaces loses ssh keys for git push

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#596]
Start a Workspace
Wait an hour+ for it to idle
Refresh its browser tab once, maybe three times
I wakes and connects
Change code then git commit and attempt git push (via the dialog box)

and you are likely to see this error

<img width="419" alt="screenshot 2017-08-16 23 12 31" src="https://user-images.githubusercontent.com/378310/29394514-b732941a-82d8-11e7-9b80-22306a750388.png">

**Comment by burrsutter** [comment]
Workaround is to click Create Workspace again, but then your project may fail to import.  The workaround for that is to manually import the project from github.

**Comment by burrsutter** [comment]
Che : 1.0.288

**Comment by l0rd** [comment]
That should be fixed when multi-tenant Che is implemented eclipse/che#5943 but for now the workaround is to fix https://github.com/redhat-developer/rh-che/issues/297

**Comment by l0rd** [comment]
Now that https://github.com/redhat-developer/rh-che/issues/297 has been fixed the error should not be reproducable. @burrsutter can you confirm?

**Comment by ibuziuk** [comment]
@ldimaggi @rhopp could you please verify on the latest che version ?

**Comment by rhopp** [comment]
@ibuziuk I was able to push to github repository from workspace after the host was idled and awakened.

**Comment by ibuziuk** [comment]
@rhopp thanks for verifying! Closing
