### ISSUE TITLE
Creating a new workspace - when successful - browser window with workspace is not opened

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#599]
After creating a new workspace, Chrome is no longer opening the new workspace window. See screencast:

https://drive.google.com/a/redhat.com/file/d/0B1s-ZoxD8FjUTEpqdmFWT0lUQWs/view?usp=sharing

**Comment by rhopp** [comment]
It seems that you have blocked popups. See Burr's workshop document, section "Create Tab - Codebases - to Create a Che Workspace"
<img width="367" alt="image47" src="https://user-images.githubusercontent.com/1215011/29406964-01a23590-8343-11e7-9907-e368a8a398ff.png">
<img width="232" alt="image49" src="https://user-images.githubusercontent.com/1215011/29406981-0e65b4a0-8343-11e7-8c2e-43db95ae3b0b.png">

**Comment by ldimaggi** [comment]
Closing - user error.   ;-)
