### ISSUE TITLE
Stack reports modal does not display the build number.

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#600]
<img width="1440" alt="screen shot 2017-08-17 at 10 24 56 am" src="https://user-images.githubusercontent.com/5430080/29397521-6b60771e-833c-11e7-9657-558f1dbabbbe.png">

**Comment by arunkumars08** [comment]
@jyasveer It is a known issue. The reason is because the PR in runtime console is still to be merged. https://github.com/fabric8-ui/fabric8-runtime-console/pull/548 Once that is merged, you will not see this.

**Comment by jyasveer** [comment]
This is fixed now. Thanks @arunkumars08
