### ISSUE TITLE
Not receiving email notifications from planner

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#602]
Following the workshop, I created a work item and assigned it to myself. I'm supposed to receive an email notification.

After 1 hour, I still not have received the email notification.

**Comment by aslakknutsen** [comment]
@slemeur I can see there are currently 7 email notifications attempted sent to you. Most are currently in state "deferred". 

Most of them seem to be in a graylist process: 
    451 4.7.1 Greylisting in action, please come back in 00:03:14"

First message sent at GMT: Thursday, August 17, 2017 9:23:44 AM
with sent status at GMT: Thursday, August 17, 2017 12:07:26 PM

Last message attempted sent at GMT: Thursday, August 17, 2017 9:47:49 AM
with last deferred attempt at GMT: Thursday, August 17, 2017 11:05:36 AM

**Comment by aslakknutsen** [comment]
Note: When this task (https://github.com/fabric8-services/fabric8-notification/issues/21) gets resolved sometime during the day you won't be able to receive notifications on your own actions. Under the assumption that you are awake when you do them ;)

**Comment by slemeur** [comment]
I now have received all the notifications. I'll close that issue, but why there is so much delay?

**Comment by aslakknutsen** [comment]
I think there is a general delay primarily because we haven't proven to the world we're not spammers yet.. :)

**Comment by slemeur** [comment]
ok :) ! Thanks
