### ISSUE TITLE
Che's editor is almost unusable - missing edits, automatically moving cursor to top

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#603]
The Che's editor is behaving in a way which is making it challenging to use.

I'm experiencing issues while reproducing the workshop doc instructions:
**1- After few edits, the editor's cursor is moving to the top of the file**
![editor-move-to-top](https://user-images.githubusercontent.com/1636769/29413546-066b7766-835d-11e7-88ee-aa3ae796d528.gif)

**2- Some edits are lost**
![editor-remove-changes](https://user-images.githubusercontent.com/1636769/29413438-ab81181a-835c-11e7-9b17-36c57c8f75ea.gif)
(you can see at the end of the animated gif, that I input a `d` and it was removed nearly instantly)

**3- Nearly each input fires the display of the modal loader at the middle of the screen**
![lot-of-events-while-editing](https://user-images.githubusercontent.com/1636769/29413306-3db12f78-835c-11e7-9757-f0f29f5f0ac3.gif)

**Comment by slemeur** [comment]
linking to upstream issues: 
https://github.com/eclipse/che/issues/6028
https://github.com/eclipse/che/issues/6027

**Comment by slemeur** [comment]
The two upstream issues have been fixed, but there is still some edits that are lost.
To reproduce, try to input when the autosave event is fired (=when the blue star is just removed from the file's tab).

**Comment by l0rd** [comment]
@slemeur do you still have the issue? Is it something that you are experiencing only when using Che on OSIO or it happens on upstream too?

**Comment by slemeur** [comment]
I cannot reproduce the issue anymore. Closing it.
