### ISSUE TITLE
Intermittent issue - "Build #0" is seen - but the first build is build #1

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#604]
See attached screenshots - the steps to cause this issue to occur (seen 2 times on August 16):
* Clean user OSO account
* Create new space, new quickstart project
* Observe Build #0 on space dashboard page:

![screenshot from 2017-08-16 23-15-54](https://user-images.githubusercontent.com/642621/29415983-bad80f82-8332-11e7-89cf-632464dfa390.png)

* Navigate to pipeline page - observe that it is now named Build #1:

![screenshot from 2017-08-16 23-16-09](https://user-images.githubusercontent.com/642621/29416015-d5cb0376-8332-11e7-9ab1-58740bf77e83.png)

**Comment by joshuawilson** [comment]
When I run it, I see build#0 for a second on the dashboard. Once the build pipeline starts it updates to Build#1.

**Comment by qodfathr** [comment]
@ldimaggi I have not seen this in a long time. Closable?

**Comment by joshuawilson** [comment]
Looks fixed, closing.
