### ISSUE TITLE
OCP 3.5 - Jenkins Persistent -  "Jenkin's doesn't have label maven..."

### ISSUE THREAD

**Issue by jcperezamin** [openshiftio/openshift.io#606]
Running a Jenkinsfile with a Jenkins Persistent using Openshift + Maven + Latest RedHat/Centos release image is stuck on "Jenkin's doesn't have label maven...". but running on Jenkins Ephemeral is working out.

Are there some limitations in using Jenkins Persistent inside Openshift with Maven?

**Comment by joshuawilson** [comment]
Is this for the application that get generated or for OSIO and it run? Can you please provide some context?

**Comment by jcperezamin** [comment]
You can reproduce the error using this example of jenkinsfile https://github.com/OpenShiftDemos/openshift-cd-demo/tree/ocp-3.5

Only change is it would be running in a persistent jenkins not epheremal

**Comment by joshuawilson** [comment]
@jstrachan @rawlingsj @kbsingh this sounds like one for you.

**Comment by rawlingsj** [comment]
@jcperezamin are you running this on OpenShift.io or OpenShift.com?   OpenShift.io comes with a persistent Jenkins OOTB and is running in `$YOUR_USERNAME_jenkins` namespace.  This also means the quota's you have available to you can be used to run your applications rather than build infra.

**Comment by jcperezamin** [comment]
I am using Openshift 3.5 company cluster setup in AWS.

**Comment by rawlingsj** [comment]
OK so this issue tracker is for the hosted service OpenShift.io so you'll want to raise this (with a bit more info like error messages / logs etc) on either that repo that you linked to https://github.com/openshiftio/openshift.io/issues/606#issuecomment-323263552 or seek support through your Red Hat subscription alternatively if this is Origin then you could try an issue on their issue tracker https://github.com/openshift/origin/issues
