### ISSUE TITLE
Recommendation messages are getting truncated even though there is enough space

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#608]
<img width="1423" alt="screen shot 2017-08-18 at 10 30 04 am" src="https://user-images.githubusercontent.com/7880465/29444837-723e83e0-8400-11e7-897a-2906d56a7320.png">

**Comment by tisnik** [comment]
I can see the same problem in FF:
Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

Current resolution is 1640 x 1000, ie. there's enough space in FF

**Comment by jyasveer** [comment]
this issue is fixed here https://github.com/fabric8-ui/fabric8-recommender/pull/269
