### ISSUE TITLE
[8](5) Performance tests for end to end consumption of user facing API

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#609]
So far, there been performance tests done at individual components. End to end performance testing of the user API would need be instrumental in scaling the resources (which resources , how much to scale upto) as needed and calculate associated cost involved at infra. level

Acceptance Criteria:

- [x] SLA, throughput for Component analysis API / requests (for known component)
- [x] SLA, throughput for Component analysis API / requests (for unknown component)
- [x] SLA, throughput for Stack analysis API / requests (with stacks containing known components)
- [ ] SLA, throughput for Stack analysis API / requests (with few of the stacks containing unknown components)
- [ ] Calculate the log size across ONLINE part of OSIO analytics (MB) for the  throughput on user facing traffic
- [ ] Calculate the log size across OFFLINE part of OSIO analytics (MB) for the  incremental data refresh

# Actual results:

## SLA criteria and results:

Shared with the team

## Component analysis

Duration of concurrent (parallel) component analysis:
https://github.com/fabric8-analytics/fabric8-analytics.github.io/blob/master/perf-tests/jobs_api/flow_analysis/concurrent/jobs_flow_scheduling_1-18_threads.png

Duration of component analytics steps (for selected components):
https://github.com/fabric8-analytics/fabric8-analytics.github.io/blob/master/perf-tests/jobs_api/flow_analysis/pypi_clojure_py.png

## Stack analysis

Results for production:
https://github.com/fabric8-analytics/fabric8-analytics.github.io/tree/master/perf-tests/core_api/stack_analysis/production

Average times:
https://github.com/fabric8-analytics/fabric8-analytics.github.io/blob/master/perf-tests/core_api/stack_analysis/production/average_times.png

Min+avg+max times:
https://github.com/fabric8-analytics/fabric8-analytics.github.io/blob/master/perf-tests/core_api/stack_analysis/production/min_avg_max_times.png

## Component analysis
Results for production:
https://fabric8-analytics.github.io/perf-tests/core_api/component_analysis/component_analysis.png

Min+avg+max times:
https://fabric8-analytics.github.io/perf-tests/core_api/component_analysis/component_analysis_min_max_avg_times.png

Parallel component analysis for known component:
https://fabric8-analytics.github.io/perf-tests/core_api/component_analysis/component_analysis_parallel_calls_known_component.png

Parallel component analysis for unknown component:
https://fabric8-analytics.github.io/perf-tests/core_api/component_analysis/component_analysis_parallel_calls_unknown_component.png

### Stack API

**Comment by samuzzal-choudhury** [comment]
On request, added Pavel T as the assignee.

**Comment by krishnapaparaju** [comment]
@tisnik @samuzzal-choudhury we need to maintain a simple matrix with number of replicas required to support certain 'n' number of stack analysis and component analysis requests and response times  would be perceived by the end user

@GeorgeActon @miteshvp @msrb

**Comment by samuzzal-choudhury** [comment]
@krishnapaparaju Here are the SLA benchmarks for stack analysis:

https://docs.google.com/spreadsheets/d/13CRoYJPxGrDkhgnTKeyjP80SVdY0Sdfg6bbGlIT6azY/edit?ts=59e5024c#gid=0

**Comment by miteshvp** [comment]
Closing this issue as performance numbers are shared as mentioned in the document in previous comment.
