### ISSUE TITLE
Improve, Validate recommendations for OSIO Quickstart applications 

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#610]
Verify recommendations for these quickstart applications, part of OSIO work flow and the workshops being conducted.

https://docs.google.com/spreadsheets/d/1_-BZu_0hMyIhfG5ElTM0VmZZuOjgKrZ1SJr6PS9il1s/

**Comment by krishnapaparaju** [comment]
Changed the label for the milestone

**Comment by qodfathr** [comment]
@krishnapaparaju this looks like it was in support of workshops. Please close if nothing more to be done. Thx.
