### ISSUE TITLE
Migrate all the deployment units onto public CI/CD

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#612]
Currently all the OSIO analytics related deployments done thru CentralCI, would need to migrated to CentOS pipelines.

**fabric8-analytics-pgbouncer**
- [x] CI scripts checked in into the fabric8-analytics-pgbouncer repository
- [x] jobs for fabric8-analytics-pgbouncer created in CentOS CI
- [x] webhooks set for fabric8-analytics-pgbouncer

**fabric8-analytics-jobs**
- [x] CI scripts checked in into the fabric8-analytics-jobs repository
- [x] jobs for fabric8-analytics-jobs created in CentOS CI
- [x] webhooks set for fabric8-analytics-jobs

**fabric8-analytics-stack-analysis**
- [x] CI scripts checked in into the fabric8-analytics-stack-analysis repository
- [x] jobs for fabric8-analytics-stack-analysis created in CentOS CI
- [x] webhooks set for fabric8-analytics-stack-analysis

**fabric8-analytics-license-analysis**
- [x] CI scripts checked in into the fabric8-analytics-license-analysis repository
- [x] jobs for fabric8-analytics-license-analysis created in CentOS CI
- [x] webhooks set for fabric8-analytics-license-analysis

**gremlin-docker**
- [x] CI scripts checked in into the gremlin-docker repository
- [x] jobs for gremlin-docker created in CentOS CI
- [x] webhooks set for gremlin-docker

**anitya-docker**
- [x] CI scripts checked in into the anitya-docker repository
- [x] jobs for anitya-docker created in CentOS CI
- [x] webhooks set for anitya-docker

**fabric8-analytics-cvedb-s3-dump-docker**
- [x] CI scripts checked in into the fabric8-analytics-cvedb-s3-dump-docker repository
- [x] jobs for fabric8-analytics-cvedb-s3-dump-docker created in CentOS CI
- [x] webhooks set for fabric8-analytics-cvedb-s3-dump-docker

**fabric8-analytics-worker-base**
- [x] CI scripts checked in into the fabric8-analytics-worker-base repository
- [x] jobs for fabric8-analytics-worker-base created in CentOS CI
- [x] webhooks set for fabric8-analytics-worker-base

**fabric8-analytics-worker**
- [x] CI scripts checked in into the fabric8-analytics-worker repository
- [x] jobs for fabric8-analytics-worker created in CentOS CI
- [x] webhooks set for fabric8-analytics-worker

**fabric8-analytics-server**
- [x] CI scripts checked in into the fabric8-analytics-server repository
- [x] jobs for fabric8-analytics-server created in CentOS CI
- [x] webhooks set for fabric8-analytics-server

**fabric8-analytics-data-model**
- [x] CI scripts checked in into the fabric8-analytics-data-model repository
- [x] jobs for fabric8-analytics-data-model created in CentOS CI
- [x] webhooks set for fabric8-analytics-data-model

https://docs.google.com/spreadsheets/d/1cWHmGVnQ4T8bVKwCiQqBb8BAyJ1v1z9z3SKQxYSC17c

**Comment by msrb** [comment]
Following PRs need to be merged to complete this task:
- https://github.com/fabric8-analytics/fabric8-analytics-server/pull/133 (API server, cc @samuzzal-choudhury)
- https://github.com/fabric8-analytics/fabric8-analytics-data-model/pull/43 (data-importer, cc @miteshvp)
- https://github.com/almighty/almighty-jobs/pull/271 (job definition for data-importer, cc @vpavlin)

**Comment by msrb** [comment]
Everything we deploy to staging/prod now goes through CentOS CI.

@krishnapaparaju I believe this issue can be closed now.

**Comment by msrb** [comment]
We are CentOS CI citizens already. Closing.
