### ISSUE TITLE
Application components tagging: Migrate from manual tagging to tagging based on algorithm

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#613]
Currently packages are manually tagged to attach meaning / category for an application component to indicate the purpose of an application component which is foundation to determine intents across a group of application components. 

This milestone covers:
  (a) Tags generated by algorithm fed intent based alogithms 
  (b) process / algorithm needs to be in place to verify the accuracy of each tag being generated

**Comment by miteshvp** [comment]
@SaketJNU

**Comment by miteshvp** [comment]
Moved from models based on tags to different DL models. Hence not relevant. Closing this.
