### ISSUE TITLE
Intermittent issue - Che workspace window fails to open

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#618]
Will added logs if this can be recreated - seeing this issue multiple times today. 

After creating a new project, attempting to create a codebase fails - no error is returned to the user.

**Comment by l0rd** [comment]
When you say "Fails to open" do you mean that the new tab opens but the IDE doesn't shows up? Or clicking the "Create workspace" button doesn't do anything at all?

That may be related to https://github.com/fabric8-ui/fabric8-ui/issues/1825 or #579 

@eivantsov do you have any idea?

**Comment by eivantsov** [comment]
@l0rd i have got the same question to @ldimaggi - how exactly it does not work. Screenshots and server logs will help of course.

**Comment by ldimaggi** [comment]
Cannot recreate - probably was a problem with Che not running. Closing this issue - thx!
