### ISSUE TITLE
Che: Spring Boot Commands

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#621]
Spring Boot Commands, "build" should be
scl enable rh-maven33 'mvn install -f ${current.project.path}'
and there should be a "clean build" which is
scl enable rh-maven33 'mvn clean install -f ${current.project.path}'

The former is specifically to allow for Spring DevTools hot redeploy.  The end-user still needs to Save (unless auto-save is enabled) and then run this Build command in order for his currently running app to be updated.

**Comment by benoitf** [comment]
It's fixed

**Comment by joshuawilson** [comment]
@burrsutter can we close this?

**Comment by l0rd** [comment]
Closing it. @burrsutter feel free to reopen if you still have problems with spring boot commands.
