### ISSUE TITLE
Add to Space visible/clickable when not logged in

### ISSUE THREAD

**Issue by vpavlin** [openshiftio/openshift.io#626]
When not logged in into OSIO, you can veiw your space (expected), but the button *Add to Space* is still there and clickable, but it throws errors when you try to use it. Would be better if users could not see it at all if they are not authorized to add to space.

![screenshot from 2017-08-21 10-09-22](https://user-images.githubusercontent.com/4759808/29509533-e5e3ee02-8658-11e7-942d-d15de1187e76.png)
![screenshot from 2017-08-21 10-09-15](https://user-images.githubusercontent.com/4759808/29509541-e8cee630-8658-11e7-9942-73920d18d3e9.png)

**Comment by joshuawilson** [comment]
related to #1399

**Comment by qodfathr** [comment]
This particular issue is fixed, but there are several others in the same vein (per #1399).
