### ISSUE TITLE
Cleanup failed with "Response with status: 0 for URL: null"

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#627]
Today, I tried the new "Clean tenant" button, but it failed with ""Response with status: 0 for URL: null"":
![image](https://user-images.githubusercontent.com/1215011/29510140-09aef74e-865b-11e7-8bb3-97812f8c40ae.png)

I looked into openshift console and it seemed clean (nothing in rhopp-che, nothing in rhopp-jenkins).

**Comment by rhopp** [comment]
Doing "Clean tenant" again, no error showed up.

**Comment by aslakknutsen** [comment]
Can't find any errors in the backend. Clean and all related calls seems to return 200 OK.

**Comment by joshuawilson** [comment]
@rhopp can you look at your console logs when you try it again. Post any errors you find there.

**Comment by joshuawilson** [comment]
Closing as this appears fixed. If you see this again, please reopen.

**Comment by mishaone** [comment]
I've just encountered this. Context: Upgraded to Che 6, trying to reuse a name I've used before for projects and it offers old workspaces. I tried to reset my environment to try again (prod) and this appeared:

![tenant_error](https://user-images.githubusercontent.com/926572/38345662-a9d0130e-38d3-11e8-8724-6e4b057f1568.png)

**Comment by mishaone** [comment]
Console information, if it helps:
![console_log](https://user-images.githubusercontent.com/926572/38345711-eb665b0c-38d3-11e8-8f3d-4deccdb7ebbc.png)

**Comment by mishaone** [comment]
Went to dashboard, tried again. Same error (and console log message).

**Comment by joshuawilson** [comment]
Is this still an issue?

**Comment by mishaone** [comment]
I haven't seen it for a while so if nobody else has, we can close it, I think.
