### ISSUE TITLE
[3]Support multiple manifest files across all the integration points

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#628]
Currently Analytics platform support projects with multiple manifest files (eg: multiple POM files for Maven ecosystem).

Support for multiple manifest files is now available for OSIO workflow and needs to be extend this to other integration points like IDEs:  (a) DevStudio/Eclipse (b)  VSCode Extension.

@GeorgeActon  please take a look at this...

##### Sub Tasks
- [x] Add multiple manifest file support in VScode
- [x] Add multiple manifest file support in devstudio

**Comment by samuzzal-choudhury** [comment]
Both the sub-tasks are complete and hence closing this use case. CC: @krishnapaparaju @GeorgeActon @GeetikaBatra @invincibleJai @jyasveer
