### ISSUE TITLE
Infinite scrolling appears to be present, but is not working for viewing spaces

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#629]
See attached screenshot - when the user has a large number of spaces, performing 'view all spaces' does not return all spaces - and the user cannot scroll to view all spaces:

![screenshot from 2017-08-21 09-17-31](https://user-images.githubusercontent.com/642621/29522738-3efe50c8-8658-11e7-9424-cec929cf97ed.png)

**Comment by qodfathr** [comment]
Fixed, plus we've got a new Spaces UI coming.
