### ISSUE TITLE
User cleanup has a limit on the number of spaces it can delete at one time

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#630]
It looks like the new "clean tenant" has a limit of being able to delete 50-60 spaces at a time. Can the clean tenant feature be changed to delete ALL of tenant's spaces? Thx!

**Comment by joshuawilson** [comment]
@aslakknutsen is there a limitation on the api?
cc @dgutride

**Comment by aslakknutsen** [comment]
@dgutride You loop over the spaces for a user and delete 1 by 1, don't you? Are you taking pagination into account?

**Comment by joshuawilson** [comment]
We do not have a `clean tenant`. `Reset Environment` will delete everything. I just added 70 new spaces and they were all removed with reset env. 

Closing as this appears fixed.
