### ISSUE TITLE
Improve GNOSIS Reference Architecture

### ISSUE THREAD

**Issue by tuhinsharma** [openshiftio/openshift.io#634]
- [ ] Include multiple layers in Gnosis reference architecture

- [ ] Use a less minimum support count which give us significantly large number of itemsets.
The intention is to capture 3-itemsets and greater than 3-itemsets. We call 2-itemsets and greater than 2-itemsets as intents.

- [ ] Constraint the number of parents for each nodes above the “topic/keywords” nodes.

**Comment by joshuawilson** [comment]
@sara-02 Usually a User Story is the context for an Enhancement. This should not have both labels. Please pick one.

**Comment by qodfathr** [comment]
I see no associated tasks against this user story, an no parent epic. Is this work that we still intend to do at some point, or can we close this?

**Comment by joshuawilson** [comment]
cc @sivaavkd @krishnapaparaju

**Comment by sivaavkd** [comment]
Closing this for now.  if we need to use PGM for something other than vert.x and springboot, we will create a new item for this.
