### ISSUE TITLE
Improve the Generation of Kronos Dependency Graph 

### ISSUE THREAD

**Issue by tuhinsharma** [openshiftio/openshift.io#635]
Modify the logic for computing alternate packages. (Frido shared an idea https://docs.google.com/document/d/1vtJlUSovs63N2w314XNbefW8XOA3UNOb4ZRU3hfwzfk/edit?usp=sharing )

**Comment by joshuawilson** [comment]
@sara-02 the labels user-story and enhancement should not be used at the same time.

**Comment by tuxdna** [comment]
@tuhinsharma Can you point to the code-base where current approach is implemented?

**Comment by joshuawilson** [comment]
The description does appear to be more of an Enhancement.
cc @krishnapaparaju

**Comment by qodfathr** [comment]
I see no associated tasks against this user story, an no parent epic. Is this work that we still intend to do at some point, or can we close this?

**Comment by miteshvp** [comment]
Closing this issue as it is no longer valid
