### ISSUE TITLE
Run tagger to collect tags for OSIO example stacks

### ISSUE THREAD

**Issue by SaketJNU** [openshiftio/openshift.io#636]
OSIO start-up example has five stacks with 13 packages belonging to springboot and vert.x and README file is available on S3 (assumed). Run tagger to collect tags for these 13 packages. It requires:
- [x]  Check whether S3 bucket has required README files.
- [x] run tagger to collect tags.
- [x] update the S3 buckets with collected tags.

**Comment by fridex** [comment]
> Check whether S3 bucket has required README files.

This is not required to do explicitly. The resulting S3 bucket with results (prod-keywords-summary) states origin of keywords/tags so there is no need to check README files (the same applies for other tag sources).

**Comment by fridex** [comment]
@SaketJNU could this be marked as completed?

**Comment by joshuawilson** [comment]
Can we close this?
