### ISSUE TITLE
Improve Co-occurrence Matrix Generation

### ISSUE THREAD

**Issue by tuhinsharma** [openshiftio/openshift.io#637]
Sparkify the code for speed up. Use Spark Dataframe to boost the computation.
Current implementation : We are using pandas dataframe and updating row by row which is inefficient.

**Comment by qodfathr** [comment]
I see no associated tasks against this user story, an no parent epic. Is this work that we still intend to do at some point, or can we close this?

**Comment by miteshvp** [comment]
Closing this issue as we have achieved improvements already.
