### ISSUE TITLE
Improve PGM (the Probabilistic Graph Model)

### ISSUE THREAD

**Issue by tuhinsharma** [openshiftio/openshift.io#638]
- [ ] Include the concept of anchor packages. 	
- [ ] Train the model for significantly large number of github manifest files.

**Comment by krishnapaparaju** [comment]
@miteshvp @sara-02 any work being done around this issue ?

**Comment by sara-02** [comment]
@krishnapaparaju None as of now.

**Comment by qodfathr** [comment]
Is this still valid for the backlog? Do we intend to do this work?

**Comment by qodfathr** [comment]
If #638 is closed due to no intention to work on it, then this should also be closed.

**Comment by miteshvp** [comment]
Closing this issue as we are using a different approach to improve on PGM recommendations.
