### ISSUE TITLE
Create a Framework for Automated Evaluation of Recommendations

### ISSUE THREAD

**Issue by tuhinsharma** [openshiftio/openshift.io#639]
Evaluate recommendations for Companion packages, Outlier packages, Alternate packages for 100 manifest files (for each ecosystems) automatically whenever a new Implementation or PR is merged.

Tasks:
-  [X]  Rest Endpoint to call the accuracy evaluation class (calls PGM scoring internally)
-  [X]  Record the precision

**Comment by sara-02** [comment]
Linked to #749

**Comment by sara-02** [comment]
Covered by https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/134
