### ISSUE TITLE
License Analysis: Implement outliers based on licenses

### ISSUE THREAD

**Issue by harjinder-hari** [openshiftio/openshift.io#640]
Identify the license based outlier i.e. the set of components whose licenses were responsible for making the overall stack license very restrictive even when these components are less in number as compared to other less restrictive components.

For example, consider the stack of components { C1, C2, C3 } with licenses { L1, L2, L3 } respectively. Now, let us say L1 and L2 are less-restrictive licenses e.g BSD and Apache and L3 is very restrictive e.g. GPLv2+ then the stack license will be AGPLv3. So, only because of L3, we got such a restrictive stack license and that's how we can flag L3 as outlier license and C3 as outlier component.

**Comment by harjinder-hari** [comment]
- [ ] Add support for license synonyms i.e. the set of terms that mean same license.
- [ ] Provide details about unknown licenses, conflict licenses in the output of license analysis.
- [ ] Implement outliers based on licenses.

**Comment by miteshvp** [comment]
@harjinder-hari - can we mark this as completed/closed?

**Comment by harjinder-hari** [comment]
@miteshvp not yet. I will finish the integration tests today. Then this issue can be closed. Will keep you updated.

**Comment by joshuawilson** [comment]
You don't have to close it but you can't stay here. Please close or move to backlog or next sprint.

**Comment by miteshvp** [comment]
I will open a new issue for license analysis integration tests. Closing this one now.
