### ISSUE TITLE
mail notification should have area as part of mail text and as a mail header

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#644]
I currently get ~50-80 mails from notifiy.openshift.io and it is tedius to process as the area is not rendered anywhere nor is it part of headers to actually be filtered/grouped by good email clients.

Suggestion:

Have a label in the body of the mail with the area listed and link to it:

**Area**: [Planner](https://openshift.io/openshiftio/openshiftio/plan?area=Planner)

AND

Have a mail header like "X-Planner-Area: Planner" which would allow filtering and grouping without having to parse the html/text mail.

**Comment by aslakknutsen** [comment]
@mindreeper2420 Something for you ! :)

**Comment by mindreeper2420** [comment]
@maxandersen isn't something like this already present in the body?
<img width="538" alt="screen shot 2017-09-06 at 8 29 43 pm" src="https://user-images.githubusercontent.com/4032718/30140394-28dadb76-9342-11e7-8c2d-1e5ad39a6e24.png">

The "openshiftio/openshiftio" currently links to the Space Owner and Space Name, so would you just want the `/plan?area=Planner` added to the end?

**Comment by joshuawilson** [comment]
I think `area=Planner` would work. It should be in the title as that is what gets visually scanned. That would allow you to read the ones for your area first.
