### ISSUE TITLE
The preview "stage application" in pipeline disappeared.

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#647]
There was a link as you can see in the "Rollout to stage" pipeline as you can see in the following picture

![screenshot 2017-08-23 10 30 58](https://user-images.githubusercontent.com/30131/29621257-352940d4-87ee-11e7-94cd-1a3db9043fe5.png)

But it doesn't show any more.

![screenshot 2017-08-23 10 27 39](https://user-images.githubusercontent.com/30131/29621294-52f261a4-87ee-11e7-827a-80b52430a82d.png)

**Comment by rawlingsj** [comment]
Are there any errors in the browser javascript console?  Also is the app still running in the stage environment?

**Comment by rafabene** [comment]
Closing as I was never saw it happening again.

**Comment by DonSchenck** [comment]
![metoo](https://user-images.githubusercontent.com/5067110/29674979-c03017a6-88c1-11e7-861f-57541aed5a02.JPG)
Happened to me as well.

**Comment by qodfathr** [comment]
Close as dupe #456.
