### ISSUE TITLE
Make filtering of boosters that work/don't work on openshift.io more managable

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#650]
currently we are doing hacks to filter the list of boosters available on openshift.io

Lets work with launch team to get it handled better.

- [ ] [Add filters into catalog/repos](https://github.com/openshiftio/launchpad-addon/issues/48)

**Comment by qodfathr** [comment]
Is this still an issue?

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2054
