### ISSUE TITLE
stale / dead WkSp's still hold quota for tenant's che allocation

### ISSUE THREAD

**Issue by kbsingh** [openshiftio/openshift.io#652]
With stale wksp, when a user aims to create a new workspace they are unable to do so since the stale deployments are still holding onto the resources allocated from the quota. Is it possible to auto-clear out these stale pieces when bringing up a new workspace ? 

cc @vpavlin

**Comment by vpavlin** [comment]
I clicked "Create Workspace", got che opened, but workspace creation failed. I checked OSO and saw 2 workspace DCs, with no pods running

```
$ oc get pods
NAME          READY     STATUS    RESTARTS   AGE
che-1-tvsnr   1/1       Running   0          26m
```
I looked into workspace deployment which was trying to start and saw

```
Error creating: pods "che-ws-22e0i90do8xrvxbm-4274950485-" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=4492m,limits.memory=2300Mi, used: limits.cpu=5859m,limits.memory=3000Mi, limited: limits.cpu=6,limits.memory=3Gi
```
But quotas tab seemed ok:

![screenshot from 2017-08-24 15-01-56](https://user-images.githubusercontent.com/4759808/29668181-8abf18ba-88df-11e7-92ee-90dbb8bda2a4.png)

Deleting existing workspace DCs and clicking create again worked in the end.

**Comment by l0rd** [comment]
Related to OpenShift upstream issue https://bugzilla.redhat.com/show_bug.cgi?id=1482337

**Comment by ibuziuk** [comment]
> Cluster Info:
> OC Version: v3.6.173.0.37
> Docker Version: 1.12.6-55.gitc4618fb.el7
> Kube Version: v1.6.1+5115d708d7
> Metrics Version: v3.6.173.0.37
> Logging Version: v3.6.173.0.37

Tested. Should be fixed now on prod cluster after the latest update. @rhopp Could you please verify & close ?

**Comment by ibuziuk** [comment]
Upstream issue is closed. Closing
