### ISSUE TITLE
Unable to setup Authorization after initial setup

### ISSUE THREAD

**Issue by kameshsampath** [openshiftio/openshift.io#654]
Following the steps below

1. Login to openshift.io, 
2. Setup github authorization
3. (optional) create space and import project 
4. Get back to Github and revoke permissions to openshift.io
5. Comeback to the OpenShift.io screen,
6. Do try import again, the application is not asking for re-authorization.

There no  currently to setup re-authorization again

**Comment by alexeykazakov** [comment]
Here are two issues which cover this:
https://github.com/fabric8-services/fabric8-auth/issues/73
https://github.com/fabric8-services/fabric8-auth/issues/38

**Comment by alexeykazakov** [comment]
It's now possible to re-connect GitHub account in the user profile page. Autodetection of invalid tokens is covered in https://github.com/openshiftio/openshift.io/issues/869 and https://github.com/fabric8-services/fabric8-auth/issues/38
Closing.
