### ISSUE TITLE
'Update Profile' page is not scrollable - 'Reset Environment' button is invisible

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#656]
Using Chrome in Incognito mode during internal workshop: the `Update Profile` page did not allow for vertical scrolling, which means that I could not see the `Rest Environment` button until I expanded the browser window on a larger screen.

**Comment by joshuawilson** [comment]
@mindreeper2420 can you add this to your list

**Comment by mindreeper2420** [comment]
I'm unable to reproduce the non-scrolling effect. On a 788x465 screen, I can scroll, as seen below:
![screen shot 2017-08-24 at 6 05 17 pm](https://user-images.githubusercontent.com/4032718/29690901-e943d198-88f6-11e7-986d-0519e4918945.png)

@xcoulon what version of Chrome are you using and on what OS? My screenshot was taken with Version 60.0.3112.101 (Official Build) (64-bit) running macOS 10.12.6.

**Comment by xcoulon** [comment]
@mindreeper2420 I was running Version 60.0.3112.101 (Official Build) (64-bit) on macOS 10.11.6 but I can't reproduce it today, neither on normal mode, nor on 'incognito' mode. Sorry about that.
I'll close the issue for now and will reopen if I can reproduce it again.
