### ISSUE TITLE
Remove background gradient in space dashboard

### ISSUE THREAD

**Issue by kwk** [openshiftio/openshift.io#658]
I'm not a UI expert but I feel that color or saturation gradients most of the time disrupt your focus and draw the attention away. For example, on the space dashboard, there seems to be a very huge gradient in the background, going from a darker shade in the top left to lighter shade in the bottom right corner:

![screenshot from 2017-08-24 18-22-32](https://user-images.githubusercontent.com/193408/29676832-7c993b16-88f9-11e7-9a94-c9cb1a1f4d06.png)

I myself always follow this gradient with my eye to see where it is leading to and I do this without knowing.

That's why I suggest to remove the gradient background in the space dashboard.

**Comment by joshuawilson** [comment]
cc @catrobson

**Comment by joshuawilson** [comment]
@kwk I just checked and it is a solid #D1D1D1 grey from corner to corner. Maybe it is your monitor.

**Comment by catrobson** [comment]
@kwk yup, there is no gradient on this page.  We're also looking at the shade of gray we use for backgrounds on our pages overall which might help the perception problem that could have occurred here if it isn't your monitor ;).  https://github.com/fabric8-ui/fabric8-ux/issues/625

Closing this issue.
