### ISSUE TITLE
provide a canonical URL to a users profile pages

### ISSUE THREAD

**Issue by jstrachan** [openshiftio/openshift.io#662]
it'd be nice to be able to link to users profile pages. e.g. from the wiki in docs on how to `Update Tenant` it'd be nice to link to the update profile page.

e.g.  we could use a canonical link like this: http://openshift.io/_profile/_update which would redirect to https://openshift.io/james_strachan/_update (for me)

we've also got a user case in CD; when we generate PRs against team/che/jenkins, it'd be nice to comment on the PR a URL that advanced users can use to try out the PR inside their openshift.io tenant account. e.g. a URL something like this....

* http://openshift.io/_profile/_tenant?jenkinsVersion=4.0.0-TJ-PR-TEST1&mavenRepo=http://nexus.cd.k8s.fabric8.io/content/repositories/staging

Then the new pages http://openshift.io/_profile/* would redirect to the http://openshift.io/userEntityId/* page.

**Comment by jstrachan** [comment]
cc @joshuawilson @dgutride

**Comment by joshuawilson** [comment]
Good idea, @dgutride can you take care of this?

**Comment by dgutride** [comment]
PR up here: https://github.com/fabric8-ui/fabric8-ui/pull/1933 - adds new /_profile route
