### ISSUE TITLE
Automated acceptance tests on app wizard (focused wizard flows)

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#663]
# Description
As a developer, I want to to make sure bug fixes done on app wizard won't break neither the import flow not the quickstart flow. 

# Acceptance Criteria
- [ ] Each PR on f8-ui wizard should trigger the tests. 
- [ ] Each PR on f8-generator should trigger the tests. 
- [ ] Based on [e2e test on import](https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/src/tests/work-item/work-item-list/EE/openshift-io-burr-import-che.spec.js), create a new space, launch import wizard, select organisation, select one project, verify success.
- [ ] Based on [e2e test on import](https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/src/tests/work-item/work-item-list/EE/openshift-io-burr-import-che.spec.js), create a new space, launch import wizard, select organisation, select 2 projects verify success and 2 code bases are created.
- [ ] Based on [e2e test on quickstart](https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/src/tests/work-item/work-item-list/EE/openshift-io-burr-quickstart.spec.js), create a new space, launch quickstart wizard, keep default space name for repo name, verify success.
- [ ] Based on [e2e test on quickstart](https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/src/tests/work-item/work-item-list/EE/openshift-io-burr-quickstart.spec.js), create a new space, launch 2 quickstart wizard, keeping default space name for repo name, verify validation error.

**Comment by corinnekrych** [comment]
@ldimaggi @joshuawilson here is an epic for the e2e test we could do next sprint. @ldimaggi feel free to add more content so we can plan this one for sprint 136.

**Comment by joshuawilson** [comment]
I think this would be called an "acceptance" test, not sure though. 
Thanks for adding this @corinnekrych

**Comment by corinnekrych** [comment]
@joshuawilson ok renamed :)

**Comment by ldimaggi** [comment]
Closing this issue.  The EE tests that are now running on Centos CI verify the creation of pipelines and Che workspaces for all of our (5) integrated quickstarts. We are now working on getting the tests running on each PR.
