### ISSUE TITLE
Intermittent issue - Status icons do not represent actual Jenkins/Che state

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#665]
Seeing this now and then - it'a affecting automated EE tests as the tests rely on the icons to determine when a tenant update is complete and successful:

![screenshot from 2017-08-25 23-06-15](https://user-images.githubusercontent.com/642621/29738189-c2fb66be-89ea-11e7-8909-b0ce0654ced4.png)

![screenshot from 2017-08-25 23-06-35](https://user-images.githubusercontent.com/642621/29738190-c597f7ac-89ea-11e7-9952-0f93a88b874e.png)

**Comment by ldimaggi** [comment]
Seeing this frequently today. Very frequently.

**Comment by ldimaggi** [comment]
Actually- this seems to be happening all the time today - only for the Jenkins status icon.

**Comment by VeerMuchandi** [comment]
I have the same exact issue

**Comment by joshuawilson** [comment]
cc @kbsingh @jstrachan @rawlingsj

**Comment by rawlingsj** [comment]
This really isn't much to go on. If the status says Jenkins isn't green  I would guess that Jenkins isn't running. With things like this it's best to include any information from the namespace in this case Jenkins. Check if pods are running, if not try checking the deployment config and RC events and attach them to the issue. 

I wonder if we should create a 'gofabric8 diagnose osio' command to generate a gist or report of useful info, to help folkes raising issues due to lack of centralised logs and metrics in tenant namespaces?

**Comment by kbsingh** [comment]
Have you guys looked at tge zabbix dashboard, @jrawlings all the version and pod info you are looking for is included there.

-1 for creating more per user workarounds for service side  problems.

**Comment by rawlingsj** [comment]
@kbsingh I've not said I'm looking for version and pod info.  Are all the deployment config and replication controller events captured there?

**Comment by rawlingsj** [comment]
a `gofabric8 diagnose osio` would also..

- Help users provide better info when raising issues.  This issue for example contains no info to help diagnose the problem which means helpers are slower to react.
- Easier triaging of issue.  If more info is provided upfront then it is easier to label + recognise duplicates etc.
- Beneficial for advanced users that don't have access to our centralised logs and metrics solution (assuming they capture things like the events mentioned above, right now I don't think they do, if I'm wrong lets get that info out to the dev teams ASAP).  This will help users and developers alike capture the 'state of their tenant namespaces' and be in a better place to investigate themselves + google search similar 'gofabric8 diagnose osio' reported issues + resolutions.
- This is a quick solution (guesstimate a day's work) which can be moved away from when we have better insight into users tenant namespaces


I could even see an advanced solution that returns a list of possible matches of similar reported issues.  Meaning no new issue needs raising at all and users can move on quickly.

**Comment by kbsingh** [comment]
Yes, events stream is captured at this point for the entire namespace,  but at 30 min intervals so its not realtime yet.

**Comment by ldimaggi** [comment]
The original description in this issue shows 2 simultaneous screenshots - one shows the Jenkins icon off in the OSIO UI, the other shows Jenkins pods running in the OSO web console.

**Comment by ldimaggi** [comment]
The original description in this issue shows 2  simultaneous screenshots - one shows the Jenkins icon off in the OSIO  UI, the other shows Jenkins pods running in the OSO web console.

**Comment by jstrachan** [comment]
When tests fail we need them to diagnose why and report accurate error messages so we can more easily respond to issues in a timely fashion. So the gofabric8 CLI sounds a good idea to me - as something the tests run on failure - not something we need to show to end users. 

If we find accounts get into a funny state we need to fix that ASAP; if it's common outside of the tests we could internally use the same code automatically - or via a button on the UI - but fir now let's get the tests to report accurately why they fail - other than 'Jenkins didn't start'

Having 30 minute polling for events in zabbix doesn't seem too useful for the test - if the test fails we need to immediately capture the status & events, before the test is re-run to simplify diagnosis (and events get GC'd too)

**Comment by aslakknutsen** [comment]
This seems to be the reason why it doesn't show up:
https://github.com/fabric8-ui/fabric8-ui/pull/1921

A problem on _all_ accounts that have a newer v of tenants.

**Comment by ldimaggi** [comment]
This problem seems to still be there"

![screenshot from 2017-08-27 14-31-59](https://user-images.githubusercontent.com/642621/29752905-9c25c584-8b34-11e7-9cb9-30734078c007.png)

**Comment by aslakknutsen** [comment]
@ldimaggi Are you trying from the same account? Can you try again? You might have tested before it hit production.

**Comment by ldimaggi** [comment]
Still seeing this:

![screenshot from 2017-08-27 20-13-35](https://user-images.githubusercontent.com/642621/29755352-ab4aa072-8b64-11e7-9c69-53fb8c2a6467.png)

**Comment by ldimaggi** [comment]
Just saw it be successful!

![screenshot from 2017-08-27 23-07-30](https://user-images.githubusercontent.com/642621/29757795-8bfe5516-8b7c-11e7-82b8-59c410356136.png)
