### ISSUE TITLE
Autoscale f8a worker pods based on number of messages in queues

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#668]
# Description
Currently we can only scale f8a worker pods manually via pull requests to https://github.com/openshiftio/saas-analytics repo. We want to be able to autoscale workers based on number of messages in SQS. The initial implementation can work with just `{stage,prod}_ingestion_bayesianAnalysisFlow_v0` queues. 

# Acceptance criteria
- [x] worker pods are autoscaled (up and down) automatically based on number of messages in `{stage,prod}_ingestion_bayesianAnalysisFlow_v0` queues
- [x] upper limit on number of worker replicas is configurable
- [x] documentation explaining how to configure rules for autoscaling exists
- [ ] code runs in production

**Comment by krishnapaparaju** [comment]
can we document the findings around following OpenShift documentation for autoscaling ?

 https://docs.openshift.com/container-platform/3.6/dev_guide/pod_autoscaling.html

**Comment by humaton** [comment]
Currently, openshift autoscaler supports only CPU or MEM utilization. Our workers are not scalable based on this metrics since some tasks are CPU consuming other are not. Same works for memory utilization. We did try to use custom metrics for scaling but it's not ready yet.

**Comment by krishnapaparaju** [comment]
Following up with OpenShift team ... @msrb @humaton

**Comment by msrb** [comment]
I will move this forward while @humaton is on PTO.

**Comment by msrb** [comment]
Just an update here: scaler is running in staging now, @humaton is talking to SD as we need a service account before we move it to prod.

**Comment by krishnapaparaju** [comment]
@humaton do we have documentation around the strategy been followed to get around the current limitation of OpenShift around scaling..

**Comment by humaton** [comment]
@krishnapaparaju you mean like documentation for oc command scale? I am not sure I follow you here. We use standard way for scaling openshift deployments nothing special. We just don't use autoscaling.

**Comment by msrb** [comment]
Some documentation can be found in https://github.com/fabric8-analytics/fabric8-analytics-scaler.

Since we can't use the built-in memory or CPU-based autoscaling that OpenShift currently offers, we periodically check how many messages is there in SQS and we call `oc scale <deployment-config> --replicas=<corresponding-number-of-replicas>`.

**Comment by msrb** [comment]
Autoscaler still lives only in staging as it hasn't been properly tested yet. I am gonna close this issue, but follow up issue for moving this service to prod is here: https://github.com/openshiftio/openshift.io/issues/1441
