### ISSUE TITLE
[3] Refresh GitHub data in S3

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#670]
# Description
We want to refresh all already ingested GitHub data and we want to repeat this automatically every 2 weeks from now on.

# Acceptance criteria
- [x] ~~all GitHub data available in S3 are up-to-date (not older than 2 weeks)~~ all post-summit GitHub data available in S3 are up-to-date
- [x] all GitHub data in S3 will be automatically refreshed every 2 weeks
- [x] graph layer is notified about the updated data

**Comment by fridex** [comment]
Please update jobs service in production as the current master already has some related fixes/code to run this periodically.

**Comment by krishnapaparaju** [comment]
Who is working on this task ? I do not see assigned to anyone. 

This is a key task for keeping the sanity of the data..

Can someone document the current open issues / bugs to have incrementally refresh data ?

@GeorgeActon @fridex

**Comment by fridex** [comment]
> Who is working on this task ? I do not see assigned to anyone.
> 
> This is a key task for keeping the sanity of the data..
>
> Can someone document the current open issues / bugs to have incrementally refresh data ?

There were done some related fixes in the jobs service so our periodic jobs are scheduled correctly, it was already deployed to production and it looks like the periodical refresh was correctly done 7th-8th September (it is configured to be done each 14 days from now on as stated in the task description).

To completely finish this task there needs to be scheduled a job that would create package-related entries in the RDS that were not created yet for some previously analysed packages (before we introduced strictly package related analyses without version). This was already discussed in the core stream and is prioritized. @jpopelka will probably take this work item.

**Comment by krishnapaparaju** [comment]
thanks @fridex. 

Once @jpopelka get a handle on pushing package related entries into RDS,  next interesting metric to get handle on is the number of workers that are required to support consistent incremental refreshes for all the currently supported ecosystems: Maven, Node, Python and .NET..

@jfchevrette

**Comment by fridex** [comment]
I've scheduled a batch that takes care of refreshing github data for components that were ingested before summit (it will take some time) based on @jpopelka query. The batch should sync results to graph database. For components that were ingested after summit, we should have data already refreshed and synced to graph (triggered by periodic job). This will be done periodically every 2 weeks based on periodic job configuration.

**Comment by fridex** [comment]
The batch was not so successful as we encountered issues with queue configuration. The batch will be rescheduled again once workers will be free.

Payload used for selective task runs on our jobs API service:

```json
{
  "flow_arguments": [
    {
      "$filter": {
        "joins": [
          {
            "on": {
              "analyses.id": "versions.id"
            },
            "table": "versions"
          },
          {
            "on": {
              "versions.package_id": "packages.id"
            },
            "table": "packages"
          },
          {
            "on": {
              "ecosystems.id": "packages.ecosystem_id"
            },
            "table": "ecosystems"
          }
        ],
        "select": [
          "packages.name as name",
          "ecosystems.name as ecosystem",
          "versions.identifier as version"
        ],
        "distinct": true,
        "table": "analyses",
        "where": {
          "analyses.started_at <": "2017-05-29 9:44:00"
        }
      },
      "force": true
    }
  ],
  "flow_name": "bayesianFlow",
  "run_subsequent": false,
  "task_names": [
    "github_details",
    "PackageResultCollector",
    "PackageGraphImporterTask"
  ]
}
```

Postponed due to https://github.com/openshiftio/openshift.io/issues/707

**Comment by msrb** [comment]
I've seen this running in prod and [configuration](https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/f8a_jobs/default_jobs/githubGatheringJob.yaml) looks OK to me (the task runs every 2 weeks and ingests the refreshed data to graph). Although this is still running in prod for pre-summit data, I am OK to mark this as complete. Thanks everyone, especially to @fridex, for fixing roughly zillion little bugs that were haunting this task for a very long time. Great job!
