### ISSUE TITLE
Give user the option to stop import if it will overwrite a pre-existing jenkins file

### ISSUE THREAD

**Issue by bmicklea** [openshiftio/openshift.io#671]
Link to: https://github.com/fabric8io/fabric8-generator/issues/38

Marking this as a bug because overwriting someone's files without warning is not a standard or acceptable practice.

**Comment by bmicklea** [comment]
Waiting on James to return from PTO

**Comment by joshuawilson** [comment]
cc @jstrachan @rawlingsj

**Comment by jstrachan** [comment]
cc @corinnekrych

**Comment by joshuawilson** [comment]
@jstrachan are you saying this is something for @corinnekrych to do?

**Comment by jstrachan** [comment]
yeah - we chatted about  fabric8io/fabric8-generator#38 and was CC'ing her to this related issue

**Comment by bmicklea** [comment]
Closing as two linked issues are closed.

**Comment by joshuawilson** [comment]
@bmicklea I think this has been fixed yet. @corinnekrych can you please confirm.

**Comment by corinnekrych** [comment]
@joshuawilson yes it should be completed with the merge of the UI PR: https://github.com/fabric8-ui/fabric8-ui/pull/1992
