### ISSUE TITLE
 Have CI/CD in place for fabric8 analytics LSP

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#672]
# Description
Have CI/CD in place for fabric8 analytics LSP

# Acceptance criteria
- [x] Should make a release on PR merge
- [x] Raise PR on RH-CHE with updated release
- [x] Trigger npm release , which can be consumed by node app (VSCode plugin can consume now)

**Comment by joshuawilson** [comment]
You should talk to @rawlingsj

**Comment by miteshvp** [comment]
@invincibleJai - we should take this up in J train.

**Comment by miteshvp** [comment]
@invincibleJai - any updates?

**Comment by invincibleJai** [comment]
@miteshvp we need to plan this in upcoming sprint in 153 we din't had this.

**Comment by invincibleJai** [comment]
closing as implemented.
