### ISSUE TITLE
OSIO status icon should provide "push" information to user in the event that any of the tracked resources is not in a "green" state

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#674]
At present, the user must query/click on the status icon to view the state of the tracked resources. 

The status pulldown icon should provide the user with status information (blinking, turning red, showing a warning/error, etc.) whenever any resource is in a non-green state.

**Comment by qodfathr** [comment]
I'm going to close as a "reverse dupe" of #1363 . While this issue was recorded first, all of the action is happening in the other issue. @ldimaggi please grab yourself a gold star sticker from the closet.
