### ISSUE TITLE
Import project wizard step 1 is very confusing

### ISSUE THREAD

**Issue by omajid** [openshiftio/openshift.io#677]
1. Create a new space in OpenShift.io
2. Click "Add to space" (or any other way to get to the "How would you like to get started?" dialog.
3. Select "Import Existing Code"

You then get this dialog:

![strange](https://user-images.githubusercontent.com/174451/29790680-a774b39e-8c08-11e7-9f34-9862ef2f8e03.png)

It asks me for my organization. It is difficult to understand that they are asking about my *github* organization.

**Comment by corinnekrych** [comment]
it should be redesigned with https://github.com/fabric8-ui/fabric8-ui/issues/1915

**Comment by joshuawilson** [comment]
Closing as this has been fixed.
