### ISSUE TITLE
Import project step 4 flow is very confusing

### ISSUE THREAD

**Issue by omajid** [openshiftio/openshift.io#678]
I created a new space, then started the import project wizard to import a project from github. On step 4, I see some options to check or uncheck. If I uncheck the "Add webhooks" option, the Next button becomes enabled:

![step4](https://user-images.githubusercontent.com/174451/29791022-91b0f116-8c09-11e7-8628-4258907efaab.png)

If I click on Next, it says "Validating" and brings me back to step 4, but this time the "Next" button is disabled.

**Comment by corinnekrych** [comment]
@catrobson I think this related to what we discussed about the finish/next button UX issue.
if you can advise on a better UX, I'll be all in favor.

This is how forge work you can go next (and validate) each field until the end of the wizard steps. The next button becomes grayed either if some fields is invalid (in that case we displayed red errors at fields level) or if we reached the end of the flow. if we changed any input, next is enabled again and we redo the next/validation process.

The main avantage atm to have both next/finish button is the ability to skip some steps (with default values).

**Comment by joshuawilson** [comment]
@catrobson please advise.

**Comment by catrobson** [comment]
I think we might need this final page of the wizard to act a bit differently to have a sensible user experience.

On this page we should ideally only have the "Finish" button enabled, regardless of changes made to the screen.  Finish should validate any changes on that final page and then kick off the Forge creation process.

**Comment by omajid** [comment]
> On this page we should ideally only have the "Finish" button enabled, regardless of changes made to the screen. Finish should validate any changes on that final page and then kick off the Forge creation process.

As a user, this approach sounds much more sensible than the current implementation.

**Comment by joshuawilson** [comment]
@catrobson has this been added to the designs?

**Comment by catrobson** [comment]
We will reflect this in updated wizard design screens - The old wireframes are out of date at this point for the actual content and I'm not sure it makes sense to try to capture it fully there.  (Old ones for reference which do allude to this behavior: https://redhat.invisionapp.com/d/main#/console/10426007/228077943/preview).

New design efforts:  https://github.com/fabric8-ui/fabric8-ux/issues/697, https://github.com/fabric8-ui/fabric8-ux/issues/740

**Comment by qodfathr** [comment]
Fixed.
