### ISSUE TITLE
Default jenkinsfile added by openshift.io fails with strange error message

### ISSUE THREAD

**Issue by omajid** [openshiftio/openshift.io#679]
I created a new project and imported into OpenShift.io. OpenShift added a jenkinsfile to it: https://github.com/omajid/HelloWorld/blob/master/Jenkinsfile

When I kick off a build, this fails with an error from git itself. Here is the log from jenkins:

    OpenShift Build rhn-engineering-omajid/helloworld-1 from https://github.com/omajid/HelloWorld.git
    Checking out git https://github.com/omajid/HelloWorld.git into /var/lib/jenkins/jobs/rhn-engineering-omajid/jobs/helloworld/workspace@script to read Jenkinsfile
    Cloning the remote Git repository
    Cloning repository https://github.com/omajid/HelloWorld.git
     > git init /var/lib/jenkins/jobs/rhn-engineering-omajid/jobs/helloworld/workspace@script # timeout=10
    Fetching upstream changes from https://github.com/omajid/HelloWorld.git
     > git --version # timeout=10
     > git fetch --tags --progress https://github.com/omajid/HelloWorld.git +refs/heads/*:refs/remotes/origin/*
     > git config remote.origin.url https://github.com/omajid/HelloWorld.git # timeout=10
     > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
     > git config remote.origin.url https://github.com/omajid/HelloWorld.git # timeout=10
    Fetching upstream changes from https://github.com/omajid/HelloWorld.git
     > git fetch --tags --progress https://github.com/omajid/HelloWorld.git +refs/heads/*:refs/remotes/origin/*
     > git rev-parse origin/master^{commit} # timeout=10
    Checking out Revision 579ab04b3477549f376ca12ee33011906ba46e67 (origin/master)
    Commit message: "Adding pipeline"
     > git config core.sparsecheckout # timeout=10
     > git checkout -f 579ab04b3477549f376ca12ee33011906ba46e67
    First time build. Skipping changelog.
    Loading library github.com/fabric8io/fabric8-pipeline-library@master
    Creating git repository in /var/lib/jenkins/caches/git-a328a55fee5293c8cf80d5616db2c459
     > git init /var/lib/jenkins/caches/git-a328a55fee5293c8cf80d5616db2c459 # timeout=10
    Setting origin to https://github.com/fabric8io/fabric8-pipeline-library.git
     > git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
    Fetching origin...
    Fetching upstream changes from origin
     > git --version # timeout=10
     > git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/*
     > git rev-parse master^{commit} # timeout=10
     > git rev-parse origin/master^{commit} # timeout=10
    Cloning the remote Git repository
    Cloning with configured refspecs honoured and without tags
    Cloning repository https://github.com/fabric8io/fabric8-pipeline-library.git
     > git init /var/lib/jenkins/jobs/rhn-engineering-omajid/jobs/helloworld/workspace@libs/github.com/fabric8io/fabric8-pipeline-library # timeout=10
    Fetching upstream changes from https://github.com/fabric8io/fabric8-pipeline-library.git
     > git --version # timeout=10
     > git fetch --no-tags --progress https://github.com/fabric8io/fabric8-pipeline-library.git +refs/heads/*:refs/remotes/origin/*
     > git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
     > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
     > git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
    Fetching without tags
    Fetching upstream changes from https://github.com/fabric8io/fabric8-pipeline-library.git
     > git fetch --no-tags --progress https://github.com/fabric8io/fabric8-pipeline-library.git +refs/heads/*:refs/remotes/origin/*
    Checking out Revision 5800884151e570c4ef0ff28ac320e96d248ef87c (master)
    Commit message: "Merge pull request #304 from rawlingsj/master"
     > git config core.sparsecheckout # timeout=10
     > git checkout -f 5800884151e570c4ef0ff28ac320e96d248ef87c
    First time build. Skipping changelog.
    [Pipeline] echo
    Loaded PipelineConfiguration PipelineConfiguration{jobNameToKindMap={}, ciBranchPatterns=[PR-.*], cdBranchPatterns=[master], cdGitHostAndOrganisationToBranchPatterns={}, disableITestsCD=false, disableITestsCI=false, useDockerSocketFlag=false}
    [Pipeline] echo
    Loaded the useDockerSocket flag false
    [Pipeline] podTemplate
    [Pipeline] {
    [Pipeline] node
    Still waiting to schedule task
    jenkins-slave-9k5tv-grr3t is offline
    Running on jenkins-slave-9k5tv-grr3t in /home/jenkins/workspace/rhn-engineering-omajid/helloworld
    [Pipeline] {
    [Pipeline] checkout
    Cloning the remote Git repository
    Cloning repository https://github.com/omajid/HelloWorld.git
     > git init /home/jenkins/workspace/rhn-engineering-omajid/helloworld # timeout=10
    Fetching upstream changes from https://github.com/omajid/HelloWorld.git
     > git --version # timeout=10
     > git fetch --tags --progress https://github.com/omajid/HelloWorld.git +refs/heads/*:refs/remotes/origin/*
     > git config remote.origin.url https://github.com/omajid/HelloWorld.git # timeout=10
     > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
     > git config remote.origin.url https://github.com/omajid/HelloWorld.git # timeout=10
    Fetching upstream changes from https://github.com/omajid/HelloWorld.git
     > git fetch --tags --progress https://github.com/omajid/HelloWorld.git +refs/heads/*:refs/remotes/origin/*
     > git rev-parse origin/master^{commit} # timeout=10
    Checking out Revision 579ab04b3477549f376ca12ee33011906ba46e67 (origin/master)
    Commit message: "Adding pipeline"
     > git config core.sparsecheckout # timeout=10
     > git checkout -f 579ab04b3477549f376ca12ee33011906ba46e67
    [Pipeline] sh
    [helloworld] Running shell script
    + git symbolic-ref --short HEAD
    fatal: ref HEAD is not a symbolic ref
    [Pipeline] }
    [Pipeline] // node
    [Pipeline] }
    [Pipeline] // podTemplate
    [Pipeline] End of Pipeline
    ERROR: script returned exit code 128
    Finished: FAILURE

**Comment by joshuawilson** [comment]
Currently you are only able to "Create new" in the wizard. The "import" feature has not been fully implemented.

**Comment by jstrachan** [comment]
is this still an issue? Import seems to work fine for me

**Comment by omajid** [comment]
Just happened to me.

1. I created https://github.com/omajid/HelloWorld2 (I just did https://github.com/omajid/HelloWorld2/commit/cbcb5597a871b2d248393d89e13e1946b6df9cdf, the second commit in repo was added by OpenShift.io)
2. Imported it into a new space on openshift.io (was recognized by wizard as a java stack, not .NET Core, but that is a separate issue). I did not add build hooks.
3. Kicked off a build. Log is here: https://jenkins-rhn-engineering-omajid-jenkins.8a09.starter-us-east-2.openshiftapps.com/job/rhn-engineering-omajid/job/helloworld2/1/console

Last few lines of log:

    Checking out Revision 44cda975ec9e9b0fb4cc13a87d6a4875022910e4 (origin/master)
    Commit message: "Adding pipeline"
     > git config core.sparsecheckout # timeout=10
     > git checkout -f 44cda975ec9e9b0fb4cc13a87d6a4875022910e4
    [Pipeline] sh
    [helloworld2] Running shell script
    + git symbolic-ref --short HEAD
    fatal: ref HEAD is not a symbolic ref
    [Pipeline] }
    [Pipeline] // node
    [Pipeline] }
    [Pipeline] // podTemplate
    [Pipeline] End of Pipeline
    ERROR: script returned exit code 128
    Finished: FAILURE

**Comment by joshuawilson** [comment]
@jstrachan can you take a look at the content @omajid provided.

**Comment by omajid** [comment]
I can no longer reproduce this. Closing.
