### ISSUE TITLE
Redesign of the Board View

### ISSUE THREAD

**Issue by bmicklea** [openshiftio/openshift.io#680]
We had some good feedback from a community member who suggested that it would be helpful to have (an optional) Review stage that would sit between In Progress and Complete.

For organizations which are using a gitflow and pull request paradigm this provides important visibility, plus (at some point) we could theoretically automate the movement of a work item to that stage based on the creation of a PR for the branch.

**Comment by bmicklea** [comment]
@qodfathr - not sure where to put this in the planner backlog or if it was there already but I think it makes sense to have an optional review state for the board.

**Comment by qodfathr** [comment]
The roadmap calls for a highly customizable board -- both in terms of columns and swim lanes. Note that there are all sorts of challenges which need to be considered, not the least of which is what does it mean to move a WI from one column to another. In other words, does moving a WI change its state? If yes, what are the rules for those state changes? What if the columns do not match the available states for the WIT 1:1? Alternatively, perhaps some columns imply the existence of a label on a WI.
These are all valid models, and we are looking to unify them. So, yes, on the roadmap, but lots of work to be done to clarify what this will look like. We'll be looking at this deeper in a couple of months.

**Comment by joshuawilson** [comment]
cc @michaelkleinhenz

**Comment by michaelkleinhenz** [comment]
Note: we're currently working with Todd on a redesign of the board view. There is a WIP document here: https://docs.google.com/document/d/1VzcxKV5EVhBcVS_OvUj9oXfuKdK_tVL8SINSJbFIOCQ/edit#heading=h.68nstgzglraa

**Comment by michaelkleinhenz** [comment]
For backlog cleanup, I am closing this issue and copy over the comments to #330 which is the story dealing with the update to the board view.
