### ISSUE TITLE
[5] Find a new source of CVE data for NPM

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#682]
# Description

We need to find a new source of CVE data for NPM ecosystem. The database (snyk) that we've been using previously hasn't been updated for ~2 months and upstream has stopped publishing (full) information about vulnerabilities. With crucial information missing (like range which versions are affected), it's not very useful any more. We want to spend some time evaluating different sources of CVE data for NPM and then switch to the best alternative.

Possible candidates:
- OSS Index
  - REST API: https://ossindex.net/docs/restapi2
  - auditjs:
    - https://github.com/OSSIndex/auditjs
    - https://www.npmjs.com/package/auditjs
- Retire.JS
  - https://github.com/RetireJS/retire.js
  - https://www.npmjs.com/package/retire
- NSP
  - https://nodesecurity.io/tools
  - https://github.com/nodesecurity/nsp
  - https://www.npmjs.com/package/nsp
- OWASP Dependency-check
  - https://jeremylong.github.io/DependencyCheck/analyzers/nodejs.html
- http://www.cvedetails.com
- https://vulners.com
- https://nvd.nist.gov
- http://cve.mitre.org & http://cve.mitre.org
- internal sources

# Acceptance criteria
- document describing pros and cons of all evaluated sources is created; it also contains reasoning behind the final decision
- CVE data in S3 are coming from the new source
- code runs in production

**Comment by jpopelka** [comment]
Document describing individual sources of CVE/CWE:
https://docs.google.com/a/redhat.com/document/d/1Xa68aMUNTjJW8D0UMIrrxRZtNs0vomeXQtz4njL3f0o/edit?usp=sharing

**Comment by krishnapaparaju** [comment]
@msrb we will a do spike around CVEs to solve this challenge (of finding the right sources for CVEs) with goal being reducing dependency on external sources

**Comment by krishnapaparaju** [comment]
@jpopelka cvedetails.com looks good to me with the coverage, license terms. Can you please evaluate this source for the ecosystems that we needed to support (to start with NPM, Maven, PyPi and .NET)

**Comment by jpopelka** [comment]
www.cvedetails.com has been evaluated and mentioned in the [document](https://docs.google.com/document/d/1Xa68aMUNTjJW8D0UMIrrxRZtNs0vomeXQtz4njL3f0o) as well

**Comment by jpopelka** [comment]
I've reviewed www.cvedetails.com once more specifically for [Python security scans use case](https://github.com/openshiftio/openshift.io/issues/792) and added my findings into a [document](https://docs.google.com/document/d/1ScTu7BlGu9nzbSnOPb_eyiKU1ZPwjfMo1xe76YzD8Q4)

**Comment by pombredanne** [comment]
@jpopelka I would be interested to get a look at your research ... but the doc access is not public. Shall I request read access to the google doc?

**Comment by pombredanne** [comment]
@jpopelka note that as part of the https://github.com/nexB/vulnerablecode (started as a GSoC project and is really in its infancy) I am working on building eventually a comprehensive aggregated data set and feed of package vulnerabilities (and this includes working with buddies from cve-search too for this).

**Comment by pombredanne** [comment]
@jpopelka Thanks ++ I can see the doc now. Nicely done research!

**Comment by 0xh0b0** [comment]
@jpopelka I would like to access the document as well.
Please approve access request.

**Comment by 0xh0b0** [comment]
@jpopelka please approve access to the npm package also.
Thanks you!!
