### ISSUE TITLE
Integration with Libraries.io

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#684]
Integration of Libraries.io would enable quicker Onboarding of newer ecosystems at OSIO platform.
This opens up single point of integration for all the supported ecosystems and this integration would cover at least 70% of data needs for an ecosystem. 
Notable data variables not covered with Libraries.io: (a) Deducted licenses (b) CVEs 

This integration needs to be covered on technical side along with closing in partnership related discussion with Libraries.io

**Comment by miteshvp** [comment]
Its already implemented. Hence closing this.
