### ISSUE TITLE
Proposal: Sources for CVE data

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#685]
Currently OSIO analytics platform depend on 'snyk.io' for CVE data sources. 'snyk.io' cover NPM, Maven, PyPi and Ruby ecosystems. 

Ask is to have proposal document covering ..
               (a) Paid version of 'synk.io' to flag CVEs (for NPM, Maven, PyPi, Ruby) with minimal lag.
                    Currently OSIO platform use free version of CVE database which does not get updated frequently as the OSIO users would like.
              (b) Need sources for CVEs covering  the ecosystems not currently covered by snyk.io

**Comment by rgarg1** [comment]
@krishnapaparaju What rules out https://nvd.nist.gov/? I'm sure you'd have done the due diligence for this. Just curious.

**Comment by jpopelka** [comment]
@rgarg1 NVD is not the only source.
There's also cve.mitre.org & cve.mitre.org, cvedetails.com, nodesecurity.io (for nodejs) and many sites which aggregate data from these. See also #682 

Problem is that mapping platform/package names to [CPE](https://nvd.nist.gov/products/cpe) which NVD uses is not that straightforward. For example for Maven we use [OWASP Dependency Check](https://www.owasp.org/index.php/OWASP_Dependency_Check) which does this for us and does it very well. We use the same tool also for Python, but in this case it does quite a bad job, see https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/131
We use [snyk.io's public vulnerability database](https://github.com/snyk/vulnerabilitydb) only for NPM so this task (or #682) is primarily about finding another tool/source for NPM, but it might eventually be used also for Python and .NET.

**Comment by jpopelka** [comment]
I think this can be closed as we already covered this in follow-up tickets like #1052
