### ISSUE TITLE
Control rolling update of workers via maxSurge and maxUnavailable

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#687]
# Description

Currently we rely on the default k8s/OpenShift settings for rolling update deployments. Since there can be many workers running, we should explicitly set at least `maxSurge` to some safe value (default is 25%).

See the docs for k8s: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment

# Acceptance criteria
- [x] OpenShift template for workers configures `maxSurge` for rolling deployment, and possibly also `maxUnavailable`
- [ ] worker deployment in production runs with this new configuration

**Comment by humaton** [comment]
After discussion with @fridex and @vpavlin we decided to use .spec.strategy.type==Recreate for workers and set maxSurge=100% for the other parts of the project. In this case, workers will be always all killed and all recreated. Other deployments should have 0 downtimes with this config.

**Comment by fridex** [comment]
> After discussion with @fridex and @vpavlin we decided to use .spec.strategy.type==Recreate for workers

Reasoning - we need to be sure that during deployment there are no old workers that would accept messages with old flow configuration. This can occur if rolling deployment would be done in rolling strategy - a new worker would be up but old workers that can still process messages can pick old message with old flow configuration - under some circumstances this can have not nice affects (never ending flow). Downtime on worker side is acceptable.

**Comment by fridex** [comment]
Closing, as done.
