### ISSUE TITLE
Move Graph Importer as part of Selinon Workers

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#688]
_From @miteshvp on August 18, 2017 4:55_

Currently, graph sync for any EPV happens outside of worker process by way of data-model's API endpoint. This unnecessarily increases a moving piece and one more disconnected data gathering. Rather we should move this graph importer task as part of other selinon stable, so that we can take advantage of audit trail and sync to graph only those EPVs that are either failed/refreshed. 

_Copied from original issue: fabric8-analytics/fabric8-analytics-worker#263_

**Comment by msrb** [comment]
Pulling into Sprint 137 as discussed today with Mitesh.

**Comment by msrb** [comment]
Moving back to backlog as nobody plans to move this forward in sprint 141.

**Comment by jpopelka** [comment]
@msrb Re-openning since I think this was closed by mistake.

The code change is being done in https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/355 (follow-up of https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/335)
