### ISSUE TITLE
Supported Integrations of  OSIO Analytics platform 

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#691]
Here are the targeted list of integrations for OSIO analytics platform:

- [x] OSIO work flow  (Stack analysis at Che, Build pipelines)

- [x] DevStudio plugin

- [ ] Eclipse plugin

- [x] VSCode extension

- [ ] CodeEnvy extension

**Comment by qodfathr** [comment]
Do we have issues created for each integration so we can link them back to here?

**Comment by miteshvp** [comment]
Closing this issue as those extensions are available for Che, Dev-studio and VsCode.
