### ISSUE TITLE
API server fails with status 500 for springboot microservices demo app

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#695]
Steps to recreate:
1. In openshift.io, create a new space and import "https://github.com/samuzzal-choudhury/microspringboot1" (Fork this repo onto your org if required)
2. Complete the space creation wizard steps and let a build trigger for that automatically.
3. Check Jenkins logs for that build.

Following error shows up in the build log - 
```
Running Bayesian stack analysis...
Bayesian API URL is https://recommender.api.openshift.io/api/v1
com.redhat.jenkins.plugins.bayesian.BayesianException: Bayesian error: 500
	at com.redhat.jenkins.plugins.bayesian.Bayesian.submitStackForAnalysis(Bayesian.java:109)
	at com.redhat.jenkins.plugins.bayesian.BayesianAnalysisStep$Execution.run(BayesianAnalysisStep.java:99)
	at com.redhat.jenkins.plugins.bayesian.BayesianAnalysisStep$Execution.run(BayesianAnalysisStep.java:68)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

[Pipeline] error
[Pipeline] }
ERROR: Bayesian analysis failed com.redhat.jenkins.plugins.bayesian.BayesianStepResponse@76e6d6
Retrying
```

Corresponding API server log: https://gist.github.com/samuzzal-choudhury/dbf8c0a9aaad8b978123c4c97f065b8f

**Comment by msrb** [comment]
Just talked to @jyasveer about this. My findings:

- nothing wrong in the jenkins plugin, it gets 500 from the API server so it doesn't know how to continue
- I think the real problem lies here:
https://github.com/fabric8-analytics/fabric8-analytics-server/blob/304f1e0148c18d9742f4db290bf5b86031e0ce73/bayesian/api_v1.py#L634-L638

The maximum size of a message on SQS is 256k ([docs](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/limits-messages.html)).

The size of the manifest file in question is no where close to that limit:
```
$ ls -lah target/stackinfo/poms/pom.xml
-rw-rw-r--. 1 msrb msrb 164K Aug 30 10:35 target/stackinfo/poms/pom.xml
```

But we are sending it to SQS twice from some reason, in a single message.

Ideally we should store the manifest on S3 first and then pass only reference to it in SQS messages.

**Comment by samuzzal-choudhury** [comment]
@msrb API server is working fine with the pom.xml in https://github.com/samuzzal-choudhury/microspringboot1 as I tried that out from PostMan. So, I don't think it cab be an API issue rather an issue of how API is being called.

**Comment by samuzzal-choudhury** [comment]
@burrsutter Turns out that the Bayesian Jenkins plugin generated an effective POM which is too big  to be handled by the AWS SQS. Only way to handle this scenario is to send a reference of the manifest (pom.xml) files instead of the content of the file. The fix is on the way.

**Comment by krishnapaparaju** [comment]
@samuzzal-choudhury You can reference a bigger object (not sure about the size, but much bigger 256K) on S3 thru SQS message.

**Comment by fridex** [comment]
> @samuzzal-choudhury You can reference a bigger object (not sure about the size, but much bigger 256K) on S3 thru SQS message.

Yes - we need to reference object stored on S3 in SQS message, not to directly pass manifest files in message payload. This issue was tracked here [1] - that's why we hit SQS message size limitation.

[1] https://github.com/fabric8-analytics/fabric8-analytics-server/issues/43

**Comment by samuzzal-choudhury** [comment]
PRs have been merged and the changes have been being tested on the staging environment:

Server https://github.com/fabric8-analytics/fabric8-analytics-server/pull/144
Worker https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/293

**Comment by samuzzal-choudhury** [comment]
The changes are in prod and those are working as expected. Hence closing this issue.
