### ISSUE TITLE
[8] User Story: Develop and deploy Eclipse fabric8-analytics plugin

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#699]
##### Acceptance Criteria:

* An Eclipse plugin with the support for both fabric8-analytics LSP and stack analysis is available in a public marketplace.
* User authentication and token management is in place for the plugin.
* Plugin supports stack analysis of multiple manifest files present in the project.
* All required integration tests for the plugin are functional.
* CI/CD for the plugin repository is in place with the integration tests.

#### Tasks
- [ ] Add fabric8 analytics plugin/feature into JBT and Devstudio. https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/60

**Comment by qodfathr** [comment]
May we get a status update on this?

**Comment by miteshvp** [comment]
Not relevant. Hence closing
