### ISSUE TITLE
[5] Set up test environment for fabric8-analytics LSP

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#703]
Set up test environment for fabric8-analytics LSP, Currently we don't have testcases for language server and even the framework needed to run those are not in place i.e mocha to run test in node environment

# Acceptance Criteria

- [ ] Setting test environment for fabric8-analytics LSP
- [ ] Increase test coverage

**Comment by krishnapaparaju** [comment]
More documentation around this execution would be useful as the documentation needs to include more details..

**Comment by invincibleJai** [comment]
@krishnapaparaju have updated the description Krishna, Currently we don't have testcases for language server and even the framework needed to run those are not in place i.e mocha to run test in node environment

**Comment by miteshvp** [comment]
Not relevant any longer.
