### ISSUE TITLE
Handle effective pom files in mercator

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#705]
# Description

[mercator](https://github.com/fabric8-analytics/mercator-go), our tool for extracting dependencies from manifest files, always tries to build effective pom first (because pom.xml files are not self-contained). This strategy works fine for data ingestion, but it doesn't really work on user-provided pom.xml files which may reference dependencies that are not available in Maven Central (parent poms, inner-project deps, deps from private Nexus instances, ...).

Luckily, all pom.xml files coming from pipelines are already in effective format so there is no reason to try to build it again. Therefore we want to enhance pom.xml support in mercator so it's possible to just extract dependencies from given poms and skip building of effective poms entirely.

# Acceptance criteria
- [x] mercator supports pom.xml files which are already in effective format
- [x] mercator doesn't try to build effective poms for poms which are already in effective format
- [x] version of mercator running in production supports this new feature
- [x] integration stream has been notified that the new feature is available in staging/production

**Comment by msrb** [comment]
@jyasveer FYI.

**Comment by tuxdna** [comment]
@jyasveer  Could you provide a sample pom file what can reproduce the issue for this task?

**Comment by jyasveer** [comment]
Here you go Saleem

**Comment by tuxdna** [comment]
@jyasveer Looks like an attachment is missing

**Comment by jyasveer** [comment]
On 31-Aug-2017, at 1:18 PM, Saleem Ansari <notifications@github.com> wrote:

@jyasveer <https://github.com/jyasveer> Could you provide a sample pom file
what can reproduce the issue for this task?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshiftio/openshift.io/issues/705#issuecomment-326218152>,
or mute the thread

**Comment by tuxdna** [comment]
Using this file ( shared by @jyasveer elsewhere ) - https://gist.github.com/tuxdna/b54950567722c1cd66a8c9ddf5fb96e7

**Comment by jyasveer** [comment]
[pom.xml.txt](https://github.com/openshiftio/openshift.io/files/1266419/pom.xml.txt)

**Comment by tuxdna** [comment]
After downloading the file, and running mercator on it I get this:

```
$ mercator -config ./handlers.yml ~/Downloads/pom.xml 
{
   "versions": {
      "Java-POM": ""
   },
   "items": [
      {
         "time": "2017-08-31T15:50:09.748663249+05:30",
         "path": "/home/saleem/Downloads/pom.xml",
         "ecosystem": "Java-POM",
         "digests": {
            "manifest": "8bc924baa5ba11f6ed2548c4db4e3ffe4f49361a"
         }
      }
   ]
}

```

**Comment by msrb** [comment]
To completely process pom.xml files, you can run mercator as following:

`MERCATOR_JAVA_RESOLVE_POMS=true mercator pom.xml`

**Comment by tuxdna** [comment]
@msrb 

I am getting same output as above, after adding the env variable:

```
$ MERCATOR_JAVA_RESOLVE_POMS=true ./mercator -config handlers.yml ~/Downloads/pom.xml 
{
   "versions": {
      "Java-POM": ""
   },
   "items": [
      {
         "time": "2017-08-31T16:46:13.294753206+05:30",
         "path": "/home/saleem/Downloads/pom.xml",
         "ecosystem": "Java-POM",
         "digests": {
            "manifest": "8bc924baa5ba11f6ed2548c4db4e3ffe4f49361a"
         }
      }
   ]
}

```

@jyasveer Does this behavior replicate the issue for this task?

**Comment by tuxdna** [comment]
Alright, after some fiddling around with mercator and java-handler, I figured out how to generate dependencies from a given pom file:

 * Clone mercator repo, and then build java_handler ( sufficient for this case )
 * Run Java handler on the sample pom.xml file

```
cd handlers/java_handler
mvn clean package
```

Or alternatively for a closer to a dev environment ( easier to debug etc. ):

```
CLASSPATH=$(mvn dependency:build-classpath | grep -A1 'Dependencies classpath:' | tail -1)

MERCATOR_JAVA_RESOLVE_POMS=true java -cp $CLASSPATH:target/classes/ mercator.MercatorJava ~/Downloads/pom.xml  | python -mjson.tool
{
    "pom.xml": {
        "artifactId": "microspringboot1",
        "dependencies": {
            "compile": {
                "org.springframework.boot:spring-boot-starter-actuator::": "1.5.6.RELEASE",
                "org.springframework.boot:spring-boot-starter-web::": "1.5.6.RELEASE",
                "org.springframework.cloud:spring-cloud-starter-hystrix::": "1.3.2.RELEASE"
            },
            "runtime": {
                "org.springframework.boot:spring-boot-devtools::": "1.5.6.RELEASE"
            },
            "test": {
                "org.springframework.boot:spring-boot-starter-test::": "1.5.6.RELEASE"
            }
        },
        "description": "Demo project for Spring Boot",
        "groupId": "com.redhat.developers.osio",
        "licenses": [
            "Apache License, Version 2.0"
        ],
        "name": "microspringboot1",
        "scm_url": "https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/microspringboot1",
        "url": "http://projects.spring.io/spring-boot/microspringboot1/",
        "version": "0.0.1-SNAPSHOT"
    }
}


```

It takes some time ( in minutes ) to generate this output. This is due to the fact that, java_handler uses Maven Invoker to download all the dependencies ( a temp folder ), to generate effective pom file.

@msr @jyasveer: With the above description, does it make sense to have effective pom generation be made optional ( controlled via CLI flag / env variables ) ?

**Comment by tuxdna** [comment]
The resulting POM file looks like this: https://gist.github.com/tuxdna/b54950567722c1cd66a8c9ddf5fb96e7#file-resolvedpom605313494541275704-xml

**Comment by msrb** [comment]
> does it make sense to have effective pom generation be made optional ( controlled via CLI flag / env variables ) ?

Yes, that's exactly what we want to do 👍

**Comment by jyasveer** [comment]
Yes. we can ignore the effective pom generation.
I have a question here:-
1. If our manifests come via jenkins pipeline plugin, we run the effective
pom generation step and then invoke the api which i see as fine.

2. Now what if we want to read the repo from the github directly, bcoz i
have implemented a use case where we can read the repo by passing just the
github url. So here in this case, we have to run the effective pom
generation step on the raw pom.xml file.

Any thoughts ?

Jyasveer Gotta

Software Engineer

Red Hat India <https://www.redhat.com>

jgotta@redhat.com
<https://red.ht/sig>

**Comment by tuxdna** [comment]
For a project containing only a single `pom.xml` at the base path, the effective pom contains dependencies at following xpath `/project/dependencyManagement/dependencies/dependency/`

 * https://gist.github.com/tuxdna/b54950567722c1cd66a8c9ddf5fb96e7#file-resolvedpom605313494541275704-xml


However for a project containing multiple `pom.xml` files such as this one (https://github.com/jyasveer/maven-multi-module-example-2), the effective pom contains dependencies at following xpath `/projects/project/dependencies/dependency/`

 * https://gist.github.com/tuxdna/b54950567722c1cd66a8c9ddf5fb96e7#file-effective-pom-xml

**Comment by msrb** [comment]
@tuxdna 

Real dependencies are only in `/projects/project/dependencies/dependency/`.

**Comment by tuxdna** [comment]
@msrb 

While I do understand that we want to disable effective pom generation, I am not sure of why we should completely disable that?

@jyasveer 

Can you confirm that the effective pom file generated by Jenkins plugin contains the [following line](https://gist.github.com/tuxdna/b54950567722c1cd66a8c9ddf5fb96e7#file-effective-pom-xml-L11) ?

```
  <!-- Effective POM for project 'SOME_PROJECT_NAME'               -->
```

If yes, then the solution will be easy to implement i.e. we only generate effective pom files when we don't have one ( by detecting the absence of the line above ).

There will be other cases to handle as well:

 * multi module projects ( with sub project / modules etc. )
 * having or not having `dependencyManagement` sections etc. ( my last comment in this issue explains the difference )

Looking forward to your responses. @msrb and @jyasveer :-)

**Comment by msrb** [comment]
> While I do understand that we want to disable effective pom generation, I am not sure of why we should completely disable that?

There needs to be a way how to tell mercator that it shouldn't build effective pom and it should process the pom.xml as it is. I think the issue you filled against mercator repo will solve this problem 😉 

> multi module projects ( with sub project / modules etc. )

I think the way how it is implemented right now is that we run mercator on each pom.xml file separately. So mercator, as used by API server, doesn't know about multi module projects.

**Comment by tuxdna** [comment]
@msrb: Yes, this PR https://github.com/fabric8-analytics/mercator-go/pull/16 will enable us to configure POM expansion / resolution using `MERCATOR_JAVA_RESOLVE_POMS=true` env variable.

Now in case of a multi POM project, do we aggregate the dependencies gathered from different pom.xml files, i.e. the aggregate of all dependencies will represent this project?

**Comment by miteshvp** [comment]
> Now in case of a multi POM project, do we aggregate the dependencies gathered from different pom.xml files, i.e. the aggregate of all dependencies will represent this project?

AFAIK, each manifest will be shown as separate tabs to the end-user. That means, we should not aggregate deps for multi-manifest scenario, rather each manifest is one stack request for us.
@samuzzal-choudhury please correct me if my understanding is wrong.

**Comment by jyasveer** [comment]
@tuxdna 
This command is run in the jenkins plugin [command in jenkins](https://github.com/jyasveer/fabric8-analytics-jenkins-plugin-test-microspringboot1/blob/master/Jenkinsfile#L6)
And i don't see this [text](https://gist.github.com/tuxdna/b54950567722c1cd66a8c9ddf5fb96e7#file-effective-pom-xml-L11) in the generated effective poms

**Comment by tuxdna** [comment]
@jyasveer: Can you elaborate on why `io.github.stackinfo:stackinfo-maven-plugin:0.2:prepare` is required to be present in resolved file? Perhaps I am missing some context here.

**Comment by msrb** [comment]
@tuxdna We call `io.github.stackinfo:stackinfo-maven-plugin:0.2:prepare` in pipelines to generate effective poms in the same environment where build just happened (so we know all required poms and dependencies are on the system, and they can be non-free, private, not available in Maven Central, ...).

We then send those already generated effective poms to fabric8-analytics for analysis.

**Comment by tuxdna** [comment]
@msrb On it. Let me check.

**Comment by tuxdna** [comment]
@msrb In that case, the string that @jyasveer mentioned need not be a part of mercator's output? I am confused with that comment.

**Comment by tuxdna** [comment]
First check list is complete via - https://github.com/fabric8-analytics/mercator-go/issues/15

**Comment by jpopelka** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/346 runs on staging

**Comment by fridex** [comment]
@jpopelka can this be marked as completed now?

**Comment by jpopelka** [comment]
It's been [pushed to prod](https://github.com/openshiftio/saas-analytics/pull/102).
Now somebody from integration stream should verify that the acceptance criteria are met - @jyasveer ?

**Comment by msrb** [comment]
Seems to be working as expected, thanks guys 😉

**Comment by krishnapaparaju** [comment]
@samuzzal-choudhury this change would break the current flow at IDE extensions. 

@invincibleJai how do we handle this at VSCode extension ?

@GeetikaBatra how do we handle this at DevStudio plugin ?

cc @msrb @GeorgeActon

**Comment by krishnapaparaju** [comment]
Please ensure the current API supports both kinds of pom.xml (effective, normal) till IDE extensions could support effective pom.xml

**Comment by msrb** [comment]
I will revert the changes for now as we discussed on a meeting today with @GeetikaBatra @invincibleJai @samuzzal-choudhury and @miteshvp.

**Comment by msrb** [comment]
PR restoring the original behavior: https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/387
