### ISSUE TITLE
Rerun license worker on already ingested components

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#707]
# Description

We have switched to a new tool for detecting licenses on source code level. It produces much better results, but majority of our license data in S3 was produced by the old tool and thus is of lower quality. We want to rerun license worker on all already ingested components to get better license data.

The goal for sprint 137 is to have 10% of license data in S3 produced by the new worker. 

# Dependencies:
- autoscaling of workers: #668

# Acceptance criteria:
- [ ] license data (detected licenses) in production S3 buckets were produced by the new license worker

**Comment by fridex** [comment]
[This template for jobs](https://github.com/fabric8-analytics/fabric8-analytics-jobs#run-graph-syncs-of-previously-analysed-ecosystem-package-version) can be used, just add `source_lisences` to tasks that should be run (`task_names` array) and tweak `limit` and `offset` based on desired batch size.

**Comment by fridex** [comment]
The batch has been scheduled. It will take some time to finish (I assume significant based on number of packages available).

**Comment by msrb** [comment]
This is running in production at the moment. I am not 100% confident that the run will be successful so let's keep this open for now.

**Comment by krishnapaparaju** [comment]
@msrb I believe we are talking about detected licenses (as part of this issue). Showing detected licenses is not current priority, not being shown to OSIO users. Might be important piece of information down the road, I would suggest not to spend workers towards this workitem.

**Comment by fridex** [comment]
> @msrb I believe we are talking about detected licenses (as part of this issue). Showing detected licenses is not current priority, not being shown to OSIO users. Might be important piece of information down the road, I would suggest not to spend workers towards this workitem.

Based on this comment and discussion we had on today's standup, I will stop the batch run and move this card back to backlog.

**Comment by fridex** [comment]
> Based on this comment and discussion we had on today's standup, I will stop the batch run and move this card back to backlog.

Workers are still processing the batch, there was an error with endpoint (https://github.com/fabric8-analytics/fabric8-analytics-jobs/issues/188)

**Comment by miteshvp** [comment]
Closing this as I do not see any workers batch.
