### ISSUE TITLE
Enable tests for Jobs service which require authentication

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#709]
# Description

Pavel (@tisnik) prepared E2E tests for our Jobs service, but some of them are not enabled in CI at the moment, because they require authentication.

# Acceptance criteria
- [ ] all existing tests for Jobs service all enabled and pass in CI

**Comment by pkajaba** [comment]
I am afraid this can't be done with automation.

1) It can be done if we update token in Jenkins every 2 weeks. 

2) It MIGHT be done if we stored credentials of GitHub user which is inside Jenkins. However, this is dangerous since with some effort everybody can read these secrets.

@fridex suggested that we have tests in place and we will run them just time to time with personals tokens.

**Comment by fridex** [comment]
> @fridex suggested that we have tests in place and we will run them just time to time with personals tokens.

We could have these tests in place/ready for execution but do not run them on each PR in publicly available Jenkins instance. Basically all solutions that we come up with are not straightforward or require changes that could affect our security by introducing new security holes.

We could test them from "time to time" and every time there is done a change in our authentication mechanism.

**Comment by fridex** [comment]
We can try to reach out to other teams in OSIO to check if they do tests like these in CICO and if so how do they do them automatically.

**Comment by ldimaggi** [comment]
See the EE tests defined here for reference:  
https://github.com/almighty/almighty-jobs/blob/master/devtools-ci-index.yaml

**Comment by fridex** [comment]
Ping... Any new findings or solutions?

**Comment by msrb** [comment]
We need to find out if it's possible to have credentials in Jenkins that can be used only by particular job/set of jobs. Or we could run these credentials-sensitive tests in Central CI.

https://github.com/openshiftio/openshift.io/issues/1329 has higher priority in this sprint, so I am moving this issue back to backlog.

**Comment by miteshvp** [comment]
Done. Closing.
