### ISSUE TITLE
Gather tags from StackOverflow

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#710]
# Description

In order to proceed with tagging, we would like to gather tags from StackOverflow. These tags are not strictly bound to any ecosystem, so we could treat them as ecosystem agnostic tags and use them with per-ecosystem specific tags (aggregate tags multiple sources - see [tagger aggregation](https://github.com/fabric8-analytics/fabric8-analytics-tagger/#aggregating-keywords---aggregate)).

Tags are available as a ZIP file containing an XML file at [StackOverflow](https://archive.org/download/stackexchange), but there could be explored more suitable ways on how to download these tags (database snapshot?, API?).

# Acceptance criteria

- [x] Implement tagger collector that would automatically download and collect tags with their occurrence count - more details can be found in [tagger README](https://github.com/fabric8-analytics/fabric8-analytics-tagger/#collecting-keywords---collect), one can also study [already implemented PyPI tags gathering](https://github.com/fabric8-analytics/fabric8-analytics-tagger/blob/master/f8a_tagger/collectors/pypi.py). Tags gathering needs to be fully automated without any additional input (running tagger CLI or directly using already existing tagger API so this work could be later adopted to other parts e.g. core workers).
- [x] Tags gathering is run using implemented tagger collector and collected tags are placed in [tags repo](https://github.com/fabric8-analytics/fabric8-analytics-tags) under [raw directory](https://github.com/fabric8-analytics/fabric8-analytics-tags/tree/master/raw), respecting tagger tags format
- [ ] License of StackOverflow data (tags) is checked so tags can be used

**Comment by pkajaba** [comment]
PR submitted: https://github.com/fabric8-analytics/fabric8-analytics-tagger/pull/29

**Comment by krishnapaparaju** [comment]
Can you please point me to  (a) master list of tags across all the ecosystems (b) Master list of tags for each ecosystem eg: Maven. These master lists are something that we can validate against and play a big role in crow sourcing the tagging work.

@samuzzal-choudhury @miteshvp @msrb

**Comment by pkajaba** [comment]
@krishnapaparaju not sure whether this is what you are looking for, but tags for ecosystems can be found here: https://github.com/fabric8-analytics/fabric8-analytics-tags/tree/master/raw

**Comment by fridex** [comment]
The last bit missing here is licensing. Was it checked? It should be CC based on [license.txt](https://ia800500.us.archive.org/22/items/stackexchange/license.txt) file so we should be fine.

**Comment by pkajaba** [comment]
You are right, it's CC. I tried to reach @GeorgeActon to verify whether it's really OK. I am waiting for his response.

**Comment by joshuawilson** [comment]
You don't have to close it but you can't stay here. Please close or move to backlog or next sprint.

**Comment by miteshvp** [comment]
Done. Closing
