### ISSUE TITLE
Show only CentOS stacks in the quickstart section of Che dashboard

### ISSUE THREAD

**Issue by bmicklea** [openshiftio/openshift.io#711]
At some point we should show only OSIO-compatible stacks (based on CentOS presumably) in the stack sections of the Che dashboard when it's deployed to OSIO.

**Comment by bmicklea** [comment]
@davidfestal - FYI it was confusing when I went into OSIO and the Che dashboard and saw a bunch of non-CentOS.

**Comment by ibuziuk** [comment]
![image](https://user-images.githubusercontent.com/1461122/30264801-6349008a-96da-11e7-92d2-3dc1d6184b6c.png)
@bmicklea looks like all the stacks are centos based in quickstart section - che 2.0.16

**Comment by bmicklea** [comment]
@ibuziuk - my point was that when we have a package of Che on OpenShift we should really remove any stacks that aren't compatible with OS.

**Comment by ibuziuk** [comment]
We have discussed this issue with @l0rd during stand-up. Currently the following stacks are predefined in rh-che assembly:
![image](https://user-images.githubusercontent.com/1461122/30334393-c6419a8e-97df-11e7-9d1d-f641e9e3172e.png)
All of them are supposed to work on osio, so it was decided to check all the stacks after fixing inconsistencies [1] and either exclude  or create separate issues for those  which are not working on osio for some reason

[1] Inconsistencies between stacks #147

**Comment by qodfathr** [comment]
@bmicklea is this issue still correct? Should it be CentOS only? RHEL only? Some combo?

**Comment by bmicklea** [comment]
This has been fixed, thanks for the bump. Closing.
