### ISSUE TITLE
Gather tags from MVN Repository

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#712]
# Description

In order to tag Maven projects, we would like to gather tags from [MVN Repository](http://mvnrepository.com/). Unfortunately, it looks like MVN repository has no API so this gathering needs to be probably done directly on HTML by scraping tags. Also there is probably no listing of projects on MVN Repository so we would need to list projects using maven indexer.

It would be also good to parametrize this gathering so we can periodically gather new tags based on project releasing - maven indexer stores releases by appending to list, so probably keeping index to project listing should do the trick.

# Acceptance criteria

- [x] Implement tagger collector that would automatically download and collect tags with their occurrence count - more details can be found in [tagger README](https://github.com/fabric8-analytics/fabric8-analytics-tagger/#collecting-keywords---collect), one can also study [already implemented PyPI tags gathering](https://github.com/fabric8-analytics/fabric8-analytics-tagger/blob/master/f8a_tagger/collectors/pypi.py). Tags gathering needs to be fully automated without any additional input (running tagger CLI or directly using already existing tagger library API so this work could be later adopted to other parts e.g. core workers).
- [x] Tags gathering is run using implemented tagger collector and collected tags are placed in [tags repo](https://github.com/fabric8-analytics/fabric8-analytics-tags) under [raw directory](https://github.com/fabric8-analytics/fabric8-analytics-tags/tree/master/raw), respecting tagger tags format
- [ ] Check for possible other ways on how to aggregate these tags
 
- [ ] License of Maven repository data (tags) is checked so tags can be used

**Comment by pkajaba** [comment]
PR merged: https://github.com/fabric8-analytics/fabric8-analytics-tagger/pull/36

**Comment by pkajaba** [comment]
I encountered issue because mvnrepository.com has some throttling in place, so we can't gather all tags. I have to research what are our options.

**Comment by fridex** [comment]
> I encountered issue because mvnrepository.com has some throttling in place, so we can't gather all tags. I have to research what are our options.

@pkajaba added sleeping between requests in https://github.com/fabric8-analytics/fabric8-analytics-tagger/pull/42 to avoid ban. Gathering will be considerably slower.

**Comment by joshuawilson** [comment]
You don't have to close it but you can't stay here. Please close or move to backlog or next sprint.

**Comment by miteshvp** [comment]
Done. Closing
