### ISSUE TITLE
Disable email updates in user profiles

### ISSUE THREAD

**Issue by bmicklea** [openshiftio/openshift.io#713]
Cross linked to: https://github.com/fabric8-ui/fabric8-ui/pull/1936

Users can currently edit their email in the OSIO profile page to something that is unverified and can't receive email. When we repeatedly try and email those addresses it harms our spam score and could result (ultimately) in blacklisting.

**Comment by alexeykazakov** [comment]
Email updates are now disabled in user profile (in UI)
