### ISSUE TITLE
Analytics report appears to provide a link to the project's pom.xml, but the file name is not a link

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#715]
See attached screenshot - the pom.xml file name is displayed in blue text implying that it is a live link - but it is static text and not a link.

![screenshot from 2017-08-30 13-20-40](https://user-images.githubusercontent.com/642621/29886179-3da09a66-8d87-11e7-8e61-782b134209b1.png)

**Comment by burrsutter** [comment]
duplicate of #714

**Comment by krishnapaparaju** [comment]
@arunkumars08  font colour for the text as part of tab ('pom.xml') to reflect that its not a link.

**Comment by arunkumars08** [comment]
@ldimaggi Yes, that shouldn't be highlighted as a link. However it is not a link to project's pom.xml. It is just an indicator of the manifest file.

**Comment by arunkumars08** [comment]
@ldimaggi The color problem is addressed now and is in production. Please verify and let me know in case of issues.

**Comment by ldimaggi** [comment]
Verified the fix - closing.
