### ISSUE TITLE
Stack recommendations causes browser thrashing and ultimately lock

### ISSUE THREAD

**Issue by bmicklea** [openshiftio/openshift.io#716]
Stack recomendations in OSIO using the vert.x-basic project triggers cascading recommendation tabs for pom.xml (~1 pom.xml / 3 secs). As the number of these grow the browser runs slower and slower and ultimately becomes unusable.

## How to Reproduce
- Follow the steps in the [workshop document](https://docs.google.com/document/d/1KsV8oHRe7DYCVCMfVrB2yd3hU4iBi11YI5MyuXoozQw/edit#)
- When the space is created and the Build #1 pipeline completes notice that the stack recommendations begin (this may take several minutes)
- Once stack recommendations start watch for the progression of more and more pom.xml
- If you stay on this screen for >5 minutes you'll find the browser is either extremely slow or unusable

![screen shot 2017-08-30 at 2 58 07 pm](https://user-images.githubusercontent.com/7644938/29889887-c23ea590-8d93-11e7-90d5-9002a11fa8f6.png)

**Comment by bmicklea** [comment]
@adisakala and @krishnapaparaju - this is a blocker as it makes it very difficult for students to complete the workshop. I assume it's related to the recent update of the analytics version in production.

**Comment by krishnapaparaju** [comment]
@bmicklea , will look into this right away.
