### ISSUE TITLE
After successful import of existing code - 'OK' button is non operative

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#719]
The button highlighted in the attached screenshot is not operative after a successful import:

![screenshot from 2017-08-30 22-07-48](https://user-images.githubusercontent.com/642621/29903237-d0d7c6ee-8dd0-11e7-9264-c6f72fbc2d7a.png)

**Comment by ldimaggi** [comment]
Yup - found by the EE tests:
https://ci.centos.org/job/devtools-test-end-to-end-openshift.io/293/console

**Comment by corinnekrych** [comment]
@ldimaggi it should be fixed by: https://github.com/fabric8io/fabric8-generator/pull/46 once pushed to prod

**Comment by joshuawilson** [comment]
@ldimaggi please verify.

**Comment by ldimaggi** [comment]
Verified!
