### ISSUE TITLE
www.openshift.io is not promoted to prod

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#720]
It seems that https://github.com/openshiftio/saas-openshiftio/blob/master/dsaas-services/www.openshift.io.yaml doesn't promote the latest openshift.io app (https://github.com/openshiftio/openshift.io) to prod.
I see a new deployment but it's some old image.

**Comment by vpavlin** [comment]
Hi, I see new image...the tag for image should be `befd41` based on last master commit

I see it being correctly used here https://ci.centos.org/view/Devtools/job/devtools-saas-openshiftio-promote-to-prod/230/console

And I see the image with this tag to be used in dsaas-production project in OSD

Can you elaborate why do you think it's an old image?

**Comment by sbose78** [comment]
This fix in prod will call 'logout' , and then redirect to login when you try logging in on https://openshift.io, I tried it out and looks like the fix works.

https://github.com/openshiftio/openshift.io/commit/befd416efc8aa5198a1767cb428981bec4d25ae4#diff-670d0a4d2d9db6ee9ce223391cf66387R93

Functionally, it does looks like prod has the right image.

**Comment by alexeykazakov** [comment]
@vpavlin yes, @sbose78 is correct. I see the old code in that image. But the image in prod-preview does have the correct code.

**Comment by alexeykazakov** [comment]
Any update on this?

**Comment by joshuawilson** [comment]
@alexeykazakov Prod has you commit, which is the latest. Maybe you need a hard refresh or it doesn't do what you thought it should do.

**Comment by alexeykazakov** [comment]
It was the cache! Closing.
