### ISSUE TITLE
Issue with 'show complete stack report' in the dashboard page

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#721]
Only first time click on 'show complete stack report' (at the space dashboard page) opens up the stack report. Any further clicks on this click would not open up stack report. 

If user moves away from dashboard of a space, comes back to space dashboard.. first click would work with 'show complete stack report' , further clicks would not open up complete stack report.

**Comment by arunkumars08** [comment]
@krishnapaparaju The fix for this is in production. Please let me know if it still persists.

**Comment by joshuawilson** [comment]
Closing, please reopen if still needed.
