### ISSUE TITLE
Issue with stack report on space change from dashboard screen (left top) 

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#722]
Steps to reproduce

- open space dashboard 
<img width="1680" alt="screen shot 2017-08-31 at 9 58 27 am" src="https://user-images.githubusercontent.com/5129024/29906484-fe6f91ba-8e32-11e7-9e53-0d1cd21aeb34.png">

- now switch space from dashboard view itself (left top nav)
<img width="1679" alt="screen shot 2017-08-31 at 9 59 32 am" src="https://user-images.githubusercontent.com/5129024/29906507-210fbb0a-8e33-11e7-8c6f-475ebedc2454.png">

now we have two entries of `pom.xml` should be one.

**Comment by arunkumars08** [comment]
@invincibleJai The fix for this is in prod. Please let me know in case this issue still persists.

**Comment by nelmax1** [comment]
Looks better now, thank you for fixing it!

**Comment by invincibleJai** [comment]
@arunkumars08 looks good. Thanks !!
