### ISSUE TITLE
work item description has HTML markups <br /> post creation of work item from stack report

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#723]
work item description has HTML markups <br /> post creation of work item from stack report, needs to be markdown(supported)

<img width="1676" alt="screen shot 2017-08-31 at 10 04 07 am" src="https://user-images.githubusercontent.com/5129024/29906639-d951ef44-8e33-11e7-983e-a79b80c27873.png">

**Comment by invincibleJai** [comment]
@arunkumars08 have been fixed , in prod now pls verify
CC @samuzzal-choudhury

**Comment by arunkumars08** [comment]
@invincibleJai Appears as expected.

**Comment by invincibleJai** [comment]
@arunkumars08 thanks. Closing it
