### ISSUE TITLE
Gather tags from npm.js

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#725]
# Description

In order to tag NPM projects, we would like to gather tags from [npmjs.com](http://npmjs.com). It would be good to parametrize this gathering so we can periodically gather new tags based on new project releasing.

This gathering should gather ALL topics that are present at npmjs in order to tag projects.

# Acceptance criteria

- [ ] License of npmjs.com repository data (tags) is checked so tags can be used
- [ ] Check for possible ways on how to aggregate these tags
  *  is there an API call? 
  * we already use [SkimDB](https://skimdb.npmjs.com/) to get info about packages and releases, this could be suitable for tags gathering as well - needs inspection
- [ ] Implement tagger collector that would automatically download and collect tags with their occurrence count - more details can be found in [tagger README](https://github.com/fabric8-analytics/fabric8-analytics-tagger/#collecting-keywords---collect), one can also study [already implemented PyPI tags gathering](https://github.com/fabric8-analytics/fabric8-analytics-tagger/blob/master/f8a_tagger/collectors/pypi.py). Tags gathering needs to be fully automated without any additional input (running tagger CLI or directly using already existing tagger library API so this work could be later adopted to other parts e.g. core workers).
 - [ ] Tags gathering is run using implemented tagger collector and collected tags are placed in [tags repo](https://github.com/fabric8-analytics/fabric8-analytics-tags) under [raw directory](https://github.com/fabric8-analytics/fabric8-analytics-tags/tree/master/raw), respecting tagger tags format

**Comment by miteshvp** [comment]
Done in a separate exercise. Closing.
