### ISSUE TITLE
Automatize PGM training

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#729]
# Description

In order to automate PGM training we could introduce API endpoint that would trigger training job and place appropriate training outcome on S3. This was probably already implemented but was removed - search git log history to revert removal.

Training could be automatically triggered from jobs service by creating a periodic job that would handle this operation. PGM API would not be exposed outside cluster but rather jobs service would act like a gateway to PGM API as jobs service already handles authentication.

# Acceptance criteria
 - [ ] introduce/revert PGM API endpoint for triggering training that stores training results on S3
 - [ ] create a job handler in jobs service (follow [instructions in documentation](https://github.com/fabric8-analytics/fabric8-analytics-jobs#implementing-a-job)) that contacts PGM API to train model
- [ ] introduce [job YAML configuration](https://github.com/fabric8-analytics/fabric8-analytics-jobs#default-jobs) that makes sure jobs API is called periodically, one can follow one of the [existing job configurations as an example](https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/f8a_jobs/default_jobs/cveCheckJob.yaml)
- [ ] create a unit test for job handler
- [ ] make sure handler is called in production periodically respecting configuration and triggers training
- [ ] make sure training is correctly done in production and results are stored on S3 in an appropriate bucket

**Comment by fridex** [comment]
CC @tuhinsharma

**Comment by miteshvp** [comment]
Done. Closing
