### ISSUE TITLE
Automatically update newly trained PGM model

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#730]
# Description

In order to automate PGM updates we could introduce API endpoint that would trigger updating PGM model data by retrieving already trained model data from S3 (see related #729). This was probably already implemented but was removed - search git log history to revert removal.

Updates could be automatically triggered from jobs service by creating a periodic job that would handle this operation. PGM API would not be exposed outside the cluster but rather jobs service would act like a gateway to PGM API as jobs service already handles authentication.

# Acceptance criteria
 - [ ] introduce/revert PGM API endpoint for updating training that are stored on S3
 - [ ] create a job handler in jobs service (follow [instructions in documentation](https://github.com/fabric8-analytics/fabric8-analytics-jobs#implementing-a-job)) that contacts PGM API to update model
- [ ] introduce [job YAML configuration](https://github.com/fabric8-analytics/fabric8-analytics-jobs#default-jobs) that makes sure jobs API is called periodically, one can follow one of the [existing job configurations as an example](https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/f8a_jobs/default_jobs/cveCheckJob.yaml)
- [ ] create a unit test for new job handler
- [ ] make sure handler is called in production periodically respecting configuration and triggers PGM model updates
- [ ] make sure updates are correctly done in production and PGM correctly respect updates of model data

**Comment by fridex** [comment]
CC @tuhinsharma

**Comment by fridex** [comment]
Possible optimization we could change training part described in #729 to automatically trigger update once model data get updated and placed on S3. With this we would "immediately" update model after training. Needs discussion and design decisions with @tuhinsharma. Having "update" endpoint as described in this issue could be beneficial in long-term anyway.

**Comment by sivaavkd** [comment]
This is not relevant anymore, closing this.
