### ISSUE TITLE
[13] Dynamically add new tasks in analytics core during runtime

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#731]
# Description

[Selinon/Dispatcher](https://github.com/selinon/selinon) that was developed for analytics core does not support changes in the [YAML configuration files](https://github.com/fabric8-analytics/fabric8-analytics-worker/tree/master/f8a_worker/dispatcher) when it comes to adding/removing tasks or changing structure of task flow graph on runtime. We would like to add such support which would enable us to add tasks dynamically without purging queues in production. There will be needed support for message-related migrations as described in [Selinon RFE](https://github.com/selinon/selinonlib/issues/) and [Selinon documentation](http://selinon.readthedocs.io/en/latest/faq.html#is-it-possible-to-do-changes-in-the-configuration-and-do-continuous-redeployment) for more info on this.

# Acceptance criteria
 - [x] [Selinonlib](https://github.com/selinon/selinonlib/) can perform message migrations based on YAML configuration file changes
    * the output would be a JSON describing changes in the YAML cofiguration
 - [x] [Selinon](https://github.com/selinon/selinon) adds/respects message versions and can tackle changes in the YAML configuration
    * every time worker starts, it checks for previously generated migrations (by selinonlib) based on changes in the YAML configuration
    * messages on queue needs to be versioned each time they are sent to queue
    * before dispatcher performs any actions in scheduling, it performs message migrations based on message versions (let's say similarly to alembic)
 - [x] code is tested in Selinon and Selinonlib CI
 - [ ] analytics core supports YAML configuration file changes and performs migrations in production

**Comment by fridex** [comment]
Documentation available at https://selinon.readthedocs.io/en/latest/migrations.html.

**Comment by fridex** [comment]
Code done mostly in https://github.com/selinon/selinon/pull/48, https://github.com/selinon/selinon/pull/56, https://github.com/selinon/selinonlib/pull/46, https://github.com/selinon/selinonlib/pull/45, https://github.com/selinon/selinonlib/pull/44 and https://github.com/selinon/selinonlib/pull/43

**Comment by fridex** [comment]
Changes in worker: https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/437

**Comment by msrb** [comment]
The code runs in prod now, thanks @fridex!
