### ISSUE TITLE
Configure PCP for aggregating process-level metrics in analytics core

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#732]
# Description

With Performance Co-Pilot we would be able to monitor all processes that are run inside containers. We would like to do so to possibly detect very resource hungry processes in the cluster and separate them on standalone workers with configured resource limits. This would prevent from recent CPU-related issues in the cluster.

Please follow thread [1], possibly contact Frank Eigler <fche@> and Fridolin <fridolin@>

[1] devtools-bayesian mailing list, thread "Performance Co-Pilot" from Sun, 18 Jun 2017

# Acceptance criteria

- [ ] inspect which metrics could be gathered
- [ ] create account in PCP (contact fche)
- [ ] PCP collects metrics in production environment
- [ ] make sure metrics are correctly gathered and correctly reported

**Comment by krishnapaparaju** [comment]
Did we consider sysdig for system level metrics ?

**Comment by fridex** [comment]
> Did we consider sysdig for system level metrics?

Thanks for suggestion. This needs to be consulted with service delivery team as these solutions are hosted/managed by them.

**Comment by fche** [comment]
sysdig requires custom kernel extensions and some other infrastructure; unlikely.

As for PCP, the normal OSIO OSD monitoring widgetry is already configured to track per-process resource usage.  The analytics component would need to opt into this by installing the pcp pmcd background process into the container(s) that you need monitored.  We can help with this; several other OSIO OSD components have already done the same (alm-core, che-server, etc.).

**Comment by tuxdna** [comment]
@fche Thanks for pointing to PCP. Is a running pmcd background process sufficient for collecting the metrics, as in this fille below ?

 * https://github.com/redhat-developer/rh-che/blob/bb51e5ab8625cb66b77ec3dc6ded7ecdb9ff4aa6/dockerfiles/che-fabric8/Dockerfile#L10

**Comment by fche** [comment]
Is the bayesian software likely to stay inside its own distinct namespaces on OSD?  If so, would you like it to be monitored internally (with its own copy of all the pcp collection infrastructure, as in the osd-monitor pod)?  Or would you like it remotely monitored, cross-namespace from within normal OSD?

**Comment by kbsingh** [comment]
the analytics stack is deployed into its own namespace. 

However, I would *strongly* recommend not doing your own monitoring UX - that should be consolidated with the osio service stack in zabbix.

**Comment by fche** [comment]
The plain pcp webapps represent a zero cost alternative, no custom UX involved.  Does there already exist a zabbix schema/plan for absorbing this information?

**Comment by kbsingh** [comment]
if every 22 feature teams end up with their own monitoring stack, we've effectively failed at the whole monitoring goals.

**Comment by fche** [comment]
KB, I don't know how what you're worried about relates to anything that I said.  :-)

Anyway, first things first, getting some basic data collection going.  That'll require some patches against each of the microservice pods, just like:
https://github.com/fche/fabric8-toggles/commit/d8bca43e00b921e93b8ab3869a0476dbcfb29441

Then we need to pick the model for central logging and/or zabbix relay.  If the only data sink is to be zabbix, one needs to pick a schema and metrics, and then one needs no local storage.  (The mattermost monitoring prototype is like this.)   If on the other hand one wants the fuller PCP experience with more local logging and perhaps the webui, then one needs local storage and a few more components.  (That's OSD/OSO OSIO EIEIO.)

**Comment by fche** [comment]
@fridex, could you identify a candidate pod (from bayesian-*) that would benefit most from instrumentation?  Can its copy on .rh-idev. get some workload, so we can identify which resources it may be short of (cpu? memory?).

**Comment by fridex** [comment]
> @fridex, could you identify a candidate pod (from bayesian-*) that would benefit most from instrumentation? Can its copy on .rh-idev. get some workload, so we can identify which resources it may be short of (cpu? memory?).

IMHO all bayesian-worker-{api,ingestion,priority} pods could be really strong candidates here - they all are one [image](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/Dockerfile) (based on [worker-base image](https://github.com/fabric8-analytics/fabric8-analytics-worker-base/blob/master/Dockerfile) that is candidate for placing PCP) deployed with different configuration (env variables), so only a change at one place should be needed.

I think memory will be critical (especially when analysing java/maven). CPU shouldn't have that big impact, but worth to have stats.

**Comment by fche** [comment]
@fridex, from looking at the deployment yamls, they seem to be different images based on the same analytics-worker intermediate.  Since the pcp agent needs to be started with a modified CMD/ENTRYPOINT, we'd probably be just as well editing only those individual -{api,ingestion,priority} Dockerfiles rather than a common base *and* the individual ones.

**Comment by msrb** [comment]
@fche all those deployments actually share the same `registry.devshift.net/bayesian/cucos-worker` image. The base image contains various tools and runtimes that don't change very often. So PCP would fit there perfectly.

We can then modify CMD in the worker image itself.

**Comment by fche** [comment]
Can you point me to the worker image Dockerfiles too pls?

**Comment by msrb** [comment]
There is only one worker image Dockerfile. [Here](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/Dockerfile) you go :)

**Comment by fche** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/444  -- for the individual pod-side collection

**Comment by msrb** [comment]
@fche 

I can see following in worker logs:
```
pmcd: cannot open log "/dev/force-logging-to-stderr" for writing : Permission denied
Log for pmcd on bayesian-worker-ingestion-28-ghctn started Thu Nov 30 14:16:01 2017


active agent dom   pid  in out ver protocol parameters
============ === ===== === === === ======== ==========
pmcd           2                 2 dso i:6  lib=/var/lib/pcp/pmdas/pmcd/pmda_pmcd.so entry=pmcd_init [0x7f7589c54140]
proc           3                 2 dso i:6  lib=/var/lib/pcp/pmdas/proc/pmda_proc.so entry=proc_init [0x7f7589a32e70]
linux         60                 2 dso i:6  lib=/var/lib/pcp/pmdas/linux/pmda_linux.so entry=linux_init [0x7f7589801d70]

Host access list empty: host-based access control turned off
User access list empty: user-based access control turned off
Group access list empty: group-based access control turned off


pmcd: PID = 6, PDU version = 2
pmcd request port(s):
  sts fd   port  family address
  === ==== ===== ====== =======
  ok     5       unix   /var/run/pcp/pmcd.socket
  ok     3 44321 inet   INADDR_ANY
  ok     4 44321 ipv6   INADDR_ANY
```

Should we be worried about the first line?
```
pmcd: cannot open log "/dev/force-logging-to-stderr" for writing : Permission denied
```

**Comment by fche** [comment]
Nope, that's all good.  It's a workaround for this pending issue:
https://github.com/performancecopilot/pcp/issues/365

**Comment by msrb** [comment]
workers with PCP are now running in production.

**Comment by fche** [comment]
OK, now we just need to get the data actually collected (not just made available for collection, which is what the current work does), and sent out someplace.  Is it the case that y'all intend to be in a separate openshift namespace from the rest of osio f8 infrastructure?  Then we'll need a local copy of 'osd-monitor' or similar.

**Comment by fche** [comment]
Now online for .rh-idev. preview: https://osd-monitor-bayesian-preview.b6ff.rh-idev.openshiftapps.com/
Pending (waiting for a serviceaccount) for identical setup for .dsaas. production.
Ping me offline for the required authentication.

**Comment by msrb** [comment]
@fche Thanks Frank, really appreciate the help. I will reach out to you for the auth details.

**Comment by sivaavkd** [comment]
Discussed this with Michal.. PCP is implemented and can be closed.
