### ISSUE TITLE
Description in work item created from Stack Report should reflect the new data points

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#733]
[1] We still see the description highlighting the old data points.

It has to be highlighting usage of alternate and companion components.

In case of companion components, 
Something like: 

Stack analysis has identified some additional components for your application stack. You have chosen to add io.vertx:vertx-codegen with 3.4.2 to your application stack

In case of alternate components,
Something like:

Stack analysis has identified alternate components for io.vertx:vertx-web. You have chosen to replace io.vertx:vertx-web with io.vertx:vertx-web-templ-handlebars and version: 3.4.1 in your application stack

<img width="1678" alt="screen shot 2017-08-31 at 3 01 30 pm" src="https://user-images.githubusercontent.com/7880465/29916929-e8a6ccce-8e5d-11e7-8333-b821e1ce95a6.png">

**Comment by invincibleJai** [comment]
@arunkumars08 fixed it , changes can be seen in prod now. Pls verify
CC @samuzzal-choudhury

**Comment by arunkumars08** [comment]
@invincibleJai It appears as expected.
