### ISSUE TITLE
[13]Unit Tests and Integration Tests for Devstudio

### ISSUE THREAD

**Issue by GeetikaBatra** [openshiftio/openshift.io#734]
- [ ] Unit Tests

- [ ] Integration Tests

**Comment by GeorgeActon** [comment]
@Geetika Can you assign this to yourself since you are working on it.

**Comment by krishnapaparaju** [comment]
Where these integration tests are run ? Would this integration tests cover the Java specific code which runs inside the plugin ?

**Comment by GeetikaBatra** [comment]
Hi Srikrishna, these integration tests would cover java specific code. I don't understand if the tests would run inside plugin.

**Comment by GeorgeActon** [comment]
@GeetikaBatra use the labels provided. Do not add WIP in the title use the status/in-progress label
