### ISSUE TITLE
[1][Done]Categories/Topics not listed for a user stack components

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#735]
When I submit a stack for analysis, topics appear for alternate and companion recommendations, but somehow it does not appear for given input stack components. Previous iterations used to show topics for the same set of pom.xmls.

**Comment by jyasveer** [comment]
We already have the code this. This line should get us the topic_list for the components in user stack.
https://github.com/fabric8-analytics/fabric8-analytics-server/blob/master/bayesian/api_v1.py#L365

However i will check it again and close it

**Comment by miteshvp** [comment]
verified that issue has been fixed.
