### ISSUE TITLE
Add OC to Che cmd interface for usablity & resolve oc firewall issues in workshops

### ISSUE THREAD

**Issue by cctrieloff** [openshiftio/openshift.io#736]
@burr @bradmicklea I watched the workshop yesterday and quite a few people had firewall issues with OC...  would it help if we included OC into the cmd shell of Che, so they could OC from there?  There would be no firewall issues with such an approach.
burr
@cctrieloff yes, it should be in the Che Terminal
ideally the Che Terminal has all the needed tools like mvn, git, java, oc
or if it is a node.js workspace
npm, node, oc, git
Let's raise that as an issue - think that would make a huge improvement in the user experience

**Comment by bmicklea** [comment]
@gorkem and @eivantsov not sure who is the best person to do this but I think it's probably just a matter of adding OC binary to the workspace definition, right?

**Comment by gorkem** [comment]
We need to manage the oc binary version. Also on OSIO we usually set the credentials for CLI tools so that they are ready to use. 

This is something for @l0rd to consider for next sprint.

**Comment by l0rd** [comment]
Linking to an existing issue in our repo https://github.com/redhat-developer/rh-che/issues/292. I've updated that one to `severity/P1`.

**Comment by ibuziuk** [comment]
https://github.com/redhat-developer/rh-che/issues/292 is done and now all pre-defined stacks include latest version of oc. Could we close this one now ?

**Comment by bmicklea** [comment]
I think so but see @gorkem's comment in [292](https://github.com/redhat-developer/rh-che/issues/292#issuecomment-329021580).
