### ISSUE TITLE
Logging into OSIO from pages other than landing page, lands the user at home page post login

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#737]
1) While the user is logged out and visits a URL in OSIO, say https://openshift.io/openshiftio/openshiftio/plan

2) Now to log into the system, he clicks the login button on the top right corner

3) Provides the OSIO credentials and login

4) The user post login, ends up at the Home page: https://openshift.io/_home. The context to the URL he started with in step#1 is lost

There must be a mechanism to redirect the user back to the page where he started.

**Comment by alexeykazakov** [comment]
Login API supports "redirect" param which should be used to redirect back to original page.

**Comment by alexeykazakov** [comment]
Removed team/auth because it's actually matter of using redirect_url param properly in UI when login user.

**Comment by aptmac** [comment]
This appears to be fixed; if I visit a page like https://openshift.io/openshiftio/openshiftio while logged out and then log in, I am sent to https://openshift.io/openshiftio/openshiftio (and not the home page).

**Comment by alexeykazakov** [comment]
Yes. There were some bugs in UI which prevented correct redirection after login but they should be fixed by now. Closing.
