### ISSUE TITLE
Revamping the UI design in the portal to the latest UX

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#743]
### Acceptance Criteria

- [x] Change the design for stack level information
- [x] Change the design for component level information [User components]
- [x] Change the design for component level information [Companion components]
- [x] Change the design for component level information [Alternate components]

User Story
https://github.com/openshiftio/openshift.io/issues/702

**Comment by joshuawilson** [comment]
This looks more like a user story to me that has 4 tasks/issues listed that should be the work.

**Comment by krishnapaparaju** [comment]
@arunkumars08 what are the current open items in this task of improving UX ?

**Comment by arunkumars08** [comment]
@samuzzal-choudhury This issue can be closed if verified once.

**Comment by arunkumars08** [comment]
Closing as the tasks are complete.
