### ISSUE TITLE
Update SoS reports to include Analytics specific data requirements 

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#745]
SoS reports provide diagnostic information for a combination packages (application stack). 

To start using SoS reports as key data sources to measure (at OSIO analytics platform) health of an application stack, need to close in these two work items:

  
- [ ] Understand the current structure / data variables, supported application runtime versions at SoS reports
- [ ]  Document required changes / addition of data variables to SoS reports
- [ ] Implement plugin towards these changes, release process aligning with RHEL's release cycle.

@GeorgeActon @msrb @miteshvp @samuzzal-choudhury

**Comment by jpopelka** [comment]
If we are still interested in SCLs, then somebody should take over https://github.com/sosreport/sos/pull/900 and finish it since Slavek won't do that.

**Comment by msrb** [comment]
Document describing SoS reports in context of f8a: https://docs.google.com/document/d/14n347Ebg5uf5DXFFWTmo-ahDypeMH2o1pS1Bnuyp3R4/edit#heading=h.ri8epctg2w2y

**Comment by miteshvp** [comment]
Not relevant. Closing this.
