### ISSUE TITLE
Display reasoning for Alternative and Companion components

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#748]
### Description
End user should be shown the reason behind alternate and companion components

#### Acceptance Criteria
- Alternate components are recommended with reasoning about the outliers (usage based or license based)
- Companion components are recommended with reasoning about the confidence of co-occurrence with other stack components 

##### Tasks
- [x] https://github.com/openshiftio/openshift.io/issues/984

**Comment by krishnapaparaju** [comment]
Would need to work backwards: Baseline the reason that would be shown on UI before planning the implementation.

@samuzzal-choudhury

**Comment by sara-02** [comment]
@miteshvp This looks like a duplicate of #771

**Comment by miteshvp** [comment]
@sara-02 thanks. I have added the link in the description now.

**Comment by miteshvp** [comment]
@harjinder-hari maybe, you may want to improve the description with more details https://github.com/openshiftio/openshift.io/issues/771

**Comment by krishnapaparaju** [comment]
@miteshvp @saara-02 what are the possible reasons OSIO user get to see for recommended alternative components ?

**Comment by sara-02** [comment]
@krishnapaparaju Alternate recommendation shown if the component is either a PGM outlier or a license outlier.

**Comment by miteshvp** [comment]
Current implementaion recommends an alternate packages if they are usage based outliers or license based outliers. Reasoning is only implemented for Usage based.
