### ISSUE TITLE
Generated project doesn't respect the top level package.

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#750]
During the project creation wizard asks for a "top level package"

![screenshot 2017-09-04 15 04 00](https://user-images.githubusercontent.com/30131/30036536-52da8410-9182-11e7-80d3-3b564bab5003.png)

But the project is created with the package "io.openshift.booster" in the java package.

![screenshot 2017-09-04 14 59 40](https://user-images.githubusercontent.com/30131/30036549-7661f45e-9182-11e7-8dfa-e40ed24b8295.png)

**Comment by jstrachan** [comment]
package is no longer an option in the RHOAR booster addon. For background see openshiftio/appdev-planning#34
