### ISSUE TITLE
Typo in the generated Vert.x project

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#751]
Small typo on line 32 
(starter -> started): System.out.println("Server starter on port " + ar.result().actualPort()); 

should probably be System.out.println("Server started on port " + ar.result().actualPort())

![screenshot 2017-09-04 15 08 09](https://user-images.githubusercontent.com/30131/30036611-ea68b982-9182-11e7-889a-b78bd659e78c.png)

## Impacts
- [ ] #2084 Getting Started Quickly with a Framework - from Wizard, to IDE, to Deployment

**Comment by ALRubinger** [comment]
https://github.com/openshiftio-vertx-boosters/vertx-http-booster/pull/20
https://github.com/openshiftio-vertx-boosters/vertx-http-booster-redhat/pull/5

**Comment by ALRubinger** [comment]
PRs submitted.

Note that the Boosters are owned by the project teams, so in the future the best avenue to request changes is to ask 'em directly. :)  Easy fixes here so we were happy to help direct traffic.

**Comment by joshuawilson** [comment]
@ALRubinger thanks. Can you also post here when they get merged so we can close this.

**Comment by ALRubinger** [comment]
@joshuawilson That doesn't make much sense to me.  If you're filing issues here in openshiftio, I'm guessing you'd want to do your own verification that the fixes were merged, released, and visible through OSIO.  I'd like to avoid babysitting issues and manual cross-tracking.  If only we had a tool to help us do that? :P

**Comment by joshuawilson** [comment]
@ALRubinger They are your PRs right? It's not like I was asking you towatch something external to you. 
 All you have to do is link this issue with those PRs with "fixes" and the URL to this one. Then when they are closed they will notify this one. Since this was raised here, it needs to be verified by the OP or a lead to be closed.

**Comment by ALRubinger** [comment]
@joshuawilson Yep they're my PRs, but merging them into the upstream doesn't mean they're surfaced and available in OSIO was my point.  I can ping back when they're merged and y'all can decide how you want to handle it.

**Comment by joshuawilson** [comment]
Thanks @ALRubinger

**Comment by joshuawilson** [comment]
@ALRubinger were your PR's merged?

**Comment by gastaldi** [comment]
Closing as the version in production already uses the updated booster
