### ISSUE TITLE
PRs not triggering builds

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#752]
For a github project configured for use with OpenShift.io, when I open a PR, a build pipeline does not get triggered https://github.com/sbose78/my-app-test/pull/2

In the Jenkins logs, the last 3 statements are :
```

INFO: Received PushEvent for https://github.com/sbose78/my-app-test from 192.30.252.45 ⇒ https://jenkins-shbose-jenkins.8a09.starter-us-east-2.openshiftapps.com/github-webhook/
--
  | Sep 05, 2017 6:13:07 AM org.jenkinsci.plugins.github_branch_source.PushGHEventSubscriber onEvent
  | INFO: Received PUSH for https://github.com/sbose78/my-app-test from 192.30.252.45 ⇒ https://jenkins-shbose-jenkins.8a09.starter-us-east-2.openshiftapps.com/github-webhook/
  | Sep 05, 2017 6:17:45 AM org.jenkinsci.plugins.github_branch_source.PullRequestGHEventSubscriber onEvent
  | INFO: Received PULL_REQUEST for https://github.com/sbose78/my-app-test from 192.30.252.34 ⇒ https://jenkins-shbose-jenkins.8a09.starter-us-east-2.openshiftapps.com/github-webhook/

```

CC: @rawlingsj @jstrachan 

The webhook status in Github has a 200OK for the PR specific call to the jenkins webhooks url.

```
Request URL: https://jenkins-shbose-jenkins.8a09.starter-us-east-2.openshiftapps.com/github-webhook/
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/aff25de
X-GitHub-Delivery: eec303f0-9201-11e7-930b-efdcff46c18b
X-GitHub-Event: pull_request
X-Hub-Signature: sha1=b3e919b0623f0bd0e545b41e4d0cb294bb1e8d08
```

It seems as if the jenkins job is not configured to react to PRs.

**Comment by rawlingsj** [comment]
Was this on a clean environment?  I wonder if something else is affecting this as we use the same Jenkins image and plugins for our own PRs now which works great.  If this was a clean environment I'll take a look at some point today.

**Comment by rupalibehera** [comment]
Yeah @rawlingsj, I am also not sure why it is not triggering with the default settings, but i think so as we have set  "Filter by name (with wildcards)"  to "master" it is not checking for other branches and PR's too, when I changed it to "*" it triggered a build for my PR and for the new branch too. May we need to modify in configmap

**Comment by rawlingsj** [comment]
Ah actually I had that last night! I set it to `master|PR.*`

**Comment by rawlingsj** [comment]
@jstrachan is the default config.xml in the backend forge repo?

**Comment by rupalibehera** [comment]
Yeah I was looking for that file.

**Comment by rawlingsj** [comment]
@rupalibehera this looks like it https://github.com/fabric8io/fabric8-generator/blob/master/src/main/resources/io/fabric8/forge/generator/kubernetes/github-org-job-config.xml#L37

**Comment by sbose78** [comment]
Tested the fix, works - but here's the process..

This change impacts the https://jenkins-shbose-jenkins.8a09.starter-us-east-2.openshiftapps.com/job/sbose78/config.xml file which doesn't get updated when on doing an `update tenant` 

( apart from going into the pod and making the fix as per https://github.com/fabric8io/fabric8-generator/commit/203b7cd95c5fd2a0b7fab077af9c0c56968aef0c ) 

To get this fix, I needed to do a "reset environment" so that the https://jenkins-shbose-jenkins.8a09.starter-us-east-2.openshiftapps.com/job/sbose78/config.xml  gets recreated when I create my first space after that.

**Comment by sbose78** [comment]
When I update the PR by updating the changed file, a new build does not get triggered. https://github.com/openshiftio/openshift.io/issues/762
