### ISSUE TITLE
[3]Task: Read manifest file from github url.

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#753]
Until now we are only able to trigger the stack analyses by providing the required manifest files and corresponding path to the manifest file. 
What about the projects available in github ? 
This task aims at reading the project from github and parse the manifest files and fetch the corresponding paths, then trigger a stack analyses. So after this task is completed we would just require a github url to trigger a stack analyses.
here is the PR https://github.com/fabric8-analytics/fabric8-analytics-server/pull/115

**Comment by krishnapaparaju** [comment]
There is no description mentioned. Please update the task.

@GeorgeActon @samuzzal-choudhury

**Comment by GeorgeActon** [comment]
@jyasveer add a desription and link to the higher level story as requested by Srikrishna

**Comment by jyasveer** [comment]
Implemented
