### ISSUE TITLE
Error message is displayed for users, who do not belong to a github org, when creating a new project

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#756]
The error is not displayed for users that belong to an org:

![screenshot 2017-09-05 10 58 37](https://user-images.githubusercontent.com/642621/30069446-c4fa7e40-922e-11e7-9adc-7ba3a252633b.png)

**Comment by ldimaggi** [comment]
Thanks to Corinne for finding this!

**Comment by corinnekrych** [comment]
fixed in https://github.com/openshiftio/openshift.io/issues/966
