### ISSUE TITLE
Inconsistent naming of quickstarts

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#757]
Small point - but Vertx should be Vert.x:

![screenshot from 2017-09-05 14-05-07](https://user-images.githubusercontent.com/642621/30075714-a358e536-9244-11e7-8d6a-c6936f1b683c.png)

**Comment by joshuawilson** [comment]
Is this still an issue?

**Comment by ldimaggi** [comment]
One of those quickstarts has been removed - let's close this one.
