### ISSUE TITLE
Quickstart    Secured Vert.x - Rest & Red Hat SSO - fails to build

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#758]
Build log is attached. 

Error is:
ERROR: Error during kubernetes apply: hudson.AbortException: No resources passed into the step using the 'file' argument or found in the default target folder generated by the fabric8-maven-plugin

**Comment by ldimaggi** [comment]
[build_log.txt](https://github.com/openshiftio/openshift.io/files/1278723/build_log.txt)

**Comment by rawlingsj** [comment]
The pipeline fails to find the openshift template yaml under the parent`./target` dir.  Looking at the project that was generated https://github.com/ldimaggi/setpember5a the fabric8-maven-plugin generated yaml is under the app folder `app/target/classes/template.yml`.  Has this worked previously?  Is the directory structure as expected?  

For this to work either the booster needs to change to generate yaml in the parent `./target` folder or it somehow needs to tell the pipeline which folder (in this case "app") contains the `target/classes/template.yml` used to apply.

**Comment by ldimaggi** [comment]
Failing quickstarts have been removed.
