### ISSUE TITLE
WildFly Swarm map related quickstarts failing

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#759]
These new quickstarts are failing:
* HTTP CRUD - Wildfly Swarm
* WildFly Swarm - Circuit Breaker
* WildFly Swarm - Config Map
* WildFly Swarm - HTTP
* WildFly Swarm - Health Checks
* WildFly Swarm - REST and RH SSO

In the Swarm case, the pod won't even start, in Vert.x and Spring Boot case, the pod starts just fine, but the application doesn't work correctly, because the configmap isn't created -- the boosters expect that it is created upfront.

These quickstarts are expected to fail until this PR is merged:
https://github.com/fabric8io/fabric8-team-components/pull/122

**Comment by rawlingsj** [comment]
We were chatting on MM and think we now have the full booster catalogue rather than the cut down OSIO branch.
@aslakknutsen @jstrachan does that sound about right?

**Comment by Ladicek** [comment]
https://github.com/fabric8io/fabric8-team-components/pull/122 isn't related to ConfigMap boosters, but rather to all Swarm boosters.

**Comment by rawlingsj** [comment]
Interestingly the OSIO branch does include the vertx and springboot configmap boosters https://github.com/openshiftio/booster-catalog/tree/osio/configmap - I wonder if this is right?

**Comment by Ladicek** [comment]
I think the branch includes them because it's not immediately obvious they're failing -- they start just fine, but the application behavior is wrong.

**Comment by ldimaggi** [comment]
The failing quickstarts have been removed.
