### ISSUE TITLE
Node.js - CRUD Example - quickstart fails - missing pom.xml file

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#761]
Building this quickstart fails in OSIO - build error is:

```
[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.2:set (default-cli): Goal requires a project to execute but there is no POM in this directory (/home/jenkins/workspace/estsep61504702243331_master-3UCHJHXDNTS2Z3CYXMRNNDIIVQQG3N2PDHDNRMBP7YYMLN6HF4ZA). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
```

And - yes - the pom.xml file is missing:

![screenshot from 2017-09-06 09-00-17](https://user-images.githubusercontent.com/642621/30113344-6d0a622c-92e2-11e7-916f-e9cde59f6477.png)

**Comment by Ladicek** [comment]
Well it's Node.js, no `pom.xml` is expected. Why is it even trying to run Maven?

**Comment by ldimaggi** [comment]
Same issue is also seen for this quickstart:
Node.js - HTTP

**Comment by ldimaggi** [comment]
OSIO expects it.

**Comment by rawlingsj** [comment]
Right now OSIO only supports Java, this sounds like the same issue where we're using the full booster catalogue rather than our cut down version.

**Comment by Ladicek** [comment]
So I see the Fabric8 Jenkinsfile library also contains the pipelines for Node.js, so maybe it's just a matter of copying the corrent Jenkinsfile? (I realize I'm very likely oversimplifying here...)

**Comment by rawlingsj** [comment]
It's not right now no.  The pipeline library makes use of the docker socket for non java builds on openshift.  So this wont work on OSIO right now.

**Comment by jstrachan** [comment]
the boosters that don't work on OSIO have now been removed
