### ISSUE TITLE
Quickstarts unexpectedly added to OSIO app generation wizard

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#764]
The following quickstarts are now available in the OSIO 'add to space' wizard - the quickstarts marked in bold were present before September 5. 

Is this addition of the other quickstarts intentional? Several of the new quickstarts are experiencing build failures:
https://github.com/openshiftio/openshift.io/issues/761
https://github.com/openshiftio/openshift.io/issues/759

**Vert.x HTTP Booster***
Secured Vertx - Rest & Red Hat SSO
**Vert.x - HTTP & Config Map***
Vert.x CRUD Example using JBDC
**Vert.x Health Check Example***
Node.js - CRUD Example
Noce.js - HTTP
Node.js - Health Checks
Secured Spring Boot Tomcat - HTTP & Red Hat SSO
Spring Boot - CRUD
Spring Boot - ConfigMap
**Spring Boot - HTTP***
Spring Boot Circuit Breaker Example
**Spring Boot Health Check Example***
HTTP CRUD - Wildfly Swarm
Wildfly Swarm - Circuit Breaker
Wildfly Swarm - Config Map
Wildfly Swarm - HTTP
Wildfly Swarm - Health Checks
Wildfly Swarm - REST and RH SSO

**Comment by corinnekrych** [comment]
@ldimaggi this is the work @jstrachan has been doing reusing launchpad booster catalog.
Ongoing work is to step-up automated testing for booster.
@jstrachan if the build of the some quickstarts fails, are they going to be filtered from the list?

**Comment by jstrachan** [comment]
I'm just releasing a fix that brings back the old filters if there's no custom booster catalog / git ref being used

**Comment by jstrachan** [comment]
@corinnekrych right now its gonna be a manual process to curate the filtering; but the aim is to use CI / CD to enable/disable boosters using the E2E Tests - its gonna take a little while to get there mind you ;)

**Comment by ldimaggi** [comment]
Question on:
'...the aim is to use CI / CD to enable/disable boosters using the E2E Tests...'

Are planning on dynamically altering the list of available quickstarts/boosters based on whether or not the quickstarts are failing at any point in time?

**Comment by jstrachan** [comment]
Yeah. I don't think its gonna be too 'dynamic' really; its more a case of more boosters will appear as they are ready & any that start failing after being added will get removed (with issues raised against the developers so we can hopefully get them back again ASAP) - so that at any time only working boosters are shown in the list

**Comment by jstrachan** [comment]
fixed in prod
