### ISSUE TITLE
Update Analytics Functionality

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#767]
Update the analytics functionality of the marketing page.
The proper utilities must be utilized, as well as fixes need to be made to various libraries.

**Comment by qodfathr** [comment]
@mindreeper2420  @joshuawilson wasn't this related to the fact when we were going to expose an analytics form of some sort that an anonymous user could use without even logging into OSIO? Is that even still part of the plan? I think this may be a dead issue?

**Comment by mindreeper2420** [comment]
@qodfathr I believe that was pulled out of the overall plan and that this is indeed a dead issue.
