### ISSUE TITLE
Analytics - Report window is not automatically refreshed after report is processed

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#769]
Saw this today - while a report is being processed an "in progress" message is displayed:

![screenshot 24](https://user-images.githubusercontent.com/642621/30130783-5f99798a-9318-11e7-891a-f93cb1593d61.png)

But - the screen is not automatically refreshed when the report was completed. A manual browser refresh/reload resulted in the reporting being displayed:

![screenshot 25](https://user-images.githubusercontent.com/642621/30130832-8234627a-9318-11e7-9ff6-312b526f93b2.png)

**Comment by joshuawilson** [comment]
Has this been fixed?

**Comment by ldimaggi** [comment]
Closing - I have not seen this issue recently.
