### ISSUE TITLE
Display reasoning for Alternate/Companion components recommendations

### ISSUE THREAD

**Issue by harjinder-hari** [openshiftio/openshift.io#771]
Identify and prepare reason(s) that will help user clearly understand why an alternate/companion component was recommended by the system.

For example, if a component C1 makes the overall stack license more restrictive i.e. C1 is a license based outlier and if there is a similar and popular component C2 then system is expected to recommend C2. Here, the system should also generate a reason statement like "_C2 can make the stack license less restrictive_"

**Comment by joshuawilson** [comment]
@harjinder-hari I'm not sure this is really a user story. Looks more like an enhancement.

**Comment by sara-02** [comment]
@miteshvp @harjinder-hari This looks like a duplicate of #748
