### ISSUE TITLE
Extend support for collecting GitHub manifest files

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#772]
Note this is just for tracking purposes, this work was not officially planned for this sprint, but it popped up during the sprint and it is high priority (related to tagging).

# Description
The old "collect manifest files from most starred GH repositories" job doesn't satisfy our needs any more. We want to be able to collect and process manifest files from GH repositories denoted by "random" query.

# Acceptance criteria
- [x] It's possible to collect and process manifest files for arbitrary list of GitHub repositories
- [x] `manifest.json` file containing list of packages extracted from the manifest files can be generated and stored in given location in S3
- [x] the code runs in production

**Comment by msrb** [comment]
PR: https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/159

Merged.

**Comment by msrb** [comment]
The code runs in production now.

**Comment by joshuawilson** [comment]
moved to the main Sprint 137 milestone

**Comment by krishnapaparaju** [comment]
Please document steps to follow for retrieving manifest files from GitHub

@msrb @SaketJNU

**Comment by msrb** [comment]
@krishnapaparaju @SaketJNU I will add some docs 😉

**Comment by krishnapaparaju** [comment]
@SaketJNU can you please add docs. covering the scripts that are being used to retrieve manifest files from GitHub
