### ISSUE TITLE
Better Management of Deployments

### ISSUE THREAD

**Issue by cctrieloff** [openshiftio/openshift.io#773]
Watching the workshops, Burr creates 3 services, seeing what is going on is not optimal. By making 3 changes to the Applications tab we can improve the usability of the system.

A.) Add for each Service Deployed the requested limits from the YAML (extra points, add a link to the file in GitHub for easy future editing that opens it in Che :-)
B.) Add for each environment the limits for that env read from OpenShift, and then display how much has been used. i.e. Burr Packs 3 services into each env.  Knowing if it is working is tough for the user to debug. Adding (A & B) makes this simple (i.e. what do I have, what is being requested)
C.) rename the tab from Applications to Deployments.

![app1](https://user-images.githubusercontent.com/13753654/30167199-a15bae56-93b3-11e7-8286-eb191733f271.png)

**Comment by cctrieloff** [comment]
@catrobson here are the 3 comments I made to you yesterday for better workshop usability.

Carl.

**Comment by cctrieloff** [comment]
jfchevrette
12:19 PM
  1

oc get quota -n namespace -o yaml will give you limits and usage for all 3 quota types (compute-resources, compute-resources-timebound and object-counts)

**Comment by qodfathr** [comment]
Given the new design for Deployments, would you be willing to close this @cctrieloff ?

**Comment by stevengutz** [comment]
Are we closing this?

**Comment by joshuawilson** [comment]
We do have other issues that talk to some of this but it is not implemented yet. I'll leave it to @cctrieloff if he wants to close it.

**Comment by joshuawilson** [comment]
The work appears done. Closing.
