### ISSUE TITLE
Missing blue balls in the Forge Wizard

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#774]
Steps 1 and 2 (missing 3 and 4)
https://www.evernote.com/l/AQc4i2FPOIBBY7I1TBmC8zAbIHF1ETFjqGU

but 3 and 4 show up a wee bit later in the process
https://www.evernote.com/l/AQcVSoDBAGxGiar8lS01wiRbWvRhKajbbLE

**Comment by corinnekrych** [comment]
fixed in https://github.com/openshiftio/openshift.io/issues/966
