### ISSUE TITLE
Different application name under "Applications"

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#775]
My application is called "myvertxhello" as you can see in the Pipelines tab

![screenshot 2017-09-07 19 23 57](https://user-images.githubusercontent.com/30131/30189488-1c57446e-9402-11e7-8550-63abadad3efd.png)

But under applications tab it shows as "booster-rest-http-vertx"

![screenshot 2017-09-07 19 24 47](https://user-images.githubusercontent.com/30131/30189497-3989c28c-9402-11e7-8402-ea1489648f1d.png)

**Comment by jstrachan** [comment]
fixed - the app name is now stored as the pom.xml `artifactId` so that the `Deployment(Config), RS/RC & Pods` use the same name prefix
