### ISSUE TITLE
Applications tab should show rollout information

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#776]
When I hit the approve button in the pipeline and I go to the applications tab it already shows the version 1.0.2

![screenshot 2017-09-07 19 37 59](https://user-images.githubusercontent.com/30131/30189796-2ebcb560-9404-11e7-83fb-b3653214c972.png)

But that information is wrong while the rolling update is happening. I click on the 1.0.2 link and I see the version 1.0.1 because the rollout didn't complete.

![screenshot 2017-09-07 19 37 53](https://user-images.githubusercontent.com/30131/30189808-436b7a14-9404-11e7-8d3c-9c3795310703.png)

The applications tab should show the rollout happening or just change to 1.0.2 when the rollout completes

**Comment by qodfathr** [comment]
The Applications screen has been replaced by the Deployments screen. The design for the Deployments screen addresses this capability.
