### ISSUE TITLE
p-meier is the creator of my github repository

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#777]
p-meier is now the creator of my github repository, it should be the actual end-user, not "p-meier".
https://screencast.com/t/6JL3GHSm1fz

**Comment by aslakknutsen** [comment]
The commit seems to have this info on it:

git@github.com:burrzinga/thenewapi.git
```
Author: burrzinga <private@github.com>
Date:   Fri Sep 8 00:40:48 2017 +0000
```

**Comment by aslakknutsen** [comment]
A little bit confused to why GH would think that is p-meier.

**Comment by alexeykazakov** [comment]
Probably bc the commit uses <private@github.com> instead of the actual user name?

**Comment by aslakknutsen** [comment]
I assume GH is returning private@github.com in API when email is masked, but if I remember correctly @burrsutter account does not have a private email... But even then, not sure about the link to the p-meier account. It's possible that p-meier has registered private@github.com as an email on his account but...

I doubt GH has started masking email addressed in the raw git repo as that would change the SHA's.

**Comment by alexeykazakov** [comment]
This is what I see in my repo:
```
commit 649c5dd481f2338a34a748da8193df4395ef6421
Author: alexeykazakov-osio <xyz@gmail.com>
Date:   Fri Sep 29 04:14:33 2017 +0000

    Some change

commit 2213c437aa9304733a933b0f0fdc5e8ad0eaf38c
Author: alexeykazakov-osio <private@github.com>
Date:   Fri Sep 29 04:06:34 2017 +0000
```
I replaced my real @gmail.com email by xyz@gmail.com above ^. Which is the only and public email I have in my account.
Here is the repo - https://github.com/alexeykazakov-osio/mysuperspace/commits/master

**Comment by aslakknutsen** [comment]
@alexeykazakov I think I missed the point of the xyz@gmail.com part...

**Comment by alexeykazakov** [comment]
@aslakknutsen Just didn't want to expose my real email in the comment above so I edited the original output and replaced the realm email by xyz@gmail.com

**Comment by joshuawilson** [comment]
So how do we fix this?

**Comment by alexeykazakov** [comment]
1. We should use the user's public email in the initial commit instead of private@github.com
2. If user doesn't have any public email then create the initial commit using some osio email (bot@openshift.io ?) We could register a user with such email so it renders nicely in GitHub UI.

**Comment by joshuawilson** [comment]
would this be fixed in the registration process? github connection point? app wizard?

**Comment by alexeykazakov** [comment]
The first commit is created by forge generator I think?

**Comment by joshuawilson** [comment]
@jstrachan do you have any insight on this?

**Comment by alexeykazakov** [comment]
https://github.com/fabric8io/fabric8-generator/blob/master/src/main/java/io/fabric8/forge/generator/github/GitHubFacade.java#L241

**Comment by alexeykazakov** [comment]
How it looks now:
![openshift-io](https://user-images.githubusercontent.com/620087/31961362-5d5b96a0-b8af-11e7-8fc9-ef1d37862284.png)

But we still need to fix forge generator to use https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GHMyself.java#L69 getEmails2() to load user's emails properly from GitHub.
See https://github.com/fabric8io/fabric8-generator/pull/75#issuecomment-339038356

**Comment by joshuawilson** [comment]
Is this fixed?

**Comment by alexeykazakov** [comment]
openshift-io user is now the creator of the repo. But it’s rather a workaround. The proper solution should be a fix in the app wizard (forge) which should properly load the GitHub user email and use it to create the first commit.

**Comment by joshuawilson** [comment]
@gastaldi can you add this to your list of things to do?

**Comment by gastaldi** [comment]
I can have a look, unless one of the openshiftio addon maintainers does it first (/cc @jrawlings @jstrachan).

In launchpad-missioncontol (which is used in fabric8-launch but not in the openshiftio addon - wait until our unified codebase efforts are done), we use openshiftio-launchpad as the initial commit user: https://github.com/fabric8-launch/launchpad-missioncontrol/blob/master/services/github-service-impl/src/main/java/io/openshift/appdev/missioncontrol/service/github/impl/kohsuke/KohsukeGitHubServiceImpl.java#L220

**Comment by alexeykazakov** [comment]
Removed team/auth because it's not an Auth related issue.

**Comment by qodfathr** [comment]
I'll recommend that the current solution is good enough to close this issue, but we should open a new issue to address this the "right way" per @alexeykazakov (unless that's already been done, of course...)

**Comment by gastaldi** [comment]
Closing. Reopen if the problem persists
