### ISSUE TITLE
Work Item has assigned values different for each context view

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#779]
I have created a new workitem. If I open it in the Backlog tab it shows as Unassigned.

![screenshot 2017-09-07 20 55 21](https://user-images.githubusercontent.com/30131/30191450-e330a4ac-940e-11e7-8a65-0f89b3b5a89a.png)

In the Board tab it still as new. But when I open it, it shows as "In progress" and already assigned to myself.

![screenshot 2017-09-07 20 57 10](https://user-images.githubusercontent.com/30131/30191513-23b77d0c-940f-11e7-8f5c-e8299c4e40c2.png)

It can be related to #778

**Comment by joshuawilson** [comment]
cc @michaelkleinhenz

**Comment by rafabene** [comment]
Note that the title is also different (Camel case)

**Comment by nimishamukherjee** [comment]
@rafabene can you confirm if you still face this issue as we were not able to replicate this issue. 
We only noticed a difference in the work item ID

**Comment by rafabene** [comment]
I'm not able to replicate the issue anymore. Closing...
