### ISSUE TITLE
Detail View: Work Item fields stay in loading state after editing the title

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#783]
When editing the title of a work item from the WI details screen, the stay in loading mode.

## Steps to reproduce
1- Create a new WI
2- From the WI detail screen, edit the title and save

Current output: WI type + Area + Iteration are showing 
Expected output: As those fields have not been edited, they should not need to be reloaded.

See the attached gif:
![editing-wi-details](https://user-images.githubusercontent.com/1636769/30204121-96adf294-9484-11e7-9c76-ecd456da18c3.gif)

**Comment by joshuawilson** [comment]
cc @michaelkleinhenz

**Comment by nimishamukherjee** [comment]
This issue has been fixed. @slemeur please check.

**Comment by michaelkleinhenz** [comment]
Fixed.
