### ISSUE TITLE
Improvements in WI details screen

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#785]
# Goals
This issue is listing improvements in order to provide a more usable work item "detail" view. 
The issue is splitted into two sections:
- Quick fixes: things that are rather small and should be easy to fix
- Layout Improvements: making the layout more readable and easier to process for an end-user

# Quick Fixes

### Inconsistent edition modes
![screen_shot_2017-09-08_at_11_21_53](https://user-images.githubusercontent.com/1636769/30206227-b5be6dce-948b-11e7-9e1a-abf59945f641.png)

We have many different ways to let the user confirming the edition of fields. We need to make those consistent.
- cancel on the left in default color
- confirm on the right in primary color

### Edition should not require to click on the "pen" icon
When the user wants to edit a field, he needs to go on the "pen" icon. The interaction on this is not really easy to understand - especially because this "pen" is shown only while the field is hovered and the mouse cursor is moving to the edition one. 
To make it more logical, when the field is hovered, a click on it should provide the ability to edit the field

![screen shot 2017-09-08 at 12 19 14](https://user-images.githubusercontent.com/1636769/30207509-10ab3240-9490-11e7-90d3-82b6214135c6.png)

### Confirming the edition should be done when clicking outside of the fields
When the user completed his edits, he is likely going to click outside of the field. This action (clicking outside of the field) should also confirm the edits.

### Confirming the edition should be possible with the keyboard
When the user completed his edits and he keeps his hands on his keyboard, he should be able to confirm the edits he just did without using the mouse. 

We should allow the edition mode from a single click on the textfield.

### Escaping the edition mode should be possible from "esc" on the keyboard
It should be possible for the user to escape and cancel the edition mode on a textfield by using "esc" on the keyboard.

### Edition should be possible only on a single field
It should not be possible to edits all the fields at the same. When we allow that, there are many chances that the user will forgot to confirm the edition on one field. 

Let's prevent that - and allow only the edition of a single field at a time. 

### Placeholder in markdown textarea is inconsistent
The placeholder in the markdown area is inconsistent. It should just use the default font, but in gray. 
![screen shot 2017-09-08 at 12 21 22](https://user-images.githubusercontent.com/1636769/30207601-5b9b3bc4-9490-11e7-87fe-6a4908b6b8db.png)

# Layout Improvements

We need to adjust the layout so the information are easier to process and the user is able to understand the issue in less than 5s.

Here is a proposal, but UX team should provide better requirements:
![wi-details](https://user-images.githubusercontent.com/1636769/30220809-3b307170-94c1-11e7-8a7b-f311d6801d06.png)

**Comment by joshuawilson** [comment]
cc: @michaelkleinhenz @catrobson

**Comment by catrobson** [comment]
@slemeur - we actually had a consistent edit and save model specified quite a while ago here:  https://redhat.invisionapp.com/share/UAACVQ7XT#/217944720_Save-Edit_-_001
Save button should only be enabled when valid field input has been achieved.  Using primary button (blue) in this situation is probably overkill since the user's focus is already on the field since they chose to edit it.  The save should also go first, before the cancel.  Agree this needs to be applied consistently.

+1 on all other comments

**Comment by catrobson** [comment]
@mganesan @smahil

**Comment by michaelkleinhenz** [comment]
Created individual issues: #964 and #963

**Comment by zhutaoredhat** [comment]
Hi @slemeur  @joshuawilson  @michaelkleinhenz @catrobson I had ever posted a blog about "inline edit" on PatternFly.
https://blog.patternfly.org/inline-edit-on-forms-conceptual-design/ and here is a demo about it patternfly/patternfly#671. 
Now I am working on the task Design: Inline field editing #663. Welcome your feedback~
