### ISSUE TITLE
Analytic report title looks like a placeholder

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#787]
The title for the detailed analytical report is:  "Report title on Application" - this looks like a generic  placeholder:

![screen shot 2017-09-07 at 3 48 10 pm](https://user-images.githubusercontent.com/642621/30255483-38512faa-9672-11e7-81be-f9adab2e9cc0.png)

**Comment by invincibleJai** [comment]
@arunkumars08 FYI

**Comment by invincibleJai** [comment]
@ldimaggi have changed the place holder now it's "Stack report for vertx-basic-nov-28-3, Build #1", it's in prod now.

**Comment by ldimaggi** [comment]
Verified - closing - thanks!
