### ISSUE TITLE
Improvements in WI list screen

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#789]
# Goals
This issue is listing few improvements and tweaks that we should do in order to cleanup the list of WI. 

# Quick Fixes

## Positions, sizes and alignements

<img width="1088" alt="screen_shot_2017-09-11_at_10_13_26" src="https://user-images.githubusercontent.com/1636769/30265663-1659d42c-96dd-11e7-8a34-d1ee43002e44.png">
- [ ] Add more padding between the `>` arrow and the WI's status
- [ ] Fix the vertical alignement for the icons revealed on hover

![screen_shot_2017-09-11_at_10_38_08](https://user-images.githubusercontent.com/1636769/30267195-0d6dadfc-96e2-11e7-9a2f-a3401177863e.png)
- [ ] Fix the avatar placeholder to be the same size than a valid avatar

## Others

![screen shot 2017-09-11 at 11 13 41](https://user-images.githubusercontent.com/1636769/30267281-4ce7b28e-96e2-11e7-96a3-957ae3859250.png)
- [ ] The icons used for "display in full screen" or "display quick preview" are difficult to understand. 
- [ ] Add tooltip for WI status
- [ ] Add tooltip for WI type
- [ ] Add tooltip for "display full screen" 
- [ ] Add tooltip for "display quick preview" 

It is really hard to visually process the list of WI. As a quick fix, maybe we could:
- add a light line separator between each WI
- reduce the WI row's height

**Comment by joshuawilson** [comment]
cc @michaelkleinhenz @catrobson

**Comment by michaelkleinhenz** [comment]
Issues copied to #325
