### ISSUE TITLE
Improvements in WI quick preview

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#790]
# Goals
This issue is listing improvements in order to provide a more usable work item "detail" view. 
The issue is splitted into two sections:
- Quick fixes: things that are rather small and should be easy to fix
- Layout Improvements: making the layout more readable and easier to process for an end-user

# Quick Fixes
We should apply the same treatments than those defined in the following issue: https://github.com/openshiftio/openshift.io/issues/785

# Layout improvements
We need to adjust the layout so the information are easier to process and the user is able to understand the issue in less than 5s.

For that we need to apply the same treatments than those identified in https://github.com/openshiftio/openshift.io/issues/785

### Display the complete issue description 
As a user, the description of the WI is very important, I should not have to click on a "Show more" link to see the complete description.

### Display the complete WI's title
As a user, I don't want to click anywhere to see the complete title of a WI.
![screen shot 2017-09-11 at 11 54 00](https://user-images.githubusercontent.com/1636769/30269073-0133fd24-96e8-11e7-9136-a0fb3fdcf561.png)

### Markdown components is rendering elements outside of its area
This is a little bug.
![screen shot 2017-09-11 at 11 55 16](https://user-images.githubusercontent.com/1636769/30269182-501fe57e-96e8-11e7-9e3f-698e8a815e7b.png)

### Comments are disappearing once collapse
There is a bug in the layout, when the user is collapsing the comments of the WI. It is not possible to show them again.
![collapse-comments](https://user-images.githubusercontent.com/1636769/30269008-d23d9df4-96e7-11e7-98c8-116a9576f905.gif)

**Comment by joshuawilson** [comment]
cc @michaelkleinhenz @catrobson

**Comment by michaelkleinhenz** [comment]
Created individual issues #962 #961 #960.
