### ISSUE TITLE
[8] Better vulnerabilities data (CVEs) for Python

### ISSUE THREAD

**Issue by jpopelka** [openshiftio/openshift.io#792]
# Description

When implementing security scans for Python, we chose the easiest solution, which was using the same tool, that we'd already been using for Maven packages, i.e. [OWASP Dependency Check](https://www.owasp.org/index.php/OWASP_Dependency_Check).

It has an experimental [Python Analyzer](https://jeremylong.github.io/DependencyCheck/analyzers/python.html) which we currently use.
However the number of false-positives is quite high, see https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/131 for existing fabric8-analytics-worker issue.

We should either fix it or find another source of vulnerabilities data for Python ecosystem.

Other possible candidates:

- [pyup's](https://pyup.io) [safety-db](https://github.com/pyupio/safety-db) for basic info + https://nvd.nist.gov or http://www.cvedetails.com for more CVE details
- scrape all data from http://www.cvedetails.com

# Acceptance criteria
- [x] document describing pros and cons of all evaluated sources is created; it also contains reasoning behind the final decision
- [x] CVE data in S3 are coming from the new source
- [x] code runs in production

**Comment by jpopelka** [comment]
Results of my experiments with www.cvedetails.com and [pyupio/safety-db](https://github.com/pyupio/safety-db) are described in this document: https://docs.google.com/a/redhat.com/document/d/1ScTu7BlGu9nzbSnOPb_eyiKU1ZPwjfMo1xe76YzD8Q4/edit?usp=sharing

**Comment by fridex** [comment]
I missed this card. As posted on ML, candidates: https://github.com/pyupio/safety-db, https://pypi.python.org/pypi/safety

**Comment by jpopelka** [comment]
[Document](https://docs.google.com/document/d/1ScTu7BlGu9nzbSnOPb_eyiKU1ZPwjfMo1xe76YzD8Q4) has been created.
I decided to [fix the issues we are seeing with OWASP Dependency Check](https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/363) rather than using other source of data.  Change has been merged and runs on staging.
I'll mark this as completed once it's pushed to production.
