### ISSUE TITLE
Add quickstart to space, deselecting options activates unnecessary 'Next' key

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#793]
Steps to recreate:
* While adding a quickstart to a space:
![capture1](https://user-images.githubusercontent.com/642621/30291657-94d7b534-9701-11e7-9733-53304dd00d3d.PNG)

* If the user deselects either checkbox, the 'Next' key is activated:
![capture2](https://user-images.githubusercontent.com/642621/30291691-a67b7d84-9701-11e7-944f-e773d42918d7.PNG)

* But, pressing the newly activated 'Next' key only returns the user to the same dialog screen:
![capture3](https://user-images.githubusercontent.com/642621/30291726-ba6d4408-9701-11e7-9c0b-32d808200d27.PNG)

**Comment by corinnekrych** [comment]
fixed in https://github.com/openshiftio/openshift.io/issues/966
