### ISSUE TITLE
Task: CI/CD implementation for the Independent UI Portal

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#796]
Introduce CI/CD for the independent stack ui portal. List of sub tasks that needs to be targeted
- [x] Create a valid Dockerfile that can be used to create a docker image and can be deployed to openshift
- [x] Create a openshift template for the project
- [x] Introduce the cico-* files for the repo
- [x] Update the jenkins job file in almighty-jobs
- [x] Add the configuration in saas-analytics
- [ ] Initiate discussion with the SD team regarding the `URL` to the Stack Report Web Application.
- [x] Add the webhooks in the github

**Comment by jyasveer** [comment]
Facing this error for now. Its blocking me to proceed further. 
When i run `npm install` for this repo https://github.com/fabric8-analytics/fabric8-analytics-stack-report-ui in the local machine, it is working totally fine. However when i try to run the same command in the docker file, i am getting this following error :-
```
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Received 22866K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
  killed: false,
  code: 2,
  signal: null,
```

**Comment by jyasveer** [comment]
Above issue is fixed now

**Comment by jyasveer** [comment]
PRs for this task
- https://github.com/fabric8-analytics/fabric8-analytics-stack-report-ui/pull/14
- https://github.com/fabric8-analytics/fabric8-analytics-stack-report-ui/pull/16
- https://github.com/almighty/almighty-jobs/pull/303
- https://github.com/openshiftio/saas-analytics/pull/97

**Comment by samuzzal-choudhury** [comment]
@jyasveer after a discussion with @GeorgeActon , subtasks are not supposed to be estimated as we have already estimated the user story.

**Comment by jyasveer** [comment]
I am facing a bug where on PR build is not triggering. have raised a bug here :-https://bugs.centos.org/view.php?id=13889
