### ISSUE TITLE
Always redirected back to openshift.io homepage on clicking login

### ISSUE THREAD

**Issue by budhrg** [openshiftio/openshift.io#799]
Hi,

Whenever, I am trying to login to openshift.io account, I am always getting redirected to openshift.io home page.
Here is the process: 
- I click on Login button in https://openshift.io
- Added my deveopers.redhat.com credentials
- See `https://openshift.io/_gettingstarted` with progress bar in progress
- Redirected back to https://openshift.io page after 15+ seconds

#### Screenshots
![screenshot from 2017-09-12 22-21-47](https://user-images.githubusercontent.com/1132451/30338880-bbf7292e-980a-11e7-9899-b2dfc6ddd31d.png)

![screenshot from 2017-09-12 21-53-25](https://user-images.githubusercontent.com/1132451/30338895-cbcf7392-980a-11e7-9966-342a4ca0952d.png)

**Comment by alexeykazakov** [comment]
We investigated it with @budhrg and here is what we found out. Incognito mode didn't help. It was reproducible in other browsers (FF) too.

The backend actually did login properly and returned the tokens. But I noticed some weird /api/user request (see screenshot in the description). This request doesn't have any headers! It looks like something is broken on UI side. Didn't notice any errors in console though.

We workaround this problem by going to https://openshift.io/alkazako then clicking on Login there. This time UI worked well and @budhrg was able to login.

But again. I checked all requests/responses to backend to login and the backend properly logged in. So, doesn't look like a backend issue.

I couldn't reproduce it in my machine when tried to impersonate @budhrg.

**Comment by alexeykazakov** [comment]
@joshuawilson take a look at this please.

**Comment by budhrg** [comment]
Just to add, after logging out, I am still facing same behavior. I need to login by going into link https://openshift.io/bgurung%40redhat.com (my OSIO profile) and login from there.

**Comment by alexeykazakov** [comment]
The network connection was very slow. Just a crazy idea... maybe that UI failed to load something and failed silently?

**Comment by alexeykazakov** [comment]
I did see the same complaints from other users but clearing browser cache usually helped.

**Comment by joshuawilson** [comment]
I have heard of others facing this too.
@dgutride when you have time, can you please take a look at this.

**Comment by rgarg1** [comment]
@budhrg @joshuawilson Same as #737 ?

**Comment by alexeykazakov** [comment]
No, https://github.com/openshiftio/openshift.io/issues/737 is not the same issue. 737 is about redirecting back to the original page after successful login.
And this issue is about not being able to login at all.

**Comment by joshuawilson** [comment]
We just deployed a new Landing Page. Can you please try again and verify.

**Comment by qodfathr** [comment]
Fixed.
