### ISSUE TITLE
Impacting Workshop: Can't start springboot CHE intance

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#801]
It gives me an error: Start of environment 'default' failed. Error: ImageStreamTag che-ws-fq204e6nddbolsuno9d38zfl2tccz3jq not found!

**Comment by ldimaggi** [comment]
![screenshot 40](https://user-images.githubusercontent.com/642621/30343207-928bbfea-97ca-11e7-8822-7a6b537df5db.png)

**Comment by ldimaggi** [comment]
See:  https://github.com/openshiftio/openshift.io/issues/798

**Comment by ibuziuk** [comment]
Duplicate - https://github.com/openshiftio/openshift.io/issues/798
Closing
