### ISSUE TITLE
'Reset Environment' is not clearing Planner WI list, possible caching issue

### ISSUE THREAD

**Issue by RanjithRV** [openshiftio/openshift.io#802]
Reset Environment is not clearing Planner workitems even though the associated space has been cleared. Refreshing the page also does not help. But when I login using incognito mode or if I close the browser and reopen it then the deprecated Planner workitems do not show up anymore. 

![planner-items-after-cleanup](https://user-images.githubusercontent.com/22077715/30358993-6ba67c58-9865-11e7-9a5b-9083460e25fc.png)

**Comment by joshuawilson** [comment]
@RanjithRV does a hard refresh clear it?

**Comment by RanjithRV** [comment]
Didn't try hard refresh, will try it out next time

RANJITH VARAKANTAM

PRINCIPAL AGILE COACH, ICP-ACC, CSP, PMP

Red Hat India Pvt. Ltd. <https://www.redhat.com/>

rvarakan@redhat.com    M: 7032511191
<https://red.ht/sig>

**Comment by michaelkleinhenz** [comment]
Dupe of #778.
