### ISSUE TITLE
Have tooltips for type icons to make it clearer what they represent

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#804]
**Description**
As a user, I want to be able to easily identify the workitem by its type

**Acceptance Criteria**
[] Hovering the mouse over the workitem icon anywhere in planner should show its Type as a tool-tip
[] A context-sensitive help describing the meaning and expected usage of various WI types is provided

**Relationships**
Put linked Team/Product story links here

**Comment by joshuawilson** [comment]
Hover is not Mobile friendly. We should do very little hover.

**Comment by joshuawilson** [comment]
cc @michaelkleinhenz

**Comment by michaelkleinhenz** [comment]
I vote for always having text in addition to the icon. Since the very beginning it was very confusing for me to only have the icon there. I think Konrad did a renegade PR against the recommendations from UX to add the label to the quick preview :-)

**Comment by michaelkleinhenz** [comment]
Fixed in PR#2167.
