### ISSUE TITLE
Extract version information also during a manifest data collect

### ISSUE THREAD

**Issue by SaketJNU** [openshiftio/openshift.io#811]
## Description
The api  mentioned at swagger **/jobs/aggregate-github-manifest-pkgs** is useful to collects the manifest files from github with certain criteria. Currently, it is collecting only package-names not version level information. Version level information is useful to run tagger to collect tags from various other data-sources like readme, description, stackoverflow etc.

### Acceptance Criteria 
Integrated code is running on prod.
### Task
-[ ] update current manifest collector to extract version level information also. 
-[ ] Implement a new function to create a new list of packages with following information so that a tagger related job can automatically be scheduled from list  to extract tags.
```Format: 
 {
"ecosystem": "ecosystem_name",
   "force": true,
   "force_graph_sync": true,
   "name": "package_name",
   "version": "package_version'
   "recursive_limit": 0
 }

**Comment by fridex** [comment]
Could you please elaborate on this? I think this is already done as we call dependency snapshot after retrieving package list - see `dependency_snapshot.json` in prod-bayesian-github-manifest-metadata bucket.

**Comment by SaketJNU** [comment]
Yes, it is there, I am asking abut few line changes in manifest aggregate function so that we can extract version information also during manifest.json creation, so that one more list as per tagger requirement need to stored in S3 bucket. I have identified the place some work has been done and will raise a PR for this. Hopefully that PR will make things more clear.

**Comment by fridex** [comment]
> Hopefully that PR will make things more clear.

OK, will wait.

**Comment by miteshvp** [comment]
@fridex intent here is to collect manifest_lists with Package names which will be an input for PGM. Similarly Saket will also create a list based on your inputs that can be fed to tagger. I hope it clears your doubt.

**Comment by fridex** [comment]
> @fridex intent here is to collect manifest_lists with Package names which will be an input for PGM. Similarly Saket will also create a list based on your inputs that can be fed to tagger. I hope it clears your doubt.

I'm not sure here (I think we are already collecting this list in the stated endpoint), but OK - I will leave this work on you.

**Comment by SaketJNU** [comment]
Created a PR for as an action item.  https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/163

**Comment by SaketJNU** [comment]
Subtask figured out from https://github.com/openshiftio/openshift.io/issues/780 and https://github.com/openshiftio/openshift.io/issues/781

**Comment by SaketJNU** [comment]
The PR has been merged so we can close this issue.
