### ISSUE TITLE
New analytic report treats the entire browser as a model display - scrolls the browser, not the report

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#816]
See attached screenshot - a better presentation would be to scroll within the report.

![screenshot from 2017-09-13 13-51-29](https://user-images.githubusercontent.com/642621/30392666-7bf538b2-988b-11e7-82ad-d7c28f823593.png)

**Comment by muruGanesan** [comment]
I will look at this and fix

**Comment by krishnapaparaju** [comment]
@muruGanesan  @samuzzal-choudhury Is this been fixed ?

**Comment by samuzzal-choudhury** [comment]
@krishnapaparaju AFAIK the UX team is working on a revamped UX which should address all these issues and the UI implementation is dependent on its completion. @muruGanesan please keep me honest on this.

**Comment by joshuawilson** [comment]
@krishnapaparaju is this for sprint 140?

**Comment by krishnapaparaju** [comment]
Yes @joshuawilson ..

**Comment by samuzzal-choudhury** [comment]
A sprint work item #1277 is already in progress for revamping the UX for OSIO stack report. This issue shall be addressed during the implementation.

**Comment by samuzzal-choudhury** [comment]
@joshuawilson I think this issue reports a cosmetic change. Should not we change the severity to SEV 4 instead?

**Comment by invincibleJai** [comment]
@ldimaggi have made the changes in existing stack report as you suggested i.e having scroll within the report and it's in prod now.

**Comment by ldimaggi** [comment]
Verified - closing.

**Comment by jyasveer** [comment]
@ldimaggi @invincibleJai 
I suggest we should remove the scroll within the report instead have the scroll on the browser page. For many reasons:-
1. Our report sits within a modal, and having a scroll within the modal is not recommended as per UX. With this, we find two scrolls now, one within the report and one in the background page. This behaviour is annoying for the user.
2. Second thing is key binding does not work for the modal screen, which compels the user not to use the arrow keys to scroll vertically.
3. This scroll also truncates some of the ui component within the report modal.

In the best interest i am reverting this fix.
