### ISSUE TITLE
Viewing the new analytic report can be disorienting 

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#817]
Viewing the new analytic report can be disorienting as the information in columns and rows "pops up" - see screencast:

https://www.dropbox.com/s/72f3x6wa3s54m7s/report_display.webm?dl=0

Can we add a mode where the information must be explicitly expanded or compressed?

**Comment by joshuawilson** [comment]
This is very hard to look at.

**Comment by muruGanesan** [comment]
I will look at this issue and fix

**Comment by samuzzal-choudhury** [comment]
@ldimaggi  The UX revamp for stack report is in progress and current wireframe can be found here -  https://redhat.invisionapp.com/share/P5E5BDKQ3. We already have an in-progress work item for sprint 140 https://github.com/openshiftio/openshift.io/issues/1277 to work on this new UX and would like to track the progress with that.

Closing this issue as this is a duplicate of https://github.com/openshiftio/openshift.io/issues/1277.
