### ISSUE TITLE
Broken landing page of openshift.io

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#818]
The current state of the landing page on openshift.io is not rendering properly its image.

As a consequence, the layout is broken and user has to scroll (vertically, horizontally) in the page.

See attached gif.
![openshift-homepage](https://user-images.githubusercontent.com/1636769/30421411-f9ee90a4-993c-11e7-90f5-e986fb841e7e.gif)

**Comment by ldimaggi** [comment]
I noticed this yesterday - a hard reload (contro/shift/r) in the browser resolved it. Guessing it was due to the new UI being partially loaded in the browser?

![screenshot from 2017-09-14 07-36-48](https://user-images.githubusercontent.com/642621/30427872-7ed77272-991f-11e7-8ce7-76d782348984.png)

**Comment by joshuawilson** [comment]
This is a cache issue. 
Closing as refresh fixes it.

**Comment by alexeykazakov** [comment]
We really need to address the cache issues. Users hit that all the time.
