### ISSUE TITLE
Users have to hard refresh browser from time to time

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#819]
We really need to address the cache issues. Users hit that pretty often.
The last example - https://github.com/openshiftio/openshift.io/issues/818

**Comment by joshuawilson** [comment]
@mindreeper2420 if you do make any progress in your caching research please post it here.

**Comment by joshuawilson** [comment]
Fixing this should also eliminate the need for incognito mode.

**Comment by joshuawilson** [comment]
@dgutride maybe you could take a look at this.

**Comment by qodfathr** [comment]
FYI, I find that if I leave my browser open on OSIO overnight, I can rarely do anything successfully without a refresh (but need not be a hard refresh; just a regular F5).

**Comment by qodfathr** [comment]
I left my browser window open on OpenShift.io for an extended period of time (several days). When I returned to it, I could not do any basic navigation in the app.

I was sitting on the Account Home page, and noticed output similar to the following in the browser console:
![image](https://user-images.githubusercontent.com/16322190/36113736-d18d89ea-0ffb-11e8-9e05-49c54f862b7d.png)
This is repeating over and over again.

I suspect my token is no longer valid. But OSIO should gracefully handle this condition. 

More details, if helpful:
```

WrappedWebSocket | @ | VM38:164
-- | -- | --
  | $WebSocket.connect | @ | main.dfbd359….bundle.js:1
  | $WebSocket | @ | main.dfbd359….bundle.js:1
  | Watcher.lazyCreateWebSocket | @ | main.dfbd359….bundle.js:1
  | Watcher.recreate | @ | main.dfbd359….bundle.js:1
  | (anonymous) | @ | main.dfbd359….bundle.js:1
  | r | @ | patternfly.min.css:1
  | SafeSubscriber.__tryOrUnsub | @ | patternfly.min.css:1
  | SafeSubscriber.complete | @ | patternfly.min.css:1
  | Subscriber._complete | @ | patternfly.min.css:1
  | Subscriber.complete | @ | patternfly.min.css:1
  | Subject.complete | @ | patternfly.min.css:1
  | $WebSocket.onCloseHandler | @ | main.dfbd359….bundle.js:1
  | e.socket.socket.readyState.readyStateConstants.OPEN.socket.onclose | @ | main.dfbd359….bundle.js:1
  | h | @ | zone.js:1150
  | wrapped | @ | main.dfbd359….bundle.js:1
  | ZoneDelegate.invokeTask | @ | zone.js:414
  | onInvokeTask | @ | patternfly.min.css:1
  | ZoneDelegate.invokeTask | @ | zone.js:411
  | Zone.runTask | @ | zone.js:177
  | ZoneTask.invokeTask | @ | zone.js:484
  | p | @ | zone.js:1524
  | h | @ | zone.js:1542
```

cc: @ldimaggi

**Comment by ldimaggi** [comment]
Todd - are you also seeing return status codes of 200 in the console log?

**Comment by qodfathr** [comment]
@ldimaggi yes, there were all 200s. Which I found to be humorous -- "status code 200 was unexpected!" Oh, so you *expected* it to fail???

**Comment by aslakknutsen** [comment]
@christianvogt this is fixed now?

**Comment by joshuawilson** [comment]
This has been fixed.
