### ISSUE TITLE
After Che workspace fails to start - deployments.extensions already exists

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#820]
Steps to recreate:
* Create a new project, attempt to create a new workspace
* If this error occurs - https://github.com/openshiftio/openshift.io/issues/501

The user is presented with this error message:
```
The Che server is unable to ping your workspace. 
This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
org.eclipse.che.api.core.ServerException: Timeout. The Che server is unable to ping 
your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
```

At this point, if the user attempts to start the workspace from the Che dashboard, this error is raised:

```

2017-09-14 19:43:39,724[aceSharedPool-1]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 539]  - 
Failure executing: POST at: https://kubernetes.default.svc/apis/extensions/v1beta1/namespaces/ldimaggi-osiotest1-che/deployments. 
Message: deployments.extensions "che-ws-isna3mmgsqjvkj08" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=extensions, 
kind=deployments, name=che-ws-isna3mmgsqjvkj08, 
retryAfterSeconds=null, additionalProperties={}), kind=Status, message=deployments.extensions 
"che-ws-isna3mmgsqjvkj08" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
```

**Comment by ldimaggi** [comment]
In order to resolve this problem, the user must delete the workspace through the Che dashboard, and then create a new workspace from the OSIO codespace page.

**Comment by ldimaggi** [comment]
[che_log_sept14.txt](https://github.com/openshiftio/openshift.io/files/1304390/che_log_sept14.txt)

**Comment by ibuziuk** [comment]
Ok, so this issue is a side effect of https://github.com/openshiftio/openshift.io/issues/501, right ?

**Comment by ldimaggi** [comment]
Yes - that is correct!

**Comment by ldimaggi** [comment]
One more instance of this issue:

![screenshot from 2017-09-15 08-38-56](https://user-images.githubusercontent.com/642621/30482875-c37fade4-99f2-11e7-9964-4403d25601fd.png)

[che-2-lzz79_log.txt](https://github.com/openshiftio/openshift.io/files/1306384/che-2-lzz79_log.txt)

**Comment by joshuawilson** [comment]
What is the status on this?

**Comment by l0rd** [comment]
That has been solved by cluster update that happened earlier this week. This issue was related https://github.com/redhat-developer/rh-che/issues/325. @ldimaggi can we close it?

**Comment by l0rd** [comment]
I am closing this issue (c.f. previous comment). @ldimaggi feel free to reopen if you are still able to reproduce.
