### ISSUE TITLE
Landing page causing security warning: overpass.css

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#821]
The following resources are attempted loaded over http on a https site causing them to be blocked with security warning in Chrome:

http://overpass-30e2.kxcdn.com/overpass.css
http://overpass-30e2.kxcdn.com/overpass-mono.css

Loaded from somewhere on: 
https://openshift.io/

**Comment by mindreeper2420** [comment]
I've pushed a PR to fix this. The CDN from Overpass.org is using http, so I've switched it over to use Google Fonts.
