### ISSUE TITLE
Landing page cuts text when scaled

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#822]
![screenshot from 2017-09-15 09-50-38](https://user-images.githubusercontent.com/132158/30473331-5f8bd34a-9a00-11e7-9bc4-d5a68cd1304c.png)

**Comment by joshuawilson** [comment]
@mindreeper2420 do you have time to fix this?

**Comment by mindreeper2420** [comment]
@joshuawilson sure - I'll take a look.

@aslakknutsen what browser+version are you using?
