### ISSUE TITLE
Wizard had an error during Workshop

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#825]
During the workshop the new quickstart wizard gave the following error:

"ExecuteForgeCommandErrorThe forge-quick-start :: next :: 3 command failed or only partially succeededmessageAn issue occurs with Forge backend. Please check the service is running."

**Comment by rafabene** [comment]
This happened with at least two people in the workshop

**Comment by joshuawilson** [comment]
This may be a duplicate or related to #824

**Comment by ibuziuk** [comment]
@joshuawilson could you clarify how the wizard issue is related to che ?

**Comment by joshuawilson** [comment]
@ibuziuk I got confused while in the middle of the workshop and thought this was a different issue. I'll clean it up.

**Comment by ibuziuk** [comment]
@joshuawilson thanks for clarifaications ;-)

**Comment by joshuawilson** [comment]
Closing as this hasn't been seen in a while. 
@rafabene if you see it again, please reopen.
