### ISSUE TITLE
Group ID does not get properly generated into my project

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#826]
Group ID is a prompt in the Forge Wizard, yet making a change to this field does not actually "stick" and show up in the generated codebase.

https://screencast.com/t/uNK6tv3rn

https://screencast.com/t/I0qwY7EE1Jt

Why is this the case?  We are currently copying a pre-defined template and not using a Maven archetype, however, we could "search & replace" the original Maven package name and replace it with the proper maven group id

**Comment by joshuawilson** [comment]
@corinnekrych @jstrachan do you know what is happening here?

**Comment by corinnekrych** [comment]
@burrsutter in step3: have you unchecked `override jenkins/pom file` ?

**Comment by jstrachan** [comment]
I think this could be an issue with the underlying RHOAR forge addon; traditionally fabric8 always used archetypes so you could always specify the group, artifact & version. 

Though I think the RHOAR folks moved away from that and prefer to hard code things. If we can be sure we're passing through the custom groupId + artifact ID and they are being ignored by the RHOAR addon we can raise an issue there https://github.com/openshiftio/launchpad-addon/issues

**Comment by rafabene** [comment]
I've seen this issue before, but as the name states it the GroupId, I'm not sure if we expect that the package name should be changed also.

**Comment by jstrachan** [comment]
I upgraded to the latest launchpad-addon and we now properly default the `artifactId` from the project name and changing the groupId & version do result in `groupId + artifactId + version` being updated in the generated `pom.xml`. 

Fixes now released into prod - @burrsutter could you check its now fixed?
