### ISSUE TITLE
Configure automated error reporting to track issues automatically

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#830]
# Description

Currently all errors are visible in OpenShift logs and subsequently sent to configured ELK stack where they are easily browsable besides info messages to help devs track errors. Catching errors in Kibana is not that straightforward as it requires developer's time to check log for errors and explicitly query for errors that occurred in the cluster. Instead, we could set up monitoring service (like [Sentry](https://sentry.io)) that would help us to automatically aggregate and notify devs about issues that are happened.

If Sentry would be used (this needs to be set up by service delivery team), there is already available documentation that would help [to configure Sentry to work with Flask](https://docs.sentry.io/clients/python/integrations/flask/). For core workers, there need to be made changes in Selinon (https://github.com/selinon/selinon/pull/33 and https://github.com/selinon/selinonlib/pull/18 and new release should be made, contact @fridex).

# Acceptance criteria

- Prerequisite: Service Delivery offers monitoring service (e.g. Sentry)
- [x] errors are automatically aggregated and reported in all Flask based applications and in core workers
- [x] errors are pushed to monitoring service (e.g. Sentry with configured project)
- [ ] errors are browsable and automatically reported to devs with aggregated metadata about issues

**Comment by miteshvp** [comment]
We are already pushing the errors to Sentry. Sentry gives a dashboard view for all the errors.
