### ISSUE TITLE
Server Documentation and Readme corrections.

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#833]
API server documentation currently does not exist in `fabric8-analytics-server`. The related Readme file changes and broken links are to be corrected as well.

Related Issues:
https://github.com/fabric8-analytics/fabric8-analytics-server/issues/20
https://github.com/fabric8-analytics/fabric8-analytics-server/issues/21

**Comment by GeorgeActon** [comment]
@samuzzal-choudhury I set this to a bug SEV3. Please confirm.

**Comment by krishnapaparaju** [comment]
@samuzzal-choudhury can you please work with Preethy and close this issue

**Comment by sunilk747** [comment]
@samuzzal-choudhury If the documentation and readme corrections are done can you please close this issue?

**Comment by sivaavkd** [comment]
@Preeticp - can you please discuss with @samuzzal-choudhury and see if there is something that needs to be done here ?  Lets target to complete this in the current sprint.

**Comment by Preeticp** [comment]
Ack @sivaavkd will coordinate with @samuzzal-choudhury

**Comment by miteshvp** [comment]
@Preeticp @samuzzal-choudhury any updates here?

**Comment by Preeticp** [comment]
WIP here: https://docs.google.com/document/d/1M0EVdcz6kpcvh1LVJ5Spc2LycjYZ0yDp2BWWDD1f-1g/edit?usp=sharing.

**Comment by Preeticp** [comment]
Sounds good to me @samuzzal-choudhury will work on those and close this issue.

**Comment by Preeticp** [comment]
@samuzzal-choudhury please review and merge this PR if it seems alright: https://github.com/fabric8-analytics/fabric8-analytics-server/pull/360

**Comment by Preeticp** [comment]
Fixed via https://github.com/fabric8-analytics/fabric8-analytics-server/pull/360
