### ISSUE TITLE
RFE: FAQ for unit test developers

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#836]
_From @tisnik on June 16, 2017 9:32_

RFE: Create description how to create/update unit test. 

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#28_

**Comment by qodfathr** [comment]
Question on this one: is this asking for a FAQ for *users* of fabric8/OSIO, or is it for *contributors* to fabric8/OSIO?

**Comment by miteshvp** [comment]
We have README's for unit tests now.
