### ISSUE TITLE
RFE: implement some sort of code quality tests (lints)

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#838]
_From @tisnik on June 16, 2017 10:7_

This is part of the overall QA coverage of fabric8 project.

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#30_

**Comment by samuzzal-choudhury** [comment]
_From @fridex on June 18, 2017 15:24_

There was a plan to add some linters such as pylint or coala bears but it never happened. I think it will require quiet large effort as the current code base does not conform to pep standards, but it would increase code quality a lot (as well as PR code quality).

**Comment by miteshvp** [comment]
pylint job runs as part of every PR creation
