### ISSUE TITLE
Expose component analyses on task level

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#839]
_From @fridex on June 21, 2017 13:21_

Currently the `/api/v1/component-analyses` endpoint shows results of all tasks that were run during analysis. It would be nice to have smaller granularity there and be able to get results of specific tasks.

This would lead to better optimization when querying for some particular data - e.g. if there are requested only github related statistics, there is no need to show results of other tasks (note that the output of some tasks can be very large).

This could be done in API v2.

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#38_

**Comment by samuzzal-choudhury** [comment]
@fridex Component analyses response schema will require a change which will incur subsequent changes in UI and Che LSP plugin. Let me include this in one of the upcoming sprints.

But, about the requirement to fetch data for only one task, can you write a proposal doc and add the link of that in this issue?

**Comment by samuzzal-choudhury** [comment]
_From @fridex on June 21, 2017 14:34_

> But, about the requirement to fetch data for only one task, can you write a proposal doc and add the link of that in this issue?

I'm not sure what should be stated inside such document. Basically what I'm proposing is to introduce endpoints like:

```
 /api/v1/component-analyses/<ecosystem>/<package>/<version>/<task>
```
An example could be:

```
 /api/v1/component-analyses/npm/serve-static/1.7.1/licenses
```

**Comment by miteshvp** [comment]
Not relevant. Component analyses gives a collaborated view from all services
