### ISSUE TITLE
 API Server: Proposal for supporting OpenAPI spec

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#841]
_From @GeetikaBatra on June 28, 2017 16:7_

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#52_

**Comment by qodfathr** [comment]
@samuzzal-choudhury @GeetikaBatra is there a proposal for supporting OpenAPI spec for which you can provide a link? Without any description on this issue, it's impossible for me to determine the goal. Maybe this is type/task instead?

**Comment by samuzzal-choudhury** [comment]
@qodfathr we will have to take up this engineering activity at a later time. This is not a priority at this moment and we can close this.
