### ISSUE TITLE
RFE: component-analysis API HTTP codes

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#842]
_From @tisnik on July 12, 2017 9:11_

Currently when you acces component-analysis API endpoints the API respond either by:

```200 OK``` if analysis is done

```404 NOT FOUND``` if: analysis just started OR is in progress

Because this API endpoints is used for many things at once, I'd suggest to use:

```200 OK``` if analysis is done and available (as currently implemented)
```201 CREATED``` or ```202 ACCEPTED``` when new analysis is to be started (ie ecosystem+component+version are ok). The former option follows RFC 7231
```202 ACCEPTED``` or if analysis is in progress
```404 NOT FOUND``` if the ecosystem|component|version are not ok or in case of other error

WDYT?

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#66_

**Comment by samuzzal-choudhury** [comment]
_From @tisnik on July 12, 2017 9:26_

Well TBH the current behaviour when HTTP GET start analysis seems to be against RFC 7231 as well, let's discuss about it in another issue ;)

**Comment by miteshvp** [comment]
Handled the response codes. Closing this.
