### ISSUE TITLE
Typo in stack analysis v2 result JSON 

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#843]
_From @tisnik on July 17, 2017 11:50_

outlier_prbability should be outlier_probability:

```
           "recommendations": {
                "companion": [],
                "usage_outliers": [
                    {
                        "package_name": "wheel",
                        "outlier_prbability": 0.71875
                    },
                    {
                        "package_name": "setuptools",
                        "outlier_prbability": 0.640625
                    }
                ],
                "alternate": []
```

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#73_

**Comment by samuzzal-choudhury** [comment]
@tisnik changed the severity to P3 as this does not affect any functionality.

**Comment by qodfathr** [comment]
Anyone consuming the API will have their application broken when the typo is finally fixed, correct? Is this API available to consumers outside of the Analytics team? If yes, I'd argue this could be as high as a SEV1. If no, then I'm okay with SEV3 as the only clients that will need to be fixed are our own.

**Comment by sunilk747** [comment]
@samuzzal-choudhury Is this bug fixed? If it is done please close this or else point me to the file where it needs to be changed I will raise a PR for it.

**Comment by samuzzal-choudhury** [comment]
@sunilk747 are you blocked because of this? This schema change will trigger changes in OSIO stack report as well as stack-report-ui. Let's hold on until the next sprint.

**Comment by sivaavkd** [comment]
@samuzzal-choudhury If we correct this small text, does this have a bigger impact ?  If so, lets remove it from 147.  Otherwise, please target to address this in the current sprint.

**Comment by samuzzal-choudhury** [comment]
@sivaavkd this change will have its direct impact on the UI. Also, removing my assignment as I am not planning to work on this in the near future.

**Comment by miteshvp** [comment]
rewired the logic to not rely on the said key - https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/commit/08fe9261be9520a43b4fb7cff55a1dd8a15b4747#diff-da74cad2a6a25f1b6964fd31d23df6e6L29
@abs51295 - can you please make sure, README's are corrected for `stack-analysis` and `common` repo, and tests are corrected again in these repo if needed

**Comment by abs51295** [comment]
@tisnik will take this forward. cc: @sivaavkd

**Comment by tisnik** [comment]
@abs51295 is it changed in unit tests as well?

**Comment by abs51295** [comment]
@tisnik yes the unit tests have been updated accordingly.

**Comment by abs51295** [comment]
Yes, the outlier dict from server will now reflect the `frequency_count` parameter instead of `outlier_prbability` and the value of the variable will be >=0.

**Comment by miteshvp** [comment]
@abs51295 `>=0` vs between `0 .. 1` has different meaning. Can you change the tests accordingly if not done. Else, please close this issue once tests are modified. Thanks.

**Comment by abs51295** [comment]
@miteshvp @tisnik is taking care of the tests.

**Comment by tisnik** [comment]
@abs51295 there are changes made in the e2e tests: https://github.com/fabric8-analytics/fabric8-analytics-common/pull/609   could you please verify that we are fixing the same issue please?

**Comment by tisnik** [comment]
@abs51295 also please make sure the API documentation is updated accordingly https://docs.openshift.io/analytics-integration-api-guide.html

**Comment by msrb** [comment]
If we are removing some keys from the API response, then we are breaking the API. This is the only public API that we have and we expect OSIO users to consume it :)

Wouldn't be better to update the [documentation](https://docs.openshift.io/analytics-integration-api-guide.html) and say that we don't consider the API to be stable yet and that it can change without prior notice in future?

@Preeticp @sivaavkd @samuzzal-choudhury @miteshvp

**Comment by tisnik** [comment]
The implementation has been fixed and we don't have to change the documentation as it does not mention outliers (it will need to be fixed later via another issue ;)
