### ISSUE TITLE
RFE: support for '-r' option in the requirements.txt (PyPi ecosystem)

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#846]
_From @tisnik on July 17, 2017 13:30_

According to the documentation (https://pip.pypa.io/en/latest/reference/pip_install/#requirements-file-format) and real requirements.txt files I've found:

it is possible to use the following option to refer to other requirements file:

```
-r more_requirements.txt
```

It seems that it is not supported in fabric8-analytics right now.

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#76_

**Comment by samuzzal-choudhury** [comment]
@tisnik would you like to put some more notes with an example of the current behaviour and an example of the expected behaviour?

**Comment by qodfathr** [comment]
There must be a bug related to this. Either the documentation is wrong, or the application is wrong. Can someone tell me which it is? Thank you.

**Comment by miteshvp** [comment]
Closing this as not relevant.
