### ISSUE TITLE
Compatible release clause does not work in stack analysis v2

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#847]
_From @tisnik on July 18, 2017 10:58_

The specification:
https://www.python.org/dev/peps/pep-0440/#compatible-release

requirements.txt that is sent to the stack analysis v2:

```
click~=6.7
```

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#78_

**Comment by jpopelka** [comment]
Should be fixed with https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/138

**Comment by jpopelka** [comment]
@tisnik can you verify that this has been fixed ?

**Comment by tisnik** [comment]
I works, TYVM. I'm closing this issue, the regression test (new feature for this project :) will follow tomorrow.
