### ISSUE TITLE
The * character in final releases does not work in stack analysis v2

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#848]
_From @tisnik on July 18, 2017 11:2_

It seems that * character that is allowed to specify final releases for package
https://www.python.org/dev/peps/pep-0440/#final-releases
does not work in stack analysis v2

requirements.txt to check:

```
click==6.*
```

on the other hand this one works:

```
click==6.7.*
```

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#79_

**Comment by jpopelka** [comment]
Should be fixed with https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/348

**Comment by jpopelka** [comment]
@tisnik can you verify that this has been fixed ?

**Comment by tisnik** [comment]
This feature works as well, TYVM! As I wrote under #847, the regression test for this issue will follow soon.
