### ISSUE TITLE
RFE: the API endpoint to force analysis for selected component on given ecosystem

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#853]
_From @tisnik on August 31, 2017 9:1_

Currently, the following endpoint called with GET method starts analysis for selected component+version only when the analysis is not finished already:

```
/api/v1/component-analyses/<ecosystem>/<package>/<version>
```

It would be nice to have the same endpoint, but for the method POST or PUT to force new analysis, even if old analysis already exists.

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#139_

**Comment by samuzzal-choudhury** [comment]
_From @fridex on August 31, 2017 9:5_

An idea for next iteration - we could make it more "sensitive" by providing endpoint for updating only certain task results (as we already have selective task runs). A user could say - I want to update only github data and so. This would be similar to https://github.com/fabric8-analytics/fabric8-analytics-server/issues/38

**Comment by samuzzal-choudhury** [comment]
_From @tisnik on August 31, 2017 10:33_

It would be really nice @fridex, TY in advance :)

**Comment by msrb** [comment]
Note this will require changes to authentication as we don't want to let anyone with a valid OSIO token to force new analyses.

**Comment by fridex** [comment]
Note this was already done in https://github.com/fabric8-analytics/fabric8-analytics-server/pull/141. Using authentication against existing OSIO token.

**Comment by qodfathr** [comment]
@samuzzal-choudhury @tisnik can either of you confirm if this has been fixed?

**Comment by samuzzal-choudhury** [comment]
@qodfathr changes are already available. Closing this issue. CC: @tisnik
