### ISSUE TITLE
RFE: add new attributes started_at and finished_at to component analysis response

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#854]
_From @tisnik on August 31, 2017 9:10_

It would be nice to have ```started_at``` and ```finished_at``` attributes in the component analysis response with the same meaning, as for stack analysis. Ideally that attributes would represent UTC time in format ```%Y-%m-%dT%H:%M:%S.%f``` or ```%Y-%m-%dT%H:%M:%S``` (w/o milliseconds)

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#140_

**Comment by samuzzal-choudhury** [comment]
_From @fridex on August 31, 2017 11:39_

This is not that straightforward for us as we provide response based on data that are available in the graph AFAIK. This information is tracked in the init/finalize task and subsequently closed (finished_at) in the finalize task (or finalize task error task).

We would probably need to sync even `InitBayesianFlow` task to graph to expose such information. CC @miteshvp

**Comment by samuzzal-choudhury** [comment]
_From @fridex on August 31, 2017 13:9_

We looked at the current output of component-analyses endpoint with @tisnik and it looks like we are not providing information about task run (when the given task was run and when finished) - parts of the `_audit` field we have for each task.

These metadata are especially helpful when providing data that change in time (e.g. github data) so a user is aware of data age (and can possibly force updates on demand). Also it will make testing and benchmarking a lot easier for @tisnik.

@samuzzal-choudhury @miteshvp Could we reintroduce these audit logs?

**Comment by msrb** [comment]
IIRC `_audit` field is/was hidden by default, one can add `?debug=true` query string to reveal it.

**Comment by msrb** [comment]
Note it can take days for analysis to finish, so it would be better to have timestamps in every task (where it makes sense).

**Comment by fridex** [comment]
`?debug=true` is not available anymore (but would be valuable I think).

**Comment by miteshvp** [comment]
Debug was introduced for audit trail. Closing this
