### ISSUE TITLE
[1] Source code style improvement: do not use bare except in the fabric8-analytics-server repository

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#856]
_From @tisnik on September 18, 2017 15:20_

Can anybody with the knowledge about the code fix the following warnings about not-so-nice code style?

```
auth.py:160:9: E722 do not use bare except'
utils.py:89:9: E722 do not use bare except'
utils.py:106:9: E722 do not use bare except'
utils.py:238:5: E722 do not use bare except'
bayesian/api_v1.py:64:5: E722 do not use bare except'
```

It's detected for source files from the ```bayesian``` directory. TYVM in advance

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#153_

**Comment by tisnik** [comment]
@samuzzal-choudhury if you want to, I can take over this issue to finish #942 (this is the only remaining part)

**Comment by tisnik** [comment]
Fixed by https://github.com/fabric8-analytics/fabric8-analytics-server/commit/163c3254aea2b880a9f9cc21bc3aa9da50946ccc
