### ISSUE TITLE
Unit test takes longer to run

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#859]
_From @corinnekrych on August 30, 2017 11:45_

Prior to this [commit to introduce runtime console](https://github.com/fabric8-ui/fabric8-ui/commit/f6bde5ea7249f4bf686c2bdcdd6648183e57fa9b) tests take
* 1.467 secs to run
* start date: 13:29:51 end date 13:31:29 of 1min38s to load and run

After, tests take: 
* 27.548 secs to run (which is ok as runtime-console comes with more unit tests
 * start date: 13:23:01 end date 13:27:12 of 4min11s to load and run

I notice the PR on runtime-console remove the webpack plugin https://github.com/s-panferov/awesome-typescript-loader (a plugin to speed up TS compilation).  See this [commit](https://github.com/fabric8-ui/fabric8-ui/commit/11427410d0e0195251bfbee43ca21bc0bf6cd27b)
@joshuawilson not sure why we removed it.

 

_Copied from original issue: fabric8-ui/fabric8-ui#1934_

**Comment by aptmac** [comment]
I took a brief look into this - was this increase in test runtime not to be expected? The commit [0] referenced at the top of this issue introduced 131 spec files, and each of those require time to be ran. 

Additionally, the elapsed time increase reported here was about 26 seconds. I went through the a-runtime-console spec files and forced them to be skipped when running tests, and noticed that they are currently responsible for ~24 seconds.

Current master branch:
![head](https://user-images.githubusercontent.com/10425301/42526297-682760b8-8443-11e8-912c-afd3ae076eba.png)

Current master branch with all a-runtime-console test files skipped:
![head-wo-aruntime](https://user-images.githubusercontent.com/10425301/42526298-683f4246-8443-11e8-8f65-b6c33f0e3de5.png)

[0] https://github.com/fabric8-ui/fabric8-ui/commit/f6bde5ea7249f4bf686c2bdcdd6648183e57fa9b

**Comment by stevengutz** [comment]
@joshuawilson Is this still valid?  I think we should close this

**Comment by stevengutz** [comment]
@joshuawilson Todd added an "Info-needed" tag to this 7 months ago and not info has been provided.  Clearly it can't be important

**Comment by joshuawilson** [comment]
this has been fixed in the latest update where we moved to Jest for test framework
