### ISSUE TITLE
"Open in IDEA" under Pipelines does not work

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#860]
_From @mindreeper2420 on August 25, 2017 17:40_

Under Create/Pipelines, there is a kabob menu option to "Open in IDEA" that does not work. When I click on the option, I do not receive any kind of notification or error - it just closes the kabob menu.

<img width="455" alt="screen shot 2017-08-25 at 1 37 57 pm 2" src="https://user-images.githubusercontent.com/4032718/29725690-f97731aa-899a-11e7-9621-f6f98013eb04.png">

_Copied from original issue: fabric8-ui/fabric8-ui#1917_

**Comment by joshuawilson** [comment]
_From @gorkem on September 1, 2017 5:5_

Why do we even have this menu?

**Comment by joshuawilson** [comment]
@gorkem I think it was something @jstrachan was working on.

**Comment by joshuawilson** [comment]
_From @jstrachan on September 4, 2017 11:8_

@gorkem because not everyone uses Che yet - folks use eclipse / VS Code / IDEA too. There are moves for similar IDEA functionality for VS Code / Eclipse too. Ideally I'd prefer an "Open in IDE" dialog then have more options for opening in Che / IDEA / Eclipse / VS Code / using git CLI and vi/emacs etc)

**Comment by joshuawilson** [comment]
_From @jstrachan on September 4, 2017 11:11_

@mindreeper2420 I suspect the issue is you've not installed Jetbrains Toolbox which has the URL handler? 

I'm hoping to move that menu item into a dialog box so we can add a warning for IDEA that it requires Jetbrains Toolbox (unfortunately there's no easy way to test if a URL is gonna work or not AFAIK) - plus we could then have a CLI tab to show folks how to fork / clone a project from the CLI too

**Comment by joshuawilson** [comment]
_From @jstrachan on September 4, 2017 11:15_

There's been some attempts to offer Jetbrains Toolbox like URL handling for VS code:

* https://github.com/Microsoft/vscode/issues/22014
* https://github.com/Microsoft/vscode/issues/20291

and eclipse:

* https://bugs.eclipse.org/bugs/show_bug.cgi?id=513364
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=513262

though neither work right yet AFAIK (we'd ideally be able to include the git ref/branch/PR in the URL)

**Comment by joshuawilson** [comment]
_From @mindreeper2420 on September 4, 2017 13:11_

I don't have anything installed, as I don't use JetBrains software. If this doesn't work without prompting and all sorts of things installed, it should either be removed from production until we have the process/flow in place, or have it changed to 'Open in Che' until one is ready, no?

The fact that it gave no prompt, no information and just closed the menu without telling me why was confusing/frustrating. :-/

**Comment by joshuawilson** [comment]
_From @mindreeper2420 on September 4, 2017 13:16_

Might it also make sense to keep this in the menu, but greyed out/disabled, and an 'Open with Che' also in the menu, but disabled? The only problem I see is the Che instances idling - then it will take a few minutes to start back up and launch.

**Comment by joshuawilson** [comment]
_From @jstrachan on September 4, 2017 13:17_

yeah - any Open in IDE option should navigate to a dialog of sorts; as even Che takes a while to startup and IDEA might not be installed - ditto any other desktop IDE etc

**Comment by qodfathr** [comment]
per #510, we are removing this menu option. Fixed via removal. :)
