### ISSUE TITLE
use a nicer widget to pick quickstarts instead of the combo box

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#861]
_From @jstrachan on August 25, 2017 15:2_

the latest greatest forge back end using the latest `launchpad-addon` now has a single step to pick a quickstart (or booster in RHOAR speak) then step2 is the project info page (github org, name, group id, version etc).

* Step1:
<img width="1022" alt="pipelines_-_fabric8_io" src="https://user-images.githubusercontent.com/30140/29719514-4de6bb44-89ae-11e7-9a97-753283435620.png">

* Step 2
<img width="1022" alt="pipelines_-_fabric8_io" src="https://user-images.githubusercontent.com/30140/29719527-63c3b322-89ae-11e7-9330-6a8c61423bec.png">

However a combo box isn't the nicest widget for picking from a list of things.  We maybe want to use a list or patternfly card/list view?

We also might wanna add a little text filter box so folks can easily filter by text; maybe also filter combo boxes for runtime and/or mission?

Incidentally the JSON that comes back for each quickstart ('booster') looks like the following so we can render this & filter it however we like on the client:

```json
            [
                {
                    "id":"Secured Vertx - Rest & Red Hat SSO",
                    "description":"Quickstart to expose a REST Greeting endpoint using Eclipse Vert.x & Secured by Red Hat SSO",
                    "missionId":"rest-http-secured",
                    "missionName":"Secured",
                    "name":"Secured Vertx - Rest & Red Hat SSO",
                    "runtimeId":"vert.x",
                    "runtimeName":"Eclipse Vert.x"
                },
                {
                    "id":"Vert.x - HTTP & Config Map",
                    "description":"Simple HTTP endpoint where the Vert.x application uses OpenShift ConfigMap to get the application parameters.",
                    "missionId":"configmap",
                    "missionName":"Externalized Configuration",
                    "name":"Vert.x - HTTP & Config Map",
                    "runtimeId":"vert.x",
                    "runtimeName":"Eclipse Vert.x"
                },
...
```

_Copied from original issue: fabric8-ui/fabric8-ui#1915_

**Comment by joshuawilson** [comment]
_From @jstrachan on August 25, 2017 15:2_

cc @catrobson

**Comment by joshuawilson** [comment]
_From @catrobson on August 25, 2017 15:18_

+1 that we  want this to changeover to something easier to browse than a picker dropdown.  @mindreeper2420 is working  up a new design for the launch team that hopefully we can follow here as well.

**Comment by corinnekrych** [comment]
it is fixed in https://github.com/openshiftio/openshift.io/issues/966
