### ISSUE TITLE
Updating user profile requires browser refresh to see the changes

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#862]
_From @alexeykazakov on August 18, 2017 16:19_

1. Go to Update Profile page
2. Change email
3. Click on Update
4. I see the old email in the profile again
5. Refresh the browser
6. Now I see the updated email

I didn't try with other fields though.

_Copied from original issue: fabric8-ui/fabric8-ui#1896_

**Comment by qodfathr** [comment]
This is still happening. Moreover, if you do not refresh, if you go to edit your profile again, the profiler editor shows the old email address, not the new one. So it looks like nothing happened when you did the first update.
