### ISSUE TITLE
on the Codebases page we should have the option to create a Pipeline for a Codebase

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#864]
_From @jstrachan on August 17, 2017 10:0_

folks can create codebases via a github URL, which is great. Folks may then want to then create a pipeline for it after the codebase has been created; so we should:

* know if a Codebase has an associated Pipeline or not and if not provide a kebab option on a Codebase to `Create Pipeline`

The `Create Pipeline` wizard would then work kinda like the `Import` wizard; only we already know the github coordinates so it could miss out the first 2 pages and go straight to the 'Pick Pipeline' page

_Copied from original issue: fabric8-ui/fabric8-ui#1884_

**Comment by qodfathr** [comment]
Closing, as this will get addressed in some way by https://github.com/fabric8-ui/fabric8-ux/issues/839, #1707, #1576, which are all related to the same area of concern.
