### ISSUE TITLE
Import vs. Create Codebase - resolve capability and update UI

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#865]
_From @catrobson on August 14, 2017 13:51_

Decide if we should have a create vs. import codebase capability on the space dashboard, update this issue and UI to reflect decisions made.

_Copied from original issue: fabric8-ui/fabric8-ui#1867_

**Comment by joshuawilson** [comment]
@catrobson what do you want to do with this?

**Comment by catrobson** [comment]
I'd like to keep carrying this forward in our backlog, we still need at address it.

**Comment by qodfathr** [comment]
@catrobson, with the advent of https://github.com/fabric8-ui/fabric8-ux/issues/839, can we now close this question in favor of that one as the answer?

**Comment by catrobson** [comment]
@qodfathr yes
