### ISSUE TITLE
Status Icon Does Not Show Rollup

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#867]
_From @mindreeper2420 on July 26, 2017 15:58_

In the Status drop down, when a status is anything other than green (check mark), it should appear in the header as such. Currently, the status icon in the header is always shown as the check mark, regardless of what the individual statuses are.

<img width="265" alt="screen shot 2017-07-26 at 11 57 24 am" src="https://user-images.githubusercontent.com/4032718/28630922-9eeb0da0-71f9-11e7-9be2-7c8b155b3dda.png">

_Copied from original issue: fabric8-ui/fabric8-ui#1797_

**Comment by joshuawilson** [comment]
Some of the values need to be polled to get them, they aren't there until you open the menu. So it is not simple to just copy it to the top.
If we want to patch it, we could change the icon to the text "status".

**Comment by aslakknutsen** [comment]
Reclassify as an Enhancement, not a bug.

**Comment by joshuawilson** [comment]
Why is this not a bug, it should have always rolled up to the button?

**Comment by jiekang** [comment]
This element no longer exists in production. I think this issue can be closed. @joshuawilson Thoughts?

**Comment by joshuawilson** [comment]
It was removed completely. Closing.
