### ISSUE TITLE
Quota limits, when reached and resulting in deployment failures, are not reported to user in OSIO UI

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#874]
_From @ldimaggi on July 9, 2017 3:17_

Steps to recreate:
* "Clean out" existing spaces, github repos, OpenShift pods, deployments, build configs, etc. 
* Create (3) new projects (Vert.X, Spring-Boot, Vert.X Config Map)
* Observe success reported for rollout to stage and run:

![screenshot from 2017-07-08 23-13-19](https://user-images.githubusercontent.com/642621/27990894-774f3da8-6433-11e7-8860-7c4b00de5d01.png)

But - observe that quota errors have actually blocked deployment of one of the projects:

![screenshot from 2017-07-08 23-13-34](https://user-images.githubusercontent.com/642621/27990897-8f2a7a5a-6433-11e7-9593-6e3b7f2bf40d.png)

_Copied from original issue: fabric8-ui/fabric8-ui#1679_

**Comment by joshuawilson** [comment]
_From @ldimaggi on July 9, 2017 3:18_

Related to:  https://github.com/fabric8-ui/fabric8-ui/issues/1648

**Comment by alexeykazakov** [comment]
Duplicates https://github.com/openshiftio/openshift.io/issues/2629 ?

**Comment by joshuawilson** [comment]
yes
