### ISSUE TITLE
Che workspaces use replicasets, can we move to using Deployments instead

### ISSUE THREAD

**Issue by kbsingh** [openshiftio/openshift.io#875]
at the moment, we are using replicasets - if I recall correctly, this was down to us using the replicaset as a way to do time allocations - however, with openshift 3.6+ since we have a real idle api, do we want to consider moving to regular deployment configs for the workspace bringups ?

**Comment by ibuziuk** [comment]
@sleshchenko @l0rd  am I correct that in che6 it was decided to create pods directly without usage of dc (same manner as used for jenkins pod are currently been created on osio) ?

**Comment by sleshchenko** [comment]
@ibuziuk Yes, you're correct.

**Comment by ibuziuk** [comment]
If there is no objections the issue should be closed as outdated once che6 would be used on osio

**Comment by ibuziuk** [comment]
closing, since migration to che 6 is finished and replica sets are not used for workspace creation anymore
