### ISSUE TITLE
 "Add to Space" - results in SSO error creating Che workspace

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#878]
_From @ldimaggi on July 7, 2017 16:15_

This issue first started showing up on July 7 - After creating a new project, either by creating the project from a quickstart, or by importing existing code, attempts to create a new Che workspace are blocked by an "ERR_TOO_MANY_REDIRECTS" error. The Che workspaces, however, are created. The user must use an incognito window to access the workspaces in Che. 

________________________________

Original description follows:

Steps to recreate:
* Create a new project (Add to Space) by importing existing code - for example from: https://github.com/osiotest314/vertx-wiki2
* Observe successful import:
![screenshot from 2017-07-07 11-59-02](https://user-images.githubusercontent.com/642621/27966346-ee7a238e-630c-11e7-8748-7bfe6cfd9bd0.png)

* Attempt to create Che workspace - observe error reported to user in browser:
This page isn’t working
sso.openshift.io redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
![screenshot from 2017-07-07 11-59-41](https://user-images.githubusercontent.com/642621/27966388-127dd91a-630d-11e7-8f08-e978ed94296f.png)

* In codespace page of UI - observe absence of link to workspace:
![screenshot from 2017-07-07 12-03-19](https://user-images.githubusercontent.com/642621/27966422-2cc348e6-630d-11e7-9e60-b82ccb1b988f.png)

* In Che - observe workspace has actually been created:
![screenshot from 2017-07-07 12-10-28](https://user-images.githubusercontent.com/642621/27966454-4c97465e-630d-11e7-8000-573dff5e31a4.png)

* After about 5 minutes - observe link to workspace in OSIO UI:
![screenshot from 2017-07-07 12-06-19](https://user-images.githubusercontent.com/642621/27966480-5d941dd8-630d-11e7-9c74-2be106339d26.png)

* Attempt to open the Che workspace - observe this error is shown again:
![screenshot from 2017-07-07 11-59-41](https://user-images.githubusercontent.com/642621/27966514-8257a702-630d-11e7-9e19-7547d76f6bcf.png)

* Access Che directly - the workspace is there:
![screenshot from 2017-07-07 12-14-14](https://user-images.githubusercontent.com/642621/27966621-db73fb38-630d-11e7-8e73-831a716b8963.png)

_Copied from original issue: fabric8-ui/fabric8-ui#1662_

**Comment by joshuawilson** [comment]
_From @ldimaggi on July 8, 2017 18:6_

SSO issue may be a caching issue - need to investigate - using an incognito window resolved the problems.

**Comment by joshuawilson** [comment]
_From @alexeykazakov on July 8, 2017 19:7_

See https://github.com/redhat-developer/rh-che/issues/180

**Comment by l0rd** [comment]
This has been fixed 2 months ago

**Comment by ldimaggi** [comment]
Closing - no longer a problem.
