### ISSUE TITLE
Caching in the UI results in the user seeing references to deleted spaces

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#879]
_From @ldimaggi on July 7, 2017 15:50_

To recreate this issue:
* Create and delete spaces - The deleted spaces are shown in the 'recent spaces' lists - if a space is deleted and then recreated, its name can appear more than once in the list.

Screenshots - these screenshots are all taken at the same time - the "view all spaces" list is correct - the others are incorrect.

![screenshot from 2017-07-07 07-55-23](https://user-images.githubusercontent.com/642621/27965576-41d66748-630a-11e7-97af-1798eef62bd8.png)
![screenshot from 2017-07-07 07-55-00](https://user-images.githubusercontent.com/642621/27965577-41d853be-630a-11e7-83c0-7097021c19d7.png)
![screenshot from 2017-07-07 07-54-37](https://user-images.githubusercontent.com/642621/27965578-41dd0f80-630a-11e7-9ff1-ca1033f317b9.png)

_Copied from original issue: fabric8-ui/fabric8-ui#1661_

**Comment by joshuawilson** [comment]
_From @ldimaggi on July 7, 2017 15:56_

![screenshot from 2017-07-07 11-55-47](https://user-images.githubusercontent.com/642621/27965902-4231092c-630b-11e7-97a2-9f5004807759.png)

**Comment by joshuawilson** [comment]
Does a refresh or hard refresh fix it?

**Comment by joshuawilson** [comment]
_From @ldimaggi on July 7, 2017 17:39_

Yes - a control/r refresh clears the recent spaces displayed in the account home view.

**Comment by joshuawilson** [comment]
_From @ldimaggi on July 7, 2017 20:47_

![screenshot from 2017-07-07 15-36-27](https://user-images.githubusercontent.com/642621/27976338-ffc29096-6333-11e7-94eb-327130fd6d9a.png)

**Comment by ldimaggi** [comment]
879 is still a bug
deleted spaces still appear in the account home page - under recent pages

**Comment by ldimaggi** [comment]
Closing - long since resolved.
