### ISSUE TITLE
Error in pushing project to stage caused by timeout reported as success in OSIO UI

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#880]
_From @ldimaggi on July 6, 2017 19:57_

Steps to recreate:
* Create a new Vert.X project - accept all defaults

The push to stage failed due to a timeout. The UI presented this as success:

![screenshot 23](https://user-images.githubusercontent.com/642621/27930144-8b752dfa-6263-11e7-9924-51a711be9d7e.png)

Openshift correctly trapped the error:

![screenshot 24](https://user-images.githubusercontent.com/642621/27930168-9bd99960-6263-11e7-9d51-4368c4fbd9c6.png)

![screenshot 25](https://user-images.githubusercontent.com/642621/27930172-a2b670f0-6263-11e7-98bd-fb566f031df0.png)

The log indicated:

```
--
--> Scaling testjul61499369606171-1 to 1
  | --> Waiting up to 10m0s for pods in rc testjul61499369606171-1 to become ready
  | error: update acceptor rejected testjul61499369606171-1: pods for rc "testjul61499369606171-1" took longer than 600 seconds to become ready

```

_Copied from original issue: fabric8-ui/fabric8-ui#1648_

**Comment by joshuawilson** [comment]
_From @ldimaggi on July 10, 2017 17:9_

Just saw another instance of this issue:

![screenshot from 2017-07-10 11-50-55](https://user-images.githubusercontent.com/642621/28030224-d49e8700-6570-11e7-9d2a-0376e9e1ba8c.png)
![screenshot from 2017-07-10 11-44-30](https://user-images.githubusercontent.com/642621/28030225-d4b4ab3e-6570-11e7-81c3-fa58871ecfa2.png)
![screenshot from 2017-07-10 11-43-58](https://user-images.githubusercontent.com/642621/28030226-d4b53e1e-6570-11e7-85fb-2d509e435245.png)

Seems to be a pattern - is there anything that would make stage more likely to timeout than run?

**Comment by joshuawilson** [comment]
@rawlingsj @jstrachan Is this disconnect in the UI or in the pipeline?

**Comment by qodfathr** [comment]
@ldimaggi this is pretty old and I don't recall seeing it in quite some time. Please close if you feel this has been fixed.

**Comment by ldimaggi** [comment]
Closing - this has not been seen for a while.
