### ISSUE TITLE
Pipeline fails while build is successful - the user might miss the error symbol as the pipeline phases stays green

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#881]
_From @ldimaggi on July 6, 2017 19:24_

It's possible for a build to be successful, but the pipeline fails. The resulting pipeline display shows both red and green results - we should better highlight that the pipeline failed.

![screenshot from 2017-07-06 14-54-24](https://user-images.githubusercontent.com/642621/27928927-081ef3ea-625f-11e7-9890-8d5f1ceead37.png)

Log fragment follows:

```

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.804 s
[INFO] Finished at: 2017-07-06T18:45:41+00:00
[INFO] Final Memory: 12M/491M
[INFO] ------------------------------------------------------------------------
[Pipeline] sh
[osiotest314_july6a_master-UI254UKQTLZZP2P4YZWI42Y7XEVMOSXYHFXCI3PXFGZ5T5LMGXJA] Running shell script
Executing shell script inside container [maven] of pod [jenkins-slave-mvcm8-1f5tv]
Executing command: sh -c echo $$ > '/home/jenkins/workspace/osiotest314_july6a_master-UI254UKQTLZZP2P4YZWI42Y7XEVMOSXYHFXCI3PXFGZ5T5LMGXJA@tmp/durable-aab9fd76/pid'; jsc=durable-053596687ba2418070239e64749ac522; JENKINS_SERVER_COOKIE=$jsc '/home/jenkins/workspace/osiotest314_july6a_master-UI254UKQTLZZP2P4YZWI42Y7XEVMOSXYHFXCI3PXFGZ5T5LMGXJA@tmp/durable-aab9fd76/script.sh' > '/home/jenkins/workspace/osiotest314_july6a_master-UI254UKQTLZZP2P4YZWI42Y7XEVMOSXYHFXCI3PXFGZ5T5LMGXJA@tmp/durable-aab9fd76/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/workspace/osiotest314_july6a_master-UI254UKQTLZZP2P4YZWI42Y7XEVMOSXYHFXCI3PXFGZ5T5LMGXJA@tmp/durable-aab9fd76/jenkins-result.txt' 
cd "/home/jenkins/workspace/osiotest314_july6a_master-UI254UKQTLZZP2P4YZWI42Y7XEVMOSXYHFXCI3PXFGZ5T5LMGXJA"
sh -c echo $$ > '/home/jenkins/workspace/osiotest314_july6a_master-UI254UKQTLZZP2P4YZWI42Y7XEVMOSXYHFXCI3PXFGZ5T[?1034hsh-4.2$ [Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code -2
Finished: FAILURE
```

_Copied from original issue: fabric8-ui/fabric8-ui#1646_

**Comment by joshuawilson** [comment]
@jstrachan how can it fail and pass at the same time?

**Comment by joshuawilson** [comment]
_From @jstrachan on July 7, 2017 5:16_

the status of a stage != the status of the build. 

From the log all the stages are green (see the 'SUCCESS') in the build log - thats the last stage. Then after all that the final build that returned an error. So the UI is totally correct - the stages all were green but the build failed right at the end.

I'll try figure out why though; as thats a tad wacky - usually there's not much to do once the final stage is complete (but pipelines can do more stuff outside the last stage)

**Comment by joshuawilson** [comment]
_From @ldimaggi on July 7, 2017 11:49_

This issue is related - https://github.com/fabric8-ui/fabric8-ui/issues/1648

**Comment by joshuawilson** [comment]
@jstrachan Is this something we should change in the UI? or is it good enough now. I'm asking because it was confusing to us. Maybe @catrobson can come up with a better way to display this so the user will understand.

**Comment by joshuawilson** [comment]
related to #1615

**Comment by joshuawilson** [comment]
_From @catrobson on July 25, 2017 12:26_

@jstrachan Are we able to give the user some information about the problem with the build failure?  I think the user in this case is looking to understand why I am in a failure state, so we need some information to show.  If so, can I get an example of what that might look like so I can consider how to integrate it into the screen for these cases?

**Comment by qodfathr** [comment]
Is there really a bug here? The stages are Geen, which is correct, and there is a red X on the overall build, which is also correct. At best, this is a request for change/enhancement, but I'm struggling to call this one a bug.

My option would be different if there wasn't the red X.

I'm going to relabel as feature, but feel free to put back to bug if you feel strongly about it.

cc: @ldimaggi @catrobson

**Comment by ldimaggi** [comment]
I have not seen this bug for a long time - I vote to just close it. We can always re-open it if we start seeing it again.
