### ISSUE TITLE
"View all Spaces" returns random subsets of a user's spaces

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#883]
_From @joshuawilson on July 3, 2017 20:38_

_From @ldimaggi on July 3, 2017 19:10_

I first started seeing this issue on July 3 - when a user views all spaces, random subsets of that user's spaces are seen:

![screenshot from 2017-07-03 14-26-01](https://user-images.githubusercontent.com/642621/27805194-403d941c-6001-11e7-9e9e-1cb7bfcf3fe8.png)

![screenshot from 2017-07-03 14-45-19](https://user-images.githubusercontent.com/642621/27805201-494de228-6001-11e7-83d5-3281b38e6837.png)

_Copied from original issue: fabric8-ui/fabric8-planner#2055_

_Copied from original issue: fabric8-ui/fabric8-ui#1626_

**Comment by joshuawilson** [comment]
_From @aslakknutsen on July 3, 2017 19:32_

This is a f8-ui issue, not planner. But possible caused by no pagination support in the UI and random returned order from server.

**Comment by joshuawilson** [comment]
I wonder if this has to do with pagination of the result set.

**Comment by joshuawilson** [comment]
_From @aslakknutsen on August 14, 2017 21:15_

What order do we want spaces in here? @catrobson

**Comment by joshuawilson** [comment]
IMHO, I would want it in either most recently visited or alphabetical.

**Comment by joshuawilson** [comment]
_From @catrobson on August 15, 2017 1:46_

This is being redesigned right now here:  https://github.com/fabric8-ui/fabric8-ux/issues/572
Right now we're thinking about showing these by latest change date, but this might be quite volatile so I need to think about that a bit more.  Last visited might be less volatile for if the user changes the filter criteria or refreshes the page.  Alphabetical by default is typically not useful, so we will want this to be based on some relevance metric like last visited or most recently changed.

**Comment by qodfathr** [comment]
Given new design of Spaces, perhaps this can be closed? (At best, it's NPTF since it's an issue related to a screen which is going away.)

**Comment by ldimaggi** [comment]
+1 - closing.
