### ISSUE TITLE
Areas to use tree-list view

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#885]
_From @catrobson on June 29, 2017 19:1_

Change over Area list page to use tree-list view control to show parent and children areas as a tree rather than in a flat list with parent/child/grandchild/etc.

_Copied from original issue: fabric8-ui/fabric8-ui#1617_

**Comment by joshuawilson** [comment]
@catrobson is this to be designed or do you have designs?

**Comment by joshuawilson** [comment]
ping @catrobson

**Comment by joshuawilson** [comment]
_From @catrobson on July 25, 2017 12:23_

@dgutride and I discussed that this could move forward without designs for just swapping out the list component itself to a tree-list component.  None of the other interactions will be affected, and the only change we discussed was that we would consider adding in drag-and-drop with the tree-list component.

**Comment by jiekang** [comment]
Closing as the Areas page is a tree list view. See https://github.com/fabric8-ui/fabric8-ui/pull/2638
