### ISSUE TITLE
Context menu should include View my spaces option

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#887]
_From @dgutride on June 23, 2017 17:32_

The top menu should include a View my spaces link takes the user to their profile page and automatically shows the spaces tab.

_Copied from original issue: fabric8-ui/fabric8-ui#1595_

**Comment by chrislessard** [comment]
@joshuawilson  is this still relevant ? I believe a very similar feature exists already.

**Comment by joshuawilson** [comment]
I think we can close it as the whole nav is getting redesigned. 
@dgutride please reopen if you still need it.
