### ISSUE TITLE
Intermittent issue - auto-recreation of pods is not always successful

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#889]
_From @ldimaggi on June 21, 2017 18:6_

This issue is being logged to ensure that its solution is fully verified. 

When out of memory issues are encountered, the workaround is to manually delete Jenkins pods as they are automatically recreated. Sometimes, the automatic recreation fails, and they must be recreated manually.

We have to verify that the automatic recreation is successful after this issue is resolved:
https://github.com/fabric8io/fabric8-init-tenant/issues/74

NOTE: running pipelines for the first time will take longer as build and base docker images are pulled onto the node
[Pipeline] container
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Build Release)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

java.lang.OutOfMemoryError: Metaspace
Finished: FAILURE

-------------------------------------------------------------------

Solution is generally to manually delete jenkins* pods - and then watch them be recreated automatially.

In my case, on June 21, it was necessary to manual deploy the jenkins and jenkins content-registry deployments to resolve the issue.

This issue is probably caused by tenant service updates issue logged here: https://github.com/fabric8io/fabric8-init-tenant/issues/74

_Copied from original issue: fabric8-ui/fabric8-ui#1567_

**Comment by joshuawilson** [comment]
_From @ldimaggi on June 21, 2017 18:12_

Related to:
https://github.com/fabric8io/fabric8-ui/issues/1279

**Comment by qodfathr** [comment]
With the many changes to Jenkins, I wonder if this is still valid? @ldimaggi, do you have an opinion? We should verify against an account with Jenkins idling enabled.

**Comment by ldimaggi** [comment]
The ability to reset a user's environment made this issue obsolete. Do we want to have users randomly deleting resources in OSO? I'd vote to simply close this issue.
