### ISSUE TITLE
Over time, a user's maven .m2 Persistent Volume and Content Repo runs out of space - must be cleaned out manually

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#891]
_From @ldimaggi on June 21, 2017 14:3_

Related to: https://github.com/fabric8io/fabric8-ui/issues/1526

There's no centralised logs or metrics for tenant namespaces - and over time, a user's maven .m2 Persistent Volume runs out of space - as does the user's content repo

Current solution is to create a Jenkinfile that mounts the .m2 folder and runs rm - rf 

We should ship jenkins with this job, call it purge or something - then a user can simply run oc start-build purge-pvs

_Copied from original issue: fabric8-ui/fabric8-ui#1560_

**Comment by joshuawilson** [comment]
_From @ldimaggi on June 21, 2017 14:4_

To clean out the content repo:

oc project almusertest1-jenkins

oc get pods
NAME                                 READY     STATUS      RESTARTS   AGE
content-repository-5-3cw6j           1/1       Running     0          1d

oc exec -ti content-repository-5-3cw6j bash
rm -rf /var/www/html/content/repositories

Can we also clean out the .m2 repo from the container's shell?

No because it's not mounted there - it's mounted in the build pod.

**Comment by joshuawilson** [comment]
_From @rawlingsj on June 21, 2017 15:8_

I'm gonna knock up a housekeeping pipeline that folks can run + add a diagnose one too that will help us investigate issues and even automatically solve known issues where we can.

**Comment by joshuawilson** [comment]
_From @ldimaggi on June 21, 2017 15:12_

Thanks James - if we cannot solve this automatically (ala a garbage collector type approach) then we had better find a way to reliably warn the users and give them an easy way to fix this....when it happens.

**Comment by joshuawilson** [comment]
@ldimaggi if we can't get it fixed automatically soon enough, could you please add this to https://github.com/openshiftio/openshift.io/wiki/FAQ

**Comment by qodfathr** [comment]
@joshuawilson is this still correctly an open issue? If it is, I'll get it prioritized under an epic.

**Comment by ldimaggi** [comment]
The fact that I have not seen this issue in several months of heavy manual and automated testing makes me think that it has been resolved. I vote to close this.

**Comment by fabricepipart** [comment]
Hi!

Actually I am facing the same issue that is described here on my openshift.io account. By default I have a Pipeline that is set up to clean the m2repo. But I have no way to clean the content-repository. 

And I can't apply the workaround mentioned here since I don't have the rights to connect inside the container (I suppose the rights for those infrastructure pods have changed).
