### ISSUE TITLE
Quickstart wizard should have a back button

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#893]
_From @joshuawilson on June 21, 2017 5:16_

_From @mishaone on June 21, 2017 4:57_

The 5 step wizard for the quickstart app menu has a next and finished option, but should have a back option as well to go to a former step in the process to change something if required. At the moment the only workaround for this is to quit the process and start again from scratch.

How to replicate:
1. Add to space > Create a quickstart project
2. Add project type information in step 1 of the 5 step wizard and click next
3. Try to go back to correct information in a previous step. There should be an option for previous as well as next here.

_Copied from original issue: openshiftio/openshift.io#262_

_Copied from original issue: fabric8-ui/fabric8-ui#1555_

**Comment by joshuawilson** [comment]
@mishaone I'm not sure the API we are using can support going back. @mitchharpur or @corinnekrych can you please confirm.

**Comment by joshuawilson** [comment]
With the changes we are making, this may be possible in the hear term.

**Comment by joshuawilson** [comment]
_From @corinnekrych on August 8, 2017 12:14_

@joshuawilson with the patternfly wizard there is a back button:
https://github.com/patternfly/patternfly-ng/blob/master/src/app/wizard/wizard.component.ts#L50

cc: @catrobson do we want to be able to go back?

**Comment by joshuawilson** [comment]
_From @catrobson on August 8, 2017 12:31_

@corinnekrych yes, we'd like to be able to allow the user to go back and change things on previous steps.  I *think* that the API changes that James was working on would enable us to do that.

**Comment by joshuawilson** [comment]
_From @corinnekrych on August 8, 2017 12:38_

if we're in quickstart wizard and we want to go back, I think we only need to send an http call with previous params. No nee to change anything to forge add-on (ie: no API changes required).
@catrobson I think atm this is more a UI limitation.
@jstrachan could you confirm?

**Comment by joshuawilson** [comment]
@jstrachan were you able to update the Forge REST endpoint to support fetching the needed info and validation on Finish?

**Comment by joshuawilson** [comment]
_From @jstrachan on August 8, 2017 12:51_

@corinnekrych the client side should be able to move back at any time really without talking to the forge server side

@joshuawilson no I've not yet had chance to reimplement the server side forge wizard on the client side with the associated new REST API on the server and used on the client; its a more long term change when my TODO list is much shorter

**Comment by corinnekrych** [comment]
@joshuawilson this one should be fixed with the refactor/rewrite of the wizard going on in  https://github.com/fabric8-ui/fabric8-ui/pull/1997
