### ISSUE TITLE
We should be able to stop and delete a workspace from the codebase UI

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#896]
_From @l0rd on June 16, 2017 14:18_

Users are not able to clean-up workspaces right now and look for workarounds like using [Che dashboard](https://github.com/redhat-developer/rh-che/issues/105).

Some discussions about porting Che dashboard functionalities to the codebase UI have already been initiated. But having stop and delete buttons is really the minimum otherwise we won't be able to remove Che dashboard.

cc @ashumilova @gorkem @ibuziuk @joshuawilson 

_Copied from original issue: fabric8-ui/fabric8-ui#1528_

**Comment by joshuawilson** [comment]
I'm still not sure how much functionality makes sense to add to the codebases page. That said, we should discuss it here.

cc @maxandersen @aslakknutsen @catrobson

**Comment by joshuawilson** [comment]
The status/open-for-dev label is for issues that have a clear specification. This one needs discussion.

**Comment by joshuawilson** [comment]
@catrobson we are going to need to work with @l0rd and the che team to figure out how we either change the Codebases page or what a Workspaces page would look like so that we can provide the che controls that are needed.

**Comment by joshuawilson** [comment]
_From @slemeur on August 8, 2017 11:56_

I worked on the following set of specifications for these use cases: 
https://redhat.invisionapp.com/share/94CH0VNV5

I think it covers what is needed, but we can refined them and scope them. First goal would be to only allow browsing the existing workspaces and deleting them from a new "Workspaces" tab. We can then add the other capabilities.

**Comment by joshuawilson** [comment]
The visuals you provided appear releated to https://github.com/fabric8-ui/fabric8-ui/issues/1825

**Comment by joshuawilson** [comment]
_From @slemeur on August 8, 2017 13:19_

@joshuawilson: They are also providing mockups for what a "Workspaces page" would look like.

**Comment by qodfathr** [comment]
Closing in favor of epic #1936
