### ISSUE TITLE
New project creation - builds are failing - project jar not found - root cause is that over time, a user's Maven .m2 PV can run out of space

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#897]
_From @ldimaggi on June 16, 2017 3:6_

Create new project fails - build fails - project jar is not found:

https://jenkins-almusertest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/job/almightytest/job/june16a/job/master/1/console

`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install (default-install) on project june16a: Failed to install artifact com.example:june16a:jar:1.0.1: /root/.mvnrepository/com/example/june16a/1.0.1/june16a-1.0.1.jar (No such file or directory) -> [Help 1]`

Steps to recreate:
* Login to openshift.io
* Create a new space
* Create a new project - quickstart/Vert.X - accept all defaults

_Copied from original issue: fabric8-ui/fabric8-ui#1526_

**Comment by joshuawilson** [comment]
_From @ldimaggi on June 16, 2017 16:53_

I think that the root cause of this is that the Jenkins services can not be scaled up or down, For the Jenkins service, the up/down icons are disabled.

How does the user resolve debug/resolve this issue?

![screenshot from 2017-06-16 12-35-43](https://user-images.githubusercontent.com/642621/27236377-c88e3e06-5292-11e7-836c-a3184c04450a.png)

**Comment by joshuawilson** [comment]
@jstrachan do you have any ideas on this?

**Comment by joshuawilson** [comment]
@ldimaggi Please specify the steps to reproduce.

**Comment by joshuawilson** [comment]
_From @rawlingsj on June 16, 2017 20:53_

` Failed to install artifact com.example:june16a:jar:1.0.1: /root/.mvnrepository` sounds like you've run out of diskspace on the .m2 PV.  We only have 1GB per PV and the .m2 dir is mounted on one.  If you're running lots of tests then I'd say this is probably the issue.

To trash the PV (persistent volume) you need to delete the `jenkins-mvn-local-repo` PVC (persistent volume claim) in your jenkins namespace. I'm not sure if you manually delete the PVC and update tenant if it will be recreated, but it's worth a go.  

If it fails you can always recreate it by running the following command replacing `foo` with your username 
```
oc apply -f https://raw.githubusercontent.com/fabric8io/fabric8-team-components/master/jenkins-openshift/src/main/fabric8/jenkins-mvn-local-repo-pvc.yml -n foo-jenkins
```

**Comment by joshuawilson** [comment]
_From @ldimaggi on June 18, 2017 3:56_

Thanks - but that did not resolve this.

**Comment by joshuawilson** [comment]
_From @rawlingsj on June 20, 2017 17:36_

So you deleted the PVC and get the exact same error with the new empty PV? 

Does this happen on a fresh create project wizard too?  Only this seem to be the only occurrence of this error so am surprised at the steps to recreate.  I've been able to create vertx quickstarts and run their pipelines.

**Comment by joshuawilson** [comment]
_From @ldimaggi on June 20, 2017 19:8_

Yes - watch the screencasts here - just ran the test again today:

https://drive.google.com/drive/folders/0B1s-ZoxD8FjUZmRjcE1rRG1QWjg?usp=sharing

**Comment by joshuawilson** [comment]
_From @ldimaggi on June 21, 2017 13:46_

James discovered that:

Over time, a user's maven .m2 Persistent Volume runs out of space - as does the user's content repo

Current solution is to create a Jenkinfile that mounts the .m2 folder and runs rm - rf

**Comment by joshuawilson** [comment]
@jstrachan what is the status on this?

**Comment by jstrachan** [comment]
no idea - is it still an actual issue with the vertx quickstarts?

**Comment by joshuawilson** [comment]
@ldimaggi can you verify please.

**Comment by ldimaggi** [comment]
Closing - this issue has not been seen for months.
