### ISSUE TITLE
delete option on the Applications page should delete all resources associated with an App

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#899]
_From @jstrachan on June 14, 2017 8:48_

not just the Deployment/DeploymentConfig but also all the associated ReplicaSets, Pods, Service, Route, ConfigMap, Secrets etc

_Copied from original issue: fabric8-ui/fabric8-ui#1508_

**Comment by qodfathr** [comment]
@joshuawilson I see that https://github.com/fabric8-ui/fabric8-ui/issues/1508 is closed. Can this be closed?

**Comment by joshuawilson** [comment]
It was only closed there to move it here, the work was never done.
However this is for a page that is going away, so I'm going to close it.
