### ISSUE TITLE
Reset URL on login errors to avoid recursive error messages in notification

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#90]
![screenshot from 2017-04-24 16-26-11](https://cloud.githubusercontent.com/assets/132158/25357182/e4bd3fca-290a-11e7-98d7-69a9cdd9a1c7.png)

**Comment by pmuir** [comment]
@alexeykazakov please take this one on.

**Comment by alexeykazakov** [comment]
@maxandersen @joshuawilson I can't assign myself. Please assign to me.

**Comment by joshuawilson** [comment]
@alexeykazakov has this been fixed?

**Comment by alexeykazakov** [comment]
I didn’t see it for awhile. It looks like it was fixed in UI.
