### ISSUE TITLE
delete Pipeline should prompt the user if they wish to delete the apps from each environment too

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#900]
_From @jstrachan on June 14, 2017 8:47_

if you delete a Pipeline the dialog should prompt the user to ask if they want to delete the associated resources from the Stage and Run environments too.

If so all the resources for a pipeline should be removed

_Copied from original issue: fabric8-ui/fabric8-ui#1507_

**Comment by qodfathr** [comment]
I'm not sure what this is proposing.

The first sentence says talks about deleting "the associated resources from the .. environments." What is meant by associated? The deployments, deployment configs, etc.  etc.?

The second sentence seems to limit it to just the pipeline resources. But are their any pipeline resources in the State/Run environments?

Also, I believe the pipeline delete functionality is already behaving as intended.

I cautiously vote to close.
