### ISSUE TITLE
Update Gulp Scripts

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#903]
_From @mindreeper2420 on June 12, 2017 14:9_

Update Gulp Scripts to build less files, move images/fonts and consume node_modules for frameworks (PatternFly, Bootstrap and Font Awesome). Convert Webpack scripts to Gulp scripts, where appropriate.

_Copied from original issue: fabric8-ui/fabric8-ui#1497_

**Comment by mindreeper2420** [comment]
@joshuawilson I don't believe that this is necessary anymore.
