### ISSUE TITLE
review the Apps page UX

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#904]
_From @jstrachan on June 9, 2017 12:15_

we may wanna polish it a bit etc.

I like [this demo](https://drive.google.com/file/d/0B-T8vwICvu2MTDV5M25tTURoOUU/view)that Jorge pointed us at: 

<img width="1364" alt="osepipelinedashboard_export_mp4_-_google_drive" src="https://user-images.githubusercontent.com/30140/26974931-8248f864-4d15-11e7-8add-12badc4fe0ed.png">

so we could add the (optional) Promote button on the right. Then adding more detail expandable information (like features implemented, git commit, jenkins build log, view in github, CPU / memory or quotas etc)

_Copied from original issue: fabric8-ui/fabric8-ui#1483_

**Comment by joshuawilson** [comment]
_From @jstrachan on June 9, 2017 12:15_

+ @catrobson

**Comment by joshuawilson** [comment]
@catrobson can you please consider this and share it with whoever is doing the designs.

**Comment by qodfathr** [comment]
Now handled via #287
