### ISSUE TITLE
changing spaces via the context drop down; should that keep on the same page but just change the space?

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#905]
_From @jstrachan on June 6, 2017 9:26_

if I'm on the Codebases / Pipelines / Apps / Environments page and switch between 2 spaces I'd have thought the UI should stay on the same space; not always go to the space overview page. Otherwise to switch between 2 spaces when looking at something in the Create site, we have to then navigate to Create then navigate to the tab we were on which feels clunky.

@catrobson does that sound a more natural UX to you? 

_Copied from original issue: fabric8-ui/fabric8-ui#1449_

**Comment by joshuawilson** [comment]
I do like that idea. If I'm planning and I need to add an issue to another space it would be better if the context switcher just switched the context and not my view too. 

I think the question we need to ask (and answer) is this; Why would a use change spaces?

**Comment by joshuawilson** [comment]
_From @jstrachan on June 8, 2017 17:6_

because you're working on different apps in different spaces and you want to switch between them (either planning / codebases / pipelines / apps / environments)?

**Comment by joshuawilson** [comment]
_From @catrobson on June 13, 2017 18:3_

I like this idea as well, but I think we need to think through what happens if I move over into a user context and then back to a space context.  Let me take a task to do a quick run-through of this so we make sure we have all scenarios/use cases covered for how to handle leaving the user in context as they switch between spaces and users.

**Comment by joshuawilson** [comment]
@catrobson were you able to look into this?

@qodfathr what do you think?

**Comment by qodfathr** [comment]
I'm not sure what I think of this. I can argue both for and against it. My recommendation is to hold off until we can A/B test it.

**Comment by serenamarie125** [comment]
@joshuawilson based on the quick win updates, i don't think this is applicable anymore.  Do you agree?  If so, can you please Close?

**Comment by joshuawilson** [comment]
What of the quick wins changes this? We still have the context menu and can change spaces.

**Comment by serenamarie125** [comment]
@joshuawilson I don't think we should be addressing this, given that we are making the IA changes.
