### ISSUE TITLE
Pipeline(s) not shown after creation over 'Add to Space'

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#906]
_From @joshuawilson on June 5, 2017 16:34_

_From @pkettman on June 5, 2017 14:30_

Steps:
Created a new project/codebase over 'Add to Space' with a selected pipeline
The pipeline is not available in OSIO Pipelines list

Reason:
The OSIO codebase was not linked to an expected default namespace pkettman, but to namespace pke-test1, which I had created previously while I testing the OSO.

https://gist.github.com/pkettman/b722228ae7bb67f282a7d1cc93d03711

_Copied from original issue: openshiftio/openshift.io#191_

_Copied from original issue: fabric8-ui/fabric8-ui#1445_

**Comment by joshuawilson** [comment]
_From @rawlingsj on June 5, 2017 17:41_

FWIW we worked around the issue by manually deleting the `pke-test1` openshift project and created a new one `oc new-project pkettman` but note this is not a solution.

**Comment by joshuawilson** [comment]
@rawlingsj do you have a proposed solution?

**Comment by joshuawilson** [comment]
_From @rawlingsj on June 5, 2017 19:36_

No proposed solution, my suggestion of deleting the existing users home namespace and recreating one which matched the username in keycloak worked but asking folks to do this themselves seems extreme.  

I guess when a user signs up with openshift.com they can choose their namespace name via `oc new-project foo` as long as it's unique where as openshift.io expects it to match their username in keycloak.

**Comment by joshuawilson** [comment]
maybe @alexeykazakov should be involved in this too

**Comment by joshuawilson** [comment]
_From @alexeykazakov on June 5, 2017 22:29_

Actually the init tenant service creates namespaces based on the OSO username. Not the Keycloak one. But currently the keycloak username == OSO username == developers.redhat.com username. We should improve our tenant namespace management in OSIO.

**Comment by joshuawilson** [comment]
_From @rawlingsj on June 5, 2017 22:38_

But in this case @pkettman already had an openshift.com account and had created a namespace called `pke-test1` which doesn't equal any username.  Therefore when @pkettman signed into openshift.io there's an incorrect assumption in the UI that the user had a namespace of `pkettman`.

To work around the issue we deleted the `pke-test1` and manually created a new one `pkettman` with oc new-project but that is a manual step we don't want to advise to users who already have an openshift.com account I'd have thought?  Or do we say if you already have an openshift.com account and namespace that you may need to delete it so that one that matches their username is created?

**Comment by joshuawilson** [comment]
_From @alexeykazakov on June 5, 2017 23:1_

I'm not sure what approach is better here. Ideally we should support existing namespaces I guess.
cc: @aslakknutsen @qodfathr.
What I'm saying is that it's rather an issue of how we manage namespaces. It's not related to SSO.

**Comment by joshuawilson** [comment]
@rawlingsj @alexeykazakov do either of you have a suggestion on how to fix this?

**Comment by joshuawilson** [comment]
@alexeykazakov fixed by the new proxy we are setting up?

**Comment by alexeykazakov** [comment]
The main issue here is that the use can create a namespace manually before OSIO initiates the tenant. It happens for example when users logs into OpenShift.com after approval and then starts creating projects before logging into OSIO. Then OSIO is screwed.
The OSO proxy won’t solve this problem.
This will be fixed if we refactor our registration flow and start initiating tenant as part of approval.

**Comment by alexeykazakov** [comment]
I think we can close this issue. This particular problem with this user was manually fixed. The general solution will be addressed as part of our multi cluster support effort - https://github.com/openshiftio/openshift.io/issues/948#issuecomment-345361433

**Comment by joshuawilson** [comment]
Thanks, closing.
