### ISSUE TITLE
when we deploy an app and we're out of quota we get a spinner which can be confusing

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#907]
_From @jstrachan on June 5, 2017 14:38_

here's an example:
<img width="1053" alt="fabric8_and_keycloak_account_management" src="https://cloud.githubusercontent.com/assets/30140/26788360/d53568dc-4a04-11e7-8927-90e9bc4939f5.png">

in this case we've created a Deployment with a replica count of 1 but no pods have been started yet. So we show a spinner. But when no pods have actually started; we maybe should show some kind of indication to the user that they are probably out of Quota which we could then link to the openshift quota page?

@catrobson am sure you'll have plenty to say on the overall UX of this page too ;) 

_Copied from original issue: fabric8-ui/fabric8-ui#1443_

**Comment by joshuawilson** [comment]
_From @jstrachan on June 5, 2017 14:38_

this is related too https://github.com/fabric8-ui/fabric8-runtime-console/issues/490

**Comment by qodfathr** [comment]
Closing as this screen is being removed. If we have a similar issue on #287 , we can open a new issue for that.
