### ISSUE TITLE
Can't open with Firefox on a Mac

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#908]
_From @joshuawilson on June 1, 2017 20:49_

_From @luebken on June 1, 2017 9:32_

Trying to open with Firefox on a Mac I got the following error:

```
Warning: Unresponsive script
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: https://openshift.io/_assets/l…f49acb8aeb061f0c40eb.bundle.js:1
```
<img width="1637" alt="screen shot 2017-06-01 at 11 29 40" src="https://cloud.githubusercontent.com/assets/53055/26673645/ee11faf4-46bd-11e7-83a7-1b7b2f20c2e9.png">

_Copied from original issue: openshiftio/openshift.io#188_

_Copied from original issue: fabric8-ui/fabric8-ui#1434_

**Comment by joshuawilson** [comment]
_From @maxandersen on June 1, 2017 11:21_

I don't get unresponsive script - I just don't get it loading at all on Firefox. Very weird.

Works for me in Chrome and Safari which would be the workaround.

Can you tell me if that works for you ?

also, I just used openshift.io - did you try another url ?

**Comment by joshuawilson** [comment]
_From @luebken on June 1, 2017 12:7_

I was able to reproduce it: I opened the pipeline history in a new tab.

<img width="1677" alt="screen shot 2017-06-01 at 14 05 04" src="https://cloud.githubusercontent.com/assets/53055/26678986/7f65ccbe-46d3-11e7-9d45-524e27dfd2fa.png">

**Comment by joshuawilson** [comment]
@mindreeper2420 can you reproduce this? (since you have a Mac)

**Comment by joshuawilson** [comment]
@luebken it looks like you tried to access https://openshift.io/_error. Did you get this error on that page or were you redirected to it?

**Comment by joshuawilson** [comment]
_From @mindreeper2420 on June 22, 2017 12:37_

@joshuawilson I get this:

![viewpipelineserror](https://user-images.githubusercontent.com/4032718/27434224-fdc4c6c0-5725-11e7-8577-4bde1c1b1fd4.gif)

**Comment by joshuawilson** [comment]
Did you click on something to get there? Or did you manually type in the URL

**Comment by joshuawilson** [comment]
_From @mindreeper2420 on June 22, 2017 15:30_

I clicked on the 'View Pipeline Runs' link, but by using cmd+click to open it in a new tab in the background. Just clicking on the link (no new tab) works fine.

**Comment by joshuawilson** [comment]
@luebken are you creating a new tab?
@mindreeper2420 we have an issue for new tab #1539

**Comment by joshuawilson** [comment]
@luebken @mindreeper2420 is this still an issue?

**Comment by mindreeper2420** [comment]
@joshuawilson @luebken I have no issue opening the Pipeline history in Firefox - either in the same window or a new tab. Firefox 56.0 on macOS 10.13.

**Comment by joshuawilson** [comment]
I'm going to close this. Please reopen if you are still seeing this issue.
