### ISSUE TITLE
add a "_notauthorized" page

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#910]
_From @jstrachan on May 24, 2017 14:42_

when using fabric8-ui on premise such as on minishift the user can login as a user who is not yet approved. On OpenShift.io we redirect to: https://manage.openshift.com/openshiftio which is fine.

However we probably need a little page we can use for on premise that basically says something like...

```
you are not authorized in KeyCloak

either try authorize user ${foo} in KeyCloak at this link or ask your administrator to approve your user
```

_Copied from original issue: fabric8-ui/fabric8-ui#1393_

**Comment by joshuawilson** [comment]
_From @alexeykazakov on May 24, 2017 16:49_

@jstrachan this redirect URL can be set via ALMIGHTY_AUTH_NOTAPPROVED_REDIRECT env var for the api service.

**Comment by joshuawilson** [comment]
_From @alexeykazakov on May 24, 2017 16:53_

if the env var is not set then a JSON with an error message: `user <username> is not approved` will be returned to the browser instead.

**Comment by joshuawilson** [comment]
_From @rawlingsj on May 24, 2017 16:57_

That's interesting, ok so until we have a not authorized page we can use that.  It's crude but explains what's happening rather than the redirect to the red hat developer site.

**Comment by joshuawilson** [comment]
We have an "error" page that I eventually plan to use for all redirects. It should take the error message and display it. However, how we do this is up to @fabric8io/uxd and @qodfathr

**Comment by joshuawilson** [comment]
_From @jstrachan on May 25, 2017 9:26_

@alexeykazakov thanks for the heads up! I've switched the default now to leave `ALMIGHTY_AUTH_NOTAPPROVED_REDIRECT` blank so it generates the JSON. 

Though I prefer having a single static HTML page for not-approved, its a nicer UX; then we can give the user more meaningful nice HTML as to what not approved means and how to work around it (e.g. instructions on how to approve someone in KeyCloak etc). Maybe one day we could add a button to raise an issue to approve the user on more real systems?

@joshuawilson I'd rather not use a generic error page as its not really that the system failed; its that we know the user is not marked as approved in keycloak so would prefer a little HTML page to provide a better UX really.

**Comment by joshuawilson** [comment]
@mindreeper2420 aren't you working on something related to this?

**Comment by mindreeper2420** [comment]
There is currently a UX story in place for a design of a ‘not authorized’ page. 

fabric8-UX story: https://github.com/fabric8-ui/fabric8-ux/issues/686

**Comment by joshuawilson** [comment]
Where is it hosted at that it is not in prod yet?

**Comment by alexeykazakov** [comment]
@joshuawilson it's openshiftio app. It was merged pretty long time ago https://github.com/openshiftio/openshift.io/pull/1701 and https://github.com/openshiftio/openshift.io/commit/95b1972ba19c15722ad6921a299ee4143aaf5d49 and it's available in preview https://prod-preview.openshift.io/not-authorized.html
But it's still not deployed to prod. So it's not available in https://openshift.io/not-authorized.html
I've created https://github.com/openshiftio/saas-openshiftio/pull/542 to deploy it to prod.

**Comment by joshuawilson** [comment]
merged the PR, closing this.

**Comment by joshuawilson** [comment]
thanks
