### ISSUE TITLE
the Finish button should not need to invoke Validate again if there's been no change

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#911]
_From @jstrachan on May 23, 2017 13:37_

if you change a field on the first page and tab, it validates. Then if I click `Finish` it validates again. It'd be nice to avoid this extra validation; as validation is kinda slow ;) 

_Copied from original issue: fabric8-ui/fabric8-ui#1380_

**Comment by joshuawilson** [comment]
I'm guessing this is for the App Wizard.

**Comment by joshuawilson** [comment]
_From @jstrachan on May 25, 2017 7:23_

ah yeah sorry! :) this is the app wizard - lemme create a label for that to make it a bit more clear what issues relate to it

**Comment by corinnekrych** [comment]
it's fixed with https://github.com/openshiftio/openshift.io/issues/966
