### ISSUE TITLE
Help link top right should link to documentation

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#912]
_From @catrobson on May 23, 2017 11:34_

Help link in username dropdown should link to documentation, not Fabric8 documentation online.  Documentation link location:  https://access.redhat.com/documentation/en-us/red_hat_openshift.io/1/html-single/user_guide.

_Copied from original issue: fabric8-ui/fabric8-ui#1378_

**Comment by joshuawilson** [comment]
That link returns a 404 page and after looking around I can't find the correct link there.

**Comment by joshuawilson** [comment]
@catrobson That link you provided doesn't work. Can you please provide the correct link?

**Comment by joshuawilson** [comment]
@rkratky I think this issue fits with the work you are doing.

**Comment by rkratky** [comment]
@joshuawilson, the docs will be at docs.openshift.io. I believe this link can be considered final.

**Comment by joshuawilson** [comment]
Thanks @rkratky.
@mindreeper2420 can you add this to your list, please.

**Comment by mindreeper2420** [comment]
@joshuawilson - where is the documentation located? I’ve not seen nor heard of any.

**Comment by joshuawilson** [comment]
@mindreeper2420 as @rkratky stated they are at https://docs.openshift.io/

**Comment by mindreeper2420** [comment]
@joshuawilson @rkratky my bad! That is what happens when you look at GitHub on your phone 😎 . I'll file a PR for this today.
