### ISSUE TITLE
add a simple code browser/editor UI?

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#914]
_From @jstrachan on May 22, 2017 13:11_

we used to have this in the old fabric8-console; a way to browse & edit text files in git without firing up a full IDE. Its particularly handy for demos where you can instantly browse and edit code.

more of a long term thing really as it avoids having to wait for the Che workspace/service to come up etc

_Copied from original issue: fabric8-ui/fabric8-ui#1371_

Related upstream che issue - https://github.com/eclipse/che/issues/5006

**Comment by joshuawilson** [comment]
Interesting idea. You may want to also consider one of the many REPLs out there like Plunker as a source of inspiration.

**Comment by joshuawilson** [comment]
_From @jstrachan on May 23, 2017 7:5_

yeah - in https://github.com/fabric8io/fabric8-console we created a simple UI that looks and feels like navigating around a github repository; but keeping the fabric8 nav bar/UI so you can easily switch between source, pipelines, apps, environments etc. Its kinda handy really; though Che is our IDE - there's times an editor is handy. I still find myself doing some changes just in the github.com site ;)

**Comment by joshuawilson** [comment]
_From @pmuir on May 23, 2017 14:9_

I think the Che team also want to provide an embeddable version of Che... @l0rd

**Comment by joshuawilson** [comment]
_From @l0rd on May 23, 2017 15:23_

@pmuir I'm not sure if Che would fit here. We want to provide 3 flavors of Che:

**osio-ide**: that's openshit.io IDE
**fabric8-ide**: that's osio-ide that can run on your local minishift
**eclipse-che**: upstream Che that is configured to talk with the Docker API directly

And we can have these really quickly.

But, regardless of the flavour, Che is still more than an editor it's a coding workspace manager that is able to start stop containers.

**Comment by joshuawilson** [comment]
_From @gorkem on May 25, 2017 11:36_

This is a scenario we want to support eventually. You can follow up progress on https://github.com/eclipse/che/issues/5006. The trick is to back the embedded widget with a factory which will provide the workspace. I think a factory, combined with the new universal command palette https://github.com/eclipse/che/issues/4993 will be enough to reach all the functionality on the embedded mode. The only concern is the startup times for the workspaces which is actively worked on. Also I feel that embedded widget can have ways to optimize startup by omitting/delaying some functionality.

**Comment by ibuziuk** [comment]
Upstream issue https://github.com/eclipse/che/issues/5006

**Comment by ibuziuk** [comment]
Closing in favour of upstream che issue - eclipse/che#5006
