### ISSUE TITLE
after creating a new app, the `Analyze` tab is kinda confusing as you don't really get to see the new app/pipeline

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#916]
_From @jstrachan on May 17, 2017 16:22_

I wonder if we should default to taking the user to the Create tab (and maybe the Pipelines tag) so users can see their new app being built?

_Copied from original issue: fabric8-ui/fabric8-ui#1318_

**Comment by joshuawilson** [comment]
_From @jstrachan on May 17, 2017 17:13_

or maybe the wizard should prompt if the user wants to see the new pipeline and/or codebase?

**Comment by joshuawilson** [comment]
@qodfathr @catrobson what do you think?

**Comment by joshuawilson** [comment]
_From @catrobson on May 23, 2017 0:29_

We need to improve the dashboard to actually show the user what is happening rather than bring them to a different place in the application.  The dashboard should give me an overview of everything going on in the system which it doesn't do a great job of today.  Let's do an ideal design of this and drive towards better data and APIs that can show useful information rather than routing the user somewhere else.  UXD Issue:  https://github.com/fabric8io/fabric8-ux/issues/443

**Comment by joshuawilson** [comment]
@catrobson I'm assigning this to you until the designs are ready.

**Comment by joshuawilson** [comment]
@jstrachan there was a bug in the dashboard that prevented it from displaying. Can you please confirm that this is still an issue.

**Comment by joshuawilson** [comment]
_From @jstrachan on June 21, 2017 7:35_

Its still an issue.

If you are on the Analyse tab and you create a new app, once you click OK on the wizard it stays on the Analyse tab. You have to stare at the screen very carefully to spot that anything's really happened (you will hopefully detect something new happening in the Pipeline rectangle if your browser window is big enough to show that below the large stack report rectangle). 

I'd have thought it should take you to some Create page (Codebases / Pipelines) by default so its more obvious that a new app has been created and a pipeline triggered? Afterall you've been `Analysing` then decided to `Create` something; so staying on the `Analyse` page when you've created a Codebase and Pipeilne feels confusing to me at least - since you've made the first step to `Create` so it feels the UI should flow in that direction

**Comment by joshuawilson** [comment]
@jstrachan that makes sense. 

I think we still need @catrobson to come up with the updated designs and user flows to nail down what we do.

**Comment by joshuawilson** [comment]
_From @jstrachan on June 21, 2017 13:43_

totally agreed - this page could be the first page folks see when clicking on links on github projects; so we want a really slick lovely page!

Mind you we could probably add the functions we need (Fork repo, Create Codebase and/or create Workspace / and or Open Workspace, Import Pipeline)  using simple buttons for now until we replace the HTML layout with something slick from UX

**Comment by joshuawilson** [comment]
_From @jstrachan on June 21, 2017 13:44_

we'll also need to show `you are not logged into openshift.io; to be able to work on this codebase we recommend you  [Log In]` etc

**Comment by joshuawilson** [comment]
@catrobson @qodfathr are you considering a change in the flow?

**Comment by qodfathr** [comment]
As of today, the flow is essentially correct. We'll create new Scenarios as necessary, although we already know that the Analyze screen group is an area of future investment and we anticipate seeing big changes here future trains (likely by K). #1252 is still a significant issue, however.
