### ISSUE TITLE
how should we allow users to pick the upstream quickstarts in addition to the RHOAR ones?

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#917]
_From @jstrachan on May 13, 2017 10:33_

more of a UX question than anything else really. Right now we've 1 wizard which just uses the RHOAR wizards (vertx, spring boot, WF swarm) but we've loads more quickstarts we could let users use (node, php, C++, go, swift, ruby, python et al - together with camel/fuse quickstarts too).

So we maybe need a way to pick which 'set' of quickstarts to choose from first? Then we can let users pick from the available ones?

Or do we need a more sophisticated UI to let folks pick what quickstarts to be shown? e.g. we may want to disable upstream quickstarts for some users?

_Copied from original issue: fabric8-ui/fabric8-ui#1302_

**Comment by joshuawilson** [comment]
_From @jstrachan on May 13, 2017 10:34_

right now we have 2 separate wizards for RHOAR and upstream quickstarts; which isn't an awesome UX - wonder if we need a better combined wizard that groks all possible quickstarts with a nice way to filter/choose?

**Comment by joshuawilson** [comment]
@fabric8io/uxd What do you think?

**Comment by joshuawilson** [comment]
_From @catrobson on May 23, 2017 0:37_

+1 to reconsider the wizard.  UX Issue:  https://github.com/fabric8io/fabric8-ux/issues/444

**Comment by jstrachan** [comment]
now we've updated to the latest RHOAR addon we could look at trying to turn the current upstream quickstarts into boosters; no clue whats involved in that mind you ;)

**Comment by joshuawilson** [comment]
@krishnapaparaju I think this fits into what you are trying to do.

**Comment by slemeur** [comment]
No I think we should be closing this issue as this would need to be revisit along with the ability to bring more boosters to OSIO.
