### ISSUE TITLE
have a canonical openshift.io console URL for a github repo and/or branch...

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#918]
_From @jstrachan on May 13, 2017 10:28_

which when opened in a browser would present the user with the options to:

* create or open a Che workspace for the git repo
* import the project as a Pipeline so that it can built/ran 
* fork the repo to another organisation (then do the above)

e.g. a URL something like `https://openshift.io/github/owner/repo/[branchOrTag[/filePath]]` so that its super easy to link to a git repo and/or branch and/or file so that it can be easily opened in a Che workspace or built etc.

We should maybe support other git URLs too I guess as well: 

    https://openshift.io/open?url=https:/....&branch=foo&file=foo/bar/Cheese.java

We can then:

* generate an `openshift.io it` button that folks can add to github repos so folks can one click open/run/build in openshift.io (like other buttons on github like the javadoc button etc like here: https://github.com/fabric8io/kubernetes-client/blob/master/README.md
* provide a Chrome plugin to `openshift.io it` like the IDEA Chrome plugin that adds an open in IDEA button to github projects https://chrome.google.com/webstore/detail/jetbrains-toolbox-extensi/offnedcbhjldheanlbojaefbfbllddna?hl=en

_Copied from original issue: fabric8-ui/fabric8-ui#1301_

**Comment by joshuawilson** [comment]
_From @jstrachan on May 13, 2017 10:29_

we could implement this page using the component/code from #1290 as well - but also to add the ability to import a BuildConfig so it can be built/deployed on your tenant etc

**Comment by joshuawilson** [comment]
_From @pmuir on May 19, 2017 14:51_

Codenvy Factories are relevant here.

**Comment by joshuawilson** [comment]
@jstrachan @pmuir @maxandersen @catrobson 
Where would these URLs be set/stored/used? Would they be a link on the Codebases page?

**Comment by joshuawilson** [comment]
_From @jstrachan on June 21, 2017 7:14_

We'd be able to use these URLs inside README.md files on github projects for example. Or on wiki pages. Links are kinda handy on the internet to link to things from anywhere. They could be used as links in commits / PRs in the planner when we populate PRs/commits from github too; or as links on Deployments / Pods in the runtime views (as we know the github repo and commit sha of the running code).

Then we could create a Chrome plugin to add an `openshift.io` button to all projects on github just like you can get an IDEA button on all github projects via this plugin: https://chrome.google.com/webstore/detail/jetbrains-toolbox-extensi/offnedcbhjldheanlbojaefbfbllddna?hl=en

**Comment by joshuawilson** [comment]
Maybe I'm missing something. The only way I can see to do this is to set up routes to go to those URLs. 

OR they would be artificially created and stored but not really usable. Meaning `https://openshift.io/github/owner/` would be dead.

If you want every level active then aren't we duplicating github?

I do think the idea has merit, I just don't understand how to do it.

**Comment by joshuawilson** [comment]
_From @jstrachan on June 21, 2017 13:34_

I think you've misunderstood me completely :) Lemme try again! 

All I'm talking about is using the usual Angular router to create a single HTML page inside fabric8-ui for viewing github repos (optionally branches) from which we can offer the user options to Fork, Open in Che, import as a Pipeline options etc. 

The actual URL we use doesn't matter. Given `https://openshift.io/{entity}/{space}` is reserved for a username and optional space and we've been using `https://openshift.io./_home` and `https://openshift.io./_getstarted` as magic pages we could either: 
* use `https://openshift.io./_github/{orgName}/{repoName}(/{branch})` as a new magic page
* make the 'github' entity special and override the angular routing rules so that we can use `https://openshift.io./github/{orgName}/{repoName}[/{branch}]` without clashing with the current create/analyse pages

 The former is probably simpler  but just with slightly less cool URLs :)

Then from a given URL like, say, `https://openshift.io./_github/jstrachan/demo123` we will know the full github URL, the org, repo name and branch; so can then (if the user clicks the right button) create a Codebase, fork the repo, import a pipeline with a few clicks (mostly just selecting which Space to put them in or which github org to fork to)

**Comment by ibuziuk** [comment]
Closing as outdated
