### ISSUE TITLE
create an Angular component to link to view/open/create a workspace for a git URL and optional branch/sha

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#919]
_From @jstrachan on May 11, 2017 14:37_

e.g. on a Pipeline / BuildConfig / Deployment / Work Item we may be able to find the github URL, branch and possibly Che stack ID.

It would be nice to be able to link to a single page via "Open In Che" links around the UI which would then:

* check to see if there is a workspace already for the given git URL, branch and stack ID and if so open it
* if not prompt the user to create a workspace; when its ready let them open it.

i.e. similar to the behavior of the Codebases UI; but letting folks link to a codebase page without knowing what the codebase is yet - just knowing the git URL, branch, stack

Once we've something like this we can then add an 'Open in Che' link to the Pipelines page for example

_Copied from original issue: fabric8-ui/fabric8-ui#1290_

**Comment by joshuawilson** [comment]
_From @jstrachan on May 11, 2017 14:45_

@dlabrecq wonder if you had a clue here? the basic issue is when viewing, say, a Pipeline, WorkItem, Deployment or some other resource we may find a git URL / branch / che stack; but not be aware if there's a Codebase/Workspace for it yet. 

So figure we could just have a page we link to that then wraps up looking for the corresponding codebase/workspace and supports lazily creating one on the fly (maybe with the user confirming if they wanna add the codebase etc). 

We can also then link to this page when using the Space wizard to create a new page?

**Comment by joshuawilson** [comment]
_From @dlabrecq on May 11, 2017 20:8_

We currently have the ability to retrieve a list of the user's codebases which can be iterated over to match a GitHub URL. If a match is found, we can easily open Che. 

(It's my understanding that the Che APIs don't accept a branch. The user must select a branch within Che.)

If there is no matching codebase, you can create one providing you have a GitHub URL. If you're suggesting a GitHub URL is always available, I suspect all this could be done via a service instead of a new page.

If not, a modal could prompt the user to enter one? Although, I'll defer to the @catrobson here.

**Comment by joshuawilson** [comment]
_From @jstrachan on May 11, 2017 21:25_

I wonder if for now we can create a component like: 

    <open-codebase-link gitUrl='foo' branch='bar' stackId='abc'>Open Che<...>

Where everything but git URL is optional - we can then use this markup on pages like the pipelines & work items - then the implementation can lazily load the codebases to open a modal or whatever?

**Comment by joshuawilson** [comment]
_From @jstrachan on May 11, 2017 21:29_

Though a service to open the link may be easier too ;)

**Comment by joshuawilson** [comment]
@jstrachan is this still something you think we should pursue? I'm not clear on how this would work.
cc @maxandersen @catrobson

**Comment by joshuawilson** [comment]
_From @jstrachan on June 21, 2017 7:12_

yes I think we should still do it as there are going to be many places in the UI we need to 'open in Che'. In terms of how it would work I'm assuming its an angular component along the lines of
```
<open-in-che-link [gitUrl]="foo" [branch]="bar">Open in Che</open-in-che-link> 
```
or something like that. 

We'd like to use this on multiple Pipeline / Build / Deployment / Pod UIs for a start; am sure we could use it in the planner when we start supporting PRs or commits too.

**Comment by joshuawilson** [comment]
@ashumilova this is an interesting idea that is worth thinking about.

**Comment by maxandersen** [comment]
> @ashumilova this is an interesting idea that is worth thinking about.

There are no ashumilova references in this issue...wrong issue you commented on ?

**Comment by joshuawilson** [comment]
That is why I pinged her on it, so she can consider it for her work.

**Comment by maxandersen** [comment]
ack -  of course - I read it as a reply not a "ping" - my bad :)

**Comment by ibuziuk** [comment]
Closing as outdated
