### ISSUE TITLE
Feature request - Automated method for users to delete a project

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#920]
_From @ldimaggi on May 10, 2017 12:55_

(And also delete all a project's assets.)

Related to:  https://github.com/fabric8io/fabric8-ui/issues/1283

_Copied from original issue: fabric8-ui/fabric8-ui#1284_

**Comment by joshuawilson** [comment]
What do you mean by "project"? Is this in OpenShift or are you referring to Space?

What would the user workflow be for the scenario you listed?

**Comment by joshuawilson** [comment]
_From @ldimaggi on May 22, 2017 19:41_

This is related to the Spaces - where the user adds a project (such as a Vert.X HTTP Booster) to a space. It should be possible for a user to delete a project and by doing so also optionally have the project's assest (pipeline, github repo, etc.) deleted.  Thx!

**Comment by joshuawilson** [comment]
I agree we need to be able to have the "delete" clean up after it's self.

**Comment by jiekang** [comment]
There is environment reset and I think deletion of resources is being tracked in other issues. Can this one be closed @joshuawilson or is it still needed?

**Comment by joshuawilson** [comment]
I agree, closing.
