### ISSUE TITLE
Blue links on dark background are hard to read

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#921]
_From @rkratky on May 5, 2017 12:10_

Links rendered as blue text on dark background are difficult to read. The styling should be different.

![blue-links](https://cloud.githubusercontent.com/assets/6623103/25744913/99bf5ef0-319c-11e7-9737-319d42341e6c.png)

_Copied from original issue: fabric8-ui/fabric8-ui#1260_

**Comment by joshuawilson** [comment]
@catrobson @mindreeper2420 can you please take a look at this.

**Comment by joshuawilson** [comment]
_From @catrobson on May 23, 2017 0:39_

Yup, agreed it is hard to read.  Will get visual input.

**Comment by junezhang** [comment]
@catrobson @bdellascio Here are two designs for the improvement, one is same with the style of www.redhat.com, still use blue color on the dark background(reference link is here:https://www.redhat.com/en/success-stories/macquarie), but the blue color is #73bcf7, lighter than current one; the other one is using the white and underline style on the dark background. welcome feedback.

<img width="977" alt="link-color" src="https://user-images.githubusercontent.com/701009/31669456-bd24d5a0-b31a-11e7-9d8c-9d9dd01ceb97.png">

**Comment by catrobson** [comment]
@junezhang I think V1 is a good improvement to make the text more accessible and readable.  Would support moving forward with V1!

**Comment by joshuawilson** [comment]
@mindreeper2420 can you add this to your list.
