### ISSUE TITLE
Work item title moves to the second line in the Planner list view when navigating between Plan and Create tabs

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#926]
_From @nimishamukherjee on April 21, 2017 16:43_

1. Select a space
2. Select Plan tab (Analyze Plan Create)
4. Select Backlog
3. The work item title appears next to the ID
![beforenavigatingtocreate](https://cloud.githubusercontent.com/assets/1892722/25287284/6ec56686-26de-11e7-85c5-21477955c88e.png)
4. Select Create (Analyze Plan Create)
5. Select Plan tab (Analyze Plan Create)
6. Select Backlog 
7. The work item title appears in the second line
![afternavigatingtocreate](https://cloud.githubusercontent.com/assets/1892722/25287600/9cf30b2a-26df-11e7-80ea-ffeae9545582.png)

_Copied from original issue: fabric8-ui/fabric8-ui#974_

**Comment by joshuawilson** [comment]
reference notes on #1199 for further direction

**Comment by joshuawilson** [comment]
@michaelkleinhenz @nimishamukherjee this appears fixed to me, but since it is a planner issue I'm passing it back to you for confirmation.

**Comment by nimishamukherjee** [comment]
Created issue [1670](https://openshift.io/openshiftio/openshiftio/plan/detail/1670) for QE to verify.

**Comment by jarifibrahim** [comment]
@nimishamukherjee @joshuawilson This issue seems to be resolved.
