### ISSUE TITLE
Create Error page

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#929]
_From @joshuawilson on April 6, 2017 6:28_

We need to handle Error when pages don't load. 

Use this design. https://redhat.invisionapp.com/share/VTB0FR05Z

_Copied from original issue: fabric8-ui/fabric8-ui#536_

**Comment by joshuawilson** [comment]
_From @catrobson on April 12, 2017 19:32_

There are additional error page situations that you can see here:  https://redhat.invisionapp.com/share/UQB3HEXFN

**Comment by joshuawilson** [comment]
@catrobson since all the pages look the same except for the text, I thought we could change that on the fly as needed.

**Comment by joshuawilson** [comment]
_From @catrobson on April 13, 2017 16:4_

Yup - makes sense to me @joshuawilson

**Comment by joshuawilson** [comment]
We have the error page but we need the flow that gets a user to it. In most cases if something doesn't exist we redirect them. 
What flows would bring a user to an error page.

**Comment by qodfathr** [comment]
The error page has been created, so technically this issue can be closed. If we need user flows for other kinds of errors, each one of those should get its own issue (and a common parent Scenario).
