### ISSUE TITLE
Validate username is ok

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#932]
_From @pmuir on March 28, 2017 20:27_

usernames may only contain lower-case letters, numbers, and dashes. They may not start or end with a dash. Max 63 chars in length.

_Copied from original issue: fabric8-ui/fabric8-ui#382_

**Comment by joshuawilson** [comment]
@SMahil please verify this has been completed and close or fix it.

**Comment by joshuawilson** [comment]
_From @SMahil on June 15, 2017 5:17_

Sure @joshuawilson

**Comment by joshuawilson** [comment]
_From @SMahil on June 15, 2017 7:0_

@joshuawilson Currently we are taking the usernames directly for RedHat login system. Where/on which page you want me to put the validation?

**Comment by joshuawilson** [comment]
_From @alexeykazakov on June 15, 2017 7:7_

We used to allow editing usernames. Then we disabled it.

**Comment by joshuawilson** [comment]
@alexeykazakov is there any thought to allowing it again, if so we can make sure the logic is there and then close this.

**Comment by joshuawilson** [comment]
_From @alexeykazakov on June 15, 2017 16:56_

Yes, our intention is to allow to change usernames. The first step would be to allow to change it only once right after registration/first login. But eventually we would like to allow change the username anytime. Our sso supports it. The problem is in opensfhit namespace names which are currently based on OSO usernames which we don't control. As soon as we improve our tenant namespace management we can enable username editing again. So, +1 to keep UI verification in a good shape. We will need it later.

**Comment by joshuawilson** [comment]
@SMahil on the "gettingStarted" page that you go to when you first login, there is a place that you can change your username. Though as has been stated, it is currently disabled. You can turn it on to work with it but leave it off when you

**Comment by joshuawilson** [comment]
_From @SMahil on June 19, 2017 7:1_

@joshuawilson this functionality is already there. I have questions. Can a username start with a number ? Are we allowing uppercase characters in username?

**Comment by joshuawilson** [comment]
@alexeykazakov can you define the exact list of requirements for the user name?

**Comment by joshuawilson** [comment]
_From @alexeykazakov on June 19, 2017 21:47_

@pmuir has already specified requirements :) See the description of the issue:

> usernames may only contain lower-case letters, numbers, and dashes. They may not start or end with a dash. Max 63 chars in length.

To be clear. We don't have any technical limitations from sso. Any string can be a username. But usernames are part of URLs so they should be URL-friendly. And maybe @catrobson can add anything from the UX point of view.

**Comment by qodfathr** [comment]
@joshuawilson @alexeykazakov @SMahil anyone want to confirm if this old issue is addressed?

**Comment by alexeykazakov** [comment]
We do not support changing usernames in OSIO. And I don't think we will be able to support it soon. I'm closing this issue since there is nothing to validate in UI for usernames.
