### ISSUE TITLE
Profile picture should come from github

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#934]
_From @catrobson on February 23, 2017 19:12_

The profile picture is not being carried in from github correctly:

![image](https://cloud.githubusercontent.com/assets/3739227/23274820/1977a7e0-f9d2-11e6-8694-0a772bd4e736.png)

_Copied from original issue: fabric8-ui/fabric8-ui#193_

**Comment by joshuawilson** [comment]
_From @pmuir on February 24, 2017 13:19_

@catrobson I will need to borrow you or your account to reproduce.

**Comment by joshuawilson** [comment]
_From @catrobson on February 24, 2017 17:38_

After discussion with @alexeykazakov, the current profile picture is being carried in from gravatar.  We don't ask the user before doing this, so its a bit hard for the user to identify where this mysterious profile picture came from.

Instead, I propose that we have a blank state image for the profile picture until we link to the user's github account.  Upon the github link, we will bring in the users profile picture from github.

Issue for UXD to create a blank state profile picture:  https://github.com/fabric8io/fabric8-ux/issues/224

**Comment by joshuawilson** [comment]
_From @pmuir on March 17, 2017 1:0_

I'm not actually clear where the image is coming from now that we get the user record from developers.redhat.com.

However, @catrobson we now have the ability for the user to update their image by providing a new URL. We can't implement image storage atm. Can you think about how we present that UX?

**Comment by joshuawilson** [comment]
_From @catrobson on April 12, 2017 20:21_

@alexeykazakov - can you describe where we currently stand with this?  Where are we getting the user profile image from by default before the user attempts to change it?

**Comment by joshuawilson** [comment]
_From @alexeykazakov on April 20, 2017 1:43_

@catrobson sorry, I missed your question somehow. Currently we generating a gravatar URL based on user's email.

**Comment by joshuawilson** [comment]
@catrobson what do we want to do here? Do we need to add something to the profile to allow the user to point to another image?

**Comment by joshuawilson** [comment]
_From @catrobson on June 17, 2017 10:42_

I think there are a few options:
Option 1:  Pull the user profile image from one of the OATH accounts (github most likely for now, eventually we would use a Red Hat one used for login
Option 2: Only allow for user uploaded profile images.

If we go the way of Option 2, it might be work we throw away as we get a proper "Red Hat Account" set up with picture, profile information, etc.  I'm not sure if there is a clean and clear way to do Option 1 for now - I need some technical feasibility and constraints to work with on the design if we go with Option 1.

**Comment by qodfathr** [comment]
Addressed, as we now have a way for people to update their profile with whatever image URL they want. (Although, to be fair, that functionality is very buggy right now and I have security concerns which need to be discussed.)
