### ISSUE TITLE
[5] Initial ingestion of Go ecosystem

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#939]
# Description
We want to start ingesting Go ecosystem. Initial run will probably reveal some bugs, so we can start small, let's say with 1000 packages (not components) and fix bugs. Then we can target 10% (for now) of Go packages hosted on GitHub (as there is no "Maven Central" for Go).

# Acceptance criteria
- [ ] 10% of the Go packages hosted on GitHub is analysed and available in production S3 buckets

**Comment by fridex** [comment]
Blocked until https://github.com/openshiftio/openshift.io/issues/686

**Comment by fridex** [comment]
Relavant: https://github.com/openshiftio/openshift.io/issues/952

**Comment by msrb** [comment]
Starting small in staging environment. If everything goes well there I will schedule bigger batch in production so workers are busy over the weekend.

**Comment by msrb** [comment]
First observation: anitya task is failing - which is weird because it shouldn't be executed for Go ecosystem.

**Comment by fridex** [comment]
> First observation: anitya task is failing - which is weird because it shouldn't be executed for Go ecosystem.

Looks like logical error: https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/394

**Comment by msrb** [comment]
I can see errors like following in jobs service:
```
2017-10-18 08:21:52,579 - Couldn't get latest commit for github.com/grafana/grafana/pkg/social
```

This is not just the jobs service, we will have similar problems on worker level as well. Perhaps we should `go get` the package, instead if trying to use git directly.

**Comment by jpopelka** [comment]
You're right, many of the [packages](http://go-search.org/api?action=packages) don't point to the main repo, but to a directory in it
For example source code of "github.com/bradfitz/gomemcache/memcache" lives in "memcache" directory of https://github.com/bradfitz/gomemcache repo.

Regarding `go get`: not sure we can get older revision of a package, since I don't see anything like that in `go get --help`

**Comment by msrb** [comment]
@tuxdna PR merged 😉 thanks. Could you please try to analyze couple hundred Go packages in staging to see how it goes?

**Comment by tuxdna** [comment]
It seems like our Go ingestion is working well. All the Golang packages which were scheduled by Jobs API, ended up in graph storage. For more details do look at this gist:

 * https://gist.github.com/tuxdna/615db46b337f24c28a3c7dede2f0bbe1#file-readme-md

There were was one error encountered in logs which is reported in this issue: https://github.com/openshiftio/openshift.io/issues/1299

Another thing to note is that, all the packages which were scheduled by the Jobs API, had only three components to golang packages i.e. `github.com/<some_org>/<some_name>`. This essentially means that Jobs API didn't schedule any package which should be present in a sub folder of a git repo such as `github.com/flynn/flynn/bootstrap`.

**Comment by tuxdna** [comment]
I scheduled another ingestion job for 400 go packages. It turns out that many packages are not getting scheduled due to error similar to following:

```
Couldn't get latest commit for github.com/astaxie/beego/session
```

As in previous comment, any go package name that contains more than two components, `github.com/astaxie/beego/session` fails. An issue has been filed here: https://github.com/fabric8-analytics/fabric8-analytics-jobs/issues/208

**Comment by tuxdna** [comment]
So far following sequence of Go packages were scheduled:

 * 400
 * then 400
 * then 20000
 * then 40000 ( yesterday )

As of now `20207` have been ingested from 40000 scheduled recently. This should account for over 10% of total Go packages.

**Comment by tuxdna** [comment]
It is 24287 packages as of now i.e. 100 * 24287 / 756881 = 3.2 %

**Comment by tuxdna** [comment]
It is 24287 packages as of now i.e. 100 * 31321 / 756881 = 4.13816 %

**Comment by msrb** [comment]
Good progress here, thanks @tuxdna 😉

**Comment by tuxdna** [comment]
It is 32894 packages as of now i.e. 100 * 32894 / 756881 = 4.3459 %

**Comment by miteshvp** [comment]
Graph being our OLTP, I guess we should share the statistics keeping pacakges synced to graph. WDYT? @msrb @tuxdna

**Comment by msrb** [comment]
@miteshvp I am all for it. But I am not sure how to get the numbers :) Could you please share the steps how to get them?

**Comment by tuxdna** [comment]
It is 71928 packages as of now i.e.100 * 71928 / 756881 ~= 9.5 %

**Comment by tuxdna** [comment]
It is 74664 packages as of now i.e. 100 * 74664 / 756881 ~= 9.86 %

**Comment by msrb** [comment]
Note I can see there is almost 100k messages in ingestion queues. The chances are that we won't be able to process significant portion of them in time and they will timeout (after 14 days in queues).

It should be possible to [specify range of packages](https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/f8a_jobs/handlers/golang_popular_analyses.py#L81) that should be analyzed, i.e. not start from zero every time.

`count` parameter can be number or dash-separated range, e.g. `80000-100000`.


https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/f8a_jobs/handlers/golang_popular_analyses.py#L81

**Comment by msrb** [comment]
We will reach the 10% goal by the end of the sprint though.

**Comment by msrb** [comment]
We are at 81730, which is ~10.8%, and still counting...

Thanks @tuxdna 😉
