### ISSUE TITLE
[5] Better CVE data for Maven ecosystem

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#940]
# Description

DependencyCheck has a good support for Java/Maven, but since it relies on NVD, the process of determining whether component is vulnerable or not involves guessing of CPE names. Also the data in NVD are not always accurate. We want to find a better source of CVE data for Maven and either replace DependencyChcek (and NVD) completely or use this new source alongside existing implementation.

Note one candidate could be https://github.com/victims/victims-cve-db (http://www.victi.ms/about.html).

# Description
- [x] document describing pros and cons of all evaluated sources is created; it also contains reasoning behind the final decision
- [x] CVE data for Maven in S3 are coming from the new source, or the new source is used in addition to the existing one
- [x] code runs in production

**Comment by jpopelka** [comment]
Do we actually have any examples of maven packages with wrong security scans ?
Because I don't recall any problems with security scans of maven packages.

**Comment by jpopelka** [comment]
> Note one candidate could be https://github.com/victims/victims-cve-db (http://www.victi.ms/about.html).

Since https://github.com/victims/victims-cve-db/pull/95 the data will be [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0) licensed, which as I understand it means, that if we used victims-cve-db in our security scans, we'd need to distribute the resulting data under the same license.

**Comment by msrb** [comment]
> Since victims/victims-cve-db#95 the data will be CC BY-SA 4.0 licensed, which as I understand it means, that if we used victims-cve-db in our security scans, we'd need to distribute the resulting data under the same license.

Which, I think, is not a problem (?)

**Comment by jpopelka** [comment]
I've created a CLI for searching victims-cve-db, see [PR#96](https://github.com/victims/victims-cve-db/pull/96)

**Comment by jpopelka** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/420

**Comment by jpopelka** [comment]
The only evaluated source has been [Victims CVE DB](https://github.com/victims/victims-cve-db).
Pros are that there are vulnerabilities which are not in NVD (thus not reported by OWASP DependencyCheck).
Cons are that (by words of one of the interested people) "it has since rotted away because it requires a lot of manual work".
So I decided it would be nice to use it just as an addition to the existing solution (DependencyCheck).

The task will be completed once https://github.com/openshiftio/saas-analytics/pull/149 is merged.
