### ISSUE TITLE
[3] Setup Python linter as a separate job on CentosCI

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#941]
Currently we run Python linters (on bayesian-common and bayesian-server ATM) as part of the 'main' CI job, which is not the perfect solution, because users can see just one message for each PR that is related to checking and testing:

```All checks have passed
1 successful check```

It would be better to separate this part into new jobs and use the different label for such jobs.

**Comment by pkajaba** [comment]
jobs are ready for each active repository. Marking it as done.
