### ISSUE TITLE
[13] Setup Python linter for all relevant fabric8-analytics repositories

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#942]
# Description

In order to remove any unnecessary coding errors and automate error checking (see https://github.com/openshiftio/openshift.io/issues/829), we would like to run linters on every PR.

# Acceptance criteria

- [x] all repos respect one unified configuration of code linters that is shared across the whole team
- [x] PRs are checked in CI (depends on https://github.com/openshiftio/openshift.io/issues/941)

All pull requests in the following repo listing are checked against the output of linters:

- [x] fabric8-analytics-server
- [x] fabric8-analytics-worker
- [x] fabric8-analytics-common
- [x] fabric8-analytics-stack-analysis
- [x] fabric8-analytics-license-analysis
- [x] fabric8-analytics-jobs
- [x] fabric8-analytics-tagger
- [x] fabric8-analytics-data-model
- [x] fabric8-analytics-recommender

# Tracking of individual steps:

## fabric8-analytics-server
- [x] linter script and configuration are in the repository
- [x] CI job is setup
- [x] all linter warnings are fixed
- [x] all linter errors are fixed

**Related issues**
- [x] #856 

## fabric8-analytics-worker
- [x] linter script and configuration are in the repository
- [x] CI job is setup
- [x] all linter warnings are fixed
- [x] all linter errors are fixed

**Related issues**
- [x] #1026

## fabric8-analytics-common
- [x] linter script and configuration are in the repository
- [x] CI job is setup
- [x] all linter warnings are fixed
- [x] all linter errors are fixed

## fabric8-analytics-stack-analysis
- [x] linter script and configuration are in the repository
- [x] CI job is setup
- [x] all linter warnings are fixed
- [x] all linter errors are fixed

## fabric8-analytics-license-analysis
- [x] linter script and configuration are in the repository
- [x] CI job is setup
- [x] all linter warnings are fixed
- [x] all linter errors are fixed

**Related issues**
- [x] #1013

## fabric8-analytics-jobs
- [x] linter script and configuration are in the repository
- [x] CI job is setup
- [x] all linter warnings are fixed
- [x] all linter errors are fixed

**Related issues**
- [x] #1003

## fabric8-analytics-tagger
- [x] linter script and configuration are in the repository
- [x] CI job is setup
- [x] all linter warnings are fixed
- [x] all linter errors are fixed

## fabric8-analytics-data-model
- [x] linter script and configuration are in the repository
- [x] CI job is setup
- [x] all linter warnings are fixed
- [x] all linter errors are fixed

**Related issues**
- [x] #1004

## fabric8-analytics-recommender
- [x] linter script and configuration are in the repository
- [x] CI job is setup
- [x] all linter warnings are fixed
- [x] all linter errors are fixed

**Comment by fridex** [comment]
Relevant (possibly duplicate): https://github.com/openshiftio/openshift.io/issues/829

**Comment by tisnik** [comment]
@fridex yes, #829 seems to be an Epic for #942 and #943 as well
