### ISSUE TITLE
Creation of new build pipeline can require up several minutes before providing feedback to user in OSIO UI

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#945]
See attached Jenkins pod log - when a new project is added into the user's space, and a new build pipeline is created, it is taking up to 3 minutes for a Jenkins Pod to be scheduled - in an otherwise idle user account.

Steps to recreate:
* Reset user environment
* Create new space
* Create new quickstart project

```
Sep 19, 2017 6:50:41 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
INFO: Waiting for Pod to be scheduled (29/100): jenkins-slave-4ml2n-f40rk
Sep 19, 2017 6:50:47 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
INFO: Container is waiting jenkins-slave-4ml2n-f40rk [jnlp]: ContainerStateWaiting(message=null, reason=ContainerCreating, additionalProperties={})
Sep 19, 2017 6:50:47 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
INFO: Container is waiting jenkins-slave-4ml2n-f40rk [maven]: ContainerStateWaiting(message=null, reason=ContainerCreating, additionalProperties={})
Sep 19, 2017 6:50:47 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
INFO: Waiting for Pod to be scheduled (30/100): jenkins-slave-4ml2n-f40rk
Sep 19, 2017 6:50:48 PM hudson.TcpSlaveAgentListener$ConnectionHandler run
INFO: Accepted JNLP4-connect connection #1 from /10.131.52.1:42804
[jenkins-2.log.txt](https://github.com/openshiftio/openshift.io/files/1315668/jenkins-2.log.txt)
Sep 19, 2017 6:50:54 PM hudson.slaves.NodeProvisioner$2 run
INFO: Kubernetes Pod Template provisioning successfully completed. We have now 2 computer(s)
```

## Impacts
- [ ] #2155 CI Experience placeholder

**Comment by ldimaggi** [comment]
[jenkins-2.log.txt](https://github.com/openshiftio/openshift.io/files/1315669/jenkins-2.log.txt)

**Comment by joshuawilson** [comment]
@jstrachan this looks like something for you. If not please redirect.

**Comment by aslakknutsen** [comment]
Trying to figure out what happened between 18:47 and 18:50. Unknown at this point.

```
2017-09-19T18:53:08Z	Killing container with id docker://jnlp:Need to kill Pod
2017-09-19T18:53:37Z	Killing container with id docker://maven:Need to kill Pod
2017-09-19T18:53:51Z	Error syncing pod
2017-09-19T18:50:42Z	Started container
2017-09-19T18:50:41Z	Successfully pulled image "fabric8/maven-builder:2.2.297"
2017-09-19T18:50:46Z	Created container
2017-09-19T18:50:46Z	Successfully pulled image "fabric8/jenkins-slave-base-centos7:0.0.1"
2017-09-19T18:50:42Z	Created container
2017-09-19T18:50:42Z	pulling image "fabric8/jenkins-slave-base-centos7:0.0.1"
2017-09-19T18:50:37Z	pulling image "fabric8/maven-builder:2.2.297"
2017-09-19T18:50:47Z	Started container
2017-09-19T18:49:31Z	Pod sandbox changed, it will be killed and re-created.
2017-09-19T18:49:29Z	Error syncing pod
2017-09-19T18:47:45Z	Successfully assigned jenkins-slave-4ml2n-f40rk to ip-172-31-69-112.us-east-2.compute.internal
```

**Comment by ldimaggi** [comment]
Another log - about 4 min to get the pipeline running - see attached log.
[another_jenkins_pod_log.txt](https://github.com/openshiftio/openshift.io/files/1316239/another_jenkins_pod_log.txt)

**Comment by aslakknutsen** [comment]
Seems to suffer a lot from quota issues:

```
pods "jenkins-slave-7wgtp-6k7z2" is forbidden: exceeded quota: compute-resources-timebound, requested: limits.cpu=3,limits.memory=1536Mi, used: limits.cpu=3,limits.memory=1536Mi, limited: limits.cpu=4,limits.memory=2Gi.
```

**Comment by joshuawilson** [comment]
@ldimaggi are you still seeing this?

**Comment by ldimaggi** [comment]
Yes - this issue is still being seen.

**Comment by qodfathr** [comment]
@ldimaggi still an issue? If only one prod-preview, we have a new env/prod-preview label you may use.

**Comment by ldimaggi** [comment]
I think that we should close this bug in favor of this newer issue:  https://github.com/openshiftio/openshift.io/issues/1933

**Comment by maxandersen** [comment]
> I think that we should close this bug in favor of this newer issue: #1933

@ldimaggi how is this issue that is about openshift.io build issue related to #1933 that is about build issues on GKE ?

**Comment by maxandersen** [comment]
reopening as i'm also seeing very slow jenkins start build times on prod.

**Comment by ldimaggi** [comment]
Another data point - on Feb 2, late afternoon Boston time, I was seeing VERY slow response times - it improved later that evening.

**Comment by mishaone** [comment]
First time using prod-preview here and haven't had a build start yet (3 so far set to new).

**Comment by lordofthejars** [comment]
I am not sure if we can do much more for this now. We improved a bit the starting time by reducing the number of starting plugins, but maybe this should be something to be addressed for Build.Next?

**Comment by ldimaggi** [comment]
The problem has a couple of parts:
* There is no feedback to the user while the Jenkins slave is being allocated/spun up. Waiting several minutes with no feedback may cause some users to assume the build failed. 
* I think that we have to reassess this issue by tracking the startup time while the system is under load. We may see longer times for users. 
* The time is variable. For example, I just saw it require 6+ minutes when the system was relatively quiet. 6+ minutes is a long time for users to wait.

![screenshot from 2018-04-24 12-20-28](https://user-images.githubusercontent.com/642621/39200675-cc6b6ee0-47ba-11e8-805e-4384c10e36f3.png)

**Comment by lordofthejars** [comment]
Yes I understand what you mean, but I see not easy solution since we are
really tight to HW resources. Maybe as workaround we could provide a warni
g to user explaining why it takes so long?

**Comment by ldimaggi** [comment]
I think that would be adequate - the issue right now is that the user sees nothing until the "view log" link appears.

**Comment by ldimaggi** [comment]
Another recent example:

![screenshot from 2018-04-24 22-47-48](https://user-images.githubusercontent.com/642621/39223719-a21418c0-4811-11e8-987c-426c6725fa3d.png)

**Comment by catrobson** [comment]
@muruGanesan can you take a look into this and provide any suggestions?

**Comment by ldimaggi** [comment]
I'd vote for #2 - ideally we could show the user a progress-bar.

**Comment by muruGanesan** [comment]
@ldimaggi, I'm planning put all '3' together...

**Comment by qodfathr** [comment]
Maybe instead of saying "No stages have started" we can say something else which may help users to understand? Something like "Setting up build server." I'd avoid being too specific (i.e. don't say "Setting up Jenkins slave pod" or "Unidling jenkins master node"), because, even if more accurate, it's probably less understandable to the uninformed.

Is that potentially the quickest fix?

**Comment by muruGanesan** [comment]
@qodfathr, thanks, I will work on few options and come back.

**Comment by muruGanesan** [comment]
First-cut proposal

![osio-945_proposal-01](https://user-images.githubusercontent.com/26006817/39308243-963a1c3a-4982-11e8-83e7-edc10a619806.jpg)

**Comment by ldimaggi** [comment]
+1

I'd suggest changing "Hide and run at the background" to simply "Hide and run in background"

This looks good and will be very helpful!

**Comment by muruGanesan** [comment]
@qodfathr, @ldimaggi Thanks for your feedback.
Here is the updated version. 
NOTE: I will fine-tune Icon, font style & size etc... and provide the design elements tomorrow.

![osio-945_proposal-02](https://user-images.githubusercontent.com/26006817/39319228-19280e8e-499e-11e8-9172-b011f30e1252.jpg)

**Comment by joshuawilson** [comment]
Platform can assist since Build does not have anyone on the UI.
@christianvogt you want to try to do this?

Has the SVG been vetted by a visual designer? 
Has the copy been vetted?
cc @catrobson

**Comment by muruGanesan** [comment]
@joshuawilson 
The image has been created by a visual designer.  The base "clock image" (fa-clock-o) is from PatternFly but the green color 'pie' chart overlay should be based on the progress... it should increase.
But is a good idea to review with another visual designer.
@catrobson, can we review the icon with Kyle or Brain before implementation?

**Comment by joshuawilson** [comment]
So you want the green to animate? Did you state that above, I missed it.

**Comment by catrobson** [comment]
@muruGanesan If we animate the green in a circle, it would be a deterministic loader (we would need to know where we are between 0% and 100%).  I don't think we actually have this information to do this, which is why we had the spinning animation.  We could use the fa-clock statically, or move to a spinner animation, but I don't think we can do a full loading animation with a % complete.

**Comment by muruGanesan** [comment]
@joshuawilson, if possible we can animate based on the progress... It provides indication to the user that something happening... 

"Creating animation" is difficult or time consuming then we can use static image.

**Comment by muruGanesan** [comment]
@catrobson, we will use the 'fa-clock'.

**Comment by qodfathr** [comment]
I'm fine with moving ahead with this, however, thinking about this more, I think there is a more appropriate solution -- but let's consider it for a longer-term solution. At issue is the fact that we are attempting to show two very different statuses with one solution.

The first status is of the Jenkins server itself. And, today, that's universal across all of your build pipelines. In the future, there may be multiple build servers -- even multiple *types* of build servers -- but, let's ignore that for now. We used to use the Status Widget to tell you about the Jenkins master. I think we need to bring that information back -- but, since the status widget is gone, maybe there should be a visual indication at the top of the Pipelines Screen regarding the status of the Jenkins master associated with the account owning the displayed Space -- sleeping, starting, running, failed, etc.

I'm finding that I'm jumping over to the OSO console to see precisely this information. And the one thing that is missing even there is some sort of status for the state between 'the pod is started' and 'Jenkins is ready'. Something like: Idle -> Starting -> *Warming Up* -> Running. My builds will only be able to being once the master reaches the Running state (which is different that the pod running -- it's about Jenkins running and ready to go).

**Comment by catrobson** [comment]
@qodfathr - Thanks so much, I didn't put all the discussions around this together to tie together the different stages of what the user is waiting for here.  Your proposal to separate the Jenkins master idle state to running state from the pipelines running themselves makes a lot of sense to me, and having this all on the Pipelines page feels like it could pull this story together.  @muruGanesan I think this is worth considering if we are able to this week.  If not your info messages at least give a slightly better feeling than no information at all, and we can work towards this separation of status as a second step.

**Comment by bdellasc** [comment]
@muruGanesan @catrobson I agree RE: not overlaying the pie determinate indicator for the reasons Cat mentioned. 

One thing to keep in mind: for the [Tenant status indicator](https://redhat.invisionapp.com/share/ZFEP5QKXA#/266500220_00_PriorityOfStates) (which we're not using yet), we use the Clock to indicate "waiting" for the tenant. I feel like the spinner with the "this might take a while" messaging would be more a more accurate a visual representation than the clock icon. It sounds like things ARE happening, and it's the USER waiting, not the stuff on the back-end. This would also help us avoid using the same icon for two different statuses in the UI when we eventually implement the tenant status Indicator.

**Comment by maxandersen** [comment]
related to https://github.com/openshiftio/openshift.io/issues/3054

**Comment by muruGanesan** [comment]
@ldimaggi, @lordofthejars, @joshuawilson, @mishaone, @qodfathr, @maxandersen, @catrobson, @pradeepto, @bdellasc 

Please find the temporary UX proposal. i.e. provide feedback to the user [about the system's status]
![osio-945_proposal-03](https://user-images.githubusercontent.com/26006817/39474934-ce505874-4d73-11e8-97af-daafcad7cdbc.jpg)

**Comment by bdellasc** [comment]
@muruGanesan What size is the clock icon? I'm ok with going with this general direction if we can bring down the size of that clock icon a little. If you have a source file, I can do a quick visual pass on it.

**Comment by muruGanesan** [comment]
@bdellasc, I have not specified any size... since it is a vector (font) please go ahead and define the size as per the standard... Thanks for taking this up.

**Comment by bdellasc** [comment]
This is a different layout than anything else we have. For now, if we can just bring the clock down in size a little bit, I think that will be sufficient for now...

Icon color: #8B8D8F

If icons are defined in relative sizes (ems):
- If it's a 12px base font size, the clock icon should be: 2.3em
- If it's a 14px base font size, the clock icon would be 2em

If icons are defined in actual pixel sizes:
- I mocked this up at 28px

![openshiftio-945](https://user-images.githubusercontent.com/17882357/39722802-c6b418ba-5211-11e8-86f7-88ec5fece382.png)

**Comment by muruGanesan** [comment]
@bdellasc, would you be able to provide the icon (i.e.) as per the standard and close this issue?

**Comment by joshuawilson** [comment]
You shouldn't close the issue as the focus is not design. This requires a fix to be implemented before you can close it. 
If you are done with design, please remove designer from the assignee list and ping me.

**Comment by muruGanesan** [comment]
@joshuawilson, Please assign to an appropriate team...
Any UX support please reach out to me or @bdellasc

**Comment by joshuawilson** [comment]
@christianvogt can you take this on since build doesn't have anyone working UI?

**Comment by invincibleJai** [comment]
Thanks @muruGanesan @bdellasc for input. I have few doubts

1. In case of user have reached Quota limit and triggers a build, and we show above message won't it be again misleading? as that will never complete.

2. If user clicks on "Hide and run in background", will it hide the message and mostly be back to current scenario i.e blank?

**Comment by invincibleJai** [comment]
Thanks @muruGanesan it helps. Will reach out to you if needed.

**Comment by invincibleJai** [comment]
There are three steps here till stages appear

1. Builds gets triggered but not started i.e Jenkins log urls is not there

<img width="1635" alt="screen shot 2018-05-16 at 10 24 16 pm" src="https://user-images.githubusercontent.com/5129024/40159677-0814d002-59c8-11e8-8cb7-7c66da6dd756.png">

Above message looks good here.

2. Build is started i.e Jenkins log urls is there but stages have not started

<img width="1659" alt="screen shot 2018-05-17 at 11 53 08 am" src="https://user-images.githubusercontent.com/5129024/40159896-edccc898-59c8-11e8-996c-7410527cdb16.png">


We can have some different message here i.e "Build has started. Can view logs for more info." Something like this. @muruGanesan let me know if it makes sense.

2. Build is started and  stages have started

<img width="1653" alt="screen shot 2018-05-17 at 11 44 09 am" src="https://user-images.githubusercontent.com/5129024/40159782-5e43368a-59c8-11e8-9dd1-25fc6ba78c46.png">

and for 

>Quota limit reached = different scenario and the user should be redirected to take actions (like increase quota by purchase/delete some space) - I haven't covered in this issue.
Please refer: #2911

Thanks it looks nice, am not sure who is working on this. This can be triggered in build/launcher.

> "Hide and run in background" = this is a new proposal from UX wherein, the user can move away from the build/pipeline screen and continue his/her tasks... as soon as the build is ready/complete it will 'notify' user to come back.
[NOTE: it is a proposal from UX; Eng team can decide based on the feasibility]

It needs some more thoughts and it won't be feasible i think.

@muruGanesan let me know if it looks good or if you have some suggestion for no.2

**Comment by muruGanesan** [comment]
@invincibleJai,  Thanks. 

1) In step 2# : "Build has started. Can view logs for more info." - make sense...
2)

**Comment by krishnapaparaju** [comment]
@invincibleJai can you please update the current status.. thanks.

**Comment by invincibleJai** [comment]
@krishnapaparaju it has been fixed as suggested by @muruGanesan and changes are in prod.

**Comment by krishnapaparaju** [comment]
@invincibleJai we can close this issue..
