### ISSUE TITLE
login in with a new user still presents UX content from previous user

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#946]
_From @kbsingh on September 19, 2017 21:51_

Logged out from openshift.io via developers.redhat.com ( ie, logged out from both places ) - going back to openshift.io i am presented with login option. logging in with a different user this time, I still see content ( spaces's list, profile details ) from the previous user. Eventually this times out and I do get the correct details, but for some minutes, am unable to get to my own spaces, as the previous users details are still displayed.

_Copied from original issue: fabric8-services/fabric8-wit#1648_

**Comment by alexeykazakov** [comment]
This should be fixed. Please re-open if still can reproduce.
