### ISSUE TITLE
Benchmarks of core workers and their configuration

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#950]
# Description

We would like to check and evaluate performance on component level and on stack-analysis level. There are already present nice benchmarks done by @tisnik that does performance tests on worker side. These benchmarks track results and metadata info that are available in results we store on S3 (execution time of tasks that results are stored on S3), however we have some tasks that do not have direct results - they are used for creating required database entries, or general flow/metainfo bookkeeping.

The goal of this task is to identify weak parts and spot possible opportunities where we could optimize our analyses. Besides @tisnik's benchmarks, one could use Kibana dashboard to track what is going on in the system by checking [events that are done in the system](https://selinon.readthedocs.io/en/latest/trace.html). One could also apply [already known optimizations](https://selinon.readthedocs.io/en/latest/optimization.html) of a flow execution or design new ones. Having notion about [system's design](https://selinon.readthedocs.io/en/latest/internals.html) would be appropriate.

The outcome of this work can be either a document or (ideally) scripts that can use [directly ElasticSearch API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html) for querying to evaluate performance. Scripts can sit in a separate repo and should be agnostic to configuration of core workers so we can use the same code for different flows (component analysis, stack analaysis), in future if we decide to create new flows or anytime we raise concerns about execution time of tasks in the cluster.

# Acceptance criteria

- [ ] a document or scripts that could help us track execution time of tasks and check task's performance
- [ ] a list of possible time execution expensive tasks
- [ ] suggestions on how to optimize our workers

**Comment by miteshvp** [comment]
Not relevant
