### ISSUE TITLE
Work Item List: "Associate with Iteration" in Kebab Menu not working

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#951]
Despite re-associating an Iteration with the WI it is not reflected in the preview.

Please see the following screenshots.
![3](https://user-images.githubusercontent.com/16647625/30632137-aa2c4210-9e04-11e7-9400-91564f21e915.png)
![1](https://user-images.githubusercontent.com/16647625/30632138-aa2d7072-9e04-11e7-9782-412b9a874e32.png)
![2](https://user-images.githubusercontent.com/16647625/30632139-aa2fe0f0-9e04-11e7-9d11-4ad5ca902353.png)

**Comment by michaelkleinhenz** [comment]
Splitted up into seperate issues.
