### ISSUE TITLE
Spike around go package management

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#953]
# Description

The way how go programming language is treated in core is different. Go projects can directly use git repositories. However there are used package managers in community. [The official package manager](https://github.com/Masterminds/glide#golang-dep) in go ecosystem looks like in an early stage. Community also uses [glide](https://glide.sh/) package manager.

This spike should explore these package managers and state how complicated it would be to add support of these package managers to core workers, what needs to be done in which parts of core system. The resulting document should also state advantages and disadvantages of package managers and the impact of supporting these package managers.

# Acceptance criteria

- [x] Explore [glide](https://glide.sh/)
- [ ] Explore [go's official package manager](https://github.com/Masterminds/glide#golang-dep)
- [ ] Document observations in a document (with pros&cons)
- [ ] Document changes needed to support these package managers

**Comment by msrb** [comment]
There is more package managers https://github.com/golang/go/wiki/PackageManagementTools. A lot of them simply produce `vendor/vendor.js` file (or similar, easy-to-parse file). Note it looks like vendoring in Go usually happens on application level, not on library level. If my understanding is correct, then this work is needed for stack analysis (mecator needs to be able to extract dependencies from vendor files), not component analysis.

**Comment by jpopelka** [comment]
Regarding Glide support see #1406 and #1618

**Comment by miteshvp** [comment]
implemented. Closing.
