### ISSUE TITLE
[3] Develop integration tests to check the results of component analysis

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#954]
The new tests should follow these steps:

- [x] force the analysis of component (with known expected results for given ecosystem+component+version)
- [x] wait for the analysis, report error if the analysis timeout
- [x] check if all package metadata are present in the AWS S3
- [x] check if all component metadata are present in the AWS S3
- [x] check the content of package metadata (given the package is known)
- [x] check the content of component metadata (given the component is known)
- [x] report all differences

**Comment by miteshvp** [comment]
@tisnik marking this as closed. Please re-open if needed.
