### ISSUE TITLE
Quick Preview: Comments are disappearing once collapse

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#962]
There is a bug in the layout, when the user is collapsing the comments of the WI. It is not possible to show them again.

![](https://user-images.githubusercontent.com/1636769/30269008-d23d9df4-96e7-11e7-98c8-116a9576f905.gif)

**Comment by SMahil** [comment]
@vikram-raj @michaelkleinhenz This issue has been fixed in 

https://github.com/fabric8-ui/fabric8-planner/pull/2152

**Comment by vikram-raj** [comment]
Thanks @SMahil
