### ISSUE TITLE
Detail View: Layout needs to be improved

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#963]
There is a lot to improve on the general layout there: the description field needs to be larger, the comments area needs to be larger etc.

![](https://user-images.githubusercontent.com/1636769/30220809-3b307170-94c1-11e7-8a7b-f311d6801d06.png)

**Comment by SMahil** [comment]
PR: https://github.com/fabric8-ui/fabric8-planner/pull/2177
