### ISSUE TITLE
Work Items in unassigned state not returned in filter query

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#967]
The following query returns no data on UI, even when there are several Bugs in Unassigned state: https://openshift.io/openshiftio/openshiftio/plan?workitemtype=Bug&assignee=Unassigned

The back end return [] for the query: filter[expression]={"$AND":[{"assignee":{"$EQ":"none"}},{"space":{"$EQ":"020f756e-b51a-4b43-b113-45cec16b9ce9"}}]}

Update: Backend was fixed, however the change in UI from none to null is pending.

**Comment by rgarg1** [comment]
Backend fix: https://github.com/fabric8-services/fabric8-wit/pull/1596

**Comment by nimishamukherjee** [comment]
OSIO - https://openshift.io/openshiftio/openshiftio/plan/detail/1530 and https://openshift.io/openshiftio/openshiftio/plan/detail/1480

**Comment by michaelkleinhenz** [comment]
Fixed.
