### ISSUE TITLE
Work Item Title Text is showing special characters in encoded form

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#968]
WI title, if contains a special character like " ' ", the display string post save shows up in escaped from, making it very user unfriendly.

https://drive.google.com/open?id=0BwLIZeed5jyKVU91c1NWcWdXc1U

Escaping the strings is necessary, but the system should not reflect back the string in escaped from to the user.

**Comment by michaelkleinhenz** [comment]
Fixed with PR#2169.
