### ISSUE TITLE
External URLs open in same browser tab

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#970]
All external URLs in the WI description field open is the same tab, disrupting the user context. They should open in a new tab. Internal OSIO URLs can open in the same tab.

Test it here: https://www.redhat.com/en

**Comment by michaelkleinhenz** [comment]
This is intended behaviour.

**Comment by catrobson** [comment]
+1 that URLs external to OSIO should open in a new tab.  @michaelkleinhenz - Where was this noted as intended behavior?

**Comment by michaelkleinhenz** [comment]
We had a discussion in the team before and the argument was that as a developer, I want to have complete control over where a link is opening - this is a crucial thing of my workflow. When it is a "normal" link, I have this control. If the system designates it to open in a new window, then this control is taken away from me.

*But* we discussed it again in today's daily and Pranav has given another good reason for opening in a new tab: we are not able to preserve all state when returning from an external link. For example, the open state of the quick preview is not preserved. So at this time, we can not completely preserve the working state of the user - so the team decided that we will go with external links in new tabs for now and shift the discussion to later.

**Comment by joshuawilson** [comment]
Additionally, this is in reference to external links. I think the common paradigm is that external links open in a new tab and internal links don't. That helps to keep the flow intact not just the state.

**Comment by michaelkleinhenz** [comment]
Fixed for GitHub links in PR ngx-widgets#110. Needs another change in the backend's markdown rendering.

**Comment by michaelkleinhenz** [comment]
Fixed for all other links by https://github.com/fabric8-services/fabric8-wit/pull/1664.
