### ISSUE TITLE
Sidebar: Iteration Kebab Menu remains open

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#971]
The kebab menu for iterations remain open even after the focus is moved to other part of the page. Its possible to make multiple kebab menus to remain open at a time.

**Comment by rgarg1** [comment]
![iter kebab remains open](https://user-images.githubusercontent.com/28748448/30644449-0b4a3a18-9e30-11e7-8471-fc3294f07445.png)

**Comment by joshuawilson** [comment]
cc @michaelkleinhenz

**Comment by nimishamukherjee** [comment]
This would get fixed with the new tree list component from Patternfly-ng

**Comment by joshuawilson** [comment]
@michaelkleinhenz why remove the label `area/planner`? Is this not work to be done in the Planner? Or do you see the work being done someplace else?

**Comment by michaelkleinhenz** [comment]
Fixed.

**Comment by rgarg1** [comment]
Fixed!
