### ISSUE TITLE
Spike around Maven ecosystem

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#972]
# Description

We used to use `Anitya` for getting latest versions and release feed for `Maven`. However, release feed has never really worked since we are using `maven-index-checker`. It's too heavy for Anitya pipeline since Anytia is designed for curling lightweight ecosystem endpoints.

**GOAL**: of this spike is to determine whether a) we should fix integration with `Anytia` b) Implement standalone service for `Maven` ecosystem (`firehose-fetcher` is taking care of the most of other ecosystems) c) reimplement `Anytia`'s functionality, where we include all our requirements.

# Acceptance criteria

- [ ] document describing cons, pros, possible risk and estimated times to implement of outlined actions,  Note that you can include even more options if it came to your mind during working on this.

**Comment by fridex** [comment]
@pkajaba please fill the task

**Comment by msrb** [comment]
The problem really is:

Anitya has always been kinda detached from the rest of the system and it led to weird issues with latest versions. Plus, as you've mentioned, Maven support in Anitya was broken from the day one.

`firehose-fetcher` is not really a replacement for Anitya. It helps us to keep up with new releases and it solves the problem with latest versions (in a fragile way, IMO). It was easy to implement and it does the job for now, but that's it. The real problem with firehose is that Java/Maven support is not working. So the low hanging fruit here could be to [implement something similar ourselves just for Maven](https://github.com/openshiftio/openshift.io/issues/690).

Mid/long-term we want more robust solution for monitoring upstream for existing and new releases. But I don't think we can afford to wait for it with Maven not really working right now.

**Comment by msrb** [comment]
This is no longer relevant as we have implemented https://github.com/openshiftio/openshift.io/issues/690 for Maven. "Anitya 2.0" should be a different issue.
