### ISSUE TITLE
[3] Finding out reasons on why no tags found for a package

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#975]
# Description

Now we tag projects in production. We have a complete list of projects that should be tagged, but some of them could be missing. This work item is about checking which packages were not tagged during the initial tagger run and also find out reasoning why these packages couldn't be tagged (lack of data for tagger?, non-existing packages?). Ideally we would like to also suggest improvements on the tagging work so we would tag as many packages as possible in our tagging pipeline.

# Acceptance criteria

- [x] check which packages were not tagged (ideally in an automated way so we can re-iterate inspection)
- [x] check why packages were not tagged (also in an automated way)
- [x] suggest improvements in tagging pipeline

**Comment by fridex** [comment]
Implementation of automated script is present in [this repo](https://github.com/fabric8-analytics/devnull/tree/master/why_missing_maven) with found issues in JSON. Tagging re-scheduled in production for the missing packages.

**Comment by miteshvp** [comment]
@fridex marking it as closed. Please re-open if needed.
