### ISSUE TITLE
Automated API tests for Forge Wizard for Quickstart

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#977]
# Description
As a developer, I want to test the Forge API for the [Fabric8 addon](https://github.com/fabric8io/fabric8-generator/).

# Acceptance Criteria
- [x] Test quickstart repository flow step1 ChooseMissionStep / ChooseRuntimeStep with success and error
- [x] Test quickstart repository flow step2 Fabric8ProjectInfoStep with success and error
- [x] Test quickstart repository flow step3 ChoosePipelineStep success and error
- [x] Test quickstart repository flow step4 GitHubImportRepoStepwith success and error
- [x] Test quickstart repository flow step5 BuildConfigStep ChoosePipelineStep with success and error
_NOTE_: Some wizard steps used for fabric8 addon are inherited or just reuse the one defined in [launchpad-io](https://github.com/openshiftio/launchpad-addon)

**Comment by joshuawilson** [comment]
Is this complete?

**Comment by corinnekrych** [comment]
Pending review as you can see in the PR linked.
@rgarg1 do you need help with the review?

**Comment by rgarg1** [comment]
@corinnekrych Reviewed. Seeing few failures. Check https://github.com/fabric8io/fabric8-test/pull/221
