### ISSUE TITLE
Notifications in OSIO

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#978]
# Description
As a user of OpenShift.io, I would like to be able to see notifications within the application so I can easily react to them while using the product rather than having to move back to e-mail to see changes happening across the system.

# Acceptance Criteria
- [ ] Notification Drawer is added to OpenShift.io and shows the latest notifications for the overall system as well as specific spaces the user is collaborating on
- [ ] Notification full page is added to OpenShift.io and allows the user to view and manage their notifications at large across the system
- [ ] Notification settings are added to the user settings area that allow users to control notifications at the system and space level

## Implementing Features and Sub-Experiences
- [ ] #1990 
- [ ] #1577 
- [ ] #1190 
- [ ] #333 
- [ ] #285

## Associated Defects
- [ ] #1554
- [ ] #1375 

## Parent Scenario
#2026 Finding meaningful and actionable information within a large development project

**Comment by catrobson** [comment]
Designs for Notifications Drawer and Full Page: https://redhat.invisionapp.com/d/main#/projects/prototypes/11914584

Note:  Settings need to be resolved across multiple designs happening in UXD.

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/1996
