### ISSUE TITLE
"View last build" pipeline kebab option brings user to page with broken image

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#979]
Steps to recreate:
* Select "view last build" from pipeline page:
![screenshot 59](https://user-images.githubusercontent.com/642621/30660599-6da14614-9e0f-11e7-9ce8-63225112189d.png)

* Observe the broken image on the build page:
![screenshot 60](https://user-images.githubusercontent.com/642621/30660616-7d47969a-9e0f-11e7-8387-b5f0e7837da2.png)

**Comment by qodfathr** [comment]
Fixed via removal.
