### ISSUE TITLE
"View test report" pipeline kebab option results in a 404 error

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#981]
If a user selects 'View Last Report' from a pipeline kebab:

![screenshot 63](https://user-images.githubusercontent.com/642621/30663576-17ab54a2-9e19-11e7-932a-b9424cbb8b04.png)

The browser attempts to open this page:   https://openshift.io/nulltestReport

This fails and redirects the user to the 404 error page:

![screenshot 64](https://user-images.githubusercontent.com/642621/30663657-5df127c0-9e19-11e7-9da2-2a59560c12f5.png)

**Comment by samuzzal-choudhury** [comment]
"View test report" in the kebab menu of is not meant for opening "Stack Report". This is beyond the scope of the recommender UI. Removing the stream/integration and team/analytics labels. @joshuawilson could you please set an appropriate backlog milestone to this?  tag. CC: @krishnapaparaju @miteshvp @ldimaggi

**Comment by joshuawilson** [comment]
@catrobson can you please confirm the design of this menu option? Is it in any design or was it just added by a someone?

**Comment by catrobson** [comment]
@joshuawilson this was not planned into any design, just got added.

**Comment by qodfathr** [comment]
I recommend that we remove this menu option for now.

**Comment by qodfathr** [comment]
Fixed via removal.
