### ISSUE TITLE
Machine Generated Stacks

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#986]
### Description:
We want to help developers to generate a stack based on their inputs. There will be different types of Inputs 
1. Categories such as Web, UI, Cloud, Security, etc.
2. Ecosystem such as Java (Vertx, Springboot), Python, Node, etc.
3. Manual selection of components based on descriptive data such as Github Statistics, Licenses, Usage Data, etc.

#### Acceptance Criteria:
For selective categories and ecosystems, end-users should be provided with options to 
- [ ] Generate a stack automatically
- [ ] Manually select and choose components to form their stack based on descriptive data

**Comment by pkajaba** [comment]
From what I understand spike is supposed to do some research about the problem and not deliver a complete solution. This seems to be more like epic...

**Comment by humaton** [comment]
@miteshvp is this spike or user story? Inthe name I read spike and in tasks, I read implementation. So which one is this?

**Comment by vpavlin** [comment]
@miteshvp Can you elaborate on the goal of this spike? I do not understand what do you expect as the outcome and what are the motivations behind this.

Also I'd suggest to replace start.spring.io with launch.openshift.io as that would make it easy for you to contact it's devs and collaborate (@gastaldi)

**Comment by miteshvp** [comment]
@pkajaba @humaton @vpavlin - thanks for pointing out, its a user-story. Again, Vasek, thanks for suggestion. Replaced the reference.

**Comment by adisakala** [comment]
Yes this will be integrated with Andy's team.

**Comment by vpavlin** [comment]
@miteshvp And could you please elaborate a bit more on the goals, please? I'd suggest you extend the description so that it's understandable even for people who were not on the planning. Right now it sounds to me without any context like you want to reimplement start.spring.io or launch.openshift.io:)

**Comment by miteshvp** [comment]
@vpavlin - I guess that's pretty much it.

**Comment by humaton** [comment]
@miteshvp and why would we need/want to reimplement such thing? Should not be better to come up with stack definition and reuse existing boilerplate generators?

**Comment by miteshvp** [comment]
@humaton - Idea is we are trying to build machine generated stacks based on keywords/categories. But this will be part of a bigger user-story/epic that someone else is putting across. Till that time, I will move this back to Analytics Backlog to clear the confusions.

**Comment by ALRubinger** [comment]
@all We in RHOAR are looking at working with this with you, coordinated through @maxandersen.  It amounts to a feature enhancement on the Getting Started experience we're building together that's now more restricted in Launch.  Let's raise at the next integration team meeting to move forward; Max will coordinate for the DevTools side.

**Comment by ALRubinger** [comment]
FYI @quintesse @gastaldi @edewit

**Comment by GeorgeActon** [comment]
Agreed. This is a discussion and awareness only at the moment. We need the broader business vision and PM engagement before we can go further than that.

**Comment by maxandersen** [comment]
as others asked i'm curious to what the output of this would actually be ? a list of dependencies ? and what would its use be ?

**Comment by sunilk747** [comment]
@miteshvp Can we close it? AFAIK we are not proceeding with machine generating stack.

**Comment by miteshvp** [comment]
Closing this issue as its being followed as one of the task items in
https://github.com/openshiftio/openshift.io/issues/1971 and https://github.com/openshiftio/openshift.io/issues/1935
