### ISSUE TITLE
Sidebar: Expand Caret too high in position

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#991]
The expand caret is too high in the line position:
![bildschirmfoto von 2017-09-21 10-58-14](https://user-images.githubusercontent.com/7101098/30687570-f39f81a2-9ebb-11e7-806c-9079dd143564.png)

**Comment by SMahil** [comment]
@Michael This has been fixed in below PR
https://github.com/fabric8-ui/fabric8-planner/pull/2152
