### ISSUE TITLE
Sidebar: "Delete Iteration" should be possible

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#993]
Currently, we can not delete an iteration.

**Comment by pranavgore09** [comment]
@michaelkleinhenz  Please verify
- After deletion what should happen to WI having that iteration?
        1. Obvious (just remove the relation between deleted iteration and WI) 
        2. Move WI to its parent iteration if any

- And what should happen to child iterations?
       1. Move all child iterations up in the hierarchy

Any other **side-effects** than mentioned above?

**Comment by michaelkleinhenz** [comment]
- WIs: 
1. yes, remove the iteration value on the Wis.
2. no, we just remove the iteration, not set another (for now).

- child iterations
1. I think the most logical way would be to remove the child iterations as well. If that is possible without much extra work, we should do that.

**Comment by pranavgore09** [comment]
> WIs:
yes, remove the iteration value on the Wis.
no, we just remove the iteration, not set another (for now).

Okay, I will start over it

> child iterations
I think the most logical way would be to remove the child iterations as well. If that is possible without much extra work, we should do that.

I will check once and come back

**Comment by nimishamukherjee** [comment]
OSIO - https://openshift.io/openshiftio/openshiftio/plan/detail/1531
