### ISSUE TITLE
No scroller in Pipelines view

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#994]
1. create two projects in one space
2. navigate to Pipelines view (something like https://openshift.io/username/spacename/create/pipelines)

result: 
There is no scroller so it's impossible to see the second pipeline on smaller screen/in small browser window. 

![osio_pipelines_scroller](https://user-images.githubusercontent.com/445100/30688276-003dc11a-9ebe-11e7-9855-e919b69cd101.png)

**Comment by qodfathr** [comment]
Fixed.
